In [1]:
%matplotlib inline

# scientific computing and plotting
import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt
import seaborn as sns

# HDDM related packages
import pymc as pm
import hddm
import kabuki
import arviz as az
print("The current HDDM version is: ", hddm.__version__)
print("The current kabuki version is: ", kabuki.__version__)
print("The current PyMC version is: ", pm.__version__)
print("The current ArviZ version is: ", az.__version__)

import warnings
warnings.filterwarnings('ignore')

The current HDDM version is:  1.0.1RC
The current kabuki version is:  0.6.5RC4
The current PyMC version is:  2.3.8
The current ArviZ version is:  0.15.1

In [2]:
# read data
data = pd.read_csv('MS_categ_id_hddm_stim.csv')
data

       subj_idx   val     id  stim  response      rt
0          7304  Good   Self     1         1  0.4236
1          7304   Bad  Other     0         0  0.5631
2          7304   Bad   Self     1         1  0.7198
3          7304  Good  Other     0         0  0.6799
4          7304  Good   Self     1         1  0.3560
...         ...   ...    ...   ...       ...     ...
14488      7345  Good  Other     0         0  0.3472
14489      7345   Bad   Self     1         1  0.4249
14490      7345   Bad   Self     1         1  0.3351
14491      7345   Bad  Other     0         0  0.4232
14492      7345  Good  Other     0         0  0.4049

[14493 rows x 6 columns]

In [3]:
# accuracy coding
data['choice'] = data['response'].copy()                       # 保存 choice 编码（1=Self, 0=Other）
data['acc'] = (data['response'] == data['stim']).astype(int)   # 计算正确率

data['response'] = data['acc']

In [10]:
#hddm 
#hddm_acc
# HDDM accuracy coding 
# v varies across different stim and id

data['response'] =data['acc']
hddm_id_m0_acc_diff = hddm.HDDM(data, include=['a', 'v', 't','z'], depends_on={'v': ['id','stim']})

hddm_id_m0_acc_diff_idata = hddm_id_m0_acc_diff.sample(2000, burn=500, chains=4, return_infdata=True, dbname = 'hddm_id_m0_acc_diff.db', db = 'pickle')
hddm_id_m0_acc_diff.save('hddm_id_m0_acc_diff.hddm')
# hddm.load('hddm_id_m0_acc.hddm')

No model attribute --> setting up standard HDDM
Set model to ddm

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

[-----------------90%--------------    ] 1802 of 2000 complete in 235.7 sec
[-----------------90%--------------    ] 1806 of 2000 complete in 236.2 sec
[-----------------90%--------------    ] 1810 of 2000 complete in 236.7 sec
[-----------------90%--------------    ] 1814 of 2000 complete in 237.2 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 237.7 sec
[-----------------91%--------------    ] 1822 of 2000 complete in 238.2 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 238.8 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 239.3 sec
[-----------------91%--------------    ] 1834 of 2000 complete in 239.8 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 240.3 sec
[-----------------92%--------------    ] 1842 of 2000 complete in 240.8 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 241.3 sec
[-----------------92%---------------   ] 1850 of 2000 complete in 241.8 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 242.4 sec
[-----------------92%---------------   ] 1858 of 2000 complete in 242.9 sec
[-----------------93%---------------   ] 1862 of 2000 complete in 243.5 sec
[-----------------93%---------------   ] 1866 of 2000 complete in 244.0 sec
[-----------------93%---------------   ] 1870 of 2000 complete in 244.5 sec
[-----------------93%---------------   ] 1874 of 2000 complete in 245.0 sec
[-----------------93%---------------   ] 1878 of 2000 complete in 245.6 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 246.1 sec
[-----------------94%---------------   ] 1886 of 2000 complete in 246.7 sec
[-----------------94%---------------   ] 1890 of 2000 complete in 247.2 sec
[-----------------94%---------------   ] 1894 of 2000 complete in 247.7 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 248.2 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 248.7 sec
[-----------------95%----------------  ] 1906 of 2000 complete in 249.3 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 249.8 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 250.3 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 250.8 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 251.3 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 251.9 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 252.4 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 252.9 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 253.4 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 254.0 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 254.6 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 255.1 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 255.6 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 256.1 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 256.6 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 257.2 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 257.8 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 258.4 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 259.1 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 259.7 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 260.2 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 260.8 sec
[-----------------100%-----------------] 2000 of 2000 complete in 261.2 sec
hddm sampling elpased time:  261.348 s
[                  0%                  ] 8 of 2000 complete in 0.6 sec
[                  0%                  ] 14 of 2000 complete in 1.1 sec
[                  1%                  ] 20 of 2000 complete in 1.6 sec
[                  1%                  ] 26 of 2000 complete in 2.1 sec
[                  1%                  ] 33 of 2000 complete in 2.6 sec
[                  2%                  ] 40 of 2000 complete in 3.2 sec
[                  2%                  ] 47 of 2000 complete in 3.7 sec
[-                 2%                  ] 53 of 2000 complete in 4.3 sec
[-                 3%                  ] 60 of 2000 complete in 4.9 sec
[-                 3%                  ] 66 of 2000 complete in 5.4 sec
[-                 3%                  ] 73 of 2000 complete in 5.9 sec
[-                 4%                  ] 80 of 2000 complete in 6.5 sec
[-                 4%                  ] 87 of 2000 complete in 7.1 sec
[-                 4%                  ] 94 of 2000 complete in 7.6 sec
[-                 5%                  ] 101 of 2000 complete in 8.2 sec
[--                5%                  ] 108 of 2000 complete in 8.7 sec
[--                5%                  ] 115 of 2000 complete in 9.2 sec
[--                6%                  ] 122 of 2000 complete in 9.8 sec
[--                6%                  ] 128 of 2000 complete in 10.3 sec
[--                6%                  ] 135 of 2000 complete in 10.8 sec
[--                7%                  ] 142 of 2000 complete in 11.4 sec
[--                7%                  ] 149 of 2000 complete in 11.9 sec
[--                7%                  ] 156 of 2000 complete in 12.5 sec
[---               8%                  ] 163 of 2000 complete in 13.0 sec
[---               8%                  ] 170 of 2000 complete in 13.6 sec
[---               8%                  ] 177 of 2000 complete in 14.1 sec
[---               9%                  ] 184 of 2000 complete in 14.7 sec
[---               9%                  ] 191 of 2000 complete in 15.2 sec
[---               9%                  ] 197 of 2000 complete in 15.8 sec
[---              10%                  ] 204 of 2000 complete in 16.3 sec
[---              10%                  ] 210 of 2000 complete in 16.8 sec
[----             10%                  ] 217 of 2000 complete in 17.4 sec
[----             11%                  ] 224 of 2000 complete in 18.0 sec
[----             11%                  ] 231 of 2000 complete in 18.5 sec
[----             11%                  ] 238 of 2000 complete in 19.1 sec
[----             12%                  ] 245 of 2000 complete in 19.7 sec
[----             12%                  ] 252 of 2000 complete in 20.2 sec
[----             12%                  ] 259 of 2000 complete in 20.8 sec
[-----            13%                  ] 266 of 2000 complete in 21.3 sec
[-----            13%                  ] 272 of 2000 complete in 21.8 sec
[-----            13%                  ] 279 of 2000 complete in 22.4 sec
[-----            14%                  ] 286 of 2000 complete in 23.0 sec
[-----            14%                  ] 293 of 2000 complete in 23.5 sec
[-----            14%                  ] 299 of 2000 complete in 24.0 sec
[-----            15%                  ] 305 of 2000 complete in 24.5 sec
[-----            15%                  ] 312 of 2000 complete in 25.1 sec
[------           15%                  ] 319 of 2000 complete in 25.7 sec
[------           16%                  ] 326 of 2000 complete in 26.3 sec
[------           16%                  ] 332 of 2000 complete in 26.8 sec
[------           16%                  ] 338 of 2000 complete in 27.3 sec
[------           17%                  ] 345 of 2000 complete in 27.9 sec
[------           17%                  ] 352 of 2000 complete in 28.4 sec
[------           17%                  ] 359 of 2000 complete in 29.0 sec
[------           18%                  ] 366 of 2000 complete in 29.6 sec
[-------          18%                  ] 372 of 2000 complete in 30.1 sec
[-------          18%                  ] 379 of 2000 complete in 30.6 sec
[-------          19%                  ] 386 of 2000 complete in 31.2 sec
[-------          19%                  ] 393 of 2000 complete in 31.7 sec
[-------          20%                  ] 400 of 2000 complete in 32.3 sec
[-------          20%                  ] 407 of 2000 complete in 32.8 sec
[-----------------94%---------------   ] 1890 of 2000 complete in 242.9 sec
[-----------------94%---------------   ] 1894 of 2000 complete in 243.4 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 243.9 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 244.5 sec
[-----------------95%----------------  ] 1906 of 2000 complete in 245.0 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 245.5 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 246.0 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 246.5 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 247.0 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 247.6 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 248.1 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 248.6 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 249.1 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 249.6 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 250.3 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 250.8 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 251.3 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 251.8 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 252.4 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 252.9 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 253.5 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 254.2 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 254.7 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 255.2 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 255.8 sec
[-----------------99%----------------- ] 1996 of 2000 complete in 256.4 sec
[-----------------100%-----------------] 2001 of 2000 complete in 257.1 sec
hddm sampling elpased time:  257.213 s
[                  0%                  ] 8 of 2000 complete in 0.6 sec
[                  0%                  ] 14 of 2000 complete in 1.1 sec
[                  1%                  ] 21 of 2000 complete in 1.6 sec
[                  1%                  ] 28 of 2000 complete in 2.2 sec
[                  1%                  ] 35 of 2000 complete in 2.8 sec
[                  2%                  ] 42 of 2000 complete in 3.3 sec
[                  2%                  ] 49 of 2000 complete in 3.9 sec
[-                 2%                  ] 55 of 2000 complete in 4.4 sec
[-                 3%                  ] 62 of 2000 complete in 5.0 sec
[-                 3%                  ] 69 of 2000 complete in 5.5 sec
[-                 3%                  ] 76 of 2000 complete in 6.1 sec
[-                 4%                  ] 83 of 2000 complete in 6.6 sec
[-                 4%                  ] 90 of 2000 complete in 7.2 sec
[-                 4%                  ] 97 of 2000 complete in 7.7 sec
[-                 5%                  ] 104 of 2000 complete in 8.2 sec
[--                5%                  ] 111 of 2000 complete in 8.8 sec
[--                5%                  ] 118 of 2000 complete in 9.3 sec
[--                6%                  ] 125 of 2000 complete in 9.8 sec
[--                6%                  ] 132 of 2000 complete in 10.4 sec
[--                6%                  ] 139 of 2000 complete in 10.9 sec
[--                7%                  ] 146 of 2000 complete in 11.5 sec
[--                7%                  ] 153 of 2000 complete in 12.0 sec
[---               8%                  ] 160 of 2000 complete in 12.6 sec
[---               8%                  ] 167 of 2000 complete in 13.1 sec
[---               8%                  ] 174 of 2000 complete in 13.6 sec
[---               9%                  ] 181 of 2000 complete in 14.2 sec
[---               9%                  ] 188 of 2000 complete in 14.7 sec
[---               9%                  ] 195 of 2000 complete in 15.3 sec
[---              10%                  ] 201 of 2000 complete in 15.8 sec
[---              10%                  ] 208 of 2000 complete in 16.4 sec
[----             10%                  ] 215 of 2000 complete in 16.9 sec
[----             11%                  ] 222 of 2000 complete in 17.5 sec
[----             11%                  ] 229 of 2000 complete in 18.0 sec
[----             11%                  ] 236 of 2000 complete in 18.6 sec
[----             12%                  ] 243 of 2000 complete in 19.1 sec
[----             12%                  ] 250 of 2000 complete in 19.7 sec
[----             12%                  ] 257 of 2000 complete in 20.2 sec
[-----            13%                  ] 264 of 2000 complete in 20.8 sec
[-----            13%                  ] 271 of 2000 complete in 21.3 sec
[-----            13%                  ] 278 of 2000 complete in 21.9 sec
[-----            14%                  ] 285 of 2000 complete in 22.5 sec
[-----            14%                  ] 292 of 2000 complete in 23.0 sec
[-----            14%                  ] 299 of 2000 complete in 23.5 sec
[-----            15%                  ] 306 of 2000 complete in 24.1 sec
[-----            15%                  ] 312 of 2000 complete in 24.6 sec
[------           15%                  ] 319 of 2000 complete in 25.1 sec
[------           16%                  ] 326 of 2000 complete in 25.7 sec
[------           16%                  ] 333 of 2000 complete in 26.3 sec
[------           16%                  ] 339 of 2000 complete in 26.8 sec
[------           17%                  ] 345 of 2000 complete in 27.3 sec
[------           17%                  ] 352 of 2000 complete in 27.9 sec
[------           17%                  ] 359 of 2000 complete in 28.4 sec
[------           18%                  ] 366 of 2000 complete in 29.0 sec
[-------          18%                  ] 373 of 2000 complete in 29.5 sec
[-------          19%                  ] 380 of 2000 complete in 30.1 sec
[-------          19%                  ] 387 of 2000 complete in 30.6 sec
[-------          19%                  ] 394 of 2000 complete in 31.2 sec
[-------          20%                  ] 401 of 2000 complete in 31.7 sec
[-------          20%                  ] 408 of 2000 complete in 32.2 sec
[-------          20%                  ] 415 of 2000 complete in 32.8 sec
[--------         21%                  ] 422 of 2000 complete in 33.3 sec
[--------         21%                  ] 429 of 2000 complete in 33.8 sec
[--------         21%                  ] 436 of 2000 complete in 34.4 sec
[--------         22%                  ] 443 of 2000 complete in 34.9 sec
[--------         22%                  ] 450 of 2000 complete in 35.4 sec
[--------         22%                  ] 457 of 2000 complete in 36.0 sec
[--------         23%                  ] 464 of 2000 complete in 36.5 sec
[--------         23%                  ] 471 of 2000 complete in 37.1 sec
[---------        23%                  ] 478 of 2000 complete in 37.6 sec
[---------        24%                  ] 485 of 2000 complete in 38.1 sec
[---------        24%                  ] 492 of 2000 complete in 38.7 sec
[---------        24%                  ] 499 of 2000 complete in 39.2 sec
[---------        25%                  ] 506 of 2000 complete in 39.7 sec
[---------        25%                  ] 513 of 2000 complete in 40.3 sec
[---------        26%                  ] 520 of 2000 complete in 40.8 sec
[----------       26%                  ] 527 of 2000 complete in 41.4 sec
[----------       26%                  ] 534 of 2000 complete in 41.9 sec
[----------       27%                  ] 541 of 2000 complete in 42.5 sec
[----------       27%                  ] 548 of 2000 complete in 43.0 sec
[----------       27%                  ] 555 of 2000 complete in 43.5 sec
[----------       28%                  ] 562 of 2000 complete in 44.1 sec
[----------       28%                  ] 569 of 2000 complete in 44.6 sec

[-----------------95%----------------  ] 1915 of 2000 complete in 244.3 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 244.9 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 245.4 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 245.9 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 246.4 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 246.9 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 247.4 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 248.0 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 248.5 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 249.0 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 249.5 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 250.1 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 250.6 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 251.1 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 251.6 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 252.3 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 252.8 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 253.4 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 254.0 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 254.5 sec
[-----------------100%-----------------] 2000 of 2000 complete in 255.1 sec
[-----------------100%-----------------] 2000 of 2000 complete in 255.3 sec
hddm sampling elpased time:  255.419 s
[                  0%                  ] 8 of 2000 complete in 0.6 sec
[                  0%                  ] 15 of 2000 complete in 1.1 sec
[                  1%                  ] 22 of 2000 complete in 1.7 sec
[                  1%                  ] 29 of 2000 complete in 2.2 sec
[                  1%                  ] 36 of 2000 complete in 2.8 sec
[                  2%                  ] 43 of 2000 complete in 3.3 sec
[                  2%                  ] 50 of 2000 complete in 3.9 sec
[-                 2%                  ] 56 of 2000 complete in 4.4 sec
[-                 3%                  ] 63 of 2000 complete in 5.0 sec
[-                 3%                  ] 70 of 2000 complete in 5.5 sec
[-                 3%                  ] 77 of 2000 complete in 6.1 sec
[-                 4%                  ] 84 of 2000 complete in 6.6 sec
[-                 4%                  ] 91 of 2000 complete in 7.2 sec
[-                 4%                  ] 98 of 2000 complete in 7.7 sec
[-                 5%                  ] 105 of 2000 complete in 8.2 sec
[--                5%                  ] 112 of 2000 complete in 8.7 sec
[--                5%                  ] 119 of 2000 complete in 9.3 sec
[--                6%                  ] 126 of 2000 complete in 9.8 sec
[--                6%                  ] 133 of 2000 complete in 10.4 sec
[--                7%                  ] 140 of 2000 complete in 10.9 sec
[--                7%                  ] 147 of 2000 complete in 11.4 sec
[--                7%                  ] 154 of 2000 complete in 12.0 sec
[---               8%                  ] 161 of 2000 complete in 12.5 sec
[---               8%                  ] 168 of 2000 complete in 13.1 sec
[---               8%                  ] 175 of 2000 complete in 13.6 sec
[---               9%                  ] 182 of 2000 complete in 14.2 sec
[---               9%                  ] 189 of 2000 complete in 14.7 sec
[---               9%                  ] 196 of 2000 complete in 15.3 sec
[---              10%                  ] 202 of 2000 complete in 15.8 sec
[---              10%                  ] 209 of 2000 complete in 16.3 sec
[----             10%                  ] 216 of 2000 complete in 16.9 sec
[----             11%                  ] 223 of 2000 complete in 17.5 sec
[----             11%                  ] 230 of 2000 complete in 18.0 sec
[----             11%                  ] 237 of 2000 complete in 18.6 sec
[----             12%                  ] 244 of 2000 complete in 19.1 sec
[----             12%                  ] 251 of 2000 complete in 19.7 sec
[----             12%                  ] 258 of 2000 complete in 20.2 sec
[-----            13%                  ] 265 of 2000 complete in 20.7 sec
[-----            13%                  ] 272 of 2000 complete in 21.3 sec
[-----            13%                  ] 279 of 2000 complete in 21.8 sec
[-----            14%                  ] 286 of 2000 complete in 22.4 sec
[-----            14%                  ] 293 of 2000 complete in 22.9 sec
[-----            15%                  ] 300 of 2000 complete in 23.5 sec
[-----            15%                  ] 307 of 2000 complete in 24.0 sec
[-----            15%                  ] 314 of 2000 complete in 24.6 sec
[------           16%                  ] 321 of 2000 complete in 25.1 sec
[------           16%                  ] 328 of 2000 complete in 25.7 sec
[------           16%                  ] 335 of 2000 complete in 26.2 sec
[------           17%                  ] 342 of 2000 complete in 26.8 sec
[------           17%                  ] 348 of 2000 complete in 27.3 sec
[------           17%                  ] 355 of 2000 complete in 27.9 sec
[------           18%                  ] 362 of 2000 complete in 28.4 sec
[-------          18%                  ] 369 of 2000 complete in 29.0 sec
[-------          18%                  ] 376 of 2000 complete in 29.5 sec
[-------          19%                  ] 383 of 2000 complete in 30.1 sec
[-------          19%                  ] 390 of 2000 complete in 30.6 sec
[-------          19%                  ] 397 of 2000 complete in 31.2 sec
[-------          20%                  ] 404 of 2000 complete in 31.7 sec
[-------          20%                  ] 411 of 2000 complete in 32.3 sec
[-------          20%                  ] 418 of 2000 complete in 32.8 sec
[--------         21%                  ] 425 of 2000 complete in 33.3 sec
[--------         21%                  ] 432 of 2000 complete in 33.9 sec
[--------         21%                  ] 439 of 2000 complete in 34.4 sec
[--------         22%                  ] 446 of 2000 complete in 34.9 sec
[--------         22%                  ] 453 of 2000 complete in 35.4 sec
[--------         23%                  ] 460 of 2000 complete in 36.0 sec
[--------         23%                  ] 467 of 2000 complete in 36.5 sec
[---------        23%                  ] 474 of 2000 complete in 37.0 sec
[---------        24%                  ] 481 of 2000 complete in 37.6 sec
[---------        24%                  ] 488 of 2000 complete in 38.1 sec
[---------        24%                  ] 495 of 2000 complete in 38.6 sec
[---------        25%                  ] 502 of 2000 complete in 39.2 sec
[---------        25%                  ] 509 of 2000 complete in 39.7 sec
[---------        25%                  ] 516 of 2000 complete in 40.3 sec
[---------        26%                  ] 523 of 2000 complete in 40.8 sec
[----------       26%                  ] 530 of 2000 complete in 41.3 sec
[----------       26%                  ] 537 of 2000 complete in 41.9 sec
[----------       27%                  ] 544 of 2000 complete in 42.4 sec
[----------       27%                  ] 551 of 2000 complete in 43.0 sec
[----------       27%                  ] 558 of 2000 complete in 43.5 sec
[----------       28%                  ] 565 of 2000 complete in 44.0 sec
[----------       28%                  ] 572 of 2000 complete in 44.6 sec
[-----------      28%                  ] 579 of 2000 complete in 45.1 sec
[-----------      29%                  ] 586 of 2000 complete in 45.6 sec
[-----------      29%                  ] 593 of 2000 complete in 46.2 sec
[-----------      30%                  ] 600 of 2000 complete in 46.7 sec
[-----------      30%                  ] 607 of 2000 complete in 47.3 sec
[-----------      30%                  ] 614 of 2000 complete in 47.8 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 246.5 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 247.2 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 247.7 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 248.2 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 248.7 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 249.2 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 249.7 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 250.3 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 250.8 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 251.4 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 252.0 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 252.6 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 253.1 sec
[-----------------100%-----------------] 2000 of 2000 complete in 253.7 sec
[-----------------100%-----------------] 2000 of 2000 complete in 253.9 sec
hddm sampling elpased time:  254.009 s
[                  0%                  ] 8 of 2000 complete in 0.5 sec
[                  0%                  ] 15 of 2000 complete in 1.1 sec
[                  1%                  ] 22 of 2000 complete in 1.6 sec
[                  1%                  ] 29 of 2000 complete in 2.2 sec
[                  1%                  ] 36 of 2000 complete in 2.8 sec
[                  2%                  ] 43 of 2000 complete in 3.3 sec
[                  2%                  ] 50 of 2000 complete in 3.9 sec
[-                 2%                  ] 57 of 2000 complete in 4.4 sec
[-                 3%                  ] 64 of 2000 complete in 5.0 sec
[-                 3%                  ] 71 of 2000 complete in 5.5 sec
[-                 3%                  ] 78 of 2000 complete in 6.1 sec
[-                 4%                  ] 85 of 2000 complete in 6.6 sec
[-                 4%                  ] 92 of 2000 complete in 7.1 sec
[-                 4%                  ] 99 of 2000 complete in 7.7 sec
[--                5%                  ] 106 of 2000 complete in 8.2 sec
[--                5%                  ] 113 of 2000 complete in 8.7 sec
[--                6%                  ] 120 of 2000 complete in 9.2 sec
[--                6%                  ] 127 of 2000 complete in 9.8 sec
[--                6%                  ] 134 of 2000 complete in 10.3 sec
[--                7%                  ] 141 of 2000 complete in 10.9 sec
[--                7%                  ] 148 of 2000 complete in 11.4 sec
[--                7%                  ] 155 of 2000 complete in 11.9 sec
[---               8%                  ] 162 of 2000 complete in 12.5 sec
[---               8%                  ] 169 of 2000 complete in 13.0 sec
[---               8%                  ] 176 of 2000 complete in 13.5 sec
[---               9%                  ] 183 of 2000 complete in 14.1 sec
[---               9%                  ] 190 of 2000 complete in 14.6 sec
[---               9%                  ] 197 of 2000 complete in 15.1 sec
[---              10%                  ] 203 of 2000 complete in 15.6 sec
[---              10%                  ] 210 of 2000 complete in 16.2 sec
[----             10%                  ] 217 of 2000 complete in 16.7 sec
[----             11%                  ] 224 of 2000 complete in 17.3 sec
[----             11%                  ] 231 of 2000 complete in 17.8 sec
[----             11%                  ] 238 of 2000 complete in 18.4 sec
[----             12%                  ] 245 of 2000 complete in 18.9 sec
[----             12%                  ] 252 of 2000 complete in 19.4 sec
[----             12%                  ] 259 of 2000 complete in 20.0 sec
[-----            13%                  ] 266 of 2000 complete in 20.5 sec
[-----            13%                  ] 273 of 2000 complete in 21.1 sec
[-----            14%                  ] 280 of 2000 complete in 21.6 sec
[-----            14%                  ] 287 of 2000 complete in 22.2 sec
[-----            14%                  ] 294 of 2000 complete in 22.7 sec
[-----            15%                  ] 301 of 2000 complete in 23.2 sec
[-----            15%                  ] 308 of 2000 complete in 23.8 sec
[-----            15%                  ] 314 of 2000 complete in 24.3 sec
[------           16%                  ] 321 of 2000 complete in 24.8 sec
[------           16%                  ] 328 of 2000 complete in 25.4 sec
[------           16%                  ] 335 of 2000 complete in 25.9 sec
[------           17%                  ] 342 of 2000 complete in 26.5 sec
[------           17%                  ] 348 of 2000 complete in 27.0 sec
[------           17%                  ] 355 of 2000 complete in 27.5 sec
[------           18%                  ] 362 of 2000 complete in 28.1 sec
[-------          18%                  ] 369 of 2000 complete in 28.6 sec
[-------          18%                  ] 376 of 2000 complete in 29.2 sec
[-------          19%                  ] 383 of 2000 complete in 29.7 sec
[-------          19%                  ] 390 of 2000 complete in 30.3 sec
[-------          19%                  ] 397 of 2000 complete in 30.8 sec
[-------          20%                  ] 404 of 2000 complete in 31.4 sec
[-------          20%                  ] 411 of 2000 complete in 31.9 sec
[-------          20%                  ] 418 of 2000 complete in 32.4 sec
[--------         21%                  ] 425 of 2000 complete in 32.9 sec
[--------         21%                  ] 432 of 2000 complete in 33.5 sec
[--------         21%                  ] 439 of 2000 complete in 34.0 sec
[--------         22%                  ] 446 of 2000 complete in 34.5 sec
[--------         22%                  ] 453 of 2000 complete in 35.1 sec
[--------         23%                  ] 460 of 2000 complete in 35.6 sec
[--------         23%                  ] 467 of 2000 complete in 36.1 sec
[---------        23%                  ] 474 of 2000 complete in 36.7 sec
[---------        24%                  ] 481 of 2000 complete in 37.2 sec
[---------        24%                  ] 488 of 2000 complete in 37.7 sec
[---------        24%                  ] 495 of 2000 complete in 38.3 sec
[---------        25%                  ] 502 of 2000 complete in 38.8 sec
[---------        25%                  ] 509 of 2000 complete in 39.3 sec
[---------        25%                  ] 516 of 2000 complete in 39.9 sec
[---------        26%                  ] 523 of 2000 complete in 40.4 sec
[----------       26%                  ] 530 of 2000 complete in 40.9 sec
[----------       26%                  ] 537 of 2000 complete in 41.5 sec
[----------       27%                  ] 544 of 2000 complete in 42.0 sec
[----------       27%                  ] 551 of 2000 complete in 42.5 sec
[----------       27%                  ] 558 of 2000 complete in 43.1 sec
[----------       28%                  ] 565 of 2000 complete in 43.6 sec
[----------       28%                  ] 572 of 2000 complete in 44.1 sec
[-----------      28%                  ] 579 of 2000 complete in 44.7 sec
[-----------      29%                  ] 586 of 2000 complete in 45.2 sec
[-----------      29%                  ] 593 of 2000 complete in 45.7 sec
[-----------      30%                  ] 600 of 2000 complete in 46.3 sec
[-----------      30%                  ] 607 of 2000 complete in 46.8 sec
[-----------      30%                  ] 614 of 2000 complete in 47.3 sec
[-----------      31%                  ] 621 of 2000 complete in 47.9 sec
[-----------      31%                  ] 628 of 2000 complete in 48.4 sec
[------------     31%                  ] 634 of 2000 complete in 48.9 sec
[------------     32%                  ] 641 of 2000 complete in 49.5 sec
[------------     32%                  ] 648 of 2000 complete in 50.0 sec
[------------     32%                  ] 655 of 2000 complete in 50.6 sec
[------------     33%                  ] 662 of 2000 complete in 51.2 sec

[-------          20%                  ] 414 of 2000 complete in 33.4 sec
[-------          21%                  ] 421 of 2000 complete in 33.9 sec
[--------         21%                  ] 428 of 2000 complete in 34.5 sec
[--------         21%                  ] 435 of 2000 complete in 35.0 sec
[--------         22%                  ] 442 of 2000 complete in 35.5 sec
[--------         22%                  ] 449 of 2000 complete in 36.1 sec
[--------         22%                  ] 456 of 2000 complete in 36.6 sec
[--------         23%                  ] 463 of 2000 complete in 37.2 sec
[--------         23%                  ] 470 of 2000 complete in 37.8 sec
[---------        23%                  ] 477 of 2000 complete in 38.3 sec
[---------        24%                  ] 484 of 2000 complete in 38.8 sec
[---------        24%                  ] 491 of 2000 complete in 39.4 sec
[---------        24%                  ] 498 of 2000 complete in 39.9 sec
[---------        25%                  ] 505 of 2000 complete in 40.5 sec
[---------        25%                  ] 512 of 2000 complete in 41.0 sec
[---------        25%                  ] 519 of 2000 complete in 41.6 sec
[---------        26%                  ] 526 of 2000 complete in 42.1 sec
[----------       26%                  ] 533 of 2000 complete in 42.7 sec
[----------       27%                  ] 540 of 2000 complete in 43.3 sec
[----------       27%                  ] 547 of 2000 complete in 43.8 sec
[----------       27%                  ] 554 of 2000 complete in 44.4 sec
[----------       28%                  ] 561 of 2000 complete in 44.9 sec
[----------       28%                  ] 568 of 2000 complete in 45.5 sec
[----------       28%                  ] 575 of 2000 complete in 46.1 sec
[-----------      29%                  ] 582 of 2000 complete in 46.6 sec
[-----------      29%                  ] 589 of 2000 complete in 47.2 sec
[-----------      29%                  ] 596 of 2000 complete in 47.7 sec
[-----------      30%                  ] 603 of 2000 complete in 48.3 sec
[-----------      30%                  ] 609 of 2000 complete in 48.8 sec
[-----------      30%                  ] 616 of 2000 complete in 49.4 sec
[-----------      31%                  ] 622 of 2000 complete in 49.9 sec
[-----------      31%                  ] 629 of 2000 complete in 50.5 sec
[------------     31%                  ] 636 of 2000 complete in 51.0 sec
[------------     32%                  ] 643 of 2000 complete in 51.6 sec
[------------     32%                  ] 650 of 2000 complete in 52.1 sec
[------------     32%                  ] 657 of 2000 complete in 52.7 sec
[------------     33%                  ] 664 of 2000 complete in 53.2 sec
[------------     33%                  ] 671 of 2000 complete in 53.8 sec
[------------     33%                  ] 678 of 2000 complete in 54.4 sec
[-------------    34%                  ] 685 of 2000 complete in 54.9 sec
[-------------    34%                  ] 692 of 2000 complete in 55.5 sec
[-------------    34%                  ] 698 of 2000 complete in 56.0 sec
[-------------    35%                  ] 704 of 2000 complete in 56.6 sec
[-------------    35%                  ] 710 of 2000 complete in 57.1 sec
[-------------    35%                  ] 717 of 2000 complete in 57.6 sec
[-------------    36%                  ] 723 of 2000 complete in 58.1 sec
[-------------    36%                  ] 729 of 2000 complete in 58.7 sec
[-------------    36%                  ] 736 of 2000 complete in 59.2 sec
[--------------   37%                  ] 743 of 2000 complete in 59.8 sec
[--------------   37%                  ] 750 of 2000 complete in 60.4 sec
[--------------   37%                  ] 757 of 2000 complete in 60.9 sec
[--------------   38%                  ] 764 of 2000 complete in 61.5 sec
[--------------   38%                  ] 771 of 2000 complete in 62.0 sec
[--------------   38%                  ] 778 of 2000 complete in 62.6 sec
[--------------   39%                  ] 785 of 2000 complete in 63.1 sec
[---------------  39%                  ] 792 of 2000 complete in 63.7 sec
[---------------  39%                  ] 799 of 2000 complete in 64.2 sec
[---------------  40%                  ] 806 of 2000 complete in 64.8 sec
[---------------  40%                  ] 813 of 2000 complete in 65.3 sec
[---------------  41%                  ] 820 of 2000 complete in 65.9 sec
[---------------  41%                  ] 827 of 2000 complete in 66.4 sec
[---------------  41%                  ] 834 of 2000 complete in 67.0 sec
[---------------  42%                  ] 841 of 2000 complete in 67.6 sec
[---------------- 42%                  ] 848 of 2000 complete in 68.1 sec
[---------------- 42%                  ] 855 of 2000 complete in 68.7 sec
[---------------- 43%                  ] 862 of 2000 complete in 69.2 sec
[---------------- 43%                  ] 869 of 2000 complete in 69.8 sec
[---------------- 43%                  ] 876 of 2000 complete in 70.3 sec
[---------------- 44%                  ] 882 of 2000 complete in 70.9 sec
[---------------- 44%                  ] 888 of 2000 complete in 71.4 sec
[---------------- 44%                  ] 894 of 2000 complete in 71.9 sec
[-----------------45%                  ] 901 of 2000 complete in 72.5 sec
[-----------------45%                  ] 908 of 2000 complete in 73.0 sec
[-----------------45%                  ] 915 of 2000 complete in 73.6 sec
[-----------------46%                  ] 921 of 2000 complete in 74.1 sec
[-----------------46%                  ] 927 of 2000 complete in 74.6 sec
[-----------------46%                  ] 934 of 2000 complete in 75.2 sec
[-----------------47%                  ] 941 of 2000 complete in 75.7 sec
[-----------------47%                  ] 947 of 2000 complete in 76.2 sec
[-----------------47%                  ] 954 of 2000 complete in 76.8 sec
[-----------------48%                  ] 961 of 2000 complete in 77.3 sec
[-----------------48%                  ] 968 of 2000 complete in 77.9 sec
[-----------------48%                  ] 975 of 2000 complete in 78.4 sec
[-----------------49%                  ] 982 of 2000 complete in 79.0 sec
[-----------------49%                  ] 989 of 2000 complete in 79.5 sec
[-----------------49%                  ] 996 of 2000 complete in 80.1 sec
[-----------------50%                  ] 1003 of 2000 complete in 80.7 sec
[-----------------50%                  ] 1010 of 2000 complete in 81.2 sec
[-----------------50%                  ] 1017 of 2000 complete in 81.8 sec
[-----------------51%                  ] 1024 of 2000 complete in 82.3 sec
[-----------------51%                  ] 1031 of 2000 complete in 82.9 sec
[-----------------51%                  ] 1038 of 2000 complete in 83.5 sec
[-----------------52%                  ] 1045 of 2000 complete in 84.0 sec
[-----------------52%                  ] 1052 of 2000 complete in 84.6 sec
[-----------------52%                  ] 1059 of 2000 complete in 85.1 sec
[-----------------53%                  ] 1066 of 2000 complete in 85.7 sec
[-----------------53%                  ] 1073 of 2000 complete in 86.2 sec
[-----------------54%                  ] 1080 of 2000 complete in 86.8 sec
[-----------------54%                  ] 1087 of 2000 complete in 87.4 sec
[-----------------54%                  ] 1094 of 2000 complete in 87.9 sec
[-----------------55%                  ] 1101 of 2000 complete in 88.5 sec
[-----------------55%-                 ] 1108 of 2000 complete in 89.0 sec
[-----------------55%-                 ] 1115 of 2000 complete in 89.6 sec
[-----------------56%-                 ] 1122 of 2000 complete in 90.1 sec
[-----------------56%-                 ] 1129 of 2000 complete in 90.7 sec
[-----------------56%-                 ] 1136 of 2000 complete in 91.2 sec
[-----------------57%-                 ] 1143 of 2000 complete in 91.8 sec
[-----------------57%-                 ] 1150 of 2000 complete in 92.3 sec
[-----------------57%-                 ] 1157 of 2000 complete in 92.9 sec
[-----------------58%--                ] 1164 of 2000 complete in 93.4 sec
[----------       28%                  ] 576 of 2000 complete in 45.2 sec
[-----------      29%                  ] 583 of 2000 complete in 45.7 sec
[-----------      29%                  ] 590 of 2000 complete in 46.3 sec
[-----------      29%                  ] 597 of 2000 complete in 46.8 sec
[-----------      30%                  ] 604 of 2000 complete in 47.3 sec
[-----------      30%                  ] 611 of 2000 complete in 47.9 sec
[-----------      30%                  ] 618 of 2000 complete in 48.4 sec
[-----------      31%                  ] 624 of 2000 complete in 48.9 sec
[-----------      31%                  ] 631 of 2000 complete in 49.5 sec
[------------     31%                  ] 637 of 2000 complete in 50.0 sec
[------------     32%                  ] 644 of 2000 complete in 50.6 sec
[------------     32%                  ] 651 of 2000 complete in 51.2 sec
[------------     32%                  ] 658 of 2000 complete in 51.7 sec
[------------     33%                  ] 665 of 2000 complete in 52.3 sec
[------------     33%                  ] 672 of 2000 complete in 52.8 sec
[------------     33%                  ] 679 of 2000 complete in 53.3 sec
[-------------    34%                  ] 686 of 2000 complete in 53.9 sec
[-------------    34%                  ] 693 of 2000 complete in 54.4 sec
[-------------    35%                  ] 700 of 2000 complete in 55.0 sec
[-------------    35%                  ] 707 of 2000 complete in 55.6 sec
[-------------    35%                  ] 713 of 2000 complete in 56.1 sec
[-------------    35%                  ] 719 of 2000 complete in 56.6 sec
[-------------    36%                  ] 726 of 2000 complete in 57.2 sec
[-------------    36%                  ] 733 of 2000 complete in 57.7 sec
[--------------   37%                  ] 740 of 2000 complete in 58.3 sec
[--------------   37%                  ] 746 of 2000 complete in 58.8 sec
[--------------   37%                  ] 753 of 2000 complete in 59.4 sec
[--------------   38%                  ] 760 of 2000 complete in 59.9 sec
[--------------   38%                  ] 767 of 2000 complete in 60.5 sec
[--------------   38%                  ] 774 of 2000 complete in 61.0 sec
[--------------   39%                  ] 781 of 2000 complete in 61.5 sec
[--------------   39%                  ] 788 of 2000 complete in 62.1 sec
[---------------  39%                  ] 795 of 2000 complete in 62.6 sec
[---------------  40%                  ] 802 of 2000 complete in 63.2 sec
[---------------  40%                  ] 809 of 2000 complete in 63.7 sec
[---------------  40%                  ] 816 of 2000 complete in 64.2 sec
[---------------  41%                  ] 823 of 2000 complete in 64.8 sec
[---------------  41%                  ] 830 of 2000 complete in 65.3 sec
[---------------  41%                  ] 837 of 2000 complete in 65.9 sec
[---------------- 42%                  ] 844 of 2000 complete in 66.4 sec
[---------------- 42%                  ] 851 of 2000 complete in 67.0 sec
[---------------- 42%                  ] 858 of 2000 complete in 67.5 sec
[---------------- 43%                  ] 865 of 2000 complete in 68.1 sec
[---------------- 43%                  ] 872 of 2000 complete in 68.6 sec
[---------------- 43%                  ] 879 of 2000 complete in 69.2 sec
[---------------- 44%                  ] 886 of 2000 complete in 69.7 sec
[---------------- 44%                  ] 893 of 2000 complete in 70.2 sec
[-----------------44%                  ] 899 of 2000 complete in 70.7 sec
[-----------------45%                  ] 905 of 2000 complete in 71.3 sec
[-----------------45%                  ] 911 of 2000 complete in 71.8 sec
[-----------------45%                  ] 918 of 2000 complete in 72.3 sec
[-----------------46%                  ] 925 of 2000 complete in 72.9 sec
[-----------------46%                  ] 932 of 2000 complete in 73.4 sec
[-----------------46%                  ] 939 of 2000 complete in 74.0 sec
[-----------------47%                  ] 945 of 2000 complete in 74.5 sec
[-----------------47%                  ] 952 of 2000 complete in 75.1 sec
[-----------------47%                  ] 959 of 2000 complete in 75.6 sec
[-----------------48%                  ] 966 of 2000 complete in 76.2 sec
[-----------------48%                  ] 973 of 2000 complete in 76.7 sec
[-----------------49%                  ] 980 of 2000 complete in 77.3 sec
[-----------------49%                  ] 987 of 2000 complete in 77.8 sec
[-----------------49%                  ] 993 of 2000 complete in 78.3 sec
[-----------------50%                  ] 1000 of 2000 complete in 78.9 sec
[-----------------50%                  ] 1007 of 2000 complete in 79.4 sec
[-----------------50%                  ] 1014 of 2000 complete in 80.0 sec
[-----------------51%                  ] 1021 of 2000 complete in 80.5 sec
[-----------------51%                  ] 1028 of 2000 complete in 81.0 sec
[-----------------51%                  ] 1035 of 2000 complete in 81.6 sec
[-----------------52%                  ] 1042 of 2000 complete in 82.1 sec
[-----------------52%                  ] 1049 of 2000 complete in 82.7 sec
[-----------------52%                  ] 1056 of 2000 complete in 83.2 sec
[-----------------53%                  ] 1063 of 2000 complete in 83.8 sec
[-----------------53%                  ] 1070 of 2000 complete in 84.3 sec
[-----------------53%                  ] 1077 of 2000 complete in 84.9 sec
[-----------------54%                  ] 1084 of 2000 complete in 85.4 sec
[-----------------54%                  ] 1091 of 2000 complete in 86.0 sec
[-----------------54%                  ] 1098 of 2000 complete in 86.5 sec
[-----------------55%                  ] 1105 of 2000 complete in 87.0 sec
[-----------------55%-                 ] 1112 of 2000 complete in 87.6 sec
[-----------------55%-                 ] 1119 of 2000 complete in 88.1 sec
[-----------------56%-                 ] 1126 of 2000 complete in 88.7 sec
[-----------------56%-                 ] 1133 of 2000 complete in 89.2 sec
[-----------------57%-                 ] 1140 of 2000 complete in 89.8 sec
[-----------------57%-                 ] 1147 of 2000 complete in 90.3 sec
[-----------------57%-                 ] 1154 of 2000 complete in 90.8 sec
[-----------------58%--                ] 1161 of 2000 complete in 91.4 sec
[-----------------58%--                ] 1168 of 2000 complete in 91.9 sec
[-----------------58%--                ] 1175 of 2000 complete in 92.5 sec
[-----------------59%--                ] 1182 of 2000 complete in 93.0 sec
[-----------------59%--                ] 1189 of 2000 complete in 93.6 sec
[-----------------59%--                ] 1196 of 2000 complete in 94.1 sec
[-----------------60%--                ] 1203 of 2000 complete in 94.6 sec
[-----------------60%--                ] 1210 of 2000 complete in 95.2 sec
[-----------------60%---               ] 1217 of 2000 complete in 95.7 sec
[-----------------61%---               ] 1224 of 2000 complete in 96.3 sec
[-----------------61%---               ] 1231 of 2000 complete in 96.9 sec
[-----------------61%---               ] 1238 of 2000 complete in 97.4 sec
[-----------------62%---               ] 1245 of 2000 complete in 98.0 sec
[-----------------62%---               ] 1251 of 2000 complete in 98.5 sec
[-----------------62%---               ] 1257 of 2000 complete in 99.0 sec
[-----------------63%----              ] 1264 of 2000 complete in 99.6 sec
[-----------------63%----              ] 1271 of 2000 complete in 100.2 sec
[-----------------63%----              ] 1278 of 2000 complete in 100.7 sec
[-----------------64%----              ] 1285 of 2000 complete in 101.3 sec
[-----------------64%----              ] 1291 of 2000 complete in 101.8 sec
[-----------------64%----              ] 1298 of 2000 complete in 102.3 sec
[-----------------65%----              ] 1305 of 2000 complete in 102.9 sec
[-----------------65%----              ] 1312 of 2000 complete in 103.4 sec
[-----------------65%-----             ] 1319 of 2000 complete in 104.0 sec

[-----------      31%                  ] 621 of 2000 complete in 48.3 sec
[-----------      31%                  ] 627 of 2000 complete in 48.8 sec
[------------     31%                  ] 634 of 2000 complete in 49.4 sec
[------------     32%                  ] 641 of 2000 complete in 49.9 sec
[------------     32%                  ] 648 of 2000 complete in 50.5 sec
[------------     32%                  ] 655 of 2000 complete in 51.1 sec
[------------     33%                  ] 662 of 2000 complete in 51.6 sec
[------------     33%                  ] 669 of 2000 complete in 52.2 sec
[------------     33%                  ] 676 of 2000 complete in 52.7 sec
[------------     34%                  ] 683 of 2000 complete in 53.3 sec
[-------------    34%                  ] 690 of 2000 complete in 53.8 sec
[-------------    34%                  ] 697 of 2000 complete in 54.3 sec
[-------------    35%                  ] 704 of 2000 complete in 54.9 sec
[-------------    35%                  ] 711 of 2000 complete in 55.4 sec
[-------------    35%                  ] 717 of 2000 complete in 56.0 sec
[-------------    36%                  ] 723 of 2000 complete in 56.5 sec
[-------------    36%                  ] 730 of 2000 complete in 57.1 sec
[--------------   36%                  ] 737 of 2000 complete in 57.6 sec
[--------------   37%                  ] 744 of 2000 complete in 58.2 sec
[--------------   37%                  ] 750 of 2000 complete in 58.7 sec
[--------------   37%                  ] 757 of 2000 complete in 59.2 sec
[--------------   38%                  ] 764 of 2000 complete in 59.8 sec
[--------------   38%                  ] 771 of 2000 complete in 60.3 sec
[--------------   38%                  ] 778 of 2000 complete in 60.8 sec
[--------------   39%                  ] 785 of 2000 complete in 61.4 sec
[---------------  39%                  ] 792 of 2000 complete in 61.9 sec
[---------------  39%                  ] 799 of 2000 complete in 62.4 sec
[---------------  40%                  ] 806 of 2000 complete in 63.0 sec
[---------------  40%                  ] 813 of 2000 complete in 63.5 sec
[---------------  41%                  ] 820 of 2000 complete in 64.1 sec
[---------------  41%                  ] 827 of 2000 complete in 64.6 sec
[---------------  41%                  ] 834 of 2000 complete in 65.1 sec
[---------------  42%                  ] 841 of 2000 complete in 65.7 sec
[---------------- 42%                  ] 848 of 2000 complete in 66.2 sec
[---------------- 42%                  ] 855 of 2000 complete in 66.8 sec
[---------------- 43%                  ] 862 of 2000 complete in 67.3 sec
[---------------- 43%                  ] 869 of 2000 complete in 67.9 sec
[---------------- 43%                  ] 876 of 2000 complete in 68.4 sec
[---------------- 44%                  ] 883 of 2000 complete in 68.9 sec
[---------------- 44%                  ] 890 of 2000 complete in 69.5 sec
[-----------------44%                  ] 897 of 2000 complete in 70.0 sec
[-----------------45%                  ] 904 of 2000 complete in 70.6 sec
[-----------------45%                  ] 910 of 2000 complete in 71.1 sec
[-----------------45%                  ] 916 of 2000 complete in 71.6 sec
[-----------------46%                  ] 923 of 2000 complete in 72.2 sec
[-----------------46%                  ] 930 of 2000 complete in 72.7 sec
[-----------------46%                  ] 937 of 2000 complete in 73.3 sec
[-----------------47%                  ] 944 of 2000 complete in 73.8 sec
[-----------------47%                  ] 951 of 2000 complete in 74.4 sec
[-----------------47%                  ] 958 of 2000 complete in 75.0 sec
[-----------------48%                  ] 965 of 2000 complete in 75.5 sec
[-----------------48%                  ] 972 of 2000 complete in 76.1 sec
[-----------------48%                  ] 979 of 2000 complete in 76.6 sec
[-----------------49%                  ] 986 of 2000 complete in 77.1 sec
[-----------------49%                  ] 993 of 2000 complete in 77.7 sec
[-----------------50%                  ] 1000 of 2000 complete in 78.2 sec
[-----------------50%                  ] 1007 of 2000 complete in 78.8 sec
[-----------------50%                  ] 1014 of 2000 complete in 79.3 sec
[-----------------51%                  ] 1021 of 2000 complete in 79.8 sec
[-----------------51%                  ] 1028 of 2000 complete in 80.4 sec
[-----------------51%                  ] 1035 of 2000 complete in 80.9 sec
[-----------------52%                  ] 1042 of 2000 complete in 81.4 sec
[-----------------52%                  ] 1049 of 2000 complete in 82.0 sec
[-----------------52%                  ] 1056 of 2000 complete in 82.5 sec
[-----------------53%                  ] 1063 of 2000 complete in 83.1 sec
[-----------------53%                  ] 1070 of 2000 complete in 83.6 sec
[-----------------53%                  ] 1077 of 2000 complete in 84.2 sec
[-----------------54%                  ] 1084 of 2000 complete in 84.7 sec
[-----------------54%                  ] 1091 of 2000 complete in 85.3 sec
[-----------------54%                  ] 1098 of 2000 complete in 85.8 sec
[-----------------55%                  ] 1105 of 2000 complete in 86.3 sec
[-----------------55%-                 ] 1112 of 2000 complete in 86.9 sec
[-----------------55%-                 ] 1119 of 2000 complete in 87.4 sec
[-----------------56%-                 ] 1126 of 2000 complete in 88.0 sec
[-----------------56%-                 ] 1133 of 2000 complete in 88.5 sec
[-----------------57%-                 ] 1140 of 2000 complete in 89.1 sec
[-----------------57%-                 ] 1147 of 2000 complete in 89.6 sec
[-----------------57%-                 ] 1154 of 2000 complete in 90.1 sec
[-----------------58%--                ] 1161 of 2000 complete in 90.7 sec
[-----------------58%--                ] 1168 of 2000 complete in 91.2 sec
[-----------------58%--                ] 1175 of 2000 complete in 91.7 sec
[-----------------59%--                ] 1182 of 2000 complete in 92.3 sec
[-----------------59%--                ] 1189 of 2000 complete in 92.8 sec
[-----------------59%--                ] 1196 of 2000 complete in 93.3 sec
[-----------------60%--                ] 1203 of 2000 complete in 93.9 sec
[-----------------60%--                ] 1210 of 2000 complete in 94.4 sec
[-----------------60%---               ] 1217 of 2000 complete in 95.0 sec
[-----------------61%---               ] 1224 of 2000 complete in 95.5 sec
[-----------------61%---               ] 1231 of 2000 complete in 96.1 sec
[-----------------61%---               ] 1238 of 2000 complete in 96.7 sec
[-----------------62%---               ] 1245 of 2000 complete in 97.2 sec
[-----------------62%---               ] 1252 of 2000 complete in 97.8 sec
[-----------------62%---               ] 1259 of 2000 complete in 98.3 sec
[-----------------63%----              ] 1265 of 2000 complete in 98.8 sec
[-----------------63%----              ] 1272 of 2000 complete in 99.4 sec
[-----------------63%----              ] 1279 of 2000 complete in 100.0 sec
[-----------------64%----              ] 1286 of 2000 complete in 100.5 sec
[-----------------64%----              ] 1293 of 2000 complete in 101.1 sec
[-----------------65%----              ] 1300 of 2000 complete in 101.7 sec
[-----------------65%----              ] 1307 of 2000 complete in 102.2 sec
[-----------------65%----              ] 1314 of 2000 complete in 102.8 sec
[-----------------66%-----             ] 1321 of 2000 complete in 103.3 sec
[-----------------66%-----             ] 1328 of 2000 complete in 103.9 sec
[-----------------66%-----             ] 1335 of 2000 complete in 104.4 sec
[-----------------67%-----             ] 1342 of 2000 complete in 105.0 sec
[-----------------67%-----             ] 1349 of 2000 complete in 105.6 sec
[-----------------67%-----             ] 1356 of 2000 complete in 106.1 sec
[-----------------68%-----             ] 1363 of 2000 complete in 106.7 sec
[-----------------68%------            ] 1370 of 2000 complete in 107.2 sec
[------------     33%                  ] 669 of 2000 complete in 51.7 sec
[------------     33%                  ] 676 of 2000 complete in 52.2 sec
[------------     34%                  ] 683 of 2000 complete in 52.8 sec
[-------------    34%                  ] 690 of 2000 complete in 53.3 sec
[-------------    34%                  ] 697 of 2000 complete in 53.8 sec
[-------------    35%                  ] 704 of 2000 complete in 54.4 sec
[-------------    35%                  ] 711 of 2000 complete in 54.9 sec
[-------------    35%                  ] 718 of 2000 complete in 55.5 sec
[-------------    36%                  ] 724 of 2000 complete in 56.0 sec
[-------------    36%                  ] 730 of 2000 complete in 56.5 sec
[--------------   36%                  ] 737 of 2000 complete in 57.1 sec
[--------------   37%                  ] 744 of 2000 complete in 57.6 sec
[--------------   37%                  ] 751 of 2000 complete in 58.2 sec
[--------------   37%                  ] 757 of 2000 complete in 58.7 sec
[--------------   38%                  ] 764 of 2000 complete in 59.3 sec
[--------------   38%                  ] 771 of 2000 complete in 59.8 sec
[--------------   38%                  ] 778 of 2000 complete in 60.3 sec
[--------------   39%                  ] 785 of 2000 complete in 60.9 sec
[---------------  39%                  ] 792 of 2000 complete in 61.4 sec
[---------------  39%                  ] 799 of 2000 complete in 61.9 sec
[---------------  40%                  ] 806 of 2000 complete in 62.5 sec
[---------------  40%                  ] 813 of 2000 complete in 63.0 sec
[---------------  41%                  ] 820 of 2000 complete in 63.6 sec
[---------------  41%                  ] 827 of 2000 complete in 64.1 sec
[---------------  41%                  ] 834 of 2000 complete in 64.6 sec
[---------------  42%                  ] 841 of 2000 complete in 65.2 sec
[---------------- 42%                  ] 848 of 2000 complete in 65.7 sec
[---------------- 42%                  ] 855 of 2000 complete in 66.2 sec
[---------------- 43%                  ] 862 of 2000 complete in 66.8 sec
[---------------- 43%                  ] 869 of 2000 complete in 67.3 sec
[---------------- 43%                  ] 876 of 2000 complete in 67.9 sec
[---------------- 44%                  ] 883 of 2000 complete in 68.4 sec
[---------------- 44%                  ] 890 of 2000 complete in 68.9 sec
[-----------------44%                  ] 897 of 2000 complete in 69.5 sec
[-----------------45%                  ] 904 of 2000 complete in 70.0 sec
[-----------------45%                  ] 911 of 2000 complete in 70.6 sec
[-----------------45%                  ] 917 of 2000 complete in 71.1 sec
[-----------------46%                  ] 923 of 2000 complete in 71.6 sec
[-----------------46%                  ] 930 of 2000 complete in 72.2 sec
[-----------------46%                  ] 937 of 2000 complete in 72.7 sec
[-----------------47%                  ] 944 of 2000 complete in 73.3 sec
[-----------------47%                  ] 951 of 2000 complete in 73.8 sec
[-----------------47%                  ] 957 of 2000 complete in 74.4 sec
[-----------------48%                  ] 964 of 2000 complete in 74.9 sec
[-----------------48%                  ] 971 of 2000 complete in 75.4 sec
[-----------------48%                  ] 978 of 2000 complete in 76.0 sec
[-----------------49%                  ] 985 of 2000 complete in 76.5 sec
[-----------------49%                  ] 992 of 2000 complete in 77.1 sec
[-----------------49%                  ] 999 of 2000 complete in 77.6 sec
[-----------------50%                  ] 1006 of 2000 complete in 78.2 sec
[-----------------50%                  ] 1013 of 2000 complete in 78.7 sec
[-----------------51%                  ] 1020 of 2000 complete in 79.2 sec
[-----------------51%                  ] 1027 of 2000 complete in 79.8 sec
[-----------------51%                  ] 1034 of 2000 complete in 80.3 sec
[-----------------52%                  ] 1041 of 2000 complete in 80.9 sec
[-----------------52%                  ] 1048 of 2000 complete in 81.4 sec
[-----------------52%                  ] 1055 of 2000 complete in 81.9 sec
[-----------------53%                  ] 1062 of 2000 complete in 82.5 sec
[-----------------53%                  ] 1069 of 2000 complete in 83.0 sec
[-----------------53%                  ] 1076 of 2000 complete in 83.6 sec
[-----------------54%                  ] 1083 of 2000 complete in 84.1 sec
[-----------------54%                  ] 1090 of 2000 complete in 84.6 sec
[-----------------54%                  ] 1097 of 2000 complete in 85.2 sec
[-----------------55%                  ] 1104 of 2000 complete in 85.7 sec
[-----------------55%-                 ] 1111 of 2000 complete in 86.2 sec
[-----------------55%-                 ] 1118 of 2000 complete in 86.8 sec
[-----------------56%-                 ] 1125 of 2000 complete in 87.3 sec
[-----------------56%-                 ] 1132 of 2000 complete in 87.8 sec
[-----------------56%-                 ] 1139 of 2000 complete in 88.4 sec
[-----------------57%-                 ] 1146 of 2000 complete in 88.9 sec
[-----------------57%-                 ] 1153 of 2000 complete in 89.5 sec
[-----------------58%--                ] 1160 of 2000 complete in 90.0 sec
[-----------------58%--                ] 1167 of 2000 complete in 90.5 sec
[-----------------58%--                ] 1174 of 2000 complete in 91.1 sec
[-----------------59%--                ] 1181 of 2000 complete in 91.6 sec
[-----------------59%--                ] 1188 of 2000 complete in 92.1 sec
[-----------------59%--                ] 1195 of 2000 complete in 92.7 sec
[-----------------60%--                ] 1202 of 2000 complete in 93.2 sec
[-----------------60%--                ] 1209 of 2000 complete in 93.7 sec
[-----------------60%---               ] 1216 of 2000 complete in 94.3 sec
[-----------------61%---               ] 1223 of 2000 complete in 94.8 sec
[-----------------61%---               ] 1230 of 2000 complete in 95.4 sec
[-----------------61%---               ] 1237 of 2000 complete in 95.9 sec
[-----------------62%---               ] 1244 of 2000 complete in 96.5 sec
[-----------------62%---               ] 1251 of 2000 complete in 97.1 sec
[-----------------62%---               ] 1258 of 2000 complete in 97.6 sec
[-----------------63%----              ] 1265 of 2000 complete in 98.2 sec
[-----------------63%----              ] 1272 of 2000 complete in 98.8 sec
[-----------------63%----              ] 1279 of 2000 complete in 99.3 sec
[-----------------64%----              ] 1286 of 2000 complete in 99.9 sec
[-----------------64%----              ] 1293 of 2000 complete in 100.4 sec
[-----------------65%----              ] 1300 of 2000 complete in 101.0 sec
[-----------------65%----              ] 1307 of 2000 complete in 101.6 sec
[-----------------65%----              ] 1314 of 2000 complete in 102.1 sec
[-----------------66%-----             ] 1321 of 2000 complete in 102.7 sec
[-----------------66%-----             ] 1328 of 2000 complete in 103.2 sec
[-----------------66%-----             ] 1335 of 2000 complete in 103.8 sec
[-----------------67%-----             ] 1342 of 2000 complete in 104.3 sec
[-----------------67%-----             ] 1349 of 2000 complete in 104.9 sec
[-----------------67%-----             ] 1356 of 2000 complete in 105.4 sec
[-----------------68%-----             ] 1363 of 2000 complete in 106.0 sec
[-----------------68%------            ] 1370 of 2000 complete in 106.6 sec
[-----------------68%------            ] 1377 of 2000 complete in 107.2 sec
[-----------------69%------            ] 1384 of 2000 complete in 107.7 sec
[-----------------69%------            ] 1390 of 2000 complete in 108.2 sec
[-----------------69%------            ] 1397 of 2000 complete in 108.8 sec
[-----------------70%------            ] 1404 of 2000 complete in 109.3 sec
[-----------------70%------            ] 1410 of 2000 complete in 109.8 sec
[-----------------70%------            ] 1417 of 2000 complete in 110.4 sec

[-----------------58%--                ] 1171 of 2000 complete in 94.0 sec
[-----------------58%--                ] 1178 of 2000 complete in 94.5 sec
[-----------------59%--                ] 1184 of 2000 complete in 95.0 sec
[-----------------59%--                ] 1191 of 2000 complete in 95.5 sec
[-----------------59%--                ] 1198 of 2000 complete in 96.1 sec
[-----------------60%--                ] 1205 of 2000 complete in 96.7 sec
[-----------------60%---               ] 1212 of 2000 complete in 97.3 sec
[-----------------60%---               ] 1219 of 2000 complete in 97.8 sec
[-----------------61%---               ] 1225 of 2000 complete in 98.3 sec
[-----------------61%---               ] 1231 of 2000 complete in 98.9 sec
[-----------------61%---               ] 1238 of 2000 complete in 99.4 sec
[-----------------62%---               ] 1245 of 2000 complete in 100.0 sec
[-----------------62%---               ] 1252 of 2000 complete in 100.6 sec
[-----------------62%---               ] 1259 of 2000 complete in 101.1 sec
[-----------------63%----              ] 1265 of 2000 complete in 101.7 sec
[-----------------63%----              ] 1272 of 2000 complete in 102.2 sec
[-----------------63%----              ] 1279 of 2000 complete in 102.8 sec
[-----------------64%----              ] 1286 of 2000 complete in 103.3 sec
[-----------------64%----              ] 1293 of 2000 complete in 103.9 sec
[-----------------65%----              ] 1300 of 2000 complete in 104.5 sec
[-----------------65%----              ] 1306 of 2000 complete in 105.0 sec
[-----------------65%----              ] 1313 of 2000 complete in 105.6 sec
[-----------------65%-----             ] 1319 of 2000 complete in 106.1 sec
[-----------------66%-----             ] 1326 of 2000 complete in 106.6 sec
[-----------------66%-----             ] 1332 of 2000 complete in 107.1 sec
[-----------------66%-----             ] 1339 of 2000 complete in 107.7 sec
[-----------------67%-----             ] 1345 of 2000 complete in 108.2 sec
[-----------------67%-----             ] 1352 of 2000 complete in 108.8 sec
[-----------------67%-----             ] 1358 of 2000 complete in 109.3 sec
[-----------------68%-----             ] 1364 of 2000 complete in 109.8 sec
[-----------------68%------            ] 1371 of 2000 complete in 110.4 sec
[-----------------68%------            ] 1378 of 2000 complete in 111.0 sec
[-----------------69%------            ] 1384 of 2000 complete in 111.5 sec
[-----------------69%------            ] 1391 of 2000 complete in 112.0 sec
[-----------------69%------            ] 1398 of 2000 complete in 112.6 sec
[-----------------70%------            ] 1404 of 2000 complete in 113.1 sec
[-----------------70%------            ] 1410 of 2000 complete in 113.6 sec
[-----------------70%------            ] 1416 of 2000 complete in 114.2 sec
[-----------------71%-------           ] 1423 of 2000 complete in 114.7 sec
[-----------------71%-------           ] 1429 of 2000 complete in 115.3 sec
[-----------------71%-------           ] 1435 of 2000 complete in 115.8 sec
[-----------------72%-------           ] 1441 of 2000 complete in 116.3 sec
[-----------------72%-------           ] 1448 of 2000 complete in 116.9 sec
[-----------------72%-------           ] 1455 of 2000 complete in 117.5 sec
[-----------------73%-------           ] 1462 of 2000 complete in 118.0 sec
[-----------------73%-------           ] 1468 of 2000 complete in 118.5 sec
[-----------------73%--------          ] 1475 of 2000 complete in 119.1 sec
[-----------------74%--------          ] 1482 of 2000 complete in 119.7 sec
[-----------------74%--------          ] 1488 of 2000 complete in 120.3 sec
[-----------------74%--------          ] 1494 of 2000 complete in 120.8 sec
[-----------------75%--------          ] 1501 of 2000 complete in 121.4 sec
[-----------------75%--------          ] 1508 of 2000 complete in 121.9 sec
[-----------------75%--------          ] 1515 of 2000 complete in 122.5 sec
[-----------------76%--------          ] 1522 of 2000 complete in 123.0 sec
[-----------------76%---------         ] 1529 of 2000 complete in 123.6 sec
[-----------------76%---------         ] 1536 of 2000 complete in 124.2 sec
[-----------------77%---------         ] 1543 of 2000 complete in 124.7 sec
[-----------------77%---------         ] 1550 of 2000 complete in 125.3 sec
[-----------------77%---------         ] 1557 of 2000 complete in 125.9 sec
[-----------------78%---------         ] 1564 of 2000 complete in 126.4 sec
[-----------------78%---------         ] 1571 of 2000 complete in 127.0 sec
[-----------------78%---------         ] 1578 of 2000 complete in 127.6 sec
[-----------------79%----------        ] 1585 of 2000 complete in 128.1 sec
[-----------------79%----------        ] 1592 of 2000 complete in 128.7 sec
[-----------------79%----------        ] 1599 of 2000 complete in 129.3 sec
[-----------------80%----------        ] 1605 of 2000 complete in 129.8 sec
[-----------------80%----------        ] 1612 of 2000 complete in 130.4 sec
[-----------------80%----------        ] 1618 of 2000 complete in 130.9 sec
[-----------------81%----------        ] 1624 of 2000 complete in 131.4 sec
[-----------------81%----------        ] 1630 of 2000 complete in 131.9 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 132.5 sec
[-----------------82%-----------       ] 1643 of 2000 complete in 133.0 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 133.6 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 134.1 sec
[-----------------83%-----------       ] 1662 of 2000 complete in 134.7 sec
[-----------------83%-----------       ] 1668 of 2000 complete in 135.2 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 135.8 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 136.3 sec
[-----------------84%------------      ] 1687 of 2000 complete in 136.8 sec
[-----------------84%------------      ] 1693 of 2000 complete in 137.3 sec
[-----------------85%------------      ] 1700 of 2000 complete in 137.9 sec
[-----------------85%------------      ] 1706 of 2000 complete in 138.4 sec
[-----------------85%------------      ] 1713 of 2000 complete in 139.0 sec
[-----------------85%------------      ] 1719 of 2000 complete in 139.6 sec
[-----------------86%------------      ] 1725 of 2000 complete in 140.1 sec
[-----------------86%------------      ] 1732 of 2000 complete in 140.6 sec
[-----------------86%-------------     ] 1738 of 2000 complete in 141.2 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 141.7 sec
[-----------------87%-------------     ] 1750 of 2000 complete in 142.2 sec
[-----------------87%-------------     ] 1757 of 2000 complete in 142.8 sec
[-----------------88%-------------     ] 1764 of 2000 complete in 143.3 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 143.9 sec
[-----------------88%-------------     ] 1778 of 2000 complete in 144.4 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 144.9 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 145.5 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 146.1 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 146.6 sec
[-----------------90%--------------    ] 1812 of 2000 complete in 147.2 sec
[-----------------90%--------------    ] 1819 of 2000 complete in 147.8 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 148.3 sec
[-----------------91%--------------    ] 1833 of 2000 complete in 148.9 sec
[-----------------92%--------------    ] 1840 of 2000 complete in 149.5 sec
[-----------------92%---------------   ] 1847 of 2000 complete in 150.0 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 150.6 sec
[-----------------93%---------------   ] 1861 of 2000 complete in 151.2 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 151.7 sec
[-----------------93%---------------   ] 1874 of 2000 complete in 152.2 sec
hddm sampling elpased time:  173.316 s
Start converting to InferenceData...

In [11]:
az.summary(hddm_id_m0_acc_diff_idata)

,mean,sd,hdi_3%,hdi_97%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
a,1.542,0.049,1.449,1.632,0.002,0.001,901.0,2709.0,1.00
a_std,0.284,0.041,0.210,0.361,0.002,0.001,417.0,1312.0,1.00
a_subj.7304,1.561,0.080,1.401,1.704,0.003,0.002,530.0,1031.0,1.01
a_subj.7305,1.762,0.087,1.596,1.922,0.003,0.002,651.0,1395.0,1.01
a_subj.7306,1.501,0.076,1.358,1.639,0.003,0.002,615.0,984.0,1.01
...,...,...,...,...,...,...,...,...,...
z_subj.7342,0.296,0.017,0.262,0.327,0.000,0.000,1594.0,2753.0,1.00
z_subj.7343,0.287,0.018,0.253,0.322,0.001,0.000,1272.0,2213.0,1.01
z_subj.7344,0.318,0.017,0.285,0.350,0.000,0.000,2070.0,3170.0,1.00
z_subj.7345,0.327,0.018,0.296,0.363,0.000,0.000,1625.0,2606.0,1.00
z_subj.73370,0.323,0.024,0.280,0.370,0.001,0.001,1025.0,1435.0,1.00

In [12]:
hddm_id_m0_acc_stats = hddm_id_m0_acc_diff.gen_stats()
hddm_id_m0_acc_stats[hddm_id_m0_acc_stats.index.isin(['a', 'v(Self.1)', 'v(Other.1)', 
                                                'v(Self.0)', 'v(Other.0)','z'])]

,mean,std,2.5q,25q,50q,75q,97.5q,mc err
a,1.541629,0.048798,1.450443,1.508542,1.539374,1.573815,1.642481,0.001415
v(Other.0),3.387548,0.141752,3.109703,3.290372,3.385496,3.485077,3.668188,0.002849
v(Self.1),3.872383,0.143023,3.596189,3.773458,3.871976,3.967797,4.154047,0.002913
z,0.33411,0.006831,0.320656,0.329734,0.333889,0.338589,0.347912,0.000348

In [16]:
#hddm_choice
# HDDM choice coding 
# v varies across different stim and id
hddm_id_m1_choice_diff = hddm.HDDM(data, include=['a', 'v', 't','z'], depends_on={'v': ['id', 'stim']})

hddm_id_m1_choice_diff_idata = hddm_id_m1_choice_diff.sample(2000, burn=500, chains=4, return_infdata=True, dbname = 'hddm_id_m1_choice_diff.db', db = 'pickle')
hddm_id_m1_choice_diff.save('hddm_id_m1_choice_diff.hddm')
# hddm.load('hddm_id_m1_choice.hddm')

No model attribute --> setting up standard HDDM
Set model to ddm

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

[-----------------69%------            ] 1390 of 2000 complete in 110.2 sec
[-----------------69%------            ] 1396 of 2000 complete in 110.7 sec
[-----------------70%------            ] 1403 of 2000 complete in 111.2 sec
[-----------------70%------            ] 1410 of 2000 complete in 111.8 sec
[-----------------70%------            ] 1417 of 2000 complete in 112.4 sec
[-----------------71%-------           ] 1424 of 2000 complete in 112.9 sec
[-----------------71%-------           ] 1431 of 2000 complete in 113.5 sec
[-----------------71%-------           ] 1438 of 2000 complete in 114.1 sec
[-----------------72%-------           ] 1445 of 2000 complete in 114.6 sec
[-----------------72%-------           ] 1452 of 2000 complete in 115.2 sec
[-----------------72%-------           ] 1459 of 2000 complete in 115.8 sec
[-----------------73%-------           ] 1466 of 2000 complete in 116.3 sec
[-----------------73%-------           ] 1473 of 2000 complete in 116.9 sec
[-----------------74%--------          ] 1480 of 2000 complete in 117.5 sec
[-----------------74%--------          ] 1487 of 2000 complete in 118.0 sec
[-----------------74%--------          ] 1494 of 2000 complete in 118.6 sec
[-----------------75%--------          ] 1501 of 2000 complete in 119.2 sec
[-----------------75%--------          ] 1507 of 2000 complete in 119.7 sec
[-----------------75%--------          ] 1514 of 2000 complete in 120.2 sec
[-----------------76%--------          ] 1521 of 2000 complete in 120.8 sec
[-----------------76%---------         ] 1528 of 2000 complete in 121.4 sec
[-----------------76%---------         ] 1535 of 2000 complete in 122.0 sec
[-----------------77%---------         ] 1542 of 2000 complete in 122.5 sec
[-----------------77%---------         ] 1549 of 2000 complete in 123.1 sec
[-----------------77%---------         ] 1556 of 2000 complete in 123.7 sec
[-----------------78%---------         ] 1563 of 2000 complete in 124.2 sec
[-----------------78%---------         ] 1570 of 2000 complete in 124.8 sec
[-----------------78%---------         ] 1576 of 2000 complete in 125.3 sec
[-----------------79%----------        ] 1583 of 2000 complete in 125.9 sec
[-----------------79%----------        ] 1590 of 2000 complete in 126.4 sec
[-----------------79%----------        ] 1596 of 2000 complete in 126.9 sec
[-----------------80%----------        ] 1603 of 2000 complete in 127.5 sec
[-----------------80%----------        ] 1610 of 2000 complete in 128.1 sec
[-----------------80%----------        ] 1617 of 2000 complete in 128.7 sec
[-----------------81%----------        ] 1624 of 2000 complete in 129.2 sec
[-----------------81%----------        ] 1631 of 2000 complete in 129.8 sec
[-----------------81%-----------       ] 1638 of 2000 complete in 130.4 sec
[-----------------82%-----------       ] 1644 of 2000 complete in 130.9 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 131.4 sec
[-----------------82%-----------       ] 1658 of 2000 complete in 132.0 sec
[-----------------83%-----------       ] 1665 of 2000 complete in 132.6 sec
[-----------------83%-----------       ] 1672 of 2000 complete in 133.2 sec
[-----------------83%-----------       ] 1679 of 2000 complete in 133.7 sec
[-----------------84%------------      ] 1686 of 2000 complete in 134.3 sec
[-----------------84%------------      ] 1693 of 2000 complete in 134.9 sec
[-----------------85%------------      ] 1700 of 2000 complete in 135.4 sec
[-----------------85%------------      ] 1707 of 2000 complete in 136.0 sec
[-----------------85%------------      ] 1714 of 2000 complete in 136.5 sec
[-----------------86%------------      ] 1721 of 2000 complete in 137.1 sec
[-----------------86%------------      ] 1728 of 2000 complete in 137.7 sec
[-----------------86%------------      ] 1735 of 2000 complete in 138.2 sec
[-----------------87%-------------     ] 1742 of 2000 complete in 138.8 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 139.4 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 139.9 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 140.5 sec
[-----------------88%-------------     ] 1770 of 2000 complete in 141.0 sec
[-----------------88%-------------     ] 1777 of 2000 complete in 141.6 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 142.2 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 142.7 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 143.3 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 143.8 sec
[-----------------90%--------------    ] 1812 of 2000 complete in 144.4 sec
[-----------------90%--------------    ] 1819 of 2000 complete in 145.0 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 145.5 sec
[-----------------91%--------------    ] 1833 of 2000 complete in 146.1 sec
[-----------------92%--------------    ] 1840 of 2000 complete in 146.7 sec
[-----------------92%---------------   ] 1847 of 2000 complete in 147.3 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 147.8 sec
[-----------------93%---------------   ] 1861 of 2000 complete in 148.4 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 148.9 sec
[-----------------93%---------------   ] 1875 of 2000 complete in 149.5 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 150.1 sec
[-----------------94%---------------   ] 1889 of 2000 complete in 150.6 sec
[-----------------94%----------------  ] 1896 of 2000 complete in 151.2 sec
[-----------------95%----------------  ] 1903 of 2000 complete in 151.7 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 152.3 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 152.9 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 153.4 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 154.0 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 154.5 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 155.1 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 155.6 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 156.2 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 156.7 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 157.3 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 157.8 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 158.4 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 158.9 sec
[-----------------100%-----------------] 2000 of 2000 complete in 159.4 sec
[-----------------100%-----------------] 2000 of 2000 complete in 159.5 sec
hddm sampling elpased time:  159.618 s
[                  0%                  ] 8 of 2000 complete in 0.6 sec
[                  0%                  ] 15 of 2000 complete in 1.1 sec
[                  1%                  ] 22 of 2000 complete in 1.7 sec
[                  1%                  ] 28 of 2000 complete in 2.2 sec
[                  1%                  ] 35 of 2000 complete in 2.8 sec
[                  2%                  ] 42 of 2000 complete in 3.3 sec
[                  2%                  ] 49 of 2000 complete in 3.9 sec
[-                 2%                  ] 56 of 2000 complete in 4.5 sec
[-                 3%                  ] 63 of 2000 complete in 5.0 sec
[-                 3%                  ] 70 of 2000 complete in 5.6 sec
[-                 3%                  ] 76 of 2000 complete in 6.1 sec
[-                 4%                  ] 81 of 2000 complete in 6.7 sec
[-                 4%                  ] 88 of 2000 complete in 7.2 sec
[-                 4%                  ] 94 of 2000 complete in 7.8 sec
[-                 5%                  ] 100 of 2000 complete in 8.3 sec
[--                5%                  ] 106 of 2000 complete in 8.9 sec
[--                5%                  ] 112 of 2000 complete in 9.4 sec
[--                5%                  ] 118 of 2000 complete in 9.9 sec
[-----------------78%---------         ] 1569 of 2000 complete in 123.1 sec
[-----------------78%---------         ] 1576 of 2000 complete in 123.6 sec
[-----------------79%----------        ] 1583 of 2000 complete in 124.2 sec
[-----------------79%----------        ] 1590 of 2000 complete in 124.8 sec
[-----------------79%----------        ] 1597 of 2000 complete in 125.3 sec
[-----------------80%----------        ] 1603 of 2000 complete in 125.8 sec
[-----------------80%----------        ] 1610 of 2000 complete in 126.4 sec
[-----------------80%----------        ] 1616 of 2000 complete in 126.9 sec
[-----------------81%----------        ] 1623 of 2000 complete in 127.5 sec
[-----------------81%----------        ] 1630 of 2000 complete in 128.0 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 128.6 sec
[-----------------82%-----------       ] 1644 of 2000 complete in 129.2 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 129.7 sec
[-----------------82%-----------       ] 1658 of 2000 complete in 130.3 sec
[-----------------83%-----------       ] 1664 of 2000 complete in 130.8 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 131.4 sec
[-----------------83%-----------       ] 1678 of 2000 complete in 131.9 sec
[-----------------84%------------      ] 1685 of 2000 complete in 132.5 sec
[-----------------84%------------      ] 1692 of 2000 complete in 133.1 sec
[-----------------84%------------      ] 1699 of 2000 complete in 133.6 sec
[-----------------85%------------      ] 1706 of 2000 complete in 134.2 sec
[-----------------85%------------      ] 1713 of 2000 complete in 134.7 sec
[-----------------86%------------      ] 1720 of 2000 complete in 135.3 sec
[-----------------86%------------      ] 1727 of 2000 complete in 135.9 sec
[-----------------86%------------      ] 1734 of 2000 complete in 136.4 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 137.0 sec
[-----------------87%-------------     ] 1748 of 2000 complete in 137.5 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 138.1 sec
[-----------------88%-------------     ] 1762 of 2000 complete in 138.6 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 139.2 sec
[-----------------88%-------------     ] 1776 of 2000 complete in 139.8 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 140.3 sec
[-----------------89%--------------    ] 1790 of 2000 complete in 140.9 sec
[-----------------89%--------------    ] 1797 of 2000 complete in 141.5 sec
[-----------------90%--------------    ] 1804 of 2000 complete in 142.0 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 142.6 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 143.1 sec
[-----------------91%--------------    ] 1825 of 2000 complete in 143.7 sec
[-----------------91%--------------    ] 1832 of 2000 complete in 144.3 sec
[-----------------91%--------------    ] 1839 of 2000 complete in 144.8 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 145.4 sec
[-----------------92%---------------   ] 1853 of 2000 complete in 145.9 sec
[-----------------93%---------------   ] 1860 of 2000 complete in 146.5 sec
[-----------------93%---------------   ] 1866 of 2000 complete in 147.0 sec
[-----------------93%---------------   ] 1873 of 2000 complete in 147.5 sec
[-----------------94%---------------   ] 1880 of 2000 complete in 148.1 sec
[-----------------94%---------------   ] 1887 of 2000 complete in 148.7 sec
[-----------------94%---------------   ] 1894 of 2000 complete in 149.2 sec
[-----------------95%----------------  ] 1901 of 2000 complete in 149.8 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 150.3 sec
[-----------------95%----------------  ] 1915 of 2000 complete in 150.9 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 151.4 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 152.0 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 152.5 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 153.1 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 153.6 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 154.2 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 154.7 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 155.3 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 155.8 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 156.4 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 156.9 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 157.5 sec
[-----------------100%-----------------] 2000 of 2000 complete in 157.6 sec
hddm sampling elpased time:  157.738 s
[                  0%                  ] 8 of 2000 complete in 0.5 sec
[                  0%                  ] 15 of 2000 complete in 1.1 sec
[                  1%                  ] 22 of 2000 complete in 1.6 sec
[                  1%                  ] 29 of 2000 complete in 2.2 sec
[                  1%                  ] 35 of 2000 complete in 2.7 sec
[                  2%                  ] 42 of 2000 complete in 3.3 sec
[                  2%                  ] 49 of 2000 complete in 3.8 sec
[-                 2%                  ] 56 of 2000 complete in 4.4 sec
[-                 3%                  ] 63 of 2000 complete in 5.0 sec
[-                 3%                  ] 70 of 2000 complete in 5.5 sec
[-                 3%                  ] 77 of 2000 complete in 6.1 sec
[-                 4%                  ] 82 of 2000 complete in 6.7 sec
[-                 4%                  ] 89 of 2000 complete in 7.2 sec
[-                 4%                  ] 95 of 2000 complete in 7.8 sec
[-                 5%                  ] 101 of 2000 complete in 8.3 sec
[--                5%                  ] 107 of 2000 complete in 8.8 sec
[--                5%                  ] 113 of 2000 complete in 9.4 sec
[--                5%                  ] 119 of 2000 complete in 9.9 sec
[--                6%                  ] 125 of 2000 complete in 10.4 sec
[--                6%                  ] 131 of 2000 complete in 10.9 sec
[--                6%                  ] 137 of 2000 complete in 11.4 sec
[--                7%                  ] 143 of 2000 complete in 12.0 sec
[--                7%                  ] 149 of 2000 complete in 12.5 sec
[--                7%                  ] 155 of 2000 complete in 13.0 sec
[---               8%                  ] 161 of 2000 complete in 13.5 sec
[---               8%                  ] 167 of 2000 complete in 14.0 sec
[---               8%                  ] 174 of 2000 complete in 14.6 sec
[---               9%                  ] 181 of 2000 complete in 15.2 sec
[---               9%                  ] 187 of 2000 complete in 15.7 sec
[---               9%                  ] 193 of 2000 complete in 16.2 sec
[---              10%                  ] 200 of 2000 complete in 16.7 sec
[---              10%                  ] 207 of 2000 complete in 17.3 sec
[----             10%                  ] 214 of 2000 complete in 17.8 sec
[----             11%                  ] 221 of 2000 complete in 18.3 sec
[----             11%                  ] 228 of 2000 complete in 18.8 sec
[----             11%                  ] 235 of 2000 complete in 19.4 sec
[----             12%                  ] 242 of 2000 complete in 19.9 sec
[----             12%                  ] 249 of 2000 complete in 20.4 sec
[----             12%                  ] 256 of 2000 complete in 20.9 sec
[----             13%                  ] 263 of 2000 complete in 21.5 sec
[-----            13%                  ] 270 of 2000 complete in 22.0 sec
[-----            13%                  ] 277 of 2000 complete in 22.5 sec
[-----            14%                  ] 284 of 2000 complete in 23.1 sec
[-----            14%                  ] 291 of 2000 complete in 23.6 sec

[-----------------81%----------        ] 1620 of 2000 complete in 126.1 sec
[-----------------81%----------        ] 1627 of 2000 complete in 126.7 sec
[-----------------81%-----------       ] 1634 of 2000 complete in 127.3 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 127.8 sec
[-----------------82%-----------       ] 1648 of 2000 complete in 128.4 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 128.9 sec
[-----------------83%-----------       ] 1662 of 2000 complete in 129.5 sec
[-----------------83%-----------       ] 1669 of 2000 complete in 130.0 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 130.6 sec
[-----------------84%-----------       ] 1683 of 2000 complete in 131.1 sec
[-----------------84%------------      ] 1690 of 2000 complete in 131.7 sec
[-----------------84%------------      ] 1697 of 2000 complete in 132.2 sec
[-----------------85%------------      ] 1704 of 2000 complete in 132.8 sec
[-----------------85%------------      ] 1711 of 2000 complete in 133.4 sec
[-----------------85%------------      ] 1718 of 2000 complete in 133.9 sec
[-----------------86%------------      ] 1725 of 2000 complete in 134.5 sec
[-----------------86%------------      ] 1732 of 2000 complete in 135.0 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 135.6 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 136.1 sec
[-----------------87%-------------     ] 1753 of 2000 complete in 136.7 sec
[-----------------88%-------------     ] 1760 of 2000 complete in 137.2 sec
[-----------------88%-------------     ] 1767 of 2000 complete in 137.8 sec
[-----------------88%-------------     ] 1774 of 2000 complete in 138.3 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 138.9 sec
[-----------------89%-------------     ] 1788 of 2000 complete in 139.4 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 140.0 sec
[-----------------90%--------------    ] 1802 of 2000 complete in 140.5 sec
[-----------------90%--------------    ] 1809 of 2000 complete in 141.1 sec
[-----------------90%--------------    ] 1816 of 2000 complete in 141.7 sec
[-----------------91%--------------    ] 1823 of 2000 complete in 142.2 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 142.8 sec
[-----------------91%--------------    ] 1837 of 2000 complete in 143.3 sec
[-----------------92%---------------   ] 1844 of 2000 complete in 143.9 sec
[-----------------92%---------------   ] 1851 of 2000 complete in 144.4 sec
[-----------------92%---------------   ] 1858 of 2000 complete in 145.0 sec
[-----------------93%---------------   ] 1865 of 2000 complete in 145.5 sec
[-----------------93%---------------   ] 1872 of 2000 complete in 146.1 sec
[-----------------93%---------------   ] 1879 of 2000 complete in 146.6 sec
[-----------------94%---------------   ] 1886 of 2000 complete in 147.2 sec
[-----------------94%---------------   ] 1893 of 2000 complete in 147.8 sec
[-----------------95%----------------  ] 1900 of 2000 complete in 148.3 sec
[-----------------95%----------------  ] 1907 of 2000 complete in 148.9 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 149.4 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 150.0 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 150.5 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 151.0 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 151.6 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 152.1 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 152.7 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 153.2 sec
[-----------------98%----------------- ] 1970 of 2000 complete in 153.8 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 154.3 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 154.9 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 155.4 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 156.0 sec
[-----------------100%-----------------] 2000 of 2000 complete in 156.2 sec
hddm sampling elpased time:  156.361 s
[                  0%                  ] 8 of 2000 complete in 0.5 sec
[                  0%                  ] 15 of 2000 complete in 1.1 sec
[                  1%                  ] 22 of 2000 complete in 1.6 sec
[                  1%                  ] 29 of 2000 complete in 2.2 sec
[                  1%                  ] 36 of 2000 complete in 2.8 sec
[                  2%                  ] 43 of 2000 complete in 3.3 sec
[                  2%                  ] 50 of 2000 complete in 3.9 sec
[-                 2%                  ] 57 of 2000 complete in 4.4 sec
[-                 3%                  ] 64 of 2000 complete in 5.0 sec
[-                 3%                  ] 71 of 2000 complete in 5.5 sec
[-                 3%                  ] 78 of 2000 complete in 6.1 sec
[-                 4%                  ] 83 of 2000 complete in 6.6 sec
[-                 4%                  ] 90 of 2000 complete in 7.2 sec
[-                 4%                  ] 96 of 2000 complete in 7.7 sec
[-                 5%                  ] 102 of 2000 complete in 8.2 sec
[--                5%                  ] 108 of 2000 complete in 8.8 sec
[--                5%                  ] 114 of 2000 complete in 9.3 sec
[--                6%                  ] 120 of 2000 complete in 9.8 sec
[--                6%                  ] 126 of 2000 complete in 10.4 sec
[--                6%                  ] 132 of 2000 complete in 10.9 sec
[--                6%                  ] 138 of 2000 complete in 11.4 sec
[--                7%                  ] 144 of 2000 complete in 11.9 sec
[--                7%                  ] 150 of 2000 complete in 12.4 sec
[--                7%                  ] 157 of 2000 complete in 13.0 sec
[---               8%                  ] 164 of 2000 complete in 13.6 sec
[---               8%                  ] 171 of 2000 complete in 14.2 sec
[---               8%                  ] 178 of 2000 complete in 14.7 sec
[---               9%                  ] 185 of 2000 complete in 15.3 sec
[---               9%                  ] 191 of 2000 complete in 15.8 sec
[---               9%                  ] 198 of 2000 complete in 16.3 sec
[---              10%                  ] 205 of 2000 complete in 16.9 sec
[----             10%                  ] 212 of 2000 complete in 17.4 sec
[----             10%                  ] 219 of 2000 complete in 18.0 sec
[----             11%                  ] 226 of 2000 complete in 18.5 sec
[----             11%                  ] 233 of 2000 complete in 19.0 sec
[----             12%                  ] 240 of 2000 complete in 19.5 sec
[----             12%                  ] 247 of 2000 complete in 20.1 sec
[----             12%                  ] 254 of 2000 complete in 20.6 sec
[----             13%                  ] 261 of 2000 complete in 21.1 sec
[-----            13%                  ] 268 of 2000 complete in 21.6 sec
[-----            13%                  ] 275 of 2000 complete in 22.1 sec
[-----            14%                  ] 282 of 2000 complete in 22.7 sec
[-----            14%                  ] 289 of 2000 complete in 23.2 sec
[-----            14%                  ] 296 of 2000 complete in 23.7 sec
[-----            15%                  ] 303 of 2000 complete in 24.2 sec
[-----            15%                  ] 310 of 2000 complete in 24.8 sec
[------           15%                  ] 317 of 2000 complete in 25.3 sec
[------           16%                  ] 324 of 2000 complete in 25.8 sec
[------           16%                  ] 331 of 2000 complete in 26.3 sec
[------           16%                  ] 338 of 2000 complete in 26.9 sec
[------           17%                  ] 345 of 2000 complete in 27.4 sec
[------           17%                  ] 352 of 2000 complete in 27.9 sec
[------           17%                  ] 359 of 2000 complete in 28.4 sec
[-----------------83%-----------       ] 1678 of 2000 complete in 130.4 sec
[-----------------84%------------      ] 1685 of 2000 complete in 131.0 sec
[-----------------84%------------      ] 1692 of 2000 complete in 131.6 sec
[-----------------84%------------      ] 1699 of 2000 complete in 132.1 sec
[-----------------85%------------      ] 1706 of 2000 complete in 132.7 sec
[-----------------85%------------      ] 1713 of 2000 complete in 133.2 sec
[-----------------86%------------      ] 1720 of 2000 complete in 133.8 sec
[-----------------86%------------      ] 1727 of 2000 complete in 134.3 sec
[-----------------86%------------      ] 1734 of 2000 complete in 134.9 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 135.4 sec
[-----------------87%-------------     ] 1748 of 2000 complete in 136.0 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 136.6 sec
[-----------------88%-------------     ] 1762 of 2000 complete in 137.1 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 137.6 sec
[-----------------88%-------------     ] 1776 of 2000 complete in 138.2 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 138.7 sec
[-----------------89%--------------    ] 1790 of 2000 complete in 139.3 sec
[-----------------89%--------------    ] 1797 of 2000 complete in 139.8 sec
[-----------------90%--------------    ] 1804 of 2000 complete in 140.4 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 141.0 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 141.5 sec
[-----------------91%--------------    ] 1825 of 2000 complete in 142.1 sec
[-----------------91%--------------    ] 1832 of 2000 complete in 142.6 sec
[-----------------91%--------------    ] 1839 of 2000 complete in 143.2 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 143.7 sec
[-----------------92%---------------   ] 1853 of 2000 complete in 144.3 sec
[-----------------93%---------------   ] 1860 of 2000 complete in 144.8 sec
[-----------------93%---------------   ] 1867 of 2000 complete in 145.4 sec
[-----------------93%---------------   ] 1874 of 2000 complete in 145.9 sec
[-----------------94%---------------   ] 1881 of 2000 complete in 146.5 sec
[-----------------94%---------------   ] 1888 of 2000 complete in 147.0 sec
[-----------------94%----------------  ] 1895 of 2000 complete in 147.6 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 148.1 sec
[-----------------95%----------------  ] 1909 of 2000 complete in 148.7 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 149.2 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 149.8 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 150.4 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 150.9 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 151.5 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 152.0 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 152.6 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 153.1 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 153.7 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 154.2 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 154.8 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 155.3 sec
[-----------------100%-----------------] 2000 of 2000 complete in 155.9 sec
[-----------------100%-----------------] 2000 of 2000 complete in 156.0 sec
hddm sampling elpased time:  156.085 s
[                  0%                  ] 8 of 2000 complete in 0.5 sec
[                  0%                  ] 15 of 2000 complete in 1.1 sec
[                  1%                  ] 22 of 2000 complete in 1.6 sec
[                  1%                  ] 29 of 2000 complete in 2.2 sec
[                  1%                  ] 36 of 2000 complete in 2.8 sec
[                  2%                  ] 43 of 2000 complete in 3.3 sec
[                  2%                  ] 50 of 2000 complete in 3.9 sec
[-                 2%                  ] 57 of 2000 complete in 4.4 sec
[-                 3%                  ] 64 of 2000 complete in 5.0 sec
[-                 3%                  ] 71 of 2000 complete in 5.5 sec
[-                 3%                  ] 78 of 2000 complete in 6.1 sec
[-                 4%                  ] 83 of 2000 complete in 6.6 sec
[-                 4%                  ] 89 of 2000 complete in 7.1 sec
[-                 4%                  ] 96 of 2000 complete in 7.7 sec
[-                 5%                  ] 102 of 2000 complete in 8.2 sec
[--                5%                  ] 108 of 2000 complete in 8.7 sec
[--                5%                  ] 114 of 2000 complete in 9.3 sec
[--                6%                  ] 120 of 2000 complete in 9.8 sec
[--                6%                  ] 126 of 2000 complete in 10.3 sec
[--                6%                  ] 132 of 2000 complete in 10.9 sec
[--                6%                  ] 138 of 2000 complete in 11.4 sec
[--                7%                  ] 144 of 2000 complete in 11.9 sec
[--                7%                  ] 150 of 2000 complete in 12.4 sec
[--                7%                  ] 156 of 2000 complete in 12.9 sec
[---               8%                  ] 163 of 2000 complete in 13.5 sec
[---               8%                  ] 170 of 2000 complete in 14.1 sec
[---               8%                  ] 177 of 2000 complete in 14.6 sec
[---               9%                  ] 184 of 2000 complete in 15.2 sec
[---               9%                  ] 190 of 2000 complete in 15.7 sec
[---               9%                  ] 196 of 2000 complete in 16.2 sec
[---              10%                  ] 203 of 2000 complete in 16.8 sec
[---              10%                  ] 210 of 2000 complete in 17.3 sec
[----             10%                  ] 217 of 2000 complete in 17.8 sec
[----             11%                  ] 224 of 2000 complete in 18.3 sec
[----             11%                  ] 231 of 2000 complete in 18.9 sec
[----             11%                  ] 238 of 2000 complete in 19.4 sec
[----             12%                  ] 245 of 2000 complete in 19.9 sec
[----             12%                  ] 252 of 2000 complete in 20.4 sec
[----             12%                  ] 259 of 2000 complete in 21.0 sec
[-----            13%                  ] 266 of 2000 complete in 21.5 sec
[-----            13%                  ] 273 of 2000 complete in 22.0 sec
[-----            14%                  ] 280 of 2000 complete in 22.5 sec
[-----            14%                  ] 287 of 2000 complete in 23.1 sec
[-----            14%                  ] 294 of 2000 complete in 23.6 sec
[-----            15%                  ] 301 of 2000 complete in 24.1 sec
[-----            15%                  ] 308 of 2000 complete in 24.6 sec
[-----            15%                  ] 315 of 2000 complete in 25.2 sec
[------           16%                  ] 322 of 2000 complete in 25.7 sec
[------           16%                  ] 329 of 2000 complete in 26.2 sec
[------           16%                  ] 336 of 2000 complete in 26.7 sec
[------           17%                  ] 343 of 2000 complete in 27.3 sec
[------           17%                  ] 350 of 2000 complete in 27.8 sec
[------           17%                  ] 357 of 2000 complete in 28.3 sec
[------           18%                  ] 364 of 2000 complete in 28.8 sec
[-------          18%                  ] 371 of 2000 complete in 29.4 sec
[-------          18%                  ] 378 of 2000 complete in 29.9 sec
[-------          19%                  ] 385 of 2000 complete in 30.5 sec
[-------          19%                  ] 392 of 2000 complete in 31.0 sec
[-------          19%                  ] 399 of 2000 complete in 31.6 sec
[-------          20%                  ] 406 of 2000 complete in 32.1 sec
[-------          20%                  ] 413 of 2000 complete in 32.6 sec

[--                6%                  ] 124 of 2000 complete in 10.5 sec
[--                6%                  ] 130 of 2000 complete in 11.0 sec
[--                6%                  ] 136 of 2000 complete in 11.6 sec
[--                7%                  ] 142 of 2000 complete in 12.1 sec
[--                7%                  ] 148 of 2000 complete in 12.6 sec
[--                7%                  ] 155 of 2000 complete in 13.2 sec
[---               8%                  ] 161 of 2000 complete in 13.7 sec
[---               8%                  ] 168 of 2000 complete in 14.3 sec
[---               8%                  ] 175 of 2000 complete in 14.8 sec
[---               9%                  ] 182 of 2000 complete in 15.4 sec
[---               9%                  ] 188 of 2000 complete in 15.9 sec
[---               9%                  ] 195 of 2000 complete in 16.5 sec
[---              10%                  ] 202 of 2000 complete in 17.1 sec
[---              10%                  ] 209 of 2000 complete in 17.6 sec
[----             10%                  ] 216 of 2000 complete in 18.1 sec
[----             11%                  ] 223 of 2000 complete in 18.7 sec
[----             11%                  ] 230 of 2000 complete in 19.2 sec
[----             11%                  ] 237 of 2000 complete in 19.8 sec
[----             12%                  ] 244 of 2000 complete in 20.3 sec
[----             12%                  ] 251 of 2000 complete in 20.8 sec
[----             12%                  ] 258 of 2000 complete in 21.4 sec
[-----            13%                  ] 265 of 2000 complete in 21.9 sec
[-----            13%                  ] 272 of 2000 complete in 22.5 sec
[-----            13%                  ] 279 of 2000 complete in 23.0 sec
[-----            14%                  ] 286 of 2000 complete in 23.5 sec
[-----            14%                  ] 293 of 2000 complete in 24.1 sec
[-----            15%                  ] 300 of 2000 complete in 24.6 sec
[-----            15%                  ] 307 of 2000 complete in 25.2 sec
[-----            15%                  ] 314 of 2000 complete in 25.7 sec
[------           16%                  ] 321 of 2000 complete in 26.2 sec
[------           16%                  ] 328 of 2000 complete in 26.8 sec
[------           16%                  ] 335 of 2000 complete in 27.3 sec
[------           17%                  ] 342 of 2000 complete in 27.9 sec
[------           17%                  ] 349 of 2000 complete in 28.4 sec
[------           17%                  ] 356 of 2000 complete in 29.0 sec
[------           18%                  ] 363 of 2000 complete in 29.5 sec
[-------          18%                  ] 370 of 2000 complete in 30.1 sec
[-------          18%                  ] 377 of 2000 complete in 30.6 sec
[-------          19%                  ] 384 of 2000 complete in 31.2 sec
[-------          19%                  ] 391 of 2000 complete in 31.7 sec
[-------          19%                  ] 398 of 2000 complete in 32.3 sec
[-------          20%                  ] 405 of 2000 complete in 32.8 sec
[-------          20%                  ] 412 of 2000 complete in 33.4 sec
[-------          20%                  ] 419 of 2000 complete in 33.9 sec
[--------         21%                  ] 426 of 2000 complete in 34.4 sec
[--------         21%                  ] 433 of 2000 complete in 35.0 sec
[--------         22%                  ] 440 of 2000 complete in 35.5 sec
[--------         22%                  ] 447 of 2000 complete in 36.1 sec
[--------         22%                  ] 454 of 2000 complete in 36.6 sec
[--------         23%                  ] 461 of 2000 complete in 37.2 sec
[--------         23%                  ] 468 of 2000 complete in 37.7 sec
[---------        23%                  ] 475 of 2000 complete in 38.3 sec
[---------        24%                  ] 482 of 2000 complete in 38.8 sec
[---------        24%                  ] 489 of 2000 complete in 39.3 sec
[---------        24%                  ] 496 of 2000 complete in 39.9 sec
[---------        25%                  ] 503 of 2000 complete in 40.4 sec
[---------        25%                  ] 510 of 2000 complete in 41.0 sec
[---------        25%                  ] 517 of 2000 complete in 41.5 sec
[---------        26%                  ] 524 of 2000 complete in 42.0 sec
[----------       26%                  ] 531 of 2000 complete in 42.6 sec
[----------       26%                  ] 538 of 2000 complete in 43.1 sec
[----------       27%                  ] 545 of 2000 complete in 43.7 sec
[----------       27%                  ] 552 of 2000 complete in 44.2 sec
[----------       27%                  ] 559 of 2000 complete in 44.8 sec
[----------       28%                  ] 566 of 2000 complete in 45.3 sec
[----------       28%                  ] 573 of 2000 complete in 45.8 sec
[-----------      29%                  ] 580 of 2000 complete in 46.4 sec
[-----------      29%                  ] 587 of 2000 complete in 46.9 sec
[-----------      29%                  ] 594 of 2000 complete in 47.5 sec
[-----------      30%                  ] 601 of 2000 complete in 48.0 sec
[-----------      30%                  ] 608 of 2000 complete in 48.6 sec
[-----------      30%                  ] 615 of 2000 complete in 49.1 sec
[-----------      31%                  ] 622 of 2000 complete in 49.6 sec
[-----------      31%                  ] 629 of 2000 complete in 50.2 sec
[------------     31%                  ] 636 of 2000 complete in 50.7 sec
[------------     32%                  ] 643 of 2000 complete in 51.3 sec
[------------     32%                  ] 650 of 2000 complete in 51.8 sec
[------------     32%                  ] 657 of 2000 complete in 52.4 sec
[------------     33%                  ] 664 of 2000 complete in 52.9 sec
[------------     33%                  ] 671 of 2000 complete in 53.5 sec
[------------     33%                  ] 678 of 2000 complete in 54.0 sec
[-------------    34%                  ] 685 of 2000 complete in 54.5 sec
[-------------    34%                  ] 692 of 2000 complete in 55.1 sec
[-------------    34%                  ] 699 of 2000 complete in 55.6 sec
[-------------    35%                  ] 706 of 2000 complete in 56.2 sec
[-------------    35%                  ] 713 of 2000 complete in 56.7 sec
[-------------    36%                  ] 720 of 2000 complete in 57.3 sec
[-------------    36%                  ] 727 of 2000 complete in 57.8 sec
[-------------    36%                  ] 734 of 2000 complete in 58.4 sec
[--------------   37%                  ] 741 of 2000 complete in 58.9 sec
[--------------   37%                  ] 748 of 2000 complete in 59.4 sec
[--------------   37%                  ] 755 of 2000 complete in 60.0 sec
[--------------   38%                  ] 762 of 2000 complete in 60.5 sec
[--------------   38%                  ] 769 of 2000 complete in 61.1 sec
[--------------   38%                  ] 776 of 2000 complete in 61.6 sec
[--------------   39%                  ] 783 of 2000 complete in 62.1 sec
[---------------  39%                  ] 790 of 2000 complete in 62.7 sec
[---------------  39%                  ] 797 of 2000 complete in 63.2 sec
[---------------  40%                  ] 804 of 2000 complete in 63.7 sec
[---------------  40%                  ] 811 of 2000 complete in 64.3 sec
[---------------  40%                  ] 818 of 2000 complete in 64.8 sec
[---------------  41%                  ] 825 of 2000 complete in 65.3 sec
[---------------  41%                  ] 832 of 2000 complete in 65.8 sec
[---------------  41%                  ] 839 of 2000 complete in 66.4 sec
[---------------- 42%                  ] 846 of 2000 complete in 66.9 sec
[---------------- 42%                  ] 853 of 2000 complete in 67.5 sec
[---------------- 43%                  ] 860 of 2000 complete in 68.0 sec
[---------------- 43%                  ] 867 of 2000 complete in 68.5 sec
[---------------- 43%                  ] 874 of 2000 complete in 69.1 sec
[---------------- 44%                  ] 881 of 2000 complete in 69.6 sec
[-----            14%                  ] 298 of 2000 complete in 24.1 sec
[-----            15%                  ] 305 of 2000 complete in 24.6 sec
[-----            15%                  ] 312 of 2000 complete in 25.2 sec
[------           15%                  ] 319 of 2000 complete in 25.7 sec
[------           16%                  ] 326 of 2000 complete in 26.2 sec
[------           16%                  ] 333 of 2000 complete in 26.8 sec
[------           17%                  ] 340 of 2000 complete in 27.3 sec
[------           17%                  ] 347 of 2000 complete in 27.8 sec
[------           17%                  ] 354 of 2000 complete in 28.3 sec
[------           18%                  ] 361 of 2000 complete in 28.9 sec
[------           18%                  ] 368 of 2000 complete in 29.4 sec
[-------          18%                  ] 375 of 2000 complete in 30.0 sec
[-------          19%                  ] 382 of 2000 complete in 30.5 sec
[-------          19%                  ] 389 of 2000 complete in 31.0 sec
[-------          19%                  ] 396 of 2000 complete in 31.6 sec
[-------          20%                  ] 403 of 2000 complete in 32.1 sec
[-------          20%                  ] 410 of 2000 complete in 32.7 sec
[-------          20%                  ] 417 of 2000 complete in 33.2 sec
[--------         21%                  ] 424 of 2000 complete in 33.8 sec
[--------         21%                  ] 431 of 2000 complete in 34.3 sec
[--------         21%                  ] 438 of 2000 complete in 34.9 sec
[--------         22%                  ] 445 of 2000 complete in 35.4 sec
[--------         22%                  ] 452 of 2000 complete in 35.9 sec
[--------         22%                  ] 459 of 2000 complete in 36.5 sec
[--------         23%                  ] 466 of 2000 complete in 37.0 sec
[--------         23%                  ] 473 of 2000 complete in 37.5 sec
[---------        24%                  ] 480 of 2000 complete in 38.1 sec
[---------        24%                  ] 487 of 2000 complete in 38.6 sec
[---------        24%                  ] 494 of 2000 complete in 39.1 sec
[---------        25%                  ] 501 of 2000 complete in 39.7 sec
[---------        25%                  ] 508 of 2000 complete in 40.2 sec
[---------        25%                  ] 515 of 2000 complete in 40.8 sec
[---------        26%                  ] 522 of 2000 complete in 41.3 sec
[----------       26%                  ] 529 of 2000 complete in 41.8 sec
[----------       26%                  ] 536 of 2000 complete in 42.3 sec
[----------       27%                  ] 543 of 2000 complete in 42.9 sec
[----------       27%                  ] 550 of 2000 complete in 43.4 sec
[----------       27%                  ] 557 of 2000 complete in 44.0 sec
[----------       28%                  ] 564 of 2000 complete in 44.5 sec
[----------       28%                  ] 571 of 2000 complete in 45.0 sec
[----------       28%                  ] 578 of 2000 complete in 45.6 sec
[-----------      29%                  ] 585 of 2000 complete in 46.1 sec
[-----------      29%                  ] 592 of 2000 complete in 46.6 sec
[-----------      29%                  ] 599 of 2000 complete in 47.2 sec
[-----------      30%                  ] 606 of 2000 complete in 47.7 sec
[-----------      30%                  ] 613 of 2000 complete in 48.2 sec
[-----------      31%                  ] 620 of 2000 complete in 48.8 sec
[-----------      31%                  ] 627 of 2000 complete in 49.3 sec
[------------     31%                  ] 634 of 2000 complete in 49.8 sec
[------------     32%                  ] 641 of 2000 complete in 50.4 sec
[------------     32%                  ] 648 of 2000 complete in 50.9 sec
[------------     32%                  ] 655 of 2000 complete in 51.4 sec
[------------     33%                  ] 662 of 2000 complete in 51.9 sec
[------------     33%                  ] 669 of 2000 complete in 52.5 sec
[------------     33%                  ] 676 of 2000 complete in 53.0 sec
[------------     34%                  ] 683 of 2000 complete in 53.6 sec
[-------------    34%                  ] 690 of 2000 complete in 54.1 sec
[-------------    34%                  ] 697 of 2000 complete in 54.6 sec
[-------------    35%                  ] 704 of 2000 complete in 55.2 sec
[-------------    35%                  ] 711 of 2000 complete in 55.7 sec
[-------------    35%                  ] 718 of 2000 complete in 56.2 sec
[-------------    36%                  ] 725 of 2000 complete in 56.8 sec
[-------------    36%                  ] 732 of 2000 complete in 57.3 sec
[--------------   36%                  ] 739 of 2000 complete in 57.8 sec
[--------------   37%                  ] 746 of 2000 complete in 58.3 sec
[--------------   37%                  ] 753 of 2000 complete in 58.9 sec
[--------------   38%                  ] 760 of 2000 complete in 59.4 sec
[--------------   38%                  ] 767 of 2000 complete in 60.0 sec
[--------------   38%                  ] 774 of 2000 complete in 60.5 sec
[--------------   39%                  ] 781 of 2000 complete in 61.0 sec
[--------------   39%                  ] 788 of 2000 complete in 61.6 sec
[---------------  39%                  ] 795 of 2000 complete in 62.1 sec
[---------------  40%                  ] 802 of 2000 complete in 62.6 sec
[---------------  40%                  ] 809 of 2000 complete in 63.1 sec
[---------------  40%                  ] 816 of 2000 complete in 63.7 sec
[---------------  41%                  ] 823 of 2000 complete in 64.2 sec
[---------------  41%                  ] 830 of 2000 complete in 64.7 sec
[---------------  41%                  ] 837 of 2000 complete in 65.3 sec
[---------------- 42%                  ] 844 of 2000 complete in 65.8 sec
[---------------- 42%                  ] 851 of 2000 complete in 66.3 sec
[---------------- 42%                  ] 858 of 2000 complete in 66.8 sec
[---------------- 43%                  ] 865 of 2000 complete in 67.4 sec
[---------------- 43%                  ] 872 of 2000 complete in 67.9 sec
[---------------- 43%                  ] 879 of 2000 complete in 68.4 sec
[---------------- 44%                  ] 886 of 2000 complete in 69.0 sec
[---------------- 44%                  ] 893 of 2000 complete in 69.5 sec
[-----------------45%                  ] 900 of 2000 complete in 70.1 sec
[-----------------45%                  ] 907 of 2000 complete in 70.6 sec
[-----------------45%                  ] 914 of 2000 complete in 71.1 sec
[-----------------46%                  ] 921 of 2000 complete in 71.7 sec
[-----------------46%                  ] 928 of 2000 complete in 72.2 sec
[-----------------46%                  ] 935 of 2000 complete in 72.7 sec
[-----------------47%                  ] 942 of 2000 complete in 73.3 sec
[-----------------47%                  ] 949 of 2000 complete in 73.8 sec
[-----------------47%                  ] 956 of 2000 complete in 74.3 sec
[-----------------48%                  ] 963 of 2000 complete in 74.9 sec
[-----------------48%                  ] 970 of 2000 complete in 75.4 sec
[-----------------48%                  ] 977 of 2000 complete in 75.9 sec
[-----------------49%                  ] 984 of 2000 complete in 76.4 sec
[-----------------49%                  ] 991 of 2000 complete in 77.0 sec
[-----------------49%                  ] 998 of 2000 complete in 77.5 sec
[-----------------50%                  ] 1005 of 2000 complete in 78.0 sec
[-----------------50%                  ] 1012 of 2000 complete in 78.6 sec
[-----------------50%                  ] 1019 of 2000 complete in 79.1 sec
[-----------------51%                  ] 1026 of 2000 complete in 79.7 sec
[-----------------51%                  ] 1033 of 2000 complete in 80.2 sec
[-----------------52%                  ] 1040 of 2000 complete in 80.7 sec
[-----------------52%                  ] 1047 of 2000 complete in 81.3 sec
[-----------------52%                  ] 1054 of 2000 complete in 81.8 sec
[-----------------53%                  ] 1061 of 2000 complete in 82.3 sec

[------           18%                  ] 366 of 2000 complete in 29.0 sec
[-------          18%                  ] 373 of 2000 complete in 29.5 sec
[-------          19%                  ] 380 of 2000 complete in 30.1 sec
[-------          19%                  ] 387 of 2000 complete in 30.6 sec
[-------          19%                  ] 394 of 2000 complete in 31.2 sec
[-------          20%                  ] 401 of 2000 complete in 31.7 sec
[-------          20%                  ] 408 of 2000 complete in 32.2 sec
[-------          20%                  ] 415 of 2000 complete in 32.8 sec
[--------         21%                  ] 422 of 2000 complete in 33.3 sec
[--------         21%                  ] 429 of 2000 complete in 33.8 sec
[--------         21%                  ] 436 of 2000 complete in 34.3 sec
[--------         22%                  ] 443 of 2000 complete in 34.9 sec
[--------         22%                  ] 450 of 2000 complete in 35.4 sec
[--------         22%                  ] 457 of 2000 complete in 35.9 sec
[--------         23%                  ] 464 of 2000 complete in 36.4 sec
[--------         23%                  ] 471 of 2000 complete in 36.9 sec
[---------        23%                  ] 478 of 2000 complete in 37.5 sec
[---------        24%                  ] 485 of 2000 complete in 38.0 sec
[---------        24%                  ] 492 of 2000 complete in 38.5 sec
[---------        24%                  ] 499 of 2000 complete in 39.1 sec
[---------        25%                  ] 506 of 2000 complete in 39.6 sec
[---------        25%                  ] 513 of 2000 complete in 40.1 sec
[---------        26%                  ] 520 of 2000 complete in 40.7 sec
[----------       26%                  ] 527 of 2000 complete in 41.2 sec
[----------       26%                  ] 534 of 2000 complete in 41.7 sec
[----------       27%                  ] 541 of 2000 complete in 42.2 sec
[----------       27%                  ] 548 of 2000 complete in 42.8 sec
[----------       27%                  ] 555 of 2000 complete in 43.3 sec
[----------       28%                  ] 562 of 2000 complete in 43.8 sec
[----------       28%                  ] 569 of 2000 complete in 44.3 sec
[----------       28%                  ] 576 of 2000 complete in 44.9 sec
[-----------      29%                  ] 583 of 2000 complete in 45.4 sec
[-----------      29%                  ] 590 of 2000 complete in 46.0 sec
[-----------      29%                  ] 597 of 2000 complete in 46.5 sec
[-----------      30%                  ] 604 of 2000 complete in 47.0 sec
[-----------      30%                  ] 611 of 2000 complete in 47.5 sec
[-----------      30%                  ] 618 of 2000 complete in 48.1 sec
[-----------      31%                  ] 625 of 2000 complete in 48.6 sec
[------------     31%                  ] 632 of 2000 complete in 49.1 sec
[------------     31%                  ] 639 of 2000 complete in 49.6 sec
[------------     32%                  ] 646 of 2000 complete in 50.2 sec
[------------     32%                  ] 653 of 2000 complete in 50.7 sec
[------------     33%                  ] 660 of 2000 complete in 51.2 sec
[------------     33%                  ] 667 of 2000 complete in 51.7 sec
[------------     33%                  ] 674 of 2000 complete in 52.3 sec
[------------     34%                  ] 681 of 2000 complete in 52.8 sec
[-------------    34%                  ] 688 of 2000 complete in 53.3 sec
[-------------    34%                  ] 695 of 2000 complete in 53.9 sec
[-------------    35%                  ] 702 of 2000 complete in 54.4 sec
[-------------    35%                  ] 709 of 2000 complete in 54.9 sec
[-------------    35%                  ] 716 of 2000 complete in 55.4 sec
[-------------    36%                  ] 723 of 2000 complete in 56.0 sec
[-------------    36%                  ] 730 of 2000 complete in 56.5 sec
[--------------   36%                  ] 737 of 2000 complete in 57.0 sec
[--------------   37%                  ] 744 of 2000 complete in 57.6 sec
[--------------   37%                  ] 751 of 2000 complete in 58.1 sec
[--------------   37%                  ] 758 of 2000 complete in 58.6 sec
[--------------   38%                  ] 765 of 2000 complete in 59.1 sec
[--------------   38%                  ] 772 of 2000 complete in 59.7 sec
[--------------   38%                  ] 779 of 2000 complete in 60.2 sec
[--------------   39%                  ] 786 of 2000 complete in 60.7 sec
[---------------  39%                  ] 793 of 2000 complete in 61.2 sec
[---------------  40%                  ] 800 of 2000 complete in 61.7 sec
[---------------  40%                  ] 807 of 2000 complete in 62.3 sec
[---------------  40%                  ] 814 of 2000 complete in 62.8 sec
[---------------  41%                  ] 821 of 2000 complete in 63.3 sec
[---------------  41%                  ] 828 of 2000 complete in 63.9 sec
[---------------  41%                  ] 835 of 2000 complete in 64.4 sec
[---------------  42%                  ] 842 of 2000 complete in 65.0 sec
[---------------- 42%                  ] 849 of 2000 complete in 65.5 sec
[---------------- 42%                  ] 856 of 2000 complete in 66.0 sec
[---------------- 43%                  ] 863 of 2000 complete in 66.5 sec
[---------------- 43%                  ] 870 of 2000 complete in 67.1 sec
[---------------- 43%                  ] 877 of 2000 complete in 67.6 sec
[---------------- 44%                  ] 884 of 2000 complete in 68.1 sec
[---------------- 44%                  ] 891 of 2000 complete in 68.7 sec
[-----------------44%                  ] 898 of 2000 complete in 69.2 sec
[-----------------45%                  ] 905 of 2000 complete in 69.7 sec
[-----------------45%                  ] 912 of 2000 complete in 70.3 sec
[-----------------45%                  ] 919 of 2000 complete in 70.8 sec
[-----------------46%                  ] 926 of 2000 complete in 71.3 sec
[-----------------46%                  ] 933 of 2000 complete in 71.8 sec
[-----------------47%                  ] 940 of 2000 complete in 72.4 sec
[-----------------47%                  ] 947 of 2000 complete in 72.9 sec
[-----------------47%                  ] 954 of 2000 complete in 73.4 sec
[-----------------48%                  ] 961 of 2000 complete in 73.9 sec
[-----------------48%                  ] 968 of 2000 complete in 74.5 sec
[-----------------48%                  ] 975 of 2000 complete in 75.0 sec
[-----------------49%                  ] 982 of 2000 complete in 75.5 sec
[-----------------49%                  ] 989 of 2000 complete in 76.1 sec
[-----------------49%                  ] 996 of 2000 complete in 76.6 sec
[-----------------50%                  ] 1003 of 2000 complete in 77.1 sec
[-----------------50%                  ] 1010 of 2000 complete in 77.6 sec
[-----------------50%                  ] 1017 of 2000 complete in 78.2 sec
[-----------------51%                  ] 1024 of 2000 complete in 78.7 sec
[-----------------51%                  ] 1031 of 2000 complete in 79.2 sec
[-----------------51%                  ] 1038 of 2000 complete in 79.8 sec
[-----------------52%                  ] 1045 of 2000 complete in 80.3 sec
[-----------------52%                  ] 1052 of 2000 complete in 80.8 sec
[-----------------52%                  ] 1059 of 2000 complete in 81.3 sec
[-----------------53%                  ] 1066 of 2000 complete in 81.8 sec
[-----------------53%                  ] 1073 of 2000 complete in 82.4 sec
[-----------------54%                  ] 1080 of 2000 complete in 82.9 sec
[-----------------54%                  ] 1087 of 2000 complete in 83.4 sec
[-----------------54%                  ] 1094 of 2000 complete in 83.9 sec
[-----------------55%                  ] 1101 of 2000 complete in 84.5 sec
[-----------------55%-                 ] 1108 of 2000 complete in 85.0 sec
[-----------------55%-                 ] 1115 of 2000 complete in 85.5 sec
[-----------------56%-                 ] 1122 of 2000 complete in 86.1 sec
[-----------------56%-                 ] 1129 of 2000 complete in 86.6 sec
[-------          21%                  ] 420 of 2000 complete in 33.1 sec
[--------         21%                  ] 427 of 2000 complete in 33.7 sec
[--------         21%                  ] 434 of 2000 complete in 34.2 sec
[--------         22%                  ] 441 of 2000 complete in 34.7 sec
[--------         22%                  ] 448 of 2000 complete in 35.2 sec
[--------         22%                  ] 455 of 2000 complete in 35.7 sec
[--------         23%                  ] 462 of 2000 complete in 36.3 sec
[--------         23%                  ] 469 of 2000 complete in 36.8 sec
[---------        23%                  ] 476 of 2000 complete in 37.3 sec
[---------        24%                  ] 483 of 2000 complete in 37.9 sec
[---------        24%                  ] 490 of 2000 complete in 38.4 sec
[---------        24%                  ] 497 of 2000 complete in 38.9 sec
[---------        25%                  ] 504 of 2000 complete in 39.5 sec
[---------        25%                  ] 511 of 2000 complete in 40.0 sec
[---------        25%                  ] 518 of 2000 complete in 40.5 sec
[---------        26%                  ] 525 of 2000 complete in 41.1 sec
[----------       26%                  ] 532 of 2000 complete in 41.6 sec
[----------       26%                  ] 539 of 2000 complete in 42.1 sec
[----------       27%                  ] 546 of 2000 complete in 42.7 sec
[----------       27%                  ] 553 of 2000 complete in 43.2 sec
[----------       28%                  ] 560 of 2000 complete in 43.7 sec
[----------       28%                  ] 567 of 2000 complete in 44.2 sec
[----------       28%                  ] 574 of 2000 complete in 44.8 sec
[-----------      29%                  ] 581 of 2000 complete in 45.3 sec
[-----------      29%                  ] 588 of 2000 complete in 45.8 sec
[-----------      29%                  ] 595 of 2000 complete in 46.4 sec
[-----------      30%                  ] 602 of 2000 complete in 46.9 sec
[-----------      30%                  ] 609 of 2000 complete in 47.4 sec
[-----------      30%                  ] 616 of 2000 complete in 48.0 sec
[-----------      31%                  ] 623 of 2000 complete in 48.5 sec
[-----------      31%                  ] 630 of 2000 complete in 49.0 sec
[------------     31%                  ] 637 of 2000 complete in 49.5 sec
[------------     32%                  ] 644 of 2000 complete in 50.1 sec
[------------     32%                  ] 651 of 2000 complete in 50.6 sec
[------------     32%                  ] 658 of 2000 complete in 51.1 sec
[------------     33%                  ] 665 of 2000 complete in 51.7 sec
[------------     33%                  ] 672 of 2000 complete in 52.2 sec
[------------     33%                  ] 679 of 2000 complete in 52.7 sec
[-------------    34%                  ] 686 of 2000 complete in 53.2 sec
[-------------    34%                  ] 693 of 2000 complete in 53.8 sec
[-------------    35%                  ] 700 of 2000 complete in 54.3 sec
[-------------    35%                  ] 707 of 2000 complete in 54.8 sec
[-------------    35%                  ] 714 of 2000 complete in 55.4 sec
[-------------    36%                  ] 721 of 2000 complete in 55.9 sec
[-------------    36%                  ] 728 of 2000 complete in 56.4 sec
[-------------    36%                  ] 735 of 2000 complete in 57.0 sec
[--------------   37%                  ] 742 of 2000 complete in 57.5 sec
[--------------   37%                  ] 749 of 2000 complete in 58.0 sec
[--------------   37%                  ] 756 of 2000 complete in 58.5 sec
[--------------   38%                  ] 763 of 2000 complete in 59.1 sec
[--------------   38%                  ] 770 of 2000 complete in 59.6 sec
[--------------   38%                  ] 777 of 2000 complete in 60.1 sec
[--------------   39%                  ] 784 of 2000 complete in 60.6 sec
[---------------  39%                  ] 791 of 2000 complete in 61.1 sec
[---------------  39%                  ] 798 of 2000 complete in 61.7 sec
[---------------  40%                  ] 805 of 2000 complete in 62.2 sec
[---------------  40%                  ] 812 of 2000 complete in 62.7 sec
[---------------  40%                  ] 819 of 2000 complete in 63.3 sec
[---------------  41%                  ] 826 of 2000 complete in 63.8 sec
[---------------  41%                  ] 833 of 2000 complete in 64.3 sec
[---------------  42%                  ] 840 of 2000 complete in 64.8 sec
[---------------- 42%                  ] 847 of 2000 complete in 65.3 sec
[---------------- 42%                  ] 854 of 2000 complete in 65.9 sec
[---------------- 43%                  ] 861 of 2000 complete in 66.4 sec
[---------------- 43%                  ] 868 of 2000 complete in 66.9 sec
[---------------- 43%                  ] 875 of 2000 complete in 67.5 sec
[---------------- 44%                  ] 882 of 2000 complete in 68.0 sec
[---------------- 44%                  ] 889 of 2000 complete in 68.5 sec
[-----------------44%                  ] 896 of 2000 complete in 69.1 sec
[-----------------45%                  ] 903 of 2000 complete in 69.6 sec
[-----------------45%                  ] 910 of 2000 complete in 70.2 sec
[-----------------45%                  ] 917 of 2000 complete in 70.7 sec
[-----------------46%                  ] 924 of 2000 complete in 71.2 sec
[-----------------46%                  ] 931 of 2000 complete in 71.8 sec
[-----------------46%                  ] 938 of 2000 complete in 72.3 sec
[-----------------47%                  ] 945 of 2000 complete in 72.8 sec
[-----------------47%                  ] 952 of 2000 complete in 73.4 sec
[-----------------47%                  ] 959 of 2000 complete in 73.9 sec
[-----------------48%                  ] 966 of 2000 complete in 74.4 sec
[-----------------48%                  ] 973 of 2000 complete in 74.9 sec
[-----------------49%                  ] 980 of 2000 complete in 75.5 sec
[-----------------49%                  ] 987 of 2000 complete in 76.0 sec
[-----------------49%                  ] 994 of 2000 complete in 76.5 sec
[-----------------50%                  ] 1001 of 2000 complete in 77.0 sec
[-----------------50%                  ] 1008 of 2000 complete in 77.6 sec
[-----------------50%                  ] 1015 of 2000 complete in 78.1 sec
[-----------------51%                  ] 1022 of 2000 complete in 78.6 sec
[-----------------51%                  ] 1029 of 2000 complete in 79.2 sec
[-----------------51%                  ] 1036 of 2000 complete in 79.7 sec
[-----------------52%                  ] 1043 of 2000 complete in 80.2 sec
[-----------------52%                  ] 1050 of 2000 complete in 80.7 sec
[-----------------52%                  ] 1057 of 2000 complete in 81.3 sec
[-----------------53%                  ] 1064 of 2000 complete in 81.8 sec
[-----------------53%                  ] 1071 of 2000 complete in 82.3 sec
[-----------------53%                  ] 1078 of 2000 complete in 82.9 sec
[-----------------54%                  ] 1085 of 2000 complete in 83.4 sec
[-----------------54%                  ] 1092 of 2000 complete in 83.9 sec
[-----------------54%                  ] 1099 of 2000 complete in 84.4 sec
[-----------------55%-                 ] 1106 of 2000 complete in 85.0 sec
[-----------------55%-                 ] 1113 of 2000 complete in 85.5 sec
[-----------------56%-                 ] 1120 of 2000 complete in 86.0 sec
[-----------------56%-                 ] 1127 of 2000 complete in 86.5 sec
[-----------------56%-                 ] 1134 of 2000 complete in 87.1 sec
[-----------------57%-                 ] 1141 of 2000 complete in 87.6 sec
[-----------------57%-                 ] 1148 of 2000 complete in 88.1 sec
[-----------------57%-                 ] 1155 of 2000 complete in 88.6 sec
[-----------------58%--                ] 1162 of 2000 complete in 89.2 sec
[-----------------58%--                ] 1169 of 2000 complete in 89.7 sec
[-----------------58%--                ] 1176 of 2000 complete in 90.2 sec
[-----------------59%--                ] 1183 of 2000 complete in 90.8 sec

[---------------- 44%                  ] 888 of 2000 complete in 70.2 sec
[-----------------44%                  ] 895 of 2000 complete in 70.7 sec
[-----------------45%                  ] 902 of 2000 complete in 71.2 sec
[-----------------45%                  ] 909 of 2000 complete in 71.8 sec
[-----------------45%                  ] 916 of 2000 complete in 72.3 sec
[-----------------46%                  ] 923 of 2000 complete in 72.9 sec
[-----------------46%                  ] 930 of 2000 complete in 73.4 sec
[-----------------46%                  ] 937 of 2000 complete in 73.9 sec
[-----------------47%                  ] 944 of 2000 complete in 74.5 sec
[-----------------47%                  ] 951 of 2000 complete in 75.1 sec
[-----------------47%                  ] 958 of 2000 complete in 75.6 sec
[-----------------48%                  ] 965 of 2000 complete in 76.1 sec
[-----------------48%                  ] 972 of 2000 complete in 76.7 sec
[-----------------48%                  ] 979 of 2000 complete in 77.2 sec
[-----------------49%                  ] 986 of 2000 complete in 77.7 sec
[-----------------49%                  ] 993 of 2000 complete in 78.3 sec
[-----------------50%                  ] 1000 of 2000 complete in 78.8 sec
[-----------------50%                  ] 1007 of 2000 complete in 79.3 sec
[-----------------50%                  ] 1014 of 2000 complete in 79.9 sec
[-----------------51%                  ] 1021 of 2000 complete in 80.4 sec
[-----------------51%                  ] 1028 of 2000 complete in 80.9 sec
[-----------------51%                  ] 1035 of 2000 complete in 81.5 sec
[-----------------52%                  ] 1042 of 2000 complete in 82.0 sec
[-----------------52%                  ] 1049 of 2000 complete in 82.6 sec
[-----------------52%                  ] 1056 of 2000 complete in 83.1 sec
[-----------------53%                  ] 1063 of 2000 complete in 83.6 sec
[-----------------53%                  ] 1070 of 2000 complete in 84.2 sec
[-----------------53%                  ] 1077 of 2000 complete in 84.7 sec
[-----------------54%                  ] 1084 of 2000 complete in 85.3 sec
[-----------------54%                  ] 1091 of 2000 complete in 85.8 sec
[-----------------54%                  ] 1098 of 2000 complete in 86.3 sec
[-----------------55%                  ] 1105 of 2000 complete in 86.9 sec
[-----------------55%-                 ] 1112 of 2000 complete in 87.4 sec
[-----------------55%-                 ] 1119 of 2000 complete in 87.9 sec
[-----------------56%-                 ] 1126 of 2000 complete in 88.5 sec
[-----------------56%-                 ] 1133 of 2000 complete in 89.0 sec
[-----------------57%-                 ] 1140 of 2000 complete in 89.5 sec
[-----------------57%-                 ] 1147 of 2000 complete in 90.1 sec
[-----------------57%-                 ] 1154 of 2000 complete in 90.6 sec
[-----------------58%--                ] 1161 of 2000 complete in 91.2 sec
[-----------------58%--                ] 1168 of 2000 complete in 91.7 sec
[-----------------58%--                ] 1175 of 2000 complete in 92.2 sec
[-----------------59%--                ] 1182 of 2000 complete in 92.8 sec
[-----------------59%--                ] 1189 of 2000 complete in 93.4 sec
[-----------------59%--                ] 1196 of 2000 complete in 93.9 sec
[-----------------60%--                ] 1203 of 2000 complete in 94.4 sec
[-----------------60%--                ] 1210 of 2000 complete in 95.0 sec
[-----------------60%---               ] 1217 of 2000 complete in 95.5 sec
[-----------------61%---               ] 1224 of 2000 complete in 96.0 sec
[-----------------61%---               ] 1231 of 2000 complete in 96.6 sec
[-----------------61%---               ] 1238 of 2000 complete in 97.1 sec
[-----------------62%---               ] 1245 of 2000 complete in 97.7 sec
[-----------------62%---               ] 1252 of 2000 complete in 98.2 sec
[-----------------62%---               ] 1258 of 2000 complete in 98.7 sec
[-----------------63%----              ] 1265 of 2000 complete in 99.3 sec
[-----------------63%----              ] 1272 of 2000 complete in 99.8 sec
[-----------------63%----              ] 1279 of 2000 complete in 100.4 sec
[-----------------64%----              ] 1286 of 2000 complete in 100.9 sec
[-----------------64%----              ] 1293 of 2000 complete in 101.5 sec
[-----------------65%----              ] 1300 of 2000 complete in 102.0 sec
[-----------------65%----              ] 1307 of 2000 complete in 102.5 sec
[-----------------65%----              ] 1314 of 2000 complete in 103.1 sec
[-----------------66%-----             ] 1321 of 2000 complete in 103.6 sec
[-----------------66%-----             ] 1328 of 2000 complete in 104.1 sec
[-----------------66%-----             ] 1335 of 2000 complete in 104.7 sec
[-----------------67%-----             ] 1342 of 2000 complete in 105.2 sec
[-----------------67%-----             ] 1349 of 2000 complete in 105.8 sec
[-----------------67%-----             ] 1356 of 2000 complete in 106.3 sec
[-----------------68%-----             ] 1363 of 2000 complete in 106.8 sec
[-----------------68%------            ] 1370 of 2000 complete in 107.4 sec
[-----------------68%------            ] 1377 of 2000 complete in 107.9 sec
[-----------------69%------            ] 1384 of 2000 complete in 108.5 sec
[-----------------69%------            ] 1391 of 2000 complete in 109.0 sec
[-----------------69%------            ] 1398 of 2000 complete in 109.6 sec
[-----------------70%------            ] 1405 of 2000 complete in 110.1 sec
[-----------------70%------            ] 1412 of 2000 complete in 110.7 sec
[-----------------70%------            ] 1419 of 2000 complete in 111.2 sec
[-----------------71%-------           ] 1426 of 2000 complete in 111.7 sec
[-----------------71%-------           ] 1433 of 2000 complete in 112.3 sec
[-----------------72%-------           ] 1440 of 2000 complete in 112.8 sec
[-----------------72%-------           ] 1447 of 2000 complete in 113.3 sec
[-----------------72%-------           ] 1454 of 2000 complete in 113.9 sec
[-----------------73%-------           ] 1461 of 2000 complete in 114.4 sec
[-----------------73%-------           ] 1468 of 2000 complete in 115.0 sec
[-----------------73%--------          ] 1475 of 2000 complete in 115.5 sec
[-----------------74%--------          ] 1482 of 2000 complete in 116.1 sec
[-----------------74%--------          ] 1489 of 2000 complete in 116.6 sec
[-----------------74%--------          ] 1496 of 2000 complete in 117.2 sec
[-----------------75%--------          ] 1503 of 2000 complete in 117.7 sec
[-----------------75%--------          ] 1510 of 2000 complete in 118.3 sec
[-----------------75%--------          ] 1517 of 2000 complete in 118.8 sec
[-----------------76%--------          ] 1524 of 2000 complete in 119.4 sec
[-----------------76%---------         ] 1531 of 2000 complete in 119.9 sec
[-----------------76%---------         ] 1538 of 2000 complete in 120.5 sec
[-----------------77%---------         ] 1545 of 2000 complete in 121.0 sec
[-----------------77%---------         ] 1552 of 2000 complete in 121.6 sec
[-----------------77%---------         ] 1559 of 2000 complete in 122.2 sec
[-----------------78%---------         ] 1566 of 2000 complete in 122.7 sec
[-----------------78%---------         ] 1573 of 2000 complete in 123.3 sec
[-----------------79%----------        ] 1580 of 2000 complete in 123.9 sec
[-----------------79%----------        ] 1587 of 2000 complete in 124.4 sec
[-----------------79%----------        ] 1594 of 2000 complete in 125.0 sec
[-----------------80%----------        ] 1601 of 2000 complete in 125.5 sec
[-----------------80%----------        ] 1608 of 2000 complete in 126.1 sec
[-----------------80%----------        ] 1615 of 2000 complete in 126.6 sec
[-----------------81%----------        ] 1622 of 2000 complete in 127.2 sec
[-----------------81%----------        ] 1629 of 2000 complete in 127.7 sec
[-----------------81%-----------       ] 1636 of 2000 complete in 128.3 sec
[-----------------53%                  ] 1068 of 2000 complete in 82.9 sec
[-----------------53%                  ] 1075 of 2000 complete in 83.4 sec
[-----------------54%                  ] 1082 of 2000 complete in 83.9 sec
[-----------------54%                  ] 1089 of 2000 complete in 84.5 sec
[-----------------54%                  ] 1096 of 2000 complete in 85.0 sec
[-----------------55%                  ] 1103 of 2000 complete in 85.5 sec
[-----------------55%-                 ] 1110 of 2000 complete in 86.1 sec
[-----------------55%-                 ] 1117 of 2000 complete in 86.6 sec
[-----------------56%-                 ] 1124 of 2000 complete in 87.1 sec
[-----------------56%-                 ] 1131 of 2000 complete in 87.7 sec
[-----------------56%-                 ] 1138 of 2000 complete in 88.2 sec
[-----------------57%-                 ] 1145 of 2000 complete in 88.7 sec
[-----------------57%-                 ] 1152 of 2000 complete in 89.2 sec
[-----------------57%--                ] 1159 of 2000 complete in 89.8 sec
[-----------------58%--                ] 1166 of 2000 complete in 90.3 sec
[-----------------58%--                ] 1173 of 2000 complete in 90.9 sec
[-----------------59%--                ] 1180 of 2000 complete in 91.4 sec
[-----------------59%--                ] 1187 of 2000 complete in 91.9 sec
[-----------------59%--                ] 1194 of 2000 complete in 92.5 sec
[-----------------60%--                ] 1201 of 2000 complete in 93.0 sec
[-----------------60%--                ] 1208 of 2000 complete in 93.5 sec
[-----------------60%---               ] 1215 of 2000 complete in 94.1 sec
[-----------------61%---               ] 1222 of 2000 complete in 94.6 sec
[-----------------61%---               ] 1229 of 2000 complete in 95.1 sec
[-----------------61%---               ] 1236 of 2000 complete in 95.6 sec
[-----------------62%---               ] 1243 of 2000 complete in 96.2 sec
[-----------------62%---               ] 1250 of 2000 complete in 96.7 sec
[-----------------62%---               ] 1257 of 2000 complete in 97.2 sec
[-----------------63%----              ] 1264 of 2000 complete in 97.7 sec
[-----------------63%----              ] 1271 of 2000 complete in 98.3 sec
[-----------------63%----              ] 1278 of 2000 complete in 98.8 sec
[-----------------64%----              ] 1285 of 2000 complete in 99.4 sec
[-----------------64%----              ] 1292 of 2000 complete in 99.9 sec
[-----------------64%----              ] 1299 of 2000 complete in 100.4 sec
[-----------------65%----              ] 1306 of 2000 complete in 101.0 sec
[-----------------65%----              ] 1313 of 2000 complete in 101.5 sec
[-----------------66%-----             ] 1320 of 2000 complete in 102.1 sec
[-----------------66%-----             ] 1327 of 2000 complete in 102.6 sec
[-----------------66%-----             ] 1334 of 2000 complete in 103.1 sec
[-----------------67%-----             ] 1341 of 2000 complete in 103.7 sec
[-----------------67%-----             ] 1348 of 2000 complete in 104.2 sec
[-----------------67%-----             ] 1355 of 2000 complete in 104.8 sec
[-----------------68%-----             ] 1362 of 2000 complete in 105.3 sec
[-----------------68%------            ] 1369 of 2000 complete in 105.8 sec
[-----------------68%------            ] 1376 of 2000 complete in 106.4 sec
[-----------------69%------            ] 1383 of 2000 complete in 106.9 sec
[-----------------69%------            ] 1390 of 2000 complete in 107.5 sec
[-----------------69%------            ] 1397 of 2000 complete in 108.0 sec
[-----------------70%------            ] 1404 of 2000 complete in 108.5 sec
[-----------------70%------            ] 1411 of 2000 complete in 109.1 sec
[-----------------70%------            ] 1418 of 2000 complete in 109.6 sec
[-----------------71%-------           ] 1425 of 2000 complete in 110.2 sec
[-----------------71%-------           ] 1432 of 2000 complete in 110.7 sec
[-----------------71%-------           ] 1439 of 2000 complete in 111.2 sec
[-----------------72%-------           ] 1446 of 2000 complete in 111.8 sec
[-----------------72%-------           ] 1453 of 2000 complete in 112.3 sec
[-----------------73%-------           ] 1460 of 2000 complete in 112.8 sec
[-----------------73%-------           ] 1467 of 2000 complete in 113.4 sec
[-----------------73%--------          ] 1474 of 2000 complete in 113.9 sec
[-----------------74%--------          ] 1481 of 2000 complete in 114.4 sec
[-----------------74%--------          ] 1488 of 2000 complete in 115.0 sec
[-----------------74%--------          ] 1495 of 2000 complete in 115.5 sec
[-----------------75%--------          ] 1502 of 2000 complete in 116.1 sec
[-----------------75%--------          ] 1509 of 2000 complete in 116.6 sec
[-----------------75%--------          ] 1516 of 2000 complete in 117.2 sec
[-----------------76%--------          ] 1523 of 2000 complete in 117.7 sec
[-----------------76%---------         ] 1530 of 2000 complete in 118.3 sec
[-----------------76%---------         ] 1537 of 2000 complete in 118.8 sec
[-----------------77%---------         ] 1544 of 2000 complete in 119.4 sec
[-----------------77%---------         ] 1551 of 2000 complete in 119.9 sec
[-----------------77%---------         ] 1558 of 2000 complete in 120.5 sec
[-----------------78%---------         ] 1565 of 2000 complete in 121.0 sec
[-----------------78%---------         ] 1572 of 2000 complete in 121.6 sec
[-----------------78%----------        ] 1579 of 2000 complete in 122.1 sec
[-----------------79%----------        ] 1586 of 2000 complete in 122.7 sec
[-----------------79%----------        ] 1593 of 2000 complete in 123.2 sec
[-----------------80%----------        ] 1600 of 2000 complete in 123.8 sec
[-----------------80%----------        ] 1607 of 2000 complete in 124.3 sec
[-----------------80%----------        ] 1614 of 2000 complete in 124.9 sec
[-----------------81%----------        ] 1621 of 2000 complete in 125.4 sec
[-----------------81%----------        ] 1628 of 2000 complete in 126.0 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 126.6 sec
[-----------------82%-----------       ] 1642 of 2000 complete in 127.1 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 127.7 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 128.2 sec
[-----------------83%-----------       ] 1663 of 2000 complete in 128.8 sec
[-----------------83%-----------       ] 1670 of 2000 complete in 129.3 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 129.8 sec
[-----------------84%-----------       ] 1682 of 2000 complete in 130.4 sec
[-----------------84%------------      ] 1688 of 2000 complete in 130.9 sec
[-----------------84%------------      ] 1695 of 2000 complete in 131.4 sec
[-----------------85%------------      ] 1702 of 2000 complete in 132.0 sec
[-----------------85%------------      ] 1709 of 2000 complete in 132.5 sec
[-----------------85%------------      ] 1716 of 2000 complete in 133.1 sec
[-----------------86%------------      ] 1723 of 2000 complete in 133.6 sec
[-----------------86%------------      ] 1730 of 2000 complete in 134.2 sec
[-----------------86%-------------     ] 1737 of 2000 complete in 134.7 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 135.3 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 135.8 sec
[-----------------87%-------------     ] 1758 of 2000 complete in 136.4 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 136.9 sec
[-----------------88%-------------     ] 1772 of 2000 complete in 137.5 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 138.0 sec
[-----------------89%-------------     ] 1786 of 2000 complete in 138.5 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 139.1 sec
[-----------------90%--------------    ] 1800 of 2000 complete in 139.6 sec
[-----------------90%--------------    ] 1807 of 2000 complete in 140.2 sec
[-----------------90%--------------    ] 1814 of 2000 complete in 140.7 sec

[-----------------56%-                 ] 1136 of 2000 complete in 87.1 sec
[-----------------57%-                 ] 1143 of 2000 complete in 87.6 sec
[-----------------57%-                 ] 1150 of 2000 complete in 88.2 sec
[-----------------57%-                 ] 1157 of 2000 complete in 88.7 sec
[-----------------58%--                ] 1164 of 2000 complete in 89.2 sec
[-----------------58%--                ] 1171 of 2000 complete in 89.7 sec
[-----------------58%--                ] 1178 of 2000 complete in 90.3 sec
[-----------------59%--                ] 1185 of 2000 complete in 90.8 sec
[-----------------59%--                ] 1192 of 2000 complete in 91.3 sec
[-----------------59%--                ] 1199 of 2000 complete in 91.9 sec
[-----------------60%--                ] 1206 of 2000 complete in 92.4 sec
[-----------------60%---               ] 1213 of 2000 complete in 92.9 sec
[-----------------61%---               ] 1220 of 2000 complete in 93.4 sec
[-----------------61%---               ] 1227 of 2000 complete in 94.0 sec
[-----------------61%---               ] 1234 of 2000 complete in 94.5 sec
[-----------------62%---               ] 1241 of 2000 complete in 95.0 sec
[-----------------62%---               ] 1248 of 2000 complete in 95.5 sec
[-----------------62%---               ] 1255 of 2000 complete in 96.1 sec
[-----------------63%---               ] 1262 of 2000 complete in 96.6 sec
[-----------------63%----              ] 1269 of 2000 complete in 97.1 sec
[-----------------63%----              ] 1276 of 2000 complete in 97.6 sec
[-----------------64%----              ] 1283 of 2000 complete in 98.2 sec
[-----------------64%----              ] 1290 of 2000 complete in 98.7 sec
[-----------------64%----              ] 1297 of 2000 complete in 99.3 sec
[-----------------65%----              ] 1304 of 2000 complete in 99.9 sec
[-----------------65%----              ] 1311 of 2000 complete in 100.4 sec
[-----------------65%-----             ] 1318 of 2000 complete in 100.9 sec
[-----------------66%-----             ] 1325 of 2000 complete in 101.4 sec
[-----------------66%-----             ] 1332 of 2000 complete in 102.0 sec
[-----------------66%-----             ] 1339 of 2000 complete in 102.5 sec
[-----------------67%-----             ] 1346 of 2000 complete in 103.1 sec
[-----------------67%-----             ] 1353 of 2000 complete in 103.6 sec
[-----------------68%-----             ] 1360 of 2000 complete in 104.1 sec
[-----------------68%-----             ] 1367 of 2000 complete in 104.6 sec
[-----------------68%------            ] 1374 of 2000 complete in 105.2 sec
[-----------------69%------            ] 1381 of 2000 complete in 105.7 sec
[-----------------69%------            ] 1388 of 2000 complete in 106.2 sec
[-----------------69%------            ] 1395 of 2000 complete in 106.7 sec
[-----------------70%------            ] 1402 of 2000 complete in 107.3 sec
[-----------------70%------            ] 1409 of 2000 complete in 107.8 sec
[-----------------70%------            ] 1416 of 2000 complete in 108.3 sec
[-----------------71%-------           ] 1423 of 2000 complete in 108.8 sec
[-----------------71%-------           ] 1430 of 2000 complete in 109.3 sec
[-----------------71%-------           ] 1437 of 2000 complete in 109.9 sec
[-----------------72%-------           ] 1444 of 2000 complete in 110.4 sec
[-----------------72%-------           ] 1451 of 2000 complete in 110.9 sec
[-----------------72%-------           ] 1458 of 2000 complete in 111.5 sec
[-----------------73%-------           ] 1465 of 2000 complete in 112.0 sec
[-----------------73%-------           ] 1472 of 2000 complete in 112.5 sec
[-----------------73%--------          ] 1479 of 2000 complete in 113.0 sec
[-----------------74%--------          ] 1486 of 2000 complete in 113.5 sec
[-----------------74%--------          ] 1493 of 2000 complete in 114.1 sec
[-----------------75%--------          ] 1500 of 2000 complete in 114.6 sec
[-----------------75%--------          ] 1507 of 2000 complete in 115.1 sec
[-----------------75%--------          ] 1514 of 2000 complete in 115.7 sec
[-----------------76%--------          ] 1521 of 2000 complete in 116.2 sec
[-----------------76%---------         ] 1528 of 2000 complete in 116.8 sec
[-----------------76%---------         ] 1535 of 2000 complete in 117.3 sec
[-----------------77%---------         ] 1542 of 2000 complete in 117.9 sec
[-----------------77%---------         ] 1549 of 2000 complete in 118.4 sec
[-----------------77%---------         ] 1556 of 2000 complete in 119.0 sec
[-----------------78%---------         ] 1563 of 2000 complete in 119.5 sec
[-----------------78%---------         ] 1570 of 2000 complete in 120.0 sec
[-----------------78%---------         ] 1577 of 2000 complete in 120.6 sec
[-----------------79%----------        ] 1584 of 2000 complete in 121.1 sec
[-----------------79%----------        ] 1591 of 2000 complete in 121.7 sec
[-----------------79%----------        ] 1598 of 2000 complete in 122.2 sec
[-----------------80%----------        ] 1605 of 2000 complete in 122.8 sec
[-----------------80%----------        ] 1612 of 2000 complete in 123.3 sec
[-----------------80%----------        ] 1619 of 2000 complete in 123.9 sec
[-----------------81%----------        ] 1626 of 2000 complete in 124.4 sec
[-----------------81%-----------       ] 1633 of 2000 complete in 124.9 sec
[-----------------82%-----------       ] 1640 of 2000 complete in 125.5 sec
[-----------------82%-----------       ] 1647 of 2000 complete in 126.0 sec
[-----------------82%-----------       ] 1654 of 2000 complete in 126.6 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 127.1 sec
[-----------------83%-----------       ] 1668 of 2000 complete in 127.6 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 128.2 sec
[-----------------84%-----------       ] 1682 of 2000 complete in 128.7 sec
[-----------------84%------------      ] 1689 of 2000 complete in 129.3 sec
[-----------------84%------------      ] 1695 of 2000 complete in 129.8 sec
[-----------------85%------------      ] 1701 of 2000 complete in 130.3 sec
[-----------------85%------------      ] 1707 of 2000 complete in 130.9 sec
[-----------------85%------------      ] 1714 of 2000 complete in 131.4 sec
[-----------------86%------------      ] 1721 of 2000 complete in 132.0 sec
[-----------------86%------------      ] 1728 of 2000 complete in 132.5 sec
[-----------------86%------------      ] 1735 of 2000 complete in 133.1 sec
[-----------------87%-------------     ] 1742 of 2000 complete in 133.6 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 134.2 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 134.7 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 135.2 sec
[-----------------88%-------------     ] 1770 of 2000 complete in 135.8 sec
[-----------------88%-------------     ] 1777 of 2000 complete in 136.3 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 136.9 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 137.4 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 137.9 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 138.5 sec
[-----------------90%--------------    ] 1812 of 2000 complete in 139.0 sec
[-----------------90%--------------    ] 1819 of 2000 complete in 139.6 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 140.1 sec
[-----------------91%--------------    ] 1833 of 2000 complete in 140.7 sec
[-----------------92%--------------    ] 1840 of 2000 complete in 141.2 sec
[-----------------92%---------------   ] 1847 of 2000 complete in 141.8 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 142.3 sec
[-----------------93%---------------   ] 1861 of 2000 complete in 142.8 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 143.4 sec
[-----------------93%---------------   ] 1875 of 2000 complete in 143.9 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 144.4 sec
[-----------------59%--                ] 1190 of 2000 complete in 91.3 sec
[-----------------59%--                ] 1197 of 2000 complete in 91.9 sec
[-----------------60%--                ] 1204 of 2000 complete in 92.4 sec
[-----------------60%---               ] 1211 of 2000 complete in 92.9 sec
[-----------------60%---               ] 1218 of 2000 complete in 93.4 sec
[-----------------61%---               ] 1225 of 2000 complete in 94.0 sec
[-----------------61%---               ] 1232 of 2000 complete in 94.5 sec
[-----------------61%---               ] 1239 of 2000 complete in 95.0 sec
[-----------------62%---               ] 1246 of 2000 complete in 95.6 sec
[-----------------62%---               ] 1253 of 2000 complete in 96.1 sec
[-----------------63%---               ] 1260 of 2000 complete in 96.6 sec
[-----------------63%----              ] 1267 of 2000 complete in 97.2 sec
[-----------------63%----              ] 1274 of 2000 complete in 97.7 sec
[-----------------64%----              ] 1281 of 2000 complete in 98.2 sec
[-----------------64%----              ] 1288 of 2000 complete in 98.8 sec
[-----------------64%----              ] 1295 of 2000 complete in 99.3 sec
[-----------------65%----              ] 1302 of 2000 complete in 99.9 sec
[-----------------65%----              ] 1309 of 2000 complete in 100.4 sec
[-----------------65%-----             ] 1316 of 2000 complete in 100.9 sec
[-----------------66%-----             ] 1323 of 2000 complete in 101.5 sec
[-----------------66%-----             ] 1330 of 2000 complete in 102.0 sec
[-----------------66%-----             ] 1337 of 2000 complete in 102.5 sec
[-----------------67%-----             ] 1344 of 2000 complete in 103.0 sec
[-----------------67%-----             ] 1351 of 2000 complete in 103.6 sec
[-----------------67%-----             ] 1358 of 2000 complete in 104.1 sec
[-----------------68%-----             ] 1365 of 2000 complete in 104.6 sec
[-----------------68%------            ] 1372 of 2000 complete in 105.2 sec
[-----------------68%------            ] 1379 of 2000 complete in 105.7 sec
[-----------------69%------            ] 1386 of 2000 complete in 106.2 sec
[-----------------69%------            ] 1393 of 2000 complete in 106.7 sec
[-----------------70%------            ] 1400 of 2000 complete in 107.3 sec
[-----------------70%------            ] 1407 of 2000 complete in 107.8 sec
[-----------------70%------            ] 1414 of 2000 complete in 108.3 sec
[-----------------71%------            ] 1421 of 2000 complete in 108.8 sec
[-----------------71%-------           ] 1428 of 2000 complete in 109.4 sec
[-----------------71%-------           ] 1435 of 2000 complete in 109.9 sec
[-----------------72%-------           ] 1442 of 2000 complete in 110.4 sec
[-----------------72%-------           ] 1449 of 2000 complete in 110.9 sec
[-----------------72%-------           ] 1456 of 2000 complete in 111.5 sec
[-----------------73%-------           ] 1463 of 2000 complete in 112.0 sec
[-----------------73%-------           ] 1470 of 2000 complete in 112.5 sec
[-----------------73%--------          ] 1477 of 2000 complete in 113.1 sec
[-----------------74%--------          ] 1484 of 2000 complete in 113.6 sec
[-----------------74%--------          ] 1491 of 2000 complete in 114.1 sec
[-----------------74%--------          ] 1498 of 2000 complete in 114.7 sec
[-----------------75%--------          ] 1505 of 2000 complete in 115.2 sec
[-----------------75%--------          ] 1512 of 2000 complete in 115.8 sec
[-----------------75%--------          ] 1519 of 2000 complete in 116.3 sec
[-----------------76%--------          ] 1526 of 2000 complete in 116.9 sec
[-----------------76%---------         ] 1533 of 2000 complete in 117.4 sec
[-----------------77%---------         ] 1540 of 2000 complete in 118.0 sec
[-----------------77%---------         ] 1547 of 2000 complete in 118.5 sec
[-----------------77%---------         ] 1554 of 2000 complete in 119.0 sec
[-----------------78%---------         ] 1561 of 2000 complete in 119.6 sec
[-----------------78%---------         ] 1568 of 2000 complete in 120.1 sec
[-----------------78%---------         ] 1575 of 2000 complete in 120.7 sec
[-----------------79%----------        ] 1582 of 2000 complete in 121.2 sec
[-----------------79%----------        ] 1589 of 2000 complete in 121.8 sec
[-----------------79%----------        ] 1596 of 2000 complete in 122.3 sec
[-----------------80%----------        ] 1603 of 2000 complete in 122.9 sec
[-----------------80%----------        ] 1610 of 2000 complete in 123.4 sec
[-----------------80%----------        ] 1617 of 2000 complete in 124.0 sec
[-----------------81%----------        ] 1624 of 2000 complete in 124.5 sec
[-----------------81%----------        ] 1631 of 2000 complete in 125.1 sec
[-----------------81%-----------       ] 1638 of 2000 complete in 125.6 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 126.1 sec
[-----------------82%-----------       ] 1652 of 2000 complete in 126.7 sec
[-----------------82%-----------       ] 1659 of 2000 complete in 127.2 sec
[-----------------83%-----------       ] 1666 of 2000 complete in 127.8 sec
[-----------------83%-----------       ] 1673 of 2000 complete in 128.3 sec
[-----------------84%-----------       ] 1680 of 2000 complete in 128.9 sec
[-----------------84%------------      ] 1687 of 2000 complete in 129.4 sec
[-----------------84%------------      ] 1693 of 2000 complete in 130.0 sec
[-----------------84%------------      ] 1699 of 2000 complete in 130.5 sec
[-----------------85%------------      ] 1705 of 2000 complete in 131.0 sec
[-----------------85%------------      ] 1712 of 2000 complete in 131.6 sec
[-----------------85%------------      ] 1719 of 2000 complete in 132.1 sec
[-----------------86%------------      ] 1726 of 2000 complete in 132.7 sec
[-----------------86%------------      ] 1733 of 2000 complete in 133.2 sec
[-----------------87%-------------     ] 1740 of 2000 complete in 133.8 sec
[-----------------87%-------------     ] 1747 of 2000 complete in 134.3 sec
[-----------------87%-------------     ] 1754 of 2000 complete in 134.9 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 135.4 sec
[-----------------88%-------------     ] 1768 of 2000 complete in 135.9 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 136.5 sec
[-----------------89%-------------     ] 1782 of 2000 complete in 137.0 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 137.6 sec
[-----------------89%--------------    ] 1796 of 2000 complete in 138.1 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 138.6 sec
[-----------------90%--------------    ] 1810 of 2000 complete in 139.2 sec
[-----------------90%--------------    ] 1817 of 2000 complete in 139.7 sec
[-----------------91%--------------    ] 1824 of 2000 complete in 140.3 sec
[-----------------91%--------------    ] 1831 of 2000 complete in 140.8 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 141.3 sec
[-----------------92%---------------   ] 1845 of 2000 complete in 141.9 sec
[-----------------92%---------------   ] 1852 of 2000 complete in 142.4 sec
[-----------------92%---------------   ] 1859 of 2000 complete in 143.0 sec
[-----------------93%---------------   ] 1866 of 2000 complete in 143.5 sec
[-----------------93%---------------   ] 1873 of 2000 complete in 144.0 sec
[-----------------94%---------------   ] 1880 of 2000 complete in 144.6 sec
[-----------------94%---------------   ] 1887 of 2000 complete in 145.1 sec
[-----------------94%---------------   ] 1894 of 2000 complete in 145.7 sec
[-----------------95%----------------  ] 1901 of 2000 complete in 146.2 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 146.8 sec
[-----------------95%----------------  ] 1915 of 2000 complete in 147.3 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 147.8 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 148.4 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 148.9 sec

hddm sampling elpased time:  169.826 s
Start converting to InferenceData...

In [17]:
az.summary(hddm_id_m1_choice_diff_idata)

,mean,sd,hdi_3%,hdi_97%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
a,1.543,0.049,1.451,1.637,0.002,0.001,813.0,2169.0,1.01
a_std,0.287,0.043,0.213,0.369,0.002,0.002,306.0,1392.0,1.01
a_subj.7304,1.562,0.085,1.400,1.714,0.004,0.003,397.0,881.0,1.01
a_subj.7305,1.759,0.088,1.589,1.916,0.003,0.002,656.0,1087.0,1.01
a_subj.7306,1.501,0.075,1.363,1.649,0.003,0.002,637.0,1026.0,1.00
...,...,...,...,...,...,...,...,...,...
z_subj.7342,0.296,0.017,0.266,0.330,0.000,0.000,1690.0,2905.0,1.00
z_subj.7343,0.288,0.018,0.253,0.322,0.000,0.000,1374.0,2505.0,1.01
z_subj.7344,0.318,0.017,0.286,0.352,0.000,0.000,2069.0,2940.0,1.00
z_subj.7345,0.328,0.018,0.292,0.361,0.000,0.000,1714.0,2728.0,1.00
z_subj.73370,0.323,0.024,0.278,0.370,0.001,0.001,874.0,1351.0,1.00

In [18]:
hddm_id_m1_choice_stats = hddm_id_m1_choice_diff.gen_stats()
hddm_id_m1_choice_stats[hddm_id_m1_choice_stats.index.isin(['a', 'v(Self.1)', 'v(Other.1)', 
                                                'v(Self.0)', 'v(Other.0)','z'])]

,mean,std,2.5q,25q,50q,75q,97.5q,mc err
a,1.542898,0.04914,1.451828,1.509728,1.540336,1.573351,1.64476,0.001505
v(Other.0),3.384387,0.142205,3.10401,3.288584,3.38614,3.481219,3.662592,0.002641
v(Self.1),3.871663,0.143146,3.589999,3.775724,3.867112,3.96823,4.148788,0.002662
z,0.334843,0.007113,0.320837,0.330044,0.334637,0.339519,0.349895,0.000388

In [20]:
#HDDMStimCoding
#choice coding + v flip + dc
#accuracy coding + z flip
#hddmStim_v_flip
data['response'] = data['choice']

# stimCoding v flip + dc
hddmStim_vflip_dc_m1 = hddm.HDDMStimCoding(
    data,
    stim_col='stim',
    split_param='v',
    drift_criterion=True,
    depends_on={'v':['stim'],'dc': ['id']},
    bias =True,
    include=['v', 'a', 't', 'z'],
)

hddmStim_vflip_dc_m1_idata = hddmStim_vflip_dc_m1.sample(2000, burn=500, chains=4, return_infdata=True, dbname = 'hddmStim_vflip_dc_m1.db', db = 'pickle')
hddmStim_vflip_dc_m1.save('hddmStim_vflip_dc_m1.hddm')

No model attribute --> setting up standard HDDM
Set model to ddm

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

[-----------------82%-----------       ] 1643 of 2000 complete in 128.9 sec
[-----------------82%-----------       ] 1650 of 2000 complete in 129.4 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 129.9 sec
[-----------------83%-----------       ] 1662 of 2000 complete in 130.5 sec
[-----------------83%-----------       ] 1668 of 2000 complete in 131.0 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 131.6 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 132.1 sec
[-----------------84%------------      ] 1688 of 2000 complete in 132.6 sec
[-----------------84%------------      ] 1695 of 2000 complete in 133.2 sec
[-----------------85%------------      ] 1702 of 2000 complete in 133.7 sec
[-----------------85%------------      ] 1709 of 2000 complete in 134.3 sec
[-----------------85%------------      ] 1716 of 2000 complete in 134.8 sec
[-----------------86%------------      ] 1723 of 2000 complete in 135.4 sec
[-----------------86%------------      ] 1730 of 2000 complete in 135.9 sec
[-----------------86%-------------     ] 1737 of 2000 complete in 136.5 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 137.1 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 137.6 sec
[-----------------87%-------------     ] 1758 of 2000 complete in 138.2 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 138.7 sec
[-----------------88%-------------     ] 1772 of 2000 complete in 139.3 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 139.8 sec
[-----------------89%-------------     ] 1786 of 2000 complete in 140.3 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 140.9 sec
[-----------------90%--------------    ] 1800 of 2000 complete in 141.4 sec
[-----------------90%--------------    ] 1807 of 2000 complete in 142.0 sec
[-----------------90%--------------    ] 1814 of 2000 complete in 142.5 sec
[-----------------91%--------------    ] 1821 of 2000 complete in 143.1 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 143.7 sec
[-----------------91%--------------    ] 1835 of 2000 complete in 144.2 sec
[-----------------92%--------------    ] 1842 of 2000 complete in 144.8 sec
[-----------------92%---------------   ] 1849 of 2000 complete in 145.3 sec
[-----------------92%---------------   ] 1856 of 2000 complete in 145.9 sec
[-----------------93%---------------   ] 1863 of 2000 complete in 146.4 sec
[-----------------93%---------------   ] 1870 of 2000 complete in 147.0 sec
[-----------------93%---------------   ] 1877 of 2000 complete in 147.5 sec
[-----------------94%---------------   ] 1884 of 2000 complete in 148.1 sec
[-----------------94%---------------   ] 1891 of 2000 complete in 148.6 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 149.2 sec
[-----------------95%----------------  ] 1905 of 2000 complete in 149.7 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 150.3 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 150.8 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 151.4 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 151.9 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 152.4 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 153.0 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 153.6 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 154.1 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 154.7 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 155.2 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 155.7 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 156.2 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 156.8 sec
[-----------------100%-----------------] 2000 of 2000 complete in 157.2 sec
hddm sampling elpased time:  157.38 s
[                  0%                  ] 6 of 2000 complete in 0.5 sec
[                  0%                  ] 12 of 2000 complete in 1.1 sec
[                  0%                  ] 18 of 2000 complete in 1.7 sec
[                  1%                  ] 24 of 2000 complete in 2.3 sec
[                  1%                  ] 29 of 2000 complete in 2.8 sec
[                  1%                  ] 35 of 2000 complete in 3.3 sec
[                  2%                  ] 41 of 2000 complete in 4.0 sec
[                  2%                  ] 47 of 2000 complete in 4.5 sec
[-                 2%                  ] 53 of 2000 complete in 5.1 sec
[-                 2%                  ] 59 of 2000 complete in 5.7 sec
[-                 3%                  ] 65 of 2000 complete in 6.3 sec
[-                 3%                  ] 71 of 2000 complete in 6.9 sec
[-                 3%                  ] 77 of 2000 complete in 7.4 sec
[-                 4%                  ] 83 of 2000 complete in 8.0 sec
[-                 4%                  ] 89 of 2000 complete in 8.6 sec
[-                 4%                  ] 95 of 2000 complete in 9.2 sec
[-                 5%                  ] 101 of 2000 complete in 9.8 sec
[--                5%                  ] 106 of 2000 complete in 10.3 sec
[--                5%                  ] 111 of 2000 complete in 10.9 sec
[--                5%                  ] 116 of 2000 complete in 11.4 sec
[--                6%                  ] 122 of 2000 complete in 12.0 sec
[--                6%                  ] 127 of 2000 complete in 12.6 sec
[--                6%                  ] 132 of 2000 complete in 13.2 sec
[--                6%                  ] 137 of 2000 complete in 13.7 sec
[--                7%                  ] 142 of 2000 complete in 14.3 sec
[--                7%                  ] 148 of 2000 complete in 14.9 sec
[--                7%                  ] 154 of 2000 complete in 15.4 sec
[---               8%                  ] 160 of 2000 complete in 16.0 sec
[---               8%                  ] 166 of 2000 complete in 16.6 sec
[---               8%                  ] 172 of 2000 complete in 17.2 sec
[---               8%                  ] 177 of 2000 complete in 17.7 sec
[---               9%                  ] 183 of 2000 complete in 18.3 sec
[---               9%                  ] 189 of 2000 complete in 18.9 sec
[---               9%                  ] 194 of 2000 complete in 19.4 sec
[---              10%                  ] 200 of 2000 complete in 20.0 sec
[---              10%                  ] 205 of 2000 complete in 20.5 sec
[---              10%                  ] 210 of 2000 complete in 21.1 sec
[----             10%                  ] 216 of 2000 complete in 21.7 sec
[----             11%                  ] 221 of 2000 complete in 22.2 sec
[----             11%                  ] 227 of 2000 complete in 22.8 sec
[----             11%                  ] 233 of 2000 complete in 23.4 sec
[----             11%                  ] 238 of 2000 complete in 23.9 sec
[----             12%                  ] 244 of 2000 complete in 24.5 sec
[----             12%                  ] 249 of 2000 complete in 25.0 sec
[----             12%                  ] 254 of 2000 complete in 25.5 sec
[----             13%                  ] 260 of 2000 complete in 26.1 sec
[-----            13%                  ] 265 of 2000 complete in 26.6 sec
[-----            13%                  ] 270 of 2000 complete in 27.2 sec
[-----            13%                  ] 275 of 2000 complete in 27.7 sec
[-----            14%                  ] 280 of 2000 complete in 28.2 sec
[-----            14%                  ] 285 of 2000 complete in 28.7 sec
[-----            14%                  ] 290 of 2000 complete in 29.2 sec
[-----            14%                  ] 296 of 2000 complete in 29.8 sec
[-----            15%                  ] 302 of 2000 complete in 30.4 sec
[-----            15%                  ] 307 of 2000 complete in 31.0 sec
[-----            15%                  ] 313 of 2000 complete in 31.5 sec
[-----------------91%--------------    ] 1821 of 2000 complete in 141.2 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 141.8 sec
[-----------------91%--------------    ] 1835 of 2000 complete in 142.4 sec
[-----------------92%--------------    ] 1842 of 2000 complete in 142.9 sec
[-----------------92%---------------   ] 1849 of 2000 complete in 143.4 sec
[-----------------92%---------------   ] 1856 of 2000 complete in 144.0 sec
[-----------------93%---------------   ] 1863 of 2000 complete in 144.5 sec
[-----------------93%---------------   ] 1870 of 2000 complete in 145.1 sec
[-----------------93%---------------   ] 1877 of 2000 complete in 145.6 sec
[-----------------94%---------------   ] 1884 of 2000 complete in 146.2 sec
[-----------------94%---------------   ] 1891 of 2000 complete in 146.7 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 147.3 sec
[-----------------95%----------------  ] 1905 of 2000 complete in 147.8 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 148.4 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 148.9 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 149.4 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 150.0 sec
[-----------------97%----------------  ] 1940 of 2000 complete in 150.5 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 151.1 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 151.7 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 152.2 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 152.8 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 153.3 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 153.9 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 154.4 sec
[-----------------99%----------------- ] 1996 of 2000 complete in 154.9 sec
[-----------------100%-----------------] 2000 of 2000 complete in 155.3 sec
hddm sampling elpased time:  155.474 s
[                  0%                  ] 7 of 2000 complete in 0.6 sec
[                  0%                  ] 13 of 2000 complete in 1.2 sec
[                  0%                  ] 19 of 2000 complete in 1.7 sec
[                  1%                  ] 25 of 2000 complete in 2.3 sec
[                  1%                  ] 31 of 2000 complete in 2.9 sec
[                  1%                  ] 37 of 2000 complete in 3.5 sec
[                  2%                  ] 43 of 2000 complete in 4.1 sec
[                  2%                  ] 49 of 2000 complete in 4.6 sec
[-                 2%                  ] 55 of 2000 complete in 5.2 sec
[-                 3%                  ] 61 of 2000 complete in 5.8 sec
[-                 3%                  ] 67 of 2000 complete in 6.4 sec
[-                 3%                  ] 73 of 2000 complete in 7.0 sec
[-                 3%                  ] 79 of 2000 complete in 7.5 sec
[-                 4%                  ] 85 of 2000 complete in 8.1 sec
[-                 4%                  ] 91 of 2000 complete in 8.7 sec
[-                 4%                  ] 97 of 2000 complete in 9.2 sec
[-                 5%                  ] 103 of 2000 complete in 9.8 sec
[--                5%                  ] 108 of 2000 complete in 10.4 sec
[--                5%                  ] 113 of 2000 complete in 10.9 sec
[--                5%                  ] 118 of 2000 complete in 11.4 sec
[--                6%                  ] 124 of 2000 complete in 12.0 sec
[--                6%                  ] 129 of 2000 complete in 12.6 sec
[--                6%                  ] 134 of 2000 complete in 13.1 sec
[--                6%                  ] 139 of 2000 complete in 13.7 sec
[--                7%                  ] 144 of 2000 complete in 14.2 sec
[--                7%                  ] 150 of 2000 complete in 14.8 sec
[--                7%                  ] 156 of 2000 complete in 15.3 sec
[---               8%                  ] 162 of 2000 complete in 15.9 sec
[---               8%                  ] 168 of 2000 complete in 16.5 sec
[---               8%                  ] 174 of 2000 complete in 17.1 sec
[---               8%                  ] 179 of 2000 complete in 17.6 sec
[---               9%                  ] 185 of 2000 complete in 18.2 sec
[---               9%                  ] 190 of 2000 complete in 18.7 sec
[---               9%                  ] 196 of 2000 complete in 19.3 sec
[---              10%                  ] 202 of 2000 complete in 19.8 sec
[---              10%                  ] 208 of 2000 complete in 20.4 sec
[----             10%                  ] 213 of 2000 complete in 21.0 sec
[----             10%                  ] 219 of 2000 complete in 21.6 sec
[----             11%                  ] 225 of 2000 complete in 22.2 sec
[----             11%                  ] 231 of 2000 complete in 22.8 sec
[----             11%                  ] 237 of 2000 complete in 23.3 sec
[----             12%                  ] 242 of 2000 complete in 23.9 sec
[----             12%                  ] 248 of 2000 complete in 24.5 sec
[----             12%                  ] 254 of 2000 complete in 25.0 sec
[----             13%                  ] 260 of 2000 complete in 25.6 sec
[-----            13%                  ] 266 of 2000 complete in 26.2 sec
[-----            13%                  ] 272 of 2000 complete in 26.8 sec
[-----            13%                  ] 277 of 2000 complete in 27.4 sec
[-----            14%                  ] 282 of 2000 complete in 27.9 sec
[-----            14%                  ] 287 of 2000 complete in 28.4 sec
[-----            14%                  ] 293 of 2000 complete in 29.0 sec
[-----            14%                  ] 299 of 2000 complete in 29.6 sec
[-----            15%                  ] 305 of 2000 complete in 30.2 sec
[-----            15%                  ] 311 of 2000 complete in 30.8 sec
[------           15%                  ] 317 of 2000 complete in 31.3 sec
[------           16%                  ] 323 of 2000 complete in 31.9 sec
[------           16%                  ] 329 of 2000 complete in 32.5 sec
[------           16%                  ] 335 of 2000 complete in 33.1 sec
[------           17%                  ] 340 of 2000 complete in 33.6 sec
[------           17%                  ] 346 of 2000 complete in 34.2 sec
[------           17%                  ] 352 of 2000 complete in 34.8 sec
[------           17%                  ] 358 of 2000 complete in 35.4 sec
[------           18%                  ] 363 of 2000 complete in 35.9 sec
[-------          18%                  ] 369 of 2000 complete in 36.5 sec
[-------          18%                  ] 375 of 2000 complete in 37.0 sec
[-------          19%                  ] 381 of 2000 complete in 37.6 sec
[-------          19%                  ] 387 of 2000 complete in 38.2 sec
[-------          19%                  ] 393 of 2000 complete in 38.8 sec
[-------          19%                  ] 399 of 2000 complete in 39.4 sec
[-------          20%                  ] 405 of 2000 complete in 40.0 sec
[-------          20%                  ] 410 of 2000 complete in 40.5 sec
[-------          20%                  ] 416 of 2000 complete in 41.1 sec
[-------          21%                  ] 421 of 2000 complete in 41.6 sec
[--------         21%                  ] 427 of 2000 complete in 42.2 sec
[--------         21%                  ] 433 of 2000 complete in 42.8 sec
[--------         21%                  ] 439 of 2000 complete in 43.3 sec
[--------         22%                  ] 445 of 2000 complete in 43.9 sec
[--------         22%                  ] 451 of 2000 complete in 44.5 sec
[--------         22%                  ] 457 of 2000 complete in 45.1 sec
[--------         23%                  ] 463 of 2000 complete in 45.7 sec
[--------         23%                  ] 469 of 2000 complete in 46.2 sec
[---------        23%                  ] 475 of 2000 complete in 46.8 sec

[-----------------94%---------------   ] 1889 of 2000 complete in 145.0 sec
[-----------------94%----------------  ] 1896 of 2000 complete in 145.5 sec
[-----------------95%----------------  ] 1903 of 2000 complete in 146.1 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 146.6 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 147.1 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 147.7 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 148.2 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 148.7 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 149.3 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 149.8 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 150.3 sec
[-----------------98%----------------- ] 1966 of 2000 complete in 150.9 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 151.4 sec
[-----------------99%----------------- ] 1980 of 2000 complete in 152.0 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 152.5 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 153.1 sec
[-----------------100%-----------------] 2001 of 2000 complete in 153.6 sec
hddm sampling elpased time:  153.767 s
[                  0%                  ] 7 of 2000 complete in 0.6 sec
[                  0%                  ] 13 of 2000 complete in 1.2 sec
[                  0%                  ] 19 of 2000 complete in 1.7 sec
[                  1%                  ] 25 of 2000 complete in 2.3 sec
[                  1%                  ] 31 of 2000 complete in 2.9 sec
[                  1%                  ] 37 of 2000 complete in 3.4 sec
[                  2%                  ] 43 of 2000 complete in 4.0 sec
[                  2%                  ] 49 of 2000 complete in 4.6 sec
[-                 2%                  ] 55 of 2000 complete in 5.1 sec
[-                 3%                  ] 61 of 2000 complete in 5.7 sec
[-                 3%                  ] 67 of 2000 complete in 6.3 sec
[-                 3%                  ] 73 of 2000 complete in 6.9 sec
[-                 3%                  ] 79 of 2000 complete in 7.4 sec
[-                 4%                  ] 85 of 2000 complete in 8.0 sec
[-                 4%                  ] 91 of 2000 complete in 8.6 sec
[-                 4%                  ] 97 of 2000 complete in 9.1 sec
[-                 5%                  ] 103 of 2000 complete in 9.7 sec
[--                5%                  ] 109 of 2000 complete in 10.3 sec
[--                5%                  ] 114 of 2000 complete in 10.9 sec
[--                5%                  ] 119 of 2000 complete in 11.4 sec
[--                6%                  ] 125 of 2000 complete in 12.0 sec
[--                6%                  ] 130 of 2000 complete in 12.5 sec
[--                6%                  ] 135 of 2000 complete in 13.1 sec
[--                7%                  ] 140 of 2000 complete in 13.6 sec
[--                7%                  ] 145 of 2000 complete in 14.1 sec
[--                7%                  ] 151 of 2000 complete in 14.7 sec
[--                7%                  ] 157 of 2000 complete in 15.3 sec
[---               8%                  ] 163 of 2000 complete in 15.9 sec
[---               8%                  ] 169 of 2000 complete in 16.4 sec
[---               8%                  ] 175 of 2000 complete in 17.0 sec
[---               9%                  ] 180 of 2000 complete in 17.5 sec
[---               9%                  ] 186 of 2000 complete in 18.1 sec
[---               9%                  ] 192 of 2000 complete in 18.7 sec
[---               9%                  ] 198 of 2000 complete in 19.2 sec
[---              10%                  ] 204 of 2000 complete in 19.8 sec
[---              10%                  ] 210 of 2000 complete in 20.4 sec
[----             10%                  ] 215 of 2000 complete in 20.9 sec
[----             11%                  ] 220 of 2000 complete in 21.4 sec
[----             11%                  ] 226 of 2000 complete in 22.0 sec
[----             11%                  ] 231 of 2000 complete in 22.5 sec
[----             11%                  ] 237 of 2000 complete in 23.1 sec
[----             12%                  ] 243 of 2000 complete in 23.7 sec
[----             12%                  ] 249 of 2000 complete in 24.3 sec
[----             12%                  ] 255 of 2000 complete in 24.9 sec
[----             13%                  ] 261 of 2000 complete in 25.4 sec
[-----            13%                  ] 267 of 2000 complete in 26.0 sec
[-----            13%                  ] 273 of 2000 complete in 26.6 sec
[-----            13%                  ] 278 of 2000 complete in 27.1 sec
[-----            14%                  ] 283 of 2000 complete in 27.7 sec
[-----            14%                  ] 288 of 2000 complete in 28.2 sec
[-----            14%                  ] 294 of 2000 complete in 28.8 sec
[-----            15%                  ] 300 of 2000 complete in 29.3 sec
[-----            15%                  ] 306 of 2000 complete in 29.9 sec
[-----            15%                  ] 312 of 2000 complete in 30.5 sec
[------           15%                  ] 318 of 2000 complete in 31.1 sec
[------           16%                  ] 324 of 2000 complete in 31.7 sec
[------           16%                  ] 330 of 2000 complete in 32.2 sec
[------           16%                  ] 336 of 2000 complete in 32.8 sec
[------           17%                  ] 342 of 2000 complete in 33.4 sec
[------           17%                  ] 347 of 2000 complete in 33.9 sec
[------           17%                  ] 353 of 2000 complete in 34.5 sec
[------           17%                  ] 359 of 2000 complete in 35.1 sec
[------           18%                  ] 365 of 2000 complete in 35.6 sec
[-------          18%                  ] 370 of 2000 complete in 36.2 sec
[-------          18%                  ] 376 of 2000 complete in 36.7 sec
[-------          19%                  ] 382 of 2000 complete in 37.3 sec
[-------          19%                  ] 388 of 2000 complete in 37.9 sec
[-------          19%                  ] 394 of 2000 complete in 38.5 sec
[-------          20%                  ] 400 of 2000 complete in 39.0 sec
[-------          20%                  ] 406 of 2000 complete in 39.6 sec
[-------          20%                  ] 412 of 2000 complete in 40.2 sec
[-------          20%                  ] 417 of 2000 complete in 40.7 sec
[--------         21%                  ] 423 of 2000 complete in 41.3 sec
[--------         21%                  ] 429 of 2000 complete in 41.9 sec
[--------         21%                  ] 435 of 2000 complete in 42.4 sec
[--------         22%                  ] 441 of 2000 complete in 43.0 sec
[--------         22%                  ] 447 of 2000 complete in 43.6 sec
[--------         22%                  ] 453 of 2000 complete in 44.1 sec
[--------         22%                  ] 459 of 2000 complete in 44.7 sec
[--------         23%                  ] 465 of 2000 complete in 45.3 sec
[--------         23%                  ] 471 of 2000 complete in 45.9 sec
[---------        23%                  ] 477 of 2000 complete in 46.4 sec
[---------        24%                  ] 483 of 2000 complete in 47.0 sec
[---------        24%                  ] 489 of 2000 complete in 47.6 sec
[---------        24%                  ] 495 of 2000 complete in 48.1 sec
[---------        25%                  ] 501 of 2000 complete in 48.7 sec
[---------        25%                  ] 507 of 2000 complete in 49.3 sec
[---------        25%                  ] 513 of 2000 complete in 49.9 sec
[---------        25%                  ] 519 of 2000 complete in 50.4 sec
[---------        26%                  ] 525 of 2000 complete in 51.0 sec
[----------       26%                  ] 531 of 2000 complete in 51.6 sec
[----------       26%                  ] 537 of 2000 complete in 52.2 sec
[----------       27%                  ] 543 of 2000 complete in 52.7 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 149.5 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 150.0 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 150.6 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 151.1 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 151.7 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 152.2 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 152.7 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 153.3 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 153.8 sec
[-----------------100%-----------------] 2000 of 2000 complete in 154.0 sec
hddm sampling elpased time:  154.151 s
[                  0%                  ] 7 of 2000 complete in 0.6 sec
[                  0%                  ] 13 of 2000 complete in 1.1 sec
[                  0%                  ] 19 of 2000 complete in 1.7 sec
[                  1%                  ] 25 of 2000 complete in 2.3 sec
[                  1%                  ] 31 of 2000 complete in 2.9 sec
[                  1%                  ] 37 of 2000 complete in 3.5 sec
[                  2%                  ] 43 of 2000 complete in 4.0 sec
[                  2%                  ] 49 of 2000 complete in 4.6 sec
[-                 2%                  ] 55 of 2000 complete in 5.2 sec
[-                 3%                  ] 61 of 2000 complete in 5.8 sec
[-                 3%                  ] 67 of 2000 complete in 6.3 sec
[-                 3%                  ] 72 of 2000 complete in 6.8 sec
[-                 3%                  ] 78 of 2000 complete in 7.4 sec
[-                 4%                  ] 84 of 2000 complete in 8.0 sec
[-                 4%                  ] 90 of 2000 complete in 8.6 sec
[-                 4%                  ] 96 of 2000 complete in 9.2 sec
[-                 5%                  ] 102 of 2000 complete in 9.8 sec
[--                5%                  ] 107 of 2000 complete in 10.3 sec
[--                5%                  ] 112 of 2000 complete in 10.9 sec
[--                5%                  ] 117 of 2000 complete in 11.4 sec
[--                6%                  ] 123 of 2000 complete in 12.0 sec
[--                6%                  ] 128 of 2000 complete in 12.5 sec
[--                6%                  ] 133 of 2000 complete in 13.1 sec
[--                6%                  ] 138 of 2000 complete in 13.6 sec
[--                7%                  ] 143 of 2000 complete in 14.2 sec
[--                7%                  ] 149 of 2000 complete in 14.8 sec
[--                7%                  ] 154 of 2000 complete in 15.3 sec
[---               8%                  ] 160 of 2000 complete in 15.9 sec
[---               8%                  ] 166 of 2000 complete in 16.5 sec
[---               8%                  ] 171 of 2000 complete in 17.0 sec
[---               8%                  ] 176 of 2000 complete in 17.5 sec
[---               9%                  ] 182 of 2000 complete in 18.1 sec
[---               9%                  ] 187 of 2000 complete in 18.6 sec
[---               9%                  ] 193 of 2000 complete in 19.2 sec
[---               9%                  ] 199 of 2000 complete in 19.8 sec
[---              10%                  ] 204 of 2000 complete in 20.3 sec
[---              10%                  ] 209 of 2000 complete in 20.8 sec
[----             10%                  ] 214 of 2000 complete in 21.4 sec
[----             10%                  ] 219 of 2000 complete in 21.9 sec
[----             11%                  ] 224 of 2000 complete in 22.4 sec
[----             11%                  ] 229 of 2000 complete in 22.9 sec
[----             11%                  ] 234 of 2000 complete in 23.4 sec
[----             11%                  ] 239 of 2000 complete in 24.0 sec
[----             12%                  ] 244 of 2000 complete in 24.5 sec
[----             12%                  ] 249 of 2000 complete in 25.0 sec
[----             12%                  ] 254 of 2000 complete in 25.5 sec
[----             12%                  ] 259 of 2000 complete in 26.0 sec
[-----            13%                  ] 264 of 2000 complete in 26.5 sec
[-----            13%                  ] 269 of 2000 complete in 27.1 sec
[-----            13%                  ] 274 of 2000 complete in 27.7 sec
[-----            13%                  ] 279 of 2000 complete in 28.2 sec
[-----            14%                  ] 284 of 2000 complete in 28.7 sec
[-----            14%                  ] 289 of 2000 complete in 29.2 sec
[-----            14%                  ] 295 of 2000 complete in 29.8 sec
[-----            15%                  ] 300 of 2000 complete in 30.3 sec
[-----            15%                  ] 305 of 2000 complete in 30.8 sec
[-----            15%                  ] 311 of 2000 complete in 31.4 sec
[------           15%                  ] 317 of 2000 complete in 32.0 sec
[------           16%                  ] 323 of 2000 complete in 32.5 sec
[------           16%                  ] 329 of 2000 complete in 33.1 sec
[------           16%                  ] 334 of 2000 complete in 33.6 sec
[------           17%                  ] 340 of 2000 complete in 34.2 sec
[------           17%                  ] 346 of 2000 complete in 34.8 sec
[------           17%                  ] 352 of 2000 complete in 35.4 sec
[------           17%                  ] 357 of 2000 complete in 35.9 sec
[------           18%                  ] 363 of 2000 complete in 36.5 sec
[-------          18%                  ] 369 of 2000 complete in 37.0 sec
[-------          18%                  ] 375 of 2000 complete in 37.6 sec
[-------          19%                  ] 381 of 2000 complete in 38.2 sec
[-------          19%                  ] 387 of 2000 complete in 38.8 sec
[-------          19%                  ] 393 of 2000 complete in 39.4 sec
[-------          19%                  ] 399 of 2000 complete in 39.9 sec
[-------          20%                  ] 405 of 2000 complete in 40.5 sec
[-------          20%                  ] 411 of 2000 complete in 41.1 sec
[-------          20%                  ] 417 of 2000 complete in 41.7 sec
[--------         21%                  ] 423 of 2000 complete in 42.3 sec
[--------         21%                  ] 429 of 2000 complete in 42.8 sec
[--------         21%                  ] 435 of 2000 complete in 43.4 sec
[--------         22%                  ] 441 of 2000 complete in 44.0 sec
[--------         22%                  ] 447 of 2000 complete in 44.6 sec
[--------         22%                  ] 453 of 2000 complete in 45.1 sec
[--------         22%                  ] 459 of 2000 complete in 45.7 sec
[--------         23%                  ] 465 of 2000 complete in 46.3 sec
[--------         23%                  ] 471 of 2000 complete in 46.9 sec
[---------        23%                  ] 477 of 2000 complete in 47.4 sec
[---------        24%                  ] 483 of 2000 complete in 48.0 sec
[---------        24%                  ] 489 of 2000 complete in 48.6 sec
[---------        24%                  ] 495 of 2000 complete in 49.1 sec
[---------        25%                  ] 501 of 2000 complete in 49.7 sec
[---------        25%                  ] 507 of 2000 complete in 50.3 sec
[---------        25%                  ] 513 of 2000 complete in 50.9 sec
[---------        25%                  ] 519 of 2000 complete in 51.4 sec
[---------        26%                  ] 525 of 2000 complete in 52.0 sec
[----------       26%                  ] 531 of 2000 complete in 52.6 sec
[----------       26%                  ] 537 of 2000 complete in 53.2 sec
[----------       27%                  ] 543 of 2000 complete in 53.8 sec
[----------       27%                  ] 549 of 2000 complete in 54.3 sec
[----------       27%                  ] 555 of 2000 complete in 54.9 sec
[----------       28%                  ] 561 of 2000 complete in 55.5 sec
[----------       28%                  ] 567 of 2000 complete in 56.1 sec

[------           15%                  ] 319 of 2000 complete in 32.1 sec
[------           16%                  ] 324 of 2000 complete in 32.6 sec
[------           16%                  ] 330 of 2000 complete in 33.2 sec
[------           16%                  ] 335 of 2000 complete in 33.8 sec
[------           17%                  ] 341 of 2000 complete in 34.4 sec
[------           17%                  ] 346 of 2000 complete in 34.9 sec
[------           17%                  ] 352 of 2000 complete in 35.5 sec
[------           17%                  ] 357 of 2000 complete in 36.0 sec
[------           18%                  ] 362 of 2000 complete in 36.5 sec
[------           18%                  ] 367 of 2000 complete in 37.0 sec
[-------          18%                  ] 373 of 2000 complete in 37.6 sec
[-------          18%                  ] 378 of 2000 complete in 38.1 sec
[-------          19%                  ] 384 of 2000 complete in 38.7 sec
[-------          19%                  ] 389 of 2000 complete in 39.2 sec
[-------          19%                  ] 395 of 2000 complete in 39.8 sec
[-------          20%                  ] 400 of 2000 complete in 40.3 sec
[-------          20%                  ] 405 of 2000 complete in 40.8 sec
[-------          20%                  ] 410 of 2000 complete in 41.3 sec
[-------          20%                  ] 415 of 2000 complete in 41.8 sec
[-------          21%                  ] 421 of 2000 complete in 42.4 sec
[--------         21%                  ] 426 of 2000 complete in 42.9 sec
[--------         21%                  ] 431 of 2000 complete in 43.4 sec
[--------         21%                  ] 437 of 2000 complete in 44.0 sec
[--------         22%                  ] 443 of 2000 complete in 44.6 sec
[--------         22%                  ] 449 of 2000 complete in 45.2 sec
[--------         22%                  ] 454 of 2000 complete in 45.7 sec
[--------         23%                  ] 460 of 2000 complete in 46.3 sec
[--------         23%                  ] 465 of 2000 complete in 46.8 sec
[--------         23%                  ] 471 of 2000 complete in 47.4 sec
[---------        23%                  ] 477 of 2000 complete in 48.0 sec
[---------        24%                  ] 483 of 2000 complete in 48.6 sec
[---------        24%                  ] 488 of 2000 complete in 49.1 sec
[---------        24%                  ] 494 of 2000 complete in 49.7 sec
[---------        25%                  ] 500 of 2000 complete in 50.3 sec
[---------        25%                  ] 506 of 2000 complete in 50.8 sec
[---------        25%                  ] 512 of 2000 complete in 51.4 sec
[---------        25%                  ] 518 of 2000 complete in 52.0 sec
[---------        26%                  ] 524 of 2000 complete in 52.6 sec
[----------       26%                  ] 529 of 2000 complete in 53.1 sec
[----------       26%                  ] 535 of 2000 complete in 53.7 sec
[----------       27%                  ] 541 of 2000 complete in 54.3 sec
[----------       27%                  ] 546 of 2000 complete in 54.8 sec
[----------       27%                  ] 552 of 2000 complete in 55.4 sec
[----------       27%                  ] 557 of 2000 complete in 55.9 sec
[----------       28%                  ] 563 of 2000 complete in 56.5 sec
[----------       28%                  ] 568 of 2000 complete in 57.0 sec
[----------       28%                  ] 574 of 2000 complete in 57.6 sec
[-----------      28%                  ] 579 of 2000 complete in 58.1 sec
[-----------      29%                  ] 584 of 2000 complete in 58.6 sec
[-----------      29%                  ] 590 of 2000 complete in 59.2 sec
[-----------      29%                  ] 596 of 2000 complete in 59.8 sec
[-----------      30%                  ] 602 of 2000 complete in 60.4 sec
[-----------      30%                  ] 608 of 2000 complete in 61.0 sec
[-----------      30%                  ] 614 of 2000 complete in 61.6 sec
[-----------      30%                  ] 619 of 2000 complete in 62.1 sec
[-----------      31%                  ] 624 of 2000 complete in 62.6 sec
[-----------      31%                  ] 629 of 2000 complete in 63.1 sec
[------------     31%                  ] 634 of 2000 complete in 63.7 sec
[------------     31%                  ] 639 of 2000 complete in 64.2 sec
[------------     32%                  ] 644 of 2000 complete in 64.8 sec
[------------     32%                  ] 649 of 2000 complete in 65.3 sec
[------------     32%                  ] 654 of 2000 complete in 65.8 sec
[------------     32%                  ] 659 of 2000 complete in 66.3 sec
[------------     33%                  ] 664 of 2000 complete in 66.9 sec
[------------     33%                  ] 668 of 2000 complete in 67.4 sec
[------------     33%                  ] 672 of 2000 complete in 67.9 sec
[------------     33%                  ] 678 of 2000 complete in 68.5 sec
[------------     34%                  ] 683 of 2000 complete in 69.1 sec
[-------------    34%                  ] 689 of 2000 complete in 69.7 sec
[-------------    34%                  ] 694 of 2000 complete in 70.2 sec
[-------------    34%                  ] 699 of 2000 complete in 70.7 sec
[-------------    35%                  ] 704 of 2000 complete in 71.2 sec
[-------------    35%                  ] 709 of 2000 complete in 71.7 sec
[-------------    35%                  ] 715 of 2000 complete in 72.3 sec
[-------------    36%                  ] 721 of 2000 complete in 72.9 sec
[-------------    36%                  ] 727 of 2000 complete in 73.5 sec
[-------------    36%                  ] 732 of 2000 complete in 74.0 sec
[--------------   36%                  ] 738 of 2000 complete in 74.6 sec
[--------------   37%                  ] 743 of 2000 complete in 75.1 sec
[--------------   37%                  ] 749 of 2000 complete in 75.7 sec
[--------------   37%                  ] 755 of 2000 complete in 76.3 sec
[--------------   38%                  ] 761 of 2000 complete in 76.9 sec
[--------------   38%                  ] 767 of 2000 complete in 77.4 sec
[--------------   38%                  ] 773 of 2000 complete in 78.0 sec
[--------------   38%                  ] 779 of 2000 complete in 78.6 sec
[--------------   39%                  ] 785 of 2000 complete in 79.2 sec
[---------------  39%                  ] 791 of 2000 complete in 79.8 sec
[---------------  39%                  ] 797 of 2000 complete in 80.4 sec
[---------------  40%                  ] 803 of 2000 complete in 81.0 sec
[---------------  40%                  ] 809 of 2000 complete in 81.6 sec
[---------------  40%                  ] 814 of 2000 complete in 82.1 sec
[---------------  41%                  ] 820 of 2000 complete in 82.7 sec
[---------------  41%                  ] 826 of 2000 complete in 83.2 sec
[---------------  41%                  ] 832 of 2000 complete in 83.8 sec
[---------------  41%                  ] 838 of 2000 complete in 84.4 sec
[---------------- 42%                  ] 844 of 2000 complete in 85.0 sec
[---------------- 42%                  ] 850 of 2000 complete in 85.6 sec
[---------------- 42%                  ] 856 of 2000 complete in 86.2 sec
[---------------- 43%                  ] 862 of 2000 complete in 86.8 sec
[---------------- 43%                  ] 868 of 2000 complete in 87.3 sec
[---------------- 43%                  ] 874 of 2000 complete in 87.9 sec
[---------------- 44%                  ] 880 of 2000 complete in 88.5 sec
[---------------- 44%                  ] 886 of 2000 complete in 89.1 sec
[---------------- 44%                  ] 892 of 2000 complete in 89.7 sec
[-----------------44%                  ] 898 of 2000 complete in 90.3 sec
[-----------------45%                  ] 904 of 2000 complete in 90.9 sec
[-----------------45%                  ] 910 of 2000 complete in 91.5 sec
[-----------------45%                  ] 916 of 2000 complete in 92.1 sec
[-----------------46%                  ] 922 of 2000 complete in 92.7 sec
[-----------------46%                  ] 928 of 2000 complete in 93.3 sec
[---------        24%                  ] 481 of 2000 complete in 47.4 sec
[---------        24%                  ] 487 of 2000 complete in 48.0 sec
[---------        24%                  ] 493 of 2000 complete in 48.6 sec
[---------        24%                  ] 499 of 2000 complete in 49.1 sec
[---------        25%                  ] 505 of 2000 complete in 49.7 sec
[---------        25%                  ] 511 of 2000 complete in 50.3 sec
[---------        25%                  ] 517 of 2000 complete in 50.9 sec
[---------        26%                  ] 523 of 2000 complete in 51.5 sec
[----------       26%                  ] 529 of 2000 complete in 52.1 sec
[----------       26%                  ] 534 of 2000 complete in 52.6 sec
[----------       27%                  ] 540 of 2000 complete in 53.1 sec
[----------       27%                  ] 546 of 2000 complete in 53.7 sec
[----------       27%                  ] 552 of 2000 complete in 54.3 sec
[----------       27%                  ] 558 of 2000 complete in 54.9 sec
[----------       28%                  ] 564 of 2000 complete in 55.5 sec
[----------       28%                  ] 570 of 2000 complete in 56.0 sec
[----------       28%                  ] 575 of 2000 complete in 56.5 sec
[-----------      29%                  ] 581 of 2000 complete in 57.1 sec
[-----------      29%                  ] 587 of 2000 complete in 57.7 sec
[-----------      29%                  ] 593 of 2000 complete in 58.3 sec
[-----------      29%                  ] 599 of 2000 complete in 58.9 sec
[-----------      30%                  ] 605 of 2000 complete in 59.4 sec
[-----------      30%                  ] 611 of 2000 complete in 60.0 sec
[-----------      30%                  ] 617 of 2000 complete in 60.6 sec
[-----------      31%                  ] 623 of 2000 complete in 61.2 sec
[-----------      31%                  ] 629 of 2000 complete in 61.8 sec
[------------     31%                  ] 634 of 2000 complete in 62.3 sec
[------------     31%                  ] 639 of 2000 complete in 62.8 sec
[------------     32%                  ] 645 of 2000 complete in 63.4 sec
[------------     32%                  ] 650 of 2000 complete in 63.9 sec
[------------     32%                  ] 655 of 2000 complete in 64.4 sec
[------------     33%                  ] 660 of 2000 complete in 65.0 sec
[------------     33%                  ] 665 of 2000 complete in 65.5 sec
[------------     33%                  ] 670 of 2000 complete in 66.0 sec
[------------     33%                  ] 675 of 2000 complete in 66.5 sec
[------------     34%                  ] 680 of 2000 complete in 67.1 sec
[------------     34%                  ] 684 of 2000 complete in 67.7 sec
[-------------    34%                  ] 689 of 2000 complete in 68.2 sec
[-------------    34%                  ] 694 of 2000 complete in 68.7 sec
[-------------    34%                  ] 699 of 2000 complete in 69.2 sec
[-------------    35%                  ] 705 of 2000 complete in 69.8 sec
[-------------    35%                  ] 710 of 2000 complete in 70.3 sec
[-------------    35%                  ] 716 of 2000 complete in 70.9 sec
[-------------    36%                  ] 722 of 2000 complete in 71.5 sec
[-------------    36%                  ] 728 of 2000 complete in 72.1 sec
[-------------    36%                  ] 734 of 2000 complete in 72.6 sec
[--------------   36%                  ] 739 of 2000 complete in 73.1 sec
[--------------   37%                  ] 745 of 2000 complete in 73.7 sec
[--------------   37%                  ] 751 of 2000 complete in 74.3 sec
[--------------   37%                  ] 757 of 2000 complete in 74.9 sec
[--------------   38%                  ] 763 of 2000 complete in 75.5 sec
[--------------   38%                  ] 769 of 2000 complete in 76.0 sec
[--------------   38%                  ] 775 of 2000 complete in 76.6 sec
[--------------   39%                  ] 781 of 2000 complete in 77.2 sec
[--------------   39%                  ] 787 of 2000 complete in 77.8 sec
[---------------  39%                  ] 793 of 2000 complete in 78.3 sec
[---------------  39%                  ] 799 of 2000 complete in 78.9 sec
[---------------  40%                  ] 805 of 2000 complete in 79.5 sec
[---------------  40%                  ] 811 of 2000 complete in 80.0 sec
[---------------  40%                  ] 817 of 2000 complete in 80.6 sec
[---------------  41%                  ] 823 of 2000 complete in 81.2 sec
[---------------  41%                  ] 829 of 2000 complete in 81.8 sec
[---------------  41%                  ] 835 of 2000 complete in 82.3 sec
[---------------  42%                  ] 841 of 2000 complete in 82.9 sec
[---------------- 42%                  ] 847 of 2000 complete in 83.5 sec
[---------------- 42%                  ] 853 of 2000 complete in 84.0 sec
[---------------- 42%                  ] 859 of 2000 complete in 84.6 sec
[---------------- 43%                  ] 865 of 2000 complete in 85.2 sec
[---------------- 43%                  ] 871 of 2000 complete in 85.8 sec
[---------------- 43%                  ] 877 of 2000 complete in 86.4 sec
[---------------- 44%                  ] 883 of 2000 complete in 87.0 sec
[---------------- 44%                  ] 889 of 2000 complete in 87.5 sec
[-----------------44%                  ] 895 of 2000 complete in 88.1 sec
[-----------------45%                  ] 901 of 2000 complete in 88.7 sec
[-----------------45%                  ] 907 of 2000 complete in 89.3 sec
[-----------------45%                  ] 913 of 2000 complete in 89.8 sec
[-----------------45%                  ] 919 of 2000 complete in 90.4 sec
[-----------------46%                  ] 925 of 2000 complete in 91.0 sec
[-----------------46%                  ] 931 of 2000 complete in 91.6 sec
[-----------------46%                  ] 937 of 2000 complete in 92.1 sec
[-----------------47%                  ] 943 of 2000 complete in 92.7 sec
[-----------------47%                  ] 949 of 2000 complete in 93.3 sec
[-----------------47%                  ] 955 of 2000 complete in 93.8 sec
[-----------------48%                  ] 961 of 2000 complete in 94.4 sec
[-----------------48%                  ] 967 of 2000 complete in 95.0 sec
[-----------------48%                  ] 973 of 2000 complete in 95.6 sec
[-----------------48%                  ] 979 of 2000 complete in 96.2 sec
[-----------------49%                  ] 984 of 2000 complete in 96.7 sec
[-----------------49%                  ] 990 of 2000 complete in 97.2 sec
[-----------------49%                  ] 995 of 2000 complete in 97.8 sec
[-----------------50%                  ] 1001 of 2000 complete in 98.3 sec
[-----------------50%                  ] 1006 of 2000 complete in 98.9 sec
[-----------------50%                  ] 1012 of 2000 complete in 99.4 sec
[-----------------50%                  ] 1018 of 2000 complete in 100.0 sec
[-----------------51%                  ] 1023 of 2000 complete in 100.5 sec
[-----------------51%                  ] 1028 of 2000 complete in 101.1 sec
[-----------------51%                  ] 1034 of 2000 complete in 101.7 sec
[-----------------51%                  ] 1039 of 2000 complete in 102.2 sec
[-----------------52%                  ] 1044 of 2000 complete in 102.7 sec
[-----------------52%                  ] 1050 of 2000 complete in 103.3 sec
[-----------------52%                  ] 1056 of 2000 complete in 103.8 sec
[-----------------53%                  ] 1062 of 2000 complete in 104.4 sec
[-----------------53%                  ] 1067 of 2000 complete in 104.9 sec
[-----------------53%                  ] 1073 of 2000 complete in 105.5 sec
[-----------------53%                  ] 1078 of 2000 complete in 106.0 sec
[-----------------54%                  ] 1084 of 2000 complete in 106.6 sec
[-----------------54%                  ] 1090 of 2000 complete in 107.2 sec
[-----------------54%                  ] 1095 of 2000 complete in 107.7 sec
[-----------------55%                  ] 1101 of 2000 complete in 108.3 sec
[-----------------55%-                 ] 1107 of 2000 complete in 108.9 sec

[----------       27%                  ] 549 of 2000 complete in 53.3 sec
[----------       27%                  ] 555 of 2000 complete in 53.9 sec
[----------       28%                  ] 561 of 2000 complete in 54.5 sec
[----------       28%                  ] 567 of 2000 complete in 55.1 sec
[----------       28%                  ] 573 of 2000 complete in 55.6 sec
[-----------      28%                  ] 579 of 2000 complete in 56.2 sec
[-----------      29%                  ] 585 of 2000 complete in 56.8 sec
[-----------      29%                  ] 591 of 2000 complete in 57.4 sec
[-----------      29%                  ] 597 of 2000 complete in 58.0 sec
[-----------      30%                  ] 603 of 2000 complete in 58.5 sec
[-----------      30%                  ] 609 of 2000 complete in 59.1 sec
[-----------      30%                  ] 615 of 2000 complete in 59.7 sec
[-----------      31%                  ] 621 of 2000 complete in 60.3 sec
[-----------      31%                  ] 627 of 2000 complete in 60.8 sec
[------------     31%                  ] 633 of 2000 complete in 61.4 sec
[------------     31%                  ] 638 of 2000 complete in 61.9 sec
[------------     32%                  ] 644 of 2000 complete in 62.5 sec
[------------     32%                  ] 649 of 2000 complete in 63.0 sec
[------------     32%                  ] 655 of 2000 complete in 63.6 sec
[------------     33%                  ] 661 of 2000 complete in 64.2 sec
[------------     33%                  ] 666 of 2000 complete in 64.8 sec
[------------     33%                  ] 672 of 2000 complete in 65.4 sec
[------------     33%                  ] 677 of 2000 complete in 65.9 sec
[------------     34%                  ] 683 of 2000 complete in 66.5 sec
[-------------    34%                  ] 688 of 2000 complete in 67.1 sec
[-------------    34%                  ] 692 of 2000 complete in 67.6 sec
[-------------    34%                  ] 697 of 2000 complete in 68.2 sec
[-------------    35%                  ] 703 of 2000 complete in 68.8 sec
[-------------    35%                  ] 709 of 2000 complete in 69.3 sec
[-------------    35%                  ] 714 of 2000 complete in 69.9 sec
[-------------    36%                  ] 720 of 2000 complete in 70.5 sec
[-------------    36%                  ] 725 of 2000 complete in 71.0 sec
[-------------    36%                  ] 731 of 2000 complete in 71.6 sec
[--------------   36%                  ] 737 of 2000 complete in 72.1 sec
[--------------   37%                  ] 743 of 2000 complete in 72.7 sec
[--------------   37%                  ] 748 of 2000 complete in 73.2 sec
[--------------   37%                  ] 754 of 2000 complete in 73.8 sec
[--------------   38%                  ] 760 of 2000 complete in 74.4 sec
[--------------   38%                  ] 766 of 2000 complete in 75.0 sec
[--------------   38%                  ] 772 of 2000 complete in 75.5 sec
[--------------   38%                  ] 778 of 2000 complete in 76.1 sec
[--------------   39%                  ] 784 of 2000 complete in 76.7 sec
[---------------  39%                  ] 790 of 2000 complete in 77.3 sec
[---------------  39%                  ] 796 of 2000 complete in 77.9 sec
[---------------  40%                  ] 802 of 2000 complete in 78.5 sec
[---------------  40%                  ] 808 of 2000 complete in 79.0 sec
[---------------  40%                  ] 814 of 2000 complete in 79.6 sec
[---------------  41%                  ] 820 of 2000 complete in 80.2 sec
[---------------  41%                  ] 826 of 2000 complete in 80.7 sec
[---------------  41%                  ] 832 of 2000 complete in 81.3 sec
[---------------  41%                  ] 838 of 2000 complete in 81.9 sec
[---------------- 42%                  ] 844 of 2000 complete in 82.4 sec
[---------------- 42%                  ] 850 of 2000 complete in 83.0 sec
[---------------- 42%                  ] 856 of 2000 complete in 83.6 sec
[---------------- 43%                  ] 862 of 2000 complete in 84.2 sec
[---------------- 43%                  ] 868 of 2000 complete in 84.7 sec
[---------------- 43%                  ] 874 of 2000 complete in 85.3 sec
[---------------- 44%                  ] 880 of 2000 complete in 85.9 sec
[---------------- 44%                  ] 886 of 2000 complete in 86.4 sec
[---------------- 44%                  ] 892 of 2000 complete in 87.0 sec
[-----------------44%                  ] 898 of 2000 complete in 87.6 sec
[-----------------45%                  ] 904 of 2000 complete in 88.2 sec
[-----------------45%                  ] 910 of 2000 complete in 88.7 sec
[-----------------45%                  ] 916 of 2000 complete in 89.3 sec
[-----------------46%                  ] 922 of 2000 complete in 89.9 sec
[-----------------46%                  ] 928 of 2000 complete in 90.4 sec
[-----------------46%                  ] 934 of 2000 complete in 91.0 sec
[-----------------47%                  ] 940 of 2000 complete in 91.6 sec
[-----------------47%                  ] 946 of 2000 complete in 92.2 sec
[-----------------47%                  ] 952 of 2000 complete in 92.7 sec
[-----------------47%                  ] 958 of 2000 complete in 93.3 sec
[-----------------48%                  ] 964 of 2000 complete in 93.9 sec
[-----------------48%                  ] 970 of 2000 complete in 94.5 sec
[-----------------48%                  ] 976 of 2000 complete in 95.0 sec
[-----------------49%                  ] 982 of 2000 complete in 95.6 sec
[-----------------49%                  ] 988 of 2000 complete in 96.2 sec
[-----------------49%                  ] 994 of 2000 complete in 96.8 sec
[-----------------50%                  ] 1000 of 2000 complete in 97.4 sec
[-----------------50%                  ] 1005 of 2000 complete in 97.9 sec
[-----------------50%                  ] 1011 of 2000 complete in 98.5 sec
[-----------------50%                  ] 1016 of 2000 complete in 99.0 sec
[-----------------51%                  ] 1022 of 2000 complete in 99.6 sec
[-----------------51%                  ] 1028 of 2000 complete in 100.2 sec
[-----------------51%                  ] 1034 of 2000 complete in 100.8 sec
[-----------------52%                  ] 1040 of 2000 complete in 101.4 sec
[-----------------52%                  ] 1045 of 2000 complete in 101.9 sec
[-----------------52%                  ] 1051 of 2000 complete in 102.5 sec
[-----------------52%                  ] 1057 of 2000 complete in 103.1 sec
[-----------------53%                  ] 1063 of 2000 complete in 103.6 sec
[-----------------53%                  ] 1069 of 2000 complete in 104.2 sec
[-----------------53%                  ] 1074 of 2000 complete in 104.7 sec
[-----------------54%                  ] 1080 of 2000 complete in 105.3 sec
[-----------------54%                  ] 1085 of 2000 complete in 105.8 sec
[-----------------54%                  ] 1091 of 2000 complete in 106.4 sec
[-----------------54%                  ] 1097 of 2000 complete in 107.0 sec
[-----------------55%                  ] 1103 of 2000 complete in 107.6 sec
[-----------------55%-                 ] 1109 of 2000 complete in 108.2 sec
[-----------------55%-                 ] 1115 of 2000 complete in 108.7 sec
[-----------------56%-                 ] 1121 of 2000 complete in 109.3 sec
[-----------------56%-                 ] 1127 of 2000 complete in 109.9 sec
[-----------------56%-                 ] 1133 of 2000 complete in 110.5 sec
[-----------------56%-                 ] 1138 of 2000 complete in 111.0 sec
[-----------------57%-                 ] 1143 of 2000 complete in 111.6 sec
[-----------------57%-                 ] 1149 of 2000 complete in 112.1 sec
[-----------------57%-                 ] 1155 of 2000 complete in 112.7 sec
[-----------------58%--                ] 1161 of 2000 complete in 113.3 sec
[-----------------58%--                ] 1167 of 2000 complete in 113.9 sec
[-----------------58%--                ] 1173 of 2000 complete in 114.5 sec
[-----------------58%--                ] 1178 of 2000 complete in 115.0 sec
[----------       28%                  ] 573 of 2000 complete in 56.6 sec
[-----------      28%                  ] 579 of 2000 complete in 57.2 sec
[-----------      29%                  ] 585 of 2000 complete in 57.8 sec
[-----------      29%                  ] 591 of 2000 complete in 58.4 sec
[-----------      29%                  ] 597 of 2000 complete in 58.9 sec
[-----------      30%                  ] 603 of 2000 complete in 59.5 sec
[-----------      30%                  ] 609 of 2000 complete in 60.1 sec
[-----------      30%                  ] 615 of 2000 complete in 60.7 sec
[-----------      31%                  ] 621 of 2000 complete in 61.2 sec
[-----------      31%                  ] 627 of 2000 complete in 61.8 sec
[------------     31%                  ] 633 of 2000 complete in 62.4 sec
[------------     31%                  ] 639 of 2000 complete in 63.0 sec
[------------     32%                  ] 644 of 2000 complete in 63.5 sec
[------------     32%                  ] 649 of 2000 complete in 64.0 sec
[------------     32%                  ] 654 of 2000 complete in 64.6 sec
[------------     32%                  ] 659 of 2000 complete in 65.1 sec
[------------     33%                  ] 664 of 2000 complete in 65.6 sec
[------------     33%                  ] 669 of 2000 complete in 66.1 sec
[------------     33%                  ] 675 of 2000 complete in 66.8 sec
[------------     33%                  ] 679 of 2000 complete in 67.3 sec
[------------     34%                  ] 683 of 2000 complete in 67.8 sec
[-------------    34%                  ] 689 of 2000 complete in 68.4 sec
[-------------    34%                  ] 694 of 2000 complete in 68.9 sec
[-------------    35%                  ] 700 of 2000 complete in 69.5 sec
[-------------    35%                  ] 705 of 2000 complete in 70.0 sec
[-------------    35%                  ] 711 of 2000 complete in 70.6 sec
[-------------    35%                  ] 716 of 2000 complete in 71.1 sec
[-------------    36%                  ] 722 of 2000 complete in 71.7 sec
[-------------    36%                  ] 728 of 2000 complete in 72.3 sec
[-------------    36%                  ] 734 of 2000 complete in 72.8 sec
[--------------   37%                  ] 740 of 2000 complete in 73.4 sec
[--------------   37%                  ] 746 of 2000 complete in 74.0 sec
[--------------   37%                  ] 752 of 2000 complete in 74.6 sec
[--------------   37%                  ] 758 of 2000 complete in 75.2 sec
[--------------   38%                  ] 764 of 2000 complete in 75.8 sec
[--------------   38%                  ] 770 of 2000 complete in 76.3 sec
[--------------   38%                  ] 776 of 2000 complete in 76.9 sec
[--------------   39%                  ] 782 of 2000 complete in 77.5 sec
[--------------   39%                  ] 788 of 2000 complete in 78.1 sec
[---------------  39%                  ] 794 of 2000 complete in 78.7 sec
[---------------  40%                  ] 800 of 2000 complete in 79.3 sec
[---------------  40%                  ] 806 of 2000 complete in 79.8 sec
[---------------  40%                  ] 812 of 2000 complete in 80.4 sec
[---------------  40%                  ] 817 of 2000 complete in 80.9 sec
[---------------  41%                  ] 823 of 2000 complete in 81.5 sec
[---------------  41%                  ] 829 of 2000 complete in 82.1 sec
[---------------  41%                  ] 835 of 2000 complete in 82.7 sec
[---------------  42%                  ] 841 of 2000 complete in 83.2 sec
[---------------- 42%                  ] 847 of 2000 complete in 83.8 sec
[---------------- 42%                  ] 853 of 2000 complete in 84.4 sec
[---------------- 42%                  ] 859 of 2000 complete in 85.0 sec
[---------------- 43%                  ] 865 of 2000 complete in 85.5 sec
[---------------- 43%                  ] 871 of 2000 complete in 86.1 sec
[---------------- 43%                  ] 877 of 2000 complete in 86.7 sec
[---------------- 44%                  ] 883 of 2000 complete in 87.3 sec
[---------------- 44%                  ] 889 of 2000 complete in 87.8 sec
[-----------------44%                  ] 895 of 2000 complete in 88.4 sec
[-----------------45%                  ] 901 of 2000 complete in 89.0 sec
[-----------------45%                  ] 907 of 2000 complete in 89.6 sec
[-----------------45%                  ] 913 of 2000 complete in 90.1 sec
[-----------------45%                  ] 919 of 2000 complete in 90.7 sec
[-----------------46%                  ] 925 of 2000 complete in 91.3 sec
[-----------------46%                  ] 931 of 2000 complete in 91.8 sec
[-----------------46%                  ] 937 of 2000 complete in 92.4 sec
[-----------------47%                  ] 943 of 2000 complete in 93.0 sec
[-----------------47%                  ] 949 of 2000 complete in 93.5 sec
[-----------------47%                  ] 955 of 2000 complete in 94.1 sec
[-----------------48%                  ] 961 of 2000 complete in 94.7 sec
[-----------------48%                  ] 967 of 2000 complete in 95.3 sec
[-----------------48%                  ] 973 of 2000 complete in 95.8 sec
[-----------------48%                  ] 979 of 2000 complete in 96.4 sec
[-----------------49%                  ] 985 of 2000 complete in 97.0 sec
[-----------------49%                  ] 991 of 2000 complete in 97.6 sec
[-----------------49%                  ] 997 of 2000 complete in 98.2 sec
[-----------------50%                  ] 1003 of 2000 complete in 98.8 sec
[-----------------50%                  ] 1009 of 2000 complete in 99.4 sec
[-----------------50%                  ] 1014 of 2000 complete in 99.9 sec
[-----------------51%                  ] 1020 of 2000 complete in 100.5 sec
[-----------------51%                  ] 1025 of 2000 complete in 101.0 sec
[-----------------51%                  ] 1031 of 2000 complete in 101.6 sec
[-----------------51%                  ] 1036 of 2000 complete in 102.1 sec
[-----------------52%                  ] 1042 of 2000 complete in 102.6 sec
[-----------------52%                  ] 1047 of 2000 complete in 103.2 sec
[-----------------52%                  ] 1053 of 2000 complete in 103.7 sec
[-----------------52%                  ] 1059 of 2000 complete in 104.3 sec
[-----------------53%                  ] 1065 of 2000 complete in 104.9 sec
[-----------------53%                  ] 1070 of 2000 complete in 105.4 sec
[-----------------53%                  ] 1075 of 2000 complete in 105.9 sec
[-----------------54%                  ] 1081 of 2000 complete in 106.5 sec
[-----------------54%                  ] 1087 of 2000 complete in 107.1 sec
[-----------------54%                  ] 1092 of 2000 complete in 107.6 sec
[-----------------54%                  ] 1097 of 2000 complete in 108.1 sec
[-----------------55%                  ] 1102 of 2000 complete in 108.6 sec
[-----------------55%-                 ] 1107 of 2000 complete in 109.2 sec
[-----------------55%-                 ] 1112 of 2000 complete in 109.7 sec
[-----------------55%-                 ] 1117 of 2000 complete in 110.2 sec
[-----------------56%-                 ] 1122 of 2000 complete in 110.7 sec
[-----------------56%-                 ] 1127 of 2000 complete in 111.2 sec
[-----------------56%-                 ] 1132 of 2000 complete in 111.7 sec
[-----------------56%-                 ] 1137 of 2000 complete in 112.3 sec
[-----------------57%-                 ] 1142 of 2000 complete in 112.8 sec
[-----------------57%-                 ] 1148 of 2000 complete in 113.4 sec
[-----------------57%-                 ] 1153 of 2000 complete in 113.9 sec
[-----------------57%--                ] 1158 of 2000 complete in 114.4 sec
[-----------------58%--                ] 1163 of 2000 complete in 114.9 sec
[-----------------58%--                ] 1169 of 2000 complete in 115.5 sec
[-----------------58%--                ] 1174 of 2000 complete in 116.0 sec
[-----------------58%--                ] 1179 of 2000 complete in 116.5 sec
[-----------------59%--                ] 1184 of 2000 complete in 117.0 sec

[-----------------46%                  ] 933 of 2000 complete in 93.8 sec
[-----------------46%                  ] 938 of 2000 complete in 94.3 sec
[-----------------47%                  ] 943 of 2000 complete in 94.8 sec
[-----------------47%                  ] 949 of 2000 complete in 95.4 sec
[-----------------47%                  ] 955 of 2000 complete in 96.0 sec
[-----------------48%                  ] 960 of 2000 complete in 96.5 sec
[-----------------48%                  ] 965 of 2000 complete in 97.0 sec
[-----------------48%                  ] 970 of 2000 complete in 97.5 sec
[-----------------48%                  ] 975 of 2000 complete in 98.0 sec
[-----------------49%                  ] 980 of 2000 complete in 98.5 sec
[-----------------49%                  ] 985 of 2000 complete in 99.0 sec
[-----------------49%                  ] 991 of 2000 complete in 99.6 sec
[-----------------49%                  ] 996 of 2000 complete in 100.1 sec
[-----------------50%                  ] 1001 of 2000 complete in 100.6 sec
[-----------------50%                  ] 1006 of 2000 complete in 101.1 sec
[-----------------50%                  ] 1011 of 2000 complete in 101.7 sec
[-----------------50%                  ] 1016 of 2000 complete in 102.2 sec
[-----------------51%                  ] 1021 of 2000 complete in 102.7 sec
[-----------------51%                  ] 1026 of 2000 complete in 103.2 sec
[-----------------51%                  ] 1032 of 2000 complete in 103.8 sec
[-----------------51%                  ] 1038 of 2000 complete in 104.4 sec
[-----------------52%                  ] 1043 of 2000 complete in 104.9 sec
[-----------------52%                  ] 1048 of 2000 complete in 105.4 sec
[-----------------52%                  ] 1053 of 2000 complete in 105.9 sec
[-----------------52%                  ] 1058 of 2000 complete in 106.4 sec
[-----------------53%                  ] 1063 of 2000 complete in 106.9 sec
[-----------------53%                  ] 1069 of 2000 complete in 107.5 sec
[-----------------53%                  ] 1075 of 2000 complete in 108.1 sec
[-----------------54%                  ] 1080 of 2000 complete in 108.6 sec
[-----------------54%                  ] 1085 of 2000 complete in 109.1 sec
[-----------------54%                  ] 1090 of 2000 complete in 109.6 sec
[-----------------54%                  ] 1095 of 2000 complete in 110.1 sec
[-----------------55%                  ] 1100 of 2000 complete in 110.6 sec
[-----------------55%                  ] 1105 of 2000 complete in 111.1 sec
[-----------------55%-                 ] 1110 of 2000 complete in 111.6 sec
[-----------------55%-                 ] 1116 of 2000 complete in 112.2 sec
[-----------------56%-                 ] 1122 of 2000 complete in 112.8 sec
[-----------------56%-                 ] 1127 of 2000 complete in 113.3 sec
[-----------------56%-                 ] 1132 of 2000 complete in 113.9 sec
[-----------------56%-                 ] 1137 of 2000 complete in 114.4 sec
[-----------------57%-                 ] 1142 of 2000 complete in 114.9 sec
[-----------------57%-                 ] 1147 of 2000 complete in 115.4 sec
[-----------------57%-                 ] 1152 of 2000 complete in 115.9 sec
[-----------------57%-                 ] 1157 of 2000 complete in 116.4 sec
[-----------------58%--                ] 1162 of 2000 complete in 116.9 sec
[-----------------58%--                ] 1168 of 2000 complete in 117.5 sec
[-----------------58%--                ] 1173 of 2000 complete in 118.0 sec
[-----------------58%--                ] 1179 of 2000 complete in 118.6 sec
[-----------------59%--                ] 1184 of 2000 complete in 119.1 sec
[-----------------59%--                ] 1190 of 2000 complete in 119.7 sec
[-----------------59%--                ] 1195 of 2000 complete in 120.2 sec
[-----------------60%--                ] 1201 of 2000 complete in 120.8 sec
[-----------------60%--                ] 1207 of 2000 complete in 121.4 sec
[-----------------60%---               ] 1212 of 2000 complete in 122.0 sec
[-----------------60%---               ] 1217 of 2000 complete in 122.5 sec
[-----------------61%---               ] 1222 of 2000 complete in 123.0 sec
[-----------------61%---               ] 1227 of 2000 complete in 123.5 sec
[-----------------61%---               ] 1231 of 2000 complete in 124.0 sec
[-----------------61%---               ] 1236 of 2000 complete in 124.6 sec
[-----------------62%---               ] 1241 of 2000 complete in 125.1 sec
[-----------------62%---               ] 1245 of 2000 complete in 125.6 sec
[-----------------62%---               ] 1250 of 2000 complete in 126.2 sec
[-----------------62%---               ] 1255 of 2000 complete in 126.8 sec
[-----------------63%---               ] 1260 of 2000 complete in 127.4 sec
[-----------------63%----              ] 1265 of 2000 complete in 128.0 sec
[-----------------63%----              ] 1270 of 2000 complete in 128.5 sec
[-----------------63%----              ] 1275 of 2000 complete in 129.0 sec
[-----------------64%----              ] 1280 of 2000 complete in 129.5 sec
[-----------------64%----              ] 1285 of 2000 complete in 130.1 sec
[-----------------64%----              ] 1290 of 2000 complete in 130.6 sec
[-----------------64%----              ] 1295 of 2000 complete in 131.1 sec
[-----------------65%----              ] 1301 of 2000 complete in 131.7 sec
[-----------------65%----              ] 1306 of 2000 complete in 132.2 sec
[-----------------65%----              ] 1311 of 2000 complete in 132.8 sec
[-----------------65%-----             ] 1316 of 2000 complete in 133.3 sec
[-----------------66%-----             ] 1321 of 2000 complete in 133.8 sec
[-----------------66%-----             ] 1326 of 2000 complete in 134.4 sec
[-----------------66%-----             ] 1331 of 2000 complete in 135.0 sec
[-----------------66%-----             ] 1336 of 2000 complete in 135.6 sec
[-----------------67%-----             ] 1341 of 2000 complete in 136.1 sec
[-----------------67%-----             ] 1346 of 2000 complete in 136.7 sec
[-----------------67%-----             ] 1351 of 2000 complete in 137.3 sec
[-----------------67%-----             ] 1356 of 2000 complete in 137.8 sec
[-----------------68%-----             ] 1361 of 2000 complete in 138.3 sec
[-----------------68%-----             ] 1366 of 2000 complete in 138.9 sec
[-----------------68%------            ] 1371 of 2000 complete in 139.4 sec
[-----------------68%------            ] 1376 of 2000 complete in 139.9 sec
[-----------------69%------            ] 1381 of 2000 complete in 140.5 sec
[-----------------69%------            ] 1386 of 2000 complete in 141.0 sec
[-----------------69%------            ] 1391 of 2000 complete in 141.5 sec
[-----------------69%------            ] 1396 of 2000 complete in 142.1 sec
[-----------------70%------            ] 1401 of 2000 complete in 142.6 sec
[-----------------70%------            ] 1406 of 2000 complete in 143.1 sec
[-----------------70%------            ] 1411 of 2000 complete in 143.7 sec
[-----------------70%------            ] 1416 of 2000 complete in 144.3 sec
[-----------------71%------            ] 1421 of 2000 complete in 144.8 sec
[-----------------71%-------           ] 1426 of 2000 complete in 145.3 sec
[-----------------71%-------           ] 1431 of 2000 complete in 145.9 sec
[-----------------71%-------           ] 1436 of 2000 complete in 146.4 sec
[-----------------72%-------           ] 1441 of 2000 complete in 147.0 sec
[-----------------72%-------           ] 1446 of 2000 complete in 147.5 sec
[-----------------72%-------           ] 1451 of 2000 complete in 148.0 sec
[-----------------72%-------           ] 1456 of 2000 complete in 148.6 sec
[-----------------73%-------           ] 1461 of 2000 complete in 149.1 sec
[-----------------73%-------           ] 1465 of 2000 complete in 149.7 sec
[-----------------73%-------           ] 1469 of 2000 complete in 150.2 sec
[-----------------73%--------          ] 1474 of 2000 complete in 150.8 sec
[-----------------73%--------          ] 1479 of 2000 complete in 151.3 sec
[-----------------55%-                 ] 1113 of 2000 complete in 109.5 sec
[-----------------55%-                 ] 1119 of 2000 complete in 110.1 sec
[-----------------56%-                 ] 1125 of 2000 complete in 110.7 sec
[-----------------56%-                 ] 1131 of 2000 complete in 111.3 sec
[-----------------56%-                 ] 1136 of 2000 complete in 111.8 sec
[-----------------57%-                 ] 1141 of 2000 complete in 112.3 sec
[-----------------57%-                 ] 1146 of 2000 complete in 112.8 sec
[-----------------57%-                 ] 1152 of 2000 complete in 113.4 sec
[-----------------57%-                 ] 1157 of 2000 complete in 113.9 sec
[-----------------58%--                ] 1163 of 2000 complete in 114.5 sec
[-----------------58%--                ] 1169 of 2000 complete in 115.1 sec
[-----------------58%--                ] 1175 of 2000 complete in 115.7 sec
[-----------------59%--                ] 1181 of 2000 complete in 116.2 sec
[-----------------59%--                ] 1186 of 2000 complete in 116.7 sec
[-----------------59%--                ] 1191 of 2000 complete in 117.2 sec
[-----------------59%--                ] 1196 of 2000 complete in 117.8 sec
[-----------------60%--                ] 1202 of 2000 complete in 118.3 sec
[-----------------60%--                ] 1208 of 2000 complete in 118.9 sec
[-----------------60%---               ] 1214 of 2000 complete in 119.5 sec
[-----------------61%---               ] 1220 of 2000 complete in 120.1 sec
[-----------------61%---               ] 1226 of 2000 complete in 120.7 sec
[-----------------61%---               ] 1232 of 2000 complete in 121.3 sec
[-----------------61%---               ] 1238 of 2000 complete in 121.9 sec
[-----------------62%---               ] 1244 of 2000 complete in 122.4 sec
[-----------------62%---               ] 1249 of 2000 complete in 123.0 sec
[-----------------62%---               ] 1255 of 2000 complete in 123.6 sec
[-----------------62%---               ] 1259 of 2000 complete in 124.1 sec
[-----------------63%----              ] 1264 of 2000 complete in 124.6 sec
[-----------------63%----              ] 1269 of 2000 complete in 125.2 sec
[-----------------63%----              ] 1274 of 2000 complete in 125.8 sec
[-----------------63%----              ] 1279 of 2000 complete in 126.4 sec
[-----------------64%----              ] 1284 of 2000 complete in 127.0 sec
[-----------------64%----              ] 1289 of 2000 complete in 127.5 sec
[-----------------64%----              ] 1294 of 2000 complete in 128.1 sec
[-----------------64%----              ] 1299 of 2000 complete in 128.6 sec
[-----------------65%----              ] 1304 of 2000 complete in 129.2 sec
[-----------------65%----              ] 1309 of 2000 complete in 129.7 sec
[-----------------65%----              ] 1314 of 2000 complete in 130.2 sec
[-----------------65%-----             ] 1319 of 2000 complete in 130.7 sec
[-----------------66%-----             ] 1324 of 2000 complete in 131.2 sec
[-----------------66%-----             ] 1329 of 2000 complete in 131.7 sec
[-----------------66%-----             ] 1334 of 2000 complete in 132.2 sec
[-----------------66%-----             ] 1339 of 2000 complete in 132.7 sec
[-----------------67%-----             ] 1344 of 2000 complete in 133.3 sec
[-----------------67%-----             ] 1349 of 2000 complete in 133.8 sec
[-----------------67%-----             ] 1354 of 2000 complete in 134.3 sec
[-----------------67%-----             ] 1359 of 2000 complete in 134.9 sec
[-----------------68%-----             ] 1364 of 2000 complete in 135.5 sec
[-----------------68%------            ] 1369 of 2000 complete in 136.1 sec
[-----------------68%------            ] 1374 of 2000 complete in 136.6 sec
[-----------------68%------            ] 1379 of 2000 complete in 137.2 sec
[-----------------69%------            ] 1384 of 2000 complete in 137.7 sec
[-----------------69%------            ] 1389 of 2000 complete in 138.2 sec
[-----------------69%------            ] 1395 of 2000 complete in 138.8 sec
[-----------------70%------            ] 1401 of 2000 complete in 139.4 sec
[-----------------70%------            ] 1406 of 2000 complete in 140.0 sec
[-----------------70%------            ] 1411 of 2000 complete in 140.5 sec
[-----------------70%------            ] 1416 of 2000 complete in 141.1 sec
[-----------------71%-------           ] 1422 of 2000 complete in 141.7 sec
[-----------------71%-------           ] 1427 of 2000 complete in 142.2 sec
[-----------------71%-------           ] 1432 of 2000 complete in 142.7 sec
[-----------------71%-------           ] 1437 of 2000 complete in 143.2 sec
[-----------------72%-------           ] 1442 of 2000 complete in 143.8 sec
[-----------------72%-------           ] 1447 of 2000 complete in 144.3 sec
[-----------------72%-------           ] 1452 of 2000 complete in 144.8 sec
[-----------------72%-------           ] 1458 of 2000 complete in 145.4 sec
[-----------------73%-------           ] 1463 of 2000 complete in 146.0 sec
[-----------------73%-------           ] 1468 of 2000 complete in 146.5 sec
[-----------------73%-------           ] 1473 of 2000 complete in 147.1 sec
[-----------------73%--------          ] 1478 of 2000 complete in 147.6 sec
[-----------------74%--------          ] 1483 of 2000 complete in 148.1 sec
[-----------------74%--------          ] 1488 of 2000 complete in 148.6 sec
[-----------------74%--------          ] 1493 of 2000 complete in 149.2 sec
[-----------------74%--------          ] 1497 of 2000 complete in 149.8 sec
[-----------------75%--------          ] 1501 of 2000 complete in 150.3 sec
[-----------------75%--------          ] 1506 of 2000 complete in 150.8 sec
[-----------------75%--------          ] 1511 of 2000 complete in 151.4 sec
[-----------------75%--------          ] 1516 of 2000 complete in 152.0 sec
[-----------------76%--------          ] 1521 of 2000 complete in 152.6 sec
[-----------------76%--------          ] 1525 of 2000 complete in 153.1 sec
[-----------------76%---------         ] 1530 of 2000 complete in 153.7 sec
[-----------------76%---------         ] 1535 of 2000 complete in 154.2 sec
[-----------------77%---------         ] 1540 of 2000 complete in 154.8 sec
[-----------------77%---------         ] 1545 of 2000 complete in 155.4 sec
[-----------------77%---------         ] 1550 of 2000 complete in 155.9 sec
[-----------------77%---------         ] 1556 of 2000 complete in 156.5 sec
[-----------------78%---------         ] 1561 of 2000 complete in 157.1 sec
[-----------------78%---------         ] 1566 of 2000 complete in 157.6 sec
[-----------------78%---------         ] 1571 of 2000 complete in 158.1 sec
[-----------------78%---------         ] 1576 of 2000 complete in 158.6 sec
[-----------------79%----------        ] 1581 of 2000 complete in 159.1 sec
[-----------------79%----------        ] 1586 of 2000 complete in 159.7 sec
[-----------------79%----------        ] 1591 of 2000 complete in 160.2 sec
[-----------------79%----------        ] 1596 of 2000 complete in 160.7 sec
[-----------------80%----------        ] 1601 of 2000 complete in 161.2 sec
[-----------------80%----------        ] 1606 of 2000 complete in 161.8 sec
[-----------------80%----------        ] 1611 of 2000 complete in 162.3 sec
[-----------------80%----------        ] 1616 of 2000 complete in 162.9 sec
[-----------------81%----------        ] 1621 of 2000 complete in 163.5 sec
[-----------------81%----------        ] 1626 of 2000 complete in 164.1 sec
[-----------------81%----------        ] 1631 of 2000 complete in 164.6 sec
[-----------------81%-----------       ] 1636 of 2000 complete in 165.1 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 165.7 sec
[-----------------82%-----------       ] 1646 of 2000 complete in 166.2 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 166.7 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 167.3 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 167.8 sec

[-----------------59%--                ] 1184 of 2000 complete in 115.6 sec
[-----------------59%--                ] 1190 of 2000 complete in 116.1 sec
[-----------------59%--                ] 1196 of 2000 complete in 116.7 sec
[-----------------60%--                ] 1201 of 2000 complete in 117.2 sec
[-----------------60%--                ] 1207 of 2000 complete in 117.8 sec
[-----------------60%---               ] 1213 of 2000 complete in 118.4 sec
[-----------------60%---               ] 1219 of 2000 complete in 119.0 sec
[-----------------61%---               ] 1225 of 2000 complete in 119.6 sec
[-----------------61%---               ] 1231 of 2000 complete in 120.2 sec
[-----------------61%---               ] 1237 of 2000 complete in 120.8 sec
[-----------------62%---               ] 1243 of 2000 complete in 121.4 sec
[-----------------62%---               ] 1249 of 2000 complete in 122.0 sec
[-----------------62%---               ] 1255 of 2000 complete in 122.5 sec
[-----------------63%---               ] 1260 of 2000 complete in 123.0 sec
[-----------------63%----              ] 1265 of 2000 complete in 123.5 sec
[-----------------63%----              ] 1270 of 2000 complete in 124.2 sec
[-----------------63%----              ] 1275 of 2000 complete in 124.7 sec
[-----------------64%----              ] 1280 of 2000 complete in 125.3 sec
[-----------------64%----              ] 1285 of 2000 complete in 125.9 sec
[-----------------64%----              ] 1290 of 2000 complete in 126.5 sec
[-----------------64%----              ] 1295 of 2000 complete in 127.0 sec
[-----------------65%----              ] 1300 of 2000 complete in 127.5 sec
[-----------------65%----              ] 1305 of 2000 complete in 128.1 sec
[-----------------65%----              ] 1310 of 2000 complete in 128.6 sec
[-----------------65%----              ] 1315 of 2000 complete in 129.1 sec
[-----------------66%-----             ] 1320 of 2000 complete in 129.7 sec
[-----------------66%-----             ] 1325 of 2000 complete in 130.2 sec
[-----------------66%-----             ] 1331 of 2000 complete in 130.7 sec
[-----------------66%-----             ] 1336 of 2000 complete in 131.3 sec
[-----------------67%-----             ] 1341 of 2000 complete in 131.8 sec
[-----------------67%-----             ] 1346 of 2000 complete in 132.3 sec
[-----------------67%-----             ] 1351 of 2000 complete in 132.8 sec
[-----------------67%-----             ] 1357 of 2000 complete in 133.4 sec
[-----------------68%-----             ] 1362 of 2000 complete in 134.0 sec
[-----------------68%-----             ] 1367 of 2000 complete in 134.5 sec
[-----------------68%------            ] 1372 of 2000 complete in 135.1 sec
[-----------------68%------            ] 1377 of 2000 complete in 135.7 sec
[-----------------69%------            ] 1382 of 2000 complete in 136.2 sec
[-----------------69%------            ] 1387 of 2000 complete in 136.8 sec
[-----------------69%------            ] 1392 of 2000 complete in 137.4 sec
[-----------------69%------            ] 1397 of 2000 complete in 137.9 sec
[-----------------70%------            ] 1402 of 2000 complete in 138.4 sec
[-----------------70%------            ] 1407 of 2000 complete in 138.9 sec
[-----------------70%------            ] 1413 of 2000 complete in 139.5 sec
[-----------------70%------            ] 1418 of 2000 complete in 140.0 sec
[-----------------71%-------           ] 1423 of 2000 complete in 140.6 sec
[-----------------71%-------           ] 1428 of 2000 complete in 141.1 sec
[-----------------71%-------           ] 1434 of 2000 complete in 141.7 sec
[-----------------71%-------           ] 1439 of 2000 complete in 142.3 sec
[-----------------72%-------           ] 1444 of 2000 complete in 142.8 sec
[-----------------72%-------           ] 1450 of 2000 complete in 143.4 sec
[-----------------72%-------           ] 1455 of 2000 complete in 143.9 sec
[-----------------73%-------           ] 1460 of 2000 complete in 144.5 sec
[-----------------73%-------           ] 1465 of 2000 complete in 145.0 sec
[-----------------73%-------           ] 1470 of 2000 complete in 145.5 sec
[-----------------73%--------          ] 1475 of 2000 complete in 146.0 sec
[-----------------74%--------          ] 1480 of 2000 complete in 146.6 sec
[-----------------74%--------          ] 1485 of 2000 complete in 147.1 sec
[-----------------74%--------          ] 1490 of 2000 complete in 147.7 sec
[-----------------74%--------          ] 1495 of 2000 complete in 148.2 sec
[-----------------75%--------          ] 1500 of 2000 complete in 148.8 sec
[-----------------75%--------          ] 1505 of 2000 complete in 149.3 sec
[-----------------75%--------          ] 1509 of 2000 complete in 149.9 sec
[-----------------75%--------          ] 1514 of 2000 complete in 150.5 sec
[-----------------75%--------          ] 1519 of 2000 complete in 151.0 sec
[-----------------76%--------          ] 1524 of 2000 complete in 151.6 sec
[-----------------76%---------         ] 1529 of 2000 complete in 152.2 sec
[-----------------76%---------         ] 1534 of 2000 complete in 152.8 sec
[-----------------76%---------         ] 1539 of 2000 complete in 153.4 sec
[-----------------77%---------         ] 1544 of 2000 complete in 153.9 sec
[-----------------77%---------         ] 1549 of 2000 complete in 154.5 sec
[-----------------77%---------         ] 1554 of 2000 complete in 155.1 sec
[-----------------77%---------         ] 1559 of 2000 complete in 155.6 sec
[-----------------78%---------         ] 1564 of 2000 complete in 156.1 sec
[-----------------78%---------         ] 1569 of 2000 complete in 156.6 sec
[-----------------78%---------         ] 1574 of 2000 complete in 157.2 sec
[-----------------78%----------        ] 1579 of 2000 complete in 157.7 sec
[-----------------79%----------        ] 1584 of 2000 complete in 158.2 sec
[-----------------79%----------        ] 1589 of 2000 complete in 158.8 sec
[-----------------79%----------        ] 1594 of 2000 complete in 159.3 sec
[-----------------79%----------        ] 1599 of 2000 complete in 159.8 sec
[-----------------80%----------        ] 1604 of 2000 complete in 160.3 sec
[-----------------80%----------        ] 1609 of 2000 complete in 160.9 sec
[-----------------80%----------        ] 1614 of 2000 complete in 161.4 sec
[-----------------80%----------        ] 1619 of 2000 complete in 161.9 sec
[-----------------81%----------        ] 1624 of 2000 complete in 162.5 sec
[-----------------81%----------        ] 1629 of 2000 complete in 163.0 sec
[-----------------81%-----------       ] 1634 of 2000 complete in 163.6 sec
[-----------------81%-----------       ] 1639 of 2000 complete in 164.2 sec
[-----------------82%-----------       ] 1644 of 2000 complete in 164.7 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 165.3 sec
[-----------------82%-----------       ] 1654 of 2000 complete in 165.8 sec
[-----------------82%-----------       ] 1659 of 2000 complete in 166.3 sec
[-----------------83%-----------       ] 1664 of 2000 complete in 166.9 sec
[-----------------83%-----------       ] 1669 of 2000 complete in 167.4 sec
[-----------------83%-----------       ] 1674 of 2000 complete in 168.0 sec
[-----------------83%-----------       ] 1679 of 2000 complete in 168.6 sec
[-----------------84%-----------       ] 1684 of 2000 complete in 169.1 sec
[-----------------84%------------      ] 1689 of 2000 complete in 169.7 sec
[-----------------84%------------      ] 1694 of 2000 complete in 170.2 sec
[-----------------84%------------      ] 1699 of 2000 complete in 170.8 sec
[-----------------85%------------      ] 1704 of 2000 complete in 171.3 sec
[-----------------85%------------      ] 1709 of 2000 complete in 171.9 sec
[-----------------85%------------      ] 1714 of 2000 complete in 172.4 sec
[-----------------85%------------      ] 1719 of 2000 complete in 173.0 sec
[-----------------86%------------      ] 1724 of 2000 complete in 173.5 sec
[-----------------86%------------      ] 1729 of 2000 complete in 174.1 sec
[-----------------59%--                ] 1190 of 2000 complete in 117.6 sec
[-----------------59%--                ] 1196 of 2000 complete in 118.2 sec
[-----------------60%--                ] 1201 of 2000 complete in 118.7 sec
[-----------------60%--                ] 1207 of 2000 complete in 119.3 sec
[-----------------60%---               ] 1213 of 2000 complete in 119.9 sec
[-----------------60%---               ] 1219 of 2000 complete in 120.5 sec
[-----------------61%---               ] 1224 of 2000 complete in 121.0 sec
[-----------------61%---               ] 1230 of 2000 complete in 121.6 sec
[-----------------61%---               ] 1236 of 2000 complete in 122.2 sec
[-----------------62%---               ] 1242 of 2000 complete in 122.8 sec
[-----------------62%---               ] 1248 of 2000 complete in 123.3 sec
[-----------------62%---               ] 1253 of 2000 complete in 123.9 sec
[-----------------62%---               ] 1258 of 2000 complete in 124.5 sec
[-----------------63%---               ] 1263 of 2000 complete in 125.0 sec
[-----------------63%----              ] 1268 of 2000 complete in 125.6 sec
[-----------------63%----              ] 1273 of 2000 complete in 126.2 sec
[-----------------63%----              ] 1278 of 2000 complete in 126.8 sec
[-----------------64%----              ] 1283 of 2000 complete in 127.3 sec
[-----------------64%----              ] 1288 of 2000 complete in 127.9 sec
[-----------------64%----              ] 1293 of 2000 complete in 128.4 sec
[-----------------64%----              ] 1298 of 2000 complete in 128.9 sec
[-----------------65%----              ] 1303 of 2000 complete in 129.4 sec
[-----------------65%----              ] 1308 of 2000 complete in 130.0 sec
[-----------------65%----              ] 1314 of 2000 complete in 130.5 sec
[-----------------66%-----             ] 1320 of 2000 complete in 131.1 sec
[-----------------66%-----             ] 1326 of 2000 complete in 131.7 sec
[-----------------66%-----             ] 1331 of 2000 complete in 132.2 sec
[-----------------66%-----             ] 1336 of 2000 complete in 132.8 sec
[-----------------67%-----             ] 1341 of 2000 complete in 133.3 sec
[-----------------67%-----             ] 1346 of 2000 complete in 133.8 sec
[-----------------67%-----             ] 1351 of 2000 complete in 134.3 sec
[-----------------67%-----             ] 1356 of 2000 complete in 134.9 sec
[-----------------68%-----             ] 1361 of 2000 complete in 135.5 sec
[-----------------68%-----             ] 1366 of 2000 complete in 136.0 sec
[-----------------68%------            ] 1371 of 2000 complete in 136.6 sec
[-----------------68%------            ] 1376 of 2000 complete in 137.2 sec
[-----------------69%------            ] 1381 of 2000 complete in 137.7 sec
[-----------------69%------            ] 1386 of 2000 complete in 138.2 sec
[-----------------69%------            ] 1391 of 2000 complete in 138.7 sec
[-----------------69%------            ] 1396 of 2000 complete in 139.3 sec
[-----------------70%------            ] 1401 of 2000 complete in 139.8 sec
[-----------------70%------            ] 1406 of 2000 complete in 140.3 sec
[-----------------70%------            ] 1411 of 2000 complete in 140.8 sec
[-----------------70%------            ] 1416 of 2000 complete in 141.4 sec
[-----------------71%------            ] 1421 of 2000 complete in 141.9 sec
[-----------------71%-------           ] 1426 of 2000 complete in 142.4 sec
[-----------------71%-------           ] 1431 of 2000 complete in 142.9 sec
[-----------------71%-------           ] 1436 of 2000 complete in 143.4 sec
[-----------------72%-------           ] 1441 of 2000 complete in 143.9 sec
[-----------------72%-------           ] 1446 of 2000 complete in 144.5 sec
[-----------------72%-------           ] 1451 of 2000 complete in 145.0 sec
[-----------------72%-------           ] 1456 of 2000 complete in 145.5 sec
[-----------------73%-------           ] 1461 of 2000 complete in 146.1 sec
[-----------------73%-------           ] 1466 of 2000 complete in 146.6 sec
[-----------------73%-------           ] 1471 of 2000 complete in 147.1 sec
[-----------------73%--------          ] 1476 of 2000 complete in 147.7 sec
[-----------------74%--------          ] 1481 of 2000 complete in 148.2 sec
[-----------------74%--------          ] 1486 of 2000 complete in 148.7 sec
[-----------------74%--------          ] 1491 of 2000 complete in 149.3 sec
[-----------------74%--------          ] 1495 of 2000 complete in 149.8 sec
[-----------------75%--------          ] 1500 of 2000 complete in 150.4 sec
[-----------------75%--------          ] 1505 of 2000 complete in 151.0 sec
[-----------------75%--------          ] 1510 of 2000 complete in 151.5 sec
[-----------------75%--------          ] 1515 of 2000 complete in 152.1 sec
[-----------------76%--------          ] 1520 of 2000 complete in 152.7 sec
[-----------------76%--------          ] 1525 of 2000 complete in 153.3 sec
[-----------------76%---------         ] 1530 of 2000 complete in 153.9 sec
[-----------------76%---------         ] 1535 of 2000 complete in 154.4 sec
[-----------------77%---------         ] 1540 of 2000 complete in 155.0 sec
[-----------------77%---------         ] 1545 of 2000 complete in 155.5 sec
[-----------------77%---------         ] 1550 of 2000 complete in 156.1 sec
[-----------------77%---------         ] 1555 of 2000 complete in 156.6 sec
[-----------------78%---------         ] 1560 of 2000 complete in 157.1 sec
[-----------------78%---------         ] 1565 of 2000 complete in 157.6 sec
[-----------------78%---------         ] 1570 of 2000 complete in 158.1 sec
[-----------------78%---------         ] 1575 of 2000 complete in 158.7 sec
[-----------------79%----------        ] 1580 of 2000 complete in 159.2 sec
[-----------------79%----------        ] 1585 of 2000 complete in 159.7 sec
[-----------------79%----------        ] 1590 of 2000 complete in 160.2 sec
[-----------------79%----------        ] 1595 of 2000 complete in 160.7 sec
[-----------------80%----------        ] 1601 of 2000 complete in 161.3 sec
[-----------------80%----------        ] 1606 of 2000 complete in 161.9 sec
[-----------------80%----------        ] 1611 of 2000 complete in 162.4 sec
[-----------------80%----------        ] 1616 of 2000 complete in 163.0 sec
[-----------------81%----------        ] 1621 of 2000 complete in 163.5 sec
[-----------------81%----------        ] 1626 of 2000 complete in 164.1 sec
[-----------------81%----------        ] 1631 of 2000 complete in 164.6 sec
[-----------------81%-----------       ] 1636 of 2000 complete in 165.2 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 165.7 sec
[-----------------82%-----------       ] 1646 of 2000 complete in 166.2 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 166.8 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 167.3 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 167.8 sec
[-----------------83%-----------       ] 1666 of 2000 complete in 168.4 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 169.0 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 169.5 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 170.1 sec
[-----------------84%------------      ] 1686 of 2000 complete in 170.6 sec
[-----------------84%------------      ] 1691 of 2000 complete in 171.1 sec
[-----------------84%------------      ] 1696 of 2000 complete in 171.7 sec
[-----------------85%------------      ] 1701 of 2000 complete in 172.2 sec
[-----------------85%------------      ] 1706 of 2000 complete in 172.7 sec
[-----------------85%------------      ] 1711 of 2000 complete in 173.3 sec
[-----------------85%------------      ] 1716 of 2000 complete in 173.8 sec
[-----------------86%------------      ] 1721 of 2000 complete in 174.4 sec
[-----------------86%------------      ] 1726 of 2000 complete in 174.9 sec
[-----------------86%------------      ] 1731 of 2000 complete in 175.5 sec

hddm sampling elpased time:  224.99 s
Start converting to InferenceData...

In [21]:
# model summary
az.summary(hddmStim_vflip_dc_m1_idata)

,mean,sd,hdi_3%,hdi_97%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
a,2.050,0.180,1.724,2.388,0.035,0.025,28.0,103.0,1.09
a_std,0.989,0.165,0.701,1.306,0.033,0.024,26.0,115.0,1.10
a_subj.7304,1.989,0.714,1.300,3.342,0.277,0.205,10.0,62.0,1.32
a_subj.7305,1.736,0.099,1.554,1.917,0.003,0.002,842.0,987.0,1.00
a_subj.7306,1.391,0.081,1.253,1.551,0.003,0.002,678.0,1283.0,1.01
...,...,...,...,...,...,...,...,...,...
dc_subj(Self).7342,-0.687,1.315,-3.211,1.647,0.584,0.440,5.0,27.0,2.15
dc_subj(Self).7343,0.535,1.034,-1.274,2.259,0.332,0.242,11.0,30.0,1.30
dc_subj(Self).7344,-0.581,1.226,-3.081,1.445,0.529,0.397,6.0,27.0,1.92
dc_subj(Self).7345,-0.285,1.298,-2.843,1.933,0.569,0.428,5.0,19.0,2.01
dc_subj(Self).73370,0.525,1.216,-2.096,2.385,0.506,0.377,6.0,22.0,1.70

[-----------------86%------------      ] 1734 of 2000 complete in 174.6 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 175.2 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 175.8 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 176.4 sec
[-----------------87%-------------     ] 1754 of 2000 complete in 177.0 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 177.6 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 178.1 sec
[-----------------88%-------------     ] 1768 of 2000 complete in 178.7 sec
[-----------------88%-------------     ] 1773 of 2000 complete in 179.3 sec
[-----------------88%-------------     ] 1778 of 2000 complete in 179.9 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 180.5 sec
[-----------------89%-------------     ] 1788 of 2000 complete in 181.0 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 181.6 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 182.2 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 182.8 sec
[-----------------90%--------------    ] 1808 of 2000 complete in 183.3 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 183.9 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 184.4 sec
[-----------------91%--------------    ] 1823 of 2000 complete in 185.0 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 185.6 sec
[-----------------91%--------------    ] 1833 of 2000 complete in 186.1 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 186.6 sec
[-----------------92%---------------   ] 1843 of 2000 complete in 187.2 sec
[-----------------92%---------------   ] 1847 of 2000 complete in 187.7 sec
[-----------------92%---------------   ] 1852 of 2000 complete in 188.3 sec
[-----------------92%---------------   ] 1857 of 2000 complete in 188.8 sec
[-----------------93%---------------   ] 1862 of 2000 complete in 189.3 sec
[-----------------93%---------------   ] 1867 of 2000 complete in 189.9 sec
[-----------------93%---------------   ] 1872 of 2000 complete in 190.4 sec
[-----------------93%---------------   ] 1877 of 2000 complete in 191.0 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 191.5 sec
[-----------------94%---------------   ] 1887 of 2000 complete in 192.1 sec
[-----------------94%---------------   ] 1892 of 2000 complete in 192.6 sec
[-----------------94%----------------  ] 1897 of 2000 complete in 193.2 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 193.8 sec
[-----------------95%----------------  ] 1907 of 2000 complete in 194.3 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 194.9 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 195.4 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 196.0 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 196.5 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 197.1 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 197.6 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 198.2 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 198.7 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 199.2 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 199.8 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 200.3 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 200.8 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 201.4 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 201.9 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 202.4 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 203.0 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 203.5 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 204.1 sec
[-----------------100%-----------------] 2000 of 2000 complete in 204.5 sec
hddm sampling elpased time:  204.658 s
[-----------------86%------------      ] 1736 of 2000 complete in 176.1 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 176.7 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 177.3 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 177.8 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 178.4 sec
[-----------------88%-------------     ] 1760 of 2000 complete in 178.9 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 179.5 sec
[-----------------88%-------------     ] 1770 of 2000 complete in 180.1 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 180.7 sec
[-----------------89%-------------     ] 1780 of 2000 complete in 181.3 sec
[-----------------89%-------------     ] 1785 of 2000 complete in 181.9 sec
[-----------------89%--------------    ] 1790 of 2000 complete in 182.4 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 183.0 sec
[-----------------90%--------------    ] 1800 of 2000 complete in 183.5 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 184.1 sec
[-----------------90%--------------    ] 1810 of 2000 complete in 184.6 sec
[-----------------90%--------------    ] 1815 of 2000 complete in 185.2 sec
[-----------------91%--------------    ] 1820 of 2000 complete in 185.7 sec
[-----------------91%--------------    ] 1825 of 2000 complete in 186.2 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 186.8 sec
[-----------------91%--------------    ] 1835 of 2000 complete in 187.3 sec
[-----------------91%--------------    ] 1839 of 2000 complete in 187.8 sec
[-----------------92%---------------   ] 1844 of 2000 complete in 188.4 sec
[-----------------92%---------------   ] 1849 of 2000 complete in 188.9 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 189.4 sec
[-----------------92%---------------   ] 1859 of 2000 complete in 190.0 sec
[-----------------93%---------------   ] 1864 of 2000 complete in 190.5 sec
[-----------------93%---------------   ] 1869 of 2000 complete in 191.0 sec
[-----------------93%---------------   ] 1874 of 2000 complete in 191.6 sec
[-----------------93%---------------   ] 1879 of 2000 complete in 192.1 sec
[-----------------94%---------------   ] 1884 of 2000 complete in 192.7 sec
[-----------------94%---------------   ] 1889 of 2000 complete in 193.2 sec
[-----------------94%---------------   ] 1894 of 2000 complete in 193.8 sec
[-----------------94%----------------  ] 1899 of 2000 complete in 194.4 sec
[-----------------95%----------------  ] 1904 of 2000 complete in 194.9 sec
[-----------------95%----------------  ] 1909 of 2000 complete in 195.4 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 196.0 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 196.5 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 197.0 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 197.6 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 198.1 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 198.7 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 199.2 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 199.8 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 200.3 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 200.8 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 201.4 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 201.9 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 202.5 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 203.0 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 203.5 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 204.1 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 204.6 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 205.2 sec
[-----------------100%-----------------] 2000 of 2000 complete in 205.4 sec
hddm sampling elpased time:  205.546 s

[-----------------83%-----------       ] 1666 of 2000 complete in 168.4 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 168.9 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 169.5 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 170.0 sec
[-----------------84%------------      ] 1686 of 2000 complete in 170.6 sec
[-----------------84%------------      ] 1691 of 2000 complete in 171.1 sec
[-----------------84%------------      ] 1696 of 2000 complete in 171.7 sec
[-----------------85%------------      ] 1701 of 2000 complete in 172.2 sec
[-----------------85%------------      ] 1706 of 2000 complete in 172.7 sec
[-----------------85%------------      ] 1711 of 2000 complete in 173.3 sec
[-----------------85%------------      ] 1716 of 2000 complete in 173.9 sec
[-----------------86%------------      ] 1721 of 2000 complete in 174.4 sec
[-----------------86%------------      ] 1726 of 2000 complete in 175.0 sec
[-----------------86%------------      ] 1731 of 2000 complete in 175.5 sec
[-----------------86%------------      ] 1736 of 2000 complete in 176.1 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 176.7 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 177.3 sec
[-----------------87%-------------     ] 1750 of 2000 complete in 177.8 sec
[-----------------87%-------------     ] 1754 of 2000 complete in 178.3 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 179.0 sec
[-----------------88%-------------     ] 1764 of 2000 complete in 179.5 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 180.1 sec
[-----------------88%-------------     ] 1774 of 2000 complete in 180.7 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 181.3 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 181.9 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 182.5 sec
[-----------------89%--------------    ] 1794 of 2000 complete in 183.0 sec
[-----------------89%--------------    ] 1799 of 2000 complete in 183.6 sec
[-----------------90%--------------    ] 1804 of 2000 complete in 184.1 sec
[-----------------90%--------------    ] 1809 of 2000 complete in 184.7 sec
[-----------------90%--------------    ] 1814 of 2000 complete in 185.2 sec
[-----------------90%--------------    ] 1819 of 2000 complete in 185.8 sec
[-----------------91%--------------    ] 1824 of 2000 complete in 186.3 sec
[-----------------91%--------------    ] 1829 of 2000 complete in 186.9 sec
[-----------------91%--------------    ] 1834 of 2000 complete in 187.4 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 187.9 sec
[-----------------92%---------------   ] 1843 of 2000 complete in 188.5 sec
[-----------------92%---------------   ] 1848 of 2000 complete in 189.0 sec
[-----------------92%---------------   ] 1853 of 2000 complete in 189.6 sec
[-----------------92%---------------   ] 1858 of 2000 complete in 190.1 sec
[-----------------93%---------------   ] 1863 of 2000 complete in 190.7 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 191.2 sec
[-----------------93%---------------   ] 1873 of 2000 complete in 191.8 sec
[-----------------93%---------------   ] 1878 of 2000 complete in 192.3 sec
[-----------------94%---------------   ] 1883 of 2000 complete in 192.9 sec
[-----------------94%---------------   ] 1888 of 2000 complete in 193.4 sec
[-----------------94%---------------   ] 1893 of 2000 complete in 194.0 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 194.5 sec
[-----------------95%----------------  ] 1903 of 2000 complete in 195.1 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 195.6 sec
[-----------------95%----------------  ] 1913 of 2000 complete in 196.2 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 196.7 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 197.2 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 197.8 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 198.3 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 198.9 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 199.4 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 200.0 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 200.5 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 201.0 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 201.6 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 202.1 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 202.7 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 203.2 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 203.8 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 204.3 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 204.9 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 205.4 sec
[-----------------100%-----------------] 2000 of 2000 complete in 205.7 sec
hddm sampling elpased time:  205.923 s
[-----------------74%--------          ] 1483 of 2000 complete in 151.9 sec
[-----------------74%--------          ] 1488 of 2000 complete in 152.5 sec
[-----------------74%--------          ] 1492 of 2000 complete in 153.0 sec
[-----------------74%--------          ] 1497 of 2000 complete in 153.6 sec
[-----------------75%--------          ] 1502 of 2000 complete in 154.2 sec
[-----------------75%--------          ] 1507 of 2000 complete in 154.7 sec
[-----------------75%--------          ] 1512 of 2000 complete in 155.3 sec
[-----------------75%--------          ] 1517 of 2000 complete in 155.8 sec
[-----------------76%--------          ] 1522 of 2000 complete in 156.3 sec
[-----------------76%---------         ] 1527 of 2000 complete in 156.9 sec
[-----------------76%---------         ] 1532 of 2000 complete in 157.5 sec
[-----------------76%---------         ] 1537 of 2000 complete in 158.0 sec
[-----------------77%---------         ] 1542 of 2000 complete in 158.5 sec
[-----------------77%---------         ] 1547 of 2000 complete in 159.1 sec
[-----------------77%---------         ] 1552 of 2000 complete in 159.6 sec
[-----------------77%---------         ] 1557 of 2000 complete in 160.1 sec
[-----------------78%---------         ] 1562 of 2000 complete in 160.7 sec
[-----------------78%---------         ] 1567 of 2000 complete in 161.2 sec
[-----------------78%---------         ] 1572 of 2000 complete in 161.8 sec
[-----------------78%---------         ] 1577 of 2000 complete in 162.3 sec
[-----------------79%----------        ] 1582 of 2000 complete in 162.9 sec
[-----------------79%----------        ] 1587 of 2000 complete in 163.5 sec
[-----------------79%----------        ] 1592 of 2000 complete in 164.1 sec
[-----------------79%----------        ] 1597 of 2000 complete in 164.6 sec
[-----------------80%----------        ] 1602 of 2000 complete in 165.2 sec
[-----------------80%----------        ] 1607 of 2000 complete in 165.7 sec
[-----------------80%----------        ] 1612 of 2000 complete in 166.3 sec
[-----------------80%----------        ] 1617 of 2000 complete in 166.8 sec
[-----------------81%----------        ] 1622 of 2000 complete in 167.4 sec
[-----------------81%----------        ] 1627 of 2000 complete in 168.0 sec
[-----------------81%-----------       ] 1632 of 2000 complete in 168.5 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 169.1 sec
[-----------------82%-----------       ] 1642 of 2000 complete in 169.7 sec
[-----------------82%-----------       ] 1647 of 2000 complete in 170.2 sec
[-----------------82%-----------       ] 1652 of 2000 complete in 170.8 sec
[-----------------82%-----------       ] 1657 of 2000 complete in 171.3 sec
[-----------------83%-----------       ] 1662 of 2000 complete in 171.9 sec
[-----------------83%-----------       ] 1667 of 2000 complete in 172.4 sec
[-----------------83%-----------       ] 1672 of 2000 complete in 173.0 sec
[-----------------83%-----------       ] 1677 of 2000 complete in 173.5 sec
[-----------------84%-----------       ] 1682 of 2000 complete in 174.1 sec
[-----------------84%------------      ] 1687 of 2000 complete in 174.7 sec
[-----------------84%------------      ] 1692 of 2000 complete in 175.2 sec
[-----------------84%------------      ] 1697 of 2000 complete in 175.8 sec
[-----------------85%------------      ] 1702 of 2000 complete in 176.4 sec
[-----------------85%------------      ] 1707 of 2000 complete in 177.0 sec
[-----------------85%------------      ] 1712 of 2000 complete in 177.6 sec
[-----------------85%------------      ] 1716 of 2000 complete in 178.2 sec
[-----------------86%------------      ] 1720 of 2000 complete in 178.7 sec
[-----------------86%------------      ] 1724 of 2000 complete in 179.2 sec
[-----------------86%------------      ] 1729 of 2000 complete in 179.8 sec
[-----------------86%------------      ] 1734 of 2000 complete in 180.4 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 181.0 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 181.6 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 182.2 sec
[-----------------87%-------------     ] 1754 of 2000 complete in 182.7 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 183.3 sec
[-----------------88%-------------     ] 1764 of 2000 complete in 183.9 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 184.4 sec
[-----------------88%-------------     ] 1774 of 2000 complete in 185.0 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 185.5 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 186.1 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 186.6 sec
[-----------------89%--------------    ] 1794 of 2000 complete in 187.2 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 187.7 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 188.3 sec
[-----------------90%--------------    ] 1808 of 2000 complete in 188.9 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 189.4 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 190.0 sec
[-----------------91%--------------    ] 1823 of 2000 complete in 190.6 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 191.1 sec
[-----------------91%--------------    ] 1833 of 2000 complete in 191.7 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 192.3 sec
[-----------------92%---------------   ] 1843 of 2000 complete in 192.8 sec
[-----------------92%---------------   ] 1848 of 2000 complete in 193.4 sec
[-----------------92%---------------   ] 1853 of 2000 complete in 194.0 sec
[-----------------92%---------------   ] 1858 of 2000 complete in 194.5 sec
[-----------------93%---------------   ] 1863 of 2000 complete in 195.1 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 195.6 sec
[-----------------93%---------------   ] 1873 of 2000 complete in 196.2 sec
[-----------------93%---------------   ] 1878 of 2000 complete in 196.7 sec
[-----------------94%---------------   ] 1883 of 2000 complete in 197.3 sec
[-----------------94%---------------   ] 1888 of 2000 complete in 197.9 sec
[-----------------94%---------------   ] 1893 of 2000 complete in 198.4 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 199.0 sec
[-----------------95%----------------  ] 1903 of 2000 complete in 199.5 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 200.1 sec
[-----------------95%----------------  ] 1913 of 2000 complete in 200.6 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 201.2 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 201.7 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 202.3 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 202.9 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 203.4 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 204.0 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 204.5 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 205.1 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 205.6 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 206.2 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 206.7 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 207.2 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 207.8 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 208.3 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 208.8 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 209.3 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 209.8 sec
[-----------------100%-----------------] 2000 of 2000 complete in 210.1 sec
hddm sampling elpased time:  210.309 s

In [22]:
hddmStim_vflip_dc_m1_stats = hddmStim_vflip_dc_m1.gen_stats()
hddmStim_vflip_dc_m1_stats[hddmStim_vflip_dc_m1_stats.index.isin(['a', 'z', 'v', 'dc(Self)', 'dc(Other)'])]

,mean,std,2.5q,25q,50q,75q,97.5q,mc err
a,2.050306,0.179803,1.728572,1.925511,2.039999,2.162563,2.433044,0.009784
z,0.540915,0.006224,0.528607,0.536715,0.540845,0.545097,0.553285,0.000287
dc(Other),-1.493223,0.671067,-2.82605,-1.972389,-1.420472,-1.033564,-0.239602,0.064631
dc(Self),-0.113159,1.115641,-2.421948,-0.591783,0.013326,0.75642,1.492218,0.110072

In [24]:
data['response'] = data['acc']

# stimCoding z flip 
hddmStim_zflip_m1_diff = hddm.HDDMStimCoding(
    data,
    stim_col='stim',
    split_param='z',
    #drift_criterion=True,
    depends_on={'v':['id','stim']},
    bias =True,
    include=['v', 'a', 't'],
)

hddmStim_zflip_m1_diff_idata = hddmStim_zflip_m1_diff.sample(2000, burn=500, chains=4, return_infdata=True, dbname = 'hddmStim_zflip_m1_diff.db', db = 'pickle')
hddmStim_zflip_m1_diff.save('hddmStim_zflip_m1_diff.hddm')

Setting model to be non-informative
Adding z to includes.
No model attribute --> setting up standard HDDM
Set model to ddm

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

[                  0%                  ] 6 of 2000 complete in 0.5 sec
[                  0%                  ] 11 of 2000 complete in 1.0 sec
[                  0%                  ] 16 of 2000 complete in 1.6 sec
[                  1%                  ] 21 of 2000 complete in 2.1 sec
[                  1%                  ] 26 of 2000 complete in 2.6 sec
[                  1%                  ] 31 of 2000 complete in 3.1 sec
[                  1%                  ] 36 of 2000 complete in 3.6 sec
[                  2%                  ] 41 of 2000 complete in 4.2 sec
[                  2%                  ] 46 of 2000 complete in 4.7 sec
[                  2%                  ] 51 of 2000 complete in 5.2 sec
[-                 2%                  ] 56 of 2000 complete in 5.7 sec
[-                 3%                  ] 61 of 2000 complete in 6.2 sec
[-                 3%                  ] 66 of 2000 complete in 6.7 sec
[-                 3%                  ] 71 of 2000 complete in 7.2 sec
[-                 3%                  ] 76 of 2000 complete in 7.7 sec
[-                 4%                  ] 81 of 2000 complete in 8.3 sec
[-                 4%                  ] 86 of 2000 complete in 8.8 sec
[-                 4%                  ] 91 of 2000 complete in 9.3 sec
[-                 4%                  ] 96 of 2000 complete in 9.8 sec
[-                 5%                  ] 101 of 2000 complete in 10.4 sec
[--                5%                  ] 106 of 2000 complete in 11.0 sec
[--                5%                  ] 111 of 2000 complete in 11.5 sec
[--                5%                  ] 116 of 2000 complete in 12.0 sec
[--                6%                  ] 121 of 2000 complete in 12.5 sec
[--                6%                  ] 126 of 2000 complete in 13.1 sec
[--                6%                  ] 131 of 2000 complete in 13.7 sec
[--                6%                  ] 136 of 2000 complete in 14.3 sec
[--                7%                  ] 141 of 2000 complete in 14.8 sec
[--                7%                  ] 146 of 2000 complete in 15.4 sec
[--                7%                  ] 151 of 2000 complete in 15.9 sec
[--                7%                  ] 156 of 2000 complete in 16.4 sec
[---               8%                  ] 161 of 2000 complete in 17.0 sec
[---               8%                  ] 166 of 2000 complete in 17.5 sec
[---               8%                  ] 171 of 2000 complete in 18.1 sec
[---               8%                  ] 176 of 2000 complete in 18.6 sec
[---               9%                  ] 181 of 2000 complete in 19.1 sec
[---               9%                  ] 186 of 2000 complete in 19.6 sec
[---               9%                  ] 191 of 2000 complete in 20.2 sec
[---               9%                  ] 196 of 2000 complete in 20.7 sec
[---              10%                  ] 201 of 2000 complete in 21.2 sec
[---              10%                  ] 206 of 2000 complete in 21.7 sec
[----             10%                  ] 211 of 2000 complete in 22.2 sec
[----             10%                  ] 216 of 2000 complete in 22.7 sec
[----             11%                  ] 221 of 2000 complete in 23.3 sec
[----             11%                  ] 226 of 2000 complete in 23.8 sec
[----             11%                  ] 231 of 2000 complete in 24.3 sec
[----             11%                  ] 236 of 2000 complete in 24.8 sec
[----             12%                  ] 241 of 2000 complete in 25.4 sec
[----             12%                  ] 246 of 2000 complete in 25.9 sec
[----             12%                  ] 251 of 2000 complete in 26.4 sec
[----             12%                  ] 256 of 2000 complete in 26.9 sec
[----             13%                  ] 261 of 2000 complete in 27.4 sec
[-----            13%                  ] 266 of 2000 complete in 27.9 sec
[-----            13%                  ] 271 of 2000 complete in 28.5 sec
[-----            13%                  ] 276 of 2000 complete in 29.0 sec
[-----            14%                  ] 281 of 2000 complete in 29.5 sec
[-----            14%                  ] 286 of 2000 complete in 30.1 sec
[-----            14%                  ] 291 of 2000 complete in 30.6 sec
[-----            14%                  ] 296 of 2000 complete in 31.1 sec
[-----            15%                  ] 300 of 2000 complete in 31.7 sec
[-----            15%                  ] 305 of 2000 complete in 32.3 sec
[-----            15%                  ] 310 of 2000 complete in 32.9 sec
[-----            15%                  ] 315 of 2000 complete in 33.5 sec
[------           16%                  ] 320 of 2000 complete in 34.0 sec
[------           16%                  ] 325 of 2000 complete in 34.6 sec
[------           16%                  ] 330 of 2000 complete in 35.2 sec
[------           16%                  ] 335 of 2000 complete in 35.8 sec
[------           17%                  ] 340 of 2000 complete in 36.3 sec
[------           17%                  ] 345 of 2000 complete in 36.9 sec
[------           17%                  ] 350 of 2000 complete in 37.4 sec
[------           17%                  ] 355 of 2000 complete in 38.0 sec
[------           18%                  ] 360 of 2000 complete in 38.5 sec
[------           18%                  ] 365 of 2000 complete in 39.0 sec
[-------          18%                  ] 370 of 2000 complete in 39.6 sec
[-------          18%                  ] 375 of 2000 complete in 40.1 sec
[-------          19%                  ] 380 of 2000 complete in 40.7 sec
[-------          19%                  ] 385 of 2000 complete in 41.2 sec
[-------          19%                  ] 390 of 2000 complete in 41.8 sec
[-------          19%                  ] 395 of 2000 complete in 42.3 sec
[-------          20%                  ] 401 of 2000 complete in 42.9 sec
[-------          20%                  ] 406 of 2000 complete in 43.4 sec
[-------          20%                  ] 411 of 2000 complete in 43.9 sec
[-------          20%                  ] 416 of 2000 complete in 44.4 sec
[-------          21%                  ] 421 of 2000 complete in 44.9 sec
[--------         21%                  ] 426 of 2000 complete in 45.5 sec
[--------         21%                  ] 431 of 2000 complete in 46.0 sec
[--------         21%                  ] 436 of 2000 complete in 46.5 sec
[--------         22%                  ] 441 of 2000 complete in 47.0 sec
[--------         22%                  ] 446 of 2000 complete in 47.5 sec
[--------         22%                  ] 451 of 2000 complete in 48.0 sec
[--------         22%                  ] 456 of 2000 complete in 48.5 sec
[--------         23%                  ] 462 of 2000 complete in 49.1 sec
[--------         23%                  ] 468 of 2000 complete in 49.7 sec
[---------        23%                  ] 474 of 2000 complete in 50.3 sec
[---------        24%                  ] 480 of 2000 complete in 50.9 sec
[---------        24%                  ] 485 of 2000 complete in 51.4 sec
[---------        24%                  ] 491 of 2000 complete in 52.0 sec
[---------        24%                  ] 496 of 2000 complete in 52.5 sec
[---------        25%                  ] 501 of 2000 complete in 53.0 sec
[---------        25%                  ] 506 of 2000 complete in 53.5 sec
[---------        25%                  ] 511 of 2000 complete in 54.0 sec
[---------        25%                  ] 516 of 2000 complete in 54.5 sec
[---------        26%                  ] 521 of 2000 complete in 55.1 sec
[----------       26%                  ] 527 of 2000 complete in 55.7 sec
[----------       26%                  ] 532 of 2000 complete in 56.2 sec
[----------       26%                  ] 538 of 2000 complete in 56.8 sec
[----------       27%                  ] 543 of 2000 complete in 57.3 sec
[----------       27%                  ] 548 of 2000 complete in 57.8 sec
[----------       27%                  ] 553 of 2000 complete in 58.3 sec
[----------       27%                  ] 558 of 2000 complete in 58.8 sec
[----------       28%                  ] 564 of 2000 complete in 59.4 sec
[                  0%                  ] 6 of 2000 complete in 0.5 sec
[                  0%                  ] 12 of 2000 complete in 1.1 sec
[                  0%                  ] 17 of 2000 complete in 1.6 sec
[                  1%                  ] 22 of 2000 complete in 2.1 sec
[                  1%                  ] 27 of 2000 complete in 2.7 sec
[                  1%                  ] 32 of 2000 complete in 3.2 sec
[                  1%                  ] 38 of 2000 complete in 3.7 sec
[                  2%                  ] 44 of 2000 complete in 4.3 sec
[                  2%                  ] 49 of 2000 complete in 4.9 sec
[-                 2%                  ] 54 of 2000 complete in 5.4 sec
[-                 2%                  ] 59 of 2000 complete in 5.9 sec
[-                 3%                  ] 64 of 2000 complete in 6.4 sec
[-                 3%                  ] 69 of 2000 complete in 6.9 sec
[-                 3%                  ] 74 of 2000 complete in 7.5 sec
[-                 3%                  ] 79 of 2000 complete in 8.0 sec
[-                 4%                  ] 84 of 2000 complete in 8.5 sec
[-                 4%                  ] 89 of 2000 complete in 9.0 sec
[-                 4%                  ] 94 of 2000 complete in 9.5 sec
[-                 4%                  ] 99 of 2000 complete in 10.0 sec
[-                 5%                  ] 104 of 2000 complete in 10.7 sec
[--                5%                  ] 109 of 2000 complete in 11.2 sec
[--                5%                  ] 114 of 2000 complete in 11.7 sec
[--                5%                  ] 119 of 2000 complete in 12.2 sec
[--                6%                  ] 124 of 2000 complete in 12.7 sec
[--                6%                  ] 129 of 2000 complete in 13.3 sec
[--                6%                  ] 133 of 2000 complete in 13.8 sec
[--                6%                  ] 138 of 2000 complete in 14.4 sec
[--                7%                  ] 143 of 2000 complete in 15.0 sec
[--                7%                  ] 148 of 2000 complete in 15.5 sec
[--                7%                  ] 153 of 2000 complete in 16.1 sec
[---               7%                  ] 158 of 2000 complete in 16.6 sec
[---               8%                  ] 163 of 2000 complete in 17.2 sec
[---               8%                  ] 168 of 2000 complete in 17.7 sec
[---               8%                  ] 173 of 2000 complete in 18.2 sec
[---               8%                  ] 179 of 2000 complete in 18.8 sec
[---               9%                  ] 184 of 2000 complete in 19.4 sec
[---               9%                  ] 189 of 2000 complete in 19.9 sec
[---               9%                  ] 194 of 2000 complete in 20.4 sec
[---              10%                  ] 200 of 2000 complete in 21.0 sec
[---              10%                  ] 205 of 2000 complete in 21.5 sec
[---              10%                  ] 210 of 2000 complete in 22.0 sec
[----             10%                  ] 215 of 2000 complete in 22.6 sec
[----             11%                  ] 220 of 2000 complete in 23.1 sec
[----             11%                  ] 225 of 2000 complete in 23.6 sec
[----             11%                  ] 230 of 2000 complete in 24.1 sec
[----             11%                  ] 235 of 2000 complete in 24.6 sec
[----             12%                  ] 240 of 2000 complete in 25.1 sec
[----             12%                  ] 245 of 2000 complete in 25.7 sec
[----             12%                  ] 250 of 2000 complete in 26.2 sec
[----             12%                  ] 255 of 2000 complete in 26.7 sec
[----             13%                  ] 260 of 2000 complete in 27.2 sec
[-----            13%                  ] 265 of 2000 complete in 27.7 sec
[-----            13%                  ] 270 of 2000 complete in 28.3 sec
[-----            13%                  ] 275 of 2000 complete in 28.8 sec
[-----            14%                  ] 280 of 2000 complete in 29.3 sec
[-----            14%                  ] 285 of 2000 complete in 29.8 sec
[-----            14%                  ] 290 of 2000 complete in 30.4 sec
[-----            14%                  ] 295 of 2000 complete in 30.9 sec
[-----            14%                  ] 299 of 2000 complete in 31.5 sec
[-----            15%                  ] 304 of 2000 complete in 32.0 sec
[-----            15%                  ] 309 of 2000 complete in 32.6 sec
[-----            15%                  ] 314 of 2000 complete in 33.2 sec
[------           15%                  ] 319 of 2000 complete in 33.7 sec
[------           16%                  ] 324 of 2000 complete in 34.3 sec
[------           16%                  ] 329 of 2000 complete in 34.9 sec
[------           16%                  ] 334 of 2000 complete in 35.4 sec
[------           16%                  ] 339 of 2000 complete in 36.0 sec
[------           17%                  ] 344 of 2000 complete in 36.6 sec
[------           17%                  ] 349 of 2000 complete in 37.1 sec
[------           17%                  ] 354 of 2000 complete in 37.6 sec
[------           17%                  ] 359 of 2000 complete in 38.2 sec
[------           18%                  ] 364 of 2000 complete in 38.7 sec
[-------          18%                  ] 369 of 2000 complete in 39.3 sec
[-------          18%                  ] 374 of 2000 complete in 39.8 sec
[-------          18%                  ] 379 of 2000 complete in 40.4 sec
[-------          19%                  ] 384 of 2000 complete in 40.9 sec
[-------          19%                  ] 389 of 2000 complete in 41.5 sec
[-------          19%                  ] 394 of 2000 complete in 42.0 sec
[-------          19%                  ] 399 of 2000 complete in 42.5 sec
[-------          20%                  ] 405 of 2000 complete in 43.1 sec
[-------          20%                  ] 410 of 2000 complete in 43.6 sec
[-------          20%                  ] 415 of 2000 complete in 44.1 sec
[-------          21%                  ] 420 of 2000 complete in 44.6 sec
[--------         21%                  ] 426 of 2000 complete in 45.2 sec
[--------         21%                  ] 432 of 2000 complete in 45.8 sec
[--------         21%                  ] 437 of 2000 complete in 46.3 sec
[--------         22%                  ] 442 of 2000 complete in 46.8 sec
[--------         22%                  ] 448 of 2000 complete in 47.4 sec
[--------         22%                  ] 454 of 2000 complete in 48.0 sec
[--------         22%                  ] 459 of 2000 complete in 48.5 sec
[--------         23%                  ] 464 of 2000 complete in 49.0 sec
[--------         23%                  ] 469 of 2000 complete in 49.5 sec
[---------        23%                  ] 474 of 2000 complete in 50.1 sec
[---------        23%                  ] 479 of 2000 complete in 50.6 sec
[---------        24%                  ] 485 of 2000 complete in 51.2 sec
[---------        24%                  ] 491 of 2000 complete in 51.7 sec
[---------        24%                  ] 497 of 2000 complete in 52.3 sec
[---------        25%                  ] 503 of 2000 complete in 53.0 sec
[---------        25%                  ] 508 of 2000 complete in 53.5 sec
[---------        25%                  ] 514 of 2000 complete in 54.1 sec
[---------        25%                  ] 519 of 2000 complete in 54.6 sec
[---------        26%                  ] 525 of 2000 complete in 55.2 sec
[----------       26%                  ] 530 of 2000 complete in 55.7 sec
[----------       26%                  ] 535 of 2000 complete in 56.2 sec
[----------       27%                  ] 540 of 2000 complete in 56.7 sec
[----------       27%                  ] 545 of 2000 complete in 57.2 sec
[----------       27%                  ] 551 of 2000 complete in 57.8 sec
[----------       27%                  ] 556 of 2000 complete in 58.3 sec
[----------       28%                  ] 561 of 2000 complete in 58.8 sec
[----------       28%                  ] 566 of 2000 complete in 59.3 sec
[----------       28%                  ] 572 of 2000 complete in 59.9 sec

[                  0%                  ] 6 of 2000 complete in 0.5 sec
[                  0%                  ] 11 of 2000 complete in 1.0 sec
[                  0%                  ] 16 of 2000 complete in 1.5 sec
[                  1%                  ] 21 of 2000 complete in 2.1 sec
[                  1%                  ] 26 of 2000 complete in 2.6 sec
[                  1%                  ] 31 of 2000 complete in 3.1 sec
[                  1%                  ] 37 of 2000 complete in 3.7 sec
[                  2%                  ] 42 of 2000 complete in 4.2 sec
[                  2%                  ] 47 of 2000 complete in 4.7 sec
[                  2%                  ] 52 of 2000 complete in 5.2 sec
[-                 2%                  ] 57 of 2000 complete in 5.7 sec
[-                 3%                  ] 62 of 2000 complete in 6.2 sec
[-                 3%                  ] 67 of 2000 complete in 6.7 sec
[-                 3%                  ] 72 of 2000 complete in 7.2 sec
[-                 3%                  ] 77 of 2000 complete in 7.8 sec
[-                 4%                  ] 82 of 2000 complete in 8.3 sec
[-                 4%                  ] 88 of 2000 complete in 8.9 sec
[-                 4%                  ] 93 of 2000 complete in 9.4 sec
[-                 4%                  ] 99 of 2000 complete in 10.0 sec
[-                 5%                  ] 104 of 2000 complete in 10.6 sec
[--                5%                  ] 109 of 2000 complete in 11.2 sec
[--                5%                  ] 114 of 2000 complete in 11.7 sec
[--                5%                  ] 119 of 2000 complete in 12.2 sec
[--                6%                  ] 124 of 2000 complete in 12.7 sec
[--                6%                  ] 129 of 2000 complete in 13.3 sec
[--                6%                  ] 133 of 2000 complete in 13.8 sec
[--                6%                  ] 138 of 2000 complete in 14.4 sec
[--                7%                  ] 143 of 2000 complete in 15.0 sec
[--                7%                  ] 148 of 2000 complete in 15.5 sec
[--                7%                  ] 153 of 2000 complete in 16.1 sec
[---               7%                  ] 158 of 2000 complete in 16.6 sec
[---               8%                  ] 163 of 2000 complete in 17.2 sec
[---               8%                  ] 168 of 2000 complete in 17.7 sec
[---               8%                  ] 173 of 2000 complete in 18.2 sec
[---               8%                  ] 178 of 2000 complete in 18.7 sec
[---               9%                  ] 183 of 2000 complete in 19.3 sec
[---               9%                  ] 188 of 2000 complete in 19.8 sec
[---               9%                  ] 193 of 2000 complete in 20.3 sec
[---               9%                  ] 199 of 2000 complete in 20.9 sec
[---              10%                  ] 204 of 2000 complete in 21.4 sec
[---              10%                  ] 209 of 2000 complete in 22.0 sec
[----             10%                  ] 214 of 2000 complete in 22.5 sec
[----             10%                  ] 219 of 2000 complete in 23.0 sec
[----             11%                  ] 224 of 2000 complete in 23.5 sec
[----             11%                  ] 230 of 2000 complete in 24.1 sec
[----             11%                  ] 235 of 2000 complete in 24.6 sec
[----             12%                  ] 240 of 2000 complete in 25.2 sec
[----             12%                  ] 245 of 2000 complete in 25.7 sec
[----             12%                  ] 250 of 2000 complete in 26.2 sec
[----             12%                  ] 255 of 2000 complete in 26.7 sec
[----             13%                  ] 260 of 2000 complete in 27.2 sec
[-----            13%                  ] 265 of 2000 complete in 27.8 sec
[-----            13%                  ] 270 of 2000 complete in 28.3 sec
[-----            13%                  ] 275 of 2000 complete in 28.8 sec
[-----            14%                  ] 280 of 2000 complete in 29.4 sec
[-----            14%                  ] 285 of 2000 complete in 29.9 sec
[-----            14%                  ] 290 of 2000 complete in 30.4 sec
[-----            14%                  ] 295 of 2000 complete in 31.0 sec
[-----            14%                  ] 299 of 2000 complete in 31.5 sec
[-----            15%                  ] 304 of 2000 complete in 32.1 sec
[-----            15%                  ] 309 of 2000 complete in 32.7 sec
[-----            15%                  ] 314 of 2000 complete in 33.3 sec
[------           15%                  ] 319 of 2000 complete in 33.8 sec
[------           16%                  ] 324 of 2000 complete in 34.4 sec
[------           16%                  ] 329 of 2000 complete in 35.0 sec
[------           16%                  ] 334 of 2000 complete in 35.5 sec
[------           16%                  ] 339 of 2000 complete in 36.1 sec
[------           17%                  ] 344 of 2000 complete in 36.6 sec
[------           17%                  ] 349 of 2000 complete in 37.2 sec
[------           17%                  ] 354 of 2000 complete in 37.7 sec
[------           17%                  ] 359 of 2000 complete in 38.2 sec
[------           18%                  ] 364 of 2000 complete in 38.8 sec
[-------          18%                  ] 369 of 2000 complete in 39.4 sec
[-------          18%                  ] 374 of 2000 complete in 39.9 sec
[-------          18%                  ] 379 of 2000 complete in 40.4 sec
[-------          19%                  ] 384 of 2000 complete in 41.0 sec
[-------          19%                  ] 389 of 2000 complete in 41.5 sec
[-------          19%                  ] 394 of 2000 complete in 42.1 sec
[-------          19%                  ] 399 of 2000 complete in 42.6 sec
[-------          20%                  ] 404 of 2000 complete in 43.1 sec
[-------          20%                  ] 409 of 2000 complete in 43.6 sec
[-------          20%                  ] 414 of 2000 complete in 44.1 sec
[-------          20%                  ] 419 of 2000 complete in 44.6 sec
[--------         21%                  ] 425 of 2000 complete in 45.2 sec
[--------         21%                  ] 430 of 2000 complete in 45.8 sec
[--------         21%                  ] 435 of 2000 complete in 46.3 sec
[--------         22%                  ] 441 of 2000 complete in 46.9 sec
[--------         22%                  ] 446 of 2000 complete in 47.4 sec
[--------         22%                  ] 452 of 2000 complete in 48.0 sec
[--------         22%                  ] 457 of 2000 complete in 48.5 sec
[--------         23%                  ] 463 of 2000 complete in 49.1 sec
[--------         23%                  ] 468 of 2000 complete in 49.6 sec
[---------        23%                  ] 474 of 2000 complete in 50.2 sec
[---------        24%                  ] 480 of 2000 complete in 50.8 sec
[---------        24%                  ] 485 of 2000 complete in 51.3 sec
[---------        24%                  ] 491 of 2000 complete in 51.8 sec
[---------        24%                  ] 496 of 2000 complete in 52.3 sec
[---------        25%                  ] 502 of 2000 complete in 52.9 sec
[---------        25%                  ] 508 of 2000 complete in 53.5 sec
[---------        25%                  ] 514 of 2000 complete in 54.1 sec
[---------        26%                  ] 520 of 2000 complete in 54.7 sec
[---------        26%                  ] 525 of 2000 complete in 55.2 sec
[----------       26%                  ] 531 of 2000 complete in 55.8 sec
[----------       26%                  ] 536 of 2000 complete in 56.4 sec
[----------       27%                  ] 542 of 2000 complete in 57.0 sec
[----------       27%                  ] 548 of 2000 complete in 57.6 sec
[----------       27%                  ] 553 of 2000 complete in 58.1 sec
[----------       27%                  ] 559 of 2000 complete in 58.6 sec
[----------       28%                  ] 564 of 2000 complete in 59.2 sec
[----------       28%                  ] 569 of 2000 complete in 59.7 sec
[----------       28%                  ] 574 of 2000 complete in 60.2 sec
[                  0%                  ] 6 of 2000 complete in 0.5 sec
[                  0%                  ] 11 of 2000 complete in 1.0 sec
[                  0%                  ] 16 of 2000 complete in 1.5 sec
[                  1%                  ] 21 of 2000 complete in 2.1 sec
[                  1%                  ] 26 of 2000 complete in 2.6 sec
[                  1%                  ] 31 of 2000 complete in 3.1 sec
[                  1%                  ] 37 of 2000 complete in 3.7 sec
[                  2%                  ] 42 of 2000 complete in 4.2 sec
[                  2%                  ] 47 of 2000 complete in 4.7 sec
[                  2%                  ] 52 of 2000 complete in 5.2 sec
[-                 2%                  ] 57 of 2000 complete in 5.7 sec
[-                 3%                  ] 62 of 2000 complete in 6.2 sec
[-                 3%                  ] 68 of 2000 complete in 6.8 sec
[-                 3%                  ] 74 of 2000 complete in 7.4 sec
[-                 3%                  ] 79 of 2000 complete in 7.9 sec
[-                 4%                  ] 84 of 2000 complete in 8.5 sec
[-                 4%                  ] 90 of 2000 complete in 9.1 sec
[-                 4%                  ] 96 of 2000 complete in 9.7 sec
[-                 5%                  ] 101 of 2000 complete in 10.2 sec
[-                 5%                  ] 105 of 2000 complete in 10.7 sec
[--                5%                  ] 110 of 2000 complete in 11.2 sec
[--                5%                  ] 115 of 2000 complete in 11.7 sec
[--                6%                  ] 120 of 2000 complete in 12.2 sec
[--                6%                  ] 125 of 2000 complete in 12.8 sec
[--                6%                  ] 130 of 2000 complete in 13.3 sec
[--                6%                  ] 134 of 2000 complete in 13.8 sec
[--                6%                  ] 139 of 2000 complete in 14.4 sec
[--                7%                  ] 144 of 2000 complete in 14.9 sec
[--                7%                  ] 149 of 2000 complete in 15.5 sec
[--                7%                  ] 154 of 2000 complete in 16.0 sec
[---               7%                  ] 159 of 2000 complete in 16.5 sec
[---               8%                  ] 164 of 2000 complete in 17.0 sec
[---               8%                  ] 169 of 2000 complete in 17.6 sec
[---               8%                  ] 174 of 2000 complete in 18.1 sec
[---               8%                  ] 179 of 2000 complete in 18.6 sec
[---               9%                  ] 184 of 2000 complete in 19.1 sec
[---               9%                  ] 189 of 2000 complete in 19.7 sec
[---               9%                  ] 194 of 2000 complete in 20.2 sec
[---               9%                  ] 199 of 2000 complete in 20.7 sec
[---              10%                  ] 204 of 2000 complete in 21.3 sec
[---              10%                  ] 209 of 2000 complete in 21.8 sec
[----             10%                  ] 214 of 2000 complete in 22.3 sec
[----             10%                  ] 219 of 2000 complete in 22.8 sec
[----             11%                  ] 224 of 2000 complete in 23.3 sec
[----             11%                  ] 229 of 2000 complete in 23.8 sec
[----             11%                  ] 234 of 2000 complete in 24.3 sec
[----             11%                  ] 239 of 2000 complete in 24.9 sec
[----             12%                  ] 244 of 2000 complete in 25.4 sec
[----             12%                  ] 249 of 2000 complete in 25.9 sec
[----             12%                  ] 254 of 2000 complete in 26.4 sec
[----             13%                  ] 260 of 2000 complete in 27.0 sec
[-----            13%                  ] 266 of 2000 complete in 27.6 sec
[-----            13%                  ] 271 of 2000 complete in 28.1 sec
[-----            13%                  ] 276 of 2000 complete in 28.6 sec
[-----            14%                  ] 281 of 2000 complete in 29.1 sec
[-----            14%                  ] 287 of 2000 complete in 29.8 sec
[-----            14%                  ] 292 of 2000 complete in 30.3 sec
[-----            14%                  ] 297 of 2000 complete in 30.8 sec
[-----            15%                  ] 302 of 2000 complete in 31.5 sec
[-----            15%                  ] 307 of 2000 complete in 32.1 sec
[-----            15%                  ] 312 of 2000 complete in 32.6 sec
[------           15%                  ] 317 of 2000 complete in 33.2 sec
[------           16%                  ] 322 of 2000 complete in 33.8 sec
[------           16%                  ] 327 of 2000 complete in 34.3 sec
[------           16%                  ] 332 of 2000 complete in 34.9 sec
[------           16%                  ] 337 of 2000 complete in 35.5 sec
[------           17%                  ] 342 of 2000 complete in 36.0 sec
[------           17%                  ] 347 of 2000 complete in 36.6 sec
[------           17%                  ] 352 of 2000 complete in 37.1 sec
[------           17%                  ] 357 of 2000 complete in 37.6 sec
[------           18%                  ] 362 of 2000 complete in 38.2 sec
[------           18%                  ] 367 of 2000 complete in 38.7 sec
[-------          18%                  ] 372 of 2000 complete in 39.3 sec
[-------          18%                  ] 377 of 2000 complete in 39.8 sec
[-------          19%                  ] 382 of 2000 complete in 40.3 sec
[-------          19%                  ] 387 of 2000 complete in 40.9 sec
[-------          19%                  ] 392 of 2000 complete in 41.4 sec
[-------          19%                  ] 397 of 2000 complete in 42.0 sec
[-------          20%                  ] 402 of 2000 complete in 42.5 sec
[-------          20%                  ] 408 of 2000 complete in 43.1 sec
[-------          20%                  ] 414 of 2000 complete in 43.7 sec
[-------          20%                  ] 419 of 2000 complete in 44.2 sec
[--------         21%                  ] 425 of 2000 complete in 44.8 sec
[--------         21%                  ] 431 of 2000 complete in 45.4 sec
[--------         21%                  ] 437 of 2000 complete in 46.0 sec
[--------         22%                  ] 442 of 2000 complete in 46.5 sec
[--------         22%                  ] 448 of 2000 complete in 47.1 sec
[--------         22%                  ] 454 of 2000 complete in 47.7 sec
[--------         23%                  ] 460 of 2000 complete in 48.3 sec
[--------         23%                  ] 466 of 2000 complete in 48.9 sec
[--------         23%                  ] 472 of 2000 complete in 49.4 sec
[---------        23%                  ] 478 of 2000 complete in 50.0 sec
[---------        24%                  ] 483 of 2000 complete in 50.6 sec
[---------        24%                  ] 489 of 2000 complete in 51.1 sec
[---------        24%                  ] 495 of 2000 complete in 51.7 sec
[---------        25%                  ] 500 of 2000 complete in 52.2 sec
[---------        25%                  ] 506 of 2000 complete in 52.8 sec
[---------        25%                  ] 512 of 2000 complete in 53.4 sec
[---------        25%                  ] 517 of 2000 complete in 53.9 sec
[---------        26%                  ] 523 of 2000 complete in 54.5 sec
[----------       26%                  ] 528 of 2000 complete in 55.0 sec
[----------       26%                  ] 534 of 2000 complete in 55.6 sec
[----------       26%                  ] 539 of 2000 complete in 56.1 sec
[----------       27%                  ] 545 of 2000 complete in 56.7 sec
[----------       27%                  ] 551 of 2000 complete in 57.3 sec
[----------       27%                  ] 556 of 2000 complete in 57.8 sec
[----------       28%                  ] 562 of 2000 complete in 58.4 sec
[----------       28%                  ] 568 of 2000 complete in 59.0 sec
[----------       28%                  ] 574 of 2000 complete in 59.6 sec
[-----------      28%                  ] 579 of 2000 complete in 60.1 sec
[-----------      29%                  ] 584 of 2000 complete in 60.6 sec

[----------       28%                  ] 569 of 2000 complete in 59.9 sec
[----------       28%                  ] 574 of 2000 complete in 60.4 sec
[-----------      28%                  ] 579 of 2000 complete in 60.9 sec
[-----------      29%                  ] 585 of 2000 complete in 61.5 sec
[-----------      29%                  ] 590 of 2000 complete in 62.0 sec
[-----------      29%                  ] 596 of 2000 complete in 62.6 sec
[-----------      30%                  ] 601 of 2000 complete in 63.1 sec
[-----------      30%                  ] 606 of 2000 complete in 63.6 sec
[-----------      30%                  ] 611 of 2000 complete in 64.2 sec
[-----------      30%                  ] 617 of 2000 complete in 64.8 sec
[-----------      31%                  ] 623 of 2000 complete in 65.4 sec
[-----------      31%                  ] 628 of 2000 complete in 65.9 sec
[------------     31%                  ] 633 of 2000 complete in 66.4 sec
[------------     31%                  ] 638 of 2000 complete in 66.9 sec
[------------     32%                  ] 643 of 2000 complete in 67.4 sec
[------------     32%                  ] 649 of 2000 complete in 68.0 sec
[------------     32%                  ] 655 of 2000 complete in 68.6 sec
[------------     33%                  ] 660 of 2000 complete in 69.1 sec
[------------     33%                  ] 665 of 2000 complete in 69.6 sec
[------------     33%                  ] 670 of 2000 complete in 70.1 sec
[------------     33%                  ] 675 of 2000 complete in 70.6 sec
[------------     34%                  ] 680 of 2000 complete in 71.1 sec
[-------------    34%                  ] 686 of 2000 complete in 71.7 sec
[-------------    34%                  ] 692 of 2000 complete in 72.3 sec
[-------------    34%                  ] 698 of 2000 complete in 72.9 sec
[-------------    35%                  ] 703 of 2000 complete in 73.4 sec
[-------------    35%                  ] 708 of 2000 complete in 73.9 sec
[-------------    35%                  ] 714 of 2000 complete in 74.5 sec
[-------------    35%                  ] 719 of 2000 complete in 75.1 sec
[-------------    36%                  ] 725 of 2000 complete in 75.6 sec
[-------------    36%                  ] 730 of 2000 complete in 76.2 sec
[-------------    36%                  ] 736 of 2000 complete in 76.7 sec
[--------------   37%                  ] 741 of 2000 complete in 77.2 sec
[--------------   37%                  ] 747 of 2000 complete in 77.8 sec
[--------------   37%                  ] 752 of 2000 complete in 78.3 sec
[--------------   37%                  ] 758 of 2000 complete in 78.9 sec
[--------------   38%                  ] 763 of 2000 complete in 79.5 sec
[--------------   38%                  ] 768 of 2000 complete in 80.0 sec
[--------------   38%                  ] 773 of 2000 complete in 80.5 sec
[--------------   38%                  ] 778 of 2000 complete in 81.0 sec
[--------------   39%                  ] 783 of 2000 complete in 81.5 sec
[--------------   39%                  ] 789 of 2000 complete in 82.1 sec
[---------------  39%                  ] 794 of 2000 complete in 82.6 sec
[---------------  39%                  ] 799 of 2000 complete in 83.1 sec
[---------------  40%                  ] 804 of 2000 complete in 83.7 sec
[---------------  40%                  ] 810 of 2000 complete in 84.2 sec
[---------------  40%                  ] 815 of 2000 complete in 84.8 sec
[---------------  41%                  ] 820 of 2000 complete in 85.3 sec
[---------------  41%                  ] 825 of 2000 complete in 85.8 sec
[---------------  41%                  ] 830 of 2000 complete in 86.3 sec
[---------------  41%                  ] 836 of 2000 complete in 86.9 sec
[---------------  42%                  ] 841 of 2000 complete in 87.4 sec
[---------------- 42%                  ] 846 of 2000 complete in 87.9 sec
[---------------- 42%                  ] 851 of 2000 complete in 88.4 sec
[---------------- 42%                  ] 857 of 2000 complete in 89.0 sec
[---------------- 43%                  ] 862 of 2000 complete in 89.5 sec
[---------------- 43%                  ] 867 of 2000 complete in 90.0 sec
[---------------- 43%                  ] 873 of 2000 complete in 90.6 sec
[---------------- 43%                  ] 879 of 2000 complete in 91.2 sec
[---------------- 44%                  ] 884 of 2000 complete in 91.7 sec
[---------------- 44%                  ] 890 of 2000 complete in 92.3 sec
[-----------------44%                  ] 895 of 2000 complete in 92.9 sec
[-----------------45%                  ] 900 of 2000 complete in 93.4 sec
[-----------------45%                  ] 905 of 2000 complete in 93.9 sec
[-----------------45%                  ] 910 of 2000 complete in 94.4 sec
[-----------------45%                  ] 915 of 2000 complete in 94.9 sec
[-----------------46%                  ] 920 of 2000 complete in 95.4 sec
[-----------------46%                  ] 925 of 2000 complete in 96.0 sec
[-----------------46%                  ] 930 of 2000 complete in 96.5 sec
[-----------------46%                  ] 935 of 2000 complete in 97.0 sec
[-----------------47%                  ] 941 of 2000 complete in 97.6 sec
[-----------------47%                  ] 946 of 2000 complete in 98.1 sec
[-----------------47%                  ] 951 of 2000 complete in 98.6 sec
[-----------------47%                  ] 956 of 2000 complete in 99.1 sec
[-----------------48%                  ] 961 of 2000 complete in 99.6 sec
[-----------------48%                  ] 966 of 2000 complete in 100.2 sec
[-----------------48%                  ] 971 of 2000 complete in 100.7 sec
[-----------------48%                  ] 977 of 2000 complete in 101.3 sec
[-----------------49%                  ] 983 of 2000 complete in 101.9 sec
[-----------------49%                  ] 988 of 2000 complete in 102.4 sec
[-----------------49%                  ] 993 of 2000 complete in 102.9 sec
[-----------------49%                  ] 998 of 2000 complete in 103.4 sec
[-----------------50%                  ] 1004 of 2000 complete in 104.0 sec
[-----------------50%                  ] 1009 of 2000 complete in 104.5 sec
[-----------------50%                  ] 1014 of 2000 complete in 105.0 sec
[-----------------50%                  ] 1019 of 2000 complete in 105.6 sec
[-----------------51%                  ] 1025 of 2000 complete in 106.2 sec
[-----------------51%                  ] 1031 of 2000 complete in 106.7 sec
[-----------------51%                  ] 1036 of 2000 complete in 107.2 sec
[-----------------52%                  ] 1041 of 2000 complete in 107.7 sec
[-----------------52%                  ] 1046 of 2000 complete in 108.3 sec
[-----------------52%                  ] 1052 of 2000 complete in 108.8 sec
[-----------------52%                  ] 1057 of 2000 complete in 109.3 sec
[-----------------53%                  ] 1062 of 2000 complete in 109.9 sec
[-----------------53%                  ] 1067 of 2000 complete in 110.4 sec
[-----------------53%                  ] 1072 of 2000 complete in 110.9 sec
[-----------------53%                  ] 1077 of 2000 complete in 111.4 sec
[-----------------54%                  ] 1082 of 2000 complete in 111.9 sec
[-----------------54%                  ] 1087 of 2000 complete in 112.5 sec
[-----------------54%                  ] 1092 of 2000 complete in 113.0 sec
[-----------------54%                  ] 1097 of 2000 complete in 113.5 sec
[-----------------55%                  ] 1102 of 2000 complete in 114.0 sec
[-----------------55%-                 ] 1107 of 2000 complete in 114.6 sec
[-----------------55%-                 ] 1112 of 2000 complete in 115.1 sec
[-----------------55%-                 ] 1117 of 2000 complete in 115.6 sec
[-----------------56%-                 ] 1122 of 2000 complete in 116.1 sec
[-----------------56%-                 ] 1128 of 2000 complete in 116.7 sec
[-----------------56%-                 ] 1133 of 2000 complete in 117.3 sec
[-----------------56%-                 ] 1138 of 2000 complete in 117.8 sec
[----------       28%                  ] 577 of 2000 complete in 60.4 sec
[-----------      29%                  ] 582 of 2000 complete in 60.9 sec
[-----------      29%                  ] 587 of 2000 complete in 61.4 sec
[-----------      29%                  ] 592 of 2000 complete in 61.9 sec
[-----------      29%                  ] 597 of 2000 complete in 62.5 sec
[-----------      30%                  ] 603 of 2000 complete in 63.1 sec
[-----------      30%                  ] 609 of 2000 complete in 63.6 sec
[-----------      30%                  ] 614 of 2000 complete in 64.2 sec
[-----------      30%                  ] 619 of 2000 complete in 64.7 sec
[-----------      31%                  ] 624 of 2000 complete in 65.2 sec
[-----------      31%                  ] 629 of 2000 complete in 65.7 sec
[------------     31%                  ] 634 of 2000 complete in 66.2 sec
[------------     32%                  ] 640 of 2000 complete in 66.8 sec
[------------     32%                  ] 646 of 2000 complete in 67.4 sec
[------------     32%                  ] 651 of 2000 complete in 67.9 sec
[------------     32%                  ] 656 of 2000 complete in 68.4 sec
[------------     33%                  ] 662 of 2000 complete in 69.0 sec
[------------     33%                  ] 668 of 2000 complete in 69.6 sec
[------------     33%                  ] 673 of 2000 complete in 70.1 sec
[------------     33%                  ] 678 of 2000 complete in 70.6 sec
[------------     34%                  ] 684 of 2000 complete in 71.2 sec
[-------------    34%                  ] 690 of 2000 complete in 71.8 sec
[-------------    34%                  ] 695 of 2000 complete in 72.3 sec
[-------------    35%                  ] 700 of 2000 complete in 72.8 sec
[-------------    35%                  ] 705 of 2000 complete in 73.3 sec
[-------------    35%                  ] 710 of 2000 complete in 73.8 sec
[-------------    35%                  ] 715 of 2000 complete in 74.3 sec
[-------------    36%                  ] 721 of 2000 complete in 74.9 sec
[-------------    36%                  ] 726 of 2000 complete in 75.4 sec
[-------------    36%                  ] 731 of 2000 complete in 75.9 sec
[-------------    36%                  ] 736 of 2000 complete in 76.5 sec
[--------------   37%                  ] 741 of 2000 complete in 77.0 sec
[--------------   37%                  ] 746 of 2000 complete in 77.5 sec
[--------------   37%                  ] 752 of 2000 complete in 78.1 sec
[--------------   37%                  ] 757 of 2000 complete in 78.6 sec
[--------------   38%                  ] 762 of 2000 complete in 79.1 sec
[--------------   38%                  ] 768 of 2000 complete in 79.7 sec
[--------------   38%                  ] 773 of 2000 complete in 80.2 sec
[--------------   38%                  ] 778 of 2000 complete in 80.7 sec
[--------------   39%                  ] 783 of 2000 complete in 81.2 sec
[--------------   39%                  ] 788 of 2000 complete in 81.7 sec
[---------------  39%                  ] 793 of 2000 complete in 82.3 sec
[---------------  39%                  ] 799 of 2000 complete in 82.8 sec
[---------------  40%                  ] 804 of 2000 complete in 83.4 sec
[---------------  40%                  ] 809 of 2000 complete in 83.9 sec
[---------------  40%                  ] 814 of 2000 complete in 84.4 sec
[---------------  40%                  ] 819 of 2000 complete in 84.9 sec
[---------------  41%                  ] 824 of 2000 complete in 85.4 sec
[---------------  41%                  ] 829 of 2000 complete in 85.9 sec
[---------------  41%                  ] 834 of 2000 complete in 86.5 sec
[---------------  42%                  ] 840 of 2000 complete in 87.1 sec
[---------------- 42%                  ] 845 of 2000 complete in 87.6 sec
[---------------- 42%                  ] 850 of 2000 complete in 88.1 sec
[---------------- 42%                  ] 855 of 2000 complete in 88.6 sec
[---------------- 43%                  ] 860 of 2000 complete in 89.1 sec
[---------------- 43%                  ] 865 of 2000 complete in 89.6 sec
[---------------- 43%                  ] 870 of 2000 complete in 90.1 sec
[---------------- 43%                  ] 875 of 2000 complete in 90.6 sec
[---------------- 44%                  ] 881 of 2000 complete in 91.2 sec
[---------------- 44%                  ] 887 of 2000 complete in 91.8 sec
[---------------- 44%                  ] 892 of 2000 complete in 92.3 sec
[-----------------44%                  ] 897 of 2000 complete in 92.9 sec
[-----------------45%                  ] 902 of 2000 complete in 93.4 sec
[-----------------45%                  ] 907 of 2000 complete in 93.9 sec
[-----------------45%                  ] 913 of 2000 complete in 94.5 sec
[-----------------45%                  ] 919 of 2000 complete in 95.1 sec
[-----------------46%                  ] 925 of 2000 complete in 95.7 sec
[-----------------46%                  ] 930 of 2000 complete in 96.3 sec
[-----------------46%                  ] 935 of 2000 complete in 96.8 sec
[-----------------47%                  ] 940 of 2000 complete in 97.3 sec
[-----------------47%                  ] 946 of 2000 complete in 97.8 sec
[-----------------47%                  ] 951 of 2000 complete in 98.4 sec
[-----------------47%                  ] 957 of 2000 complete in 99.0 sec
[-----------------48%                  ] 962 of 2000 complete in 99.5 sec
[-----------------48%                  ] 967 of 2000 complete in 100.0 sec
[-----------------48%                  ] 972 of 2000 complete in 100.5 sec
[-----------------48%                  ] 977 of 2000 complete in 101.0 sec
[-----------------49%                  ] 982 of 2000 complete in 101.6 sec
[-----------------49%                  ] 988 of 2000 complete in 102.1 sec
[-----------------49%                  ] 993 of 2000 complete in 102.7 sec
[-----------------49%                  ] 999 of 2000 complete in 103.3 sec
[-----------------50%                  ] 1005 of 2000 complete in 103.9 sec
[-----------------50%                  ] 1010 of 2000 complete in 104.4 sec
[-----------------50%                  ] 1016 of 2000 complete in 104.9 sec
[-----------------51%                  ] 1021 of 2000 complete in 105.5 sec
[-----------------51%                  ] 1027 of 2000 complete in 106.0 sec
[-----------------51%                  ] 1032 of 2000 complete in 106.6 sec
[-----------------51%                  ] 1037 of 2000 complete in 107.1 sec
[-----------------52%                  ] 1042 of 2000 complete in 107.6 sec
[-----------------52%                  ] 1048 of 2000 complete in 108.2 sec
[-----------------52%                  ] 1054 of 2000 complete in 108.7 sec
[-----------------52%                  ] 1059 of 2000 complete in 109.2 sec
[-----------------53%                  ] 1065 of 2000 complete in 109.8 sec
[-----------------53%                  ] 1070 of 2000 complete in 110.4 sec
[-----------------53%                  ] 1075 of 2000 complete in 110.9 sec
[-----------------54%                  ] 1080 of 2000 complete in 111.4 sec
[-----------------54%                  ] 1085 of 2000 complete in 112.0 sec
[-----------------54%                  ] 1090 of 2000 complete in 112.5 sec
[-----------------54%                  ] 1095 of 2000 complete in 113.0 sec
[-----------------55%                  ] 1100 of 2000 complete in 113.5 sec
[-----------------55%                  ] 1105 of 2000 complete in 114.0 sec
[-----------------55%-                 ] 1110 of 2000 complete in 114.6 sec
[-----------------55%-                 ] 1115 of 2000 complete in 115.1 sec
[-----------------56%-                 ] 1120 of 2000 complete in 115.6 sec
[-----------------56%-                 ] 1125 of 2000 complete in 116.1 sec
[-----------------56%-                 ] 1130 of 2000 complete in 116.6 sec
[-----------------56%-                 ] 1135 of 2000 complete in 117.1 sec
[-----------------57%-                 ] 1140 of 2000 complete in 117.6 sec
[-----------------57%-                 ] 1145 of 2000 complete in 118.2 sec

[-----------      28%                  ] 579 of 2000 complete in 60.7 sec
[-----------      29%                  ] 584 of 2000 complete in 61.2 sec
[-----------      29%                  ] 589 of 2000 complete in 61.7 sec
[-----------      29%                  ] 595 of 2000 complete in 62.3 sec
[-----------      30%                  ] 601 of 2000 complete in 62.9 sec
[-----------      30%                  ] 606 of 2000 complete in 63.4 sec
[-----------      30%                  ] 611 of 2000 complete in 63.9 sec
[-----------      30%                  ] 616 of 2000 complete in 64.4 sec
[-----------      31%                  ] 621 of 2000 complete in 64.9 sec
[-----------      31%                  ] 626 of 2000 complete in 65.4 sec
[-----------      31%                  ] 631 of 2000 complete in 65.9 sec
[------------     31%                  ] 637 of 2000 complete in 66.5 sec
[------------     32%                  ] 643 of 2000 complete in 67.1 sec
[------------     32%                  ] 648 of 2000 complete in 67.6 sec
[------------     32%                  ] 653 of 2000 complete in 68.2 sec
[------------     32%                  ] 658 of 2000 complete in 68.7 sec
[------------     33%                  ] 664 of 2000 complete in 69.3 sec
[------------     33%                  ] 670 of 2000 complete in 69.9 sec
[------------     33%                  ] 675 of 2000 complete in 70.4 sec
[------------     34%                  ] 681 of 2000 complete in 71.0 sec
[-------------    34%                  ] 686 of 2000 complete in 71.5 sec
[-------------    34%                  ] 692 of 2000 complete in 72.1 sec
[-------------    34%                  ] 698 of 2000 complete in 72.7 sec
[-------------    35%                  ] 704 of 2000 complete in 73.3 sec
[-------------    35%                  ] 710 of 2000 complete in 73.9 sec
[-------------    35%                  ] 715 of 2000 complete in 74.4 sec
[-------------    36%                  ] 721 of 2000 complete in 75.0 sec
[-------------    36%                  ] 727 of 2000 complete in 75.6 sec
[-------------    36%                  ] 732 of 2000 complete in 76.1 sec
[--------------   36%                  ] 737 of 2000 complete in 76.6 sec
[--------------   37%                  ] 742 of 2000 complete in 77.1 sec
[--------------   37%                  ] 747 of 2000 complete in 77.6 sec
[--------------   37%                  ] 752 of 2000 complete in 78.2 sec
[--------------   37%                  ] 758 of 2000 complete in 78.8 sec
[--------------   38%                  ] 763 of 2000 complete in 79.3 sec
[--------------   38%                  ] 768 of 2000 complete in 79.8 sec
[--------------   38%                  ] 773 of 2000 complete in 80.3 sec
[--------------   38%                  ] 779 of 2000 complete in 80.9 sec
[--------------   39%                  ] 784 of 2000 complete in 81.4 sec
[---------------  39%                  ] 790 of 2000 complete in 82.0 sec
[---------------  39%                  ] 795 of 2000 complete in 82.5 sec
[---------------  40%                  ] 800 of 2000 complete in 83.0 sec
[---------------  40%                  ] 805 of 2000 complete in 83.6 sec
[---------------  40%                  ] 810 of 2000 complete in 84.1 sec
[---------------  40%                  ] 815 of 2000 complete in 84.6 sec
[---------------  41%                  ] 821 of 2000 complete in 85.2 sec
[---------------  41%                  ] 826 of 2000 complete in 85.7 sec
[---------------  41%                  ] 831 of 2000 complete in 86.2 sec
[---------------  41%                  ] 836 of 2000 complete in 86.7 sec
[---------------  42%                  ] 841 of 2000 complete in 87.2 sec
[---------------- 42%                  ] 847 of 2000 complete in 87.8 sec
[---------------- 42%                  ] 852 of 2000 complete in 88.3 sec
[---------------- 42%                  ] 858 of 2000 complete in 88.9 sec
[---------------- 43%                  ] 864 of 2000 complete in 89.5 sec
[---------------- 43%                  ] 869 of 2000 complete in 90.0 sec
[---------------- 43%                  ] 874 of 2000 complete in 90.6 sec
[---------------- 43%                  ] 879 of 2000 complete in 91.1 sec
[---------------- 44%                  ] 884 of 2000 complete in 91.6 sec
[---------------- 44%                  ] 889 of 2000 complete in 92.1 sec
[---------------- 44%                  ] 894 of 2000 complete in 92.6 sec
[-----------------44%                  ] 899 of 2000 complete in 93.2 sec
[-----------------45%                  ] 904 of 2000 complete in 93.7 sec
[-----------------45%                  ] 910 of 2000 complete in 94.3 sec
[-----------------45%                  ] 916 of 2000 complete in 94.9 sec
[-----------------46%                  ] 921 of 2000 complete in 95.4 sec
[-----------------46%                  ] 927 of 2000 complete in 96.0 sec
[-----------------46%                  ] 933 of 2000 complete in 96.6 sec
[-----------------46%                  ] 938 of 2000 complete in 97.1 sec
[-----------------47%                  ] 943 of 2000 complete in 97.6 sec
[-----------------47%                  ] 948 of 2000 complete in 98.1 sec
[-----------------47%                  ] 953 of 2000 complete in 98.7 sec
[-----------------47%                  ] 958 of 2000 complete in 99.2 sec
[-----------------48%                  ] 963 of 2000 complete in 99.7 sec
[-----------------48%                  ] 968 of 2000 complete in 100.2 sec
[-----------------48%                  ] 973 of 2000 complete in 100.7 sec
[-----------------48%                  ] 978 of 2000 complete in 101.2 sec
[-----------------49%                  ] 984 of 2000 complete in 101.8 sec
[-----------------49%                  ] 989 of 2000 complete in 102.3 sec
[-----------------49%                  ] 995 of 2000 complete in 102.9 sec
[-----------------50%                  ] 1000 of 2000 complete in 103.4 sec
[-----------------50%                  ] 1006 of 2000 complete in 104.0 sec
[-----------------50%                  ] 1011 of 2000 complete in 104.5 sec
[-----------------50%                  ] 1016 of 2000 complete in 105.0 sec
[-----------------51%                  ] 1021 of 2000 complete in 105.5 sec
[-----------------51%                  ] 1026 of 2000 complete in 106.0 sec
[-----------------51%                  ] 1031 of 2000 complete in 106.5 sec
[-----------------51%                  ] 1036 of 2000 complete in 107.1 sec
[-----------------52%                  ] 1041 of 2000 complete in 107.6 sec
[-----------------52%                  ] 1047 of 2000 complete in 108.1 sec
[-----------------52%                  ] 1053 of 2000 complete in 108.7 sec
[-----------------52%                  ] 1058 of 2000 complete in 109.2 sec
[-----------------53%                  ] 1064 of 2000 complete in 109.8 sec
[-----------------53%                  ] 1069 of 2000 complete in 110.3 sec
[-----------------53%                  ] 1074 of 2000 complete in 110.9 sec
[-----------------53%                  ] 1079 of 2000 complete in 111.4 sec
[-----------------54%                  ] 1084 of 2000 complete in 111.9 sec
[-----------------54%                  ] 1089 of 2000 complete in 112.4 sec
[-----------------54%                  ] 1094 of 2000 complete in 112.9 sec
[-----------------54%                  ] 1099 of 2000 complete in 113.5 sec
[-----------------55%                  ] 1104 of 2000 complete in 114.0 sec
[-----------------55%-                 ] 1109 of 2000 complete in 114.5 sec
[-----------------55%-                 ] 1114 of 2000 complete in 115.0 sec
[-----------------55%-                 ] 1119 of 2000 complete in 115.6 sec
[-----------------56%-                 ] 1124 of 2000 complete in 116.1 sec
[-----------------56%-                 ] 1129 of 2000 complete in 116.6 sec
[-----------------56%-                 ] 1134 of 2000 complete in 117.1 sec
[-----------------56%-                 ] 1139 of 2000 complete in 117.6 sec
[-----------------57%-                 ] 1144 of 2000 complete in 118.2 sec
[-----------------57%-                 ] 1149 of 2000 complete in 118.7 sec
[-----------      29%                  ] 589 of 2000 complete in 61.1 sec
[-----------      29%                  ] 594 of 2000 complete in 61.7 sec
[-----------      30%                  ] 600 of 2000 complete in 62.2 sec
[-----------      30%                  ] 606 of 2000 complete in 62.8 sec
[-----------      30%                  ] 611 of 2000 complete in 63.3 sec
[-----------      30%                  ] 617 of 2000 complete in 63.9 sec
[-----------      31%                  ] 622 of 2000 complete in 64.4 sec
[-----------      31%                  ] 628 of 2000 complete in 65.0 sec
[------------     31%                  ] 633 of 2000 complete in 65.6 sec
[------------     31%                  ] 638 of 2000 complete in 66.1 sec
[------------     32%                  ] 644 of 2000 complete in 66.6 sec
[------------     32%                  ] 649 of 2000 complete in 67.1 sec
[------------     32%                  ] 654 of 2000 complete in 67.6 sec
[------------     32%                  ] 659 of 2000 complete in 68.2 sec
[------------     33%                  ] 665 of 2000 complete in 68.7 sec
[------------     33%                  ] 671 of 2000 complete in 69.3 sec
[------------     33%                  ] 677 of 2000 complete in 69.9 sec
[------------     34%                  ] 682 of 2000 complete in 70.4 sec
[-------------    34%                  ] 687 of 2000 complete in 70.9 sec
[-------------    34%                  ] 692 of 2000 complete in 71.4 sec
[-------------    34%                  ] 697 of 2000 complete in 71.9 sec
[-------------    35%                  ] 702 of 2000 complete in 72.4 sec
[-------------    35%                  ] 707 of 2000 complete in 73.0 sec
[-------------    35%                  ] 713 of 2000 complete in 73.5 sec
[-------------    35%                  ] 718 of 2000 complete in 74.0 sec
[-------------    36%                  ] 724 of 2000 complete in 74.6 sec
[-------------    36%                  ] 730 of 2000 complete in 75.2 sec
[-------------    36%                  ] 736 of 2000 complete in 75.8 sec
[--------------   37%                  ] 741 of 2000 complete in 76.3 sec
[--------------   37%                  ] 747 of 2000 complete in 76.9 sec
[--------------   37%                  ] 752 of 2000 complete in 77.4 sec
[--------------   37%                  ] 758 of 2000 complete in 78.0 sec
[--------------   38%                  ] 763 of 2000 complete in 78.5 sec
[--------------   38%                  ] 768 of 2000 complete in 79.0 sec
[--------------   38%                  ] 773 of 2000 complete in 79.6 sec
[--------------   38%                  ] 779 of 2000 complete in 80.2 sec
[--------------   39%                  ] 784 of 2000 complete in 80.7 sec
[--------------   39%                  ] 789 of 2000 complete in 81.2 sec
[---------------  39%                  ] 794 of 2000 complete in 81.7 sec
[---------------  39%                  ] 799 of 2000 complete in 82.2 sec
[---------------  40%                  ] 804 of 2000 complete in 82.7 sec
[---------------  40%                  ] 809 of 2000 complete in 83.2 sec
[---------------  40%                  ] 814 of 2000 complete in 83.7 sec
[---------------  40%                  ] 819 of 2000 complete in 84.2 sec
[---------------  41%                  ] 825 of 2000 complete in 84.8 sec
[---------------  41%                  ] 830 of 2000 complete in 85.3 sec
[---------------  41%                  ] 835 of 2000 complete in 85.9 sec
[---------------  42%                  ] 840 of 2000 complete in 86.4 sec
[---------------- 42%                  ] 845 of 2000 complete in 86.9 sec
[---------------- 42%                  ] 850 of 2000 complete in 87.4 sec
[---------------- 42%                  ] 855 of 2000 complete in 87.9 sec
[---------------- 43%                  ] 860 of 2000 complete in 88.4 sec
[---------------- 43%                  ] 866 of 2000 complete in 89.0 sec
[---------------- 43%                  ] 871 of 2000 complete in 89.5 sec
[---------------- 43%                  ] 877 of 2000 complete in 90.1 sec
[---------------- 44%                  ] 882 of 2000 complete in 90.6 sec
[---------------- 44%                  ] 888 of 2000 complete in 91.2 sec
[---------------- 44%                  ] 894 of 2000 complete in 91.8 sec
[-----------------44%                  ] 899 of 2000 complete in 92.3 sec
[-----------------45%                  ] 904 of 2000 complete in 92.9 sec
[-----------------45%                  ] 909 of 2000 complete in 93.4 sec
[-----------------45%                  ] 914 of 2000 complete in 93.9 sec
[-----------------46%                  ] 920 of 2000 complete in 94.5 sec
[-----------------46%                  ] 925 of 2000 complete in 95.0 sec
[-----------------46%                  ] 930 of 2000 complete in 95.5 sec
[-----------------46%                  ] 936 of 2000 complete in 96.1 sec
[-----------------47%                  ] 941 of 2000 complete in 96.6 sec
[-----------------47%                  ] 947 of 2000 complete in 97.2 sec
[-----------------47%                  ] 953 of 2000 complete in 97.8 sec
[-----------------47%                  ] 958 of 2000 complete in 98.4 sec
[-----------------48%                  ] 964 of 2000 complete in 98.9 sec
[-----------------48%                  ] 969 of 2000 complete in 99.5 sec
[-----------------48%                  ] 974 of 2000 complete in 100.0 sec
[-----------------48%                  ] 979 of 2000 complete in 100.5 sec
[-----------------49%                  ] 984 of 2000 complete in 101.0 sec
[-----------------49%                  ] 990 of 2000 complete in 101.6 sec
[-----------------49%                  ] 995 of 2000 complete in 102.1 sec
[-----------------50%                  ] 1001 of 2000 complete in 102.7 sec
[-----------------50%                  ] 1007 of 2000 complete in 103.3 sec
[-----------------50%                  ] 1012 of 2000 complete in 103.8 sec
[-----------------50%                  ] 1018 of 2000 complete in 104.4 sec
[-----------------51%                  ] 1024 of 2000 complete in 105.0 sec
[-----------------51%                  ] 1029 of 2000 complete in 105.5 sec
[-----------------51%                  ] 1035 of 2000 complete in 106.1 sec
[-----------------52%                  ] 1040 of 2000 complete in 106.6 sec
[-----------------52%                  ] 1045 of 2000 complete in 107.1 sec
[-----------------52%                  ] 1050 of 2000 complete in 107.6 sec
[-----------------52%                  ] 1055 of 2000 complete in 108.1 sec
[-----------------53%                  ] 1060 of 2000 complete in 108.6 sec
[-----------------53%                  ] 1066 of 2000 complete in 109.2 sec
[-----------------53%                  ] 1072 of 2000 complete in 109.8 sec
[-----------------53%                  ] 1077 of 2000 complete in 110.3 sec
[-----------------54%                  ] 1082 of 2000 complete in 110.8 sec
[-----------------54%                  ] 1087 of 2000 complete in 111.3 sec
[-----------------54%                  ] 1093 of 2000 complete in 111.9 sec
[-----------------54%                  ] 1098 of 2000 complete in 112.5 sec
[-----------------55%                  ] 1103 of 2000 complete in 113.0 sec
[-----------------55%-                 ] 1108 of 2000 complete in 113.5 sec
[-----------------55%-                 ] 1113 of 2000 complete in 114.0 sec
[-----------------55%-                 ] 1118 of 2000 complete in 114.5 sec
[-----------------56%-                 ] 1123 of 2000 complete in 115.1 sec
[-----------------56%-                 ] 1128 of 2000 complete in 115.6 sec
[-----------------56%-                 ] 1133 of 2000 complete in 116.1 sec
[-----------------56%-                 ] 1138 of 2000 complete in 116.6 sec
[-----------------57%-                 ] 1143 of 2000 complete in 117.1 sec
[-----------------57%-                 ] 1148 of 2000 complete in 117.6 sec
[-----------------57%-                 ] 1153 of 2000 complete in 118.1 sec
[-----------------57%--                ] 1158 of 2000 complete in 118.6 sec
[-----------------58%--                ] 1163 of 2000 complete in 119.1 sec

[-----------------57%-                 ] 1143 of 2000 complete in 118.3 sec
[-----------------57%-                 ] 1148 of 2000 complete in 118.8 sec
[-----------------57%-                 ] 1153 of 2000 complete in 119.4 sec
[-----------------57%--                ] 1158 of 2000 complete in 119.9 sec
[-----------------58%--                ] 1163 of 2000 complete in 120.4 sec
[-----------------58%--                ] 1168 of 2000 complete in 120.9 sec
[-----------------58%--                ] 1173 of 2000 complete in 121.5 sec
[-----------------58%--                ] 1178 of 2000 complete in 122.0 sec
[-----------------59%--                ] 1183 of 2000 complete in 122.5 sec
[-----------------59%--                ] 1188 of 2000 complete in 123.1 sec
[-----------------59%--                ] 1193 of 2000 complete in 123.6 sec
[-----------------59%--                ] 1198 of 2000 complete in 124.1 sec
[-----------------60%--                ] 1203 of 2000 complete in 124.7 sec
[-----------------60%--                ] 1208 of 2000 complete in 125.2 sec
[-----------------60%---               ] 1213 of 2000 complete in 125.7 sec
[-----------------60%---               ] 1218 of 2000 complete in 126.2 sec
[-----------------61%---               ] 1223 of 2000 complete in 126.7 sec
[-----------------61%---               ] 1228 of 2000 complete in 127.3 sec
[-----------------61%---               ] 1233 of 2000 complete in 127.8 sec
[-----------------61%---               ] 1238 of 2000 complete in 128.3 sec
[-----------------62%---               ] 1243 of 2000 complete in 128.8 sec
[-----------------62%---               ] 1248 of 2000 complete in 129.4 sec
[-----------------62%---               ] 1253 of 2000 complete in 129.9 sec
[-----------------62%---               ] 1258 of 2000 complete in 130.4 sec
[-----------------63%---               ] 1263 of 2000 complete in 130.9 sec
[-----------------63%----              ] 1268 of 2000 complete in 131.5 sec
[-----------------63%----              ] 1273 of 2000 complete in 132.0 sec
[-----------------63%----              ] 1278 of 2000 complete in 132.5 sec
[-----------------64%----              ] 1283 of 2000 complete in 133.0 sec
[-----------------64%----              ] 1288 of 2000 complete in 133.6 sec
[-----------------64%----              ] 1293 of 2000 complete in 134.1 sec
[-----------------64%----              ] 1298 of 2000 complete in 134.6 sec
[-----------------65%----              ] 1303 of 2000 complete in 135.1 sec
[-----------------65%----              ] 1308 of 2000 complete in 135.6 sec
[-----------------65%----              ] 1313 of 2000 complete in 136.2 sec
[-----------------65%-----             ] 1318 of 2000 complete in 136.7 sec
[-----------------66%-----             ] 1323 of 2000 complete in 137.2 sec
[-----------------66%-----             ] 1328 of 2000 complete in 137.8 sec
[-----------------66%-----             ] 1333 of 2000 complete in 138.3 sec
[-----------------66%-----             ] 1338 of 2000 complete in 138.8 sec
[-----------------67%-----             ] 1343 of 2000 complete in 139.4 sec
[-----------------67%-----             ] 1348 of 2000 complete in 139.9 sec
[-----------------67%-----             ] 1353 of 2000 complete in 140.4 sec
[-----------------67%-----             ] 1358 of 2000 complete in 140.9 sec
[-----------------68%-----             ] 1363 of 2000 complete in 141.4 sec
[-----------------68%-----             ] 1368 of 2000 complete in 142.0 sec
[-----------------68%------            ] 1373 of 2000 complete in 142.5 sec
[-----------------68%------            ] 1378 of 2000 complete in 143.0 sec
[-----------------69%------            ] 1383 of 2000 complete in 143.6 sec
[-----------------69%------            ] 1388 of 2000 complete in 144.1 sec
[-----------------69%------            ] 1393 of 2000 complete in 144.6 sec
[-----------------69%------            ] 1398 of 2000 complete in 145.1 sec
[-----------------70%------            ] 1403 of 2000 complete in 145.7 sec
[-----------------70%------            ] 1408 of 2000 complete in 146.2 sec
[-----------------70%------            ] 1413 of 2000 complete in 146.7 sec
[-----------------70%------            ] 1418 of 2000 complete in 147.2 sec
[-----------------71%-------           ] 1423 of 2000 complete in 147.7 sec
[-----------------71%-------           ] 1428 of 2000 complete in 148.3 sec
[-----------------71%-------           ] 1433 of 2000 complete in 148.8 sec
[-----------------71%-------           ] 1438 of 2000 complete in 149.3 sec
[-----------------72%-------           ] 1443 of 2000 complete in 149.8 sec
[-----------------72%-------           ] 1448 of 2000 complete in 150.4 sec
[-----------------72%-------           ] 1453 of 2000 complete in 150.9 sec
[-----------------72%-------           ] 1458 of 2000 complete in 151.4 sec
[-----------------73%-------           ] 1463 of 2000 complete in 151.9 sec
[-----------------73%-------           ] 1468 of 2000 complete in 152.5 sec
[-----------------73%-------           ] 1473 of 2000 complete in 153.0 sec
[-----------------73%--------          ] 1478 of 2000 complete in 153.5 sec
[-----------------74%--------          ] 1483 of 2000 complete in 154.0 sec
[-----------------74%--------          ] 1488 of 2000 complete in 154.6 sec
[-----------------74%--------          ] 1493 of 2000 complete in 155.1 sec
[-----------------74%--------          ] 1498 of 2000 complete in 155.6 sec
[-----------------75%--------          ] 1503 of 2000 complete in 156.2 sec
[-----------------75%--------          ] 1508 of 2000 complete in 156.7 sec
[-----------------75%--------          ] 1513 of 2000 complete in 157.2 sec
[-----------------75%--------          ] 1518 of 2000 complete in 157.8 sec
[-----------------76%--------          ] 1523 of 2000 complete in 158.3 sec
[-----------------76%---------         ] 1528 of 2000 complete in 158.8 sec
[-----------------76%---------         ] 1533 of 2000 complete in 159.3 sec
[-----------------76%---------         ] 1538 of 2000 complete in 159.8 sec
[-----------------77%---------         ] 1543 of 2000 complete in 160.4 sec
[-----------------77%---------         ] 1548 of 2000 complete in 160.9 sec
[-----------------77%---------         ] 1553 of 2000 complete in 161.4 sec
[-----------------77%---------         ] 1558 of 2000 complete in 161.9 sec
[-----------------78%---------         ] 1563 of 2000 complete in 162.5 sec
[-----------------78%---------         ] 1568 of 2000 complete in 163.0 sec
[-----------------78%---------         ] 1573 of 2000 complete in 163.5 sec
[-----------------78%---------         ] 1578 of 2000 complete in 164.0 sec
[-----------------79%----------        ] 1583 of 2000 complete in 164.6 sec
[-----------------79%----------        ] 1588 of 2000 complete in 165.1 sec
[-----------------79%----------        ] 1593 of 2000 complete in 165.6 sec
[-----------------79%----------        ] 1598 of 2000 complete in 166.1 sec
[-----------------80%----------        ] 1603 of 2000 complete in 166.7 sec
[-----------------80%----------        ] 1608 of 2000 complete in 167.2 sec
[-----------------80%----------        ] 1613 of 2000 complete in 167.7 sec
[-----------------80%----------        ] 1618 of 2000 complete in 168.2 sec
[-----------------81%----------        ] 1623 of 2000 complete in 168.7 sec
[-----------------81%----------        ] 1628 of 2000 complete in 169.2 sec
[-----------------81%-----------       ] 1633 of 2000 complete in 169.8 sec
[-----------------81%-----------       ] 1638 of 2000 complete in 170.3 sec
[-----------------82%-----------       ] 1643 of 2000 complete in 170.8 sec
[-----------------82%-----------       ] 1648 of 2000 complete in 171.3 sec
[-----------------82%-----------       ] 1653 of 2000 complete in 171.9 sec
[-----------------82%-----------       ] 1658 of 2000 complete in 172.4 sec
[-----------------83%-----------       ] 1663 of 2000 complete in 172.9 sec
[-----------------83%-----------       ] 1668 of 2000 complete in 173.4 sec
[-----------------83%-----------       ] 1673 of 2000 complete in 173.9 sec
[-----------------57%-                 ] 1150 of 2000 complete in 118.7 sec
[-----------------57%-                 ] 1155 of 2000 complete in 119.2 sec
[-----------------58%--                ] 1160 of 2000 complete in 119.7 sec
[-----------------58%--                ] 1165 of 2000 complete in 120.3 sec
[-----------------58%--                ] 1170 of 2000 complete in 120.8 sec
[-----------------58%--                ] 1175 of 2000 complete in 121.3 sec
[-----------------59%--                ] 1180 of 2000 complete in 121.8 sec
[-----------------59%--                ] 1185 of 2000 complete in 122.4 sec
[-----------------59%--                ] 1190 of 2000 complete in 122.9 sec
[-----------------59%--                ] 1195 of 2000 complete in 123.4 sec
[-----------------60%--                ] 1200 of 2000 complete in 124.0 sec
[-----------------60%--                ] 1205 of 2000 complete in 124.5 sec
[-----------------60%--                ] 1210 of 2000 complete in 125.0 sec
[-----------------60%---               ] 1215 of 2000 complete in 125.5 sec
[-----------------61%---               ] 1220 of 2000 complete in 126.1 sec
[-----------------61%---               ] 1225 of 2000 complete in 126.6 sec
[-----------------61%---               ] 1230 of 2000 complete in 127.1 sec
[-----------------61%---               ] 1235 of 2000 complete in 127.6 sec
[-----------------62%---               ] 1240 of 2000 complete in 128.1 sec
[-----------------62%---               ] 1245 of 2000 complete in 128.7 sec
[-----------------62%---               ] 1250 of 2000 complete in 129.2 sec
[-----------------62%---               ] 1255 of 2000 complete in 129.7 sec
[-----------------63%---               ] 1260 of 2000 complete in 130.2 sec
[-----------------63%----              ] 1265 of 2000 complete in 130.7 sec
[-----------------63%----              ] 1270 of 2000 complete in 131.3 sec
[-----------------63%----              ] 1275 of 2000 complete in 131.8 sec
[-----------------64%----              ] 1280 of 2000 complete in 132.3 sec
[-----------------64%----              ] 1285 of 2000 complete in 132.9 sec
[-----------------64%----              ] 1290 of 2000 complete in 133.4 sec
[-----------------64%----              ] 1295 of 2000 complete in 133.9 sec
[-----------------65%----              ] 1300 of 2000 complete in 134.4 sec
[-----------------65%----              ] 1305 of 2000 complete in 135.0 sec
[-----------------65%----              ] 1310 of 2000 complete in 135.5 sec
[-----------------65%----              ] 1315 of 2000 complete in 136.0 sec
[-----------------66%-----             ] 1320 of 2000 complete in 136.5 sec
[-----------------66%-----             ] 1325 of 2000 complete in 137.0 sec
[-----------------66%-----             ] 1330 of 2000 complete in 137.5 sec
[-----------------66%-----             ] 1335 of 2000 complete in 138.1 sec
[-----------------67%-----             ] 1340 of 2000 complete in 138.6 sec
[-----------------67%-----             ] 1345 of 2000 complete in 139.1 sec
[-----------------67%-----             ] 1350 of 2000 complete in 139.7 sec
[-----------------67%-----             ] 1355 of 2000 complete in 140.2 sec
[-----------------68%-----             ] 1360 of 2000 complete in 140.7 sec
[-----------------68%-----             ] 1365 of 2000 complete in 141.2 sec
[-----------------68%------            ] 1370 of 2000 complete in 141.7 sec
[-----------------68%------            ] 1375 of 2000 complete in 142.3 sec
[-----------------69%------            ] 1380 of 2000 complete in 142.8 sec
[-----------------69%------            ] 1385 of 2000 complete in 143.3 sec
[-----------------69%------            ] 1390 of 2000 complete in 143.8 sec
[-----------------69%------            ] 1395 of 2000 complete in 144.3 sec
[-----------------70%------            ] 1400 of 2000 complete in 144.8 sec
[-----------------70%------            ] 1405 of 2000 complete in 145.4 sec
[-----------------70%------            ] 1411 of 2000 complete in 146.0 sec
[-----------------70%------            ] 1416 of 2000 complete in 146.5 sec
[-----------------71%------            ] 1421 of 2000 complete in 147.0 sec
[-----------------71%-------           ] 1426 of 2000 complete in 147.6 sec
[-----------------71%-------           ] 1431 of 2000 complete in 148.1 sec
[-----------------71%-------           ] 1436 of 2000 complete in 148.6 sec
[-----------------72%-------           ] 1441 of 2000 complete in 149.1 sec
[-----------------72%-------           ] 1446 of 2000 complete in 149.6 sec
[-----------------72%-------           ] 1451 of 2000 complete in 150.2 sec
[-----------------72%-------           ] 1456 of 2000 complete in 150.7 sec
[-----------------73%-------           ] 1461 of 2000 complete in 151.2 sec
[-----------------73%-------           ] 1466 of 2000 complete in 151.7 sec
[-----------------73%-------           ] 1471 of 2000 complete in 152.2 sec
[-----------------73%--------          ] 1476 of 2000 complete in 152.8 sec
[-----------------74%--------          ] 1481 of 2000 complete in 153.3 sec
[-----------------74%--------          ] 1486 of 2000 complete in 153.8 sec
[-----------------74%--------          ] 1491 of 2000 complete in 154.3 sec
[-----------------74%--------          ] 1496 of 2000 complete in 154.9 sec
[-----------------75%--------          ] 1501 of 2000 complete in 155.4 sec
[-----------------75%--------          ] 1506 of 2000 complete in 155.9 sec
[-----------------75%--------          ] 1511 of 2000 complete in 156.5 sec
[-----------------75%--------          ] 1516 of 2000 complete in 157.0 sec
[-----------------76%--------          ] 1521 of 2000 complete in 157.5 sec
[-----------------76%--------          ] 1526 of 2000 complete in 158.0 sec
[-----------------76%---------         ] 1531 of 2000 complete in 158.6 sec
[-----------------76%---------         ] 1536 of 2000 complete in 159.1 sec
[-----------------77%---------         ] 1541 of 2000 complete in 159.6 sec
[-----------------77%---------         ] 1546 of 2000 complete in 160.1 sec
[-----------------77%---------         ] 1551 of 2000 complete in 160.7 sec
[-----------------77%---------         ] 1556 of 2000 complete in 161.2 sec
[-----------------78%---------         ] 1561 of 2000 complete in 161.7 sec
[-----------------78%---------         ] 1566 of 2000 complete in 162.2 sec
[-----------------78%---------         ] 1571 of 2000 complete in 162.8 sec
[-----------------78%---------         ] 1576 of 2000 complete in 163.3 sec
[-----------------79%----------        ] 1581 of 2000 complete in 163.8 sec
[-----------------79%----------        ] 1586 of 2000 complete in 164.3 sec
[-----------------79%----------        ] 1591 of 2000 complete in 164.8 sec
[-----------------79%----------        ] 1596 of 2000 complete in 165.4 sec
[-----------------80%----------        ] 1601 of 2000 complete in 165.9 sec
[-----------------80%----------        ] 1606 of 2000 complete in 166.4 sec
[-----------------80%----------        ] 1611 of 2000 complete in 167.0 sec
[-----------------80%----------        ] 1616 of 2000 complete in 167.5 sec
[-----------------81%----------        ] 1621 of 2000 complete in 168.0 sec
[-----------------81%----------        ] 1626 of 2000 complete in 168.6 sec
[-----------------81%----------        ] 1631 of 2000 complete in 169.1 sec
[-----------------81%-----------       ] 1636 of 2000 complete in 169.6 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 170.1 sec
[-----------------82%-----------       ] 1646 of 2000 complete in 170.6 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 171.1 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 171.6 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 172.1 sec
[-----------------83%-----------       ] 1666 of 2000 complete in 172.7 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 173.2 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 173.7 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 174.2 sec

[-----------------58%--                ] 1168 of 2000 complete in 119.7 sec
[-----------------58%--                ] 1173 of 2000 complete in 120.2 sec
[-----------------58%--                ] 1178 of 2000 complete in 120.7 sec
[-----------------59%--                ] 1183 of 2000 complete in 121.2 sec
[-----------------59%--                ] 1188 of 2000 complete in 121.8 sec
[-----------------59%--                ] 1193 of 2000 complete in 122.3 sec
[-----------------59%--                ] 1198 of 2000 complete in 122.8 sec
[-----------------60%--                ] 1203 of 2000 complete in 123.3 sec
[-----------------60%--                ] 1208 of 2000 complete in 123.8 sec
[-----------------60%---               ] 1213 of 2000 complete in 124.4 sec
[-----------------60%---               ] 1218 of 2000 complete in 124.9 sec
[-----------------61%---               ] 1223 of 2000 complete in 125.4 sec
[-----------------61%---               ] 1228 of 2000 complete in 125.9 sec
[-----------------61%---               ] 1233 of 2000 complete in 126.5 sec
[-----------------61%---               ] 1238 of 2000 complete in 127.0 sec
[-----------------62%---               ] 1243 of 2000 complete in 127.5 sec
[-----------------62%---               ] 1248 of 2000 complete in 128.0 sec
[-----------------62%---               ] 1253 of 2000 complete in 128.6 sec
[-----------------62%---               ] 1258 of 2000 complete in 129.1 sec
[-----------------63%---               ] 1263 of 2000 complete in 129.6 sec
[-----------------63%----              ] 1268 of 2000 complete in 130.1 sec
[-----------------63%----              ] 1273 of 2000 complete in 130.6 sec
[-----------------63%----              ] 1278 of 2000 complete in 131.1 sec
[-----------------64%----              ] 1283 of 2000 complete in 131.7 sec
[-----------------64%----              ] 1288 of 2000 complete in 132.2 sec
[-----------------64%----              ] 1293 of 2000 complete in 132.7 sec
[-----------------64%----              ] 1298 of 2000 complete in 133.2 sec
[-----------------65%----              ] 1303 of 2000 complete in 133.7 sec
[-----------------65%----              ] 1308 of 2000 complete in 134.2 sec
[-----------------65%----              ] 1313 of 2000 complete in 134.7 sec
[-----------------65%-----             ] 1318 of 2000 complete in 135.2 sec
[-----------------66%-----             ] 1323 of 2000 complete in 135.7 sec
[-----------------66%-----             ] 1328 of 2000 complete in 136.3 sec
[-----------------66%-----             ] 1333 of 2000 complete in 136.8 sec
[-----------------66%-----             ] 1338 of 2000 complete in 137.3 sec
[-----------------67%-----             ] 1343 of 2000 complete in 137.8 sec
[-----------------67%-----             ] 1348 of 2000 complete in 138.3 sec
[-----------------67%-----             ] 1353 of 2000 complete in 138.8 sec
[-----------------67%-----             ] 1358 of 2000 complete in 139.3 sec
[-----------------68%-----             ] 1363 of 2000 complete in 139.8 sec
[-----------------68%-----             ] 1368 of 2000 complete in 140.4 sec
[-----------------68%------            ] 1373 of 2000 complete in 140.9 sec
[-----------------68%------            ] 1378 of 2000 complete in 141.4 sec
[-----------------69%------            ] 1383 of 2000 complete in 141.9 sec
[-----------------69%------            ] 1388 of 2000 complete in 142.5 sec
[-----------------69%------            ] 1393 of 2000 complete in 143.0 sec
[-----------------69%------            ] 1398 of 2000 complete in 143.5 sec
[-----------------70%------            ] 1404 of 2000 complete in 144.1 sec
[-----------------70%------            ] 1409 of 2000 complete in 144.6 sec
[-----------------70%------            ] 1414 of 2000 complete in 145.1 sec
[-----------------70%------            ] 1419 of 2000 complete in 145.6 sec
[-----------------71%-------           ] 1424 of 2000 complete in 146.1 sec
[-----------------71%-------           ] 1429 of 2000 complete in 146.6 sec
[-----------------71%-------           ] 1434 of 2000 complete in 147.2 sec
[-----------------71%-------           ] 1439 of 2000 complete in 147.7 sec
[-----------------72%-------           ] 1444 of 2000 complete in 148.2 sec
[-----------------72%-------           ] 1449 of 2000 complete in 148.7 sec
[-----------------72%-------           ] 1454 of 2000 complete in 149.2 sec
[-----------------72%-------           ] 1459 of 2000 complete in 149.7 sec
[-----------------73%-------           ] 1464 of 2000 complete in 150.3 sec
[-----------------73%-------           ] 1469 of 2000 complete in 150.8 sec
[-----------------73%--------          ] 1474 of 2000 complete in 151.3 sec
[-----------------73%--------          ] 1479 of 2000 complete in 151.8 sec
[-----------------74%--------          ] 1485 of 2000 complete in 152.4 sec
[-----------------74%--------          ] 1490 of 2000 complete in 152.9 sec
[-----------------74%--------          ] 1495 of 2000 complete in 153.4 sec
[-----------------75%--------          ] 1500 of 2000 complete in 154.0 sec
[-----------------75%--------          ] 1505 of 2000 complete in 154.5 sec
[-----------------75%--------          ] 1510 of 2000 complete in 155.0 sec
[-----------------75%--------          ] 1515 of 2000 complete in 155.5 sec
[-----------------76%--------          ] 1520 of 2000 complete in 156.1 sec
[-----------------76%--------          ] 1525 of 2000 complete in 156.6 sec
[-----------------76%---------         ] 1530 of 2000 complete in 157.1 sec
[-----------------76%---------         ] 1535 of 2000 complete in 157.6 sec
[-----------------77%---------         ] 1540 of 2000 complete in 158.1 sec
[-----------------77%---------         ] 1545 of 2000 complete in 158.6 sec
[-----------------77%---------         ] 1550 of 2000 complete in 159.1 sec
[-----------------77%---------         ] 1555 of 2000 complete in 159.7 sec
[-----------------78%---------         ] 1560 of 2000 complete in 160.2 sec
[-----------------78%---------         ] 1565 of 2000 complete in 160.7 sec
[-----------------78%---------         ] 1570 of 2000 complete in 161.2 sec
[-----------------78%---------         ] 1575 of 2000 complete in 161.7 sec
[-----------------79%----------        ] 1580 of 2000 complete in 162.2 sec
[-----------------79%----------        ] 1585 of 2000 complete in 162.7 sec
[-----------------79%----------        ] 1590 of 2000 complete in 163.2 sec
[-----------------79%----------        ] 1595 of 2000 complete in 163.8 sec
[-----------------80%----------        ] 1600 of 2000 complete in 164.3 sec
[-----------------80%----------        ] 1605 of 2000 complete in 164.8 sec
[-----------------80%----------        ] 1610 of 2000 complete in 165.3 sec
[-----------------80%----------        ] 1615 of 2000 complete in 165.9 sec
[-----------------81%----------        ] 1620 of 2000 complete in 166.4 sec
[-----------------81%----------        ] 1625 of 2000 complete in 166.9 sec
[-----------------81%----------        ] 1630 of 2000 complete in 167.4 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 167.9 sec
[-----------------82%-----------       ] 1640 of 2000 complete in 168.4 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 168.9 sec
[-----------------82%-----------       ] 1650 of 2000 complete in 169.5 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 170.0 sec
[-----------------83%-----------       ] 1660 of 2000 complete in 170.5 sec
[-----------------83%-----------       ] 1665 of 2000 complete in 171.0 sec
[-----------------83%-----------       ] 1670 of 2000 complete in 171.5 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 172.1 sec
[-----------------84%-----------       ] 1680 of 2000 complete in 172.6 sec
[-----------------84%------------      ] 1685 of 2000 complete in 173.1 sec
[-----------------84%------------      ] 1690 of 2000 complete in 173.6 sec
[-----------------84%------------      ] 1695 of 2000 complete in 174.1 sec
[-----------------85%------------      ] 1700 of 2000 complete in 174.6 sec
[-----------------57%-                 ] 1154 of 2000 complete in 119.2 sec
[-----------------57%--                ] 1159 of 2000 complete in 119.8 sec
[-----------------58%--                ] 1164 of 2000 complete in 120.3 sec
[-----------------58%--                ] 1169 of 2000 complete in 120.8 sec
[-----------------58%--                ] 1174 of 2000 complete in 121.3 sec
[-----------------58%--                ] 1179 of 2000 complete in 121.8 sec
[-----------------59%--                ] 1184 of 2000 complete in 122.3 sec
[-----------------59%--                ] 1189 of 2000 complete in 122.9 sec
[-----------------59%--                ] 1194 of 2000 complete in 123.4 sec
[-----------------59%--                ] 1199 of 2000 complete in 123.9 sec
[-----------------60%--                ] 1204 of 2000 complete in 124.5 sec
[-----------------60%--                ] 1209 of 2000 complete in 125.0 sec
[-----------------60%---               ] 1214 of 2000 complete in 125.5 sec
[-----------------60%---               ] 1219 of 2000 complete in 126.0 sec
[-----------------61%---               ] 1224 of 2000 complete in 126.6 sec
[-----------------61%---               ] 1229 of 2000 complete in 127.1 sec
[-----------------61%---               ] 1234 of 2000 complete in 127.6 sec
[-----------------61%---               ] 1239 of 2000 complete in 128.1 sec
[-----------------62%---               ] 1244 of 2000 complete in 128.6 sec
[-----------------62%---               ] 1249 of 2000 complete in 129.2 sec
[-----------------62%---               ] 1254 of 2000 complete in 129.7 sec
[-----------------62%---               ] 1259 of 2000 complete in 130.2 sec
[-----------------63%----              ] 1264 of 2000 complete in 130.7 sec
[-----------------63%----              ] 1269 of 2000 complete in 131.3 sec
[-----------------63%----              ] 1274 of 2000 complete in 131.8 sec
[-----------------63%----              ] 1279 of 2000 complete in 132.3 sec
[-----------------64%----              ] 1284 of 2000 complete in 132.8 sec
[-----------------64%----              ] 1289 of 2000 complete in 133.4 sec
[-----------------64%----              ] 1294 of 2000 complete in 133.9 sec
[-----------------64%----              ] 1299 of 2000 complete in 134.4 sec
[-----------------65%----              ] 1304 of 2000 complete in 134.9 sec
[-----------------65%----              ] 1309 of 2000 complete in 135.4 sec
[-----------------65%----              ] 1314 of 2000 complete in 136.0 sec
[-----------------65%-----             ] 1319 of 2000 complete in 136.5 sec
[-----------------66%-----             ] 1324 of 2000 complete in 137.0 sec
[-----------------66%-----             ] 1329 of 2000 complete in 137.5 sec
[-----------------66%-----             ] 1334 of 2000 complete in 138.0 sec
[-----------------66%-----             ] 1339 of 2000 complete in 138.6 sec
[-----------------67%-----             ] 1344 of 2000 complete in 139.1 sec
[-----------------67%-----             ] 1349 of 2000 complete in 139.6 sec
[-----------------67%-----             ] 1354 of 2000 complete in 140.1 sec
[-----------------67%-----             ] 1359 of 2000 complete in 140.6 sec
[-----------------68%-----             ] 1364 of 2000 complete in 141.2 sec
[-----------------68%------            ] 1369 of 2000 complete in 141.7 sec
[-----------------68%------            ] 1374 of 2000 complete in 142.2 sec
[-----------------68%------            ] 1379 of 2000 complete in 142.7 sec
[-----------------69%------            ] 1384 of 2000 complete in 143.2 sec
[-----------------69%------            ] 1389 of 2000 complete in 143.7 sec
[-----------------69%------            ] 1394 of 2000 complete in 144.3 sec
[-----------------69%------            ] 1399 of 2000 complete in 144.8 sec
[-----------------70%------            ] 1404 of 2000 complete in 145.3 sec
[-----------------70%------            ] 1409 of 2000 complete in 145.9 sec
[-----------------70%------            ] 1414 of 2000 complete in 146.4 sec
[-----------------70%------            ] 1419 of 2000 complete in 146.9 sec
[-----------------71%-------           ] 1424 of 2000 complete in 147.4 sec
[-----------------71%-------           ] 1429 of 2000 complete in 148.0 sec
[-----------------71%-------           ] 1434 of 2000 complete in 148.5 sec
[-----------------71%-------           ] 1439 of 2000 complete in 149.0 sec
[-----------------72%-------           ] 1444 of 2000 complete in 149.6 sec
[-----------------72%-------           ] 1449 of 2000 complete in 150.1 sec
[-----------------72%-------           ] 1454 of 2000 complete in 150.6 sec
[-----------------72%-------           ] 1459 of 2000 complete in 151.1 sec
[-----------------73%-------           ] 1464 of 2000 complete in 151.7 sec
[-----------------73%-------           ] 1469 of 2000 complete in 152.2 sec
[-----------------73%--------          ] 1474 of 2000 complete in 152.7 sec
[-----------------73%--------          ] 1479 of 2000 complete in 153.2 sec
[-----------------74%--------          ] 1484 of 2000 complete in 153.8 sec
[-----------------74%--------          ] 1489 of 2000 complete in 154.3 sec
[-----------------74%--------          ] 1494 of 2000 complete in 154.8 sec
[-----------------74%--------          ] 1499 of 2000 complete in 155.3 sec
[-----------------75%--------          ] 1504 of 2000 complete in 155.8 sec
[-----------------75%--------          ] 1509 of 2000 complete in 156.4 sec
[-----------------75%--------          ] 1514 of 2000 complete in 156.9 sec
[-----------------75%--------          ] 1519 of 2000 complete in 157.4 sec
[-----------------76%--------          ] 1524 of 2000 complete in 158.0 sec
[-----------------76%---------         ] 1529 of 2000 complete in 158.5 sec
[-----------------76%---------         ] 1534 of 2000 complete in 159.0 sec
[-----------------76%---------         ] 1539 of 2000 complete in 159.5 sec
[-----------------77%---------         ] 1544 of 2000 complete in 160.1 sec
[-----------------77%---------         ] 1549 of 2000 complete in 160.6 sec
[-----------------77%---------         ] 1554 of 2000 complete in 161.1 sec
[-----------------77%---------         ] 1559 of 2000 complete in 161.6 sec
[-----------------78%---------         ] 1564 of 2000 complete in 162.1 sec
[-----------------78%---------         ] 1569 of 2000 complete in 162.7 sec
[-----------------78%---------         ] 1574 of 2000 complete in 163.2 sec
[-----------------78%----------        ] 1579 of 2000 complete in 163.7 sec
[-----------------79%----------        ] 1584 of 2000 complete in 164.3 sec
[-----------------79%----------        ] 1589 of 2000 complete in 164.8 sec
[-----------------79%----------        ] 1594 of 2000 complete in 165.3 sec
[-----------------79%----------        ] 1599 of 2000 complete in 165.9 sec
[-----------------80%----------        ] 1604 of 2000 complete in 166.4 sec
[-----------------80%----------        ] 1609 of 2000 complete in 166.9 sec
[-----------------80%----------        ] 1614 of 2000 complete in 167.4 sec
[-----------------80%----------        ] 1619 of 2000 complete in 167.9 sec
[-----------------81%----------        ] 1624 of 2000 complete in 168.5 sec
[-----------------81%----------        ] 1630 of 2000 complete in 169.1 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 169.6 sec
[-----------------82%-----------       ] 1640 of 2000 complete in 170.1 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 170.6 sec
[-----------------82%-----------       ] 1650 of 2000 complete in 171.1 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 171.6 sec
[-----------------83%-----------       ] 1660 of 2000 complete in 172.2 sec
[-----------------83%-----------       ] 1666 of 2000 complete in 172.8 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 173.3 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 173.8 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 174.3 sec
[-----------------84%------------      ] 1686 of 2000 complete in 174.8 sec

hddm sampling elpased time:  229.497 s
Start converting to InferenceData...
[-----------------85%------------      ] 1705 of 2000 complete in 175.1 sec
[-----------------85%------------      ] 1710 of 2000 complete in 175.7 sec
[-----------------85%------------      ] 1715 of 2000 complete in 176.2 sec
[-----------------86%------------      ] 1720 of 2000 complete in 176.7 sec
[-----------------86%------------      ] 1725 of 2000 complete in 177.2 sec
[-----------------86%------------      ] 1730 of 2000 complete in 177.7 sec
[-----------------86%------------      ] 1735 of 2000 complete in 178.2 sec
[-----------------87%-------------     ] 1740 of 2000 complete in 178.8 sec
[-----------------87%-------------     ] 1745 of 2000 complete in 179.3 sec
[-----------------87%-------------     ] 1750 of 2000 complete in 179.8 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 180.3 sec
[-----------------88%-------------     ] 1760 of 2000 complete in 180.8 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 181.3 sec
[-----------------88%-------------     ] 1770 of 2000 complete in 181.8 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 182.4 sec
[-----------------89%-------------     ] 1780 of 2000 complete in 182.9 sec
[-----------------89%-------------     ] 1785 of 2000 complete in 183.4 sec
[-----------------89%--------------    ] 1790 of 2000 complete in 183.9 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 184.4 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 185.0 sec
[-----------------90%--------------    ] 1806 of 2000 complete in 185.6 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 186.1 sec
[-----------------90%--------------    ] 1816 of 2000 complete in 186.6 sec
[-----------------91%--------------    ] 1821 of 2000 complete in 187.1 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 187.6 sec
[-----------------91%--------------    ] 1831 of 2000 complete in 188.1 sec
[-----------------91%--------------    ] 1836 of 2000 complete in 188.6 sec
[-----------------92%--------------    ] 1841 of 2000 complete in 189.2 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 189.7 sec
[-----------------92%---------------   ] 1851 of 2000 complete in 190.2 sec
[-----------------92%---------------   ] 1856 of 2000 complete in 190.7 sec
[-----------------93%---------------   ] 1861 of 2000 complete in 191.3 sec
[-----------------93%---------------   ] 1866 of 2000 complete in 191.8 sec
[-----------------93%---------------   ] 1871 of 2000 complete in 192.3 sec
[-----------------93%---------------   ] 1877 of 2000 complete in 192.9 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 193.4 sec
[-----------------94%---------------   ] 1887 of 2000 complete in 194.0 sec
[-----------------94%---------------   ] 1892 of 2000 complete in 194.5 sec
[-----------------94%----------------  ] 1897 of 2000 complete in 195.0 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 195.5 sec
[-----------------95%----------------  ] 1907 of 2000 complete in 196.0 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 196.5 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 197.0 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 197.6 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 198.1 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 198.6 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 199.1 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 199.6 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 200.1 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 200.6 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 201.1 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 201.7 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 202.3 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 202.8 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 203.3 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 203.8 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 204.3 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 204.8 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 205.4 sec
[-----------------100%-----------------] 2000 of 2000 complete in 205.7 sec
hddm sampling elpased time:  205.81 s
[-----------------84%------------      ] 1691 of 2000 complete in 175.4 sec
[-----------------84%------------      ] 1696 of 2000 complete in 175.9 sec
[-----------------85%------------      ] 1701 of 2000 complete in 176.4 sec
[-----------------85%------------      ] 1706 of 2000 complete in 176.9 sec
[-----------------85%------------      ] 1711 of 2000 complete in 177.5 sec
[-----------------85%------------      ] 1716 of 2000 complete in 178.0 sec
[-----------------86%------------      ] 1721 of 2000 complete in 178.5 sec
[-----------------86%------------      ] 1726 of 2000 complete in 179.0 sec
[-----------------86%------------      ] 1731 of 2000 complete in 179.6 sec
[-----------------86%------------      ] 1736 of 2000 complete in 180.1 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 180.6 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 181.1 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 181.6 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 182.1 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 182.6 sec
[-----------------88%-------------     ] 1766 of 2000 complete in 183.2 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 183.7 sec
[-----------------88%-------------     ] 1776 of 2000 complete in 184.2 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 184.7 sec
[-----------------89%-------------     ] 1786 of 2000 complete in 185.2 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 185.7 sec
[-----------------89%--------------    ] 1796 of 2000 complete in 186.3 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 186.8 sec
[-----------------90%--------------    ] 1806 of 2000 complete in 187.3 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 187.8 sec
[-----------------90%--------------    ] 1816 of 2000 complete in 188.4 sec
[-----------------91%--------------    ] 1821 of 2000 complete in 188.9 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 189.4 sec
[-----------------91%--------------    ] 1831 of 2000 complete in 190.0 sec
[-----------------91%--------------    ] 1836 of 2000 complete in 190.5 sec
[-----------------92%--------------    ] 1841 of 2000 complete in 191.0 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 191.5 sec
[-----------------92%---------------   ] 1851 of 2000 complete in 192.0 sec
[-----------------92%---------------   ] 1856 of 2000 complete in 192.6 sec
[-----------------93%---------------   ] 1861 of 2000 complete in 193.1 sec
[-----------------93%---------------   ] 1866 of 2000 complete in 193.6 sec
[-----------------93%---------------   ] 1871 of 2000 complete in 194.1 sec
[-----------------93%---------------   ] 1876 of 2000 complete in 194.6 sec
[-----------------94%---------------   ] 1881 of 2000 complete in 195.1 sec
[-----------------94%---------------   ] 1886 of 2000 complete in 195.6 sec
[-----------------94%---------------   ] 1891 of 2000 complete in 196.2 sec
[-----------------94%----------------  ] 1896 of 2000 complete in 196.7 sec
[-----------------95%----------------  ] 1901 of 2000 complete in 197.2 sec
[-----------------95%----------------  ] 1906 of 2000 complete in 197.7 sec
[-----------------95%----------------  ] 1911 of 2000 complete in 198.2 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 198.7 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 199.2 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 199.7 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 200.3 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 200.9 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 201.4 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 201.9 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 202.4 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 202.9 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 203.4 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 204.0 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 204.5 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 205.0 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 205.5 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 206.0 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 206.6 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 207.1 sec
[-----------------100%-----------------] 2000 of 2000 complete in 207.5 sec
hddm sampling elpased time:  207.681 s

[-----------------84%------------      ] 1686 of 2000 complete in 174.8 sec
[-----------------84%------------      ] 1691 of 2000 complete in 175.3 sec
[-----------------84%------------      ] 1696 of 2000 complete in 175.8 sec
[-----------------85%------------      ] 1701 of 2000 complete in 176.4 sec
[-----------------85%------------      ] 1706 of 2000 complete in 176.9 sec
[-----------------85%------------      ] 1711 of 2000 complete in 177.4 sec
[-----------------85%------------      ] 1716 of 2000 complete in 177.9 sec
[-----------------86%------------      ] 1721 of 2000 complete in 178.5 sec
[-----------------86%------------      ] 1726 of 2000 complete in 179.0 sec
[-----------------86%------------      ] 1731 of 2000 complete in 179.5 sec
[-----------------86%------------      ] 1736 of 2000 complete in 180.1 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 180.6 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 181.1 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 181.6 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 182.1 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 182.7 sec
[-----------------88%-------------     ] 1766 of 2000 complete in 183.2 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 183.7 sec
[-----------------88%-------------     ] 1776 of 2000 complete in 184.3 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 184.8 sec
[-----------------89%-------------     ] 1786 of 2000 complete in 185.3 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 185.8 sec
[-----------------89%--------------    ] 1796 of 2000 complete in 186.4 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 186.9 sec
[-----------------90%--------------    ] 1806 of 2000 complete in 187.4 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 187.9 sec
[-----------------90%--------------    ] 1816 of 2000 complete in 188.4 sec
[-----------------91%--------------    ] 1821 of 2000 complete in 189.0 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 189.5 sec
[-----------------91%--------------    ] 1831 of 2000 complete in 190.0 sec
[-----------------91%--------------    ] 1836 of 2000 complete in 190.5 sec
[-----------------92%--------------    ] 1841 of 2000 complete in 191.0 sec
[-----------------92%---------------   ] 1847 of 2000 complete in 191.6 sec
[-----------------92%---------------   ] 1852 of 2000 complete in 192.2 sec
[-----------------92%---------------   ] 1857 of 2000 complete in 192.7 sec
[-----------------93%---------------   ] 1862 of 2000 complete in 193.2 sec
[-----------------93%---------------   ] 1867 of 2000 complete in 193.7 sec
[-----------------93%---------------   ] 1872 of 2000 complete in 194.3 sec
[-----------------93%---------------   ] 1877 of 2000 complete in 194.8 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 195.3 sec
[-----------------94%---------------   ] 1887 of 2000 complete in 195.8 sec
[-----------------94%---------------   ] 1892 of 2000 complete in 196.3 sec
[-----------------94%----------------  ] 1897 of 2000 complete in 196.8 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 197.3 sec
[-----------------95%----------------  ] 1907 of 2000 complete in 197.9 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 198.4 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 198.9 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 199.4 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 200.0 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 200.5 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 201.1 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 201.6 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 202.1 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 202.6 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 203.1 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 203.7 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 204.2 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 204.8 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 205.3 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 205.8 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 206.4 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 207.0 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 207.5 sec
[-----------------100%-----------------] 2000 of 2000 complete in 207.7 sec
hddm sampling elpased time:  207.855 s
[-----------------83%-----------       ] 1678 of 2000 complete in 174.5 sec
[-----------------84%-----------       ] 1683 of 2000 complete in 175.0 sec
[-----------------84%------------      ] 1688 of 2000 complete in 175.5 sec
[-----------------84%------------      ] 1693 of 2000 complete in 176.1 sec
[-----------------84%------------      ] 1698 of 2000 complete in 176.6 sec
[-----------------85%------------      ] 1703 of 2000 complete in 177.1 sec
[-----------------85%------------      ] 1708 of 2000 complete in 177.6 sec
[-----------------85%------------      ] 1713 of 2000 complete in 178.1 sec
[-----------------85%------------      ] 1718 of 2000 complete in 178.6 sec
[-----------------86%------------      ] 1723 of 2000 complete in 179.2 sec
[-----------------86%------------      ] 1728 of 2000 complete in 179.7 sec
[-----------------86%------------      ] 1733 of 2000 complete in 180.2 sec
[-----------------86%-------------     ] 1738 of 2000 complete in 180.7 sec
[-----------------87%-------------     ] 1743 of 2000 complete in 181.3 sec
[-----------------87%-------------     ] 1748 of 2000 complete in 181.8 sec
[-----------------87%-------------     ] 1753 of 2000 complete in 182.3 sec
[-----------------87%-------------     ] 1758 of 2000 complete in 182.8 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 183.4 sec
[-----------------88%-------------     ] 1768 of 2000 complete in 183.9 sec
[-----------------88%-------------     ] 1773 of 2000 complete in 184.4 sec
[-----------------88%-------------     ] 1778 of 2000 complete in 185.0 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 185.5 sec
[-----------------89%-------------     ] 1788 of 2000 complete in 186.0 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 186.5 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 187.1 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 187.6 sec
[-----------------90%--------------    ] 1808 of 2000 complete in 188.1 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 188.7 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 189.2 sec
[-----------------91%--------------    ] 1823 of 2000 complete in 189.7 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 190.2 sec
[-----------------91%--------------    ] 1833 of 2000 complete in 190.8 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 191.3 sec
[-----------------92%---------------   ] 1843 of 2000 complete in 191.8 sec
[-----------------92%---------------   ] 1848 of 2000 complete in 192.3 sec
[-----------------92%---------------   ] 1853 of 2000 complete in 192.8 sec
[-----------------92%---------------   ] 1858 of 2000 complete in 193.3 sec
[-----------------93%---------------   ] 1863 of 2000 complete in 193.9 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 194.4 sec
[-----------------93%---------------   ] 1873 of 2000 complete in 194.9 sec
[-----------------93%---------------   ] 1878 of 2000 complete in 195.4 sec
[-----------------94%---------------   ] 1883 of 2000 complete in 195.9 sec
[-----------------94%---------------   ] 1888 of 2000 complete in 196.5 sec
[-----------------94%---------------   ] 1893 of 2000 complete in 197.0 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 197.5 sec
[-----------------95%----------------  ] 1903 of 2000 complete in 198.0 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 198.5 sec
[-----------------95%----------------  ] 1913 of 2000 complete in 199.0 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 199.6 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 200.1 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 200.6 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 201.1 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 201.7 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 202.2 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 202.7 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 203.2 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 203.8 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 204.3 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 204.8 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 205.3 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 205.9 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 206.4 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 207.0 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 207.5 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 208.0 sec
[-----------------100%-----------------] 2000 of 2000 complete in 208.4 sec
hddm sampling elpased time:  208.503 s

In [25]:
summary = az.summary(hddmStim_zflip_m1_diff_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

             mean     sd  hdi_3%  hdi_97%  mcse_mean  mcse_sd  ess_bulk
a           1.832  0.345   1.214    2.439      0.010    0.007    1466.0  \
a_std       1.295  0.313   0.811    1.885      0.039    0.027      62.0
v(Other.0)  3.529  0.220   3.123    3.946      0.023    0.017      88.0
v(Self.1)   3.394  0.224   2.988    3.833      0.021    0.015     109.0
v_std       1.327  0.123   1.104    1.559      0.014    0.010      83.0
t           0.235  0.010   0.215    0.253      0.002    0.001      30.0
t_std       0.052  0.008   0.039    0.068      0.001    0.001      36.0
z           0.542  0.007   0.528    0.555      0.000    0.000    1486.0
z_std       0.158  0.024   0.113    0.202      0.001    0.001     424.0

            ess_tail  r_hat
a             1075.0   1.01
a_std          340.0   1.05
v(Other.0)    1565.0   1.03
v(Self.1)     1182.0   1.03
v_std          862.0   1.04
t              127.0   1.08
t_std          324.0   1.08
z             2992.0   1.01
z_std         2233.0   1.02

In [27]:
#HDDMRegression
#accuracy coding
#choice coding
#stim coding: accuracy coding + v flip + dc
#stim coding: choice coding + z flp
# accuracy coding
data['response'] = data['acc']

v_reg = [{"model": "v ~ 1", "link_func": lambda x: x}]

hddmReg_id_m0_acc_diff = hddm.HDDMRegressor(
    data,
    v_reg,
    bias=True, p_outlier=0.05,
    include=['v', 'a', 't', 'z'],
    depends_on={'v':['id','stim']},
    group_only_regressors=False
)

hddmReg_id_m0_acc_diff_idata = hddmReg_id_m0_acc_diff.sample(2000, burn=500, chains=4, return_infdata=True, dbname = 'hddmReg_id_m0_acc_diff.db', db = 'pickle')
hddmReg_id_m0_acc_diff.save('hddmReg_id_m0_acc_diff.hddm')

No model attribute --> setting up standard HDDM
Set model to ddm

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

[                  0%                  ] 3 of 2000 complete in 0.8 sec
[                  0%                  ] 4 of 2000 complete in 1.3 sec
[                  0%                  ] 6 of 2000 complete in 2.2 sec
[                  0%                  ] 8 of 2000 complete in 3.1 sec
[                  0%                  ] 10 of 2000 complete in 4.0 sec
[                  0%                  ] 12 of 2000 complete in 4.9 sec
[                  0%                  ] 14 of 2000 complete in 5.7 sec
[                  0%                  ] 16 of 2000 complete in 6.6 sec
[                  0%                  ] 18 of 2000 complete in 7.5 sec
[                  1%                  ] 20 of 2000 complete in 8.3 sec
[                  1%                  ] 22 of 2000 complete in 9.2 sec
[                  1%                  ] 24 of 2000 complete in 10.1 sec
[                  1%                  ] 26 of 2000 complete in 10.9 sec
[                  1%                  ] 28 of 2000 complete in 11.8 sec
[                  1%                  ] 30 of 2000 complete in 12.7 sec
[                  1%                  ] 32 of 2000 complete in 13.6 sec
[                  1%                  ] 34 of 2000 complete in 14.5 sec
[                  1%                  ] 36 of 2000 complete in 15.3 sec
[                  1%                  ] 38 of 2000 complete in 16.2 sec
[                  2%                  ] 40 of 2000 complete in 17.0 sec
[                  2%                  ] 42 of 2000 complete in 17.9 sec
[                  2%                  ] 44 of 2000 complete in 18.7 sec
[                  2%                  ] 46 of 2000 complete in 19.6 sec
[                  2%                  ] 48 of 2000 complete in 20.5 sec
[                  2%                  ] 50 of 2000 complete in 21.4 sec
[                  2%                  ] 52 of 2000 complete in 22.3 sec
[-                 2%                  ] 54 of 2000 complete in 23.1 sec
[-                 2%                  ] 56 of 2000 complete in 24.1 sec
[-                 2%                  ] 58 of 2000 complete in 25.0 sec
[-                 3%                  ] 60 of 2000 complete in 25.8 sec
[-                 3%                  ] 62 of 2000 complete in 26.7 sec
[-                 3%                  ] 64 of 2000 complete in 27.5 sec
[-                 3%                  ] 66 of 2000 complete in 28.3 sec
[-                 3%                  ] 68 of 2000 complete in 29.2 sec
[-                 3%                  ] 70 of 2000 complete in 30.0 sec
[-                 3%                  ] 72 of 2000 complete in 30.9 sec
[-                 3%                  ] 74 of 2000 complete in 31.8 sec
[-                 3%                  ] 76 of 2000 complete in 32.6 sec
[-                 3%                  ] 78 of 2000 complete in 33.5 sec
[-                 4%                  ] 80 of 2000 complete in 34.4 sec
[-                 4%                  ] 82 of 2000 complete in 35.2 sec
[-                 4%                  ] 84 of 2000 complete in 36.0 sec
[-                 4%                  ] 86 of 2000 complete in 36.9 sec
[-                 4%                  ] 88 of 2000 complete in 37.7 sec
[-                 4%                  ] 90 of 2000 complete in 38.5 sec
[-                 4%                  ] 92 of 2000 complete in 39.4 sec
[-                 4%                  ] 94 of 2000 complete in 40.2 sec
[-                 4%                  ] 96 of 2000 complete in 41.1 sec
[-                 4%                  ] 98 of 2000 complete in 41.9 sec
[-                 5%                  ] 100 of 2000 complete in 42.8 sec
[-                 5%                  ] 102 of 2000 complete in 43.6 sec
[-                 5%                  ] 104 of 2000 complete in 44.5 sec
[--                5%                  ] 106 of 2000 complete in 45.3 sec
[--                5%                  ] 108 of 2000 complete in 46.1 sec
[--                5%                  ] 110 of 2000 complete in 47.0 sec
[--                5%                  ] 112 of 2000 complete in 47.9 sec
[--                5%                  ] 114 of 2000 complete in 48.7 sec
[--                5%                  ] 116 of 2000 complete in 49.5 sec
[--                5%                  ] 118 of 2000 complete in 50.4 sec
[--                6%                  ] 120 of 2000 complete in 51.2 sec
[--                6%                  ] 122 of 2000 complete in 52.1 sec
[--                6%                  ] 124 of 2000 complete in 52.9 sec
[--                6%                  ] 126 of 2000 complete in 53.7 sec
[--                6%                  ] 128 of 2000 complete in 54.5 sec
[--                6%                  ] 130 of 2000 complete in 55.3 sec
[--                6%                  ] 132 of 2000 complete in 56.1 sec
[--                6%                  ] 134 of 2000 complete in 56.9 sec
[--                6%                  ] 136 of 2000 complete in 57.7 sec
[--                6%                  ] 138 of 2000 complete in 58.6 sec
[--                7%                  ] 140 of 2000 complete in 59.4 sec
[--                7%                  ] 142 of 2000 complete in 60.2 sec
[--                7%                  ] 144 of 2000 complete in 61.0 sec
[--                7%                  ] 146 of 2000 complete in 61.8 sec
[--                7%                  ] 148 of 2000 complete in 62.6 sec
[--                7%                  ] 150 of 2000 complete in 63.4 sec
[--                7%                  ] 152 of 2000 complete in 64.3 sec
[--                7%                  ] 154 of 2000 complete in 65.1 sec
[--                7%                  ] 156 of 2000 complete in 65.9 sec
[---               7%                  ] 158 of 2000 complete in 66.7 sec
[---               8%                  ] 160 of 2000 complete in 67.4 sec
[---               8%                  ] 162 of 2000 complete in 68.2 sec
[---               8%                  ] 164 of 2000 complete in 69.1 sec
[---               8%                  ] 166 of 2000 complete in 70.0 sec
[---               8%                  ] 168 of 2000 complete in 70.8 sec
[---               8%                  ] 170 of 2000 complete in 71.6 sec
[---               8%                  ] 172 of 2000 complete in 72.4 sec
[---               8%                  ] 174 of 2000 complete in 73.2 sec
[---               8%                  ] 176 of 2000 complete in 74.0 sec
[---               8%                  ] 178 of 2000 complete in 74.8 sec
[---               9%                  ] 180 of 2000 complete in 75.6 sec
[---               9%                  ] 182 of 2000 complete in 76.4 sec
[---               9%                  ] 184 of 2000 complete in 77.2 sec
[---               9%                  ] 186 of 2000 complete in 78.0 sec
[---               9%                  ] 188 of 2000 complete in 78.8 sec
[---               9%                  ] 190 of 2000 complete in 79.7 sec
[---               9%                  ] 192 of 2000 complete in 80.5 sec
[---               9%                  ] 194 of 2000 complete in 81.4 sec
[---               9%                  ] 196 of 2000 complete in 82.2 sec
[---               9%                  ] 198 of 2000 complete in 83.0 sec
[---              10%                  ] 200 of 2000 complete in 83.8 sec
[---              10%                  ] 202 of 2000 complete in 84.6 sec
[---              10%                  ] 204 of 2000 complete in 85.4 sec
[---              10%                  ] 206 of 2000 complete in 86.3 sec
[---              10%                  ] 208 of 2000 complete in 87.1 sec
[---              10%                  ] 210 of 2000 complete in 87.9 sec
[----             10%                  ] 212 of 2000 complete in 88.7 sec
[----             10%                  ] 214 of 2000 complete in 89.5 sec
[----             10%                  ] 216 of 2000 complete in 90.3 sec
[----             10%                  ] 218 of 2000 complete in 91.1 sec
[----             11%                  ] 220 of 2000 complete in 91.9 sec
[----             11%                  ] 222 of 2000 complete in 92.7 sec
[                  0%                  ] 3 of 2000 complete in 0.9 sec
[                  0%                  ] 4 of 2000 complete in 1.4 sec
[                  0%                  ] 6 of 2000 complete in 2.3 sec
[                  0%                  ] 8 of 2000 complete in 3.2 sec
[                  0%                  ] 10 of 2000 complete in 4.1 sec
[                  0%                  ] 12 of 2000 complete in 5.0 sec
[                  0%                  ] 14 of 2000 complete in 5.8 sec
[                  0%                  ] 16 of 2000 complete in 6.8 sec
[                  0%                  ] 18 of 2000 complete in 7.7 sec
[                  1%                  ] 20 of 2000 complete in 8.6 sec
[                  1%                  ] 22 of 2000 complete in 9.5 sec
[                  1%                  ] 24 of 2000 complete in 10.3 sec
[                  1%                  ] 26 of 2000 complete in 11.2 sec
[                  1%                  ] 28 of 2000 complete in 12.1 sec
[                  1%                  ] 30 of 2000 complete in 13.0 sec
[                  1%                  ] 32 of 2000 complete in 13.9 sec
[                  1%                  ] 34 of 2000 complete in 14.8 sec
[                  1%                  ] 36 of 2000 complete in 15.6 sec
[                  1%                  ] 38 of 2000 complete in 16.4 sec
[                  2%                  ] 40 of 2000 complete in 17.3 sec
[                  2%                  ] 42 of 2000 complete in 18.1 sec
[                  2%                  ] 44 of 2000 complete in 19.1 sec
[                  2%                  ] 46 of 2000 complete in 20.0 sec
[                  2%                  ] 48 of 2000 complete in 20.9 sec
[                  2%                  ] 50 of 2000 complete in 21.7 sec
[                  2%                  ] 52 of 2000 complete in 22.6 sec
[-                 2%                  ] 54 of 2000 complete in 23.5 sec
[-                 2%                  ] 56 of 2000 complete in 24.4 sec
[-                 2%                  ] 58 of 2000 complete in 25.3 sec
[-                 3%                  ] 60 of 2000 complete in 26.1 sec
[-                 3%                  ] 62 of 2000 complete in 27.0 sec
[-                 3%                  ] 64 of 2000 complete in 27.8 sec
[-                 3%                  ] 66 of 2000 complete in 28.7 sec
[-                 3%                  ] 68 of 2000 complete in 29.6 sec
[-                 3%                  ] 70 of 2000 complete in 30.5 sec
[-                 3%                  ] 72 of 2000 complete in 31.3 sec
[-                 3%                  ] 74 of 2000 complete in 32.2 sec
[-                 3%                  ] 76 of 2000 complete in 33.1 sec
[-                 3%                  ] 78 of 2000 complete in 33.9 sec
[-                 4%                  ] 80 of 2000 complete in 34.8 sec
[-                 4%                  ] 82 of 2000 complete in 35.6 sec
[-                 4%                  ] 84 of 2000 complete in 36.5 sec
[-                 4%                  ] 86 of 2000 complete in 37.3 sec
[-                 4%                  ] 88 of 2000 complete in 38.2 sec
[-                 4%                  ] 90 of 2000 complete in 39.0 sec
[-                 4%                  ] 92 of 2000 complete in 39.9 sec
[-                 4%                  ] 94 of 2000 complete in 40.8 sec
[-                 4%                  ] 96 of 2000 complete in 41.6 sec
[-                 4%                  ] 98 of 2000 complete in 42.4 sec
[-                 5%                  ] 100 of 2000 complete in 43.3 sec
[-                 5%                  ] 102 of 2000 complete in 44.1 sec
[-                 5%                  ] 104 of 2000 complete in 45.0 sec
[--                5%                  ] 106 of 2000 complete in 45.8 sec
[--                5%                  ] 108 of 2000 complete in 46.7 sec
[--                5%                  ] 110 of 2000 complete in 47.5 sec
[--                5%                  ] 112 of 2000 complete in 48.3 sec
[--                5%                  ] 114 of 2000 complete in 49.1 sec
[--                5%                  ] 116 of 2000 complete in 50.0 sec
[--                5%                  ] 118 of 2000 complete in 50.8 sec
[--                6%                  ] 120 of 2000 complete in 51.7 sec
[--                6%                  ] 122 of 2000 complete in 52.6 sec
[--                6%                  ] 124 of 2000 complete in 53.4 sec
[--                6%                  ] 126 of 2000 complete in 54.2 sec
[--                6%                  ] 128 of 2000 complete in 55.1 sec
[--                6%                  ] 130 of 2000 complete in 55.9 sec
[--                6%                  ] 132 of 2000 complete in 56.7 sec
[--                6%                  ] 134 of 2000 complete in 57.5 sec
[--                6%                  ] 136 of 2000 complete in 58.3 sec
[--                6%                  ] 138 of 2000 complete in 59.1 sec
[--                7%                  ] 140 of 2000 complete in 60.0 sec
[--                7%                  ] 142 of 2000 complete in 60.8 sec
[--                7%                  ] 144 of 2000 complete in 61.6 sec
[--                7%                  ] 146 of 2000 complete in 62.4 sec
[--                7%                  ] 148 of 2000 complete in 63.2 sec
[--                7%                  ] 150 of 2000 complete in 64.1 sec
[--                7%                  ] 152 of 2000 complete in 64.9 sec
[--                7%                  ] 154 of 2000 complete in 65.8 sec
[--                7%                  ] 156 of 2000 complete in 66.6 sec
[---               7%                  ] 158 of 2000 complete in 67.4 sec
[---               8%                  ] 160 of 2000 complete in 68.2 sec
[---               8%                  ] 162 of 2000 complete in 69.1 sec
[---               8%                  ] 164 of 2000 complete in 69.9 sec
[---               8%                  ] 166 of 2000 complete in 70.8 sec
[---               8%                  ] 168 of 2000 complete in 71.6 sec
[---               8%                  ] 170 of 2000 complete in 72.4 sec
[---               8%                  ] 172 of 2000 complete in 73.2 sec
[---               8%                  ] 174 of 2000 complete in 74.1 sec
[---               8%                  ] 176 of 2000 complete in 74.9 sec
[---               8%                  ] 178 of 2000 complete in 75.7 sec
[---               9%                  ] 180 of 2000 complete in 76.5 sec
[---               9%                  ] 182 of 2000 complete in 77.3 sec
[---               9%                  ] 184 of 2000 complete in 78.1 sec
[---               9%                  ] 186 of 2000 complete in 78.9 sec
[---               9%                  ] 188 of 2000 complete in 79.8 sec
[---               9%                  ] 190 of 2000 complete in 80.6 sec
[---               9%                  ] 192 of 2000 complete in 81.4 sec
[---               9%                  ] 194 of 2000 complete in 82.2 sec
[---               9%                  ] 196 of 2000 complete in 83.0 sec
[---               9%                  ] 198 of 2000 complete in 83.8 sec
[---              10%                  ] 200 of 2000 complete in 84.6 sec
[---              10%                  ] 202 of 2000 complete in 85.5 sec
[---              10%                  ] 204 of 2000 complete in 86.4 sec
[---              10%                  ] 206 of 2000 complete in 87.2 sec
[---              10%                  ] 208 of 2000 complete in 88.0 sec
[---              10%                  ] 210 of 2000 complete in 88.8 sec
[----             10%                  ] 212 of 2000 complete in 89.6 sec
[----             10%                  ] 214 of 2000 complete in 90.5 sec
[----             10%                  ] 216 of 2000 complete in 91.3 sec
[----             10%                  ] 218 of 2000 complete in 92.1 sec
[----             11%                  ] 220 of 2000 complete in 92.8 sec
[----             11%                  ] 222 of 2000 complete in 93.7 sec
[                  0%                  ] 3 of 2000 complete in 0.8 sec
[                  0%                  ] 4 of 2000 complete in 1.3 sec
[                  0%                  ] 6 of 2000 complete in 2.2 sec
[                  0%                  ] 8 of 2000 complete in 3.1 sec
[                  0%                  ] 10 of 2000 complete in 3.9 sec
[                  0%                  ] 12 of 2000 complete in 4.9 sec
[                  0%                  ] 14 of 2000 complete in 5.8 sec
[                  0%                  ] 16 of 2000 complete in 6.7 sec
[                  0%                  ] 18 of 2000 complete in 7.6 sec
[                  1%                  ] 20 of 2000 complete in 8.5 sec
[                  1%                  ] 22 of 2000 complete in 9.4 sec
[                  1%                  ] 24 of 2000 complete in 10.3 sec
[                  1%                  ] 26 of 2000 complete in 11.2 sec
[                  1%                  ] 28 of 2000 complete in 12.1 sec
[                  1%                  ] 30 of 2000 complete in 12.9 sec
[                  1%                  ] 32 of 2000 complete in 13.8 sec
[                  1%                  ] 34 of 2000 complete in 14.8 sec
[                  1%                  ] 36 of 2000 complete in 15.6 sec
[                  1%                  ] 38 of 2000 complete in 16.4 sec
[                  2%                  ] 40 of 2000 complete in 17.3 sec
[                  2%                  ] 42 of 2000 complete in 18.1 sec
[                  2%                  ] 44 of 2000 complete in 19.0 sec
[                  2%                  ] 46 of 2000 complete in 19.9 sec
[                  2%                  ] 48 of 2000 complete in 20.8 sec
[                  2%                  ] 50 of 2000 complete in 21.7 sec
[                  2%                  ] 52 of 2000 complete in 22.5 sec
[-                 2%                  ] 54 of 2000 complete in 23.4 sec
[-                 2%                  ] 56 of 2000 complete in 24.4 sec
[-                 2%                  ] 58 of 2000 complete in 25.3 sec
[-                 3%                  ] 60 of 2000 complete in 26.2 sec
[-                 3%                  ] 62 of 2000 complete in 27.0 sec
[-                 3%                  ] 64 of 2000 complete in 27.9 sec
[-                 3%                  ] 66 of 2000 complete in 28.8 sec
[-                 3%                  ] 68 of 2000 complete in 29.6 sec
[-                 3%                  ] 70 of 2000 complete in 30.5 sec
[-                 3%                  ] 72 of 2000 complete in 31.3 sec
[-                 3%                  ] 74 of 2000 complete in 32.2 sec
[-                 3%                  ] 76 of 2000 complete in 33.1 sec
[-                 3%                  ] 78 of 2000 complete in 34.0 sec
[-                 4%                  ] 80 of 2000 complete in 34.9 sec
[-                 4%                  ] 82 of 2000 complete in 35.8 sec
[-                 4%                  ] 84 of 2000 complete in 36.6 sec
[-                 4%                  ] 86 of 2000 complete in 37.5 sec
[-                 4%                  ] 88 of 2000 complete in 38.4 sec
[-                 4%                  ] 90 of 2000 complete in 39.3 sec
[-                 4%                  ] 92 of 2000 complete in 40.1 sec
[-                 4%                  ] 94 of 2000 complete in 40.9 sec
[-                 4%                  ] 96 of 2000 complete in 41.8 sec
[-                 4%                  ] 98 of 2000 complete in 42.6 sec
[-                 5%                  ] 100 of 2000 complete in 43.4 sec

[                  0%                  ] 3 of 2000 complete in 0.8 sec
[                  0%                  ] 4 of 2000 complete in 1.3 sec
[                  0%                  ] 6 of 2000 complete in 2.3 sec
[                  0%                  ] 8 of 2000 complete in 3.1 sec
[                  0%                  ] 10 of 2000 complete in 4.0 sec
[                  0%                  ] 12 of 2000 complete in 4.9 sec
[                  0%                  ] 14 of 2000 complete in 5.8 sec
[                  0%                  ] 16 of 2000 complete in 6.7 sec
[                  0%                  ] 18 of 2000 complete in 7.6 sec
[                  1%                  ] 20 of 2000 complete in 8.4 sec
[                  1%                  ] 22 of 2000 complete in 9.3 sec
[                  1%                  ] 24 of 2000 complete in 10.2 sec
[                  1%                  ] 26 of 2000 complete in 11.1 sec
[                  1%                  ] 28 of 2000 complete in 11.9 sec
[                  1%                  ] 30 of 2000 complete in 12.8 sec
[                  1%                  ] 32 of 2000 complete in 13.7 sec
[                  1%                  ] 34 of 2000 complete in 14.6 sec
[                  1%                  ] 36 of 2000 complete in 15.4 sec
[                  1%                  ] 38 of 2000 complete in 16.3 sec
[                  2%                  ] 40 of 2000 complete in 17.1 sec
[                  2%                  ] 42 of 2000 complete in 18.0 sec
[                  2%                  ] 44 of 2000 complete in 18.9 sec
[                  2%                  ] 46 of 2000 complete in 19.9 sec
[                  2%                  ] 48 of 2000 complete in 20.8 sec
[                  2%                  ] 50 of 2000 complete in 21.7 sec
[                  2%                  ] 52 of 2000 complete in 22.6 sec
[-                 2%                  ] 54 of 2000 complete in 23.5 sec
[-                 2%                  ] 56 of 2000 complete in 24.4 sec
[-                 2%                  ] 58 of 2000 complete in 25.2 sec
[-                 3%                  ] 60 of 2000 complete in 26.1 sec
[-                 3%                  ] 62 of 2000 complete in 27.0 sec
[-                 3%                  ] 64 of 2000 complete in 27.8 sec
[-                 3%                  ] 66 of 2000 complete in 28.7 sec
[-                 3%                  ] 68 of 2000 complete in 29.6 sec
[-                 3%                  ] 70 of 2000 complete in 30.5 sec
[-                 3%                  ] 72 of 2000 complete in 31.4 sec
[-                 3%                  ] 74 of 2000 complete in 32.2 sec
[-                 3%                  ] 76 of 2000 complete in 33.1 sec
[-                 3%                  ] 78 of 2000 complete in 34.0 sec
[-                 4%                  ] 80 of 2000 complete in 34.8 sec
[-                 4%                  ] 82 of 2000 complete in 35.7 sec
[-                 4%                  ] 84 of 2000 complete in 36.6 sec
[-                 4%                  ] 86 of 2000 complete in 37.4 sec
[-                 4%                  ] 88 of 2000 complete in 38.3 sec
[-                 4%                  ] 90 of 2000 complete in 39.2 sec
[-                 4%                  ] 92 of 2000 complete in 40.0 sec
[-                 4%                  ] 94 of 2000 complete in 40.9 sec
[-                 4%                  ] 96 of 2000 complete in 41.7 sec
[-                 4%                  ] 98 of 2000 complete in 42.5 sec
[-                 5%                  ] 100 of 2000 complete in 43.4 sec
[-                 5%                  ] 102 of 2000 complete in 44.3 sec
[-                 5%                  ] 104 of 2000 complete in 45.1 sec
[--                5%                  ] 106 of 2000 complete in 45.9 sec
[--                5%                  ] 108 of 2000 complete in 46.8 sec
[--                5%                  ] 110 of 2000 complete in 47.6 sec
[--                5%                  ] 112 of 2000 complete in 48.5 sec
[--                5%                  ] 114 of 2000 complete in 49.3 sec
[--                5%                  ] 116 of 2000 complete in 50.1 sec
[--                5%                  ] 118 of 2000 complete in 51.0 sec
[--                6%                  ] 120 of 2000 complete in 51.8 sec
[--                6%                  ] 122 of 2000 complete in 52.7 sec
[--                6%                  ] 124 of 2000 complete in 53.5 sec
[--                6%                  ] 126 of 2000 complete in 54.3 sec
[--                6%                  ] 128 of 2000 complete in 55.1 sec
[--                6%                  ] 130 of 2000 complete in 56.0 sec
[--                6%                  ] 132 of 2000 complete in 56.8 sec
[--                6%                  ] 134 of 2000 complete in 57.6 sec
[--                6%                  ] 136 of 2000 complete in 58.4 sec
[--                6%                  ] 138 of 2000 complete in 59.2 sec
[--                7%                  ] 140 of 2000 complete in 60.0 sec
[--                7%                  ] 142 of 2000 complete in 60.9 sec
[--                7%                  ] 144 of 2000 complete in 61.6 sec
[--                7%                  ] 146 of 2000 complete in 62.5 sec
[--                7%                  ] 148 of 2000 complete in 63.3 sec
[--                7%                  ] 150 of 2000 complete in 64.2 sec
[--                7%                  ] 152 of 2000 complete in 65.0 sec
[--                7%                  ] 154 of 2000 complete in 65.8 sec
[--                7%                  ] 156 of 2000 complete in 66.6 sec
[---               7%                  ] 158 of 2000 complete in 67.4 sec
[---               8%                  ] 160 of 2000 complete in 68.2 sec
[---               8%                  ] 162 of 2000 complete in 69.1 sec
[---               8%                  ] 164 of 2000 complete in 70.0 sec
[---               8%                  ] 166 of 2000 complete in 70.8 sec
[---               8%                  ] 168 of 2000 complete in 71.6 sec
[---               8%                  ] 170 of 2000 complete in 72.4 sec
[---               8%                  ] 172 of 2000 complete in 73.2 sec
[---               8%                  ] 174 of 2000 complete in 74.1 sec
[---               8%                  ] 176 of 2000 complete in 74.9 sec
[---               8%                  ] 178 of 2000 complete in 75.7 sec
[---               9%                  ] 180 of 2000 complete in 76.5 sec
[---               9%                  ] 182 of 2000 complete in 77.3 sec
[---               9%                  ] 184 of 2000 complete in 78.2 sec
[---               9%                  ] 186 of 2000 complete in 79.0 sec
[---               9%                  ] 188 of 2000 complete in 79.8 sec
[---               9%                  ] 190 of 2000 complete in 80.7 sec
[---               9%                  ] 192 of 2000 complete in 81.6 sec
[---               9%                  ] 194 of 2000 complete in 82.4 sec
[---               9%                  ] 196 of 2000 complete in 83.2 sec
[---               9%                  ] 198 of 2000 complete in 84.0 sec
[---              10%                  ] 200 of 2000 complete in 84.9 sec
[---              10%                  ] 202 of 2000 complete in 85.7 sec
[---              10%                  ] 204 of 2000 complete in 86.6 sec
[---              10%                  ] 206 of 2000 complete in 87.4 sec
[---              10%                  ] 208 of 2000 complete in 88.2 sec
[---              10%                  ] 210 of 2000 complete in 89.0 sec
[----             10%                  ] 212 of 2000 complete in 89.8 sec
[----             10%                  ] 214 of 2000 complete in 90.6 sec
[----             10%                  ] 216 of 2000 complete in 91.4 sec
[----             10%                  ] 218 of 2000 complete in 92.2 sec
[----             11%                  ] 220 of 2000 complete in 93.1 sec
[----             11%                  ] 222 of 2000 complete in 93.9 sec
[----             11%                  ] 224 of 2000 complete in 93.5 sec
[----             11%                  ] 226 of 2000 complete in 94.3 sec
[----             11%                  ] 228 of 2000 complete in 95.2 sec
[----             11%                  ] 230 of 2000 complete in 96.1 sec
[----             11%                  ] 232 of 2000 complete in 97.0 sec
[----             11%                  ] 234 of 2000 complete in 97.8 sec
[----             11%                  ] 236 of 2000 complete in 98.7 sec
[----             11%                  ] 238 of 2000 complete in 99.6 sec
[----             12%                  ] 240 of 2000 complete in 100.4 sec
[----             12%                  ] 242 of 2000 complete in 101.3 sec
[----             12%                  ] 244 of 2000 complete in 102.2 sec
[----             12%                  ] 246 of 2000 complete in 103.1 sec
[----             12%                  ] 248 of 2000 complete in 103.9 sec
[----             12%                  ] 250 of 2000 complete in 104.8 sec
[----             12%                  ] 252 of 2000 complete in 105.7 sec
[----             12%                  ] 254 of 2000 complete in 106.5 sec
[----             12%                  ] 256 of 2000 complete in 107.4 sec
[----             12%                  ] 258 of 2000 complete in 108.3 sec
[----             13%                  ] 260 of 2000 complete in 109.2 sec
[----             13%                  ] 262 of 2000 complete in 110.0 sec
[-----            13%                  ] 264 of 2000 complete in 110.9 sec
[-----            13%                  ] 266 of 2000 complete in 111.7 sec
[-----            13%                  ] 268 of 2000 complete in 112.6 sec
[-----            13%                  ] 270 of 2000 complete in 113.5 sec
[-----            13%                  ] 272 of 2000 complete in 114.3 sec
[-----            13%                  ] 274 of 2000 complete in 115.2 sec
[-----            13%                  ] 276 of 2000 complete in 116.1 sec
[-----            13%                  ] 278 of 2000 complete in 116.9 sec
[-----            14%                  ] 280 of 2000 complete in 117.8 sec
[-----            14%                  ] 282 of 2000 complete in 118.6 sec
[-----            14%                  ] 284 of 2000 complete in 119.5 sec
[-----            14%                  ] 286 of 2000 complete in 120.4 sec
[-----            14%                  ] 288 of 2000 complete in 121.2 sec
[-----            14%                  ] 290 of 2000 complete in 122.1 sec
[-----            14%                  ] 292 of 2000 complete in 123.0 sec
[-----            14%                  ] 294 of 2000 complete in 123.8 sec
[-----            14%                  ] 296 of 2000 complete in 124.7 sec
[-----            14%                  ] 298 of 2000 complete in 125.5 sec
[-----            15%                  ] 300 of 2000 complete in 126.4 sec
[-----            15%                  ] 302 of 2000 complete in 127.3 sec
[-----            15%                  ] 304 of 2000 complete in 128.1 sec
[-----            15%                  ] 306 of 2000 complete in 129.0 sec
[-----            15%                  ] 308 of 2000 complete in 129.8 sec
[-----            15%                  ] 310 of 2000 complete in 130.7 sec
[-----            15%                  ] 312 of 2000 complete in 131.5 sec
[-----            15%                  ] 314 of 2000 complete in 132.4 sec
[------           15%                  ] 316 of 2000 complete in 133.3 sec
[------           15%                  ] 318 of 2000 complete in 134.1 sec
[------           16%                  ] 320 of 2000 complete in 135.0 sec
[------           16%                  ] 322 of 2000 complete in 135.9 sec
[------           16%                  ] 324 of 2000 complete in 136.8 sec
[------           16%                  ] 326 of 2000 complete in 137.6 sec
[------           16%                  ] 328 of 2000 complete in 138.5 sec
[------           16%                  ] 330 of 2000 complete in 139.4 sec
[------           16%                  ] 332 of 2000 complete in 140.2 sec
[------           16%                  ] 334 of 2000 complete in 141.0 sec
[------           16%                  ] 336 of 2000 complete in 141.9 sec
[------           16%                  ] 338 of 2000 complete in 142.7 sec
[------           17%                  ] 340 of 2000 complete in 143.5 sec
[------           17%                  ] 342 of 2000 complete in 144.4 sec
[------           17%                  ] 344 of 2000 complete in 145.2 sec
[------           17%                  ] 346 of 2000 complete in 146.1 sec
[------           17%                  ] 348 of 2000 complete in 146.9 sec
[------           17%                  ] 350 of 2000 complete in 147.8 sec
[------           17%                  ] 352 of 2000 complete in 148.6 sec
[------           17%                  ] 354 of 2000 complete in 149.5 sec
[------           17%                  ] 356 of 2000 complete in 150.3 sec
[------           17%                  ] 358 of 2000 complete in 151.1 sec
[------           18%                  ] 360 of 2000 complete in 152.0 sec
[------           18%                  ] 362 of 2000 complete in 152.9 sec
[------           18%                  ] 364 of 2000 complete in 153.8 sec
[------           18%                  ] 366 of 2000 complete in 154.6 sec
[------           18%                  ] 368 of 2000 complete in 155.5 sec
[-------          18%                  ] 369 of 2000 complete in 156.1 sec
[-------          18%                  ] 370 of 2000 complete in 156.6 sec
[-------          18%                  ] 372 of 2000 complete in 157.5 sec
[-------          18%                  ] 374 of 2000 complete in 158.4 sec
[-------          18%                  ] 376 of 2000 complete in 159.4 sec
[-------          18%                  ] 378 of 2000 complete in 160.2 sec
[-------          19%                  ] 380 of 2000 complete in 161.1 sec
[-------          19%                  ] 382 of 2000 complete in 162.0 sec
[-------          19%                  ] 384 of 2000 complete in 162.8 sec
[-------          19%                  ] 386 of 2000 complete in 163.7 sec
[-------          19%                  ] 388 of 2000 complete in 164.6 sec
[-------          19%                  ] 390 of 2000 complete in 165.4 sec
[-------          19%                  ] 392 of 2000 complete in 166.3 sec
[-------          19%                  ] 394 of 2000 complete in 167.1 sec
[-------          19%                  ] 396 of 2000 complete in 168.0 sec
[-------          19%                  ] 398 of 2000 complete in 168.9 sec
[-------          20%                  ] 400 of 2000 complete in 169.8 sec
[-------          20%                  ] 402 of 2000 complete in 170.7 sec
[-------          20%                  ] 404 of 2000 complete in 171.5 sec
[-------          20%                  ] 406 of 2000 complete in 172.4 sec
[-------          20%                  ] 408 of 2000 complete in 173.4 sec
[-------          20%                  ] 410 of 2000 complete in 174.3 sec
[-------          20%                  ] 412 of 2000 complete in 175.2 sec
[-------          20%                  ] 414 of 2000 complete in 176.1 sec
[-------          20%                  ] 416 of 2000 complete in 176.9 sec
[-------          20%                  ] 418 of 2000 complete in 177.7 sec
[-------          21%                  ] 420 of 2000 complete in 178.6 sec
[--------         21%                  ] 422 of 2000 complete in 179.4 sec
[--------         21%                  ] 424 of 2000 complete in 180.2 sec
[--------         21%                  ] 426 of 2000 complete in 181.0 sec
[--------         21%                  ] 428 of 2000 complete in 181.9 sec
[--------         21%                  ] 430 of 2000 complete in 182.7 sec
[--------         21%                  ] 432 of 2000 complete in 183.5 sec
[--------         21%                  ] 434 of 2000 complete in 184.4 sec
[--------         21%                  ] 436 of 2000 complete in 185.2 sec
[--------         21%                  ] 438 of 2000 complete in 186.1 sec

[----             11%                  ] 224 of 2000 complete in 94.8 sec
[----             11%                  ] 226 of 2000 complete in 95.7 sec
[----             11%                  ] 228 of 2000 complete in 96.6 sec
[----             11%                  ] 230 of 2000 complete in 97.4 sec
[----             11%                  ] 232 of 2000 complete in 98.3 sec
[----             11%                  ] 234 of 2000 complete in 99.1 sec
[----             11%                  ] 236 of 2000 complete in 100.0 sec
[----             11%                  ] 238 of 2000 complete in 100.8 sec
[----             12%                  ] 240 of 2000 complete in 101.7 sec
[----             12%                  ] 242 of 2000 complete in 102.6 sec
[----             12%                  ] 244 of 2000 complete in 103.5 sec
[----             12%                  ] 246 of 2000 complete in 104.3 sec
[----             12%                  ] 248 of 2000 complete in 105.2 sec
[----             12%                  ] 250 of 2000 complete in 106.1 sec
[----             12%                  ] 252 of 2000 complete in 107.0 sec
[----             12%                  ] 254 of 2000 complete in 107.8 sec
[----             12%                  ] 256 of 2000 complete in 108.6 sec
[----             12%                  ] 258 of 2000 complete in 109.5 sec
[----             13%                  ] 260 of 2000 complete in 110.3 sec
[----             13%                  ] 262 of 2000 complete in 111.1 sec
[-----            13%                  ] 264 of 2000 complete in 112.0 sec
[-----            13%                  ] 266 of 2000 complete in 112.8 sec
[-----            13%                  ] 268 of 2000 complete in 113.6 sec
[-----            13%                  ] 270 of 2000 complete in 114.5 sec
[-----            13%                  ] 272 of 2000 complete in 115.3 sec
[-----            13%                  ] 274 of 2000 complete in 116.2 sec
[-----            13%                  ] 276 of 2000 complete in 117.1 sec
[-----            13%                  ] 278 of 2000 complete in 117.9 sec
[-----            14%                  ] 280 of 2000 complete in 118.8 sec
[-----            14%                  ] 282 of 2000 complete in 119.8 sec
[-----            14%                  ] 284 of 2000 complete in 120.6 sec
[-----            14%                  ] 286 of 2000 complete in 121.5 sec
[-----            14%                  ] 288 of 2000 complete in 122.3 sec
[-----            14%                  ] 290 of 2000 complete in 123.3 sec
[-----            14%                  ] 292 of 2000 complete in 124.2 sec
[-----            14%                  ] 294 of 2000 complete in 125.0 sec
[-----            14%                  ] 296 of 2000 complete in 125.9 sec
[-----            14%                  ] 298 of 2000 complete in 126.8 sec
[-----            15%                  ] 300 of 2000 complete in 127.6 sec
[-----            15%                  ] 302 of 2000 complete in 128.5 sec
[-----            15%                  ] 304 of 2000 complete in 129.3 sec
[-----            15%                  ] 306 of 2000 complete in 130.2 sec
[-----            15%                  ] 308 of 2000 complete in 131.1 sec
[-----            15%                  ] 310 of 2000 complete in 131.9 sec
[-----            15%                  ] 312 of 2000 complete in 132.8 sec
[-----            15%                  ] 314 of 2000 complete in 133.7 sec
[------           15%                  ] 316 of 2000 complete in 134.5 sec
[------           15%                  ] 318 of 2000 complete in 135.4 sec
[------           16%                  ] 320 of 2000 complete in 136.3 sec
[------           16%                  ] 322 of 2000 complete in 137.1 sec
[------           16%                  ] 324 of 2000 complete in 138.0 sec
[------           16%                  ] 326 of 2000 complete in 138.9 sec
[------           16%                  ] 328 of 2000 complete in 139.8 sec
[------           16%                  ] 330 of 2000 complete in 140.6 sec
[------           16%                  ] 332 of 2000 complete in 141.5 sec
[------           16%                  ] 334 of 2000 complete in 142.3 sec
[------           16%                  ] 336 of 2000 complete in 143.2 sec
[------           16%                  ] 338 of 2000 complete in 144.1 sec
[------           17%                  ] 340 of 2000 complete in 144.9 sec
[------           17%                  ] 342 of 2000 complete in 145.8 sec
[------           17%                  ] 344 of 2000 complete in 146.6 sec
[------           17%                  ] 346 of 2000 complete in 147.4 sec
[------           17%                  ] 348 of 2000 complete in 148.3 sec
[------           17%                  ] 350 of 2000 complete in 149.1 sec
[------           17%                  ] 352 of 2000 complete in 150.0 sec
[------           17%                  ] 354 of 2000 complete in 150.8 sec
[------           17%                  ] 356 of 2000 complete in 151.7 sec
[------           17%                  ] 358 of 2000 complete in 152.5 sec
[------           18%                  ] 360 of 2000 complete in 153.4 sec
[------           18%                  ] 362 of 2000 complete in 154.3 sec
[------           18%                  ] 364 of 2000 complete in 155.1 sec
[------           18%                  ] 365 of 2000 complete in 155.7 sec
[------           18%                  ] 366 of 2000 complete in 156.2 sec
[------           18%                  ] 367 of 2000 complete in 156.7 sec
[-------          18%                  ] 369 of 2000 complete in 157.6 sec
[-------          18%                  ] 371 of 2000 complete in 158.4 sec
[-------          18%                  ] 373 of 2000 complete in 159.4 sec
[-------          18%                  ] 375 of 2000 complete in 160.3 sec
[-------          18%                  ] 377 of 2000 complete in 161.2 sec
[-------          18%                  ] 379 of 2000 complete in 162.0 sec
[-------          19%                  ] 381 of 2000 complete in 162.9 sec
[-------          19%                  ] 383 of 2000 complete in 163.8 sec
[-------          19%                  ] 385 of 2000 complete in 164.6 sec
[-------          19%                  ] 387 of 2000 complete in 165.5 sec
[-------          19%                  ] 389 of 2000 complete in 166.4 sec
[-------          19%                  ] 391 of 2000 complete in 167.2 sec
[-------          19%                  ] 393 of 2000 complete in 168.1 sec
[-------          19%                  ] 395 of 2000 complete in 168.9 sec
[-------          19%                  ] 397 of 2000 complete in 169.9 sec
[-------          19%                  ] 399 of 2000 complete in 170.8 sec
[-------          20%                  ] 401 of 2000 complete in 171.7 sec
[-------          20%                  ] 403 of 2000 complete in 172.6 sec
[-------          20%                  ] 405 of 2000 complete in 173.5 sec
[-------          20%                  ] 407 of 2000 complete in 174.4 sec
[-------          20%                  ] 409 of 2000 complete in 175.3 sec
[-------          20%                  ] 411 of 2000 complete in 176.2 sec
[-------          20%                  ] 413 of 2000 complete in 177.0 sec
[-------          20%                  ] 415 of 2000 complete in 177.8 sec
[-------          20%                  ] 417 of 2000 complete in 178.7 sec
[-------          20%                  ] 419 of 2000 complete in 179.5 sec
[-------          21%                  ] 421 of 2000 complete in 180.4 sec
[--------         21%                  ] 423 of 2000 complete in 181.2 sec
[--------         21%                  ] 425 of 2000 complete in 182.1 sec
[--------         21%                  ] 427 of 2000 complete in 182.9 sec
[--------         21%                  ] 429 of 2000 complete in 183.8 sec
[--------         21%                  ] 431 of 2000 complete in 184.6 sec
[--------         21%                  ] 433 of 2000 complete in 185.5 sec
[--------         21%                  ] 435 of 2000 complete in 186.3 sec
[--------         21%                  ] 437 of 2000 complete in 187.2 sec
[----             11%                  ] 224 of 2000 complete in 94.8 sec
[----             11%                  ] 226 of 2000 complete in 95.7 sec
[----             11%                  ] 228 of 2000 complete in 96.6 sec
[----             11%                  ] 230 of 2000 complete in 97.5 sec
[----             11%                  ] 232 of 2000 complete in 98.3 sec
[----             11%                  ] 234 of 2000 complete in 99.2 sec
[----             11%                  ] 236 of 2000 complete in 100.1 sec
[----             11%                  ] 238 of 2000 complete in 101.0 sec
[----             12%                  ] 240 of 2000 complete in 101.9 sec
[----             12%                  ] 242 of 2000 complete in 102.8 sec
[----             12%                  ] 244 of 2000 complete in 103.7 sec
[----             12%                  ] 246 of 2000 complete in 104.5 sec
[----             12%                  ] 248 of 2000 complete in 105.4 sec
[----             12%                  ] 250 of 2000 complete in 106.2 sec
[----             12%                  ] 252 of 2000 complete in 107.1 sec
[----             12%                  ] 254 of 2000 complete in 108.0 sec
[----             12%                  ] 256 of 2000 complete in 108.8 sec
[----             12%                  ] 258 of 2000 complete in 109.7 sec
[----             13%                  ] 260 of 2000 complete in 110.5 sec
[----             13%                  ] 262 of 2000 complete in 111.4 sec
[-----            13%                  ] 264 of 2000 complete in 112.2 sec
[-----            13%                  ] 266 of 2000 complete in 113.1 sec
[-----            13%                  ] 268 of 2000 complete in 113.9 sec
[-----            13%                  ] 270 of 2000 complete in 114.8 sec
[-----            13%                  ] 272 of 2000 complete in 115.6 sec
[-----            13%                  ] 274 of 2000 complete in 116.5 sec
[-----            13%                  ] 276 of 2000 complete in 117.4 sec
[-----            13%                  ] 278 of 2000 complete in 118.2 sec
[-----            14%                  ] 280 of 2000 complete in 119.1 sec
[-----            14%                  ] 282 of 2000 complete in 119.9 sec
[-----            14%                  ] 284 of 2000 complete in 120.8 sec
[-----            14%                  ] 286 of 2000 complete in 121.7 sec
[-----            14%                  ] 288 of 2000 complete in 122.6 sec
[-----            14%                  ] 290 of 2000 complete in 123.5 sec
[-----            14%                  ] 292 of 2000 complete in 124.4 sec
[-----            14%                  ] 294 of 2000 complete in 125.3 sec
[-----            14%                  ] 296 of 2000 complete in 126.2 sec
[-----            14%                  ] 298 of 2000 complete in 127.1 sec
[-----            15%                  ] 300 of 2000 complete in 127.9 sec
[-----            15%                  ] 302 of 2000 complete in 128.8 sec
[-----            15%                  ] 304 of 2000 complete in 129.6 sec
[-----            15%                  ] 306 of 2000 complete in 130.5 sec
[-----            15%                  ] 308 of 2000 complete in 131.4 sec
[-----            15%                  ] 310 of 2000 complete in 132.2 sec
[-----            15%                  ] 312 of 2000 complete in 133.1 sec
[-----            15%                  ] 314 of 2000 complete in 134.0 sec
[------           15%                  ] 316 of 2000 complete in 134.9 sec
[------           15%                  ] 318 of 2000 complete in 135.8 sec
[------           16%                  ] 320 of 2000 complete in 136.6 sec
[------           16%                  ] 322 of 2000 complete in 137.5 sec
[------           16%                  ] 324 of 2000 complete in 138.3 sec
[------           16%                  ] 326 of 2000 complete in 139.2 sec
[------           16%                  ] 328 of 2000 complete in 140.0 sec
[------           16%                  ] 330 of 2000 complete in 140.9 sec
[------           16%                  ] 332 of 2000 complete in 141.8 sec
[------           16%                  ] 334 of 2000 complete in 142.6 sec
[------           16%                  ] 336 of 2000 complete in 143.5 sec
[------           16%                  ] 338 of 2000 complete in 144.3 sec
[------           17%                  ] 340 of 2000 complete in 145.2 sec
[------           17%                  ] 342 of 2000 complete in 146.0 sec
[------           17%                  ] 344 of 2000 complete in 146.8 sec
[------           17%                  ] 346 of 2000 complete in 147.7 sec
[------           17%                  ] 348 of 2000 complete in 148.6 sec
[------           17%                  ] 350 of 2000 complete in 149.4 sec
[------           17%                  ] 352 of 2000 complete in 150.3 sec
[------           17%                  ] 354 of 2000 complete in 151.1 sec
[------           17%                  ] 356 of 2000 complete in 151.9 sec
[------           17%                  ] 358 of 2000 complete in 152.8 sec
[------           18%                  ] 360 of 2000 complete in 153.7 sec
[------           18%                  ] 362 of 2000 complete in 154.6 sec
[------           18%                  ] 364 of 2000 complete in 155.4 sec
[------           18%                  ] 365 of 2000 complete in 156.0 sec
[------           18%                  ] 366 of 2000 complete in 156.5 sec
[------           18%                  ] 368 of 2000 complete in 157.4 sec
[-------          18%                  ] 370 of 2000 complete in 158.3 sec
[-------          18%                  ] 372 of 2000 complete in 159.3 sec
[-------          18%                  ] 374 of 2000 complete in 160.2 sec
[-------          18%                  ] 376 of 2000 complete in 161.1 sec
[-------          18%                  ] 378 of 2000 complete in 162.0 sec
[-------          19%                  ] 380 of 2000 complete in 162.8 sec
[-------          19%                  ] 382 of 2000 complete in 163.7 sec
[-------          19%                  ] 384 of 2000 complete in 164.5 sec
[-------          19%                  ] 386 of 2000 complete in 165.4 sec
[-------          19%                  ] 388 of 2000 complete in 166.3 sec
[-------          19%                  ] 390 of 2000 complete in 167.1 sec
[-------          19%                  ] 392 of 2000 complete in 167.9 sec
[-------          19%                  ] 394 of 2000 complete in 168.8 sec
[-------          19%                  ] 396 of 2000 complete in 169.7 sec
[-------          19%                  ] 398 of 2000 complete in 170.6 sec
[-------          20%                  ] 400 of 2000 complete in 171.5 sec
[-------          20%                  ] 402 of 2000 complete in 172.4 sec
[-------          20%                  ] 404 of 2000 complete in 173.3 sec
[-------          20%                  ] 406 of 2000 complete in 174.3 sec
[-------          20%                  ] 408 of 2000 complete in 175.2 sec
[-------          20%                  ] 410 of 2000 complete in 176.0 sec
[-------          20%                  ] 412 of 2000 complete in 176.9 sec
[-------          20%                  ] 414 of 2000 complete in 177.7 sec
[-------          20%                  ] 416 of 2000 complete in 178.5 sec
[-------          20%                  ] 418 of 2000 complete in 179.4 sec
[-------          21%                  ] 420 of 2000 complete in 180.3 sec
[--------         21%                  ] 422 of 2000 complete in 181.1 sec
[--------         21%                  ] 424 of 2000 complete in 182.0 sec
[--------         21%                  ] 426 of 2000 complete in 182.8 sec
[--------         21%                  ] 428 of 2000 complete in 183.6 sec
[--------         21%                  ] 430 of 2000 complete in 184.5 sec
[--------         21%                  ] 432 of 2000 complete in 185.4 sec
[--------         21%                  ] 434 of 2000 complete in 186.2 sec
[--------         21%                  ] 436 of 2000 complete in 187.1 sec
[--------         21%                  ] 438 of 2000 complete in 188.0 sec

[----             11%                  ] 224 of 2000 complete in 94.5 sec
[----             11%                  ] 226 of 2000 complete in 95.4 sec
[----             11%                  ] 228 of 2000 complete in 96.3 sec
[----             11%                  ] 230 of 2000 complete in 97.2 sec
[----             11%                  ] 232 of 2000 complete in 98.0 sec
[----             11%                  ] 234 of 2000 complete in 98.9 sec
[----             11%                  ] 236 of 2000 complete in 99.8 sec
[----             11%                  ] 238 of 2000 complete in 100.6 sec
[----             12%                  ] 240 of 2000 complete in 101.5 sec
[----             12%                  ] 242 of 2000 complete in 102.4 sec
[----             12%                  ] 244 of 2000 complete in 103.3 sec
[----             12%                  ] 246 of 2000 complete in 104.1 sec
[----             12%                  ] 248 of 2000 complete in 105.0 sec
[----             12%                  ] 250 of 2000 complete in 105.8 sec
[----             12%                  ] 252 of 2000 complete in 106.7 sec
[----             12%                  ] 254 of 2000 complete in 107.6 sec
[----             12%                  ] 256 of 2000 complete in 108.4 sec
[----             12%                  ] 258 of 2000 complete in 109.2 sec
[----             13%                  ] 260 of 2000 complete in 110.1 sec
[----             13%                  ] 262 of 2000 complete in 110.9 sec
[-----            13%                  ] 264 of 2000 complete in 111.8 sec
[-----            13%                  ] 266 of 2000 complete in 112.6 sec
[-----            13%                  ] 268 of 2000 complete in 113.5 sec
[-----            13%                  ] 270 of 2000 complete in 114.3 sec
[-----            13%                  ] 272 of 2000 complete in 115.2 sec
[-----            13%                  ] 274 of 2000 complete in 116.0 sec
[-----            13%                  ] 276 of 2000 complete in 116.9 sec
[-----            13%                  ] 278 of 2000 complete in 117.8 sec
[-----            14%                  ] 280 of 2000 complete in 118.7 sec
[-----            14%                  ] 282 of 2000 complete in 119.5 sec
[-----            14%                  ] 284 of 2000 complete in 120.4 sec
[-----            14%                  ] 286 of 2000 complete in 121.2 sec
[-----            14%                  ] 288 of 2000 complete in 122.1 sec
[-----            14%                  ] 290 of 2000 complete in 123.0 sec
[-----            14%                  ] 292 of 2000 complete in 123.9 sec
[-----            14%                  ] 294 of 2000 complete in 124.8 sec
[-----            14%                  ] 296 of 2000 complete in 125.6 sec
[-----            14%                  ] 298 of 2000 complete in 126.5 sec
[-----            15%                  ] 300 of 2000 complete in 127.3 sec
[-----            15%                  ] 302 of 2000 complete in 128.2 sec
[-----            15%                  ] 304 of 2000 complete in 129.0 sec
[-----            15%                  ] 306 of 2000 complete in 129.9 sec
[-----            15%                  ] 308 of 2000 complete in 130.8 sec
[-----            15%                  ] 310 of 2000 complete in 131.6 sec
[-----            15%                  ] 312 of 2000 complete in 132.5 sec
[-----            15%                  ] 314 of 2000 complete in 133.3 sec
[------           15%                  ] 316 of 2000 complete in 134.2 sec
[------           15%                  ] 318 of 2000 complete in 135.1 sec
[------           16%                  ] 320 of 2000 complete in 135.9 sec
[------           16%                  ] 322 of 2000 complete in 136.8 sec
[------           16%                  ] 324 of 2000 complete in 137.7 sec
[------           16%                  ] 326 of 2000 complete in 138.6 sec
[------           16%                  ] 328 of 2000 complete in 139.4 sec
[------           16%                  ] 330 of 2000 complete in 140.3 sec
[------           16%                  ] 332 of 2000 complete in 141.1 sec
[------           16%                  ] 334 of 2000 complete in 142.0 sec
[------           16%                  ] 336 of 2000 complete in 142.8 sec
[------           16%                  ] 338 of 2000 complete in 143.7 sec
[------           17%                  ] 340 of 2000 complete in 144.5 sec
[------           17%                  ] 342 of 2000 complete in 145.4 sec
[------           17%                  ] 344 of 2000 complete in 146.2 sec
[------           17%                  ] 346 of 2000 complete in 147.1 sec
[------           17%                  ] 348 of 2000 complete in 147.9 sec
[------           17%                  ] 350 of 2000 complete in 148.8 sec
[------           17%                  ] 352 of 2000 complete in 149.7 sec
[------           17%                  ] 354 of 2000 complete in 150.6 sec
[------           17%                  ] 356 of 2000 complete in 151.4 sec
[------           17%                  ] 358 of 2000 complete in 152.3 sec
[------           18%                  ] 360 of 2000 complete in 153.1 sec
[------           18%                  ] 362 of 2000 complete in 154.0 sec
[------           18%                  ] 364 of 2000 complete in 154.9 sec
[------           18%                  ] 366 of 2000 complete in 155.9 sec
[------           18%                  ] 367 of 2000 complete in 156.4 sec
[-------          18%                  ] 369 of 2000 complete in 157.3 sec
[-------          18%                  ] 371 of 2000 complete in 158.2 sec
[-------          18%                  ] 373 of 2000 complete in 159.2 sec
[-------          18%                  ] 375 of 2000 complete in 160.1 sec
[-------          18%                  ] 377 of 2000 complete in 161.0 sec
[-------          18%                  ] 379 of 2000 complete in 161.9 sec
[-------          19%                  ] 381 of 2000 complete in 162.7 sec
[-------          19%                  ] 383 of 2000 complete in 163.7 sec
[-------          19%                  ] 385 of 2000 complete in 164.5 sec
[-------          19%                  ] 387 of 2000 complete in 165.4 sec
[-------          19%                  ] 389 of 2000 complete in 166.3 sec
[-------          19%                  ] 391 of 2000 complete in 167.1 sec
[-------          19%                  ] 393 of 2000 complete in 167.9 sec
[-------          19%                  ] 395 of 2000 complete in 168.8 sec
[-------          19%                  ] 397 of 2000 complete in 169.7 sec
[-------          19%                  ] 399 of 2000 complete in 170.6 sec
[-------          20%                  ] 401 of 2000 complete in 171.5 sec
[-------          20%                  ] 403 of 2000 complete in 172.4 sec
[-------          20%                  ] 405 of 2000 complete in 173.4 sec
[-------          20%                  ] 407 of 2000 complete in 174.3 sec
[-------          20%                  ] 409 of 2000 complete in 175.2 sec
[-------          20%                  ] 411 of 2000 complete in 176.1 sec
[-------          20%                  ] 413 of 2000 complete in 177.0 sec
[-------          20%                  ] 415 of 2000 complete in 177.8 sec
[-------          20%                  ] 417 of 2000 complete in 178.7 sec
[-------          20%                  ] 419 of 2000 complete in 179.5 sec
[-------          21%                  ] 421 of 2000 complete in 180.4 sec
[--------         21%                  ] 423 of 2000 complete in 181.3 sec
[--------         21%                  ] 425 of 2000 complete in 182.1 sec
[--------         21%                  ] 427 of 2000 complete in 183.0 sec
[--------         21%                  ] 429 of 2000 complete in 183.8 sec
[--------         21%                  ] 431 of 2000 complete in 184.7 sec
[--------         21%                  ] 433 of 2000 complete in 185.5 sec
[--------         21%                  ] 435 of 2000 complete in 186.4 sec
[--------         21%                  ] 437 of 2000 complete in 187.2 sec
[--------         21%                  ] 439 of 2000 complete in 188.0 sec
[--------         22%                  ] 440 of 2000 complete in 186.9 sec
[--------         22%                  ] 442 of 2000 complete in 187.8 sec
[--------         22%                  ] 444 of 2000 complete in 188.6 sec
[--------         22%                  ] 446 of 2000 complete in 189.5 sec
[--------         22%                  ] 448 of 2000 complete in 190.3 sec
[--------         22%                  ] 450 of 2000 complete in 191.1 sec
[--------         22%                  ] 452 of 2000 complete in 192.0 sec
[--------         22%                  ] 454 of 2000 complete in 192.8 sec
[--------         22%                  ] 456 of 2000 complete in 193.7 sec
[--------         22%                  ] 458 of 2000 complete in 194.5 sec
[--------         23%                  ] 460 of 2000 complete in 195.4 sec
[--------         23%                  ] 462 of 2000 complete in 196.2 sec
[--------         23%                  ] 464 of 2000 complete in 197.1 sec
[--------         23%                  ] 466 of 2000 complete in 197.9 sec
[--------         23%                  ] 468 of 2000 complete in 198.8 sec
[--------         23%                  ] 470 of 2000 complete in 199.7 sec
[--------         23%                  ] 472 of 2000 complete in 200.5 sec
[---------        23%                  ] 474 of 2000 complete in 201.4 sec
[---------        23%                  ] 476 of 2000 complete in 202.2 sec
[---------        23%                  ] 478 of 2000 complete in 203.1 sec
[---------        24%                  ] 480 of 2000 complete in 203.9 sec
[---------        24%                  ] 482 of 2000 complete in 204.8 sec
[---------        24%                  ] 484 of 2000 complete in 205.6 sec
[---------        24%                  ] 486 of 2000 complete in 206.5 sec
[---------        24%                  ] 488 of 2000 complete in 207.3 sec
[---------        24%                  ] 490 of 2000 complete in 208.2 sec
[---------        24%                  ] 492 of 2000 complete in 209.0 sec
[---------        24%                  ] 494 of 2000 complete in 209.9 sec
[---------        24%                  ] 496 of 2000 complete in 210.8 sec
[---------        24%                  ] 498 of 2000 complete in 211.6 sec
[---------        25%                  ] 500 of 2000 complete in 212.5 sec
[---------        25%                  ] 502 of 2000 complete in 213.4 sec
[---------        25%                  ] 504 of 2000 complete in 214.2 sec
[---------        25%                  ] 506 of 2000 complete in 215.0 sec
[---------        25%                  ] 508 of 2000 complete in 215.9 sec
[---------        25%                  ] 510 of 2000 complete in 216.8 sec
[---------        25%                  ] 512 of 2000 complete in 217.6 sec
[---------        25%                  ] 514 of 2000 complete in 218.5 sec
[---------        25%                  ] 516 of 2000 complete in 219.4 sec
[---------        25%                  ] 518 of 2000 complete in 220.2 sec
[---------        26%                  ] 520 of 2000 complete in 221.1 sec
[---------        26%                  ] 522 of 2000 complete in 221.9 sec
[---------        26%                  ] 524 of 2000 complete in 222.8 sec
[---------        26%                  ] 526 of 2000 complete in 223.6 sec
[----------       26%                  ] 528 of 2000 complete in 224.5 sec
[----------       26%                  ] 530 of 2000 complete in 225.4 sec
[----------       26%                  ] 532 of 2000 complete in 226.2 sec
[----------       26%                  ] 534 of 2000 complete in 227.1 sec
[----------       26%                  ] 536 of 2000 complete in 227.9 sec
[----------       26%                  ] 538 of 2000 complete in 228.8 sec
[----------       26%                  ] 539 of 2000 complete in 229.3 sec
[----------       27%                  ] 541 of 2000 complete in 230.3 sec
[----------       27%                  ] 543 of 2000 complete in 231.1 sec
[----------       27%                  ] 545 of 2000 complete in 232.0 sec
[----------       27%                  ] 547 of 2000 complete in 232.9 sec
[----------       27%                  ] 548 of 2000 complete in 233.4 sec
[----------       27%                  ] 549 of 2000 complete in 233.9 sec
[----------       27%                  ] 551 of 2000 complete in 234.8 sec
[----------       27%                  ] 553 of 2000 complete in 235.6 sec
[----------       27%                  ] 555 of 2000 complete in 236.5 sec
[----------       27%                  ] 557 of 2000 complete in 237.4 sec
[----------       27%                  ] 559 of 2000 complete in 238.2 sec
[----------       28%                  ] 561 of 2000 complete in 239.1 sec
[----------       28%                  ] 563 of 2000 complete in 240.0 sec
[----------       28%                  ] 565 of 2000 complete in 240.8 sec
[----------       28%                  ] 567 of 2000 complete in 241.7 sec
[----------       28%                  ] 569 of 2000 complete in 242.6 sec
[----------       28%                  ] 571 of 2000 complete in 243.4 sec
[----------       28%                  ] 573 of 2000 complete in 244.2 sec
[----------       28%                  ] 575 of 2000 complete in 245.1 sec
[----------       28%                  ] 577 of 2000 complete in 245.9 sec
[-----------      28%                  ] 579 of 2000 complete in 246.8 sec
[-----------      29%                  ] 581 of 2000 complete in 247.6 sec
[-----------      29%                  ] 583 of 2000 complete in 248.4 sec
[-----------      29%                  ] 585 of 2000 complete in 249.2 sec
[-----------      29%                  ] 587 of 2000 complete in 250.1 sec
[-----------      29%                  ] 589 of 2000 complete in 250.9 sec
[-----------      29%                  ] 591 of 2000 complete in 251.7 sec
[-----------      29%                  ] 593 of 2000 complete in 252.6 sec
[-----------      29%                  ] 595 of 2000 complete in 253.4 sec
[-----------      29%                  ] 597 of 2000 complete in 254.2 sec
[-----------      29%                  ] 599 of 2000 complete in 255.2 sec
[-----------      30%                  ] 601 of 2000 complete in 256.1 sec
[-----------      30%                  ] 603 of 2000 complete in 257.0 sec
[-----------      30%                  ] 605 of 2000 complete in 258.0 sec
[-----------      30%                  ] 607 of 2000 complete in 258.8 sec
[-----------      30%                  ] 609 of 2000 complete in 259.7 sec
[-----------      30%                  ] 611 of 2000 complete in 260.6 sec
[-----------      30%                  ] 613 of 2000 complete in 261.5 sec
[-----------      30%                  ] 615 of 2000 complete in 262.3 sec
[-----------      30%                  ] 617 of 2000 complete in 263.2 sec
[-----------      30%                  ] 619 of 2000 complete in 264.0 sec
[-----------      31%                  ] 621 of 2000 complete in 264.9 sec
[-----------      31%                  ] 623 of 2000 complete in 265.8 sec
[-----------      31%                  ] 625 of 2000 complete in 266.6 sec
[-----------      31%                  ] 627 of 2000 complete in 267.5 sec
[-----------      31%                  ] 629 of 2000 complete in 268.4 sec
[-----------      31%                  ] 631 of 2000 complete in 269.3 sec
[------------     31%                  ] 633 of 2000 complete in 270.2 sec
[------------     31%                  ] 635 of 2000 complete in 271.1 sec
[------------     31%                  ] 637 of 2000 complete in 272.0 sec
[------------     31%                  ] 639 of 2000 complete in 272.9 sec
[------------     32%                  ] 641 of 2000 complete in 273.7 sec
[------------     32%                  ] 643 of 2000 complete in 274.6 sec
[------------     32%                  ] 645 of 2000 complete in 275.5 sec
[------------     32%                  ] 647 of 2000 complete in 276.3 sec
[------------     32%                  ] 649 of 2000 complete in 277.3 sec
[------------     32%                  ] 651 of 2000 complete in 278.3 sec
[------------     32%                  ] 653 of 2000 complete in 279.2 sec

[--------         21%                  ] 439 of 2000 complete in 188.1 sec
[--------         22%                  ] 441 of 2000 complete in 188.9 sec
[--------         22%                  ] 443 of 2000 complete in 189.8 sec
[--------         22%                  ] 445 of 2000 complete in 190.6 sec
[--------         22%                  ] 447 of 2000 complete in 191.5 sec
[--------         22%                  ] 449 of 2000 complete in 192.3 sec
[--------         22%                  ] 451 of 2000 complete in 193.2 sec
[--------         22%                  ] 453 of 2000 complete in 194.0 sec
[--------         22%                  ] 455 of 2000 complete in 194.9 sec
[--------         22%                  ] 457 of 2000 complete in 195.8 sec
[--------         22%                  ] 459 of 2000 complete in 196.6 sec
[--------         23%                  ] 461 of 2000 complete in 197.4 sec
[--------         23%                  ] 463 of 2000 complete in 198.2 sec
[--------         23%                  ] 465 of 2000 complete in 199.1 sec
[--------         23%                  ] 467 of 2000 complete in 200.0 sec
[--------         23%                  ] 469 of 2000 complete in 200.9 sec
[--------         23%                  ] 471 of 2000 complete in 201.7 sec
[--------         23%                  ] 473 of 2000 complete in 202.6 sec
[---------        23%                  ] 475 of 2000 complete in 203.4 sec
[---------        23%                  ] 477 of 2000 complete in 204.3 sec
[---------        23%                  ] 479 of 2000 complete in 205.1 sec
[---------        24%                  ] 481 of 2000 complete in 206.0 sec
[---------        24%                  ] 483 of 2000 complete in 206.8 sec
[---------        24%                  ] 485 of 2000 complete in 207.7 sec
[---------        24%                  ] 487 of 2000 complete in 208.5 sec
[---------        24%                  ] 489 of 2000 complete in 209.4 sec
[---------        24%                  ] 491 of 2000 complete in 210.2 sec
[---------        24%                  ] 493 of 2000 complete in 211.1 sec
[---------        24%                  ] 495 of 2000 complete in 212.0 sec
[---------        24%                  ] 497 of 2000 complete in 212.9 sec
[---------        24%                  ] 499 of 2000 complete in 213.7 sec
[---------        25%                  ] 501 of 2000 complete in 214.6 sec
[---------        25%                  ] 503 of 2000 complete in 215.5 sec
[---------        25%                  ] 505 of 2000 complete in 216.3 sec
[---------        25%                  ] 507 of 2000 complete in 217.2 sec
[---------        25%                  ] 509 of 2000 complete in 218.0 sec
[---------        25%                  ] 511 of 2000 complete in 218.9 sec
[---------        25%                  ] 513 of 2000 complete in 219.8 sec
[---------        25%                  ] 515 of 2000 complete in 220.7 sec
[---------        25%                  ] 517 of 2000 complete in 221.6 sec
[---------        25%                  ] 519 of 2000 complete in 222.4 sec
[---------        26%                  ] 521 of 2000 complete in 223.3 sec
[---------        26%                  ] 523 of 2000 complete in 224.2 sec
[---------        26%                  ] 525 of 2000 complete in 225.1 sec
[----------       26%                  ] 527 of 2000 complete in 226.0 sec
[----------       26%                  ] 529 of 2000 complete in 226.9 sec
[----------       26%                  ] 531 of 2000 complete in 227.7 sec
[----------       26%                  ] 533 of 2000 complete in 228.6 sec
[----------       26%                  ] 535 of 2000 complete in 229.6 sec
[----------       26%                  ] 537 of 2000 complete in 230.5 sec
[----------       26%                  ] 539 of 2000 complete in 231.3 sec
[----------       27%                  ] 541 of 2000 complete in 232.2 sec
[----------       27%                  ] 543 of 2000 complete in 233.1 sec
[----------       27%                  ] 544 of 2000 complete in 233.6 sec
[----------       27%                  ] 546 of 2000 complete in 234.5 sec
[----------       27%                  ] 548 of 2000 complete in 235.4 sec
[----------       27%                  ] 550 of 2000 complete in 236.3 sec
[----------       27%                  ] 552 of 2000 complete in 237.2 sec
[----------       27%                  ] 554 of 2000 complete in 238.1 sec
[----------       27%                  ] 556 of 2000 complete in 238.9 sec
[----------       27%                  ] 558 of 2000 complete in 239.8 sec
[----------       28%                  ] 560 of 2000 complete in 240.7 sec
[----------       28%                  ] 562 of 2000 complete in 241.6 sec
[----------       28%                  ] 564 of 2000 complete in 242.5 sec
[----------       28%                  ] 566 of 2000 complete in 243.4 sec
[----------       28%                  ] 568 of 2000 complete in 244.3 sec
[----------       28%                  ] 570 of 2000 complete in 245.1 sec
[----------       28%                  ] 572 of 2000 complete in 246.0 sec
[----------       28%                  ] 574 of 2000 complete in 246.9 sec
[----------       28%                  ] 576 of 2000 complete in 247.7 sec
[----------       28%                  ] 578 of 2000 complete in 248.6 sec
[-----------      29%                  ] 580 of 2000 complete in 249.4 sec
[-----------      29%                  ] 582 of 2000 complete in 250.3 sec
[-----------      29%                  ] 584 of 2000 complete in 251.1 sec
[-----------      29%                  ] 586 of 2000 complete in 252.0 sec
[-----------      29%                  ] 588 of 2000 complete in 252.8 sec
[-----------      29%                  ] 590 of 2000 complete in 253.7 sec
[-----------      29%                  ] 592 of 2000 complete in 254.5 sec
[-----------      29%                  ] 594 of 2000 complete in 255.5 sec
[-----------      29%                  ] 596 of 2000 complete in 256.4 sec
[-----------      29%                  ] 598 of 2000 complete in 257.3 sec
[-----------      30%                  ] 600 of 2000 complete in 258.2 sec
[-----------      30%                  ] 602 of 2000 complete in 259.1 sec
[-----------      30%                  ] 604 of 2000 complete in 259.9 sec
[-----------      30%                  ] 606 of 2000 complete in 260.8 sec
[-----------      30%                  ] 608 of 2000 complete in 261.6 sec
[-----------      30%                  ] 610 of 2000 complete in 262.5 sec
[-----------      30%                  ] 612 of 2000 complete in 263.5 sec
[-----------      30%                  ] 614 of 2000 complete in 264.4 sec
[-----------      30%                  ] 616 of 2000 complete in 265.3 sec
[-----------      30%                  ] 618 of 2000 complete in 266.2 sec
[-----------      31%                  ] 620 of 2000 complete in 267.1 sec
[-----------      31%                  ] 622 of 2000 complete in 268.0 sec
[-----------      31%                  ] 624 of 2000 complete in 268.9 sec
[-----------      31%                  ] 626 of 2000 complete in 269.7 sec
[-----------      31%                  ] 628 of 2000 complete in 270.6 sec
[-----------      31%                  ] 630 of 2000 complete in 271.6 sec
[------------     31%                  ] 632 of 2000 complete in 272.5 sec
[------------     31%                  ] 634 of 2000 complete in 273.4 sec
[------------     31%                  ] 636 of 2000 complete in 274.2 sec
[------------     31%                  ] 638 of 2000 complete in 275.1 sec
[------------     32%                  ] 640 of 2000 complete in 276.0 sec
[------------     32%                  ] 642 of 2000 complete in 276.9 sec
[------------     32%                  ] 644 of 2000 complete in 277.9 sec
[------------     32%                  ] 646 of 2000 complete in 278.8 sec
[------------     32%                  ] 648 of 2000 complete in 279.6 sec
[------------     32%                  ] 650 of 2000 complete in 280.5 sec
[------------     32%                  ] 651 of 2000 complete in 281.1 sec
[------------     32%                  ] 653 of 2000 complete in 282.0 sec
[--------         22%                  ] 440 of 2000 complete in 188.8 sec
[--------         22%                  ] 442 of 2000 complete in 189.7 sec
[--------         22%                  ] 444 of 2000 complete in 190.5 sec
[--------         22%                  ] 446 of 2000 complete in 191.4 sec
[--------         22%                  ] 448 of 2000 complete in 192.3 sec
[--------         22%                  ] 450 of 2000 complete in 193.2 sec
[--------         22%                  ] 452 of 2000 complete in 194.0 sec
[--------         22%                  ] 454 of 2000 complete in 194.9 sec
[--------         22%                  ] 456 of 2000 complete in 195.7 sec
[--------         22%                  ] 458 of 2000 complete in 196.6 sec
[--------         23%                  ] 460 of 2000 complete in 197.4 sec
[--------         23%                  ] 462 of 2000 complete in 198.3 sec
[--------         23%                  ] 464 of 2000 complete in 199.1 sec
[--------         23%                  ] 466 of 2000 complete in 200.0 sec
[--------         23%                  ] 468 of 2000 complete in 200.9 sec
[--------         23%                  ] 470 of 2000 complete in 201.7 sec
[--------         23%                  ] 472 of 2000 complete in 202.6 sec
[---------        23%                  ] 474 of 2000 complete in 203.4 sec
[---------        23%                  ] 476 of 2000 complete in 204.3 sec
[---------        23%                  ] 478 of 2000 complete in 205.1 sec
[---------        24%                  ] 480 of 2000 complete in 206.0 sec
[---------        24%                  ] 482 of 2000 complete in 206.9 sec
[---------        24%                  ] 484 of 2000 complete in 207.7 sec
[---------        24%                  ] 486 of 2000 complete in 208.6 sec
[---------        24%                  ] 488 of 2000 complete in 209.4 sec
[---------        24%                  ] 490 of 2000 complete in 210.3 sec
[---------        24%                  ] 492 of 2000 complete in 211.1 sec
[---------        24%                  ] 494 of 2000 complete in 212.0 sec
[---------        24%                  ] 496 of 2000 complete in 212.9 sec
[---------        24%                  ] 498 of 2000 complete in 213.7 sec
[---------        25%                  ] 500 of 2000 complete in 214.5 sec
[---------        25%                  ] 502 of 2000 complete in 215.4 sec
[---------        25%                  ] 504 of 2000 complete in 216.3 sec
[---------        25%                  ] 506 of 2000 complete in 217.2 sec
[---------        25%                  ] 508 of 2000 complete in 218.0 sec
[---------        25%                  ] 510 of 2000 complete in 218.9 sec
[---------        25%                  ] 512 of 2000 complete in 219.8 sec
[---------        25%                  ] 514 of 2000 complete in 220.7 sec
[---------        25%                  ] 516 of 2000 complete in 221.5 sec
[---------        25%                  ] 518 of 2000 complete in 222.3 sec
[---------        26%                  ] 520 of 2000 complete in 223.3 sec
[---------        26%                  ] 522 of 2000 complete in 224.2 sec
[---------        26%                  ] 524 of 2000 complete in 225.0 sec
[---------        26%                  ] 526 of 2000 complete in 225.9 sec
[----------       26%                  ] 528 of 2000 complete in 226.7 sec
[----------       26%                  ] 530 of 2000 complete in 227.6 sec
[----------       26%                  ] 532 of 2000 complete in 228.4 sec
[----------       26%                  ] 534 of 2000 complete in 229.4 sec
[----------       26%                  ] 536 of 2000 complete in 230.4 sec
[----------       26%                  ] 538 of 2000 complete in 231.2 sec
[----------       27%                  ] 540 of 2000 complete in 232.1 sec
[----------       27%                  ] 542 of 2000 complete in 232.9 sec
[----------       27%                  ] 544 of 2000 complete in 233.9 sec
[----------       27%                  ] 546 of 2000 complete in 234.8 sec
[----------       27%                  ] 548 of 2000 complete in 235.7 sec
[----------       27%                  ] 550 of 2000 complete in 236.5 sec
[----------       27%                  ] 552 of 2000 complete in 237.4 sec
[----------       27%                  ] 554 of 2000 complete in 238.3 sec
[----------       27%                  ] 556 of 2000 complete in 239.1 sec
[----------       27%                  ] 558 of 2000 complete in 240.0 sec
[----------       28%                  ] 560 of 2000 complete in 240.8 sec
[----------       28%                  ] 562 of 2000 complete in 241.7 sec
[----------       28%                  ] 564 of 2000 complete in 242.6 sec
[----------       28%                  ] 566 of 2000 complete in 243.4 sec
[----------       28%                  ] 568 of 2000 complete in 244.3 sec
[----------       28%                  ] 570 of 2000 complete in 245.2 sec
[----------       28%                  ] 572 of 2000 complete in 246.0 sec
[----------       28%                  ] 574 of 2000 complete in 246.9 sec
[----------       28%                  ] 576 of 2000 complete in 247.7 sec
[----------       28%                  ] 578 of 2000 complete in 248.5 sec
[-----------      29%                  ] 580 of 2000 complete in 249.4 sec
[-----------      29%                  ] 582 of 2000 complete in 250.2 sec
[-----------      29%                  ] 584 of 2000 complete in 251.1 sec
[-----------      29%                  ] 586 of 2000 complete in 251.9 sec
[-----------      29%                  ] 588 of 2000 complete in 252.8 sec
[-----------      29%                  ] 590 of 2000 complete in 253.7 sec
[-----------      29%                  ] 592 of 2000 complete in 254.5 sec
[-----------      29%                  ] 594 of 2000 complete in 255.5 sec
[-----------      29%                  ] 596 of 2000 complete in 256.4 sec
[-----------      29%                  ] 598 of 2000 complete in 257.3 sec
[-----------      30%                  ] 600 of 2000 complete in 258.3 sec
[-----------      30%                  ] 602 of 2000 complete in 259.1 sec
[-----------      30%                  ] 604 of 2000 complete in 260.0 sec
[-----------      30%                  ] 606 of 2000 complete in 260.9 sec
[-----------      30%                  ] 608 of 2000 complete in 261.7 sec
[-----------      30%                  ] 610 of 2000 complete in 262.5 sec
[-----------      30%                  ] 612 of 2000 complete in 263.4 sec
[-----------      30%                  ] 614 of 2000 complete in 264.3 sec
[-----------      30%                  ] 616 of 2000 complete in 265.2 sec
[-----------      30%                  ] 618 of 2000 complete in 266.1 sec
[-----------      31%                  ] 620 of 2000 complete in 267.0 sec
[-----------      31%                  ] 622 of 2000 complete in 267.9 sec
[-----------      31%                  ] 624 of 2000 complete in 268.8 sec
[-----------      31%                  ] 626 of 2000 complete in 269.7 sec
[-----------      31%                  ] 628 of 2000 complete in 270.5 sec
[-----------      31%                  ] 630 of 2000 complete in 271.5 sec
[------------     31%                  ] 632 of 2000 complete in 272.4 sec
[------------     31%                  ] 634 of 2000 complete in 273.2 sec
[------------     31%                  ] 636 of 2000 complete in 274.1 sec
[------------     31%                  ] 638 of 2000 complete in 275.0 sec
[------------     32%                  ] 640 of 2000 complete in 275.9 sec
[------------     32%                  ] 642 of 2000 complete in 276.7 sec
[------------     32%                  ] 644 of 2000 complete in 277.7 sec
[------------     32%                  ] 645 of 2000 complete in 278.2 sec
[------------     32%                  ] 647 of 2000 complete in 279.1 sec
[------------     32%                  ] 649 of 2000 complete in 279.9 sec
[------------     32%                  ] 651 of 2000 complete in 280.9 sec
[------------     32%                  ] 652 of 2000 complete in 281.4 sec
[------------     32%                  ] 654 of 2000 complete in 282.2 sec

[--------         22%                  ] 441 of 2000 complete in 188.9 sec
[--------         22%                  ] 443 of 2000 complete in 189.8 sec
[--------         22%                  ] 445 of 2000 complete in 190.6 sec
[--------         22%                  ] 447 of 2000 complete in 191.4 sec
[--------         22%                  ] 449 of 2000 complete in 192.3 sec
[--------         22%                  ] 451 of 2000 complete in 193.2 sec
[--------         22%                  ] 453 of 2000 complete in 194.0 sec
[--------         22%                  ] 455 of 2000 complete in 194.9 sec
[--------         22%                  ] 457 of 2000 complete in 195.7 sec
[--------         22%                  ] 459 of 2000 complete in 196.6 sec
[--------         23%                  ] 461 of 2000 complete in 197.5 sec
[--------         23%                  ] 463 of 2000 complete in 198.3 sec
[--------         23%                  ] 465 of 2000 complete in 199.2 sec
[--------         23%                  ] 467 of 2000 complete in 200.1 sec
[--------         23%                  ] 469 of 2000 complete in 201.0 sec
[--------         23%                  ] 471 of 2000 complete in 201.8 sec
[--------         23%                  ] 473 of 2000 complete in 202.7 sec
[---------        23%                  ] 475 of 2000 complete in 203.6 sec
[---------        23%                  ] 477 of 2000 complete in 204.4 sec
[---------        23%                  ] 479 of 2000 complete in 205.3 sec
[---------        24%                  ] 481 of 2000 complete in 206.1 sec
[---------        24%                  ] 483 of 2000 complete in 207.0 sec
[---------        24%                  ] 485 of 2000 complete in 207.8 sec
[---------        24%                  ] 487 of 2000 complete in 208.7 sec
[---------        24%                  ] 489 of 2000 complete in 209.5 sec
[---------        24%                  ] 491 of 2000 complete in 210.4 sec
[---------        24%                  ] 493 of 2000 complete in 211.2 sec
[---------        24%                  ] 495 of 2000 complete in 212.1 sec
[---------        24%                  ] 497 of 2000 complete in 212.9 sec
[---------        24%                  ] 499 of 2000 complete in 213.8 sec
[---------        25%                  ] 501 of 2000 complete in 214.6 sec
[---------        25%                  ] 503 of 2000 complete in 215.5 sec
[---------        25%                  ] 505 of 2000 complete in 216.4 sec
[---------        25%                  ] 507 of 2000 complete in 217.2 sec
[---------        25%                  ] 509 of 2000 complete in 218.1 sec
[---------        25%                  ] 511 of 2000 complete in 219.0 sec
[---------        25%                  ] 513 of 2000 complete in 219.9 sec
[---------        25%                  ] 515 of 2000 complete in 220.8 sec
[---------        25%                  ] 517 of 2000 complete in 221.7 sec
[---------        25%                  ] 519 of 2000 complete in 222.6 sec
[---------        26%                  ] 521 of 2000 complete in 223.4 sec
[---------        26%                  ] 523 of 2000 complete in 224.3 sec
[---------        26%                  ] 525 of 2000 complete in 225.2 sec
[----------       26%                  ] 527 of 2000 complete in 226.0 sec
[----------       26%                  ] 529 of 2000 complete in 226.9 sec
[----------       26%                  ] 531 of 2000 complete in 227.8 sec
[----------       26%                  ] 533 of 2000 complete in 228.6 sec
[----------       26%                  ] 535 of 2000 complete in 229.7 sec
[----------       26%                  ] 537 of 2000 complete in 230.6 sec
[----------       26%                  ] 539 of 2000 complete in 231.4 sec
[----------       27%                  ] 541 of 2000 complete in 232.3 sec
[----------       27%                  ] 543 of 2000 complete in 233.3 sec
[----------       27%                  ] 544 of 2000 complete in 233.8 sec
[----------       27%                  ] 546 of 2000 complete in 234.7 sec
[----------       27%                  ] 548 of 2000 complete in 235.5 sec
[----------       27%                  ] 550 of 2000 complete in 236.4 sec
[----------       27%                  ] 552 of 2000 complete in 237.3 sec
[----------       27%                  ] 554 of 2000 complete in 238.1 sec
[----------       27%                  ] 556 of 2000 complete in 239.0 sec
[----------       27%                  ] 558 of 2000 complete in 239.9 sec
[----------       28%                  ] 560 of 2000 complete in 240.8 sec
[----------       28%                  ] 562 of 2000 complete in 241.6 sec
[----------       28%                  ] 564 of 2000 complete in 242.5 sec
[----------       28%                  ] 566 of 2000 complete in 243.3 sec
[----------       28%                  ] 568 of 2000 complete in 244.2 sec
[----------       28%                  ] 570 of 2000 complete in 245.1 sec
[----------       28%                  ] 572 of 2000 complete in 245.9 sec
[----------       28%                  ] 574 of 2000 complete in 246.8 sec
[----------       28%                  ] 576 of 2000 complete in 247.6 sec
[----------       28%                  ] 578 of 2000 complete in 248.5 sec
[-----------      29%                  ] 580 of 2000 complete in 249.3 sec
[-----------      29%                  ] 582 of 2000 complete in 250.2 sec
[-----------      29%                  ] 584 of 2000 complete in 251.0 sec
[-----------      29%                  ] 586 of 2000 complete in 251.9 sec
[-----------      29%                  ] 588 of 2000 complete in 252.7 sec
[-----------      29%                  ] 590 of 2000 complete in 253.6 sec
[-----------      29%                  ] 592 of 2000 complete in 254.5 sec
[-----------      29%                  ] 594 of 2000 complete in 255.5 sec
[-----------      29%                  ] 596 of 2000 complete in 256.4 sec
[-----------      29%                  ] 598 of 2000 complete in 257.3 sec
[-----------      30%                  ] 600 of 2000 complete in 258.2 sec
[-----------      30%                  ] 602 of 2000 complete in 259.1 sec
[-----------      30%                  ] 604 of 2000 complete in 259.9 sec
[-----------      30%                  ] 606 of 2000 complete in 260.8 sec
[-----------      30%                  ] 608 of 2000 complete in 261.7 sec
[-----------      30%                  ] 610 of 2000 complete in 262.5 sec
[-----------      30%                  ] 612 of 2000 complete in 263.4 sec
[-----------      30%                  ] 614 of 2000 complete in 264.3 sec
[-----------      30%                  ] 616 of 2000 complete in 265.2 sec
[-----------      30%                  ] 618 of 2000 complete in 266.1 sec
[-----------      31%                  ] 620 of 2000 complete in 266.9 sec
[-----------      31%                  ] 622 of 2000 complete in 267.8 sec
[-----------      31%                  ] 624 of 2000 complete in 268.8 sec
[-----------      31%                  ] 626 of 2000 complete in 269.6 sec
[-----------      31%                  ] 628 of 2000 complete in 270.5 sec
[-----------      31%                  ] 630 of 2000 complete in 271.4 sec
[------------     31%                  ] 632 of 2000 complete in 272.3 sec
[------------     31%                  ] 633 of 2000 complete in 272.8 sec
[------------     31%                  ] 635 of 2000 complete in 273.7 sec
[------------     31%                  ] 637 of 2000 complete in 274.6 sec
[------------     31%                  ] 639 of 2000 complete in 275.5 sec
[------------     32%                  ] 641 of 2000 complete in 276.3 sec
[------------     32%                  ] 643 of 2000 complete in 277.2 sec
[------------     32%                  ] 645 of 2000 complete in 278.2 sec
[------------     32%                  ] 647 of 2000 complete in 279.0 sec
[------------     32%                  ] 649 of 2000 complete in 279.9 sec
[------------     32%                  ] 651 of 2000 complete in 280.9 sec
[------------     32%                  ] 653 of 2000 complete in 281.8 sec
[------------     32%                  ] 655 of 2000 complete in 282.7 sec
[------------     32%                  ] 655 of 2000 complete in 280.1 sec
[------------     32%                  ] 657 of 2000 complete in 281.0 sec
[------------     32%                  ] 659 of 2000 complete in 281.9 sec
[------------     33%                  ] 661 of 2000 complete in 282.8 sec
[------------     33%                  ] 663 of 2000 complete in 283.7 sec
[------------     33%                  ] 665 of 2000 complete in 284.5 sec
[------------     33%                  ] 667 of 2000 complete in 285.4 sec
[------------     33%                  ] 669 of 2000 complete in 286.2 sec
[------------     33%                  ] 671 of 2000 complete in 287.1 sec
[------------     33%                  ] 673 of 2000 complete in 288.0 sec
[------------     33%                  ] 675 of 2000 complete in 289.0 sec
[------------     33%                  ] 677 of 2000 complete in 289.8 sec
[------------     33%                  ] 679 of 2000 complete in 290.7 sec
[------------     34%                  ] 681 of 2000 complete in 291.6 sec
[------------     34%                  ] 683 of 2000 complete in 292.5 sec
[------------     34%                  ] 684 of 2000 complete in 293.0 sec
[-------------    34%                  ] 686 of 2000 complete in 293.9 sec
[-------------    34%                  ] 688 of 2000 complete in 294.7 sec
[-------------    34%                  ] 690 of 2000 complete in 295.6 sec
[-------------    34%                  ] 692 of 2000 complete in 296.4 sec
[-------------    34%                  ] 694 of 2000 complete in 297.3 sec
[-------------    34%                  ] 696 of 2000 complete in 298.1 sec
[-------------    34%                  ] 698 of 2000 complete in 299.0 sec
[-------------    35%                  ] 700 of 2000 complete in 299.9 sec
[-------------    35%                  ] 702 of 2000 complete in 300.8 sec
[-------------    35%                  ] 704 of 2000 complete in 301.6 sec
[-------------    35%                  ] 706 of 2000 complete in 302.5 sec
[-------------    35%                  ] 708 of 2000 complete in 303.3 sec
[-------------    35%                  ] 710 of 2000 complete in 304.1 sec
[-------------    35%                  ] 712 of 2000 complete in 305.0 sec
[-------------    35%                  ] 714 of 2000 complete in 305.9 sec
[-------------    35%                  ] 716 of 2000 complete in 306.7 sec
[-------------    35%                  ] 718 of 2000 complete in 307.6 sec
[-------------    36%                  ] 720 of 2000 complete in 308.5 sec
[-------------    36%                  ] 722 of 2000 complete in 309.3 sec
[-------------    36%                  ] 724 of 2000 complete in 310.2 sec
[-------------    36%                  ] 726 of 2000 complete in 311.0 sec
[-------------    36%                  ] 728 of 2000 complete in 311.9 sec
[-------------    36%                  ] 730 of 2000 complete in 312.7 sec
[-------------    36%                  ] 732 of 2000 complete in 313.5 sec
[-------------    36%                  ] 734 of 2000 complete in 314.4 sec
[-------------    36%                  ] 736 of 2000 complete in 315.2 sec
[--------------   36%                  ] 738 of 2000 complete in 316.1 sec
[--------------   37%                  ] 740 of 2000 complete in 316.9 sec
[--------------   37%                  ] 742 of 2000 complete in 317.8 sec
[--------------   37%                  ] 744 of 2000 complete in 318.6 sec
[--------------   37%                  ] 746 of 2000 complete in 319.5 sec
[--------------   37%                  ] 748 of 2000 complete in 320.4 sec
[--------------   37%                  ] 750 of 2000 complete in 321.2 sec
[--------------   37%                  ] 752 of 2000 complete in 322.1 sec
[--------------   37%                  ] 754 of 2000 complete in 323.0 sec
[--------------   37%                  ] 756 of 2000 complete in 323.8 sec
[--------------   37%                  ] 758 of 2000 complete in 324.7 sec
[--------------   38%                  ] 760 of 2000 complete in 325.6 sec
[--------------   38%                  ] 762 of 2000 complete in 326.4 sec
[--------------   38%                  ] 764 of 2000 complete in 327.3 sec
[--------------   38%                  ] 766 of 2000 complete in 328.2 sec
[--------------   38%                  ] 768 of 2000 complete in 329.0 sec
[--------------   38%                  ] 770 of 2000 complete in 329.9 sec
[--------------   38%                  ] 772 of 2000 complete in 330.7 sec
[--------------   38%                  ] 774 of 2000 complete in 331.5 sec
[--------------   38%                  ] 776 of 2000 complete in 332.4 sec
[--------------   38%                  ] 778 of 2000 complete in 333.2 sec
[--------------   39%                  ] 780 of 2000 complete in 334.1 sec
[--------------   39%                  ] 782 of 2000 complete in 335.0 sec
[--------------   39%                  ] 784 of 2000 complete in 335.9 sec
[--------------   39%                  ] 786 of 2000 complete in 336.7 sec
[--------------   39%                  ] 788 of 2000 complete in 337.6 sec
[---------------  39%                  ] 790 of 2000 complete in 338.4 sec
[---------------  39%                  ] 792 of 2000 complete in 339.3 sec
[---------------  39%                  ] 794 of 2000 complete in 340.2 sec
[---------------  39%                  ] 796 of 2000 complete in 341.1 sec
[---------------  39%                  ] 798 of 2000 complete in 342.0 sec
[---------------  40%                  ] 800 of 2000 complete in 342.9 sec
[---------------  40%                  ] 802 of 2000 complete in 343.8 sec
[---------------  40%                  ] 804 of 2000 complete in 344.6 sec
[---------------  40%                  ] 806 of 2000 complete in 345.4 sec
[---------------  40%                  ] 808 of 2000 complete in 346.3 sec
[---------------  40%                  ] 810 of 2000 complete in 347.2 sec
[---------------  40%                  ] 812 of 2000 complete in 348.1 sec
[---------------  40%                  ] 814 of 2000 complete in 349.0 sec
[---------------  40%                  ] 816 of 2000 complete in 349.8 sec
[---------------  40%                  ] 818 of 2000 complete in 350.7 sec
[---------------  41%                  ] 820 of 2000 complete in 351.6 sec
[---------------  41%                  ] 822 of 2000 complete in 352.4 sec
[---------------  41%                  ] 824 of 2000 complete in 353.3 sec
[---------------  41%                  ] 826 of 2000 complete in 354.2 sec
[---------------  41%                  ] 828 of 2000 complete in 355.0 sec
[---------------  41%                  ] 830 of 2000 complete in 355.9 sec
[---------------  41%                  ] 832 of 2000 complete in 356.8 sec
[---------------  41%                  ] 834 of 2000 complete in 357.6 sec
[---------------  41%                  ] 836 of 2000 complete in 358.5 sec
[---------------  41%                  ] 838 of 2000 complete in 359.3 sec
[---------------  42%                  ] 840 of 2000 complete in 360.1 sec
[---------------  42%                  ] 842 of 2000 complete in 361.0 sec
[---------------- 42%                  ] 844 of 2000 complete in 361.8 sec
[---------------- 42%                  ] 846 of 2000 complete in 362.7 sec
[---------------- 42%                  ] 848 of 2000 complete in 363.5 sec
[---------------- 42%                  ] 850 of 2000 complete in 364.4 sec
[---------------- 42%                  ] 852 of 2000 complete in 365.3 sec
[---------------- 42%                  ] 854 of 2000 complete in 366.1 sec
[---------------- 42%                  ] 856 of 2000 complete in 367.0 sec
[---------------- 42%                  ] 858 of 2000 complete in 367.8 sec
[---------------- 43%                  ] 860 of 2000 complete in 368.6 sec
[---------------- 43%                  ] 862 of 2000 complete in 369.5 sec
[---------------- 43%                  ] 864 of 2000 complete in 370.4 sec
[---------------- 43%                  ] 866 of 2000 complete in 371.2 sec
[---------------- 43%                  ] 868 of 2000 complete in 372.0 sec
[---------------- 43%                  ] 870 of 2000 complete in 372.9 sec

[------------     32%                  ] 655 of 2000 complete in 282.9 sec
[------------     32%                  ] 657 of 2000 complete in 283.7 sec
[------------     32%                  ] 659 of 2000 complete in 284.6 sec
[------------     33%                  ] 661 of 2000 complete in 285.4 sec
[------------     33%                  ] 663 of 2000 complete in 286.3 sec
[------------     33%                  ] 665 of 2000 complete in 287.2 sec
[------------     33%                  ] 667 of 2000 complete in 288.2 sec
[------------     33%                  ] 668 of 2000 complete in 288.7 sec
[------------     33%                  ] 670 of 2000 complete in 289.6 sec
[------------     33%                  ] 672 of 2000 complete in 290.4 sec
[------------     33%                  ] 674 of 2000 complete in 291.3 sec
[------------     33%                  ] 676 of 2000 complete in 292.2 sec
[------------     33%                  ] 677 of 2000 complete in 292.7 sec
[------------     33%                  ] 679 of 2000 complete in 293.6 sec
[------------     34%                  ] 681 of 2000 complete in 294.4 sec
[------------     34%                  ] 683 of 2000 complete in 295.3 sec
[-------------    34%                  ] 685 of 2000 complete in 296.2 sec
[-------------    34%                  ] 687 of 2000 complete in 297.0 sec
[-------------    34%                  ] 689 of 2000 complete in 297.9 sec
[-------------    34%                  ] 691 of 2000 complete in 298.8 sec
[-------------    34%                  ] 693 of 2000 complete in 299.7 sec
[-------------    34%                  ] 695 of 2000 complete in 300.6 sec
[-------------    34%                  ] 697 of 2000 complete in 301.4 sec
[-------------    34%                  ] 699 of 2000 complete in 302.3 sec
[-------------    35%                  ] 701 of 2000 complete in 303.2 sec
[-------------    35%                  ] 703 of 2000 complete in 304.0 sec
[-------------    35%                  ] 705 of 2000 complete in 304.9 sec
[-------------    35%                  ] 707 of 2000 complete in 305.7 sec
[-------------    35%                  ] 709 of 2000 complete in 306.6 sec
[-------------    35%                  ] 711 of 2000 complete in 307.4 sec
[-------------    35%                  ] 713 of 2000 complete in 308.3 sec
[-------------    35%                  ] 715 of 2000 complete in 309.2 sec
[-------------    35%                  ] 717 of 2000 complete in 310.0 sec
[-------------    35%                  ] 719 of 2000 complete in 310.9 sec
[-------------    36%                  ] 721 of 2000 complete in 311.8 sec
[-------------    36%                  ] 723 of 2000 complete in 312.6 sec
[-------------    36%                  ] 725 of 2000 complete in 313.5 sec
[-------------    36%                  ] 727 of 2000 complete in 314.3 sec
[-------------    36%                  ] 729 of 2000 complete in 315.2 sec
[-------------    36%                  ] 731 of 2000 complete in 316.0 sec
[-------------    36%                  ] 733 of 2000 complete in 316.9 sec
[-------------    36%                  ] 735 of 2000 complete in 317.7 sec
[--------------   36%                  ] 737 of 2000 complete in 318.6 sec
[--------------   36%                  ] 739 of 2000 complete in 319.5 sec
[--------------   37%                  ] 741 of 2000 complete in 320.3 sec
[--------------   37%                  ] 743 of 2000 complete in 321.2 sec
[--------------   37%                  ] 745 of 2000 complete in 322.1 sec
[--------------   37%                  ] 747 of 2000 complete in 322.9 sec
[--------------   37%                  ] 749 of 2000 complete in 323.8 sec
[--------------   37%                  ] 751 of 2000 complete in 324.7 sec
[--------------   37%                  ] 753 of 2000 complete in 325.5 sec
[--------------   37%                  ] 755 of 2000 complete in 326.4 sec
[--------------   37%                  ] 757 of 2000 complete in 327.3 sec
[--------------   37%                  ] 759 of 2000 complete in 328.1 sec
[--------------   38%                  ] 761 of 2000 complete in 329.0 sec
[--------------   38%                  ] 763 of 2000 complete in 329.9 sec
[--------------   38%                  ] 765 of 2000 complete in 330.7 sec
[--------------   38%                  ] 767 of 2000 complete in 331.5 sec
[--------------   38%                  ] 769 of 2000 complete in 332.4 sec
[--------------   38%                  ] 771 of 2000 complete in 333.3 sec
[--------------   38%                  ] 773 of 2000 complete in 334.2 sec
[--------------   38%                  ] 775 of 2000 complete in 335.1 sec
[--------------   38%                  ] 777 of 2000 complete in 336.0 sec
[--------------   38%                  ] 779 of 2000 complete in 336.9 sec
[--------------   39%                  ] 781 of 2000 complete in 337.8 sec
[--------------   39%                  ] 783 of 2000 complete in 338.6 sec
[--------------   39%                  ] 785 of 2000 complete in 339.6 sec
[--------------   39%                  ] 787 of 2000 complete in 340.4 sec
[--------------   39%                  ] 789 of 2000 complete in 341.3 sec
[---------------  39%                  ] 791 of 2000 complete in 342.2 sec
[---------------  39%                  ] 793 of 2000 complete in 343.1 sec
[---------------  39%                  ] 795 of 2000 complete in 344.0 sec
[---------------  39%                  ] 797 of 2000 complete in 344.8 sec
[---------------  39%                  ] 799 of 2000 complete in 345.7 sec
[---------------  40%                  ] 801 of 2000 complete in 346.5 sec
[---------------  40%                  ] 803 of 2000 complete in 347.4 sec
[---------------  40%                  ] 805 of 2000 complete in 348.3 sec
[---------------  40%                  ] 807 of 2000 complete in 349.2 sec
[---------------  40%                  ] 809 of 2000 complete in 350.0 sec
[---------------  40%                  ] 811 of 2000 complete in 350.9 sec
[---------------  40%                  ] 813 of 2000 complete in 351.8 sec
[---------------  40%                  ] 815 of 2000 complete in 352.7 sec
[---------------  40%                  ] 817 of 2000 complete in 353.5 sec
[---------------  40%                  ] 819 of 2000 complete in 354.4 sec
[---------------  41%                  ] 821 of 2000 complete in 355.3 sec
[---------------  41%                  ] 823 of 2000 complete in 356.2 sec
[---------------  41%                  ] 825 of 2000 complete in 357.1 sec
[---------------  41%                  ] 827 of 2000 complete in 358.0 sec
[---------------  41%                  ] 829 of 2000 complete in 358.8 sec
[---------------  41%                  ] 831 of 2000 complete in 359.6 sec
[---------------  41%                  ] 833 of 2000 complete in 360.5 sec
[---------------  41%                  ] 835 of 2000 complete in 361.3 sec
[---------------  41%                  ] 837 of 2000 complete in 362.2 sec
[---------------  41%                  ] 839 of 2000 complete in 363.1 sec
[---------------  42%                  ] 841 of 2000 complete in 363.9 sec
[---------------- 42%                  ] 843 of 2000 complete in 364.8 sec
[---------------- 42%                  ] 845 of 2000 complete in 365.7 sec
[---------------- 42%                  ] 847 of 2000 complete in 366.5 sec
[---------------- 42%                  ] 849 of 2000 complete in 367.4 sec
[---------------- 42%                  ] 851 of 2000 complete in 368.2 sec
[---------------- 42%                  ] 853 of 2000 complete in 369.1 sec
[---------------- 42%                  ] 855 of 2000 complete in 369.9 sec
[---------------- 42%                  ] 857 of 2000 complete in 370.7 sec
[---------------- 42%                  ] 859 of 2000 complete in 371.6 sec
[---------------- 43%                  ] 861 of 2000 complete in 372.4 sec
[---------------- 43%                  ] 863 of 2000 complete in 373.3 sec
[---------------- 43%                  ] 865 of 2000 complete in 374.2 sec
[---------------- 43%                  ] 867 of 2000 complete in 375.0 sec
[---------------- 43%                  ] 869 of 2000 complete in 375.9 sec
[------------     32%                  ] 656 of 2000 complete in 283.1 sec
[------------     32%                  ] 658 of 2000 complete in 284.0 sec
[------------     33%                  ] 660 of 2000 complete in 284.8 sec
[------------     33%                  ] 662 of 2000 complete in 285.7 sec
[------------     33%                  ] 664 of 2000 complete in 286.5 sec
[------------     33%                  ] 666 of 2000 complete in 287.5 sec
[------------     33%                  ] 668 of 2000 complete in 288.4 sec
[------------     33%                  ] 669 of 2000 complete in 288.9 sec
[------------     33%                  ] 671 of 2000 complete in 289.8 sec
[------------     33%                  ] 673 of 2000 complete in 290.7 sec
[------------     33%                  ] 675 of 2000 complete in 291.6 sec
[------------     33%                  ] 677 of 2000 complete in 292.4 sec
[------------     33%                  ] 678 of 2000 complete in 292.9 sec
[------------     34%                  ] 680 of 2000 complete in 293.8 sec
[------------     34%                  ] 682 of 2000 complete in 294.7 sec
[------------     34%                  ] 684 of 2000 complete in 295.5 sec
[-------------    34%                  ] 686 of 2000 complete in 296.4 sec
[-------------    34%                  ] 688 of 2000 complete in 297.3 sec
[-------------    34%                  ] 690 of 2000 complete in 298.1 sec
[-------------    34%                  ] 692 of 2000 complete in 298.9 sec
[-------------    34%                  ] 694 of 2000 complete in 299.9 sec
[-------------    34%                  ] 696 of 2000 complete in 300.8 sec
[-------------    34%                  ] 698 of 2000 complete in 301.6 sec
[-------------    35%                  ] 700 of 2000 complete in 302.4 sec
[-------------    35%                  ] 702 of 2000 complete in 303.3 sec
[-------------    35%                  ] 704 of 2000 complete in 304.2 sec
[-------------    35%                  ] 706 of 2000 complete in 305.1 sec
[-------------    35%                  ] 708 of 2000 complete in 306.0 sec
[-------------    35%                  ] 710 of 2000 complete in 306.8 sec
[-------------    35%                  ] 712 of 2000 complete in 307.7 sec
[-------------    35%                  ] 714 of 2000 complete in 308.5 sec
[-------------    35%                  ] 716 of 2000 complete in 309.4 sec
[-------------    35%                  ] 718 of 2000 complete in 310.2 sec
[-------------    36%                  ] 720 of 2000 complete in 311.1 sec
[-------------    36%                  ] 722 of 2000 complete in 311.9 sec
[-------------    36%                  ] 724 of 2000 complete in 312.8 sec
[-------------    36%                  ] 726 of 2000 complete in 313.7 sec
[-------------    36%                  ] 728 of 2000 complete in 314.6 sec
[-------------    36%                  ] 730 of 2000 complete in 315.4 sec
[-------------    36%                  ] 732 of 2000 complete in 316.3 sec
[-------------    36%                  ] 734 of 2000 complete in 317.1 sec
[-------------    36%                  ] 736 of 2000 complete in 318.0 sec
[--------------   36%                  ] 738 of 2000 complete in 318.9 sec
[--------------   37%                  ] 740 of 2000 complete in 319.8 sec
[--------------   37%                  ] 742 of 2000 complete in 320.6 sec
[--------------   37%                  ] 744 of 2000 complete in 321.5 sec
[--------------   37%                  ] 746 of 2000 complete in 322.4 sec
[--------------   37%                  ] 748 of 2000 complete in 323.2 sec
[--------------   37%                  ] 750 of 2000 complete in 324.1 sec
[--------------   37%                  ] 752 of 2000 complete in 325.0 sec
[--------------   37%                  ] 754 of 2000 complete in 325.9 sec
[--------------   37%                  ] 756 of 2000 complete in 326.7 sec
[--------------   37%                  ] 758 of 2000 complete in 327.6 sec
[--------------   38%                  ] 760 of 2000 complete in 328.5 sec
[--------------   38%                  ] 762 of 2000 complete in 329.4 sec
[--------------   38%                  ] 764 of 2000 complete in 330.2 sec
[--------------   38%                  ] 766 of 2000 complete in 331.1 sec
[--------------   38%                  ] 768 of 2000 complete in 331.9 sec
[--------------   38%                  ] 770 of 2000 complete in 332.8 sec
[--------------   38%                  ] 772 of 2000 complete in 333.7 sec
[--------------   38%                  ] 774 of 2000 complete in 334.6 sec
[--------------   38%                  ] 776 of 2000 complete in 335.5 sec
[--------------   38%                  ] 778 of 2000 complete in 336.4 sec
[--------------   39%                  ] 780 of 2000 complete in 337.3 sec
[--------------   39%                  ] 782 of 2000 complete in 338.1 sec
[--------------   39%                  ] 784 of 2000 complete in 339.0 sec
[--------------   39%                  ] 786 of 2000 complete in 339.9 sec
[--------------   39%                  ] 788 of 2000 complete in 340.8 sec
[---------------  39%                  ] 790 of 2000 complete in 341.7 sec
[---------------  39%                  ] 792 of 2000 complete in 342.6 sec
[---------------  39%                  ] 794 of 2000 complete in 343.5 sec
[---------------  39%                  ] 796 of 2000 complete in 344.4 sec
[---------------  39%                  ] 798 of 2000 complete in 345.3 sec
[---------------  40%                  ] 800 of 2000 complete in 346.1 sec
[---------------  40%                  ] 802 of 2000 complete in 347.0 sec
[---------------  40%                  ] 804 of 2000 complete in 347.8 sec
[---------------  40%                  ] 806 of 2000 complete in 348.7 sec
[---------------  40%                  ] 808 of 2000 complete in 349.5 sec
[---------------  40%                  ] 810 of 2000 complete in 350.4 sec
[---------------  40%                  ] 812 of 2000 complete in 351.3 sec
[---------------  40%                  ] 814 of 2000 complete in 352.1 sec
[---------------  40%                  ] 816 of 2000 complete in 353.0 sec
[---------------  40%                  ] 818 of 2000 complete in 353.9 sec
[---------------  41%                  ] 820 of 2000 complete in 354.8 sec
[---------------  41%                  ] 822 of 2000 complete in 355.7 sec
[---------------  41%                  ] 824 of 2000 complete in 356.6 sec
[---------------  41%                  ] 826 of 2000 complete in 357.5 sec
[---------------  41%                  ] 828 of 2000 complete in 358.4 sec
[---------------  41%                  ] 830 of 2000 complete in 359.2 sec
[---------------  41%                  ] 832 of 2000 complete in 360.1 sec
[---------------  41%                  ] 834 of 2000 complete in 361.0 sec
[---------------  41%                  ] 836 of 2000 complete in 361.8 sec
[---------------  41%                  ] 838 of 2000 complete in 362.7 sec
[---------------  42%                  ] 840 of 2000 complete in 363.7 sec
[---------------  42%                  ] 842 of 2000 complete in 364.6 sec
[---------------- 42%                  ] 844 of 2000 complete in 365.4 sec
[---------------- 42%                  ] 846 of 2000 complete in 366.3 sec
[---------------- 42%                  ] 848 of 2000 complete in 367.2 sec
[---------------- 42%                  ] 850 of 2000 complete in 368.0 sec
[---------------- 42%                  ] 852 of 2000 complete in 368.9 sec
[---------------- 42%                  ] 854 of 2000 complete in 369.8 sec
[---------------- 42%                  ] 856 of 2000 complete in 370.6 sec
[---------------- 42%                  ] 858 of 2000 complete in 371.4 sec
[---------------- 43%                  ] 860 of 2000 complete in 372.2 sec
[---------------- 43%                  ] 862 of 2000 complete in 373.1 sec
[---------------- 43%                  ] 864 of 2000 complete in 373.9 sec
[---------------- 43%                  ] 866 of 2000 complete in 374.7 sec
[---------------- 43%                  ] 868 of 2000 complete in 375.5 sec
[---------------- 43%                  ] 870 of 2000 complete in 376.4 sec

[------------     32%                  ] 657 of 2000 complete in 283.6 sec
[------------     32%                  ] 659 of 2000 complete in 284.5 sec
[------------     33%                  ] 661 of 2000 complete in 285.3 sec
[------------     33%                  ] 663 of 2000 complete in 286.1 sec
[------------     33%                  ] 665 of 2000 complete in 287.0 sec
[------------     33%                  ] 667 of 2000 complete in 287.9 sec
[------------     33%                  ] 669 of 2000 complete in 288.9 sec
[------------     33%                  ] 671 of 2000 complete in 289.8 sec
[------------     33%                  ] 673 of 2000 complete in 290.7 sec
[------------     33%                  ] 675 of 2000 complete in 291.5 sec
[------------     33%                  ] 677 of 2000 complete in 292.4 sec
[------------     33%                  ] 679 of 2000 complete in 293.3 sec
[------------     34%                  ] 681 of 2000 complete in 294.2 sec
[------------     34%                  ] 683 of 2000 complete in 295.1 sec
[-------------    34%                  ] 685 of 2000 complete in 295.9 sec
[-------------    34%                  ] 687 of 2000 complete in 296.7 sec
[-------------    34%                  ] 689 of 2000 complete in 297.6 sec
[-------------    34%                  ] 691 of 2000 complete in 298.4 sec
[-------------    34%                  ] 693 of 2000 complete in 299.3 sec
[-------------    34%                  ] 695 of 2000 complete in 300.3 sec
[-------------    34%                  ] 697 of 2000 complete in 301.2 sec
[-------------    34%                  ] 699 of 2000 complete in 302.0 sec
[-------------    35%                  ] 701 of 2000 complete in 302.9 sec
[-------------    35%                  ] 703 of 2000 complete in 303.7 sec
[-------------    35%                  ] 705 of 2000 complete in 304.6 sec
[-------------    35%                  ] 707 of 2000 complete in 305.5 sec
[-------------    35%                  ] 709 of 2000 complete in 306.4 sec
[-------------    35%                  ] 711 of 2000 complete in 307.2 sec
[-------------    35%                  ] 713 of 2000 complete in 308.1 sec
[-------------    35%                  ] 715 of 2000 complete in 308.9 sec
[-------------    35%                  ] 717 of 2000 complete in 309.8 sec
[-------------    35%                  ] 719 of 2000 complete in 310.7 sec
[-------------    36%                  ] 721 of 2000 complete in 311.5 sec
[-------------    36%                  ] 723 of 2000 complete in 312.4 sec
[-------------    36%                  ] 725 of 2000 complete in 313.3 sec
[-------------    36%                  ] 727 of 2000 complete in 314.2 sec
[-------------    36%                  ] 729 of 2000 complete in 315.0 sec
[-------------    36%                  ] 731 of 2000 complete in 315.8 sec
[-------------    36%                  ] 733 of 2000 complete in 316.7 sec
[-------------    36%                  ] 735 of 2000 complete in 317.5 sec
[--------------   36%                  ] 737 of 2000 complete in 318.4 sec
[--------------   36%                  ] 739 of 2000 complete in 319.3 sec
[--------------   37%                  ] 741 of 2000 complete in 320.1 sec
[--------------   37%                  ] 743 of 2000 complete in 321.0 sec
[--------------   37%                  ] 745 of 2000 complete in 321.8 sec
[--------------   37%                  ] 747 of 2000 complete in 322.7 sec
[--------------   37%                  ] 749 of 2000 complete in 323.5 sec
[--------------   37%                  ] 751 of 2000 complete in 324.4 sec
[--------------   37%                  ] 753 of 2000 complete in 325.3 sec
[--------------   37%                  ] 755 of 2000 complete in 326.2 sec
[--------------   37%                  ] 757 of 2000 complete in 327.1 sec
[--------------   37%                  ] 759 of 2000 complete in 328.0 sec
[--------------   38%                  ] 761 of 2000 complete in 328.8 sec
[--------------   38%                  ] 763 of 2000 complete in 329.7 sec
[--------------   38%                  ] 765 of 2000 complete in 330.5 sec
[--------------   38%                  ] 767 of 2000 complete in 331.3 sec
[--------------   38%                  ] 769 of 2000 complete in 332.1 sec
[--------------   38%                  ] 771 of 2000 complete in 333.0 sec
[--------------   38%                  ] 773 of 2000 complete in 333.9 sec
[--------------   38%                  ] 775 of 2000 complete in 334.8 sec
[--------------   38%                  ] 777 of 2000 complete in 335.7 sec
[--------------   38%                  ] 779 of 2000 complete in 336.6 sec
[--------------   39%                  ] 781 of 2000 complete in 337.5 sec
[--------------   39%                  ] 783 of 2000 complete in 338.3 sec
[--------------   39%                  ] 785 of 2000 complete in 339.2 sec
[--------------   39%                  ] 787 of 2000 complete in 340.1 sec
[--------------   39%                  ] 789 of 2000 complete in 341.0 sec
[---------------  39%                  ] 791 of 2000 complete in 341.8 sec
[---------------  39%                  ] 793 of 2000 complete in 342.7 sec
[---------------  39%                  ] 795 of 2000 complete in 343.6 sec
[---------------  39%                  ] 797 of 2000 complete in 344.5 sec
[---------------  39%                  ] 799 of 2000 complete in 345.4 sec
[---------------  40%                  ] 801 of 2000 complete in 346.3 sec
[---------------  40%                  ] 803 of 2000 complete in 347.2 sec
[---------------  40%                  ] 805 of 2000 complete in 348.1 sec
[---------------  40%                  ] 807 of 2000 complete in 349.0 sec
[---------------  40%                  ] 809 of 2000 complete in 349.9 sec
[---------------  40%                  ] 811 of 2000 complete in 350.8 sec
[---------------  40%                  ] 813 of 2000 complete in 351.6 sec
[---------------  40%                  ] 815 of 2000 complete in 352.5 sec
[---------------  40%                  ] 817 of 2000 complete in 353.3 sec
[---------------  40%                  ] 819 of 2000 complete in 354.2 sec
[---------------  41%                  ] 821 of 2000 complete in 355.1 sec
[---------------  41%                  ] 823 of 2000 complete in 356.0 sec
[---------------  41%                  ] 825 of 2000 complete in 356.8 sec
[---------------  41%                  ] 827 of 2000 complete in 357.7 sec
[---------------  41%                  ] 829 of 2000 complete in 358.6 sec
[---------------  41%                  ] 831 of 2000 complete in 359.4 sec
[---------------  41%                  ] 833 of 2000 complete in 360.3 sec
[---------------  41%                  ] 835 of 2000 complete in 361.2 sec
[---------------  41%                  ] 837 of 2000 complete in 362.0 sec
[---------------  41%                  ] 839 of 2000 complete in 362.9 sec
[---------------  42%                  ] 841 of 2000 complete in 363.8 sec
[---------------- 42%                  ] 843 of 2000 complete in 364.7 sec
[---------------- 42%                  ] 845 of 2000 complete in 365.5 sec
[---------------- 42%                  ] 847 of 2000 complete in 366.3 sec
[---------------- 42%                  ] 849 of 2000 complete in 367.2 sec
[---------------- 42%                  ] 851 of 2000 complete in 368.0 sec
[---------------- 42%                  ] 853 of 2000 complete in 368.9 sec
[---------------- 42%                  ] 855 of 2000 complete in 369.8 sec
[---------------- 42%                  ] 857 of 2000 complete in 370.6 sec
[---------------- 42%                  ] 859 of 2000 complete in 371.5 sec
[---------------- 43%                  ] 861 of 2000 complete in 372.3 sec
[---------------- 43%                  ] 863 of 2000 complete in 373.1 sec
[---------------- 43%                  ] 865 of 2000 complete in 374.0 sec
[---------------- 43%                  ] 867 of 2000 complete in 374.9 sec
[---------------- 43%                  ] 869 of 2000 complete in 375.7 sec
[---------------- 43%                  ] 871 of 2000 complete in 376.6 sec
[---------------- 43%                  ] 873 of 2000 complete in 377.4 sec
[---------------- 43%                  ] 872 of 2000 complete in 373.7 sec
[---------------- 43%                  ] 874 of 2000 complete in 374.5 sec
[---------------- 43%                  ] 876 of 2000 complete in 375.4 sec
[---------------- 43%                  ] 878 of 2000 complete in 376.2 sec
[---------------- 44%                  ] 880 of 2000 complete in 377.0 sec
[---------------- 44%                  ] 882 of 2000 complete in 377.9 sec
[---------------- 44%                  ] 884 of 2000 complete in 378.7 sec
[---------------- 44%                  ] 886 of 2000 complete in 379.6 sec
[---------------- 44%                  ] 888 of 2000 complete in 380.4 sec
[---------------- 44%                  ] 890 of 2000 complete in 381.2 sec
[---------------- 44%                  ] 892 of 2000 complete in 382.0 sec
[---------------- 44%                  ] 894 of 2000 complete in 382.9 sec
[-----------------44%                  ] 896 of 2000 complete in 383.8 sec
[-----------------44%                  ] 898 of 2000 complete in 384.7 sec
[-----------------45%                  ] 900 of 2000 complete in 385.5 sec
[-----------------45%                  ] 902 of 2000 complete in 386.3 sec
[-----------------45%                  ] 904 of 2000 complete in 387.1 sec
[-----------------45%                  ] 906 of 2000 complete in 388.0 sec
[-----------------45%                  ] 908 of 2000 complete in 388.8 sec
[-----------------45%                  ] 910 of 2000 complete in 389.6 sec
[-----------------45%                  ] 912 of 2000 complete in 390.5 sec
[-----------------45%                  ] 914 of 2000 complete in 391.4 sec
[-----------------45%                  ] 916 of 2000 complete in 392.3 sec
[-----------------45%                  ] 918 of 2000 complete in 393.1 sec
[-----------------46%                  ] 920 of 2000 complete in 393.9 sec
[-----------------46%                  ] 922 of 2000 complete in 394.8 sec
[-----------------46%                  ] 924 of 2000 complete in 395.6 sec
[-----------------46%                  ] 926 of 2000 complete in 396.5 sec
[-----------------46%                  ] 928 of 2000 complete in 397.3 sec
[-----------------46%                  ] 930 of 2000 complete in 398.2 sec
[-----------------46%                  ] 932 of 2000 complete in 399.1 sec
[-----------------46%                  ] 934 of 2000 complete in 399.9 sec
[-----------------46%                  ] 936 of 2000 complete in 400.8 sec
[-----------------46%                  ] 938 of 2000 complete in 401.6 sec
[-----------------47%                  ] 940 of 2000 complete in 402.5 sec
[-----------------47%                  ] 942 of 2000 complete in 403.4 sec
[-----------------47%                  ] 944 of 2000 complete in 404.2 sec
[-----------------47%                  ] 946 of 2000 complete in 405.1 sec
[-----------------47%                  ] 948 of 2000 complete in 405.9 sec
[-----------------47%                  ] 950 of 2000 complete in 406.8 sec
[-----------------47%                  ] 952 of 2000 complete in 407.7 sec
[-----------------47%                  ] 954 of 2000 complete in 408.5 sec
[-----------------47%                  ] 956 of 2000 complete in 409.4 sec
[-----------------47%                  ] 958 of 2000 complete in 410.3 sec
[-----------------48%                  ] 960 of 2000 complete in 411.2 sec
[-----------------48%                  ] 962 of 2000 complete in 412.0 sec
[-----------------48%                  ] 964 of 2000 complete in 412.8 sec
[-----------------48%                  ] 966 of 2000 complete in 413.7 sec
[-----------------48%                  ] 968 of 2000 complete in 414.6 sec
[-----------------48%                  ] 970 of 2000 complete in 415.4 sec
[-----------------48%                  ] 972 of 2000 complete in 416.3 sec
[-----------------48%                  ] 974 of 2000 complete in 417.1 sec
[-----------------48%                  ] 976 of 2000 complete in 417.9 sec
[-----------------48%                  ] 978 of 2000 complete in 418.8 sec
[-----------------49%                  ] 980 of 2000 complete in 419.7 sec
[-----------------49%                  ] 982 of 2000 complete in 420.5 sec
[-----------------49%                  ] 984 of 2000 complete in 421.4 sec
[-----------------49%                  ] 985 of 2000 complete in 422.0 sec
[-----------------49%                  ] 986 of 2000 complete in 422.5 sec
[-----------------49%                  ] 988 of 2000 complete in 423.4 sec
[-----------------49%                  ] 990 of 2000 complete in 424.2 sec
[-----------------49%                  ] 992 of 2000 complete in 425.1 sec
[-----------------49%                  ] 994 of 2000 complete in 425.9 sec
[-----------------49%                  ] 996 of 2000 complete in 426.7 sec
[-----------------49%                  ] 998 of 2000 complete in 427.6 sec
[-----------------50%                  ] 1000 of 2000 complete in 428.4 sec
[-----------------50%                  ] 1002 of 2000 complete in 429.2 sec
[-----------------50%                  ] 1004 of 2000 complete in 430.1 sec
[-----------------50%                  ] 1006 of 2000 complete in 430.9 sec
[-----------------50%                  ] 1008 of 2000 complete in 431.7 sec
[-----------------50%                  ] 1010 of 2000 complete in 432.6 sec
[-----------------50%                  ] 1012 of 2000 complete in 433.4 sec
[-----------------50%                  ] 1014 of 2000 complete in 434.2 sec
[-----------------50%                  ] 1016 of 2000 complete in 435.1 sec
[-----------------50%                  ] 1018 of 2000 complete in 435.9 sec
[-----------------51%                  ] 1020 of 2000 complete in 436.7 sec
[-----------------51%                  ] 1022 of 2000 complete in 437.6 sec
[-----------------51%                  ] 1024 of 2000 complete in 438.4 sec
[-----------------51%                  ] 1026 of 2000 complete in 439.2 sec
[-----------------51%                  ] 1028 of 2000 complete in 440.0 sec
[-----------------51%                  ] 1030 of 2000 complete in 440.9 sec
[-----------------51%                  ] 1032 of 2000 complete in 441.7 sec
[-----------------51%                  ] 1034 of 2000 complete in 442.5 sec
[-----------------51%                  ] 1036 of 2000 complete in 443.4 sec
[-----------------51%                  ] 1038 of 2000 complete in 444.3 sec
[-----------------52%                  ] 1040 of 2000 complete in 445.1 sec
[-----------------52%                  ] 1042 of 2000 complete in 445.9 sec
[-----------------52%                  ] 1044 of 2000 complete in 446.7 sec
[-----------------52%                  ] 1046 of 2000 complete in 447.5 sec
[-----------------52%                  ] 1048 of 2000 complete in 448.3 sec
[-----------------52%                  ] 1050 of 2000 complete in 449.2 sec
[-----------------52%                  ] 1052 of 2000 complete in 450.0 sec
[-----------------52%                  ] 1054 of 2000 complete in 450.8 sec
[-----------------52%                  ] 1056 of 2000 complete in 451.6 sec
[-----------------52%                  ] 1058 of 2000 complete in 452.5 sec
[-----------------53%                  ] 1060 of 2000 complete in 453.3 sec
[-----------------53%                  ] 1062 of 2000 complete in 454.1 sec
[-----------------53%                  ] 1064 of 2000 complete in 454.9 sec
[-----------------53%                  ] 1066 of 2000 complete in 455.7 sec
[-----------------53%                  ] 1068 of 2000 complete in 456.6 sec
[-----------------53%                  ] 1070 of 2000 complete in 457.4 sec
[-----------------53%                  ] 1072 of 2000 complete in 458.2 sec
[-----------------53%                  ] 1074 of 2000 complete in 459.1 sec
[-----------------53%                  ] 1076 of 2000 complete in 459.9 sec
[-----------------53%                  ] 1078 of 2000 complete in 460.8 sec
[-----------------54%                  ] 1080 of 2000 complete in 461.6 sec
[-----------------54%                  ] 1082 of 2000 complete in 462.4 sec
[-----------------54%                  ] 1084 of 2000 complete in 463.2 sec

[---------------- 43%                  ] 871 of 2000 complete in 376.7 sec
[---------------- 43%                  ] 873 of 2000 complete in 377.6 sec
[---------------- 43%                  ] 875 of 2000 complete in 378.5 sec
[---------------- 43%                  ] 877 of 2000 complete in 379.3 sec
[---------------- 43%                  ] 879 of 2000 complete in 380.1 sec
[---------------- 44%                  ] 881 of 2000 complete in 381.0 sec
[---------------- 44%                  ] 883 of 2000 complete in 381.8 sec
[---------------- 44%                  ] 885 of 2000 complete in 382.7 sec
[---------------- 44%                  ] 887 of 2000 complete in 383.6 sec
[---------------- 44%                  ] 889 of 2000 complete in 384.5 sec
[---------------- 44%                  ] 891 of 2000 complete in 385.3 sec
[---------------- 44%                  ] 893 of 2000 complete in 386.2 sec
[-----------------44%                  ] 895 of 2000 complete in 387.1 sec
[-----------------44%                  ] 897 of 2000 complete in 387.9 sec
[-----------------44%                  ] 899 of 2000 complete in 388.7 sec
[-----------------45%                  ] 901 of 2000 complete in 389.5 sec
[-----------------45%                  ] 903 of 2000 complete in 390.4 sec
[-----------------45%                  ] 905 of 2000 complete in 391.3 sec
[-----------------45%                  ] 907 of 2000 complete in 392.2 sec
[-----------------45%                  ] 909 of 2000 complete in 393.0 sec
[-----------------45%                  ] 911 of 2000 complete in 393.9 sec
[-----------------45%                  ] 913 of 2000 complete in 394.8 sec
[-----------------45%                  ] 915 of 2000 complete in 395.6 sec
[-----------------45%                  ] 917 of 2000 complete in 396.5 sec
[-----------------45%                  ] 919 of 2000 complete in 397.3 sec
[-----------------46%                  ] 921 of 2000 complete in 398.2 sec
[-----------------46%                  ] 923 of 2000 complete in 399.1 sec
[-----------------46%                  ] 925 of 2000 complete in 400.0 sec
[-----------------46%                  ] 927 of 2000 complete in 400.8 sec
[-----------------46%                  ] 929 of 2000 complete in 401.6 sec
[-----------------46%                  ] 931 of 2000 complete in 402.5 sec
[-----------------46%                  ] 933 of 2000 complete in 403.3 sec
[-----------------46%                  ] 935 of 2000 complete in 404.2 sec
[-----------------46%                  ] 937 of 2000 complete in 405.1 sec
[-----------------46%                  ] 939 of 2000 complete in 406.0 sec
[-----------------47%                  ] 941 of 2000 complete in 406.9 sec
[-----------------47%                  ] 943 of 2000 complete in 407.8 sec
[-----------------47%                  ] 945 of 2000 complete in 408.6 sec
[-----------------47%                  ] 947 of 2000 complete in 409.5 sec
[-----------------47%                  ] 949 of 2000 complete in 410.4 sec
[-----------------47%                  ] 951 of 2000 complete in 411.3 sec
[-----------------47%                  ] 953 of 2000 complete in 412.1 sec
[-----------------47%                  ] 955 of 2000 complete in 413.0 sec
[-----------------47%                  ] 957 of 2000 complete in 413.9 sec
[-----------------47%                  ] 959 of 2000 complete in 414.7 sec
[-----------------48%                  ] 961 of 2000 complete in 415.6 sec
[-----------------48%                  ] 963 of 2000 complete in 416.4 sec
[-----------------48%                  ] 965 of 2000 complete in 417.3 sec
[-----------------48%                  ] 967 of 2000 complete in 418.2 sec
[-----------------48%                  ] 969 of 2000 complete in 419.0 sec
[-----------------48%                  ] 971 of 2000 complete in 420.0 sec
[-----------------48%                  ] 973 of 2000 complete in 420.8 sec
[-----------------48%                  ] 974 of 2000 complete in 421.4 sec
[-----------------48%                  ] 975 of 2000 complete in 421.9 sec
[-----------------48%                  ] 976 of 2000 complete in 422.4 sec
[-----------------48%                  ] 978 of 2000 complete in 423.3 sec
[-----------------49%                  ] 980 of 2000 complete in 424.1 sec
[-----------------49%                  ] 982 of 2000 complete in 425.0 sec
[-----------------49%                  ] 984 of 2000 complete in 425.8 sec
[-----------------49%                  ] 986 of 2000 complete in 426.7 sec
[-----------------49%                  ] 988 of 2000 complete in 427.5 sec
[-----------------49%                  ] 990 of 2000 complete in 428.3 sec
[-----------------49%                  ] 992 of 2000 complete in 429.2 sec
[-----------------49%                  ] 994 of 2000 complete in 430.1 sec
[-----------------49%                  ] 996 of 2000 complete in 431.0 sec
[-----------------49%                  ] 998 of 2000 complete in 431.8 sec
[-----------------50%                  ] 1000 of 2000 complete in 432.6 sec
[-----------------50%                  ] 1002 of 2000 complete in 433.5 sec
[-----------------50%                  ] 1004 of 2000 complete in 434.3 sec
[-----------------50%                  ] 1006 of 2000 complete in 435.2 sec
[-----------------50%                  ] 1008 of 2000 complete in 436.0 sec
[-----------------50%                  ] 1010 of 2000 complete in 436.8 sec
[-----------------50%                  ] 1012 of 2000 complete in 437.7 sec
[-----------------50%                  ] 1014 of 2000 complete in 438.5 sec
[-----------------50%                  ] 1016 of 2000 complete in 439.3 sec
[-----------------50%                  ] 1018 of 2000 complete in 440.2 sec
[-----------------51%                  ] 1020 of 2000 complete in 441.0 sec
[-----------------51%                  ] 1022 of 2000 complete in 441.8 sec
[-----------------51%                  ] 1024 of 2000 complete in 442.7 sec
[-----------------51%                  ] 1026 of 2000 complete in 443.6 sec
[-----------------51%                  ] 1028 of 2000 complete in 444.4 sec
[-----------------51%                  ] 1030 of 2000 complete in 445.3 sec
[-----------------51%                  ] 1032 of 2000 complete in 446.1 sec
[-----------------51%                  ] 1034 of 2000 complete in 446.9 sec
[-----------------51%                  ] 1036 of 2000 complete in 447.8 sec
[-----------------51%                  ] 1038 of 2000 complete in 448.6 sec
[-----------------52%                  ] 1040 of 2000 complete in 449.4 sec
[-----------------52%                  ] 1042 of 2000 complete in 450.3 sec
[-----------------52%                  ] 1044 of 2000 complete in 451.1 sec
[-----------------52%                  ] 1046 of 2000 complete in 451.9 sec
[-----------------52%                  ] 1048 of 2000 complete in 452.8 sec
[-----------------52%                  ] 1050 of 2000 complete in 453.6 sec
[-----------------52%                  ] 1052 of 2000 complete in 454.4 sec
[-----------------52%                  ] 1054 of 2000 complete in 455.3 sec
[-----------------52%                  ] 1056 of 2000 complete in 456.1 sec
[-----------------52%                  ] 1058 of 2000 complete in 457.0 sec
[-----------------53%                  ] 1060 of 2000 complete in 457.8 sec
[-----------------53%                  ] 1062 of 2000 complete in 458.7 sec
[-----------------53%                  ] 1064 of 2000 complete in 459.5 sec
[-----------------53%                  ] 1066 of 2000 complete in 460.3 sec
[-----------------53%                  ] 1068 of 2000 complete in 461.2 sec
[-----------------53%                  ] 1070 of 2000 complete in 462.0 sec
[-----------------53%                  ] 1072 of 2000 complete in 462.8 sec
[-----------------53%                  ] 1074 of 2000 complete in 463.7 sec
[-----------------53%                  ] 1076 of 2000 complete in 464.5 sec
[-----------------53%                  ] 1078 of 2000 complete in 465.3 sec
[-----------------54%                  ] 1080 of 2000 complete in 466.1 sec
[-----------------54%                  ] 1082 of 2000 complete in 467.0 sec
[---------------- 43%                  ] 872 of 2000 complete in 377.3 sec
[---------------- 43%                  ] 874 of 2000 complete in 378.1 sec
[---------------- 43%                  ] 876 of 2000 complete in 379.0 sec
[---------------- 43%                  ] 878 of 2000 complete in 379.8 sec
[---------------- 44%                  ] 880 of 2000 complete in 380.7 sec
[---------------- 44%                  ] 882 of 2000 complete in 381.5 sec
[---------------- 44%                  ] 884 of 2000 complete in 382.4 sec
[---------------- 44%                  ] 886 of 2000 complete in 383.3 sec
[---------------- 44%                  ] 888 of 2000 complete in 384.1 sec
[---------------- 44%                  ] 890 of 2000 complete in 385.0 sec
[---------------- 44%                  ] 892 of 2000 complete in 385.8 sec
[---------------- 44%                  ] 894 of 2000 complete in 386.7 sec
[-----------------44%                  ] 896 of 2000 complete in 387.5 sec
[-----------------44%                  ] 898 of 2000 complete in 388.3 sec
[-----------------45%                  ] 900 of 2000 complete in 389.1 sec
[-----------------45%                  ] 902 of 2000 complete in 390.0 sec
[-----------------45%                  ] 904 of 2000 complete in 390.8 sec
[-----------------45%                  ] 906 of 2000 complete in 391.7 sec
[-----------------45%                  ] 908 of 2000 complete in 392.6 sec
[-----------------45%                  ] 910 of 2000 complete in 393.4 sec
[-----------------45%                  ] 912 of 2000 complete in 394.3 sec
[-----------------45%                  ] 914 of 2000 complete in 395.1 sec
[-----------------45%                  ] 916 of 2000 complete in 396.0 sec
[-----------------45%                  ] 918 of 2000 complete in 396.9 sec
[-----------------46%                  ] 920 of 2000 complete in 397.7 sec
[-----------------46%                  ] 922 of 2000 complete in 398.7 sec
[-----------------46%                  ] 924 of 2000 complete in 399.5 sec
[-----------------46%                  ] 926 of 2000 complete in 400.4 sec
[-----------------46%                  ] 928 of 2000 complete in 401.3 sec
[-----------------46%                  ] 930 of 2000 complete in 402.1 sec
[-----------------46%                  ] 932 of 2000 complete in 403.0 sec
[-----------------46%                  ] 934 of 2000 complete in 403.9 sec
[-----------------46%                  ] 936 of 2000 complete in 404.8 sec
[-----------------46%                  ] 938 of 2000 complete in 405.6 sec
[-----------------47%                  ] 940 of 2000 complete in 406.5 sec
[-----------------47%                  ] 942 of 2000 complete in 407.4 sec
[-----------------47%                  ] 944 of 2000 complete in 408.2 sec
[-----------------47%                  ] 946 of 2000 complete in 409.1 sec
[-----------------47%                  ] 948 of 2000 complete in 410.0 sec
[-----------------47%                  ] 950 of 2000 complete in 410.9 sec
[-----------------47%                  ] 952 of 2000 complete in 411.8 sec
[-----------------47%                  ] 954 of 2000 complete in 412.6 sec
[-----------------47%                  ] 956 of 2000 complete in 413.4 sec
[-----------------47%                  ] 958 of 2000 complete in 414.3 sec
[-----------------48%                  ] 960 of 2000 complete in 415.2 sec
[-----------------48%                  ] 962 of 2000 complete in 416.1 sec
[-----------------48%                  ] 964 of 2000 complete in 416.9 sec
[-----------------48%                  ] 966 of 2000 complete in 417.8 sec
[-----------------48%                  ] 968 of 2000 complete in 418.6 sec
[-----------------48%                  ] 970 of 2000 complete in 419.5 sec
[-----------------48%                  ] 972 of 2000 complete in 420.4 sec
[-----------------48%                  ] 974 of 2000 complete in 421.3 sec
[-----------------48%                  ] 975 of 2000 complete in 421.8 sec
[-----------------48%                  ] 976 of 2000 complete in 422.4 sec
[-----------------48%                  ] 978 of 2000 complete in 423.3 sec
[-----------------49%                  ] 980 of 2000 complete in 424.1 sec
[-----------------49%                  ] 982 of 2000 complete in 425.0 sec
[-----------------49%                  ] 984 of 2000 complete in 425.8 sec
[-----------------49%                  ] 986 of 2000 complete in 426.7 sec
[-----------------49%                  ] 988 of 2000 complete in 427.5 sec
[-----------------49%                  ] 990 of 2000 complete in 428.3 sec
[-----------------49%                  ] 992 of 2000 complete in 429.2 sec
[-----------------49%                  ] 994 of 2000 complete in 430.0 sec
[-----------------49%                  ] 996 of 2000 complete in 430.9 sec
[-----------------49%                  ] 998 of 2000 complete in 431.8 sec
[-----------------50%                  ] 1000 of 2000 complete in 432.6 sec
[-----------------50%                  ] 1002 of 2000 complete in 433.4 sec
[-----------------50%                  ] 1004 of 2000 complete in 434.2 sec
[-----------------50%                  ] 1006 of 2000 complete in 435.1 sec
[-----------------50%                  ] 1008 of 2000 complete in 435.9 sec
[-----------------50%                  ] 1010 of 2000 complete in 436.7 sec
[-----------------50%                  ] 1012 of 2000 complete in 437.6 sec
[-----------------50%                  ] 1014 of 2000 complete in 438.4 sec
[-----------------50%                  ] 1016 of 2000 complete in 439.2 sec
[-----------------50%                  ] 1018 of 2000 complete in 440.1 sec
[-----------------51%                  ] 1020 of 2000 complete in 440.9 sec
[-----------------51%                  ] 1022 of 2000 complete in 441.7 sec
[-----------------51%                  ] 1024 of 2000 complete in 442.5 sec
[-----------------51%                  ] 1026 of 2000 complete in 443.4 sec
[-----------------51%                  ] 1028 of 2000 complete in 444.2 sec
[-----------------51%                  ] 1030 of 2000 complete in 445.0 sec
[-----------------51%                  ] 1032 of 2000 complete in 445.8 sec
[-----------------51%                  ] 1034 of 2000 complete in 446.7 sec
[-----------------51%                  ] 1036 of 2000 complete in 447.5 sec
[-----------------51%                  ] 1038 of 2000 complete in 448.3 sec
[-----------------52%                  ] 1040 of 2000 complete in 449.2 sec
[-----------------52%                  ] 1042 of 2000 complete in 450.0 sec
[-----------------52%                  ] 1044 of 2000 complete in 450.9 sec
[-----------------52%                  ] 1046 of 2000 complete in 451.7 sec
[-----------------52%                  ] 1048 of 2000 complete in 452.5 sec
[-----------------52%                  ] 1050 of 2000 complete in 453.4 sec
[-----------------52%                  ] 1052 of 2000 complete in 454.2 sec
[-----------------52%                  ] 1054 of 2000 complete in 455.0 sec
[-----------------52%                  ] 1056 of 2000 complete in 455.9 sec
[-----------------52%                  ] 1058 of 2000 complete in 456.7 sec
[-----------------53%                  ] 1060 of 2000 complete in 457.5 sec
[-----------------53%                  ] 1062 of 2000 complete in 458.3 sec
[-----------------53%                  ] 1064 of 2000 complete in 459.1 sec
[-----------------53%                  ] 1066 of 2000 complete in 459.9 sec
[-----------------53%                  ] 1068 of 2000 complete in 460.7 sec
[-----------------53%                  ] 1070 of 2000 complete in 461.6 sec
[-----------------53%                  ] 1072 of 2000 complete in 462.4 sec
[-----------------53%                  ] 1074 of 2000 complete in 463.2 sec
[-----------------53%                  ] 1076 of 2000 complete in 464.1 sec
[-----------------53%                  ] 1078 of 2000 complete in 464.9 sec
[-----------------54%                  ] 1080 of 2000 complete in 465.7 sec
[-----------------54%                  ] 1082 of 2000 complete in 466.6 sec
[-----------------54%                  ] 1084 of 2000 complete in 467.4 sec

[---------------- 43%                  ] 875 of 2000 complete in 378.3 sec
[---------------- 43%                  ] 877 of 2000 complete in 379.2 sec
[---------------- 43%                  ] 879 of 2000 complete in 380.0 sec
[---------------- 44%                  ] 881 of 2000 complete in 380.8 sec
[---------------- 44%                  ] 883 of 2000 complete in 381.6 sec
[---------------- 44%                  ] 885 of 2000 complete in 382.4 sec
[---------------- 44%                  ] 887 of 2000 complete in 383.3 sec
[---------------- 44%                  ] 889 of 2000 complete in 384.2 sec
[---------------- 44%                  ] 891 of 2000 complete in 385.0 sec
[---------------- 44%                  ] 893 of 2000 complete in 385.9 sec
[-----------------44%                  ] 895 of 2000 complete in 386.7 sec
[-----------------44%                  ] 897 of 2000 complete in 387.5 sec
[-----------------44%                  ] 899 of 2000 complete in 388.4 sec
[-----------------45%                  ] 901 of 2000 complete in 389.2 sec
[-----------------45%                  ] 903 of 2000 complete in 390.0 sec
[-----------------45%                  ] 905 of 2000 complete in 390.9 sec
[-----------------45%                  ] 907 of 2000 complete in 391.8 sec
[-----------------45%                  ] 909 of 2000 complete in 392.8 sec
[-----------------45%                  ] 911 of 2000 complete in 393.6 sec
[-----------------45%                  ] 913 of 2000 complete in 394.5 sec
[-----------------45%                  ] 915 of 2000 complete in 395.3 sec
[-----------------45%                  ] 917 of 2000 complete in 396.2 sec
[-----------------45%                  ] 919 of 2000 complete in 397.1 sec
[-----------------46%                  ] 921 of 2000 complete in 397.9 sec
[-----------------46%                  ] 923 of 2000 complete in 398.9 sec
[-----------------46%                  ] 925 of 2000 complete in 399.8 sec
[-----------------46%                  ] 927 of 2000 complete in 400.7 sec
[-----------------46%                  ] 929 of 2000 complete in 401.5 sec
[-----------------46%                  ] 931 of 2000 complete in 402.4 sec
[-----------------46%                  ] 933 of 2000 complete in 403.2 sec
[-----------------46%                  ] 935 of 2000 complete in 404.1 sec
[-----------------46%                  ] 937 of 2000 complete in 405.0 sec
[-----------------46%                  ] 939 of 2000 complete in 405.8 sec
[-----------------47%                  ] 941 of 2000 complete in 406.7 sec
[-----------------47%                  ] 943 of 2000 complete in 407.6 sec
[-----------------47%                  ] 945 of 2000 complete in 408.4 sec
[-----------------47%                  ] 947 of 2000 complete in 409.3 sec
[-----------------47%                  ] 949 of 2000 complete in 410.2 sec
[-----------------47%                  ] 951 of 2000 complete in 411.1 sec
[-----------------47%                  ] 953 of 2000 complete in 412.0 sec
[-----------------47%                  ] 955 of 2000 complete in 412.8 sec
[-----------------47%                  ] 957 of 2000 complete in 413.7 sec
[-----------------47%                  ] 959 of 2000 complete in 414.5 sec
[-----------------48%                  ] 961 of 2000 complete in 415.4 sec
[-----------------48%                  ] 963 of 2000 complete in 416.2 sec
[-----------------48%                  ] 965 of 2000 complete in 417.1 sec
[-----------------48%                  ] 967 of 2000 complete in 417.9 sec
[-----------------48%                  ] 969 of 2000 complete in 418.7 sec
[-----------------48%                  ] 971 of 2000 complete in 419.6 sec
[-----------------48%                  ] 973 of 2000 complete in 420.5 sec
[-----------------48%                  ] 975 of 2000 complete in 421.5 sec
[-----------------48%                  ] 976 of 2000 complete in 422.1 sec
[-----------------48%                  ] 977 of 2000 complete in 422.6 sec
[-----------------48%                  ] 979 of 2000 complete in 423.4 sec
[-----------------49%                  ] 981 of 2000 complete in 424.3 sec
[-----------------49%                  ] 983 of 2000 complete in 425.1 sec
[-----------------49%                  ] 985 of 2000 complete in 425.9 sec
[-----------------49%                  ] 987 of 2000 complete in 426.8 sec
[-----------------49%                  ] 989 of 2000 complete in 427.6 sec
[-----------------49%                  ] 991 of 2000 complete in 428.5 sec
[-----------------49%                  ] 993 of 2000 complete in 429.3 sec
[-----------------49%                  ] 995 of 2000 complete in 430.2 sec
[-----------------49%                  ] 997 of 2000 complete in 431.1 sec
[-----------------49%                  ] 999 of 2000 complete in 431.9 sec
[-----------------50%                  ] 1001 of 2000 complete in 432.7 sec
[-----------------50%                  ] 1003 of 2000 complete in 433.5 sec
[-----------------50%                  ] 1005 of 2000 complete in 434.4 sec
[-----------------50%                  ] 1007 of 2000 complete in 435.3 sec
[-----------------50%                  ] 1009 of 2000 complete in 436.1 sec
[-----------------50%                  ] 1011 of 2000 complete in 437.0 sec
[-----------------50%                  ] 1013 of 2000 complete in 437.8 sec
[-----------------50%                  ] 1015 of 2000 complete in 438.6 sec
[-----------------50%                  ] 1017 of 2000 complete in 439.5 sec
[-----------------50%                  ] 1019 of 2000 complete in 440.3 sec
[-----------------51%                  ] 1021 of 2000 complete in 441.2 sec
[-----------------51%                  ] 1023 of 2000 complete in 442.0 sec
[-----------------51%                  ] 1025 of 2000 complete in 442.9 sec
[-----------------51%                  ] 1027 of 2000 complete in 443.7 sec
[-----------------51%                  ] 1029 of 2000 complete in 444.5 sec
[-----------------51%                  ] 1031 of 2000 complete in 445.3 sec
[-----------------51%                  ] 1033 of 2000 complete in 446.2 sec
[-----------------51%                  ] 1035 of 2000 complete in 447.0 sec
[-----------------51%                  ] 1037 of 2000 complete in 447.8 sec
[-----------------51%                  ] 1039 of 2000 complete in 448.7 sec
[-----------------52%                  ] 1041 of 2000 complete in 449.5 sec
[-----------------52%                  ] 1043 of 2000 complete in 450.4 sec
[-----------------52%                  ] 1045 of 2000 complete in 451.2 sec
[-----------------52%                  ] 1047 of 2000 complete in 452.0 sec
[-----------------52%                  ] 1049 of 2000 complete in 452.8 sec
[-----------------52%                  ] 1051 of 2000 complete in 453.7 sec
[-----------------52%                  ] 1053 of 2000 complete in 454.5 sec
[-----------------52%                  ] 1055 of 2000 complete in 455.4 sec
[-----------------52%                  ] 1057 of 2000 complete in 456.2 sec
[-----------------52%                  ] 1059 of 2000 complete in 457.0 sec
[-----------------53%                  ] 1061 of 2000 complete in 457.9 sec
[-----------------53%                  ] 1063 of 2000 complete in 458.7 sec
[-----------------53%                  ] 1065 of 2000 complete in 459.5 sec
[-----------------53%                  ] 1067 of 2000 complete in 460.4 sec
[-----------------53%                  ] 1069 of 2000 complete in 461.2 sec
[-----------------53%                  ] 1071 of 2000 complete in 462.0 sec
[-----------------53%                  ] 1073 of 2000 complete in 462.8 sec
[-----------------53%                  ] 1075 of 2000 complete in 463.7 sec
[-----------------53%                  ] 1077 of 2000 complete in 464.5 sec
[-----------------53%                  ] 1079 of 2000 complete in 465.3 sec
[-----------------54%                  ] 1081 of 2000 complete in 466.1 sec
[-----------------54%                  ] 1083 of 2000 complete in 467.0 sec
[-----------------54%                  ] 1085 of 2000 complete in 467.8 sec
[-----------------54%                  ] 1087 of 2000 complete in 468.7 sec
[-----------------54%                  ] 1086 of 2000 complete in 464.0 sec
[-----------------54%                  ] 1088 of 2000 complete in 464.9 sec
[-----------------54%                  ] 1090 of 2000 complete in 465.7 sec
[-----------------54%                  ] 1092 of 2000 complete in 466.5 sec
[-----------------54%                  ] 1094 of 2000 complete in 467.4 sec
[-----------------54%                  ] 1096 of 2000 complete in 468.2 sec
[-----------------54%                  ] 1098 of 2000 complete in 469.0 sec
[-----------------55%                  ] 1100 of 2000 complete in 469.8 sec
[-----------------55%                  ] 1102 of 2000 complete in 470.6 sec
[-----------------55%                  ] 1104 of 2000 complete in 471.5 sec
[-----------------55%-                 ] 1106 of 2000 complete in 472.3 sec
[-----------------55%-                 ] 1108 of 2000 complete in 473.1 sec
[-----------------55%-                 ] 1110 of 2000 complete in 473.9 sec
[-----------------55%-                 ] 1112 of 2000 complete in 474.8 sec
[-----------------55%-                 ] 1114 of 2000 complete in 475.7 sec
[-----------------55%-                 ] 1116 of 2000 complete in 476.5 sec
[-----------------55%-                 ] 1118 of 2000 complete in 477.5 sec
[-----------------56%-                 ] 1120 of 2000 complete in 478.4 sec
[-----------------56%-                 ] 1122 of 2000 complete in 479.3 sec
[-----------------56%-                 ] 1124 of 2000 complete in 480.2 sec
[-----------------56%-                 ] 1126 of 2000 complete in 481.1 sec
[-----------------56%-                 ] 1128 of 2000 complete in 481.9 sec
[-----------------56%-                 ] 1130 of 2000 complete in 482.8 sec
[-----------------56%-                 ] 1132 of 2000 complete in 483.6 sec
[-----------------56%-                 ] 1134 of 2000 complete in 484.5 sec
[-----------------56%-                 ] 1136 of 2000 complete in 485.3 sec
[-----------------56%-                 ] 1138 of 2000 complete in 486.2 sec
[-----------------57%-                 ] 1140 of 2000 complete in 487.0 sec
[-----------------57%-                 ] 1142 of 2000 complete in 487.9 sec
[-----------------57%-                 ] 1144 of 2000 complete in 488.7 sec
[-----------------57%-                 ] 1146 of 2000 complete in 489.6 sec
[-----------------57%-                 ] 1148 of 2000 complete in 490.4 sec
[-----------------57%-                 ] 1150 of 2000 complete in 491.3 sec
[-----------------57%-                 ] 1152 of 2000 complete in 492.2 sec
[-----------------57%-                 ] 1154 of 2000 complete in 493.0 sec
[-----------------57%-                 ] 1156 of 2000 complete in 493.8 sec
[-----------------57%--                ] 1158 of 2000 complete in 494.7 sec
[-----------------58%--                ] 1160 of 2000 complete in 495.6 sec
[-----------------58%--                ] 1162 of 2000 complete in 496.5 sec
[-----------------58%--                ] 1164 of 2000 complete in 497.4 sec
[-----------------58%--                ] 1166 of 2000 complete in 498.2 sec
[-----------------58%--                ] 1168 of 2000 complete in 499.1 sec
[-----------------58%--                ] 1170 of 2000 complete in 499.9 sec
[-----------------58%--                ] 1172 of 2000 complete in 500.7 sec
[-----------------58%--                ] 1174 of 2000 complete in 501.6 sec
[-----------------58%--                ] 1176 of 2000 complete in 502.5 sec
[-----------------58%--                ] 1178 of 2000 complete in 503.4 sec
[-----------------59%--                ] 1180 of 2000 complete in 504.2 sec
[-----------------59%--                ] 1182 of 2000 complete in 505.1 sec
[-----------------59%--                ] 1184 of 2000 complete in 505.9 sec
[-----------------59%--                ] 1186 of 2000 complete in 506.7 sec
[-----------------59%--                ] 1188 of 2000 complete in 507.5 sec
[-----------------59%--                ] 1190 of 2000 complete in 508.4 sec
[-----------------59%--                ] 1192 of 2000 complete in 509.2 sec
[-----------------59%--                ] 1194 of 2000 complete in 510.1 sec
[-----------------59%--                ] 1196 of 2000 complete in 510.9 sec
[-----------------59%--                ] 1198 of 2000 complete in 511.7 sec
[-----------------60%--                ] 1200 of 2000 complete in 512.5 sec
[-----------------60%--                ] 1202 of 2000 complete in 513.4 sec
[-----------------60%--                ] 1204 of 2000 complete in 514.2 sec
[-----------------60%--                ] 1206 of 2000 complete in 515.0 sec
[-----------------60%--                ] 1208 of 2000 complete in 515.9 sec
[-----------------60%--                ] 1210 of 2000 complete in 516.7 sec
[-----------------60%---               ] 1212 of 2000 complete in 517.6 sec
[-----------------60%---               ] 1214 of 2000 complete in 518.4 sec
[-----------------60%---               ] 1216 of 2000 complete in 519.2 sec
[-----------------60%---               ] 1218 of 2000 complete in 520.0 sec
[-----------------61%---               ] 1220 of 2000 complete in 520.9 sec
[-----------------61%---               ] 1222 of 2000 complete in 521.7 sec
[-----------------61%---               ] 1224 of 2000 complete in 522.6 sec
[-----------------61%---               ] 1226 of 2000 complete in 523.4 sec
[-----------------61%---               ] 1228 of 2000 complete in 524.2 sec
[-----------------61%---               ] 1230 of 2000 complete in 525.1 sec
[-----------------61%---               ] 1232 of 2000 complete in 525.9 sec
[-----------------61%---               ] 1234 of 2000 complete in 526.7 sec
[-----------------61%---               ] 1236 of 2000 complete in 527.6 sec
[-----------------61%---               ] 1238 of 2000 complete in 528.4 sec
[-----------------62%---               ] 1240 of 2000 complete in 529.2 sec
[-----------------62%---               ] 1242 of 2000 complete in 530.1 sec
[-----------------62%---               ] 1244 of 2000 complete in 530.9 sec
[-----------------62%---               ] 1246 of 2000 complete in 531.7 sec
[-----------------62%---               ] 1248 of 2000 complete in 532.5 sec
[-----------------62%---               ] 1250 of 2000 complete in 533.4 sec
[-----------------62%---               ] 1252 of 2000 complete in 534.2 sec
[-----------------62%---               ] 1254 of 2000 complete in 535.0 sec
[-----------------62%---               ] 1256 of 2000 complete in 535.8 sec
[-----------------62%---               ] 1258 of 2000 complete in 536.6 sec
[-----------------63%---               ] 1260 of 2000 complete in 537.5 sec
[-----------------63%---               ] 1262 of 2000 complete in 538.3 sec
[-----------------63%----              ] 1264 of 2000 complete in 539.1 sec
[-----------------63%----              ] 1266 of 2000 complete in 540.0 sec
[-----------------63%----              ] 1268 of 2000 complete in 540.8 sec
[-----------------63%----              ] 1270 of 2000 complete in 541.7 sec
[-----------------63%----              ] 1272 of 2000 complete in 542.5 sec
[-----------------63%----              ] 1274 of 2000 complete in 543.4 sec
[-----------------63%----              ] 1276 of 2000 complete in 544.2 sec
[-----------------63%----              ] 1278 of 2000 complete in 545.1 sec
[-----------------64%----              ] 1280 of 2000 complete in 545.9 sec
[-----------------64%----              ] 1282 of 2000 complete in 546.8 sec
[-----------------64%----              ] 1284 of 2000 complete in 547.7 sec
[-----------------64%----              ] 1286 of 2000 complete in 548.5 sec
[-----------------64%----              ] 1288 of 2000 complete in 549.4 sec
[-----------------64%----              ] 1290 of 2000 complete in 550.3 sec
[-----------------64%----              ] 1292 of 2000 complete in 551.1 sec
[-----------------64%----              ] 1294 of 2000 complete in 552.0 sec
[-----------------64%----              ] 1296 of 2000 complete in 552.8 sec
[-----------------64%----              ] 1298 of 2000 complete in 553.6 sec

[-----------------54%                  ] 1086 of 2000 complete in 468.2 sec
[-----------------54%                  ] 1088 of 2000 complete in 469.0 sec
[-----------------54%                  ] 1090 of 2000 complete in 469.8 sec
[-----------------54%                  ] 1092 of 2000 complete in 470.7 sec
[-----------------54%                  ] 1094 of 2000 complete in 471.5 sec
[-----------------54%                  ] 1096 of 2000 complete in 472.4 sec
[-----------------54%                  ] 1098 of 2000 complete in 473.2 sec
[-----------------55%                  ] 1100 of 2000 complete in 474.0 sec
[-----------------55%                  ] 1102 of 2000 complete in 474.9 sec
[-----------------55%                  ] 1104 of 2000 complete in 475.7 sec
[-----------------55%-                 ] 1106 of 2000 complete in 476.6 sec
[-----------------55%-                 ] 1108 of 2000 complete in 477.5 sec
[-----------------55%-                 ] 1110 of 2000 complete in 478.4 sec
[-----------------55%-                 ] 1112 of 2000 complete in 479.3 sec
[-----------------55%-                 ] 1114 of 2000 complete in 480.3 sec
[-----------------55%-                 ] 1116 of 2000 complete in 481.1 sec
[-----------------55%-                 ] 1118 of 2000 complete in 482.0 sec
[-----------------56%-                 ] 1120 of 2000 complete in 482.8 sec
[-----------------56%-                 ] 1122 of 2000 complete in 483.8 sec
[-----------------56%-                 ] 1124 of 2000 complete in 484.6 sec
[-----------------56%-                 ] 1126 of 2000 complete in 485.5 sec
[-----------------56%-                 ] 1128 of 2000 complete in 486.4 sec
[-----------------56%-                 ] 1130 of 2000 complete in 487.3 sec
[-----------------56%-                 ] 1132 of 2000 complete in 488.1 sec
[-----------------56%-                 ] 1134 of 2000 complete in 489.0 sec
[-----------------56%-                 ] 1136 of 2000 complete in 489.8 sec
[-----------------56%-                 ] 1138 of 2000 complete in 490.7 sec
[-----------------57%-                 ] 1140 of 2000 complete in 491.5 sec
[-----------------57%-                 ] 1142 of 2000 complete in 492.4 sec
[-----------------57%-                 ] 1144 of 2000 complete in 493.2 sec
[-----------------57%-                 ] 1146 of 2000 complete in 494.1 sec
[-----------------57%-                 ] 1148 of 2000 complete in 494.9 sec
[-----------------57%-                 ] 1150 of 2000 complete in 495.8 sec
[-----------------57%-                 ] 1152 of 2000 complete in 496.7 sec
[-----------------57%-                 ] 1154 of 2000 complete in 497.5 sec
[-----------------57%-                 ] 1156 of 2000 complete in 498.4 sec
[-----------------57%--                ] 1158 of 2000 complete in 499.2 sec
[-----------------58%--                ] 1160 of 2000 complete in 500.0 sec
[-----------------58%--                ] 1162 of 2000 complete in 500.9 sec
[-----------------58%--                ] 1164 of 2000 complete in 501.8 sec
[-----------------58%--                ] 1166 of 2000 complete in 502.7 sec
[-----------------58%--                ] 1168 of 2000 complete in 503.6 sec
[-----------------58%--                ] 1170 of 2000 complete in 504.4 sec
[-----------------58%--                ] 1172 of 2000 complete in 505.2 sec
[-----------------58%--                ] 1174 of 2000 complete in 506.0 sec
[-----------------58%--                ] 1176 of 2000 complete in 506.9 sec
[-----------------58%--                ] 1178 of 2000 complete in 507.7 sec
[-----------------59%--                ] 1180 of 2000 complete in 508.5 sec
[-----------------59%--                ] 1182 of 2000 complete in 509.3 sec
[-----------------59%--                ] 1184 of 2000 complete in 510.2 sec
[-----------------59%--                ] 1186 of 2000 complete in 511.0 sec
[-----------------59%--                ] 1188 of 2000 complete in 511.9 sec
[-----------------59%--                ] 1190 of 2000 complete in 512.7 sec
[-----------------59%--                ] 1192 of 2000 complete in 513.6 sec
[-----------------59%--                ] 1194 of 2000 complete in 514.4 sec
[-----------------59%--                ] 1196 of 2000 complete in 515.3 sec
[-----------------59%--                ] 1198 of 2000 complete in 516.2 sec
[-----------------60%--                ] 1200 of 2000 complete in 517.0 sec
[-----------------60%--                ] 1202 of 2000 complete in 517.9 sec
[-----------------60%--                ] 1204 of 2000 complete in 518.7 sec
[-----------------60%--                ] 1206 of 2000 complete in 519.5 sec
[-----------------60%--                ] 1208 of 2000 complete in 520.3 sec
[-----------------60%--                ] 1210 of 2000 complete in 521.2 sec
[-----------------60%---               ] 1212 of 2000 complete in 521.9 sec
[-----------------60%---               ] 1214 of 2000 complete in 522.8 sec
[-----------------60%---               ] 1216 of 2000 complete in 523.6 sec
[-----------------60%---               ] 1218 of 2000 complete in 524.4 sec
[-----------------61%---               ] 1220 of 2000 complete in 525.3 sec
[-----------------61%---               ] 1222 of 2000 complete in 526.1 sec
[-----------------61%---               ] 1224 of 2000 complete in 526.9 sec
[-----------------61%---               ] 1226 of 2000 complete in 527.8 sec
[-----------------61%---               ] 1228 of 2000 complete in 528.6 sec
[-----------------61%---               ] 1230 of 2000 complete in 529.4 sec
[-----------------61%---               ] 1232 of 2000 complete in 530.3 sec
[-----------------61%---               ] 1234 of 2000 complete in 531.1 sec
[-----------------61%---               ] 1236 of 2000 complete in 531.9 sec
[-----------------61%---               ] 1238 of 2000 complete in 532.7 sec
[-----------------62%---               ] 1240 of 2000 complete in 533.6 sec
[-----------------62%---               ] 1242 of 2000 complete in 534.4 sec
[-----------------62%---               ] 1244 of 2000 complete in 535.2 sec
[-----------------62%---               ] 1246 of 2000 complete in 536.1 sec
[-----------------62%---               ] 1248 of 2000 complete in 536.9 sec
[-----------------62%---               ] 1250 of 2000 complete in 537.7 sec
[-----------------62%---               ] 1252 of 2000 complete in 538.6 sec
[-----------------62%---               ] 1254 of 2000 complete in 539.5 sec
[-----------------62%---               ] 1256 of 2000 complete in 540.3 sec
[-----------------62%---               ] 1258 of 2000 complete in 541.2 sec
[-----------------63%---               ] 1260 of 2000 complete in 542.0 sec
[-----------------63%---               ] 1262 of 2000 complete in 542.8 sec
[-----------------63%----              ] 1264 of 2000 complete in 543.7 sec
[-----------------63%----              ] 1266 of 2000 complete in 544.5 sec
[-----------------63%----              ] 1268 of 2000 complete in 545.4 sec
[-----------------63%----              ] 1270 of 2000 complete in 546.3 sec
[-----------------63%----              ] 1272 of 2000 complete in 547.2 sec
[-----------------63%----              ] 1274 of 2000 complete in 548.1 sec
[-----------------63%----              ] 1276 of 2000 complete in 549.0 sec
[-----------------63%----              ] 1278 of 2000 complete in 549.8 sec
[-----------------64%----              ] 1280 of 2000 complete in 550.7 sec
[-----------------64%----              ] 1282 of 2000 complete in 551.6 sec
[-----------------64%----              ] 1284 of 2000 complete in 552.4 sec
[-----------------64%----              ] 1286 of 2000 complete in 553.2 sec
[-----------------64%----              ] 1288 of 2000 complete in 554.1 sec
[-----------------64%----              ] 1290 of 2000 complete in 554.9 sec
[-----------------64%----              ] 1292 of 2000 complete in 555.7 sec
[-----------------64%----              ] 1294 of 2000 complete in 556.6 sec
[-----------------64%----              ] 1296 of 2000 complete in 557.4 sec
[-----------------64%----              ] 1298 of 2000 complete in 558.3 sec
[-----------------54%                  ] 1084 of 2000 complete in 467.8 sec
[-----------------54%                  ] 1086 of 2000 complete in 468.6 sec
[-----------------54%                  ] 1088 of 2000 complete in 469.4 sec
[-----------------54%                  ] 1090 of 2000 complete in 470.3 sec
[-----------------54%                  ] 1092 of 2000 complete in 471.1 sec
[-----------------54%                  ] 1094 of 2000 complete in 472.0 sec
[-----------------54%                  ] 1096 of 2000 complete in 472.8 sec
[-----------------54%                  ] 1098 of 2000 complete in 473.6 sec
[-----------------55%                  ] 1100 of 2000 complete in 474.4 sec
[-----------------55%                  ] 1102 of 2000 complete in 475.2 sec
[-----------------55%                  ] 1104 of 2000 complete in 476.1 sec
[-----------------55%-                 ] 1106 of 2000 complete in 477.0 sec
[-----------------55%-                 ] 1108 of 2000 complete in 477.9 sec
[-----------------55%-                 ] 1110 of 2000 complete in 478.8 sec
[-----------------55%-                 ] 1112 of 2000 complete in 479.7 sec
[-----------------55%-                 ] 1114 of 2000 complete in 480.6 sec
[-----------------55%-                 ] 1116 of 2000 complete in 481.4 sec
[-----------------55%-                 ] 1118 of 2000 complete in 482.3 sec
[-----------------56%-                 ] 1120 of 2000 complete in 483.2 sec
[-----------------56%-                 ] 1122 of 2000 complete in 484.1 sec
[-----------------56%-                 ] 1124 of 2000 complete in 484.9 sec
[-----------------56%-                 ] 1126 of 2000 complete in 485.8 sec
[-----------------56%-                 ] 1128 of 2000 complete in 486.6 sec
[-----------------56%-                 ] 1130 of 2000 complete in 487.5 sec
[-----------------56%-                 ] 1132 of 2000 complete in 488.4 sec
[-----------------56%-                 ] 1134 of 2000 complete in 489.3 sec
[-----------------56%-                 ] 1136 of 2000 complete in 490.2 sec
[-----------------56%-                 ] 1138 of 2000 complete in 491.0 sec
[-----------------57%-                 ] 1140 of 2000 complete in 491.9 sec
[-----------------57%-                 ] 1142 of 2000 complete in 492.7 sec
[-----------------57%-                 ] 1144 of 2000 complete in 493.6 sec
[-----------------57%-                 ] 1146 of 2000 complete in 494.5 sec
[-----------------57%-                 ] 1148 of 2000 complete in 495.4 sec
[-----------------57%-                 ] 1150 of 2000 complete in 496.3 sec
[-----------------57%-                 ] 1152 of 2000 complete in 497.2 sec
[-----------------57%-                 ] 1154 of 2000 complete in 498.1 sec
[-----------------57%-                 ] 1156 of 2000 complete in 498.9 sec
[-----------------57%--                ] 1158 of 2000 complete in 499.7 sec
[-----------------58%--                ] 1160 of 2000 complete in 500.6 sec
[-----------------58%--                ] 1162 of 2000 complete in 501.4 sec
[-----------------58%--                ] 1164 of 2000 complete in 502.3 sec
[-----------------58%--                ] 1166 of 2000 complete in 503.2 sec
[-----------------58%--                ] 1168 of 2000 complete in 504.1 sec
[-----------------58%--                ] 1170 of 2000 complete in 504.9 sec
[-----------------58%--                ] 1172 of 2000 complete in 505.8 sec
[-----------------58%--                ] 1174 of 2000 complete in 506.6 sec
[-----------------58%--                ] 1176 of 2000 complete in 507.5 sec
[-----------------58%--                ] 1178 of 2000 complete in 508.3 sec
[-----------------59%--                ] 1180 of 2000 complete in 509.2 sec
[-----------------59%--                ] 1182 of 2000 complete in 510.1 sec
[-----------------59%--                ] 1184 of 2000 complete in 510.9 sec
[-----------------59%--                ] 1186 of 2000 complete in 511.8 sec
[-----------------59%--                ] 1188 of 2000 complete in 512.6 sec
[-----------------59%--                ] 1190 of 2000 complete in 513.4 sec
[-----------------59%--                ] 1192 of 2000 complete in 514.3 sec
[-----------------59%--                ] 1194 of 2000 complete in 515.1 sec
[-----------------59%--                ] 1196 of 2000 complete in 516.0 sec
[-----------------59%--                ] 1198 of 2000 complete in 516.8 sec
[-----------------60%--                ] 1200 of 2000 complete in 517.6 sec
[-----------------60%--                ] 1202 of 2000 complete in 518.4 sec
[-----------------60%--                ] 1204 of 2000 complete in 519.2 sec
[-----------------60%--                ] 1206 of 2000 complete in 520.1 sec
[-----------------60%--                ] 1208 of 2000 complete in 520.9 sec
[-----------------60%--                ] 1210 of 2000 complete in 521.7 sec
[-----------------60%---               ] 1212 of 2000 complete in 522.6 sec
[-----------------60%---               ] 1214 of 2000 complete in 523.4 sec
[-----------------60%---               ] 1216 of 2000 complete in 524.3 sec
[-----------------60%---               ] 1218 of 2000 complete in 525.1 sec
[-----------------61%---               ] 1220 of 2000 complete in 525.9 sec
[-----------------61%---               ] 1222 of 2000 complete in 526.8 sec
[-----------------61%---               ] 1224 of 2000 complete in 527.6 sec
[-----------------61%---               ] 1226 of 2000 complete in 528.4 sec
[-----------------61%---               ] 1228 of 2000 complete in 529.2 sec
[-----------------61%---               ] 1230 of 2000 complete in 530.0 sec
[-----------------61%---               ] 1232 of 2000 complete in 530.9 sec
[-----------------61%---               ] 1234 of 2000 complete in 531.7 sec
[-----------------61%---               ] 1236 of 2000 complete in 532.5 sec
[-----------------61%---               ] 1238 of 2000 complete in 533.4 sec
[-----------------62%---               ] 1240 of 2000 complete in 534.2 sec
[-----------------62%---               ] 1242 of 2000 complete in 535.0 sec
[-----------------62%---               ] 1244 of 2000 complete in 535.9 sec
[-----------------62%---               ] 1246 of 2000 complete in 536.7 sec
[-----------------62%---               ] 1248 of 2000 complete in 537.5 sec
[-----------------62%---               ] 1250 of 2000 complete in 538.4 sec
[-----------------62%---               ] 1252 of 2000 complete in 539.2 sec
[-----------------62%---               ] 1254 of 2000 complete in 540.1 sec
[-----------------62%---               ] 1256 of 2000 complete in 541.0 sec
[-----------------62%---               ] 1258 of 2000 complete in 541.8 sec
[-----------------63%---               ] 1260 of 2000 complete in 542.6 sec
[-----------------63%---               ] 1262 of 2000 complete in 543.5 sec
[-----------------63%----              ] 1264 of 2000 complete in 544.4 sec
[-----------------63%----              ] 1266 of 2000 complete in 545.3 sec
[-----------------63%----              ] 1268 of 2000 complete in 546.1 sec
[-----------------63%----              ] 1270 of 2000 complete in 546.9 sec
[-----------------63%----              ] 1272 of 2000 complete in 547.8 sec
[-----------------63%----              ] 1274 of 2000 complete in 548.7 sec
[-----------------63%----              ] 1276 of 2000 complete in 549.6 sec
[-----------------63%----              ] 1278 of 2000 complete in 550.5 sec
[-----------------64%----              ] 1280 of 2000 complete in 551.4 sec
[-----------------64%----              ] 1282 of 2000 complete in 552.3 sec
[-----------------64%----              ] 1284 of 2000 complete in 553.1 sec
[-----------------64%----              ] 1286 of 2000 complete in 554.0 sec
[-----------------64%----              ] 1288 of 2000 complete in 554.9 sec
[-----------------64%----              ] 1290 of 2000 complete in 555.7 sec
[-----------------64%----              ] 1292 of 2000 complete in 556.5 sec
[-----------------64%----              ] 1294 of 2000 complete in 557.4 sec
[-----------------64%----              ] 1296 of 2000 complete in 558.3 sec

[-----------------54%                  ] 1089 of 2000 complete in 469.5 sec
[-----------------54%                  ] 1091 of 2000 complete in 470.3 sec
[-----------------54%                  ] 1093 of 2000 complete in 471.2 sec
[-----------------54%                  ] 1095 of 2000 complete in 472.0 sec
[-----------------54%                  ] 1097 of 2000 complete in 472.8 sec
[-----------------54%                  ] 1099 of 2000 complete in 473.7 sec
[-----------------55%                  ] 1101 of 2000 complete in 474.5 sec
[-----------------55%                  ] 1103 of 2000 complete in 475.3 sec
[-----------------55%                  ] 1105 of 2000 complete in 476.2 sec
[-----------------55%-                 ] 1107 of 2000 complete in 477.1 sec
[-----------------55%-                 ] 1109 of 2000 complete in 478.0 sec
[-----------------55%-                 ] 1111 of 2000 complete in 478.9 sec
[-----------------55%-                 ] 1113 of 2000 complete in 479.9 sec
[-----------------55%-                 ] 1115 of 2000 complete in 480.7 sec
[-----------------55%-                 ] 1117 of 2000 complete in 481.6 sec
[-----------------55%-                 ] 1119 of 2000 complete in 482.5 sec
[-----------------56%-                 ] 1121 of 2000 complete in 483.4 sec
[-----------------56%-                 ] 1123 of 2000 complete in 484.2 sec
[-----------------56%-                 ] 1125 of 2000 complete in 485.1 sec
[-----------------56%-                 ] 1127 of 2000 complete in 486.0 sec
[-----------------56%-                 ] 1129 of 2000 complete in 486.8 sec
[-----------------56%-                 ] 1131 of 2000 complete in 487.7 sec
[-----------------56%-                 ] 1133 of 2000 complete in 488.5 sec
[-----------------56%-                 ] 1135 of 2000 complete in 489.4 sec
[-----------------56%-                 ] 1137 of 2000 complete in 490.2 sec
[-----------------56%-                 ] 1139 of 2000 complete in 491.1 sec
[-----------------57%-                 ] 1141 of 2000 complete in 491.9 sec
[-----------------57%-                 ] 1143 of 2000 complete in 492.8 sec
[-----------------57%-                 ] 1145 of 2000 complete in 493.6 sec
[-----------------57%-                 ] 1147 of 2000 complete in 494.5 sec
[-----------------57%-                 ] 1149 of 2000 complete in 495.5 sec
[-----------------57%-                 ] 1151 of 2000 complete in 496.4 sec
[-----------------57%-                 ] 1153 of 2000 complete in 497.3 sec
[-----------------57%-                 ] 1155 of 2000 complete in 498.1 sec
[-----------------57%-                 ] 1157 of 2000 complete in 499.0 sec
[-----------------57%--                ] 1159 of 2000 complete in 499.8 sec
[-----------------58%--                ] 1161 of 2000 complete in 500.6 sec
[-----------------58%--                ] 1163 of 2000 complete in 501.5 sec
[-----------------58%--                ] 1165 of 2000 complete in 502.4 sec
[-----------------58%--                ] 1167 of 2000 complete in 503.3 sec
[-----------------58%--                ] 1169 of 2000 complete in 504.2 sec
[-----------------58%--                ] 1171 of 2000 complete in 505.0 sec
[-----------------58%--                ] 1173 of 2000 complete in 505.8 sec
[-----------------58%--                ] 1175 of 2000 complete in 506.7 sec
[-----------------58%--                ] 1177 of 2000 complete in 507.5 sec
[-----------------58%--                ] 1179 of 2000 complete in 508.3 sec
[-----------------59%--                ] 1181 of 2000 complete in 509.1 sec
[-----------------59%--                ] 1183 of 2000 complete in 510.0 sec
[-----------------59%--                ] 1185 of 2000 complete in 510.8 sec
[-----------------59%--                ] 1187 of 2000 complete in 511.7 sec
[-----------------59%--                ] 1189 of 2000 complete in 512.5 sec
[-----------------59%--                ] 1191 of 2000 complete in 513.4 sec
[-----------------59%--                ] 1193 of 2000 complete in 514.2 sec
[-----------------59%--                ] 1195 of 2000 complete in 515.0 sec
[-----------------59%--                ] 1197 of 2000 complete in 515.9 sec
[-----------------59%--                ] 1199 of 2000 complete in 516.7 sec
[-----------------60%--                ] 1201 of 2000 complete in 517.5 sec
[-----------------60%--                ] 1203 of 2000 complete in 518.3 sec
[-----------------60%--                ] 1205 of 2000 complete in 519.2 sec
[-----------------60%--                ] 1207 of 2000 complete in 520.0 sec
[-----------------60%--                ] 1209 of 2000 complete in 520.8 sec
[-----------------60%---               ] 1211 of 2000 complete in 521.6 sec
[-----------------60%---               ] 1213 of 2000 complete in 522.5 sec
[-----------------60%---               ] 1215 of 2000 complete in 523.3 sec
[-----------------60%---               ] 1217 of 2000 complete in 524.1 sec
[-----------------60%---               ] 1219 of 2000 complete in 525.0 sec
[-----------------61%---               ] 1221 of 2000 complete in 525.8 sec
[-----------------61%---               ] 1223 of 2000 complete in 526.7 sec
[-----------------61%---               ] 1225 of 2000 complete in 527.5 sec
[-----------------61%---               ] 1227 of 2000 complete in 528.4 sec
[-----------------61%---               ] 1229 of 2000 complete in 529.2 sec
[-----------------61%---               ] 1231 of 2000 complete in 530.0 sec
[-----------------61%---               ] 1233 of 2000 complete in 530.9 sec
[-----------------61%---               ] 1235 of 2000 complete in 531.7 sec
[-----------------61%---               ] 1237 of 2000 complete in 532.5 sec
[-----------------61%---               ] 1239 of 2000 complete in 533.3 sec
[-----------------62%---               ] 1241 of 2000 complete in 534.2 sec
[-----------------62%---               ] 1243 of 2000 complete in 535.0 sec
[-----------------62%---               ] 1245 of 2000 complete in 535.8 sec
[-----------------62%---               ] 1247 of 2000 complete in 536.7 sec
[-----------------62%---               ] 1249 of 2000 complete in 537.6 sec
[-----------------62%---               ] 1251 of 2000 complete in 538.4 sec
[-----------------62%---               ] 1253 of 2000 complete in 539.2 sec
[-----------------62%---               ] 1255 of 2000 complete in 540.1 sec
[-----------------62%---               ] 1257 of 2000 complete in 540.9 sec
[-----------------62%---               ] 1259 of 2000 complete in 541.8 sec
[-----------------63%---               ] 1261 of 2000 complete in 542.6 sec
[-----------------63%---               ] 1263 of 2000 complete in 543.4 sec
[-----------------63%----              ] 1265 of 2000 complete in 544.3 sec
[-----------------63%----              ] 1267 of 2000 complete in 545.1 sec
[-----------------63%----              ] 1269 of 2000 complete in 546.0 sec
[-----------------63%----              ] 1271 of 2000 complete in 546.9 sec
[-----------------63%----              ] 1273 of 2000 complete in 547.8 sec
[-----------------63%----              ] 1275 of 2000 complete in 548.7 sec
[-----------------63%----              ] 1277 of 2000 complete in 549.6 sec
[-----------------63%----              ] 1279 of 2000 complete in 550.4 sec
[-----------------64%----              ] 1281 of 2000 complete in 551.3 sec
[-----------------64%----              ] 1283 of 2000 complete in 552.1 sec
[-----------------64%----              ] 1285 of 2000 complete in 552.9 sec
[-----------------64%----              ] 1287 of 2000 complete in 553.8 sec
[-----------------64%----              ] 1289 of 2000 complete in 554.6 sec
[-----------------64%----              ] 1291 of 2000 complete in 555.5 sec
[-----------------64%----              ] 1293 of 2000 complete in 556.3 sec
[-----------------64%----              ] 1295 of 2000 complete in 557.2 sec
[-----------------64%----              ] 1297 of 2000 complete in 558.1 sec
[-----------------64%----              ] 1299 of 2000 complete in 558.9 sec
[-----------------65%----              ] 1301 of 2000 complete in 559.8 sec
[-----------------65%----              ] 1300 of 2000 complete in 554.5 sec
[-----------------65%----              ] 1302 of 2000 complete in 555.3 sec
[-----------------65%----              ] 1304 of 2000 complete in 556.1 sec
[-----------------65%----              ] 1306 of 2000 complete in 556.9 sec
[-----------------65%----              ] 1308 of 2000 complete in 557.8 sec
[-----------------65%----              ] 1310 of 2000 complete in 558.6 sec
[-----------------65%----              ] 1312 of 2000 complete in 559.5 sec
[-----------------65%----              ] 1314 of 2000 complete in 560.3 sec
[-----------------65%-----             ] 1316 of 2000 complete in 561.2 sec
[-----------------65%-----             ] 1318 of 2000 complete in 562.0 sec
[-----------------66%-----             ] 1320 of 2000 complete in 562.9 sec
[-----------------66%-----             ] 1322 of 2000 complete in 563.8 sec
[-----------------66%-----             ] 1324 of 2000 complete in 564.7 sec
[-----------------66%-----             ] 1326 of 2000 complete in 565.5 sec
[-----------------66%-----             ] 1328 of 2000 complete in 566.4 sec
[-----------------66%-----             ] 1330 of 2000 complete in 567.2 sec
[-----------------66%-----             ] 1332 of 2000 complete in 568.1 sec
[-----------------66%-----             ] 1334 of 2000 complete in 568.9 sec
[-----------------66%-----             ] 1336 of 2000 complete in 569.7 sec
[-----------------66%-----             ] 1338 of 2000 complete in 570.6 sec
[-----------------67%-----             ] 1340 of 2000 complete in 571.6 sec
[-----------------67%-----             ] 1342 of 2000 complete in 572.5 sec
[-----------------67%-----             ] 1344 of 2000 complete in 573.5 sec
[-----------------67%-----             ] 1345 of 2000 complete in 574.0 sec
[-----------------67%-----             ] 1347 of 2000 complete in 574.9 sec
[-----------------67%-----             ] 1349 of 2000 complete in 575.8 sec
[-----------------67%-----             ] 1351 of 2000 complete in 576.6 sec
[-----------------67%-----             ] 1353 of 2000 complete in 577.5 sec
[-----------------67%-----             ] 1355 of 2000 complete in 578.5 sec
[-----------------67%-----             ] 1357 of 2000 complete in 579.3 sec
[-----------------67%-----             ] 1359 of 2000 complete in 580.1 sec
[-----------------68%-----             ] 1361 of 2000 complete in 580.9 sec
[-----------------68%-----             ] 1363 of 2000 complete in 581.8 sec
[-----------------68%-----             ] 1365 of 2000 complete in 582.6 sec
[-----------------68%-----             ] 1367 of 2000 complete in 583.5 sec
[-----------------68%------            ] 1369 of 2000 complete in 584.3 sec
[-----------------68%------            ] 1371 of 2000 complete in 585.1 sec
[-----------------68%------            ] 1373 of 2000 complete in 586.0 sec
[-----------------68%------            ] 1375 of 2000 complete in 586.8 sec
[-----------------68%------            ] 1377 of 2000 complete in 587.7 sec
[-----------------68%------            ] 1379 of 2000 complete in 588.7 sec
[-----------------69%------            ] 1381 of 2000 complete in 589.6 sec
[-----------------69%------            ] 1383 of 2000 complete in 590.5 sec
[-----------------69%------            ] 1385 of 2000 complete in 591.4 sec
[-----------------69%------            ] 1387 of 2000 complete in 592.3 sec
[-----------------69%------            ] 1389 of 2000 complete in 593.2 sec
[-----------------69%------            ] 1391 of 2000 complete in 594.1 sec
[-----------------69%------            ] 1392 of 2000 complete in 594.7 sec
[-----------------69%------            ] 1394 of 2000 complete in 595.6 sec
[-----------------69%------            ] 1396 of 2000 complete in 596.4 sec
[-----------------69%------            ] 1398 of 2000 complete in 597.3 sec
[-----------------70%------            ] 1400 of 2000 complete in 598.1 sec
[-----------------70%------            ] 1401 of 2000 complete in 598.7 sec
[-----------------70%------            ] 1403 of 2000 complete in 599.6 sec
[-----------------70%------            ] 1405 of 2000 complete in 600.7 sec
[-----------------70%------            ] 1406 of 2000 complete in 601.3 sec
[-----------------70%------            ] 1407 of 2000 complete in 601.9 sec
[-----------------70%------            ] 1409 of 2000 complete in 602.8 sec
[-----------------70%------            ] 1411 of 2000 complete in 603.7 sec
[-----------------70%------            ] 1413 of 2000 complete in 604.5 sec
[-----------------70%------            ] 1415 of 2000 complete in 605.4 sec
[-----------------70%------            ] 1417 of 2000 complete in 606.3 sec
[-----------------70%------            ] 1418 of 2000 complete in 606.8 sec
[-----------------71%------            ] 1420 of 2000 complete in 607.7 sec
[-----------------71%-------           ] 1422 of 2000 complete in 608.6 sec
[-----------------71%-------           ] 1424 of 2000 complete in 609.4 sec
[-----------------71%-------           ] 1426 of 2000 complete in 610.3 sec
[-----------------71%-------           ] 1428 of 2000 complete in 611.1 sec
[-----------------71%-------           ] 1430 of 2000 complete in 611.9 sec
[-----------------71%-------           ] 1432 of 2000 complete in 612.8 sec
[-----------------71%-------           ] 1434 of 2000 complete in 613.6 sec
[-----------------71%-------           ] 1436 of 2000 complete in 614.4 sec
[-----------------71%-------           ] 1438 of 2000 complete in 615.3 sec
[-----------------72%-------           ] 1440 of 2000 complete in 616.1 sec
[-----------------72%-------           ] 1442 of 2000 complete in 616.9 sec
[-----------------72%-------           ] 1444 of 2000 complete in 617.8 sec
[-----------------72%-------           ] 1446 of 2000 complete in 618.6 sec
[-----------------72%-------           ] 1448 of 2000 complete in 619.4 sec
[-----------------72%-------           ] 1450 of 2000 complete in 620.2 sec
[-----------------72%-------           ] 1452 of 2000 complete in 621.1 sec
[-----------------72%-------           ] 1454 of 2000 complete in 621.9 sec
[-----------------72%-------           ] 1456 of 2000 complete in 622.8 sec
[-----------------72%-------           ] 1458 of 2000 complete in 623.6 sec
[-----------------73%-------           ] 1460 of 2000 complete in 624.4 sec
[-----------------73%-------           ] 1462 of 2000 complete in 625.3 sec
[-----------------73%-------           ] 1464 of 2000 complete in 626.1 sec
[-----------------73%-------           ] 1466 of 2000 complete in 627.0 sec
[-----------------73%-------           ] 1468 of 2000 complete in 627.8 sec
[-----------------73%-------           ] 1470 of 2000 complete in 628.6 sec
[-----------------73%-------           ] 1472 of 2000 complete in 629.4 sec
[-----------------73%--------          ] 1474 of 2000 complete in 630.3 sec
[-----------------73%--------          ] 1476 of 2000 complete in 631.1 sec
[-----------------73%--------          ] 1478 of 2000 complete in 632.0 sec
[-----------------74%--------          ] 1480 of 2000 complete in 632.8 sec
[-----------------74%--------          ] 1482 of 2000 complete in 633.6 sec
[-----------------74%--------          ] 1484 of 2000 complete in 634.4 sec
[-----------------74%--------          ] 1486 of 2000 complete in 635.3 sec
[-----------------74%--------          ] 1488 of 2000 complete in 636.2 sec
[-----------------74%--------          ] 1490 of 2000 complete in 637.0 sec
[-----------------74%--------          ] 1492 of 2000 complete in 637.9 sec
[-----------------74%--------          ] 1494 of 2000 complete in 638.7 sec
[-----------------74%--------          ] 1496 of 2000 complete in 639.6 sec
[-----------------74%--------          ] 1498 of 2000 complete in 640.4 sec
[-----------------75%--------          ] 1500 of 2000 complete in 641.3 sec
[-----------------75%--------          ] 1502 of 2000 complete in 642.1 sec
[-----------------75%--------          ] 1504 of 2000 complete in 642.9 sec
[-----------------75%--------          ] 1506 of 2000 complete in 643.8 sec

[-----------------64%----              ] 1298 of 2000 complete in 559.1 sec
[-----------------65%----              ] 1300 of 2000 complete in 560.0 sec
[-----------------65%----              ] 1302 of 2000 complete in 560.8 sec
[-----------------65%----              ] 1304 of 2000 complete in 561.7 sec
[-----------------65%----              ] 1306 of 2000 complete in 562.5 sec
[-----------------65%----              ] 1308 of 2000 complete in 563.4 sec
[-----------------65%----              ] 1310 of 2000 complete in 564.3 sec
[-----------------65%----              ] 1312 of 2000 complete in 565.1 sec
[-----------------65%----              ] 1314 of 2000 complete in 566.0 sec
[-----------------65%-----             ] 1316 of 2000 complete in 566.8 sec
[-----------------65%-----             ] 1318 of 2000 complete in 567.6 sec
[-----------------66%-----             ] 1320 of 2000 complete in 568.5 sec
[-----------------66%-----             ] 1322 of 2000 complete in 569.3 sec
[-----------------66%-----             ] 1324 of 2000 complete in 570.2 sec
[-----------------66%-----             ] 1326 of 2000 complete in 571.2 sec
[-----------------66%-----             ] 1327 of 2000 complete in 571.7 sec
[-----------------66%-----             ] 1329 of 2000 complete in 572.6 sec
[-----------------66%-----             ] 1330 of 2000 complete in 573.2 sec
[-----------------66%-----             ] 1331 of 2000 complete in 573.7 sec
[-----------------66%-----             ] 1332 of 2000 complete in 574.2 sec
[-----------------66%-----             ] 1334 of 2000 complete in 575.1 sec
[-----------------66%-----             ] 1336 of 2000 complete in 575.9 sec
[-----------------66%-----             ] 1338 of 2000 complete in 576.8 sec
[-----------------67%-----             ] 1340 of 2000 complete in 577.7 sec
[-----------------67%-----             ] 1342 of 2000 complete in 578.6 sec
[-----------------67%-----             ] 1344 of 2000 complete in 579.4 sec
[-----------------67%-----             ] 1346 of 2000 complete in 580.3 sec
[-----------------67%-----             ] 1348 of 2000 complete in 581.1 sec
[-----------------67%-----             ] 1350 of 2000 complete in 582.0 sec
[-----------------67%-----             ] 1352 of 2000 complete in 582.8 sec
[-----------------67%-----             ] 1354 of 2000 complete in 583.6 sec
[-----------------67%-----             ] 1356 of 2000 complete in 584.5 sec
[-----------------67%-----             ] 1358 of 2000 complete in 585.3 sec
[-----------------68%-----             ] 1360 of 2000 complete in 586.2 sec
[-----------------68%-----             ] 1362 of 2000 complete in 587.1 sec
[-----------------68%-----             ] 1364 of 2000 complete in 588.0 sec
[-----------------68%-----             ] 1365 of 2000 complete in 588.5 sec
[-----------------68%-----             ] 1367 of 2000 complete in 589.4 sec
[-----------------68%------            ] 1369 of 2000 complete in 590.3 sec
[-----------------68%------            ] 1371 of 2000 complete in 591.2 sec
[-----------------68%------            ] 1373 of 2000 complete in 592.1 sec
[-----------------68%------            ] 1375 of 2000 complete in 593.0 sec
[-----------------68%------            ] 1377 of 2000 complete in 594.0 sec
[-----------------68%------            ] 1378 of 2000 complete in 594.5 sec
[-----------------69%------            ] 1380 of 2000 complete in 595.4 sec
[-----------------69%------            ] 1382 of 2000 complete in 596.3 sec
[-----------------69%------            ] 1384 of 2000 complete in 597.2 sec
[-----------------69%------            ] 1386 of 2000 complete in 598.1 sec
[-----------------69%------            ] 1387 of 2000 complete in 598.7 sec
[-----------------69%------            ] 1389 of 2000 complete in 599.6 sec
[-----------------69%------            ] 1391 of 2000 complete in 600.7 sec
[-----------------69%------            ] 1392 of 2000 complete in 601.3 sec
[-----------------69%------            ] 1393 of 2000 complete in 601.9 sec
[-----------------69%------            ] 1395 of 2000 complete in 602.8 sec
[-----------------69%------            ] 1397 of 2000 complete in 603.7 sec
[-----------------69%------            ] 1399 of 2000 complete in 604.6 sec
[-----------------70%------            ] 1401 of 2000 complete in 605.5 sec
[-----------------70%------            ] 1403 of 2000 complete in 606.4 sec
[-----------------70%------            ] 1405 of 2000 complete in 607.4 sec
[-----------------70%------            ] 1407 of 2000 complete in 608.3 sec
[-----------------70%------            ] 1409 of 2000 complete in 609.1 sec
[-----------------70%------            ] 1411 of 2000 complete in 610.0 sec
[-----------------70%------            ] 1413 of 2000 complete in 610.8 sec
[-----------------70%------            ] 1415 of 2000 complete in 611.7 sec
[-----------------70%------            ] 1417 of 2000 complete in 612.5 sec
[-----------------70%------            ] 1419 of 2000 complete in 613.4 sec
[-----------------71%------            ] 1421 of 2000 complete in 614.2 sec
[-----------------71%-------           ] 1423 of 2000 complete in 615.0 sec
[-----------------71%-------           ] 1425 of 2000 complete in 615.9 sec
[-----------------71%-------           ] 1427 of 2000 complete in 616.7 sec
[-----------------71%-------           ] 1429 of 2000 complete in 617.5 sec
[-----------------71%-------           ] 1431 of 2000 complete in 618.4 sec
[-----------------71%-------           ] 1433 of 2000 complete in 619.2 sec
[-----------------71%-------           ] 1435 of 2000 complete in 620.1 sec
[-----------------71%-------           ] 1437 of 2000 complete in 620.9 sec
[-----------------71%-------           ] 1439 of 2000 complete in 621.7 sec
[-----------------72%-------           ] 1441 of 2000 complete in 622.6 sec
[-----------------72%-------           ] 1443 of 2000 complete in 623.4 sec
[-----------------72%-------           ] 1445 of 2000 complete in 624.2 sec
[-----------------72%-------           ] 1447 of 2000 complete in 625.1 sec
[-----------------72%-------           ] 1449 of 2000 complete in 625.9 sec
[-----------------72%-------           ] 1451 of 2000 complete in 626.8 sec
[-----------------72%-------           ] 1453 of 2000 complete in 627.6 sec
[-----------------72%-------           ] 1455 of 2000 complete in 628.5 sec
[-----------------72%-------           ] 1457 of 2000 complete in 629.3 sec
[-----------------72%-------           ] 1459 of 2000 complete in 630.1 sec
[-----------------73%-------           ] 1461 of 2000 complete in 631.0 sec
[-----------------73%-------           ] 1463 of 2000 complete in 631.8 sec
[-----------------73%-------           ] 1465 of 2000 complete in 632.6 sec
[-----------------73%-------           ] 1467 of 2000 complete in 633.5 sec
[-----------------73%-------           ] 1469 of 2000 complete in 634.4 sec
[-----------------73%-------           ] 1471 of 2000 complete in 635.3 sec
[-----------------73%-------           ] 1473 of 2000 complete in 636.1 sec
[-----------------73%--------          ] 1475 of 2000 complete in 637.0 sec
[-----------------73%--------          ] 1477 of 2000 complete in 637.8 sec
[-----------------73%--------          ] 1479 of 2000 complete in 638.7 sec
[-----------------74%--------          ] 1481 of 2000 complete in 639.5 sec
[-----------------74%--------          ] 1483 of 2000 complete in 640.4 sec
[-----------------74%--------          ] 1485 of 2000 complete in 641.2 sec
[-----------------74%--------          ] 1487 of 2000 complete in 642.1 sec
[-----------------74%--------          ] 1489 of 2000 complete in 642.9 sec
[-----------------74%--------          ] 1491 of 2000 complete in 643.7 sec
[-----------------74%--------          ] 1493 of 2000 complete in 644.6 sec
[-----------------74%--------          ] 1495 of 2000 complete in 645.5 sec
[-----------------74%--------          ] 1497 of 2000 complete in 646.4 sec
[-----------------74%--------          ] 1499 of 2000 complete in 647.2 sec
[-----------------75%--------          ] 1501 of 2000 complete in 648.0 sec
[-----------------65%----              ] 1300 of 2000 complete in 559.1 sec
[-----------------65%----              ] 1302 of 2000 complete in 560.0 sec
[-----------------65%----              ] 1304 of 2000 complete in 560.9 sec
[-----------------65%----              ] 1306 of 2000 complete in 561.8 sec
[-----------------65%----              ] 1308 of 2000 complete in 562.6 sec
[-----------------65%----              ] 1310 of 2000 complete in 563.5 sec
[-----------------65%----              ] 1312 of 2000 complete in 564.3 sec
[-----------------65%----              ] 1314 of 2000 complete in 565.1 sec
[-----------------65%-----             ] 1316 of 2000 complete in 566.0 sec
[-----------------65%-----             ] 1318 of 2000 complete in 566.8 sec
[-----------------66%-----             ] 1320 of 2000 complete in 567.6 sec
[-----------------66%-----             ] 1322 of 2000 complete in 568.5 sec
[-----------------66%-----             ] 1324 of 2000 complete in 569.3 sec
[-----------------66%-----             ] 1326 of 2000 complete in 570.1 sec
[-----------------66%-----             ] 1328 of 2000 complete in 571.0 sec
[-----------------66%-----             ] 1329 of 2000 complete in 571.6 sec
[-----------------66%-----             ] 1330 of 2000 complete in 572.1 sec
[-----------------66%-----             ] 1332 of 2000 complete in 573.1 sec
[-----------------66%-----             ] 1334 of 2000 complete in 574.0 sec
[-----------------66%-----             ] 1336 of 2000 complete in 574.9 sec
[-----------------66%-----             ] 1338 of 2000 complete in 575.8 sec
[-----------------67%-----             ] 1340 of 2000 complete in 576.7 sec
[-----------------67%-----             ] 1342 of 2000 complete in 577.6 sec
[-----------------67%-----             ] 1344 of 2000 complete in 578.5 sec
[-----------------67%-----             ] 1346 of 2000 complete in 579.4 sec
[-----------------67%-----             ] 1348 of 2000 complete in 580.2 sec
[-----------------67%-----             ] 1350 of 2000 complete in 581.0 sec
[-----------------67%-----             ] 1352 of 2000 complete in 581.9 sec
[-----------------67%-----             ] 1354 of 2000 complete in 582.8 sec
[-----------------67%-----             ] 1356 of 2000 complete in 583.6 sec
[-----------------67%-----             ] 1358 of 2000 complete in 584.5 sec
[-----------------68%-----             ] 1360 of 2000 complete in 585.3 sec
[-----------------68%-----             ] 1362 of 2000 complete in 586.2 sec
[-----------------68%-----             ] 1364 of 2000 complete in 587.0 sec
[-----------------68%-----             ] 1366 of 2000 complete in 587.9 sec
[-----------------68%-----             ] 1368 of 2000 complete in 588.9 sec
[-----------------68%------            ] 1370 of 2000 complete in 589.8 sec
[-----------------68%------            ] 1372 of 2000 complete in 590.7 sec
[-----------------68%------            ] 1374 of 2000 complete in 591.6 sec
[-----------------68%------            ] 1376 of 2000 complete in 592.5 sec
[-----------------68%------            ] 1378 of 2000 complete in 593.4 sec
[-----------------69%------            ] 1380 of 2000 complete in 594.3 sec
[-----------------69%------            ] 1381 of 2000 complete in 594.9 sec
[-----------------69%------            ] 1383 of 2000 complete in 595.7 sec
[-----------------69%------            ] 1385 of 2000 complete in 596.5 sec
[-----------------69%------            ] 1387 of 2000 complete in 597.4 sec
[-----------------69%------            ] 1389 of 2000 complete in 598.3 sec
[-----------------69%------            ] 1390 of 2000 complete in 598.9 sec
[-----------------69%------            ] 1392 of 2000 complete in 599.8 sec
[-----------------69%------            ] 1394 of 2000 complete in 600.8 sec
[-----------------69%------            ] 1395 of 2000 complete in 601.4 sec
[-----------------69%------            ] 1396 of 2000 complete in 602.0 sec
[-----------------69%------            ] 1398 of 2000 complete in 603.0 sec
[-----------------70%------            ] 1400 of 2000 complete in 603.9 sec
[-----------------70%------            ] 1402 of 2000 complete in 604.8 sec
[-----------------70%------            ] 1404 of 2000 complete in 605.7 sec
[-----------------70%------            ] 1406 of 2000 complete in 606.6 sec
[-----------------70%------            ] 1408 of 2000 complete in 607.5 sec
[-----------------70%------            ] 1410 of 2000 complete in 608.4 sec
[-----------------70%------            ] 1412 of 2000 complete in 609.3 sec
[-----------------70%------            ] 1414 of 2000 complete in 610.1 sec
[-----------------70%------            ] 1416 of 2000 complete in 610.9 sec
[-----------------70%------            ] 1418 of 2000 complete in 611.8 sec
[-----------------71%------            ] 1420 of 2000 complete in 612.6 sec
[-----------------71%-------           ] 1422 of 2000 complete in 613.5 sec
[-----------------71%-------           ] 1424 of 2000 complete in 614.3 sec
[-----------------71%-------           ] 1426 of 2000 complete in 615.1 sec
[-----------------71%-------           ] 1428 of 2000 complete in 616.0 sec
[-----------------71%-------           ] 1430 of 2000 complete in 616.8 sec
[-----------------71%-------           ] 1432 of 2000 complete in 617.6 sec
[-----------------71%-------           ] 1434 of 2000 complete in 618.4 sec
[-----------------71%-------           ] 1436 of 2000 complete in 619.3 sec
[-----------------71%-------           ] 1438 of 2000 complete in 620.1 sec
[-----------------72%-------           ] 1440 of 2000 complete in 621.0 sec
[-----------------72%-------           ] 1442 of 2000 complete in 621.8 sec
[-----------------72%-------           ] 1444 of 2000 complete in 622.6 sec
[-----------------72%-------           ] 1446 of 2000 complete in 623.4 sec
[-----------------72%-------           ] 1448 of 2000 complete in 624.3 sec
[-----------------72%-------           ] 1450 of 2000 complete in 625.2 sec
[-----------------72%-------           ] 1452 of 2000 complete in 626.0 sec
[-----------------72%-------           ] 1454 of 2000 complete in 626.9 sec
[-----------------72%-------           ] 1456 of 2000 complete in 627.7 sec
[-----------------72%-------           ] 1458 of 2000 complete in 628.5 sec
[-----------------73%-------           ] 1460 of 2000 complete in 629.3 sec
[-----------------73%-------           ] 1462 of 2000 complete in 630.2 sec
[-----------------73%-------           ] 1464 of 2000 complete in 631.0 sec
[-----------------73%-------           ] 1466 of 2000 complete in 631.8 sec
[-----------------73%-------           ] 1468 of 2000 complete in 632.7 sec
[-----------------73%-------           ] 1470 of 2000 complete in 633.5 sec
[-----------------73%-------           ] 1472 of 2000 complete in 634.4 sec
[-----------------73%--------          ] 1474 of 2000 complete in 635.2 sec
[-----------------73%--------          ] 1476 of 2000 complete in 636.1 sec
[-----------------73%--------          ] 1478 of 2000 complete in 636.9 sec
[-----------------74%--------          ] 1480 of 2000 complete in 637.7 sec
[-----------------74%--------          ] 1482 of 2000 complete in 638.6 sec
[-----------------74%--------          ] 1484 of 2000 complete in 639.4 sec
[-----------------74%--------          ] 1486 of 2000 complete in 640.3 sec
[-----------------74%--------          ] 1488 of 2000 complete in 641.2 sec
[-----------------74%--------          ] 1490 of 2000 complete in 642.0 sec
[-----------------74%--------          ] 1492 of 2000 complete in 642.9 sec
[-----------------74%--------          ] 1494 of 2000 complete in 643.8 sec
[-----------------74%--------          ] 1496 of 2000 complete in 644.6 sec
[-----------------74%--------          ] 1498 of 2000 complete in 645.5 sec
[-----------------75%--------          ] 1500 of 2000 complete in 646.4 sec
[-----------------75%--------          ] 1502 of 2000 complete in 647.2 sec
[-----------------75%--------          ] 1504 of 2000 complete in 648.1 sec
[-----------------75%--------          ] 1506 of 2000 complete in 648.9 sec

[-----------------65%----              ] 1303 of 2000 complete in 560.6 sec
[-----------------65%----              ] 1305 of 2000 complete in 561.6 sec
[-----------------65%----              ] 1307 of 2000 complete in 562.4 sec
[-----------------65%----              ] 1309 of 2000 complete in 563.2 sec
[-----------------65%----              ] 1311 of 2000 complete in 564.1 sec
[-----------------65%----              ] 1313 of 2000 complete in 565.0 sec
[-----------------65%----              ] 1315 of 2000 complete in 565.8 sec
[-----------------65%-----             ] 1317 of 2000 complete in 566.6 sec
[-----------------65%-----             ] 1319 of 2000 complete in 567.5 sec
[-----------------66%-----             ] 1321 of 2000 complete in 568.4 sec
[-----------------66%-----             ] 1323 of 2000 complete in 569.2 sec
[-----------------66%-----             ] 1325 of 2000 complete in 570.0 sec
[-----------------66%-----             ] 1327 of 2000 complete in 570.9 sec
[-----------------66%-----             ] 1328 of 2000 complete in 571.5 sec
[-----------------66%-----             ] 1329 of 2000 complete in 572.0 sec
[-----------------66%-----             ] 1331 of 2000 complete in 573.0 sec
[-----------------66%-----             ] 1333 of 2000 complete in 574.0 sec
[-----------------66%-----             ] 1335 of 2000 complete in 574.9 sec
[-----------------66%-----             ] 1337 of 2000 complete in 575.7 sec
[-----------------66%-----             ] 1339 of 2000 complete in 576.5 sec
[-----------------67%-----             ] 1341 of 2000 complete in 577.4 sec
[-----------------67%-----             ] 1343 of 2000 complete in 578.4 sec
[-----------------67%-----             ] 1345 of 2000 complete in 579.2 sec
[-----------------67%-----             ] 1347 of 2000 complete in 580.0 sec
[-----------------67%-----             ] 1349 of 2000 complete in 580.9 sec
[-----------------67%-----             ] 1351 of 2000 complete in 581.8 sec
[-----------------67%-----             ] 1353 of 2000 complete in 582.6 sec
[-----------------67%-----             ] 1355 of 2000 complete in 583.4 sec
[-----------------67%-----             ] 1357 of 2000 complete in 584.3 sec
[-----------------67%-----             ] 1359 of 2000 complete in 585.1 sec
[-----------------68%-----             ] 1361 of 2000 complete in 585.9 sec
[-----------------68%-----             ] 1363 of 2000 complete in 586.8 sec
[-----------------68%-----             ] 1365 of 2000 complete in 587.7 sec
[-----------------68%-----             ] 1367 of 2000 complete in 588.6 sec
[-----------------68%------            ] 1369 of 2000 complete in 589.5 sec
[-----------------68%------            ] 1371 of 2000 complete in 590.5 sec
[-----------------68%------            ] 1373 of 2000 complete in 591.4 sec
[-----------------68%------            ] 1375 of 2000 complete in 592.3 sec
[-----------------68%------            ] 1377 of 2000 complete in 593.2 sec
[-----------------68%------            ] 1379 of 2000 complete in 594.1 sec
[-----------------69%------            ] 1380 of 2000 complete in 594.7 sec
[-----------------69%------            ] 1382 of 2000 complete in 595.6 sec
[-----------------69%------            ] 1384 of 2000 complete in 596.4 sec
[-----------------69%------            ] 1386 of 2000 complete in 597.3 sec
[-----------------69%------            ] 1388 of 2000 complete in 598.2 sec
[-----------------69%------            ] 1389 of 2000 complete in 598.7 sec
[-----------------69%------            ] 1391 of 2000 complete in 599.6 sec
[-----------------69%------            ] 1393 of 2000 complete in 600.7 sec
[-----------------69%------            ] 1394 of 2000 complete in 601.2 sec
[-----------------69%------            ] 1395 of 2000 complete in 601.8 sec
[-----------------69%------            ] 1397 of 2000 complete in 602.8 sec
[-----------------69%------            ] 1399 of 2000 complete in 603.7 sec
[-----------------70%------            ] 1401 of 2000 complete in 604.6 sec
[-----------------70%------            ] 1403 of 2000 complete in 605.5 sec
[-----------------70%------            ] 1405 of 2000 complete in 606.5 sec
[-----------------70%------            ] 1407 of 2000 complete in 607.4 sec
[-----------------70%------            ] 1409 of 2000 complete in 608.3 sec
[-----------------70%------            ] 1411 of 2000 complete in 609.2 sec
[-----------------70%------            ] 1413 of 2000 complete in 610.0 sec
[-----------------70%------            ] 1415 of 2000 complete in 610.9 sec
[-----------------70%------            ] 1417 of 2000 complete in 611.7 sec
[-----------------70%------            ] 1419 of 2000 complete in 612.5 sec
[-----------------71%------            ] 1421 of 2000 complete in 613.3 sec
[-----------------71%-------           ] 1423 of 2000 complete in 614.1 sec
[-----------------71%-------           ] 1425 of 2000 complete in 615.0 sec
[-----------------71%-------           ] 1427 of 2000 complete in 615.9 sec
[-----------------71%-------           ] 1429 of 2000 complete in 616.7 sec
[-----------------71%-------           ] 1431 of 2000 complete in 617.5 sec
[-----------------71%-------           ] 1433 of 2000 complete in 618.4 sec
[-----------------71%-------           ] 1435 of 2000 complete in 619.2 sec
[-----------------71%-------           ] 1437 of 2000 complete in 620.0 sec
[-----------------71%-------           ] 1439 of 2000 complete in 620.8 sec
[-----------------72%-------           ] 1441 of 2000 complete in 621.7 sec
[-----------------72%-------           ] 1443 of 2000 complete in 622.5 sec
[-----------------72%-------           ] 1445 of 2000 complete in 623.3 sec
[-----------------72%-------           ] 1447 of 2000 complete in 624.2 sec
[-----------------72%-------           ] 1449 of 2000 complete in 625.0 sec
[-----------------72%-------           ] 1451 of 2000 complete in 625.9 sec
[-----------------72%-------           ] 1453 of 2000 complete in 626.7 sec
[-----------------72%-------           ] 1455 of 2000 complete in 627.5 sec
[-----------------72%-------           ] 1457 of 2000 complete in 628.4 sec
[-----------------72%-------           ] 1459 of 2000 complete in 629.2 sec
[-----------------73%-------           ] 1461 of 2000 complete in 630.0 sec
[-----------------73%-------           ] 1463 of 2000 complete in 630.9 sec
[-----------------73%-------           ] 1465 of 2000 complete in 631.7 sec
[-----------------73%-------           ] 1467 of 2000 complete in 632.5 sec
[-----------------73%-------           ] 1469 of 2000 complete in 633.4 sec
[-----------------73%-------           ] 1471 of 2000 complete in 634.3 sec
[-----------------73%-------           ] 1473 of 2000 complete in 635.1 sec
[-----------------73%--------          ] 1475 of 2000 complete in 636.0 sec
[-----------------73%--------          ] 1477 of 2000 complete in 636.9 sec
[-----------------73%--------          ] 1479 of 2000 complete in 637.7 sec
[-----------------74%--------          ] 1481 of 2000 complete in 638.5 sec
[-----------------74%--------          ] 1483 of 2000 complete in 639.4 sec
[-----------------74%--------          ] 1485 of 2000 complete in 640.3 sec
[-----------------74%--------          ] 1487 of 2000 complete in 641.1 sec
[-----------------74%--------          ] 1489 of 2000 complete in 641.9 sec
[-----------------74%--------          ] 1491 of 2000 complete in 642.8 sec
[-----------------74%--------          ] 1493 of 2000 complete in 643.6 sec
[-----------------74%--------          ] 1495 of 2000 complete in 644.5 sec
[-----------------74%--------          ] 1497 of 2000 complete in 645.5 sec
[-----------------74%--------          ] 1499 of 2000 complete in 646.3 sec
[-----------------75%--------          ] 1501 of 2000 complete in 647.2 sec
[-----------------75%--------          ] 1503 of 2000 complete in 648.1 sec
[-----------------75%--------          ] 1505 of 2000 complete in 648.9 sec
[-----------------75%--------          ] 1507 of 2000 complete in 649.7 sec
[-----------------75%--------          ] 1509 of 2000 complete in 650.6 sec
[-----------------75%--------          ] 1508 of 2000 complete in 644.6 sec
[-----------------75%--------          ] 1510 of 2000 complete in 645.5 sec
[-----------------75%--------          ] 1512 of 2000 complete in 646.4 sec
[-----------------75%--------          ] 1514 of 2000 complete in 647.2 sec
[-----------------75%--------          ] 1516 of 2000 complete in 648.1 sec
[-----------------75%--------          ] 1518 of 2000 complete in 648.9 sec
[-----------------76%--------          ] 1520 of 2000 complete in 649.7 sec
[-----------------76%--------          ] 1522 of 2000 complete in 650.5 sec
[-----------------76%--------          ] 1524 of 2000 complete in 651.3 sec
[-----------------76%--------          ] 1526 of 2000 complete in 652.2 sec
[-----------------76%---------         ] 1528 of 2000 complete in 653.0 sec
[-----------------76%---------         ] 1530 of 2000 complete in 653.8 sec
[-----------------76%---------         ] 1532 of 2000 complete in 654.7 sec
[-----------------76%---------         ] 1534 of 2000 complete in 655.5 sec
[-----------------76%---------         ] 1536 of 2000 complete in 656.4 sec
[-----------------76%---------         ] 1538 of 2000 complete in 657.2 sec
[-----------------77%---------         ] 1540 of 2000 complete in 658.1 sec
[-----------------77%---------         ] 1542 of 2000 complete in 658.9 sec
[-----------------77%---------         ] 1544 of 2000 complete in 659.7 sec
[-----------------77%---------         ] 1546 of 2000 complete in 660.5 sec
[-----------------77%---------         ] 1548 of 2000 complete in 661.4 sec
[-----------------77%---------         ] 1550 of 2000 complete in 662.3 sec
[-----------------77%---------         ] 1552 of 2000 complete in 663.1 sec
[-----------------77%---------         ] 1554 of 2000 complete in 664.0 sec
[-----------------77%---------         ] 1556 of 2000 complete in 664.9 sec
[-----------------77%---------         ] 1558 of 2000 complete in 665.7 sec
[-----------------78%---------         ] 1560 of 2000 complete in 666.6 sec
[-----------------78%---------         ] 1562 of 2000 complete in 667.4 sec
[-----------------78%---------         ] 1564 of 2000 complete in 668.3 sec
[-----------------78%---------         ] 1566 of 2000 complete in 669.2 sec
[-----------------78%---------         ] 1568 of 2000 complete in 670.0 sec
[-----------------78%---------         ] 1570 of 2000 complete in 670.9 sec
[-----------------78%---------         ] 1572 of 2000 complete in 671.7 sec
[-----------------78%---------         ] 1574 of 2000 complete in 672.6 sec
[-----------------78%---------         ] 1576 of 2000 complete in 673.4 sec
[-----------------78%---------         ] 1578 of 2000 complete in 674.3 sec
[-----------------79%----------        ] 1580 of 2000 complete in 675.1 sec
[-----------------79%----------        ] 1582 of 2000 complete in 676.0 sec
[-----------------79%----------        ] 1584 of 2000 complete in 676.8 sec
[-----------------79%----------        ] 1586 of 2000 complete in 677.6 sec
[-----------------79%----------        ] 1588 of 2000 complete in 678.5 sec
[-----------------79%----------        ] 1590 of 2000 complete in 679.3 sec
[-----------------79%----------        ] 1592 of 2000 complete in 680.1 sec
[-----------------79%----------        ] 1594 of 2000 complete in 681.0 sec
[-----------------79%----------        ] 1596 of 2000 complete in 681.9 sec
[-----------------79%----------        ] 1598 of 2000 complete in 682.7 sec
[-----------------80%----------        ] 1600 of 2000 complete in 683.5 sec
[-----------------80%----------        ] 1602 of 2000 complete in 684.4 sec
[-----------------80%----------        ] 1604 of 2000 complete in 685.3 sec
[-----------------80%----------        ] 1606 of 2000 complete in 686.2 sec
[-----------------80%----------        ] 1608 of 2000 complete in 687.1 sec
[-----------------80%----------        ] 1610 of 2000 complete in 687.9 sec
[-----------------80%----------        ] 1612 of 2000 complete in 688.8 sec
[-----------------80%----------        ] 1614 of 2000 complete in 689.7 sec
[-----------------80%----------        ] 1616 of 2000 complete in 690.6 sec
[-----------------80%----------        ] 1618 of 2000 complete in 691.4 sec
[-----------------81%----------        ] 1620 of 2000 complete in 692.3 sec
[-----------------81%----------        ] 1622 of 2000 complete in 693.1 sec
[-----------------81%----------        ] 1624 of 2000 complete in 694.0 sec
[-----------------81%----------        ] 1626 of 2000 complete in 694.9 sec
[-----------------81%----------        ] 1628 of 2000 complete in 695.7 sec
[-----------------81%----------        ] 1630 of 2000 complete in 696.6 sec
[-----------------81%-----------       ] 1632 of 2000 complete in 697.5 sec
[-----------------81%-----------       ] 1634 of 2000 complete in 698.4 sec
[-----------------81%-----------       ] 1636 of 2000 complete in 699.3 sec
[-----------------81%-----------       ] 1638 of 2000 complete in 700.1 sec
[-----------------82%-----------       ] 1640 of 2000 complete in 701.0 sec
[-----------------82%-----------       ] 1642 of 2000 complete in 701.8 sec
[-----------------82%-----------       ] 1644 of 2000 complete in 702.7 sec
[-----------------82%-----------       ] 1646 of 2000 complete in 703.5 sec
[-----------------82%-----------       ] 1648 of 2000 complete in 704.3 sec
[-----------------82%-----------       ] 1650 of 2000 complete in 705.1 sec
[-----------------82%-----------       ] 1652 of 2000 complete in 706.0 sec
[-----------------82%-----------       ] 1654 of 2000 complete in 706.9 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 707.8 sec
[-----------------82%-----------       ] 1658 of 2000 complete in 708.7 sec
[-----------------83%-----------       ] 1660 of 2000 complete in 709.6 sec
[-----------------83%-----------       ] 1662 of 2000 complete in 710.4 sec
[-----------------83%-----------       ] 1664 of 2000 complete in 711.4 sec
[-----------------83%-----------       ] 1666 of 2000 complete in 712.2 sec
[-----------------83%-----------       ] 1668 of 2000 complete in 713.1 sec
[-----------------83%-----------       ] 1670 of 2000 complete in 714.0 sec
[-----------------83%-----------       ] 1672 of 2000 complete in 714.8 sec
[-----------------83%-----------       ] 1674 of 2000 complete in 715.7 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 716.5 sec
[-----------------83%-----------       ] 1678 of 2000 complete in 717.4 sec
[-----------------84%-----------       ] 1680 of 2000 complete in 718.2 sec
[-----------------84%-----------       ] 1682 of 2000 complete in 719.1 sec
[-----------------84%-----------       ] 1684 of 2000 complete in 719.9 sec
[-----------------84%------------      ] 1686 of 2000 complete in 720.8 sec
[-----------------84%------------      ] 1688 of 2000 complete in 721.6 sec
[-----------------84%------------      ] 1690 of 2000 complete in 722.5 sec
[-----------------84%------------      ] 1692 of 2000 complete in 723.3 sec
[-----------------84%------------      ] 1694 of 2000 complete in 724.2 sec
[-----------------84%------------      ] 1696 of 2000 complete in 725.1 sec
[-----------------84%------------      ] 1698 of 2000 complete in 725.9 sec
[-----------------85%------------      ] 1700 of 2000 complete in 726.8 sec
[-----------------85%------------      ] 1702 of 2000 complete in 727.6 sec
[-----------------85%------------      ] 1704 of 2000 complete in 728.4 sec
[-----------------85%------------      ] 1706 of 2000 complete in 729.3 sec
[-----------------85%------------      ] 1708 of 2000 complete in 730.1 sec
[-----------------85%------------      ] 1710 of 2000 complete in 730.9 sec
[-----------------85%------------      ] 1712 of 2000 complete in 731.8 sec
[-----------------85%------------      ] 1714 of 2000 complete in 732.6 sec
[-----------------85%------------      ] 1716 of 2000 complete in 733.5 sec
[-----------------85%------------      ] 1718 of 2000 complete in 734.4 sec
[-----------------86%------------      ] 1720 of 2000 complete in 735.3 sec

[-----------------75%--------          ] 1503 of 2000 complete in 648.9 sec
[-----------------75%--------          ] 1505 of 2000 complete in 649.8 sec
[-----------------75%--------          ] 1507 of 2000 complete in 650.6 sec
[-----------------75%--------          ] 1509 of 2000 complete in 651.5 sec
[-----------------75%--------          ] 1511 of 2000 complete in 652.3 sec
[-----------------75%--------          ] 1513 of 2000 complete in 653.2 sec
[-----------------75%--------          ] 1515 of 2000 complete in 654.0 sec
[-----------------75%--------          ] 1517 of 2000 complete in 654.9 sec
[-----------------75%--------          ] 1519 of 2000 complete in 655.8 sec
[-----------------76%--------          ] 1521 of 2000 complete in 656.6 sec
[-----------------76%--------          ] 1523 of 2000 complete in 657.5 sec
[-----------------76%--------          ] 1525 of 2000 complete in 658.4 sec
[-----------------76%---------         ] 1527 of 2000 complete in 659.2 sec
[-----------------76%---------         ] 1529 of 2000 complete in 660.1 sec
[-----------------76%---------         ] 1531 of 2000 complete in 660.9 sec
[-----------------76%---------         ] 1533 of 2000 complete in 661.8 sec
[-----------------76%---------         ] 1535 of 2000 complete in 662.7 sec
[-----------------76%---------         ] 1537 of 2000 complete in 663.6 sec
[-----------------76%---------         ] 1539 of 2000 complete in 664.4 sec
[-----------------77%---------         ] 1541 of 2000 complete in 665.3 sec
[-----------------77%---------         ] 1543 of 2000 complete in 666.2 sec
[-----------------77%---------         ] 1545 of 2000 complete in 667.1 sec
[-----------------77%---------         ] 1547 of 2000 complete in 667.9 sec
[-----------------77%---------         ] 1549 of 2000 complete in 668.8 sec
[-----------------77%---------         ] 1551 of 2000 complete in 669.6 sec
[-----------------77%---------         ] 1553 of 2000 complete in 670.5 sec
[-----------------77%---------         ] 1555 of 2000 complete in 671.3 sec
[-----------------77%---------         ] 1557 of 2000 complete in 672.2 sec
[-----------------77%---------         ] 1559 of 2000 complete in 673.0 sec
[-----------------78%---------         ] 1561 of 2000 complete in 673.9 sec
[-----------------78%---------         ] 1563 of 2000 complete in 674.8 sec
[-----------------78%---------         ] 1565 of 2000 complete in 675.6 sec
[-----------------78%---------         ] 1567 of 2000 complete in 676.5 sec
[-----------------78%---------         ] 1569 of 2000 complete in 677.4 sec
[-----------------78%---------         ] 1571 of 2000 complete in 678.2 sec
[-----------------78%---------         ] 1573 of 2000 complete in 679.0 sec
[-----------------78%---------         ] 1575 of 2000 complete in 679.9 sec
[-----------------78%---------         ] 1577 of 2000 complete in 680.7 sec
[-----------------78%----------        ] 1579 of 2000 complete in 681.6 sec
[-----------------79%----------        ] 1581 of 2000 complete in 682.5 sec
[-----------------79%----------        ] 1583 of 2000 complete in 683.3 sec
[-----------------79%----------        ] 1585 of 2000 complete in 684.2 sec
[-----------------79%----------        ] 1587 of 2000 complete in 685.0 sec
[-----------------79%----------        ] 1589 of 2000 complete in 685.9 sec
[-----------------79%----------        ] 1591 of 2000 complete in 686.7 sec
[-----------------79%----------        ] 1593 of 2000 complete in 687.6 sec
[-----------------79%----------        ] 1595 of 2000 complete in 688.5 sec
[-----------------79%----------        ] 1597 of 2000 complete in 689.4 sec
[-----------------79%----------        ] 1599 of 2000 complete in 690.3 sec
[-----------------80%----------        ] 1601 of 2000 complete in 691.1 sec
[-----------------80%----------        ] 1603 of 2000 complete in 692.0 sec
[-----------------80%----------        ] 1605 of 2000 complete in 692.8 sec
[-----------------80%----------        ] 1607 of 2000 complete in 693.7 sec
[-----------------80%----------        ] 1609 of 2000 complete in 694.6 sec
[-----------------80%----------        ] 1611 of 2000 complete in 695.4 sec
[-----------------80%----------        ] 1613 of 2000 complete in 696.3 sec
[-----------------80%----------        ] 1615 of 2000 complete in 697.2 sec
[-----------------80%----------        ] 1617 of 2000 complete in 698.1 sec
[-----------------80%----------        ] 1619 of 2000 complete in 699.0 sec
[-----------------81%----------        ] 1621 of 2000 complete in 699.9 sec
[-----------------81%----------        ] 1623 of 2000 complete in 700.7 sec
[-----------------81%----------        ] 1625 of 2000 complete in 701.6 sec
[-----------------81%----------        ] 1627 of 2000 complete in 702.4 sec
[-----------------81%----------        ] 1629 of 2000 complete in 703.3 sec
[-----------------81%----------        ] 1631 of 2000 complete in 704.1 sec
[-----------------81%-----------       ] 1633 of 2000 complete in 704.9 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 705.8 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 706.7 sec
[-----------------81%-----------       ] 1639 of 2000 complete in 707.6 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 708.5 sec
[-----------------82%-----------       ] 1643 of 2000 complete in 709.4 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 710.2 sec
[-----------------82%-----------       ] 1647 of 2000 complete in 711.1 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 712.0 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 712.9 sec
[-----------------82%-----------       ] 1653 of 2000 complete in 713.7 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 714.6 sec
[-----------------82%-----------       ] 1657 of 2000 complete in 715.5 sec
[-----------------82%-----------       ] 1659 of 2000 complete in 716.4 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 717.3 sec
[-----------------83%-----------       ] 1663 of 2000 complete in 718.2 sec
[-----------------83%-----------       ] 1665 of 2000 complete in 719.0 sec
[-----------------83%-----------       ] 1667 of 2000 complete in 719.9 sec
[-----------------83%-----------       ] 1669 of 2000 complete in 720.7 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 721.6 sec
[-----------------83%-----------       ] 1673 of 2000 complete in 722.5 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 723.3 sec
[-----------------83%-----------       ] 1677 of 2000 complete in 724.2 sec
[-----------------83%-----------       ] 1679 of 2000 complete in 725.1 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 725.9 sec
[-----------------84%-----------       ] 1683 of 2000 complete in 726.8 sec
[-----------------84%------------      ] 1685 of 2000 complete in 727.6 sec
[-----------------84%------------      ] 1687 of 2000 complete in 728.5 sec
[-----------------84%------------      ] 1689 of 2000 complete in 729.3 sec
[-----------------84%------------      ] 1691 of 2000 complete in 730.2 sec
[-----------------84%------------      ] 1693 of 2000 complete in 731.1 sec
[-----------------84%------------      ] 1695 of 2000 complete in 731.9 sec
[-----------------84%------------      ] 1697 of 2000 complete in 732.8 sec
[-----------------84%------------      ] 1699 of 2000 complete in 733.7 sec
[-----------------85%------------      ] 1701 of 2000 complete in 734.6 sec
[-----------------85%------------      ] 1703 of 2000 complete in 735.5 sec
[-----------------85%------------      ] 1705 of 2000 complete in 736.4 sec
[-----------------85%------------      ] 1707 of 2000 complete in 737.2 sec
[-----------------85%------------      ] 1709 of 2000 complete in 738.1 sec
[-----------------85%------------      ] 1711 of 2000 complete in 739.0 sec
[-----------------85%------------      ] 1713 of 2000 complete in 739.8 sec
[-----------------85%------------      ] 1715 of 2000 complete in 740.6 sec
[-----------------75%--------          ] 1508 of 2000 complete in 649.8 sec
[-----------------75%--------          ] 1510 of 2000 complete in 650.7 sec
[-----------------75%--------          ] 1512 of 2000 complete in 651.5 sec
[-----------------75%--------          ] 1514 of 2000 complete in 652.3 sec
[-----------------75%--------          ] 1516 of 2000 complete in 653.2 sec
[-----------------75%--------          ] 1518 of 2000 complete in 654.0 sec
[-----------------76%--------          ] 1520 of 2000 complete in 654.8 sec
[-----------------76%--------          ] 1522 of 2000 complete in 655.7 sec
[-----------------76%--------          ] 1524 of 2000 complete in 656.6 sec
[-----------------76%--------          ] 1526 of 2000 complete in 657.5 sec
[-----------------76%---------         ] 1528 of 2000 complete in 658.3 sec
[-----------------76%---------         ] 1530 of 2000 complete in 659.2 sec
[-----------------76%---------         ] 1532 of 2000 complete in 660.0 sec
[-----------------76%---------         ] 1534 of 2000 complete in 660.9 sec
[-----------------76%---------         ] 1536 of 2000 complete in 661.7 sec
[-----------------76%---------         ] 1538 of 2000 complete in 662.6 sec
[-----------------77%---------         ] 1540 of 2000 complete in 663.5 sec
[-----------------77%---------         ] 1542 of 2000 complete in 664.3 sec
[-----------------77%---------         ] 1544 of 2000 complete in 665.2 sec
[-----------------77%---------         ] 1546 of 2000 complete in 666.1 sec
[-----------------77%---------         ] 1548 of 2000 complete in 666.9 sec
[-----------------77%---------         ] 1550 of 2000 complete in 667.8 sec
[-----------------77%---------         ] 1552 of 2000 complete in 668.7 sec
[-----------------77%---------         ] 1554 of 2000 complete in 669.6 sec
[-----------------77%---------         ] 1556 of 2000 complete in 670.4 sec
[-----------------77%---------         ] 1558 of 2000 complete in 671.2 sec
[-----------------78%---------         ] 1560 of 2000 complete in 672.1 sec
[-----------------78%---------         ] 1562 of 2000 complete in 672.9 sec
[-----------------78%---------         ] 1564 of 2000 complete in 673.7 sec
[-----------------78%---------         ] 1566 of 2000 complete in 674.6 sec
[-----------------78%---------         ] 1568 of 2000 complete in 675.5 sec
[-----------------78%---------         ] 1570 of 2000 complete in 676.3 sec
[-----------------78%---------         ] 1572 of 2000 complete in 677.2 sec
[-----------------78%---------         ] 1574 of 2000 complete in 678.0 sec
[-----------------78%---------         ] 1576 of 2000 complete in 678.8 sec
[-----------------78%---------         ] 1578 of 2000 complete in 679.6 sec
[-----------------79%----------        ] 1580 of 2000 complete in 680.5 sec
[-----------------79%----------        ] 1582 of 2000 complete in 681.4 sec
[-----------------79%----------        ] 1584 of 2000 complete in 682.2 sec
[-----------------79%----------        ] 1586 of 2000 complete in 683.0 sec
[-----------------79%----------        ] 1588 of 2000 complete in 683.9 sec
[-----------------79%----------        ] 1590 of 2000 complete in 684.7 sec
[-----------------79%----------        ] 1592 of 2000 complete in 685.6 sec
[-----------------79%----------        ] 1594 of 2000 complete in 686.5 sec
[-----------------79%----------        ] 1596 of 2000 complete in 687.3 sec
[-----------------79%----------        ] 1598 of 2000 complete in 688.2 sec
[-----------------80%----------        ] 1600 of 2000 complete in 689.1 sec
[-----------------80%----------        ] 1602 of 2000 complete in 690.0 sec
[-----------------80%----------        ] 1604 of 2000 complete in 690.9 sec
[-----------------80%----------        ] 1606 of 2000 complete in 691.7 sec
[-----------------80%----------        ] 1608 of 2000 complete in 692.6 sec
[-----------------80%----------        ] 1610 of 2000 complete in 693.5 sec
[-----------------80%----------        ] 1612 of 2000 complete in 694.4 sec
[-----------------80%----------        ] 1614 of 2000 complete in 695.3 sec
[-----------------80%----------        ] 1616 of 2000 complete in 696.1 sec
[-----------------80%----------        ] 1618 of 2000 complete in 697.0 sec
[-----------------81%----------        ] 1620 of 2000 complete in 697.9 sec
[-----------------81%----------        ] 1622 of 2000 complete in 698.8 sec
[-----------------81%----------        ] 1624 of 2000 complete in 699.7 sec
[-----------------81%----------        ] 1626 of 2000 complete in 700.5 sec
[-----------------81%----------        ] 1628 of 2000 complete in 701.3 sec
[-----------------81%----------        ] 1630 of 2000 complete in 702.2 sec
[-----------------81%-----------       ] 1632 of 2000 complete in 703.1 sec
[-----------------81%-----------       ] 1634 of 2000 complete in 703.9 sec
[-----------------81%-----------       ] 1636 of 2000 complete in 704.8 sec
[-----------------81%-----------       ] 1638 of 2000 complete in 705.6 sec
[-----------------82%-----------       ] 1640 of 2000 complete in 706.5 sec
[-----------------82%-----------       ] 1642 of 2000 complete in 707.4 sec
[-----------------82%-----------       ] 1644 of 2000 complete in 708.3 sec
[-----------------82%-----------       ] 1646 of 2000 complete in 709.2 sec
[-----------------82%-----------       ] 1648 of 2000 complete in 710.0 sec
[-----------------82%-----------       ] 1650 of 2000 complete in 710.9 sec
[-----------------82%-----------       ] 1652 of 2000 complete in 711.8 sec
[-----------------82%-----------       ] 1654 of 2000 complete in 712.6 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 713.5 sec
[-----------------82%-----------       ] 1658 of 2000 complete in 714.5 sec
[-----------------83%-----------       ] 1660 of 2000 complete in 715.3 sec
[-----------------83%-----------       ] 1662 of 2000 complete in 716.2 sec
[-----------------83%-----------       ] 1664 of 2000 complete in 717.1 sec
[-----------------83%-----------       ] 1666 of 2000 complete in 718.0 sec
[-----------------83%-----------       ] 1668 of 2000 complete in 718.9 sec
[-----------------83%-----------       ] 1670 of 2000 complete in 719.7 sec
[-----------------83%-----------       ] 1672 of 2000 complete in 720.6 sec
[-----------------83%-----------       ] 1674 of 2000 complete in 721.4 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 722.3 sec
[-----------------83%-----------       ] 1678 of 2000 complete in 723.1 sec
[-----------------84%-----------       ] 1680 of 2000 complete in 724.0 sec
[-----------------84%-----------       ] 1682 of 2000 complete in 724.9 sec
[-----------------84%-----------       ] 1684 of 2000 complete in 725.7 sec
[-----------------84%------------      ] 1686 of 2000 complete in 726.5 sec
[-----------------84%------------      ] 1688 of 2000 complete in 727.4 sec
[-----------------84%------------      ] 1690 of 2000 complete in 728.3 sec
[-----------------84%------------      ] 1692 of 2000 complete in 729.1 sec
[-----------------84%------------      ] 1694 of 2000 complete in 729.9 sec
[-----------------84%------------      ] 1696 of 2000 complete in 730.8 sec
[-----------------84%------------      ] 1698 of 2000 complete in 731.7 sec
[-----------------85%------------      ] 1700 of 2000 complete in 732.6 sec
[-----------------85%------------      ] 1702 of 2000 complete in 733.5 sec
[-----------------85%------------      ] 1704 of 2000 complete in 734.4 sec
[-----------------85%------------      ] 1706 of 2000 complete in 735.3 sec
[-----------------85%------------      ] 1708 of 2000 complete in 736.2 sec
[-----------------85%------------      ] 1710 of 2000 complete in 737.1 sec
[-----------------85%------------      ] 1712 of 2000 complete in 737.9 sec
[-----------------85%------------      ] 1714 of 2000 complete in 738.8 sec
[-----------------85%------------      ] 1716 of 2000 complete in 739.7 sec
[-----------------85%------------      ] 1718 of 2000 complete in 740.5 sec
[-----------------86%------------      ] 1720 of 2000 complete in 741.4 sec

[-----------------75%--------          ] 1511 of 2000 complete in 651.5 sec
[-----------------75%--------          ] 1513 of 2000 complete in 652.3 sec
[-----------------75%--------          ] 1515 of 2000 complete in 653.2 sec
[-----------------75%--------          ] 1517 of 2000 complete in 654.0 sec
[-----------------75%--------          ] 1519 of 2000 complete in 654.9 sec
[-----------------76%--------          ] 1521 of 2000 complete in 655.7 sec
[-----------------76%--------          ] 1523 of 2000 complete in 656.6 sec
[-----------------76%--------          ] 1525 of 2000 complete in 657.5 sec
[-----------------76%---------         ] 1527 of 2000 complete in 658.3 sec
[-----------------76%---------         ] 1529 of 2000 complete in 659.1 sec
[-----------------76%---------         ] 1531 of 2000 complete in 660.0 sec
[-----------------76%---------         ] 1533 of 2000 complete in 660.8 sec
[-----------------76%---------         ] 1535 of 2000 complete in 661.7 sec
[-----------------76%---------         ] 1537 of 2000 complete in 662.6 sec
[-----------------76%---------         ] 1539 of 2000 complete in 663.5 sec
[-----------------77%---------         ] 1541 of 2000 complete in 664.3 sec
[-----------------77%---------         ] 1543 of 2000 complete in 665.2 sec
[-----------------77%---------         ] 1545 of 2000 complete in 666.1 sec
[-----------------77%---------         ] 1547 of 2000 complete in 666.9 sec
[-----------------77%---------         ] 1549 of 2000 complete in 667.8 sec
[-----------------77%---------         ] 1551 of 2000 complete in 668.7 sec
[-----------------77%---------         ] 1553 of 2000 complete in 669.6 sec
[-----------------77%---------         ] 1555 of 2000 complete in 670.4 sec
[-----------------77%---------         ] 1557 of 2000 complete in 671.3 sec
[-----------------77%---------         ] 1559 of 2000 complete in 672.1 sec
[-----------------78%---------         ] 1561 of 2000 complete in 673.0 sec
[-----------------78%---------         ] 1563 of 2000 complete in 673.8 sec
[-----------------78%---------         ] 1565 of 2000 complete in 674.7 sec
[-----------------78%---------         ] 1567 of 2000 complete in 675.6 sec
[-----------------78%---------         ] 1569 of 2000 complete in 676.4 sec
[-----------------78%---------         ] 1571 of 2000 complete in 677.3 sec
[-----------------78%---------         ] 1573 of 2000 complete in 678.1 sec
[-----------------78%---------         ] 1575 of 2000 complete in 678.9 sec
[-----------------78%---------         ] 1577 of 2000 complete in 679.8 sec
[-----------------78%----------        ] 1579 of 2000 complete in 680.7 sec
[-----------------79%----------        ] 1581 of 2000 complete in 681.6 sec
[-----------------79%----------        ] 1583 of 2000 complete in 682.4 sec
[-----------------79%----------        ] 1585 of 2000 complete in 683.3 sec
[-----------------79%----------        ] 1587 of 2000 complete in 684.2 sec
[-----------------79%----------        ] 1589 of 2000 complete in 685.0 sec
[-----------------79%----------        ] 1591 of 2000 complete in 685.9 sec
[-----------------79%----------        ] 1593 of 2000 complete in 686.9 sec
[-----------------79%----------        ] 1595 of 2000 complete in 687.8 sec
[-----------------79%----------        ] 1597 of 2000 complete in 688.7 sec
[-----------------79%----------        ] 1599 of 2000 complete in 689.5 sec
[-----------------80%----------        ] 1601 of 2000 complete in 690.4 sec
[-----------------80%----------        ] 1603 of 2000 complete in 691.3 sec
[-----------------80%----------        ] 1605 of 2000 complete in 692.1 sec
[-----------------80%----------        ] 1607 of 2000 complete in 693.0 sec
[-----------------80%----------        ] 1609 of 2000 complete in 693.9 sec
[-----------------80%----------        ] 1611 of 2000 complete in 694.7 sec
[-----------------80%----------        ] 1613 of 2000 complete in 695.6 sec
[-----------------80%----------        ] 1615 of 2000 complete in 696.5 sec
[-----------------80%----------        ] 1617 of 2000 complete in 697.4 sec
[-----------------80%----------        ] 1619 of 2000 complete in 698.3 sec
[-----------------81%----------        ] 1621 of 2000 complete in 699.2 sec
[-----------------81%----------        ] 1623 of 2000 complete in 700.1 sec
[-----------------81%----------        ] 1625 of 2000 complete in 701.0 sec
[-----------------81%----------        ] 1627 of 2000 complete in 701.8 sec
[-----------------81%----------        ] 1629 of 2000 complete in 702.7 sec
[-----------------81%----------        ] 1631 of 2000 complete in 703.6 sec
[-----------------81%-----------       ] 1633 of 2000 complete in 704.4 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 705.2 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 706.0 sec
[-----------------81%-----------       ] 1639 of 2000 complete in 706.9 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 707.9 sec
[-----------------82%-----------       ] 1643 of 2000 complete in 708.7 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 709.6 sec
[-----------------82%-----------       ] 1647 of 2000 complete in 710.4 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 711.3 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 712.2 sec
[-----------------82%-----------       ] 1653 of 2000 complete in 713.1 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 714.0 sec
[-----------------82%-----------       ] 1657 of 2000 complete in 714.8 sec
[-----------------82%-----------       ] 1659 of 2000 complete in 715.7 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 716.5 sec
[-----------------83%-----------       ] 1663 of 2000 complete in 717.4 sec
[-----------------83%-----------       ] 1665 of 2000 complete in 718.3 sec
[-----------------83%-----------       ] 1667 of 2000 complete in 719.2 sec
[-----------------83%-----------       ] 1669 of 2000 complete in 720.1 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 720.9 sec
[-----------------83%-----------       ] 1673 of 2000 complete in 721.8 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 722.6 sec
[-----------------83%-----------       ] 1677 of 2000 complete in 723.5 sec
[-----------------83%-----------       ] 1679 of 2000 complete in 724.4 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 725.2 sec
[-----------------84%-----------       ] 1683 of 2000 complete in 726.1 sec
[-----------------84%------------      ] 1685 of 2000 complete in 727.0 sec
[-----------------84%------------      ] 1687 of 2000 complete in 727.8 sec
[-----------------84%------------      ] 1689 of 2000 complete in 728.7 sec
[-----------------84%------------      ] 1691 of 2000 complete in 729.5 sec
[-----------------84%------------      ] 1693 of 2000 complete in 730.4 sec
[-----------------84%------------      ] 1695 of 2000 complete in 731.2 sec
[-----------------84%------------      ] 1697 of 2000 complete in 732.1 sec
[-----------------84%------------      ] 1699 of 2000 complete in 733.0 sec
[-----------------85%------------      ] 1701 of 2000 complete in 733.9 sec
[-----------------85%------------      ] 1703 of 2000 complete in 734.8 sec
[-----------------85%------------      ] 1705 of 2000 complete in 735.7 sec
[-----------------85%------------      ] 1707 of 2000 complete in 736.6 sec
[-----------------85%------------      ] 1709 of 2000 complete in 737.4 sec
[-----------------85%------------      ] 1711 of 2000 complete in 738.3 sec
[-----------------85%------------      ] 1713 of 2000 complete in 739.1 sec
[-----------------85%------------      ] 1715 of 2000 complete in 740.0 sec
[-----------------85%------------      ] 1717 of 2000 complete in 740.8 sec
[-----------------85%------------      ] 1719 of 2000 complete in 741.7 sec
[-----------------86%------------      ] 1721 of 2000 complete in 742.5 sec
[-----------------86%------------      ] 1723 of 2000 complete in 743.4 sec
[-----------------86%------------      ] 1722 of 2000 complete in 736.2 sec
[-----------------86%------------      ] 1724 of 2000 complete in 737.0 sec
[-----------------86%------------      ] 1726 of 2000 complete in 737.9 sec
[-----------------86%------------      ] 1728 of 2000 complete in 738.7 sec
[-----------------86%------------      ] 1730 of 2000 complete in 739.6 sec
[-----------------86%------------      ] 1732 of 2000 complete in 740.4 sec
[-----------------86%------------      ] 1734 of 2000 complete in 741.3 sec
[-----------------86%------------      ] 1736 of 2000 complete in 742.2 sec
[-----------------86%-------------     ] 1738 of 2000 complete in 743.0 sec
[-----------------87%-------------     ] 1740 of 2000 complete in 743.8 sec
[-----------------87%-------------     ] 1742 of 2000 complete in 744.7 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 745.6 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 746.5 sec
[-----------------87%-------------     ] 1748 of 2000 complete in 747.3 sec
[-----------------87%-------------     ] 1750 of 2000 complete in 748.2 sec
[-----------------87%-------------     ] 1752 of 2000 complete in 749.0 sec
[-----------------87%-------------     ] 1754 of 2000 complete in 749.9 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 750.7 sec
[-----------------87%-------------     ] 1758 of 2000 complete in 751.6 sec
[-----------------88%-------------     ] 1760 of 2000 complete in 752.5 sec
[-----------------88%-------------     ] 1762 of 2000 complete in 753.3 sec
[-----------------88%-------------     ] 1764 of 2000 complete in 754.3 sec
[-----------------88%-------------     ] 1766 of 2000 complete in 755.1 sec
[-----------------88%-------------     ] 1768 of 2000 complete in 756.0 sec
[-----------------88%-------------     ] 1770 of 2000 complete in 756.9 sec
[-----------------88%-------------     ] 1772 of 2000 complete in 757.7 sec
[-----------------88%-------------     ] 1774 of 2000 complete in 758.6 sec
[-----------------88%-------------     ] 1776 of 2000 complete in 759.4 sec
[-----------------88%-------------     ] 1778 of 2000 complete in 760.3 sec
[-----------------89%-------------     ] 1780 of 2000 complete in 761.2 sec
[-----------------89%-------------     ] 1782 of 2000 complete in 762.0 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 762.8 sec
[-----------------89%-------------     ] 1786 of 2000 complete in 763.7 sec
[-----------------89%-------------     ] 1788 of 2000 complete in 764.5 sec
[-----------------89%--------------    ] 1790 of 2000 complete in 765.3 sec
[-----------------89%--------------    ] 1792 of 2000 complete in 766.2 sec
[-----------------89%--------------    ] 1794 of 2000 complete in 767.0 sec
[-----------------89%--------------    ] 1796 of 2000 complete in 767.8 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 768.7 sec
[-----------------90%--------------    ] 1800 of 2000 complete in 769.6 sec
[-----------------90%--------------    ] 1802 of 2000 complete in 770.6 sec
[-----------------90%--------------    ] 1804 of 2000 complete in 771.4 sec
[-----------------90%--------------    ] 1806 of 2000 complete in 772.2 sec
[-----------------90%--------------    ] 1808 of 2000 complete in 773.1 sec
[-----------------90%--------------    ] 1810 of 2000 complete in 774.0 sec
[-----------------90%--------------    ] 1812 of 2000 complete in 774.8 sec
[-----------------90%--------------    ] 1814 of 2000 complete in 775.6 sec
[-----------------90%--------------    ] 1816 of 2000 complete in 776.4 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 777.3 sec
[-----------------91%--------------    ] 1820 of 2000 complete in 778.1 sec
[-----------------91%--------------    ] 1822 of 2000 complete in 778.9 sec
[-----------------91%--------------    ] 1824 of 2000 complete in 779.8 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 780.6 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 781.4 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 782.3 sec
[-----------------91%--------------    ] 1832 of 2000 complete in 783.1 sec
[-----------------91%--------------    ] 1834 of 2000 complete in 783.9 sec
[-----------------91%--------------    ] 1836 of 2000 complete in 784.8 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 785.8 sec
[-----------------92%--------------    ] 1840 of 2000 complete in 786.6 sec
[-----------------92%--------------    ] 1841 of 2000 complete in 787.2 sec
[-----------------92%---------------   ] 1843 of 2000 complete in 788.1 sec
[-----------------92%---------------   ] 1845 of 2000 complete in 789.0 sec
[-----------------92%---------------   ] 1847 of 2000 complete in 790.0 sec
[-----------------92%---------------   ] 1849 of 2000 complete in 790.8 sec
[-----------------92%---------------   ] 1851 of 2000 complete in 791.7 sec
[-----------------92%---------------   ] 1853 of 2000 complete in 792.5 sec
[-----------------92%---------------   ] 1855 of 2000 complete in 793.4 sec
[-----------------92%---------------   ] 1857 of 2000 complete in 794.2 sec
[-----------------92%---------------   ] 1859 of 2000 complete in 795.1 sec
[-----------------93%---------------   ] 1861 of 2000 complete in 795.9 sec
[-----------------93%---------------   ] 1863 of 2000 complete in 796.8 sec
[-----------------93%---------------   ] 1865 of 2000 complete in 797.6 sec
[-----------------93%---------------   ] 1867 of 2000 complete in 798.5 sec
[-----------------93%---------------   ] 1869 of 2000 complete in 799.5 sec
[-----------------93%---------------   ] 1871 of 2000 complete in 800.4 sec
[-----------------93%---------------   ] 1873 of 2000 complete in 801.3 sec
[-----------------93%---------------   ] 1875 of 2000 complete in 802.1 sec
[-----------------93%---------------   ] 1877 of 2000 complete in 803.0 sec
[-----------------93%---------------   ] 1878 of 2000 complete in 803.6 sec
[-----------------93%---------------   ] 1879 of 2000 complete in 804.2 sec
[-----------------94%---------------   ] 1881 of 2000 complete in 805.1 sec
[-----------------94%---------------   ] 1883 of 2000 complete in 806.1 sec
[-----------------94%---------------   ] 1884 of 2000 complete in 806.7 sec
[-----------------94%---------------   ] 1886 of 2000 complete in 807.6 sec
[-----------------94%---------------   ] 1888 of 2000 complete in 808.6 sec
[-----------------94%---------------   ] 1889 of 2000 complete in 809.1 sec
[-----------------94%---------------   ] 1891 of 2000 complete in 810.0 sec
[-----------------94%---------------   ] 1893 of 2000 complete in 811.0 sec
[-----------------94%----------------  ] 1895 of 2000 complete in 811.8 sec
[-----------------94%----------------  ] 1897 of 2000 complete in 812.7 sec
[-----------------94%----------------  ] 1899 of 2000 complete in 813.5 sec
[-----------------95%----------------  ] 1901 of 2000 complete in 814.4 sec
[-----------------95%----------------  ] 1903 of 2000 complete in 815.3 sec
[-----------------95%----------------  ] 1905 of 2000 complete in 816.1 sec
[-----------------95%----------------  ] 1907 of 2000 complete in 817.1 sec
[-----------------95%----------------  ] 1909 of 2000 complete in 818.0 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 818.6 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 819.5 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 820.4 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 821.3 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 821.8 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 822.4 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 823.2 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 824.1 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 824.9 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 825.7 sec

[-----------------86%------------      ] 1722 of 2000 complete in 742.4 sec
[-----------------86%------------      ] 1724 of 2000 complete in 743.2 sec
[-----------------86%------------      ] 1726 of 2000 complete in 744.0 sec
[-----------------86%------------      ] 1728 of 2000 complete in 744.8 sec
[-----------------86%------------      ] 1730 of 2000 complete in 745.7 sec
[-----------------86%------------      ] 1732 of 2000 complete in 746.5 sec
[-----------------86%------------      ] 1734 of 2000 complete in 747.4 sec
[-----------------86%------------      ] 1736 of 2000 complete in 748.2 sec
[-----------------86%-------------     ] 1738 of 2000 complete in 749.1 sec
[-----------------87%-------------     ] 1740 of 2000 complete in 749.9 sec
[-----------------87%-------------     ] 1742 of 2000 complete in 750.8 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 751.7 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 752.5 sec
[-----------------87%-------------     ] 1748 of 2000 complete in 753.4 sec
[-----------------87%-------------     ] 1750 of 2000 complete in 754.2 sec
[-----------------87%-------------     ] 1752 of 2000 complete in 755.1 sec
[-----------------87%-------------     ] 1754 of 2000 complete in 756.0 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 756.8 sec
[-----------------87%-------------     ] 1758 of 2000 complete in 757.7 sec
[-----------------88%-------------     ] 1760 of 2000 complete in 758.5 sec
[-----------------88%-------------     ] 1762 of 2000 complete in 759.4 sec
[-----------------88%-------------     ] 1764 of 2000 complete in 760.3 sec
[-----------------88%-------------     ] 1766 of 2000 complete in 761.2 sec
[-----------------88%-------------     ] 1768 of 2000 complete in 762.0 sec
[-----------------88%-------------     ] 1770 of 2000 complete in 762.9 sec
[-----------------88%-------------     ] 1772 of 2000 complete in 763.7 sec
[-----------------88%-------------     ] 1774 of 2000 complete in 764.6 sec
[-----------------88%-------------     ] 1776 of 2000 complete in 765.4 sec
[-----------------88%-------------     ] 1778 of 2000 complete in 766.3 sec
[-----------------89%-------------     ] 1780 of 2000 complete in 767.1 sec
[-----------------89%-------------     ] 1782 of 2000 complete in 767.9 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 768.8 sec
[-----------------89%-------------     ] 1786 of 2000 complete in 769.8 sec
[-----------------89%-------------     ] 1788 of 2000 complete in 770.7 sec
[-----------------89%--------------    ] 1790 of 2000 complete in 771.5 sec
[-----------------89%--------------    ] 1792 of 2000 complete in 772.3 sec
[-----------------89%--------------    ] 1794 of 2000 complete in 773.2 sec
[-----------------89%--------------    ] 1796 of 2000 complete in 774.0 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 774.9 sec
[-----------------90%--------------    ] 1800 of 2000 complete in 775.7 sec
[-----------------90%--------------    ] 1802 of 2000 complete in 776.5 sec
[-----------------90%--------------    ] 1804 of 2000 complete in 777.4 sec
[-----------------90%--------------    ] 1806 of 2000 complete in 778.2 sec
[-----------------90%--------------    ] 1808 of 2000 complete in 779.0 sec
[-----------------90%--------------    ] 1810 of 2000 complete in 779.8 sec
[-----------------90%--------------    ] 1812 of 2000 complete in 780.7 sec
[-----------------90%--------------    ] 1814 of 2000 complete in 781.5 sec
[-----------------90%--------------    ] 1816 of 2000 complete in 782.4 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 783.2 sec
[-----------------91%--------------    ] 1820 of 2000 complete in 784.1 sec
[-----------------91%--------------    ] 1822 of 2000 complete in 784.9 sec
[-----------------91%--------------    ] 1824 of 2000 complete in 785.9 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 786.8 sec
[-----------------91%--------------    ] 1827 of 2000 complete in 787.3 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 787.8 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 788.7 sec
[-----------------91%--------------    ] 1831 of 2000 complete in 789.2 sec
[-----------------91%--------------    ] 1833 of 2000 complete in 790.2 sec
[-----------------91%--------------    ] 1835 of 2000 complete in 791.1 sec
[-----------------91%--------------    ] 1837 of 2000 complete in 791.9 sec
[-----------------91%--------------    ] 1839 of 2000 complete in 792.7 sec
[-----------------92%--------------    ] 1841 of 2000 complete in 793.6 sec
[-----------------92%---------------   ] 1843 of 2000 complete in 794.4 sec
[-----------------92%---------------   ] 1845 of 2000 complete in 795.2 sec
[-----------------92%---------------   ] 1847 of 2000 complete in 796.1 sec
[-----------------92%---------------   ] 1849 of 2000 complete in 797.0 sec
[-----------------92%---------------   ] 1851 of 2000 complete in 797.8 sec
[-----------------92%---------------   ] 1853 of 2000 complete in 798.6 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 799.1 sec
[-----------------92%---------------   ] 1855 of 2000 complete in 799.7 sec
[-----------------92%---------------   ] 1857 of 2000 complete in 800.6 sec
[-----------------92%---------------   ] 1859 of 2000 complete in 801.4 sec
[-----------------93%---------------   ] 1861 of 2000 complete in 802.3 sec
[-----------------93%---------------   ] 1863 of 2000 complete in 803.2 sec
[-----------------93%---------------   ] 1864 of 2000 complete in 803.8 sec
[-----------------93%---------------   ] 1865 of 2000 complete in 804.3 sec
[-----------------93%---------------   ] 1867 of 2000 complete in 805.2 sec
[-----------------93%---------------   ] 1869 of 2000 complete in 806.3 sec
[-----------------93%---------------   ] 1870 of 2000 complete in 806.8 sec
[-----------------93%---------------   ] 1872 of 2000 complete in 807.8 sec
[-----------------93%---------------   ] 1873 of 2000 complete in 808.3 sec
[-----------------93%---------------   ] 1875 of 2000 complete in 809.3 sec
[-----------------93%---------------   ] 1877 of 2000 complete in 810.2 sec
[-----------------93%---------------   ] 1879 of 2000 complete in 811.1 sec
[-----------------94%---------------   ] 1881 of 2000 complete in 812.0 sec
[-----------------94%---------------   ] 1883 of 2000 complete in 812.8 sec
[-----------------94%---------------   ] 1885 of 2000 complete in 813.7 sec
[-----------------94%---------------   ] 1887 of 2000 complete in 814.5 sec
[-----------------94%---------------   ] 1889 of 2000 complete in 815.4 sec
[-----------------94%---------------   ] 1891 of 2000 complete in 816.3 sec
[-----------------94%---------------   ] 1893 of 2000 complete in 817.2 sec
[-----------------94%---------------   ] 1894 of 2000 complete in 817.7 sec
[-----------------94%----------------  ] 1895 of 2000 complete in 818.3 sec
[-----------------94%----------------  ] 1896 of 2000 complete in 818.8 sec
[-----------------94%----------------  ] 1897 of 2000 complete in 819.3 sec
[-----------------94%----------------  ] 1899 of 2000 complete in 820.2 sec
[-----------------95%----------------  ] 1901 of 2000 complete in 821.1 sec
[-----------------95%----------------  ] 1903 of 2000 complete in 822.1 sec
[-----------------95%----------------  ] 1905 of 2000 complete in 823.0 sec
[-----------------95%----------------  ] 1907 of 2000 complete in 823.9 sec
[-----------------95%----------------  ] 1909 of 2000 complete in 824.7 sec
[-----------------95%----------------  ] 1911 of 2000 complete in 825.6 sec
[-----------------95%----------------  ] 1913 of 2000 complete in 826.5 sec
[-----------------95%----------------  ] 1915 of 2000 complete in 827.4 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 828.2 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 829.1 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 830.0 sec
[-----------------85%------------      ] 1717 of 2000 complete in 741.6 sec
[-----------------85%------------      ] 1719 of 2000 complete in 742.4 sec
[-----------------86%------------      ] 1721 of 2000 complete in 743.3 sec
[-----------------86%------------      ] 1723 of 2000 complete in 744.1 sec
[-----------------86%------------      ] 1725 of 2000 complete in 745.0 sec
[-----------------86%------------      ] 1727 of 2000 complete in 745.8 sec
[-----------------86%------------      ] 1729 of 2000 complete in 746.7 sec
[-----------------86%------------      ] 1731 of 2000 complete in 747.6 sec
[-----------------86%------------      ] 1733 of 2000 complete in 748.5 sec
[-----------------86%------------      ] 1735 of 2000 complete in 749.3 sec
[-----------------86%-------------     ] 1737 of 2000 complete in 750.2 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 751.1 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 751.9 sec
[-----------------87%-------------     ] 1743 of 2000 complete in 752.8 sec
[-----------------87%-------------     ] 1745 of 2000 complete in 753.7 sec
[-----------------87%-------------     ] 1747 of 2000 complete in 754.6 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 755.5 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 756.3 sec
[-----------------87%-------------     ] 1753 of 2000 complete in 757.2 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 758.0 sec
[-----------------87%-------------     ] 1757 of 2000 complete in 758.9 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 759.8 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 760.7 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 761.6 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 762.4 sec
[-----------------88%-------------     ] 1767 of 2000 complete in 763.3 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 764.1 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 765.0 sec
[-----------------88%-------------     ] 1773 of 2000 complete in 765.8 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 766.7 sec
[-----------------88%-------------     ] 1777 of 2000 complete in 767.5 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 768.4 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 769.4 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 770.3 sec
[-----------------89%-------------     ] 1785 of 2000 complete in 771.1 sec
[-----------------89%-------------     ] 1787 of 2000 complete in 772.0 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 772.9 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 773.8 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 774.6 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 775.4 sec
[-----------------89%--------------    ] 1797 of 2000 complete in 776.3 sec
[-----------------89%--------------    ] 1799 of 2000 complete in 777.1 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 777.9 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 778.7 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 779.6 sec
[-----------------90%--------------    ] 1807 of 2000 complete in 780.4 sec
[-----------------90%--------------    ] 1809 of 2000 complete in 781.3 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 782.1 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 783.0 sec
[-----------------90%--------------    ] 1815 of 2000 complete in 783.8 sec
[-----------------90%--------------    ] 1817 of 2000 complete in 784.6 sec
[-----------------90%--------------    ] 1819 of 2000 complete in 785.6 sec
[-----------------91%--------------    ] 1821 of 2000 complete in 786.5 sec
[-----------------91%--------------    ] 1822 of 2000 complete in 787.0 sec
[-----------------91%--------------    ] 1824 of 2000 complete in 788.0 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 788.9 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 789.8 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 790.7 sec
[-----------------91%--------------    ] 1832 of 2000 complete in 791.5 sec
[-----------------91%--------------    ] 1834 of 2000 complete in 792.4 sec
[-----------------91%--------------    ] 1836 of 2000 complete in 793.2 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 794.1 sec
[-----------------92%--------------    ] 1840 of 2000 complete in 794.9 sec
[-----------------92%--------------    ] 1842 of 2000 complete in 795.7 sec
[-----------------92%---------------   ] 1844 of 2000 complete in 796.6 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 797.5 sec
[-----------------92%---------------   ] 1848 of 2000 complete in 798.3 sec
[-----------------92%---------------   ] 1850 of 2000 complete in 799.3 sec
[-----------------92%---------------   ] 1852 of 2000 complete in 800.2 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 801.1 sec
[-----------------92%---------------   ] 1856 of 2000 complete in 801.9 sec
[-----------------92%---------------   ] 1858 of 2000 complete in 802.8 sec
[-----------------92%---------------   ] 1859 of 2000 complete in 803.3 sec
[-----------------93%---------------   ] 1860 of 2000 complete in 803.9 sec
[-----------------93%---------------   ] 1862 of 2000 complete in 804.8 sec
[-----------------93%---------------   ] 1864 of 2000 complete in 805.9 sec
[-----------------93%---------------   ] 1865 of 2000 complete in 806.4 sec
[-----------------93%---------------   ] 1867 of 2000 complete in 807.4 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 807.9 sec
[-----------------93%---------------   ] 1870 of 2000 complete in 808.9 sec
[-----------------93%---------------   ] 1872 of 2000 complete in 809.9 sec
[-----------------93%---------------   ] 1874 of 2000 complete in 810.8 sec
[-----------------93%---------------   ] 1876 of 2000 complete in 811.7 sec
[-----------------93%---------------   ] 1878 of 2000 complete in 812.6 sec
[-----------------94%---------------   ] 1880 of 2000 complete in 813.4 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 814.3 sec
[-----------------94%---------------   ] 1884 of 2000 complete in 815.2 sec
[-----------------94%---------------   ] 1886 of 2000 complete in 816.1 sec
[-----------------94%---------------   ] 1888 of 2000 complete in 817.0 sec
[-----------------94%---------------   ] 1889 of 2000 complete in 817.5 sec
[-----------------94%---------------   ] 1890 of 2000 complete in 818.0 sec
[-----------------94%---------------   ] 1891 of 2000 complete in 818.5 sec
[-----------------94%---------------   ] 1893 of 2000 complete in 819.5 sec
[-----------------94%----------------  ] 1895 of 2000 complete in 820.4 sec
[-----------------94%----------------  ] 1897 of 2000 complete in 821.3 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 821.9 sec
[-----------------95%----------------  ] 1900 of 2000 complete in 822.8 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 823.6 sec
[-----------------95%----------------  ] 1904 of 2000 complete in 824.5 sec
[-----------------95%----------------  ] 1906 of 2000 complete in 825.3 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 826.2 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 827.1 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 828.0 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 828.9 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 829.8 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 830.7 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 831.5 sec

[-----------------86%------------      ] 1725 of 2000 complete in 744.2 sec
[-----------------86%------------      ] 1727 of 2000 complete in 745.0 sec
[-----------------86%------------      ] 1729 of 2000 complete in 745.9 sec
[-----------------86%------------      ] 1731 of 2000 complete in 746.7 sec
[-----------------86%------------      ] 1733 of 2000 complete in 747.5 sec
[-----------------86%------------      ] 1735 of 2000 complete in 748.4 sec
[-----------------86%-------------     ] 1737 of 2000 complete in 749.3 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 750.1 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 751.0 sec
[-----------------87%-------------     ] 1743 of 2000 complete in 751.8 sec
[-----------------87%-------------     ] 1745 of 2000 complete in 752.7 sec
[-----------------87%-------------     ] 1747 of 2000 complete in 753.6 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 754.5 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 755.3 sec
[-----------------87%-------------     ] 1753 of 2000 complete in 756.2 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 757.0 sec
[-----------------87%-------------     ] 1757 of 2000 complete in 757.9 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 758.7 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 759.6 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 760.6 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 761.4 sec
[-----------------88%-------------     ] 1767 of 2000 complete in 762.3 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 763.1 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 764.0 sec
[-----------------88%-------------     ] 1773 of 2000 complete in 764.8 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 765.7 sec
[-----------------88%-------------     ] 1777 of 2000 complete in 766.6 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 767.4 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 768.3 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 769.2 sec
[-----------------89%-------------     ] 1785 of 2000 complete in 770.2 sec
[-----------------89%-------------     ] 1787 of 2000 complete in 771.0 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 771.9 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 772.7 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 773.6 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 774.4 sec
[-----------------89%--------------    ] 1797 of 2000 complete in 775.2 sec
[-----------------89%--------------    ] 1799 of 2000 complete in 776.1 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 776.9 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 777.8 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 778.6 sec
[-----------------90%--------------    ] 1807 of 2000 complete in 779.4 sec
[-----------------90%--------------    ] 1809 of 2000 complete in 780.3 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 781.1 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 782.0 sec
[-----------------90%--------------    ] 1815 of 2000 complete in 782.8 sec
[-----------------90%--------------    ] 1817 of 2000 complete in 783.6 sec
[-----------------90%--------------    ] 1819 of 2000 complete in 784.5 sec
[-----------------91%--------------    ] 1821 of 2000 complete in 785.4 sec
[-----------------91%--------------    ] 1823 of 2000 complete in 786.3 sec
[-----------------91%--------------    ] 1825 of 2000 complete in 787.3 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 787.8 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 788.7 sec
[-----------------91%--------------    ] 1829 of 2000 complete in 789.2 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 789.7 sec
[-----------------91%--------------    ] 1832 of 2000 complete in 790.6 sec
[-----------------91%--------------    ] 1834 of 2000 complete in 791.4 sec
[-----------------91%--------------    ] 1836 of 2000 complete in 792.3 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 793.1 sec
[-----------------92%--------------    ] 1840 of 2000 complete in 793.9 sec
[-----------------92%--------------    ] 1842 of 2000 complete in 794.8 sec
[-----------------92%---------------   ] 1844 of 2000 complete in 795.6 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 796.4 sec
[-----------------92%---------------   ] 1847 of 2000 complete in 796.9 sec
[-----------------92%---------------   ] 1849 of 2000 complete in 797.7 sec
[-----------------92%---------------   ] 1851 of 2000 complete in 798.6 sec
[-----------------92%---------------   ] 1852 of 2000 complete in 799.1 sec
[-----------------92%---------------   ] 1853 of 2000 complete in 799.6 sec
[-----------------92%---------------   ] 1855 of 2000 complete in 800.5 sec
[-----------------92%---------------   ] 1857 of 2000 complete in 801.4 sec
[-----------------92%---------------   ] 1859 of 2000 complete in 802.2 sec
[-----------------93%---------------   ] 1861 of 2000 complete in 803.1 sec
[-----------------93%---------------   ] 1862 of 2000 complete in 803.7 sec
[-----------------93%---------------   ] 1863 of 2000 complete in 804.3 sec
[-----------------93%---------------   ] 1865 of 2000 complete in 805.2 sec
[-----------------93%---------------   ] 1866 of 2000 complete in 805.7 sec
[-----------------93%---------------   ] 1867 of 2000 complete in 806.2 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 806.7 sec
[-----------------93%---------------   ] 1870 of 2000 complete in 807.7 sec
[-----------------93%---------------   ] 1872 of 2000 complete in 808.7 sec
[-----------------93%---------------   ] 1873 of 2000 complete in 809.2 sec
[-----------------93%---------------   ] 1875 of 2000 complete in 810.2 sec
[-----------------93%---------------   ] 1877 of 2000 complete in 811.1 sec
[-----------------93%---------------   ] 1879 of 2000 complete in 812.0 sec
[-----------------94%---------------   ] 1881 of 2000 complete in 812.9 sec
[-----------------94%---------------   ] 1883 of 2000 complete in 813.7 sec
[-----------------94%---------------   ] 1885 of 2000 complete in 814.5 sec
[-----------------94%---------------   ] 1887 of 2000 complete in 815.4 sec
[-----------------94%---------------   ] 1889 of 2000 complete in 816.3 sec
[-----------------94%---------------   ] 1891 of 2000 complete in 817.2 sec
[-----------------94%---------------   ] 1893 of 2000 complete in 818.3 sec
[-----------------94%----------------  ] 1895 of 2000 complete in 819.2 sec
[-----------------94%----------------  ] 1897 of 2000 complete in 820.1 sec
[-----------------94%----------------  ] 1899 of 2000 complete in 821.0 sec
[-----------------95%----------------  ] 1901 of 2000 complete in 822.0 sec
[-----------------95%----------------  ] 1903 of 2000 complete in 822.9 sec
[-----------------95%----------------  ] 1905 of 2000 complete in 823.7 sec
[-----------------95%----------------  ] 1907 of 2000 complete in 824.6 sec
[-----------------95%----------------  ] 1909 of 2000 complete in 825.5 sec
[-----------------95%----------------  ] 1911 of 2000 complete in 826.4 sec
[-----------------95%----------------  ] 1913 of 2000 complete in 827.3 sec
[-----------------95%----------------  ] 1915 of 2000 complete in 828.2 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 829.1 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 829.9 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 830.8 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 831.6 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 832.5 sec
hddm sampling elpased time:  897.775 s
Start converting to InferenceData...

In [28]:
az.summary(hddmReg_id_m0_acc_diff_idata)

,mean,sd,hdi_3%,hdi_97%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
a,1.538,0.048,1.450,1.629,0.002,0.001,1044.0,2453.0,1.00
a_std,0.283,0.041,0.213,0.362,0.002,0.002,321.0,1548.0,1.01
a_subj.7304,1.564,0.079,1.413,1.714,0.004,0.002,495.0,977.0,1.01
a_subj.7305,1.758,0.085,1.609,1.925,0.003,0.002,653.0,1276.0,1.00
a_subj.7306,1.495,0.077,1.358,1.645,0.003,0.002,619.0,1058.0,1.00
...,...,...,...,...,...,...,...,...,...
v_Intercept_subj(Self.1).7342,3.324,0.212,2.924,3.727,0.006,0.004,1419.0,2572.0,1.00
v_Intercept_subj(Self.1).7343,4.236,0.259,3.736,4.699,0.009,0.006,870.0,1574.0,1.00
v_Intercept_subj(Self.1).7344,4.016,0.240,3.578,4.481,0.005,0.004,1993.0,3372.0,1.00
v_Intercept_subj(Self.1).7345,4.235,0.239,3.795,4.690,0.006,0.004,1723.0,3214.0,1.00
v_Intercept_subj(Self.1).73370,4.002,0.260,3.514,4.489,0.011,0.008,562.0,947.0,1.00

In [29]:
hddmReg_id_m0_acc_diff_stats = hddmReg_id_m0_acc_diff.gen_stats()
hddmReg_id_m0_acc_diff_stats[hddmReg_id_m0_acc_diff_stats.index.isin(['a', 'z', 'v_Intercept(Self.1)','v_Intercept(Other.1)',
                                                     'v_Intercept(Self.0)','v_Intercept(Other.0)'])]

,mean,std,2.5q,25q,50q,75q,97.5q,mc err
a,1.53848,0.048042,1.449743,1.504477,1.537449,1.570085,1.635752,0.001335
z,0.334762,0.007064,0.321119,0.329907,0.334697,0.339465,0.348748,0.000369
v_Intercept(Other.0),3.380037,0.141629,3.101698,3.287635,3.381873,3.475266,3.653325,0.002485
v_Intercept(Self.1),3.867435,0.142979,3.585582,3.770739,3.865179,3.963057,4.15388,0.002692

In [33]:
# choice coding
data['response'] = data['choice']

v_reg = [{"model": "v ~ 1", "link_func": lambda x: x}]

hddmReg_id_m2_choice_diff = hddm.HDDMRegressor(
    data,
    v_reg,
    bias=True, p_outlier=0.05,
    include=['v', 'a', 't', 'z'],
    depends_on={'v':['id']},
    group_only_regressors=False
)

hddmReg_id_m2_choice_diff_idata = hddmReg_id_m2_choice_diff.sample(2000, burn=500, chains=4, return_infdata=True, dbname = 'hddmReg_id_m2_choice_diff.db', db = 'pickle')
hddmReg_id_m2_choice_diff.save('hddmReg_id_m2_choice_diff.hddm')

No model attribute --> setting up standard HDDM
Set model to ddm

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

[                  0%                  ] 2 of 2000 complete in 0.8 sec
[                  0%                  ] 3 of 2000 complete in 1.9 sec
[                  0%                  ] 4 of 2000 complete in 2.7 sec
[                  0%                  ] 5 of 2000 complete in 3.2 sec
[                  0%                  ] 7 of 2000 complete in 4.2 sec
[                  0%                  ] 9 of 2000 complete in 5.0 sec
[                  0%                  ] 11 of 2000 complete in 5.9 sec
[                  0%                  ] 13 of 2000 complete in 6.7 sec
[                  0%                  ] 15 of 2000 complete in 7.6 sec
[                  0%                  ] 17 of 2000 complete in 8.4 sec
[                  0%                  ] 19 of 2000 complete in 9.3 sec
[                  1%                  ] 21 of 2000 complete in 10.1 sec
[                  1%                  ] 22 of 2000 complete in 10.6 sec
[                  1%                  ] 24 of 2000 complete in 11.5 sec
[                  1%                  ] 26 of 2000 complete in 12.4 sec
[                  1%                  ] 28 of 2000 complete in 13.2 sec
[                  1%                  ] 30 of 2000 complete in 14.0 sec
[                  1%                  ] 32 of 2000 complete in 14.9 sec
[                  1%                  ] 34 of 2000 complete in 15.7 sec
[                  1%                  ] 36 of 2000 complete in 16.6 sec
[                  1%                  ] 38 of 2000 complete in 17.4 sec
[                  2%                  ] 40 of 2000 complete in 18.2 sec
[                  2%                  ] 42 of 2000 complete in 19.0 sec
[                  2%                  ] 44 of 2000 complete in 19.9 sec
[                  2%                  ] 46 of 2000 complete in 20.7 sec
[                  2%                  ] 48 of 2000 complete in 21.5 sec
[                  2%                  ] 50 of 2000 complete in 22.4 sec
[                  2%                  ] 52 of 2000 complete in 23.3 sec
[-                 2%                  ] 54 of 2000 complete in 24.2 sec
[-                 2%                  ] 56 of 2000 complete in 25.1 sec
[-                 2%                  ] 58 of 2000 complete in 26.1 sec
[-                 2%                  ] 59 of 2000 complete in 26.7 sec
[-                 3%                  ] 60 of 2000 complete in 27.2 sec
[-                 3%                  ] 62 of 2000 complete in 28.1 sec
[-                 3%                  ] 64 of 2000 complete in 28.9 sec
[-                 3%                  ] 66 of 2000 complete in 29.7 sec
[-                 3%                  ] 68 of 2000 complete in 30.6 sec
[-                 3%                  ] 70 of 2000 complete in 31.4 sec
[-                 3%                  ] 72 of 2000 complete in 32.3 sec
[-                 3%                  ] 74 of 2000 complete in 33.1 sec
[-                 3%                  ] 76 of 2000 complete in 34.0 sec
[-                 3%                  ] 78 of 2000 complete in 34.8 sec
[-                 4%                  ] 80 of 2000 complete in 35.6 sec
[-                 4%                  ] 82 of 2000 complete in 36.5 sec
[-                 4%                  ] 84 of 2000 complete in 37.3 sec
[-                 4%                  ] 86 of 2000 complete in 38.2 sec
[-                 4%                  ] 88 of 2000 complete in 39.1 sec
[-                 4%                  ] 90 of 2000 complete in 40.1 sec
[-                 4%                  ] 92 of 2000 complete in 41.0 sec
[-                 4%                  ] 94 of 2000 complete in 41.8 sec
[-                 4%                  ] 96 of 2000 complete in 42.7 sec
[-                 4%                  ] 98 of 2000 complete in 43.5 sec
[-                 5%                  ] 100 of 2000 complete in 44.4 sec
[-                 5%                  ] 102 of 2000 complete in 45.2 sec
[-                 5%                  ] 104 of 2000 complete in 46.0 sec
[--                5%                  ] 106 of 2000 complete in 46.9 sec
[--                5%                  ] 108 of 2000 complete in 47.7 sec
[--                5%                  ] 110 of 2000 complete in 48.6 sec
[--                5%                  ] 112 of 2000 complete in 49.4 sec
[--                5%                  ] 114 of 2000 complete in 50.3 sec
[--                5%                  ] 116 of 2000 complete in 51.1 sec
[--                5%                  ] 118 of 2000 complete in 51.9 sec
[--                6%                  ] 120 of 2000 complete in 52.7 sec
[--                6%                  ] 122 of 2000 complete in 53.6 sec
[--                6%                  ] 124 of 2000 complete in 54.5 sec
[--                6%                  ] 126 of 2000 complete in 55.4 sec
[--                6%                  ] 128 of 2000 complete in 56.3 sec
[--                6%                  ] 130 of 2000 complete in 57.2 sec
[--                6%                  ] 132 of 2000 complete in 58.0 sec
[--                6%                  ] 134 of 2000 complete in 58.9 sec
[--                6%                  ] 136 of 2000 complete in 59.7 sec
[--                6%                  ] 138 of 2000 complete in 60.5 sec
[--                7%                  ] 140 of 2000 complete in 61.3 sec
[--                7%                  ] 142 of 2000 complete in 62.2 sec
[--                7%                  ] 144 of 2000 complete in 63.0 sec
[--                7%                  ] 146 of 2000 complete in 63.9 sec
[--                7%                  ] 148 of 2000 complete in 64.7 sec
[--                7%                  ] 150 of 2000 complete in 65.5 sec
[--                7%                  ] 152 of 2000 complete in 66.4 sec
[--                7%                  ] 154 of 2000 complete in 67.2 sec
[--                7%                  ] 156 of 2000 complete in 68.0 sec
[---               7%                  ] 158 of 2000 complete in 68.8 sec
[---               8%                  ] 160 of 2000 complete in 69.7 sec
[---               8%                  ] 162 of 2000 complete in 70.6 sec
[---               8%                  ] 164 of 2000 complete in 71.4 sec
[---               8%                  ] 166 of 2000 complete in 72.3 sec
[---               8%                  ] 168 of 2000 complete in 73.3 sec
[---               8%                  ] 170 of 2000 complete in 74.1 sec
[---               8%                  ] 172 of 2000 complete in 75.0 sec
[---               8%                  ] 174 of 2000 complete in 75.8 sec
[---               8%                  ] 176 of 2000 complete in 76.6 sec
[---               8%                  ] 178 of 2000 complete in 77.4 sec
[---               9%                  ] 180 of 2000 complete in 78.2 sec
[---               9%                  ] 182 of 2000 complete in 79.0 sec
[---               9%                  ] 184 of 2000 complete in 79.9 sec
[---               9%                  ] 186 of 2000 complete in 80.7 sec
[---               9%                  ] 188 of 2000 complete in 81.5 sec
[---               9%                  ] 190 of 2000 complete in 82.3 sec
[---               9%                  ] 192 of 2000 complete in 83.2 sec
[---               9%                  ] 194 of 2000 complete in 84.0 sec
[---               9%                  ] 196 of 2000 complete in 84.8 sec
[---               9%                  ] 198 of 2000 complete in 85.6 sec
[---              10%                  ] 200 of 2000 complete in 86.5 sec
[---              10%                  ] 202 of 2000 complete in 87.3 sec
[---              10%                  ] 204 of 2000 complete in 88.1 sec
[---              10%                  ] 206 of 2000 complete in 89.0 sec
[---              10%                  ] 208 of 2000 complete in 89.8 sec
[---              10%                  ] 210 of 2000 complete in 90.7 sec
[----             10%                  ] 212 of 2000 complete in 91.5 sec
[----             10%                  ] 214 of 2000 complete in 92.3 sec
[----             10%                  ] 216 of 2000 complete in 93.1 sec
[                  0%                  ] 2 of 2000 complete in 1.4 sec
[                  0%                  ] 3 of 2000 complete in 2.2 sec
[                  0%                  ] 4 of 2000 complete in 2.8 sec
[                  0%                  ] 5 of 2000 complete in 3.4 sec
[                  0%                  ] 7 of 2000 complete in 4.3 sec
[                  0%                  ] 9 of 2000 complete in 5.1 sec
[                  0%                  ] 11 of 2000 complete in 6.0 sec
[                  0%                  ] 13 of 2000 complete in 6.9 sec
[                  0%                  ] 15 of 2000 complete in 7.7 sec
[                  0%                  ] 17 of 2000 complete in 8.5 sec
[                  0%                  ] 19 of 2000 complete in 9.4 sec
[                  1%                  ] 21 of 2000 complete in 10.2 sec
[                  1%                  ] 23 of 2000 complete in 11.2 sec
[                  1%                  ] 25 of 2000 complete in 12.0 sec
[                  1%                  ] 27 of 2000 complete in 12.9 sec
[                  1%                  ] 29 of 2000 complete in 13.8 sec
[                  1%                  ] 31 of 2000 complete in 14.6 sec
[                  1%                  ] 33 of 2000 complete in 15.5 sec
[                  1%                  ] 35 of 2000 complete in 16.3 sec
[                  1%                  ] 37 of 2000 complete in 17.1 sec
[                  1%                  ] 39 of 2000 complete in 17.9 sec
[                  2%                  ] 41 of 2000 complete in 18.8 sec
[                  2%                  ] 43 of 2000 complete in 19.6 sec
[                  2%                  ] 45 of 2000 complete in 20.5 sec
[                  2%                  ] 47 of 2000 complete in 21.3 sec
[                  2%                  ] 49 of 2000 complete in 22.2 sec
[                  2%                  ] 51 of 2000 complete in 23.0 sec
[-                 2%                  ] 53 of 2000 complete in 23.9 sec
[-                 2%                  ] 55 of 2000 complete in 24.8 sec
[-                 2%                  ] 57 of 2000 complete in 25.7 sec
[-                 2%                  ] 59 of 2000 complete in 26.7 sec
[-                 3%                  ] 60 of 2000 complete in 27.2 sec
[-                 3%                  ] 62 of 2000 complete in 28.1 sec
[-                 3%                  ] 64 of 2000 complete in 28.9 sec
[-                 3%                  ] 66 of 2000 complete in 29.8 sec
[-                 3%                  ] 68 of 2000 complete in 30.6 sec
[-                 3%                  ] 70 of 2000 complete in 31.4 sec
[-                 3%                  ] 72 of 2000 complete in 32.3 sec
[-                 3%                  ] 74 of 2000 complete in 33.2 sec
[-                 3%                  ] 76 of 2000 complete in 34.0 sec
[-                 3%                  ] 78 of 2000 complete in 34.9 sec
[-                 4%                  ] 80 of 2000 complete in 35.7 sec
[-                 4%                  ] 82 of 2000 complete in 36.5 sec
[-                 4%                  ] 84 of 2000 complete in 37.4 sec
[-                 4%                  ] 86 of 2000 complete in 38.3 sec
[-                 4%                  ] 88 of 2000 complete in 39.2 sec
[-                 4%                  ] 90 of 2000 complete in 40.2 sec
[-                 4%                  ] 92 of 2000 complete in 41.1 sec
[-                 4%                  ] 94 of 2000 complete in 42.0 sec
[-                 4%                  ] 96 of 2000 complete in 42.8 sec
[-                 4%                  ] 98 of 2000 complete in 43.6 sec
[-                 5%                  ] 100 of 2000 complete in 44.4 sec
[-                 5%                  ] 102 of 2000 complete in 45.2 sec
[-                 5%                  ] 104 of 2000 complete in 46.1 sec
[--                5%                  ] 106 of 2000 complete in 46.9 sec
[--                5%                  ] 108 of 2000 complete in 47.8 sec
[--                5%                  ] 110 of 2000 complete in 48.6 sec
[--                5%                  ] 112 of 2000 complete in 49.5 sec
[--                5%                  ] 114 of 2000 complete in 50.3 sec
[--                5%                  ] 116 of 2000 complete in 51.1 sec
[--                5%                  ] 118 of 2000 complete in 52.0 sec
[--                6%                  ] 120 of 2000 complete in 52.8 sec
[--                6%                  ] 122 of 2000 complete in 53.7 sec
[--                6%                  ] 124 of 2000 complete in 54.6 sec
[--                6%                  ] 126 of 2000 complete in 55.4 sec
[--                6%                  ] 128 of 2000 complete in 56.3 sec
[--                6%                  ] 130 of 2000 complete in 57.2 sec
[--                6%                  ] 132 of 2000 complete in 58.0 sec
[--                6%                  ] 134 of 2000 complete in 58.8 sec
[--                6%                  ] 136 of 2000 complete in 59.6 sec
[--                6%                  ] 138 of 2000 complete in 60.4 sec
[--                7%                  ] 140 of 2000 complete in 61.3 sec
[--                7%                  ] 142 of 2000 complete in 62.1 sec
[--                7%                  ] 144 of 2000 complete in 63.0 sec
[--                7%                  ] 146 of 2000 complete in 63.8 sec
[--                7%                  ] 148 of 2000 complete in 64.6 sec
[--                7%                  ] 150 of 2000 complete in 65.5 sec
[--                7%                  ] 152 of 2000 complete in 66.3 sec
[--                7%                  ] 154 of 2000 complete in 67.1 sec
[--                7%                  ] 156 of 2000 complete in 68.0 sec
[---               7%                  ] 158 of 2000 complete in 68.8 sec
[---               8%                  ] 160 of 2000 complete in 69.7 sec
[---               8%                  ] 162 of 2000 complete in 70.5 sec
[---               8%                  ] 164 of 2000 complete in 71.4 sec
[---               8%                  ] 166 of 2000 complete in 72.3 sec
[---               8%                  ] 168 of 2000 complete in 73.2 sec
[---               8%                  ] 170 of 2000 complete in 74.1 sec
[---               8%                  ] 172 of 2000 complete in 74.9 sec
[---               8%                  ] 174 of 2000 complete in 75.8 sec
[---               8%                  ] 176 of 2000 complete in 76.6 sec
[---               8%                  ] 178 of 2000 complete in 77.4 sec
[---               9%                  ] 180 of 2000 complete in 78.2 sec
[---               9%                  ] 182 of 2000 complete in 79.1 sec
[---               9%                  ] 184 of 2000 complete in 79.9 sec
[---               9%                  ] 186 of 2000 complete in 80.8 sec
[---               9%                  ] 188 of 2000 complete in 81.6 sec
[---               9%                  ] 190 of 2000 complete in 82.4 sec
[---               9%                  ] 192 of 2000 complete in 83.3 sec
[---               9%                  ] 194 of 2000 complete in 84.1 sec
[---               9%                  ] 196 of 2000 complete in 85.0 sec
[---               9%                  ] 198 of 2000 complete in 85.8 sec
[---              10%                  ] 200 of 2000 complete in 86.6 sec
[---              10%                  ] 202 of 2000 complete in 87.4 sec
[---              10%                  ] 204 of 2000 complete in 88.2 sec
[---              10%                  ] 206 of 2000 complete in 89.1 sec
[---              10%                  ] 208 of 2000 complete in 89.8 sec
[---              10%                  ] 210 of 2000 complete in 90.7 sec
[----             10%                  ] 212 of 2000 complete in 91.5 sec
[----             10%                  ] 214 of 2000 complete in 92.3 sec
[----             10%                  ] 216 of 2000 complete in 93.2 sec
[----             10%                  ] 218 of 2000 complete in 94.1 sec

[                  0%                  ] 2 of 2000 complete in 0.9 sec
[                  0%                  ] 3 of 2000 complete in 1.9 sec
[                  0%                  ] 4 of 2000 complete in 2.7 sec
[                  0%                  ] 5 of 2000 complete in 3.2 sec
[                  0%                  ] 7 of 2000 complete in 4.1 sec
[                  0%                  ] 9 of 2000 complete in 5.0 sec
[                  0%                  ] 11 of 2000 complete in 5.9 sec
[                  0%                  ] 13 of 2000 complete in 6.8 sec
[                  0%                  ] 15 of 2000 complete in 7.6 sec
[                  0%                  ] 17 of 2000 complete in 8.5 sec
[                  0%                  ] 19 of 2000 complete in 9.4 sec
[                  1%                  ] 21 of 2000 complete in 10.3 sec
[                  1%                  ] 22 of 2000 complete in 10.8 sec
[                  1%                  ] 24 of 2000 complete in 11.7 sec
[                  1%                  ] 26 of 2000 complete in 12.6 sec
[                  1%                  ] 28 of 2000 complete in 13.5 sec
[                  1%                  ] 30 of 2000 complete in 14.4 sec
[                  1%                  ] 32 of 2000 complete in 15.3 sec
[                  1%                  ] 34 of 2000 complete in 16.1 sec
[                  1%                  ] 36 of 2000 complete in 17.0 sec
[                  1%                  ] 38 of 2000 complete in 17.9 sec
[                  2%                  ] 40 of 2000 complete in 18.7 sec
[                  2%                  ] 42 of 2000 complete in 19.6 sec
[                  2%                  ] 44 of 2000 complete in 20.4 sec
[                  2%                  ] 46 of 2000 complete in 21.3 sec
[                  2%                  ] 48 of 2000 complete in 22.1 sec
[                  2%                  ] 50 of 2000 complete in 23.0 sec
[                  2%                  ] 52 of 2000 complete in 23.9 sec
[-                 2%                  ] 54 of 2000 complete in 24.8 sec
[-                 2%                  ] 55 of 2000 complete in 25.3 sec
[-                 2%                  ] 57 of 2000 complete in 26.3 sec
[-                 2%                  ] 58 of 2000 complete in 26.8 sec
[-                 2%                  ] 59 of 2000 complete in 27.4 sec
[-                 3%                  ] 61 of 2000 complete in 28.2 sec
[-                 3%                  ] 63 of 2000 complete in 29.1 sec
[-                 3%                  ] 65 of 2000 complete in 30.0 sec
[-                 3%                  ] 67 of 2000 complete in 30.8 sec
[-                 3%                  ] 69 of 2000 complete in 31.7 sec
[-                 3%                  ] 71 of 2000 complete in 32.6 sec
[-                 3%                  ] 73 of 2000 complete in 33.5 sec
[-                 3%                  ] 75 of 2000 complete in 34.4 sec
[-                 3%                  ] 77 of 2000 complete in 35.2 sec
[-                 3%                  ] 79 of 2000 complete in 36.1 sec
[-                 4%                  ] 81 of 2000 complete in 36.9 sec
[-                 4%                  ] 83 of 2000 complete in 37.9 sec
[-                 4%                  ] 85 of 2000 complete in 38.8 sec
[-                 4%                  ] 87 of 2000 complete in 39.8 sec
[-                 4%                  ] 89 of 2000 complete in 40.7 sec
[-                 4%                  ] 91 of 2000 complete in 41.6 sec
[-                 4%                  ] 93 of 2000 complete in 42.5 sec
[-                 4%                  ] 95 of 2000 complete in 43.4 sec
[-                 4%                  ] 97 of 2000 complete in 44.2 sec
[-                 4%                  ] 99 of 2000 complete in 45.1 sec
[-                 5%                  ] 101 of 2000 complete in 46.0 sec
[-                 5%                  ] 103 of 2000 complete in 46.8 sec
[-                 5%                  ] 105 of 2000 complete in 47.7 sec
[--                5%                  ] 107 of 2000 complete in 48.6 sec
[--                5%                  ] 109 of 2000 complete in 49.5 sec
[--                5%                  ] 111 of 2000 complete in 50.3 sec
[--                5%                  ] 113 of 2000 complete in 51.2 sec
[--                5%                  ] 115 of 2000 complete in 52.0 sec
[--                5%                  ] 117 of 2000 complete in 52.8 sec
[--                5%                  ] 119 of 2000 complete in 53.7 sec
[--                6%                  ] 121 of 2000 complete in 54.6 sec
[--                6%                  ] 123 of 2000 complete in 55.5 sec
[--                6%                  ] 125 of 2000 complete in 56.4 sec
[--                6%                  ] 127 of 2000 complete in 57.3 sec
[--                6%                  ] 129 of 2000 complete in 58.1 sec
[--                6%                  ] 131 of 2000 complete in 59.0 sec
[--                6%                  ] 133 of 2000 complete in 59.8 sec
[--                6%                  ] 135 of 2000 complete in 60.7 sec
[--                6%                  ] 137 of 2000 complete in 61.6 sec
[--                6%                  ] 139 of 2000 complete in 62.4 sec
[--                7%                  ] 141 of 2000 complete in 63.3 sec
[--                7%                  ] 143 of 2000 complete in 64.2 sec
[--                7%                  ] 145 of 2000 complete in 65.0 sec
[--                7%                  ] 147 of 2000 complete in 65.9 sec
[--                7%                  ] 149 of 2000 complete in 66.7 sec
[--                7%                  ] 151 of 2000 complete in 67.6 sec
[--                7%                  ] 153 of 2000 complete in 68.4 sec
[--                7%                  ] 155 of 2000 complete in 69.3 sec
[--                7%                  ] 157 of 2000 complete in 70.1 sec
[---               7%                  ] 159 of 2000 complete in 71.0 sec
[---               8%                  ] 161 of 2000 complete in 71.9 sec
[---               8%                  ] 162 of 2000 complete in 72.4 sec
[---               8%                  ] 164 of 2000 complete in 73.4 sec
[---               8%                  ] 166 of 2000 complete in 74.3 sec
[---               8%                  ] 168 of 2000 complete in 75.1 sec
[---               8%                  ] 170 of 2000 complete in 76.0 sec
[---               8%                  ] 172 of 2000 complete in 76.9 sec
[---               8%                  ] 174 of 2000 complete in 77.7 sec
[---               8%                  ] 176 of 2000 complete in 78.6 sec
[---               8%                  ] 178 of 2000 complete in 79.4 sec
[---               9%                  ] 180 of 2000 complete in 80.2 sec
[---               9%                  ] 182 of 2000 complete in 81.1 sec
[---               9%                  ] 184 of 2000 complete in 81.9 sec
[---               9%                  ] 186 of 2000 complete in 82.7 sec
[---               9%                  ] 188 of 2000 complete in 83.6 sec
[---               9%                  ] 190 of 2000 complete in 84.4 sec
[---               9%                  ] 192 of 2000 complete in 85.2 sec
[---               9%                  ] 194 of 2000 complete in 86.1 sec
[---               9%                  ] 196 of 2000 complete in 86.9 sec
[---               9%                  ] 198 of 2000 complete in 87.8 sec
[---              10%                  ] 200 of 2000 complete in 88.6 sec
[---              10%                  ] 202 of 2000 complete in 89.4 sec
[---              10%                  ] 204 of 2000 complete in 90.3 sec
[---              10%                  ] 206 of 2000 complete in 91.1 sec
[---              10%                  ] 208 of 2000 complete in 92.0 sec
[---              10%                  ] 210 of 2000 complete in 92.8 sec
[----             10%                  ] 212 of 2000 complete in 93.7 sec
[----             10%                  ] 214 of 2000 complete in 94.6 sec
[                  0%                  ] 2 of 2000 complete in 0.8 sec
[                  0%                  ] 3 of 2000 complete in 1.9 sec
[                  0%                  ] 4 of 2000 complete in 2.6 sec
[                  0%                  ] 5 of 2000 complete in 3.2 sec
[                  0%                  ] 7 of 2000 complete in 4.1 sec
[                  0%                  ] 9 of 2000 complete in 5.0 sec
[                  0%                  ] 11 of 2000 complete in 5.9 sec
[                  0%                  ] 13 of 2000 complete in 6.8 sec
[                  0%                  ] 15 of 2000 complete in 7.6 sec
[                  0%                  ] 17 of 2000 complete in 8.5 sec
[                  0%                  ] 19 of 2000 complete in 9.4 sec
[                  1%                  ] 21 of 2000 complete in 10.3 sec
[                  1%                  ] 23 of 2000 complete in 11.2 sec
[                  1%                  ] 25 of 2000 complete in 12.1 sec
[                  1%                  ] 27 of 2000 complete in 13.0 sec
[                  1%                  ] 29 of 2000 complete in 13.9 sec
[                  1%                  ] 31 of 2000 complete in 14.7 sec
[                  1%                  ] 33 of 2000 complete in 15.6 sec
[                  1%                  ] 35 of 2000 complete in 16.5 sec
[                  1%                  ] 37 of 2000 complete in 17.3 sec
[                  1%                  ] 39 of 2000 complete in 18.1 sec
[                  2%                  ] 41 of 2000 complete in 19.0 sec
[                  2%                  ] 43 of 2000 complete in 19.8 sec
[                  2%                  ] 45 of 2000 complete in 20.7 sec
[                  2%                  ] 47 of 2000 complete in 21.5 sec
[                  2%                  ] 49 of 2000 complete in 22.4 sec
[                  2%                  ] 51 of 2000 complete in 23.3 sec
[-                 2%                  ] 53 of 2000 complete in 24.2 sec
[-                 2%                  ] 55 of 2000 complete in 25.1 sec
[-                 2%                  ] 57 of 2000 complete in 26.1 sec
[-                 2%                  ] 58 of 2000 complete in 26.7 sec
[-                 2%                  ] 59 of 2000 complete in 27.2 sec
[-                 3%                  ] 61 of 2000 complete in 28.1 sec
[-                 3%                  ] 63 of 2000 complete in 28.9 sec
[-                 3%                  ] 65 of 2000 complete in 29.8 sec
[-                 3%                  ] 67 of 2000 complete in 30.6 sec
[-                 3%                  ] 69 of 2000 complete in 31.5 sec
[-                 3%                  ] 71 of 2000 complete in 32.5 sec
[-                 3%                  ] 73 of 2000 complete in 33.3 sec
[-                 3%                  ] 75 of 2000 complete in 34.2 sec
[-                 3%                  ] 77 of 2000 complete in 35.0 sec
[-                 3%                  ] 79 of 2000 complete in 35.8 sec
[-                 4%                  ] 81 of 2000 complete in 36.7 sec
[-                 4%                  ] 83 of 2000 complete in 37.6 sec
[-                 4%                  ] 85 of 2000 complete in 38.5 sec
[-                 4%                  ] 87 of 2000 complete in 39.4 sec
[-                 4%                  ] 89 of 2000 complete in 40.4 sec
[-                 4%                  ] 91 of 2000 complete in 41.3 sec
[-                 4%                  ] 93 of 2000 complete in 42.2 sec
[-                 4%                  ] 95 of 2000 complete in 43.1 sec
[-                 4%                  ] 97 of 2000 complete in 44.0 sec
[-                 4%                  ] 99 of 2000 complete in 44.9 sec
[-                 5%                  ] 101 of 2000 complete in 45.8 sec
[-                 5%                  ] 103 of 2000 complete in 46.6 sec
[-                 5%                  ] 105 of 2000 complete in 47.5 sec
[--                5%                  ] 107 of 2000 complete in 48.4 sec
[--                5%                  ] 109 of 2000 complete in 49.2 sec
[--                5%                  ] 111 of 2000 complete in 50.1 sec
[--                5%                  ] 113 of 2000 complete in 50.9 sec
[--                5%                  ] 115 of 2000 complete in 51.8 sec
[--                5%                  ] 117 of 2000 complete in 52.6 sec
[--                5%                  ] 119 of 2000 complete in 53.5 sec
[--                6%                  ] 121 of 2000 complete in 54.5 sec
[--                6%                  ] 123 of 2000 complete in 55.4 sec
[--                6%                  ] 125 of 2000 complete in 56.3 sec
[--                6%                  ] 127 of 2000 complete in 57.2 sec
[--                6%                  ] 129 of 2000 complete in 58.0 sec
[--                6%                  ] 131 of 2000 complete in 58.8 sec
[--                6%                  ] 133 of 2000 complete in 59.7 sec
[--                6%                  ] 135 of 2000 complete in 60.5 sec
[--                6%                  ] 137 of 2000 complete in 61.4 sec
[--                6%                  ] 139 of 2000 complete in 62.3 sec
[--                7%                  ] 141 of 2000 complete in 63.1 sec
[--                7%                  ] 143 of 2000 complete in 64.0 sec
[--                7%                  ] 145 of 2000 complete in 64.8 sec
[--                7%                  ] 147 of 2000 complete in 65.7 sec
[--                7%                  ] 149 of 2000 complete in 66.6 sec
[--                7%                  ] 151 of 2000 complete in 67.4 sec
[--                7%                  ] 153 of 2000 complete in 68.3 sec
[--                7%                  ] 155 of 2000 complete in 69.2 sec
[--                7%                  ] 157 of 2000 complete in 70.0 sec
[---               7%                  ] 159 of 2000 complete in 70.9 sec
[---               8%                  ] 161 of 2000 complete in 71.8 sec
[---               8%                  ] 163 of 2000 complete in 72.8 sec
[---               8%                  ] 165 of 2000 complete in 73.7 sec
[---               8%                  ] 167 of 2000 complete in 74.6 sec
[---               8%                  ] 169 of 2000 complete in 75.4 sec
[---               8%                  ] 171 of 2000 complete in 76.3 sec
[---               8%                  ] 173 of 2000 complete in 77.1 sec
[---               8%                  ] 175 of 2000 complete in 78.0 sec
[---               8%                  ] 177 of 2000 complete in 78.8 sec
[---               8%                  ] 179 of 2000 complete in 79.6 sec
[---               9%                  ] 181 of 2000 complete in 80.5 sec
[---               9%                  ] 183 of 2000 complete in 81.3 sec
[---               9%                  ] 185 of 2000 complete in 82.2 sec
[---               9%                  ] 187 of 2000 complete in 83.0 sec
[---               9%                  ] 189 of 2000 complete in 83.9 sec
[---               9%                  ] 191 of 2000 complete in 84.8 sec
[---               9%                  ] 193 of 2000 complete in 85.6 sec
[---               9%                  ] 195 of 2000 complete in 86.4 sec
[---               9%                  ] 197 of 2000 complete in 87.3 sec
[---               9%                  ] 199 of 2000 complete in 88.2 sec
[---              10%                  ] 201 of 2000 complete in 89.0 sec
[---              10%                  ] 203 of 2000 complete in 89.8 sec
[---              10%                  ] 205 of 2000 complete in 90.7 sec
[---              10%                  ] 207 of 2000 complete in 91.5 sec
[---              10%                  ] 209 of 2000 complete in 92.4 sec
[----             10%                  ] 211 of 2000 complete in 93.3 sec
[----             10%                  ] 213 of 2000 complete in 94.2 sec
[----             10%                  ] 215 of 2000 complete in 95.1 sec
[----             10%                  ] 217 of 2000 complete in 96.1 sec

[----             11%                  ] 220 of 2000 complete in 95.0 sec
[----             11%                  ] 222 of 2000 complete in 95.9 sec
[----             11%                  ] 224 of 2000 complete in 96.8 sec
[----             11%                  ] 226 of 2000 complete in 97.7 sec
[----             11%                  ] 228 of 2000 complete in 98.6 sec
[----             11%                  ] 230 of 2000 complete in 99.5 sec
[----             11%                  ] 232 of 2000 complete in 100.3 sec
[----             11%                  ] 234 of 2000 complete in 101.3 sec
[----             11%                  ] 235 of 2000 complete in 101.8 sec
[----             11%                  ] 237 of 2000 complete in 102.7 sec
[----             11%                  ] 238 of 2000 complete in 103.3 sec
[----             12%                  ] 240 of 2000 complete in 104.2 sec
[----             12%                  ] 241 of 2000 complete in 104.8 sec
[----             12%                  ] 242 of 2000 complete in 105.3 sec
[----             12%                  ] 243 of 2000 complete in 105.8 sec
[----             12%                  ] 244 of 2000 complete in 106.3 sec
[----             12%                  ] 246 of 2000 complete in 107.3 sec
[----             12%                  ] 247 of 2000 complete in 107.8 sec
[----             12%                  ] 249 of 2000 complete in 108.7 sec
[----             12%                  ] 251 of 2000 complete in 109.6 sec
[----             12%                  ] 253 of 2000 complete in 110.5 sec
[----             12%                  ] 255 of 2000 complete in 111.4 sec
[----             12%                  ] 257 of 2000 complete in 112.3 sec
[----             12%                  ] 259 of 2000 complete in 113.2 sec
[----             13%                  ] 261 of 2000 complete in 114.1 sec
[----             13%                  ] 263 of 2000 complete in 115.0 sec
[-----            13%                  ] 265 of 2000 complete in 115.9 sec
[-----            13%                  ] 267 of 2000 complete in 116.7 sec
[-----            13%                  ] 269 of 2000 complete in 117.6 sec
[-----            13%                  ] 271 of 2000 complete in 118.4 sec
[-----            13%                  ] 273 of 2000 complete in 119.2 sec
[-----            13%                  ] 275 of 2000 complete in 120.0 sec
[-----            13%                  ] 277 of 2000 complete in 120.8 sec
[-----            13%                  ] 279 of 2000 complete in 121.7 sec
[-----            14%                  ] 281 of 2000 complete in 122.5 sec
[-----            14%                  ] 283 of 2000 complete in 123.3 sec
[-----            14%                  ] 285 of 2000 complete in 124.1 sec
[-----            14%                  ] 287 of 2000 complete in 125.0 sec
[-----            14%                  ] 289 of 2000 complete in 125.8 sec
[-----            14%                  ] 291 of 2000 complete in 126.7 sec
[-----            14%                  ] 293 of 2000 complete in 127.6 sec
[-----            14%                  ] 295 of 2000 complete in 128.4 sec
[-----            14%                  ] 297 of 2000 complete in 129.3 sec
[-----            14%                  ] 299 of 2000 complete in 130.2 sec
[-----            15%                  ] 301 of 2000 complete in 131.1 sec
[-----            15%                  ] 303 of 2000 complete in 131.9 sec
[-----            15%                  ] 305 of 2000 complete in 132.8 sec
[-----            15%                  ] 307 of 2000 complete in 133.7 sec
[-----            15%                  ] 309 of 2000 complete in 134.6 sec
[-----            15%                  ] 311 of 2000 complete in 135.5 sec
[-----            15%                  ] 313 of 2000 complete in 136.3 sec
[-----            15%                  ] 315 of 2000 complete in 137.2 sec
[------           15%                  ] 317 of 2000 complete in 138.0 sec
[------           15%                  ] 319 of 2000 complete in 138.9 sec
[------           16%                  ] 321 of 2000 complete in 139.8 sec
[------           16%                  ] 323 of 2000 complete in 140.6 sec
[------           16%                  ] 325 of 2000 complete in 141.5 sec
[------           16%                  ] 327 of 2000 complete in 142.4 sec
[------           16%                  ] 329 of 2000 complete in 143.2 sec
[------           16%                  ] 331 of 2000 complete in 144.1 sec
[------           16%                  ] 333 of 2000 complete in 144.9 sec
[------           16%                  ] 335 of 2000 complete in 145.8 sec
[------           16%                  ] 337 of 2000 complete in 146.7 sec
[------           16%                  ] 339 of 2000 complete in 147.6 sec
[------           17%                  ] 341 of 2000 complete in 148.4 sec
[------           17%                  ] 343 of 2000 complete in 149.3 sec
[------           17%                  ] 345 of 2000 complete in 150.1 sec
[------           17%                  ] 347 of 2000 complete in 150.9 sec
[------           17%                  ] 349 of 2000 complete in 151.8 sec
[------           17%                  ] 351 of 2000 complete in 152.6 sec
[------           17%                  ] 353 of 2000 complete in 153.5 sec
[------           17%                  ] 355 of 2000 complete in 154.3 sec
[------           17%                  ] 357 of 2000 complete in 155.2 sec
[------           17%                  ] 359 of 2000 complete in 156.0 sec
[------           18%                  ] 361 of 2000 complete in 156.8 sec
[------           18%                  ] 363 of 2000 complete in 157.7 sec
[------           18%                  ] 365 of 2000 complete in 158.5 sec
[------           18%                  ] 367 of 2000 complete in 159.4 sec
[-------          18%                  ] 369 of 2000 complete in 160.2 sec
[-------          18%                  ] 371 of 2000 complete in 161.0 sec
[-------          18%                  ] 373 of 2000 complete in 161.9 sec
[-------          18%                  ] 375 of 2000 complete in 162.8 sec
[-------          18%                  ] 377 of 2000 complete in 163.6 sec
[-------          18%                  ] 379 of 2000 complete in 164.5 sec
[-------          19%                  ] 381 of 2000 complete in 165.3 sec
[-------          19%                  ] 383 of 2000 complete in 166.2 sec
[-------          19%                  ] 385 of 2000 complete in 167.0 sec
[-------          19%                  ] 387 of 2000 complete in 167.9 sec
[-------          19%                  ] 389 of 2000 complete in 168.7 sec
[-------          19%                  ] 391 of 2000 complete in 169.5 sec
[-------          19%                  ] 393 of 2000 complete in 170.4 sec
[-------          19%                  ] 395 of 2000 complete in 171.2 sec
[-------          19%                  ] 397 of 2000 complete in 172.1 sec
[-------          19%                  ] 399 of 2000 complete in 172.9 sec
[-------          20%                  ] 401 of 2000 complete in 173.7 sec
[-------          20%                  ] 403 of 2000 complete in 174.6 sec
[-------          20%                  ] 405 of 2000 complete in 175.4 sec
[-------          20%                  ] 407 of 2000 complete in 176.3 sec
[-------          20%                  ] 409 of 2000 complete in 177.1 sec
[-------          20%                  ] 411 of 2000 complete in 178.0 sec
[-------          20%                  ] 413 of 2000 complete in 178.8 sec
[-------          20%                  ] 415 of 2000 complete in 179.7 sec
[-------          20%                  ] 417 of 2000 complete in 180.5 sec
[-------          20%                  ] 419 of 2000 complete in 181.4 sec
[-------          21%                  ] 421 of 2000 complete in 182.3 sec
[--------         21%                  ] 423 of 2000 complete in 183.2 sec
[--------         21%                  ] 425 of 2000 complete in 184.0 sec
[--------         21%                  ] 427 of 2000 complete in 184.8 sec
[--------         21%                  ] 429 of 2000 complete in 185.7 sec
[----             10%                  ] 218 of 2000 complete in 94.0 sec
[----             11%                  ] 220 of 2000 complete in 95.0 sec
[----             11%                  ] 222 of 2000 complete in 95.9 sec
[----             11%                  ] 224 of 2000 complete in 96.8 sec
[----             11%                  ] 226 of 2000 complete in 97.7 sec
[----             11%                  ] 228 of 2000 complete in 98.6 sec
[----             11%                  ] 230 of 2000 complete in 99.5 sec
[----             11%                  ] 232 of 2000 complete in 100.3 sec
[----             11%                  ] 234 of 2000 complete in 101.2 sec
[----             11%                  ] 236 of 2000 complete in 102.2 sec
[----             11%                  ] 237 of 2000 complete in 102.7 sec
[----             11%                  ] 238 of 2000 complete in 103.3 sec
[----             11%                  ] 239 of 2000 complete in 103.8 sec
[----             12%                  ] 240 of 2000 complete in 104.3 sec
[----             12%                  ] 242 of 2000 complete in 105.3 sec
[----             12%                  ] 243 of 2000 complete in 105.8 sec
[----             12%                  ] 244 of 2000 complete in 106.3 sec
[----             12%                  ] 246 of 2000 complete in 107.4 sec
[----             12%                  ] 248 of 2000 complete in 108.3 sec
[----             12%                  ] 250 of 2000 complete in 109.2 sec
[----             12%                  ] 252 of 2000 complete in 110.1 sec
[----             12%                  ] 254 of 2000 complete in 111.0 sec
[----             12%                  ] 256 of 2000 complete in 111.9 sec
[----             12%                  ] 258 of 2000 complete in 112.7 sec
[----             13%                  ] 260 of 2000 complete in 113.6 sec
[----             13%                  ] 262 of 2000 complete in 114.5 sec
[-----            13%                  ] 264 of 2000 complete in 115.4 sec
[-----            13%                  ] 266 of 2000 complete in 116.2 sec
[-----            13%                  ] 268 of 2000 complete in 117.0 sec
[-----            13%                  ] 270 of 2000 complete in 117.9 sec
[-----            13%                  ] 272 of 2000 complete in 118.7 sec
[-----            13%                  ] 274 of 2000 complete in 119.6 sec
[-----            13%                  ] 276 of 2000 complete in 120.4 sec
[-----            13%                  ] 278 of 2000 complete in 121.3 sec
[-----            14%                  ] 280 of 2000 complete in 122.1 sec
[-----            14%                  ] 282 of 2000 complete in 123.0 sec
[-----            14%                  ] 284 of 2000 complete in 123.8 sec
[-----            14%                  ] 286 of 2000 complete in 124.7 sec
[-----            14%                  ] 288 of 2000 complete in 125.5 sec
[-----            14%                  ] 290 of 2000 complete in 126.3 sec
[-----            14%                  ] 292 of 2000 complete in 127.2 sec
[-----            14%                  ] 294 of 2000 complete in 128.1 sec
[-----            14%                  ] 296 of 2000 complete in 129.0 sec
[-----            14%                  ] 298 of 2000 complete in 129.8 sec
[-----            15%                  ] 300 of 2000 complete in 130.7 sec
[-----            15%                  ] 302 of 2000 complete in 131.6 sec
[-----            15%                  ] 304 of 2000 complete in 132.5 sec
[-----            15%                  ] 306 of 2000 complete in 133.4 sec
[-----            15%                  ] 308 of 2000 complete in 134.2 sec
[-----            15%                  ] 310 of 2000 complete in 135.1 sec
[-----            15%                  ] 312 of 2000 complete in 136.0 sec
[-----            15%                  ] 314 of 2000 complete in 136.8 sec
[------           15%                  ] 316 of 2000 complete in 137.7 sec
[------           15%                  ] 318 of 2000 complete in 138.6 sec
[------           16%                  ] 320 of 2000 complete in 139.4 sec
[------           16%                  ] 322 of 2000 complete in 140.3 sec
[------           16%                  ] 324 of 2000 complete in 141.2 sec
[------           16%                  ] 326 of 2000 complete in 142.0 sec
[------           16%                  ] 328 of 2000 complete in 142.9 sec
[------           16%                  ] 330 of 2000 complete in 143.8 sec
[------           16%                  ] 332 of 2000 complete in 144.7 sec
[------           16%                  ] 334 of 2000 complete in 145.6 sec
[------           16%                  ] 336 of 2000 complete in 146.5 sec
[------           16%                  ] 338 of 2000 complete in 147.4 sec
[------           17%                  ] 340 of 2000 complete in 148.2 sec
[------           17%                  ] 342 of 2000 complete in 149.1 sec
[------           17%                  ] 344 of 2000 complete in 150.0 sec
[------           17%                  ] 346 of 2000 complete in 150.8 sec
[------           17%                  ] 348 of 2000 complete in 151.7 sec
[------           17%                  ] 350 of 2000 complete in 152.5 sec
[------           17%                  ] 352 of 2000 complete in 153.4 sec
[------           17%                  ] 354 of 2000 complete in 154.2 sec
[------           17%                  ] 356 of 2000 complete in 155.1 sec
[------           17%                  ] 358 of 2000 complete in 155.9 sec
[------           18%                  ] 360 of 2000 complete in 156.8 sec
[------           18%                  ] 362 of 2000 complete in 157.6 sec
[------           18%                  ] 364 of 2000 complete in 158.5 sec
[------           18%                  ] 366 of 2000 complete in 159.4 sec
[------           18%                  ] 368 of 2000 complete in 160.2 sec
[-------          18%                  ] 370 of 2000 complete in 161.1 sec
[-------          18%                  ] 372 of 2000 complete in 161.9 sec
[-------          18%                  ] 374 of 2000 complete in 162.8 sec
[-------          18%                  ] 376 of 2000 complete in 163.7 sec
[-------          18%                  ] 378 of 2000 complete in 164.6 sec
[-------          19%                  ] 380 of 2000 complete in 165.4 sec
[-------          19%                  ] 382 of 2000 complete in 166.3 sec
[-------          19%                  ] 384 of 2000 complete in 167.1 sec
[-------          19%                  ] 386 of 2000 complete in 167.9 sec
[-------          19%                  ] 388 of 2000 complete in 168.8 sec
[-------          19%                  ] 390 of 2000 complete in 169.6 sec
[-------          19%                  ] 392 of 2000 complete in 170.5 sec
[-------          19%                  ] 394 of 2000 complete in 171.3 sec
[-------          19%                  ] 396 of 2000 complete in 172.2 sec
[-------          19%                  ] 398 of 2000 complete in 173.0 sec
[-------          20%                  ] 400 of 2000 complete in 173.9 sec
[-------          20%                  ] 402 of 2000 complete in 174.7 sec
[-------          20%                  ] 404 of 2000 complete in 175.6 sec
[-------          20%                  ] 406 of 2000 complete in 176.4 sec
[-------          20%                  ] 408 of 2000 complete in 177.3 sec
[-------          20%                  ] 410 of 2000 complete in 178.1 sec
[-------          20%                  ] 412 of 2000 complete in 179.0 sec
[-------          20%                  ] 414 of 2000 complete in 179.8 sec
[-------          20%                  ] 416 of 2000 complete in 180.7 sec
[-------          20%                  ] 418 of 2000 complete in 181.6 sec
[-------          21%                  ] 420 of 2000 complete in 182.5 sec
[--------         21%                  ] 422 of 2000 complete in 183.3 sec
[--------         21%                  ] 424 of 2000 complete in 184.2 sec
[--------         21%                  ] 426 of 2000 complete in 185.1 sec
[--------         21%                  ] 428 of 2000 complete in 186.0 sec

[----             10%                  ] 216 of 2000 complete in 95.6 sec
[----             10%                  ] 218 of 2000 complete in 96.5 sec
[----             11%                  ] 220 of 2000 complete in 97.4 sec
[----             11%                  ] 222 of 2000 complete in 98.4 sec
[----             11%                  ] 224 of 2000 complete in 99.3 sec
[----             11%                  ] 226 of 2000 complete in 100.2 sec
[----             11%                  ] 228 of 2000 complete in 101.1 sec
[----             11%                  ] 229 of 2000 complete in 101.6 sec
[----             11%                  ] 230 of 2000 complete in 102.1 sec
[----             11%                  ] 232 of 2000 complete in 103.2 sec
[----             11%                  ] 233 of 2000 complete in 103.7 sec
[----             11%                  ] 235 of 2000 complete in 104.7 sec
[----             11%                  ] 236 of 2000 complete in 105.2 sec
[----             11%                  ] 237 of 2000 complete in 105.7 sec
[----             11%                  ] 238 of 2000 complete in 106.2 sec
[----             11%                  ] 239 of 2000 complete in 106.8 sec
[----             12%                  ] 240 of 2000 complete in 107.3 sec
[----             12%                  ] 242 of 2000 complete in 108.2 sec
[----             12%                  ] 244 of 2000 complete in 109.2 sec
[----             12%                  ] 246 of 2000 complete in 110.1 sec
[----             12%                  ] 248 of 2000 complete in 111.1 sec
[----             12%                  ] 250 of 2000 complete in 112.0 sec
[----             12%                  ] 252 of 2000 complete in 112.8 sec
[----             12%                  ] 254 of 2000 complete in 113.7 sec
[----             12%                  ] 256 of 2000 complete in 114.6 sec
[----             12%                  ] 258 of 2000 complete in 115.5 sec
[----             13%                  ] 260 of 2000 complete in 116.3 sec
[----             13%                  ] 262 of 2000 complete in 117.2 sec
[-----            13%                  ] 264 of 2000 complete in 118.0 sec
[-----            13%                  ] 266 of 2000 complete in 118.9 sec
[-----            13%                  ] 268 of 2000 complete in 119.8 sec
[-----            13%                  ] 270 of 2000 complete in 120.6 sec
[-----            13%                  ] 272 of 2000 complete in 121.5 sec
[-----            13%                  ] 274 of 2000 complete in 122.3 sec
[-----            13%                  ] 276 of 2000 complete in 123.2 sec
[-----            13%                  ] 278 of 2000 complete in 124.1 sec
[-----            14%                  ] 280 of 2000 complete in 125.0 sec
[-----            14%                  ] 282 of 2000 complete in 125.8 sec
[-----            14%                  ] 284 of 2000 complete in 126.7 sec
[-----            14%                  ] 286 of 2000 complete in 127.6 sec
[-----            14%                  ] 288 of 2000 complete in 128.6 sec
[-----            14%                  ] 290 of 2000 complete in 129.5 sec
[-----            14%                  ] 292 of 2000 complete in 130.4 sec
[-----            14%                  ] 294 of 2000 complete in 131.3 sec
[-----            14%                  ] 296 of 2000 complete in 132.2 sec
[-----            14%                  ] 298 of 2000 complete in 133.0 sec
[-----            15%                  ] 300 of 2000 complete in 133.9 sec
[-----            15%                  ] 302 of 2000 complete in 134.8 sec
[-----            15%                  ] 304 of 2000 complete in 135.7 sec
[-----            15%                  ] 306 of 2000 complete in 136.6 sec
[-----            15%                  ] 308 of 2000 complete in 137.5 sec
[-----            15%                  ] 310 of 2000 complete in 138.4 sec
[-----            15%                  ] 312 of 2000 complete in 139.3 sec
[-----            15%                  ] 314 of 2000 complete in 140.2 sec
[------           15%                  ] 316 of 2000 complete in 141.1 sec
[------           15%                  ] 318 of 2000 complete in 141.9 sec
[------           16%                  ] 320 of 2000 complete in 142.8 sec
[------           16%                  ] 322 of 2000 complete in 143.7 sec
[------           16%                  ] 324 of 2000 complete in 144.6 sec
[------           16%                  ] 326 of 2000 complete in 145.6 sec
[------           16%                  ] 328 of 2000 complete in 146.5 sec
[------           16%                  ] 330 of 2000 complete in 147.4 sec
[------           16%                  ] 332 of 2000 complete in 148.2 sec
[------           16%                  ] 334 of 2000 complete in 149.1 sec
[------           16%                  ] 336 of 2000 complete in 150.0 sec
[------           16%                  ] 338 of 2000 complete in 150.8 sec
[------           17%                  ] 340 of 2000 complete in 151.7 sec
[------           17%                  ] 342 of 2000 complete in 152.5 sec
[------           17%                  ] 344 of 2000 complete in 153.4 sec
[------           17%                  ] 346 of 2000 complete in 154.3 sec
[------           17%                  ] 348 of 2000 complete in 155.1 sec
[------           17%                  ] 350 of 2000 complete in 156.0 sec
[------           17%                  ] 352 of 2000 complete in 156.9 sec
[------           17%                  ] 354 of 2000 complete in 157.7 sec
[------           17%                  ] 356 of 2000 complete in 158.5 sec
[------           17%                  ] 358 of 2000 complete in 159.4 sec
[------           18%                  ] 360 of 2000 complete in 160.3 sec
[------           18%                  ] 362 of 2000 complete in 161.1 sec
[------           18%                  ] 364 of 2000 complete in 162.0 sec
[------           18%                  ] 366 of 2000 complete in 162.9 sec
[------           18%                  ] 368 of 2000 complete in 163.8 sec
[-------          18%                  ] 370 of 2000 complete in 164.7 sec
[-------          18%                  ] 372 of 2000 complete in 165.5 sec
[-------          18%                  ] 374 of 2000 complete in 166.4 sec
[-------          18%                  ] 376 of 2000 complete in 167.3 sec
[-------          18%                  ] 378 of 2000 complete in 168.1 sec
[-------          19%                  ] 380 of 2000 complete in 169.0 sec
[-------          19%                  ] 382 of 2000 complete in 169.8 sec
[-------          19%                  ] 384 of 2000 complete in 170.7 sec
[-------          19%                  ] 386 of 2000 complete in 171.6 sec
[-------          19%                  ] 388 of 2000 complete in 172.4 sec
[-------          19%                  ] 390 of 2000 complete in 173.3 sec
[-------          19%                  ] 392 of 2000 complete in 174.2 sec
[-------          19%                  ] 394 of 2000 complete in 175.0 sec
[-------          19%                  ] 396 of 2000 complete in 175.9 sec
[-------          19%                  ] 398 of 2000 complete in 176.7 sec
[-------          20%                  ] 400 of 2000 complete in 177.6 sec
[-------          20%                  ] 402 of 2000 complete in 178.4 sec
[-------          20%                  ] 404 of 2000 complete in 179.3 sec
[-------          20%                  ] 406 of 2000 complete in 180.2 sec
[-------          20%                  ] 408 of 2000 complete in 181.1 sec
[-------          20%                  ] 410 of 2000 complete in 182.0 sec
[-------          20%                  ] 412 of 2000 complete in 182.9 sec
[-------          20%                  ] 414 of 2000 complete in 183.7 sec
[-------          20%                  ] 416 of 2000 complete in 184.6 sec
[-------          20%                  ] 418 of 2000 complete in 185.5 sec
[-------          21%                  ] 420 of 2000 complete in 186.4 sec
[-------          21%                  ] 421 of 2000 complete in 187.1 sec
[--------         21%                  ] 423 of 2000 complete in 188.0 sec
[----             10%                  ] 219 of 2000 complete in 97.0 sec
[----             11%                  ] 221 of 2000 complete in 97.9 sec
[----             11%                  ] 223 of 2000 complete in 98.8 sec
[----             11%                  ] 225 of 2000 complete in 99.7 sec
[----             11%                  ] 227 of 2000 complete in 100.6 sec
[----             11%                  ] 229 of 2000 complete in 101.5 sec
[----             11%                  ] 230 of 2000 complete in 102.1 sec
[----             11%                  ] 231 of 2000 complete in 102.6 sec
[----             11%                  ] 232 of 2000 complete in 103.1 sec
[----             11%                  ] 233 of 2000 complete in 103.6 sec
[----             11%                  ] 234 of 2000 complete in 104.1 sec
[----             11%                  ] 235 of 2000 complete in 104.7 sec
[----             11%                  ] 236 of 2000 complete in 105.2 sec
[----             11%                  ] 237 of 2000 complete in 105.7 sec
[----             11%                  ] 238 of 2000 complete in 106.3 sec
[----             11%                  ] 239 of 2000 complete in 106.8 sec
[----             12%                  ] 240 of 2000 complete in 107.3 sec
[----             12%                  ] 242 of 2000 complete in 108.3 sec
[----             12%                  ] 244 of 2000 complete in 109.2 sec
[----             12%                  ] 246 of 2000 complete in 110.2 sec
[----             12%                  ] 248 of 2000 complete in 111.1 sec
[----             12%                  ] 250 of 2000 complete in 112.0 sec
[----             12%                  ] 252 of 2000 complete in 112.9 sec
[----             12%                  ] 254 of 2000 complete in 113.8 sec
[----             12%                  ] 256 of 2000 complete in 114.7 sec
[----             12%                  ] 258 of 2000 complete in 115.6 sec
[----             13%                  ] 260 of 2000 complete in 116.5 sec
[----             13%                  ] 262 of 2000 complete in 117.3 sec
[-----            13%                  ] 264 of 2000 complete in 118.2 sec
[-----            13%                  ] 266 of 2000 complete in 119.1 sec
[-----            13%                  ] 268 of 2000 complete in 119.9 sec
[-----            13%                  ] 270 of 2000 complete in 120.8 sec
[-----            13%                  ] 272 of 2000 complete in 121.7 sec
[-----            13%                  ] 274 of 2000 complete in 122.6 sec
[-----            13%                  ] 276 of 2000 complete in 123.5 sec
[-----            13%                  ] 278 of 2000 complete in 124.3 sec
[-----            14%                  ] 280 of 2000 complete in 125.2 sec
[-----            14%                  ] 282 of 2000 complete in 126.0 sec
[-----            14%                  ] 284 of 2000 complete in 126.9 sec
[-----            14%                  ] 286 of 2000 complete in 127.8 sec
[-----            14%                  ] 288 of 2000 complete in 128.6 sec
[-----            14%                  ] 290 of 2000 complete in 129.6 sec
[-----            14%                  ] 292 of 2000 complete in 130.5 sec
[-----            14%                  ] 294 of 2000 complete in 131.4 sec
[-----            14%                  ] 296 of 2000 complete in 132.2 sec
[-----            14%                  ] 298 of 2000 complete in 133.1 sec
[-----            15%                  ] 300 of 2000 complete in 134.0 sec
[-----            15%                  ] 302 of 2000 complete in 134.9 sec
[-----            15%                  ] 304 of 2000 complete in 135.8 sec
[-----            15%                  ] 306 of 2000 complete in 136.7 sec
[-----            15%                  ] 308 of 2000 complete in 137.6 sec
[-----            15%                  ] 310 of 2000 complete in 138.5 sec
[-----            15%                  ] 312 of 2000 complete in 139.4 sec
[-----            15%                  ] 314 of 2000 complete in 140.3 sec
[------           15%                  ] 316 of 2000 complete in 141.2 sec
[------           15%                  ] 318 of 2000 complete in 142.1 sec
[------           16%                  ] 320 of 2000 complete in 142.9 sec
[------           16%                  ] 322 of 2000 complete in 143.8 sec
[------           16%                  ] 324 of 2000 complete in 144.7 sec
[------           16%                  ] 326 of 2000 complete in 145.6 sec
[------           16%                  ] 328 of 2000 complete in 146.5 sec
[------           16%                  ] 330 of 2000 complete in 147.4 sec
[------           16%                  ] 332 of 2000 complete in 148.3 sec
[------           16%                  ] 334 of 2000 complete in 149.1 sec
[------           16%                  ] 336 of 2000 complete in 150.0 sec
[------           16%                  ] 338 of 2000 complete in 150.9 sec
[------           17%                  ] 340 of 2000 complete in 151.8 sec
[------           17%                  ] 342 of 2000 complete in 152.7 sec
[------           17%                  ] 344 of 2000 complete in 153.5 sec
[------           17%                  ] 346 of 2000 complete in 154.4 sec
[------           17%                  ] 348 of 2000 complete in 155.3 sec
[------           17%                  ] 350 of 2000 complete in 156.2 sec
[------           17%                  ] 352 of 2000 complete in 157.1 sec
[------           17%                  ] 354 of 2000 complete in 158.0 sec
[------           17%                  ] 356 of 2000 complete in 158.8 sec
[------           17%                  ] 358 of 2000 complete in 159.7 sec
[------           18%                  ] 360 of 2000 complete in 160.5 sec
[------           18%                  ] 362 of 2000 complete in 161.4 sec
[------           18%                  ] 364 of 2000 complete in 162.3 sec
[------           18%                  ] 366 of 2000 complete in 163.2 sec
[------           18%                  ] 368 of 2000 complete in 164.1 sec
[-------          18%                  ] 370 of 2000 complete in 165.0 sec
[-------          18%                  ] 372 of 2000 complete in 165.9 sec
[-------          18%                  ] 374 of 2000 complete in 166.8 sec
[-------          18%                  ] 376 of 2000 complete in 167.6 sec
[-------          18%                  ] 378 of 2000 complete in 168.5 sec
[-------          19%                  ] 380 of 2000 complete in 169.4 sec
[-------          19%                  ] 382 of 2000 complete in 170.2 sec
[-------          19%                  ] 384 of 2000 complete in 171.1 sec
[-------          19%                  ] 386 of 2000 complete in 171.9 sec
[-------          19%                  ] 388 of 2000 complete in 172.8 sec
[-------          19%                  ] 390 of 2000 complete in 173.7 sec
[-------          19%                  ] 392 of 2000 complete in 174.5 sec
[-------          19%                  ] 394 of 2000 complete in 175.4 sec
[-------          19%                  ] 396 of 2000 complete in 176.2 sec
[-------          19%                  ] 398 of 2000 complete in 177.1 sec
[-------          20%                  ] 400 of 2000 complete in 178.0 sec
[-------          20%                  ] 402 of 2000 complete in 178.9 sec
[-------          20%                  ] 404 of 2000 complete in 179.8 sec
[-------          20%                  ] 406 of 2000 complete in 180.7 sec
[-------          20%                  ] 408 of 2000 complete in 181.7 sec
[-------          20%                  ] 410 of 2000 complete in 182.6 sec
[-------          20%                  ] 412 of 2000 complete in 183.5 sec
[-------          20%                  ] 414 of 2000 complete in 184.3 sec
[-------          20%                  ] 416 of 2000 complete in 185.2 sec
[-------          20%                  ] 418 of 2000 complete in 186.1 sec
[-------          20%                  ] 419 of 2000 complete in 186.7 sec
[-------          21%                  ] 420 of 2000 complete in 187.3 sec
[--------         21%                  ] 422 of 2000 complete in 188.2 sec

[--------         21%                  ] 430 of 2000 complete in 187.0 sec
[--------         21%                  ] 432 of 2000 complete in 187.9 sec
[--------         21%                  ] 434 of 2000 complete in 188.9 sec
[--------         21%                  ] 435 of 2000 complete in 189.4 sec
[--------         21%                  ] 436 of 2000 complete in 189.9 sec
[--------         21%                  ] 437 of 2000 complete in 190.4 sec
[--------         21%                  ] 438 of 2000 complete in 191.0 sec
[--------         22%                  ] 440 of 2000 complete in 192.0 sec
[--------         22%                  ] 442 of 2000 complete in 192.9 sec
[--------         22%                  ] 444 of 2000 complete in 194.0 sec
[--------         22%                  ] 445 of 2000 complete in 194.5 sec
[--------         22%                  ] 447 of 2000 complete in 195.5 sec
[--------         22%                  ] 448 of 2000 complete in 196.0 sec
[--------         22%                  ] 449 of 2000 complete in 196.5 sec
[--------         22%                  ] 451 of 2000 complete in 197.5 sec
[--------         22%                  ] 453 of 2000 complete in 198.3 sec
[--------         22%                  ] 455 of 2000 complete in 199.2 sec
[--------         22%                  ] 457 of 2000 complete in 200.1 sec
[--------         22%                  ] 459 of 2000 complete in 200.9 sec
[--------         23%                  ] 461 of 2000 complete in 201.7 sec
[--------         23%                  ] 463 of 2000 complete in 202.6 sec
[--------         23%                  ] 465 of 2000 complete in 203.5 sec
[--------         23%                  ] 467 of 2000 complete in 204.3 sec
[--------         23%                  ] 469 of 2000 complete in 205.3 sec
[--------         23%                  ] 470 of 2000 complete in 205.8 sec
[--------         23%                  ] 472 of 2000 complete in 206.7 sec
[---------        23%                  ] 474 of 2000 complete in 207.5 sec
[---------        23%                  ] 476 of 2000 complete in 208.5 sec
[---------        23%                  ] 478 of 2000 complete in 209.4 sec
[---------        24%                  ] 480 of 2000 complete in 210.4 sec
[---------        24%                  ] 482 of 2000 complete in 211.2 sec
[---------        24%                  ] 484 of 2000 complete in 212.1 sec
[---------        24%                  ] 486 of 2000 complete in 212.9 sec
[---------        24%                  ] 488 of 2000 complete in 213.8 sec
[---------        24%                  ] 490 of 2000 complete in 214.7 sec
[---------        24%                  ] 492 of 2000 complete in 215.5 sec
[---------        24%                  ] 494 of 2000 complete in 216.4 sec
[---------        24%                  ] 496 of 2000 complete in 217.2 sec
[---------        24%                  ] 498 of 2000 complete in 218.1 sec
[---------        25%                  ] 500 of 2000 complete in 219.0 sec
[---------        25%                  ] 502 of 2000 complete in 219.8 sec
[---------        25%                  ] 504 of 2000 complete in 220.7 sec
[---------        25%                  ] 505 of 2000 complete in 221.2 sec
[---------        25%                  ] 506 of 2000 complete in 221.7 sec
[---------        25%                  ] 508 of 2000 complete in 222.7 sec
[---------        25%                  ] 510 of 2000 complete in 223.5 sec
[---------        25%                  ] 512 of 2000 complete in 224.4 sec
[---------        25%                  ] 514 of 2000 complete in 225.4 sec
[---------        25%                  ] 515 of 2000 complete in 225.9 sec
[---------        25%                  ] 517 of 2000 complete in 226.9 sec
[---------        25%                  ] 518 of 2000 complete in 227.4 sec
[---------        25%                  ] 519 of 2000 complete in 227.9 sec
[---------        26%                  ] 521 of 2000 complete in 228.8 sec
[---------        26%                  ] 522 of 2000 complete in 229.4 sec
[---------        26%                  ] 524 of 2000 complete in 230.3 sec
[---------        26%                  ] 526 of 2000 complete in 231.2 sec
[----------       26%                  ] 528 of 2000 complete in 232.0 sec
[----------       26%                  ] 529 of 2000 complete in 232.6 sec
[----------       26%                  ] 531 of 2000 complete in 233.5 sec
[----------       26%                  ] 533 of 2000 complete in 234.4 sec
[----------       26%                  ] 535 of 2000 complete in 235.4 sec
[----------       26%                  ] 537 of 2000 complete in 236.3 sec
[----------       26%                  ] 539 of 2000 complete in 237.2 sec
[----------       27%                  ] 541 of 2000 complete in 238.1 sec
[----------       27%                  ] 543 of 2000 complete in 239.0 sec
[----------       27%                  ] 545 of 2000 complete in 239.8 sec
[----------       27%                  ] 547 of 2000 complete in 240.7 sec
[----------       27%                  ] 549 of 2000 complete in 241.6 sec
[----------       27%                  ] 551 of 2000 complete in 242.4 sec
[----------       27%                  ] 553 of 2000 complete in 243.3 sec
[----------       27%                  ] 555 of 2000 complete in 244.1 sec
[----------       27%                  ] 557 of 2000 complete in 245.0 sec
[----------       27%                  ] 559 of 2000 complete in 245.9 sec
[----------       28%                  ] 561 of 2000 complete in 246.8 sec
[----------       28%                  ] 563 of 2000 complete in 247.7 sec
[----------       28%                  ] 565 of 2000 complete in 248.6 sec
[----------       28%                  ] 567 of 2000 complete in 249.5 sec
[----------       28%                  ] 569 of 2000 complete in 250.4 sec
[----------       28%                  ] 571 of 2000 complete in 251.3 sec
[----------       28%                  ] 573 of 2000 complete in 252.2 sec
[----------       28%                  ] 575 of 2000 complete in 253.1 sec
[----------       28%                  ] 577 of 2000 complete in 254.0 sec
[-----------      28%                  ] 579 of 2000 complete in 254.9 sec
[-----------      29%                  ] 581 of 2000 complete in 255.8 sec
[-----------      29%                  ] 583 of 2000 complete in 256.6 sec
[-----------      29%                  ] 585 of 2000 complete in 257.5 sec
[-----------      29%                  ] 587 of 2000 complete in 258.3 sec
[-----------      29%                  ] 589 of 2000 complete in 259.1 sec
[-----------      29%                  ] 591 of 2000 complete in 260.0 sec
[-----------      29%                  ] 593 of 2000 complete in 261.0 sec
[-----------      29%                  ] 595 of 2000 complete in 261.9 sec
[-----------      29%                  ] 597 of 2000 complete in 262.7 sec
[-----------      29%                  ] 599 of 2000 complete in 263.6 sec
[-----------      30%                  ] 601 of 2000 complete in 264.4 sec
[-----------      30%                  ] 603 of 2000 complete in 265.3 sec
[-----------      30%                  ] 605 of 2000 complete in 266.1 sec
[-----------      30%                  ] 607 of 2000 complete in 267.0 sec
[-----------      30%                  ] 609 of 2000 complete in 267.9 sec
[-----------      30%                  ] 611 of 2000 complete in 268.8 sec
[-----------      30%                  ] 613 of 2000 complete in 269.6 sec
[-----------      30%                  ] 615 of 2000 complete in 270.5 sec
[-----------      30%                  ] 617 of 2000 complete in 271.3 sec
[-----------      30%                  ] 619 of 2000 complete in 272.2 sec
[-----------      31%                  ] 621 of 2000 complete in 273.0 sec
[-----------      31%                  ] 623 of 2000 complete in 273.9 sec
[-----------      31%                  ] 625 of 2000 complete in 274.8 sec
[-----------      31%                  ] 627 of 2000 complete in 275.6 sec
[-----------      31%                  ] 629 of 2000 complete in 276.4 sec
[-----------      31%                  ] 631 of 2000 complete in 277.3 sec
[--------         21%                  ] 431 of 2000 complete in 186.7 sec
[--------         21%                  ] 432 of 2000 complete in 187.2 sec
[--------         21%                  ] 434 of 2000 complete in 188.2 sec
[--------         21%                  ] 436 of 2000 complete in 189.2 sec
[--------         21%                  ] 437 of 2000 complete in 189.7 sec
[--------         21%                  ] 438 of 2000 complete in 190.2 sec
[--------         21%                  ] 439 of 2000 complete in 190.7 sec
[--------         22%                  ] 440 of 2000 complete in 191.3 sec
[--------         22%                  ] 442 of 2000 complete in 192.2 sec
[--------         22%                  ] 444 of 2000 complete in 193.2 sec
[--------         22%                  ] 446 of 2000 complete in 194.2 sec
[--------         22%                  ] 448 of 2000 complete in 195.2 sec
[--------         22%                  ] 450 of 2000 complete in 196.2 sec
[--------         22%                  ] 452 of 2000 complete in 197.1 sec
[--------         22%                  ] 454 of 2000 complete in 198.1 sec
[--------         22%                  ] 456 of 2000 complete in 198.9 sec
[--------         22%                  ] 458 of 2000 complete in 199.7 sec
[--------         23%                  ] 460 of 2000 complete in 200.6 sec
[--------         23%                  ] 462 of 2000 complete in 201.4 sec
[--------         23%                  ] 464 of 2000 complete in 202.3 sec
[--------         23%                  ] 466 of 2000 complete in 203.2 sec
[--------         23%                  ] 468 of 2000 complete in 204.0 sec
[--------         23%                  ] 470 of 2000 complete in 204.9 sec
[--------         23%                  ] 471 of 2000 complete in 205.4 sec
[--------         23%                  ] 473 of 2000 complete in 206.3 sec
[---------        23%                  ] 475 of 2000 complete in 207.2 sec
[---------        23%                  ] 477 of 2000 complete in 208.0 sec
[---------        23%                  ] 479 of 2000 complete in 208.9 sec
[---------        24%                  ] 480 of 2000 complete in 209.4 sec
[---------        24%                  ] 482 of 2000 complete in 210.3 sec
[---------        24%                  ] 484 of 2000 complete in 211.2 sec
[---------        24%                  ] 486 of 2000 complete in 212.0 sec
[---------        24%                  ] 488 of 2000 complete in 212.9 sec
[---------        24%                  ] 490 of 2000 complete in 213.7 sec
[---------        24%                  ] 492 of 2000 complete in 214.6 sec
[---------        24%                  ] 494 of 2000 complete in 215.5 sec
[---------        24%                  ] 496 of 2000 complete in 216.3 sec
[---------        24%                  ] 498 of 2000 complete in 217.1 sec
[---------        25%                  ] 500 of 2000 complete in 218.0 sec
[---------        25%                  ] 502 of 2000 complete in 218.9 sec
[---------        25%                  ] 504 of 2000 complete in 219.7 sec
[---------        25%                  ] 506 of 2000 complete in 220.6 sec
[---------        25%                  ] 508 of 2000 complete in 221.5 sec
[---------        25%                  ] 509 of 2000 complete in 222.0 sec
[---------        25%                  ] 511 of 2000 complete in 222.9 sec
[---------        25%                  ] 513 of 2000 complete in 223.8 sec
[---------        25%                  ] 515 of 2000 complete in 224.7 sec
[---------        25%                  ] 517 of 2000 complete in 225.6 sec
[---------        25%                  ] 519 of 2000 complete in 226.6 sec
[---------        26%                  ] 521 of 2000 complete in 227.6 sec
[---------        26%                  ] 523 of 2000 complete in 228.5 sec
[---------        26%                  ] 525 of 2000 complete in 229.5 sec
[----------       26%                  ] 527 of 2000 complete in 230.4 sec
[----------       26%                  ] 529 of 2000 complete in 231.2 sec
[----------       26%                  ] 531 of 2000 complete in 232.1 sec
[----------       26%                  ] 532 of 2000 complete in 232.6 sec
[----------       26%                  ] 534 of 2000 complete in 233.5 sec
[----------       26%                  ] 536 of 2000 complete in 234.4 sec
[----------       26%                  ] 538 of 2000 complete in 235.3 sec
[----------       27%                  ] 540 of 2000 complete in 236.3 sec
[----------       27%                  ] 542 of 2000 complete in 237.2 sec
[----------       27%                  ] 544 of 2000 complete in 238.1 sec
[----------       27%                  ] 546 of 2000 complete in 238.9 sec
[----------       27%                  ] 548 of 2000 complete in 239.7 sec
[----------       27%                  ] 550 of 2000 complete in 240.6 sec
[----------       27%                  ] 552 of 2000 complete in 241.5 sec
[----------       27%                  ] 554 of 2000 complete in 242.3 sec
[----------       27%                  ] 556 of 2000 complete in 243.2 sec
[----------       27%                  ] 558 of 2000 complete in 244.1 sec
[----------       28%                  ] 560 of 2000 complete in 244.9 sec
[----------       28%                  ] 562 of 2000 complete in 245.8 sec
[----------       28%                  ] 564 of 2000 complete in 246.7 sec
[----------       28%                  ] 566 of 2000 complete in 247.6 sec
[----------       28%                  ] 568 of 2000 complete in 248.5 sec
[----------       28%                  ] 570 of 2000 complete in 249.5 sec
[----------       28%                  ] 572 of 2000 complete in 250.4 sec
[----------       28%                  ] 574 of 2000 complete in 251.3 sec
[----------       28%                  ] 576 of 2000 complete in 252.3 sec
[----------       28%                  ] 578 of 2000 complete in 253.2 sec
[-----------      29%                  ] 580 of 2000 complete in 254.1 sec
[-----------      29%                  ] 582 of 2000 complete in 255.0 sec
[-----------      29%                  ] 584 of 2000 complete in 255.9 sec
[-----------      29%                  ] 586 of 2000 complete in 256.7 sec
[-----------      29%                  ] 588 of 2000 complete in 257.6 sec
[-----------      29%                  ] 590 of 2000 complete in 258.4 sec
[-----------      29%                  ] 592 of 2000 complete in 259.2 sec
[-----------      29%                  ] 594 of 2000 complete in 260.1 sec
[-----------      29%                  ] 595 of 2000 complete in 260.6 sec
[-----------      29%                  ] 597 of 2000 complete in 261.5 sec
[-----------      29%                  ] 599 of 2000 complete in 262.4 sec
[-----------      30%                  ] 601 of 2000 complete in 263.2 sec
[-----------      30%                  ] 603 of 2000 complete in 264.1 sec
[-----------      30%                  ] 605 of 2000 complete in 264.9 sec
[-----------      30%                  ] 607 of 2000 complete in 265.8 sec
[-----------      30%                  ] 609 of 2000 complete in 266.6 sec
[-----------      30%                  ] 611 of 2000 complete in 267.5 sec
[-----------      30%                  ] 613 of 2000 complete in 268.4 sec
[-----------      30%                  ] 615 of 2000 complete in 269.3 sec
[-----------      30%                  ] 617 of 2000 complete in 270.1 sec
[-----------      30%                  ] 619 of 2000 complete in 270.9 sec
[-----------      31%                  ] 621 of 2000 complete in 271.8 sec
[-----------      31%                  ] 623 of 2000 complete in 272.6 sec
[-----------      31%                  ] 625 of 2000 complete in 273.4 sec
[-----------      31%                  ] 627 of 2000 complete in 274.3 sec
[-----------      31%                  ] 629 of 2000 complete in 275.1 sec
[-----------      31%                  ] 631 of 2000 complete in 276.0 sec
[------------     31%                  ] 633 of 2000 complete in 276.8 sec
[------------     31%                  ] 635 of 2000 complete in 277.7 sec
[------------     31%                  ] 637 of 2000 complete in 278.5 sec

[--------         21%                  ] 425 of 2000 complete in 188.9 sec
[--------         21%                  ] 426 of 2000 complete in 189.5 sec
[--------         21%                  ] 427 of 2000 complete in 190.0 sec
[--------         21%                  ] 428 of 2000 complete in 190.5 sec
[--------         21%                  ] 429 of 2000 complete in 191.0 sec
[--------         21%                  ] 430 of 2000 complete in 191.5 sec
[--------         21%                  ] 431 of 2000 complete in 192.1 sec
[--------         21%                  ] 433 of 2000 complete in 193.0 sec
[--------         21%                  ] 434 of 2000 complete in 193.5 sec
[--------         21%                  ] 436 of 2000 complete in 194.5 sec
[--------         21%                  ] 438 of 2000 complete in 195.5 sec
[--------         22%                  ] 440 of 2000 complete in 196.5 sec
[--------         22%                  ] 441 of 2000 complete in 197.0 sec
[--------         22%                  ] 442 of 2000 complete in 197.5 sec
[--------         22%                  ] 444 of 2000 complete in 198.3 sec
[--------         22%                  ] 446 of 2000 complete in 199.2 sec
[--------         22%                  ] 448 of 2000 complete in 200.1 sec
[--------         22%                  ] 450 of 2000 complete in 201.0 sec
[--------         22%                  ] 452 of 2000 complete in 201.8 sec
[--------         22%                  ] 454 of 2000 complete in 202.7 sec
[--------         22%                  ] 456 of 2000 complete in 203.6 sec
[--------         22%                  ] 458 of 2000 complete in 204.5 sec
[--------         23%                  ] 460 of 2000 complete in 205.5 sec
[--------         23%                  ] 462 of 2000 complete in 206.4 sec
[--------         23%                  ] 464 of 2000 complete in 207.2 sec
[--------         23%                  ] 466 of 2000 complete in 208.1 sec
[--------         23%                  ] 468 of 2000 complete in 209.0 sec
[--------         23%                  ] 470 of 2000 complete in 209.9 sec
[--------         23%                  ] 472 of 2000 complete in 210.9 sec
[---------        23%                  ] 474 of 2000 complete in 211.7 sec
[---------        23%                  ] 476 of 2000 complete in 212.6 sec
[---------        23%                  ] 478 of 2000 complete in 213.5 sec
[---------        24%                  ] 480 of 2000 complete in 214.3 sec
[---------        24%                  ] 482 of 2000 complete in 215.2 sec
[---------        24%                  ] 484 of 2000 complete in 216.0 sec
[---------        24%                  ] 486 of 2000 complete in 216.9 sec
[---------        24%                  ] 488 of 2000 complete in 217.8 sec
[---------        24%                  ] 490 of 2000 complete in 218.7 sec
[---------        24%                  ] 492 of 2000 complete in 219.5 sec
[---------        24%                  ] 494 of 2000 complete in 220.4 sec
[---------        24%                  ] 496 of 2000 complete in 221.3 sec
[---------        24%                  ] 498 of 2000 complete in 222.2 sec
[---------        25%                  ] 500 of 2000 complete in 223.1 sec
[---------        25%                  ] 502 of 2000 complete in 224.1 sec
[---------        25%                  ] 504 of 2000 complete in 225.0 sec
[---------        25%                  ] 506 of 2000 complete in 226.0 sec
[---------        25%                  ] 508 of 2000 complete in 226.9 sec
[---------        25%                  ] 509 of 2000 complete in 227.5 sec
[---------        25%                  ] 511 of 2000 complete in 228.4 sec
[---------        25%                  ] 513 of 2000 complete in 229.5 sec
[---------        25%                  ] 515 of 2000 complete in 230.4 sec
[---------        25%                  ] 517 of 2000 complete in 231.3 sec
[---------        25%                  ] 519 of 2000 complete in 232.1 sec
[---------        26%                  ] 520 of 2000 complete in 232.6 sec
[---------        26%                  ] 522 of 2000 complete in 233.5 sec
[---------        26%                  ] 524 of 2000 complete in 234.4 sec
[---------        26%                  ] 525 of 2000 complete in 234.9 sec
[---------        26%                  ] 526 of 2000 complete in 235.4 sec
[----------       26%                  ] 528 of 2000 complete in 236.4 sec
[----------       26%                  ] 530 of 2000 complete in 237.3 sec
[----------       26%                  ] 532 of 2000 complete in 238.2 sec
[----------       26%                  ] 534 of 2000 complete in 239.1 sec
[----------       26%                  ] 536 of 2000 complete in 240.0 sec
[----------       26%                  ] 538 of 2000 complete in 240.9 sec
[----------       27%                  ] 540 of 2000 complete in 241.7 sec
[----------       27%                  ] 542 of 2000 complete in 242.7 sec
[----------       27%                  ] 544 of 2000 complete in 243.5 sec
[----------       27%                  ] 546 of 2000 complete in 244.4 sec
[----------       27%                  ] 548 of 2000 complete in 245.3 sec
[----------       27%                  ] 550 of 2000 complete in 246.2 sec
[----------       27%                  ] 552 of 2000 complete in 247.2 sec
[----------       27%                  ] 554 of 2000 complete in 248.1 sec
[----------       27%                  ] 556 of 2000 complete in 249.0 sec
[----------       27%                  ] 558 of 2000 complete in 249.9 sec
[----------       28%                  ] 560 of 2000 complete in 250.9 sec
[----------       28%                  ] 562 of 2000 complete in 251.8 sec
[----------       28%                  ] 564 of 2000 complete in 252.7 sec
[----------       28%                  ] 566 of 2000 complete in 253.6 sec
[----------       28%                  ] 568 of 2000 complete in 254.6 sec
[----------       28%                  ] 570 of 2000 complete in 255.5 sec
[----------       28%                  ] 572 of 2000 complete in 256.3 sec
[----------       28%                  ] 574 of 2000 complete in 257.2 sec
[----------       28%                  ] 576 of 2000 complete in 258.1 sec
[----------       28%                  ] 578 of 2000 complete in 258.9 sec
[-----------      29%                  ] 580 of 2000 complete in 259.8 sec
[-----------      29%                  ] 582 of 2000 complete in 260.8 sec
[-----------      29%                  ] 584 of 2000 complete in 261.7 sec
[-----------      29%                  ] 586 of 2000 complete in 262.6 sec
[-----------      29%                  ] 588 of 2000 complete in 263.4 sec
[-----------      29%                  ] 590 of 2000 complete in 264.3 sec
[-----------      29%                  ] 592 of 2000 complete in 265.2 sec
[-----------      29%                  ] 594 of 2000 complete in 266.1 sec
[-----------      29%                  ] 596 of 2000 complete in 267.0 sec
[-----------      29%                  ] 598 of 2000 complete in 267.8 sec
[-----------      30%                  ] 600 of 2000 complete in 268.7 sec
[-----------      30%                  ] 602 of 2000 complete in 269.6 sec
[-----------      30%                  ] 604 of 2000 complete in 270.5 sec
[-----------      30%                  ] 606 of 2000 complete in 271.3 sec
[-----------      30%                  ] 608 of 2000 complete in 272.2 sec
[-----------      30%                  ] 610 of 2000 complete in 273.1 sec
[-----------      30%                  ] 612 of 2000 complete in 273.9 sec
[-----------      30%                  ] 614 of 2000 complete in 274.8 sec
[-----------      30%                  ] 616 of 2000 complete in 275.7 sec
[-----------      30%                  ] 618 of 2000 complete in 276.5 sec
[-----------      31%                  ] 620 of 2000 complete in 277.4 sec
[-----------      31%                  ] 622 of 2000 complete in 278.2 sec
[-----------      31%                  ] 624 of 2000 complete in 279.1 sec
[-----------      31%                  ] 626 of 2000 complete in 279.9 sec
[-----------      31%                  ] 628 of 2000 complete in 280.8 sec
[--------         21%                  ] 424 of 2000 complete in 189.3 sec
[--------         21%                  ] 425 of 2000 complete in 189.8 sec
[--------         21%                  ] 426 of 2000 complete in 190.3 sec
[--------         21%                  ] 428 of 2000 complete in 191.3 sec
[--------         21%                  ] 429 of 2000 complete in 191.9 sec
[--------         21%                  ] 430 of 2000 complete in 192.4 sec
[--------         21%                  ] 431 of 2000 complete in 192.9 sec
[--------         21%                  ] 432 of 2000 complete in 193.4 sec
[--------         21%                  ] 433 of 2000 complete in 193.9 sec
[--------         21%                  ] 434 of 2000 complete in 194.4 sec
[--------         21%                  ] 436 of 2000 complete in 195.4 sec
[--------         21%                  ] 438 of 2000 complete in 196.4 sec
[--------         22%                  ] 440 of 2000 complete in 197.4 sec
[--------         22%                  ] 442 of 2000 complete in 198.3 sec
[--------         22%                  ] 444 of 2000 complete in 199.1 sec
[--------         22%                  ] 446 of 2000 complete in 200.0 sec
[--------         22%                  ] 448 of 2000 complete in 200.8 sec
[--------         22%                  ] 450 of 2000 complete in 201.7 sec
[--------         22%                  ] 452 of 2000 complete in 202.6 sec
[--------         22%                  ] 454 of 2000 complete in 203.5 sec
[--------         22%                  ] 456 of 2000 complete in 204.4 sec
[--------         22%                  ] 458 of 2000 complete in 205.4 sec
[--------         23%                  ] 460 of 2000 complete in 206.4 sec
[--------         23%                  ] 462 of 2000 complete in 207.2 sec
[--------         23%                  ] 464 of 2000 complete in 208.2 sec
[--------         23%                  ] 466 of 2000 complete in 209.2 sec
[--------         23%                  ] 468 of 2000 complete in 210.1 sec
[--------         23%                  ] 470 of 2000 complete in 211.0 sec
[--------         23%                  ] 472 of 2000 complete in 211.9 sec
[---------        23%                  ] 474 of 2000 complete in 212.8 sec
[---------        23%                  ] 476 of 2000 complete in 213.7 sec
[---------        23%                  ] 478 of 2000 complete in 214.6 sec
[---------        24%                  ] 480 of 2000 complete in 215.4 sec
[---------        24%                  ] 482 of 2000 complete in 216.3 sec
[---------        24%                  ] 484 of 2000 complete in 217.2 sec
[---------        24%                  ] 486 of 2000 complete in 218.0 sec
[---------        24%                  ] 488 of 2000 complete in 218.9 sec
[---------        24%                  ] 490 of 2000 complete in 219.8 sec
[---------        24%                  ] 492 of 2000 complete in 220.6 sec
[---------        24%                  ] 494 of 2000 complete in 221.6 sec
[---------        24%                  ] 496 of 2000 complete in 222.6 sec
[---------        24%                  ] 498 of 2000 complete in 223.5 sec
[---------        25%                  ] 500 of 2000 complete in 224.4 sec
[---------        25%                  ] 502 of 2000 complete in 225.3 sec
[---------        25%                  ] 504 of 2000 complete in 226.3 sec
[---------        25%                  ] 506 of 2000 complete in 227.3 sec
[---------        25%                  ] 507 of 2000 complete in 227.8 sec
[---------        25%                  ] 509 of 2000 complete in 228.8 sec
[---------        25%                  ] 510 of 2000 complete in 229.3 sec
[---------        25%                  ] 512 of 2000 complete in 230.3 sec
[---------        25%                  ] 514 of 2000 complete in 231.2 sec
[---------        25%                  ] 516 of 2000 complete in 232.0 sec
[---------        25%                  ] 517 of 2000 complete in 232.6 sec
[---------        25%                  ] 519 of 2000 complete in 233.5 sec
[---------        26%                  ] 521 of 2000 complete in 234.4 sec
[---------        26%                  ] 523 of 2000 complete in 235.4 sec
[---------        26%                  ] 525 of 2000 complete in 236.4 sec
[----------       26%                  ] 527 of 2000 complete in 237.3 sec
[----------       26%                  ] 529 of 2000 complete in 238.2 sec
[----------       26%                  ] 531 of 2000 complete in 239.0 sec
[----------       26%                  ] 533 of 2000 complete in 239.9 sec
[----------       26%                  ] 535 of 2000 complete in 240.8 sec
[----------       26%                  ] 537 of 2000 complete in 241.7 sec
[----------       26%                  ] 539 of 2000 complete in 242.6 sec
[----------       27%                  ] 541 of 2000 complete in 243.5 sec
[----------       27%                  ] 543 of 2000 complete in 244.3 sec
[----------       27%                  ] 545 of 2000 complete in 245.2 sec
[----------       27%                  ] 547 of 2000 complete in 246.1 sec
[----------       27%                  ] 549 of 2000 complete in 247.0 sec
[----------       27%                  ] 551 of 2000 complete in 248.0 sec
[----------       27%                  ] 553 of 2000 complete in 248.9 sec
[----------       27%                  ] 555 of 2000 complete in 249.8 sec
[----------       27%                  ] 557 of 2000 complete in 250.7 sec
[----------       27%                  ] 558 of 2000 complete in 251.2 sec
[----------       28%                  ] 560 of 2000 complete in 252.2 sec
[----------       28%                  ] 562 of 2000 complete in 253.1 sec
[----------       28%                  ] 564 of 2000 complete in 254.0 sec
[----------       28%                  ] 566 of 2000 complete in 255.0 sec
[----------       28%                  ] 568 of 2000 complete in 255.9 sec
[----------       28%                  ] 570 of 2000 complete in 256.7 sec
[----------       28%                  ] 572 of 2000 complete in 257.7 sec
[----------       28%                  ] 574 of 2000 complete in 258.5 sec
[----------       28%                  ] 576 of 2000 complete in 259.4 sec
[----------       28%                  ] 578 of 2000 complete in 260.3 sec
[-----------      29%                  ] 580 of 2000 complete in 261.3 sec
[-----------      29%                  ] 582 of 2000 complete in 262.1 sec
[-----------      29%                  ] 584 of 2000 complete in 263.0 sec
[-----------      29%                  ] 586 of 2000 complete in 263.9 sec
[-----------      29%                  ] 588 of 2000 complete in 264.8 sec
[-----------      29%                  ] 590 of 2000 complete in 265.7 sec
[-----------      29%                  ] 592 of 2000 complete in 266.6 sec
[-----------      29%                  ] 594 of 2000 complete in 267.4 sec
[-----------      29%                  ] 596 of 2000 complete in 268.3 sec
[-----------      29%                  ] 598 of 2000 complete in 269.2 sec
[-----------      30%                  ] 600 of 2000 complete in 270.1 sec
[-----------      30%                  ] 602 of 2000 complete in 270.9 sec
[-----------      30%                  ] 604 of 2000 complete in 271.8 sec
[-----------      30%                  ] 606 of 2000 complete in 272.6 sec
[-----------      30%                  ] 608 of 2000 complete in 273.5 sec
[-----------      30%                  ] 610 of 2000 complete in 274.4 sec
[-----------      30%                  ] 612 of 2000 complete in 275.2 sec
[-----------      30%                  ] 614 of 2000 complete in 276.1 sec
[-----------      30%                  ] 616 of 2000 complete in 276.9 sec
[-----------      30%                  ] 618 of 2000 complete in 277.8 sec
[-----------      31%                  ] 620 of 2000 complete in 278.7 sec
[-----------      31%                  ] 622 of 2000 complete in 279.6 sec
[-----------      31%                  ] 624 of 2000 complete in 280.4 sec
[-----------      31%                  ] 626 of 2000 complete in 281.3 sec
[-----------      31%                  ] 628 of 2000 complete in 282.1 sec

[------------     31%                  ] 633 of 2000 complete in 278.1 sec
[------------     31%                  ] 635 of 2000 complete in 278.9 sec
[------------     31%                  ] 637 of 2000 complete in 279.8 sec
[------------     31%                  ] 639 of 2000 complete in 280.6 sec
[------------     32%                  ] 641 of 2000 complete in 281.4 sec
[------------     32%                  ] 643 of 2000 complete in 282.3 sec
[------------     32%                  ] 645 of 2000 complete in 283.2 sec
[------------     32%                  ] 647 of 2000 complete in 284.1 sec
[------------     32%                  ] 649 of 2000 complete in 284.9 sec
[------------     32%                  ] 651 of 2000 complete in 285.7 sec
[------------     32%                  ] 653 of 2000 complete in 286.6 sec
[------------     32%                  ] 655 of 2000 complete in 287.4 sec
[------------     32%                  ] 657 of 2000 complete in 288.3 sec
[------------     32%                  ] 659 of 2000 complete in 289.1 sec
[------------     33%                  ] 661 of 2000 complete in 290.0 sec
[------------     33%                  ] 663 of 2000 complete in 290.8 sec
[------------     33%                  ] 665 of 2000 complete in 291.7 sec
[------------     33%                  ] 667 of 2000 complete in 292.5 sec
[------------     33%                  ] 669 of 2000 complete in 293.4 sec
[------------     33%                  ] 671 of 2000 complete in 294.3 sec
[------------     33%                  ] 673 of 2000 complete in 295.2 sec
[------------     33%                  ] 675 of 2000 complete in 296.0 sec
[------------     33%                  ] 677 of 2000 complete in 297.0 sec
[------------     33%                  ] 679 of 2000 complete in 297.8 sec
[------------     34%                  ] 681 of 2000 complete in 298.7 sec
[------------     34%                  ] 683 of 2000 complete in 299.5 sec
[-------------    34%                  ] 685 of 2000 complete in 300.4 sec
[-------------    34%                  ] 687 of 2000 complete in 301.3 sec
[-------------    34%                  ] 689 of 2000 complete in 302.1 sec
[-------------    34%                  ] 691 of 2000 complete in 303.0 sec
[-------------    34%                  ] 693 of 2000 complete in 303.9 sec
[-------------    34%                  ] 695 of 2000 complete in 304.8 sec
[-------------    34%                  ] 697 of 2000 complete in 305.7 sec
[-------------    34%                  ] 699 of 2000 complete in 306.6 sec
[-------------    35%                  ] 701 of 2000 complete in 307.5 sec
[-------------    35%                  ] 703 of 2000 complete in 308.3 sec
[-------------    35%                  ] 705 of 2000 complete in 309.2 sec
[-------------    35%                  ] 707 of 2000 complete in 310.1 sec
[-------------    35%                  ] 709 of 2000 complete in 311.0 sec
[-------------    35%                  ] 711 of 2000 complete in 311.8 sec
[-------------    35%                  ] 713 of 2000 complete in 312.7 sec
[-------------    35%                  ] 715 of 2000 complete in 313.6 sec
[-------------    35%                  ] 716 of 2000 complete in 314.2 sec
[-------------    35%                  ] 718 of 2000 complete in 315.1 sec
[-------------    36%                  ] 720 of 2000 complete in 316.0 sec
[-------------    36%                  ] 722 of 2000 complete in 316.9 sec
[-------------    36%                  ] 724 of 2000 complete in 317.7 sec
[-------------    36%                  ] 726 of 2000 complete in 318.6 sec
[-------------    36%                  ] 728 of 2000 complete in 319.5 sec
[-------------    36%                  ] 730 of 2000 complete in 320.4 sec
[-------------    36%                  ] 731 of 2000 complete in 320.9 sec
[-------------    36%                  ] 733 of 2000 complete in 321.8 sec
[-------------    36%                  ] 735 of 2000 complete in 322.7 sec
[--------------   36%                  ] 737 of 2000 complete in 323.6 sec
[--------------   36%                  ] 739 of 2000 complete in 324.5 sec
[--------------   37%                  ] 741 of 2000 complete in 325.3 sec
[--------------   37%                  ] 743 of 2000 complete in 326.2 sec
[--------------   37%                  ] 745 of 2000 complete in 327.0 sec
[--------------   37%                  ] 747 of 2000 complete in 327.9 sec
[--------------   37%                  ] 749 of 2000 complete in 328.7 sec
[--------------   37%                  ] 751 of 2000 complete in 329.5 sec
[--------------   37%                  ] 753 of 2000 complete in 330.4 sec
[--------------   37%                  ] 755 of 2000 complete in 331.2 sec
[--------------   37%                  ] 757 of 2000 complete in 332.1 sec
[--------------   37%                  ] 759 of 2000 complete in 333.0 sec
[--------------   38%                  ] 761 of 2000 complete in 333.9 sec
[--------------   38%                  ] 763 of 2000 complete in 334.8 sec
[--------------   38%                  ] 765 of 2000 complete in 335.8 sec
[--------------   38%                  ] 766 of 2000 complete in 336.3 sec
[--------------   38%                  ] 767 of 2000 complete in 336.8 sec
[--------------   38%                  ] 769 of 2000 complete in 337.8 sec
[--------------   38%                  ] 771 of 2000 complete in 338.8 sec
[--------------   38%                  ] 773 of 2000 complete in 339.7 sec
[--------------   38%                  ] 775 of 2000 complete in 340.6 sec
[--------------   38%                  ] 777 of 2000 complete in 341.5 sec
[--------------   38%                  ] 779 of 2000 complete in 342.4 sec
[--------------   39%                  ] 781 of 2000 complete in 343.3 sec
[--------------   39%                  ] 783 of 2000 complete in 344.1 sec
[--------------   39%                  ] 785 of 2000 complete in 345.1 sec
[--------------   39%                  ] 787 of 2000 complete in 345.9 sec
[--------------   39%                  ] 789 of 2000 complete in 346.8 sec
[---------------  39%                  ] 791 of 2000 complete in 347.7 sec
[---------------  39%                  ] 793 of 2000 complete in 348.6 sec
[---------------  39%                  ] 795 of 2000 complete in 349.4 sec
[---------------  39%                  ] 797 of 2000 complete in 350.3 sec
[---------------  39%                  ] 799 of 2000 complete in 351.2 sec
[---------------  40%                  ] 801 of 2000 complete in 352.0 sec
[---------------  40%                  ] 803 of 2000 complete in 353.0 sec
[---------------  40%                  ] 805 of 2000 complete in 353.9 sec
[---------------  40%                  ] 806 of 2000 complete in 354.4 sec
[---------------  40%                  ] 807 of 2000 complete in 355.0 sec
[---------------  40%                  ] 808 of 2000 complete in 355.5 sec
[---------------  40%                  ] 809 of 2000 complete in 356.0 sec
[---------------  40%                  ] 810 of 2000 complete in 356.6 sec
[---------------  40%                  ] 811 of 2000 complete in 357.1 sec
[---------------  40%                  ] 812 of 2000 complete in 357.6 sec
[---------------  40%                  ] 813 of 2000 complete in 358.2 sec
[---------------  40%                  ] 814 of 2000 complete in 358.7 sec
[---------------  40%                  ] 815 of 2000 complete in 359.2 sec
[---------------  40%                  ] 817 of 2000 complete in 360.2 sec
[---------------  40%                  ] 819 of 2000 complete in 361.1 sec
[---------------  41%                  ] 821 of 2000 complete in 362.1 sec
[---------------  41%                  ] 822 of 2000 complete in 362.6 sec
[---------------  41%                  ] 824 of 2000 complete in 363.6 sec
[---------------  41%                  ] 826 of 2000 complete in 364.5 sec
[---------------  41%                  ] 828 of 2000 complete in 365.5 sec
[---------------  41%                  ] 830 of 2000 complete in 366.4 sec
[---------------  41%                  ] 832 of 2000 complete in 367.2 sec
[---------------  41%                  ] 834 of 2000 complete in 368.1 sec
[------------     31%                  ] 639 of 2000 complete in 279.3 sec
[------------     32%                  ] 641 of 2000 complete in 280.1 sec
[------------     32%                  ] 643 of 2000 complete in 281.0 sec
[------------     32%                  ] 645 of 2000 complete in 281.8 sec
[------------     32%                  ] 647 of 2000 complete in 282.7 sec
[------------     32%                  ] 649 of 2000 complete in 283.6 sec
[------------     32%                  ] 651 of 2000 complete in 284.4 sec
[------------     32%                  ] 653 of 2000 complete in 285.3 sec
[------------     32%                  ] 655 of 2000 complete in 286.1 sec
[------------     32%                  ] 657 of 2000 complete in 287.0 sec
[------------     32%                  ] 659 of 2000 complete in 287.8 sec
[------------     33%                  ] 661 of 2000 complete in 288.6 sec
[------------     33%                  ] 663 of 2000 complete in 289.5 sec
[------------     33%                  ] 665 of 2000 complete in 290.4 sec
[------------     33%                  ] 667 of 2000 complete in 291.3 sec
[------------     33%                  ] 669 of 2000 complete in 292.1 sec
[------------     33%                  ] 671 of 2000 complete in 293.0 sec
[------------     33%                  ] 673 of 2000 complete in 293.8 sec
[------------     33%                  ] 675 of 2000 complete in 294.6 sec
[------------     33%                  ] 677 of 2000 complete in 295.5 sec
[------------     33%                  ] 679 of 2000 complete in 296.4 sec
[------------     34%                  ] 681 of 2000 complete in 297.3 sec
[------------     34%                  ] 683 of 2000 complete in 298.2 sec
[-------------    34%                  ] 685 of 2000 complete in 299.0 sec
[-------------    34%                  ] 687 of 2000 complete in 299.8 sec
[-------------    34%                  ] 689 of 2000 complete in 300.7 sec
[-------------    34%                  ] 691 of 2000 complete in 301.6 sec
[-------------    34%                  ] 693 of 2000 complete in 302.4 sec
[-------------    34%                  ] 695 of 2000 complete in 303.3 sec
[-------------    34%                  ] 697 of 2000 complete in 304.1 sec
[-------------    34%                  ] 699 of 2000 complete in 305.0 sec
[-------------    35%                  ] 701 of 2000 complete in 305.9 sec
[-------------    35%                  ] 703 of 2000 complete in 306.7 sec
[-------------    35%                  ] 705 of 2000 complete in 307.6 sec
[-------------    35%                  ] 707 of 2000 complete in 308.5 sec
[-------------    35%                  ] 709 of 2000 complete in 309.3 sec
[-------------    35%                  ] 711 of 2000 complete in 310.2 sec
[-------------    35%                  ] 713 of 2000 complete in 311.1 sec
[-------------    35%                  ] 715 of 2000 complete in 312.0 sec
[-------------    35%                  ] 717 of 2000 complete in 312.9 sec
[-------------    35%                  ] 719 of 2000 complete in 313.8 sec
[-------------    36%                  ] 720 of 2000 complete in 314.3 sec
[-------------    36%                  ] 722 of 2000 complete in 315.3 sec
[-------------    36%                  ] 724 of 2000 complete in 316.1 sec
[-------------    36%                  ] 726 of 2000 complete in 317.0 sec
[-------------    36%                  ] 728 of 2000 complete in 317.9 sec
[-------------    36%                  ] 730 of 2000 complete in 318.8 sec
[-------------    36%                  ] 732 of 2000 complete in 319.7 sec
[-------------    36%                  ] 734 of 2000 complete in 320.5 sec
[-------------    36%                  ] 735 of 2000 complete in 321.0 sec
[--------------   36%                  ] 737 of 2000 complete in 321.9 sec
[--------------   36%                  ] 739 of 2000 complete in 322.7 sec
[--------------   37%                  ] 741 of 2000 complete in 323.7 sec
[--------------   37%                  ] 743 of 2000 complete in 324.6 sec
[--------------   37%                  ] 745 of 2000 complete in 325.4 sec
[--------------   37%                  ] 747 of 2000 complete in 326.3 sec
[--------------   37%                  ] 749 of 2000 complete in 327.1 sec
[--------------   37%                  ] 751 of 2000 complete in 327.9 sec
[--------------   37%                  ] 753 of 2000 complete in 328.7 sec
[--------------   37%                  ] 755 of 2000 complete in 329.6 sec
[--------------   37%                  ] 757 of 2000 complete in 330.4 sec
[--------------   37%                  ] 759 of 2000 complete in 331.2 sec
[--------------   38%                  ] 761 of 2000 complete in 332.1 sec
[--------------   38%                  ] 763 of 2000 complete in 333.0 sec
[--------------   38%                  ] 765 of 2000 complete in 333.9 sec
[--------------   38%                  ] 767 of 2000 complete in 334.8 sec
[--------------   38%                  ] 769 of 2000 complete in 335.7 sec
[--------------   38%                  ] 770 of 2000 complete in 336.2 sec
[--------------   38%                  ] 772 of 2000 complete in 337.2 sec
[--------------   38%                  ] 773 of 2000 complete in 337.7 sec
[--------------   38%                  ] 774 of 2000 complete in 338.2 sec
[--------------   38%                  ] 776 of 2000 complete in 339.1 sec
[--------------   38%                  ] 778 of 2000 complete in 340.0 sec
[--------------   39%                  ] 780 of 2000 complete in 340.9 sec
[--------------   39%                  ] 782 of 2000 complete in 341.8 sec
[--------------   39%                  ] 784 of 2000 complete in 342.7 sec
[--------------   39%                  ] 786 of 2000 complete in 343.6 sec
[--------------   39%                  ] 788 of 2000 complete in 344.4 sec
[---------------  39%                  ] 790 of 2000 complete in 345.3 sec
[---------------  39%                  ] 792 of 2000 complete in 346.2 sec
[---------------  39%                  ] 794 of 2000 complete in 347.1 sec
[---------------  39%                  ] 796 of 2000 complete in 347.9 sec
[---------------  39%                  ] 798 of 2000 complete in 348.8 sec
[---------------  40%                  ] 800 of 2000 complete in 349.7 sec
[---------------  40%                  ] 802 of 2000 complete in 350.5 sec
[---------------  40%                  ] 804 of 2000 complete in 351.4 sec
[---------------  40%                  ] 806 of 2000 complete in 352.3 sec
[---------------  40%                  ] 808 of 2000 complete in 353.3 sec
[---------------  40%                  ] 810 of 2000 complete in 354.2 sec
[---------------  40%                  ] 812 of 2000 complete in 355.3 sec
[---------------  40%                  ] 813 of 2000 complete in 355.8 sec
[---------------  40%                  ] 814 of 2000 complete in 356.3 sec
[---------------  40%                  ] 815 of 2000 complete in 356.8 sec
[---------------  40%                  ] 816 of 2000 complete in 357.4 sec
[---------------  40%                  ] 817 of 2000 complete in 357.9 sec
[---------------  40%                  ] 818 of 2000 complete in 358.4 sec
[---------------  40%                  ] 819 of 2000 complete in 359.0 sec
[---------------  41%                  ] 820 of 2000 complete in 359.5 sec
[---------------  41%                  ] 822 of 2000 complete in 360.5 sec
[---------------  41%                  ] 824 of 2000 complete in 361.4 sec
[---------------  41%                  ] 826 of 2000 complete in 362.5 sec
[---------------  41%                  ] 828 of 2000 complete in 363.4 sec
[---------------  41%                  ] 830 of 2000 complete in 364.3 sec
[---------------  41%                  ] 832 of 2000 complete in 365.2 sec
[---------------  41%                  ] 834 of 2000 complete in 366.1 sec
[---------------  41%                  ] 836 of 2000 complete in 366.9 sec
[---------------  41%                  ] 838 of 2000 complete in 367.8 sec
[---------------  42%                  ] 840 of 2000 complete in 368.6 sec
[---------------  42%                  ] 842 of 2000 complete in 369.4 sec

[-----------      31%                  ] 630 of 2000 complete in 281.7 sec
[------------     31%                  ] 632 of 2000 complete in 282.6 sec
[------------     31%                  ] 634 of 2000 complete in 283.4 sec
[------------     31%                  ] 636 of 2000 complete in 284.3 sec
[------------     31%                  ] 638 of 2000 complete in 285.1 sec
[------------     32%                  ] 640 of 2000 complete in 286.0 sec
[------------     32%                  ] 642 of 2000 complete in 286.8 sec
[------------     32%                  ] 644 of 2000 complete in 287.7 sec
[------------     32%                  ] 646 of 2000 complete in 288.5 sec
[------------     32%                  ] 648 of 2000 complete in 289.4 sec
[------------     32%                  ] 650 of 2000 complete in 290.3 sec
[------------     32%                  ] 652 of 2000 complete in 291.2 sec
[------------     32%                  ] 654 of 2000 complete in 292.1 sec
[------------     32%                  ] 656 of 2000 complete in 293.0 sec
[------------     32%                  ] 658 of 2000 complete in 293.8 sec
[------------     33%                  ] 660 of 2000 complete in 294.7 sec
[------------     33%                  ] 662 of 2000 complete in 295.6 sec
[------------     33%                  ] 664 of 2000 complete in 296.5 sec
[------------     33%                  ] 666 of 2000 complete in 297.4 sec
[------------     33%                  ] 668 of 2000 complete in 298.3 sec
[------------     33%                  ] 670 of 2000 complete in 299.2 sec
[------------     33%                  ] 672 of 2000 complete in 300.1 sec
[------------     33%                  ] 674 of 2000 complete in 300.9 sec
[------------     33%                  ] 676 of 2000 complete in 301.9 sec
[------------     33%                  ] 678 of 2000 complete in 302.7 sec
[------------     34%                  ] 680 of 2000 complete in 303.7 sec
[------------     34%                  ] 682 of 2000 complete in 304.6 sec
[------------     34%                  ] 684 of 2000 complete in 305.5 sec
[-------------    34%                  ] 686 of 2000 complete in 306.4 sec
[-------------    34%                  ] 688 of 2000 complete in 307.2 sec
[-------------    34%                  ] 690 of 2000 complete in 308.1 sec
[-------------    34%                  ] 691 of 2000 complete in 308.6 sec
[-------------    34%                  ] 693 of 2000 complete in 309.5 sec
[-------------    34%                  ] 695 of 2000 complete in 310.3 sec
[-------------    34%                  ] 697 of 2000 complete in 311.3 sec
[-------------    34%                  ] 699 of 2000 complete in 312.2 sec
[-------------    35%                  ] 701 of 2000 complete in 313.0 sec
[-------------    35%                  ] 702 of 2000 complete in 313.6 sec
[-------------    35%                  ] 703 of 2000 complete in 314.1 sec
[-------------    35%                  ] 704 of 2000 complete in 314.6 sec
[-------------    35%                  ] 706 of 2000 complete in 315.5 sec
[-------------    35%                  ] 708 of 2000 complete in 316.4 sec
[-------------    35%                  ] 710 of 2000 complete in 317.3 sec
[-------------    35%                  ] 712 of 2000 complete in 318.2 sec
[-------------    35%                  ] 714 of 2000 complete in 319.0 sec
[-------------    35%                  ] 716 of 2000 complete in 320.0 sec
[-------------    35%                  ] 718 of 2000 complete in 320.9 sec
[-------------    36%                  ] 720 of 2000 complete in 321.8 sec
[-------------    36%                  ] 722 of 2000 complete in 322.7 sec
[-------------    36%                  ] 724 of 2000 complete in 323.6 sec
[-------------    36%                  ] 726 of 2000 complete in 324.6 sec
[-------------    36%                  ] 728 of 2000 complete in 325.4 sec
[-------------    36%                  ] 730 of 2000 complete in 326.3 sec
[-------------    36%                  ] 732 of 2000 complete in 327.1 sec
[-------------    36%                  ] 734 of 2000 complete in 327.9 sec
[-------------    36%                  ] 736 of 2000 complete in 328.8 sec
[--------------   36%                  ] 738 of 2000 complete in 329.6 sec
[--------------   37%                  ] 740 of 2000 complete in 330.5 sec
[--------------   37%                  ] 742 of 2000 complete in 331.4 sec
[--------------   37%                  ] 744 of 2000 complete in 332.2 sec
[--------------   37%                  ] 746 of 2000 complete in 333.2 sec
[--------------   37%                  ] 748 of 2000 complete in 334.1 sec
[--------------   37%                  ] 750 of 2000 complete in 335.0 sec
[--------------   37%                  ] 752 of 2000 complete in 336.0 sec
[--------------   37%                  ] 753 of 2000 complete in 336.6 sec
[--------------   37%                  ] 755 of 2000 complete in 337.6 sec
[--------------   37%                  ] 757 of 2000 complete in 338.5 sec
[--------------   37%                  ] 759 of 2000 complete in 339.4 sec
[--------------   38%                  ] 761 of 2000 complete in 340.4 sec
[--------------   38%                  ] 763 of 2000 complete in 341.3 sec
[--------------   38%                  ] 765 of 2000 complete in 342.2 sec
[--------------   38%                  ] 767 of 2000 complete in 343.1 sec
[--------------   38%                  ] 769 of 2000 complete in 343.9 sec
[--------------   38%                  ] 771 of 2000 complete in 344.8 sec
[--------------   38%                  ] 773 of 2000 complete in 345.7 sec
[--------------   38%                  ] 775 of 2000 complete in 346.6 sec
[--------------   38%                  ] 777 of 2000 complete in 347.5 sec
[--------------   38%                  ] 779 of 2000 complete in 348.4 sec
[--------------   39%                  ] 781 of 2000 complete in 349.3 sec
[--------------   39%                  ] 783 of 2000 complete in 350.2 sec
[--------------   39%                  ] 785 of 2000 complete in 351.1 sec
[--------------   39%                  ] 787 of 2000 complete in 352.0 sec
[--------------   39%                  ] 789 of 2000 complete in 353.0 sec
[---------------  39%                  ] 791 of 2000 complete in 354.0 sec
[---------------  39%                  ] 793 of 2000 complete in 355.0 sec
[---------------  39%                  ] 794 of 2000 complete in 355.5 sec
[---------------  39%                  ] 795 of 2000 complete in 356.0 sec
[---------------  39%                  ] 796 of 2000 complete in 356.6 sec
[---------------  39%                  ] 797 of 2000 complete in 357.1 sec
[---------------  39%                  ] 798 of 2000 complete in 357.7 sec
[---------------  39%                  ] 799 of 2000 complete in 358.2 sec
[---------------  40%                  ] 800 of 2000 complete in 358.8 sec
[---------------  40%                  ] 801 of 2000 complete in 359.3 sec
[---------------  40%                  ] 803 of 2000 complete in 360.3 sec
[---------------  40%                  ] 805 of 2000 complete in 361.3 sec
[---------------  40%                  ] 807 of 2000 complete in 362.3 sec
[---------------  40%                  ] 808 of 2000 complete in 362.8 sec
[---------------  40%                  ] 810 of 2000 complete in 363.7 sec
[---------------  40%                  ] 812 of 2000 complete in 364.6 sec
[---------------  40%                  ] 814 of 2000 complete in 365.6 sec
[---------------  40%                  ] 816 of 2000 complete in 366.5 sec
[---------------  40%                  ] 818 of 2000 complete in 367.3 sec
[---------------  41%                  ] 820 of 2000 complete in 368.2 sec
[---------------  41%                  ] 822 of 2000 complete in 369.1 sec
[---------------  41%                  ] 824 of 2000 complete in 369.9 sec
[---------------  41%                  ] 826 of 2000 complete in 370.8 sec
[---------------  41%                  ] 828 of 2000 complete in 371.6 sec
[---------------  41%                  ] 830 of 2000 complete in 372.5 sec
[---------------  41%                  ] 832 of 2000 complete in 373.3 sec
[-----------      31%                  ] 630 of 2000 complete in 283.0 sec
[------------     31%                  ] 632 of 2000 complete in 283.9 sec
[------------     31%                  ] 634 of 2000 complete in 284.8 sec
[------------     31%                  ] 636 of 2000 complete in 285.6 sec
[------------     31%                  ] 638 of 2000 complete in 286.5 sec
[------------     32%                  ] 640 of 2000 complete in 287.4 sec
[------------     32%                  ] 642 of 2000 complete in 288.2 sec
[------------     32%                  ] 644 of 2000 complete in 289.1 sec
[------------     32%                  ] 646 of 2000 complete in 290.0 sec
[------------     32%                  ] 648 of 2000 complete in 290.9 sec
[------------     32%                  ] 650 of 2000 complete in 291.8 sec
[------------     32%                  ] 652 of 2000 complete in 292.7 sec
[------------     32%                  ] 654 of 2000 complete in 293.5 sec
[------------     32%                  ] 656 of 2000 complete in 294.4 sec
[------------     32%                  ] 658 of 2000 complete in 295.3 sec
[------------     33%                  ] 660 of 2000 complete in 296.1 sec
[------------     33%                  ] 662 of 2000 complete in 297.1 sec
[------------     33%                  ] 664 of 2000 complete in 297.9 sec
[------------     33%                  ] 666 of 2000 complete in 298.8 sec
[------------     33%                  ] 668 of 2000 complete in 299.7 sec
[------------     33%                  ] 670 of 2000 complete in 300.5 sec
[------------     33%                  ] 672 of 2000 complete in 301.5 sec
[------------     33%                  ] 674 of 2000 complete in 302.3 sec
[------------     33%                  ] 676 of 2000 complete in 303.2 sec
[------------     33%                  ] 678 of 2000 complete in 304.1 sec
[------------     33%                  ] 679 of 2000 complete in 304.6 sec
[------------     34%                  ] 681 of 2000 complete in 305.5 sec
[------------     34%                  ] 683 of 2000 complete in 306.4 sec
[-------------    34%                  ] 685 of 2000 complete in 307.3 sec
[-------------    34%                  ] 687 of 2000 complete in 308.2 sec
[-------------    34%                  ] 689 of 2000 complete in 309.1 sec
[-------------    34%                  ] 691 of 2000 complete in 310.0 sec
[-------------    34%                  ] 693 of 2000 complete in 310.9 sec
[-------------    34%                  ] 695 of 2000 complete in 311.8 sec
[-------------    34%                  ] 697 of 2000 complete in 312.7 sec
[-------------    34%                  ] 699 of 2000 complete in 313.7 sec
[-------------    35%                  ] 700 of 2000 complete in 314.3 sec
[-------------    35%                  ] 701 of 2000 complete in 314.8 sec
[-------------    35%                  ] 703 of 2000 complete in 315.7 sec
[-------------    35%                  ] 705 of 2000 complete in 316.6 sec
[-------------    35%                  ] 707 of 2000 complete in 317.4 sec
[-------------    35%                  ] 709 of 2000 complete in 318.3 sec
[-------------    35%                  ] 711 of 2000 complete in 319.2 sec
[-------------    35%                  ] 713 of 2000 complete in 320.1 sec
[-------------    35%                  ] 715 of 2000 complete in 321.1 sec
[-------------    35%                  ] 717 of 2000 complete in 322.0 sec
[-------------    35%                  ] 719 of 2000 complete in 322.9 sec
[-------------    36%                  ] 721 of 2000 complete in 323.8 sec
[-------------    36%                  ] 723 of 2000 complete in 324.7 sec
[-------------    36%                  ] 725 of 2000 complete in 325.6 sec
[-------------    36%                  ] 727 of 2000 complete in 326.4 sec
[-------------    36%                  ] 729 of 2000 complete in 327.3 sec
[-------------    36%                  ] 731 of 2000 complete in 328.2 sec
[-------------    36%                  ] 733 of 2000 complete in 329.0 sec
[-------------    36%                  ] 735 of 2000 complete in 329.9 sec
[--------------   36%                  ] 737 of 2000 complete in 330.8 sec
[--------------   36%                  ] 739 of 2000 complete in 331.6 sec
[--------------   37%                  ] 741 of 2000 complete in 332.6 sec
[--------------   37%                  ] 743 of 2000 complete in 333.5 sec
[--------------   37%                  ] 745 of 2000 complete in 334.4 sec
[--------------   37%                  ] 747 of 2000 complete in 335.4 sec
[--------------   37%                  ] 749 of 2000 complete in 336.4 sec
[--------------   37%                  ] 751 of 2000 complete in 337.4 sec
[--------------   37%                  ] 753 of 2000 complete in 338.3 sec
[--------------   37%                  ] 755 of 2000 complete in 339.3 sec
[--------------   37%                  ] 757 of 2000 complete in 340.2 sec
[--------------   37%                  ] 759 of 2000 complete in 341.2 sec
[--------------   38%                  ] 761 of 2000 complete in 342.1 sec
[--------------   38%                  ] 763 of 2000 complete in 343.0 sec
[--------------   38%                  ] 765 of 2000 complete in 343.8 sec
[--------------   38%                  ] 767 of 2000 complete in 344.8 sec
[--------------   38%                  ] 769 of 2000 complete in 345.7 sec
[--------------   38%                  ] 771 of 2000 complete in 346.6 sec
[--------------   38%                  ] 773 of 2000 complete in 347.5 sec
[--------------   38%                  ] 775 of 2000 complete in 348.4 sec
[--------------   38%                  ] 777 of 2000 complete in 349.3 sec
[--------------   38%                  ] 779 of 2000 complete in 350.1 sec
[--------------   39%                  ] 781 of 2000 complete in 351.1 sec
[--------------   39%                  ] 783 of 2000 complete in 351.9 sec
[--------------   39%                  ] 785 of 2000 complete in 352.9 sec
[--------------   39%                  ] 787 of 2000 complete in 353.9 sec
[--------------   39%                  ] 788 of 2000 complete in 354.4 sec
[--------------   39%                  ] 789 of 2000 complete in 354.9 sec
[---------------  39%                  ] 790 of 2000 complete in 355.4 sec
[---------------  39%                  ] 791 of 2000 complete in 356.0 sec
[---------------  39%                  ] 792 of 2000 complete in 356.5 sec
[---------------  39%                  ] 793 of 2000 complete in 357.1 sec
[---------------  39%                  ] 794 of 2000 complete in 357.6 sec
[---------------  39%                  ] 795 of 2000 complete in 358.2 sec
[---------------  39%                  ] 796 of 2000 complete in 358.7 sec
[---------------  39%                  ] 797 of 2000 complete in 359.3 sec
[---------------  39%                  ] 799 of 2000 complete in 360.2 sec
[---------------  40%                  ] 801 of 2000 complete in 361.2 sec
[---------------  40%                  ] 803 of 2000 complete in 362.2 sec
[---------------  40%                  ] 804 of 2000 complete in 362.7 sec
[---------------  40%                  ] 805 of 2000 complete in 363.2 sec
[---------------  40%                  ] 807 of 2000 complete in 364.1 sec
[---------------  40%                  ] 809 of 2000 complete in 365.1 sec
[---------------  40%                  ] 810 of 2000 complete in 365.6 sec
[---------------  40%                  ] 812 of 2000 complete in 366.4 sec
[---------------  40%                  ] 814 of 2000 complete in 367.3 sec
[---------------  40%                  ] 816 of 2000 complete in 368.2 sec
[---------------  40%                  ] 818 of 2000 complete in 369.0 sec
[---------------  41%                  ] 820 of 2000 complete in 369.9 sec
[---------------  41%                  ] 822 of 2000 complete in 370.8 sec
[---------------  41%                  ] 824 of 2000 complete in 371.6 sec
[---------------  41%                  ] 826 of 2000 complete in 372.5 sec
[---------------  41%                  ] 828 of 2000 complete in 373.4 sec
[---------------  41%                  ] 830 of 2000 complete in 374.3 sec

[---------------  41%                  ] 836 of 2000 complete in 368.9 sec
[---------------  41%                  ] 838 of 2000 complete in 369.8 sec
[---------------  42%                  ] 840 of 2000 complete in 370.7 sec
[---------------  42%                  ] 842 of 2000 complete in 371.5 sec
[---------------- 42%                  ] 844 of 2000 complete in 372.3 sec
[---------------- 42%                  ] 846 of 2000 complete in 373.2 sec
[---------------- 42%                  ] 848 of 2000 complete in 374.1 sec
[---------------- 42%                  ] 850 of 2000 complete in 375.0 sec
[---------------- 42%                  ] 852 of 2000 complete in 375.9 sec
[---------------- 42%                  ] 854 of 2000 complete in 376.7 sec
[---------------- 42%                  ] 856 of 2000 complete in 377.6 sec
[---------------- 42%                  ] 858 of 2000 complete in 378.4 sec
[---------------- 43%                  ] 860 of 2000 complete in 379.3 sec
[---------------- 43%                  ] 862 of 2000 complete in 380.1 sec
[---------------- 43%                  ] 864 of 2000 complete in 381.0 sec
[---------------- 43%                  ] 866 of 2000 complete in 381.8 sec
[---------------- 43%                  ] 868 of 2000 complete in 382.7 sec
[---------------- 43%                  ] 870 of 2000 complete in 383.6 sec
[---------------- 43%                  ] 872 of 2000 complete in 384.5 sec
[---------------- 43%                  ] 874 of 2000 complete in 385.3 sec
[---------------- 43%                  ] 876 of 2000 complete in 386.2 sec
[---------------- 43%                  ] 878 of 2000 complete in 387.1 sec
[---------------- 44%                  ] 880 of 2000 complete in 388.0 sec
[---------------- 44%                  ] 882 of 2000 complete in 388.9 sec
[---------------- 44%                  ] 884 of 2000 complete in 389.8 sec
[---------------- 44%                  ] 886 of 2000 complete in 390.7 sec
[---------------- 44%                  ] 888 of 2000 complete in 391.5 sec
[---------------- 44%                  ] 890 of 2000 complete in 392.4 sec
[---------------- 44%                  ] 892 of 2000 complete in 393.2 sec
[---------------- 44%                  ] 894 of 2000 complete in 394.1 sec
[-----------------44%                  ] 896 of 2000 complete in 395.0 sec
[-----------------44%                  ] 898 of 2000 complete in 395.8 sec
[-----------------45%                  ] 900 of 2000 complete in 396.7 sec
[-----------------45%                  ] 902 of 2000 complete in 397.5 sec
[-----------------45%                  ] 904 of 2000 complete in 398.4 sec
[-----------------45%                  ] 906 of 2000 complete in 399.2 sec
[-----------------45%                  ] 908 of 2000 complete in 400.1 sec
[-----------------45%                  ] 910 of 2000 complete in 400.9 sec
[-----------------45%                  ] 912 of 2000 complete in 401.8 sec
[-----------------45%                  ] 914 of 2000 complete in 402.7 sec
[-----------------45%                  ] 916 of 2000 complete in 403.5 sec
[-----------------45%                  ] 918 of 2000 complete in 404.4 sec
[-----------------46%                  ] 920 of 2000 complete in 405.2 sec
[-----------------46%                  ] 922 of 2000 complete in 406.0 sec
[-----------------46%                  ] 924 of 2000 complete in 406.9 sec
[-----------------46%                  ] 926 of 2000 complete in 407.7 sec
[-----------------46%                  ] 928 of 2000 complete in 408.5 sec
[-----------------46%                  ] 930 of 2000 complete in 409.4 sec
[-----------------46%                  ] 932 of 2000 complete in 410.2 sec
[-----------------46%                  ] 934 of 2000 complete in 411.1 sec
[-----------------46%                  ] 936 of 2000 complete in 412.0 sec
[-----------------46%                  ] 938 of 2000 complete in 412.9 sec
[-----------------47%                  ] 940 of 2000 complete in 413.7 sec
[-----------------47%                  ] 942 of 2000 complete in 414.6 sec
[-----------------47%                  ] 944 of 2000 complete in 415.4 sec
[-----------------47%                  ] 946 of 2000 complete in 416.3 sec
[-----------------47%                  ] 948 of 2000 complete in 417.1 sec
[-----------------47%                  ] 950 of 2000 complete in 418.0 sec
[-----------------47%                  ] 952 of 2000 complete in 418.8 sec
[-----------------47%                  ] 954 of 2000 complete in 419.7 sec
[-----------------47%                  ] 956 of 2000 complete in 420.5 sec
[-----------------47%                  ] 958 of 2000 complete in 421.4 sec
[-----------------48%                  ] 960 of 2000 complete in 422.2 sec
[-----------------48%                  ] 962 of 2000 complete in 423.1 sec
[-----------------48%                  ] 964 of 2000 complete in 423.9 sec
[-----------------48%                  ] 966 of 2000 complete in 424.8 sec
[-----------------48%                  ] 968 of 2000 complete in 425.6 sec
[-----------------48%                  ] 970 of 2000 complete in 426.4 sec
[-----------------48%                  ] 972 of 2000 complete in 427.3 sec
[-----------------48%                  ] 974 of 2000 complete in 428.1 sec
[-----------------48%                  ] 976 of 2000 complete in 428.9 sec
[-----------------48%                  ] 978 of 2000 complete in 429.7 sec
[-----------------49%                  ] 980 of 2000 complete in 430.5 sec
[-----------------49%                  ] 982 of 2000 complete in 431.4 sec
[-----------------49%                  ] 984 of 2000 complete in 432.2 sec
[-----------------49%                  ] 986 of 2000 complete in 433.0 sec
[-----------------49%                  ] 988 of 2000 complete in 433.9 sec
[-----------------49%                  ] 990 of 2000 complete in 434.7 sec
[-----------------49%                  ] 992 of 2000 complete in 435.5 sec
[-----------------49%                  ] 994 of 2000 complete in 436.4 sec
[-----------------49%                  ] 996 of 2000 complete in 437.2 sec
[-----------------49%                  ] 998 of 2000 complete in 438.1 sec
[-----------------50%                  ] 1000 of 2000 complete in 438.9 sec
[-----------------50%                  ] 1002 of 2000 complete in 439.7 sec
[-----------------50%                  ] 1004 of 2000 complete in 440.5 sec
[-----------------50%                  ] 1006 of 2000 complete in 441.4 sec
[-----------------50%                  ] 1008 of 2000 complete in 442.2 sec
[-----------------50%                  ] 1010 of 2000 complete in 443.1 sec
[-----------------50%                  ] 1012 of 2000 complete in 443.9 sec
[-----------------50%                  ] 1014 of 2000 complete in 444.8 sec
[-----------------50%                  ] 1016 of 2000 complete in 445.6 sec
[-----------------50%                  ] 1018 of 2000 complete in 446.5 sec
[-----------------51%                  ] 1020 of 2000 complete in 447.3 sec
[-----------------51%                  ] 1022 of 2000 complete in 448.2 sec
[-----------------51%                  ] 1024 of 2000 complete in 449.1 sec
[-----------------51%                  ] 1026 of 2000 complete in 449.9 sec
[-----------------51%                  ] 1028 of 2000 complete in 450.8 sec
[-----------------51%                  ] 1030 of 2000 complete in 451.6 sec
[-----------------51%                  ] 1032 of 2000 complete in 452.4 sec
[-----------------51%                  ] 1034 of 2000 complete in 453.3 sec
[-----------------51%                  ] 1036 of 2000 complete in 454.1 sec
[-----------------51%                  ] 1038 of 2000 complete in 455.0 sec
[-----------------52%                  ] 1040 of 2000 complete in 455.8 sec
[-----------------52%                  ] 1042 of 2000 complete in 456.7 sec
[-----------------52%                  ] 1044 of 2000 complete in 457.5 sec
[-----------------52%                  ] 1046 of 2000 complete in 458.4 sec
[-----------------52%                  ] 1048 of 2000 complete in 459.3 sec
[-----------------52%                  ] 1050 of 2000 complete in 460.1 sec
[---------------- 42%                  ] 844 of 2000 complete in 370.3 sec
[---------------- 42%                  ] 846 of 2000 complete in 371.2 sec
[---------------- 42%                  ] 848 of 2000 complete in 372.0 sec
[---------------- 42%                  ] 850 of 2000 complete in 372.9 sec
[---------------- 42%                  ] 852 of 2000 complete in 373.7 sec
[---------------- 42%                  ] 854 of 2000 complete in 374.6 sec
[---------------- 42%                  ] 856 of 2000 complete in 375.4 sec
[---------------- 42%                  ] 858 of 2000 complete in 376.3 sec
[---------------- 43%                  ] 860 of 2000 complete in 377.2 sec
[---------------- 43%                  ] 862 of 2000 complete in 378.0 sec
[---------------- 43%                  ] 864 of 2000 complete in 378.9 sec
[---------------- 43%                  ] 866 of 2000 complete in 379.7 sec
[---------------- 43%                  ] 868 of 2000 complete in 380.6 sec
[---------------- 43%                  ] 870 of 2000 complete in 381.4 sec
[---------------- 43%                  ] 872 of 2000 complete in 382.3 sec
[---------------- 43%                  ] 874 of 2000 complete in 383.2 sec
[---------------- 43%                  ] 876 of 2000 complete in 384.1 sec
[---------------- 43%                  ] 878 of 2000 complete in 384.9 sec
[---------------- 44%                  ] 880 of 2000 complete in 385.8 sec
[---------------- 44%                  ] 882 of 2000 complete in 386.7 sec
[---------------- 44%                  ] 884 of 2000 complete in 387.6 sec
[---------------- 44%                  ] 886 of 2000 complete in 388.5 sec
[---------------- 44%                  ] 888 of 2000 complete in 389.4 sec
[---------------- 44%                  ] 890 of 2000 complete in 390.3 sec
[---------------- 44%                  ] 892 of 2000 complete in 391.2 sec
[---------------- 44%                  ] 894 of 2000 complete in 392.0 sec
[-----------------44%                  ] 896 of 2000 complete in 392.9 sec
[-----------------44%                  ] 898 of 2000 complete in 393.7 sec
[-----------------45%                  ] 900 of 2000 complete in 394.5 sec
[-----------------45%                  ] 902 of 2000 complete in 395.4 sec
[-----------------45%                  ] 904 of 2000 complete in 396.3 sec
[-----------------45%                  ] 906 of 2000 complete in 397.1 sec
[-----------------45%                  ] 908 of 2000 complete in 398.0 sec
[-----------------45%                  ] 910 of 2000 complete in 398.9 sec
[-----------------45%                  ] 912 of 2000 complete in 399.7 sec
[-----------------45%                  ] 914 of 2000 complete in 400.6 sec
[-----------------45%                  ] 916 of 2000 complete in 401.4 sec
[-----------------45%                  ] 918 of 2000 complete in 402.3 sec
[-----------------46%                  ] 920 of 2000 complete in 403.2 sec
[-----------------46%                  ] 922 of 2000 complete in 404.0 sec
[-----------------46%                  ] 924 of 2000 complete in 404.9 sec
[-----------------46%                  ] 926 of 2000 complete in 405.7 sec
[-----------------46%                  ] 928 of 2000 complete in 406.6 sec
[-----------------46%                  ] 930 of 2000 complete in 407.4 sec
[-----------------46%                  ] 932 of 2000 complete in 408.3 sec
[-----------------46%                  ] 934 of 2000 complete in 409.2 sec
[-----------------46%                  ] 936 of 2000 complete in 410.0 sec
[-----------------46%                  ] 938 of 2000 complete in 410.9 sec
[-----------------47%                  ] 940 of 2000 complete in 411.7 sec
[-----------------47%                  ] 942 of 2000 complete in 412.6 sec
[-----------------47%                  ] 944 of 2000 complete in 413.4 sec
[-----------------47%                  ] 946 of 2000 complete in 414.3 sec
[-----------------47%                  ] 948 of 2000 complete in 415.1 sec
[-----------------47%                  ] 950 of 2000 complete in 416.0 sec
[-----------------47%                  ] 952 of 2000 complete in 416.8 sec
[-----------------47%                  ] 954 of 2000 complete in 417.7 sec
[-----------------47%                  ] 956 of 2000 complete in 418.6 sec
[-----------------47%                  ] 958 of 2000 complete in 419.5 sec
[-----------------48%                  ] 960 of 2000 complete in 420.3 sec
[-----------------48%                  ] 962 of 2000 complete in 421.2 sec
[-----------------48%                  ] 964 of 2000 complete in 422.1 sec
[-----------------48%                  ] 966 of 2000 complete in 422.9 sec
[-----------------48%                  ] 968 of 2000 complete in 423.7 sec
[-----------------48%                  ] 970 of 2000 complete in 424.6 sec
[-----------------48%                  ] 972 of 2000 complete in 425.5 sec
[-----------------48%                  ] 974 of 2000 complete in 426.3 sec
[-----------------48%                  ] 976 of 2000 complete in 427.1 sec
[-----------------48%                  ] 978 of 2000 complete in 427.9 sec
[-----------------49%                  ] 980 of 2000 complete in 428.8 sec
[-----------------49%                  ] 982 of 2000 complete in 429.6 sec
[-----------------49%                  ] 984 of 2000 complete in 430.4 sec
[-----------------49%                  ] 986 of 2000 complete in 431.3 sec
[-----------------49%                  ] 988 of 2000 complete in 432.1 sec
[-----------------49%                  ] 990 of 2000 complete in 432.9 sec
[-----------------49%                  ] 992 of 2000 complete in 433.8 sec
[-----------------49%                  ] 994 of 2000 complete in 434.6 sec
[-----------------49%                  ] 996 of 2000 complete in 435.4 sec
[-----------------49%                  ] 998 of 2000 complete in 436.3 sec
[-----------------50%                  ] 1000 of 2000 complete in 437.1 sec
[-----------------50%                  ] 1002 of 2000 complete in 437.9 sec
[-----------------50%                  ] 1004 of 2000 complete in 438.8 sec
[-----------------50%                  ] 1006 of 2000 complete in 439.6 sec
[-----------------50%                  ] 1008 of 2000 complete in 440.5 sec
[-----------------50%                  ] 1010 of 2000 complete in 441.3 sec
[-----------------50%                  ] 1012 of 2000 complete in 442.1 sec
[-----------------50%                  ] 1014 of 2000 complete in 442.9 sec
[-----------------50%                  ] 1016 of 2000 complete in 443.8 sec
[-----------------50%                  ] 1018 of 2000 complete in 444.6 sec
[-----------------51%                  ] 1020 of 2000 complete in 445.5 sec
[-----------------51%                  ] 1022 of 2000 complete in 446.3 sec
[-----------------51%                  ] 1024 of 2000 complete in 447.2 sec
[-----------------51%                  ] 1026 of 2000 complete in 448.0 sec
[-----------------51%                  ] 1028 of 2000 complete in 448.8 sec
[-----------------51%                  ] 1030 of 2000 complete in 449.7 sec
[-----------------51%                  ] 1032 of 2000 complete in 450.5 sec
[-----------------51%                  ] 1034 of 2000 complete in 451.4 sec
[-----------------51%                  ] 1036 of 2000 complete in 452.2 sec
[-----------------51%                  ] 1038 of 2000 complete in 453.1 sec
[-----------------52%                  ] 1040 of 2000 complete in 453.9 sec
[-----------------52%                  ] 1042 of 2000 complete in 454.8 sec
[-----------------52%                  ] 1044 of 2000 complete in 455.6 sec
[-----------------52%                  ] 1046 of 2000 complete in 456.5 sec
[-----------------52%                  ] 1048 of 2000 complete in 457.3 sec
[-----------------52%                  ] 1050 of 2000 complete in 458.1 sec
[-----------------52%                  ] 1052 of 2000 complete in 459.0 sec
[-----------------52%                  ] 1054 of 2000 complete in 459.8 sec
[-----------------52%                  ] 1056 of 2000 complete in 460.7 sec
[-----------------52%                  ] 1058 of 2000 complete in 461.5 sec

[---------------  41%                  ] 834 of 2000 complete in 374.2 sec
[---------------  41%                  ] 836 of 2000 complete in 375.1 sec
[---------------  41%                  ] 838 of 2000 complete in 376.0 sec
[---------------  42%                  ] 840 of 2000 complete in 376.9 sec
[---------------  42%                  ] 842 of 2000 complete in 377.7 sec
[---------------- 42%                  ] 844 of 2000 complete in 378.6 sec
[---------------- 42%                  ] 846 of 2000 complete in 379.5 sec
[---------------- 42%                  ] 848 of 2000 complete in 380.4 sec
[---------------- 42%                  ] 850 of 2000 complete in 381.3 sec
[---------------- 42%                  ] 852 of 2000 complete in 382.1 sec
[---------------- 42%                  ] 854 of 2000 complete in 383.0 sec
[---------------- 42%                  ] 856 of 2000 complete in 383.9 sec
[---------------- 42%                  ] 858 of 2000 complete in 384.8 sec
[---------------- 43%                  ] 860 of 2000 complete in 385.6 sec
[---------------- 43%                  ] 862 of 2000 complete in 386.5 sec
[---------------- 43%                  ] 864 of 2000 complete in 387.5 sec
[---------------- 43%                  ] 866 of 2000 complete in 388.4 sec
[---------------- 43%                  ] 868 of 2000 complete in 389.2 sec
[---------------- 43%                  ] 870 of 2000 complete in 390.1 sec
[---------------- 43%                  ] 872 of 2000 complete in 391.0 sec
[---------------- 43%                  ] 874 of 2000 complete in 391.8 sec
[---------------- 43%                  ] 876 of 2000 complete in 392.7 sec
[---------------- 43%                  ] 878 of 2000 complete in 393.6 sec
[---------------- 44%                  ] 880 of 2000 complete in 394.5 sec
[---------------- 44%                  ] 882 of 2000 complete in 395.3 sec
[---------------- 44%                  ] 884 of 2000 complete in 396.2 sec
[---------------- 44%                  ] 886 of 2000 complete in 397.1 sec
[---------------- 44%                  ] 888 of 2000 complete in 397.9 sec
[---------------- 44%                  ] 890 of 2000 complete in 398.8 sec
[---------------- 44%                  ] 892 of 2000 complete in 399.6 sec
[---------------- 44%                  ] 894 of 2000 complete in 400.5 sec
[-----------------44%                  ] 896 of 2000 complete in 401.4 sec
[-----------------44%                  ] 898 of 2000 complete in 402.3 sec
[-----------------45%                  ] 900 of 2000 complete in 403.2 sec
[-----------------45%                  ] 902 of 2000 complete in 404.0 sec
[-----------------45%                  ] 904 of 2000 complete in 404.9 sec
[-----------------45%                  ] 906 of 2000 complete in 405.8 sec
[-----------------45%                  ] 908 of 2000 complete in 406.6 sec
[-----------------45%                  ] 910 of 2000 complete in 407.4 sec
[-----------------45%                  ] 912 of 2000 complete in 408.3 sec
[-----------------45%                  ] 914 of 2000 complete in 409.2 sec
[-----------------45%                  ] 916 of 2000 complete in 410.1 sec
[-----------------45%                  ] 918 of 2000 complete in 410.9 sec
[-----------------46%                  ] 920 of 2000 complete in 411.8 sec
[-----------------46%                  ] 922 of 2000 complete in 412.7 sec
[-----------------46%                  ] 924 of 2000 complete in 413.6 sec
[-----------------46%                  ] 926 of 2000 complete in 414.4 sec
[-----------------46%                  ] 928 of 2000 complete in 415.3 sec
[-----------------46%                  ] 930 of 2000 complete in 416.2 sec
[-----------------46%                  ] 932 of 2000 complete in 417.0 sec
[-----------------46%                  ] 934 of 2000 complete in 417.9 sec
[-----------------46%                  ] 936 of 2000 complete in 418.7 sec
[-----------------46%                  ] 938 of 2000 complete in 419.6 sec
[-----------------47%                  ] 940 of 2000 complete in 420.4 sec
[-----------------47%                  ] 942 of 2000 complete in 421.3 sec
[-----------------47%                  ] 944 of 2000 complete in 422.1 sec
[-----------------47%                  ] 946 of 2000 complete in 423.0 sec
[-----------------47%                  ] 948 of 2000 complete in 423.8 sec
[-----------------47%                  ] 950 of 2000 complete in 424.7 sec
[-----------------47%                  ] 952 of 2000 complete in 425.5 sec
[-----------------47%                  ] 954 of 2000 complete in 426.4 sec
[-----------------47%                  ] 956 of 2000 complete in 427.3 sec
[-----------------47%                  ] 958 of 2000 complete in 428.1 sec
[-----------------48%                  ] 960 of 2000 complete in 429.0 sec
[-----------------48%                  ] 962 of 2000 complete in 429.8 sec
[-----------------48%                  ] 964 of 2000 complete in 430.7 sec
[-----------------48%                  ] 966 of 2000 complete in 431.5 sec
[-----------------48%                  ] 968 of 2000 complete in 432.3 sec
[-----------------48%                  ] 970 of 2000 complete in 433.2 sec
[-----------------48%                  ] 972 of 2000 complete in 434.0 sec
[-----------------48%                  ] 974 of 2000 complete in 434.9 sec
[-----------------48%                  ] 976 of 2000 complete in 435.7 sec
[-----------------48%                  ] 978 of 2000 complete in 436.6 sec
[-----------------49%                  ] 980 of 2000 complete in 437.5 sec
[-----------------49%                  ] 982 of 2000 complete in 438.3 sec
[-----------------49%                  ] 984 of 2000 complete in 439.2 sec
[-----------------49%                  ] 986 of 2000 complete in 440.1 sec
[-----------------49%                  ] 988 of 2000 complete in 440.9 sec
[-----------------49%                  ] 990 of 2000 complete in 441.8 sec
[-----------------49%                  ] 992 of 2000 complete in 442.7 sec
[-----------------49%                  ] 994 of 2000 complete in 443.5 sec
[-----------------49%                  ] 996 of 2000 complete in 444.4 sec
[-----------------49%                  ] 998 of 2000 complete in 445.3 sec
[-----------------50%                  ] 1000 of 2000 complete in 446.1 sec
[-----------------50%                  ] 1002 of 2000 complete in 447.0 sec
[-----------------50%                  ] 1004 of 2000 complete in 447.8 sec
[-----------------50%                  ] 1006 of 2000 complete in 448.7 sec
[-----------------50%                  ] 1008 of 2000 complete in 449.6 sec
[-----------------50%                  ] 1010 of 2000 complete in 450.4 sec
[-----------------50%                  ] 1012 of 2000 complete in 451.3 sec
[-----------------50%                  ] 1014 of 2000 complete in 452.1 sec
[-----------------50%                  ] 1016 of 2000 complete in 453.0 sec
[-----------------50%                  ] 1018 of 2000 complete in 453.9 sec
[-----------------51%                  ] 1020 of 2000 complete in 454.7 sec
[-----------------51%                  ] 1022 of 2000 complete in 455.6 sec
[-----------------51%                  ] 1024 of 2000 complete in 456.4 sec
[-----------------51%                  ] 1026 of 2000 complete in 457.3 sec
[-----------------51%                  ] 1028 of 2000 complete in 458.2 sec
[-----------------51%                  ] 1030 of 2000 complete in 459.0 sec
[-----------------51%                  ] 1032 of 2000 complete in 459.9 sec
[-----------------51%                  ] 1034 of 2000 complete in 460.7 sec
[-----------------51%                  ] 1036 of 2000 complete in 461.6 sec
[-----------------51%                  ] 1038 of 2000 complete in 462.5 sec
[-----------------52%                  ] 1040 of 2000 complete in 463.4 sec
[-----------------52%                  ] 1042 of 2000 complete in 464.2 sec
[-----------------52%                  ] 1044 of 2000 complete in 465.1 sec
[-----------------52%                  ] 1046 of 2000 complete in 466.0 sec
[-----------------52%                  ] 1048 of 2000 complete in 466.9 sec
[---------------  41%                  ] 832 of 2000 complete in 375.1 sec
[---------------  41%                  ] 834 of 2000 complete in 376.0 sec
[---------------  41%                  ] 836 of 2000 complete in 376.9 sec
[---------------  41%                  ] 838 of 2000 complete in 377.8 sec
[---------------  42%                  ] 840 of 2000 complete in 378.7 sec
[---------------  42%                  ] 842 of 2000 complete in 379.5 sec
[---------------- 42%                  ] 844 of 2000 complete in 380.4 sec
[---------------- 42%                  ] 846 of 2000 complete in 381.3 sec
[---------------- 42%                  ] 848 of 2000 complete in 382.2 sec
[---------------- 42%                  ] 850 of 2000 complete in 383.1 sec
[---------------- 42%                  ] 852 of 2000 complete in 384.0 sec
[---------------- 42%                  ] 854 of 2000 complete in 384.9 sec
[---------------- 42%                  ] 856 of 2000 complete in 385.8 sec
[---------------- 42%                  ] 858 of 2000 complete in 386.7 sec
[---------------- 43%                  ] 860 of 2000 complete in 387.6 sec
[---------------- 43%                  ] 862 of 2000 complete in 388.5 sec
[---------------- 43%                  ] 864 of 2000 complete in 389.5 sec
[---------------- 43%                  ] 866 of 2000 complete in 390.4 sec
[---------------- 43%                  ] 868 of 2000 complete in 391.3 sec
[---------------- 43%                  ] 870 of 2000 complete in 392.1 sec
[---------------- 43%                  ] 872 of 2000 complete in 393.0 sec
[---------------- 43%                  ] 874 of 2000 complete in 393.9 sec
[---------------- 43%                  ] 876 of 2000 complete in 394.8 sec
[---------------- 43%                  ] 878 of 2000 complete in 395.7 sec
[---------------- 44%                  ] 880 of 2000 complete in 396.5 sec
[---------------- 44%                  ] 882 of 2000 complete in 397.4 sec
[---------------- 44%                  ] 884 of 2000 complete in 398.2 sec
[---------------- 44%                  ] 886 of 2000 complete in 399.1 sec
[---------------- 44%                  ] 888 of 2000 complete in 400.0 sec
[---------------- 44%                  ] 890 of 2000 complete in 400.8 sec
[---------------- 44%                  ] 892 of 2000 complete in 401.7 sec
[---------------- 44%                  ] 894 of 2000 complete in 402.6 sec
[-----------------44%                  ] 896 of 2000 complete in 403.5 sec
[-----------------44%                  ] 898 of 2000 complete in 404.3 sec
[-----------------45%                  ] 900 of 2000 complete in 405.2 sec
[-----------------45%                  ] 902 of 2000 complete in 406.1 sec
[-----------------45%                  ] 904 of 2000 complete in 406.9 sec
[-----------------45%                  ] 906 of 2000 complete in 407.8 sec
[-----------------45%                  ] 908 of 2000 complete in 408.7 sec
[-----------------45%                  ] 910 of 2000 complete in 409.6 sec
[-----------------45%                  ] 912 of 2000 complete in 410.5 sec
[-----------------45%                  ] 914 of 2000 complete in 411.3 sec
[-----------------45%                  ] 916 of 2000 complete in 412.2 sec
[-----------------45%                  ] 918 of 2000 complete in 413.1 sec
[-----------------46%                  ] 920 of 2000 complete in 414.0 sec
[-----------------46%                  ] 922 of 2000 complete in 414.8 sec
[-----------------46%                  ] 924 of 2000 complete in 415.7 sec
[-----------------46%                  ] 926 of 2000 complete in 416.6 sec
[-----------------46%                  ] 928 of 2000 complete in 417.5 sec
[-----------------46%                  ] 930 of 2000 complete in 418.3 sec
[-----------------46%                  ] 932 of 2000 complete in 419.2 sec
[-----------------46%                  ] 934 of 2000 complete in 420.1 sec
[-----------------46%                  ] 936 of 2000 complete in 421.0 sec
[-----------------46%                  ] 938 of 2000 complete in 421.8 sec
[-----------------47%                  ] 940 of 2000 complete in 422.7 sec
[-----------------47%                  ] 942 of 2000 complete in 423.6 sec
[-----------------47%                  ] 944 of 2000 complete in 424.4 sec
[-----------------47%                  ] 946 of 2000 complete in 425.3 sec
[-----------------47%                  ] 948 of 2000 complete in 426.1 sec
[-----------------47%                  ] 950 of 2000 complete in 427.0 sec
[-----------------47%                  ] 952 of 2000 complete in 427.9 sec
[-----------------47%                  ] 954 of 2000 complete in 428.7 sec
[-----------------47%                  ] 956 of 2000 complete in 429.6 sec
[-----------------47%                  ] 958 of 2000 complete in 430.5 sec
[-----------------48%                  ] 960 of 2000 complete in 431.3 sec
[-----------------48%                  ] 962 of 2000 complete in 432.1 sec
[-----------------48%                  ] 964 of 2000 complete in 433.0 sec
[-----------------48%                  ] 966 of 2000 complete in 433.8 sec
[-----------------48%                  ] 968 of 2000 complete in 434.7 sec
[-----------------48%                  ] 970 of 2000 complete in 435.6 sec
[-----------------48%                  ] 972 of 2000 complete in 436.5 sec
[-----------------48%                  ] 974 of 2000 complete in 437.3 sec
[-----------------48%                  ] 976 of 2000 complete in 438.1 sec
[-----------------48%                  ] 978 of 2000 complete in 439.0 sec
[-----------------49%                  ] 980 of 2000 complete in 439.9 sec
[-----------------49%                  ] 982 of 2000 complete in 440.8 sec
[-----------------49%                  ] 984 of 2000 complete in 441.6 sec
[-----------------49%                  ] 986 of 2000 complete in 442.5 sec
[-----------------49%                  ] 988 of 2000 complete in 443.3 sec
[-----------------49%                  ] 990 of 2000 complete in 444.2 sec
[-----------------49%                  ] 992 of 2000 complete in 445.1 sec
[-----------------49%                  ] 994 of 2000 complete in 445.9 sec
[-----------------49%                  ] 996 of 2000 complete in 446.8 sec
[-----------------49%                  ] 998 of 2000 complete in 447.6 sec
[-----------------50%                  ] 1000 of 2000 complete in 448.5 sec
[-----------------50%                  ] 1002 of 2000 complete in 449.4 sec
[-----------------50%                  ] 1004 of 2000 complete in 450.3 sec
[-----------------50%                  ] 1006 of 2000 complete in 451.1 sec
[-----------------50%                  ] 1008 of 2000 complete in 452.0 sec
[-----------------50%                  ] 1010 of 2000 complete in 452.9 sec
[-----------------50%                  ] 1012 of 2000 complete in 453.8 sec
[-----------------50%                  ] 1014 of 2000 complete in 454.6 sec
[-----------------50%                  ] 1016 of 2000 complete in 455.5 sec
[-----------------50%                  ] 1018 of 2000 complete in 456.4 sec
[-----------------51%                  ] 1020 of 2000 complete in 457.3 sec
[-----------------51%                  ] 1022 of 2000 complete in 458.1 sec
[-----------------51%                  ] 1024 of 2000 complete in 459.1 sec
[-----------------51%                  ] 1026 of 2000 complete in 459.9 sec
[-----------------51%                  ] 1028 of 2000 complete in 460.8 sec
[-----------------51%                  ] 1030 of 2000 complete in 461.6 sec
[-----------------51%                  ] 1032 of 2000 complete in 462.5 sec
[-----------------51%                  ] 1034 of 2000 complete in 463.4 sec
[-----------------51%                  ] 1036 of 2000 complete in 464.3 sec
[-----------------51%                  ] 1038 of 2000 complete in 465.1 sec
[-----------------52%                  ] 1040 of 2000 complete in 466.0 sec
[-----------------52%                  ] 1042 of 2000 complete in 466.9 sec
[-----------------52%                  ] 1044 of 2000 complete in 467.7 sec
[-----------------52%                  ] 1046 of 2000 complete in 468.6 sec

[-----------------52%                  ] 1052 of 2000 complete in 461.0 sec
[-----------------52%                  ] 1054 of 2000 complete in 461.8 sec
[-----------------52%                  ] 1056 of 2000 complete in 462.7 sec
[-----------------52%                  ] 1058 of 2000 complete in 463.6 sec
[-----------------53%                  ] 1060 of 2000 complete in 464.5 sec
[-----------------53%                  ] 1062 of 2000 complete in 465.3 sec
[-----------------53%                  ] 1064 of 2000 complete in 466.1 sec
[-----------------53%                  ] 1066 of 2000 complete in 467.0 sec
[-----------------53%                  ] 1068 of 2000 complete in 467.9 sec
[-----------------53%                  ] 1070 of 2000 complete in 468.7 sec
[-----------------53%                  ] 1072 of 2000 complete in 469.6 sec
[-----------------53%                  ] 1074 of 2000 complete in 470.4 sec
[-----------------53%                  ] 1076 of 2000 complete in 471.2 sec
[-----------------53%                  ] 1078 of 2000 complete in 472.1 sec
[-----------------54%                  ] 1080 of 2000 complete in 472.9 sec
[-----------------54%                  ] 1082 of 2000 complete in 473.8 sec
[-----------------54%                  ] 1084 of 2000 complete in 474.6 sec
[-----------------54%                  ] 1086 of 2000 complete in 475.5 sec
[-----------------54%                  ] 1088 of 2000 complete in 476.4 sec
[-----------------54%                  ] 1090 of 2000 complete in 477.2 sec
[-----------------54%                  ] 1092 of 2000 complete in 478.1 sec
[-----------------54%                  ] 1094 of 2000 complete in 478.9 sec
[-----------------54%                  ] 1096 of 2000 complete in 479.8 sec
[-----------------54%                  ] 1098 of 2000 complete in 480.6 sec
[-----------------55%                  ] 1100 of 2000 complete in 481.5 sec
[-----------------55%                  ] 1102 of 2000 complete in 482.3 sec
[-----------------55%                  ] 1104 of 2000 complete in 483.2 sec
[-----------------55%-                 ] 1106 of 2000 complete in 484.0 sec
[-----------------55%-                 ] 1108 of 2000 complete in 484.9 sec
[-----------------55%-                 ] 1110 of 2000 complete in 485.8 sec
[-----------------55%-                 ] 1112 of 2000 complete in 486.7 sec
[-----------------55%-                 ] 1114 of 2000 complete in 487.6 sec
[-----------------55%-                 ] 1116 of 2000 complete in 488.4 sec
[-----------------55%-                 ] 1118 of 2000 complete in 489.2 sec
[-----------------56%-                 ] 1120 of 2000 complete in 490.0 sec
[-----------------56%-                 ] 1122 of 2000 complete in 490.9 sec
[-----------------56%-                 ] 1124 of 2000 complete in 491.8 sec
[-----------------56%-                 ] 1126 of 2000 complete in 492.6 sec
[-----------------56%-                 ] 1128 of 2000 complete in 493.5 sec
[-----------------56%-                 ] 1130 of 2000 complete in 494.3 sec
[-----------------56%-                 ] 1132 of 2000 complete in 495.2 sec
[-----------------56%-                 ] 1134 of 2000 complete in 496.0 sec
[-----------------56%-                 ] 1136 of 2000 complete in 496.9 sec
[-----------------56%-                 ] 1138 of 2000 complete in 497.7 sec
[-----------------57%-                 ] 1140 of 2000 complete in 498.5 sec
[-----------------57%-                 ] 1142 of 2000 complete in 499.4 sec
[-----------------57%-                 ] 1144 of 2000 complete in 500.2 sec
[-----------------57%-                 ] 1146 of 2000 complete in 501.1 sec
[-----------------57%-                 ] 1148 of 2000 complete in 501.9 sec
[-----------------57%-                 ] 1150 of 2000 complete in 502.7 sec
[-----------------57%-                 ] 1152 of 2000 complete in 503.6 sec
[-----------------57%-                 ] 1154 of 2000 complete in 504.4 sec
[-----------------57%-                 ] 1156 of 2000 complete in 505.2 sec
[-----------------57%--                ] 1158 of 2000 complete in 506.1 sec
[-----------------58%--                ] 1160 of 2000 complete in 506.9 sec
[-----------------58%--                ] 1162 of 2000 complete in 507.8 sec
[-----------------58%--                ] 1164 of 2000 complete in 508.6 sec
[-----------------58%--                ] 1166 of 2000 complete in 509.5 sec
[-----------------58%--                ] 1168 of 2000 complete in 510.3 sec
[-----------------58%--                ] 1170 of 2000 complete in 511.2 sec
[-----------------58%--                ] 1172 of 2000 complete in 512.0 sec
[-----------------58%--                ] 1174 of 2000 complete in 512.8 sec
[-----------------58%--                ] 1176 of 2000 complete in 513.7 sec
[-----------------58%--                ] 1178 of 2000 complete in 514.5 sec
[-----------------59%--                ] 1180 of 2000 complete in 515.4 sec
[-----------------59%--                ] 1182 of 2000 complete in 516.2 sec
[-----------------59%--                ] 1184 of 2000 complete in 517.1 sec
[-----------------59%--                ] 1186 of 2000 complete in 517.9 sec
[-----------------59%--                ] 1188 of 2000 complete in 518.8 sec
[-----------------59%--                ] 1190 of 2000 complete in 519.6 sec
[-----------------59%--                ] 1192 of 2000 complete in 520.5 sec
[-----------------59%--                ] 1194 of 2000 complete in 521.3 sec
[-----------------59%--                ] 1196 of 2000 complete in 522.2 sec
[-----------------59%--                ] 1198 of 2000 complete in 523.0 sec
[-----------------60%--                ] 1200 of 2000 complete in 523.9 sec
[-----------------60%--                ] 1202 of 2000 complete in 524.7 sec
[-----------------60%--                ] 1204 of 2000 complete in 525.6 sec
[-----------------60%--                ] 1206 of 2000 complete in 526.4 sec
[-----------------60%--                ] 1208 of 2000 complete in 527.3 sec
[-----------------60%--                ] 1210 of 2000 complete in 528.1 sec
[-----------------60%---               ] 1212 of 2000 complete in 529.0 sec
[-----------------60%---               ] 1214 of 2000 complete in 529.8 sec
[-----------------60%---               ] 1216 of 2000 complete in 530.7 sec
[-----------------60%---               ] 1218 of 2000 complete in 531.5 sec
[-----------------61%---               ] 1220 of 2000 complete in 532.3 sec
[-----------------61%---               ] 1222 of 2000 complete in 533.2 sec
[-----------------61%---               ] 1224 of 2000 complete in 534.0 sec
[-----------------61%---               ] 1226 of 2000 complete in 534.9 sec
[-----------------61%---               ] 1228 of 2000 complete in 535.7 sec
[-----------------61%---               ] 1230 of 2000 complete in 536.6 sec
[-----------------61%---               ] 1232 of 2000 complete in 537.5 sec
[-----------------61%---               ] 1234 of 2000 complete in 538.4 sec
[-----------------61%---               ] 1236 of 2000 complete in 539.2 sec
[-----------------61%---               ] 1238 of 2000 complete in 540.0 sec
[-----------------62%---               ] 1240 of 2000 complete in 540.9 sec
[-----------------62%---               ] 1242 of 2000 complete in 541.8 sec
[-----------------62%---               ] 1244 of 2000 complete in 542.7 sec
[-----------------62%---               ] 1246 of 2000 complete in 543.5 sec
[-----------------62%---               ] 1248 of 2000 complete in 544.3 sec
[-----------------62%---               ] 1250 of 2000 complete in 545.2 sec
[-----------------62%---               ] 1252 of 2000 complete in 546.0 sec
[-----------------62%---               ] 1254 of 2000 complete in 546.9 sec
[-----------------62%---               ] 1256 of 2000 complete in 547.7 sec
[-----------------62%---               ] 1258 of 2000 complete in 548.6 sec
[-----------------63%---               ] 1260 of 2000 complete in 549.5 sec
[-----------------63%---               ] 1262 of 2000 complete in 550.3 sec
[-----------------63%----              ] 1264 of 2000 complete in 551.2 sec
[-----------------53%                  ] 1060 of 2000 complete in 462.4 sec
[-----------------53%                  ] 1062 of 2000 complete in 463.2 sec
[-----------------53%                  ] 1064 of 2000 complete in 464.1 sec
[-----------------53%                  ] 1066 of 2000 complete in 465.0 sec
[-----------------53%                  ] 1068 of 2000 complete in 465.8 sec
[-----------------53%                  ] 1070 of 2000 complete in 466.6 sec
[-----------------53%                  ] 1072 of 2000 complete in 467.5 sec
[-----------------53%                  ] 1074 of 2000 complete in 468.3 sec
[-----------------53%                  ] 1076 of 2000 complete in 469.1 sec
[-----------------53%                  ] 1078 of 2000 complete in 470.0 sec
[-----------------54%                  ] 1080 of 2000 complete in 470.8 sec
[-----------------54%                  ] 1082 of 2000 complete in 471.6 sec
[-----------------54%                  ] 1084 of 2000 complete in 472.5 sec
[-----------------54%                  ] 1086 of 2000 complete in 473.3 sec
[-----------------54%                  ] 1088 of 2000 complete in 474.1 sec
[-----------------54%                  ] 1090 of 2000 complete in 475.0 sec
[-----------------54%                  ] 1092 of 2000 complete in 475.8 sec
[-----------------54%                  ] 1094 of 2000 complete in 476.7 sec
[-----------------54%                  ] 1096 of 2000 complete in 477.5 sec
[-----------------54%                  ] 1098 of 2000 complete in 478.4 sec
[-----------------55%                  ] 1100 of 2000 complete in 479.2 sec
[-----------------55%                  ] 1102 of 2000 complete in 480.0 sec
[-----------------55%                  ] 1104 of 2000 complete in 480.8 sec
[-----------------55%-                 ] 1106 of 2000 complete in 481.6 sec
[-----------------55%-                 ] 1108 of 2000 complete in 482.4 sec
[-----------------55%-                 ] 1110 of 2000 complete in 483.3 sec
[-----------------55%-                 ] 1112 of 2000 complete in 484.1 sec
[-----------------55%-                 ] 1114 of 2000 complete in 485.0 sec
[-----------------55%-                 ] 1116 of 2000 complete in 485.9 sec
[-----------------55%-                 ] 1118 of 2000 complete in 486.8 sec
[-----------------56%-                 ] 1120 of 2000 complete in 487.6 sec
[-----------------56%-                 ] 1122 of 2000 complete in 488.4 sec
[-----------------56%-                 ] 1124 of 2000 complete in 489.3 sec
[-----------------56%-                 ] 1126 of 2000 complete in 490.1 sec
[-----------------56%-                 ] 1128 of 2000 complete in 490.9 sec
[-----------------56%-                 ] 1130 of 2000 complete in 491.8 sec
[-----------------56%-                 ] 1132 of 2000 complete in 492.6 sec
[-----------------56%-                 ] 1134 of 2000 complete in 493.5 sec
[-----------------56%-                 ] 1136 of 2000 complete in 494.3 sec
[-----------------56%-                 ] 1138 of 2000 complete in 495.1 sec
[-----------------57%-                 ] 1140 of 2000 complete in 495.9 sec
[-----------------57%-                 ] 1142 of 2000 complete in 496.8 sec
[-----------------57%-                 ] 1144 of 2000 complete in 497.6 sec
[-----------------57%-                 ] 1146 of 2000 complete in 498.4 sec
[-----------------57%-                 ] 1148 of 2000 complete in 499.2 sec
[-----------------57%-                 ] 1150 of 2000 complete in 500.1 sec
[-----------------57%-                 ] 1152 of 2000 complete in 500.9 sec
[-----------------57%-                 ] 1154 of 2000 complete in 501.7 sec
[-----------------57%-                 ] 1156 of 2000 complete in 502.5 sec
[-----------------57%--                ] 1158 of 2000 complete in 503.4 sec
[-----------------58%--                ] 1160 of 2000 complete in 504.2 sec
[-----------------58%--                ] 1162 of 2000 complete in 505.1 sec
[-----------------58%--                ] 1164 of 2000 complete in 505.9 sec
[-----------------58%--                ] 1166 of 2000 complete in 506.7 sec
[-----------------58%--                ] 1168 of 2000 complete in 507.6 sec
[-----------------58%--                ] 1170 of 2000 complete in 508.4 sec
[-----------------58%--                ] 1172 of 2000 complete in 509.2 sec
[-----------------58%--                ] 1174 of 2000 complete in 510.0 sec
[-----------------58%--                ] 1176 of 2000 complete in 510.9 sec
[-----------------58%--                ] 1178 of 2000 complete in 511.7 sec
[-----------------59%--                ] 1180 of 2000 complete in 512.5 sec
[-----------------59%--                ] 1182 of 2000 complete in 513.4 sec
[-----------------59%--                ] 1184 of 2000 complete in 514.3 sec
[-----------------59%--                ] 1186 of 2000 complete in 515.1 sec
[-----------------59%--                ] 1188 of 2000 complete in 516.0 sec
[-----------------59%--                ] 1190 of 2000 complete in 516.8 sec
[-----------------59%--                ] 1192 of 2000 complete in 517.7 sec
[-----------------59%--                ] 1194 of 2000 complete in 518.5 sec
[-----------------59%--                ] 1196 of 2000 complete in 519.3 sec
[-----------------59%--                ] 1198 of 2000 complete in 520.2 sec
[-----------------60%--                ] 1200 of 2000 complete in 521.0 sec
[-----------------60%--                ] 1202 of 2000 complete in 521.9 sec
[-----------------60%--                ] 1204 of 2000 complete in 522.7 sec
[-----------------60%--                ] 1206 of 2000 complete in 523.5 sec
[-----------------60%--                ] 1208 of 2000 complete in 524.4 sec
[-----------------60%--                ] 1210 of 2000 complete in 525.2 sec
[-----------------60%---               ] 1212 of 2000 complete in 526.0 sec
[-----------------60%---               ] 1214 of 2000 complete in 526.9 sec
[-----------------60%---               ] 1216 of 2000 complete in 527.7 sec
[-----------------60%---               ] 1218 of 2000 complete in 528.6 sec
[-----------------61%---               ] 1220 of 2000 complete in 529.5 sec
[-----------------61%---               ] 1222 of 2000 complete in 530.3 sec
[-----------------61%---               ] 1224 of 2000 complete in 531.1 sec
[-----------------61%---               ] 1226 of 2000 complete in 532.0 sec
[-----------------61%---               ] 1228 of 2000 complete in 532.8 sec
[-----------------61%---               ] 1230 of 2000 complete in 533.6 sec
[-----------------61%---               ] 1232 of 2000 complete in 534.5 sec
[-----------------61%---               ] 1234 of 2000 complete in 535.3 sec
[-----------------61%---               ] 1236 of 2000 complete in 536.2 sec
[-----------------61%---               ] 1238 of 2000 complete in 537.0 sec
[-----------------62%---               ] 1240 of 2000 complete in 537.8 sec
[-----------------62%---               ] 1242 of 2000 complete in 538.6 sec
[-----------------62%---               ] 1244 of 2000 complete in 539.5 sec
[-----------------62%---               ] 1246 of 2000 complete in 540.4 sec
[-----------------62%---               ] 1248 of 2000 complete in 541.3 sec
[-----------------62%---               ] 1250 of 2000 complete in 542.2 sec
[-----------------62%---               ] 1252 of 2000 complete in 543.0 sec
[-----------------62%---               ] 1254 of 2000 complete in 543.8 sec
[-----------------62%---               ] 1256 of 2000 complete in 544.7 sec
[-----------------62%---               ] 1258 of 2000 complete in 545.5 sec
[-----------------63%---               ] 1260 of 2000 complete in 546.4 sec
[-----------------63%---               ] 1262 of 2000 complete in 547.2 sec
[-----------------63%----              ] 1264 of 2000 complete in 548.0 sec
[-----------------63%----              ] 1266 of 2000 complete in 548.9 sec
[-----------------63%----              ] 1268 of 2000 complete in 549.7 sec
[-----------------63%----              ] 1270 of 2000 complete in 550.5 sec
[-----------------63%----              ] 1272 of 2000 complete in 551.4 sec

[-----------------52%                  ] 1050 of 2000 complete in 467.7 sec
[-----------------52%                  ] 1052 of 2000 complete in 468.6 sec
[-----------------52%                  ] 1054 of 2000 complete in 469.4 sec
[-----------------52%                  ] 1056 of 2000 complete in 470.3 sec
[-----------------52%                  ] 1058 of 2000 complete in 471.1 sec
[-----------------53%                  ] 1060 of 2000 complete in 472.0 sec
[-----------------53%                  ] 1062 of 2000 complete in 472.8 sec
[-----------------53%                  ] 1064 of 2000 complete in 473.7 sec
[-----------------53%                  ] 1066 of 2000 complete in 474.6 sec
[-----------------53%                  ] 1068 of 2000 complete in 475.4 sec
[-----------------53%                  ] 1070 of 2000 complete in 476.3 sec
[-----------------53%                  ] 1072 of 2000 complete in 477.1 sec
[-----------------53%                  ] 1074 of 2000 complete in 478.0 sec
[-----------------53%                  ] 1076 of 2000 complete in 478.9 sec
[-----------------53%                  ] 1078 of 2000 complete in 479.7 sec
[-----------------54%                  ] 1080 of 2000 complete in 480.6 sec
[-----------------54%                  ] 1082 of 2000 complete in 481.4 sec
[-----------------54%                  ] 1084 of 2000 complete in 482.3 sec
[-----------------54%                  ] 1086 of 2000 complete in 483.1 sec
[-----------------54%                  ] 1088 of 2000 complete in 484.0 sec
[-----------------54%                  ] 1090 of 2000 complete in 484.8 sec
[-----------------54%                  ] 1092 of 2000 complete in 485.7 sec
[-----------------54%                  ] 1094 of 2000 complete in 486.6 sec
[-----------------54%                  ] 1096 of 2000 complete in 487.5 sec
[-----------------54%                  ] 1098 of 2000 complete in 488.3 sec
[-----------------55%                  ] 1100 of 2000 complete in 489.2 sec
[-----------------55%                  ] 1102 of 2000 complete in 490.0 sec
[-----------------55%                  ] 1104 of 2000 complete in 490.9 sec
[-----------------55%-                 ] 1106 of 2000 complete in 491.8 sec
[-----------------55%-                 ] 1108 of 2000 complete in 492.6 sec
[-----------------55%-                 ] 1110 of 2000 complete in 493.5 sec
[-----------------55%-                 ] 1112 of 2000 complete in 494.3 sec
[-----------------55%-                 ] 1114 of 2000 complete in 495.2 sec
[-----------------55%-                 ] 1116 of 2000 complete in 496.0 sec
[-----------------55%-                 ] 1118 of 2000 complete in 496.9 sec
[-----------------56%-                 ] 1120 of 2000 complete in 497.8 sec
[-----------------56%-                 ] 1122 of 2000 complete in 498.6 sec
[-----------------56%-                 ] 1124 of 2000 complete in 499.5 sec
[-----------------56%-                 ] 1126 of 2000 complete in 500.4 sec
[-----------------56%-                 ] 1128 of 2000 complete in 501.3 sec
[-----------------56%-                 ] 1130 of 2000 complete in 502.1 sec
[-----------------56%-                 ] 1132 of 2000 complete in 502.9 sec
[-----------------56%-                 ] 1134 of 2000 complete in 503.8 sec
[-----------------56%-                 ] 1136 of 2000 complete in 504.7 sec
[-----------------56%-                 ] 1138 of 2000 complete in 505.6 sec
[-----------------57%-                 ] 1140 of 2000 complete in 506.4 sec
[-----------------57%-                 ] 1142 of 2000 complete in 507.3 sec
[-----------------57%-                 ] 1144 of 2000 complete in 508.1 sec
[-----------------57%-                 ] 1146 of 2000 complete in 509.0 sec
[-----------------57%-                 ] 1148 of 2000 complete in 509.8 sec
[-----------------57%-                 ] 1150 of 2000 complete in 510.7 sec
[-----------------57%-                 ] 1152 of 2000 complete in 511.5 sec
[-----------------57%-                 ] 1154 of 2000 complete in 512.3 sec
[-----------------57%-                 ] 1156 of 2000 complete in 513.2 sec
[-----------------57%--                ] 1158 of 2000 complete in 514.1 sec
[-----------------58%--                ] 1160 of 2000 complete in 515.0 sec
[-----------------58%--                ] 1162 of 2000 complete in 515.8 sec
[-----------------58%--                ] 1164 of 2000 complete in 516.7 sec
[-----------------58%--                ] 1166 of 2000 complete in 517.5 sec
[-----------------58%--                ] 1168 of 2000 complete in 518.4 sec
[-----------------58%--                ] 1170 of 2000 complete in 519.2 sec
[-----------------58%--                ] 1172 of 2000 complete in 520.1 sec
[-----------------58%--                ] 1174 of 2000 complete in 521.0 sec
[-----------------58%--                ] 1176 of 2000 complete in 521.9 sec
[-----------------58%--                ] 1178 of 2000 complete in 522.8 sec
[-----------------59%--                ] 1180 of 2000 complete in 523.7 sec
[-----------------59%--                ] 1182 of 2000 complete in 524.5 sec
[-----------------59%--                ] 1184 of 2000 complete in 525.4 sec
[-----------------59%--                ] 1186 of 2000 complete in 526.2 sec
[-----------------59%--                ] 1188 of 2000 complete in 527.0 sec
[-----------------59%--                ] 1190 of 2000 complete in 527.9 sec
[-----------------59%--                ] 1192 of 2000 complete in 528.8 sec
[-----------------59%--                ] 1194 of 2000 complete in 529.6 sec
[-----------------59%--                ] 1196 of 2000 complete in 530.5 sec
[-----------------59%--                ] 1198 of 2000 complete in 531.3 sec
[-----------------60%--                ] 1200 of 2000 complete in 532.2 sec
[-----------------60%--                ] 1202 of 2000 complete in 533.1 sec
[-----------------60%--                ] 1204 of 2000 complete in 533.9 sec
[-----------------60%--                ] 1206 of 2000 complete in 534.8 sec
[-----------------60%--                ] 1208 of 2000 complete in 535.6 sec
[-----------------60%--                ] 1210 of 2000 complete in 536.5 sec
[-----------------60%---               ] 1212 of 2000 complete in 537.4 sec
[-----------------60%---               ] 1214 of 2000 complete in 538.2 sec
[-----------------60%---               ] 1216 of 2000 complete in 539.1 sec
[-----------------60%---               ] 1218 of 2000 complete in 539.9 sec
[-----------------61%---               ] 1220 of 2000 complete in 540.9 sec
[-----------------61%---               ] 1222 of 2000 complete in 541.8 sec
[-----------------61%---               ] 1224 of 2000 complete in 542.7 sec
[-----------------61%---               ] 1226 of 2000 complete in 543.6 sec
[-----------------61%---               ] 1228 of 2000 complete in 544.4 sec
[-----------------61%---               ] 1230 of 2000 complete in 545.3 sec
[-----------------61%---               ] 1232 of 2000 complete in 546.2 sec
[-----------------61%---               ] 1234 of 2000 complete in 547.1 sec
[-----------------61%---               ] 1236 of 2000 complete in 547.9 sec
[-----------------61%---               ] 1238 of 2000 complete in 548.8 sec
[-----------------62%---               ] 1240 of 2000 complete in 549.7 sec
[-----------------62%---               ] 1242 of 2000 complete in 550.5 sec
[-----------------62%---               ] 1244 of 2000 complete in 551.4 sec
[-----------------62%---               ] 1246 of 2000 complete in 552.2 sec
[-----------------62%---               ] 1248 of 2000 complete in 553.1 sec
[-----------------62%---               ] 1250 of 2000 complete in 554.0 sec
[-----------------62%---               ] 1252 of 2000 complete in 554.8 sec
[-----------------62%---               ] 1254 of 2000 complete in 555.7 sec
[-----------------62%---               ] 1256 of 2000 complete in 556.6 sec
[-----------------62%---               ] 1258 of 2000 complete in 557.4 sec
[-----------------63%---               ] 1260 of 2000 complete in 558.3 sec
[-----------------63%---               ] 1262 of 2000 complete in 559.2 sec
[-----------------52%                  ] 1048 of 2000 complete in 469.5 sec
[-----------------52%                  ] 1050 of 2000 complete in 470.3 sec
[-----------------52%                  ] 1052 of 2000 complete in 471.2 sec
[-----------------52%                  ] 1054 of 2000 complete in 472.1 sec
[-----------------52%                  ] 1056 of 2000 complete in 473.0 sec
[-----------------52%                  ] 1058 of 2000 complete in 473.8 sec
[-----------------53%                  ] 1060 of 2000 complete in 474.7 sec
[-----------------53%                  ] 1062 of 2000 complete in 475.6 sec
[-----------------53%                  ] 1064 of 2000 complete in 476.5 sec
[-----------------53%                  ] 1066 of 2000 complete in 477.4 sec
[-----------------53%                  ] 1068 of 2000 complete in 478.2 sec
[-----------------53%                  ] 1070 of 2000 complete in 479.1 sec
[-----------------53%                  ] 1072 of 2000 complete in 479.9 sec
[-----------------53%                  ] 1074 of 2000 complete in 480.8 sec
[-----------------53%                  ] 1076 of 2000 complete in 481.7 sec
[-----------------53%                  ] 1078 of 2000 complete in 482.5 sec
[-----------------54%                  ] 1080 of 2000 complete in 483.4 sec
[-----------------54%                  ] 1082 of 2000 complete in 484.2 sec
[-----------------54%                  ] 1084 of 2000 complete in 485.2 sec
[-----------------54%                  ] 1086 of 2000 complete in 486.0 sec
[-----------------54%                  ] 1088 of 2000 complete in 486.9 sec
[-----------------54%                  ] 1090 of 2000 complete in 487.7 sec
[-----------------54%                  ] 1092 of 2000 complete in 488.6 sec
[-----------------54%                  ] 1094 of 2000 complete in 489.4 sec
[-----------------54%                  ] 1096 of 2000 complete in 490.3 sec
[-----------------54%                  ] 1098 of 2000 complete in 491.1 sec
[-----------------55%                  ] 1100 of 2000 complete in 492.0 sec
[-----------------55%                  ] 1102 of 2000 complete in 492.8 sec
[-----------------55%                  ] 1104 of 2000 complete in 493.7 sec
[-----------------55%-                 ] 1106 of 2000 complete in 494.6 sec
[-----------------55%-                 ] 1108 of 2000 complete in 495.5 sec
[-----------------55%-                 ] 1110 of 2000 complete in 496.3 sec
[-----------------55%-                 ] 1112 of 2000 complete in 497.2 sec
[-----------------55%-                 ] 1114 of 2000 complete in 498.1 sec
[-----------------55%-                 ] 1116 of 2000 complete in 498.9 sec
[-----------------55%-                 ] 1118 of 2000 complete in 499.8 sec
[-----------------56%-                 ] 1120 of 2000 complete in 500.7 sec
[-----------------56%-                 ] 1122 of 2000 complete in 501.6 sec
[-----------------56%-                 ] 1124 of 2000 complete in 502.4 sec
[-----------------56%-                 ] 1126 of 2000 complete in 503.3 sec
[-----------------56%-                 ] 1128 of 2000 complete in 504.1 sec
[-----------------56%-                 ] 1130 of 2000 complete in 505.0 sec
[-----------------56%-                 ] 1132 of 2000 complete in 505.9 sec
[-----------------56%-                 ] 1134 of 2000 complete in 506.8 sec
[-----------------56%-                 ] 1136 of 2000 complete in 507.7 sec
[-----------------56%-                 ] 1138 of 2000 complete in 508.5 sec
[-----------------57%-                 ] 1140 of 2000 complete in 509.4 sec
[-----------------57%-                 ] 1142 of 2000 complete in 510.2 sec
[-----------------57%-                 ] 1144 of 2000 complete in 511.1 sec
[-----------------57%-                 ] 1146 of 2000 complete in 512.0 sec
[-----------------57%-                 ] 1148 of 2000 complete in 512.8 sec
[-----------------57%-                 ] 1150 of 2000 complete in 513.7 sec
[-----------------57%-                 ] 1152 of 2000 complete in 514.5 sec
[-----------------57%-                 ] 1154 of 2000 complete in 515.4 sec
[-----------------57%-                 ] 1156 of 2000 complete in 516.3 sec
[-----------------57%--                ] 1158 of 2000 complete in 517.2 sec
[-----------------58%--                ] 1160 of 2000 complete in 518.0 sec
[-----------------58%--                ] 1162 of 2000 complete in 518.9 sec
[-----------------58%--                ] 1164 of 2000 complete in 519.7 sec
[-----------------58%--                ] 1166 of 2000 complete in 520.6 sec
[-----------------58%--                ] 1168 of 2000 complete in 521.4 sec
[-----------------58%--                ] 1170 of 2000 complete in 522.3 sec
[-----------------58%--                ] 1172 of 2000 complete in 523.2 sec
[-----------------58%--                ] 1174 of 2000 complete in 524.1 sec
[-----------------58%--                ] 1176 of 2000 complete in 524.9 sec
[-----------------58%--                ] 1178 of 2000 complete in 525.8 sec
[-----------------59%--                ] 1180 of 2000 complete in 526.7 sec
[-----------------59%--                ] 1182 of 2000 complete in 527.6 sec
[-----------------59%--                ] 1184 of 2000 complete in 528.4 sec
[-----------------59%--                ] 1186 of 2000 complete in 529.3 sec
[-----------------59%--                ] 1188 of 2000 complete in 530.1 sec
[-----------------59%--                ] 1190 of 2000 complete in 531.0 sec
[-----------------59%--                ] 1192 of 2000 complete in 531.8 sec
[-----------------59%--                ] 1194 of 2000 complete in 532.7 sec
[-----------------59%--                ] 1196 of 2000 complete in 533.5 sec
[-----------------59%--                ] 1198 of 2000 complete in 534.4 sec
[-----------------60%--                ] 1200 of 2000 complete in 535.3 sec
[-----------------60%--                ] 1202 of 2000 complete in 536.1 sec
[-----------------60%--                ] 1204 of 2000 complete in 537.0 sec
[-----------------60%--                ] 1206 of 2000 complete in 537.8 sec
[-----------------60%--                ] 1208 of 2000 complete in 538.7 sec
[-----------------60%--                ] 1210 of 2000 complete in 539.6 sec
[-----------------60%---               ] 1212 of 2000 complete in 540.5 sec
[-----------------60%---               ] 1214 of 2000 complete in 541.4 sec
[-----------------60%---               ] 1216 of 2000 complete in 542.3 sec
[-----------------60%---               ] 1218 of 2000 complete in 543.2 sec
[-----------------61%---               ] 1220 of 2000 complete in 544.0 sec
[-----------------61%---               ] 1222 of 2000 complete in 544.9 sec
[-----------------61%---               ] 1224 of 2000 complete in 545.8 sec
[-----------------61%---               ] 1226 of 2000 complete in 546.6 sec
[-----------------61%---               ] 1228 of 2000 complete in 547.5 sec
[-----------------61%---               ] 1230 of 2000 complete in 548.3 sec
[-----------------61%---               ] 1232 of 2000 complete in 549.2 sec
[-----------------61%---               ] 1234 of 2000 complete in 550.0 sec
[-----------------61%---               ] 1236 of 2000 complete in 550.9 sec
[-----------------61%---               ] 1238 of 2000 complete in 551.8 sec
[-----------------62%---               ] 1240 of 2000 complete in 552.6 sec
[-----------------62%---               ] 1242 of 2000 complete in 553.5 sec
[-----------------62%---               ] 1244 of 2000 complete in 554.3 sec
[-----------------62%---               ] 1246 of 2000 complete in 555.2 sec
[-----------------62%---               ] 1248 of 2000 complete in 556.0 sec
[-----------------62%---               ] 1250 of 2000 complete in 556.9 sec
[-----------------62%---               ] 1252 of 2000 complete in 557.8 sec
[-----------------62%---               ] 1254 of 2000 complete in 558.6 sec
[-----------------62%---               ] 1256 of 2000 complete in 559.5 sec
[-----------------62%---               ] 1258 of 2000 complete in 560.3 sec
[-----------------63%---               ] 1260 of 2000 complete in 561.2 sec

[-----------------63%----              ] 1274 of 2000 complete in 552.2 sec
[-----------------63%----              ] 1276 of 2000 complete in 553.0 sec
[-----------------63%----              ] 1278 of 2000 complete in 553.9 sec
[-----------------64%----              ] 1280 of 2000 complete in 554.7 sec
[-----------------64%----              ] 1282 of 2000 complete in 555.5 sec
[-----------------64%----              ] 1284 of 2000 complete in 556.4 sec
[-----------------64%----              ] 1286 of 2000 complete in 557.2 sec
[-----------------64%----              ] 1288 of 2000 complete in 558.1 sec
[-----------------64%----              ] 1290 of 2000 complete in 558.9 sec
[-----------------64%----              ] 1292 of 2000 complete in 559.7 sec
[-----------------64%----              ] 1294 of 2000 complete in 560.6 sec
[-----------------64%----              ] 1296 of 2000 complete in 561.4 sec
[-----------------64%----              ] 1298 of 2000 complete in 562.3 sec
[-----------------65%----              ] 1300 of 2000 complete in 563.1 sec
[-----------------65%----              ] 1302 of 2000 complete in 564.0 sec
[-----------------65%----              ] 1304 of 2000 complete in 564.8 sec
[-----------------65%----              ] 1306 of 2000 complete in 565.6 sec
[-----------------65%----              ] 1308 of 2000 complete in 566.5 sec
[-----------------65%----              ] 1310 of 2000 complete in 567.3 sec
[-----------------65%----              ] 1312 of 2000 complete in 568.1 sec
[-----------------65%----              ] 1314 of 2000 complete in 568.9 sec
[-----------------65%-----             ] 1316 of 2000 complete in 569.7 sec
[-----------------65%-----             ] 1318 of 2000 complete in 570.5 sec
[-----------------66%-----             ] 1320 of 2000 complete in 571.4 sec
[-----------------66%-----             ] 1322 of 2000 complete in 572.2 sec
[-----------------66%-----             ] 1324 of 2000 complete in 573.0 sec
[-----------------66%-----             ] 1326 of 2000 complete in 573.8 sec
[-----------------66%-----             ] 1328 of 2000 complete in 574.6 sec
[-----------------66%-----             ] 1330 of 2000 complete in 575.4 sec
[-----------------66%-----             ] 1332 of 2000 complete in 576.3 sec
[-----------------66%-----             ] 1334 of 2000 complete in 577.1 sec
[-----------------66%-----             ] 1336 of 2000 complete in 577.9 sec
[-----------------66%-----             ] 1338 of 2000 complete in 578.8 sec
[-----------------67%-----             ] 1340 of 2000 complete in 579.7 sec
[-----------------67%-----             ] 1342 of 2000 complete in 580.5 sec
[-----------------67%-----             ] 1344 of 2000 complete in 581.4 sec
[-----------------67%-----             ] 1346 of 2000 complete in 582.3 sec
[-----------------67%-----             ] 1348 of 2000 complete in 583.1 sec
[-----------------67%-----             ] 1350 of 2000 complete in 584.0 sec
[-----------------67%-----             ] 1352 of 2000 complete in 584.8 sec
[-----------------67%-----             ] 1354 of 2000 complete in 585.7 sec
[-----------------67%-----             ] 1356 of 2000 complete in 586.5 sec
[-----------------67%-----             ] 1358 of 2000 complete in 587.4 sec
[-----------------68%-----             ] 1360 of 2000 complete in 588.2 sec
[-----------------68%-----             ] 1362 of 2000 complete in 589.0 sec
[-----------------68%-----             ] 1364 of 2000 complete in 589.9 sec
[-----------------68%-----             ] 1366 of 2000 complete in 590.7 sec
[-----------------68%-----             ] 1368 of 2000 complete in 591.6 sec
[-----------------68%------            ] 1370 of 2000 complete in 592.4 sec
[-----------------68%------            ] 1372 of 2000 complete in 593.2 sec
[-----------------68%------            ] 1374 of 2000 complete in 594.0 sec
[-----------------68%------            ] 1376 of 2000 complete in 594.9 sec
[-----------------68%------            ] 1378 of 2000 complete in 595.7 sec
[-----------------69%------            ] 1380 of 2000 complete in 596.6 sec
[-----------------69%------            ] 1382 of 2000 complete in 597.4 sec
[-----------------69%------            ] 1384 of 2000 complete in 598.2 sec
[-----------------69%------            ] 1386 of 2000 complete in 599.0 sec
[-----------------69%------            ] 1388 of 2000 complete in 599.9 sec
[-----------------69%------            ] 1390 of 2000 complete in 600.7 sec
[-----------------69%------            ] 1392 of 2000 complete in 601.5 sec
[-----------------69%------            ] 1394 of 2000 complete in 602.4 sec
[-----------------69%------            ] 1396 of 2000 complete in 603.2 sec
[-----------------69%------            ] 1398 of 2000 complete in 604.1 sec
[-----------------70%------            ] 1400 of 2000 complete in 604.9 sec
[-----------------70%------            ] 1402 of 2000 complete in 605.8 sec
[-----------------70%------            ] 1404 of 2000 complete in 606.6 sec
[-----------------70%------            ] 1406 of 2000 complete in 607.5 sec
[-----------------70%------            ] 1408 of 2000 complete in 608.4 sec
[-----------------70%------            ] 1410 of 2000 complete in 609.2 sec
[-----------------70%------            ] 1412 of 2000 complete in 610.0 sec
[-----------------70%------            ] 1414 of 2000 complete in 610.8 sec
[-----------------70%------            ] 1416 of 2000 complete in 611.6 sec
[-----------------70%------            ] 1418 of 2000 complete in 612.5 sec
[-----------------71%------            ] 1420 of 2000 complete in 613.3 sec
[-----------------71%-------           ] 1422 of 2000 complete in 614.2 sec
[-----------------71%-------           ] 1424 of 2000 complete in 615.0 sec
[-----------------71%-------           ] 1426 of 2000 complete in 615.8 sec
[-----------------71%-------           ] 1428 of 2000 complete in 616.6 sec
[-----------------71%-------           ] 1430 of 2000 complete in 617.4 sec
[-----------------71%-------           ] 1432 of 2000 complete in 618.3 sec
[-----------------71%-------           ] 1434 of 2000 complete in 619.1 sec
[-----------------71%-------           ] 1436 of 2000 complete in 619.9 sec
[-----------------71%-------           ] 1438 of 2000 complete in 620.7 sec
[-----------------72%-------           ] 1440 of 2000 complete in 621.6 sec
[-----------------72%-------           ] 1442 of 2000 complete in 622.5 sec
[-----------------72%-------           ] 1444 of 2000 complete in 623.3 sec
[-----------------72%-------           ] 1446 of 2000 complete in 624.2 sec
[-----------------72%-------           ] 1448 of 2000 complete in 625.0 sec
[-----------------72%-------           ] 1450 of 2000 complete in 625.9 sec
[-----------------72%-------           ] 1452 of 2000 complete in 626.8 sec
[-----------------72%-------           ] 1454 of 2000 complete in 627.6 sec
[-----------------72%-------           ] 1456 of 2000 complete in 628.4 sec
[-----------------72%-------           ] 1458 of 2000 complete in 629.2 sec
[-----------------73%-------           ] 1460 of 2000 complete in 630.1 sec
[-----------------73%-------           ] 1462 of 2000 complete in 630.9 sec
[-----------------73%-------           ] 1464 of 2000 complete in 631.7 sec
[-----------------73%-------           ] 1466 of 2000 complete in 632.5 sec
[-----------------73%-------           ] 1468 of 2000 complete in 633.4 sec
[-----------------73%-------           ] 1470 of 2000 complete in 634.2 sec
[-----------------73%-------           ] 1472 of 2000 complete in 635.1 sec
[-----------------73%--------          ] 1474 of 2000 complete in 635.9 sec
[-----------------73%--------          ] 1476 of 2000 complete in 636.8 sec
[-----------------73%--------          ] 1478 of 2000 complete in 637.7 sec
[-----------------74%--------          ] 1480 of 2000 complete in 638.5 sec
[-----------------74%--------          ] 1482 of 2000 complete in 639.3 sec
[-----------------74%--------          ] 1484 of 2000 complete in 640.1 sec
[-----------------74%--------          ] 1486 of 2000 complete in 640.9 sec
[-----------------63%----              ] 1266 of 2000 complete in 552.1 sec
[-----------------63%----              ] 1268 of 2000 complete in 552.9 sec
[-----------------63%----              ] 1270 of 2000 complete in 553.8 sec
[-----------------63%----              ] 1272 of 2000 complete in 554.6 sec
[-----------------63%----              ] 1274 of 2000 complete in 555.5 sec
[-----------------63%----              ] 1276 of 2000 complete in 556.3 sec
[-----------------63%----              ] 1278 of 2000 complete in 557.2 sec
[-----------------64%----              ] 1280 of 2000 complete in 558.0 sec
[-----------------64%----              ] 1282 of 2000 complete in 558.8 sec
[-----------------64%----              ] 1284 of 2000 complete in 559.6 sec
[-----------------64%----              ] 1286 of 2000 complete in 560.5 sec
[-----------------64%----              ] 1288 of 2000 complete in 561.3 sec
[-----------------64%----              ] 1290 of 2000 complete in 562.2 sec
[-----------------64%----              ] 1292 of 2000 complete in 563.0 sec
[-----------------64%----              ] 1294 of 2000 complete in 563.9 sec
[-----------------64%----              ] 1296 of 2000 complete in 564.7 sec
[-----------------64%----              ] 1298 of 2000 complete in 565.5 sec
[-----------------65%----              ] 1300 of 2000 complete in 566.4 sec
[-----------------65%----              ] 1302 of 2000 complete in 567.3 sec
[-----------------65%----              ] 1304 of 2000 complete in 568.1 sec
[-----------------65%----              ] 1306 of 2000 complete in 569.0 sec
[-----------------65%----              ] 1308 of 2000 complete in 569.8 sec
[-----------------65%----              ] 1310 of 2000 complete in 570.6 sec
[-----------------65%----              ] 1312 of 2000 complete in 571.5 sec
[-----------------65%----              ] 1314 of 2000 complete in 572.3 sec
[-----------------65%-----             ] 1316 of 2000 complete in 573.2 sec
[-----------------65%-----             ] 1318 of 2000 complete in 574.0 sec
[-----------------66%-----             ] 1320 of 2000 complete in 574.8 sec
[-----------------66%-----             ] 1322 of 2000 complete in 575.6 sec
[-----------------66%-----             ] 1324 of 2000 complete in 576.5 sec
[-----------------66%-----             ] 1326 of 2000 complete in 577.3 sec
[-----------------66%-----             ] 1328 of 2000 complete in 578.2 sec
[-----------------66%-----             ] 1330 of 2000 complete in 579.0 sec
[-----------------66%-----             ] 1332 of 2000 complete in 579.9 sec
[-----------------66%-----             ] 1334 of 2000 complete in 580.8 sec
[-----------------66%-----             ] 1336 of 2000 complete in 581.6 sec
[-----------------66%-----             ] 1338 of 2000 complete in 582.5 sec
[-----------------67%-----             ] 1340 of 2000 complete in 583.3 sec
[-----------------67%-----             ] 1342 of 2000 complete in 584.2 sec
[-----------------67%-----             ] 1344 of 2000 complete in 585.0 sec
[-----------------67%-----             ] 1346 of 2000 complete in 585.9 sec
[-----------------67%-----             ] 1348 of 2000 complete in 586.7 sec
[-----------------67%-----             ] 1350 of 2000 complete in 587.6 sec
[-----------------67%-----             ] 1352 of 2000 complete in 588.4 sec
[-----------------67%-----             ] 1354 of 2000 complete in 589.3 sec
[-----------------67%-----             ] 1356 of 2000 complete in 590.1 sec
[-----------------67%-----             ] 1358 of 2000 complete in 591.0 sec
[-----------------68%-----             ] 1360 of 2000 complete in 591.8 sec
[-----------------68%-----             ] 1362 of 2000 complete in 592.7 sec
[-----------------68%-----             ] 1364 of 2000 complete in 593.5 sec
[-----------------68%-----             ] 1366 of 2000 complete in 594.4 sec
[-----------------68%-----             ] 1368 of 2000 complete in 595.2 sec
[-----------------68%------            ] 1370 of 2000 complete in 596.0 sec
[-----------------68%------            ] 1372 of 2000 complete in 596.9 sec
[-----------------68%------            ] 1374 of 2000 complete in 597.7 sec
[-----------------68%------            ] 1376 of 2000 complete in 598.5 sec
[-----------------68%------            ] 1378 of 2000 complete in 599.4 sec
[-----------------69%------            ] 1380 of 2000 complete in 600.2 sec
[-----------------69%------            ] 1382 of 2000 complete in 601.1 sec
[-----------------69%------            ] 1384 of 2000 complete in 601.9 sec
[-----------------69%------            ] 1386 of 2000 complete in 602.8 sec
[-----------------69%------            ] 1388 of 2000 complete in 603.7 sec
[-----------------69%------            ] 1390 of 2000 complete in 604.5 sec
[-----------------69%------            ] 1392 of 2000 complete in 605.4 sec
[-----------------69%------            ] 1394 of 2000 complete in 606.2 sec
[-----------------69%------            ] 1396 of 2000 complete in 607.1 sec
[-----------------69%------            ] 1398 of 2000 complete in 608.0 sec
[-----------------70%------            ] 1400 of 2000 complete in 608.8 sec
[-----------------70%------            ] 1402 of 2000 complete in 609.6 sec
[-----------------70%------            ] 1404 of 2000 complete in 610.4 sec
[-----------------70%------            ] 1406 of 2000 complete in 611.2 sec
[-----------------70%------            ] 1408 of 2000 complete in 612.1 sec
[-----------------70%------            ] 1410 of 2000 complete in 612.9 sec
[-----------------70%------            ] 1412 of 2000 complete in 613.8 sec
[-----------------70%------            ] 1414 of 2000 complete in 614.6 sec
[-----------------70%------            ] 1416 of 2000 complete in 615.4 sec
[-----------------70%------            ] 1418 of 2000 complete in 616.3 sec
[-----------------71%------            ] 1420 of 2000 complete in 617.0 sec
[-----------------71%-------           ] 1422 of 2000 complete in 617.9 sec
[-----------------71%-------           ] 1424 of 2000 complete in 618.7 sec
[-----------------71%-------           ] 1426 of 2000 complete in 619.5 sec
[-----------------71%-------           ] 1428 of 2000 complete in 620.4 sec
[-----------------71%-------           ] 1430 of 2000 complete in 621.2 sec
[-----------------71%-------           ] 1432 of 2000 complete in 622.0 sec
[-----------------71%-------           ] 1434 of 2000 complete in 622.9 sec
[-----------------71%-------           ] 1436 of 2000 complete in 623.7 sec
[-----------------71%-------           ] 1438 of 2000 complete in 624.5 sec
[-----------------72%-------           ] 1440 of 2000 complete in 625.3 sec
[-----------------72%-------           ] 1442 of 2000 complete in 626.2 sec
[-----------------72%-------           ] 1444 of 2000 complete in 627.0 sec
[-----------------72%-------           ] 1446 of 2000 complete in 627.9 sec
[-----------------72%-------           ] 1448 of 2000 complete in 628.7 sec
[-----------------72%-------           ] 1450 of 2000 complete in 629.6 sec
[-----------------72%-------           ] 1452 of 2000 complete in 630.4 sec
[-----------------72%-------           ] 1454 of 2000 complete in 631.2 sec
[-----------------72%-------           ] 1456 of 2000 complete in 632.1 sec
[-----------------72%-------           ] 1458 of 2000 complete in 632.9 sec
[-----------------73%-------           ] 1460 of 2000 complete in 633.8 sec
[-----------------73%-------           ] 1462 of 2000 complete in 634.6 sec
[-----------------73%-------           ] 1464 of 2000 complete in 635.4 sec
[-----------------73%-------           ] 1466 of 2000 complete in 636.2 sec
[-----------------73%-------           ] 1468 of 2000 complete in 637.1 sec
[-----------------73%-------           ] 1470 of 2000 complete in 637.9 sec
[-----------------73%-------           ] 1472 of 2000 complete in 638.7 sec
[-----------------73%--------          ] 1474 of 2000 complete in 639.5 sec
[-----------------73%--------          ] 1476 of 2000 complete in 640.3 sec
[-----------------73%--------          ] 1478 of 2000 complete in 641.2 sec

[-----------------63%----              ] 1264 of 2000 complete in 560.0 sec
[-----------------63%----              ] 1266 of 2000 complete in 560.9 sec
[-----------------63%----              ] 1268 of 2000 complete in 561.7 sec
[-----------------63%----              ] 1270 of 2000 complete in 562.6 sec
[-----------------63%----              ] 1272 of 2000 complete in 563.4 sec
[-----------------63%----              ] 1274 of 2000 complete in 564.3 sec
[-----------------63%----              ] 1276 of 2000 complete in 565.1 sec
[-----------------63%----              ] 1278 of 2000 complete in 566.0 sec
[-----------------64%----              ] 1280 of 2000 complete in 566.9 sec
[-----------------64%----              ] 1282 of 2000 complete in 567.7 sec
[-----------------64%----              ] 1284 of 2000 complete in 568.6 sec
[-----------------64%----              ] 1286 of 2000 complete in 569.5 sec
[-----------------64%----              ] 1288 of 2000 complete in 570.3 sec
[-----------------64%----              ] 1290 of 2000 complete in 571.2 sec
[-----------------64%----              ] 1292 of 2000 complete in 572.0 sec
[-----------------64%----              ] 1294 of 2000 complete in 572.9 sec
[-----------------64%----              ] 1296 of 2000 complete in 573.7 sec
[-----------------64%----              ] 1298 of 2000 complete in 574.6 sec
[-----------------65%----              ] 1300 of 2000 complete in 575.5 sec
[-----------------65%----              ] 1302 of 2000 complete in 576.4 sec
[-----------------65%----              ] 1304 of 2000 complete in 577.2 sec
[-----------------65%----              ] 1306 of 2000 complete in 578.0 sec
[-----------------65%----              ] 1308 of 2000 complete in 578.9 sec
[-----------------65%----              ] 1310 of 2000 complete in 579.7 sec
[-----------------65%----              ] 1312 of 2000 complete in 580.6 sec
[-----------------65%----              ] 1314 of 2000 complete in 581.5 sec
[-----------------65%-----             ] 1316 of 2000 complete in 582.4 sec
[-----------------65%-----             ] 1318 of 2000 complete in 583.2 sec
[-----------------66%-----             ] 1320 of 2000 complete in 584.1 sec
[-----------------66%-----             ] 1322 of 2000 complete in 585.0 sec
[-----------------66%-----             ] 1324 of 2000 complete in 585.9 sec
[-----------------66%-----             ] 1326 of 2000 complete in 586.7 sec
[-----------------66%-----             ] 1328 of 2000 complete in 587.6 sec
[-----------------66%-----             ] 1330 of 2000 complete in 588.4 sec
[-----------------66%-----             ] 1332 of 2000 complete in 589.3 sec
[-----------------66%-----             ] 1334 of 2000 complete in 590.1 sec
[-----------------66%-----             ] 1336 of 2000 complete in 591.0 sec
[-----------------66%-----             ] 1338 of 2000 complete in 591.8 sec
[-----------------67%-----             ] 1340 of 2000 complete in 592.7 sec
[-----------------67%-----             ] 1342 of 2000 complete in 593.5 sec
[-----------------67%-----             ] 1344 of 2000 complete in 594.4 sec
[-----------------67%-----             ] 1346 of 2000 complete in 595.3 sec
[-----------------67%-----             ] 1348 of 2000 complete in 596.1 sec
[-----------------67%-----             ] 1350 of 2000 complete in 597.0 sec
[-----------------67%-----             ] 1352 of 2000 complete in 597.8 sec
[-----------------67%-----             ] 1354 of 2000 complete in 598.6 sec
[-----------------67%-----             ] 1356 of 2000 complete in 599.5 sec
[-----------------67%-----             ] 1358 of 2000 complete in 600.4 sec
[-----------------68%-----             ] 1360 of 2000 complete in 601.2 sec
[-----------------68%-----             ] 1362 of 2000 complete in 602.1 sec
[-----------------68%-----             ] 1364 of 2000 complete in 602.9 sec
[-----------------68%-----             ] 1366 of 2000 complete in 603.8 sec
[-----------------68%-----             ] 1368 of 2000 complete in 604.7 sec
[-----------------68%------            ] 1370 of 2000 complete in 605.6 sec
[-----------------68%------            ] 1372 of 2000 complete in 606.4 sec
[-----------------68%------            ] 1374 of 2000 complete in 607.3 sec
[-----------------68%------            ] 1376 of 2000 complete in 608.1 sec
[-----------------68%------            ] 1378 of 2000 complete in 609.0 sec
[-----------------69%------            ] 1380 of 2000 complete in 609.8 sec
[-----------------69%------            ] 1382 of 2000 complete in 610.7 sec
[-----------------69%------            ] 1384 of 2000 complete in 611.5 sec
[-----------------69%------            ] 1386 of 2000 complete in 612.4 sec
[-----------------69%------            ] 1388 of 2000 complete in 613.3 sec
[-----------------69%------            ] 1390 of 2000 complete in 614.2 sec
[-----------------69%------            ] 1392 of 2000 complete in 615.0 sec
[-----------------69%------            ] 1394 of 2000 complete in 615.9 sec
[-----------------69%------            ] 1396 of 2000 complete in 616.7 sec
[-----------------69%------            ] 1398 of 2000 complete in 617.5 sec
[-----------------70%------            ] 1400 of 2000 complete in 618.4 sec
[-----------------70%------            ] 1402 of 2000 complete in 619.2 sec
[-----------------70%------            ] 1404 of 2000 complete in 620.1 sec
[-----------------70%------            ] 1406 of 2000 complete in 621.0 sec
[-----------------70%------            ] 1408 of 2000 complete in 621.8 sec
[-----------------70%------            ] 1410 of 2000 complete in 622.6 sec
[-----------------70%------            ] 1412 of 2000 complete in 623.5 sec
[-----------------70%------            ] 1414 of 2000 complete in 624.4 sec
[-----------------70%------            ] 1416 of 2000 complete in 625.3 sec
[-----------------70%------            ] 1418 of 2000 complete in 626.2 sec
[-----------------71%------            ] 1420 of 2000 complete in 627.1 sec
[-----------------71%-------           ] 1422 of 2000 complete in 627.9 sec
[-----------------71%-------           ] 1424 of 2000 complete in 628.8 sec
[-----------------71%-------           ] 1426 of 2000 complete in 629.6 sec
[-----------------71%-------           ] 1428 of 2000 complete in 630.5 sec
[-----------------71%-------           ] 1430 of 2000 complete in 631.3 sec
[-----------------71%-------           ] 1432 of 2000 complete in 632.2 sec
[-----------------71%-------           ] 1434 of 2000 complete in 633.0 sec
[-----------------71%-------           ] 1436 of 2000 complete in 633.9 sec
[-----------------71%-------           ] 1438 of 2000 complete in 634.8 sec
[-----------------72%-------           ] 1440 of 2000 complete in 635.6 sec
[-----------------72%-------           ] 1442 of 2000 complete in 636.5 sec
[-----------------72%-------           ] 1444 of 2000 complete in 637.3 sec
[-----------------72%-------           ] 1446 of 2000 complete in 638.2 sec
[-----------------72%-------           ] 1448 of 2000 complete in 639.0 sec
[-----------------72%-------           ] 1450 of 2000 complete in 639.9 sec
[-----------------72%-------           ] 1452 of 2000 complete in 640.7 sec
[-----------------72%-------           ] 1454 of 2000 complete in 641.6 sec
[-----------------72%-------           ] 1456 of 2000 complete in 642.4 sec
[-----------------72%-------           ] 1458 of 2000 complete in 643.3 sec
[-----------------73%-------           ] 1460 of 2000 complete in 644.2 sec
[-----------------73%-------           ] 1462 of 2000 complete in 645.0 sec
[-----------------73%-------           ] 1464 of 2000 complete in 645.9 sec
[-----------------73%-------           ] 1466 of 2000 complete in 646.7 sec
[-----------------73%-------           ] 1468 of 2000 complete in 647.6 sec
[-----------------73%-------           ] 1470 of 2000 complete in 648.5 sec
[-----------------73%-------           ] 1472 of 2000 complete in 649.3 sec
[-----------------73%--------          ] 1474 of 2000 complete in 650.1 sec
[-----------------73%--------          ] 1476 of 2000 complete in 651.0 sec
[-----------------63%---               ] 1262 of 2000 complete in 562.0 sec
[-----------------63%----              ] 1264 of 2000 complete in 562.9 sec
[-----------------63%----              ] 1266 of 2000 complete in 563.7 sec
[-----------------63%----              ] 1268 of 2000 complete in 564.6 sec
[-----------------63%----              ] 1270 of 2000 complete in 565.4 sec
[-----------------63%----              ] 1272 of 2000 complete in 566.3 sec
[-----------------63%----              ] 1274 of 2000 complete in 567.2 sec
[-----------------63%----              ] 1276 of 2000 complete in 568.0 sec
[-----------------63%----              ] 1278 of 2000 complete in 568.9 sec
[-----------------64%----              ] 1280 of 2000 complete in 569.7 sec
[-----------------64%----              ] 1282 of 2000 complete in 570.6 sec
[-----------------64%----              ] 1284 of 2000 complete in 571.4 sec
[-----------------64%----              ] 1286 of 2000 complete in 572.3 sec
[-----------------64%----              ] 1288 of 2000 complete in 573.2 sec
[-----------------64%----              ] 1290 of 2000 complete in 574.0 sec
[-----------------64%----              ] 1292 of 2000 complete in 574.9 sec
[-----------------64%----              ] 1294 of 2000 complete in 575.8 sec
[-----------------64%----              ] 1296 of 2000 complete in 576.7 sec
[-----------------64%----              ] 1298 of 2000 complete in 577.5 sec
[-----------------65%----              ] 1300 of 2000 complete in 578.3 sec
[-----------------65%----              ] 1302 of 2000 complete in 579.2 sec
[-----------------65%----              ] 1304 of 2000 complete in 580.1 sec
[-----------------65%----              ] 1306 of 2000 complete in 581.0 sec
[-----------------65%----              ] 1308 of 2000 complete in 581.8 sec
[-----------------65%----              ] 1310 of 2000 complete in 582.7 sec
[-----------------65%----              ] 1312 of 2000 complete in 583.6 sec
[-----------------65%----              ] 1314 of 2000 complete in 584.5 sec
[-----------------65%-----             ] 1316 of 2000 complete in 585.3 sec
[-----------------65%-----             ] 1318 of 2000 complete in 586.2 sec
[-----------------66%-----             ] 1320 of 2000 complete in 587.1 sec
[-----------------66%-----             ] 1322 of 2000 complete in 588.0 sec
[-----------------66%-----             ] 1324 of 2000 complete in 588.8 sec
[-----------------66%-----             ] 1326 of 2000 complete in 589.7 sec
[-----------------66%-----             ] 1328 of 2000 complete in 590.6 sec
[-----------------66%-----             ] 1330 of 2000 complete in 591.4 sec
[-----------------66%-----             ] 1332 of 2000 complete in 592.2 sec
[-----------------66%-----             ] 1334 of 2000 complete in 593.1 sec
[-----------------66%-----             ] 1336 of 2000 complete in 593.9 sec
[-----------------66%-----             ] 1338 of 2000 complete in 594.7 sec
[-----------------67%-----             ] 1340 of 2000 complete in 595.6 sec
[-----------------67%-----             ] 1342 of 2000 complete in 596.4 sec
[-----------------67%-----             ] 1344 of 2000 complete in 597.3 sec
[-----------------67%-----             ] 1346 of 2000 complete in 598.1 sec
[-----------------67%-----             ] 1348 of 2000 complete in 599.0 sec
[-----------------67%-----             ] 1350 of 2000 complete in 599.9 sec
[-----------------67%-----             ] 1352 of 2000 complete in 600.7 sec
[-----------------67%-----             ] 1354 of 2000 complete in 601.6 sec
[-----------------67%-----             ] 1356 of 2000 complete in 602.4 sec
[-----------------67%-----             ] 1358 of 2000 complete in 603.2 sec
[-----------------68%-----             ] 1360 of 2000 complete in 604.1 sec
[-----------------68%-----             ] 1362 of 2000 complete in 605.0 sec
[-----------------68%-----             ] 1364 of 2000 complete in 605.9 sec
[-----------------68%-----             ] 1366 of 2000 complete in 606.7 sec
[-----------------68%-----             ] 1368 of 2000 complete in 607.5 sec
[-----------------68%------            ] 1370 of 2000 complete in 608.4 sec
[-----------------68%------            ] 1372 of 2000 complete in 609.2 sec
[-----------------68%------            ] 1374 of 2000 complete in 610.1 sec
[-----------------68%------            ] 1376 of 2000 complete in 611.0 sec
[-----------------68%------            ] 1378 of 2000 complete in 611.9 sec
[-----------------69%------            ] 1380 of 2000 complete in 612.7 sec
[-----------------69%------            ] 1382 of 2000 complete in 613.5 sec
[-----------------69%------            ] 1384 of 2000 complete in 614.4 sec
[-----------------69%------            ] 1386 of 2000 complete in 615.2 sec
[-----------------69%------            ] 1388 of 2000 complete in 616.1 sec
[-----------------69%------            ] 1390 of 2000 complete in 616.9 sec
[-----------------69%------            ] 1392 of 2000 complete in 617.8 sec
[-----------------69%------            ] 1394 of 2000 complete in 618.6 sec
[-----------------69%------            ] 1396 of 2000 complete in 619.5 sec
[-----------------69%------            ] 1398 of 2000 complete in 620.3 sec
[-----------------70%------            ] 1400 of 2000 complete in 621.2 sec
[-----------------70%------            ] 1402 of 2000 complete in 622.0 sec
[-----------------70%------            ] 1404 of 2000 complete in 622.9 sec
[-----------------70%------            ] 1406 of 2000 complete in 623.8 sec
[-----------------70%------            ] 1408 of 2000 complete in 624.6 sec
[-----------------70%------            ] 1410 of 2000 complete in 625.5 sec
[-----------------70%------            ] 1412 of 2000 complete in 626.4 sec
[-----------------70%------            ] 1414 of 2000 complete in 627.2 sec
[-----------------70%------            ] 1416 of 2000 complete in 628.1 sec
[-----------------70%------            ] 1418 of 2000 complete in 628.9 sec
[-----------------71%------            ] 1420 of 2000 complete in 629.8 sec
[-----------------71%-------           ] 1422 of 2000 complete in 630.6 sec
[-----------------71%-------           ] 1424 of 2000 complete in 631.5 sec
[-----------------71%-------           ] 1426 of 2000 complete in 632.3 sec
[-----------------71%-------           ] 1428 of 2000 complete in 633.2 sec
[-----------------71%-------           ] 1430 of 2000 complete in 634.0 sec
[-----------------71%-------           ] 1432 of 2000 complete in 634.9 sec
[-----------------71%-------           ] 1434 of 2000 complete in 635.7 sec
[-----------------71%-------           ] 1436 of 2000 complete in 636.6 sec
[-----------------71%-------           ] 1438 of 2000 complete in 637.5 sec
[-----------------72%-------           ] 1440 of 2000 complete in 638.3 sec
[-----------------72%-------           ] 1442 of 2000 complete in 639.2 sec
[-----------------72%-------           ] 1444 of 2000 complete in 640.0 sec
[-----------------72%-------           ] 1446 of 2000 complete in 640.9 sec
[-----------------72%-------           ] 1448 of 2000 complete in 641.8 sec
[-----------------72%-------           ] 1450 of 2000 complete in 642.6 sec
[-----------------72%-------           ] 1452 of 2000 complete in 643.5 sec
[-----------------72%-------           ] 1454 of 2000 complete in 644.3 sec
[-----------------72%-------           ] 1456 of 2000 complete in 645.2 sec
[-----------------72%-------           ] 1458 of 2000 complete in 646.1 sec
[-----------------73%-------           ] 1460 of 2000 complete in 646.9 sec
[-----------------73%-------           ] 1462 of 2000 complete in 647.8 sec
[-----------------73%-------           ] 1464 of 2000 complete in 648.7 sec
[-----------------73%-------           ] 1466 of 2000 complete in 649.6 sec
[-----------------73%-------           ] 1468 of 2000 complete in 650.4 sec
[-----------------73%-------           ] 1470 of 2000 complete in 651.3 sec
[-----------------73%-------           ] 1472 of 2000 complete in 652.2 sec
[-----------------73%--------          ] 1474 of 2000 complete in 653.0 sec

[-----------------74%--------          ] 1488 of 2000 complete in 641.7 sec
[-----------------74%--------          ] 1490 of 2000 complete in 642.6 sec
[-----------------74%--------          ] 1492 of 2000 complete in 643.4 sec
[-----------------74%--------          ] 1494 of 2000 complete in 644.2 sec
[-----------------74%--------          ] 1496 of 2000 complete in 645.0 sec
[-----------------74%--------          ] 1498 of 2000 complete in 645.9 sec
[-----------------75%--------          ] 1500 of 2000 complete in 646.7 sec
[-----------------75%--------          ] 1502 of 2000 complete in 647.6 sec
[-----------------75%--------          ] 1504 of 2000 complete in 648.4 sec
[-----------------75%--------          ] 1506 of 2000 complete in 649.2 sec
[-----------------75%--------          ] 1508 of 2000 complete in 650.0 sec
[-----------------75%--------          ] 1510 of 2000 complete in 650.9 sec
[-----------------75%--------          ] 1512 of 2000 complete in 651.7 sec
[-----------------75%--------          ] 1514 of 2000 complete in 652.5 sec
[-----------------75%--------          ] 1516 of 2000 complete in 653.4 sec
[-----------------75%--------          ] 1518 of 2000 complete in 654.2 sec
[-----------------76%--------          ] 1520 of 2000 complete in 655.1 sec
[-----------------76%--------          ] 1522 of 2000 complete in 655.9 sec
[-----------------76%--------          ] 1524 of 2000 complete in 656.7 sec
[-----------------76%--------          ] 1526 of 2000 complete in 657.6 sec
[-----------------76%---------         ] 1528 of 2000 complete in 658.4 sec
[-----------------76%---------         ] 1530 of 2000 complete in 659.3 sec
[-----------------76%---------         ] 1532 of 2000 complete in 660.1 sec
[-----------------76%---------         ] 1534 of 2000 complete in 660.9 sec
[-----------------76%---------         ] 1536 of 2000 complete in 661.7 sec
[-----------------76%---------         ] 1538 of 2000 complete in 662.5 sec
[-----------------77%---------         ] 1540 of 2000 complete in 663.4 sec
[-----------------77%---------         ] 1542 of 2000 complete in 664.2 sec
[-----------------77%---------         ] 1544 of 2000 complete in 665.0 sec
[-----------------77%---------         ] 1546 of 2000 complete in 665.9 sec
[-----------------77%---------         ] 1548 of 2000 complete in 666.7 sec
[-----------------77%---------         ] 1550 of 2000 complete in 667.5 sec
[-----------------77%---------         ] 1552 of 2000 complete in 668.4 sec
[-----------------77%---------         ] 1554 of 2000 complete in 669.3 sec
[-----------------77%---------         ] 1556 of 2000 complete in 670.2 sec
[-----------------77%---------         ] 1558 of 2000 complete in 671.1 sec
[-----------------78%---------         ] 1560 of 2000 complete in 672.0 sec
[-----------------78%---------         ] 1562 of 2000 complete in 672.8 sec
[-----------------78%---------         ] 1564 of 2000 complete in 673.6 sec
[-----------------78%---------         ] 1566 of 2000 complete in 674.4 sec
[-----------------78%---------         ] 1568 of 2000 complete in 675.3 sec
[-----------------78%---------         ] 1570 of 2000 complete in 676.1 sec
[-----------------78%---------         ] 1572 of 2000 complete in 676.9 sec
[-----------------78%---------         ] 1574 of 2000 complete in 677.8 sec
[-----------------78%---------         ] 1576 of 2000 complete in 678.6 sec
[-----------------78%---------         ] 1578 of 2000 complete in 679.4 sec
[-----------------79%----------        ] 1580 of 2000 complete in 680.3 sec
[-----------------79%----------        ] 1582 of 2000 complete in 681.1 sec
[-----------------79%----------        ] 1584 of 2000 complete in 682.0 sec
[-----------------79%----------        ] 1586 of 2000 complete in 682.9 sec
[-----------------79%----------        ] 1588 of 2000 complete in 683.8 sec
[-----------------79%----------        ] 1590 of 2000 complete in 684.7 sec
[-----------------79%----------        ] 1592 of 2000 complete in 685.5 sec
[-----------------79%----------        ] 1594 of 2000 complete in 686.4 sec
[-----------------79%----------        ] 1596 of 2000 complete in 687.2 sec
[-----------------79%----------        ] 1598 of 2000 complete in 688.0 sec
[-----------------80%----------        ] 1600 of 2000 complete in 688.9 sec
[-----------------80%----------        ] 1602 of 2000 complete in 689.8 sec
[-----------------80%----------        ] 1604 of 2000 complete in 690.6 sec
[-----------------80%----------        ] 1606 of 2000 complete in 691.4 sec
[-----------------80%----------        ] 1608 of 2000 complete in 692.3 sec
[-----------------80%----------        ] 1610 of 2000 complete in 693.1 sec
[-----------------80%----------        ] 1612 of 2000 complete in 694.0 sec
[-----------------80%----------        ] 1614 of 2000 complete in 694.8 sec
[-----------------80%----------        ] 1616 of 2000 complete in 695.6 sec
[-----------------80%----------        ] 1618 of 2000 complete in 696.5 sec
[-----------------81%----------        ] 1620 of 2000 complete in 697.3 sec
[-----------------81%----------        ] 1622 of 2000 complete in 698.1 sec
[-----------------81%----------        ] 1624 of 2000 complete in 698.9 sec
[-----------------81%----------        ] 1626 of 2000 complete in 699.8 sec
[-----------------81%----------        ] 1628 of 2000 complete in 700.6 sec
[-----------------81%----------        ] 1630 of 2000 complete in 701.4 sec
[-----------------81%-----------       ] 1632 of 2000 complete in 702.2 sec
[-----------------81%-----------       ] 1634 of 2000 complete in 703.0 sec
[-----------------81%-----------       ] 1636 of 2000 complete in 703.9 sec
[-----------------81%-----------       ] 1638 of 2000 complete in 704.7 sec
[-----------------82%-----------       ] 1640 of 2000 complete in 705.6 sec
[-----------------82%-----------       ] 1642 of 2000 complete in 706.4 sec
[-----------------82%-----------       ] 1644 of 2000 complete in 707.2 sec
[-----------------82%-----------       ] 1646 of 2000 complete in 708.0 sec
[-----------------82%-----------       ] 1648 of 2000 complete in 708.8 sec
[-----------------82%-----------       ] 1650 of 2000 complete in 709.7 sec
[-----------------82%-----------       ] 1652 of 2000 complete in 710.5 sec
[-----------------82%-----------       ] 1654 of 2000 complete in 711.3 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 712.1 sec
[-----------------82%-----------       ] 1658 of 2000 complete in 713.0 sec
[-----------------83%-----------       ] 1660 of 2000 complete in 713.8 sec
[-----------------83%-----------       ] 1662 of 2000 complete in 714.7 sec
[-----------------83%-----------       ] 1664 of 2000 complete in 715.5 sec
[-----------------83%-----------       ] 1666 of 2000 complete in 716.4 sec
[-----------------83%-----------       ] 1668 of 2000 complete in 717.2 sec
[-----------------83%-----------       ] 1670 of 2000 complete in 718.1 sec
[-----------------83%-----------       ] 1672 of 2000 complete in 718.9 sec
[-----------------83%-----------       ] 1674 of 2000 complete in 719.7 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 720.6 sec
[-----------------83%-----------       ] 1678 of 2000 complete in 721.4 sec
[-----------------84%-----------       ] 1680 of 2000 complete in 722.2 sec
[-----------------84%-----------       ] 1682 of 2000 complete in 723.0 sec
[-----------------84%-----------       ] 1684 of 2000 complete in 723.8 sec
[-----------------84%------------      ] 1686 of 2000 complete in 724.7 sec
[-----------------84%------------      ] 1688 of 2000 complete in 725.5 sec
[-----------------84%------------      ] 1690 of 2000 complete in 726.4 sec
[-----------------84%------------      ] 1692 of 2000 complete in 727.2 sec
[-----------------84%------------      ] 1694 of 2000 complete in 728.0 sec
[-----------------84%------------      ] 1696 of 2000 complete in 728.9 sec
[-----------------84%------------      ] 1698 of 2000 complete in 729.7 sec
[-----------------85%------------      ] 1700 of 2000 complete in 730.5 sec
[-----------------74%--------          ] 1480 of 2000 complete in 642.0 sec
[-----------------74%--------          ] 1482 of 2000 complete in 642.8 sec
[-----------------74%--------          ] 1484 of 2000 complete in 643.7 sec
[-----------------74%--------          ] 1486 of 2000 complete in 644.5 sec
[-----------------74%--------          ] 1488 of 2000 complete in 645.4 sec
[-----------------74%--------          ] 1490 of 2000 complete in 646.2 sec
[-----------------74%--------          ] 1492 of 2000 complete in 647.0 sec
[-----------------74%--------          ] 1494 of 2000 complete in 647.9 sec
[-----------------74%--------          ] 1496 of 2000 complete in 648.7 sec
[-----------------74%--------          ] 1498 of 2000 complete in 649.6 sec
[-----------------75%--------          ] 1500 of 2000 complete in 650.5 sec
[-----------------75%--------          ] 1502 of 2000 complete in 651.3 sec
[-----------------75%--------          ] 1504 of 2000 complete in 652.2 sec
[-----------------75%--------          ] 1506 of 2000 complete in 653.0 sec
[-----------------75%--------          ] 1508 of 2000 complete in 653.9 sec
[-----------------75%--------          ] 1510 of 2000 complete in 654.7 sec
[-----------------75%--------          ] 1512 of 2000 complete in 655.6 sec
[-----------------75%--------          ] 1514 of 2000 complete in 656.4 sec
[-----------------75%--------          ] 1516 of 2000 complete in 657.2 sec
[-----------------75%--------          ] 1518 of 2000 complete in 658.1 sec
[-----------------76%--------          ] 1520 of 2000 complete in 658.9 sec
[-----------------76%--------          ] 1522 of 2000 complete in 659.7 sec
[-----------------76%--------          ] 1524 of 2000 complete in 660.6 sec
[-----------------76%--------          ] 1526 of 2000 complete in 661.4 sec
[-----------------76%---------         ] 1528 of 2000 complete in 662.2 sec
[-----------------76%---------         ] 1530 of 2000 complete in 663.1 sec
[-----------------76%---------         ] 1532 of 2000 complete in 663.9 sec
[-----------------76%---------         ] 1534 of 2000 complete in 664.7 sec
[-----------------76%---------         ] 1536 of 2000 complete in 665.6 sec
[-----------------76%---------         ] 1538 of 2000 complete in 666.5 sec
[-----------------77%---------         ] 1540 of 2000 complete in 667.3 sec
[-----------------77%---------         ] 1542 of 2000 complete in 668.2 sec
[-----------------77%---------         ] 1544 of 2000 complete in 669.1 sec
[-----------------77%---------         ] 1545 of 2000 complete in 669.6 sec
[-----------------77%---------         ] 1547 of 2000 complete in 670.5 sec
[-----------------77%---------         ] 1549 of 2000 complete in 671.4 sec
[-----------------77%---------         ] 1551 of 2000 complete in 672.2 sec
[-----------------77%---------         ] 1553 of 2000 complete in 673.1 sec
[-----------------77%---------         ] 1555 of 2000 complete in 673.9 sec
[-----------------77%---------         ] 1557 of 2000 complete in 674.8 sec
[-----------------77%---------         ] 1559 of 2000 complete in 675.6 sec
[-----------------78%---------         ] 1561 of 2000 complete in 676.4 sec
[-----------------78%---------         ] 1563 of 2000 complete in 677.2 sec
[-----------------78%---------         ] 1565 of 2000 complete in 678.1 sec
[-----------------78%---------         ] 1567 of 2000 complete in 678.9 sec
[-----------------78%---------         ] 1569 of 2000 complete in 679.7 sec
[-----------------78%---------         ] 1571 of 2000 complete in 680.6 sec
[-----------------78%---------         ] 1573 of 2000 complete in 681.4 sec
[-----------------78%---------         ] 1575 of 2000 complete in 682.3 sec
[-----------------78%---------         ] 1577 of 2000 complete in 683.2 sec
[-----------------78%----------        ] 1579 of 2000 complete in 684.1 sec
[-----------------79%----------        ] 1581 of 2000 complete in 684.9 sec
[-----------------79%----------        ] 1583 of 2000 complete in 685.7 sec
[-----------------79%----------        ] 1585 of 2000 complete in 686.5 sec
[-----------------79%----------        ] 1587 of 2000 complete in 687.3 sec
[-----------------79%----------        ] 1589 of 2000 complete in 688.2 sec
[-----------------79%----------        ] 1591 of 2000 complete in 689.0 sec
[-----------------79%----------        ] 1593 of 2000 complete in 689.9 sec
[-----------------79%----------        ] 1595 of 2000 complete in 690.7 sec
[-----------------79%----------        ] 1597 of 2000 complete in 691.5 sec
[-----------------79%----------        ] 1599 of 2000 complete in 692.4 sec
[-----------------80%----------        ] 1601 of 2000 complete in 693.2 sec
[-----------------80%----------        ] 1603 of 2000 complete in 694.0 sec
[-----------------80%----------        ] 1605 of 2000 complete in 694.9 sec
[-----------------80%----------        ] 1607 of 2000 complete in 695.7 sec
[-----------------80%----------        ] 1609 of 2000 complete in 696.6 sec
[-----------------80%----------        ] 1611 of 2000 complete in 697.4 sec
[-----------------80%----------        ] 1613 of 2000 complete in 698.3 sec
[-----------------80%----------        ] 1615 of 2000 complete in 699.1 sec
[-----------------80%----------        ] 1617 of 2000 complete in 699.9 sec
[-----------------80%----------        ] 1619 of 2000 complete in 700.8 sec
[-----------------81%----------        ] 1621 of 2000 complete in 701.6 sec
[-----------------81%----------        ] 1623 of 2000 complete in 702.4 sec
[-----------------81%----------        ] 1625 of 2000 complete in 703.3 sec
[-----------------81%----------        ] 1627 of 2000 complete in 704.1 sec
[-----------------81%----------        ] 1629 of 2000 complete in 704.9 sec
[-----------------81%----------        ] 1631 of 2000 complete in 705.7 sec
[-----------------81%-----------       ] 1633 of 2000 complete in 706.6 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 707.4 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 708.2 sec
[-----------------81%-----------       ] 1639 of 2000 complete in 709.1 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 709.9 sec
[-----------------82%-----------       ] 1643 of 2000 complete in 710.7 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 711.5 sec
[-----------------82%-----------       ] 1647 of 2000 complete in 712.3 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 713.2 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 714.0 sec
[-----------------82%-----------       ] 1653 of 2000 complete in 714.9 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 715.8 sec
[-----------------82%-----------       ] 1657 of 2000 complete in 716.7 sec
[-----------------82%-----------       ] 1659 of 2000 complete in 717.5 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 718.3 sec
[-----------------83%-----------       ] 1663 of 2000 complete in 719.2 sec
[-----------------83%-----------       ] 1665 of 2000 complete in 720.0 sec
[-----------------83%-----------       ] 1667 of 2000 complete in 720.9 sec
[-----------------83%-----------       ] 1669 of 2000 complete in 721.7 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 722.5 sec
[-----------------83%-----------       ] 1673 of 2000 complete in 723.4 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 724.2 sec
[-----------------83%-----------       ] 1677 of 2000 complete in 725.0 sec
[-----------------83%-----------       ] 1679 of 2000 complete in 725.9 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 726.7 sec
[-----------------84%-----------       ] 1683 of 2000 complete in 727.6 sec
[-----------------84%------------      ] 1685 of 2000 complete in 728.4 sec
[-----------------84%------------      ] 1687 of 2000 complete in 729.2 sec
[-----------------84%------------      ] 1689 of 2000 complete in 730.0 sec
[-----------------84%------------      ] 1691 of 2000 complete in 730.9 sec

[-----------------73%--------          ] 1478 of 2000 complete in 651.9 sec
[-----------------74%--------          ] 1480 of 2000 complete in 652.8 sec
[-----------------74%--------          ] 1482 of 2000 complete in 653.6 sec
[-----------------74%--------          ] 1484 of 2000 complete in 654.5 sec
[-----------------74%--------          ] 1486 of 2000 complete in 655.4 sec
[-----------------74%--------          ] 1488 of 2000 complete in 656.2 sec
[-----------------74%--------          ] 1490 of 2000 complete in 657.1 sec
[-----------------74%--------          ] 1492 of 2000 complete in 657.9 sec
[-----------------74%--------          ] 1494 of 2000 complete in 658.8 sec
[-----------------74%--------          ] 1496 of 2000 complete in 659.6 sec
[-----------------74%--------          ] 1498 of 2000 complete in 660.5 sec
[-----------------75%--------          ] 1500 of 2000 complete in 661.3 sec
[-----------------75%--------          ] 1502 of 2000 complete in 662.2 sec
[-----------------75%--------          ] 1504 of 2000 complete in 663.1 sec
[-----------------75%--------          ] 1506 of 2000 complete in 664.0 sec
[-----------------75%--------          ] 1508 of 2000 complete in 664.8 sec
[-----------------75%--------          ] 1510 of 2000 complete in 665.7 sec
[-----------------75%--------          ] 1512 of 2000 complete in 666.6 sec
[-----------------75%--------          ] 1514 of 2000 complete in 667.4 sec
[-----------------75%--------          ] 1516 of 2000 complete in 668.3 sec
[-----------------75%--------          ] 1518 of 2000 complete in 669.2 sec
[-----------------76%--------          ] 1520 of 2000 complete in 670.2 sec
[-----------------76%--------          ] 1522 of 2000 complete in 671.1 sec
[-----------------76%--------          ] 1524 of 2000 complete in 672.0 sec
[-----------------76%--------          ] 1526 of 2000 complete in 672.8 sec
[-----------------76%---------         ] 1528 of 2000 complete in 673.7 sec
[-----------------76%---------         ] 1530 of 2000 complete in 674.5 sec
[-----------------76%---------         ] 1532 of 2000 complete in 675.4 sec
[-----------------76%---------         ] 1534 of 2000 complete in 676.2 sec
[-----------------76%---------         ] 1536 of 2000 complete in 677.1 sec
[-----------------76%---------         ] 1538 of 2000 complete in 677.9 sec
[-----------------77%---------         ] 1540 of 2000 complete in 678.7 sec
[-----------------77%---------         ] 1542 of 2000 complete in 679.6 sec
[-----------------77%---------         ] 1544 of 2000 complete in 680.5 sec
[-----------------77%---------         ] 1546 of 2000 complete in 681.4 sec
[-----------------77%---------         ] 1548 of 2000 complete in 682.3 sec
[-----------------77%---------         ] 1550 of 2000 complete in 683.2 sec
[-----------------77%---------         ] 1552 of 2000 complete in 684.1 sec
[-----------------77%---------         ] 1554 of 2000 complete in 684.9 sec
[-----------------77%---------         ] 1556 of 2000 complete in 685.8 sec
[-----------------77%---------         ] 1558 of 2000 complete in 686.7 sec
[-----------------78%---------         ] 1560 of 2000 complete in 687.5 sec
[-----------------78%---------         ] 1562 of 2000 complete in 688.4 sec
[-----------------78%---------         ] 1564 of 2000 complete in 689.3 sec
[-----------------78%---------         ] 1566 of 2000 complete in 690.2 sec
[-----------------78%---------         ] 1568 of 2000 complete in 691.0 sec
[-----------------78%---------         ] 1570 of 2000 complete in 691.9 sec
[-----------------78%---------         ] 1572 of 2000 complete in 692.8 sec
[-----------------78%---------         ] 1574 of 2000 complete in 693.6 sec
[-----------------78%---------         ] 1576 of 2000 complete in 694.5 sec
[-----------------78%---------         ] 1578 of 2000 complete in 695.3 sec
[-----------------79%----------        ] 1580 of 2000 complete in 696.2 sec
[-----------------79%----------        ] 1582 of 2000 complete in 697.0 sec
[-----------------79%----------        ] 1584 of 2000 complete in 697.9 sec
[-----------------79%----------        ] 1586 of 2000 complete in 698.7 sec
[-----------------79%----------        ] 1588 of 2000 complete in 699.6 sec
[-----------------79%----------        ] 1590 of 2000 complete in 700.4 sec
[-----------------79%----------        ] 1592 of 2000 complete in 701.3 sec
[-----------------79%----------        ] 1594 of 2000 complete in 702.2 sec
[-----------------79%----------        ] 1596 of 2000 complete in 703.1 sec
[-----------------79%----------        ] 1598 of 2000 complete in 703.9 sec
[-----------------80%----------        ] 1600 of 2000 complete in 704.8 sec
[-----------------80%----------        ] 1602 of 2000 complete in 705.6 sec
[-----------------80%----------        ] 1604 of 2000 complete in 706.5 sec
[-----------------80%----------        ] 1606 of 2000 complete in 707.3 sec
[-----------------80%----------        ] 1608 of 2000 complete in 708.2 sec
[-----------------80%----------        ] 1610 of 2000 complete in 709.0 sec
[-----------------80%----------        ] 1612 of 2000 complete in 709.9 sec
[-----------------80%----------        ] 1614 of 2000 complete in 710.7 sec
[-----------------80%----------        ] 1616 of 2000 complete in 711.6 sec
[-----------------80%----------        ] 1618 of 2000 complete in 712.4 sec
[-----------------81%----------        ] 1620 of 2000 complete in 713.3 sec
[-----------------81%----------        ] 1622 of 2000 complete in 714.2 sec
[-----------------81%----------        ] 1624 of 2000 complete in 715.1 sec
[-----------------81%----------        ] 1626 of 2000 complete in 716.0 sec
[-----------------81%----------        ] 1628 of 2000 complete in 716.8 sec
[-----------------81%----------        ] 1630 of 2000 complete in 717.7 sec
[-----------------81%-----------       ] 1632 of 2000 complete in 718.5 sec
[-----------------81%-----------       ] 1634 of 2000 complete in 719.4 sec
[-----------------81%-----------       ] 1636 of 2000 complete in 720.2 sec
[-----------------81%-----------       ] 1638 of 2000 complete in 721.1 sec
[-----------------82%-----------       ] 1640 of 2000 complete in 722.0 sec
[-----------------82%-----------       ] 1642 of 2000 complete in 722.8 sec
[-----------------82%-----------       ] 1644 of 2000 complete in 723.6 sec
[-----------------82%-----------       ] 1646 of 2000 complete in 724.5 sec
[-----------------82%-----------       ] 1648 of 2000 complete in 725.3 sec
[-----------------82%-----------       ] 1650 of 2000 complete in 726.2 sec
[-----------------82%-----------       ] 1652 of 2000 complete in 727.1 sec
[-----------------82%-----------       ] 1654 of 2000 complete in 727.9 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 728.8 sec
[-----------------82%-----------       ] 1658 of 2000 complete in 729.6 sec
[-----------------83%-----------       ] 1660 of 2000 complete in 730.4 sec
[-----------------83%-----------       ] 1662 of 2000 complete in 731.3 sec
[-----------------83%-----------       ] 1664 of 2000 complete in 732.2 sec
[-----------------83%-----------       ] 1666 of 2000 complete in 733.1 sec
[-----------------83%-----------       ] 1668 of 2000 complete in 733.9 sec
[-----------------83%-----------       ] 1670 of 2000 complete in 734.8 sec
[-----------------83%-----------       ] 1672 of 2000 complete in 735.7 sec
[-----------------83%-----------       ] 1674 of 2000 complete in 736.6 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 737.4 sec
[-----------------83%-----------       ] 1678 of 2000 complete in 738.3 sec
[-----------------84%-----------       ] 1680 of 2000 complete in 739.1 sec
[-----------------84%-----------       ] 1682 of 2000 complete in 740.0 sec
[-----------------84%-----------       ] 1684 of 2000 complete in 740.8 sec
[-----------------84%------------      ] 1686 of 2000 complete in 741.7 sec
[-----------------84%------------      ] 1688 of 2000 complete in 742.6 sec
[-----------------84%------------      ] 1690 of 2000 complete in 743.4 sec
[-----------------73%--------          ] 1476 of 2000 complete in 653.9 sec
[-----------------73%--------          ] 1478 of 2000 complete in 654.8 sec
[-----------------74%--------          ] 1480 of 2000 complete in 655.6 sec
[-----------------74%--------          ] 1482 of 2000 complete in 656.5 sec
[-----------------74%--------          ] 1484 of 2000 complete in 657.4 sec
[-----------------74%--------          ] 1486 of 2000 complete in 658.2 sec
[-----------------74%--------          ] 1488 of 2000 complete in 659.1 sec
[-----------------74%--------          ] 1490 of 2000 complete in 659.9 sec
[-----------------74%--------          ] 1492 of 2000 complete in 660.8 sec
[-----------------74%--------          ] 1494 of 2000 complete in 661.6 sec
[-----------------74%--------          ] 1496 of 2000 complete in 662.5 sec
[-----------------74%--------          ] 1498 of 2000 complete in 663.4 sec
[-----------------75%--------          ] 1500 of 2000 complete in 664.2 sec
[-----------------75%--------          ] 1502 of 2000 complete in 665.1 sec
[-----------------75%--------          ] 1504 of 2000 complete in 666.0 sec
[-----------------75%--------          ] 1506 of 2000 complete in 666.8 sec
[-----------------75%--------          ] 1508 of 2000 complete in 667.7 sec
[-----------------75%--------          ] 1510 of 2000 complete in 668.6 sec
[-----------------75%--------          ] 1512 of 2000 complete in 669.5 sec
[-----------------75%--------          ] 1514 of 2000 complete in 670.5 sec
[-----------------75%--------          ] 1516 of 2000 complete in 671.4 sec
[-----------------75%--------          ] 1518 of 2000 complete in 672.3 sec
[-----------------76%--------          ] 1520 of 2000 complete in 673.1 sec
[-----------------76%--------          ] 1522 of 2000 complete in 674.0 sec
[-----------------76%--------          ] 1524 of 2000 complete in 674.9 sec
[-----------------76%--------          ] 1526 of 2000 complete in 675.8 sec
[-----------------76%---------         ] 1528 of 2000 complete in 676.6 sec
[-----------------76%---------         ] 1530 of 2000 complete in 677.4 sec
[-----------------76%---------         ] 1532 of 2000 complete in 678.3 sec
[-----------------76%---------         ] 1534 of 2000 complete in 679.2 sec
[-----------------76%---------         ] 1536 of 2000 complete in 680.0 sec
[-----------------76%---------         ] 1538 of 2000 complete in 680.9 sec
[-----------------77%---------         ] 1540 of 2000 complete in 681.8 sec
[-----------------77%---------         ] 1542 of 2000 complete in 682.7 sec
[-----------------77%---------         ] 1544 of 2000 complete in 683.7 sec
[-----------------77%---------         ] 1546 of 2000 complete in 684.5 sec
[-----------------77%---------         ] 1548 of 2000 complete in 685.4 sec
[-----------------77%---------         ] 1550 of 2000 complete in 686.3 sec
[-----------------77%---------         ] 1552 of 2000 complete in 687.2 sec
[-----------------77%---------         ] 1554 of 2000 complete in 688.1 sec
[-----------------77%---------         ] 1556 of 2000 complete in 689.0 sec
[-----------------77%---------         ] 1558 of 2000 complete in 689.9 sec
[-----------------78%---------         ] 1560 of 2000 complete in 690.8 sec
[-----------------78%---------         ] 1562 of 2000 complete in 691.6 sec
[-----------------78%---------         ] 1564 of 2000 complete in 692.5 sec
[-----------------78%---------         ] 1566 of 2000 complete in 693.4 sec
[-----------------78%---------         ] 1568 of 2000 complete in 694.2 sec
[-----------------78%---------         ] 1570 of 2000 complete in 695.1 sec
[-----------------78%---------         ] 1572 of 2000 complete in 696.0 sec
[-----------------78%---------         ] 1574 of 2000 complete in 696.9 sec
[-----------------78%---------         ] 1576 of 2000 complete in 697.7 sec
[-----------------78%---------         ] 1578 of 2000 complete in 698.6 sec
[-----------------79%----------        ] 1580 of 2000 complete in 699.5 sec
[-----------------79%----------        ] 1582 of 2000 complete in 700.3 sec
[-----------------79%----------        ] 1584 of 2000 complete in 701.2 sec
[-----------------79%----------        ] 1586 of 2000 complete in 702.1 sec
[-----------------79%----------        ] 1588 of 2000 complete in 702.9 sec
[-----------------79%----------        ] 1590 of 2000 complete in 703.8 sec
[-----------------79%----------        ] 1592 of 2000 complete in 704.6 sec
[-----------------79%----------        ] 1594 of 2000 complete in 705.5 sec
[-----------------79%----------        ] 1596 of 2000 complete in 706.3 sec
[-----------------79%----------        ] 1598 of 2000 complete in 707.2 sec
[-----------------80%----------        ] 1600 of 2000 complete in 708.0 sec
[-----------------80%----------        ] 1602 of 2000 complete in 708.9 sec
[-----------------80%----------        ] 1604 of 2000 complete in 709.7 sec
[-----------------80%----------        ] 1606 of 2000 complete in 710.6 sec
[-----------------80%----------        ] 1608 of 2000 complete in 711.5 sec
[-----------------80%----------        ] 1610 of 2000 complete in 712.3 sec
[-----------------80%----------        ] 1612 of 2000 complete in 713.3 sec
[-----------------80%----------        ] 1614 of 2000 complete in 714.1 sec
[-----------------80%----------        ] 1616 of 2000 complete in 715.0 sec
[-----------------80%----------        ] 1618 of 2000 complete in 715.9 sec
[-----------------81%----------        ] 1620 of 2000 complete in 716.7 sec
[-----------------81%----------        ] 1622 of 2000 complete in 717.6 sec
[-----------------81%----------        ] 1624 of 2000 complete in 718.5 sec
[-----------------81%----------        ] 1626 of 2000 complete in 719.3 sec
[-----------------81%----------        ] 1628 of 2000 complete in 720.2 sec
[-----------------81%----------        ] 1630 of 2000 complete in 721.0 sec
[-----------------81%-----------       ] 1632 of 2000 complete in 721.9 sec
[-----------------81%-----------       ] 1634 of 2000 complete in 722.7 sec
[-----------------81%-----------       ] 1636 of 2000 complete in 723.6 sec
[-----------------81%-----------       ] 1638 of 2000 complete in 724.4 sec
[-----------------82%-----------       ] 1640 of 2000 complete in 725.3 sec
[-----------------82%-----------       ] 1642 of 2000 complete in 726.1 sec
[-----------------82%-----------       ] 1644 of 2000 complete in 727.0 sec
[-----------------82%-----------       ] 1646 of 2000 complete in 727.8 sec
[-----------------82%-----------       ] 1648 of 2000 complete in 728.7 sec
[-----------------82%-----------       ] 1650 of 2000 complete in 729.5 sec
[-----------------82%-----------       ] 1652 of 2000 complete in 730.3 sec
[-----------------82%-----------       ] 1654 of 2000 complete in 731.2 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 732.0 sec
[-----------------82%-----------       ] 1658 of 2000 complete in 732.9 sec
[-----------------83%-----------       ] 1660 of 2000 complete in 733.7 sec
[-----------------83%-----------       ] 1662 of 2000 complete in 734.6 sec
[-----------------83%-----------       ] 1664 of 2000 complete in 735.4 sec
[-----------------83%-----------       ] 1666 of 2000 complete in 736.3 sec
[-----------------83%-----------       ] 1668 of 2000 complete in 737.1 sec
[-----------------83%-----------       ] 1670 of 2000 complete in 738.0 sec
[-----------------83%-----------       ] 1672 of 2000 complete in 738.8 sec
[-----------------83%-----------       ] 1674 of 2000 complete in 739.7 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 740.5 sec
[-----------------83%-----------       ] 1678 of 2000 complete in 741.4 sec
[-----------------84%-----------       ] 1680 of 2000 complete in 742.2 sec
[-----------------84%-----------       ] 1682 of 2000 complete in 743.0 sec
[-----------------84%-----------       ] 1684 of 2000 complete in 743.9 sec
[-----------------84%------------      ] 1686 of 2000 complete in 744.8 sec
[-----------------84%------------      ] 1688 of 2000 complete in 745.6 sec

[-----------------85%------------      ] 1702 of 2000 complete in 731.3 sec
[-----------------85%------------      ] 1704 of 2000 complete in 732.1 sec
[-----------------85%------------      ] 1706 of 2000 complete in 733.0 sec
[-----------------85%------------      ] 1708 of 2000 complete in 733.8 sec
[-----------------85%------------      ] 1710 of 2000 complete in 734.7 sec
[-----------------85%------------      ] 1712 of 2000 complete in 735.5 sec
[-----------------85%------------      ] 1714 of 2000 complete in 736.3 sec
[-----------------85%------------      ] 1716 of 2000 complete in 737.2 sec
[-----------------85%------------      ] 1718 of 2000 complete in 738.0 sec
[-----------------86%------------      ] 1720 of 2000 complete in 738.8 sec
[-----------------86%------------      ] 1722 of 2000 complete in 739.6 sec
[-----------------86%------------      ] 1724 of 2000 complete in 740.5 sec
[-----------------86%------------      ] 1726 of 2000 complete in 741.3 sec
[-----------------86%------------      ] 1728 of 2000 complete in 742.1 sec
[-----------------86%------------      ] 1730 of 2000 complete in 742.9 sec
[-----------------86%------------      ] 1732 of 2000 complete in 743.8 sec
[-----------------86%------------      ] 1734 of 2000 complete in 744.6 sec
[-----------------86%------------      ] 1736 of 2000 complete in 745.4 sec
[-----------------86%-------------     ] 1738 of 2000 complete in 746.3 sec
[-----------------87%-------------     ] 1740 of 2000 complete in 747.1 sec
[-----------------87%-------------     ] 1742 of 2000 complete in 747.9 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 748.8 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 749.6 sec
[-----------------87%-------------     ] 1748 of 2000 complete in 750.5 sec
[-----------------87%-------------     ] 1750 of 2000 complete in 751.3 sec
[-----------------87%-------------     ] 1752 of 2000 complete in 752.2 sec
[-----------------87%-------------     ] 1754 of 2000 complete in 753.0 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 753.8 sec
[-----------------87%-------------     ] 1758 of 2000 complete in 754.6 sec
[-----------------88%-------------     ] 1760 of 2000 complete in 755.4 sec
[-----------------88%-------------     ] 1762 of 2000 complete in 756.3 sec
[-----------------88%-------------     ] 1764 of 2000 complete in 757.1 sec
[-----------------88%-------------     ] 1766 of 2000 complete in 757.9 sec
[-----------------88%-------------     ] 1768 of 2000 complete in 758.8 sec
[-----------------88%-------------     ] 1770 of 2000 complete in 759.6 sec
[-----------------88%-------------     ] 1772 of 2000 complete in 760.5 sec
[-----------------88%-------------     ] 1774 of 2000 complete in 761.2 sec
[-----------------88%-------------     ] 1776 of 2000 complete in 762.1 sec
[-----------------88%-------------     ] 1778 of 2000 complete in 762.9 sec
[-----------------89%-------------     ] 1780 of 2000 complete in 763.7 sec
[-----------------89%-------------     ] 1782 of 2000 complete in 764.6 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 765.4 sec
[-----------------89%-------------     ] 1786 of 2000 complete in 766.2 sec
[-----------------89%-------------     ] 1788 of 2000 complete in 767.1 sec
[-----------------89%--------------    ] 1790 of 2000 complete in 767.9 sec
[-----------------89%--------------    ] 1792 of 2000 complete in 768.8 sec
[-----------------89%--------------    ] 1794 of 2000 complete in 769.6 sec
[-----------------89%--------------    ] 1796 of 2000 complete in 770.4 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 771.2 sec
[-----------------90%--------------    ] 1800 of 2000 complete in 772.0 sec
[-----------------90%--------------    ] 1802 of 2000 complete in 772.9 sec
[-----------------90%--------------    ] 1804 of 2000 complete in 773.7 sec
[-----------------90%--------------    ] 1806 of 2000 complete in 774.5 sec
[-----------------90%--------------    ] 1808 of 2000 complete in 775.4 sec
[-----------------90%--------------    ] 1810 of 2000 complete in 776.2 sec
[-----------------90%--------------    ] 1812 of 2000 complete in 777.1 sec
[-----------------90%--------------    ] 1814 of 2000 complete in 778.0 sec
[-----------------90%--------------    ] 1816 of 2000 complete in 778.8 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 779.6 sec
[-----------------91%--------------    ] 1820 of 2000 complete in 780.4 sec
[-----------------91%--------------    ] 1822 of 2000 complete in 781.3 sec
[-----------------91%--------------    ] 1824 of 2000 complete in 782.1 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 782.9 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 783.8 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 784.6 sec
[-----------------91%--------------    ] 1832 of 2000 complete in 785.4 sec
[-----------------91%--------------    ] 1834 of 2000 complete in 786.3 sec
[-----------------91%--------------    ] 1836 of 2000 complete in 787.1 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 787.9 sec
[-----------------92%--------------    ] 1840 of 2000 complete in 788.7 sec
[-----------------92%--------------    ] 1842 of 2000 complete in 789.6 sec
[-----------------92%---------------   ] 1844 of 2000 complete in 790.4 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 791.2 sec
[-----------------92%---------------   ] 1848 of 2000 complete in 792.1 sec
[-----------------92%---------------   ] 1850 of 2000 complete in 792.9 sec
[-----------------92%---------------   ] 1852 of 2000 complete in 793.7 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 794.5 sec
[-----------------92%---------------   ] 1856 of 2000 complete in 795.4 sec
[-----------------92%---------------   ] 1858 of 2000 complete in 796.2 sec
[-----------------93%---------------   ] 1860 of 2000 complete in 797.1 sec
[-----------------93%---------------   ] 1862 of 2000 complete in 797.9 sec
[-----------------93%---------------   ] 1864 of 2000 complete in 798.8 sec
[-----------------93%---------------   ] 1866 of 2000 complete in 799.6 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 800.4 sec
[-----------------93%---------------   ] 1870 of 2000 complete in 801.3 sec
[-----------------93%---------------   ] 1872 of 2000 complete in 802.1 sec
[-----------------93%---------------   ] 1874 of 2000 complete in 802.9 sec
[-----------------93%---------------   ] 1876 of 2000 complete in 803.7 sec
[-----------------93%---------------   ] 1878 of 2000 complete in 804.6 sec
[-----------------94%---------------   ] 1880 of 2000 complete in 805.4 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 806.2 sec
[-----------------94%---------------   ] 1884 of 2000 complete in 807.0 sec
[-----------------94%---------------   ] 1886 of 2000 complete in 807.9 sec
[-----------------94%---------------   ] 1888 of 2000 complete in 808.7 sec
[-----------------94%---------------   ] 1890 of 2000 complete in 809.5 sec
[-----------------94%---------------   ] 1892 of 2000 complete in 810.4 sec
[-----------------94%---------------   ] 1894 of 2000 complete in 811.2 sec
[-----------------94%----------------  ] 1896 of 2000 complete in 812.0 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 812.8 sec
[-----------------95%----------------  ] 1900 of 2000 complete in 813.6 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 814.5 sec
[-----------------95%----------------  ] 1904 of 2000 complete in 815.4 sec
[-----------------95%----------------  ] 1906 of 2000 complete in 816.3 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 817.1 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 818.0 sec
[-----------------95%----------------  ] 1911 of 2000 complete in 818.6 sec
[-----------------95%----------------  ] 1913 of 2000 complete in 819.5 sec
[-----------------84%------------      ] 1693 of 2000 complete in 731.7 sec
[-----------------84%------------      ] 1695 of 2000 complete in 732.6 sec
[-----------------84%------------      ] 1697 of 2000 complete in 733.4 sec
[-----------------84%------------      ] 1699 of 2000 complete in 734.2 sec
[-----------------85%------------      ] 1701 of 2000 complete in 735.0 sec
[-----------------85%------------      ] 1703 of 2000 complete in 735.8 sec
[-----------------85%------------      ] 1705 of 2000 complete in 736.6 sec
[-----------------85%------------      ] 1707 of 2000 complete in 737.5 sec
[-----------------85%------------      ] 1709 of 2000 complete in 738.3 sec
[-----------------85%------------      ] 1711 of 2000 complete in 739.1 sec
[-----------------85%------------      ] 1713 of 2000 complete in 739.9 sec
[-----------------85%------------      ] 1715 of 2000 complete in 740.8 sec
[-----------------85%------------      ] 1717 of 2000 complete in 741.6 sec
[-----------------85%------------      ] 1719 of 2000 complete in 742.4 sec
[-----------------86%------------      ] 1721 of 2000 complete in 743.3 sec
[-----------------86%------------      ] 1723 of 2000 complete in 744.1 sec
[-----------------86%------------      ] 1725 of 2000 complete in 744.9 sec
[-----------------86%------------      ] 1727 of 2000 complete in 745.8 sec
[-----------------86%------------      ] 1729 of 2000 complete in 746.6 sec
[-----------------86%------------      ] 1731 of 2000 complete in 747.4 sec
[-----------------86%------------      ] 1733 of 2000 complete in 748.3 sec
[-----------------86%------------      ] 1735 of 2000 complete in 749.2 sec
[-----------------86%-------------     ] 1737 of 2000 complete in 750.0 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 750.8 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 751.6 sec
[-----------------87%-------------     ] 1743 of 2000 complete in 752.5 sec
[-----------------87%-------------     ] 1745 of 2000 complete in 753.3 sec
[-----------------87%-------------     ] 1747 of 2000 complete in 754.1 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 755.0 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 755.8 sec
[-----------------87%-------------     ] 1753 of 2000 complete in 756.7 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 757.5 sec
[-----------------87%-------------     ] 1757 of 2000 complete in 758.3 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 759.2 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 760.0 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 760.8 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 761.7 sec
[-----------------88%-------------     ] 1767 of 2000 complete in 762.5 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 763.3 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 764.2 sec
[-----------------88%-------------     ] 1773 of 2000 complete in 765.0 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 765.8 sec
[-----------------88%-------------     ] 1777 of 2000 complete in 766.7 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 767.5 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 768.4 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 769.2 sec
[-----------------89%-------------     ] 1785 of 2000 complete in 770.0 sec
[-----------------89%-------------     ] 1787 of 2000 complete in 770.9 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 771.7 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 772.5 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 773.3 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 774.2 sec
[-----------------89%--------------    ] 1797 of 2000 complete in 775.0 sec
[-----------------89%--------------    ] 1799 of 2000 complete in 775.9 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 776.8 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 777.6 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 778.5 sec
[-----------------90%--------------    ] 1807 of 2000 complete in 779.3 sec
[-----------------90%--------------    ] 1809 of 2000 complete in 780.2 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 781.0 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 781.8 sec
[-----------------90%--------------    ] 1815 of 2000 complete in 782.7 sec
[-----------------90%--------------    ] 1817 of 2000 complete in 783.5 sec
[-----------------90%--------------    ] 1819 of 2000 complete in 784.4 sec
[-----------------91%--------------    ] 1821 of 2000 complete in 785.2 sec
[-----------------91%--------------    ] 1823 of 2000 complete in 786.1 sec
[-----------------91%--------------    ] 1825 of 2000 complete in 787.0 sec
[-----------------91%--------------    ] 1827 of 2000 complete in 787.8 sec
[-----------------91%--------------    ] 1829 of 2000 complete in 788.6 sec
[-----------------91%--------------    ] 1831 of 2000 complete in 789.4 sec
[-----------------91%--------------    ] 1833 of 2000 complete in 790.3 sec
[-----------------91%--------------    ] 1835 of 2000 complete in 791.2 sec
[-----------------91%--------------    ] 1837 of 2000 complete in 792.0 sec
[-----------------91%--------------    ] 1839 of 2000 complete in 792.9 sec
[-----------------92%--------------    ] 1841 of 2000 complete in 793.7 sec
[-----------------92%---------------   ] 1843 of 2000 complete in 794.6 sec
[-----------------92%---------------   ] 1845 of 2000 complete in 795.4 sec
[-----------------92%---------------   ] 1847 of 2000 complete in 796.3 sec
[-----------------92%---------------   ] 1849 of 2000 complete in 797.1 sec
[-----------------92%---------------   ] 1851 of 2000 complete in 798.0 sec
[-----------------92%---------------   ] 1853 of 2000 complete in 798.8 sec
[-----------------92%---------------   ] 1855 of 2000 complete in 799.7 sec
[-----------------92%---------------   ] 1857 of 2000 complete in 800.5 sec
[-----------------92%---------------   ] 1859 of 2000 complete in 801.3 sec
[-----------------93%---------------   ] 1861 of 2000 complete in 802.2 sec
[-----------------93%---------------   ] 1863 of 2000 complete in 803.0 sec
[-----------------93%---------------   ] 1865 of 2000 complete in 803.8 sec
[-----------------93%---------------   ] 1867 of 2000 complete in 804.7 sec
[-----------------93%---------------   ] 1869 of 2000 complete in 805.5 sec
[-----------------93%---------------   ] 1871 of 2000 complete in 806.3 sec
[-----------------93%---------------   ] 1873 of 2000 complete in 807.2 sec
[-----------------93%---------------   ] 1875 of 2000 complete in 808.0 sec
[-----------------93%---------------   ] 1877 of 2000 complete in 808.9 sec
[-----------------93%---------------   ] 1879 of 2000 complete in 809.7 sec
[-----------------94%---------------   ] 1881 of 2000 complete in 810.5 sec
[-----------------94%---------------   ] 1883 of 2000 complete in 811.3 sec
[-----------------94%---------------   ] 1885 of 2000 complete in 812.2 sec
[-----------------94%---------------   ] 1887 of 2000 complete in 813.0 sec
[-----------------94%---------------   ] 1889 of 2000 complete in 813.8 sec
[-----------------94%---------------   ] 1891 of 2000 complete in 814.7 sec
[-----------------94%---------------   ] 1893 of 2000 complete in 815.5 sec
[-----------------94%----------------  ] 1895 of 2000 complete in 816.4 sec
[-----------------94%----------------  ] 1897 of 2000 complete in 817.3 sec
[-----------------94%----------------  ] 1899 of 2000 complete in 818.2 sec
[-----------------95%----------------  ] 1901 of 2000 complete in 819.1 sec
[-----------------95%----------------  ] 1903 of 2000 complete in 820.0 sec
[-----------------95%----------------  ] 1905 of 2000 complete in 820.9 sec

[-----------------84%------------      ] 1692 of 2000 complete in 744.3 sec
[-----------------84%------------      ] 1694 of 2000 complete in 745.1 sec
[-----------------84%------------      ] 1696 of 2000 complete in 746.0 sec
[-----------------84%------------      ] 1698 of 2000 complete in 746.9 sec
[-----------------85%------------      ] 1700 of 2000 complete in 747.7 sec
[-----------------85%------------      ] 1702 of 2000 complete in 748.6 sec
[-----------------85%------------      ] 1704 of 2000 complete in 749.5 sec
[-----------------85%------------      ] 1706 of 2000 complete in 750.3 sec
[-----------------85%------------      ] 1708 of 2000 complete in 751.2 sec
[-----------------85%------------      ] 1710 of 2000 complete in 752.0 sec
[-----------------85%------------      ] 1712 of 2000 complete in 752.9 sec
[-----------------85%------------      ] 1714 of 2000 complete in 753.8 sec
[-----------------85%------------      ] 1716 of 2000 complete in 754.6 sec
[-----------------85%------------      ] 1718 of 2000 complete in 755.5 sec
[-----------------86%------------      ] 1720 of 2000 complete in 756.4 sec
[-----------------86%------------      ] 1722 of 2000 complete in 757.2 sec
[-----------------86%------------      ] 1724 of 2000 complete in 758.0 sec
[-----------------86%------------      ] 1726 of 2000 complete in 758.9 sec
[-----------------86%------------      ] 1728 of 2000 complete in 759.7 sec
[-----------------86%------------      ] 1730 of 2000 complete in 760.6 sec
[-----------------86%------------      ] 1732 of 2000 complete in 761.5 sec
[-----------------86%------------      ] 1734 of 2000 complete in 762.3 sec
[-----------------86%------------      ] 1736 of 2000 complete in 763.2 sec
[-----------------86%-------------     ] 1738 of 2000 complete in 764.0 sec
[-----------------87%-------------     ] 1740 of 2000 complete in 764.9 sec
[-----------------87%-------------     ] 1742 of 2000 complete in 765.8 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 766.6 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 767.5 sec
[-----------------87%-------------     ] 1748 of 2000 complete in 768.3 sec
[-----------------87%-------------     ] 1750 of 2000 complete in 769.2 sec
[-----------------87%-------------     ] 1752 of 2000 complete in 770.0 sec
[-----------------87%-------------     ] 1754 of 2000 complete in 770.9 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 771.7 sec
[-----------------87%-------------     ] 1758 of 2000 complete in 772.6 sec
[-----------------88%-------------     ] 1760 of 2000 complete in 773.5 sec
[-----------------88%-------------     ] 1762 of 2000 complete in 774.3 sec
[-----------------88%-------------     ] 1764 of 2000 complete in 775.2 sec
[-----------------88%-------------     ] 1766 of 2000 complete in 776.0 sec
[-----------------88%-------------     ] 1768 of 2000 complete in 776.9 sec
[-----------------88%-------------     ] 1770 of 2000 complete in 777.8 sec
[-----------------88%-------------     ] 1772 of 2000 complete in 778.6 sec
[-----------------88%-------------     ] 1774 of 2000 complete in 779.5 sec
[-----------------88%-------------     ] 1776 of 2000 complete in 780.4 sec
[-----------------88%-------------     ] 1778 of 2000 complete in 781.2 sec
[-----------------89%-------------     ] 1780 of 2000 complete in 782.1 sec
[-----------------89%-------------     ] 1782 of 2000 complete in 783.0 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 783.8 sec
[-----------------89%-------------     ] 1786 of 2000 complete in 784.7 sec
[-----------------89%-------------     ] 1788 of 2000 complete in 785.5 sec
[-----------------89%--------------    ] 1790 of 2000 complete in 786.3 sec
[-----------------89%--------------    ] 1792 of 2000 complete in 787.2 sec
[-----------------89%--------------    ] 1794 of 2000 complete in 788.1 sec
[-----------------89%--------------    ] 1796 of 2000 complete in 788.9 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 789.8 sec
[-----------------90%--------------    ] 1800 of 2000 complete in 790.6 sec
[-----------------90%--------------    ] 1802 of 2000 complete in 791.5 sec
[-----------------90%--------------    ] 1804 of 2000 complete in 792.4 sec
[-----------------90%--------------    ] 1806 of 2000 complete in 793.2 sec
[-----------------90%--------------    ] 1808 of 2000 complete in 794.1 sec
[-----------------90%--------------    ] 1810 of 2000 complete in 795.0 sec
[-----------------90%--------------    ] 1812 of 2000 complete in 795.8 sec
[-----------------90%--------------    ] 1814 of 2000 complete in 796.7 sec
[-----------------90%--------------    ] 1816 of 2000 complete in 797.5 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 798.4 sec
[-----------------91%--------------    ] 1820 of 2000 complete in 799.2 sec
[-----------------91%--------------    ] 1822 of 2000 complete in 800.1 sec
[-----------------91%--------------    ] 1824 of 2000 complete in 801.0 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 801.8 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 802.7 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 803.5 sec
[-----------------91%--------------    ] 1832 of 2000 complete in 804.4 sec
[-----------------91%--------------    ] 1834 of 2000 complete in 805.2 sec
[-----------------91%--------------    ] 1836 of 2000 complete in 806.1 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 807.0 sec
[-----------------92%--------------    ] 1840 of 2000 complete in 807.8 sec
[-----------------92%--------------    ] 1842 of 2000 complete in 808.7 sec
[-----------------92%---------------   ] 1844 of 2000 complete in 809.6 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 810.4 sec
[-----------------92%---------------   ] 1848 of 2000 complete in 811.3 sec
[-----------------92%---------------   ] 1850 of 2000 complete in 812.2 sec
[-----------------92%---------------   ] 1852 of 2000 complete in 813.0 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 813.9 sec
[-----------------92%---------------   ] 1856 of 2000 complete in 814.8 sec
[-----------------92%---------------   ] 1858 of 2000 complete in 815.7 sec
[-----------------93%---------------   ] 1860 of 2000 complete in 816.6 sec
[-----------------93%---------------   ] 1862 of 2000 complete in 817.4 sec
[-----------------93%---------------   ] 1864 of 2000 complete in 818.4 sec
[-----------------93%---------------   ] 1866 of 2000 complete in 819.3 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 820.3 sec
[-----------------93%---------------   ] 1870 of 2000 complete in 821.1 sec
[-----------------93%---------------   ] 1872 of 2000 complete in 822.0 sec
[-----------------93%---------------   ] 1874 of 2000 complete in 822.8 sec
[-----------------93%---------------   ] 1876 of 2000 complete in 823.7 sec
[-----------------93%---------------   ] 1878 of 2000 complete in 824.6 sec
[-----------------94%---------------   ] 1880 of 2000 complete in 825.5 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 826.3 sec
[-----------------94%---------------   ] 1884 of 2000 complete in 827.1 sec
[-----------------94%---------------   ] 1886 of 2000 complete in 828.0 sec
[-----------------94%---------------   ] 1888 of 2000 complete in 828.9 sec
[-----------------94%---------------   ] 1890 of 2000 complete in 829.8 sec
[-----------------94%---------------   ] 1892 of 2000 complete in 830.7 sec
[-----------------94%---------------   ] 1894 of 2000 complete in 831.6 sec
[-----------------94%----------------  ] 1896 of 2000 complete in 832.5 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 833.3 sec
[-----------------95%----------------  ] 1900 of 2000 complete in 834.1 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 835.0 sec
[-----------------95%----------------  ] 1904 of 2000 complete in 835.9 sec
[-----------------84%------------      ] 1690 of 2000 complete in 746.5 sec
[-----------------84%------------      ] 1692 of 2000 complete in 747.4 sec
[-----------------84%------------      ] 1694 of 2000 complete in 748.2 sec
[-----------------84%------------      ] 1696 of 2000 complete in 749.1 sec
[-----------------84%------------      ] 1698 of 2000 complete in 749.9 sec
[-----------------85%------------      ] 1700 of 2000 complete in 750.8 sec
[-----------------85%------------      ] 1702 of 2000 complete in 751.7 sec
[-----------------85%------------      ] 1704 of 2000 complete in 752.5 sec
[-----------------85%------------      ] 1706 of 2000 complete in 753.4 sec
[-----------------85%------------      ] 1708 of 2000 complete in 754.2 sec
[-----------------85%------------      ] 1710 of 2000 complete in 755.1 sec
[-----------------85%------------      ] 1712 of 2000 complete in 755.9 sec
[-----------------85%------------      ] 1714 of 2000 complete in 756.8 sec
[-----------------85%------------      ] 1716 of 2000 complete in 757.7 sec
[-----------------85%------------      ] 1718 of 2000 complete in 758.5 sec
[-----------------86%------------      ] 1720 of 2000 complete in 759.4 sec
[-----------------86%------------      ] 1722 of 2000 complete in 760.2 sec
[-----------------86%------------      ] 1724 of 2000 complete in 761.1 sec
[-----------------86%------------      ] 1726 of 2000 complete in 762.0 sec
[-----------------86%------------      ] 1728 of 2000 complete in 762.8 sec
[-----------------86%------------      ] 1730 of 2000 complete in 763.6 sec
[-----------------86%------------      ] 1732 of 2000 complete in 764.5 sec
[-----------------86%------------      ] 1734 of 2000 complete in 765.3 sec
[-----------------86%------------      ] 1736 of 2000 complete in 766.2 sec
[-----------------86%-------------     ] 1738 of 2000 complete in 767.0 sec
[-----------------87%-------------     ] 1740 of 2000 complete in 767.9 sec
[-----------------87%-------------     ] 1742 of 2000 complete in 768.7 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 769.6 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 770.4 sec
[-----------------87%-------------     ] 1748 of 2000 complete in 771.3 sec
[-----------------87%-------------     ] 1750 of 2000 complete in 772.1 sec
[-----------------87%-------------     ] 1752 of 2000 complete in 773.0 sec
[-----------------87%-------------     ] 1754 of 2000 complete in 773.8 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 774.7 sec
[-----------------87%-------------     ] 1758 of 2000 complete in 775.5 sec
[-----------------88%-------------     ] 1760 of 2000 complete in 776.4 sec
[-----------------88%-------------     ] 1762 of 2000 complete in 777.3 sec
[-----------------88%-------------     ] 1764 of 2000 complete in 778.1 sec
[-----------------88%-------------     ] 1766 of 2000 complete in 779.0 sec
[-----------------88%-------------     ] 1768 of 2000 complete in 779.8 sec
[-----------------88%-------------     ] 1770 of 2000 complete in 780.7 sec
[-----------------88%-------------     ] 1772 of 2000 complete in 781.6 sec
[-----------------88%-------------     ] 1774 of 2000 complete in 782.4 sec
[-----------------88%-------------     ] 1776 of 2000 complete in 783.3 sec
[-----------------88%-------------     ] 1778 of 2000 complete in 784.2 sec
[-----------------89%-------------     ] 1780 of 2000 complete in 785.0 sec
[-----------------89%-------------     ] 1782 of 2000 complete in 785.9 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 786.7 sec
[-----------------89%-------------     ] 1786 of 2000 complete in 787.6 sec
[-----------------89%-------------     ] 1788 of 2000 complete in 788.5 sec
[-----------------89%--------------    ] 1790 of 2000 complete in 789.3 sec
[-----------------89%--------------    ] 1792 of 2000 complete in 790.1 sec
[-----------------89%--------------    ] 1794 of 2000 complete in 791.0 sec
[-----------------89%--------------    ] 1796 of 2000 complete in 791.8 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 792.7 sec
[-----------------90%--------------    ] 1800 of 2000 complete in 793.6 sec
[-----------------90%--------------    ] 1802 of 2000 complete in 794.5 sec
[-----------------90%--------------    ] 1804 of 2000 complete in 795.4 sec
[-----------------90%--------------    ] 1806 of 2000 complete in 796.2 sec
[-----------------90%--------------    ] 1808 of 2000 complete in 797.1 sec
[-----------------90%--------------    ] 1810 of 2000 complete in 797.9 sec
[-----------------90%--------------    ] 1812 of 2000 complete in 798.8 sec
[-----------------90%--------------    ] 1814 of 2000 complete in 799.6 sec
[-----------------90%--------------    ] 1816 of 2000 complete in 800.5 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 801.4 sec
[-----------------91%--------------    ] 1820 of 2000 complete in 802.2 sec
[-----------------91%--------------    ] 1822 of 2000 complete in 803.1 sec
[-----------------91%--------------    ] 1824 of 2000 complete in 803.9 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 804.8 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 805.7 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 806.5 sec
[-----------------91%--------------    ] 1832 of 2000 complete in 807.4 sec
[-----------------91%--------------    ] 1834 of 2000 complete in 808.2 sec
[-----------------91%--------------    ] 1836 of 2000 complete in 809.1 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 809.9 sec
[-----------------92%--------------    ] 1840 of 2000 complete in 810.8 sec
[-----------------92%--------------    ] 1842 of 2000 complete in 811.7 sec
[-----------------92%---------------   ] 1844 of 2000 complete in 812.5 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 813.4 sec
[-----------------92%---------------   ] 1848 of 2000 complete in 814.3 sec
[-----------------92%---------------   ] 1850 of 2000 complete in 815.1 sec
[-----------------92%---------------   ] 1852 of 2000 complete in 816.0 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 816.9 sec
[-----------------92%---------------   ] 1856 of 2000 complete in 817.8 sec
[-----------------92%---------------   ] 1858 of 2000 complete in 818.8 sec
[-----------------93%---------------   ] 1860 of 2000 complete in 819.6 sec
[-----------------93%---------------   ] 1862 of 2000 complete in 820.5 sec
[-----------------93%---------------   ] 1864 of 2000 complete in 821.4 sec
[-----------------93%---------------   ] 1866 of 2000 complete in 822.3 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 823.2 sec
[-----------------93%---------------   ] 1870 of 2000 complete in 824.0 sec
[-----------------93%---------------   ] 1872 of 2000 complete in 824.9 sec
[-----------------93%---------------   ] 1874 of 2000 complete in 825.7 sec
[-----------------93%---------------   ] 1876 of 2000 complete in 826.6 sec
[-----------------93%---------------   ] 1878 of 2000 complete in 827.4 sec
[-----------------94%---------------   ] 1880 of 2000 complete in 828.3 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 829.2 sec
[-----------------94%---------------   ] 1884 of 2000 complete in 830.1 sec
[-----------------94%---------------   ] 1886 of 2000 complete in 831.0 sec
[-----------------94%---------------   ] 1888 of 2000 complete in 831.9 sec
[-----------------94%---------------   ] 1890 of 2000 complete in 832.8 sec
[-----------------94%---------------   ] 1892 of 2000 complete in 833.6 sec
[-----------------94%---------------   ] 1894 of 2000 complete in 834.5 sec
[-----------------94%----------------  ] 1896 of 2000 complete in 835.3 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 836.2 sec
[-----------------95%----------------  ] 1900 of 2000 complete in 837.1 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 837.9 sec

hddm sampling elpased time:  900.871 s
Start converting to InferenceData...
[-----------------95%----------------  ] 1915 of 2000 complete in 820.3 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 821.2 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 822.0 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 822.9 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 823.7 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 824.5 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 825.4 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 826.2 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 827.0 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 827.8 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 828.7 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 829.6 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 830.5 sec
[-----------------97%----------------  ] 1941 of 2000 complete in 831.3 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 832.2 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 833.0 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 833.8 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 834.6 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 835.5 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 836.3 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 837.1 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 837.9 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 838.8 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 839.6 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 840.4 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 841.3 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 842.2 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 843.0 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 843.8 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 844.7 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 845.5 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 846.3 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 847.2 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 848.1 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 848.9 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 849.8 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 850.6 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 851.5 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 852.4 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 853.2 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 854.1 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 854.9 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 855.8 sec
[-----------------100%-----------------] 2001 of 2000 complete in 856.6 sec
hddm sampling elpased time:  856.755 s
[-----------------95%----------------  ] 1907 of 2000 complete in 821.7 sec
[-----------------95%----------------  ] 1909 of 2000 complete in 822.6 sec
[-----------------95%----------------  ] 1911 of 2000 complete in 823.4 sec
[-----------------95%----------------  ] 1913 of 2000 complete in 824.3 sec
[-----------------95%----------------  ] 1915 of 2000 complete in 825.1 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 825.9 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 826.7 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 827.6 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 828.5 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 829.4 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 830.2 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 831.1 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 832.0 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 832.8 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 833.6 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 834.4 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 835.3 sec
[-----------------97%----------------  ] 1941 of 2000 complete in 836.1 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 837.0 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 837.8 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 838.6 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 839.5 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 840.3 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 841.1 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 842.0 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 842.8 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 843.7 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 844.5 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 845.4 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 846.2 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 847.1 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 847.9 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 848.7 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 849.6 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 850.4 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 851.3 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 852.3 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 853.1 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 853.9 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 854.8 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 855.6 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 856.4 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 857.3 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 858.2 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 859.0 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 859.9 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 860.7 sec
[-----------------100%-----------------] 2001 of 2000 complete in 861.6 sec
hddm sampling elpased time:  861.762 s
[-----------------95%----------------  ] 1906 of 2000 complete in 836.7 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 837.6 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 838.5 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 839.3 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 840.2 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 841.0 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 841.9 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 842.7 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 843.6 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 844.5 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 845.3 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 846.2 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 847.1 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 848.0 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 848.8 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 849.7 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 850.6 sec
[-----------------97%----------------  ] 1940 of 2000 complete in 851.5 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 852.3 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 853.2 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 854.1 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 855.0 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 855.8 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 856.7 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 857.6 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 858.5 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 859.4 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 860.2 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 861.2 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 862.1 sec
[-----------------98%----------------- ] 1966 of 2000 complete in 863.0 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 863.9 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 864.4 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 865.3 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 866.1 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 866.9 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 867.7 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 868.5 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 869.3 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 870.1 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 870.9 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 871.7 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 872.6 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 873.4 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 874.2 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 875.1 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 875.9 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 876.7 sec
[-----------------100%-----------------] 2001 of 2000 complete in 877.5 sec
hddm sampling elpased time:  877.616 s

[-----------------95%----------------  ] 1904 of 2000 complete in 838.8 sec
[-----------------95%----------------  ] 1906 of 2000 complete in 839.6 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 840.5 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 841.3 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 842.2 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 843.1 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 843.9 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 844.7 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 845.6 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 846.4 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 847.4 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 848.3 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 849.1 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 849.9 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 850.8 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 851.7 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 852.6 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 853.5 sec
[-----------------97%----------------  ] 1940 of 2000 complete in 854.3 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 855.2 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 856.0 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 856.9 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 857.4 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 858.3 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 859.1 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 860.0 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 860.9 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 861.8 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 862.6 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 863.5 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 864.5 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 865.3 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 866.1 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 866.9 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 867.7 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 868.6 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 869.3 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 870.1 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 870.9 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 871.8 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 872.6 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 873.4 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 874.2 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 875.0 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 875.8 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 876.6 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 877.4 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 878.3 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 879.1 sec
[-----------------100%-----------------] 2001 of 2000 complete in 879.9 sec
hddm sampling elpased time:  879.991 s

In [34]:
az.summary(hddmReg_id_m2_choice_diff_idata)

,mean,sd,hdi_3%,hdi_97%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
a,1.968,0.173,1.650,2.276,0.035,0.025,25.0,138.0,1.11
a_std,0.908,0.166,0.614,1.216,0.038,0.027,19.0,161.0,1.14
a_subj.7304,1.544,0.221,1.308,1.754,0.047,0.035,124.0,26.0,1.03
a_subj.7305,1.736,0.102,1.557,1.926,0.004,0.003,792.0,986.0,1.01
a_subj.7306,1.395,0.082,1.246,1.545,0.003,0.002,750.0,1533.0,1.00
...,...,...,...,...,...,...,...,...,...
v_Intercept_subj(Self).7342,2.370,0.208,2.002,2.786,0.004,0.003,2318.0,3377.0,1.00
v_Intercept_subj(Self).7343,2.883,0.843,2.048,5.252,0.356,0.268,14.0,12.0,1.21
v_Intercept_subj(Self).7344,2.577,0.237,2.120,3.008,0.005,0.003,2420.0,3518.0,1.00
v_Intercept_subj(Self).7345,3.027,0.249,2.536,3.485,0.005,0.004,2494.0,3418.0,1.00
v_Intercept_subj(Self).73370,4.374,0.373,3.652,5.046,0.030,0.021,159.0,298.0,1.02

In [36]:
hddmReg_id_m2_choice_stats = hddmReg_id_m2_choice_diff.gen_stats()
hddmReg_id_m2_choice_stats[hddmReg_id_m2_choice_stats.index.isin(['a', 'z', 'v_Intercept(Self)','v_Intercept(Other)'])]

,mean,std,2.5q,25q,50q,75q,97.5q,mc err
a,1.968085,0.172523,1.675615,1.845118,1.953353,2.073132,2.355533,0.009811
z,0.543061,0.006205,0.530645,0.538928,0.543043,0.547226,0.555018,0.000279
v_Intercept(Other),-3.409962,0.213349,-3.834029,-3.553628,-3.403465,-3.263869,-3.000773,0.008124
v_Intercept(Self),3.290579,0.215212,2.882421,3.139984,3.288873,3.43277,3.730672,0.008268

In [39]:
#hddmReg_stim_v_flip
#type1：reg
# using stim coding with HDDMRegressor
# type1: choice coding + v flip +dc

data['response'] = data['choice']

# recode stimulus and apply parameter flipping
data['stim2'] = data['stim'].map({1: 1, 0: -1})

v_reg = [{'model': "v ~ 1 + id*stim2", 'link_func': lambda x: x}] 


hddmReg_stim_vflip_dc_m2 = hddm.HDDMRegressor(
    data,
    v_reg,
    bias=True,
    include=['v', 'a', 't', 'z'],
    depends_on={'v': ['id']},
    group_only_regressors=False
)

hddmReg_stim_vflip_dc_m2_idata = hddmReg_stim_vflip_dc_m2.sample(2000, burn=500, chains=4, return_infdata=True, dbname = 'hddmReg_stim_vflip_dc_m2.db', db = 'pickle')
hddmReg_stim_vflip_dc_m2.save('hddmReg_stim_vflip_dc_m2.hddm')

No model attribute --> setting up standard HDDM
Set model to ddm

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

[                  0%                  ] 2 of 2000 complete in 1.6 sec
[                  0%                  ] 3 of 2000 complete in 3.2 sec
[                  0%                  ] 4 of 2000 complete in 4.4 sec
[                  0%                  ] 5 of 2000 complete in 5.6 sec
[                  0%                  ] 6 of 2000 complete in 6.7 sec
[                  0%                  ] 7 of 2000 complete in 7.9 sec
[                  0%                  ] 8 of 2000 complete in 9.0 sec
[                  0%                  ] 9 of 2000 complete in 10.1 sec
[                  0%                  ] 10 of 2000 complete in 11.2 sec
[                  0%                  ] 11 of 2000 complete in 12.2 sec
[                  0%                  ] 12 of 2000 complete in 13.3 sec
[                  0%                  ] 13 of 2000 complete in 14.5 sec
[                  0%                  ] 14 of 2000 complete in 15.6 sec
[                  0%                  ] 15 of 2000 complete in 16.7 sec
[                  0%                  ] 16 of 2000 complete in 17.7 sec
[                  0%                  ] 17 of 2000 complete in 18.8 sec
[                  0%                  ] 18 of 2000 complete in 19.8 sec
[                  0%                  ] 19 of 2000 complete in 20.8 sec
[                  1%                  ] 20 of 2000 complete in 21.8 sec
[                  1%                  ] 21 of 2000 complete in 22.8 sec
[                  1%                  ] 22 of 2000 complete in 23.8 sec
[                  1%                  ] 23 of 2000 complete in 24.9 sec
[                  1%                  ] 24 of 2000 complete in 25.9 sec
[                  1%                  ] 25 of 2000 complete in 26.8 sec
[                  1%                  ] 26 of 2000 complete in 27.8 sec
[                  1%                  ] 27 of 2000 complete in 28.8 sec
[                  1%                  ] 28 of 2000 complete in 29.9 sec
[                  1%                  ] 29 of 2000 complete in 30.9 sec
[                  1%                  ] 30 of 2000 complete in 31.9 sec
[                  1%                  ] 31 of 2000 complete in 32.8 sec
[                  1%                  ] 32 of 2000 complete in 33.8 sec
[                  1%                  ] 33 of 2000 complete in 34.7 sec
[                  1%                  ] 34 of 2000 complete in 35.7 sec
[                  1%                  ] 35 of 2000 complete in 36.8 sec
[                  1%                  ] 36 of 2000 complete in 37.7 sec
[                  1%                  ] 37 of 2000 complete in 38.7 sec
[                  1%                  ] 38 of 2000 complete in 39.7 sec
[                  1%                  ] 39 of 2000 complete in 40.7 sec
[                  2%                  ] 40 of 2000 complete in 41.7 sec
[                  2%                  ] 41 of 2000 complete in 42.6 sec
[                  2%                  ] 42 of 2000 complete in 43.6 sec
[                  2%                  ] 43 of 2000 complete in 44.5 sec
[                  2%                  ] 44 of 2000 complete in 45.5 sec
[                  2%                  ] 45 of 2000 complete in 46.5 sec
[                  2%                  ] 46 of 2000 complete in 47.4 sec
[                  2%                  ] 47 of 2000 complete in 48.4 sec
[                  2%                  ] 48 of 2000 complete in 49.4 sec
[                  2%                  ] 49 of 2000 complete in 50.4 sec
[                  2%                  ] 50 of 2000 complete in 51.4 sec
[                  2%                  ] 51 of 2000 complete in 52.4 sec
[                  2%                  ] 52 of 2000 complete in 53.4 sec
[-                 2%                  ] 53 of 2000 complete in 54.4 sec
[-                 2%                  ] 54 of 2000 complete in 55.5 sec
[-                 2%                  ] 55 of 2000 complete in 56.5 sec
[-                 2%                  ] 56 of 2000 complete in 57.6 sec
[-                 2%                  ] 57 of 2000 complete in 58.7 sec
[-                 2%                  ] 58 of 2000 complete in 59.6 sec
[-                 2%                  ] 59 of 2000 complete in 60.6 sec
[-                 3%                  ] 60 of 2000 complete in 61.6 sec
[-                 3%                  ] 61 of 2000 complete in 62.6 sec
[-                 3%                  ] 62 of 2000 complete in 63.5 sec
[-                 3%                  ] 63 of 2000 complete in 64.5 sec
[-                 3%                  ] 64 of 2000 complete in 65.5 sec
[-                 3%                  ] 65 of 2000 complete in 66.5 sec
[-                 3%                  ] 66 of 2000 complete in 67.4 sec
[-                 3%                  ] 67 of 2000 complete in 68.4 sec
[-                 3%                  ] 68 of 2000 complete in 69.5 sec
[-                 3%                  ] 69 of 2000 complete in 70.6 sec
[-                 3%                  ] 70 of 2000 complete in 71.5 sec
[-                 3%                  ] 71 of 2000 complete in 72.5 sec
[-                 3%                  ] 72 of 2000 complete in 73.4 sec
[-                 3%                  ] 73 of 2000 complete in 74.5 sec
[-                 3%                  ] 74 of 2000 complete in 75.5 sec
[-                 3%                  ] 75 of 2000 complete in 76.5 sec
[-                 3%                  ] 76 of 2000 complete in 77.4 sec
[-                 3%                  ] 77 of 2000 complete in 78.4 sec
[-                 3%                  ] 78 of 2000 complete in 79.3 sec
[-                 3%                  ] 79 of 2000 complete in 80.3 sec
[-                 4%                  ] 80 of 2000 complete in 81.2 sec
[-                 4%                  ] 81 of 2000 complete in 82.2 sec
[-                 4%                  ] 82 of 2000 complete in 83.2 sec
[-                 4%                  ] 83 of 2000 complete in 84.2 sec
[-                 4%                  ] 84 of 2000 complete in 85.2 sec
[-                 4%                  ] 85 of 2000 complete in 86.2 sec
[-                 4%                  ] 86 of 2000 complete in 87.2 sec
[-                 4%                  ] 87 of 2000 complete in 88.2 sec
[-                 4%                  ] 88 of 2000 complete in 89.2 sec
[-                 4%                  ] 89 of 2000 complete in 90.3 sec
[-                 4%                  ] 90 of 2000 complete in 91.4 sec
[-                 4%                  ] 91 of 2000 complete in 92.4 sec
[-                 4%                  ] 92 of 2000 complete in 93.4 sec
[-                 4%                  ] 93 of 2000 complete in 94.5 sec
[-                 4%                  ] 94 of 2000 complete in 95.4 sec
[-                 4%                  ] 95 of 2000 complete in 96.5 sec
[-                 4%                  ] 96 of 2000 complete in 97.5 sec
[-                 4%                  ] 97 of 2000 complete in 98.5 sec
[-                 4%                  ] 98 of 2000 complete in 99.5 sec
[-                 4%                  ] 99 of 2000 complete in 100.5 sec
[-                 5%                  ] 100 of 2000 complete in 101.6 sec
[-                 5%                  ] 101 of 2000 complete in 102.7 sec
[-                 5%                  ] 102 of 2000 complete in 103.7 sec
[-                 5%                  ] 103 of 2000 complete in 104.7 sec
[-                 5%                  ] 104 of 2000 complete in 105.7 sec
[-                 5%                  ] 105 of 2000 complete in 106.7 sec
[--                5%                  ] 106 of 2000 complete in 107.7 sec
[--                5%                  ] 107 of 2000 complete in 108.8 sec
[--                5%                  ] 108 of 2000 complete in 109.8 sec
[--                5%                  ] 109 of 2000 complete in 110.9 sec
[--                5%                  ] 110 of 2000 complete in 111.9 sec
[--                5%                  ] 111 of 2000 complete in 113.0 sec
[--                5%                  ] 112 of 2000 complete in 113.9 sec
[--                5%                  ] 113 of 2000 complete in 114.9 sec
[                  0%                  ] 2 of 2000 complete in 1.5 sec
[                  0%                  ] 3 of 2000 complete in 2.9 sec
[                  0%                  ] 4 of 2000 complete in 4.3 sec
[                  0%                  ] 5 of 2000 complete in 5.5 sec
[                  0%                  ] 6 of 2000 complete in 6.8 sec
[                  0%                  ] 7 of 2000 complete in 7.9 sec
[                  0%                  ] 8 of 2000 complete in 9.2 sec
[                  0%                  ] 9 of 2000 complete in 10.3 sec
[                  0%                  ] 10 of 2000 complete in 11.5 sec
[                  0%                  ] 11 of 2000 complete in 12.6 sec
[                  0%                  ] 12 of 2000 complete in 13.8 sec
[                  0%                  ] 13 of 2000 complete in 15.0 sec
[                  0%                  ] 14 of 2000 complete in 16.2 sec
[                  0%                  ] 15 of 2000 complete in 17.4 sec
[                  0%                  ] 16 of 2000 complete in 18.6 sec
[                  0%                  ] 17 of 2000 complete in 19.8 sec
[                  0%                  ] 18 of 2000 complete in 20.9 sec
[                  0%                  ] 19 of 2000 complete in 22.0 sec
[                  1%                  ] 20 of 2000 complete in 23.1 sec
[                  1%                  ] 21 of 2000 complete in 24.3 sec
[                  1%                  ] 22 of 2000 complete in 25.4 sec
[                  1%                  ] 23 of 2000 complete in 26.6 sec
[                  1%                  ] 24 of 2000 complete in 27.8 sec
[                  1%                  ] 25 of 2000 complete in 28.9 sec
[                  1%                  ] 26 of 2000 complete in 30.0 sec
[                  1%                  ] 27 of 2000 complete in 31.1 sec
[                  1%                  ] 28 of 2000 complete in 32.2 sec
[                  1%                  ] 29 of 2000 complete in 33.3 sec
[                  1%                  ] 30 of 2000 complete in 34.5 sec
[                  1%                  ] 31 of 2000 complete in 35.6 sec
[                  1%                  ] 32 of 2000 complete in 36.8 sec
[                  1%                  ] 33 of 2000 complete in 38.0 sec
[                  1%                  ] 34 of 2000 complete in 39.1 sec
[                  1%                  ] 35 of 2000 complete in 40.3 sec
[                  1%                  ] 36 of 2000 complete in 41.4 sec
[                  1%                  ] 37 of 2000 complete in 42.6 sec
[                  1%                  ] 38 of 2000 complete in 43.7 sec
[                  1%                  ] 39 of 2000 complete in 44.8 sec
[                  2%                  ] 40 of 2000 complete in 45.9 sec
[                  2%                  ] 41 of 2000 complete in 47.0 sec
[                  2%                  ] 42 of 2000 complete in 48.1 sec
[                  2%                  ] 43 of 2000 complete in 49.2 sec
[                  2%                  ] 44 of 2000 complete in 50.4 sec
[                  2%                  ] 45 of 2000 complete in 51.5 sec
[                  2%                  ] 46 of 2000 complete in 52.7 sec
[                  2%                  ] 47 of 2000 complete in 53.9 sec
[                  2%                  ] 48 of 2000 complete in 55.1 sec
[                  2%                  ] 49 of 2000 complete in 56.3 sec
[                  2%                  ] 50 of 2000 complete in 57.6 sec
[                  2%                  ] 51 of 2000 complete in 58.7 sec
[                  2%                  ] 52 of 2000 complete in 59.9 sec
[-                 2%                  ] 53 of 2000 complete in 61.0 sec
[-                 2%                  ] 54 of 2000 complete in 62.1 sec
[-                 2%                  ] 55 of 2000 complete in 63.2 sec
[-                 2%                  ] 56 of 2000 complete in 64.3 sec
[-                 2%                  ] 57 of 2000 complete in 65.5 sec
[-                 2%                  ] 58 of 2000 complete in 66.6 sec
[-                 2%                  ] 59 of 2000 complete in 67.7 sec
[-                 3%                  ] 60 of 2000 complete in 68.8 sec
[-                 3%                  ] 61 of 2000 complete in 70.0 sec
[-                 3%                  ] 62 of 2000 complete in 71.1 sec
[-                 3%                  ] 63 of 2000 complete in 72.2 sec
[-                 3%                  ] 64 of 2000 complete in 73.2 sec
[-                 3%                  ] 65 of 2000 complete in 74.4 sec
[-                 3%                  ] 66 of 2000 complete in 75.5 sec
[-                 3%                  ] 67 of 2000 complete in 76.6 sec
[-                 3%                  ] 68 of 2000 complete in 77.7 sec
[-                 3%                  ] 69 of 2000 complete in 78.8 sec
[-                 3%                  ] 70 of 2000 complete in 79.9 sec
[-                 3%                  ] 71 of 2000 complete in 80.9 sec
[-                 3%                  ] 72 of 2000 complete in 81.9 sec
[-                 3%                  ] 73 of 2000 complete in 83.0 sec
[-                 3%                  ] 74 of 2000 complete in 84.1 sec
[-                 3%                  ] 75 of 2000 complete in 85.2 sec
[-                 3%                  ] 76 of 2000 complete in 86.3 sec
[-                 3%                  ] 77 of 2000 complete in 87.3 sec
[-                 3%                  ] 78 of 2000 complete in 88.4 sec
[-                 3%                  ] 79 of 2000 complete in 89.5 sec
[-                 4%                  ] 80 of 2000 complete in 90.6 sec
[-                 4%                  ] 81 of 2000 complete in 91.7 sec
[-                 4%                  ] 82 of 2000 complete in 92.8 sec
[-                 4%                  ] 83 of 2000 complete in 93.8 sec
[-                 4%                  ] 84 of 2000 complete in 94.9 sec
[-                 4%                  ] 85 of 2000 complete in 96.0 sec
[-                 4%                  ] 86 of 2000 complete in 97.0 sec
[-                 4%                  ] 87 of 2000 complete in 98.1 sec
[-                 4%                  ] 88 of 2000 complete in 99.1 sec
[-                 4%                  ] 89 of 2000 complete in 100.2 sec
[-                 4%                  ] 90 of 2000 complete in 101.4 sec
[-                 4%                  ] 91 of 2000 complete in 102.5 sec
[-                 4%                  ] 92 of 2000 complete in 103.5 sec
[-                 4%                  ] 93 of 2000 complete in 104.6 sec
[-                 4%                  ] 94 of 2000 complete in 105.7 sec
[-                 4%                  ] 95 of 2000 complete in 106.7 sec
[-                 4%                  ] 96 of 2000 complete in 107.8 sec
[-                 4%                  ] 97 of 2000 complete in 108.9 sec
[-                 4%                  ] 98 of 2000 complete in 110.0 sec
[-                 4%                  ] 99 of 2000 complete in 111.1 sec
[-                 5%                  ] 100 of 2000 complete in 112.1 sec
[-                 5%                  ] 101 of 2000 complete in 113.2 sec
[-                 5%                  ] 102 of 2000 complete in 114.2 sec
[-                 5%                  ] 103 of 2000 complete in 115.3 sec
[-                 5%                  ] 104 of 2000 complete in 116.2 sec
[-                 5%                  ] 105 of 2000 complete in 117.3 sec
[--                5%                  ] 106 of 2000 complete in 118.3 sec
[--                5%                  ] 107 of 2000 complete in 119.2 sec
[--                5%                  ] 108 of 2000 complete in 120.2 sec
[--                5%                  ] 109 of 2000 complete in 121.2 sec
[--                5%                  ] 110 of 2000 complete in 122.2 sec
[--                5%                  ] 111 of 2000 complete in 123.3 sec
[--                5%                  ] 112 of 2000 complete in 124.2 sec

[                  0%                  ] 2 of 2000 complete in 1.4 sec
[                  0%                  ] 3 of 2000 complete in 3.0 sec
[                  0%                  ] 4 of 2000 complete in 4.3 sec
[                  0%                  ] 5 of 2000 complete in 5.6 sec
[                  0%                  ] 6 of 2000 complete in 6.8 sec
[                  0%                  ] 7 of 2000 complete in 8.0 sec
[                  0%                  ] 8 of 2000 complete in 9.2 sec
[                  0%                  ] 9 of 2000 complete in 10.4 sec
[                  0%                  ] 10 of 2000 complete in 11.6 sec
[                  0%                  ] 11 of 2000 complete in 12.7 sec
[                  0%                  ] 12 of 2000 complete in 13.9 sec
[                  0%                  ] 13 of 2000 complete in 15.1 sec
[                  0%                  ] 14 of 2000 complete in 16.3 sec
[                  0%                  ] 15 of 2000 complete in 17.6 sec
[                  0%                  ] 16 of 2000 complete in 18.7 sec
[                  0%                  ] 17 of 2000 complete in 19.9 sec
[                  0%                  ] 18 of 2000 complete in 21.0 sec
[                  0%                  ] 19 of 2000 complete in 22.2 sec
[                  1%                  ] 20 of 2000 complete in 23.5 sec
[                  1%                  ] 21 of 2000 complete in 24.7 sec
[                  1%                  ] 22 of 2000 complete in 25.8 sec
[                  1%                  ] 23 of 2000 complete in 27.0 sec
[                  1%                  ] 24 of 2000 complete in 28.2 sec
[                  1%                  ] 25 of 2000 complete in 29.5 sec
[                  1%                  ] 26 of 2000 complete in 30.6 sec
[                  1%                  ] 27 of 2000 complete in 31.9 sec
[                  1%                  ] 28 of 2000 complete in 33.0 sec
[                  1%                  ] 29 of 2000 complete in 34.2 sec
[                  1%                  ] 30 of 2000 complete in 35.4 sec
[                  1%                  ] 31 of 2000 complete in 36.6 sec
[                  1%                  ] 32 of 2000 complete in 37.8 sec
[                  1%                  ] 33 of 2000 complete in 38.9 sec
[                  1%                  ] 34 of 2000 complete in 40.2 sec
[                  1%                  ] 35 of 2000 complete in 41.4 sec
[                  1%                  ] 36 of 2000 complete in 42.5 sec
[                  1%                  ] 37 of 2000 complete in 43.7 sec
[                  1%                  ] 38 of 2000 complete in 44.8 sec
[                  1%                  ] 39 of 2000 complete in 45.9 sec
[                  2%                  ] 40 of 2000 complete in 47.1 sec
[                  2%                  ] 41 of 2000 complete in 48.3 sec
[                  2%                  ] 42 of 2000 complete in 49.4 sec
[                  2%                  ] 43 of 2000 complete in 50.6 sec
[                  2%                  ] 44 of 2000 complete in 51.8 sec
[                  2%                  ] 45 of 2000 complete in 53.0 sec
[                  2%                  ] 46 of 2000 complete in 54.3 sec
[                  2%                  ] 47 of 2000 complete in 55.5 sec
[                  2%                  ] 48 of 2000 complete in 56.7 sec
[                  2%                  ] 49 of 2000 complete in 58.0 sec
[                  2%                  ] 50 of 2000 complete in 59.1 sec
[                  2%                  ] 51 of 2000 complete in 60.2 sec
[                  2%                  ] 52 of 2000 complete in 61.3 sec
[-                 2%                  ] 53 of 2000 complete in 62.4 sec
[-                 2%                  ] 54 of 2000 complete in 63.5 sec
[-                 2%                  ] 55 of 2000 complete in 64.7 sec
[-                 2%                  ] 56 of 2000 complete in 65.8 sec
[-                 2%                  ] 57 of 2000 complete in 66.9 sec
[-                 2%                  ] 58 of 2000 complete in 68.0 sec
[-                 2%                  ] 59 of 2000 complete in 69.1 sec
[-                 3%                  ] 60 of 2000 complete in 70.2 sec
[-                 3%                  ] 61 of 2000 complete in 71.3 sec
[-                 3%                  ] 62 of 2000 complete in 72.4 sec
[-                 3%                  ] 63 of 2000 complete in 73.5 sec
[-                 3%                  ] 64 of 2000 complete in 74.6 sec
[-                 3%                  ] 65 of 2000 complete in 75.7 sec
[-                 3%                  ] 66 of 2000 complete in 76.7 sec
[-                 3%                  ] 67 of 2000 complete in 77.7 sec
[-                 3%                  ] 68 of 2000 complete in 78.8 sec
[-                 3%                  ] 69 of 2000 complete in 79.8 sec
[-                 3%                  ] 70 of 2000 complete in 80.8 sec
[-                 3%                  ] 71 of 2000 complete in 81.8 sec
[-                 3%                  ] 72 of 2000 complete in 82.8 sec
[-                 3%                  ] 73 of 2000 complete in 83.8 sec
[-                 3%                  ] 74 of 2000 complete in 84.9 sec
[-                 3%                  ] 75 of 2000 complete in 86.0 sec
[-                 3%                  ] 76 of 2000 complete in 87.0 sec
[-                 3%                  ] 77 of 2000 complete in 88.1 sec
[-                 3%                  ] 78 of 2000 complete in 89.2 sec
[-                 3%                  ] 79 of 2000 complete in 90.2 sec
[-                 4%                  ] 80 of 2000 complete in 91.3 sec
[-                 4%                  ] 81 of 2000 complete in 92.4 sec
[-                 4%                  ] 82 of 2000 complete in 93.4 sec
[-                 4%                  ] 83 of 2000 complete in 94.4 sec
[-                 4%                  ] 84 of 2000 complete in 95.5 sec
[-                 4%                  ] 85 of 2000 complete in 96.6 sec
[-                 4%                  ] 86 of 2000 complete in 97.7 sec
[-                 4%                  ] 87 of 2000 complete in 98.8 sec
[-                 4%                  ] 88 of 2000 complete in 99.8 sec
[-                 4%                  ] 89 of 2000 complete in 100.8 sec
[-                 4%                  ] 90 of 2000 complete in 101.8 sec
[-                 4%                  ] 91 of 2000 complete in 102.9 sec
[-                 4%                  ] 92 of 2000 complete in 104.0 sec
[-                 4%                  ] 93 of 2000 complete in 105.0 sec
[-                 4%                  ] 94 of 2000 complete in 106.0 sec
[-                 4%                  ] 95 of 2000 complete in 107.0 sec
[-                 4%                  ] 96 of 2000 complete in 108.1 sec
[-                 4%                  ] 97 of 2000 complete in 109.2 sec
[-                 4%                  ] 98 of 2000 complete in 110.3 sec
[-                 4%                  ] 99 of 2000 complete in 111.5 sec
[-                 5%                  ] 100 of 2000 complete in 112.6 sec
[-                 5%                  ] 101 of 2000 complete in 113.7 sec
[-                 5%                  ] 102 of 2000 complete in 114.8 sec
[-                 5%                  ] 103 of 2000 complete in 115.9 sec
[-                 5%                  ] 104 of 2000 complete in 116.9 sec
[-                 5%                  ] 105 of 2000 complete in 118.0 sec
[--                5%                  ] 106 of 2000 complete in 119.1 sec
[--                5%                  ] 107 of 2000 complete in 120.1 sec
[--                5%                  ] 108 of 2000 complete in 121.2 sec
[--                5%                  ] 109 of 2000 complete in 122.2 sec
[--                5%                  ] 110 of 2000 complete in 123.3 sec
[--                5%                  ] 111 of 2000 complete in 124.3 sec
[--                5%                  ] 112 of 2000 complete in 125.3 sec
[                  0%                  ] 2 of 2000 complete in 1.6 sec
[                  0%                  ] 3 of 2000 complete in 3.1 sec
[                  0%                  ] 4 of 2000 complete in 4.5 sec
[                  0%                  ] 5 of 2000 complete in 5.9 sec
[                  0%                  ] 6 of 2000 complete in 7.1 sec
[                  0%                  ] 7 of 2000 complete in 8.4 sec
[                  0%                  ] 8 of 2000 complete in 9.6 sec
[                  0%                  ] 9 of 2000 complete in 10.8 sec
[                  0%                  ] 10 of 2000 complete in 11.9 sec
[                  0%                  ] 11 of 2000 complete in 13.2 sec
[                  0%                  ] 12 of 2000 complete in 14.4 sec
[                  0%                  ] 13 of 2000 complete in 15.6 sec
[                  0%                  ] 14 of 2000 complete in 16.9 sec
[                  0%                  ] 15 of 2000 complete in 18.1 sec
[                  0%                  ] 16 of 2000 complete in 19.4 sec
[                  0%                  ] 17 of 2000 complete in 20.5 sec
[                  0%                  ] 18 of 2000 complete in 21.7 sec
[                  0%                  ] 19 of 2000 complete in 22.9 sec
[                  1%                  ] 20 of 2000 complete in 24.2 sec
[                  1%                  ] 21 of 2000 complete in 25.4 sec
[                  1%                  ] 22 of 2000 complete in 26.6 sec
[                  1%                  ] 23 of 2000 complete in 27.8 sec
[                  1%                  ] 24 of 2000 complete in 29.0 sec
[                  1%                  ] 25 of 2000 complete in 30.2 sec
[                  1%                  ] 26 of 2000 complete in 31.4 sec
[                  1%                  ] 27 of 2000 complete in 32.6 sec
[                  1%                  ] 28 of 2000 complete in 33.8 sec
[                  1%                  ] 29 of 2000 complete in 35.1 sec
[                  1%                  ] 30 of 2000 complete in 36.3 sec
[                  1%                  ] 31 of 2000 complete in 37.5 sec
[                  1%                  ] 32 of 2000 complete in 38.7 sec
[                  1%                  ] 33 of 2000 complete in 39.9 sec
[                  1%                  ] 34 of 2000 complete in 41.2 sec
[                  1%                  ] 35 of 2000 complete in 42.4 sec
[                  1%                  ] 36 of 2000 complete in 43.5 sec
[                  1%                  ] 37 of 2000 complete in 44.7 sec
[                  1%                  ] 38 of 2000 complete in 45.8 sec
[                  1%                  ] 39 of 2000 complete in 47.0 sec
[                  2%                  ] 40 of 2000 complete in 48.1 sec
[                  2%                  ] 41 of 2000 complete in 49.3 sec
[                  2%                  ] 42 of 2000 complete in 50.5 sec
[                  2%                  ] 43 of 2000 complete in 51.7 sec
[                  2%                  ] 44 of 2000 complete in 53.0 sec
[                  2%                  ] 45 of 2000 complete in 54.1 sec
[                  2%                  ] 46 of 2000 complete in 55.4 sec
[                  2%                  ] 47 of 2000 complete in 56.6 sec
[                  2%                  ] 48 of 2000 complete in 58.0 sec
[                  2%                  ] 49 of 2000 complete in 59.2 sec
[                  2%                  ] 50 of 2000 complete in 60.3 sec
[                  2%                  ] 51 of 2000 complete in 61.5 sec
[                  2%                  ] 52 of 2000 complete in 62.7 sec
[-                 2%                  ] 53 of 2000 complete in 63.8 sec
[-                 2%                  ] 54 of 2000 complete in 65.1 sec
[-                 2%                  ] 55 of 2000 complete in 66.3 sec
[-                 2%                  ] 56 of 2000 complete in 67.4 sec
[-                 2%                  ] 57 of 2000 complete in 68.5 sec
[-                 2%                  ] 58 of 2000 complete in 69.7 sec
[-                 2%                  ] 59 of 2000 complete in 70.9 sec
[-                 3%                  ] 60 of 2000 complete in 72.1 sec
[-                 3%                  ] 61 of 2000 complete in 73.3 sec
[-                 3%                  ] 62 of 2000 complete in 74.5 sec
[-                 3%                  ] 63 of 2000 complete in 75.7 sec
[-                 3%                  ] 64 of 2000 complete in 76.9 sec
[-                 3%                  ] 65 of 2000 complete in 78.1 sec
[-                 3%                  ] 66 of 2000 complete in 79.3 sec
[-                 3%                  ] 67 of 2000 complete in 80.4 sec
[-                 3%                  ] 68 of 2000 complete in 81.5 sec
[-                 3%                  ] 69 of 2000 complete in 82.7 sec
[-                 3%                  ] 70 of 2000 complete in 83.9 sec
[-                 3%                  ] 71 of 2000 complete in 85.0 sec
[-                 3%                  ] 72 of 2000 complete in 86.2 sec
[-                 3%                  ] 73 of 2000 complete in 87.4 sec
[-                 3%                  ] 74 of 2000 complete in 88.5 sec
[-                 3%                  ] 75 of 2000 complete in 89.7 sec
[-                 3%                  ] 76 of 2000 complete in 90.8 sec
[-                 3%                  ] 77 of 2000 complete in 92.0 sec
[-                 3%                  ] 78 of 2000 complete in 93.1 sec
[-                 3%                  ] 79 of 2000 complete in 94.2 sec
[-                 4%                  ] 80 of 2000 complete in 95.4 sec
[-                 4%                  ] 81 of 2000 complete in 96.5 sec
[-                 4%                  ] 82 of 2000 complete in 97.6 sec
[-                 4%                  ] 83 of 2000 complete in 98.7 sec
[-                 4%                  ] 84 of 2000 complete in 99.7 sec
[-                 4%                  ] 85 of 2000 complete in 100.7 sec
[-                 4%                  ] 86 of 2000 complete in 101.8 sec
[-                 4%                  ] 87 of 2000 complete in 102.9 sec
[-                 4%                  ] 88 of 2000 complete in 104.1 sec
[-                 4%                  ] 89 of 2000 complete in 105.2 sec
[-                 4%                  ] 90 of 2000 complete in 106.3 sec
[-                 4%                  ] 91 of 2000 complete in 107.4 sec
[-                 4%                  ] 92 of 2000 complete in 108.6 sec
[-                 4%                  ] 93 of 2000 complete in 109.8 sec
[-                 4%                  ] 94 of 2000 complete in 111.0 sec
[-                 4%                  ] 95 of 2000 complete in 112.0 sec
[-                 4%                  ] 96 of 2000 complete in 113.2 sec
[-                 4%                  ] 97 of 2000 complete in 114.3 sec
[-                 4%                  ] 98 of 2000 complete in 115.4 sec
[-                 4%                  ] 99 of 2000 complete in 116.5 sec
[-                 5%                  ] 100 of 2000 complete in 117.6 sec
[-                 5%                  ] 101 of 2000 complete in 118.8 sec
[-                 5%                  ] 102 of 2000 complete in 119.9 sec
[-                 5%                  ] 103 of 2000 complete in 121.0 sec
[-                 5%                  ] 104 of 2000 complete in 122.2 sec
[-                 5%                  ] 105 of 2000 complete in 123.3 sec
[--                5%                  ] 106 of 2000 complete in 124.4 sec
[--                5%                  ] 107 of 2000 complete in 125.5 sec
[--                5%                  ] 108 of 2000 complete in 126.6 sec
[--                5%                  ] 109 of 2000 complete in 127.7 sec
[--                5%                  ] 110 of 2000 complete in 128.8 sec
[--                5%                  ] 111 of 2000 complete in 129.8 sec
[--                5%                  ] 112 of 2000 complete in 130.9 sec

[--                5%                  ] 114 of 2000 complete in 115.8 sec
[--                5%                  ] 115 of 2000 complete in 116.7 sec
[--                5%                  ] 116 of 2000 complete in 117.6 sec
[--                5%                  ] 117 of 2000 complete in 118.6 sec
[--                5%                  ] 118 of 2000 complete in 119.5 sec
[--                5%                  ] 119 of 2000 complete in 120.4 sec
[--                6%                  ] 120 of 2000 complete in 121.4 sec
[--                6%                  ] 121 of 2000 complete in 122.3 sec
[--                6%                  ] 122 of 2000 complete in 123.2 sec
[--                6%                  ] 123 of 2000 complete in 124.1 sec
[--                6%                  ] 124 of 2000 complete in 125.1 sec
[--                6%                  ] 125 of 2000 complete in 126.1 sec
[--                6%                  ] 126 of 2000 complete in 127.0 sec
[--                6%                  ] 127 of 2000 complete in 128.0 sec
[--                6%                  ] 128 of 2000 complete in 128.9 sec
[--                6%                  ] 129 of 2000 complete in 129.9 sec
[--                6%                  ] 130 of 2000 complete in 130.9 sec
[--                6%                  ] 131 of 2000 complete in 131.8 sec
[--                6%                  ] 132 of 2000 complete in 132.8 sec
[--                6%                  ] 133 of 2000 complete in 133.8 sec
[--                6%                  ] 134 of 2000 complete in 134.7 sec
[--                6%                  ] 135 of 2000 complete in 135.7 sec
[--                6%                  ] 136 of 2000 complete in 136.7 sec
[--                6%                  ] 137 of 2000 complete in 137.6 sec
[--                6%                  ] 138 of 2000 complete in 138.6 sec
[--                6%                  ] 139 of 2000 complete in 139.5 sec
[--                7%                  ] 140 of 2000 complete in 140.5 sec
[--                7%                  ] 141 of 2000 complete in 141.4 sec
[--                7%                  ] 142 of 2000 complete in 142.3 sec
[--                7%                  ] 143 of 2000 complete in 143.2 sec
[--                7%                  ] 144 of 2000 complete in 144.1 sec
[--                7%                  ] 145 of 2000 complete in 145.0 sec
[--                7%                  ] 146 of 2000 complete in 145.9 sec
[--                7%                  ] 147 of 2000 complete in 146.9 sec
[--                7%                  ] 148 of 2000 complete in 147.7 sec
[--                7%                  ] 149 of 2000 complete in 148.6 sec
[--                7%                  ] 150 of 2000 complete in 149.5 sec
[--                7%                  ] 151 of 2000 complete in 150.3 sec
[--                7%                  ] 152 of 2000 complete in 151.1 sec
[--                7%                  ] 153 of 2000 complete in 151.9 sec
[--                7%                  ] 154 of 2000 complete in 152.9 sec
[--                7%                  ] 155 of 2000 complete in 153.8 sec
[--                7%                  ] 156 of 2000 complete in 154.6 sec
[--                7%                  ] 157 of 2000 complete in 155.5 sec
[---               7%                  ] 158 of 2000 complete in 156.4 sec
[---               7%                  ] 159 of 2000 complete in 157.3 sec
[---               8%                  ] 160 of 2000 complete in 158.1 sec
[---               8%                  ] 161 of 2000 complete in 159.0 sec
[---               8%                  ] 162 of 2000 complete in 159.8 sec
[---               8%                  ] 163 of 2000 complete in 160.7 sec
[---               8%                  ] 164 of 2000 complete in 161.6 sec
[---               8%                  ] 165 of 2000 complete in 162.4 sec
[---               8%                  ] 166 of 2000 complete in 163.4 sec
[---               8%                  ] 167 of 2000 complete in 164.3 sec
[---               8%                  ] 168 of 2000 complete in 165.2 sec
[---               8%                  ] 169 of 2000 complete in 166.1 sec
[---               8%                  ] 170 of 2000 complete in 167.0 sec
[---               8%                  ] 171 of 2000 complete in 167.8 sec
[---               8%                  ] 172 of 2000 complete in 168.7 sec
[---               8%                  ] 173 of 2000 complete in 169.6 sec
[---               8%                  ] 174 of 2000 complete in 170.4 sec
[---               8%                  ] 175 of 2000 complete in 171.3 sec
[---               8%                  ] 176 of 2000 complete in 172.2 sec
[---               8%                  ] 177 of 2000 complete in 173.2 sec
[---               8%                  ] 178 of 2000 complete in 174.1 sec
[---               8%                  ] 179 of 2000 complete in 175.0 sec
[---               9%                  ] 180 of 2000 complete in 176.0 sec
[---               9%                  ] 181 of 2000 complete in 177.2 sec
[---               9%                  ] 182 of 2000 complete in 178.2 sec
[---               9%                  ] 183 of 2000 complete in 179.5 sec
[---               9%                  ] 184 of 2000 complete in 180.6 sec
[---               9%                  ] 185 of 2000 complete in 181.7 sec
[---               9%                  ] 186 of 2000 complete in 182.8 sec
[---               9%                  ] 187 of 2000 complete in 183.8 sec
[---               9%                  ] 188 of 2000 complete in 184.8 sec
[---               9%                  ] 189 of 2000 complete in 185.8 sec
[---               9%                  ] 190 of 2000 complete in 186.8 sec
[---               9%                  ] 191 of 2000 complete in 187.7 sec
[---               9%                  ] 192 of 2000 complete in 188.7 sec
[---               9%                  ] 193 of 2000 complete in 189.7 sec
[---               9%                  ] 194 of 2000 complete in 190.8 sec
[---               9%                  ] 195 of 2000 complete in 191.7 sec
[---               9%                  ] 196 of 2000 complete in 192.6 sec
[---               9%                  ] 197 of 2000 complete in 193.6 sec
[---               9%                  ] 198 of 2000 complete in 194.4 sec
[---               9%                  ] 199 of 2000 complete in 195.3 sec
[---              10%                  ] 200 of 2000 complete in 196.2 sec
[---              10%                  ] 201 of 2000 complete in 197.2 sec
[---              10%                  ] 202 of 2000 complete in 198.0 sec
[---              10%                  ] 203 of 2000 complete in 198.9 sec
[---              10%                  ] 204 of 2000 complete in 199.8 sec
[---              10%                  ] 205 of 2000 complete in 200.8 sec
[---              10%                  ] 206 of 2000 complete in 201.8 sec
[---              10%                  ] 207 of 2000 complete in 202.8 sec
[---              10%                  ] 208 of 2000 complete in 203.8 sec
[---              10%                  ] 209 of 2000 complete in 204.8 sec
[---              10%                  ] 210 of 2000 complete in 205.7 sec
[----             10%                  ] 211 of 2000 complete in 206.6 sec
[----             10%                  ] 212 of 2000 complete in 207.4 sec
[----             10%                  ] 213 of 2000 complete in 208.3 sec
[----             10%                  ] 214 of 2000 complete in 209.2 sec
[----             10%                  ] 215 of 2000 complete in 210.1 sec
[----             10%                  ] 216 of 2000 complete in 211.0 sec
[----             10%                  ] 217 of 2000 complete in 211.9 sec
[----             10%                  ] 218 of 2000 complete in 212.8 sec
[----             10%                  ] 219 of 2000 complete in 213.7 sec
[----             11%                  ] 220 of 2000 complete in 214.6 sec
[----             11%                  ] 221 of 2000 complete in 215.5 sec
[----             11%                  ] 222 of 2000 complete in 216.4 sec
[--                5%                  ] 113 of 2000 complete in 126.3 sec
[--                5%                  ] 114 of 2000 complete in 127.3 sec
[--                5%                  ] 115 of 2000 complete in 128.3 sec
[--                5%                  ] 116 of 2000 complete in 129.3 sec
[--                5%                  ] 117 of 2000 complete in 130.3 sec
[--                5%                  ] 118 of 2000 complete in 131.3 sec
[--                5%                  ] 119 of 2000 complete in 132.3 sec
[--                6%                  ] 120 of 2000 complete in 133.3 sec
[--                6%                  ] 121 of 2000 complete in 134.3 sec
[--                6%                  ] 122 of 2000 complete in 135.4 sec
[--                6%                  ] 123 of 2000 complete in 136.3 sec
[--                6%                  ] 124 of 2000 complete in 137.3 sec
[--                6%                  ] 125 of 2000 complete in 138.3 sec
[--                6%                  ] 126 of 2000 complete in 139.3 sec
[--                6%                  ] 127 of 2000 complete in 140.2 sec
[--                6%                  ] 128 of 2000 complete in 141.2 sec
[--                6%                  ] 129 of 2000 complete in 142.1 sec
[--                6%                  ] 130 of 2000 complete in 143.1 sec
[--                6%                  ] 131 of 2000 complete in 144.0 sec
[--                6%                  ] 132 of 2000 complete in 145.0 sec
[--                6%                  ] 133 of 2000 complete in 145.9 sec
[--                6%                  ] 134 of 2000 complete in 146.8 sec
[--                6%                  ] 135 of 2000 complete in 147.7 sec
[--                6%                  ] 136 of 2000 complete in 148.6 sec
[--                6%                  ] 137 of 2000 complete in 149.5 sec
[--                6%                  ] 138 of 2000 complete in 150.3 sec
[--                6%                  ] 139 of 2000 complete in 151.1 sec
[--                7%                  ] 140 of 2000 complete in 152.0 sec
[--                7%                  ] 141 of 2000 complete in 152.8 sec
[--                7%                  ] 142 of 2000 complete in 153.7 sec
[--                7%                  ] 143 of 2000 complete in 154.5 sec
[--                7%                  ] 144 of 2000 complete in 155.3 sec
[--                7%                  ] 145 of 2000 complete in 156.0 sec
[--                7%                  ] 146 of 2000 complete in 156.8 sec
[--                7%                  ] 147 of 2000 complete in 157.6 sec
[--                7%                  ] 148 of 2000 complete in 158.4 sec
[--                7%                  ] 149 of 2000 complete in 159.2 sec
[--                7%                  ] 150 of 2000 complete in 160.1 sec
[--                7%                  ] 151 of 2000 complete in 161.0 sec
[--                7%                  ] 152 of 2000 complete in 161.8 sec
[--                7%                  ] 153 of 2000 complete in 162.7 sec
[--                7%                  ] 154 of 2000 complete in 163.6 sec
[--                7%                  ] 155 of 2000 complete in 164.5 sec
[--                7%                  ] 156 of 2000 complete in 165.3 sec
[--                7%                  ] 157 of 2000 complete in 166.2 sec
[---               7%                  ] 158 of 2000 complete in 167.1 sec
[---               7%                  ] 159 of 2000 complete in 167.9 sec
[---               8%                  ] 160 of 2000 complete in 168.7 sec
[---               8%                  ] 161 of 2000 complete in 169.6 sec
[---               8%                  ] 162 of 2000 complete in 170.4 sec
[---               8%                  ] 163 of 2000 complete in 171.3 sec
[---               8%                  ] 164 of 2000 complete in 172.2 sec
[---               8%                  ] 165 of 2000 complete in 173.1 sec
[---               8%                  ] 166 of 2000 complete in 173.9 sec
[---               8%                  ] 167 of 2000 complete in 174.8 sec
[---               8%                  ] 168 of 2000 complete in 175.7 sec
[---               8%                  ] 169 of 2000 complete in 176.9 sec
[---               8%                  ] 170 of 2000 complete in 177.9 sec
[---               8%                  ] 171 of 2000 complete in 179.2 sec
[---               8%                  ] 172 of 2000 complete in 180.3 sec
[---               8%                  ] 173 of 2000 complete in 181.4 sec
[---               8%                  ] 174 of 2000 complete in 182.4 sec
[---               8%                  ] 175 of 2000 complete in 183.4 sec
[---               8%                  ] 176 of 2000 complete in 184.5 sec
[---               8%                  ] 177 of 2000 complete in 185.5 sec
[---               8%                  ] 178 of 2000 complete in 186.5 sec
[---               8%                  ] 179 of 2000 complete in 187.5 sec
[---               9%                  ] 180 of 2000 complete in 188.4 sec
[---               9%                  ] 181 of 2000 complete in 189.5 sec
[---               9%                  ] 182 of 2000 complete in 190.5 sec
[---               9%                  ] 183 of 2000 complete in 191.5 sec
[---               9%                  ] 184 of 2000 complete in 192.3 sec
[---               9%                  ] 185 of 2000 complete in 193.2 sec
[---               9%                  ] 186 of 2000 complete in 194.1 sec
[---               9%                  ] 187 of 2000 complete in 194.9 sec
[---               9%                  ] 188 of 2000 complete in 195.8 sec
[---               9%                  ] 189 of 2000 complete in 196.7 sec
[---               9%                  ] 190 of 2000 complete in 197.5 sec
[---               9%                  ] 191 of 2000 complete in 198.4 sec
[---               9%                  ] 192 of 2000 complete in 199.2 sec
[---               9%                  ] 193 of 2000 complete in 200.1 sec
[---               9%                  ] 194 of 2000 complete in 201.1 sec
[---               9%                  ] 195 of 2000 complete in 202.0 sec
[---               9%                  ] 196 of 2000 complete in 202.9 sec
[---               9%                  ] 197 of 2000 complete in 203.8 sec
[---               9%                  ] 198 of 2000 complete in 204.7 sec
[---               9%                  ] 199 of 2000 complete in 205.5 sec
[---              10%                  ] 200 of 2000 complete in 206.4 sec
[---              10%                  ] 201 of 2000 complete in 207.3 sec
[---              10%                  ] 202 of 2000 complete in 208.2 sec
[---              10%                  ] 203 of 2000 complete in 209.1 sec
[---              10%                  ] 204 of 2000 complete in 209.9 sec
[---              10%                  ] 205 of 2000 complete in 210.9 sec
[---              10%                  ] 206 of 2000 complete in 211.7 sec
[---              10%                  ] 207 of 2000 complete in 212.6 sec
[---              10%                  ] 208 of 2000 complete in 213.5 sec
[---              10%                  ] 209 of 2000 complete in 214.3 sec
[---              10%                  ] 210 of 2000 complete in 215.1 sec
[----             10%                  ] 211 of 2000 complete in 215.9 sec
[----             10%                  ] 212 of 2000 complete in 216.7 sec
[----             10%                  ] 213 of 2000 complete in 217.5 sec
[----             10%                  ] 214 of 2000 complete in 218.3 sec
[----             10%                  ] 215 of 2000 complete in 219.2 sec
[----             10%                  ] 216 of 2000 complete in 220.0 sec
[----             10%                  ] 217 of 2000 complete in 220.8 sec
[----             10%                  ] 218 of 2000 complete in 221.6 sec
[----             10%                  ] 219 of 2000 complete in 222.4 sec
[----             11%                  ] 220 of 2000 complete in 223.3 sec
[----             11%                  ] 221 of 2000 complete in 224.1 sec

[--                5%                  ] 113 of 2000 complete in 125.2 sec
[--                5%                  ] 114 of 2000 complete in 126.2 sec
[--                5%                  ] 115 of 2000 complete in 127.2 sec
[--                5%                  ] 116 of 2000 complete in 128.2 sec
[--                5%                  ] 117 of 2000 complete in 129.2 sec
[--                5%                  ] 118 of 2000 complete in 130.2 sec
[--                5%                  ] 119 of 2000 complete in 131.1 sec
[--                6%                  ] 120 of 2000 complete in 132.1 sec
[--                6%                  ] 121 of 2000 complete in 133.0 sec
[--                6%                  ] 122 of 2000 complete in 133.9 sec
[--                6%                  ] 123 of 2000 complete in 134.9 sec
[--                6%                  ] 124 of 2000 complete in 135.9 sec
[--                6%                  ] 125 of 2000 complete in 136.8 sec
[--                6%                  ] 126 of 2000 complete in 137.7 sec
[--                6%                  ] 127 of 2000 complete in 138.6 sec
[--                6%                  ] 128 of 2000 complete in 139.5 sec
[--                6%                  ] 129 of 2000 complete in 140.4 sec
[--                6%                  ] 130 of 2000 complete in 141.3 sec
[--                6%                  ] 131 of 2000 complete in 142.2 sec
[--                6%                  ] 132 of 2000 complete in 143.1 sec
[--                6%                  ] 133 of 2000 complete in 144.0 sec
[--                6%                  ] 134 of 2000 complete in 144.9 sec
[--                6%                  ] 135 of 2000 complete in 145.8 sec
[--                6%                  ] 136 of 2000 complete in 146.7 sec
[--                6%                  ] 137 of 2000 complete in 147.6 sec
[--                6%                  ] 138 of 2000 complete in 148.5 sec
[--                6%                  ] 139 of 2000 complete in 149.4 sec
[--                7%                  ] 140 of 2000 complete in 150.3 sec
[--                7%                  ] 141 of 2000 complete in 151.1 sec
[--                7%                  ] 142 of 2000 complete in 152.0 sec
[--                7%                  ] 143 of 2000 complete in 153.0 sec
[--                7%                  ] 144 of 2000 complete in 153.9 sec
[--                7%                  ] 145 of 2000 complete in 154.8 sec
[--                7%                  ] 146 of 2000 complete in 155.7 sec
[--                7%                  ] 147 of 2000 complete in 156.6 sec
[--                7%                  ] 148 of 2000 complete in 157.5 sec
[--                7%                  ] 149 of 2000 complete in 158.4 sec
[--                7%                  ] 150 of 2000 complete in 159.3 sec
[--                7%                  ] 151 of 2000 complete in 160.1 sec
[--                7%                  ] 152 of 2000 complete in 161.0 sec
[--                7%                  ] 153 of 2000 complete in 161.9 sec
[--                7%                  ] 154 of 2000 complete in 162.8 sec
[--                7%                  ] 155 of 2000 complete in 163.7 sec
[--                7%                  ] 156 of 2000 complete in 164.6 sec
[--                7%                  ] 157 of 2000 complete in 165.5 sec
[---               7%                  ] 158 of 2000 complete in 166.4 sec
[---               7%                  ] 159 of 2000 complete in 167.4 sec
[---               8%                  ] 160 of 2000 complete in 168.3 sec
[---               8%                  ] 161 of 2000 complete in 169.3 sec
[---               8%                  ] 162 of 2000 complete in 170.2 sec
[---               8%                  ] 163 of 2000 complete in 171.2 sec
[---               8%                  ] 164 of 2000 complete in 172.1 sec
[---               8%                  ] 165 of 2000 complete in 173.1 sec
[---               8%                  ] 166 of 2000 complete in 174.1 sec
[---               8%                  ] 167 of 2000 complete in 175.2 sec
[---               8%                  ] 168 of 2000 complete in 176.2 sec
[---               8%                  ] 169 of 2000 complete in 177.4 sec
[---               8%                  ] 170 of 2000 complete in 178.6 sec
[---               8%                  ] 171 of 2000 complete in 180.0 sec
[---               8%                  ] 172 of 2000 complete in 181.3 sec
[---               8%                  ] 173 of 2000 complete in 182.5 sec
[---               8%                  ] 174 of 2000 complete in 183.7 sec
[---               8%                  ] 175 of 2000 complete in 184.8 sec
[---               8%                  ] 176 of 2000 complete in 186.0 sec
[---               8%                  ] 177 of 2000 complete in 187.1 sec
[---               8%                  ] 178 of 2000 complete in 188.2 sec
[---               8%                  ] 179 of 2000 complete in 189.4 sec
[---               9%                  ] 180 of 2000 complete in 190.6 sec
[---               9%                  ] 181 of 2000 complete in 191.7 sec
[---               9%                  ] 182 of 2000 complete in 192.7 sec
[---               9%                  ] 183 of 2000 complete in 193.8 sec
[---               9%                  ] 184 of 2000 complete in 194.8 sec
[---               9%                  ] 185 of 2000 complete in 195.9 sec
[---               9%                  ] 186 of 2000 complete in 196.9 sec
[---               9%                  ] 187 of 2000 complete in 198.0 sec
[---               9%                  ] 188 of 2000 complete in 199.1 sec
[---               9%                  ] 189 of 2000 complete in 200.1 sec
[---               9%                  ] 190 of 2000 complete in 201.3 sec
[---               9%                  ] 191 of 2000 complete in 202.3 sec
[---               9%                  ] 192 of 2000 complete in 203.4 sec
[---               9%                  ] 193 of 2000 complete in 204.4 sec
[---               9%                  ] 194 of 2000 complete in 205.4 sec
[---               9%                  ] 195 of 2000 complete in 206.4 sec
[---               9%                  ] 196 of 2000 complete in 207.4 sec
[---               9%                  ] 197 of 2000 complete in 208.4 sec
[---               9%                  ] 198 of 2000 complete in 209.4 sec
[---               9%                  ] 199 of 2000 complete in 210.4 sec
[---              10%                  ] 200 of 2000 complete in 211.4 sec
[---              10%                  ] 201 of 2000 complete in 212.4 sec
[---              10%                  ] 202 of 2000 complete in 213.4 sec
[---              10%                  ] 203 of 2000 complete in 214.4 sec
[---              10%                  ] 204 of 2000 complete in 215.4 sec
[---              10%                  ] 205 of 2000 complete in 216.3 sec
[---              10%                  ] 206 of 2000 complete in 217.3 sec
[---              10%                  ] 207 of 2000 complete in 218.4 sec
[---              10%                  ] 208 of 2000 complete in 219.4 sec
[---              10%                  ] 209 of 2000 complete in 220.4 sec
[---              10%                  ] 210 of 2000 complete in 221.4 sec
[----             10%                  ] 211 of 2000 complete in 222.4 sec
[----             10%                  ] 212 of 2000 complete in 223.4 sec
[----             10%                  ] 213 of 2000 complete in 224.4 sec
[----             10%                  ] 214 of 2000 complete in 225.4 sec
[----             10%                  ] 215 of 2000 complete in 226.4 sec
[----             10%                  ] 216 of 2000 complete in 227.4 sec
[----             10%                  ] 217 of 2000 complete in 228.4 sec
[----             10%                  ] 218 of 2000 complete in 229.4 sec
[----             10%                  ] 219 of 2000 complete in 230.5 sec
[----             11%                  ] 220 of 2000 complete in 231.4 sec
[----             11%                  ] 221 of 2000 complete in 232.5 sec
[--                5%                  ] 113 of 2000 complete in 132.0 sec
[--                5%                  ] 114 of 2000 complete in 133.1 sec
[--                5%                  ] 115 of 2000 complete in 134.1 sec
[--                5%                  ] 116 of 2000 complete in 135.3 sec
[--                5%                  ] 117 of 2000 complete in 136.4 sec
[--                5%                  ] 118 of 2000 complete in 137.5 sec
[--                5%                  ] 119 of 2000 complete in 138.6 sec
[--                6%                  ] 120 of 2000 complete in 139.7 sec
[--                6%                  ] 121 of 2000 complete in 140.8 sec
[--                6%                  ] 122 of 2000 complete in 142.0 sec
[--                6%                  ] 123 of 2000 complete in 143.1 sec
[--                6%                  ] 124 of 2000 complete in 144.1 sec
[--                6%                  ] 125 of 2000 complete in 145.1 sec
[--                6%                  ] 126 of 2000 complete in 146.2 sec
[--                6%                  ] 127 of 2000 complete in 147.1 sec
[--                6%                  ] 128 of 2000 complete in 148.1 sec
[--                6%                  ] 129 of 2000 complete in 149.0 sec
[--                6%                  ] 130 of 2000 complete in 150.0 sec
[--                6%                  ] 131 of 2000 complete in 150.9 sec
[--                6%                  ] 132 of 2000 complete in 151.9 sec
[--                6%                  ] 133 of 2000 complete in 152.9 sec
[--                6%                  ] 134 of 2000 complete in 153.9 sec
[--                6%                  ] 135 of 2000 complete in 154.9 sec
[--                6%                  ] 136 of 2000 complete in 155.8 sec
[--                6%                  ] 137 of 2000 complete in 156.7 sec
[--                6%                  ] 138 of 2000 complete in 157.6 sec
[--                6%                  ] 139 of 2000 complete in 158.6 sec
[--                7%                  ] 140 of 2000 complete in 159.5 sec
[--                7%                  ] 141 of 2000 complete in 160.4 sec
[--                7%                  ] 142 of 2000 complete in 161.3 sec
[--                7%                  ] 143 of 2000 complete in 162.2 sec
[--                7%                  ] 144 of 2000 complete in 163.2 sec
[--                7%                  ] 145 of 2000 complete in 164.1 sec
[--                7%                  ] 146 of 2000 complete in 165.1 sec
[--                7%                  ] 147 of 2000 complete in 166.0 sec
[--                7%                  ] 148 of 2000 complete in 167.0 sec
[--                7%                  ] 149 of 2000 complete in 168.0 sec
[--                7%                  ] 150 of 2000 complete in 168.9 sec
[--                7%                  ] 151 of 2000 complete in 169.9 sec
[--                7%                  ] 152 of 2000 complete in 170.9 sec
[--                7%                  ] 153 of 2000 complete in 171.9 sec
[--                7%                  ] 154 of 2000 complete in 172.9 sec
[--                7%                  ] 155 of 2000 complete in 173.9 sec
[--                7%                  ] 156 of 2000 complete in 175.0 sec
[--                7%                  ] 157 of 2000 complete in 176.0 sec
[---               7%                  ] 158 of 2000 complete in 177.3 sec
[---               7%                  ] 159 of 2000 complete in 178.5 sec
[---               8%                  ] 160 of 2000 complete in 179.9 sec
[---               8%                  ] 161 of 2000 complete in 181.1 sec
[---               8%                  ] 162 of 2000 complete in 182.3 sec
[---               8%                  ] 163 of 2000 complete in 183.5 sec
[---               8%                  ] 164 of 2000 complete in 184.6 sec
[---               8%                  ] 165 of 2000 complete in 185.7 sec
[---               8%                  ] 166 of 2000 complete in 186.8 sec
[---               8%                  ] 167 of 2000 complete in 187.9 sec
[---               8%                  ] 168 of 2000 complete in 189.0 sec
[---               8%                  ] 169 of 2000 complete in 190.1 sec
[---               8%                  ] 170 of 2000 complete in 191.2 sec
[---               8%                  ] 171 of 2000 complete in 192.1 sec
[---               8%                  ] 172 of 2000 complete in 193.1 sec
[---               8%                  ] 173 of 2000 complete in 194.1 sec
[---               8%                  ] 174 of 2000 complete in 195.0 sec
[---               8%                  ] 175 of 2000 complete in 195.9 sec
[---               8%                  ] 176 of 2000 complete in 196.9 sec
[---               8%                  ] 177 of 2000 complete in 197.8 sec
[---               8%                  ] 178 of 2000 complete in 198.8 sec
[---               8%                  ] 179 of 2000 complete in 199.7 sec
[---               9%                  ] 180 of 2000 complete in 200.8 sec
[---               9%                  ] 181 of 2000 complete in 201.8 sec
[---               9%                  ] 182 of 2000 complete in 202.8 sec
[---               9%                  ] 183 of 2000 complete in 203.8 sec
[---               9%                  ] 184 of 2000 complete in 204.8 sec
[---               9%                  ] 185 of 2000 complete in 205.8 sec
[---               9%                  ] 186 of 2000 complete in 206.8 sec
[---               9%                  ] 187 of 2000 complete in 207.7 sec
[---               9%                  ] 188 of 2000 complete in 208.7 sec
[---               9%                  ] 189 of 2000 complete in 209.7 sec
[---               9%                  ] 190 of 2000 complete in 210.7 sec
[---               9%                  ] 191 of 2000 complete in 211.7 sec
[---               9%                  ] 192 of 2000 complete in 212.6 sec
[---               9%                  ] 193 of 2000 complete in 213.5 sec
[---               9%                  ] 194 of 2000 complete in 214.4 sec
[---               9%                  ] 195 of 2000 complete in 215.4 sec
[---               9%                  ] 196 of 2000 complete in 216.3 sec
[---               9%                  ] 197 of 2000 complete in 217.2 sec
[---               9%                  ] 198 of 2000 complete in 218.2 sec
[---               9%                  ] 199 of 2000 complete in 219.2 sec
[---              10%                  ] 200 of 2000 complete in 220.2 sec
[---              10%                  ] 201 of 2000 complete in 221.2 sec
[---              10%                  ] 202 of 2000 complete in 222.1 sec
[---              10%                  ] 203 of 2000 complete in 223.1 sec
[---              10%                  ] 204 of 2000 complete in 224.1 sec
[---              10%                  ] 205 of 2000 complete in 225.1 sec
[---              10%                  ] 206 of 2000 complete in 226.1 sec
[---              10%                  ] 207 of 2000 complete in 227.1 sec
[---              10%                  ] 208 of 2000 complete in 228.1 sec
[---              10%                  ] 209 of 2000 complete in 229.1 sec
[---              10%                  ] 210 of 2000 complete in 230.1 sec
[----             10%                  ] 211 of 2000 complete in 231.1 sec
[----             10%                  ] 212 of 2000 complete in 232.1 sec
[----             10%                  ] 213 of 2000 complete in 233.1 sec
[----             10%                  ] 214 of 2000 complete in 234.1 sec
[----             10%                  ] 215 of 2000 complete in 235.1 sec
[----             10%                  ] 216 of 2000 complete in 236.1 sec
[----             10%                  ] 217 of 2000 complete in 237.1 sec
[----             10%                  ] 218 of 2000 complete in 238.1 sec
[----             10%                  ] 219 of 2000 complete in 239.1 sec
[----             11%                  ] 220 of 2000 complete in 240.0 sec
[----             11%                  ] 221 of 2000 complete in 241.0 sec

[----             11%                  ] 223 of 2000 complete in 217.3 sec
[----             11%                  ] 224 of 2000 complete in 218.2 sec
[----             11%                  ] 225 of 2000 complete in 219.1 sec
[----             11%                  ] 226 of 2000 complete in 220.0 sec
[----             11%                  ] 227 of 2000 complete in 220.9 sec
[----             11%                  ] 228 of 2000 complete in 221.8 sec
[----             11%                  ] 229 of 2000 complete in 222.6 sec
[----             11%                  ] 230 of 2000 complete in 223.5 sec
[----             11%                  ] 231 of 2000 complete in 224.3 sec
[----             11%                  ] 232 of 2000 complete in 225.2 sec
[----             11%                  ] 233 of 2000 complete in 226.0 sec
[----             11%                  ] 234 of 2000 complete in 226.8 sec
[----             11%                  ] 235 of 2000 complete in 227.6 sec
[----             11%                  ] 236 of 2000 complete in 228.4 sec
[----             11%                  ] 237 of 2000 complete in 229.2 sec
[----             11%                  ] 238 of 2000 complete in 230.0 sec
[----             11%                  ] 239 of 2000 complete in 230.8 sec
[----             12%                  ] 240 of 2000 complete in 231.6 sec
[----             12%                  ] 241 of 2000 complete in 232.5 sec
[----             12%                  ] 242 of 2000 complete in 233.3 sec
[----             12%                  ] 243 of 2000 complete in 234.1 sec
[----             12%                  ] 244 of 2000 complete in 234.9 sec
[----             12%                  ] 245 of 2000 complete in 235.8 sec
[----             12%                  ] 246 of 2000 complete in 236.6 sec
[----             12%                  ] 247 of 2000 complete in 237.4 sec
[----             12%                  ] 248 of 2000 complete in 238.3 sec
[----             12%                  ] 249 of 2000 complete in 239.1 sec
[----             12%                  ] 250 of 2000 complete in 240.0 sec
[----             12%                  ] 251 of 2000 complete in 240.8 sec
[----             12%                  ] 252 of 2000 complete in 241.7 sec
[----             12%                  ] 253 of 2000 complete in 242.5 sec
[----             12%                  ] 254 of 2000 complete in 243.3 sec
[----             12%                  ] 255 of 2000 complete in 244.1 sec
[----             12%                  ] 256 of 2000 complete in 245.0 sec
[----             12%                  ] 257 of 2000 complete in 245.7 sec
[----             12%                  ] 258 of 2000 complete in 246.5 sec
[----             12%                  ] 259 of 2000 complete in 247.4 sec
[----             13%                  ] 260 of 2000 complete in 248.3 sec
[----             13%                  ] 261 of 2000 complete in 249.1 sec
[----             13%                  ] 262 of 2000 complete in 249.9 sec
[----             13%                  ] 263 of 2000 complete in 250.8 sec
[-----            13%                  ] 264 of 2000 complete in 251.6 sec
[-----            13%                  ] 265 of 2000 complete in 252.4 sec
[-----            13%                  ] 266 of 2000 complete in 253.2 sec
[-----            13%                  ] 267 of 2000 complete in 254.0 sec
[-----            13%                  ] 268 of 2000 complete in 254.8 sec
[-----            13%                  ] 269 of 2000 complete in 255.6 sec
[-----            13%                  ] 270 of 2000 complete in 256.4 sec
[-----            13%                  ] 271 of 2000 complete in 257.2 sec
[-----            13%                  ] 272 of 2000 complete in 258.0 sec
[-----            13%                  ] 273 of 2000 complete in 258.8 sec
[-----            13%                  ] 274 of 2000 complete in 259.6 sec
[-----            13%                  ] 275 of 2000 complete in 260.4 sec
[-----            13%                  ] 276 of 2000 complete in 261.2 sec
[-----            13%                  ] 277 of 2000 complete in 262.1 sec
[-----            13%                  ] 278 of 2000 complete in 263.0 sec
[-----            13%                  ] 279 of 2000 complete in 263.7 sec
[-----            14%                  ] 280 of 2000 complete in 264.5 sec
[-----            14%                  ] 281 of 2000 complete in 265.2 sec
[-----            14%                  ] 282 of 2000 complete in 266.0 sec
[-----            14%                  ] 283 of 2000 complete in 266.8 sec
[-----            14%                  ] 284 of 2000 complete in 267.6 sec
[-----            14%                  ] 285 of 2000 complete in 268.4 sec
[-----            14%                  ] 286 of 2000 complete in 269.2 sec
[-----            14%                  ] 287 of 2000 complete in 270.1 sec
[-----            14%                  ] 288 of 2000 complete in 270.8 sec
[-----            14%                  ] 289 of 2000 complete in 271.6 sec
[-----            14%                  ] 290 of 2000 complete in 272.4 sec
[-----            14%                  ] 291 of 2000 complete in 273.2 sec
[-----            14%                  ] 292 of 2000 complete in 274.0 sec
[-----            14%                  ] 293 of 2000 complete in 274.8 sec
[-----            14%                  ] 294 of 2000 complete in 275.5 sec
[-----            14%                  ] 295 of 2000 complete in 276.3 sec
[-----            14%                  ] 296 of 2000 complete in 277.1 sec
[-----            14%                  ] 297 of 2000 complete in 277.9 sec
[-----            14%                  ] 298 of 2000 complete in 278.8 sec
[-----            14%                  ] 299 of 2000 complete in 279.5 sec
[-----            15%                  ] 300 of 2000 complete in 280.3 sec
[-----            15%                  ] 301 of 2000 complete in 281.1 sec
[-----            15%                  ] 302 of 2000 complete in 281.9 sec
[-----            15%                  ] 303 of 2000 complete in 282.8 sec
[-----            15%                  ] 304 of 2000 complete in 283.6 sec
[-----            15%                  ] 305 of 2000 complete in 284.4 sec
[-----            15%                  ] 306 of 2000 complete in 285.2 sec
[-----            15%                  ] 307 of 2000 complete in 286.0 sec
[-----            15%                  ] 308 of 2000 complete in 286.8 sec
[-----            15%                  ] 309 of 2000 complete in 287.7 sec
[-----            15%                  ] 310 of 2000 complete in 288.5 sec
[-----            15%                  ] 311 of 2000 complete in 289.4 sec
[-----            15%                  ] 312 of 2000 complete in 290.2 sec
[-----            15%                  ] 313 of 2000 complete in 291.1 sec
[-----            15%                  ] 314 of 2000 complete in 291.9 sec
[-----            15%                  ] 315 of 2000 complete in 292.7 sec
[------           15%                  ] 316 of 2000 complete in 293.6 sec
[------           15%                  ] 317 of 2000 complete in 294.4 sec
[------           15%                  ] 318 of 2000 complete in 295.2 sec
[------           15%                  ] 319 of 2000 complete in 296.0 sec
[------           16%                  ] 320 of 2000 complete in 296.8 sec
[------           16%                  ] 321 of 2000 complete in 297.6 sec
[------           16%                  ] 322 of 2000 complete in 298.4 sec
[------           16%                  ] 323 of 2000 complete in 299.2 sec
[------           16%                  ] 324 of 2000 complete in 299.9 sec
[------           16%                  ] 325 of 2000 complete in 300.7 sec
[------           16%                  ] 326 of 2000 complete in 301.5 sec
[------           16%                  ] 327 of 2000 complete in 302.3 sec
[------           16%                  ] 328 of 2000 complete in 303.1 sec
[------           16%                  ] 329 of 2000 complete in 303.9 sec
[------           16%                  ] 330 of 2000 complete in 304.7 sec
[------           16%                  ] 331 of 2000 complete in 305.5 sec
[----             11%                  ] 222 of 2000 complete in 224.9 sec
[----             11%                  ] 223 of 2000 complete in 225.7 sec
[----             11%                  ] 224 of 2000 complete in 226.5 sec
[----             11%                  ] 225 of 2000 complete in 227.3 sec
[----             11%                  ] 226 of 2000 complete in 228.2 sec
[----             11%                  ] 227 of 2000 complete in 229.0 sec
[----             11%                  ] 228 of 2000 complete in 229.8 sec
[----             11%                  ] 229 of 2000 complete in 230.6 sec
[----             11%                  ] 230 of 2000 complete in 231.4 sec
[----             11%                  ] 231 of 2000 complete in 232.1 sec
[----             11%                  ] 232 of 2000 complete in 232.9 sec
[----             11%                  ] 233 of 2000 complete in 233.8 sec
[----             11%                  ] 234 of 2000 complete in 234.6 sec
[----             11%                  ] 235 of 2000 complete in 235.5 sec
[----             11%                  ] 236 of 2000 complete in 236.3 sec
[----             11%                  ] 237 of 2000 complete in 237.1 sec
[----             11%                  ] 238 of 2000 complete in 238.0 sec
[----             11%                  ] 239 of 2000 complete in 238.8 sec
[----             12%                  ] 240 of 2000 complete in 239.7 sec
[----             12%                  ] 241 of 2000 complete in 240.5 sec
[----             12%                  ] 242 of 2000 complete in 241.4 sec
[----             12%                  ] 243 of 2000 complete in 242.3 sec
[----             12%                  ] 244 of 2000 complete in 243.1 sec
[----             12%                  ] 245 of 2000 complete in 244.0 sec
[----             12%                  ] 246 of 2000 complete in 244.9 sec
[----             12%                  ] 247 of 2000 complete in 245.8 sec
[----             12%                  ] 248 of 2000 complete in 246.6 sec
[----             12%                  ] 249 of 2000 complete in 247.5 sec
[----             12%                  ] 250 of 2000 complete in 248.3 sec
[----             12%                  ] 251 of 2000 complete in 249.1 sec
[----             12%                  ] 252 of 2000 complete in 250.0 sec
[----             12%                  ] 253 of 2000 complete in 250.8 sec
[----             12%                  ] 254 of 2000 complete in 251.6 sec
[----             12%                  ] 255 of 2000 complete in 252.4 sec
[----             12%                  ] 256 of 2000 complete in 253.2 sec
[----             12%                  ] 257 of 2000 complete in 254.0 sec
[----             12%                  ] 258 of 2000 complete in 254.7 sec
[----             12%                  ] 259 of 2000 complete in 255.6 sec
[----             13%                  ] 260 of 2000 complete in 256.4 sec
[----             13%                  ] 261 of 2000 complete in 257.1 sec
[----             13%                  ] 262 of 2000 complete in 258.0 sec
[----             13%                  ] 263 of 2000 complete in 258.7 sec
[-----            13%                  ] 264 of 2000 complete in 259.5 sec
[-----            13%                  ] 265 of 2000 complete in 260.3 sec
[-----            13%                  ] 266 of 2000 complete in 261.2 sec
[-----            13%                  ] 267 of 2000 complete in 262.0 sec
[-----            13%                  ] 268 of 2000 complete in 262.8 sec
[-----            13%                  ] 269 of 2000 complete in 263.6 sec
[-----            13%                  ] 270 of 2000 complete in 264.4 sec
[-----            13%                  ] 271 of 2000 complete in 265.2 sec
[-----            13%                  ] 272 of 2000 complete in 266.0 sec
[-----            13%                  ] 273 of 2000 complete in 266.8 sec
[-----            13%                  ] 274 of 2000 complete in 267.6 sec
[-----            13%                  ] 275 of 2000 complete in 268.4 sec
[-----            13%                  ] 276 of 2000 complete in 269.2 sec
[-----            13%                  ] 277 of 2000 complete in 270.0 sec
[-----            13%                  ] 278 of 2000 complete in 270.8 sec
[-----            13%                  ] 279 of 2000 complete in 271.6 sec
[-----            14%                  ] 280 of 2000 complete in 272.3 sec
[-----            14%                  ] 281 of 2000 complete in 273.1 sec
[-----            14%                  ] 282 of 2000 complete in 273.9 sec
[-----            14%                  ] 283 of 2000 complete in 274.6 sec
[-----            14%                  ] 284 of 2000 complete in 275.4 sec
[-----            14%                  ] 285 of 2000 complete in 276.2 sec
[-----            14%                  ] 286 of 2000 complete in 277.0 sec
[-----            14%                  ] 287 of 2000 complete in 277.8 sec
[-----            14%                  ] 288 of 2000 complete in 278.6 sec
[-----            14%                  ] 289 of 2000 complete in 279.4 sec
[-----            14%                  ] 290 of 2000 complete in 280.2 sec
[-----            14%                  ] 291 of 2000 complete in 281.0 sec
[-----            14%                  ] 292 of 2000 complete in 281.9 sec
[-----            14%                  ] 293 of 2000 complete in 282.7 sec
[-----            14%                  ] 294 of 2000 complete in 283.5 sec
[-----            14%                  ] 295 of 2000 complete in 284.3 sec
[-----            14%                  ] 296 of 2000 complete in 285.1 sec
[-----            14%                  ] 297 of 2000 complete in 285.9 sec
[-----            14%                  ] 298 of 2000 complete in 286.8 sec
[-----            14%                  ] 299 of 2000 complete in 287.6 sec
[-----            15%                  ] 300 of 2000 complete in 288.4 sec
[-----            15%                  ] 301 of 2000 complete in 289.2 sec
[-----            15%                  ] 302 of 2000 complete in 290.1 sec
[-----            15%                  ] 303 of 2000 complete in 290.9 sec
[-----            15%                  ] 304 of 2000 complete in 291.8 sec
[-----            15%                  ] 305 of 2000 complete in 292.6 sec
[-----            15%                  ] 306 of 2000 complete in 293.4 sec
[-----            15%                  ] 307 of 2000 complete in 294.3 sec
[-----            15%                  ] 308 of 2000 complete in 295.1 sec
[-----            15%                  ] 309 of 2000 complete in 295.9 sec
[-----            15%                  ] 310 of 2000 complete in 296.7 sec
[-----            15%                  ] 311 of 2000 complete in 297.5 sec
[-----            15%                  ] 312 of 2000 complete in 298.3 sec
[-----            15%                  ] 313 of 2000 complete in 299.1 sec
[-----            15%                  ] 314 of 2000 complete in 299.9 sec
[-----            15%                  ] 315 of 2000 complete in 300.7 sec
[------           15%                  ] 316 of 2000 complete in 301.6 sec
[------           15%                  ] 317 of 2000 complete in 302.4 sec
[------           15%                  ] 318 of 2000 complete in 303.2 sec
[------           15%                  ] 319 of 2000 complete in 304.0 sec
[------           16%                  ] 320 of 2000 complete in 304.8 sec
[------           16%                  ] 321 of 2000 complete in 305.7 sec
[------           16%                  ] 322 of 2000 complete in 306.5 sec
[------           16%                  ] 323 of 2000 complete in 307.3 sec
[------           16%                  ] 324 of 2000 complete in 308.2 sec
[------           16%                  ] 325 of 2000 complete in 309.0 sec
[------           16%                  ] 326 of 2000 complete in 309.8 sec
[------           16%                  ] 327 of 2000 complete in 310.7 sec
[------           16%                  ] 328 of 2000 complete in 311.5 sec
[------           16%                  ] 329 of 2000 complete in 312.3 sec
[------           16%                  ] 330 of 2000 complete in 313.1 sec

[----             11%                  ] 222 of 2000 complete in 233.4 sec
[----             11%                  ] 223 of 2000 complete in 234.4 sec
[----             11%                  ] 224 of 2000 complete in 235.4 sec
[----             11%                  ] 225 of 2000 complete in 236.4 sec
[----             11%                  ] 226 of 2000 complete in 237.4 sec
[----             11%                  ] 227 of 2000 complete in 238.3 sec
[----             11%                  ] 228 of 2000 complete in 239.3 sec
[----             11%                  ] 229 of 2000 complete in 240.3 sec
[----             11%                  ] 230 of 2000 complete in 241.2 sec
[----             11%                  ] 231 of 2000 complete in 242.2 sec
[----             11%                  ] 232 of 2000 complete in 243.1 sec
[----             11%                  ] 233 of 2000 complete in 244.0 sec
[----             11%                  ] 234 of 2000 complete in 244.9 sec
[----             11%                  ] 235 of 2000 complete in 245.8 sec
[----             11%                  ] 236 of 2000 complete in 246.7 sec
[----             11%                  ] 237 of 2000 complete in 247.7 sec
[----             11%                  ] 238 of 2000 complete in 248.7 sec
[----             11%                  ] 239 of 2000 complete in 249.6 sec
[----             12%                  ] 240 of 2000 complete in 250.5 sec
[----             12%                  ] 241 of 2000 complete in 251.5 sec
[----             12%                  ] 242 of 2000 complete in 252.4 sec
[----             12%                  ] 243 of 2000 complete in 253.3 sec
[----             12%                  ] 244 of 2000 complete in 254.3 sec
[----             12%                  ] 245 of 2000 complete in 255.2 sec
[----             12%                  ] 246 of 2000 complete in 256.1 sec
[----             12%                  ] 247 of 2000 complete in 257.0 sec
[----             12%                  ] 248 of 2000 complete in 257.9 sec
[----             12%                  ] 249 of 2000 complete in 258.9 sec
[----             12%                  ] 250 of 2000 complete in 259.7 sec
[----             12%                  ] 251 of 2000 complete in 260.7 sec
[----             12%                  ] 252 of 2000 complete in 261.7 sec
[----             12%                  ] 253 of 2000 complete in 262.7 sec
[----             12%                  ] 254 of 2000 complete in 263.7 sec
[----             12%                  ] 255 of 2000 complete in 264.6 sec
[----             12%                  ] 256 of 2000 complete in 265.6 sec
[----             12%                  ] 257 of 2000 complete in 266.6 sec
[----             12%                  ] 258 of 2000 complete in 267.5 sec
[----             12%                  ] 259 of 2000 complete in 268.5 sec
[----             13%                  ] 260 of 2000 complete in 269.4 sec
[----             13%                  ] 261 of 2000 complete in 270.4 sec
[----             13%                  ] 262 of 2000 complete in 271.3 sec
[----             13%                  ] 263 of 2000 complete in 272.2 sec
[-----            13%                  ] 264 of 2000 complete in 273.2 sec
[-----            13%                  ] 265 of 2000 complete in 274.1 sec
[-----            13%                  ] 266 of 2000 complete in 275.1 sec
[-----            13%                  ] 267 of 2000 complete in 276.0 sec
[-----            13%                  ] 268 of 2000 complete in 276.9 sec
[-----            13%                  ] 269 of 2000 complete in 277.8 sec
[-----            13%                  ] 270 of 2000 complete in 278.7 sec
[-----            13%                  ] 271 of 2000 complete in 279.6 sec
[-----            13%                  ] 272 of 2000 complete in 280.6 sec
[-----            13%                  ] 273 of 2000 complete in 281.5 sec
[-----            13%                  ] 274 of 2000 complete in 282.4 sec
[-----            13%                  ] 275 of 2000 complete in 283.3 sec
[-----            13%                  ] 276 of 2000 complete in 284.2 sec
[-----            13%                  ] 277 of 2000 complete in 285.1 sec
[-----            13%                  ] 278 of 2000 complete in 286.0 sec
[-----            13%                  ] 279 of 2000 complete in 286.9 sec
[-----            14%                  ] 280 of 2000 complete in 287.8 sec
[-----            14%                  ] 281 of 2000 complete in 288.7 sec
[-----            14%                  ] 282 of 2000 complete in 289.6 sec
[-----            14%                  ] 283 of 2000 complete in 290.5 sec
[-----            14%                  ] 284 of 2000 complete in 291.4 sec
[-----            14%                  ] 285 of 2000 complete in 292.3 sec
[-----            14%                  ] 286 of 2000 complete in 293.2 sec
[-----            14%                  ] 287 of 2000 complete in 294.0 sec
[-----            14%                  ] 288 of 2000 complete in 294.9 sec
[-----            14%                  ] 289 of 2000 complete in 295.8 sec
[-----            14%                  ] 290 of 2000 complete in 296.6 sec
[-----            14%                  ] 291 of 2000 complete in 297.4 sec
[-----            14%                  ] 292 of 2000 complete in 298.2 sec
[-----            14%                  ] 293 of 2000 complete in 299.1 sec
[-----            14%                  ] 294 of 2000 complete in 299.9 sec
[-----            14%                  ] 295 of 2000 complete in 300.7 sec
[-----            14%                  ] 296 of 2000 complete in 301.6 sec
[-----            14%                  ] 297 of 2000 complete in 302.5 sec
[-----            14%                  ] 298 of 2000 complete in 303.4 sec
[-----            14%                  ] 299 of 2000 complete in 304.2 sec
[-----            15%                  ] 300 of 2000 complete in 305.0 sec
[-----            15%                  ] 301 of 2000 complete in 305.9 sec
[-----            15%                  ] 302 of 2000 complete in 306.8 sec
[-----            15%                  ] 303 of 2000 complete in 307.6 sec
[-----            15%                  ] 304 of 2000 complete in 308.5 sec
[-----            15%                  ] 305 of 2000 complete in 309.4 sec
[-----            15%                  ] 306 of 2000 complete in 310.3 sec
[-----            15%                  ] 307 of 2000 complete in 311.2 sec
[-----            15%                  ] 308 of 2000 complete in 312.0 sec
[-----            15%                  ] 309 of 2000 complete in 312.9 sec
[-----            15%                  ] 310 of 2000 complete in 313.9 sec
[-----            15%                  ] 311 of 2000 complete in 314.7 sec
[-----            15%                  ] 312 of 2000 complete in 315.6 sec
[-----            15%                  ] 313 of 2000 complete in 316.5 sec
[-----            15%                  ] 314 of 2000 complete in 317.4 sec
[-----            15%                  ] 315 of 2000 complete in 318.3 sec
[------           15%                  ] 316 of 2000 complete in 319.2 sec
[------           15%                  ] 317 of 2000 complete in 320.0 sec
[------           15%                  ] 318 of 2000 complete in 320.9 sec
[------           15%                  ] 319 of 2000 complete in 321.7 sec
[------           16%                  ] 320 of 2000 complete in 322.6 sec
[------           16%                  ] 321 of 2000 complete in 323.5 sec
[------           16%                  ] 322 of 2000 complete in 324.4 sec
[------           16%                  ] 323 of 2000 complete in 325.3 sec
[------           16%                  ] 324 of 2000 complete in 326.1 sec
[------           16%                  ] 325 of 2000 complete in 327.0 sec
[------           16%                  ] 326 of 2000 complete in 327.9 sec
[------           16%                  ] 327 of 2000 complete in 328.7 sec
[------           16%                  ] 328 of 2000 complete in 329.5 sec
[------           16%                  ] 329 of 2000 complete in 330.4 sec
[------           16%                  ] 330 of 2000 complete in 331.3 sec
[----             11%                  ] 222 of 2000 complete in 242.0 sec
[----             11%                  ] 223 of 2000 complete in 243.0 sec
[----             11%                  ] 224 of 2000 complete in 244.0 sec
[----             11%                  ] 225 of 2000 complete in 245.0 sec
[----             11%                  ] 226 of 2000 complete in 246.1 sec
[----             11%                  ] 227 of 2000 complete in 247.1 sec
[----             11%                  ] 228 of 2000 complete in 248.2 sec
[----             11%                  ] 229 of 2000 complete in 249.2 sec
[----             11%                  ] 230 of 2000 complete in 250.2 sec
[----             11%                  ] 231 of 2000 complete in 251.2 sec
[----             11%                  ] 232 of 2000 complete in 252.2 sec
[----             11%                  ] 233 of 2000 complete in 253.2 sec
[----             11%                  ] 234 of 2000 complete in 254.2 sec
[----             11%                  ] 235 of 2000 complete in 255.2 sec
[----             11%                  ] 236 of 2000 complete in 256.2 sec
[----             11%                  ] 237 of 2000 complete in 257.2 sec
[----             11%                  ] 238 of 2000 complete in 258.2 sec
[----             11%                  ] 239 of 2000 complete in 259.2 sec
[----             12%                  ] 240 of 2000 complete in 260.2 sec
[----             12%                  ] 241 of 2000 complete in 261.1 sec
[----             12%                  ] 242 of 2000 complete in 262.2 sec
[----             12%                  ] 243 of 2000 complete in 263.1 sec
[----             12%                  ] 244 of 2000 complete in 264.1 sec
[----             12%                  ] 245 of 2000 complete in 265.1 sec
[----             12%                  ] 246 of 2000 complete in 266.1 sec
[----             12%                  ] 247 of 2000 complete in 267.0 sec
[----             12%                  ] 248 of 2000 complete in 267.9 sec
[----             12%                  ] 249 of 2000 complete in 268.9 sec
[----             12%                  ] 250 of 2000 complete in 269.8 sec
[----             12%                  ] 251 of 2000 complete in 270.7 sec
[----             12%                  ] 252 of 2000 complete in 271.6 sec
[----             12%                  ] 253 of 2000 complete in 272.5 sec
[----             12%                  ] 254 of 2000 complete in 273.4 sec
[----             12%                  ] 255 of 2000 complete in 274.3 sec
[----             12%                  ] 256 of 2000 complete in 275.2 sec
[----             12%                  ] 257 of 2000 complete in 276.1 sec
[----             12%                  ] 258 of 2000 complete in 277.0 sec
[----             12%                  ] 259 of 2000 complete in 277.9 sec
[----             13%                  ] 260 of 2000 complete in 278.8 sec
[----             13%                  ] 261 of 2000 complete in 279.7 sec
[----             13%                  ] 262 of 2000 complete in 280.5 sec
[----             13%                  ] 263 of 2000 complete in 281.4 sec
[-----            13%                  ] 264 of 2000 complete in 282.3 sec
[-----            13%                  ] 265 of 2000 complete in 283.1 sec
[-----            13%                  ] 266 of 2000 complete in 284.1 sec
[-----            13%                  ] 267 of 2000 complete in 285.0 sec
[-----            13%                  ] 268 of 2000 complete in 285.8 sec
[-----            13%                  ] 269 of 2000 complete in 286.7 sec
[-----            13%                  ] 270 of 2000 complete in 287.6 sec
[-----            13%                  ] 271 of 2000 complete in 288.5 sec
[-----            13%                  ] 272 of 2000 complete in 289.4 sec
[-----            13%                  ] 273 of 2000 complete in 290.3 sec
[-----            13%                  ] 274 of 2000 complete in 291.2 sec
[-----            13%                  ] 275 of 2000 complete in 292.1 sec
[-----            13%                  ] 276 of 2000 complete in 293.0 sec
[-----            13%                  ] 277 of 2000 complete in 293.8 sec
[-----            13%                  ] 278 of 2000 complete in 294.7 sec
[-----            13%                  ] 279 of 2000 complete in 295.6 sec
[-----            14%                  ] 280 of 2000 complete in 296.5 sec
[-----            14%                  ] 281 of 2000 complete in 297.4 sec
[-----            14%                  ] 282 of 2000 complete in 298.2 sec
[-----            14%                  ] 283 of 2000 complete in 299.1 sec
[-----            14%                  ] 284 of 2000 complete in 300.0 sec
[-----            14%                  ] 285 of 2000 complete in 300.9 sec
[-----            14%                  ] 286 of 2000 complete in 301.8 sec
[-----            14%                  ] 287 of 2000 complete in 302.7 sec
[-----            14%                  ] 288 of 2000 complete in 303.7 sec
[-----            14%                  ] 289 of 2000 complete in 304.6 sec
[-----            14%                  ] 290 of 2000 complete in 305.4 sec
[-----            14%                  ] 291 of 2000 complete in 306.3 sec
[-----            14%                  ] 292 of 2000 complete in 307.2 sec
[-----            14%                  ] 293 of 2000 complete in 308.1 sec
[-----            14%                  ] 294 of 2000 complete in 309.0 sec
[-----            14%                  ] 295 of 2000 complete in 309.9 sec
[-----            14%                  ] 296 of 2000 complete in 310.8 sec
[-----            14%                  ] 297 of 2000 complete in 311.7 sec
[-----            14%                  ] 298 of 2000 complete in 312.6 sec
[-----            14%                  ] 299 of 2000 complete in 313.5 sec
[-----            15%                  ] 300 of 2000 complete in 314.5 sec
[-----            15%                  ] 301 of 2000 complete in 315.4 sec
[-----            15%                  ] 302 of 2000 complete in 316.3 sec
[-----            15%                  ] 303 of 2000 complete in 317.2 sec
[-----            15%                  ] 304 of 2000 complete in 318.0 sec
[-----            15%                  ] 305 of 2000 complete in 318.9 sec
[-----            15%                  ] 306 of 2000 complete in 319.8 sec
[-----            15%                  ] 307 of 2000 complete in 320.7 sec
[-----            15%                  ] 308 of 2000 complete in 321.5 sec
[-----            15%                  ] 309 of 2000 complete in 322.4 sec
[-----            15%                  ] 310 of 2000 complete in 323.2 sec
[-----            15%                  ] 311 of 2000 complete in 324.0 sec
[-----            15%                  ] 312 of 2000 complete in 324.8 sec
[-----            15%                  ] 313 of 2000 complete in 325.7 sec
[-----            15%                  ] 314 of 2000 complete in 326.5 sec
[-----            15%                  ] 315 of 2000 complete in 327.3 sec
[------           15%                  ] 316 of 2000 complete in 328.2 sec
[------           15%                  ] 317 of 2000 complete in 329.0 sec
[------           15%                  ] 318 of 2000 complete in 329.7 sec
[------           15%                  ] 319 of 2000 complete in 330.5 sec
[------           16%                  ] 320 of 2000 complete in 331.3 sec
[------           16%                  ] 321 of 2000 complete in 332.1 sec
[------           16%                  ] 322 of 2000 complete in 332.9 sec
[------           16%                  ] 323 of 2000 complete in 333.8 sec
[------           16%                  ] 324 of 2000 complete in 334.6 sec
[------           16%                  ] 325 of 2000 complete in 335.4 sec
[------           16%                  ] 326 of 2000 complete in 336.2 sec
[------           16%                  ] 327 of 2000 complete in 337.0 sec
[------           16%                  ] 328 of 2000 complete in 337.8 sec
[------           16%                  ] 329 of 2000 complete in 338.6 sec
[------           16%                  ] 330 of 2000 complete in 339.4 sec

[------           16%                  ] 332 of 2000 complete in 306.2 sec
[------           16%                  ] 333 of 2000 complete in 307.0 sec
[------           16%                  ] 334 of 2000 complete in 307.8 sec
[------           16%                  ] 335 of 2000 complete in 308.5 sec
[------           16%                  ] 336 of 2000 complete in 309.3 sec
[------           16%                  ] 337 of 2000 complete in 310.1 sec
[------           16%                  ] 338 of 2000 complete in 310.8 sec
[------           16%                  ] 339 of 2000 complete in 311.6 sec
[------           17%                  ] 340 of 2000 complete in 312.4 sec
[------           17%                  ] 341 of 2000 complete in 313.1 sec
[------           17%                  ] 342 of 2000 complete in 313.9 sec
[------           17%                  ] 343 of 2000 complete in 314.7 sec
[------           17%                  ] 344 of 2000 complete in 315.4 sec
[------           17%                  ] 345 of 2000 complete in 316.2 sec
[------           17%                  ] 346 of 2000 complete in 317.0 sec
[------           17%                  ] 347 of 2000 complete in 317.8 sec
[------           17%                  ] 348 of 2000 complete in 318.6 sec
[------           17%                  ] 349 of 2000 complete in 319.4 sec
[------           17%                  ] 350 of 2000 complete in 320.2 sec
[------           17%                  ] 351 of 2000 complete in 320.9 sec
[------           17%                  ] 352 of 2000 complete in 321.7 sec
[------           17%                  ] 353 of 2000 complete in 322.4 sec
[------           17%                  ] 354 of 2000 complete in 323.2 sec
[------           17%                  ] 355 of 2000 complete in 323.9 sec
[------           17%                  ] 356 of 2000 complete in 324.6 sec
[------           17%                  ] 357 of 2000 complete in 325.4 sec
[------           17%                  ] 358 of 2000 complete in 326.1 sec
[------           17%                  ] 359 of 2000 complete in 326.9 sec
[------           18%                  ] 360 of 2000 complete in 327.6 sec
[------           18%                  ] 361 of 2000 complete in 328.4 sec
[------           18%                  ] 362 of 2000 complete in 329.0 sec
[------           18%                  ] 363 of 2000 complete in 329.7 sec
[------           18%                  ] 364 of 2000 complete in 330.4 sec
[------           18%                  ] 365 of 2000 complete in 331.1 sec
[------           18%                  ] 366 of 2000 complete in 331.8 sec
[------           18%                  ] 367 of 2000 complete in 332.5 sec
[------           18%                  ] 368 of 2000 complete in 333.2 sec
[-------          18%                  ] 369 of 2000 complete in 333.9 sec
[-------          18%                  ] 370 of 2000 complete in 334.7 sec
[-------          18%                  ] 371 of 2000 complete in 335.4 sec
[-------          18%                  ] 372 of 2000 complete in 336.1 sec
[-------          18%                  ] 373 of 2000 complete in 336.8 sec
[-------          18%                  ] 374 of 2000 complete in 337.5 sec
[-------          18%                  ] 375 of 2000 complete in 338.2 sec
[-------          18%                  ] 376 of 2000 complete in 339.0 sec
[-------          18%                  ] 377 of 2000 complete in 339.7 sec
[-------          18%                  ] 378 of 2000 complete in 340.4 sec
[-------          18%                  ] 379 of 2000 complete in 341.1 sec
[-------          19%                  ] 380 of 2000 complete in 341.8 sec
[-------          19%                  ] 381 of 2000 complete in 342.6 sec
[-------          19%                  ] 382 of 2000 complete in 343.3 sec
[-------          19%                  ] 383 of 2000 complete in 344.0 sec
[-------          19%                  ] 384 of 2000 complete in 344.7 sec
[-------          19%                  ] 385 of 2000 complete in 345.4 sec
[-------          19%                  ] 386 of 2000 complete in 346.1 sec
[-------          19%                  ] 387 of 2000 complete in 346.9 sec
[-------          19%                  ] 388 of 2000 complete in 347.6 sec
[-------          19%                  ] 389 of 2000 complete in 348.4 sec
[-------          19%                  ] 390 of 2000 complete in 349.1 sec
[-------          19%                  ] 391 of 2000 complete in 349.8 sec
[-------          19%                  ] 392 of 2000 complete in 350.5 sec
[-------          19%                  ] 393 of 2000 complete in 351.3 sec
[-------          19%                  ] 394 of 2000 complete in 351.9 sec
[-------          19%                  ] 395 of 2000 complete in 352.6 sec
[-------          19%                  ] 396 of 2000 complete in 353.3 sec
[-------          19%                  ] 397 of 2000 complete in 354.0 sec
[-------          19%                  ] 398 of 2000 complete in 354.7 sec
[-------          19%                  ] 399 of 2000 complete in 355.4 sec
[-------          20%                  ] 400 of 2000 complete in 356.0 sec
[-------          20%                  ] 401 of 2000 complete in 356.7 sec
[-------          20%                  ] 402 of 2000 complete in 357.4 sec
[-------          20%                  ] 403 of 2000 complete in 358.1 sec
[-------          20%                  ] 404 of 2000 complete in 358.8 sec
[-------          20%                  ] 405 of 2000 complete in 359.5 sec
[-------          20%                  ] 406 of 2000 complete in 360.2 sec
[-------          20%                  ] 407 of 2000 complete in 360.9 sec
[-------          20%                  ] 408 of 2000 complete in 361.6 sec
[-------          20%                  ] 409 of 2000 complete in 362.3 sec
[-------          20%                  ] 410 of 2000 complete in 363.0 sec
[-------          20%                  ] 411 of 2000 complete in 363.7 sec
[-------          20%                  ] 412 of 2000 complete in 364.4 sec
[-------          20%                  ] 413 of 2000 complete in 365.1 sec
[-------          20%                  ] 414 of 2000 complete in 365.8 sec
[-------          20%                  ] 415 of 2000 complete in 366.4 sec
[-------          20%                  ] 416 of 2000 complete in 367.1 sec
[-------          20%                  ] 417 of 2000 complete in 367.8 sec
[-------          20%                  ] 418 of 2000 complete in 368.5 sec
[-------          20%                  ] 419 of 2000 complete in 369.2 sec
[-------          21%                  ] 420 of 2000 complete in 370.0 sec
[-------          21%                  ] 421 of 2000 complete in 370.7 sec
[--------         21%                  ] 422 of 2000 complete in 371.4 sec
[--------         21%                  ] 423 of 2000 complete in 372.1 sec
[--------         21%                  ] 424 of 2000 complete in 372.8 sec
[--------         21%                  ] 425 of 2000 complete in 373.6 sec
[--------         21%                  ] 426 of 2000 complete in 374.3 sec
[--------         21%                  ] 427 of 2000 complete in 375.0 sec
[--------         21%                  ] 428 of 2000 complete in 375.7 sec
[--------         21%                  ] 429 of 2000 complete in 376.5 sec
[--------         21%                  ] 430 of 2000 complete in 377.2 sec
[--------         21%                  ] 431 of 2000 complete in 377.9 sec
[--------         21%                  ] 432 of 2000 complete in 378.7 sec
[--------         21%                  ] 433 of 2000 complete in 379.4 sec
[--------         21%                  ] 434 of 2000 complete in 380.1 sec
[--------         21%                  ] 435 of 2000 complete in 380.9 sec
[--------         21%                  ] 436 of 2000 complete in 381.6 sec
[--------         21%                  ] 437 of 2000 complete in 382.4 sec
[--------         21%                  ] 438 of 2000 complete in 383.1 sec
[--------         21%                  ] 439 of 2000 complete in 383.9 sec
[--------         22%                  ] 440 of 2000 complete in 384.6 sec
[------           16%                  ] 331 of 2000 complete in 313.8 sec
[------           16%                  ] 332 of 2000 complete in 314.6 sec
[------           16%                  ] 333 of 2000 complete in 315.4 sec
[------           16%                  ] 334 of 2000 complete in 316.2 sec
[------           16%                  ] 335 of 2000 complete in 317.0 sec
[------           16%                  ] 336 of 2000 complete in 317.8 sec
[------           16%                  ] 337 of 2000 complete in 318.6 sec
[------           16%                  ] 338 of 2000 complete in 319.4 sec
[------           16%                  ] 339 of 2000 complete in 320.2 sec
[------           17%                  ] 340 of 2000 complete in 321.1 sec
[------           17%                  ] 341 of 2000 complete in 321.8 sec
[------           17%                  ] 342 of 2000 complete in 322.6 sec
[------           17%                  ] 343 of 2000 complete in 323.4 sec
[------           17%                  ] 344 of 2000 complete in 324.2 sec
[------           17%                  ] 345 of 2000 complete in 324.9 sec
[------           17%                  ] 346 of 2000 complete in 325.7 sec
[------           17%                  ] 347 of 2000 complete in 326.4 sec
[------           17%                  ] 348 of 2000 complete in 327.2 sec
[------           17%                  ] 349 of 2000 complete in 327.9 sec
[------           17%                  ] 350 of 2000 complete in 328.6 sec
[------           17%                  ] 351 of 2000 complete in 329.4 sec
[------           17%                  ] 352 of 2000 complete in 330.1 sec
[------           17%                  ] 353 of 2000 complete in 330.9 sec
[------           17%                  ] 354 of 2000 complete in 331.6 sec
[------           17%                  ] 355 of 2000 complete in 332.3 sec
[------           17%                  ] 356 of 2000 complete in 333.0 sec
[------           17%                  ] 357 of 2000 complete in 333.7 sec
[------           17%                  ] 358 of 2000 complete in 334.4 sec
[------           17%                  ] 359 of 2000 complete in 335.2 sec
[------           18%                  ] 360 of 2000 complete in 335.9 sec
[------           18%                  ] 361 of 2000 complete in 336.6 sec
[------           18%                  ] 362 of 2000 complete in 337.3 sec
[------           18%                  ] 363 of 2000 complete in 338.0 sec
[------           18%                  ] 364 of 2000 complete in 338.7 sec
[------           18%                  ] 365 of 2000 complete in 339.4 sec
[------           18%                  ] 366 of 2000 complete in 340.1 sec
[------           18%                  ] 367 of 2000 complete in 340.9 sec
[------           18%                  ] 368 of 2000 complete in 341.6 sec
[-------          18%                  ] 369 of 2000 complete in 342.3 sec
[-------          18%                  ] 370 of 2000 complete in 343.0 sec
[-------          18%                  ] 371 of 2000 complete in 343.7 sec
[-------          18%                  ] 372 of 2000 complete in 344.4 sec
[-------          18%                  ] 373 of 2000 complete in 345.1 sec
[-------          18%                  ] 374 of 2000 complete in 345.8 sec
[-------          18%                  ] 375 of 2000 complete in 346.6 sec
[-------          18%                  ] 376 of 2000 complete in 347.3 sec
[-------          18%                  ] 377 of 2000 complete in 348.1 sec
[-------          18%                  ] 378 of 2000 complete in 348.8 sec
[-------          18%                  ] 379 of 2000 complete in 349.5 sec
[-------          19%                  ] 380 of 2000 complete in 350.3 sec
[-------          19%                  ] 381 of 2000 complete in 351.0 sec
[-------          19%                  ] 382 of 2000 complete in 351.8 sec
[-------          19%                  ] 383 of 2000 complete in 352.5 sec
[-------          19%                  ] 384 of 2000 complete in 353.3 sec
[-------          19%                  ] 385 of 2000 complete in 354.0 sec
[-------          19%                  ] 386 of 2000 complete in 354.7 sec
[-------          19%                  ] 387 of 2000 complete in 355.4 sec
[-------          19%                  ] 388 of 2000 complete in 356.2 sec
[-------          19%                  ] 389 of 2000 complete in 356.9 sec
[-------          19%                  ] 390 of 2000 complete in 357.6 sec
[-------          19%                  ] 391 of 2000 complete in 358.4 sec
[-------          19%                  ] 392 of 2000 complete in 359.1 sec
[-------          19%                  ] 393 of 2000 complete in 359.8 sec
[-------          19%                  ] 394 of 2000 complete in 360.5 sec
[-------          19%                  ] 395 of 2000 complete in 361.3 sec
[-------          19%                  ] 396 of 2000 complete in 362.0 sec
[-------          19%                  ] 397 of 2000 complete in 362.7 sec
[-------          19%                  ] 398 of 2000 complete in 363.4 sec
[-------          19%                  ] 399 of 2000 complete in 364.1 sec
[-------          20%                  ] 400 of 2000 complete in 364.8 sec
[-------          20%                  ] 401 of 2000 complete in 365.5 sec
[-------          20%                  ] 402 of 2000 complete in 366.3 sec
[-------          20%                  ] 403 of 2000 complete in 367.0 sec
[-------          20%                  ] 404 of 2000 complete in 367.7 sec
[-------          20%                  ] 405 of 2000 complete in 368.4 sec
[-------          20%                  ] 406 of 2000 complete in 369.1 sec
[-------          20%                  ] 407 of 2000 complete in 369.8 sec
[-------          20%                  ] 408 of 2000 complete in 370.5 sec
[-------          20%                  ] 409 of 2000 complete in 371.2 sec
[-------          20%                  ] 410 of 2000 complete in 371.9 sec
[-------          20%                  ] 411 of 2000 complete in 372.6 sec
[-------          20%                  ] 412 of 2000 complete in 373.3 sec
[-------          20%                  ] 413 of 2000 complete in 374.0 sec
[-------          20%                  ] 414 of 2000 complete in 374.6 sec
[-------          20%                  ] 415 of 2000 complete in 375.3 sec
[-------          20%                  ] 416 of 2000 complete in 376.0 sec
[-------          20%                  ] 417 of 2000 complete in 376.7 sec
[-------          20%                  ] 418 of 2000 complete in 377.4 sec
[-------          20%                  ] 419 of 2000 complete in 378.2 sec
[-------          21%                  ] 420 of 2000 complete in 378.9 sec
[-------          21%                  ] 421 of 2000 complete in 379.6 sec
[--------         21%                  ] 422 of 2000 complete in 380.4 sec
[--------         21%                  ] 423 of 2000 complete in 381.1 sec
[--------         21%                  ] 424 of 2000 complete in 381.8 sec
[--------         21%                  ] 425 of 2000 complete in 382.5 sec
[--------         21%                  ] 426 of 2000 complete in 383.3 sec
[--------         21%                  ] 427 of 2000 complete in 384.0 sec
[--------         21%                  ] 428 of 2000 complete in 384.7 sec
[--------         21%                  ] 429 of 2000 complete in 385.5 sec
[--------         21%                  ] 430 of 2000 complete in 386.2 sec
[--------         21%                  ] 431 of 2000 complete in 386.9 sec
[--------         21%                  ] 432 of 2000 complete in 387.6 sec
[--------         21%                  ] 433 of 2000 complete in 388.4 sec
[--------         21%                  ] 434 of 2000 complete in 389.1 sec
[--------         21%                  ] 435 of 2000 complete in 389.9 sec
[--------         21%                  ] 436 of 2000 complete in 390.7 sec
[--------         21%                  ] 437 of 2000 complete in 391.4 sec
[--------         21%                  ] 438 of 2000 complete in 392.1 sec
[--------         21%                  ] 439 of 2000 complete in 392.9 sec

[------           16%                  ] 331 of 2000 complete in 332.1 sec
[------           16%                  ] 332 of 2000 complete in 332.9 sec
[------           16%                  ] 333 of 2000 complete in 333.8 sec
[------           16%                  ] 334 of 2000 complete in 334.6 sec
[------           16%                  ] 335 of 2000 complete in 335.4 sec
[------           16%                  ] 336 of 2000 complete in 336.3 sec
[------           16%                  ] 337 of 2000 complete in 337.1 sec
[------           16%                  ] 338 of 2000 complete in 337.9 sec
[------           16%                  ] 339 of 2000 complete in 338.8 sec
[------           17%                  ] 340 of 2000 complete in 339.6 sec
[------           17%                  ] 341 of 2000 complete in 340.5 sec
[------           17%                  ] 342 of 2000 complete in 341.3 sec
[------           17%                  ] 343 of 2000 complete in 342.1 sec
[------           17%                  ] 344 of 2000 complete in 343.0 sec
[------           17%                  ] 345 of 2000 complete in 343.8 sec
[------           17%                  ] 346 of 2000 complete in 344.6 sec
[------           17%                  ] 347 of 2000 complete in 345.4 sec
[------           17%                  ] 348 of 2000 complete in 346.3 sec
[------           17%                  ] 349 of 2000 complete in 347.2 sec
[------           17%                  ] 350 of 2000 complete in 348.1 sec
[------           17%                  ] 351 of 2000 complete in 349.0 sec
[------           17%                  ] 352 of 2000 complete in 349.9 sec
[------           17%                  ] 353 of 2000 complete in 350.8 sec
[------           17%                  ] 354 of 2000 complete in 351.6 sec
[------           17%                  ] 355 of 2000 complete in 352.5 sec
[------           17%                  ] 356 of 2000 complete in 353.4 sec
[------           17%                  ] 357 of 2000 complete in 354.3 sec
[------           17%                  ] 358 of 2000 complete in 355.2 sec
[------           17%                  ] 359 of 2000 complete in 356.1 sec
[------           18%                  ] 360 of 2000 complete in 357.0 sec
[------           18%                  ] 361 of 2000 complete in 357.9 sec
[------           18%                  ] 362 of 2000 complete in 358.9 sec
[------           18%                  ] 363 of 2000 complete in 359.8 sec
[------           18%                  ] 364 of 2000 complete in 360.8 sec
[------           18%                  ] 365 of 2000 complete in 361.7 sec
[------           18%                  ] 366 of 2000 complete in 362.7 sec
[------           18%                  ] 367 of 2000 complete in 363.6 sec
[------           18%                  ] 368 of 2000 complete in 364.5 sec
[-------          18%                  ] 369 of 2000 complete in 365.5 sec
[-------          18%                  ] 370 of 2000 complete in 366.4 sec
[-------          18%                  ] 371 of 2000 complete in 367.3 sec
[-------          18%                  ] 372 of 2000 complete in 368.3 sec
[-------          18%                  ] 373 of 2000 complete in 369.2 sec
[-------          18%                  ] 374 of 2000 complete in 370.2 sec
[-------          18%                  ] 375 of 2000 complete in 371.2 sec
[-------          18%                  ] 376 of 2000 complete in 372.2 sec
[-------          18%                  ] 377 of 2000 complete in 373.2 sec
[-------          18%                  ] 378 of 2000 complete in 374.2 sec
[-------          18%                  ] 379 of 2000 complete in 375.3 sec
[-------          19%                  ] 380 of 2000 complete in 376.3 sec
[-------          19%                  ] 381 of 2000 complete in 377.2 sec
[-------          19%                  ] 382 of 2000 complete in 378.2 sec
[-------          19%                  ] 383 of 2000 complete in 379.2 sec
[-------          19%                  ] 384 of 2000 complete in 380.3 sec
[-------          19%                  ] 385 of 2000 complete in 381.3 sec
[-------          19%                  ] 386 of 2000 complete in 382.3 sec
[-------          19%                  ] 387 of 2000 complete in 383.4 sec
[-------          19%                  ] 388 of 2000 complete in 384.4 sec
[-------          19%                  ] 389 of 2000 complete in 385.5 sec
[-------          19%                  ] 390 of 2000 complete in 386.5 sec
[-------          19%                  ] 391 of 2000 complete in 387.5 sec
[-------          19%                  ] 392 of 2000 complete in 388.5 sec
[-------          19%                  ] 393 of 2000 complete in 389.5 sec
[-------          19%                  ] 394 of 2000 complete in 390.4 sec
[-------          19%                  ] 395 of 2000 complete in 391.4 sec
[-------          19%                  ] 396 of 2000 complete in 392.4 sec
[-------          19%                  ] 397 of 2000 complete in 393.4 sec
[-------          19%                  ] 398 of 2000 complete in 394.4 sec
[-------          19%                  ] 399 of 2000 complete in 395.4 sec
[-------          20%                  ] 400 of 2000 complete in 396.4 sec
[-------          20%                  ] 401 of 2000 complete in 397.3 sec
[-------          20%                  ] 402 of 2000 complete in 398.3 sec
[-------          20%                  ] 403 of 2000 complete in 399.3 sec
[-------          20%                  ] 404 of 2000 complete in 400.2 sec
[-------          20%                  ] 405 of 2000 complete in 401.2 sec
[-------          20%                  ] 406 of 2000 complete in 402.3 sec
[-------          20%                  ] 407 of 2000 complete in 403.3 sec
[-------          20%                  ] 408 of 2000 complete in 404.3 sec
[-------          20%                  ] 409 of 2000 complete in 405.2 sec
[-------          20%                  ] 410 of 2000 complete in 406.2 sec
[-------          20%                  ] 411 of 2000 complete in 407.3 sec
[-------          20%                  ] 412 of 2000 complete in 408.3 sec
[-------          20%                  ] 413 of 2000 complete in 409.4 sec
[-------          20%                  ] 414 of 2000 complete in 410.3 sec
[-------          20%                  ] 415 of 2000 complete in 411.2 sec
[-------          20%                  ] 416 of 2000 complete in 412.2 sec
[-------          20%                  ] 417 of 2000 complete in 413.1 sec
[-------          20%                  ] 418 of 2000 complete in 414.0 sec
[-------          20%                  ] 419 of 2000 complete in 414.9 sec
[-------          21%                  ] 420 of 2000 complete in 415.8 sec
[-------          21%                  ] 421 of 2000 complete in 416.7 sec
[--------         21%                  ] 422 of 2000 complete in 417.6 sec
[--------         21%                  ] 423 of 2000 complete in 418.5 sec
[--------         21%                  ] 424 of 2000 complete in 419.5 sec
[--------         21%                  ] 425 of 2000 complete in 420.4 sec
[--------         21%                  ] 426 of 2000 complete in 421.3 sec
[--------         21%                  ] 427 of 2000 complete in 422.3 sec
[--------         21%                  ] 428 of 2000 complete in 423.3 sec
[--------         21%                  ] 429 of 2000 complete in 424.2 sec
[--------         21%                  ] 430 of 2000 complete in 425.2 sec
[--------         21%                  ] 431 of 2000 complete in 426.1 sec
[--------         21%                  ] 432 of 2000 complete in 427.1 sec
[--------         21%                  ] 433 of 2000 complete in 428.0 sec
[--------         21%                  ] 434 of 2000 complete in 429.0 sec
[--------         21%                  ] 435 of 2000 complete in 429.9 sec
[--------         21%                  ] 436 of 2000 complete in 430.8 sec
[--------         21%                  ] 437 of 2000 complete in 431.8 sec
[--------         21%                  ] 438 of 2000 complete in 432.8 sec
[--------         21%                  ] 439 of 2000 complete in 433.7 sec
[------           16%                  ] 331 of 2000 complete in 340.3 sec
[------           16%                  ] 332 of 2000 complete in 341.0 sec
[------           16%                  ] 333 of 2000 complete in 341.8 sec
[------           16%                  ] 334 of 2000 complete in 342.6 sec
[------           16%                  ] 335 of 2000 complete in 343.5 sec
[------           16%                  ] 336 of 2000 complete in 344.3 sec
[------           16%                  ] 337 of 2000 complete in 345.1 sec
[------           16%                  ] 338 of 2000 complete in 346.0 sec
[------           16%                  ] 339 of 2000 complete in 346.8 sec
[------           17%                  ] 340 of 2000 complete in 347.6 sec
[------           17%                  ] 341 of 2000 complete in 348.5 sec
[------           17%                  ] 342 of 2000 complete in 349.3 sec
[------           17%                  ] 343 of 2000 complete in 350.2 sec
[------           17%                  ] 344 of 2000 complete in 351.0 sec
[------           17%                  ] 345 of 2000 complete in 351.9 sec
[------           17%                  ] 346 of 2000 complete in 352.7 sec
[------           17%                  ] 347 of 2000 complete in 353.5 sec
[------           17%                  ] 348 of 2000 complete in 354.4 sec
[------           17%                  ] 349 of 2000 complete in 355.2 sec
[------           17%                  ] 350 of 2000 complete in 356.0 sec
[------           17%                  ] 351 of 2000 complete in 356.8 sec
[------           17%                  ] 352 of 2000 complete in 357.7 sec
[------           17%                  ] 353 of 2000 complete in 358.6 sec
[------           17%                  ] 354 of 2000 complete in 359.4 sec
[------           17%                  ] 355 of 2000 complete in 360.3 sec
[------           17%                  ] 356 of 2000 complete in 361.2 sec
[------           17%                  ] 357 of 2000 complete in 362.0 sec
[------           17%                  ] 358 of 2000 complete in 362.9 sec
[------           17%                  ] 359 of 2000 complete in 363.7 sec
[------           18%                  ] 360 of 2000 complete in 364.5 sec
[------           18%                  ] 361 of 2000 complete in 365.4 sec
[------           18%                  ] 362 of 2000 complete in 366.3 sec
[------           18%                  ] 363 of 2000 complete in 367.2 sec
[------           18%                  ] 364 of 2000 complete in 368.1 sec
[------           18%                  ] 365 of 2000 complete in 368.9 sec
[------           18%                  ] 366 of 2000 complete in 369.8 sec
[------           18%                  ] 367 of 2000 complete in 370.6 sec
[------           18%                  ] 368 of 2000 complete in 371.5 sec
[-------          18%                  ] 369 of 2000 complete in 372.4 sec
[-------          18%                  ] 370 of 2000 complete in 373.2 sec
[-------          18%                  ] 371 of 2000 complete in 374.1 sec
[-------          18%                  ] 372 of 2000 complete in 374.9 sec
[-------          18%                  ] 373 of 2000 complete in 375.8 sec
[-------          18%                  ] 374 of 2000 complete in 376.6 sec
[-------          18%                  ] 375 of 2000 complete in 377.5 sec
[-------          18%                  ] 376 of 2000 complete in 378.4 sec
[-------          18%                  ] 377 of 2000 complete in 379.3 sec
[-------          18%                  ] 378 of 2000 complete in 380.2 sec
[-------          18%                  ] 379 of 2000 complete in 381.0 sec
[-------          19%                  ] 380 of 2000 complete in 381.9 sec
[-------          19%                  ] 381 of 2000 complete in 382.8 sec
[-------          19%                  ] 382 of 2000 complete in 383.7 sec
[-------          19%                  ] 383 of 2000 complete in 384.5 sec
[-------          19%                  ] 384 of 2000 complete in 385.4 sec
[-------          19%                  ] 385 of 2000 complete in 386.3 sec
[-------          19%                  ] 386 of 2000 complete in 387.2 sec
[-------          19%                  ] 387 of 2000 complete in 388.1 sec
[-------          19%                  ] 388 of 2000 complete in 389.0 sec
[-------          19%                  ] 389 of 2000 complete in 389.9 sec
[-------          19%                  ] 390 of 2000 complete in 390.8 sec
[-------          19%                  ] 391 of 2000 complete in 391.7 sec
[-------          19%                  ] 392 of 2000 complete in 392.6 sec
[-------          19%                  ] 393 of 2000 complete in 393.4 sec
[-------          19%                  ] 394 of 2000 complete in 394.3 sec
[-------          19%                  ] 395 of 2000 complete in 395.1 sec
[-------          19%                  ] 396 of 2000 complete in 395.9 sec
[-------          19%                  ] 397 of 2000 complete in 396.8 sec
[-------          19%                  ] 398 of 2000 complete in 397.6 sec
[-------          19%                  ] 399 of 2000 complete in 398.5 sec
[-------          20%                  ] 400 of 2000 complete in 399.4 sec
[-------          20%                  ] 401 of 2000 complete in 400.2 sec
[-------          20%                  ] 402 of 2000 complete in 401.1 sec
[-------          20%                  ] 403 of 2000 complete in 402.0 sec
[-------          20%                  ] 404 of 2000 complete in 402.9 sec
[-------          20%                  ] 405 of 2000 complete in 403.8 sec
[-------          20%                  ] 406 of 2000 complete in 404.7 sec
[-------          20%                  ] 407 of 2000 complete in 405.6 sec
[-------          20%                  ] 408 of 2000 complete in 406.4 sec
[-------          20%                  ] 409 of 2000 complete in 407.4 sec
[-------          20%                  ] 410 of 2000 complete in 408.3 sec
[-------          20%                  ] 411 of 2000 complete in 409.2 sec
[-------          20%                  ] 412 of 2000 complete in 410.1 sec
[-------          20%                  ] 413 of 2000 complete in 411.0 sec
[-------          20%                  ] 414 of 2000 complete in 411.9 sec
[-------          20%                  ] 415 of 2000 complete in 412.8 sec
[-------          20%                  ] 416 of 2000 complete in 413.6 sec
[-------          20%                  ] 417 of 2000 complete in 414.6 sec
[-------          20%                  ] 418 of 2000 complete in 415.5 sec
[-------          20%                  ] 419 of 2000 complete in 416.3 sec
[-------          21%                  ] 420 of 2000 complete in 417.2 sec
[-------          21%                  ] 421 of 2000 complete in 418.1 sec
[--------         21%                  ] 422 of 2000 complete in 419.0 sec
[--------         21%                  ] 423 of 2000 complete in 419.8 sec
[--------         21%                  ] 424 of 2000 complete in 420.7 sec
[--------         21%                  ] 425 of 2000 complete in 421.6 sec
[--------         21%                  ] 426 of 2000 complete in 422.5 sec
[--------         21%                  ] 427 of 2000 complete in 423.3 sec
[--------         21%                  ] 428 of 2000 complete in 424.1 sec
[--------         21%                  ] 429 of 2000 complete in 425.0 sec
[--------         21%                  ] 430 of 2000 complete in 425.9 sec
[--------         21%                  ] 431 of 2000 complete in 426.8 sec
[--------         21%                  ] 432 of 2000 complete in 427.7 sec
[--------         21%                  ] 433 of 2000 complete in 428.5 sec
[--------         21%                  ] 434 of 2000 complete in 429.4 sec
[--------         21%                  ] 435 of 2000 complete in 430.3 sec
[--------         21%                  ] 436 of 2000 complete in 431.2 sec
[--------         21%                  ] 437 of 2000 complete in 432.0 sec
[--------         21%                  ] 438 of 2000 complete in 432.9 sec
[--------         21%                  ] 439 of 2000 complete in 433.9 sec

[--------         22%                  ] 441 of 2000 complete in 385.3 sec
[--------         22%                  ] 442 of 2000 complete in 386.0 sec
[--------         22%                  ] 443 of 2000 complete in 386.8 sec
[--------         22%                  ] 444 of 2000 complete in 387.5 sec
[--------         22%                  ] 445 of 2000 complete in 388.2 sec
[--------         22%                  ] 446 of 2000 complete in 389.0 sec
[--------         22%                  ] 447 of 2000 complete in 389.7 sec
[--------         22%                  ] 448 of 2000 complete in 390.5 sec
[--------         22%                  ] 449 of 2000 complete in 391.2 sec
[--------         22%                  ] 450 of 2000 complete in 392.0 sec
[--------         22%                  ] 451 of 2000 complete in 392.7 sec
[--------         22%                  ] 452 of 2000 complete in 393.5 sec
[--------         22%                  ] 453 of 2000 complete in 394.2 sec
[--------         22%                  ] 454 of 2000 complete in 395.0 sec
[--------         22%                  ] 455 of 2000 complete in 395.7 sec
[--------         22%                  ] 456 of 2000 complete in 396.4 sec
[--------         22%                  ] 457 of 2000 complete in 397.2 sec
[--------         22%                  ] 458 of 2000 complete in 398.0 sec
[--------         22%                  ] 459 of 2000 complete in 398.8 sec
[--------         23%                  ] 460 of 2000 complete in 399.6 sec
[--------         23%                  ] 461 of 2000 complete in 400.4 sec
[--------         23%                  ] 462 of 2000 complete in 401.1 sec
[--------         23%                  ] 463 of 2000 complete in 401.9 sec
[--------         23%                  ] 464 of 2000 complete in 402.6 sec
[--------         23%                  ] 465 of 2000 complete in 403.4 sec
[--------         23%                  ] 466 of 2000 complete in 404.2 sec
[--------         23%                  ] 467 of 2000 complete in 404.9 sec
[--------         23%                  ] 468 of 2000 complete in 405.7 sec
[--------         23%                  ] 469 of 2000 complete in 406.5 sec
[--------         23%                  ] 470 of 2000 complete in 407.3 sec
[--------         23%                  ] 471 of 2000 complete in 408.1 sec
[--------         23%                  ] 472 of 2000 complete in 409.0 sec
[--------         23%                  ] 473 of 2000 complete in 409.7 sec
[---------        23%                  ] 474 of 2000 complete in 410.5 sec
[---------        23%                  ] 475 of 2000 complete in 411.3 sec
[---------        23%                  ] 476 of 2000 complete in 412.1 sec
[---------        23%                  ] 477 of 2000 complete in 412.9 sec
[---------        23%                  ] 478 of 2000 complete in 413.7 sec
[---------        23%                  ] 479 of 2000 complete in 414.5 sec
[---------        24%                  ] 480 of 2000 complete in 415.3 sec
[---------        24%                  ] 481 of 2000 complete in 416.0 sec
[---------        24%                  ] 482 of 2000 complete in 416.8 sec
[---------        24%                  ] 483 of 2000 complete in 417.6 sec
[---------        24%                  ] 484 of 2000 complete in 418.3 sec
[---------        24%                  ] 485 of 2000 complete in 419.1 sec
[---------        24%                  ] 486 of 2000 complete in 419.9 sec
[---------        24%                  ] 487 of 2000 complete in 420.7 sec
[---------        24%                  ] 488 of 2000 complete in 421.4 sec
[---------        24%                  ] 489 of 2000 complete in 422.2 sec
[---------        24%                  ] 490 of 2000 complete in 422.9 sec
[---------        24%                  ] 491 of 2000 complete in 423.7 sec
[---------        24%                  ] 492 of 2000 complete in 424.4 sec
[---------        24%                  ] 493 of 2000 complete in 425.2 sec
[---------        24%                  ] 494 of 2000 complete in 425.9 sec
[---------        24%                  ] 495 of 2000 complete in 426.6 sec
[---------        24%                  ] 496 of 2000 complete in 427.4 sec
[---------        24%                  ] 497 of 2000 complete in 428.1 sec
[---------        24%                  ] 498 of 2000 complete in 428.8 sec
[---------        24%                  ] 499 of 2000 complete in 429.6 sec
[---------        25%                  ] 500 of 2000 complete in 430.3 sec
[---------        25%                  ] 501 of 2000 complete in 431.1 sec
[---------        25%                  ] 502 of 2000 complete in 431.9 sec
[---------        25%                  ] 503 of 2000 complete in 432.6 sec
[---------        25%                  ] 504 of 2000 complete in 433.3 sec
[---------        25%                  ] 505 of 2000 complete in 434.1 sec
[---------        25%                  ] 506 of 2000 complete in 434.8 sec
[---------        25%                  ] 507 of 2000 complete in 435.6 sec
[---------        25%                  ] 508 of 2000 complete in 436.4 sec
[---------        25%                  ] 509 of 2000 complete in 437.2 sec
[---------        25%                  ] 510 of 2000 complete in 438.0 sec
[---------        25%                  ] 511 of 2000 complete in 438.8 sec
[---------        25%                  ] 512 of 2000 complete in 439.6 sec
[---------        25%                  ] 513 of 2000 complete in 440.4 sec
[---------        25%                  ] 514 of 2000 complete in 441.1 sec
[---------        25%                  ] 515 of 2000 complete in 441.9 sec
[---------        25%                  ] 516 of 2000 complete in 442.6 sec
[---------        25%                  ] 517 of 2000 complete in 443.4 sec
[---------        25%                  ] 518 of 2000 complete in 444.2 sec
[---------        25%                  ] 519 of 2000 complete in 445.0 sec
[---------        26%                  ] 520 of 2000 complete in 445.8 sec
[---------        26%                  ] 521 of 2000 complete in 446.5 sec
[---------        26%                  ] 522 of 2000 complete in 447.3 sec
[---------        26%                  ] 523 of 2000 complete in 448.1 sec
[---------        26%                  ] 524 of 2000 complete in 448.9 sec
[---------        26%                  ] 525 of 2000 complete in 449.7 sec
[---------        26%                  ] 526 of 2000 complete in 450.5 sec
[----------       26%                  ] 527 of 2000 complete in 451.4 sec
[----------       26%                  ] 528 of 2000 complete in 452.2 sec
[----------       26%                  ] 529 of 2000 complete in 453.0 sec
[----------       26%                  ] 530 of 2000 complete in 453.9 sec
[----------       26%                  ] 531 of 2000 complete in 454.6 sec
[----------       26%                  ] 532 of 2000 complete in 455.4 sec
[----------       26%                  ] 533 of 2000 complete in 456.2 sec
[----------       26%                  ] 534 of 2000 complete in 457.0 sec
[----------       26%                  ] 535 of 2000 complete in 457.8 sec
[----------       26%                  ] 536 of 2000 complete in 458.6 sec
[----------       26%                  ] 537 of 2000 complete in 459.4 sec
[----------       26%                  ] 538 of 2000 complete in 460.3 sec
[----------       26%                  ] 539 of 2000 complete in 461.0 sec
[----------       27%                  ] 540 of 2000 complete in 461.9 sec
[----------       27%                  ] 541 of 2000 complete in 462.8 sec
[----------       27%                  ] 542 of 2000 complete in 463.6 sec
[----------       27%                  ] 543 of 2000 complete in 464.5 sec
[----------       27%                  ] 544 of 2000 complete in 465.3 sec
[----------       27%                  ] 545 of 2000 complete in 466.2 sec
[----------       27%                  ] 546 of 2000 complete in 467.0 sec
[----------       27%                  ] 547 of 2000 complete in 467.9 sec
[----------       27%                  ] 548 of 2000 complete in 468.7 sec
[----------       27%                  ] 549 of 2000 complete in 469.6 sec
[--------         22%                  ] 440 of 2000 complete in 393.6 sec
[--------         22%                  ] 441 of 2000 complete in 394.4 sec
[--------         22%                  ] 442 of 2000 complete in 395.1 sec
[--------         22%                  ] 443 of 2000 complete in 395.8 sec
[--------         22%                  ] 444 of 2000 complete in 396.6 sec
[--------         22%                  ] 445 of 2000 complete in 397.3 sec
[--------         22%                  ] 446 of 2000 complete in 398.1 sec
[--------         22%                  ] 447 of 2000 complete in 398.8 sec
[--------         22%                  ] 448 of 2000 complete in 399.6 sec
[--------         22%                  ] 449 of 2000 complete in 400.3 sec
[--------         22%                  ] 450 of 2000 complete in 401.1 sec
[--------         22%                  ] 451 of 2000 complete in 401.9 sec
[--------         22%                  ] 452 of 2000 complete in 402.6 sec
[--------         22%                  ] 453 of 2000 complete in 403.4 sec
[--------         22%                  ] 454 of 2000 complete in 404.1 sec
[--------         22%                  ] 455 of 2000 complete in 404.9 sec
[--------         22%                  ] 456 of 2000 complete in 405.6 sec
[--------         22%                  ] 457 of 2000 complete in 406.4 sec
[--------         22%                  ] 458 of 2000 complete in 407.2 sec
[--------         22%                  ] 459 of 2000 complete in 408.0 sec
[--------         23%                  ] 460 of 2000 complete in 408.9 sec
[--------         23%                  ] 461 of 2000 complete in 409.6 sec
[--------         23%                  ] 462 of 2000 complete in 410.4 sec
[--------         23%                  ] 463 of 2000 complete in 411.1 sec
[--------         23%                  ] 464 of 2000 complete in 411.9 sec
[--------         23%                  ] 465 of 2000 complete in 412.7 sec
[--------         23%                  ] 466 of 2000 complete in 413.5 sec
[--------         23%                  ] 467 of 2000 complete in 414.3 sec
[--------         23%                  ] 468 of 2000 complete in 415.1 sec
[--------         23%                  ] 469 of 2000 complete in 415.9 sec
[--------         23%                  ] 470 of 2000 complete in 416.6 sec
[--------         23%                  ] 471 of 2000 complete in 417.4 sec
[--------         23%                  ] 472 of 2000 complete in 418.2 sec
[--------         23%                  ] 473 of 2000 complete in 419.0 sec
[---------        23%                  ] 474 of 2000 complete in 419.8 sec
[---------        23%                  ] 475 of 2000 complete in 420.6 sec
[---------        23%                  ] 476 of 2000 complete in 421.4 sec
[---------        23%                  ] 477 of 2000 complete in 422.3 sec
[---------        23%                  ] 478 of 2000 complete in 423.1 sec
[---------        23%                  ] 479 of 2000 complete in 424.0 sec
[---------        24%                  ] 480 of 2000 complete in 424.8 sec
[---------        24%                  ] 481 of 2000 complete in 425.6 sec
[---------        24%                  ] 482 of 2000 complete in 426.4 sec
[---------        24%                  ] 483 of 2000 complete in 427.2 sec
[---------        24%                  ] 484 of 2000 complete in 428.0 sec
[---------        24%                  ] 485 of 2000 complete in 428.9 sec
[---------        24%                  ] 486 of 2000 complete in 429.7 sec
[---------        24%                  ] 487 of 2000 complete in 430.5 sec
[---------        24%                  ] 488 of 2000 complete in 431.3 sec
[---------        24%                  ] 489 of 2000 complete in 432.2 sec
[---------        24%                  ] 490 of 2000 complete in 433.0 sec
[---------        24%                  ] 491 of 2000 complete in 433.8 sec
[---------        24%                  ] 492 of 2000 complete in 434.7 sec
[---------        24%                  ] 493 of 2000 complete in 435.5 sec
[---------        24%                  ] 494 of 2000 complete in 436.3 sec
[---------        24%                  ] 495 of 2000 complete in 437.2 sec
[---------        24%                  ] 496 of 2000 complete in 438.0 sec
[---------        24%                  ] 497 of 2000 complete in 438.8 sec
[---------        24%                  ] 498 of 2000 complete in 439.6 sec
[---------        24%                  ] 499 of 2000 complete in 440.4 sec
[---------        25%                  ] 500 of 2000 complete in 441.2 sec
[---------        25%                  ] 501 of 2000 complete in 442.0 sec
[---------        25%                  ] 502 of 2000 complete in 442.9 sec
[---------        25%                  ] 503 of 2000 complete in 443.7 sec
[---------        25%                  ] 504 of 2000 complete in 444.6 sec
[---------        25%                  ] 505 of 2000 complete in 445.5 sec
[---------        25%                  ] 506 of 2000 complete in 446.3 sec
[---------        25%                  ] 507 of 2000 complete in 447.1 sec
[---------        25%                  ] 508 of 2000 complete in 447.9 sec
[---------        25%                  ] 509 of 2000 complete in 448.8 sec
[---------        25%                  ] 510 of 2000 complete in 449.6 sec
[---------        25%                  ] 511 of 2000 complete in 450.4 sec
[---------        25%                  ] 512 of 2000 complete in 451.2 sec
[---------        25%                  ] 513 of 2000 complete in 452.0 sec
[---------        25%                  ] 514 of 2000 complete in 452.8 sec
[---------        25%                  ] 515 of 2000 complete in 453.6 sec
[---------        25%                  ] 516 of 2000 complete in 454.5 sec
[---------        25%                  ] 517 of 2000 complete in 455.3 sec
[---------        25%                  ] 518 of 2000 complete in 456.1 sec
[---------        25%                  ] 519 of 2000 complete in 456.9 sec
[---------        26%                  ] 520 of 2000 complete in 457.7 sec
[---------        26%                  ] 521 of 2000 complete in 458.5 sec
[---------        26%                  ] 522 of 2000 complete in 459.3 sec
[---------        26%                  ] 523 of 2000 complete in 460.1 sec
[---------        26%                  ] 524 of 2000 complete in 460.9 sec
[---------        26%                  ] 525 of 2000 complete in 461.7 sec
[---------        26%                  ] 526 of 2000 complete in 462.5 sec
[----------       26%                  ] 527 of 2000 complete in 463.3 sec
[----------       26%                  ] 528 of 2000 complete in 464.1 sec
[----------       26%                  ] 529 of 2000 complete in 465.0 sec
[----------       26%                  ] 530 of 2000 complete in 465.8 sec
[----------       26%                  ] 531 of 2000 complete in 466.6 sec
[----------       26%                  ] 532 of 2000 complete in 467.4 sec
[----------       26%                  ] 533 of 2000 complete in 468.3 sec
[----------       26%                  ] 534 of 2000 complete in 469.2 sec
[----------       26%                  ] 535 of 2000 complete in 470.0 sec
[----------       26%                  ] 536 of 2000 complete in 470.8 sec
[----------       26%                  ] 537 of 2000 complete in 471.7 sec
[----------       26%                  ] 538 of 2000 complete in 472.5 sec
[----------       26%                  ] 539 of 2000 complete in 473.3 sec
[----------       27%                  ] 540 of 2000 complete in 474.2 sec
[----------       27%                  ] 541 of 2000 complete in 475.0 sec
[----------       27%                  ] 542 of 2000 complete in 475.9 sec
[----------       27%                  ] 543 of 2000 complete in 476.7 sec
[----------       27%                  ] 544 of 2000 complete in 477.5 sec
[----------       27%                  ] 545 of 2000 complete in 478.3 sec
[----------       27%                  ] 546 of 2000 complete in 479.2 sec
[----------       27%                  ] 547 of 2000 complete in 480.0 sec
[----------       27%                  ] 548 of 2000 complete in 480.8 sec

[--------         22%                  ] 440 of 2000 complete in 434.6 sec
[--------         22%                  ] 441 of 2000 complete in 435.6 sec
[--------         22%                  ] 442 of 2000 complete in 436.4 sec
[--------         22%                  ] 443 of 2000 complete in 437.3 sec
[--------         22%                  ] 444 of 2000 complete in 438.1 sec
[--------         22%                  ] 445 of 2000 complete in 439.0 sec
[--------         22%                  ] 446 of 2000 complete in 440.0 sec
[--------         22%                  ] 447 of 2000 complete in 440.9 sec
[--------         22%                  ] 448 of 2000 complete in 441.8 sec
[--------         22%                  ] 449 of 2000 complete in 442.7 sec
[--------         22%                  ] 450 of 2000 complete in 443.6 sec
[--------         22%                  ] 451 of 2000 complete in 444.5 sec
[--------         22%                  ] 452 of 2000 complete in 445.4 sec
[--------         22%                  ] 453 of 2000 complete in 446.3 sec
[--------         22%                  ] 454 of 2000 complete in 447.2 sec
[--------         22%                  ] 455 of 2000 complete in 448.2 sec
[--------         22%                  ] 456 of 2000 complete in 449.1 sec
[--------         22%                  ] 457 of 2000 complete in 450.0 sec
[--------         22%                  ] 458 of 2000 complete in 451.0 sec
[--------         22%                  ] 459 of 2000 complete in 451.9 sec
[--------         23%                  ] 460 of 2000 complete in 452.8 sec
[--------         23%                  ] 461 of 2000 complete in 453.8 sec
[--------         23%                  ] 462 of 2000 complete in 454.7 sec
[--------         23%                  ] 463 of 2000 complete in 455.6 sec
[--------         23%                  ] 464 of 2000 complete in 456.5 sec
[--------         23%                  ] 465 of 2000 complete in 457.4 sec
[--------         23%                  ] 466 of 2000 complete in 458.3 sec
[--------         23%                  ] 467 of 2000 complete in 459.2 sec
[--------         23%                  ] 468 of 2000 complete in 460.1 sec
[--------         23%                  ] 469 of 2000 complete in 461.0 sec
[--------         23%                  ] 470 of 2000 complete in 461.9 sec
[--------         23%                  ] 471 of 2000 complete in 462.8 sec
[--------         23%                  ] 472 of 2000 complete in 463.7 sec
[--------         23%                  ] 473 of 2000 complete in 464.6 sec
[---------        23%                  ] 474 of 2000 complete in 465.6 sec
[---------        23%                  ] 475 of 2000 complete in 466.5 sec
[---------        23%                  ] 476 of 2000 complete in 467.4 sec
[---------        23%                  ] 477 of 2000 complete in 468.3 sec
[---------        23%                  ] 478 of 2000 complete in 469.4 sec
[---------        23%                  ] 479 of 2000 complete in 470.4 sec
[---------        24%                  ] 480 of 2000 complete in 471.4 sec
[---------        24%                  ] 481 of 2000 complete in 472.4 sec
[---------        24%                  ] 482 of 2000 complete in 473.3 sec
[---------        24%                  ] 483 of 2000 complete in 474.3 sec
[---------        24%                  ] 484 of 2000 complete in 475.3 sec
[---------        24%                  ] 485 of 2000 complete in 476.3 sec
[---------        24%                  ] 486 of 2000 complete in 477.3 sec
[---------        24%                  ] 487 of 2000 complete in 478.2 sec
[---------        24%                  ] 488 of 2000 complete in 479.2 sec
[---------        24%                  ] 489 of 2000 complete in 480.1 sec
[---------        24%                  ] 490 of 2000 complete in 481.1 sec
[---------        24%                  ] 491 of 2000 complete in 482.1 sec
[---------        24%                  ] 492 of 2000 complete in 483.1 sec
[---------        24%                  ] 493 of 2000 complete in 484.1 sec
[---------        24%                  ] 494 of 2000 complete in 485.1 sec
[---------        24%                  ] 495 of 2000 complete in 486.1 sec
[---------        24%                  ] 496 of 2000 complete in 487.2 sec
[---------        24%                  ] 497 of 2000 complete in 488.2 sec
[---------        24%                  ] 498 of 2000 complete in 489.1 sec
[---------        24%                  ] 499 of 2000 complete in 490.2 sec
[---------        25%                  ] 500 of 2000 complete in 491.3 sec
[---------        25%                  ] 501 of 2000 complete in 492.2 sec
[---------        25%                  ] 502 of 2000 complete in 493.2 sec
[---------        25%                  ] 503 of 2000 complete in 494.2 sec
[---------        25%                  ] 504 of 2000 complete in 495.2 sec
[---------        25%                  ] 505 of 2000 complete in 496.1 sec
[---------        25%                  ] 506 of 2000 complete in 497.1 sec
[---------        25%                  ] 507 of 2000 complete in 498.0 sec
[---------        25%                  ] 508 of 2000 complete in 499.0 sec
[---------        25%                  ] 509 of 2000 complete in 500.0 sec
[---------        25%                  ] 510 of 2000 complete in 500.9 sec
[---------        25%                  ] 511 of 2000 complete in 501.9 sec
[---------        25%                  ] 512 of 2000 complete in 502.9 sec
[---------        25%                  ] 513 of 2000 complete in 503.9 sec
[---------        25%                  ] 514 of 2000 complete in 504.8 sec
[---------        25%                  ] 515 of 2000 complete in 505.8 sec
[---------        25%                  ] 516 of 2000 complete in 506.8 sec
[---------        25%                  ] 517 of 2000 complete in 507.8 sec
[---------        25%                  ] 518 of 2000 complete in 508.7 sec
[---------        25%                  ] 519 of 2000 complete in 509.6 sec
[---------        26%                  ] 520 of 2000 complete in 510.5 sec
[---------        26%                  ] 521 of 2000 complete in 511.4 sec
[---------        26%                  ] 522 of 2000 complete in 512.4 sec
[---------        26%                  ] 523 of 2000 complete in 513.3 sec
[---------        26%                  ] 524 of 2000 complete in 514.2 sec
[---------        26%                  ] 525 of 2000 complete in 515.2 sec
[---------        26%                  ] 526 of 2000 complete in 516.1 sec
[----------       26%                  ] 527 of 2000 complete in 517.0 sec
[----------       26%                  ] 528 of 2000 complete in 517.9 sec
[----------       26%                  ] 529 of 2000 complete in 518.9 sec
[----------       26%                  ] 530 of 2000 complete in 519.8 sec
[----------       26%                  ] 531 of 2000 complete in 520.6 sec
[----------       26%                  ] 532 of 2000 complete in 521.5 sec
[----------       26%                  ] 533 of 2000 complete in 522.5 sec
[----------       26%                  ] 534 of 2000 complete in 523.3 sec
[----------       26%                  ] 535 of 2000 complete in 524.3 sec
[----------       26%                  ] 536 of 2000 complete in 525.2 sec
[----------       26%                  ] 537 of 2000 complete in 526.2 sec
[----------       26%                  ] 538 of 2000 complete in 527.1 sec
[----------       26%                  ] 539 of 2000 complete in 528.1 sec
[----------       27%                  ] 540 of 2000 complete in 529.0 sec
[----------       27%                  ] 541 of 2000 complete in 529.9 sec
[----------       27%                  ] 542 of 2000 complete in 530.9 sec
[----------       27%                  ] 543 of 2000 complete in 531.8 sec
[----------       27%                  ] 544 of 2000 complete in 532.7 sec
[----------       27%                  ] 545 of 2000 complete in 533.7 sec
[----------       27%                  ] 546 of 2000 complete in 534.6 sec
[----------       27%                  ] 547 of 2000 complete in 535.6 sec
[----------       27%                  ] 548 of 2000 complete in 536.5 sec
[--------         22%                  ] 440 of 2000 complete in 434.8 sec
[--------         22%                  ] 441 of 2000 complete in 435.7 sec
[--------         22%                  ] 442 of 2000 complete in 436.6 sec
[--------         22%                  ] 443 of 2000 complete in 437.5 sec
[--------         22%                  ] 444 of 2000 complete in 438.3 sec
[--------         22%                  ] 445 of 2000 complete in 439.2 sec
[--------         22%                  ] 446 of 2000 complete in 440.1 sec
[--------         22%                  ] 447 of 2000 complete in 441.0 sec
[--------         22%                  ] 448 of 2000 complete in 441.9 sec
[--------         22%                  ] 449 of 2000 complete in 442.7 sec
[--------         22%                  ] 450 of 2000 complete in 443.6 sec
[--------         22%                  ] 451 of 2000 complete in 444.5 sec
[--------         22%                  ] 452 of 2000 complete in 445.4 sec
[--------         22%                  ] 453 of 2000 complete in 446.3 sec
[--------         22%                  ] 454 of 2000 complete in 447.2 sec
[--------         22%                  ] 455 of 2000 complete in 448.1 sec
[--------         22%                  ] 456 of 2000 complete in 449.0 sec
[--------         22%                  ] 457 of 2000 complete in 449.9 sec
[--------         22%                  ] 458 of 2000 complete in 450.8 sec
[--------         22%                  ] 459 of 2000 complete in 451.7 sec
[--------         23%                  ] 460 of 2000 complete in 452.6 sec
[--------         23%                  ] 461 of 2000 complete in 453.4 sec
[--------         23%                  ] 462 of 2000 complete in 454.3 sec
[--------         23%                  ] 463 of 2000 complete in 455.2 sec
[--------         23%                  ] 464 of 2000 complete in 456.1 sec
[--------         23%                  ] 465 of 2000 complete in 457.0 sec
[--------         23%                  ] 466 of 2000 complete in 457.9 sec
[--------         23%                  ] 467 of 2000 complete in 458.8 sec
[--------         23%                  ] 468 of 2000 complete in 459.7 sec
[--------         23%                  ] 469 of 2000 complete in 460.6 sec
[--------         23%                  ] 470 of 2000 complete in 461.5 sec
[--------         23%                  ] 471 of 2000 complete in 462.3 sec
[--------         23%                  ] 472 of 2000 complete in 463.2 sec
[--------         23%                  ] 473 of 2000 complete in 464.1 sec
[---------        23%                  ] 474 of 2000 complete in 465.0 sec
[---------        23%                  ] 475 of 2000 complete in 466.0 sec
[---------        23%                  ] 476 of 2000 complete in 466.9 sec
[---------        23%                  ] 477 of 2000 complete in 467.8 sec
[---------        23%                  ] 478 of 2000 complete in 468.7 sec
[---------        23%                  ] 479 of 2000 complete in 469.7 sec
[---------        24%                  ] 480 of 2000 complete in 470.6 sec
[---------        24%                  ] 481 of 2000 complete in 471.5 sec
[---------        24%                  ] 482 of 2000 complete in 472.5 sec
[---------        24%                  ] 483 of 2000 complete in 473.4 sec
[---------        24%                  ] 484 of 2000 complete in 474.3 sec
[---------        24%                  ] 485 of 2000 complete in 475.3 sec
[---------        24%                  ] 486 of 2000 complete in 476.2 sec
[---------        24%                  ] 487 of 2000 complete in 477.2 sec
[---------        24%                  ] 488 of 2000 complete in 478.2 sec
[---------        24%                  ] 489 of 2000 complete in 479.1 sec
[---------        24%                  ] 490 of 2000 complete in 480.0 sec
[---------        24%                  ] 491 of 2000 complete in 481.0 sec
[---------        24%                  ] 492 of 2000 complete in 481.9 sec
[---------        24%                  ] 493 of 2000 complete in 482.9 sec
[---------        24%                  ] 494 of 2000 complete in 483.8 sec
[---------        24%                  ] 495 of 2000 complete in 484.8 sec
[---------        24%                  ] 496 of 2000 complete in 485.8 sec
[---------        24%                  ] 497 of 2000 complete in 486.7 sec
[---------        24%                  ] 498 of 2000 complete in 487.7 sec
[---------        24%                  ] 499 of 2000 complete in 488.7 sec
[---------        25%                  ] 500 of 2000 complete in 489.6 sec
[---------        25%                  ] 501 of 2000 complete in 490.6 sec
[---------        25%                  ] 502 of 2000 complete in 491.5 sec
[---------        25%                  ] 503 of 2000 complete in 492.5 sec
[---------        25%                  ] 504 of 2000 complete in 493.5 sec
[---------        25%                  ] 505 of 2000 complete in 494.4 sec
[---------        25%                  ] 506 of 2000 complete in 495.4 sec
[---------        25%                  ] 507 of 2000 complete in 496.4 sec
[---------        25%                  ] 508 of 2000 complete in 497.4 sec
[---------        25%                  ] 509 of 2000 complete in 498.4 sec
[---------        25%                  ] 510 of 2000 complete in 499.4 sec
[---------        25%                  ] 511 of 2000 complete in 500.4 sec
[---------        25%                  ] 512 of 2000 complete in 501.4 sec
[---------        25%                  ] 513 of 2000 complete in 502.4 sec
[---------        25%                  ] 514 of 2000 complete in 503.4 sec
[---------        25%                  ] 515 of 2000 complete in 504.4 sec
[---------        25%                  ] 516 of 2000 complete in 505.5 sec
[---------        25%                  ] 517 of 2000 complete in 506.5 sec
[---------        25%                  ] 518 of 2000 complete in 507.5 sec
[---------        25%                  ] 519 of 2000 complete in 508.5 sec
[---------        26%                  ] 520 of 2000 complete in 509.5 sec
[---------        26%                  ] 521 of 2000 complete in 510.4 sec
[---------        26%                  ] 522 of 2000 complete in 511.4 sec
[---------        26%                  ] 523 of 2000 complete in 512.4 sec
[---------        26%                  ] 524 of 2000 complete in 513.4 sec
[---------        26%                  ] 525 of 2000 complete in 514.3 sec
[---------        26%                  ] 526 of 2000 complete in 515.3 sec
[----------       26%                  ] 527 of 2000 complete in 516.3 sec
[----------       26%                  ] 528 of 2000 complete in 517.3 sec
[----------       26%                  ] 529 of 2000 complete in 518.3 sec
[----------       26%                  ] 530 of 2000 complete in 519.2 sec
[----------       26%                  ] 531 of 2000 complete in 520.2 sec
[----------       26%                  ] 532 of 2000 complete in 521.1 sec
[----------       26%                  ] 533 of 2000 complete in 522.1 sec
[----------       26%                  ] 534 of 2000 complete in 523.1 sec
[----------       26%                  ] 535 of 2000 complete in 524.0 sec
[----------       26%                  ] 536 of 2000 complete in 524.9 sec
[----------       26%                  ] 537 of 2000 complete in 525.9 sec
[----------       26%                  ] 538 of 2000 complete in 526.9 sec
[----------       26%                  ] 539 of 2000 complete in 527.8 sec
[----------       27%                  ] 540 of 2000 complete in 528.8 sec
[----------       27%                  ] 541 of 2000 complete in 529.7 sec
[----------       27%                  ] 542 of 2000 complete in 530.7 sec
[----------       27%                  ] 543 of 2000 complete in 531.6 sec
[----------       27%                  ] 544 of 2000 complete in 532.6 sec
[----------       27%                  ] 545 of 2000 complete in 533.6 sec
[----------       27%                  ] 546 of 2000 complete in 534.6 sec
[----------       27%                  ] 547 of 2000 complete in 535.6 sec
[----------       27%                  ] 548 of 2000 complete in 536.6 sec

[----------       27%                  ] 550 of 2000 complete in 470.5 sec
[----------       27%                  ] 551 of 2000 complete in 471.3 sec
[----------       27%                  ] 552 of 2000 complete in 472.2 sec
[----------       27%                  ] 553 of 2000 complete in 473.0 sec
[----------       27%                  ] 554 of 2000 complete in 473.9 sec
[----------       27%                  ] 555 of 2000 complete in 474.8 sec
[----------       27%                  ] 556 of 2000 complete in 475.6 sec
[----------       27%                  ] 557 of 2000 complete in 476.5 sec
[----------       27%                  ] 558 of 2000 complete in 477.3 sec
[----------       27%                  ] 559 of 2000 complete in 478.2 sec
[----------       28%                  ] 560 of 2000 complete in 479.0 sec
[----------       28%                  ] 561 of 2000 complete in 479.9 sec
[----------       28%                  ] 562 of 2000 complete in 480.7 sec
[----------       28%                  ] 563 of 2000 complete in 481.6 sec
[----------       28%                  ] 564 of 2000 complete in 482.4 sec
[----------       28%                  ] 565 of 2000 complete in 483.2 sec
[----------       28%                  ] 566 of 2000 complete in 484.1 sec
[----------       28%                  ] 567 of 2000 complete in 484.9 sec
[----------       28%                  ] 568 of 2000 complete in 485.8 sec
[----------       28%                  ] 569 of 2000 complete in 486.6 sec
[----------       28%                  ] 570 of 2000 complete in 487.5 sec
[----------       28%                  ] 571 of 2000 complete in 488.4 sec
[----------       28%                  ] 572 of 2000 complete in 489.4 sec
[----------       28%                  ] 573 of 2000 complete in 490.3 sec
[----------       28%                  ] 574 of 2000 complete in 491.2 sec
[----------       28%                  ] 575 of 2000 complete in 492.1 sec
[----------       28%                  ] 576 of 2000 complete in 492.9 sec
[----------       28%                  ] 577 of 2000 complete in 493.8 sec
[----------       28%                  ] 578 of 2000 complete in 494.7 sec
[-----------      28%                  ] 579 of 2000 complete in 495.6 sec
[-----------      29%                  ] 580 of 2000 complete in 496.5 sec
[-----------      29%                  ] 581 of 2000 complete in 497.4 sec
[-----------      29%                  ] 582 of 2000 complete in 498.2 sec
[-----------      29%                  ] 583 of 2000 complete in 499.1 sec
[-----------      29%                  ] 584 of 2000 complete in 500.0 sec
[-----------      29%                  ] 585 of 2000 complete in 500.9 sec
[-----------      29%                  ] 586 of 2000 complete in 501.8 sec
[-----------      29%                  ] 587 of 2000 complete in 502.6 sec
[-----------      29%                  ] 588 of 2000 complete in 503.5 sec
[-----------      29%                  ] 589 of 2000 complete in 504.4 sec
[-----------      29%                  ] 590 of 2000 complete in 505.3 sec
[-----------      29%                  ] 591 of 2000 complete in 506.2 sec
[-----------      29%                  ] 592 of 2000 complete in 507.1 sec
[-----------      29%                  ] 593 of 2000 complete in 508.0 sec
[-----------      29%                  ] 594 of 2000 complete in 508.9 sec
[-----------      29%                  ] 595 of 2000 complete in 509.8 sec
[-----------      29%                  ] 596 of 2000 complete in 510.7 sec
[-----------      29%                  ] 597 of 2000 complete in 511.6 sec
[-----------      29%                  ] 598 of 2000 complete in 512.5 sec
[-----------      29%                  ] 599 of 2000 complete in 513.4 sec
[-----------      30%                  ] 600 of 2000 complete in 514.4 sec
[-----------      30%                  ] 601 of 2000 complete in 515.3 sec
[-----------      30%                  ] 602 of 2000 complete in 516.2 sec
[-----------      30%                  ] 603 of 2000 complete in 517.0 sec
[-----------      30%                  ] 604 of 2000 complete in 517.9 sec
[-----------      30%                  ] 605 of 2000 complete in 518.8 sec
[-----------      30%                  ] 606 of 2000 complete in 519.7 sec
[-----------      30%                  ] 607 of 2000 complete in 520.6 sec
[-----------      30%                  ] 608 of 2000 complete in 521.5 sec
[-----------      30%                  ] 609 of 2000 complete in 522.4 sec
[-----------      30%                  ] 610 of 2000 complete in 523.3 sec
[-----------      30%                  ] 611 of 2000 complete in 524.2 sec
[-----------      30%                  ] 612 of 2000 complete in 525.1 sec
[-----------      30%                  ] 613 of 2000 complete in 526.0 sec
[-----------      30%                  ] 614 of 2000 complete in 526.8 sec
[-----------      30%                  ] 615 of 2000 complete in 527.7 sec
[-----------      30%                  ] 616 of 2000 complete in 528.6 sec
[-----------      30%                  ] 617 of 2000 complete in 529.4 sec
[-----------      30%                  ] 618 of 2000 complete in 530.3 sec
[-----------      30%                  ] 619 of 2000 complete in 531.1 sec
[-----------      31%                  ] 620 of 2000 complete in 532.0 sec
[-----------      31%                  ] 621 of 2000 complete in 532.8 sec
[-----------      31%                  ] 622 of 2000 complete in 533.7 sec
[-----------      31%                  ] 623 of 2000 complete in 534.6 sec
[-----------      31%                  ] 624 of 2000 complete in 535.4 sec
[-----------      31%                  ] 625 of 2000 complete in 536.2 sec
[-----------      31%                  ] 626 of 2000 complete in 537.1 sec
[-----------      31%                  ] 627 of 2000 complete in 538.0 sec
[-----------      31%                  ] 628 of 2000 complete in 538.8 sec
[-----------      31%                  ] 629 of 2000 complete in 539.7 sec
[-----------      31%                  ] 630 of 2000 complete in 540.5 sec
[-----------      31%                  ] 631 of 2000 complete in 541.4 sec
[------------     31%                  ] 632 of 2000 complete in 542.3 sec
[------------     31%                  ] 633 of 2000 complete in 543.2 sec
[------------     31%                  ] 634 of 2000 complete in 544.1 sec
[------------     31%                  ] 635 of 2000 complete in 545.0 sec
[------------     31%                  ] 636 of 2000 complete in 545.9 sec
[------------     31%                  ] 637 of 2000 complete in 546.8 sec
[------------     31%                  ] 638 of 2000 complete in 547.7 sec
[------------     31%                  ] 639 of 2000 complete in 548.6 sec
[------------     32%                  ] 640 of 2000 complete in 549.5 sec
[------------     32%                  ] 641 of 2000 complete in 550.4 sec
[------------     32%                  ] 642 of 2000 complete in 551.3 sec
[------------     32%                  ] 643 of 2000 complete in 552.2 sec
[------------     32%                  ] 644 of 2000 complete in 553.2 sec
[------------     32%                  ] 645 of 2000 complete in 554.1 sec
[------------     32%                  ] 646 of 2000 complete in 555.0 sec
[------------     32%                  ] 647 of 2000 complete in 555.9 sec
[------------     32%                  ] 648 of 2000 complete in 556.8 sec
[------------     32%                  ] 649 of 2000 complete in 557.7 sec
[------------     32%                  ] 650 of 2000 complete in 558.5 sec
[------------     32%                  ] 651 of 2000 complete in 559.3 sec
[------------     32%                  ] 652 of 2000 complete in 560.2 sec
[------------     32%                  ] 653 of 2000 complete in 561.1 sec
[------------     32%                  ] 654 of 2000 complete in 561.9 sec
[------------     32%                  ] 655 of 2000 complete in 562.8 sec
[------------     32%                  ] 656 of 2000 complete in 563.5 sec
[------------     32%                  ] 657 of 2000 complete in 564.3 sec
[------------     32%                  ] 658 of 2000 complete in 565.1 sec
[----------       27%                  ] 549 of 2000 complete in 481.6 sec
[----------       27%                  ] 550 of 2000 complete in 482.4 sec
[----------       27%                  ] 551 of 2000 complete in 483.2 sec
[----------       27%                  ] 552 of 2000 complete in 484.0 sec
[----------       27%                  ] 553 of 2000 complete in 484.8 sec
[----------       27%                  ] 554 of 2000 complete in 485.6 sec
[----------       27%                  ] 555 of 2000 complete in 486.4 sec
[----------       27%                  ] 556 of 2000 complete in 487.2 sec
[----------       27%                  ] 557 of 2000 complete in 488.0 sec
[----------       27%                  ] 558 of 2000 complete in 488.8 sec
[----------       27%                  ] 559 of 2000 complete in 489.6 sec
[----------       28%                  ] 560 of 2000 complete in 490.4 sec
[----------       28%                  ] 561 of 2000 complete in 491.2 sec
[----------       28%                  ] 562 of 2000 complete in 491.9 sec
[----------       28%                  ] 563 of 2000 complete in 492.7 sec
[----------       28%                  ] 564 of 2000 complete in 493.5 sec
[----------       28%                  ] 565 of 2000 complete in 494.3 sec
[----------       28%                  ] 566 of 2000 complete in 495.1 sec
[----------       28%                  ] 567 of 2000 complete in 495.9 sec
[----------       28%                  ] 568 of 2000 complete in 496.7 sec
[----------       28%                  ] 569 of 2000 complete in 497.5 sec
[----------       28%                  ] 570 of 2000 complete in 498.3 sec
[----------       28%                  ] 571 of 2000 complete in 499.1 sec
[----------       28%                  ] 572 of 2000 complete in 499.9 sec
[----------       28%                  ] 573 of 2000 complete in 500.7 sec
[----------       28%                  ] 574 of 2000 complete in 501.6 sec
[----------       28%                  ] 575 of 2000 complete in 502.4 sec
[----------       28%                  ] 576 of 2000 complete in 503.2 sec
[----------       28%                  ] 577 of 2000 complete in 504.0 sec
[----------       28%                  ] 578 of 2000 complete in 504.8 sec
[-----------      28%                  ] 579 of 2000 complete in 505.6 sec
[-----------      29%                  ] 580 of 2000 complete in 506.4 sec
[-----------      29%                  ] 581 of 2000 complete in 507.2 sec
[-----------      29%                  ] 582 of 2000 complete in 508.0 sec
[-----------      29%                  ] 583 of 2000 complete in 508.8 sec
[-----------      29%                  ] 584 of 2000 complete in 509.6 sec
[-----------      29%                  ] 585 of 2000 complete in 510.3 sec
[-----------      29%                  ] 586 of 2000 complete in 511.1 sec
[-----------      29%                  ] 587 of 2000 complete in 511.9 sec
[-----------      29%                  ] 588 of 2000 complete in 512.7 sec
[-----------      29%                  ] 589 of 2000 complete in 513.4 sec
[-----------      29%                  ] 590 of 2000 complete in 514.2 sec
[-----------      29%                  ] 591 of 2000 complete in 515.0 sec
[-----------      29%                  ] 592 of 2000 complete in 515.8 sec
[-----------      29%                  ] 593 of 2000 complete in 516.6 sec
[-----------      29%                  ] 594 of 2000 complete in 517.4 sec
[-----------      29%                  ] 595 of 2000 complete in 518.2 sec
[-----------      29%                  ] 596 of 2000 complete in 519.0 sec
[-----------      29%                  ] 597 of 2000 complete in 519.7 sec
[-----------      29%                  ] 598 of 2000 complete in 520.5 sec
[-----------      29%                  ] 599 of 2000 complete in 521.3 sec
[-----------      30%                  ] 600 of 2000 complete in 522.2 sec
[-----------      30%                  ] 601 of 2000 complete in 523.0 sec
[-----------      30%                  ] 602 of 2000 complete in 523.8 sec
[-----------      30%                  ] 603 of 2000 complete in 524.6 sec
[-----------      30%                  ] 604 of 2000 complete in 525.4 sec
[-----------      30%                  ] 605 of 2000 complete in 526.3 sec
[-----------      30%                  ] 606 of 2000 complete in 527.1 sec
[-----------      30%                  ] 607 of 2000 complete in 527.9 sec
[-----------      30%                  ] 608 of 2000 complete in 528.6 sec
[-----------      30%                  ] 609 of 2000 complete in 529.4 sec
[-----------      30%                  ] 610 of 2000 complete in 530.2 sec
[-----------      30%                  ] 611 of 2000 complete in 531.0 sec
[-----------      30%                  ] 612 of 2000 complete in 531.8 sec
[-----------      30%                  ] 613 of 2000 complete in 532.6 sec
[-----------      30%                  ] 614 of 2000 complete in 533.4 sec
[-----------      30%                  ] 615 of 2000 complete in 534.1 sec
[-----------      30%                  ] 616 of 2000 complete in 534.9 sec
[-----------      30%                  ] 617 of 2000 complete in 535.7 sec
[-----------      30%                  ] 618 of 2000 complete in 536.5 sec
[-----------      30%                  ] 619 of 2000 complete in 537.2 sec
[-----------      31%                  ] 620 of 2000 complete in 538.1 sec
[-----------      31%                  ] 621 of 2000 complete in 538.9 sec
[-----------      31%                  ] 622 of 2000 complete in 539.6 sec
[-----------      31%                  ] 623 of 2000 complete in 540.4 sec
[-----------      31%                  ] 624 of 2000 complete in 541.2 sec
[-----------      31%                  ] 625 of 2000 complete in 542.0 sec
[-----------      31%                  ] 626 of 2000 complete in 542.8 sec
[-----------      31%                  ] 627 of 2000 complete in 543.6 sec
[-----------      31%                  ] 628 of 2000 complete in 544.4 sec
[-----------      31%                  ] 629 of 2000 complete in 545.2 sec
[-----------      31%                  ] 630 of 2000 complete in 546.0 sec
[-----------      31%                  ] 631 of 2000 complete in 546.8 sec
[------------     31%                  ] 632 of 2000 complete in 547.6 sec
[------------     31%                  ] 633 of 2000 complete in 548.4 sec
[------------     31%                  ] 634 of 2000 complete in 549.2 sec
[------------     31%                  ] 635 of 2000 complete in 550.0 sec
[------------     31%                  ] 636 of 2000 complete in 550.8 sec
[------------     31%                  ] 637 of 2000 complete in 551.6 sec
[------------     31%                  ] 638 of 2000 complete in 552.4 sec
[------------     31%                  ] 639 of 2000 complete in 553.2 sec
[------------     32%                  ] 640 of 2000 complete in 553.9 sec
[------------     32%                  ] 641 of 2000 complete in 554.7 sec
[------------     32%                  ] 642 of 2000 complete in 555.5 sec
[------------     32%                  ] 643 of 2000 complete in 556.3 sec
[------------     32%                  ] 644 of 2000 complete in 557.1 sec
[------------     32%                  ] 645 of 2000 complete in 557.8 sec
[------------     32%                  ] 646 of 2000 complete in 558.6 sec
[------------     32%                  ] 647 of 2000 complete in 559.5 sec
[------------     32%                  ] 648 of 2000 complete in 560.3 sec
[------------     32%                  ] 649 of 2000 complete in 561.2 sec
[------------     32%                  ] 650 of 2000 complete in 562.0 sec
[------------     32%                  ] 651 of 2000 complete in 562.8 sec
[------------     32%                  ] 652 of 2000 complete in 563.6 sec
[------------     32%                  ] 653 of 2000 complete in 564.4 sec
[------------     32%                  ] 654 of 2000 complete in 565.2 sec
[------------     32%                  ] 655 of 2000 complete in 566.0 sec
[------------     32%                  ] 656 of 2000 complete in 566.7 sec
[------------     32%                  ] 657 of 2000 complete in 567.5 sec

[----------       27%                  ] 549 of 2000 complete in 537.6 sec
[----------       27%                  ] 550 of 2000 complete in 538.6 sec
[----------       27%                  ] 551 of 2000 complete in 539.6 sec
[----------       27%                  ] 552 of 2000 complete in 540.6 sec
[----------       27%                  ] 553 of 2000 complete in 541.6 sec
[----------       27%                  ] 554 of 2000 complete in 542.6 sec
[----------       27%                  ] 555 of 2000 complete in 543.7 sec
[----------       27%                  ] 556 of 2000 complete in 544.7 sec
[----------       27%                  ] 557 of 2000 complete in 545.7 sec
[----------       27%                  ] 558 of 2000 complete in 546.8 sec
[----------       27%                  ] 559 of 2000 complete in 547.8 sec
[----------       28%                  ] 560 of 2000 complete in 548.8 sec
[----------       28%                  ] 561 of 2000 complete in 549.8 sec
[----------       28%                  ] 562 of 2000 complete in 550.8 sec
[----------       28%                  ] 563 of 2000 complete in 551.8 sec
[----------       28%                  ] 564 of 2000 complete in 552.8 sec
[----------       28%                  ] 565 of 2000 complete in 553.8 sec
[----------       28%                  ] 566 of 2000 complete in 554.8 sec
[----------       28%                  ] 567 of 2000 complete in 555.8 sec
[----------       28%                  ] 568 of 2000 complete in 556.9 sec
[----------       28%                  ] 569 of 2000 complete in 557.9 sec
[----------       28%                  ] 570 of 2000 complete in 558.9 sec
[----------       28%                  ] 571 of 2000 complete in 559.8 sec
[----------       28%                  ] 572 of 2000 complete in 560.8 sec
[----------       28%                  ] 573 of 2000 complete in 561.9 sec
[----------       28%                  ] 574 of 2000 complete in 562.8 sec
[----------       28%                  ] 575 of 2000 complete in 563.8 sec
[----------       28%                  ] 576 of 2000 complete in 564.8 sec
[----------       28%                  ] 577 of 2000 complete in 565.8 sec
[----------       28%                  ] 578 of 2000 complete in 566.7 sec
[-----------      28%                  ] 579 of 2000 complete in 567.7 sec
[-----------      29%                  ] 580 of 2000 complete in 568.7 sec
[-----------      29%                  ] 581 of 2000 complete in 569.6 sec
[-----------      29%                  ] 582 of 2000 complete in 570.6 sec
[-----------      29%                  ] 583 of 2000 complete in 571.6 sec
[-----------      29%                  ] 584 of 2000 complete in 572.5 sec
[-----------      29%                  ] 585 of 2000 complete in 573.4 sec
[-----------      29%                  ] 586 of 2000 complete in 574.4 sec
[-----------      29%                  ] 587 of 2000 complete in 575.2 sec
[-----------      29%                  ] 588 of 2000 complete in 576.1 sec
[-----------      29%                  ] 589 of 2000 complete in 577.0 sec
[-----------      29%                  ] 590 of 2000 complete in 577.9 sec
[-----------      29%                  ] 591 of 2000 complete in 578.8 sec
[-----------      29%                  ] 592 of 2000 complete in 579.7 sec
[-----------      29%                  ] 593 of 2000 complete in 580.6 sec
[-----------      29%                  ] 594 of 2000 complete in 581.5 sec
[-----------      29%                  ] 595 of 2000 complete in 582.4 sec
[-----------      29%                  ] 596 of 2000 complete in 583.3 sec
[-----------      29%                  ] 597 of 2000 complete in 584.2 sec
[-----------      29%                  ] 598 of 2000 complete in 585.1 sec
[-----------      29%                  ] 599 of 2000 complete in 586.0 sec
[-----------      30%                  ] 600 of 2000 complete in 586.8 sec
[-----------      30%                  ] 601 of 2000 complete in 587.7 sec
[-----------      30%                  ] 602 of 2000 complete in 588.6 sec
[-----------      30%                  ] 603 of 2000 complete in 589.5 sec
[-----------      30%                  ] 604 of 2000 complete in 590.4 sec
[-----------      30%                  ] 605 of 2000 complete in 591.3 sec
[-----------      30%                  ] 606 of 2000 complete in 592.3 sec
[-----------      30%                  ] 607 of 2000 complete in 593.2 sec
[-----------      30%                  ] 608 of 2000 complete in 594.1 sec
[-----------      30%                  ] 609 of 2000 complete in 595.1 sec
[-----------      30%                  ] 610 of 2000 complete in 596.0 sec
[-----------      30%                  ] 611 of 2000 complete in 596.8 sec
[-----------      30%                  ] 612 of 2000 complete in 597.7 sec
[-----------      30%                  ] 613 of 2000 complete in 598.6 sec
[-----------      30%                  ] 614 of 2000 complete in 599.6 sec
[-----------      30%                  ] 615 of 2000 complete in 600.5 sec
[-----------      30%                  ] 616 of 2000 complete in 601.4 sec
[-----------      30%                  ] 617 of 2000 complete in 602.3 sec
[-----------      30%                  ] 618 of 2000 complete in 603.2 sec
[-----------      30%                  ] 619 of 2000 complete in 604.1 sec
[-----------      31%                  ] 620 of 2000 complete in 605.0 sec
[-----------      31%                  ] 621 of 2000 complete in 605.9 sec
[-----------      31%                  ] 622 of 2000 complete in 606.8 sec
[-----------      31%                  ] 623 of 2000 complete in 607.7 sec
[-----------      31%                  ] 624 of 2000 complete in 608.6 sec
[-----------      31%                  ] 625 of 2000 complete in 609.5 sec
[-----------      31%                  ] 626 of 2000 complete in 610.4 sec
[-----------      31%                  ] 627 of 2000 complete in 611.3 sec
[-----------      31%                  ] 628 of 2000 complete in 612.1 sec
[-----------      31%                  ] 629 of 2000 complete in 613.0 sec
[-----------      31%                  ] 630 of 2000 complete in 613.9 sec
[-----------      31%                  ] 631 of 2000 complete in 614.7 sec
[------------     31%                  ] 632 of 2000 complete in 615.6 sec
[------------     31%                  ] 633 of 2000 complete in 616.5 sec
[------------     31%                  ] 634 of 2000 complete in 617.3 sec
[------------     31%                  ] 635 of 2000 complete in 618.3 sec
[------------     31%                  ] 636 of 2000 complete in 619.2 sec
[------------     31%                  ] 637 of 2000 complete in 620.1 sec
[------------     31%                  ] 638 of 2000 complete in 620.9 sec
[------------     31%                  ] 639 of 2000 complete in 621.9 sec
[------------     32%                  ] 640 of 2000 complete in 622.8 sec
[------------     32%                  ] 641 of 2000 complete in 623.7 sec
[------------     32%                  ] 642 of 2000 complete in 624.6 sec
[------------     32%                  ] 643 of 2000 complete in 625.6 sec
[------------     32%                  ] 644 of 2000 complete in 626.5 sec
[------------     32%                  ] 645 of 2000 complete in 627.5 sec
[------------     32%                  ] 646 of 2000 complete in 628.4 sec
[------------     32%                  ] 647 of 2000 complete in 629.3 sec
[------------     32%                  ] 648 of 2000 complete in 630.2 sec
[------------     32%                  ] 649 of 2000 complete in 631.2 sec
[------------     32%                  ] 650 of 2000 complete in 632.1 sec
[------------     32%                  ] 651 of 2000 complete in 633.1 sec
[------------     32%                  ] 652 of 2000 complete in 634.1 sec
[------------     32%                  ] 653 of 2000 complete in 635.0 sec
[------------     32%                  ] 654 of 2000 complete in 635.9 sec
[------------     32%                  ] 655 of 2000 complete in 636.9 sec
[------------     32%                  ] 656 of 2000 complete in 637.8 sec
[------------     32%                  ] 657 of 2000 complete in 638.8 sec
[----------       27%                  ] 549 of 2000 complete in 537.5 sec
[----------       27%                  ] 550 of 2000 complete in 538.5 sec
[----------       27%                  ] 551 of 2000 complete in 539.5 sec
[----------       27%                  ] 552 of 2000 complete in 540.5 sec
[----------       27%                  ] 553 of 2000 complete in 541.5 sec
[----------       27%                  ] 554 of 2000 complete in 542.5 sec
[----------       27%                  ] 555 of 2000 complete in 543.5 sec
[----------       27%                  ] 556 of 2000 complete in 544.5 sec
[----------       27%                  ] 557 of 2000 complete in 545.4 sec
[----------       27%                  ] 558 of 2000 complete in 546.4 sec
[----------       27%                  ] 559 of 2000 complete in 547.3 sec
[----------       28%                  ] 560 of 2000 complete in 548.3 sec
[----------       28%                  ] 561 of 2000 complete in 549.3 sec
[----------       28%                  ] 562 of 2000 complete in 550.2 sec
[----------       28%                  ] 563 of 2000 complete in 551.2 sec
[----------       28%                  ] 564 of 2000 complete in 552.3 sec
[----------       28%                  ] 565 of 2000 complete in 553.2 sec
[----------       28%                  ] 566 of 2000 complete in 554.2 sec
[----------       28%                  ] 567 of 2000 complete in 555.2 sec
[----------       28%                  ] 568 of 2000 complete in 556.2 sec
[----------       28%                  ] 569 of 2000 complete in 557.3 sec
[----------       28%                  ] 570 of 2000 complete in 558.3 sec
[----------       28%                  ] 571 of 2000 complete in 559.3 sec
[----------       28%                  ] 572 of 2000 complete in 560.3 sec
[----------       28%                  ] 573 of 2000 complete in 561.3 sec
[----------       28%                  ] 574 of 2000 complete in 562.3 sec
[----------       28%                  ] 575 of 2000 complete in 563.4 sec
[----------       28%                  ] 576 of 2000 complete in 564.3 sec
[----------       28%                  ] 577 of 2000 complete in 565.4 sec
[----------       28%                  ] 578 of 2000 complete in 566.4 sec
[-----------      28%                  ] 579 of 2000 complete in 567.4 sec
[-----------      29%                  ] 580 of 2000 complete in 568.5 sec
[-----------      29%                  ] 581 of 2000 complete in 569.6 sec
[-----------      29%                  ] 582 of 2000 complete in 570.6 sec
[-----------      29%                  ] 583 of 2000 complete in 571.6 sec
[-----------      29%                  ] 584 of 2000 complete in 572.5 sec
[-----------      29%                  ] 585 of 2000 complete in 573.6 sec
[-----------      29%                  ] 586 of 2000 complete in 574.5 sec
[-----------      29%                  ] 587 of 2000 complete in 575.5 sec
[-----------      29%                  ] 588 of 2000 complete in 576.5 sec
[-----------      29%                  ] 589 of 2000 complete in 577.4 sec
[-----------      29%                  ] 590 of 2000 complete in 578.4 sec
[-----------      29%                  ] 591 of 2000 complete in 579.3 sec
[-----------      29%                  ] 592 of 2000 complete in 580.3 sec
[-----------      29%                  ] 593 of 2000 complete in 581.2 sec
[-----------      29%                  ] 594 of 2000 complete in 582.1 sec
[-----------      29%                  ] 595 of 2000 complete in 583.1 sec
[-----------      29%                  ] 596 of 2000 complete in 584.0 sec
[-----------      29%                  ] 597 of 2000 complete in 585.0 sec
[-----------      29%                  ] 598 of 2000 complete in 585.9 sec
[-----------      29%                  ] 599 of 2000 complete in 586.9 sec
[-----------      30%                  ] 600 of 2000 complete in 587.8 sec
[-----------      30%                  ] 601 of 2000 complete in 588.9 sec
[-----------      30%                  ] 602 of 2000 complete in 589.8 sec
[-----------      30%                  ] 603 of 2000 complete in 590.8 sec
[-----------      30%                  ] 604 of 2000 complete in 591.7 sec
[-----------      30%                  ] 605 of 2000 complete in 592.7 sec
[-----------      30%                  ] 606 of 2000 complete in 593.7 sec
[-----------      30%                  ] 607 of 2000 complete in 594.6 sec
[-----------      30%                  ] 608 of 2000 complete in 595.6 sec
[-----------      30%                  ] 609 of 2000 complete in 596.5 sec
[-----------      30%                  ] 610 of 2000 complete in 597.3 sec
[-----------      30%                  ] 611 of 2000 complete in 598.3 sec
[-----------      30%                  ] 612 of 2000 complete in 599.2 sec
[-----------      30%                  ] 613 of 2000 complete in 600.1 sec
[-----------      30%                  ] 614 of 2000 complete in 601.0 sec
[-----------      30%                  ] 615 of 2000 complete in 601.9 sec
[-----------      30%                  ] 616 of 2000 complete in 602.8 sec
[-----------      30%                  ] 617 of 2000 complete in 603.7 sec
[-----------      30%                  ] 618 of 2000 complete in 604.7 sec
[-----------      30%                  ] 619 of 2000 complete in 605.6 sec
[-----------      31%                  ] 620 of 2000 complete in 606.5 sec
[-----------      31%                  ] 621 of 2000 complete in 607.5 sec
[-----------      31%                  ] 622 of 2000 complete in 608.4 sec
[-----------      31%                  ] 623 of 2000 complete in 609.3 sec
[-----------      31%                  ] 624 of 2000 complete in 610.3 sec
[-----------      31%                  ] 625 of 2000 complete in 611.2 sec
[-----------      31%                  ] 626 of 2000 complete in 612.1 sec
[-----------      31%                  ] 627 of 2000 complete in 613.1 sec
[-----------      31%                  ] 628 of 2000 complete in 614.1 sec
[-----------      31%                  ] 629 of 2000 complete in 615.1 sec
[-----------      31%                  ] 630 of 2000 complete in 616.0 sec
[-----------      31%                  ] 631 of 2000 complete in 616.9 sec
[------------     31%                  ] 632 of 2000 complete in 617.8 sec
[------------     31%                  ] 633 of 2000 complete in 618.8 sec
[------------     31%                  ] 634 of 2000 complete in 619.7 sec
[------------     31%                  ] 635 of 2000 complete in 620.7 sec
[------------     31%                  ] 636 of 2000 complete in 621.6 sec
[------------     31%                  ] 637 of 2000 complete in 622.6 sec
[------------     31%                  ] 638 of 2000 complete in 623.5 sec
[------------     31%                  ] 639 of 2000 complete in 624.5 sec
[------------     32%                  ] 640 of 2000 complete in 625.4 sec
[------------     32%                  ] 641 of 2000 complete in 626.4 sec
[------------     32%                  ] 642 of 2000 complete in 627.4 sec
[------------     32%                  ] 643 of 2000 complete in 628.4 sec
[------------     32%                  ] 644 of 2000 complete in 629.3 sec
[------------     32%                  ] 645 of 2000 complete in 630.2 sec
[------------     32%                  ] 646 of 2000 complete in 631.1 sec
[------------     32%                  ] 647 of 2000 complete in 632.0 sec
[------------     32%                  ] 648 of 2000 complete in 632.9 sec
[------------     32%                  ] 649 of 2000 complete in 633.8 sec
[------------     32%                  ] 650 of 2000 complete in 634.8 sec
[------------     32%                  ] 651 of 2000 complete in 635.7 sec
[------------     32%                  ] 652 of 2000 complete in 636.7 sec
[------------     32%                  ] 653 of 2000 complete in 637.7 sec
[------------     32%                  ] 654 of 2000 complete in 638.6 sec
[------------     32%                  ] 655 of 2000 complete in 639.5 sec
[------------     32%                  ] 656 of 2000 complete in 640.5 sec
[------------     32%                  ] 657 of 2000 complete in 641.4 sec

[------------     32%                  ] 658 of 2000 complete in 568.3 sec
[------------     32%                  ] 659 of 2000 complete in 569.1 sec
[------------     33%                  ] 660 of 2000 complete in 569.9 sec
[------------     33%                  ] 661 of 2000 complete in 570.7 sec
[------------     33%                  ] 662 of 2000 complete in 571.5 sec
[------------     33%                  ] 663 of 2000 complete in 572.3 sec
[------------     33%                  ] 664 of 2000 complete in 573.1 sec
[------------     33%                  ] 665 of 2000 complete in 573.9 sec
[------------     33%                  ] 666 of 2000 complete in 574.7 sec
[------------     33%                  ] 667 of 2000 complete in 575.5 sec
[------------     33%                  ] 668 of 2000 complete in 576.3 sec
[------------     33%                  ] 669 of 2000 complete in 577.1 sec
[------------     33%                  ] 670 of 2000 complete in 577.9 sec
[------------     33%                  ] 671 of 2000 complete in 578.7 sec
[------------     33%                  ] 672 of 2000 complete in 579.5 sec
[------------     33%                  ] 673 of 2000 complete in 580.4 sec
[------------     33%                  ] 674 of 2000 complete in 581.2 sec
[------------     33%                  ] 675 of 2000 complete in 582.1 sec
[------------     33%                  ] 676 of 2000 complete in 582.9 sec
[------------     33%                  ] 677 of 2000 complete in 583.8 sec
[------------     33%                  ] 678 of 2000 complete in 584.6 sec
[------------     33%                  ] 679 of 2000 complete in 585.4 sec
[------------     34%                  ] 680 of 2000 complete in 586.2 sec
[------------     34%                  ] 681 of 2000 complete in 587.0 sec
[------------     34%                  ] 682 of 2000 complete in 587.8 sec
[------------     34%                  ] 683 of 2000 complete in 588.6 sec
[------------     34%                  ] 684 of 2000 complete in 589.4 sec
[-------------    34%                  ] 685 of 2000 complete in 590.3 sec
[-------------    34%                  ] 686 of 2000 complete in 591.1 sec
[-------------    34%                  ] 687 of 2000 complete in 592.0 sec
[-------------    34%                  ] 688 of 2000 complete in 592.8 sec
[-------------    34%                  ] 689 of 2000 complete in 593.6 sec
[-------------    34%                  ] 690 of 2000 complete in 594.4 sec
[-------------    34%                  ] 691 of 2000 complete in 595.2 sec
[-------------    34%                  ] 692 of 2000 complete in 596.0 sec
[-------------    34%                  ] 693 of 2000 complete in 596.8 sec
[-------------    34%                  ] 694 of 2000 complete in 597.5 sec
[-------------    34%                  ] 695 of 2000 complete in 598.3 sec
[-------------    34%                  ] 696 of 2000 complete in 599.0 sec
[-------------    34%                  ] 697 of 2000 complete in 599.8 sec
[-------------    34%                  ] 698 of 2000 complete in 600.5 sec
[-------------    34%                  ] 699 of 2000 complete in 601.3 sec
[-------------    35%                  ] 700 of 2000 complete in 602.1 sec
[-------------    35%                  ] 701 of 2000 complete in 602.8 sec
[-------------    35%                  ] 702 of 2000 complete in 603.6 sec
[-------------    35%                  ] 703 of 2000 complete in 604.3 sec
[-------------    35%                  ] 704 of 2000 complete in 605.1 sec
[-------------    35%                  ] 705 of 2000 complete in 605.9 sec
[-------------    35%                  ] 706 of 2000 complete in 606.6 sec
[-------------    35%                  ] 707 of 2000 complete in 607.4 sec
[-------------    35%                  ] 708 of 2000 complete in 608.2 sec
[-------------    35%                  ] 709 of 2000 complete in 609.0 sec
[-------------    35%                  ] 710 of 2000 complete in 609.8 sec
[-------------    35%                  ] 711 of 2000 complete in 610.6 sec
[-------------    35%                  ] 712 of 2000 complete in 611.4 sec
[-------------    35%                  ] 713 of 2000 complete in 612.2 sec
[-------------    35%                  ] 714 of 2000 complete in 613.1 sec
[-------------    35%                  ] 715 of 2000 complete in 613.9 sec
[-------------    35%                  ] 716 of 2000 complete in 614.6 sec
[-------------    35%                  ] 717 of 2000 complete in 615.5 sec
[-------------    35%                  ] 718 of 2000 complete in 616.3 sec
[-------------    35%                  ] 719 of 2000 complete in 617.1 sec
[-------------    36%                  ] 720 of 2000 complete in 617.9 sec
[-------------    36%                  ] 721 of 2000 complete in 618.7 sec
[-------------    36%                  ] 722 of 2000 complete in 619.5 sec
[-------------    36%                  ] 723 of 2000 complete in 620.3 sec
[-------------    36%                  ] 724 of 2000 complete in 621.1 sec
[-------------    36%                  ] 725 of 2000 complete in 622.0 sec
[-------------    36%                  ] 726 of 2000 complete in 622.8 sec
[-------------    36%                  ] 727 of 2000 complete in 623.6 sec
[-------------    36%                  ] 728 of 2000 complete in 624.4 sec
[-------------    36%                  ] 729 of 2000 complete in 625.2 sec
[-------------    36%                  ] 730 of 2000 complete in 626.0 sec
[-------------    36%                  ] 731 of 2000 complete in 626.8 sec
[-------------    36%                  ] 732 of 2000 complete in 627.6 sec
[-------------    36%                  ] 733 of 2000 complete in 628.4 sec
[-------------    36%                  ] 734 of 2000 complete in 629.3 sec
[-------------    36%                  ] 735 of 2000 complete in 630.1 sec
[-------------    36%                  ] 736 of 2000 complete in 631.0 sec
[--------------   36%                  ] 737 of 2000 complete in 631.8 sec
[--------------   36%                  ] 738 of 2000 complete in 632.7 sec
[--------------   36%                  ] 739 of 2000 complete in 633.5 sec
[--------------   37%                  ] 740 of 2000 complete in 634.3 sec
[--------------   37%                  ] 741 of 2000 complete in 635.1 sec
[--------------   37%                  ] 742 of 2000 complete in 635.9 sec
[--------------   37%                  ] 743 of 2000 complete in 636.7 sec
[--------------   37%                  ] 744 of 2000 complete in 637.5 sec
[--------------   37%                  ] 745 of 2000 complete in 638.3 sec
[--------------   37%                  ] 746 of 2000 complete in 639.1 sec
[--------------   37%                  ] 747 of 2000 complete in 639.9 sec
[--------------   37%                  ] 748 of 2000 complete in 640.7 sec
[--------------   37%                  ] 749 of 2000 complete in 641.5 sec
[--------------   37%                  ] 750 of 2000 complete in 642.3 sec
[--------------   37%                  ] 751 of 2000 complete in 643.1 sec
[--------------   37%                  ] 752 of 2000 complete in 643.9 sec
[--------------   37%                  ] 753 of 2000 complete in 644.7 sec
[--------------   37%                  ] 754 of 2000 complete in 645.5 sec
[--------------   37%                  ] 755 of 2000 complete in 646.3 sec
[--------------   37%                  ] 756 of 2000 complete in 647.1 sec
[--------------   37%                  ] 757 of 2000 complete in 647.9 sec
[--------------   37%                  ] 758 of 2000 complete in 648.7 sec
[--------------   37%                  ] 759 of 2000 complete in 649.5 sec
[--------------   38%                  ] 760 of 2000 complete in 650.4 sec
[--------------   38%                  ] 761 of 2000 complete in 651.2 sec
[--------------   38%                  ] 762 of 2000 complete in 651.9 sec
[--------------   38%                  ] 763 of 2000 complete in 652.7 sec
[--------------   38%                  ] 764 of 2000 complete in 653.5 sec
[--------------   38%                  ] 765 of 2000 complete in 654.3 sec
[--------------   38%                  ] 766 of 2000 complete in 655.1 sec
[------------     32%                  ] 659 of 2000 complete in 565.9 sec
[------------     33%                  ] 660 of 2000 complete in 566.6 sec
[------------     33%                  ] 661 of 2000 complete in 567.5 sec
[------------     33%                  ] 662 of 2000 complete in 568.2 sec
[------------     33%                  ] 663 of 2000 complete in 569.0 sec
[------------     33%                  ] 664 of 2000 complete in 569.9 sec
[------------     33%                  ] 665 of 2000 complete in 570.7 sec
[------------     33%                  ] 666 of 2000 complete in 571.5 sec
[------------     33%                  ] 667 of 2000 complete in 572.3 sec
[------------     33%                  ] 668 of 2000 complete in 573.1 sec
[------------     33%                  ] 669 of 2000 complete in 574.0 sec
[------------     33%                  ] 670 of 2000 complete in 574.8 sec
[------------     33%                  ] 671 of 2000 complete in 575.6 sec
[------------     33%                  ] 672 of 2000 complete in 576.4 sec
[------------     33%                  ] 673 of 2000 complete in 577.2 sec
[------------     33%                  ] 674 of 2000 complete in 578.1 sec
[------------     33%                  ] 675 of 2000 complete in 578.9 sec
[------------     33%                  ] 676 of 2000 complete in 579.7 sec
[------------     33%                  ] 677 of 2000 complete in 580.5 sec
[------------     33%                  ] 678 of 2000 complete in 581.3 sec
[------------     33%                  ] 679 of 2000 complete in 582.2 sec
[------------     34%                  ] 680 of 2000 complete in 583.1 sec
[------------     34%                  ] 681 of 2000 complete in 583.9 sec
[------------     34%                  ] 682 of 2000 complete in 584.8 sec
[------------     34%                  ] 683 of 2000 complete in 585.7 sec
[------------     34%                  ] 684 of 2000 complete in 586.5 sec
[-------------    34%                  ] 685 of 2000 complete in 587.4 sec
[-------------    34%                  ] 686 of 2000 complete in 588.3 sec
[-------------    34%                  ] 687 of 2000 complete in 589.1 sec
[-------------    34%                  ] 688 of 2000 complete in 590.0 sec
[-------------    34%                  ] 689 of 2000 complete in 590.8 sec
[-------------    34%                  ] 690 of 2000 complete in 591.6 sec
[-------------    34%                  ] 691 of 2000 complete in 592.5 sec
[-------------    34%                  ] 692 of 2000 complete in 593.4 sec
[-------------    34%                  ] 693 of 2000 complete in 594.2 sec
[-------------    34%                  ] 694 of 2000 complete in 595.0 sec
[-------------    34%                  ] 695 of 2000 complete in 595.8 sec
[-------------    34%                  ] 696 of 2000 complete in 596.7 sec
[-------------    34%                  ] 697 of 2000 complete in 597.5 sec
[-------------    34%                  ] 698 of 2000 complete in 598.4 sec
[-------------    34%                  ] 699 of 2000 complete in 599.2 sec
[-------------    35%                  ] 700 of 2000 complete in 600.1 sec
[-------------    35%                  ] 701 of 2000 complete in 600.9 sec
[-------------    35%                  ] 702 of 2000 complete in 601.8 sec
[-------------    35%                  ] 703 of 2000 complete in 602.6 sec
[-------------    35%                  ] 704 of 2000 complete in 603.4 sec
[-------------    35%                  ] 705 of 2000 complete in 604.3 sec
[-------------    35%                  ] 706 of 2000 complete in 605.1 sec
[-------------    35%                  ] 707 of 2000 complete in 605.9 sec
[-------------    35%                  ] 708 of 2000 complete in 606.8 sec
[-------------    35%                  ] 709 of 2000 complete in 607.6 sec
[-------------    35%                  ] 710 of 2000 complete in 608.5 sec
[-------------    35%                  ] 711 of 2000 complete in 609.3 sec
[-------------    35%                  ] 712 of 2000 complete in 610.2 sec
[-------------    35%                  ] 713 of 2000 complete in 611.0 sec
[-------------    35%                  ] 714 of 2000 complete in 611.9 sec
[-------------    35%                  ] 715 of 2000 complete in 612.7 sec
[-------------    35%                  ] 716 of 2000 complete in 613.6 sec
[-------------    35%                  ] 717 of 2000 complete in 614.5 sec
[-------------    35%                  ] 718 of 2000 complete in 615.4 sec
[-------------    35%                  ] 719 of 2000 complete in 616.3 sec
[-------------    36%                  ] 720 of 2000 complete in 617.2 sec
[-------------    36%                  ] 721 of 2000 complete in 618.0 sec
[-------------    36%                  ] 722 of 2000 complete in 618.8 sec
[-------------    36%                  ] 723 of 2000 complete in 619.7 sec
[-------------    36%                  ] 724 of 2000 complete in 620.5 sec
[-------------    36%                  ] 725 of 2000 complete in 621.4 sec
[-------------    36%                  ] 726 of 2000 complete in 622.4 sec
[-------------    36%                  ] 727 of 2000 complete in 623.2 sec
[-------------    36%                  ] 728 of 2000 complete in 624.1 sec
[-------------    36%                  ] 729 of 2000 complete in 625.0 sec
[-------------    36%                  ] 730 of 2000 complete in 625.8 sec
[-------------    36%                  ] 731 of 2000 complete in 626.7 sec
[-------------    36%                  ] 732 of 2000 complete in 627.5 sec
[-------------    36%                  ] 733 of 2000 complete in 628.4 sec
[-------------    36%                  ] 734 of 2000 complete in 629.2 sec
[-------------    36%                  ] 735 of 2000 complete in 630.0 sec
[-------------    36%                  ] 736 of 2000 complete in 630.9 sec
[--------------   36%                  ] 737 of 2000 complete in 631.7 sec
[--------------   36%                  ] 738 of 2000 complete in 632.6 sec
[--------------   36%                  ] 739 of 2000 complete in 633.4 sec
[--------------   37%                  ] 740 of 2000 complete in 634.3 sec
[--------------   37%                  ] 741 of 2000 complete in 635.1 sec
[--------------   37%                  ] 742 of 2000 complete in 636.0 sec
[--------------   37%                  ] 743 of 2000 complete in 636.8 sec
[--------------   37%                  ] 744 of 2000 complete in 637.6 sec
[--------------   37%                  ] 745 of 2000 complete in 638.5 sec
[--------------   37%                  ] 746 of 2000 complete in 639.3 sec
[--------------   37%                  ] 747 of 2000 complete in 640.2 sec
[--------------   37%                  ] 748 of 2000 complete in 641.0 sec
[--------------   37%                  ] 749 of 2000 complete in 641.9 sec
[--------------   37%                  ] 750 of 2000 complete in 642.7 sec
[--------------   37%                  ] 751 of 2000 complete in 643.5 sec
[--------------   37%                  ] 752 of 2000 complete in 644.4 sec
[--------------   37%                  ] 753 of 2000 complete in 645.1 sec
[--------------   37%                  ] 754 of 2000 complete in 645.9 sec
[--------------   37%                  ] 755 of 2000 complete in 646.8 sec
[--------------   37%                  ] 756 of 2000 complete in 647.6 sec
[--------------   37%                  ] 757 of 2000 complete in 648.4 sec
[--------------   37%                  ] 758 of 2000 complete in 649.2 sec
[--------------   37%                  ] 759 of 2000 complete in 650.0 sec
[--------------   38%                  ] 760 of 2000 complete in 650.9 sec
[--------------   38%                  ] 761 of 2000 complete in 651.6 sec
[--------------   38%                  ] 762 of 2000 complete in 652.4 sec
[--------------   38%                  ] 763 of 2000 complete in 653.3 sec
[--------------   38%                  ] 764 of 2000 complete in 654.1 sec
[--------------   38%                  ] 765 of 2000 complete in 654.9 sec
[--------------   38%                  ] 766 of 2000 complete in 655.8 sec
[--------------   38%                  ] 767 of 2000 complete in 656.6 sec

[------------     32%                  ] 658 of 2000 complete in 642.3 sec
[------------     32%                  ] 659 of 2000 complete in 643.2 sec
[------------     33%                  ] 660 of 2000 complete in 644.1 sec
[------------     33%                  ] 661 of 2000 complete in 645.0 sec
[------------     33%                  ] 662 of 2000 complete in 645.9 sec
[------------     33%                  ] 663 of 2000 complete in 646.7 sec
[------------     33%                  ] 664 of 2000 complete in 647.7 sec
[------------     33%                  ] 665 of 2000 complete in 648.6 sec
[------------     33%                  ] 666 of 2000 complete in 649.5 sec
[------------     33%                  ] 667 of 2000 complete in 650.5 sec
[------------     33%                  ] 668 of 2000 complete in 651.4 sec
[------------     33%                  ] 669 of 2000 complete in 652.3 sec
[------------     33%                  ] 670 of 2000 complete in 653.2 sec
[------------     33%                  ] 671 of 2000 complete in 654.1 sec
[------------     33%                  ] 672 of 2000 complete in 655.0 sec
[------------     33%                  ] 673 of 2000 complete in 656.0 sec
[------------     33%                  ] 674 of 2000 complete in 656.9 sec
[------------     33%                  ] 675 of 2000 complete in 657.8 sec
[------------     33%                  ] 676 of 2000 complete in 658.7 sec
[------------     33%                  ] 677 of 2000 complete in 659.6 sec
[------------     33%                  ] 678 of 2000 complete in 660.5 sec
[------------     33%                  ] 679 of 2000 complete in 661.5 sec
[------------     34%                  ] 680 of 2000 complete in 662.3 sec
[------------     34%                  ] 681 of 2000 complete in 663.2 sec
[------------     34%                  ] 682 of 2000 complete in 664.1 sec
[------------     34%                  ] 683 of 2000 complete in 664.9 sec
[------------     34%                  ] 684 of 2000 complete in 665.7 sec
[-------------    34%                  ] 685 of 2000 complete in 666.6 sec
[-------------    34%                  ] 686 of 2000 complete in 667.4 sec
[-------------    34%                  ] 687 of 2000 complete in 668.2 sec
[-------------    34%                  ] 688 of 2000 complete in 669.1 sec
[-------------    34%                  ] 689 of 2000 complete in 669.9 sec
[-------------    34%                  ] 690 of 2000 complete in 670.7 sec
[-------------    34%                  ] 691 of 2000 complete in 671.5 sec
[-------------    34%                  ] 692 of 2000 complete in 672.4 sec
[-------------    34%                  ] 693 of 2000 complete in 673.2 sec
[-------------    34%                  ] 694 of 2000 complete in 674.0 sec
[-------------    34%                  ] 695 of 2000 complete in 674.9 sec
[-------------    34%                  ] 696 of 2000 complete in 675.7 sec
[-------------    34%                  ] 697 of 2000 complete in 676.5 sec
[-------------    34%                  ] 698 of 2000 complete in 677.3 sec
[-------------    34%                  ] 699 of 2000 complete in 678.2 sec
[-------------    35%                  ] 700 of 2000 complete in 679.1 sec
[-------------    35%                  ] 701 of 2000 complete in 679.9 sec
[-------------    35%                  ] 702 of 2000 complete in 680.8 sec
[-------------    35%                  ] 703 of 2000 complete in 681.6 sec
[-------------    35%                  ] 704 of 2000 complete in 682.5 sec
[-------------    35%                  ] 705 of 2000 complete in 683.3 sec
[-------------    35%                  ] 706 of 2000 complete in 684.2 sec
[-------------    35%                  ] 707 of 2000 complete in 685.0 sec
[-------------    35%                  ] 708 of 2000 complete in 685.9 sec
[-------------    35%                  ] 709 of 2000 complete in 686.7 sec
[-------------    35%                  ] 710 of 2000 complete in 687.6 sec
[-------------    35%                  ] 711 of 2000 complete in 688.5 sec
[-------------    35%                  ] 712 of 2000 complete in 689.3 sec
[-------------    35%                  ] 713 of 2000 complete in 690.2 sec
[-------------    35%                  ] 714 of 2000 complete in 691.0 sec
[-------------    35%                  ] 715 of 2000 complete in 691.8 sec
[-------------    35%                  ] 716 of 2000 complete in 692.6 sec
[-------------    35%                  ] 717 of 2000 complete in 693.4 sec
[-------------    35%                  ] 718 of 2000 complete in 694.2 sec
[-------------    35%                  ] 719 of 2000 complete in 694.9 sec
[-------------    36%                  ] 720 of 2000 complete in 695.7 sec
[-------------    36%                  ] 721 of 2000 complete in 696.5 sec
[-------------    36%                  ] 722 of 2000 complete in 697.2 sec
[-------------    36%                  ] 723 of 2000 complete in 698.0 sec
[-------------    36%                  ] 724 of 2000 complete in 698.8 sec
[-------------    36%                  ] 725 of 2000 complete in 699.6 sec
[-------------    36%                  ] 726 of 2000 complete in 700.3 sec
[-------------    36%                  ] 727 of 2000 complete in 701.1 sec
[-------------    36%                  ] 728 of 2000 complete in 701.9 sec
[-------------    36%                  ] 729 of 2000 complete in 702.7 sec
[-------------    36%                  ] 730 of 2000 complete in 703.5 sec
[-------------    36%                  ] 731 of 2000 complete in 704.3 sec
[-------------    36%                  ] 732 of 2000 complete in 705.1 sec
[-------------    36%                  ] 733 of 2000 complete in 705.8 sec
[-------------    36%                  ] 734 of 2000 complete in 706.6 sec
[-------------    36%                  ] 735 of 2000 complete in 707.3 sec
[-------------    36%                  ] 736 of 2000 complete in 708.1 sec
[--------------   36%                  ] 737 of 2000 complete in 708.9 sec
[--------------   36%                  ] 738 of 2000 complete in 709.7 sec
[--------------   36%                  ] 739 of 2000 complete in 710.5 sec
[--------------   37%                  ] 740 of 2000 complete in 711.3 sec
[--------------   37%                  ] 741 of 2000 complete in 712.1 sec
[--------------   37%                  ] 742 of 2000 complete in 712.9 sec
[--------------   37%                  ] 743 of 2000 complete in 713.7 sec
[--------------   37%                  ] 744 of 2000 complete in 714.5 sec
[--------------   37%                  ] 745 of 2000 complete in 715.3 sec
[--------------   37%                  ] 746 of 2000 complete in 716.1 sec
[--------------   37%                  ] 747 of 2000 complete in 717.0 sec
[--------------   37%                  ] 748 of 2000 complete in 717.8 sec
[--------------   37%                  ] 749 of 2000 complete in 718.6 sec
[--------------   37%                  ] 750 of 2000 complete in 719.5 sec
[--------------   37%                  ] 751 of 2000 complete in 720.3 sec
[--------------   37%                  ] 752 of 2000 complete in 721.2 sec
[--------------   37%                  ] 753 of 2000 complete in 722.0 sec
[--------------   37%                  ] 754 of 2000 complete in 722.9 sec
[--------------   37%                  ] 755 of 2000 complete in 723.7 sec
[--------------   37%                  ] 756 of 2000 complete in 724.5 sec
[--------------   37%                  ] 757 of 2000 complete in 725.3 sec
[--------------   37%                  ] 758 of 2000 complete in 726.1 sec
[--------------   37%                  ] 759 of 2000 complete in 726.9 sec
[--------------   38%                  ] 760 of 2000 complete in 727.7 sec
[--------------   38%                  ] 761 of 2000 complete in 728.5 sec
[--------------   38%                  ] 762 of 2000 complete in 729.3 sec
[--------------   38%                  ] 763 of 2000 complete in 730.1 sec
[--------------   38%                  ] 764 of 2000 complete in 730.8 sec
[--------------   38%                  ] 765 of 2000 complete in 731.6 sec
[--------------   38%                  ] 766 of 2000 complete in 732.4 sec
[------------     32%                  ] 658 of 2000 complete in 639.7 sec
[------------     32%                  ] 659 of 2000 complete in 640.7 sec
[------------     33%                  ] 660 of 2000 complete in 641.7 sec
[------------     33%                  ] 661 of 2000 complete in 642.7 sec
[------------     33%                  ] 662 of 2000 complete in 643.7 sec
[------------     33%                  ] 663 of 2000 complete in 644.7 sec
[------------     33%                  ] 664 of 2000 complete in 645.6 sec
[------------     33%                  ] 665 of 2000 complete in 646.6 sec
[------------     33%                  ] 666 of 2000 complete in 647.7 sec
[------------     33%                  ] 667 of 2000 complete in 648.7 sec
[------------     33%                  ] 668 of 2000 complete in 649.7 sec
[------------     33%                  ] 669 of 2000 complete in 650.7 sec
[------------     33%                  ] 670 of 2000 complete in 651.7 sec
[------------     33%                  ] 671 of 2000 complete in 652.7 sec
[------------     33%                  ] 672 of 2000 complete in 653.7 sec
[------------     33%                  ] 673 of 2000 complete in 654.8 sec
[------------     33%                  ] 674 of 2000 complete in 655.8 sec
[------------     33%                  ] 675 of 2000 complete in 656.8 sec
[------------     33%                  ] 676 of 2000 complete in 657.8 sec
[------------     33%                  ] 677 of 2000 complete in 658.8 sec
[------------     33%                  ] 678 of 2000 complete in 659.8 sec
[------------     33%                  ] 679 of 2000 complete in 660.8 sec
[------------     34%                  ] 680 of 2000 complete in 661.8 sec
[------------     34%                  ] 681 of 2000 complete in 662.8 sec
[------------     34%                  ] 682 of 2000 complete in 663.8 sec
[------------     34%                  ] 683 of 2000 complete in 664.8 sec
[------------     34%                  ] 684 of 2000 complete in 665.8 sec
[-------------    34%                  ] 685 of 2000 complete in 666.9 sec
[-------------    34%                  ] 686 of 2000 complete in 667.8 sec
[-------------    34%                  ] 687 of 2000 complete in 668.8 sec
[-------------    34%                  ] 688 of 2000 complete in 669.7 sec
[-------------    34%                  ] 689 of 2000 complete in 670.7 sec
[-------------    34%                  ] 690 of 2000 complete in 671.6 sec
[-------------    34%                  ] 691 of 2000 complete in 672.5 sec
[-------------    34%                  ] 692 of 2000 complete in 673.5 sec
[-------------    34%                  ] 693 of 2000 complete in 674.4 sec
[-------------    34%                  ] 694 of 2000 complete in 675.4 sec
[-------------    34%                  ] 695 of 2000 complete in 676.2 sec
[-------------    34%                  ] 696 of 2000 complete in 677.1 sec
[-------------    34%                  ] 697 of 2000 complete in 678.0 sec
[-------------    34%                  ] 698 of 2000 complete in 678.9 sec
[-------------    34%                  ] 699 of 2000 complete in 679.8 sec
[-------------    35%                  ] 700 of 2000 complete in 680.7 sec
[-------------    35%                  ] 701 of 2000 complete in 681.6 sec
[-------------    35%                  ] 702 of 2000 complete in 682.5 sec
[-------------    35%                  ] 703 of 2000 complete in 683.5 sec
[-------------    35%                  ] 704 of 2000 complete in 684.4 sec
[-------------    35%                  ] 705 of 2000 complete in 685.4 sec
[-------------    35%                  ] 706 of 2000 complete in 686.3 sec
[-------------    35%                  ] 707 of 2000 complete in 687.2 sec
[-------------    35%                  ] 708 of 2000 complete in 688.1 sec
[-------------    35%                  ] 709 of 2000 complete in 689.1 sec
[-------------    35%                  ] 710 of 2000 complete in 690.0 sec
[-------------    35%                  ] 711 of 2000 complete in 691.0 sec
[-------------    35%                  ] 712 of 2000 complete in 691.9 sec
[-------------    35%                  ] 713 of 2000 complete in 692.9 sec
[-------------    35%                  ] 714 of 2000 complete in 693.8 sec
[-------------    35%                  ] 715 of 2000 complete in 694.8 sec
[-------------    35%                  ] 716 of 2000 complete in 695.7 sec
[-------------    35%                  ] 717 of 2000 complete in 696.7 sec
[-------------    35%                  ] 718 of 2000 complete in 697.6 sec
[-------------    35%                  ] 719 of 2000 complete in 698.6 sec
[-------------    36%                  ] 720 of 2000 complete in 699.6 sec
[-------------    36%                  ] 721 of 2000 complete in 700.6 sec
[-------------    36%                  ] 722 of 2000 complete in 701.5 sec
[-------------    36%                  ] 723 of 2000 complete in 702.4 sec
[-------------    36%                  ] 724 of 2000 complete in 703.4 sec
[-------------    36%                  ] 725 of 2000 complete in 704.3 sec
[-------------    36%                  ] 726 of 2000 complete in 705.2 sec
[-------------    36%                  ] 727 of 2000 complete in 706.1 sec
[-------------    36%                  ] 728 of 2000 complete in 707.0 sec
[-------------    36%                  ] 729 of 2000 complete in 707.9 sec
[-------------    36%                  ] 730 of 2000 complete in 708.9 sec
[-------------    36%                  ] 731 of 2000 complete in 709.8 sec
[-------------    36%                  ] 732 of 2000 complete in 710.7 sec
[-------------    36%                  ] 733 of 2000 complete in 711.7 sec
[-------------    36%                  ] 734 of 2000 complete in 712.6 sec
[-------------    36%                  ] 735 of 2000 complete in 713.6 sec
[-------------    36%                  ] 736 of 2000 complete in 714.6 sec
[--------------   36%                  ] 737 of 2000 complete in 715.6 sec
[--------------   36%                  ] 738 of 2000 complete in 716.5 sec
[--------------   36%                  ] 739 of 2000 complete in 717.5 sec
[--------------   37%                  ] 740 of 2000 complete in 718.5 sec
[--------------   37%                  ] 741 of 2000 complete in 719.5 sec
[--------------   37%                  ] 742 of 2000 complete in 720.4 sec
[--------------   37%                  ] 743 of 2000 complete in 721.4 sec
[--------------   37%                  ] 744 of 2000 complete in 722.3 sec
[--------------   37%                  ] 745 of 2000 complete in 723.2 sec
[--------------   37%                  ] 746 of 2000 complete in 724.2 sec
[--------------   37%                  ] 747 of 2000 complete in 725.0 sec
[--------------   37%                  ] 748 of 2000 complete in 725.9 sec
[--------------   37%                  ] 749 of 2000 complete in 726.8 sec
[--------------   37%                  ] 750 of 2000 complete in 727.7 sec
[--------------   37%                  ] 751 of 2000 complete in 728.6 sec
[--------------   37%                  ] 752 of 2000 complete in 729.5 sec
[--------------   37%                  ] 753 of 2000 complete in 730.4 sec
[--------------   37%                  ] 754 of 2000 complete in 731.3 sec
[--------------   37%                  ] 755 of 2000 complete in 732.2 sec
[--------------   37%                  ] 756 of 2000 complete in 733.1 sec
[--------------   37%                  ] 757 of 2000 complete in 734.0 sec
[--------------   37%                  ] 758 of 2000 complete in 734.8 sec
[--------------   37%                  ] 759 of 2000 complete in 735.7 sec
[--------------   38%                  ] 760 of 2000 complete in 736.6 sec
[--------------   38%                  ] 761 of 2000 complete in 737.5 sec
[--------------   38%                  ] 762 of 2000 complete in 738.4 sec
[--------------   38%                  ] 763 of 2000 complete in 739.3 sec
[--------------   38%                  ] 764 of 2000 complete in 740.2 sec
[--------------   38%                  ] 765 of 2000 complete in 741.1 sec
[--------------   38%                  ] 766 of 2000 complete in 742.1 sec

[--------------   38%                  ] 768 of 2000 complete in 657.4 sec
[--------------   38%                  ] 769 of 2000 complete in 658.2 sec
[--------------   38%                  ] 770 of 2000 complete in 659.1 sec
[--------------   38%                  ] 771 of 2000 complete in 659.9 sec
[--------------   38%                  ] 772 of 2000 complete in 660.6 sec
[--------------   38%                  ] 773 of 2000 complete in 661.4 sec
[--------------   38%                  ] 774 of 2000 complete in 662.2 sec
[--------------   38%                  ] 775 of 2000 complete in 663.0 sec
[--------------   38%                  ] 776 of 2000 complete in 663.8 sec
[--------------   38%                  ] 777 of 2000 complete in 664.6 sec
[--------------   38%                  ] 778 of 2000 complete in 665.3 sec
[--------------   38%                  ] 779 of 2000 complete in 666.1 sec
[--------------   39%                  ] 780 of 2000 complete in 666.9 sec
[--------------   39%                  ] 781 of 2000 complete in 667.6 sec
[--------------   39%                  ] 782 of 2000 complete in 668.4 sec
[--------------   39%                  ] 783 of 2000 complete in 669.2 sec
[--------------   39%                  ] 784 of 2000 complete in 669.9 sec
[--------------   39%                  ] 785 of 2000 complete in 670.7 sec
[--------------   39%                  ] 786 of 2000 complete in 671.5 sec
[--------------   39%                  ] 787 of 2000 complete in 672.2 sec
[--------------   39%                  ] 788 of 2000 complete in 673.0 sec
[--------------   39%                  ] 789 of 2000 complete in 673.8 sec
[---------------  39%                  ] 790 of 2000 complete in 674.6 sec
[---------------  39%                  ] 791 of 2000 complete in 675.4 sec
[---------------  39%                  ] 792 of 2000 complete in 676.2 sec
[---------------  39%                  ] 793 of 2000 complete in 677.0 sec
[---------------  39%                  ] 794 of 2000 complete in 677.7 sec
[---------------  39%                  ] 795 of 2000 complete in 678.6 sec
[---------------  39%                  ] 796 of 2000 complete in 679.4 sec
[---------------  39%                  ] 797 of 2000 complete in 680.2 sec
[---------------  39%                  ] 798 of 2000 complete in 680.9 sec
[---------------  39%                  ] 799 of 2000 complete in 681.7 sec
[---------------  40%                  ] 800 of 2000 complete in 682.4 sec
[---------------  40%                  ] 801 of 2000 complete in 683.2 sec
[---------------  40%                  ] 802 of 2000 complete in 684.0 sec
[---------------  40%                  ] 803 of 2000 complete in 684.8 sec
[---------------  40%                  ] 804 of 2000 complete in 685.7 sec
[---------------  40%                  ] 805 of 2000 complete in 686.5 sec
[---------------  40%                  ] 806 of 2000 complete in 687.2 sec
[---------------  40%                  ] 807 of 2000 complete in 688.0 sec
[---------------  40%                  ] 808 of 2000 complete in 688.9 sec
[---------------  40%                  ] 809 of 2000 complete in 689.6 sec
[---------------  40%                  ] 810 of 2000 complete in 690.5 sec
[---------------  40%                  ] 811 of 2000 complete in 691.3 sec
[---------------  40%                  ] 812 of 2000 complete in 692.1 sec
[---------------  40%                  ] 813 of 2000 complete in 692.9 sec
[---------------  40%                  ] 814 of 2000 complete in 693.7 sec
[---------------  40%                  ] 815 of 2000 complete in 694.6 sec
[---------------  40%                  ] 816 of 2000 complete in 695.4 sec
[---------------  40%                  ] 817 of 2000 complete in 696.2 sec
[---------------  40%                  ] 818 of 2000 complete in 697.1 sec
[---------------  40%                  ] 819 of 2000 complete in 697.9 sec
[---------------  41%                  ] 820 of 2000 complete in 698.7 sec
[---------------  41%                  ] 821 of 2000 complete in 699.5 sec
[---------------  41%                  ] 822 of 2000 complete in 700.3 sec
[---------------  41%                  ] 823 of 2000 complete in 701.1 sec
[---------------  41%                  ] 824 of 2000 complete in 701.9 sec
[---------------  41%                  ] 825 of 2000 complete in 702.7 sec
[---------------  41%                  ] 826 of 2000 complete in 703.6 sec
[---------------  41%                  ] 827 of 2000 complete in 704.4 sec
[---------------  41%                  ] 828 of 2000 complete in 705.1 sec
[---------------  41%                  ] 829 of 2000 complete in 705.9 sec
[---------------  41%                  ] 830 of 2000 complete in 706.7 sec
[---------------  41%                  ] 831 of 2000 complete in 707.5 sec
[---------------  41%                  ] 832 of 2000 complete in 708.3 sec
[---------------  41%                  ] 833 of 2000 complete in 709.2 sec
[---------------  41%                  ] 834 of 2000 complete in 710.0 sec
[---------------  41%                  ] 835 of 2000 complete in 710.8 sec
[---------------  41%                  ] 836 of 2000 complete in 711.6 sec
[---------------  41%                  ] 837 of 2000 complete in 712.5 sec
[---------------  41%                  ] 838 of 2000 complete in 713.3 sec
[---------------  41%                  ] 839 of 2000 complete in 714.1 sec
[---------------  42%                  ] 840 of 2000 complete in 714.9 sec
[---------------  42%                  ] 841 of 2000 complete in 715.8 sec
[---------------  42%                  ] 842 of 2000 complete in 716.6 sec
[---------------- 42%                  ] 843 of 2000 complete in 717.4 sec
[---------------- 42%                  ] 844 of 2000 complete in 718.3 sec
[---------------- 42%                  ] 845 of 2000 complete in 719.2 sec
[---------------- 42%                  ] 846 of 2000 complete in 720.0 sec
[---------------- 42%                  ] 847 of 2000 complete in 720.9 sec
[---------------- 42%                  ] 848 of 2000 complete in 721.7 sec
[---------------- 42%                  ] 849 of 2000 complete in 722.6 sec
[---------------- 42%                  ] 850 of 2000 complete in 723.5 sec
[---------------- 42%                  ] 851 of 2000 complete in 724.3 sec
[---------------- 42%                  ] 852 of 2000 complete in 725.2 sec
[---------------- 42%                  ] 853 of 2000 complete in 726.0 sec
[---------------- 42%                  ] 854 of 2000 complete in 726.8 sec
[---------------- 42%                  ] 855 of 2000 complete in 727.6 sec
[---------------- 42%                  ] 856 of 2000 complete in 728.5 sec
[---------------- 42%                  ] 857 of 2000 complete in 729.3 sec
[---------------- 42%                  ] 858 of 2000 complete in 730.2 sec
[---------------- 42%                  ] 859 of 2000 complete in 731.1 sec
[---------------- 43%                  ] 860 of 2000 complete in 732.0 sec
[---------------- 43%                  ] 861 of 2000 complete in 732.9 sec
[---------------- 43%                  ] 862 of 2000 complete in 733.8 sec
[---------------- 43%                  ] 863 of 2000 complete in 734.7 sec
[---------------- 43%                  ] 864 of 2000 complete in 735.6 sec
[---------------- 43%                  ] 865 of 2000 complete in 736.5 sec
[---------------- 43%                  ] 866 of 2000 complete in 737.4 sec
[---------------- 43%                  ] 867 of 2000 complete in 738.3 sec
[---------------- 43%                  ] 868 of 2000 complete in 739.3 sec
[---------------- 43%                  ] 869 of 2000 complete in 740.3 sec
[---------------- 43%                  ] 870 of 2000 complete in 741.2 sec
[---------------- 43%                  ] 871 of 2000 complete in 742.1 sec
[---------------- 43%                  ] 872 of 2000 complete in 743.1 sec
[---------------- 43%                  ] 873 of 2000 complete in 744.0 sec
[---------------- 43%                  ] 874 of 2000 complete in 745.0 sec
[---------------- 43%                  ] 875 of 2000 complete in 745.9 sec
[---------------- 43%                  ] 876 of 2000 complete in 746.9 sec
[--------------   38%                  ] 767 of 2000 complete in 655.9 sec
[--------------   38%                  ] 768 of 2000 complete in 656.7 sec
[--------------   38%                  ] 769 of 2000 complete in 657.5 sec
[--------------   38%                  ] 770 of 2000 complete in 658.3 sec
[--------------   38%                  ] 771 of 2000 complete in 659.0 sec
[--------------   38%                  ] 772 of 2000 complete in 659.8 sec
[--------------   38%                  ] 773 of 2000 complete in 660.6 sec
[--------------   38%                  ] 774 of 2000 complete in 661.3 sec
[--------------   38%                  ] 775 of 2000 complete in 662.1 sec
[--------------   38%                  ] 776 of 2000 complete in 662.9 sec
[--------------   38%                  ] 777 of 2000 complete in 663.7 sec
[--------------   38%                  ] 778 of 2000 complete in 664.5 sec
[--------------   38%                  ] 779 of 2000 complete in 665.3 sec
[--------------   39%                  ] 780 of 2000 complete in 666.0 sec
[--------------   39%                  ] 781 of 2000 complete in 666.8 sec
[--------------   39%                  ] 782 of 2000 complete in 667.5 sec
[--------------   39%                  ] 783 of 2000 complete in 668.3 sec
[--------------   39%                  ] 784 of 2000 complete in 669.0 sec
[--------------   39%                  ] 785 of 2000 complete in 669.8 sec
[--------------   39%                  ] 786 of 2000 complete in 670.6 sec
[--------------   39%                  ] 787 of 2000 complete in 671.4 sec
[--------------   39%                  ] 788 of 2000 complete in 672.2 sec
[--------------   39%                  ] 789 of 2000 complete in 673.0 sec
[---------------  39%                  ] 790 of 2000 complete in 673.8 sec
[---------------  39%                  ] 791 of 2000 complete in 674.7 sec
[---------------  39%                  ] 792 of 2000 complete in 675.5 sec
[---------------  39%                  ] 793 of 2000 complete in 676.4 sec
[---------------  39%                  ] 794 of 2000 complete in 677.2 sec
[---------------  39%                  ] 795 of 2000 complete in 678.1 sec
[---------------  39%                  ] 796 of 2000 complete in 678.9 sec
[---------------  39%                  ] 797 of 2000 complete in 679.8 sec
[---------------  39%                  ] 798 of 2000 complete in 680.7 sec
[---------------  39%                  ] 799 of 2000 complete in 681.6 sec
[---------------  40%                  ] 800 of 2000 complete in 682.4 sec
[---------------  40%                  ] 801 of 2000 complete in 683.3 sec
[---------------  40%                  ] 802 of 2000 complete in 684.2 sec
[---------------  40%                  ] 803 of 2000 complete in 685.0 sec
[---------------  40%                  ] 804 of 2000 complete in 685.9 sec
[---------------  40%                  ] 805 of 2000 complete in 686.8 sec
[---------------  40%                  ] 806 of 2000 complete in 687.7 sec
[---------------  40%                  ] 807 of 2000 complete in 688.6 sec
[---------------  40%                  ] 808 of 2000 complete in 689.5 sec
[---------------  40%                  ] 809 of 2000 complete in 690.4 sec
[---------------  40%                  ] 810 of 2000 complete in 691.2 sec
[---------------  40%                  ] 811 of 2000 complete in 692.1 sec
[---------------  40%                  ] 812 of 2000 complete in 693.0 sec
[---------------  40%                  ] 813 of 2000 complete in 693.9 sec
[---------------  40%                  ] 814 of 2000 complete in 694.8 sec
[---------------  40%                  ] 815 of 2000 complete in 695.6 sec
[---------------  40%                  ] 816 of 2000 complete in 696.5 sec
[---------------  40%                  ] 817 of 2000 complete in 697.4 sec
[---------------  40%                  ] 818 of 2000 complete in 698.3 sec
[---------------  40%                  ] 819 of 2000 complete in 699.2 sec
[---------------  41%                  ] 820 of 2000 complete in 700.1 sec
[---------------  41%                  ] 821 of 2000 complete in 701.0 sec
[---------------  41%                  ] 822 of 2000 complete in 701.9 sec
[---------------  41%                  ] 823 of 2000 complete in 702.8 sec
[---------------  41%                  ] 824 of 2000 complete in 703.7 sec
[---------------  41%                  ] 825 of 2000 complete in 704.6 sec
[---------------  41%                  ] 826 of 2000 complete in 705.5 sec
[---------------  41%                  ] 827 of 2000 complete in 706.4 sec
[---------------  41%                  ] 828 of 2000 complete in 707.2 sec
[---------------  41%                  ] 829 of 2000 complete in 708.1 sec
[---------------  41%                  ] 830 of 2000 complete in 709.0 sec
[---------------  41%                  ] 831 of 2000 complete in 709.9 sec
[---------------  41%                  ] 832 of 2000 complete in 710.7 sec
[---------------  41%                  ] 833 of 2000 complete in 711.6 sec
[---------------  41%                  ] 834 of 2000 complete in 712.4 sec
[---------------  41%                  ] 835 of 2000 complete in 713.3 sec
[---------------  41%                  ] 836 of 2000 complete in 714.2 sec
[---------------  41%                  ] 837 of 2000 complete in 715.1 sec
[---------------  41%                  ] 838 of 2000 complete in 716.0 sec
[---------------  41%                  ] 839 of 2000 complete in 716.8 sec
[---------------  42%                  ] 840 of 2000 complete in 717.7 sec
[---------------  42%                  ] 841 of 2000 complete in 718.6 sec
[---------------  42%                  ] 842 of 2000 complete in 719.6 sec
[---------------- 42%                  ] 843 of 2000 complete in 720.4 sec
[---------------- 42%                  ] 844 of 2000 complete in 721.3 sec
[---------------- 42%                  ] 845 of 2000 complete in 722.3 sec
[---------------- 42%                  ] 846 of 2000 complete in 723.2 sec
[---------------- 42%                  ] 847 of 2000 complete in 724.1 sec
[---------------- 42%                  ] 848 of 2000 complete in 724.9 sec
[---------------- 42%                  ] 849 of 2000 complete in 725.8 sec
[---------------- 42%                  ] 850 of 2000 complete in 726.7 sec
[---------------- 42%                  ] 851 of 2000 complete in 727.5 sec
[---------------- 42%                  ] 852 of 2000 complete in 728.4 sec
[---------------- 42%                  ] 853 of 2000 complete in 729.2 sec
[---------------- 42%                  ] 854 of 2000 complete in 730.1 sec
[---------------- 42%                  ] 855 of 2000 complete in 730.9 sec
[---------------- 42%                  ] 856 of 2000 complete in 731.8 sec
[---------------- 42%                  ] 857 of 2000 complete in 732.5 sec
[---------------- 42%                  ] 858 of 2000 complete in 733.3 sec
[---------------- 42%                  ] 859 of 2000 complete in 734.1 sec
[---------------- 43%                  ] 860 of 2000 complete in 734.9 sec
[---------------- 43%                  ] 861 of 2000 complete in 735.7 sec
[---------------- 43%                  ] 862 of 2000 complete in 736.5 sec
[---------------- 43%                  ] 863 of 2000 complete in 737.3 sec
[---------------- 43%                  ] 864 of 2000 complete in 738.1 sec
[---------------- 43%                  ] 865 of 2000 complete in 738.9 sec
[---------------- 43%                  ] 866 of 2000 complete in 739.7 sec
[---------------- 43%                  ] 867 of 2000 complete in 740.5 sec
[---------------- 43%                  ] 868 of 2000 complete in 741.4 sec
[---------------- 43%                  ] 869 of 2000 complete in 742.2 sec
[---------------- 43%                  ] 870 of 2000 complete in 743.1 sec
[---------------- 43%                  ] 871 of 2000 complete in 743.9 sec
[---------------- 43%                  ] 872 of 2000 complete in 744.8 sec
[---------------- 43%                  ] 873 of 2000 complete in 745.7 sec
[---------------- 43%                  ] 874 of 2000 complete in 746.6 sec
[---------------- 43%                  ] 875 of 2000 complete in 747.4 sec

[--------------   38%                  ] 767 of 2000 complete in 733.2 sec
[--------------   38%                  ] 768 of 2000 complete in 734.1 sec
[--------------   38%                  ] 769 of 2000 complete in 734.9 sec
[--------------   38%                  ] 770 of 2000 complete in 735.8 sec
[--------------   38%                  ] 771 of 2000 complete in 736.6 sec
[--------------   38%                  ] 772 of 2000 complete in 737.4 sec
[--------------   38%                  ] 773 of 2000 complete in 738.3 sec
[--------------   38%                  ] 774 of 2000 complete in 739.1 sec
[--------------   38%                  ] 775 of 2000 complete in 739.9 sec
[--------------   38%                  ] 776 of 2000 complete in 740.8 sec
[--------------   38%                  ] 777 of 2000 complete in 741.6 sec
[--------------   38%                  ] 778 of 2000 complete in 742.5 sec
[--------------   38%                  ] 779 of 2000 complete in 743.3 sec
[--------------   39%                  ] 780 of 2000 complete in 744.2 sec
[--------------   39%                  ] 781 of 2000 complete in 745.1 sec
[--------------   39%                  ] 782 of 2000 complete in 746.0 sec
[--------------   39%                  ] 783 of 2000 complete in 746.9 sec
[--------------   39%                  ] 784 of 2000 complete in 747.7 sec
[--------------   39%                  ] 785 of 2000 complete in 748.6 sec
[--------------   39%                  ] 786 of 2000 complete in 749.5 sec
[--------------   39%                  ] 787 of 2000 complete in 750.4 sec
[--------------   39%                  ] 788 of 2000 complete in 751.3 sec
[--------------   39%                  ] 789 of 2000 complete in 752.1 sec
[---------------  39%                  ] 790 of 2000 complete in 753.0 sec
[---------------  39%                  ] 791 of 2000 complete in 753.8 sec
[---------------  39%                  ] 792 of 2000 complete in 754.6 sec
[---------------  39%                  ] 793 of 2000 complete in 755.4 sec
[---------------  39%                  ] 794 of 2000 complete in 756.2 sec
[---------------  39%                  ] 795 of 2000 complete in 757.0 sec
[---------------  39%                  ] 796 of 2000 complete in 757.9 sec
[---------------  39%                  ] 797 of 2000 complete in 758.8 sec
[---------------  39%                  ] 798 of 2000 complete in 759.6 sec
[---------------  39%                  ] 799 of 2000 complete in 760.5 sec
[---------------  40%                  ] 800 of 2000 complete in 761.4 sec
[---------------  40%                  ] 801 of 2000 complete in 762.4 sec
[---------------  40%                  ] 802 of 2000 complete in 763.3 sec
[---------------  40%                  ] 803 of 2000 complete in 764.2 sec
[---------------  40%                  ] 804 of 2000 complete in 765.1 sec
[---------------  40%                  ] 805 of 2000 complete in 766.0 sec
[---------------  40%                  ] 806 of 2000 complete in 766.9 sec
[---------------  40%                  ] 807 of 2000 complete in 767.8 sec
[---------------  40%                  ] 808 of 2000 complete in 768.8 sec
[---------------  40%                  ] 809 of 2000 complete in 769.7 sec
[---------------  40%                  ] 810 of 2000 complete in 770.6 sec
[---------------  40%                  ] 811 of 2000 complete in 771.4 sec
[---------------  40%                  ] 812 of 2000 complete in 772.4 sec
[---------------  40%                  ] 813 of 2000 complete in 773.3 sec
[---------------  40%                  ] 814 of 2000 complete in 774.2 sec
[---------------  40%                  ] 815 of 2000 complete in 775.1 sec
[---------------  40%                  ] 816 of 2000 complete in 776.0 sec
[---------------  40%                  ] 817 of 2000 complete in 776.9 sec
[---------------  40%                  ] 818 of 2000 complete in 777.8 sec
[---------------  40%                  ] 819 of 2000 complete in 778.7 sec
[---------------  41%                  ] 820 of 2000 complete in 779.6 sec
[---------------  41%                  ] 821 of 2000 complete in 780.6 sec
[---------------  41%                  ] 822 of 2000 complete in 781.5 sec
[---------------  41%                  ] 823 of 2000 complete in 782.5 sec
[---------------  41%                  ] 824 of 2000 complete in 783.5 sec
[---------------  41%                  ] 825 of 2000 complete in 784.4 sec
[---------------  41%                  ] 826 of 2000 complete in 785.3 sec
[---------------  41%                  ] 827 of 2000 complete in 786.2 sec
[---------------  41%                  ] 828 of 2000 complete in 787.1 sec
[---------------  41%                  ] 829 of 2000 complete in 787.9 sec
[---------------  41%                  ] 830 of 2000 complete in 788.8 sec
[---------------  41%                  ] 831 of 2000 complete in 789.7 sec
[---------------  41%                  ] 832 of 2000 complete in 790.6 sec
[---------------  41%                  ] 833 of 2000 complete in 791.5 sec
[---------------  41%                  ] 834 of 2000 complete in 792.4 sec
[---------------  41%                  ] 835 of 2000 complete in 793.3 sec
[---------------  41%                  ] 836 of 2000 complete in 794.1 sec
[---------------  41%                  ] 837 of 2000 complete in 795.0 sec
[---------------  41%                  ] 838 of 2000 complete in 796.0 sec
[---------------  41%                  ] 839 of 2000 complete in 796.8 sec
[---------------  42%                  ] 840 of 2000 complete in 797.7 sec
[---------------  42%                  ] 841 of 2000 complete in 798.5 sec
[---------------  42%                  ] 842 of 2000 complete in 799.4 sec
[---------------- 42%                  ] 843 of 2000 complete in 800.2 sec
[---------------- 42%                  ] 844 of 2000 complete in 801.1 sec
[---------------- 42%                  ] 845 of 2000 complete in 802.0 sec
[---------------- 42%                  ] 846 of 2000 complete in 802.9 sec
[---------------- 42%                  ] 847 of 2000 complete in 803.8 sec
[---------------- 42%                  ] 848 of 2000 complete in 804.7 sec
[---------------- 42%                  ] 849 of 2000 complete in 805.6 sec
[---------------- 42%                  ] 850 of 2000 complete in 806.5 sec
[---------------- 42%                  ] 851 of 2000 complete in 807.4 sec
[---------------- 42%                  ] 852 of 2000 complete in 808.3 sec
[---------------- 42%                  ] 853 of 2000 complete in 809.2 sec
[---------------- 42%                  ] 854 of 2000 complete in 810.1 sec
[---------------- 42%                  ] 855 of 2000 complete in 810.9 sec
[---------------- 42%                  ] 856 of 2000 complete in 811.9 sec
[---------------- 42%                  ] 857 of 2000 complete in 812.8 sec
[---------------- 42%                  ] 858 of 2000 complete in 813.7 sec
[---------------- 42%                  ] 859 of 2000 complete in 814.6 sec
[---------------- 43%                  ] 860 of 2000 complete in 815.5 sec
[---------------- 43%                  ] 861 of 2000 complete in 816.4 sec
[---------------- 43%                  ] 862 of 2000 complete in 817.3 sec
[---------------- 43%                  ] 863 of 2000 complete in 818.2 sec
[---------------- 43%                  ] 864 of 2000 complete in 819.1 sec
[---------------- 43%                  ] 865 of 2000 complete in 820.0 sec
[---------------- 43%                  ] 866 of 2000 complete in 821.0 sec
[---------------- 43%                  ] 867 of 2000 complete in 821.9 sec
[---------------- 43%                  ] 868 of 2000 complete in 822.8 sec
[---------------- 43%                  ] 869 of 2000 complete in 823.8 sec
[---------------- 43%                  ] 870 of 2000 complete in 824.7 sec
[---------------- 43%                  ] 871 of 2000 complete in 825.6 sec
[---------------- 43%                  ] 872 of 2000 complete in 826.6 sec
[---------------- 43%                  ] 873 of 2000 complete in 827.6 sec
[---------------- 43%                  ] 874 of 2000 complete in 828.5 sec
[---------------- 43%                  ] 875 of 2000 complete in 829.5 sec
[---------------- 43%                  ] 876 of 2000 complete in 748.3 sec
[---------------- 43%                  ] 877 of 2000 complete in 749.1 sec
[---------------- 43%                  ] 878 of 2000 complete in 750.0 sec
[---------------- 43%                  ] 879 of 2000 complete in 750.8 sec
[---------------- 44%                  ] 880 of 2000 complete in 751.7 sec
[---------------- 44%                  ] 881 of 2000 complete in 752.6 sec
[---------------- 44%                  ] 882 of 2000 complete in 753.4 sec
[---------------- 44%                  ] 883 of 2000 complete in 754.3 sec
[---------------- 44%                  ] 884 of 2000 complete in 755.1 sec
[---------------- 44%                  ] 885 of 2000 complete in 756.0 sec
[---------------- 44%                  ] 886 of 2000 complete in 756.7 sec
[---------------- 44%                  ] 887 of 2000 complete in 757.5 sec
[---------------- 44%                  ] 888 of 2000 complete in 758.3 sec
[---------------- 44%                  ] 889 of 2000 complete in 759.2 sec
[---------------- 44%                  ] 890 of 2000 complete in 759.9 sec
[---------------- 44%                  ] 891 of 2000 complete in 760.7 sec
[---------------- 44%                  ] 892 of 2000 complete in 761.5 sec
[---------------- 44%                  ] 893 of 2000 complete in 762.2 sec
[---------------- 44%                  ] 894 of 2000 complete in 763.0 sec
[-----------------44%                  ] 895 of 2000 complete in 763.8 sec
[-----------------44%                  ] 896 of 2000 complete in 764.6 sec
[-----------------44%                  ] 897 of 2000 complete in 765.3 sec
[-----------------44%                  ] 898 of 2000 complete in 766.1 sec
[-----------------44%                  ] 899 of 2000 complete in 766.9 sec
[-----------------45%                  ] 900 of 2000 complete in 767.7 sec
[-----------------45%                  ] 901 of 2000 complete in 768.4 sec
[-----------------45%                  ] 902 of 2000 complete in 769.2 sec
[-----------------45%                  ] 903 of 2000 complete in 769.9 sec
[-----------------45%                  ] 904 of 2000 complete in 770.7 sec
[-----------------45%                  ] 905 of 2000 complete in 771.5 sec
[-----------------45%                  ] 906 of 2000 complete in 772.2 sec
[-----------------45%                  ] 907 of 2000 complete in 773.0 sec
[-----------------45%                  ] 908 of 2000 complete in 773.8 sec
[-----------------45%                  ] 909 of 2000 complete in 774.6 sec
[-----------------45%                  ] 910 of 2000 complete in 775.4 sec
[-----------------45%                  ] 911 of 2000 complete in 776.2 sec
[-----------------45%                  ] 912 of 2000 complete in 777.0 sec
[-----------------45%                  ] 913 of 2000 complete in 777.9 sec
[-----------------45%                  ] 914 of 2000 complete in 778.7 sec
[-----------------45%                  ] 915 of 2000 complete in 779.5 sec
[-----------------45%                  ] 916 of 2000 complete in 780.3 sec
[-----------------45%                  ] 917 of 2000 complete in 781.1 sec
[-----------------45%                  ] 918 of 2000 complete in 781.9 sec
[-----------------45%                  ] 919 of 2000 complete in 782.8 sec
[-----------------46%                  ] 920 of 2000 complete in 783.6 sec
[-----------------46%                  ] 921 of 2000 complete in 784.3 sec
[-----------------46%                  ] 922 of 2000 complete in 785.1 sec
[-----------------46%                  ] 923 of 2000 complete in 785.9 sec
[-----------------46%                  ] 924 of 2000 complete in 786.7 sec
[-----------------46%                  ] 925 of 2000 complete in 787.5 sec
[-----------------46%                  ] 926 of 2000 complete in 788.4 sec
[-----------------46%                  ] 927 of 2000 complete in 789.3 sec
[-----------------46%                  ] 928 of 2000 complete in 790.1 sec
[-----------------46%                  ] 929 of 2000 complete in 791.0 sec
[-----------------46%                  ] 930 of 2000 complete in 791.8 sec
[-----------------46%                  ] 931 of 2000 complete in 792.7 sec
[-----------------46%                  ] 932 of 2000 complete in 793.6 sec
[-----------------46%                  ] 933 of 2000 complete in 794.4 sec
[-----------------46%                  ] 934 of 2000 complete in 795.3 sec
[-----------------46%                  ] 935 of 2000 complete in 796.2 sec
[-----------------46%                  ] 936 of 2000 complete in 797.1 sec
[-----------------46%                  ] 937 of 2000 complete in 798.0 sec
[-----------------46%                  ] 938 of 2000 complete in 798.9 sec
[-----------------46%                  ] 939 of 2000 complete in 799.7 sec
[-----------------47%                  ] 940 of 2000 complete in 800.6 sec
[-----------------47%                  ] 941 of 2000 complete in 801.5 sec
[-----------------47%                  ] 942 of 2000 complete in 802.3 sec
[-----------------47%                  ] 943 of 2000 complete in 803.2 sec
[-----------------47%                  ] 944 of 2000 complete in 804.1 sec
[-----------------47%                  ] 945 of 2000 complete in 804.9 sec
[-----------------47%                  ] 946 of 2000 complete in 805.8 sec
[-----------------47%                  ] 947 of 2000 complete in 806.7 sec
[-----------------47%                  ] 948 of 2000 complete in 807.6 sec
[-----------------47%                  ] 949 of 2000 complete in 808.5 sec
[-----------------47%                  ] 950 of 2000 complete in 809.4 sec
[-----------------47%                  ] 951 of 2000 complete in 810.4 sec
[-----------------47%                  ] 952 of 2000 complete in 811.3 sec
[-----------------47%                  ] 953 of 2000 complete in 812.2 sec
[-----------------47%                  ] 954 of 2000 complete in 813.1 sec
[-----------------47%                  ] 955 of 2000 complete in 814.0 sec
[-----------------47%                  ] 956 of 2000 complete in 814.9 sec
[-----------------47%                  ] 957 of 2000 complete in 815.8 sec
[-----------------47%                  ] 958 of 2000 complete in 816.7 sec
[-----------------47%                  ] 959 of 2000 complete in 817.6 sec
[-----------------48%                  ] 960 of 2000 complete in 818.4 sec
[-----------------48%                  ] 961 of 2000 complete in 819.4 sec
[-----------------48%                  ] 962 of 2000 complete in 820.3 sec
[-----------------48%                  ] 963 of 2000 complete in 821.2 sec
[-----------------48%                  ] 964 of 2000 complete in 822.1 sec
[-----------------48%                  ] 965 of 2000 complete in 823.0 sec
[-----------------48%                  ] 966 of 2000 complete in 823.9 sec
[-----------------48%                  ] 967 of 2000 complete in 824.8 sec
[-----------------48%                  ] 968 of 2000 complete in 825.7 sec
[-----------------48%                  ] 969 of 2000 complete in 826.6 sec
[-----------------48%                  ] 970 of 2000 complete in 827.5 sec
[-----------------48%                  ] 971 of 2000 complete in 828.5 sec
[-----------------48%                  ] 972 of 2000 complete in 829.4 sec
[-----------------48%                  ] 973 of 2000 complete in 830.3 sec
[-----------------48%                  ] 974 of 2000 complete in 831.2 sec
[-----------------48%                  ] 975 of 2000 complete in 832.1 sec
[-----------------48%                  ] 976 of 2000 complete in 833.0 sec
[-----------------48%                  ] 977 of 2000 complete in 833.9 sec
[-----------------48%                  ] 978 of 2000 complete in 834.8 sec
[-----------------48%                  ] 979 of 2000 complete in 835.8 sec
[-----------------49%                  ] 980 of 2000 complete in 836.7 sec
[-----------------49%                  ] 981 of 2000 complete in 837.6 sec
[-----------------49%                  ] 982 of 2000 complete in 838.6 sec
[-----------------49%                  ] 983 of 2000 complete in 839.5 sec
[-----------------49%                  ] 984 of 2000 complete in 840.4 sec

[--------------   38%                  ] 767 of 2000 complete in 743.0 sec
[--------------   38%                  ] 768 of 2000 complete in 743.9 sec
[--------------   38%                  ] 769 of 2000 complete in 744.9 sec
[--------------   38%                  ] 770 of 2000 complete in 745.8 sec
[--------------   38%                  ] 771 of 2000 complete in 746.7 sec
[--------------   38%                  ] 772 of 2000 complete in 747.6 sec
[--------------   38%                  ] 773 of 2000 complete in 748.6 sec
[--------------   38%                  ] 774 of 2000 complete in 749.5 sec
[--------------   38%                  ] 775 of 2000 complete in 750.4 sec
[--------------   38%                  ] 776 of 2000 complete in 751.3 sec
[--------------   38%                  ] 777 of 2000 complete in 752.2 sec
[--------------   38%                  ] 778 of 2000 complete in 753.0 sec
[--------------   38%                  ] 779 of 2000 complete in 753.9 sec
[--------------   39%                  ] 780 of 2000 complete in 754.8 sec
[--------------   39%                  ] 781 of 2000 complete in 755.7 sec
[--------------   39%                  ] 782 of 2000 complete in 756.5 sec
[--------------   39%                  ] 783 of 2000 complete in 757.4 sec
[--------------   39%                  ] 784 of 2000 complete in 758.3 sec
[--------------   39%                  ] 785 of 2000 complete in 759.2 sec
[--------------   39%                  ] 786 of 2000 complete in 760.0 sec
[--------------   39%                  ] 787 of 2000 complete in 760.9 sec
[--------------   39%                  ] 788 of 2000 complete in 761.8 sec
[--------------   39%                  ] 789 of 2000 complete in 762.7 sec
[---------------  39%                  ] 790 of 2000 complete in 763.6 sec
[---------------  39%                  ] 791 of 2000 complete in 764.5 sec
[---------------  39%                  ] 792 of 2000 complete in 765.4 sec
[---------------  39%                  ] 793 of 2000 complete in 766.3 sec
[---------------  39%                  ] 794 of 2000 complete in 767.2 sec
[---------------  39%                  ] 795 of 2000 complete in 768.1 sec
[---------------  39%                  ] 796 of 2000 complete in 769.0 sec
[---------------  39%                  ] 797 of 2000 complete in 769.8 sec
[---------------  39%                  ] 798 of 2000 complete in 770.7 sec
[---------------  39%                  ] 799 of 2000 complete in 771.6 sec
[---------------  40%                  ] 800 of 2000 complete in 772.5 sec
[---------------  40%                  ] 801 of 2000 complete in 773.4 sec
[---------------  40%                  ] 802 of 2000 complete in 774.3 sec
[---------------  40%                  ] 803 of 2000 complete in 775.2 sec
[---------------  40%                  ] 804 of 2000 complete in 776.1 sec
[---------------  40%                  ] 805 of 2000 complete in 777.0 sec
[---------------  40%                  ] 806 of 2000 complete in 777.9 sec
[---------------  40%                  ] 807 of 2000 complete in 778.8 sec
[---------------  40%                  ] 808 of 2000 complete in 779.7 sec
[---------------  40%                  ] 809 of 2000 complete in 780.6 sec
[---------------  40%                  ] 810 of 2000 complete in 781.6 sec
[---------------  40%                  ] 811 of 2000 complete in 782.5 sec
[---------------  40%                  ] 812 of 2000 complete in 783.4 sec
[---------------  40%                  ] 813 of 2000 complete in 784.4 sec
[---------------  40%                  ] 814 of 2000 complete in 785.3 sec
[---------------  40%                  ] 815 of 2000 complete in 786.2 sec
[---------------  40%                  ] 816 of 2000 complete in 787.1 sec
[---------------  40%                  ] 817 of 2000 complete in 788.1 sec
[---------------  40%                  ] 818 of 2000 complete in 789.0 sec
[---------------  40%                  ] 819 of 2000 complete in 789.9 sec
[---------------  41%                  ] 820 of 2000 complete in 790.8 sec
[---------------  41%                  ] 821 of 2000 complete in 791.7 sec
[---------------  41%                  ] 822 of 2000 complete in 792.6 sec
[---------------  41%                  ] 823 of 2000 complete in 793.5 sec
[---------------  41%                  ] 824 of 2000 complete in 794.4 sec
[---------------  41%                  ] 825 of 2000 complete in 795.4 sec
[---------------  41%                  ] 826 of 2000 complete in 796.3 sec
[---------------  41%                  ] 827 of 2000 complete in 797.3 sec
[---------------  41%                  ] 828 of 2000 complete in 798.2 sec
[---------------  41%                  ] 829 of 2000 complete in 799.2 sec
[---------------  41%                  ] 830 of 2000 complete in 800.2 sec
[---------------  41%                  ] 831 of 2000 complete in 801.1 sec
[---------------  41%                  ] 832 of 2000 complete in 802.0 sec
[---------------  41%                  ] 833 of 2000 complete in 803.0 sec
[---------------  41%                  ] 834 of 2000 complete in 803.9 sec
[---------------  41%                  ] 835 of 2000 complete in 804.8 sec
[---------------  41%                  ] 836 of 2000 complete in 805.7 sec
[---------------  41%                  ] 837 of 2000 complete in 806.6 sec
[---------------  41%                  ] 838 of 2000 complete in 807.6 sec
[---------------  41%                  ] 839 of 2000 complete in 808.5 sec
[---------------  42%                  ] 840 of 2000 complete in 809.4 sec
[---------------  42%                  ] 841 of 2000 complete in 810.4 sec
[---------------  42%                  ] 842 of 2000 complete in 811.3 sec
[---------------- 42%                  ] 843 of 2000 complete in 812.3 sec
[---------------- 42%                  ] 844 of 2000 complete in 813.2 sec
[---------------- 42%                  ] 845 of 2000 complete in 814.2 sec
[---------------- 42%                  ] 846 of 2000 complete in 815.2 sec
[---------------- 42%                  ] 847 of 2000 complete in 816.1 sec
[---------------- 42%                  ] 848 of 2000 complete in 817.1 sec
[---------------- 42%                  ] 849 of 2000 complete in 818.1 sec
[---------------- 42%                  ] 850 of 2000 complete in 819.0 sec
[---------------- 42%                  ] 851 of 2000 complete in 819.9 sec
[---------------- 42%                  ] 852 of 2000 complete in 820.8 sec
[---------------- 42%                  ] 853 of 2000 complete in 821.7 sec
[---------------- 42%                  ] 854 of 2000 complete in 822.7 sec
[---------------- 42%                  ] 855 of 2000 complete in 823.5 sec
[---------------- 42%                  ] 856 of 2000 complete in 824.5 sec
[---------------- 42%                  ] 857 of 2000 complete in 825.4 sec
[---------------- 42%                  ] 858 of 2000 complete in 826.3 sec
[---------------- 42%                  ] 859 of 2000 complete in 827.2 sec
[---------------- 43%                  ] 860 of 2000 complete in 828.1 sec
[---------------- 43%                  ] 861 of 2000 complete in 829.0 sec
[---------------- 43%                  ] 862 of 2000 complete in 829.9 sec
[---------------- 43%                  ] 863 of 2000 complete in 830.8 sec
[---------------- 43%                  ] 864 of 2000 complete in 831.7 sec
[---------------- 43%                  ] 865 of 2000 complete in 832.6 sec
[---------------- 43%                  ] 866 of 2000 complete in 833.5 sec
[---------------- 43%                  ] 867 of 2000 complete in 834.4 sec
[---------------- 43%                  ] 868 of 2000 complete in 835.3 sec
[---------------- 43%                  ] 869 of 2000 complete in 836.2 sec
[---------------- 43%                  ] 870 of 2000 complete in 837.1 sec
[---------------- 43%                  ] 871 of 2000 complete in 838.0 sec
[---------------- 43%                  ] 872 of 2000 complete in 838.9 sec
[---------------- 43%                  ] 873 of 2000 complete in 839.8 sec
[---------------- 43%                  ] 874 of 2000 complete in 840.6 sec
[---------------- 43%                  ] 875 of 2000 complete in 841.5 sec
[---------------- 43%                  ] 877 of 2000 complete in 747.8 sec
[---------------- 43%                  ] 878 of 2000 complete in 748.7 sec
[---------------- 43%                  ] 879 of 2000 complete in 749.6 sec
[---------------- 44%                  ] 880 of 2000 complete in 750.4 sec
[---------------- 44%                  ] 881 of 2000 complete in 751.3 sec
[---------------- 44%                  ] 882 of 2000 complete in 752.2 sec
[---------------- 44%                  ] 883 of 2000 complete in 753.1 sec
[---------------- 44%                  ] 884 of 2000 complete in 754.1 sec
[---------------- 44%                  ] 885 of 2000 complete in 755.0 sec
[---------------- 44%                  ] 886 of 2000 complete in 755.8 sec
[---------------- 44%                  ] 887 of 2000 complete in 756.7 sec
[---------------- 44%                  ] 888 of 2000 complete in 757.6 sec
[---------------- 44%                  ] 889 of 2000 complete in 758.4 sec
[---------------- 44%                  ] 890 of 2000 complete in 759.3 sec
[---------------- 44%                  ] 891 of 2000 complete in 760.2 sec
[---------------- 44%                  ] 892 of 2000 complete in 761.1 sec
[---------------- 44%                  ] 893 of 2000 complete in 762.0 sec
[---------------- 44%                  ] 894 of 2000 complete in 762.9 sec
[-----------------44%                  ] 895 of 2000 complete in 763.8 sec
[-----------------44%                  ] 896 of 2000 complete in 764.7 sec
[-----------------44%                  ] 897 of 2000 complete in 765.7 sec
[-----------------44%                  ] 898 of 2000 complete in 766.6 sec
[-----------------44%                  ] 899 of 2000 complete in 767.5 sec
[-----------------45%                  ] 900 of 2000 complete in 768.4 sec
[-----------------45%                  ] 901 of 2000 complete in 769.4 sec
[-----------------45%                  ] 902 of 2000 complete in 770.3 sec
[-----------------45%                  ] 903 of 2000 complete in 771.2 sec
[-----------------45%                  ] 904 of 2000 complete in 772.2 sec
[-----------------45%                  ] 905 of 2000 complete in 773.2 sec
[-----------------45%                  ] 906 of 2000 complete in 774.2 sec
[-----------------45%                  ] 907 of 2000 complete in 775.2 sec
[-----------------45%                  ] 908 of 2000 complete in 776.2 sec
[-----------------45%                  ] 909 of 2000 complete in 777.2 sec
[-----------------45%                  ] 910 of 2000 complete in 778.1 sec
[-----------------45%                  ] 911 of 2000 complete in 779.1 sec
[-----------------45%                  ] 912 of 2000 complete in 780.1 sec
[-----------------45%                  ] 913 of 2000 complete in 781.1 sec
[-----------------45%                  ] 914 of 2000 complete in 782.1 sec
[-----------------45%                  ] 915 of 2000 complete in 783.1 sec
[-----------------45%                  ] 916 of 2000 complete in 784.1 sec
[-----------------45%                  ] 917 of 2000 complete in 785.0 sec
[-----------------45%                  ] 918 of 2000 complete in 786.0 sec
[-----------------45%                  ] 919 of 2000 complete in 786.9 sec
[-----------------46%                  ] 920 of 2000 complete in 787.8 sec
[-----------------46%                  ] 921 of 2000 complete in 788.7 sec
[-----------------46%                  ] 922 of 2000 complete in 789.6 sec
[-----------------46%                  ] 923 of 2000 complete in 790.6 sec
[-----------------46%                  ] 924 of 2000 complete in 791.4 sec
[-----------------46%                  ] 925 of 2000 complete in 792.4 sec
[-----------------46%                  ] 926 of 2000 complete in 793.3 sec
[-----------------46%                  ] 927 of 2000 complete in 794.2 sec
[-----------------46%                  ] 928 of 2000 complete in 795.1 sec
[-----------------46%                  ] 929 of 2000 complete in 796.1 sec
[-----------------46%                  ] 930 of 2000 complete in 797.0 sec
[-----------------46%                  ] 931 of 2000 complete in 797.8 sec
[-----------------46%                  ] 932 of 2000 complete in 798.7 sec
[-----------------46%                  ] 933 of 2000 complete in 799.5 sec
[-----------------46%                  ] 934 of 2000 complete in 800.3 sec
[-----------------46%                  ] 935 of 2000 complete in 801.2 sec
[-----------------46%                  ] 936 of 2000 complete in 802.0 sec
[-----------------46%                  ] 937 of 2000 complete in 802.8 sec
[-----------------46%                  ] 938 of 2000 complete in 803.6 sec
[-----------------46%                  ] 939 of 2000 complete in 804.4 sec
[-----------------47%                  ] 940 of 2000 complete in 805.2 sec
[-----------------47%                  ] 941 of 2000 complete in 806.0 sec
[-----------------47%                  ] 942 of 2000 complete in 806.8 sec
[-----------------47%                  ] 943 of 2000 complete in 807.6 sec
[-----------------47%                  ] 944 of 2000 complete in 808.5 sec
[-----------------47%                  ] 945 of 2000 complete in 809.3 sec
[-----------------47%                  ] 946 of 2000 complete in 810.1 sec
[-----------------47%                  ] 947 of 2000 complete in 810.9 sec
[-----------------47%                  ] 948 of 2000 complete in 811.8 sec
[-----------------47%                  ] 949 of 2000 complete in 812.6 sec
[-----------------47%                  ] 950 of 2000 complete in 813.5 sec
[-----------------47%                  ] 951 of 2000 complete in 814.3 sec
[-----------------47%                  ] 952 of 2000 complete in 815.2 sec
[-----------------47%                  ] 953 of 2000 complete in 816.0 sec
[-----------------47%                  ] 954 of 2000 complete in 816.9 sec
[-----------------47%                  ] 955 of 2000 complete in 817.7 sec
[-----------------47%                  ] 956 of 2000 complete in 818.5 sec
[-----------------47%                  ] 957 of 2000 complete in 819.3 sec
[-----------------47%                  ] 958 of 2000 complete in 820.1 sec
[-----------------47%                  ] 959 of 2000 complete in 820.9 sec
[-----------------48%                  ] 960 of 2000 complete in 821.7 sec
[-----------------48%                  ] 961 of 2000 complete in 822.5 sec
[-----------------48%                  ] 962 of 2000 complete in 823.3 sec
[-----------------48%                  ] 963 of 2000 complete in 824.2 sec
[-----------------48%                  ] 964 of 2000 complete in 825.0 sec
[-----------------48%                  ] 965 of 2000 complete in 825.8 sec
[-----------------48%                  ] 966 of 2000 complete in 826.6 sec
[-----------------48%                  ] 967 of 2000 complete in 827.5 sec
[-----------------48%                  ] 968 of 2000 complete in 828.3 sec
[-----------------48%                  ] 969 of 2000 complete in 829.2 sec
[-----------------48%                  ] 970 of 2000 complete in 830.0 sec
[-----------------48%                  ] 971 of 2000 complete in 830.8 sec
[-----------------48%                  ] 972 of 2000 complete in 831.6 sec
[-----------------48%                  ] 973 of 2000 complete in 832.5 sec
[-----------------48%                  ] 974 of 2000 complete in 833.3 sec
[-----------------48%                  ] 975 of 2000 complete in 834.2 sec
[-----------------48%                  ] 976 of 2000 complete in 835.1 sec
[-----------------48%                  ] 977 of 2000 complete in 835.9 sec
[-----------------48%                  ] 978 of 2000 complete in 836.7 sec
[-----------------48%                  ] 979 of 2000 complete in 837.6 sec
[-----------------49%                  ] 980 of 2000 complete in 838.5 sec
[-----------------49%                  ] 981 of 2000 complete in 839.3 sec
[-----------------49%                  ] 982 of 2000 complete in 840.2 sec
[-----------------49%                  ] 983 of 2000 complete in 841.0 sec
[-----------------49%                  ] 984 of 2000 complete in 841.8 sec
[-----------------49%                  ] 985 of 2000 complete in 842.7 sec

[---------------- 43%                  ] 876 of 2000 complete in 830.4 sec
[---------------- 43%                  ] 877 of 2000 complete in 831.3 sec
[---------------- 43%                  ] 878 of 2000 complete in 832.3 sec
[---------------- 43%                  ] 879 of 2000 complete in 833.2 sec
[---------------- 44%                  ] 880 of 2000 complete in 834.1 sec
[---------------- 44%                  ] 881 of 2000 complete in 835.0 sec
[---------------- 44%                  ] 882 of 2000 complete in 836.0 sec
[---------------- 44%                  ] 883 of 2000 complete in 836.9 sec
[---------------- 44%                  ] 884 of 2000 complete in 837.9 sec
[---------------- 44%                  ] 885 of 2000 complete in 838.9 sec
[---------------- 44%                  ] 886 of 2000 complete in 839.8 sec
[---------------- 44%                  ] 887 of 2000 complete in 840.7 sec
[---------------- 44%                  ] 888 of 2000 complete in 841.6 sec
[---------------- 44%                  ] 889 of 2000 complete in 842.5 sec
[---------------- 44%                  ] 890 of 2000 complete in 843.4 sec
[---------------- 44%                  ] 891 of 2000 complete in 844.3 sec
[---------------- 44%                  ] 892 of 2000 complete in 845.1 sec
[---------------- 44%                  ] 893 of 2000 complete in 846.1 sec
[---------------- 44%                  ] 894 of 2000 complete in 847.0 sec
[-----------------44%                  ] 895 of 2000 complete in 847.9 sec
[-----------------44%                  ] 896 of 2000 complete in 848.9 sec
[-----------------44%                  ] 897 of 2000 complete in 849.8 sec
[-----------------44%                  ] 898 of 2000 complete in 850.8 sec
[-----------------44%                  ] 899 of 2000 complete in 851.7 sec
[-----------------45%                  ] 900 of 2000 complete in 852.7 sec
[-----------------45%                  ] 901 of 2000 complete in 853.7 sec
[-----------------45%                  ] 902 of 2000 complete in 854.6 sec
[-----------------45%                  ] 903 of 2000 complete in 855.6 sec
[-----------------45%                  ] 904 of 2000 complete in 856.6 sec
[-----------------45%                  ] 905 of 2000 complete in 857.6 sec
[-----------------45%                  ] 906 of 2000 complete in 858.6 sec
[-----------------45%                  ] 907 of 2000 complete in 859.6 sec
[-----------------45%                  ] 908 of 2000 complete in 860.6 sec
[-----------------45%                  ] 909 of 2000 complete in 861.6 sec
[-----------------45%                  ] 910 of 2000 complete in 862.6 sec
[-----------------45%                  ] 911 of 2000 complete in 863.6 sec
[-----------------45%                  ] 912 of 2000 complete in 864.6 sec
[-----------------45%                  ] 913 of 2000 complete in 865.5 sec
[-----------------45%                  ] 914 of 2000 complete in 866.5 sec
[-----------------45%                  ] 915 of 2000 complete in 867.4 sec
[-----------------45%                  ] 916 of 2000 complete in 868.3 sec
[-----------------45%                  ] 917 of 2000 complete in 869.3 sec
[-----------------45%                  ] 918 of 2000 complete in 870.2 sec
[-----------------45%                  ] 919 of 2000 complete in 871.0 sec
[-----------------46%                  ] 920 of 2000 complete in 871.9 sec
[-----------------46%                  ] 921 of 2000 complete in 872.8 sec
[-----------------46%                  ] 922 of 2000 complete in 873.6 sec
[-----------------46%                  ] 923 of 2000 complete in 874.5 sec
[-----------------46%                  ] 924 of 2000 complete in 875.3 sec
[-----------------46%                  ] 925 of 2000 complete in 876.2 sec
[-----------------46%                  ] 926 of 2000 complete in 877.0 sec
[-----------------46%                  ] 927 of 2000 complete in 877.8 sec
[-----------------46%                  ] 928 of 2000 complete in 878.7 sec
[-----------------46%                  ] 929 of 2000 complete in 879.6 sec
[-----------------46%                  ] 930 of 2000 complete in 880.4 sec
[-----------------46%                  ] 931 of 2000 complete in 881.2 sec
[-----------------46%                  ] 932 of 2000 complete in 882.1 sec
[-----------------46%                  ] 933 of 2000 complete in 882.9 sec
[-----------------46%                  ] 934 of 2000 complete in 883.7 sec
[-----------------46%                  ] 935 of 2000 complete in 884.6 sec
[-----------------46%                  ] 936 of 2000 complete in 885.4 sec
[-----------------46%                  ] 937 of 2000 complete in 886.2 sec
[-----------------46%                  ] 938 of 2000 complete in 887.0 sec
[-----------------46%                  ] 939 of 2000 complete in 887.8 sec
[-----------------47%                  ] 940 of 2000 complete in 888.7 sec
[-----------------47%                  ] 941 of 2000 complete in 889.5 sec
[-----------------47%                  ] 942 of 2000 complete in 890.4 sec
[-----------------47%                  ] 943 of 2000 complete in 891.2 sec
[-----------------47%                  ] 944 of 2000 complete in 892.0 sec
[-----------------47%                  ] 945 of 2000 complete in 892.9 sec
[-----------------47%                  ] 946 of 2000 complete in 893.7 sec
[-----------------47%                  ] 947 of 2000 complete in 894.5 sec
[-----------------47%                  ] 948 of 2000 complete in 895.3 sec
[-----------------47%                  ] 949 of 2000 complete in 896.1 sec
[-----------------47%                  ] 950 of 2000 complete in 896.9 sec
[-----------------47%                  ] 951 of 2000 complete in 897.7 sec
[-----------------47%                  ] 952 of 2000 complete in 898.5 sec
[-----------------47%                  ] 953 of 2000 complete in 899.3 sec
[-----------------47%                  ] 954 of 2000 complete in 900.1 sec
[-----------------47%                  ] 955 of 2000 complete in 900.9 sec
[-----------------47%                  ] 956 of 2000 complete in 901.7 sec
[-----------------47%                  ] 957 of 2000 complete in 902.4 sec
[-----------------47%                  ] 958 of 2000 complete in 903.2 sec
[-----------------47%                  ] 959 of 2000 complete in 904.0 sec
[-----------------48%                  ] 960 of 2000 complete in 904.7 sec
[-----------------48%                  ] 961 of 2000 complete in 905.5 sec
[-----------------48%                  ] 962 of 2000 complete in 906.3 sec
[-----------------48%                  ] 963 of 2000 complete in 907.1 sec
[-----------------48%                  ] 964 of 2000 complete in 907.9 sec
[-----------------48%                  ] 965 of 2000 complete in 908.6 sec
[-----------------48%                  ] 966 of 2000 complete in 909.5 sec
[-----------------48%                  ] 967 of 2000 complete in 910.3 sec
[-----------------48%                  ] 968 of 2000 complete in 911.1 sec
[-----------------48%                  ] 969 of 2000 complete in 911.9 sec
[-----------------48%                  ] 970 of 2000 complete in 912.7 sec
[-----------------48%                  ] 971 of 2000 complete in 913.5 sec
[-----------------48%                  ] 972 of 2000 complete in 914.3 sec
[-----------------48%                  ] 973 of 2000 complete in 915.0 sec
[-----------------48%                  ] 974 of 2000 complete in 915.8 sec
[-----------------48%                  ] 975 of 2000 complete in 916.5 sec
[-----------------48%                  ] 976 of 2000 complete in 917.3 sec
[-----------------48%                  ] 977 of 2000 complete in 918.0 sec
[-----------------48%                  ] 978 of 2000 complete in 918.8 sec
[-----------------48%                  ] 979 of 2000 complete in 919.5 sec
[-----------------49%                  ] 980 of 2000 complete in 920.2 sec
[-----------------49%                  ] 981 of 2000 complete in 920.9 sec
[-----------------49%                  ] 982 of 2000 complete in 921.6 sec
[-----------------49%                  ] 983 of 2000 complete in 922.3 sec
[-----------------49%                  ] 984 of 2000 complete in 923.0 sec
[-----------------49%                  ] 985 of 2000 complete in 841.4 sec
[-----------------49%                  ] 986 of 2000 complete in 842.3 sec
[-----------------49%                  ] 987 of 2000 complete in 843.2 sec
[-----------------49%                  ] 988 of 2000 complete in 844.1 sec
[-----------------49%                  ] 989 of 2000 complete in 845.0 sec
[-----------------49%                  ] 990 of 2000 complete in 845.8 sec
[-----------------49%                  ] 991 of 2000 complete in 846.7 sec
[-----------------49%                  ] 992 of 2000 complete in 847.7 sec
[-----------------49%                  ] 993 of 2000 complete in 848.6 sec
[-----------------49%                  ] 994 of 2000 complete in 849.5 sec
[-----------------49%                  ] 995 of 2000 complete in 850.5 sec
[-----------------49%                  ] 996 of 2000 complete in 851.4 sec
[-----------------49%                  ] 997 of 2000 complete in 852.3 sec
[-----------------49%                  ] 998 of 2000 complete in 853.2 sec
[-----------------49%                  ] 999 of 2000 complete in 854.1 sec
[-----------------50%                  ] 1000 of 2000 complete in 855.1 sec
[-----------------50%                  ] 1001 of 2000 complete in 856.0 sec
[-----------------50%                  ] 1002 of 2000 complete in 856.9 sec
[-----------------50%                  ] 1003 of 2000 complete in 857.9 sec
[-----------------50%                  ] 1004 of 2000 complete in 858.7 sec
[-----------------50%                  ] 1005 of 2000 complete in 859.6 sec
[-----------------50%                  ] 1006 of 2000 complete in 860.6 sec
[-----------------50%                  ] 1007 of 2000 complete in 861.5 sec
[-----------------50%                  ] 1008 of 2000 complete in 862.4 sec
[-----------------50%                  ] 1009 of 2000 complete in 863.2 sec
[-----------------50%                  ] 1010 of 2000 complete in 864.1 sec
[-----------------50%                  ] 1011 of 2000 complete in 865.0 sec
[-----------------50%                  ] 1012 of 2000 complete in 865.8 sec
[-----------------50%                  ] 1013 of 2000 complete in 866.6 sec
[-----------------50%                  ] 1014 of 2000 complete in 867.5 sec
[-----------------50%                  ] 1015 of 2000 complete in 868.3 sec
[-----------------50%                  ] 1016 of 2000 complete in 869.2 sec
[-----------------50%                  ] 1017 of 2000 complete in 870.0 sec
[-----------------50%                  ] 1018 of 2000 complete in 870.8 sec
[-----------------50%                  ] 1019 of 2000 complete in 871.6 sec
[-----------------51%                  ] 1020 of 2000 complete in 872.4 sec
[-----------------51%                  ] 1021 of 2000 complete in 873.2 sec
[-----------------51%                  ] 1022 of 2000 complete in 874.0 sec
[-----------------51%                  ] 1023 of 2000 complete in 874.8 sec
[-----------------51%                  ] 1024 of 2000 complete in 875.5 sec
[-----------------51%                  ] 1025 of 2000 complete in 876.3 sec
[-----------------51%                  ] 1026 of 2000 complete in 877.1 sec
[-----------------51%                  ] 1027 of 2000 complete in 877.9 sec
[-----------------51%                  ] 1028 of 2000 complete in 878.7 sec
[-----------------51%                  ] 1029 of 2000 complete in 879.5 sec
[-----------------51%                  ] 1030 of 2000 complete in 880.3 sec
[-----------------51%                  ] 1031 of 2000 complete in 881.2 sec
[-----------------51%                  ] 1032 of 2000 complete in 882.0 sec
[-----------------51%                  ] 1033 of 2000 complete in 882.8 sec
[-----------------51%                  ] 1034 of 2000 complete in 883.6 sec
[-----------------51%                  ] 1035 of 2000 complete in 884.5 sec
[-----------------51%                  ] 1036 of 2000 complete in 885.3 sec
[-----------------51%                  ] 1037 of 2000 complete in 886.2 sec
[-----------------51%                  ] 1038 of 2000 complete in 887.0 sec
[-----------------51%                  ] 1039 of 2000 complete in 887.9 sec
[-----------------52%                  ] 1040 of 2000 complete in 888.8 sec
[-----------------52%                  ] 1041 of 2000 complete in 889.7 sec
[-----------------52%                  ] 1042 of 2000 complete in 890.5 sec
[-----------------52%                  ] 1043 of 2000 complete in 891.4 sec
[-----------------52%                  ] 1044 of 2000 complete in 892.3 sec
[-----------------52%                  ] 1045 of 2000 complete in 893.2 sec
[-----------------52%                  ] 1046 of 2000 complete in 894.0 sec
[-----------------52%                  ] 1047 of 2000 complete in 894.8 sec
[-----------------52%                  ] 1048 of 2000 complete in 895.7 sec
[-----------------52%                  ] 1049 of 2000 complete in 896.5 sec
[-----------------52%                  ] 1050 of 2000 complete in 897.4 sec
[-----------------52%                  ] 1051 of 2000 complete in 898.2 sec
[-----------------52%                  ] 1052 of 2000 complete in 899.1 sec
[-----------------52%                  ] 1053 of 2000 complete in 899.9 sec
[-----------------52%                  ] 1054 of 2000 complete in 900.9 sec
[-----------------52%                  ] 1055 of 2000 complete in 901.7 sec
[-----------------52%                  ] 1056 of 2000 complete in 902.6 sec
[-----------------52%                  ] 1057 of 2000 complete in 903.5 sec
[-----------------52%                  ] 1058 of 2000 complete in 904.4 sec
[-----------------52%                  ] 1059 of 2000 complete in 905.2 sec
[-----------------53%                  ] 1060 of 2000 complete in 906.1 sec
[-----------------53%                  ] 1061 of 2000 complete in 906.9 sec
[-----------------53%                  ] 1062 of 2000 complete in 907.8 sec
[-----------------53%                  ] 1063 of 2000 complete in 908.6 sec
[-----------------53%                  ] 1064 of 2000 complete in 909.5 sec
[-----------------53%                  ] 1065 of 2000 complete in 910.3 sec
[-----------------53%                  ] 1066 of 2000 complete in 911.1 sec
[-----------------53%                  ] 1067 of 2000 complete in 912.0 sec
[-----------------53%                  ] 1068 of 2000 complete in 912.8 sec
[-----------------53%                  ] 1069 of 2000 complete in 913.6 sec
[-----------------53%                  ] 1070 of 2000 complete in 914.5 sec
[-----------------53%                  ] 1071 of 2000 complete in 915.3 sec
[-----------------53%                  ] 1072 of 2000 complete in 916.1 sec
[-----------------53%                  ] 1073 of 2000 complete in 917.0 sec
[-----------------53%                  ] 1074 of 2000 complete in 917.8 sec
[-----------------53%                  ] 1075 of 2000 complete in 918.7 sec
[-----------------53%                  ] 1076 of 2000 complete in 919.5 sec
[-----------------53%                  ] 1077 of 2000 complete in 920.3 sec
[-----------------53%                  ] 1078 of 2000 complete in 921.2 sec
[-----------------53%                  ] 1079 of 2000 complete in 922.0 sec
[-----------------54%                  ] 1080 of 2000 complete in 922.9 sec
[-----------------54%                  ] 1081 of 2000 complete in 923.7 sec
[-----------------54%                  ] 1082 of 2000 complete in 924.6 sec
[-----------------54%                  ] 1083 of 2000 complete in 925.5 sec
[-----------------54%                  ] 1084 of 2000 complete in 926.4 sec
[-----------------54%                  ] 1085 of 2000 complete in 927.2 sec
[-----------------54%                  ] 1086 of 2000 complete in 928.1 sec
[-----------------54%                  ] 1087 of 2000 complete in 929.0 sec
[-----------------54%                  ] 1088 of 2000 complete in 929.8 sec
[-----------------54%                  ] 1089 of 2000 complete in 930.7 sec
[-----------------54%                  ] 1090 of 2000 complete in 931.6 sec
[-----------------54%                  ] 1091 of 2000 complete in 932.5 sec

[-----------------54%                  ] 1092 of 2000 complete in 933.3 sec[-----------------49%                  ] 986 of 2000 complete in 843.5 sec
[-----------------49%                  ] 987 of 2000 complete in 844.4 sec
[-----------------49%                  ] 988 of 2000 complete in 845.2 sec
[-----------------49%                  ] 989 of 2000 complete in 846.1 sec
[-----------------49%                  ] 990 of 2000 complete in 846.9 sec
[-----------------49%                  ] 991 of 2000 complete in 847.7 sec
[-----------------49%                  ] 992 of 2000 complete in 848.6 sec
[-----------------49%                  ] 993 of 2000 complete in 849.4 sec
[-----------------49%                  ] 994 of 2000 complete in 850.3 sec
[-----------------49%                  ] 995 of 2000 complete in 851.2 sec
[-----------------49%                  ] 996 of 2000 complete in 852.1 sec
[-----------------49%                  ] 997 of 2000 complete in 853.0 sec
[-----------------49%                  ] 998 of 2000 complete in 853.9 sec
[-----------------49%                  ] 999 of 2000 complete in 854.8 sec
[-----------------50%                  ] 1000 of 2000 complete in 855.6 sec
[-----------------50%                  ] 1001 of 2000 complete in 856.5 sec
[-----------------50%                  ] 1002 of 2000 complete in 857.3 sec
[-----------------50%                  ] 1003 of 2000 complete in 858.2 sec
[-----------------50%                  ] 1004 of 2000 complete in 859.1 sec
[-----------------50%                  ] 1005 of 2000 complete in 860.0 sec
[-----------------50%                  ] 1006 of 2000 complete in 860.9 sec
[-----------------50%                  ] 1007 of 2000 complete in 861.7 sec
[-----------------50%                  ] 1008 of 2000 complete in 862.5 sec
[-----------------50%                  ] 1009 of 2000 complete in 863.4 sec
[-----------------50%                  ] 1010 of 2000 complete in 864.2 sec
[-----------------50%                  ] 1011 of 2000 complete in 865.0 sec
[-----------------50%                  ] 1012 of 2000 complete in 865.8 sec
[-----------------50%                  ] 1013 of 2000 complete in 866.6 sec
[-----------------50%                  ] 1014 of 2000 complete in 867.4 sec
[-----------------50%                  ] 1015 of 2000 complete in 868.2 sec
[-----------------50%                  ] 1016 of 2000 complete in 869.0 sec
[-----------------50%                  ] 1017 of 2000 complete in 869.9 sec
[-----------------50%                  ] 1018 of 2000 complete in 870.7 sec
[-----------------50%                  ] 1019 of 2000 complete in 871.5 sec
[-----------------51%                  ] 1020 of 2000 complete in 872.3 sec
[-----------------51%                  ] 1021 of 2000 complete in 873.2 sec
[-----------------51%                  ] 1022 of 2000 complete in 874.1 sec
[-----------------51%                  ] 1023 of 2000 complete in 874.9 sec
[-----------------51%                  ] 1024 of 2000 complete in 875.7 sec
[-----------------51%                  ] 1025 of 2000 complete in 876.6 sec
[-----------------51%                  ] 1026 of 2000 complete in 877.4 sec
[-----------------51%                  ] 1027 of 2000 complete in 878.2 sec
[-----------------51%                  ] 1028 of 2000 complete in 879.1 sec
[-----------------51%                  ] 1029 of 2000 complete in 879.9 sec
[-----------------51%                  ] 1030 of 2000 complete in 880.7 sec
[-----------------51%                  ] 1031 of 2000 complete in 881.6 sec
[-----------------51%                  ] 1032 of 2000 complete in 882.4 sec
[-----------------51%                  ] 1033 of 2000 complete in 883.2 sec
[-----------------51%                  ] 1034 of 2000 complete in 884.0 sec
[-----------------51%                  ] 1035 of 2000 complete in 884.8 sec
[-----------------51%                  ] 1036 of 2000 complete in 885.6 sec
[-----------------51%                  ] 1037 of 2000 complete in 886.3 sec
[-----------------51%                  ] 1038 of 2000 complete in 887.1 sec
[-----------------51%                  ] 1039 of 2000 complete in 887.8 sec
[-----------------52%                  ] 1040 of 2000 complete in 888.6 sec
[-----------------52%                  ] 1041 of 2000 complete in 889.4 sec
[-----------------52%                  ] 1042 of 2000 complete in 890.1 sec
[-----------------52%                  ] 1043 of 2000 complete in 890.9 sec
[-----------------52%                  ] 1044 of 2000 complete in 891.7 sec
[-----------------52%                  ] 1045 of 2000 complete in 892.5 sec
[-----------------52%                  ] 1046 of 2000 complete in 893.3 sec
[-----------------52%                  ] 1047 of 2000 complete in 894.1 sec
[-----------------52%                  ] 1048 of 2000 complete in 895.0 sec
[-----------------52%                  ] 1049 of 2000 complete in 895.9 sec
[-----------------52%                  ] 1050 of 2000 complete in 896.7 sec
[-----------------52%                  ] 1051 of 2000 complete in 897.5 sec
[-----------------52%                  ] 1052 of 2000 complete in 898.4 sec
[-----------------52%                  ] 1053 of 2000 complete in 899.3 sec
[-----------------52%                  ] 1054 of 2000 complete in 900.2 sec
[-----------------52%                  ] 1055 of 2000 complete in 901.0 sec
[-----------------52%                  ] 1056 of 2000 complete in 901.8 sec
[-----------------52%                  ] 1057 of 2000 complete in 902.7 sec
[-----------------52%                  ] 1058 of 2000 complete in 903.6 sec
[-----------------52%                  ] 1059 of 2000 complete in 904.5 sec
[-----------------53%                  ] 1060 of 2000 complete in 905.4 sec
[-----------------53%                  ] 1061 of 2000 complete in 906.3 sec
[-----------------53%                  ] 1062 of 2000 complete in 907.2 sec
[-----------------53%                  ] 1063 of 2000 complete in 908.1 sec
[-----------------53%                  ] 1064 of 2000 complete in 909.0 sec
[-----------------53%                  ] 1065 of 2000 complete in 909.9 sec
[-----------------53%                  ] 1066 of 2000 complete in 910.8 sec
[-----------------53%                  ] 1067 of 2000 complete in 911.7 sec
[-----------------53%                  ] 1068 of 2000 complete in 912.7 sec
[-----------------53%                  ] 1069 of 2000 complete in 913.6 sec
[-----------------53%                  ] 1070 of 2000 complete in 914.5 sec
[-----------------53%                  ] 1071 of 2000 complete in 915.4 sec
[-----------------53%                  ] 1072 of 2000 complete in 916.4 sec
[-----------------53%                  ] 1073 of 2000 complete in 917.3 sec
[-----------------53%                  ] 1074 of 2000 complete in 918.2 sec
[-----------------53%                  ] 1075 of 2000 complete in 919.1 sec
[-----------------53%                  ] 1076 of 2000 complete in 920.0 sec
[-----------------53%                  ] 1077 of 2000 complete in 920.8 sec
[-----------------53%                  ] 1078 of 2000 complete in 921.7 sec
[-----------------53%                  ] 1079 of 2000 complete in 922.6 sec
[-----------------54%                  ] 1080 of 2000 complete in 923.5 sec
[-----------------54%                  ] 1081 of 2000 complete in 924.3 sec
[-----------------54%                  ] 1082 of 2000 complete in 925.2 sec
[-----------------54%                  ] 1083 of 2000 complete in 926.1 sec
[-----------------54%                  ] 1084 of 2000 complete in 926.9 sec
[-----------------54%                  ] 1085 of 2000 complete in 927.8 sec
[-----------------54%                  ] 1086 of 2000 complete in 928.8 sec
[-----------------54%                  ] 1087 of 2000 complete in 929.7 sec
[-----------------54%                  ] 1088 of 2000 complete in 930.6 sec
[-----------------54%                  ] 1089 of 2000 complete in 931.4 sec
[-----------------54%                  ] 1090 of 2000 complete in 932.4 sec
[-----------------54%                  ] 1091 of 2000 complete in 933.3 sec
[-----------------54%                  ] 1092 of 2000 complete in 934.1 sec

[---------------- 43%                  ] 876 of 2000 complete in 842.4 sec
[---------------- 43%                  ] 877 of 2000 complete in 843.3 sec
[---------------- 43%                  ] 878 of 2000 complete in 844.2 sec
[---------------- 43%                  ] 879 of 2000 complete in 845.1 sec
[---------------- 44%                  ] 880 of 2000 complete in 845.9 sec
[---------------- 44%                  ] 881 of 2000 complete in 846.8 sec
[---------------- 44%                  ] 882 of 2000 complete in 847.7 sec
[---------------- 44%                  ] 883 of 2000 complete in 848.6 sec
[---------------- 44%                  ] 884 of 2000 complete in 849.5 sec
[---------------- 44%                  ] 885 of 2000 complete in 850.3 sec
[---------------- 44%                  ] 886 of 2000 complete in 851.2 sec
[---------------- 44%                  ] 887 of 2000 complete in 852.0 sec
[---------------- 44%                  ] 888 of 2000 complete in 852.9 sec
[---------------- 44%                  ] 889 of 2000 complete in 853.8 sec
[---------------- 44%                  ] 890 of 2000 complete in 854.6 sec
[---------------- 44%                  ] 891 of 2000 complete in 855.4 sec
[---------------- 44%                  ] 892 of 2000 complete in 856.3 sec
[---------------- 44%                  ] 893 of 2000 complete in 857.2 sec
[---------------- 44%                  ] 894 of 2000 complete in 858.0 sec
[-----------------44%                  ] 895 of 2000 complete in 858.9 sec
[-----------------44%                  ] 896 of 2000 complete in 859.8 sec
[-----------------44%                  ] 897 of 2000 complete in 860.7 sec
[-----------------44%                  ] 898 of 2000 complete in 861.6 sec
[-----------------44%                  ] 899 of 2000 complete in 862.5 sec
[-----------------45%                  ] 900 of 2000 complete in 863.4 sec
[-----------------45%                  ] 901 of 2000 complete in 864.3 sec
[-----------------45%                  ] 902 of 2000 complete in 865.2 sec
[-----------------45%                  ] 903 of 2000 complete in 866.1 sec
[-----------------45%                  ] 904 of 2000 complete in 867.0 sec
[-----------------45%                  ] 905 of 2000 complete in 867.9 sec
[-----------------45%                  ] 906 of 2000 complete in 868.8 sec
[-----------------45%                  ] 907 of 2000 complete in 869.7 sec
[-----------------45%                  ] 908 of 2000 complete in 870.6 sec
[-----------------45%                  ] 909 of 2000 complete in 871.4 sec
[-----------------45%                  ] 910 of 2000 complete in 872.3 sec
[-----------------45%                  ] 911 of 2000 complete in 873.2 sec
[-----------------45%                  ] 912 of 2000 complete in 874.1 sec
[-----------------45%                  ] 913 of 2000 complete in 875.0 sec
[-----------------45%                  ] 914 of 2000 complete in 875.9 sec
[-----------------45%                  ] 915 of 2000 complete in 876.7 sec
[-----------------45%                  ] 916 of 2000 complete in 877.6 sec
[-----------------45%                  ] 917 of 2000 complete in 878.4 sec
[-----------------45%                  ] 918 of 2000 complete in 879.2 sec
[-----------------45%                  ] 919 of 2000 complete in 880.1 sec
[-----------------46%                  ] 920 of 2000 complete in 880.9 sec
[-----------------46%                  ] 921 of 2000 complete in 881.8 sec
[-----------------46%                  ] 922 of 2000 complete in 882.6 sec
[-----------------46%                  ] 923 of 2000 complete in 883.5 sec
[-----------------46%                  ] 924 of 2000 complete in 884.3 sec
[-----------------46%                  ] 925 of 2000 complete in 885.2 sec
[-----------------46%                  ] 926 of 2000 complete in 886.0 sec
[-----------------46%                  ] 927 of 2000 complete in 886.8 sec
[-----------------46%                  ] 928 of 2000 complete in 887.7 sec
[-----------------46%                  ] 929 of 2000 complete in 888.5 sec
[-----------------46%                  ] 930 of 2000 complete in 889.3 sec
[-----------------46%                  ] 931 of 2000 complete in 890.2 sec
[-----------------46%                  ] 932 of 2000 complete in 891.0 sec
[-----------------46%                  ] 933 of 2000 complete in 891.9 sec
[-----------------46%                  ] 934 of 2000 complete in 892.8 sec
[-----------------46%                  ] 935 of 2000 complete in 893.6 sec
[-----------------46%                  ] 936 of 2000 complete in 894.4 sec
[-----------------46%                  ] 937 of 2000 complete in 895.3 sec
[-----------------46%                  ] 938 of 2000 complete in 896.1 sec
[-----------------46%                  ] 939 of 2000 complete in 897.0 sec
[-----------------47%                  ] 940 of 2000 complete in 897.9 sec
[-----------------47%                  ] 941 of 2000 complete in 898.8 sec
[-----------------47%                  ] 942 of 2000 complete in 899.7 sec
[-----------------47%                  ] 943 of 2000 complete in 900.6 sec
[-----------------47%                  ] 944 of 2000 complete in 901.4 sec
[-----------------47%                  ] 945 of 2000 complete in 902.3 sec
[-----------------47%                  ] 946 of 2000 complete in 903.1 sec
[-----------------47%                  ] 947 of 2000 complete in 904.0 sec
[-----------------47%                  ] 948 of 2000 complete in 904.8 sec
[-----------------47%                  ] 949 of 2000 complete in 905.7 sec
[-----------------47%                  ] 950 of 2000 complete in 906.6 sec
[-----------------47%                  ] 951 of 2000 complete in 907.4 sec
[-----------------47%                  ] 952 of 2000 complete in 908.2 sec
[-----------------47%                  ] 953 of 2000 complete in 909.1 sec
[-----------------47%                  ] 954 of 2000 complete in 910.0 sec
[-----------------47%                  ] 955 of 2000 complete in 910.8 sec
[-----------------47%                  ] 956 of 2000 complete in 911.7 sec
[-----------------47%                  ] 957 of 2000 complete in 912.5 sec
[-----------------47%                  ] 958 of 2000 complete in 913.4 sec
[-----------------47%                  ] 959 of 2000 complete in 914.3 sec
[-----------------48%                  ] 960 of 2000 complete in 915.3 sec
[-----------------48%                  ] 961 of 2000 complete in 916.2 sec
[-----------------48%                  ] 962 of 2000 complete in 917.1 sec
[-----------------48%                  ] 963 of 2000 complete in 918.0 sec
[-----------------48%                  ] 964 of 2000 complete in 918.9 sec
[-----------------48%                  ] 965 of 2000 complete in 919.7 sec
[-----------------48%                  ] 966 of 2000 complete in 920.6 sec
[-----------------48%                  ] 967 of 2000 complete in 921.5 sec
[-----------------48%                  ] 968 of 2000 complete in 922.4 sec
[-----------------48%                  ] 969 of 2000 complete in 923.3 sec
[-----------------48%                  ] 970 of 2000 complete in 924.2 sec
[-----------------48%                  ] 971 of 2000 complete in 925.2 sec
[-----------------48%                  ] 972 of 2000 complete in 926.2 sec
[-----------------48%                  ] 973 of 2000 complete in 927.1 sec
[-----------------48%                  ] 974 of 2000 complete in 928.0 sec
[-----------------48%                  ] 975 of 2000 complete in 929.0 sec
[-----------------48%                  ] 976 of 2000 complete in 930.0 sec
[-----------------48%                  ] 977 of 2000 complete in 931.0 sec
[-----------------48%                  ] 978 of 2000 complete in 931.9 sec
[-----------------48%                  ] 979 of 2000 complete in 932.9 sec
[-----------------49%                  ] 980 of 2000 complete in 933.8 sec
[-----------------49%                  ] 981 of 2000 complete in 934.8 sec
[-----------------49%                  ] 982 of 2000 complete in 935.7 sec
[-----------------49%                  ] 983 of 2000 complete in 936.7 sec
[-----------------49%                  ] 984 of 2000 complete in 937.6 sec
[-----------------49%                  ] 985 of 2000 complete in 923.8 sec
[-----------------49%                  ] 986 of 2000 complete in 924.5 sec
[-----------------49%                  ] 987 of 2000 complete in 925.3 sec
[-----------------49%                  ] 988 of 2000 complete in 926.0 sec
[-----------------49%                  ] 989 of 2000 complete in 926.7 sec
[-----------------49%                  ] 990 of 2000 complete in 927.5 sec
[-----------------49%                  ] 991 of 2000 complete in 928.2 sec
[-----------------49%                  ] 992 of 2000 complete in 929.0 sec
[-----------------49%                  ] 993 of 2000 complete in 929.8 sec
[-----------------49%                  ] 994 of 2000 complete in 930.5 sec
[-----------------49%                  ] 995 of 2000 complete in 931.3 sec
[-----------------49%                  ] 996 of 2000 complete in 932.0 sec
[-----------------49%                  ] 997 of 2000 complete in 932.8 sec
[-----------------49%                  ] 998 of 2000 complete in 933.5 sec
[-----------------49%                  ] 999 of 2000 complete in 934.2 sec
[-----------------50%                  ] 1000 of 2000 complete in 935.0 sec
[-----------------50%                  ] 1001 of 2000 complete in 935.8 sec
[-----------------50%                  ] 1002 of 2000 complete in 936.5 sec
[-----------------50%                  ] 1003 of 2000 complete in 937.3 sec
[-----------------50%                  ] 1004 of 2000 complete in 938.1 sec
[-----------------50%                  ] 1005 of 2000 complete in 938.9 sec
[-----------------50%                  ] 1006 of 2000 complete in 939.6 sec
[-----------------50%                  ] 1007 of 2000 complete in 940.4 sec
[-----------------50%                  ] 1008 of 2000 complete in 941.3 sec
[-----------------50%                  ] 1009 of 2000 complete in 942.1 sec
[-----------------50%                  ] 1010 of 2000 complete in 942.9 sec
[-----------------50%                  ] 1011 of 2000 complete in 943.8 sec
[-----------------50%                  ] 1012 of 2000 complete in 944.6 sec
[-----------------50%                  ] 1013 of 2000 complete in 945.4 sec
[-----------------50%                  ] 1014 of 2000 complete in 946.2 sec
[-----------------50%                  ] 1015 of 2000 complete in 947.0 sec
[-----------------50%                  ] 1016 of 2000 complete in 947.8 sec
[-----------------50%                  ] 1017 of 2000 complete in 948.7 sec
[-----------------50%                  ] 1018 of 2000 complete in 949.5 sec
[-----------------50%                  ] 1019 of 2000 complete in 950.3 sec
[-----------------51%                  ] 1020 of 2000 complete in 951.1 sec
[-----------------51%                  ] 1021 of 2000 complete in 952.0 sec
[-----------------51%                  ] 1022 of 2000 complete in 952.8 sec
[-----------------51%                  ] 1023 of 2000 complete in 953.6 sec
[-----------------51%                  ] 1024 of 2000 complete in 954.4 sec
[-----------------51%                  ] 1025 of 2000 complete in 955.2 sec
[-----------------51%                  ] 1026 of 2000 complete in 956.0 sec
[-----------------51%                  ] 1027 of 2000 complete in 956.8 sec
[-----------------51%                  ] 1028 of 2000 complete in 957.6 sec
[-----------------51%                  ] 1029 of 2000 complete in 958.4 sec
[-----------------51%                  ] 1030 of 2000 complete in 959.2 sec
[-----------------51%                  ] 1031 of 2000 complete in 960.1 sec
[-----------------51%                  ] 1032 of 2000 complete in 960.8 sec
[-----------------51%                  ] 1033 of 2000 complete in 961.6 sec
[-----------------51%                  ] 1034 of 2000 complete in 962.4 sec
[-----------------51%                  ] 1035 of 2000 complete in 963.2 sec
[-----------------51%                  ] 1036 of 2000 complete in 964.0 sec
[-----------------51%                  ] 1037 of 2000 complete in 964.9 sec
[-----------------51%                  ] 1038 of 2000 complete in 965.7 sec
[-----------------51%                  ] 1039 of 2000 complete in 966.5 sec
[-----------------52%                  ] 1040 of 2000 complete in 967.3 sec
[-----------------52%                  ] 1041 of 2000 complete in 968.1 sec
[-----------------52%                  ] 1042 of 2000 complete in 968.9 sec
[-----------------52%                  ] 1043 of 2000 complete in 969.7 sec
[-----------------52%                  ] 1044 of 2000 complete in 970.5 sec
[-----------------52%                  ] 1045 of 2000 complete in 971.2 sec
[-----------------52%                  ] 1046 of 2000 complete in 972.0 sec
[-----------------52%                  ] 1047 of 2000 complete in 972.8 sec
[-----------------52%                  ] 1048 of 2000 complete in 973.6 sec
[-----------------52%                  ] 1049 of 2000 complete in 974.3 sec
[-----------------52%                  ] 1050 of 2000 complete in 975.1 sec
[-----------------52%                  ] 1051 of 2000 complete in 975.8 sec
[-----------------52%                  ] 1052 of 2000 complete in 976.6 sec
[-----------------52%                  ] 1053 of 2000 complete in 977.3 sec
[-----------------52%                  ] 1054 of 2000 complete in 978.1 sec
[-----------------52%                  ] 1055 of 2000 complete in 978.8 sec
[-----------------52%                  ] 1056 of 2000 complete in 979.6 sec
[-----------------52%                  ] 1057 of 2000 complete in 980.3 sec
[-----------------52%                  ] 1058 of 2000 complete in 981.1 sec
[-----------------52%                  ] 1059 of 2000 complete in 981.8 sec
[-----------------53%                  ] 1060 of 2000 complete in 982.5 sec
[-----------------53%                  ] 1061 of 2000 complete in 983.3 sec
[-----------------53%                  ] 1062 of 2000 complete in 984.0 sec
[-----------------53%                  ] 1063 of 2000 complete in 984.7 sec
[-----------------53%                  ] 1064 of 2000 complete in 985.5 sec
[-----------------53%                  ] 1065 of 2000 complete in 986.3 sec
[-----------------53%                  ] 1066 of 2000 complete in 987.0 sec
[-----------------53%                  ] 1067 of 2000 complete in 987.8 sec
[-----------------53%                  ] 1068 of 2000 complete in 988.5 sec
[-----------------53%                  ] 1069 of 2000 complete in 989.3 sec
[-----------------53%                  ] 1070 of 2000 complete in 990.1 sec
[-----------------53%                  ] 1071 of 2000 complete in 990.8 sec
[-----------------53%                  ] 1072 of 2000 complete in 991.6 sec
[-----------------53%                  ] 1073 of 2000 complete in 992.3 sec
[-----------------53%                  ] 1074 of 2000 complete in 993.1 sec
[-----------------53%                  ] 1075 of 2000 complete in 993.8 sec
[-----------------53%                  ] 1076 of 2000 complete in 994.6 sec
[-----------------53%                  ] 1077 of 2000 complete in 995.4 sec
[-----------------53%                  ] 1078 of 2000 complete in 996.2 sec
[-----------------53%                  ] 1079 of 2000 complete in 997.0 sec
[-----------------54%                  ] 1080 of 2000 complete in 997.8 sec
[-----------------54%                  ] 1081 of 2000 complete in 998.6 sec
[-----------------54%                  ] 1082 of 2000 complete in 999.4 sec
[-----------------54%                  ] 1083 of 2000 complete in 1000.2 sec
[-----------------54%                  ] 1084 of 2000 complete in 1001.0 sec
[-----------------54%                  ] 1085 of 2000 complete in 1001.8 sec
[-----------------54%                  ] 1086 of 2000 complete in 1002.6 sec
[-----------------54%                  ] 1087 of 2000 complete in 1003.3 sec
[-----------------54%                  ] 1088 of 2000 complete in 1004.1 sec
[-----------------54%                  ] 1089 of 2000 complete in 1005.0 sec
[-----------------54%                  ] 1090 of 2000 complete in 1005.8 sec
[-----------------54%                  ] 1091 of 2000 complete in 1006.6 sec

[-----------------49%                  ] 985 of 2000 complete in 938.5 sec
[-----------------49%                  ] 986 of 2000 complete in 939.5 sec
[-----------------49%                  ] 987 of 2000 complete in 940.5 sec
[-----------------49%                  ] 988 of 2000 complete in 941.4 sec
[-----------------49%                  ] 989 of 2000 complete in 942.3 sec
[-----------------49%                  ] 990 of 2000 complete in 943.3 sec
[-----------------49%                  ] 991 of 2000 complete in 944.2 sec
[-----------------49%                  ] 992 of 2000 complete in 945.1 sec
[-----------------49%                  ] 993 of 2000 complete in 946.1 sec
[-----------------49%                  ] 994 of 2000 complete in 947.0 sec
[-----------------49%                  ] 995 of 2000 complete in 947.9 sec
[-----------------49%                  ] 996 of 2000 complete in 948.8 sec
[-----------------49%                  ] 997 of 2000 complete in 949.6 sec
[-----------------49%                  ] 998 of 2000 complete in 950.5 sec
[-----------------49%                  ] 999 of 2000 complete in 951.4 sec
[-----------------50%                  ] 1000 of 2000 complete in 952.3 sec
[-----------------50%                  ] 1001 of 2000 complete in 953.1 sec
[-----------------50%                  ] 1002 of 2000 complete in 954.0 sec
[-----------------50%                  ] 1003 of 2000 complete in 954.8 sec
[-----------------50%                  ] 1004 of 2000 complete in 955.7 sec
[-----------------50%                  ] 1005 of 2000 complete in 956.5 sec
[-----------------50%                  ] 1006 of 2000 complete in 957.4 sec
[-----------------50%                  ] 1007 of 2000 complete in 958.3 sec
[-----------------50%                  ] 1008 of 2000 complete in 959.1 sec
[-----------------50%                  ] 1009 of 2000 complete in 960.0 sec
[-----------------50%                  ] 1010 of 2000 complete in 960.8 sec
[-----------------50%                  ] 1011 of 2000 complete in 961.7 sec
[-----------------50%                  ] 1012 of 2000 complete in 962.5 sec
[-----------------50%                  ] 1013 of 2000 complete in 963.4 sec
[-----------------50%                  ] 1014 of 2000 complete in 964.2 sec
[-----------------50%                  ] 1015 of 2000 complete in 965.1 sec
[-----------------50%                  ] 1016 of 2000 complete in 965.9 sec
[-----------------50%                  ] 1017 of 2000 complete in 966.7 sec
[-----------------50%                  ] 1018 of 2000 complete in 967.5 sec
[-----------------50%                  ] 1019 of 2000 complete in 968.4 sec
[-----------------51%                  ] 1020 of 2000 complete in 969.2 sec
[-----------------51%                  ] 1021 of 2000 complete in 970.0 sec
[-----------------51%                  ] 1022 of 2000 complete in 970.8 sec
[-----------------51%                  ] 1023 of 2000 complete in 971.7 sec
[-----------------51%                  ] 1024 of 2000 complete in 972.5 sec
[-----------------51%                  ] 1025 of 2000 complete in 973.3 sec
[-----------------51%                  ] 1026 of 2000 complete in 974.2 sec
[-----------------51%                  ] 1027 of 2000 complete in 975.0 sec
[-----------------51%                  ] 1028 of 2000 complete in 975.8 sec
[-----------------51%                  ] 1029 of 2000 complete in 976.7 sec
[-----------------51%                  ] 1030 of 2000 complete in 977.5 sec
[-----------------51%                  ] 1031 of 2000 complete in 978.4 sec
[-----------------51%                  ] 1032 of 2000 complete in 979.2 sec
[-----------------51%                  ] 1033 of 2000 complete in 980.1 sec
[-----------------51%                  ] 1034 of 2000 complete in 980.9 sec
[-----------------51%                  ] 1035 of 2000 complete in 981.8 sec
[-----------------51%                  ] 1036 of 2000 complete in 982.6 sec
[-----------------51%                  ] 1037 of 2000 complete in 983.5 sec
[-----------------51%                  ] 1038 of 2000 complete in 984.4 sec
[-----------------51%                  ] 1039 of 2000 complete in 985.2 sec
[-----------------52%                  ] 1040 of 2000 complete in 986.1 sec
[-----------------52%                  ] 1041 of 2000 complete in 986.9 sec
[-----------------52%                  ] 1042 of 2000 complete in 987.8 sec
[-----------------52%                  ] 1043 of 2000 complete in 988.7 sec
[-----------------52%                  ] 1044 of 2000 complete in 989.5 sec
[-----------------52%                  ] 1045 of 2000 complete in 990.4 sec
[-----------------52%                  ] 1046 of 2000 complete in 991.2 sec
[-----------------52%                  ] 1047 of 2000 complete in 992.0 sec
[-----------------52%                  ] 1048 of 2000 complete in 992.9 sec
[-----------------52%                  ] 1049 of 2000 complete in 993.7 sec
[-----------------52%                  ] 1050 of 2000 complete in 994.5 sec
[-----------------52%                  ] 1051 of 2000 complete in 995.4 sec
[-----------------52%                  ] 1052 of 2000 complete in 996.2 sec
[-----------------52%                  ] 1053 of 2000 complete in 997.0 sec
[-----------------52%                  ] 1054 of 2000 complete in 997.9 sec
[-----------------52%                  ] 1055 of 2000 complete in 998.7 sec
[-----------------52%                  ] 1056 of 2000 complete in 999.5 sec
[-----------------52%                  ] 1057 of 2000 complete in 1000.4 sec
[-----------------52%                  ] 1058 of 2000 complete in 1001.2 sec
[-----------------52%                  ] 1059 of 2000 complete in 1002.1 sec
[-----------------53%                  ] 1060 of 2000 complete in 1002.9 sec
[-----------------53%                  ] 1061 of 2000 complete in 1003.7 sec
[-----------------53%                  ] 1062 of 2000 complete in 1004.6 sec
[-----------------53%                  ] 1063 of 2000 complete in 1005.4 sec
[-----------------53%                  ] 1064 of 2000 complete in 1006.2 sec
[-----------------53%                  ] 1065 of 2000 complete in 1007.0 sec
[-----------------53%                  ] 1066 of 2000 complete in 1007.9 sec
[-----------------53%                  ] 1067 of 2000 complete in 1008.7 sec
[-----------------53%                  ] 1068 of 2000 complete in 1009.5 sec
[-----------------53%                  ] 1069 of 2000 complete in 1010.3 sec
[-----------------53%                  ] 1070 of 2000 complete in 1011.1 sec
[-----------------53%                  ] 1071 of 2000 complete in 1012.0 sec
[-----------------53%                  ] 1072 of 2000 complete in 1012.7 sec
[-----------------53%                  ] 1073 of 2000 complete in 1013.6 sec
[-----------------53%                  ] 1074 of 2000 complete in 1014.5 sec
[-----------------53%                  ] 1075 of 2000 complete in 1015.3 sec
[-----------------53%                  ] 1076 of 2000 complete in 1016.1 sec
[-----------------53%                  ] 1077 of 2000 complete in 1016.9 sec
[-----------------53%                  ] 1078 of 2000 complete in 1017.7 sec
[-----------------53%                  ] 1079 of 2000 complete in 1018.5 sec
[-----------------54%                  ] 1080 of 2000 complete in 1019.4 sec
[-----------------54%                  ] 1081 of 2000 complete in 1020.2 sec
[-----------------54%                  ] 1082 of 2000 complete in 1021.0 sec
[-----------------54%                  ] 1083 of 2000 complete in 1021.8 sec
[-----------------54%                  ] 1084 of 2000 complete in 1022.6 sec
[-----------------54%                  ] 1085 of 2000 complete in 1023.4 sec
[-----------------54%                  ] 1086 of 2000 complete in 1024.2 sec
[-----------------54%                  ] 1087 of 2000 complete in 1025.0 sec
[-----------------54%                  ] 1088 of 2000 complete in 1025.8 sec
[-----------------54%                  ] 1089 of 2000 complete in 1026.6 sec
[-----------------54%                  ] 1090 of 2000 complete in 1027.4 sec
[-----------------54%                  ] 1091 of 2000 complete in 1028.2 sec

[-----------------54%                  ] 1093 of 2000 complete in 934.2 sec
[-----------------54%                  ] 1094 of 2000 complete in 935.1 sec
[-----------------54%                  ] 1095 of 2000 complete in 936.0 sec
[-----------------54%                  ] 1096 of 2000 complete in 936.8 sec
[-----------------54%                  ] 1097 of 2000 complete in 937.7 sec
[-----------------54%                  ] 1098 of 2000 complete in 938.6 sec
[-----------------54%                  ] 1099 of 2000 complete in 939.4 sec
[-----------------55%                  ] 1100 of 2000 complete in 940.3 sec
[-----------------55%                  ] 1101 of 2000 complete in 941.2 sec
[-----------------55%                  ] 1102 of 2000 complete in 942.0 sec
[-----------------55%                  ] 1103 of 2000 complete in 942.9 sec
[-----------------55%                  ] 1104 of 2000 complete in 943.8 sec
[-----------------55%                  ] 1105 of 2000 complete in 944.7 sec
[-----------------55%-                 ] 1106 of 2000 complete in 945.5 sec
[-----------------55%-                 ] 1107 of 2000 complete in 946.4 sec
[-----------------55%-                 ] 1108 of 2000 complete in 947.2 sec
[-----------------55%-                 ] 1109 of 2000 complete in 948.1 sec
[-----------------55%-                 ] 1110 of 2000 complete in 949.0 sec
[-----------------55%-                 ] 1111 of 2000 complete in 949.8 sec
[-----------------55%-                 ] 1112 of 2000 complete in 950.7 sec
[-----------------55%-                 ] 1113 of 2000 complete in 951.5 sec
[-----------------55%-                 ] 1114 of 2000 complete in 952.4 sec
[-----------------55%-                 ] 1115 of 2000 complete in 953.3 sec
[-----------------55%-                 ] 1116 of 2000 complete in 954.2 sec
[-----------------55%-                 ] 1117 of 2000 complete in 955.1 sec
[-----------------55%-                 ] 1118 of 2000 complete in 955.9 sec
[-----------------55%-                 ] 1119 of 2000 complete in 956.8 sec
[-----------------56%-                 ] 1120 of 2000 complete in 957.7 sec
[-----------------56%-                 ] 1121 of 2000 complete in 958.6 sec
[-----------------56%-                 ] 1122 of 2000 complete in 959.4 sec
[-----------------56%-                 ] 1123 of 2000 complete in 960.3 sec
[-----------------56%-                 ] 1124 of 2000 complete in 961.1 sec
[-----------------56%-                 ] 1125 of 2000 complete in 962.0 sec
[-----------------56%-                 ] 1126 of 2000 complete in 962.9 sec
[-----------------56%-                 ] 1127 of 2000 complete in 963.8 sec
[-----------------56%-                 ] 1128 of 2000 complete in 964.6 sec
[-----------------56%-                 ] 1129 of 2000 complete in 965.5 sec
[-----------------56%-                 ] 1130 of 2000 complete in 966.3 sec
[-----------------56%-                 ] 1131 of 2000 complete in 967.2 sec
[-----------------56%-                 ] 1132 of 2000 complete in 968.0 sec
[-----------------56%-                 ] 1133 of 2000 complete in 968.9 sec
[-----------------56%-                 ] 1134 of 2000 complete in 969.8 sec
[-----------------56%-                 ] 1135 of 2000 complete in 970.7 sec
[-----------------56%-                 ] 1136 of 2000 complete in 971.7 sec
[-----------------56%-                 ] 1137 of 2000 complete in 972.6 sec
[-----------------56%-                 ] 1138 of 2000 complete in 973.6 sec
[-----------------56%-                 ] 1139 of 2000 complete in 974.5 sec
[-----------------57%-                 ] 1140 of 2000 complete in 975.5 sec
[-----------------57%-                 ] 1141 of 2000 complete in 976.4 sec
[-----------------57%-                 ] 1142 of 2000 complete in 977.3 sec
[-----------------57%-                 ] 1143 of 2000 complete in 978.2 sec
[-----------------57%-                 ] 1144 of 2000 complete in 979.1 sec
[-----------------57%-                 ] 1145 of 2000 complete in 980.0 sec
[-----------------57%-                 ] 1146 of 2000 complete in 981.0 sec
[-----------------57%-                 ] 1147 of 2000 complete in 981.9 sec
[-----------------57%-                 ] 1148 of 2000 complete in 982.8 sec
[-----------------57%-                 ] 1149 of 2000 complete in 983.8 sec
[-----------------57%-                 ] 1150 of 2000 complete in 984.7 sec
[-----------------57%-                 ] 1151 of 2000 complete in 985.6 sec
[-----------------57%-                 ] 1152 of 2000 complete in 986.5 sec
[-----------------57%-                 ] 1153 of 2000 complete in 987.4 sec
[-----------------57%-                 ] 1154 of 2000 complete in 988.3 sec
[-----------------57%-                 ] 1155 of 2000 complete in 989.3 sec
[-----------------57%-                 ] 1156 of 2000 complete in 990.2 sec
[-----------------57%-                 ] 1157 of 2000 complete in 991.1 sec
[-----------------57%--                ] 1158 of 2000 complete in 992.1 sec
[-----------------57%--                ] 1159 of 2000 complete in 993.1 sec
[-----------------58%--                ] 1160 of 2000 complete in 994.0 sec
[-----------------58%--                ] 1161 of 2000 complete in 995.0 sec
[-----------------58%--                ] 1162 of 2000 complete in 995.9 sec
[-----------------58%--                ] 1163 of 2000 complete in 996.8 sec
[-----------------58%--                ] 1164 of 2000 complete in 997.7 sec
[-----------------58%--                ] 1165 of 2000 complete in 998.6 sec
[-----------------58%--                ] 1166 of 2000 complete in 999.6 sec
[-----------------58%--                ] 1167 of 2000 complete in 1000.5 sec
[-----------------58%--                ] 1168 of 2000 complete in 1001.4 sec
[-----------------58%--                ] 1169 of 2000 complete in 1002.3 sec
[-----------------58%--                ] 1170 of 2000 complete in 1003.2 sec
[-----------------58%--                ] 1171 of 2000 complete in 1004.1 sec
[-----------------58%--                ] 1172 of 2000 complete in 1005.1 sec
[-----------------58%--                ] 1173 of 2000 complete in 1006.0 sec
[-----------------58%--                ] 1174 of 2000 complete in 1006.9 sec
[-----------------58%--                ] 1175 of 2000 complete in 1007.9 sec
[-----------------58%--                ] 1176 of 2000 complete in 1008.8 sec
[-----------------58%--                ] 1177 of 2000 complete in 1009.7 sec
[-----------------58%--                ] 1178 of 2000 complete in 1010.7 sec
[-----------------58%--                ] 1179 of 2000 complete in 1011.6 sec
[-----------------59%--                ] 1180 of 2000 complete in 1012.6 sec
[-----------------59%--                ] 1181 of 2000 complete in 1013.5 sec
[-----------------59%--                ] 1182 of 2000 complete in 1014.4 sec
[-----------------59%--                ] 1183 of 2000 complete in 1015.4 sec
[-----------------59%--                ] 1184 of 2000 complete in 1016.3 sec
[-----------------59%--                ] 1185 of 2000 complete in 1017.3 sec
[-----------------59%--                ] 1186 of 2000 complete in 1018.2 sec
[-----------------59%--                ] 1187 of 2000 complete in 1019.1 sec
[-----------------59%--                ] 1188 of 2000 complete in 1020.0 sec
[-----------------59%--                ] 1189 of 2000 complete in 1021.1 sec
[-----------------59%--                ] 1190 of 2000 complete in 1022.0 sec
[-----------------59%--                ] 1191 of 2000 complete in 1022.9 sec
[-----------------59%--                ] 1192 of 2000 complete in 1023.9 sec
[-----------------59%--                ] 1193 of 2000 complete in 1024.8 sec
[-----------------59%--                ] 1194 of 2000 complete in 1025.7 sec
[-----------------59%--                ] 1195 of 2000 complete in 1026.7 sec
[-----------------59%--                ] 1196 of 2000 complete in 1027.6 sec
[-----------------59%--                ] 1197 of 2000 complete in 1028.5 sec
[-----------------59%--                ] 1198 of 2000 complete in 1029.5 sec
[-----------------59%--                ] 1199 of 2000 complete in 1030.4 sec

[-----------------54%                  ] 1093 of 2000 complete in 935.1 sec
[-----------------54%                  ] 1094 of 2000 complete in 936.0 sec
[-----------------54%                  ] 1095 of 2000 complete in 936.9 sec
[-----------------54%                  ] 1096 of 2000 complete in 937.8 sec
[-----------------54%                  ] 1097 of 2000 complete in 938.8 sec
[-----------------54%                  ] 1098 of 2000 complete in 939.7 sec
[-----------------54%                  ] 1099 of 2000 complete in 940.6 sec
[-----------------55%                  ] 1100 of 2000 complete in 941.5 sec
[-----------------55%                  ] 1101 of 2000 complete in 942.4 sec
[-----------------55%                  ] 1102 of 2000 complete in 943.4 sec
[-----------------55%                  ] 1103 of 2000 complete in 944.3 sec
[-----------------55%                  ] 1104 of 2000 complete in 945.3 sec
[-----------------55%                  ] 1105 of 2000 complete in 946.2 sec
[-----------------55%-                 ] 1106 of 2000 complete in 947.1 sec
[-----------------55%-                 ] 1107 of 2000 complete in 948.0 sec
[-----------------55%-                 ] 1108 of 2000 complete in 948.9 sec
[-----------------55%-                 ] 1109 of 2000 complete in 949.9 sec
[-----------------55%-                 ] 1110 of 2000 complete in 950.8 sec
[-----------------55%-                 ] 1111 of 2000 complete in 951.7 sec
[-----------------55%-                 ] 1112 of 2000 complete in 952.7 sec
[-----------------55%-                 ] 1113 of 2000 complete in 953.6 sec
[-----------------55%-                 ] 1114 of 2000 complete in 954.6 sec
[-----------------55%-                 ] 1115 of 2000 complete in 955.6 sec
[-----------------55%-                 ] 1116 of 2000 complete in 956.5 sec
[-----------------55%-                 ] 1117 of 2000 complete in 957.4 sec
[-----------------55%-                 ] 1118 of 2000 complete in 958.3 sec
[-----------------55%-                 ] 1119 of 2000 complete in 959.3 sec
[-----------------56%-                 ] 1120 of 2000 complete in 960.2 sec
[-----------------56%-                 ] 1121 of 2000 complete in 961.1 sec
[-----------------56%-                 ] 1122 of 2000 complete in 962.0 sec
[-----------------56%-                 ] 1123 of 2000 complete in 962.9 sec
[-----------------56%-                 ] 1124 of 2000 complete in 963.8 sec
[-----------------56%-                 ] 1125 of 2000 complete in 964.7 sec
[-----------------56%-                 ] 1126 of 2000 complete in 965.5 sec
[-----------------56%-                 ] 1127 of 2000 complete in 966.5 sec
[-----------------56%-                 ] 1128 of 2000 complete in 967.3 sec
[-----------------56%-                 ] 1129 of 2000 complete in 968.2 sec
[-----------------56%-                 ] 1130 of 2000 complete in 969.1 sec
[-----------------56%-                 ] 1131 of 2000 complete in 970.0 sec
[-----------------56%-                 ] 1132 of 2000 complete in 970.8 sec
[-----------------56%-                 ] 1133 of 2000 complete in 971.7 sec
[-----------------56%-                 ] 1134 of 2000 complete in 972.5 sec
[-----------------56%-                 ] 1135 of 2000 complete in 973.4 sec
[-----------------56%-                 ] 1136 of 2000 complete in 974.3 sec
[-----------------56%-                 ] 1137 of 2000 complete in 975.1 sec
[-----------------56%-                 ] 1138 of 2000 complete in 976.0 sec
[-----------------56%-                 ] 1139 of 2000 complete in 976.9 sec
[-----------------57%-                 ] 1140 of 2000 complete in 977.8 sec
[-----------------57%-                 ] 1141 of 2000 complete in 978.6 sec
[-----------------57%-                 ] 1142 of 2000 complete in 979.6 sec
[-----------------57%-                 ] 1143 of 2000 complete in 980.5 sec
[-----------------57%-                 ] 1144 of 2000 complete in 981.4 sec
[-----------------57%-                 ] 1145 of 2000 complete in 982.3 sec
[-----------------57%-                 ] 1146 of 2000 complete in 983.2 sec
[-----------------57%-                 ] 1147 of 2000 complete in 984.1 sec
[-----------------57%-                 ] 1148 of 2000 complete in 985.0 sec
[-----------------57%-                 ] 1149 of 2000 complete in 985.9 sec
[-----------------57%-                 ] 1150 of 2000 complete in 986.9 sec
[-----------------57%-                 ] 1151 of 2000 complete in 987.8 sec
[-----------------57%-                 ] 1152 of 2000 complete in 988.7 sec
[-----------------57%-                 ] 1153 of 2000 complete in 989.7 sec
[-----------------57%-                 ] 1154 of 2000 complete in 990.6 sec
[-----------------57%-                 ] 1155 of 2000 complete in 991.5 sec
[-----------------57%-                 ] 1156 of 2000 complete in 992.4 sec
[-----------------57%-                 ] 1157 of 2000 complete in 993.3 sec
[-----------------57%--                ] 1158 of 2000 complete in 994.2 sec
[-----------------57%--                ] 1159 of 2000 complete in 995.1 sec
[-----------------58%--                ] 1160 of 2000 complete in 996.0 sec
[-----------------58%--                ] 1161 of 2000 complete in 996.9 sec
[-----------------58%--                ] 1162 of 2000 complete in 997.8 sec
[-----------------58%--                ] 1163 of 2000 complete in 998.7 sec
[-----------------58%--                ] 1164 of 2000 complete in 999.6 sec
[-----------------58%--                ] 1165 of 2000 complete in 1000.5 sec
[-----------------58%--                ] 1166 of 2000 complete in 1001.3 sec
[-----------------58%--                ] 1167 of 2000 complete in 1002.2 sec
[-----------------58%--                ] 1168 of 2000 complete in 1003.0 sec
[-----------------58%--                ] 1169 of 2000 complete in 1003.9 sec
[-----------------58%--                ] 1170 of 2000 complete in 1004.8 sec
[-----------------58%--                ] 1171 of 2000 complete in 1005.7 sec
[-----------------58%--                ] 1172 of 2000 complete in 1006.5 sec
[-----------------58%--                ] 1173 of 2000 complete in 1007.4 sec
[-----------------58%--                ] 1174 of 2000 complete in 1008.3 sec
[-----------------58%--                ] 1175 of 2000 complete in 1009.2 sec
[-----------------58%--                ] 1176 of 2000 complete in 1010.1 sec
[-----------------58%--                ] 1177 of 2000 complete in 1011.0 sec
[-----------------58%--                ] 1178 of 2000 complete in 1011.9 sec
[-----------------58%--                ] 1179 of 2000 complete in 1012.7 sec
[-----------------59%--                ] 1180 of 2000 complete in 1013.6 sec
[-----------------59%--                ] 1181 of 2000 complete in 1014.5 sec
[-----------------59%--                ] 1182 of 2000 complete in 1015.4 sec
[-----------------59%--                ] 1183 of 2000 complete in 1016.2 sec
[-----------------59%--                ] 1184 of 2000 complete in 1017.1 sec
[-----------------59%--                ] 1185 of 2000 complete in 1018.0 sec
[-----------------59%--                ] 1186 of 2000 complete in 1018.9 sec
[-----------------59%--                ] 1187 of 2000 complete in 1019.8 sec
[-----------------59%--                ] 1188 of 2000 complete in 1020.7 sec
[-----------------59%--                ] 1189 of 2000 complete in 1021.6 sec
[-----------------59%--                ] 1190 of 2000 complete in 1022.5 sec
[-----------------59%--                ] 1191 of 2000 complete in 1023.4 sec
[-----------------59%--                ] 1192 of 2000 complete in 1024.3 sec
[-----------------59%--                ] 1193 of 2000 complete in 1025.3 sec
[-----------------59%--                ] 1194 of 2000 complete in 1026.2 sec
[-----------------59%--                ] 1195 of 2000 complete in 1027.1 sec
[-----------------59%--                ] 1196 of 2000 complete in 1028.0 sec
[-----------------59%--                ] 1197 of 2000 complete in 1029.0 sec
[-----------------59%--                ] 1198 of 2000 complete in 1030.0 sec
[-----------------59%--                ] 1199 of 2000 complete in 1030.9 sec
[-----------------54%                  ] 1092 of 2000 complete in 1007.5 sec
[-----------------54%                  ] 1093 of 2000 complete in 1008.4 sec
[-----------------54%                  ] 1094 of 2000 complete in 1009.2 sec
[-----------------54%                  ] 1095 of 2000 complete in 1010.0 sec
[-----------------54%                  ] 1096 of 2000 complete in 1010.9 sec
[-----------------54%                  ] 1097 of 2000 complete in 1011.8 sec
[-----------------54%                  ] 1098 of 2000 complete in 1012.6 sec
[-----------------54%                  ] 1099 of 2000 complete in 1013.5 sec
[-----------------55%                  ] 1100 of 2000 complete in 1014.4 sec
[-----------------55%                  ] 1101 of 2000 complete in 1015.2 sec
[-----------------55%                  ] 1102 of 2000 complete in 1016.1 sec
[-----------------55%                  ] 1103 of 2000 complete in 1016.9 sec
[-----------------55%                  ] 1104 of 2000 complete in 1017.8 sec
[-----------------55%                  ] 1105 of 2000 complete in 1018.6 sec
[-----------------55%-                 ] 1106 of 2000 complete in 1019.5 sec
[-----------------55%-                 ] 1107 of 2000 complete in 1020.4 sec
[-----------------55%-                 ] 1108 of 2000 complete in 1021.3 sec
[-----------------55%-                 ] 1109 of 2000 complete in 1022.1 sec
[-----------------55%-                 ] 1110 of 2000 complete in 1022.9 sec
[-----------------55%-                 ] 1111 of 2000 complete in 1023.7 sec
[-----------------55%-                 ] 1112 of 2000 complete in 1024.6 sec
[-----------------55%-                 ] 1113 of 2000 complete in 1025.4 sec
[-----------------55%-                 ] 1114 of 2000 complete in 1026.2 sec
[-----------------55%-                 ] 1115 of 2000 complete in 1027.1 sec
[-----------------55%-                 ] 1116 of 2000 complete in 1027.9 sec
[-----------------55%-                 ] 1117 of 2000 complete in 1028.8 sec
[-----------------55%-                 ] 1118 of 2000 complete in 1029.7 sec
[-----------------55%-                 ] 1119 of 2000 complete in 1030.6 sec
[-----------------56%-                 ] 1120 of 2000 complete in 1031.5 sec
[-----------------56%-                 ] 1121 of 2000 complete in 1032.4 sec
[-----------------56%-                 ] 1122 of 2000 complete in 1033.3 sec
[-----------------56%-                 ] 1123 of 2000 complete in 1034.2 sec
[-----------------56%-                 ] 1124 of 2000 complete in 1035.1 sec
[-----------------56%-                 ] 1125 of 2000 complete in 1036.0 sec
[-----------------56%-                 ] 1126 of 2000 complete in 1036.9 sec
[-----------------56%-                 ] 1127 of 2000 complete in 1037.8 sec
[-----------------56%-                 ] 1128 of 2000 complete in 1038.6 sec
[-----------------56%-                 ] 1129 of 2000 complete in 1039.5 sec
[-----------------56%-                 ] 1130 of 2000 complete in 1040.3 sec
[-----------------56%-                 ] 1131 of 2000 complete in 1041.1 sec
[-----------------56%-                 ] 1132 of 2000 complete in 1042.0 sec
[-----------------56%-                 ] 1133 of 2000 complete in 1042.8 sec
[-----------------56%-                 ] 1134 of 2000 complete in 1043.7 sec
[-----------------56%-                 ] 1135 of 2000 complete in 1044.6 sec
[-----------------56%-                 ] 1136 of 2000 complete in 1045.5 sec
[-----------------56%-                 ] 1137 of 2000 complete in 1046.4 sec
[-----------------56%-                 ] 1138 of 2000 complete in 1047.2 sec
[-----------------56%-                 ] 1139 of 2000 complete in 1048.0 sec
[-----------------57%-                 ] 1140 of 2000 complete in 1048.8 sec
[-----------------57%-                 ] 1141 of 2000 complete in 1049.6 sec
[-----------------57%-                 ] 1142 of 2000 complete in 1050.5 sec
[-----------------57%-                 ] 1143 of 2000 complete in 1051.3 sec
[-----------------57%-                 ] 1144 of 2000 complete in 1052.2 sec
[-----------------57%-                 ] 1145 of 2000 complete in 1053.0 sec
[-----------------57%-                 ] 1146 of 2000 complete in 1053.9 sec
[-----------------57%-                 ] 1147 of 2000 complete in 1054.7 sec
[-----------------57%-                 ] 1148 of 2000 complete in 1055.5 sec
[-----------------57%-                 ] 1149 of 2000 complete in 1056.4 sec
[-----------------57%-                 ] 1150 of 2000 complete in 1057.2 sec
[-----------------57%-                 ] 1151 of 2000 complete in 1058.0 sec
[-----------------57%-                 ] 1152 of 2000 complete in 1058.9 sec
[-----------------57%-                 ] 1153 of 2000 complete in 1059.8 sec
[-----------------57%-                 ] 1154 of 2000 complete in 1060.6 sec
[-----------------57%-                 ] 1155 of 2000 complete in 1061.5 sec
[-----------------57%-                 ] 1156 of 2000 complete in 1062.3 sec
[-----------------57%-                 ] 1157 of 2000 complete in 1063.2 sec
[-----------------57%--                ] 1158 of 2000 complete in 1064.0 sec
[-----------------57%--                ] 1159 of 2000 complete in 1064.8 sec
[-----------------58%--                ] 1160 of 2000 complete in 1065.7 sec
[-----------------58%--                ] 1161 of 2000 complete in 1066.6 sec
[-----------------58%--                ] 1162 of 2000 complete in 1067.4 sec
[-----------------58%--                ] 1163 of 2000 complete in 1068.2 sec
[-----------------58%--                ] 1164 of 2000 complete in 1069.0 sec
[-----------------58%--                ] 1165 of 2000 complete in 1069.9 sec
[-----------------58%--                ] 1166 of 2000 complete in 1070.8 sec
[-----------------58%--                ] 1167 of 2000 complete in 1071.7 sec
[-----------------58%--                ] 1168 of 2000 complete in 1072.6 sec
[-----------------58%--                ] 1169 of 2000 complete in 1073.4 sec
[-----------------58%--                ] 1170 of 2000 complete in 1074.3 sec
[-----------------58%--                ] 1171 of 2000 complete in 1075.2 sec
[-----------------58%--                ] 1172 of 2000 complete in 1076.1 sec
[-----------------58%--                ] 1173 of 2000 complete in 1076.9 sec
[-----------------58%--                ] 1174 of 2000 complete in 1077.8 sec
[-----------------58%--                ] 1175 of 2000 complete in 1078.6 sec
[-----------------58%--                ] 1176 of 2000 complete in 1079.5 sec
[-----------------58%--                ] 1177 of 2000 complete in 1080.4 sec
[-----------------58%--                ] 1178 of 2000 complete in 1081.2 sec
[-----------------58%--                ] 1179 of 2000 complete in 1082.1 sec
[-----------------59%--                ] 1180 of 2000 complete in 1083.0 sec
[-----------------59%--                ] 1181 of 2000 complete in 1083.9 sec
[-----------------59%--                ] 1182 of 2000 complete in 1084.8 sec
[-----------------59%--                ] 1183 of 2000 complete in 1085.7 sec
[-----------------59%--                ] 1184 of 2000 complete in 1086.7 sec
[-----------------59%--                ] 1185 of 2000 complete in 1087.6 sec
[-----------------59%--                ] 1186 of 2000 complete in 1088.5 sec
[-----------------59%--                ] 1187 of 2000 complete in 1089.4 sec
[-----------------59%--                ] 1188 of 2000 complete in 1090.3 sec
[-----------------59%--                ] 1189 of 2000 complete in 1091.3 sec
[-----------------59%--                ] 1190 of 2000 complete in 1092.2 sec
[-----------------59%--                ] 1191 of 2000 complete in 1093.1 sec
[-----------------59%--                ] 1192 of 2000 complete in 1094.0 sec
[-----------------59%--                ] 1193 of 2000 complete in 1095.0 sec
[-----------------59%--                ] 1194 of 2000 complete in 1095.9 sec
[-----------------59%--                ] 1195 of 2000 complete in 1096.8 sec
[-----------------59%--                ] 1196 of 2000 complete in 1097.8 sec
[-----------------59%--                ] 1197 of 2000 complete in 1098.7 sec

[-----------------54%                  ] 1092 of 2000 complete in 1029.1 sec
[-----------------54%                  ] 1093 of 2000 complete in 1029.9 sec
[-----------------54%                  ] 1094 of 2000 complete in 1030.7 sec
[-----------------54%                  ] 1095 of 2000 complete in 1031.5 sec
[-----------------54%                  ] 1096 of 2000 complete in 1032.3 sec
[-----------------54%                  ] 1097 of 2000 complete in 1033.1 sec
[-----------------54%                  ] 1098 of 2000 complete in 1033.9 sec
[-----------------54%                  ] 1099 of 2000 complete in 1034.6 sec
[-----------------55%                  ] 1100 of 2000 complete in 1035.4 sec
[-----------------55%                  ] 1101 of 2000 complete in 1036.2 sec
[-----------------55%                  ] 1102 of 2000 complete in 1037.0 sec
[-----------------55%                  ] 1103 of 2000 complete in 1037.8 sec
[-----------------55%                  ] 1104 of 2000 complete in 1038.5 sec
[-----------------55%                  ] 1105 of 2000 complete in 1039.3 sec
[-----------------55%-                 ] 1106 of 2000 complete in 1040.1 sec
[-----------------55%-                 ] 1107 of 2000 complete in 1040.8 sec
[-----------------55%-                 ] 1108 of 2000 complete in 1041.6 sec
[-----------------55%-                 ] 1109 of 2000 complete in 1042.4 sec
[-----------------55%-                 ] 1110 of 2000 complete in 1043.2 sec
[-----------------55%-                 ] 1111 of 2000 complete in 1044.0 sec
[-----------------55%-                 ] 1112 of 2000 complete in 1044.8 sec
[-----------------55%-                 ] 1113 of 2000 complete in 1045.7 sec
[-----------------55%-                 ] 1114 of 2000 complete in 1046.5 sec
[-----------------55%-                 ] 1115 of 2000 complete in 1047.2 sec
[-----------------55%-                 ] 1116 of 2000 complete in 1048.0 sec
[-----------------55%-                 ] 1117 of 2000 complete in 1048.8 sec
[-----------------55%-                 ] 1118 of 2000 complete in 1049.6 sec
[-----------------55%-                 ] 1119 of 2000 complete in 1050.4 sec
[-----------------56%-                 ] 1120 of 2000 complete in 1051.3 sec
[-----------------56%-                 ] 1121 of 2000 complete in 1052.1 sec
[-----------------56%-                 ] 1122 of 2000 complete in 1052.9 sec
[-----------------56%-                 ] 1123 of 2000 complete in 1053.6 sec
[-----------------56%-                 ] 1124 of 2000 complete in 1054.4 sec
[-----------------56%-                 ] 1125 of 2000 complete in 1055.2 sec
[-----------------56%-                 ] 1126 of 2000 complete in 1055.9 sec
[-----------------56%-                 ] 1127 of 2000 complete in 1056.7 sec
[-----------------56%-                 ] 1128 of 2000 complete in 1057.4 sec
[-----------------56%-                 ] 1129 of 2000 complete in 1058.2 sec
[-----------------56%-                 ] 1130 of 2000 complete in 1058.9 sec
[-----------------56%-                 ] 1131 of 2000 complete in 1059.6 sec
[-----------------56%-                 ] 1132 of 2000 complete in 1060.5 sec
[-----------------56%-                 ] 1133 of 2000 complete in 1061.2 sec
[-----------------56%-                 ] 1134 of 2000 complete in 1062.0 sec
[-----------------56%-                 ] 1135 of 2000 complete in 1062.8 sec
[-----------------56%-                 ] 1136 of 2000 complete in 1063.6 sec
[-----------------56%-                 ] 1137 of 2000 complete in 1064.4 sec
[-----------------56%-                 ] 1138 of 2000 complete in 1065.2 sec
[-----------------56%-                 ] 1139 of 2000 complete in 1066.0 sec
[-----------------57%-                 ] 1140 of 2000 complete in 1066.8 sec
[-----------------57%-                 ] 1141 of 2000 complete in 1067.6 sec
[-----------------57%-                 ] 1142 of 2000 complete in 1068.4 sec
[-----------------57%-                 ] 1143 of 2000 complete in 1069.2 sec
[-----------------57%-                 ] 1144 of 2000 complete in 1070.0 sec
[-----------------57%-                 ] 1145 of 2000 complete in 1070.8 sec
[-----------------57%-                 ] 1146 of 2000 complete in 1071.7 sec
[-----------------57%-                 ] 1147 of 2000 complete in 1072.5 sec
[-----------------57%-                 ] 1148 of 2000 complete in 1073.3 sec
[-----------------57%-                 ] 1149 of 2000 complete in 1074.1 sec
[-----------------57%-                 ] 1150 of 2000 complete in 1074.8 sec
[-----------------57%-                 ] 1151 of 2000 complete in 1075.7 sec
[-----------------57%-                 ] 1152 of 2000 complete in 1076.5 sec
[-----------------57%-                 ] 1153 of 2000 complete in 1077.3 sec
[-----------------57%-                 ] 1154 of 2000 complete in 1078.2 sec
[-----------------57%-                 ] 1155 of 2000 complete in 1079.0 sec
[-----------------57%-                 ] 1156 of 2000 complete in 1079.8 sec
[-----------------57%-                 ] 1157 of 2000 complete in 1080.6 sec
[-----------------57%--                ] 1158 of 2000 complete in 1081.4 sec
[-----------------57%--                ] 1159 of 2000 complete in 1082.3 sec
[-----------------58%--                ] 1160 of 2000 complete in 1083.1 sec
[-----------------58%--                ] 1161 of 2000 complete in 1084.0 sec
[-----------------58%--                ] 1162 of 2000 complete in 1084.8 sec
[-----------------58%--                ] 1163 of 2000 complete in 1085.6 sec
[-----------------58%--                ] 1164 of 2000 complete in 1086.5 sec
[-----------------58%--                ] 1165 of 2000 complete in 1087.4 sec
[-----------------58%--                ] 1166 of 2000 complete in 1088.2 sec
[-----------------58%--                ] 1167 of 2000 complete in 1089.1 sec
[-----------------58%--                ] 1168 of 2000 complete in 1090.0 sec
[-----------------58%--                ] 1169 of 2000 complete in 1090.9 sec
[-----------------58%--                ] 1170 of 2000 complete in 1091.7 sec
[-----------------58%--                ] 1171 of 2000 complete in 1092.7 sec
[-----------------58%--                ] 1172 of 2000 complete in 1093.5 sec
[-----------------58%--                ] 1173 of 2000 complete in 1094.5 sec
[-----------------58%--                ] 1174 of 2000 complete in 1095.4 sec
[-----------------58%--                ] 1175 of 2000 complete in 1096.3 sec
[-----------------58%--                ] 1176 of 2000 complete in 1097.1 sec
[-----------------58%--                ] 1177 of 2000 complete in 1098.0 sec
[-----------------58%--                ] 1178 of 2000 complete in 1098.9 sec
[-----------------58%--                ] 1179 of 2000 complete in 1099.8 sec
[-----------------59%--                ] 1180 of 2000 complete in 1100.7 sec
[-----------------59%--                ] 1181 of 2000 complete in 1101.6 sec
[-----------------59%--                ] 1182 of 2000 complete in 1102.5 sec
[-----------------59%--                ] 1183 of 2000 complete in 1103.3 sec
[-----------------59%--                ] 1184 of 2000 complete in 1104.2 sec
[-----------------59%--                ] 1185 of 2000 complete in 1105.1 sec
[-----------------59%--                ] 1186 of 2000 complete in 1106.0 sec
[-----------------59%--                ] 1187 of 2000 complete in 1106.9 sec
[-----------------59%--                ] 1188 of 2000 complete in 1107.8 sec
[-----------------59%--                ] 1189 of 2000 complete in 1108.7 sec
[-----------------59%--                ] 1190 of 2000 complete in 1109.6 sec
[-----------------59%--                ] 1191 of 2000 complete in 1110.5 sec
[-----------------59%--                ] 1192 of 2000 complete in 1111.4 sec
[-----------------59%--                ] 1193 of 2000 complete in 1112.3 sec
[-----------------59%--                ] 1194 of 2000 complete in 1113.3 sec
[-----------------59%--                ] 1195 of 2000 complete in 1114.1 sec
[-----------------59%--                ] 1196 of 2000 complete in 1115.1 sec
[-----------------59%--                ] 1197 of 2000 complete in 1116.0 sec
[-----------------60%--                ] 1200 of 2000 complete in 1031.2 sec
[-----------------60%--                ] 1201 of 2000 complete in 1032.2 sec
[-----------------60%--                ] 1202 of 2000 complete in 1033.1 sec
[-----------------60%--                ] 1203 of 2000 complete in 1034.0 sec
[-----------------60%--                ] 1204 of 2000 complete in 1034.9 sec
[-----------------60%--                ] 1205 of 2000 complete in 1035.8 sec
[-----------------60%--                ] 1206 of 2000 complete in 1036.7 sec
[-----------------60%--                ] 1207 of 2000 complete in 1037.6 sec
[-----------------60%--                ] 1208 of 2000 complete in 1038.5 sec
[-----------------60%--                ] 1209 of 2000 complete in 1039.5 sec
[-----------------60%--                ] 1210 of 2000 complete in 1040.4 sec
[-----------------60%---               ] 1211 of 2000 complete in 1041.3 sec
[-----------------60%---               ] 1212 of 2000 complete in 1042.3 sec
[-----------------60%---               ] 1213 of 2000 complete in 1043.2 sec
[-----------------60%---               ] 1214 of 2000 complete in 1044.2 sec
[-----------------60%---               ] 1215 of 2000 complete in 1045.1 sec
[-----------------60%---               ] 1216 of 2000 complete in 1046.1 sec
[-----------------60%---               ] 1217 of 2000 complete in 1047.0 sec
[-----------------60%---               ] 1218 of 2000 complete in 1047.9 sec
[-----------------60%---               ] 1219 of 2000 complete in 1048.8 sec
[-----------------61%---               ] 1220 of 2000 complete in 1049.7 sec
[-----------------61%---               ] 1221 of 2000 complete in 1050.7 sec
[-----------------61%---               ] 1222 of 2000 complete in 1051.6 sec
[-----------------61%---               ] 1223 of 2000 complete in 1052.5 sec
[-----------------61%---               ] 1224 of 2000 complete in 1053.5 sec
[-----------------61%---               ] 1225 of 2000 complete in 1054.4 sec
[-----------------61%---               ] 1226 of 2000 complete in 1055.3 sec
[-----------------61%---               ] 1227 of 2000 complete in 1056.2 sec
[-----------------61%---               ] 1228 of 2000 complete in 1057.1 sec
[-----------------61%---               ] 1229 of 2000 complete in 1058.0 sec
[-----------------61%---               ] 1230 of 2000 complete in 1058.9 sec
[-----------------61%---               ] 1231 of 2000 complete in 1059.7 sec
[-----------------61%---               ] 1232 of 2000 complete in 1060.6 sec
[-----------------61%---               ] 1233 of 2000 complete in 1061.5 sec
[-----------------61%---               ] 1234 of 2000 complete in 1062.4 sec
[-----------------61%---               ] 1235 of 2000 complete in 1063.4 sec
[-----------------61%---               ] 1236 of 2000 complete in 1064.3 sec
[-----------------61%---               ] 1237 of 2000 complete in 1065.2 sec
[-----------------61%---               ] 1238 of 2000 complete in 1066.2 sec
[-----------------61%---               ] 1239 of 2000 complete in 1067.1 sec
[-----------------62%---               ] 1240 of 2000 complete in 1068.0 sec
[-----------------62%---               ] 1241 of 2000 complete in 1068.9 sec
[-----------------62%---               ] 1242 of 2000 complete in 1069.8 sec
[-----------------62%---               ] 1243 of 2000 complete in 1070.7 sec
[-----------------62%---               ] 1244 of 2000 complete in 1071.6 sec
[-----------------62%---               ] 1245 of 2000 complete in 1072.5 sec
[-----------------62%---               ] 1246 of 2000 complete in 1073.4 sec
[-----------------62%---               ] 1247 of 2000 complete in 1074.3 sec
[-----------------62%---               ] 1248 of 2000 complete in 1075.2 sec
[-----------------62%---               ] 1249 of 2000 complete in 1076.1 sec
[-----------------62%---               ] 1250 of 2000 complete in 1077.0 sec
[-----------------62%---               ] 1251 of 2000 complete in 1077.9 sec
[-----------------62%---               ] 1252 of 2000 complete in 1078.8 sec
[-----------------62%---               ] 1253 of 2000 complete in 1079.7 sec
[-----------------62%---               ] 1254 of 2000 complete in 1080.6 sec
[-----------------62%---               ] 1255 of 2000 complete in 1081.4 sec
[-----------------62%---               ] 1256 of 2000 complete in 1082.4 sec
[-----------------62%---               ] 1257 of 2000 complete in 1083.3 sec
[-----------------62%---               ] 1258 of 2000 complete in 1084.2 sec
[-----------------62%---               ] 1259 of 2000 complete in 1085.1 sec
[-----------------63%---               ] 1260 of 2000 complete in 1086.0 sec
[-----------------63%---               ] 1261 of 2000 complete in 1086.9 sec
[-----------------63%---               ] 1262 of 2000 complete in 1087.7 sec
[-----------------63%---               ] 1263 of 2000 complete in 1088.6 sec
[-----------------63%----              ] 1264 of 2000 complete in 1089.5 sec
[-----------------63%----              ] 1265 of 2000 complete in 1090.4 sec
[-----------------63%----              ] 1266 of 2000 complete in 1091.3 sec
[-----------------63%----              ] 1267 of 2000 complete in 1092.2 sec
[-----------------63%----              ] 1268 of 2000 complete in 1093.1 sec
[-----------------63%----              ] 1269 of 2000 complete in 1094.0 sec
[-----------------63%----              ] 1270 of 2000 complete in 1094.9 sec
[-----------------63%----              ] 1271 of 2000 complete in 1095.7 sec
[-----------------63%----              ] 1272 of 2000 complete in 1096.6 sec
[-----------------63%----              ] 1273 of 2000 complete in 1097.5 sec
[-----------------63%----              ] 1274 of 2000 complete in 1098.4 sec
[-----------------63%----              ] 1275 of 2000 complete in 1099.3 sec
[-----------------63%----              ] 1276 of 2000 complete in 1100.2 sec
[-----------------63%----              ] 1277 of 2000 complete in 1101.2 sec
[-----------------63%----              ] 1278 of 2000 complete in 1102.1 sec
[-----------------63%----              ] 1279 of 2000 complete in 1103.0 sec
[-----------------64%----              ] 1280 of 2000 complete in 1104.0 sec
[-----------------64%----              ] 1281 of 2000 complete in 1104.9 sec
[-----------------64%----              ] 1282 of 2000 complete in 1105.9 sec
[-----------------64%----              ] 1283 of 2000 complete in 1106.9 sec
[-----------------64%----              ] 1284 of 2000 complete in 1107.8 sec
[-----------------64%----              ] 1285 of 2000 complete in 1108.8 sec
[-----------------64%----              ] 1286 of 2000 complete in 1109.8 sec
[-----------------64%----              ] 1287 of 2000 complete in 1110.7 sec
[-----------------64%----              ] 1288 of 2000 complete in 1111.7 sec
[-----------------64%----              ] 1289 of 2000 complete in 1112.6 sec
[-----------------64%----              ] 1290 of 2000 complete in 1113.6 sec
[-----------------64%----              ] 1291 of 2000 complete in 1114.5 sec
[-----------------64%----              ] 1292 of 2000 complete in 1115.5 sec
[-----------------64%----              ] 1293 of 2000 complete in 1116.5 sec
[-----------------64%----              ] 1294 of 2000 complete in 1117.4 sec
[-----------------64%----              ] 1295 of 2000 complete in 1118.4 sec
[-----------------64%----              ] 1296 of 2000 complete in 1119.3 sec
[-----------------64%----              ] 1297 of 2000 complete in 1120.2 sec
[-----------------64%----              ] 1298 of 2000 complete in 1121.1 sec
[-----------------64%----              ] 1299 of 2000 complete in 1122.1 sec
[-----------------65%----              ] 1300 of 2000 complete in 1123.0 sec
[-----------------65%----              ] 1301 of 2000 complete in 1124.0 sec
[-----------------65%----              ] 1302 of 2000 complete in 1125.0 sec
[-----------------65%----              ] 1303 of 2000 complete in 1126.0 sec
[-----------------65%----              ] 1304 of 2000 complete in 1127.0 sec
[-----------------65%----              ] 1305 of 2000 complete in 1127.9 sec

[-----------------60%--                ] 1200 of 2000 complete in 1031.9 sec
[-----------------60%--                ] 1201 of 2000 complete in 1032.8 sec
[-----------------60%--                ] 1202 of 2000 complete in 1033.7 sec
[-----------------60%--                ] 1203 of 2000 complete in 1034.6 sec
[-----------------60%--                ] 1204 of 2000 complete in 1035.5 sec
[-----------------60%--                ] 1205 of 2000 complete in 1036.5 sec
[-----------------60%--                ] 1206 of 2000 complete in 1037.4 sec
[-----------------60%--                ] 1207 of 2000 complete in 1038.3 sec
[-----------------60%--                ] 1208 of 2000 complete in 1039.3 sec
[-----------------60%--                ] 1209 of 2000 complete in 1040.2 sec
[-----------------60%--                ] 1210 of 2000 complete in 1041.1 sec
[-----------------60%---               ] 1211 of 2000 complete in 1042.0 sec
[-----------------60%---               ] 1212 of 2000 complete in 1042.9 sec
[-----------------60%---               ] 1213 of 2000 complete in 1043.8 sec
[-----------------60%---               ] 1214 of 2000 complete in 1044.8 sec
[-----------------60%---               ] 1215 of 2000 complete in 1045.8 sec
[-----------------60%---               ] 1216 of 2000 complete in 1046.6 sec
[-----------------60%---               ] 1217 of 2000 complete in 1047.5 sec
[-----------------60%---               ] 1218 of 2000 complete in 1048.4 sec
[-----------------60%---               ] 1219 of 2000 complete in 1049.3 sec
[-----------------61%---               ] 1220 of 2000 complete in 1050.2 sec
[-----------------61%---               ] 1221 of 2000 complete in 1051.1 sec
[-----------------61%---               ] 1222 of 2000 complete in 1052.0 sec
[-----------------61%---               ] 1223 of 2000 complete in 1052.9 sec
[-----------------61%---               ] 1224 of 2000 complete in 1053.8 sec
[-----------------61%---               ] 1225 of 2000 complete in 1054.7 sec
[-----------------61%---               ] 1226 of 2000 complete in 1055.6 sec
[-----------------61%---               ] 1227 of 2000 complete in 1056.5 sec
[-----------------61%---               ] 1228 of 2000 complete in 1057.5 sec
[-----------------61%---               ] 1229 of 2000 complete in 1058.4 sec
[-----------------61%---               ] 1230 of 2000 complete in 1059.4 sec
[-----------------61%---               ] 1231 of 2000 complete in 1060.3 sec
[-----------------61%---               ] 1232 of 2000 complete in 1061.3 sec
[-----------------61%---               ] 1233 of 2000 complete in 1062.3 sec
[-----------------61%---               ] 1234 of 2000 complete in 1063.3 sec
[-----------------61%---               ] 1235 of 2000 complete in 1064.2 sec
[-----------------61%---               ] 1236 of 2000 complete in 1065.2 sec
[-----------------61%---               ] 1237 of 2000 complete in 1066.2 sec
[-----------------61%---               ] 1238 of 2000 complete in 1067.2 sec
[-----------------61%---               ] 1239 of 2000 complete in 1068.2 sec
[-----------------62%---               ] 1240 of 2000 complete in 1069.2 sec
[-----------------62%---               ] 1241 of 2000 complete in 1070.2 sec
[-----------------62%---               ] 1242 of 2000 complete in 1071.2 sec
[-----------------62%---               ] 1243 of 2000 complete in 1072.1 sec
[-----------------62%---               ] 1244 of 2000 complete in 1073.1 sec
[-----------------62%---               ] 1245 of 2000 complete in 1074.1 sec
[-----------------62%---               ] 1246 of 2000 complete in 1075.0 sec
[-----------------62%---               ] 1247 of 2000 complete in 1076.0 sec
[-----------------62%---               ] 1248 of 2000 complete in 1076.9 sec
[-----------------62%---               ] 1249 of 2000 complete in 1077.9 sec
[-----------------62%---               ] 1250 of 2000 complete in 1078.9 sec
[-----------------62%---               ] 1251 of 2000 complete in 1079.9 sec
[-----------------62%---               ] 1252 of 2000 complete in 1080.9 sec
[-----------------62%---               ] 1253 of 2000 complete in 1081.9 sec
[-----------------62%---               ] 1254 of 2000 complete in 1082.8 sec
[-----------------62%---               ] 1255 of 2000 complete in 1083.8 sec
[-----------------62%---               ] 1256 of 2000 complete in 1084.8 sec
[-----------------62%---               ] 1257 of 2000 complete in 1085.8 sec
[-----------------62%---               ] 1258 of 2000 complete in 1086.7 sec
[-----------------62%---               ] 1259 of 2000 complete in 1087.7 sec
[-----------------63%---               ] 1260 of 2000 complete in 1088.7 sec
[-----------------63%---               ] 1261 of 2000 complete in 1089.7 sec
[-----------------63%---               ] 1262 of 2000 complete in 1090.6 sec
[-----------------63%---               ] 1263 of 2000 complete in 1091.5 sec
[-----------------63%----              ] 1264 of 2000 complete in 1092.5 sec
[-----------------63%----              ] 1265 of 2000 complete in 1093.5 sec
[-----------------63%----              ] 1266 of 2000 complete in 1094.4 sec
[-----------------63%----              ] 1267 of 2000 complete in 1095.4 sec
[-----------------63%----              ] 1268 of 2000 complete in 1096.4 sec
[-----------------63%----              ] 1269 of 2000 complete in 1097.4 sec
[-----------------63%----              ] 1270 of 2000 complete in 1098.4 sec
[-----------------63%----              ] 1271 of 2000 complete in 1099.4 sec
[-----------------63%----              ] 1272 of 2000 complete in 1100.4 sec
[-----------------63%----              ] 1273 of 2000 complete in 1101.4 sec
[-----------------63%----              ] 1274 of 2000 complete in 1102.3 sec
[-----------------63%----              ] 1275 of 2000 complete in 1103.4 sec
[-----------------63%----              ] 1276 of 2000 complete in 1104.4 sec
[-----------------63%----              ] 1277 of 2000 complete in 1105.4 sec
[-----------------63%----              ] 1278 of 2000 complete in 1106.4 sec
[-----------------63%----              ] 1279 of 2000 complete in 1107.4 sec
[-----------------64%----              ] 1280 of 2000 complete in 1108.3 sec
[-----------------64%----              ] 1281 of 2000 complete in 1109.2 sec
[-----------------64%----              ] 1282 of 2000 complete in 1110.1 sec
[-----------------64%----              ] 1283 of 2000 complete in 1111.1 sec
[-----------------64%----              ] 1284 of 2000 complete in 1112.0 sec
[-----------------64%----              ] 1285 of 2000 complete in 1112.9 sec
[-----------------64%----              ] 1286 of 2000 complete in 1113.8 sec
[-----------------64%----              ] 1287 of 2000 complete in 1114.7 sec
[-----------------64%----              ] 1288 of 2000 complete in 1115.5 sec
[-----------------64%----              ] 1289 of 2000 complete in 1116.4 sec
[-----------------64%----              ] 1290 of 2000 complete in 1117.3 sec
[-----------------64%----              ] 1291 of 2000 complete in 1118.2 sec
[-----------------64%----              ] 1292 of 2000 complete in 1119.1 sec
[-----------------64%----              ] 1293 of 2000 complete in 1120.0 sec
[-----------------64%----              ] 1294 of 2000 complete in 1120.8 sec
[-----------------64%----              ] 1295 of 2000 complete in 1121.7 sec
[-----------------64%----              ] 1296 of 2000 complete in 1122.5 sec
[-----------------64%----              ] 1297 of 2000 complete in 1123.4 sec
[-----------------64%----              ] 1298 of 2000 complete in 1124.3 sec
[-----------------64%----              ] 1299 of 2000 complete in 1125.2 sec
[-----------------65%----              ] 1300 of 2000 complete in 1126.2 sec
[-----------------65%----              ] 1301 of 2000 complete in 1127.0 sec
[-----------------65%----              ] 1302 of 2000 complete in 1127.9 sec
[-----------------65%----              ] 1303 of 2000 complete in 1128.8 sec
[-----------------65%----              ] 1304 of 2000 complete in 1129.7 sec
[-----------------65%----              ] 1305 of 2000 complete in 1130.5 sec
[-----------------59%--                ] 1198 of 2000 complete in 1099.6 sec
[-----------------59%--                ] 1199 of 2000 complete in 1100.6 sec
[-----------------60%--                ] 1200 of 2000 complete in 1101.6 sec
[-----------------60%--                ] 1201 of 2000 complete in 1102.6 sec
[-----------------60%--                ] 1202 of 2000 complete in 1103.5 sec
[-----------------60%--                ] 1203 of 2000 complete in 1104.5 sec
[-----------------60%--                ] 1204 of 2000 complete in 1105.5 sec
[-----------------60%--                ] 1205 of 2000 complete in 1106.6 sec
[-----------------60%--                ] 1206 of 2000 complete in 1107.6 sec
[-----------------60%--                ] 1207 of 2000 complete in 1108.6 sec
[-----------------60%--                ] 1208 of 2000 complete in 1109.6 sec
[-----------------60%--                ] 1209 of 2000 complete in 1110.6 sec
[-----------------60%--                ] 1210 of 2000 complete in 1111.5 sec
[-----------------60%---               ] 1211 of 2000 complete in 1112.5 sec
[-----------------60%---               ] 1212 of 2000 complete in 1113.5 sec
[-----------------60%---               ] 1213 of 2000 complete in 1114.5 sec
[-----------------60%---               ] 1214 of 2000 complete in 1115.5 sec
[-----------------60%---               ] 1215 of 2000 complete in 1116.5 sec
[-----------------60%---               ] 1216 of 2000 complete in 1117.6 sec
[-----------------60%---               ] 1217 of 2000 complete in 1118.6 sec
[-----------------60%---               ] 1218 of 2000 complete in 1119.7 sec
[-----------------60%---               ] 1219 of 2000 complete in 1120.7 sec
[-----------------61%---               ] 1220 of 2000 complete in 1121.7 sec
[-----------------61%---               ] 1221 of 2000 complete in 1122.7 sec
[-----------------61%---               ] 1222 of 2000 complete in 1123.7 sec
[-----------------61%---               ] 1223 of 2000 complete in 1124.7 sec
[-----------------61%---               ] 1224 of 2000 complete in 1125.8 sec
[-----------------61%---               ] 1225 of 2000 complete in 1126.8 sec
[-----------------61%---               ] 1226 of 2000 complete in 1127.7 sec
[-----------------61%---               ] 1227 of 2000 complete in 1128.7 sec
[-----------------61%---               ] 1228 of 2000 complete in 1129.6 sec
[-----------------61%---               ] 1229 of 2000 complete in 1130.6 sec
[-----------------61%---               ] 1230 of 2000 complete in 1131.5 sec
[-----------------61%---               ] 1231 of 2000 complete in 1132.4 sec
[-----------------61%---               ] 1232 of 2000 complete in 1133.4 sec
[-----------------61%---               ] 1233 of 2000 complete in 1134.3 sec
[-----------------61%---               ] 1234 of 2000 complete in 1135.2 sec
[-----------------61%---               ] 1235 of 2000 complete in 1136.2 sec
[-----------------61%---               ] 1236 of 2000 complete in 1137.1 sec
[-----------------61%---               ] 1237 of 2000 complete in 1138.1 sec
[-----------------61%---               ] 1238 of 2000 complete in 1139.0 sec
[-----------------61%---               ] 1239 of 2000 complete in 1139.9 sec
[-----------------62%---               ] 1240 of 2000 complete in 1140.8 sec
[-----------------62%---               ] 1241 of 2000 complete in 1141.7 sec
[-----------------62%---               ] 1242 of 2000 complete in 1142.6 sec
[-----------------62%---               ] 1243 of 2000 complete in 1143.6 sec
[-----------------62%---               ] 1244 of 2000 complete in 1144.5 sec
[-----------------62%---               ] 1245 of 2000 complete in 1145.4 sec
[-----------------62%---               ] 1246 of 2000 complete in 1146.4 sec
[-----------------62%---               ] 1247 of 2000 complete in 1147.3 sec
[-----------------62%---               ] 1248 of 2000 complete in 1148.3 sec
[-----------------62%---               ] 1249 of 2000 complete in 1149.2 sec
[-----------------62%---               ] 1250 of 2000 complete in 1150.1 sec
[-----------------62%---               ] 1251 of 2000 complete in 1151.0 sec
[-----------------62%---               ] 1252 of 2000 complete in 1151.9 sec
[-----------------62%---               ] 1253 of 2000 complete in 1152.9 sec
[-----------------62%---               ] 1254 of 2000 complete in 1153.8 sec
[-----------------62%---               ] 1255 of 2000 complete in 1154.7 sec
[-----------------62%---               ] 1256 of 2000 complete in 1155.6 sec
[-----------------62%---               ] 1257 of 2000 complete in 1156.5 sec
[-----------------62%---               ] 1258 of 2000 complete in 1157.4 sec
[-----------------62%---               ] 1259 of 2000 complete in 1158.4 sec
[-----------------63%---               ] 1260 of 2000 complete in 1159.3 sec
[-----------------63%---               ] 1261 of 2000 complete in 1160.3 sec
[-----------------63%---               ] 1262 of 2000 complete in 1161.3 sec
[-----------------63%---               ] 1263 of 2000 complete in 1162.3 sec
[-----------------63%----              ] 1264 of 2000 complete in 1163.3 sec
[-----------------63%----              ] 1265 of 2000 complete in 1164.2 sec
[-----------------63%----              ] 1266 of 2000 complete in 1165.2 sec
[-----------------63%----              ] 1267 of 2000 complete in 1166.2 sec
[-----------------63%----              ] 1268 of 2000 complete in 1167.1 sec
[-----------------63%----              ] 1269 of 2000 complete in 1168.0 sec
[-----------------63%----              ] 1270 of 2000 complete in 1168.9 sec
[-----------------63%----              ] 1271 of 2000 complete in 1169.8 sec
[-----------------63%----              ] 1272 of 2000 complete in 1170.8 sec
[-----------------63%----              ] 1273 of 2000 complete in 1171.7 sec
[-----------------63%----              ] 1274 of 2000 complete in 1172.6 sec
[-----------------63%----              ] 1275 of 2000 complete in 1173.6 sec
[-----------------63%----              ] 1276 of 2000 complete in 1174.5 sec
[-----------------63%----              ] 1277 of 2000 complete in 1175.5 sec
[-----------------63%----              ] 1278 of 2000 complete in 1176.4 sec
[-----------------63%----              ] 1279 of 2000 complete in 1177.3 sec
[-----------------64%----              ] 1280 of 2000 complete in 1178.3 sec
[-----------------64%----              ] 1281 of 2000 complete in 1179.2 sec
[-----------------64%----              ] 1282 of 2000 complete in 1180.1 sec
[-----------------64%----              ] 1283 of 2000 complete in 1181.0 sec
[-----------------64%----              ] 1284 of 2000 complete in 1181.9 sec
[-----------------64%----              ] 1285 of 2000 complete in 1182.8 sec
[-----------------64%----              ] 1286 of 2000 complete in 1183.8 sec
[-----------------64%----              ] 1287 of 2000 complete in 1184.8 sec
[-----------------64%----              ] 1288 of 2000 complete in 1185.7 sec
[-----------------64%----              ] 1289 of 2000 complete in 1186.6 sec
[-----------------64%----              ] 1290 of 2000 complete in 1187.6 sec
[-----------------64%----              ] 1291 of 2000 complete in 1188.5 sec
[-----------------64%----              ] 1292 of 2000 complete in 1189.4 sec
[-----------------64%----              ] 1293 of 2000 complete in 1190.3 sec
[-----------------64%----              ] 1294 of 2000 complete in 1191.3 sec
[-----------------64%----              ] 1295 of 2000 complete in 1192.2 sec
[-----------------64%----              ] 1296 of 2000 complete in 1193.1 sec
[-----------------64%----              ] 1297 of 2000 complete in 1194.1 sec
[-----------------64%----              ] 1298 of 2000 complete in 1195.0 sec
[-----------------64%----              ] 1299 of 2000 complete in 1196.0 sec
[-----------------65%----              ] 1300 of 2000 complete in 1196.9 sec
[-----------------65%----              ] 1301 of 2000 complete in 1197.9 sec
[-----------------65%----              ] 1302 of 2000 complete in 1198.8 sec
[-----------------65%----              ] 1303 of 2000 complete in 1199.7 sec

[-----------------59%--                ] 1198 of 2000 complete in 1116.8 sec
[-----------------59%--                ] 1199 of 2000 complete in 1117.7 sec
[-----------------60%--                ] 1200 of 2000 complete in 1118.6 sec
[-----------------60%--                ] 1201 of 2000 complete in 1119.5 sec
[-----------------60%--                ] 1202 of 2000 complete in 1120.4 sec
[-----------------60%--                ] 1203 of 2000 complete in 1121.3 sec
[-----------------60%--                ] 1204 of 2000 complete in 1122.2 sec
[-----------------60%--                ] 1205 of 2000 complete in 1123.1 sec
[-----------------60%--                ] 1206 of 2000 complete in 1124.0 sec
[-----------------60%--                ] 1207 of 2000 complete in 1124.9 sec
[-----------------60%--                ] 1208 of 2000 complete in 1125.9 sec
[-----------------60%--                ] 1209 of 2000 complete in 1126.8 sec
[-----------------60%--                ] 1210 of 2000 complete in 1127.7 sec
[-----------------60%---               ] 1211 of 2000 complete in 1128.6 sec
[-----------------60%---               ] 1212 of 2000 complete in 1129.5 sec
[-----------------60%---               ] 1213 of 2000 complete in 1130.4 sec
[-----------------60%---               ] 1214 of 2000 complete in 1131.3 sec
[-----------------60%---               ] 1215 of 2000 complete in 1132.3 sec
[-----------------60%---               ] 1216 of 2000 complete in 1133.2 sec
[-----------------60%---               ] 1217 of 2000 complete in 1134.1 sec
[-----------------60%---               ] 1218 of 2000 complete in 1135.1 sec
[-----------------60%---               ] 1219 of 2000 complete in 1136.1 sec
[-----------------61%---               ] 1220 of 2000 complete in 1137.0 sec
[-----------------61%---               ] 1221 of 2000 complete in 1137.8 sec
[-----------------61%---               ] 1222 of 2000 complete in 1138.8 sec
[-----------------61%---               ] 1223 of 2000 complete in 1139.7 sec
[-----------------61%---               ] 1224 of 2000 complete in 1140.7 sec
[-----------------61%---               ] 1225 of 2000 complete in 1141.6 sec
[-----------------61%---               ] 1226 of 2000 complete in 1142.5 sec
[-----------------61%---               ] 1227 of 2000 complete in 1143.4 sec
[-----------------61%---               ] 1228 of 2000 complete in 1144.4 sec
[-----------------61%---               ] 1229 of 2000 complete in 1145.3 sec
[-----------------61%---               ] 1230 of 2000 complete in 1146.2 sec
[-----------------61%---               ] 1231 of 2000 complete in 1147.1 sec
[-----------------61%---               ] 1232 of 2000 complete in 1148.1 sec
[-----------------61%---               ] 1233 of 2000 complete in 1149.0 sec
[-----------------61%---               ] 1234 of 2000 complete in 1149.9 sec
[-----------------61%---               ] 1235 of 2000 complete in 1150.8 sec
[-----------------61%---               ] 1236 of 2000 complete in 1151.7 sec
[-----------------61%---               ] 1237 of 2000 complete in 1152.5 sec
[-----------------61%---               ] 1238 of 2000 complete in 1153.4 sec
[-----------------61%---               ] 1239 of 2000 complete in 1154.2 sec
[-----------------62%---               ] 1240 of 2000 complete in 1155.1 sec
[-----------------62%---               ] 1241 of 2000 complete in 1155.9 sec
[-----------------62%---               ] 1242 of 2000 complete in 1156.8 sec
[-----------------62%---               ] 1243 of 2000 complete in 1157.6 sec
[-----------------62%---               ] 1244 of 2000 complete in 1158.5 sec
[-----------------62%---               ] 1245 of 2000 complete in 1159.3 sec
[-----------------62%---               ] 1246 of 2000 complete in 1160.3 sec
[-----------------62%---               ] 1247 of 2000 complete in 1161.2 sec
[-----------------62%---               ] 1248 of 2000 complete in 1162.2 sec
[-----------------62%---               ] 1249 of 2000 complete in 1163.1 sec
[-----------------62%---               ] 1250 of 2000 complete in 1163.9 sec
[-----------------62%---               ] 1251 of 2000 complete in 1164.8 sec
[-----------------62%---               ] 1252 of 2000 complete in 1165.7 sec
[-----------------62%---               ] 1253 of 2000 complete in 1166.6 sec
[-----------------62%---               ] 1254 of 2000 complete in 1167.4 sec
[-----------------62%---               ] 1255 of 2000 complete in 1168.3 sec
[-----------------62%---               ] 1256 of 2000 complete in 1169.2 sec
[-----------------62%---               ] 1257 of 2000 complete in 1170.1 sec
[-----------------62%---               ] 1258 of 2000 complete in 1170.9 sec
[-----------------62%---               ] 1259 of 2000 complete in 1171.7 sec
[-----------------63%---               ] 1260 of 2000 complete in 1172.6 sec
[-----------------63%---               ] 1261 of 2000 complete in 1173.5 sec
[-----------------63%---               ] 1262 of 2000 complete in 1174.4 sec
[-----------------63%---               ] 1263 of 2000 complete in 1175.3 sec
[-----------------63%----              ] 1264 of 2000 complete in 1176.2 sec
[-----------------63%----              ] 1265 of 2000 complete in 1177.1 sec
[-----------------63%----              ] 1266 of 2000 complete in 1177.9 sec
[-----------------63%----              ] 1267 of 2000 complete in 1178.9 sec
[-----------------63%----              ] 1268 of 2000 complete in 1179.8 sec
[-----------------63%----              ] 1269 of 2000 complete in 1180.7 sec
[-----------------63%----              ] 1270 of 2000 complete in 1181.6 sec
[-----------------63%----              ] 1271 of 2000 complete in 1182.5 sec
[-----------------63%----              ] 1272 of 2000 complete in 1183.4 sec
[-----------------63%----              ] 1273 of 2000 complete in 1184.3 sec
[-----------------63%----              ] 1274 of 2000 complete in 1185.1 sec
[-----------------63%----              ] 1275 of 2000 complete in 1186.0 sec
[-----------------63%----              ] 1276 of 2000 complete in 1186.8 sec
[-----------------63%----              ] 1277 of 2000 complete in 1187.7 sec
[-----------------63%----              ] 1278 of 2000 complete in 1188.5 sec
[-----------------63%----              ] 1279 of 2000 complete in 1189.4 sec
[-----------------64%----              ] 1280 of 2000 complete in 1190.2 sec
[-----------------64%----              ] 1281 of 2000 complete in 1191.0 sec
[-----------------64%----              ] 1282 of 2000 complete in 1191.9 sec
[-----------------64%----              ] 1283 of 2000 complete in 1192.7 sec
[-----------------64%----              ] 1284 of 2000 complete in 1193.6 sec
[-----------------64%----              ] 1285 of 2000 complete in 1194.4 sec
[-----------------64%----              ] 1286 of 2000 complete in 1195.3 sec
[-----------------64%----              ] 1287 of 2000 complete in 1196.2 sec
[-----------------64%----              ] 1288 of 2000 complete in 1197.0 sec
[-----------------64%----              ] 1289 of 2000 complete in 1197.9 sec
[-----------------64%----              ] 1290 of 2000 complete in 1198.7 sec
[-----------------64%----              ] 1291 of 2000 complete in 1199.6 sec
[-----------------64%----              ] 1292 of 2000 complete in 1200.5 sec
[-----------------64%----              ] 1293 of 2000 complete in 1201.4 sec
[-----------------64%----              ] 1294 of 2000 complete in 1202.3 sec
[-----------------64%----              ] 1295 of 2000 complete in 1203.2 sec
[-----------------64%----              ] 1296 of 2000 complete in 1204.1 sec
[-----------------64%----              ] 1297 of 2000 complete in 1205.0 sec
[-----------------64%----              ] 1298 of 2000 complete in 1205.9 sec
[-----------------64%----              ] 1299 of 2000 complete in 1206.9 sec
[-----------------65%----              ] 1300 of 2000 complete in 1207.8 sec
[-----------------65%----              ] 1301 of 2000 complete in 1208.7 sec
[-----------------65%----              ] 1302 of 2000 complete in 1209.6 sec
[-----------------65%----              ] 1303 of 2000 complete in 1210.5 sec
[-----------------65%----              ] 1306 of 2000 complete in 1128.9 sec
[-----------------65%----              ] 1307 of 2000 complete in 1129.8 sec
[-----------------65%----              ] 1308 of 2000 complete in 1130.8 sec
[-----------------65%----              ] 1309 of 2000 complete in 1131.7 sec
[-----------------65%----              ] 1310 of 2000 complete in 1132.7 sec
[-----------------65%----              ] 1311 of 2000 complete in 1133.6 sec
[-----------------65%----              ] 1312 of 2000 complete in 1134.6 sec
[-----------------65%----              ] 1313 of 2000 complete in 1135.5 sec
[-----------------65%----              ] 1314 of 2000 complete in 1136.5 sec
[-----------------65%----              ] 1315 of 2000 complete in 1137.4 sec
[-----------------65%-----             ] 1316 of 2000 complete in 1138.3 sec
[-----------------65%-----             ] 1317 of 2000 complete in 1139.2 sec
[-----------------65%-----             ] 1318 of 2000 complete in 1140.1 sec
[-----------------65%-----             ] 1319 of 2000 complete in 1141.0 sec
[-----------------66%-----             ] 1320 of 2000 complete in 1141.9 sec
[-----------------66%-----             ] 1321 of 2000 complete in 1142.8 sec
[-----------------66%-----             ] 1322 of 2000 complete in 1143.7 sec
[-----------------66%-----             ] 1323 of 2000 complete in 1144.6 sec
[-----------------66%-----             ] 1324 of 2000 complete in 1145.5 sec
[-----------------66%-----             ] 1325 of 2000 complete in 1146.4 sec
[-----------------66%-----             ] 1326 of 2000 complete in 1147.3 sec
[-----------------66%-----             ] 1327 of 2000 complete in 1148.2 sec
[-----------------66%-----             ] 1328 of 2000 complete in 1149.1 sec
[-----------------66%-----             ] 1329 of 2000 complete in 1149.9 sec
[-----------------66%-----             ] 1330 of 2000 complete in 1150.8 sec
[-----------------66%-----             ] 1331 of 2000 complete in 1151.7 sec
[-----------------66%-----             ] 1332 of 2000 complete in 1152.6 sec
[-----------------66%-----             ] 1333 of 2000 complete in 1153.4 sec
[-----------------66%-----             ] 1334 of 2000 complete in 1154.3 sec
[-----------------66%-----             ] 1335 of 2000 complete in 1155.2 sec
[-----------------66%-----             ] 1336 of 2000 complete in 1156.1 sec
[-----------------66%-----             ] 1337 of 2000 complete in 1156.9 sec
[-----------------66%-----             ] 1338 of 2000 complete in 1157.8 sec
[-----------------66%-----             ] 1339 of 2000 complete in 1158.7 sec
[-----------------67%-----             ] 1340 of 2000 complete in 1159.5 sec
[-----------------67%-----             ] 1341 of 2000 complete in 1160.5 sec
[-----------------67%-----             ] 1342 of 2000 complete in 1161.5 sec
[-----------------67%-----             ] 1343 of 2000 complete in 1162.4 sec
[-----------------67%-----             ] 1344 of 2000 complete in 1163.4 sec
[-----------------67%-----             ] 1345 of 2000 complete in 1164.2 sec
[-----------------67%-----             ] 1346 of 2000 complete in 1165.2 sec
[-----------------67%-----             ] 1347 of 2000 complete in 1166.1 sec
[-----------------67%-----             ] 1348 of 2000 complete in 1167.0 sec
[-----------------67%-----             ] 1349 of 2000 complete in 1167.8 sec
[-----------------67%-----             ] 1350 of 2000 complete in 1168.8 sec
[-----------------67%-----             ] 1351 of 2000 complete in 1169.7 sec
[-----------------67%-----             ] 1352 of 2000 complete in 1170.7 sec
[-----------------67%-----             ] 1353 of 2000 complete in 1171.6 sec
[-----------------67%-----             ] 1354 of 2000 complete in 1172.5 sec
[-----------------67%-----             ] 1355 of 2000 complete in 1173.5 sec
[-----------------67%-----             ] 1356 of 2000 complete in 1174.4 sec
[-----------------67%-----             ] 1357 of 2000 complete in 1175.3 sec
[-----------------67%-----             ] 1358 of 2000 complete in 1176.3 sec
[-----------------67%-----             ] 1359 of 2000 complete in 1177.2 sec
[-----------------68%-----             ] 1360 of 2000 complete in 1178.1 sec
[-----------------68%-----             ] 1361 of 2000 complete in 1179.0 sec
[-----------------68%-----             ] 1362 of 2000 complete in 1179.9 sec
[-----------------68%-----             ] 1363 of 2000 complete in 1180.8 sec
[-----------------68%-----             ] 1364 of 2000 complete in 1181.7 sec
[-----------------68%-----             ] 1365 of 2000 complete in 1182.6 sec
[-----------------68%-----             ] 1366 of 2000 complete in 1183.5 sec
[-----------------68%-----             ] 1367 of 2000 complete in 1184.4 sec
[-----------------68%-----             ] 1368 of 2000 complete in 1185.3 sec
[-----------------68%------            ] 1369 of 2000 complete in 1186.2 sec
[-----------------68%------            ] 1370 of 2000 complete in 1187.1 sec
[-----------------68%------            ] 1371 of 2000 complete in 1187.9 sec
[-----------------68%------            ] 1372 of 2000 complete in 1188.8 sec
[-----------------68%------            ] 1373 of 2000 complete in 1189.7 sec
[-----------------68%------            ] 1374 of 2000 complete in 1190.6 sec
[-----------------68%------            ] 1375 of 2000 complete in 1191.5 sec
[-----------------68%------            ] 1376 of 2000 complete in 1192.4 sec
[-----------------68%------            ] 1377 of 2000 complete in 1193.3 sec
[-----------------68%------            ] 1378 of 2000 complete in 1194.2 sec
[-----------------68%------            ] 1379 of 2000 complete in 1195.0 sec
[-----------------69%------            ] 1380 of 2000 complete in 1195.9 sec
[-----------------69%------            ] 1381 of 2000 complete in 1196.8 sec
[-----------------69%------            ] 1382 of 2000 complete in 1197.7 sec
[-----------------69%------            ] 1383 of 2000 complete in 1198.6 sec
[-----------------69%------            ] 1384 of 2000 complete in 1199.6 sec
[-----------------69%------            ] 1385 of 2000 complete in 1200.5 sec
[-----------------69%------            ] 1386 of 2000 complete in 1201.4 sec
[-----------------69%------            ] 1387 of 2000 complete in 1202.3 sec
[-----------------69%------            ] 1388 of 2000 complete in 1203.2 sec
[-----------------69%------            ] 1389 of 2000 complete in 1204.0 sec
[-----------------69%------            ] 1390 of 2000 complete in 1204.9 sec
[-----------------69%------            ] 1391 of 2000 complete in 1205.8 sec
[-----------------69%------            ] 1392 of 2000 complete in 1206.7 sec
[-----------------69%------            ] 1393 of 2000 complete in 1207.6 sec
[-----------------69%------            ] 1394 of 2000 complete in 1208.4 sec
[-----------------69%------            ] 1395 of 2000 complete in 1209.3 sec
[-----------------69%------            ] 1396 of 2000 complete in 1210.2 sec
[-----------------69%------            ] 1397 of 2000 complete in 1211.1 sec
[-----------------69%------            ] 1398 of 2000 complete in 1212.0 sec
[-----------------69%------            ] 1399 of 2000 complete in 1212.8 sec
[-----------------70%------            ] 1400 of 2000 complete in 1213.8 sec
[-----------------70%------            ] 1401 of 2000 complete in 1214.6 sec
[-----------------70%------            ] 1402 of 2000 complete in 1215.5 sec
[-----------------70%------            ] 1403 of 2000 complete in 1216.4 sec
[-----------------70%------            ] 1404 of 2000 complete in 1217.3 sec
[-----------------70%------            ] 1405 of 2000 complete in 1218.2 sec
[-----------------70%------            ] 1406 of 2000 complete in 1219.1 sec
[-----------------70%------            ] 1407 of 2000 complete in 1220.0 sec
[-----------------70%------            ] 1408 of 2000 complete in 1220.9 sec
[-----------------70%------            ] 1409 of 2000 complete in 1221.8 sec
[-----------------70%------            ] 1410 of 2000 complete in 1222.7 sec
[-----------------70%------            ] 1411 of 2000 complete in 1223.6 sec

[-----------------65%----              ] 1306 of 2000 complete in 1131.4 sec
[-----------------65%----              ] 1307 of 2000 complete in 1132.3 sec
[-----------------65%----              ] 1308 of 2000 complete in 1133.2 sec
[-----------------65%----              ] 1309 of 2000 complete in 1134.0 sec
[-----------------65%----              ] 1310 of 2000 complete in 1134.9 sec
[-----------------65%----              ] 1311 of 2000 complete in 1135.8 sec
[-----------------65%----              ] 1312 of 2000 complete in 1136.8 sec
[-----------------65%----              ] 1313 of 2000 complete in 1137.7 sec
[-----------------65%----              ] 1314 of 2000 complete in 1138.6 sec
[-----------------65%----              ] 1315 of 2000 complete in 1139.6 sec
[-----------------65%-----             ] 1316 of 2000 complete in 1140.5 sec
[-----------------65%-----             ] 1317 of 2000 complete in 1141.4 sec
[-----------------65%-----             ] 1318 of 2000 complete in 1142.3 sec
[-----------------65%-----             ] 1319 of 2000 complete in 1143.2 sec
[-----------------66%-----             ] 1320 of 2000 complete in 1144.2 sec
[-----------------66%-----             ] 1321 of 2000 complete in 1145.1 sec
[-----------------66%-----             ] 1322 of 2000 complete in 1146.0 sec
[-----------------66%-----             ] 1323 of 2000 complete in 1146.9 sec
[-----------------66%-----             ] 1324 of 2000 complete in 1147.9 sec
[-----------------66%-----             ] 1325 of 2000 complete in 1148.8 sec
[-----------------66%-----             ] 1326 of 2000 complete in 1149.7 sec
[-----------------66%-----             ] 1327 of 2000 complete in 1150.7 sec
[-----------------66%-----             ] 1328 of 2000 complete in 1151.7 sec
[-----------------66%-----             ] 1329 of 2000 complete in 1152.7 sec
[-----------------66%-----             ] 1330 of 2000 complete in 1153.7 sec
[-----------------66%-----             ] 1331 of 2000 complete in 1154.7 sec
[-----------------66%-----             ] 1332 of 2000 complete in 1155.8 sec
[-----------------66%-----             ] 1333 of 2000 complete in 1156.8 sec
[-----------------66%-----             ] 1334 of 2000 complete in 1157.9 sec
[-----------------66%-----             ] 1335 of 2000 complete in 1158.9 sec
[-----------------66%-----             ] 1336 of 2000 complete in 1159.9 sec
[-----------------66%-----             ] 1337 of 2000 complete in 1160.9 sec
[-----------------66%-----             ] 1338 of 2000 complete in 1162.1 sec
[-----------------66%-----             ] 1339 of 2000 complete in 1163.1 sec
[-----------------67%-----             ] 1340 of 2000 complete in 1164.1 sec
[-----------------67%-----             ] 1341 of 2000 complete in 1165.0 sec
[-----------------67%-----             ] 1342 of 2000 complete in 1166.1 sec
[-----------------67%-----             ] 1343 of 2000 complete in 1167.1 sec
[-----------------67%-----             ] 1344 of 2000 complete in 1168.1 sec
[-----------------67%-----             ] 1345 of 2000 complete in 1169.0 sec
[-----------------67%-----             ] 1346 of 2000 complete in 1170.0 sec
[-----------------67%-----             ] 1347 of 2000 complete in 1170.9 sec
[-----------------67%-----             ] 1348 of 2000 complete in 1171.8 sec
[-----------------67%-----             ] 1349 of 2000 complete in 1172.7 sec
[-----------------67%-----             ] 1350 of 2000 complete in 1173.7 sec
[-----------------67%-----             ] 1351 of 2000 complete in 1174.6 sec
[-----------------67%-----             ] 1352 of 2000 complete in 1175.5 sec
[-----------------67%-----             ] 1353 of 2000 complete in 1176.4 sec
[-----------------67%-----             ] 1354 of 2000 complete in 1177.4 sec
[-----------------67%-----             ] 1355 of 2000 complete in 1178.3 sec
[-----------------67%-----             ] 1356 of 2000 complete in 1179.3 sec
[-----------------67%-----             ] 1357 of 2000 complete in 1180.1 sec
[-----------------67%-----             ] 1358 of 2000 complete in 1181.1 sec
[-----------------67%-----             ] 1359 of 2000 complete in 1182.0 sec
[-----------------68%-----             ] 1360 of 2000 complete in 1182.8 sec
[-----------------68%-----             ] 1361 of 2000 complete in 1183.7 sec
[-----------------68%-----             ] 1362 of 2000 complete in 1184.6 sec
[-----------------68%-----             ] 1363 of 2000 complete in 1185.5 sec
[-----------------68%-----             ] 1364 of 2000 complete in 1186.4 sec
[-----------------68%-----             ] 1365 of 2000 complete in 1187.2 sec
[-----------------68%-----             ] 1366 of 2000 complete in 1188.1 sec
[-----------------68%-----             ] 1367 of 2000 complete in 1189.0 sec
[-----------------68%-----             ] 1368 of 2000 complete in 1189.9 sec
[-----------------68%------            ] 1369 of 2000 complete in 1190.8 sec
[-----------------68%------            ] 1370 of 2000 complete in 1191.6 sec
[-----------------68%------            ] 1371 of 2000 complete in 1192.4 sec
[-----------------68%------            ] 1372 of 2000 complete in 1193.3 sec
[-----------------68%------            ] 1373 of 2000 complete in 1194.1 sec
[-----------------68%------            ] 1374 of 2000 complete in 1194.9 sec
[-----------------68%------            ] 1375 of 2000 complete in 1195.7 sec
[-----------------68%------            ] 1376 of 2000 complete in 1196.6 sec
[-----------------68%------            ] 1377 of 2000 complete in 1197.4 sec
[-----------------68%------            ] 1378 of 2000 complete in 1198.3 sec
[-----------------68%------            ] 1379 of 2000 complete in 1199.1 sec
[-----------------69%------            ] 1380 of 2000 complete in 1200.0 sec
[-----------------69%------            ] 1381 of 2000 complete in 1200.9 sec
[-----------------69%------            ] 1382 of 2000 complete in 1201.7 sec
[-----------------69%------            ] 1383 of 2000 complete in 1202.6 sec
[-----------------69%------            ] 1384 of 2000 complete in 1203.4 sec
[-----------------69%------            ] 1385 of 2000 complete in 1204.3 sec
[-----------------69%------            ] 1386 of 2000 complete in 1205.2 sec
[-----------------69%------            ] 1387 of 2000 complete in 1206.0 sec
[-----------------69%------            ] 1388 of 2000 complete in 1206.9 sec
[-----------------69%------            ] 1389 of 2000 complete in 1207.8 sec
[-----------------69%------            ] 1390 of 2000 complete in 1208.6 sec
[-----------------69%------            ] 1391 of 2000 complete in 1209.5 sec
[-----------------69%------            ] 1392 of 2000 complete in 1210.4 sec
[-----------------69%------            ] 1393 of 2000 complete in 1211.3 sec
[-----------------69%------            ] 1394 of 2000 complete in 1212.3 sec
[-----------------69%------            ] 1395 of 2000 complete in 1213.2 sec
[-----------------69%------            ] 1396 of 2000 complete in 1214.1 sec
[-----------------69%------            ] 1397 of 2000 complete in 1215.1 sec
[-----------------69%------            ] 1398 of 2000 complete in 1216.0 sec
[-----------------69%------            ] 1399 of 2000 complete in 1216.9 sec
[-----------------70%------            ] 1400 of 2000 complete in 1217.8 sec
[-----------------70%------            ] 1401 of 2000 complete in 1218.7 sec
[-----------------70%------            ] 1402 of 2000 complete in 1219.6 sec
[-----------------70%------            ] 1403 of 2000 complete in 1220.5 sec
[-----------------70%------            ] 1404 of 2000 complete in 1221.4 sec
[-----------------70%------            ] 1405 of 2000 complete in 1222.2 sec
[-----------------70%------            ] 1406 of 2000 complete in 1223.1 sec
[-----------------70%------            ] 1407 of 2000 complete in 1223.9 sec
[-----------------70%------            ] 1408 of 2000 complete in 1224.7 sec
[-----------------70%------            ] 1409 of 2000 complete in 1225.6 sec
[-----------------70%------            ] 1410 of 2000 complete in 1226.5 sec
[-----------------70%------            ] 1411 of 2000 complete in 1227.3 sec
[-----------------65%----              ] 1304 of 2000 complete in 1200.7 sec
[-----------------65%----              ] 1305 of 2000 complete in 1201.7 sec
[-----------------65%----              ] 1306 of 2000 complete in 1202.8 sec
[-----------------65%----              ] 1307 of 2000 complete in 1203.8 sec
[-----------------65%----              ] 1308 of 2000 complete in 1204.8 sec
[-----------------65%----              ] 1309 of 2000 complete in 1205.7 sec
[-----------------65%----              ] 1310 of 2000 complete in 1206.7 sec
[-----------------65%----              ] 1311 of 2000 complete in 1207.6 sec
[-----------------65%----              ] 1312 of 2000 complete in 1208.6 sec
[-----------------65%----              ] 1313 of 2000 complete in 1209.6 sec
[-----------------65%----              ] 1314 of 2000 complete in 1210.5 sec
[-----------------65%----              ] 1315 of 2000 complete in 1211.4 sec
[-----------------65%-----             ] 1316 of 2000 complete in 1212.3 sec
[-----------------65%-----             ] 1317 of 2000 complete in 1213.2 sec
[-----------------65%-----             ] 1318 of 2000 complete in 1214.0 sec
[-----------------65%-----             ] 1319 of 2000 complete in 1214.9 sec
[-----------------66%-----             ] 1320 of 2000 complete in 1215.7 sec
[-----------------66%-----             ] 1321 of 2000 complete in 1216.6 sec
[-----------------66%-----             ] 1322 of 2000 complete in 1217.5 sec
[-----------------66%-----             ] 1323 of 2000 complete in 1218.3 sec
[-----------------66%-----             ] 1324 of 2000 complete in 1219.2 sec
[-----------------66%-----             ] 1325 of 2000 complete in 1220.0 sec
[-----------------66%-----             ] 1326 of 2000 complete in 1220.9 sec
[-----------------66%-----             ] 1327 of 2000 complete in 1221.8 sec
[-----------------66%-----             ] 1328 of 2000 complete in 1222.6 sec
[-----------------66%-----             ] 1329 of 2000 complete in 1223.5 sec
[-----------------66%-----             ] 1330 of 2000 complete in 1224.3 sec
[-----------------66%-----             ] 1331 of 2000 complete in 1225.1 sec
[-----------------66%-----             ] 1332 of 2000 complete in 1226.0 sec
[-----------------66%-----             ] 1333 of 2000 complete in 1226.8 sec
[-----------------66%-----             ] 1334 of 2000 complete in 1227.7 sec
[-----------------66%-----             ] 1335 of 2000 complete in 1228.5 sec
[-----------------66%-----             ] 1336 of 2000 complete in 1229.4 sec
[-----------------66%-----             ] 1337 of 2000 complete in 1230.2 sec
[-----------------66%-----             ] 1338 of 2000 complete in 1231.1 sec
[-----------------66%-----             ] 1339 of 2000 complete in 1232.0 sec
[-----------------67%-----             ] 1340 of 2000 complete in 1232.9 sec
[-----------------67%-----             ] 1341 of 2000 complete in 1233.7 sec
[-----------------67%-----             ] 1342 of 2000 complete in 1234.6 sec
[-----------------67%-----             ] 1343 of 2000 complete in 1235.5 sec
[-----------------67%-----             ] 1344 of 2000 complete in 1236.4 sec
[-----------------67%-----             ] 1345 of 2000 complete in 1237.3 sec
[-----------------67%-----             ] 1346 of 2000 complete in 1238.1 sec
[-----------------67%-----             ] 1347 of 2000 complete in 1239.1 sec
[-----------------67%-----             ] 1348 of 2000 complete in 1240.0 sec
[-----------------67%-----             ] 1349 of 2000 complete in 1240.9 sec
[-----------------67%-----             ] 1350 of 2000 complete in 1241.9 sec
[-----------------67%-----             ] 1351 of 2000 complete in 1242.8 sec
[-----------------67%-----             ] 1352 of 2000 complete in 1243.7 sec
[-----------------67%-----             ] 1353 of 2000 complete in 1244.7 sec
[-----------------67%-----             ] 1354 of 2000 complete in 1245.6 sec
[-----------------67%-----             ] 1355 of 2000 complete in 1246.5 sec
[-----------------67%-----             ] 1356 of 2000 complete in 1247.4 sec
[-----------------67%-----             ] 1357 of 2000 complete in 1248.3 sec
[-----------------67%-----             ] 1358 of 2000 complete in 1249.2 sec
[-----------------67%-----             ] 1359 of 2000 complete in 1250.2 sec
[-----------------68%-----             ] 1360 of 2000 complete in 1251.1 sec
[-----------------68%-----             ] 1361 of 2000 complete in 1252.0 sec
[-----------------68%-----             ] 1362 of 2000 complete in 1252.9 sec
[-----------------68%-----             ] 1363 of 2000 complete in 1253.8 sec
[-----------------68%-----             ] 1364 of 2000 complete in 1254.8 sec
[-----------------68%-----             ] 1365 of 2000 complete in 1255.6 sec
[-----------------68%-----             ] 1366 of 2000 complete in 1256.6 sec
[-----------------68%-----             ] 1367 of 2000 complete in 1257.4 sec
[-----------------68%-----             ] 1368 of 2000 complete in 1258.3 sec
[-----------------68%------            ] 1369 of 2000 complete in 1259.2 sec
[-----------------68%------            ] 1370 of 2000 complete in 1260.2 sec
[-----------------68%------            ] 1371 of 2000 complete in 1261.1 sec
[-----------------68%------            ] 1372 of 2000 complete in 1262.0 sec
[-----------------68%------            ] 1373 of 2000 complete in 1263.0 sec
[-----------------68%------            ] 1374 of 2000 complete in 1264.0 sec
[-----------------68%------            ] 1375 of 2000 complete in 1264.9 sec
[-----------------68%------            ] 1376 of 2000 complete in 1265.9 sec
[-----------------68%------            ] 1377 of 2000 complete in 1267.0 sec
[-----------------68%------            ] 1378 of 2000 complete in 1267.9 sec
[-----------------68%------            ] 1379 of 2000 complete in 1268.9 sec
[-----------------69%------            ] 1380 of 2000 complete in 1269.8 sec
[-----------------69%------            ] 1381 of 2000 complete in 1270.9 sec
[-----------------69%------            ] 1382 of 2000 complete in 1271.9 sec
[-----------------69%------            ] 1383 of 2000 complete in 1272.9 sec
[-----------------69%------            ] 1384 of 2000 complete in 1273.9 sec
[-----------------69%------            ] 1385 of 2000 complete in 1274.8 sec
[-----------------69%------            ] 1386 of 2000 complete in 1275.7 sec
[-----------------69%------            ] 1387 of 2000 complete in 1276.7 sec
[-----------------69%------            ] 1388 of 2000 complete in 1277.6 sec
[-----------------69%------            ] 1389 of 2000 complete in 1278.6 sec
[-----------------69%------            ] 1390 of 2000 complete in 1279.5 sec
[-----------------69%------            ] 1391 of 2000 complete in 1280.5 sec
[-----------------69%------            ] 1392 of 2000 complete in 1281.4 sec
[-----------------69%------            ] 1393 of 2000 complete in 1282.3 sec
[-----------------69%------            ] 1394 of 2000 complete in 1283.3 sec
[-----------------69%------            ] 1395 of 2000 complete in 1284.2 sec
[-----------------69%------            ] 1396 of 2000 complete in 1285.2 sec
[-----------------69%------            ] 1397 of 2000 complete in 1286.1 sec
[-----------------69%------            ] 1398 of 2000 complete in 1287.0 sec
[-----------------69%------            ] 1399 of 2000 complete in 1288.0 sec
[-----------------70%------            ] 1400 of 2000 complete in 1288.9 sec
[-----------------70%------            ] 1401 of 2000 complete in 1289.8 sec
[-----------------70%------            ] 1402 of 2000 complete in 1290.7 sec
[-----------------70%------            ] 1403 of 2000 complete in 1291.6 sec
[-----------------70%------            ] 1404 of 2000 complete in 1292.5 sec
[-----------------70%------            ] 1405 of 2000 complete in 1293.4 sec
[-----------------70%------            ] 1406 of 2000 complete in 1294.2 sec
[-----------------70%------            ] 1407 of 2000 complete in 1295.1 sec
[-----------------70%------            ] 1408 of 2000 complete in 1296.0 sec
[-----------------70%------            ] 1409 of 2000 complete in 1296.8 sec

[-----------------65%----              ] 1304 of 2000 complete in 1211.5 sec
[-----------------65%----              ] 1305 of 2000 complete in 1212.3 sec
[-----------------65%----              ] 1306 of 2000 complete in 1213.2 sec
[-----------------65%----              ] 1307 of 2000 complete in 1214.1 sec
[-----------------65%----              ] 1308 of 2000 complete in 1215.0 sec
[-----------------65%----              ] 1309 of 2000 complete in 1215.9 sec
[-----------------65%----              ] 1310 of 2000 complete in 1216.7 sec
[-----------------65%----              ] 1311 of 2000 complete in 1217.6 sec
[-----------------65%----              ] 1312 of 2000 complete in 1218.5 sec
[-----------------65%----              ] 1313 of 2000 complete in 1219.4 sec
[-----------------65%----              ] 1314 of 2000 complete in 1220.3 sec
[-----------------65%----              ] 1315 of 2000 complete in 1221.2 sec
[-----------------65%-----             ] 1316 of 2000 complete in 1222.1 sec
[-----------------65%-----             ] 1317 of 2000 complete in 1222.9 sec
[-----------------65%-----             ] 1318 of 2000 complete in 1223.8 sec
[-----------------65%-----             ] 1319 of 2000 complete in 1224.7 sec
[-----------------66%-----             ] 1320 of 2000 complete in 1225.6 sec
[-----------------66%-----             ] 1321 of 2000 complete in 1226.5 sec
[-----------------66%-----             ] 1322 of 2000 complete in 1227.4 sec
[-----------------66%-----             ] 1323 of 2000 complete in 1228.4 sec
[-----------------66%-----             ] 1324 of 2000 complete in 1229.2 sec
[-----------------66%-----             ] 1325 of 2000 complete in 1230.1 sec
[-----------------66%-----             ] 1326 of 2000 complete in 1231.0 sec
[-----------------66%-----             ] 1327 of 2000 complete in 1232.0 sec
[-----------------66%-----             ] 1328 of 2000 complete in 1232.9 sec
[-----------------66%-----             ] 1329 of 2000 complete in 1233.8 sec
[-----------------66%-----             ] 1330 of 2000 complete in 1234.8 sec
[-----------------66%-----             ] 1331 of 2000 complete in 1235.7 sec
[-----------------66%-----             ] 1332 of 2000 complete in 1236.6 sec
[-----------------66%-----             ] 1333 of 2000 complete in 1237.5 sec
[-----------------66%-----             ] 1334 of 2000 complete in 1238.4 sec
[-----------------66%-----             ] 1335 of 2000 complete in 1239.3 sec
[-----------------66%-----             ] 1336 of 2000 complete in 1240.1 sec
[-----------------66%-----             ] 1337 of 2000 complete in 1241.0 sec
[-----------------66%-----             ] 1338 of 2000 complete in 1241.9 sec
[-----------------66%-----             ] 1339 of 2000 complete in 1242.9 sec
[-----------------67%-----             ] 1340 of 2000 complete in 1243.8 sec
[-----------------67%-----             ] 1341 of 2000 complete in 1244.7 sec
[-----------------67%-----             ] 1342 of 2000 complete in 1245.6 sec
[-----------------67%-----             ] 1343 of 2000 complete in 1246.5 sec
[-----------------67%-----             ] 1344 of 2000 complete in 1247.4 sec
[-----------------67%-----             ] 1345 of 2000 complete in 1248.3 sec
[-----------------67%-----             ] 1346 of 2000 complete in 1249.2 sec
[-----------------67%-----             ] 1347 of 2000 complete in 1250.1 sec
[-----------------67%-----             ] 1348 of 2000 complete in 1251.0 sec
[-----------------67%-----             ] 1349 of 2000 complete in 1251.9 sec
[-----------------67%-----             ] 1350 of 2000 complete in 1252.7 sec
[-----------------67%-----             ] 1351 of 2000 complete in 1253.6 sec
[-----------------67%-----             ] 1352 of 2000 complete in 1254.5 sec
[-----------------67%-----             ] 1353 of 2000 complete in 1255.4 sec
[-----------------67%-----             ] 1354 of 2000 complete in 1256.2 sec
[-----------------67%-----             ] 1355 of 2000 complete in 1257.1 sec
[-----------------67%-----             ] 1356 of 2000 complete in 1257.9 sec
[-----------------67%-----             ] 1357 of 2000 complete in 1258.8 sec
[-----------------67%-----             ] 1358 of 2000 complete in 1259.6 sec
[-----------------67%-----             ] 1359 of 2000 complete in 1260.5 sec
[-----------------68%-----             ] 1360 of 2000 complete in 1261.4 sec
[-----------------68%-----             ] 1361 of 2000 complete in 1262.2 sec
[-----------------68%-----             ] 1362 of 2000 complete in 1263.2 sec
[-----------------68%-----             ] 1363 of 2000 complete in 1264.0 sec
[-----------------68%-----             ] 1364 of 2000 complete in 1264.9 sec
[-----------------68%-----             ] 1365 of 2000 complete in 1265.8 sec
[-----------------68%-----             ] 1366 of 2000 complete in 1266.7 sec
[-----------------68%-----             ] 1367 of 2000 complete in 1267.5 sec
[-----------------68%-----             ] 1368 of 2000 complete in 1268.4 sec
[-----------------68%------            ] 1369 of 2000 complete in 1269.3 sec
[-----------------68%------            ] 1370 of 2000 complete in 1270.2 sec
[-----------------68%------            ] 1371 of 2000 complete in 1271.1 sec
[-----------------68%------            ] 1372 of 2000 complete in 1272.0 sec
[-----------------68%------            ] 1373 of 2000 complete in 1272.9 sec
[-----------------68%------            ] 1374 of 2000 complete in 1273.7 sec
[-----------------68%------            ] 1375 of 2000 complete in 1274.6 sec
[-----------------68%------            ] 1376 of 2000 complete in 1275.4 sec
[-----------------68%------            ] 1377 of 2000 complete in 1276.3 sec
[-----------------68%------            ] 1378 of 2000 complete in 1277.1 sec
[-----------------68%------            ] 1379 of 2000 complete in 1278.0 sec
[-----------------69%------            ] 1380 of 2000 complete in 1278.8 sec
[-----------------69%------            ] 1381 of 2000 complete in 1279.7 sec
[-----------------69%------            ] 1382 of 2000 complete in 1280.5 sec
[-----------------69%------            ] 1383 of 2000 complete in 1281.4 sec
[-----------------69%------            ] 1384 of 2000 complete in 1282.3 sec
[-----------------69%------            ] 1385 of 2000 complete in 1283.1 sec
[-----------------69%------            ] 1386 of 2000 complete in 1284.0 sec
[-----------------69%------            ] 1387 of 2000 complete in 1284.9 sec
[-----------------69%------            ] 1388 of 2000 complete in 1285.9 sec
[-----------------69%------            ] 1389 of 2000 complete in 1286.8 sec
[-----------------69%------            ] 1390 of 2000 complete in 1287.7 sec
[-----------------69%------            ] 1391 of 2000 complete in 1288.7 sec
[-----------------69%------            ] 1392 of 2000 complete in 1289.6 sec
[-----------------69%------            ] 1393 of 2000 complete in 1290.5 sec
[-----------------69%------            ] 1394 of 2000 complete in 1291.5 sec
[-----------------69%------            ] 1395 of 2000 complete in 1292.4 sec
[-----------------69%------            ] 1396 of 2000 complete in 1293.4 sec
[-----------------69%------            ] 1397 of 2000 complete in 1294.3 sec
[-----------------69%------            ] 1398 of 2000 complete in 1295.2 sec
[-----------------69%------            ] 1399 of 2000 complete in 1296.1 sec
[-----------------70%------            ] 1400 of 2000 complete in 1297.0 sec
[-----------------70%------            ] 1401 of 2000 complete in 1297.9 sec
[-----------------70%------            ] 1402 of 2000 complete in 1298.8 sec
[-----------------70%------            ] 1403 of 2000 complete in 1299.7 sec
[-----------------70%------            ] 1404 of 2000 complete in 1300.6 sec
[-----------------70%------            ] 1405 of 2000 complete in 1301.5 sec
[-----------------70%------            ] 1406 of 2000 complete in 1302.4 sec
[-----------------70%------            ] 1407 of 2000 complete in 1303.3 sec
[-----------------70%------            ] 1408 of 2000 complete in 1304.2 sec
[-----------------70%------            ] 1409 of 2000 complete in 1305.1 sec
[-----------------70%------            ] 1412 of 2000 complete in 1224.5 sec
[-----------------70%------            ] 1413 of 2000 complete in 1225.5 sec
[-----------------70%------            ] 1414 of 2000 complete in 1226.4 sec
[-----------------70%------            ] 1415 of 2000 complete in 1227.3 sec
[-----------------70%------            ] 1416 of 2000 complete in 1228.2 sec
[-----------------70%------            ] 1417 of 2000 complete in 1229.1 sec
[-----------------70%------            ] 1418 of 2000 complete in 1230.0 sec
[-----------------70%------            ] 1419 of 2000 complete in 1230.9 sec
[-----------------71%------            ] 1420 of 2000 complete in 1231.9 sec
[-----------------71%------            ] 1421 of 2000 complete in 1232.9 sec
[-----------------71%-------           ] 1422 of 2000 complete in 1233.8 sec
[-----------------71%-------           ] 1423 of 2000 complete in 1234.7 sec
[-----------------71%-------           ] 1424 of 2000 complete in 1235.6 sec
[-----------------71%-------           ] 1425 of 2000 complete in 1236.6 sec
[-----------------71%-------           ] 1426 of 2000 complete in 1237.5 sec
[-----------------71%-------           ] 1427 of 2000 complete in 1238.4 sec
[-----------------71%-------           ] 1428 of 2000 complete in 1239.4 sec
[-----------------71%-------           ] 1429 of 2000 complete in 1240.2 sec
[-----------------71%-------           ] 1430 of 2000 complete in 1241.1 sec
[-----------------71%-------           ] 1431 of 2000 complete in 1242.0 sec
[-----------------71%-------           ] 1432 of 2000 complete in 1242.9 sec
[-----------------71%-------           ] 1433 of 2000 complete in 1243.8 sec
[-----------------71%-------           ] 1434 of 2000 complete in 1244.7 sec
[-----------------71%-------           ] 1435 of 2000 complete in 1245.7 sec
[-----------------71%-------           ] 1436 of 2000 complete in 1246.6 sec
[-----------------71%-------           ] 1437 of 2000 complete in 1247.5 sec
[-----------------71%-------           ] 1438 of 2000 complete in 1248.5 sec
[-----------------71%-------           ] 1439 of 2000 complete in 1249.4 sec
[-----------------72%-------           ] 1440 of 2000 complete in 1250.3 sec
[-----------------72%-------           ] 1441 of 2000 complete in 1251.2 sec
[-----------------72%-------           ] 1442 of 2000 complete in 1252.1 sec
[-----------------72%-------           ] 1443 of 2000 complete in 1253.0 sec
[-----------------72%-------           ] 1444 of 2000 complete in 1253.9 sec
[-----------------72%-------           ] 1445 of 2000 complete in 1254.8 sec
[-----------------72%-------           ] 1446 of 2000 complete in 1255.7 sec
[-----------------72%-------           ] 1447 of 2000 complete in 1256.6 sec
[-----------------72%-------           ] 1448 of 2000 complete in 1257.6 sec
[-----------------72%-------           ] 1449 of 2000 complete in 1258.5 sec
[-----------------72%-------           ] 1450 of 2000 complete in 1259.4 sec
[-----------------72%-------           ] 1451 of 2000 complete in 1260.3 sec
[-----------------72%-------           ] 1452 of 2000 complete in 1261.2 sec
[-----------------72%-------           ] 1453 of 2000 complete in 1262.1 sec
[-----------------72%-------           ] 1454 of 2000 complete in 1263.2 sec
[-----------------72%-------           ] 1455 of 2000 complete in 1264.1 sec
[-----------------72%-------           ] 1456 of 2000 complete in 1265.0 sec
[-----------------72%-------           ] 1457 of 2000 complete in 1266.0 sec
[-----------------72%-------           ] 1458 of 2000 complete in 1266.9 sec
[-----------------72%-------           ] 1459 of 2000 complete in 1267.7 sec
[-----------------73%-------           ] 1460 of 2000 complete in 1268.6 sec
[-----------------73%-------           ] 1461 of 2000 complete in 1269.5 sec
[-----------------73%-------           ] 1462 of 2000 complete in 1270.4 sec
[-----------------73%-------           ] 1463 of 2000 complete in 1271.3 sec
[-----------------73%-------           ] 1464 of 2000 complete in 1272.3 sec
[-----------------73%-------           ] 1465 of 2000 complete in 1273.2 sec
[-----------------73%-------           ] 1466 of 2000 complete in 1274.1 sec
[-----------------73%-------           ] 1467 of 2000 complete in 1275.0 sec
[-----------------73%-------           ] 1468 of 2000 complete in 1275.8 sec
[-----------------73%-------           ] 1469 of 2000 complete in 1276.7 sec
[-----------------73%-------           ] 1470 of 2000 complete in 1277.6 sec
[-----------------73%-------           ] 1471 of 2000 complete in 1278.4 sec
[-----------------73%-------           ] 1472 of 2000 complete in 1279.3 sec
[-----------------73%-------           ] 1473 of 2000 complete in 1280.2 sec
[-----------------73%--------          ] 1474 of 2000 complete in 1281.1 sec
[-----------------73%--------          ] 1475 of 2000 complete in 1282.0 sec
[-----------------73%--------          ] 1476 of 2000 complete in 1282.8 sec
[-----------------73%--------          ] 1477 of 2000 complete in 1283.6 sec
[-----------------73%--------          ] 1478 of 2000 complete in 1284.5 sec
[-----------------73%--------          ] 1479 of 2000 complete in 1285.4 sec
[-----------------74%--------          ] 1480 of 2000 complete in 1286.2 sec
[-----------------74%--------          ] 1481 of 2000 complete in 1287.1 sec
[-----------------74%--------          ] 1482 of 2000 complete in 1288.0 sec
[-----------------74%--------          ] 1483 of 2000 complete in 1288.9 sec
[-----------------74%--------          ] 1484 of 2000 complete in 1289.7 sec
[-----------------74%--------          ] 1485 of 2000 complete in 1290.6 sec
[-----------------74%--------          ] 1486 of 2000 complete in 1291.4 sec
[-----------------74%--------          ] 1487 of 2000 complete in 1292.2 sec
[-----------------74%--------          ] 1488 of 2000 complete in 1293.0 sec
[-----------------74%--------          ] 1489 of 2000 complete in 1293.9 sec
[-----------------74%--------          ] 1490 of 2000 complete in 1294.7 sec
[-----------------74%--------          ] 1491 of 2000 complete in 1295.6 sec
[-----------------74%--------          ] 1492 of 2000 complete in 1296.4 sec
[-----------------74%--------          ] 1493 of 2000 complete in 1297.2 sec
[-----------------74%--------          ] 1494 of 2000 complete in 1298.0 sec
[-----------------74%--------          ] 1495 of 2000 complete in 1298.8 sec
[-----------------74%--------          ] 1496 of 2000 complete in 1299.6 sec
[-----------------74%--------          ] 1497 of 2000 complete in 1300.5 sec
[-----------------74%--------          ] 1498 of 2000 complete in 1301.3 sec
[-----------------74%--------          ] 1499 of 2000 complete in 1302.1 sec
[-----------------75%--------          ] 1500 of 2000 complete in 1302.9 sec
[-----------------75%--------          ] 1501 of 2000 complete in 1303.7 sec
[-----------------75%--------          ] 1502 of 2000 complete in 1304.5 sec
[-----------------75%--------          ] 1503 of 2000 complete in 1305.3 sec
[-----------------75%--------          ] 1504 of 2000 complete in 1306.1 sec
[-----------------75%--------          ] 1505 of 2000 complete in 1306.9 sec
[-----------------75%--------          ] 1506 of 2000 complete in 1307.7 sec
[-----------------75%--------          ] 1507 of 2000 complete in 1308.5 sec
[-----------------75%--------          ] 1508 of 2000 complete in 1309.4 sec
[-----------------75%--------          ] 1509 of 2000 complete in 1310.2 sec
[-----------------75%--------          ] 1510 of 2000 complete in 1311.0 sec
[-----------------75%--------          ] 1511 of 2000 complete in 1311.8 sec
[-----------------75%--------          ] 1512 of 2000 complete in 1312.6 sec
[-----------------75%--------          ] 1513 of 2000 complete in 1313.4 sec
[-----------------75%--------          ] 1514 of 2000 complete in 1314.2 sec
[-----------------75%--------          ] 1515 of 2000 complete in 1315.0 sec
[-----------------75%--------          ] 1516 of 2000 complete in 1315.8 sec
[-----------------75%--------          ] 1517 of 2000 complete in 1316.7 sec

[-----------------70%------            ] 1412 of 2000 complete in 1228.2 sec
[-----------------70%------            ] 1413 of 2000 complete in 1229.1 sec
[-----------------70%------            ] 1414 of 2000 complete in 1229.9 sec
[-----------------70%------            ] 1415 of 2000 complete in 1230.8 sec
[-----------------70%------            ] 1416 of 2000 complete in 1231.6 sec
[-----------------70%------            ] 1417 of 2000 complete in 1232.5 sec
[-----------------70%------            ] 1418 of 2000 complete in 1233.3 sec
[-----------------70%------            ] 1419 of 2000 complete in 1234.2 sec
[-----------------71%------            ] 1420 of 2000 complete in 1235.0 sec
[-----------------71%------            ] 1421 of 2000 complete in 1235.9 sec
[-----------------71%-------           ] 1422 of 2000 complete in 1236.8 sec
[-----------------71%-------           ] 1423 of 2000 complete in 1237.6 sec
[-----------------71%-------           ] 1424 of 2000 complete in 1238.4 sec
[-----------------71%-------           ] 1425 of 2000 complete in 1239.3 sec
[-----------------71%-------           ] 1426 of 2000 complete in 1240.2 sec
[-----------------71%-------           ] 1427 of 2000 complete in 1241.1 sec
[-----------------71%-------           ] 1428 of 2000 complete in 1242.0 sec
[-----------------71%-------           ] 1429 of 2000 complete in 1242.9 sec
[-----------------71%-------           ] 1430 of 2000 complete in 1243.8 sec
[-----------------71%-------           ] 1431 of 2000 complete in 1244.6 sec
[-----------------71%-------           ] 1432 of 2000 complete in 1245.4 sec
[-----------------71%-------           ] 1433 of 2000 complete in 1246.3 sec
[-----------------71%-------           ] 1434 of 2000 complete in 1247.1 sec
[-----------------71%-------           ] 1435 of 2000 complete in 1248.0 sec
[-----------------71%-------           ] 1436 of 2000 complete in 1248.8 sec
[-----------------71%-------           ] 1437 of 2000 complete in 1249.7 sec
[-----------------71%-------           ] 1438 of 2000 complete in 1250.5 sec
[-----------------71%-------           ] 1439 of 2000 complete in 1251.4 sec
[-----------------72%-------           ] 1440 of 2000 complete in 1252.2 sec
[-----------------72%-------           ] 1441 of 2000 complete in 1253.1 sec
[-----------------72%-------           ] 1442 of 2000 complete in 1253.9 sec
[-----------------72%-------           ] 1443 of 2000 complete in 1254.8 sec
[-----------------72%-------           ] 1444 of 2000 complete in 1255.6 sec
[-----------------72%-------           ] 1445 of 2000 complete in 1256.5 sec
[-----------------72%-------           ] 1446 of 2000 complete in 1257.3 sec
[-----------------72%-------           ] 1447 of 2000 complete in 1258.2 sec
[-----------------72%-------           ] 1448 of 2000 complete in 1259.0 sec
[-----------------72%-------           ] 1449 of 2000 complete in 1259.9 sec
[-----------------72%-------           ] 1450 of 2000 complete in 1260.7 sec
[-----------------72%-------           ] 1451 of 2000 complete in 1261.6 sec
[-----------------72%-------           ] 1452 of 2000 complete in 1262.5 sec
[-----------------72%-------           ] 1453 of 2000 complete in 1263.4 sec
[-----------------72%-------           ] 1454 of 2000 complete in 1264.3 sec
[-----------------72%-------           ] 1455 of 2000 complete in 1265.2 sec
[-----------------72%-------           ] 1456 of 2000 complete in 1266.1 sec
[-----------------72%-------           ] 1457 of 2000 complete in 1267.0 sec
[-----------------72%-------           ] 1458 of 2000 complete in 1267.8 sec
[-----------------72%-------           ] 1459 of 2000 complete in 1268.7 sec
[-----------------73%-------           ] 1460 of 2000 complete in 1269.6 sec
[-----------------73%-------           ] 1461 of 2000 complete in 1270.4 sec
[-----------------73%-------           ] 1462 of 2000 complete in 1271.3 sec
[-----------------73%-------           ] 1463 of 2000 complete in 1272.2 sec
[-----------------73%-------           ] 1464 of 2000 complete in 1273.0 sec
[-----------------73%-------           ] 1465 of 2000 complete in 1273.9 sec
[-----------------73%-------           ] 1466 of 2000 complete in 1274.7 sec
[-----------------73%-------           ] 1467 of 2000 complete in 1275.6 sec
[-----------------73%-------           ] 1468 of 2000 complete in 1276.5 sec
[-----------------73%-------           ] 1469 of 2000 complete in 1277.4 sec
[-----------------73%-------           ] 1470 of 2000 complete in 1278.3 sec
[-----------------73%-------           ] 1471 of 2000 complete in 1279.2 sec
[-----------------73%-------           ] 1472 of 2000 complete in 1280.1 sec
[-----------------73%-------           ] 1473 of 2000 complete in 1281.0 sec
[-----------------73%--------          ] 1474 of 2000 complete in 1281.9 sec
[-----------------73%--------          ] 1475 of 2000 complete in 1282.8 sec
[-----------------73%--------          ] 1476 of 2000 complete in 1283.7 sec
[-----------------73%--------          ] 1477 of 2000 complete in 1284.7 sec
[-----------------73%--------          ] 1478 of 2000 complete in 1285.6 sec
[-----------------73%--------          ] 1479 of 2000 complete in 1286.6 sec
[-----------------74%--------          ] 1480 of 2000 complete in 1287.5 sec
[-----------------74%--------          ] 1481 of 2000 complete in 1288.4 sec
[-----------------74%--------          ] 1482 of 2000 complete in 1289.3 sec
[-----------------74%--------          ] 1483 of 2000 complete in 1290.2 sec
[-----------------74%--------          ] 1484 of 2000 complete in 1291.1 sec
[-----------------74%--------          ] 1485 of 2000 complete in 1291.9 sec
[-----------------74%--------          ] 1486 of 2000 complete in 1292.8 sec
[-----------------74%--------          ] 1487 of 2000 complete in 1293.6 sec
[-----------------74%--------          ] 1488 of 2000 complete in 1294.5 sec
[-----------------74%--------          ] 1489 of 2000 complete in 1295.4 sec
[-----------------74%--------          ] 1490 of 2000 complete in 1296.3 sec
[-----------------74%--------          ] 1491 of 2000 complete in 1297.2 sec
[-----------------74%--------          ] 1492 of 2000 complete in 1298.1 sec
[-----------------74%--------          ] 1493 of 2000 complete in 1298.9 sec
[-----------------74%--------          ] 1494 of 2000 complete in 1299.8 sec
[-----------------74%--------          ] 1495 of 2000 complete in 1300.7 sec
[-----------------74%--------          ] 1496 of 2000 complete in 1301.6 sec
[-----------------74%--------          ] 1497 of 2000 complete in 1302.4 sec
[-----------------74%--------          ] 1498 of 2000 complete in 1303.2 sec
[-----------------74%--------          ] 1499 of 2000 complete in 1304.1 sec
[-----------------75%--------          ] 1500 of 2000 complete in 1304.9 sec
[-----------------75%--------          ] 1501 of 2000 complete in 1305.8 sec
[-----------------75%--------          ] 1502 of 2000 complete in 1306.7 sec
[-----------------75%--------          ] 1503 of 2000 complete in 1307.6 sec
[-----------------75%--------          ] 1504 of 2000 complete in 1308.4 sec
[-----------------75%--------          ] 1505 of 2000 complete in 1309.2 sec
[-----------------75%--------          ] 1506 of 2000 complete in 1310.0 sec
[-----------------75%--------          ] 1507 of 2000 complete in 1310.9 sec
[-----------------75%--------          ] 1508 of 2000 complete in 1311.7 sec
[-----------------75%--------          ] 1509 of 2000 complete in 1312.5 sec
[-----------------75%--------          ] 1510 of 2000 complete in 1313.3 sec
[-----------------75%--------          ] 1511 of 2000 complete in 1314.1 sec
[-----------------75%--------          ] 1512 of 2000 complete in 1314.8 sec
[-----------------75%--------          ] 1513 of 2000 complete in 1315.7 sec
[-----------------75%--------          ] 1514 of 2000 complete in 1316.5 sec
[-----------------75%--------          ] 1515 of 2000 complete in 1317.3 sec
[-----------------75%--------          ] 1516 of 2000 complete in 1318.1 sec
[-----------------75%--------          ] 1517 of 2000 complete in 1318.9 sec
[-----------------70%------            ] 1410 of 2000 complete in 1297.7 sec
[-----------------70%------            ] 1411 of 2000 complete in 1298.6 sec
[-----------------70%------            ] 1412 of 2000 complete in 1299.5 sec
[-----------------70%------            ] 1413 of 2000 complete in 1300.3 sec
[-----------------70%------            ] 1414 of 2000 complete in 1301.2 sec
[-----------------70%------            ] 1415 of 2000 complete in 1302.0 sec
[-----------------70%------            ] 1416 of 2000 complete in 1302.9 sec
[-----------------70%------            ] 1417 of 2000 complete in 1303.7 sec
[-----------------70%------            ] 1418 of 2000 complete in 1304.5 sec
[-----------------70%------            ] 1419 of 2000 complete in 1305.4 sec
[-----------------71%------            ] 1420 of 2000 complete in 1306.2 sec
[-----------------71%------            ] 1421 of 2000 complete in 1307.1 sec
[-----------------71%-------           ] 1422 of 2000 complete in 1307.9 sec
[-----------------71%-------           ] 1423 of 2000 complete in 1308.7 sec
[-----------------71%-------           ] 1424 of 2000 complete in 1309.5 sec
[-----------------71%-------           ] 1425 of 2000 complete in 1310.3 sec
[-----------------71%-------           ] 1426 of 2000 complete in 1311.2 sec
[-----------------71%-------           ] 1427 of 2000 complete in 1311.9 sec
[-----------------71%-------           ] 1428 of 2000 complete in 1312.8 sec
[-----------------71%-------           ] 1429 of 2000 complete in 1313.6 sec
[-----------------71%-------           ] 1430 of 2000 complete in 1314.5 sec
[-----------------71%-------           ] 1431 of 2000 complete in 1315.3 sec
[-----------------71%-------           ] 1432 of 2000 complete in 1316.2 sec
[-----------------71%-------           ] 1433 of 2000 complete in 1317.0 sec
[-----------------71%-------           ] 1434 of 2000 complete in 1317.9 sec
[-----------------71%-------           ] 1435 of 2000 complete in 1318.7 sec
[-----------------71%-------           ] 1436 of 2000 complete in 1319.6 sec
[-----------------71%-------           ] 1437 of 2000 complete in 1320.4 sec
[-----------------71%-------           ] 1438 of 2000 complete in 1321.2 sec
[-----------------71%-------           ] 1439 of 2000 complete in 1322.1 sec
[-----------------72%-------           ] 1440 of 2000 complete in 1323.0 sec
[-----------------72%-------           ] 1441 of 2000 complete in 1323.8 sec
[-----------------72%-------           ] 1442 of 2000 complete in 1324.7 sec
[-----------------72%-------           ] 1443 of 2000 complete in 1325.5 sec
[-----------------72%-------           ] 1444 of 2000 complete in 1326.4 sec
[-----------------72%-------           ] 1445 of 2000 complete in 1327.3 sec
[-----------------72%-------           ] 1446 of 2000 complete in 1328.1 sec
[-----------------72%-------           ] 1447 of 2000 complete in 1329.0 sec
[-----------------72%-------           ] 1448 of 2000 complete in 1329.8 sec
[-----------------72%-------           ] 1449 of 2000 complete in 1330.7 sec
[-----------------72%-------           ] 1450 of 2000 complete in 1331.6 sec
[-----------------72%-------           ] 1451 of 2000 complete in 1332.5 sec
[-----------------72%-------           ] 1452 of 2000 complete in 1333.3 sec
[-----------------72%-------           ] 1453 of 2000 complete in 1334.2 sec
[-----------------72%-------           ] 1454 of 2000 complete in 1335.1 sec
[-----------------72%-------           ] 1455 of 2000 complete in 1336.0 sec
[-----------------72%-------           ] 1456 of 2000 complete in 1336.8 sec
[-----------------72%-------           ] 1457 of 2000 complete in 1337.7 sec
[-----------------72%-------           ] 1458 of 2000 complete in 1338.6 sec
[-----------------72%-------           ] 1459 of 2000 complete in 1339.5 sec
[-----------------73%-------           ] 1460 of 2000 complete in 1340.4 sec
[-----------------73%-------           ] 1461 of 2000 complete in 1341.3 sec
[-----------------73%-------           ] 1462 of 2000 complete in 1342.2 sec
[-----------------73%-------           ] 1463 of 2000 complete in 1343.1 sec
[-----------------73%-------           ] 1464 of 2000 complete in 1344.0 sec
[-----------------73%-------           ] 1465 of 2000 complete in 1344.8 sec
[-----------------73%-------           ] 1466 of 2000 complete in 1345.7 sec
[-----------------73%-------           ] 1467 of 2000 complete in 1346.6 sec
[-----------------73%-------           ] 1468 of 2000 complete in 1347.5 sec
[-----------------73%-------           ] 1469 of 2000 complete in 1348.3 sec
[-----------------73%-------           ] 1470 of 2000 complete in 1349.3 sec
[-----------------73%-------           ] 1471 of 2000 complete in 1350.2 sec
[-----------------73%-------           ] 1472 of 2000 complete in 1351.1 sec
[-----------------73%-------           ] 1473 of 2000 complete in 1352.0 sec
[-----------------73%--------          ] 1474 of 2000 complete in 1353.0 sec
[-----------------73%--------          ] 1475 of 2000 complete in 1353.9 sec
[-----------------73%--------          ] 1476 of 2000 complete in 1354.8 sec
[-----------------73%--------          ] 1477 of 2000 complete in 1355.8 sec
[-----------------73%--------          ] 1478 of 2000 complete in 1356.7 sec
[-----------------73%--------          ] 1479 of 2000 complete in 1357.6 sec
[-----------------74%--------          ] 1480 of 2000 complete in 1358.5 sec
[-----------------74%--------          ] 1481 of 2000 complete in 1359.5 sec
[-----------------74%--------          ] 1482 of 2000 complete in 1360.4 sec
[-----------------74%--------          ] 1483 of 2000 complete in 1361.3 sec
[-----------------74%--------          ] 1484 of 2000 complete in 1362.2 sec
[-----------------74%--------          ] 1485 of 2000 complete in 1363.1 sec
[-----------------74%--------          ] 1486 of 2000 complete in 1363.9 sec
[-----------------74%--------          ] 1487 of 2000 complete in 1364.9 sec
[-----------------74%--------          ] 1488 of 2000 complete in 1365.7 sec
[-----------------74%--------          ] 1489 of 2000 complete in 1366.7 sec
[-----------------74%--------          ] 1490 of 2000 complete in 1367.6 sec
[-----------------74%--------          ] 1491 of 2000 complete in 1368.5 sec
[-----------------74%--------          ] 1492 of 2000 complete in 1369.4 sec
[-----------------74%--------          ] 1493 of 2000 complete in 1370.3 sec
[-----------------74%--------          ] 1494 of 2000 complete in 1371.2 sec
[-----------------74%--------          ] 1495 of 2000 complete in 1372.0 sec
[-----------------74%--------          ] 1496 of 2000 complete in 1372.9 sec
[-----------------74%--------          ] 1497 of 2000 complete in 1373.8 sec
[-----------------74%--------          ] 1498 of 2000 complete in 1374.7 sec
[-----------------74%--------          ] 1499 of 2000 complete in 1375.5 sec
[-----------------75%--------          ] 1500 of 2000 complete in 1376.3 sec
[-----------------75%--------          ] 1501 of 2000 complete in 1377.2 sec
[-----------------75%--------          ] 1502 of 2000 complete in 1378.0 sec
[-----------------75%--------          ] 1503 of 2000 complete in 1378.9 sec
[-----------------75%--------          ] 1504 of 2000 complete in 1379.7 sec
[-----------------75%--------          ] 1505 of 2000 complete in 1380.6 sec
[-----------------75%--------          ] 1506 of 2000 complete in 1381.4 sec
[-----------------75%--------          ] 1507 of 2000 complete in 1382.3 sec
[-----------------75%--------          ] 1508 of 2000 complete in 1383.2 sec
[-----------------75%--------          ] 1509 of 2000 complete in 1384.1 sec
[-----------------75%--------          ] 1510 of 2000 complete in 1384.9 sec
[-----------------75%--------          ] 1511 of 2000 complete in 1385.8 sec
[-----------------75%--------          ] 1512 of 2000 complete in 1386.6 sec
[-----------------75%--------          ] 1513 of 2000 complete in 1387.5 sec
[-----------------75%--------          ] 1514 of 2000 complete in 1388.4 sec
[-----------------75%--------          ] 1515 of 2000 complete in 1389.2 sec

[-----------------75%--------          ] 1518 of 2000 complete in 1317.4 sec
[-----------------75%--------          ] 1519 of 2000 complete in 1318.2 sec
[-----------------76%--------          ] 1520 of 2000 complete in 1319.0 sec
[-----------------76%--------          ] 1521 of 2000 complete in 1319.8 sec
[-----------------76%--------          ] 1522 of 2000 complete in 1320.6 sec
[-----------------76%--------          ] 1523 of 2000 complete in 1321.4 sec
[-----------------76%--------          ] 1524 of 2000 complete in 1322.3 sec
[-----------------76%--------          ] 1525 of 2000 complete in 1323.1 sec
[-----------------76%--------          ] 1526 of 2000 complete in 1323.9 sec
[-----------------76%---------         ] 1527 of 2000 complete in 1324.7 sec
[-----------------76%---------         ] 1528 of 2000 complete in 1325.5 sec
[-----------------76%---------         ] 1529 of 2000 complete in 1326.3 sec
[-----------------76%---------         ] 1530 of 2000 complete in 1327.1 sec
[-----------------76%---------         ] 1531 of 2000 complete in 1327.9 sec
[-----------------76%---------         ] 1532 of 2000 complete in 1328.8 sec
[-----------------76%---------         ] 1533 of 2000 complete in 1329.6 sec
[-----------------76%---------         ] 1534 of 2000 complete in 1330.5 sec
[-----------------76%---------         ] 1535 of 2000 complete in 1331.3 sec
[-----------------76%---------         ] 1536 of 2000 complete in 1332.1 sec
[-----------------76%---------         ] 1537 of 2000 complete in 1332.9 sec
[-----------------76%---------         ] 1538 of 2000 complete in 1333.8 sec
[-----------------76%---------         ] 1539 of 2000 complete in 1334.6 sec
[-----------------77%---------         ] 1540 of 2000 complete in 1335.5 sec
[-----------------77%---------         ] 1541 of 2000 complete in 1336.3 sec
[-----------------77%---------         ] 1542 of 2000 complete in 1337.2 sec
[-----------------77%---------         ] 1543 of 2000 complete in 1338.0 sec
[-----------------77%---------         ] 1544 of 2000 complete in 1338.8 sec
[-----------------77%---------         ] 1545 of 2000 complete in 1339.7 sec
[-----------------77%---------         ] 1546 of 2000 complete in 1340.6 sec
[-----------------77%---------         ] 1547 of 2000 complete in 1341.4 sec
[-----------------77%---------         ] 1548 of 2000 complete in 1342.3 sec
[-----------------77%---------         ] 1549 of 2000 complete in 1343.1 sec
[-----------------77%---------         ] 1550 of 2000 complete in 1343.9 sec
[-----------------77%---------         ] 1551 of 2000 complete in 1344.7 sec
[-----------------77%---------         ] 1552 of 2000 complete in 1345.5 sec
[-----------------77%---------         ] 1553 of 2000 complete in 1346.4 sec
[-----------------77%---------         ] 1554 of 2000 complete in 1347.2 sec
[-----------------77%---------         ] 1555 of 2000 complete in 1348.1 sec
[-----------------77%---------         ] 1556 of 2000 complete in 1348.9 sec
[-----------------77%---------         ] 1557 of 2000 complete in 1349.7 sec
[-----------------77%---------         ] 1558 of 2000 complete in 1350.6 sec
[-----------------77%---------         ] 1559 of 2000 complete in 1351.4 sec
[-----------------78%---------         ] 1560 of 2000 complete in 1352.2 sec
[-----------------78%---------         ] 1561 of 2000 complete in 1353.1 sec
[-----------------78%---------         ] 1562 of 2000 complete in 1353.9 sec
[-----------------78%---------         ] 1563 of 2000 complete in 1354.8 sec
[-----------------78%---------         ] 1564 of 2000 complete in 1355.6 sec
[-----------------78%---------         ] 1565 of 2000 complete in 1356.5 sec
[-----------------78%---------         ] 1566 of 2000 complete in 1357.3 sec
[-----------------78%---------         ] 1567 of 2000 complete in 1358.2 sec
[-----------------78%---------         ] 1568 of 2000 complete in 1359.0 sec
[-----------------78%---------         ] 1569 of 2000 complete in 1359.9 sec
[-----------------78%---------         ] 1570 of 2000 complete in 1360.8 sec
[-----------------78%---------         ] 1571 of 2000 complete in 1361.6 sec
[-----------------78%---------         ] 1572 of 2000 complete in 1362.5 sec
[-----------------78%---------         ] 1573 of 2000 complete in 1363.3 sec
[-----------------78%---------         ] 1574 of 2000 complete in 1364.1 sec
[-----------------78%---------         ] 1575 of 2000 complete in 1365.0 sec
[-----------------78%---------         ] 1576 of 2000 complete in 1365.9 sec
[-----------------78%---------         ] 1577 of 2000 complete in 1366.7 sec
[-----------------78%---------         ] 1578 of 2000 complete in 1367.5 sec
[-----------------78%----------        ] 1579 of 2000 complete in 1368.3 sec
[-----------------79%----------        ] 1580 of 2000 complete in 1369.2 sec
[-----------------79%----------        ] 1581 of 2000 complete in 1370.0 sec
[-----------------79%----------        ] 1582 of 2000 complete in 1370.9 sec
[-----------------79%----------        ] 1583 of 2000 complete in 1371.8 sec
[-----------------79%----------        ] 1584 of 2000 complete in 1372.6 sec
[-----------------79%----------        ] 1585 of 2000 complete in 1373.5 sec
[-----------------79%----------        ] 1586 of 2000 complete in 1374.4 sec
[-----------------79%----------        ] 1587 of 2000 complete in 1375.2 sec
[-----------------79%----------        ] 1588 of 2000 complete in 1376.0 sec
[-----------------79%----------        ] 1589 of 2000 complete in 1376.9 sec
[-----------------79%----------        ] 1590 of 2000 complete in 1377.7 sec
[-----------------79%----------        ] 1591 of 2000 complete in 1378.6 sec
[-----------------79%----------        ] 1592 of 2000 complete in 1379.4 sec
[-----------------79%----------        ] 1593 of 2000 complete in 1380.3 sec
[-----------------79%----------        ] 1594 of 2000 complete in 1381.1 sec
[-----------------79%----------        ] 1595 of 2000 complete in 1381.9 sec
[-----------------79%----------        ] 1596 of 2000 complete in 1382.7 sec
[-----------------79%----------        ] 1597 of 2000 complete in 1383.5 sec
[-----------------79%----------        ] 1598 of 2000 complete in 1384.3 sec
[-----------------79%----------        ] 1599 of 2000 complete in 1385.2 sec
[-----------------80%----------        ] 1600 of 2000 complete in 1386.0 sec
[-----------------80%----------        ] 1601 of 2000 complete in 1386.8 sec
[-----------------80%----------        ] 1602 of 2000 complete in 1387.7 sec
[-----------------80%----------        ] 1603 of 2000 complete in 1388.5 sec
[-----------------80%----------        ] 1604 of 2000 complete in 1389.3 sec
[-----------------80%----------        ] 1605 of 2000 complete in 1390.2 sec
[-----------------80%----------        ] 1606 of 2000 complete in 1391.0 sec
[-----------------80%----------        ] 1607 of 2000 complete in 1391.8 sec
[-----------------80%----------        ] 1608 of 2000 complete in 1392.6 sec
[-----------------80%----------        ] 1609 of 2000 complete in 1393.4 sec
[-----------------80%----------        ] 1610 of 2000 complete in 1394.2 sec
[-----------------80%----------        ] 1611 of 2000 complete in 1394.9 sec
[-----------------80%----------        ] 1612 of 2000 complete in 1395.7 sec
[-----------------80%----------        ] 1613 of 2000 complete in 1396.5 sec
[-----------------80%----------        ] 1614 of 2000 complete in 1397.2 sec
[-----------------80%----------        ] 1615 of 2000 complete in 1398.0 sec
[-----------------80%----------        ] 1616 of 2000 complete in 1398.8 sec
[-----------------80%----------        ] 1617 of 2000 complete in 1399.6 sec
[-----------------80%----------        ] 1618 of 2000 complete in 1400.4 sec
[-----------------80%----------        ] 1619 of 2000 complete in 1401.1 sec
[-----------------81%----------        ] 1620 of 2000 complete in 1401.8 sec
[-----------------81%----------        ] 1621 of 2000 complete in 1402.6 sec
[-----------------81%----------        ] 1622 of 2000 complete in 1403.4 sec
[-----------------81%----------        ] 1623 of 2000 complete in 1404.3 sec
[-----------------70%------            ] 1410 of 2000 complete in 1306.0 sec
[-----------------70%------            ] 1411 of 2000 complete in 1306.9 sec
[-----------------70%------            ] 1412 of 2000 complete in 1307.9 sec
[-----------------70%------            ] 1413 of 2000 complete in 1308.8 sec
[-----------------70%------            ] 1414 of 2000 complete in 1309.7 sec
[-----------------70%------            ] 1415 of 2000 complete in 1310.6 sec
[-----------------70%------            ] 1416 of 2000 complete in 1311.5 sec
[-----------------70%------            ] 1417 of 2000 complete in 1312.4 sec
[-----------------70%------            ] 1418 of 2000 complete in 1313.3 sec
[-----------------70%------            ] 1419 of 2000 complete in 1314.3 sec
[-----------------71%------            ] 1420 of 2000 complete in 1315.2 sec
[-----------------71%------            ] 1421 of 2000 complete in 1316.2 sec
[-----------------71%-------           ] 1422 of 2000 complete in 1317.2 sec
[-----------------71%-------           ] 1423 of 2000 complete in 1318.1 sec
[-----------------71%-------           ] 1424 of 2000 complete in 1319.0 sec
[-----------------71%-------           ] 1425 of 2000 complete in 1320.0 sec
[-----------------71%-------           ] 1426 of 2000 complete in 1320.9 sec
[-----------------71%-------           ] 1427 of 2000 complete in 1321.8 sec
[-----------------71%-------           ] 1428 of 2000 complete in 1322.8 sec
[-----------------71%-------           ] 1429 of 2000 complete in 1323.7 sec
[-----------------71%-------           ] 1430 of 2000 complete in 1324.6 sec
[-----------------71%-------           ] 1431 of 2000 complete in 1325.6 sec
[-----------------71%-------           ] 1432 of 2000 complete in 1326.5 sec
[-----------------71%-------           ] 1433 of 2000 complete in 1327.4 sec
[-----------------71%-------           ] 1434 of 2000 complete in 1328.4 sec
[-----------------71%-------           ] 1435 of 2000 complete in 1329.4 sec
[-----------------71%-------           ] 1436 of 2000 complete in 1330.3 sec
[-----------------71%-------           ] 1437 of 2000 complete in 1331.3 sec
[-----------------71%-------           ] 1438 of 2000 complete in 1332.3 sec
[-----------------71%-------           ] 1439 of 2000 complete in 1333.2 sec
[-----------------72%-------           ] 1440 of 2000 complete in 1334.2 sec
[-----------------72%-------           ] 1441 of 2000 complete in 1335.2 sec
[-----------------72%-------           ] 1442 of 2000 complete in 1336.2 sec
[-----------------72%-------           ] 1443 of 2000 complete in 1337.2 sec
[-----------------72%-------           ] 1444 of 2000 complete in 1338.1 sec
[-----------------72%-------           ] 1445 of 2000 complete in 1339.1 sec
[-----------------72%-------           ] 1446 of 2000 complete in 1340.1 sec
[-----------------72%-------           ] 1447 of 2000 complete in 1341.1 sec
[-----------------72%-------           ] 1448 of 2000 complete in 1342.1 sec
[-----------------72%-------           ] 1449 of 2000 complete in 1343.1 sec
[-----------------72%-------           ] 1450 of 2000 complete in 1344.1 sec
[-----------------72%-------           ] 1451 of 2000 complete in 1345.1 sec
[-----------------72%-------           ] 1452 of 2000 complete in 1346.1 sec
[-----------------72%-------           ] 1453 of 2000 complete in 1347.1 sec
[-----------------72%-------           ] 1454 of 2000 complete in 1348.0 sec
[-----------------72%-------           ] 1455 of 2000 complete in 1348.9 sec
[-----------------72%-------           ] 1456 of 2000 complete in 1349.9 sec
[-----------------72%-------           ] 1457 of 2000 complete in 1350.8 sec
[-----------------72%-------           ] 1458 of 2000 complete in 1351.7 sec
[-----------------72%-------           ] 1459 of 2000 complete in 1352.7 sec
[-----------------73%-------           ] 1460 of 2000 complete in 1353.6 sec
[-----------------73%-------           ] 1461 of 2000 complete in 1354.6 sec
[-----------------73%-------           ] 1462 of 2000 complete in 1355.5 sec
[-----------------73%-------           ] 1463 of 2000 complete in 1356.5 sec
[-----------------73%-------           ] 1464 of 2000 complete in 1357.4 sec
[-----------------73%-------           ] 1465 of 2000 complete in 1358.3 sec
[-----------------73%-------           ] 1466 of 2000 complete in 1359.3 sec
[-----------------73%-------           ] 1467 of 2000 complete in 1360.2 sec
[-----------------73%-------           ] 1468 of 2000 complete in 1361.2 sec
[-----------------73%-------           ] 1469 of 2000 complete in 1362.2 sec
[-----------------73%-------           ] 1470 of 2000 complete in 1363.1 sec
[-----------------73%-------           ] 1471 of 2000 complete in 1364.1 sec
[-----------------73%-------           ] 1472 of 2000 complete in 1365.0 sec
[-----------------73%-------           ] 1473 of 2000 complete in 1366.0 sec
[-----------------73%--------          ] 1474 of 2000 complete in 1367.0 sec
[-----------------73%--------          ] 1475 of 2000 complete in 1367.9 sec
[-----------------73%--------          ] 1476 of 2000 complete in 1368.9 sec
[-----------------73%--------          ] 1477 of 2000 complete in 1369.9 sec
[-----------------73%--------          ] 1478 of 2000 complete in 1370.8 sec
[-----------------73%--------          ] 1479 of 2000 complete in 1371.8 sec
[-----------------74%--------          ] 1480 of 2000 complete in 1372.8 sec
[-----------------74%--------          ] 1481 of 2000 complete in 1373.7 sec
[-----------------74%--------          ] 1482 of 2000 complete in 1374.7 sec
[-----------------74%--------          ] 1483 of 2000 complete in 1375.7 sec
[-----------------74%--------          ] 1484 of 2000 complete in 1376.6 sec
[-----------------74%--------          ] 1485 of 2000 complete in 1377.6 sec
[-----------------74%--------          ] 1486 of 2000 complete in 1378.5 sec
[-----------------74%--------          ] 1487 of 2000 complete in 1379.4 sec
[-----------------74%--------          ] 1488 of 2000 complete in 1380.4 sec
[-----------------74%--------          ] 1489 of 2000 complete in 1381.3 sec
[-----------------74%--------          ] 1490 of 2000 complete in 1382.2 sec
[-----------------74%--------          ] 1491 of 2000 complete in 1383.1 sec
[-----------------74%--------          ] 1492 of 2000 complete in 1384.0 sec
[-----------------74%--------          ] 1493 of 2000 complete in 1384.9 sec
[-----------------74%--------          ] 1494 of 2000 complete in 1385.9 sec
[-----------------74%--------          ] 1495 of 2000 complete in 1386.9 sec
[-----------------74%--------          ] 1496 of 2000 complete in 1387.8 sec
[-----------------74%--------          ] 1497 of 2000 complete in 1388.8 sec
[-----------------74%--------          ] 1498 of 2000 complete in 1389.8 sec
[-----------------74%--------          ] 1499 of 2000 complete in 1390.7 sec
[-----------------75%--------          ] 1500 of 2000 complete in 1391.7 sec
[-----------------75%--------          ] 1501 of 2000 complete in 1392.6 sec
[-----------------75%--------          ] 1502 of 2000 complete in 1393.5 sec
[-----------------75%--------          ] 1503 of 2000 complete in 1394.4 sec
[-----------------75%--------          ] 1504 of 2000 complete in 1395.4 sec
[-----------------75%--------          ] 1505 of 2000 complete in 1396.3 sec
[-----------------75%--------          ] 1506 of 2000 complete in 1397.2 sec
[-----------------75%--------          ] 1507 of 2000 complete in 1398.1 sec
[-----------------75%--------          ] 1508 of 2000 complete in 1399.0 sec
[-----------------75%--------          ] 1509 of 2000 complete in 1399.9 sec
[-----------------75%--------          ] 1510 of 2000 complete in 1400.8 sec
[-----------------75%--------          ] 1511 of 2000 complete in 1401.7 sec
[-----------------75%--------          ] 1512 of 2000 complete in 1402.6 sec
[-----------------75%--------          ] 1513 of 2000 complete in 1403.6 sec
[-----------------75%--------          ] 1514 of 2000 complete in 1404.5 sec
[-----------------75%--------          ] 1515 of 2000 complete in 1405.4 sec

[-----------------75%--------          ] 1518 of 2000 complete in 1319.8 sec
[-----------------75%--------          ] 1519 of 2000 complete in 1320.6 sec
[-----------------76%--------          ] 1520 of 2000 complete in 1321.4 sec
[-----------------76%--------          ] 1521 of 2000 complete in 1322.3 sec
[-----------------76%--------          ] 1522 of 2000 complete in 1323.2 sec
[-----------------76%--------          ] 1523 of 2000 complete in 1324.1 sec
[-----------------76%--------          ] 1524 of 2000 complete in 1324.9 sec
[-----------------76%--------          ] 1525 of 2000 complete in 1325.8 sec
[-----------------76%--------          ] 1526 of 2000 complete in 1326.7 sec
[-----------------76%---------         ] 1527 of 2000 complete in 1327.5 sec
[-----------------76%---------         ] 1528 of 2000 complete in 1328.3 sec
[-----------------76%---------         ] 1529 of 2000 complete in 1329.1 sec
[-----------------76%---------         ] 1530 of 2000 complete in 1329.9 sec
[-----------------76%---------         ] 1531 of 2000 complete in 1330.8 sec
[-----------------76%---------         ] 1532 of 2000 complete in 1331.6 sec
[-----------------76%---------         ] 1533 of 2000 complete in 1332.4 sec
[-----------------76%---------         ] 1534 of 2000 complete in 1333.3 sec
[-----------------76%---------         ] 1535 of 2000 complete in 1334.1 sec
[-----------------76%---------         ] 1536 of 2000 complete in 1335.0 sec
[-----------------76%---------         ] 1537 of 2000 complete in 1335.9 sec
[-----------------76%---------         ] 1538 of 2000 complete in 1336.8 sec
[-----------------76%---------         ] 1539 of 2000 complete in 1337.6 sec
[-----------------77%---------         ] 1540 of 2000 complete in 1338.5 sec
[-----------------77%---------         ] 1541 of 2000 complete in 1339.4 sec
[-----------------77%---------         ] 1542 of 2000 complete in 1340.3 sec
[-----------------77%---------         ] 1543 of 2000 complete in 1341.2 sec
[-----------------77%---------         ] 1544 of 2000 complete in 1342.1 sec
[-----------------77%---------         ] 1545 of 2000 complete in 1343.0 sec
[-----------------77%---------         ] 1546 of 2000 complete in 1343.9 sec
[-----------------77%---------         ] 1547 of 2000 complete in 1344.8 sec
[-----------------77%---------         ] 1548 of 2000 complete in 1345.7 sec
[-----------------77%---------         ] 1549 of 2000 complete in 1346.6 sec
[-----------------77%---------         ] 1550 of 2000 complete in 1347.5 sec
[-----------------77%---------         ] 1551 of 2000 complete in 1348.4 sec
[-----------------77%---------         ] 1552 of 2000 complete in 1349.3 sec
[-----------------77%---------         ] 1553 of 2000 complete in 1350.2 sec
[-----------------77%---------         ] 1554 of 2000 complete in 1351.1 sec
[-----------------77%---------         ] 1555 of 2000 complete in 1352.1 sec
[-----------------77%---------         ] 1556 of 2000 complete in 1353.0 sec
[-----------------77%---------         ] 1557 of 2000 complete in 1353.9 sec
[-----------------77%---------         ] 1558 of 2000 complete in 1354.8 sec
[-----------------77%---------         ] 1559 of 2000 complete in 1355.7 sec
[-----------------78%---------         ] 1560 of 2000 complete in 1356.7 sec
[-----------------78%---------         ] 1561 of 2000 complete in 1357.6 sec
[-----------------78%---------         ] 1562 of 2000 complete in 1358.5 sec
[-----------------78%---------         ] 1563 of 2000 complete in 1359.4 sec
[-----------------78%---------         ] 1564 of 2000 complete in 1360.3 sec
[-----------------78%---------         ] 1565 of 2000 complete in 1361.3 sec
[-----------------78%---------         ] 1566 of 2000 complete in 1362.2 sec
[-----------------78%---------         ] 1567 of 2000 complete in 1363.1 sec
[-----------------78%---------         ] 1568 of 2000 complete in 1364.0 sec
[-----------------78%---------         ] 1569 of 2000 complete in 1365.0 sec
[-----------------78%---------         ] 1570 of 2000 complete in 1365.9 sec
[-----------------78%---------         ] 1571 of 2000 complete in 1366.9 sec
[-----------------78%---------         ] 1572 of 2000 complete in 1367.8 sec
[-----------------78%---------         ] 1573 of 2000 complete in 1368.7 sec
[-----------------78%---------         ] 1574 of 2000 complete in 1369.7 sec
[-----------------78%---------         ] 1575 of 2000 complete in 1370.6 sec
[-----------------78%---------         ] 1576 of 2000 complete in 1371.5 sec
[-----------------78%---------         ] 1577 of 2000 complete in 1372.5 sec
[-----------------78%---------         ] 1578 of 2000 complete in 1373.4 sec
[-----------------78%----------        ] 1579 of 2000 complete in 1374.3 sec
[-----------------79%----------        ] 1580 of 2000 complete in 1375.1 sec
[-----------------79%----------        ] 1581 of 2000 complete in 1376.0 sec
[-----------------79%----------        ] 1582 of 2000 complete in 1376.9 sec
[-----------------79%----------        ] 1583 of 2000 complete in 1377.8 sec
[-----------------79%----------        ] 1584 of 2000 complete in 1378.7 sec
[-----------------79%----------        ] 1585 of 2000 complete in 1379.6 sec
[-----------------79%----------        ] 1586 of 2000 complete in 1380.5 sec
[-----------------79%----------        ] 1587 of 2000 complete in 1381.4 sec
[-----------------79%----------        ] 1588 of 2000 complete in 1382.4 sec
[-----------------79%----------        ] 1589 of 2000 complete in 1383.3 sec
[-----------------79%----------        ] 1590 of 2000 complete in 1384.2 sec
[-----------------79%----------        ] 1591 of 2000 complete in 1385.1 sec
[-----------------79%----------        ] 1592 of 2000 complete in 1386.0 sec
[-----------------79%----------        ] 1593 of 2000 complete in 1386.9 sec
[-----------------79%----------        ] 1594 of 2000 complete in 1387.7 sec
[-----------------79%----------        ] 1595 of 2000 complete in 1388.6 sec
[-----------------79%----------        ] 1596 of 2000 complete in 1389.4 sec
[-----------------79%----------        ] 1597 of 2000 complete in 1390.3 sec
[-----------------79%----------        ] 1598 of 2000 complete in 1391.1 sec
[-----------------79%----------        ] 1599 of 2000 complete in 1392.0 sec
[-----------------80%----------        ] 1600 of 2000 complete in 1392.9 sec
[-----------------80%----------        ] 1601 of 2000 complete in 1393.7 sec
[-----------------80%----------        ] 1602 of 2000 complete in 1394.6 sec
[-----------------80%----------        ] 1603 of 2000 complete in 1395.5 sec
[-----------------80%----------        ] 1604 of 2000 complete in 1396.3 sec
[-----------------80%----------        ] 1605 of 2000 complete in 1397.1 sec
[-----------------80%----------        ] 1606 of 2000 complete in 1398.0 sec
[-----------------80%----------        ] 1607 of 2000 complete in 1398.8 sec
[-----------------80%----------        ] 1608 of 2000 complete in 1399.6 sec
[-----------------80%----------        ] 1609 of 2000 complete in 1400.4 sec
[-----------------80%----------        ] 1610 of 2000 complete in 1401.2 sec
[-----------------80%----------        ] 1611 of 2000 complete in 1402.1 sec
[-----------------80%----------        ] 1612 of 2000 complete in 1403.0 sec
[-----------------80%----------        ] 1613 of 2000 complete in 1403.9 sec
[-----------------80%----------        ] 1614 of 2000 complete in 1404.7 sec
[-----------------80%----------        ] 1615 of 2000 complete in 1405.6 sec
[-----------------80%----------        ] 1616 of 2000 complete in 1406.4 sec
[-----------------80%----------        ] 1617 of 2000 complete in 1407.3 sec
[-----------------80%----------        ] 1618 of 2000 complete in 1408.2 sec
[-----------------80%----------        ] 1619 of 2000 complete in 1409.1 sec
[-----------------81%----------        ] 1620 of 2000 complete in 1409.9 sec
[-----------------81%----------        ] 1621 of 2000 complete in 1410.8 sec
[-----------------81%----------        ] 1622 of 2000 complete in 1411.6 sec
[-----------------81%----------        ] 1623 of 2000 complete in 1412.5 sec
[-----------------75%--------          ] 1516 of 2000 complete in 1390.1 sec
[-----------------75%--------          ] 1517 of 2000 complete in 1390.9 sec
[-----------------75%--------          ] 1518 of 2000 complete in 1391.8 sec
[-----------------75%--------          ] 1519 of 2000 complete in 1392.6 sec
[-----------------76%--------          ] 1520 of 2000 complete in 1393.4 sec
[-----------------76%--------          ] 1521 of 2000 complete in 1394.3 sec
[-----------------76%--------          ] 1522 of 2000 complete in 1395.1 sec
[-----------------76%--------          ] 1523 of 2000 complete in 1395.9 sec
[-----------------76%--------          ] 1524 of 2000 complete in 1396.7 sec
[-----------------76%--------          ] 1525 of 2000 complete in 1397.6 sec
[-----------------76%--------          ] 1526 of 2000 complete in 1398.4 sec
[-----------------76%---------         ] 1527 of 2000 complete in 1399.3 sec
[-----------------76%---------         ] 1528 of 2000 complete in 1400.1 sec
[-----------------76%---------         ] 1529 of 2000 complete in 1401.0 sec
[-----------------76%---------         ] 1530 of 2000 complete in 1401.8 sec
[-----------------76%---------         ] 1531 of 2000 complete in 1402.6 sec
[-----------------76%---------         ] 1532 of 2000 complete in 1403.4 sec
[-----------------76%---------         ] 1533 of 2000 complete in 1404.2 sec
[-----------------76%---------         ] 1534 of 2000 complete in 1405.1 sec
[-----------------76%---------         ] 1535 of 2000 complete in 1405.9 sec
[-----------------76%---------         ] 1536 of 2000 complete in 1406.8 sec
[-----------------76%---------         ] 1537 of 2000 complete in 1407.6 sec
[-----------------76%---------         ] 1538 of 2000 complete in 1408.5 sec
[-----------------76%---------         ] 1539 of 2000 complete in 1409.3 sec
[-----------------77%---------         ] 1540 of 2000 complete in 1410.2 sec
[-----------------77%---------         ] 1541 of 2000 complete in 1411.1 sec
[-----------------77%---------         ] 1542 of 2000 complete in 1412.0 sec
[-----------------77%---------         ] 1543 of 2000 complete in 1412.9 sec
[-----------------77%---------         ] 1544 of 2000 complete in 1413.8 sec
[-----------------77%---------         ] 1545 of 2000 complete in 1414.7 sec
[-----------------77%---------         ] 1546 of 2000 complete in 1415.7 sec
[-----------------77%---------         ] 1547 of 2000 complete in 1416.6 sec
[-----------------77%---------         ] 1548 of 2000 complete in 1417.5 sec
[-----------------77%---------         ] 1549 of 2000 complete in 1418.4 sec
[-----------------77%---------         ] 1550 of 2000 complete in 1419.4 sec
[-----------------77%---------         ] 1551 of 2000 complete in 1420.3 sec
[-----------------77%---------         ] 1552 of 2000 complete in 1421.2 sec
[-----------------77%---------         ] 1553 of 2000 complete in 1422.2 sec
[-----------------77%---------         ] 1554 of 2000 complete in 1423.2 sec
[-----------------77%---------         ] 1555 of 2000 complete in 1424.1 sec
[-----------------77%---------         ] 1556 of 2000 complete in 1425.1 sec
[-----------------77%---------         ] 1557 of 2000 complete in 1426.0 sec
[-----------------77%---------         ] 1558 of 2000 complete in 1427.0 sec
[-----------------77%---------         ] 1559 of 2000 complete in 1427.9 sec
[-----------------78%---------         ] 1560 of 2000 complete in 1428.8 sec
[-----------------78%---------         ] 1561 of 2000 complete in 1429.8 sec
[-----------------78%---------         ] 1562 of 2000 complete in 1430.7 sec
[-----------------78%---------         ] 1563 of 2000 complete in 1431.7 sec
[-----------------78%---------         ] 1564 of 2000 complete in 1432.6 sec
[-----------------78%---------         ] 1565 of 2000 complete in 1433.5 sec
[-----------------78%---------         ] 1566 of 2000 complete in 1434.4 sec
[-----------------78%---------         ] 1567 of 2000 complete in 1435.3 sec
[-----------------78%---------         ] 1568 of 2000 complete in 1436.3 sec
[-----------------78%---------         ] 1569 of 2000 complete in 1437.2 sec
[-----------------78%---------         ] 1570 of 2000 complete in 1438.2 sec
[-----------------78%---------         ] 1571 of 2000 complete in 1439.1 sec
[-----------------78%---------         ] 1572 of 2000 complete in 1440.0 sec
[-----------------78%---------         ] 1573 of 2000 complete in 1441.0 sec
[-----------------78%---------         ] 1574 of 2000 complete in 1441.9 sec
[-----------------78%---------         ] 1575 of 2000 complete in 1442.8 sec
[-----------------78%---------         ] 1576 of 2000 complete in 1443.7 sec
[-----------------78%---------         ] 1577 of 2000 complete in 1444.6 sec
[-----------------78%---------         ] 1578 of 2000 complete in 1445.5 sec
[-----------------78%----------        ] 1579 of 2000 complete in 1446.4 sec
[-----------------79%----------        ] 1580 of 2000 complete in 1447.3 sec
[-----------------79%----------        ] 1581 of 2000 complete in 1448.2 sec
[-----------------79%----------        ] 1582 of 2000 complete in 1449.2 sec
[-----------------79%----------        ] 1583 of 2000 complete in 1450.1 sec
[-----------------79%----------        ] 1584 of 2000 complete in 1451.1 sec
[-----------------79%----------        ] 1585 of 2000 complete in 1452.0 sec
[-----------------79%----------        ] 1586 of 2000 complete in 1453.0 sec
[-----------------79%----------        ] 1587 of 2000 complete in 1453.9 sec
[-----------------79%----------        ] 1588 of 2000 complete in 1454.9 sec
[-----------------79%----------        ] 1589 of 2000 complete in 1455.9 sec
[-----------------79%----------        ] 1590 of 2000 complete in 1456.8 sec
[-----------------79%----------        ] 1591 of 2000 complete in 1457.8 sec
[-----------------79%----------        ] 1592 of 2000 complete in 1458.8 sec
[-----------------79%----------        ] 1593 of 2000 complete in 1459.8 sec
[-----------------79%----------        ] 1594 of 2000 complete in 1460.7 sec
[-----------------79%----------        ] 1595 of 2000 complete in 1461.6 sec
[-----------------79%----------        ] 1596 of 2000 complete in 1462.5 sec
[-----------------79%----------        ] 1597 of 2000 complete in 1463.3 sec
[-----------------79%----------        ] 1598 of 2000 complete in 1464.2 sec
[-----------------79%----------        ] 1599 of 2000 complete in 1465.1 sec
[-----------------80%----------        ] 1600 of 2000 complete in 1466.1 sec
[-----------------80%----------        ] 1601 of 2000 complete in 1467.0 sec
[-----------------80%----------        ] 1602 of 2000 complete in 1467.9 sec
[-----------------80%----------        ] 1603 of 2000 complete in 1468.9 sec
[-----------------80%----------        ] 1604 of 2000 complete in 1469.8 sec
[-----------------80%----------        ] 1605 of 2000 complete in 1470.7 sec
[-----------------80%----------        ] 1606 of 2000 complete in 1471.6 sec
[-----------------80%----------        ] 1607 of 2000 complete in 1472.6 sec
[-----------------80%----------        ] 1608 of 2000 complete in 1473.6 sec
[-----------------80%----------        ] 1609 of 2000 complete in 1474.6 sec
[-----------------80%----------        ] 1610 of 2000 complete in 1475.6 sec
[-----------------80%----------        ] 1611 of 2000 complete in 1476.6 sec
[-----------------80%----------        ] 1612 of 2000 complete in 1477.6 sec
[-----------------80%----------        ] 1613 of 2000 complete in 1478.6 sec
[-----------------80%----------        ] 1614 of 2000 complete in 1479.6 sec
[-----------------80%----------        ] 1615 of 2000 complete in 1480.5 sec
[-----------------80%----------        ] 1616 of 2000 complete in 1481.5 sec
[-----------------80%----------        ] 1617 of 2000 complete in 1482.5 sec
[-----------------80%----------        ] 1618 of 2000 complete in 1483.5 sec
[-----------------80%----------        ] 1619 of 2000 complete in 1484.5 sec
[-----------------81%----------        ] 1620 of 2000 complete in 1485.5 sec
[-----------------81%----------        ] 1621 of 2000 complete in 1486.5 sec

[-----------------81%----------        ] 1624 of 2000 complete in 1405.1 sec
[-----------------81%----------        ] 1625 of 2000 complete in 1405.9 sec
[-----------------81%----------        ] 1626 of 2000 complete in 1406.8 sec
[-----------------81%----------        ] 1627 of 2000 complete in 1407.6 sec
[-----------------81%----------        ] 1628 of 2000 complete in 1408.4 sec
[-----------------81%----------        ] 1629 of 2000 complete in 1409.3 sec
[-----------------81%----------        ] 1630 of 2000 complete in 1410.1 sec
[-----------------81%----------        ] 1631 of 2000 complete in 1410.9 sec
[-----------------81%-----------       ] 1632 of 2000 complete in 1411.7 sec
[-----------------81%-----------       ] 1633 of 2000 complete in 1412.5 sec
[-----------------81%-----------       ] 1634 of 2000 complete in 1413.4 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 1414.2 sec
[-----------------81%-----------       ] 1636 of 2000 complete in 1415.0 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 1415.8 sec
[-----------------81%-----------       ] 1638 of 2000 complete in 1416.6 sec
[-----------------81%-----------       ] 1639 of 2000 complete in 1417.4 sec
[-----------------82%-----------       ] 1640 of 2000 complete in 1418.3 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 1419.1 sec
[-----------------82%-----------       ] 1642 of 2000 complete in 1419.9 sec
[-----------------82%-----------       ] 1643 of 2000 complete in 1420.8 sec
[-----------------82%-----------       ] 1644 of 2000 complete in 1421.6 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 1422.4 sec
[-----------------82%-----------       ] 1646 of 2000 complete in 1423.2 sec
[-----------------82%-----------       ] 1647 of 2000 complete in 1424.1 sec
[-----------------82%-----------       ] 1648 of 2000 complete in 1424.9 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 1425.7 sec
[-----------------82%-----------       ] 1650 of 2000 complete in 1426.5 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 1427.3 sec
[-----------------82%-----------       ] 1652 of 2000 complete in 1428.2 sec
[-----------------82%-----------       ] 1653 of 2000 complete in 1429.0 sec
[-----------------82%-----------       ] 1654 of 2000 complete in 1429.8 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 1430.7 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 1431.6 sec
[-----------------82%-----------       ] 1657 of 2000 complete in 1432.5 sec
[-----------------82%-----------       ] 1658 of 2000 complete in 1433.4 sec
[-----------------82%-----------       ] 1659 of 2000 complete in 1434.2 sec
[-----------------83%-----------       ] 1660 of 2000 complete in 1435.1 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 1436.0 sec
[-----------------83%-----------       ] 1662 of 2000 complete in 1436.9 sec
[-----------------83%-----------       ] 1663 of 2000 complete in 1437.7 sec
[-----------------83%-----------       ] 1664 of 2000 complete in 1438.5 sec
[-----------------83%-----------       ] 1665 of 2000 complete in 1439.3 sec
[-----------------83%-----------       ] 1666 of 2000 complete in 1440.2 sec
[-----------------83%-----------       ] 1667 of 2000 complete in 1441.0 sec
[-----------------83%-----------       ] 1668 of 2000 complete in 1441.9 sec
[-----------------83%-----------       ] 1669 of 2000 complete in 1442.7 sec
[-----------------83%-----------       ] 1670 of 2000 complete in 1443.5 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 1444.4 sec
[-----------------83%-----------       ] 1672 of 2000 complete in 1445.2 sec
[-----------------83%-----------       ] 1673 of 2000 complete in 1446.0 sec
[-----------------83%-----------       ] 1674 of 2000 complete in 1446.9 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 1447.7 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 1448.5 sec
[-----------------83%-----------       ] 1677 of 2000 complete in 1449.4 sec
[-----------------83%-----------       ] 1678 of 2000 complete in 1450.2 sec
[-----------------83%-----------       ] 1679 of 2000 complete in 1451.0 sec
[-----------------84%-----------       ] 1680 of 2000 complete in 1451.8 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 1452.6 sec
[-----------------84%-----------       ] 1682 of 2000 complete in 1453.4 sec
[-----------------84%-----------       ] 1683 of 2000 complete in 1454.3 sec
[-----------------84%-----------       ] 1684 of 2000 complete in 1455.1 sec
[-----------------84%------------      ] 1685 of 2000 complete in 1455.9 sec
[-----------------84%------------      ] 1686 of 2000 complete in 1456.7 sec
[-----------------84%------------      ] 1687 of 2000 complete in 1457.5 sec
[-----------------84%------------      ] 1688 of 2000 complete in 1458.4 sec
[-----------------84%------------      ] 1689 of 2000 complete in 1459.2 sec
[-----------------84%------------      ] 1690 of 2000 complete in 1460.1 sec
[-----------------84%------------      ] 1691 of 2000 complete in 1460.9 sec
[-----------------84%------------      ] 1692 of 2000 complete in 1461.7 sec
[-----------------84%------------      ] 1693 of 2000 complete in 1462.6 sec
[-----------------84%------------      ] 1694 of 2000 complete in 1463.4 sec
[-----------------84%------------      ] 1695 of 2000 complete in 1464.2 sec
[-----------------84%------------      ] 1696 of 2000 complete in 1465.1 sec
[-----------------84%------------      ] 1697 of 2000 complete in 1466.0 sec
[-----------------84%------------      ] 1698 of 2000 complete in 1466.8 sec
[-----------------84%------------      ] 1699 of 2000 complete in 1467.6 sec
[-----------------85%------------      ] 1700 of 2000 complete in 1468.5 sec
[-----------------85%------------      ] 1701 of 2000 complete in 1469.4 sec
[-----------------85%------------      ] 1702 of 2000 complete in 1470.3 sec
[-----------------85%------------      ] 1703 of 2000 complete in 1471.2 sec
[-----------------85%------------      ] 1704 of 2000 complete in 1472.1 sec
[-----------------85%------------      ] 1705 of 2000 complete in 1473.0 sec
[-----------------85%------------      ] 1706 of 2000 complete in 1473.9 sec
[-----------------85%------------      ] 1707 of 2000 complete in 1474.7 sec
[-----------------85%------------      ] 1708 of 2000 complete in 1475.6 sec
[-----------------85%------------      ] 1709 of 2000 complete in 1476.5 sec
[-----------------85%------------      ] 1710 of 2000 complete in 1477.4 sec
[-----------------85%------------      ] 1711 of 2000 complete in 1478.3 sec
[-----------------85%------------      ] 1712 of 2000 complete in 1479.1 sec
[-----------------85%------------      ] 1713 of 2000 complete in 1480.0 sec
[-----------------85%------------      ] 1714 of 2000 complete in 1480.9 sec
[-----------------85%------------      ] 1715 of 2000 complete in 1481.7 sec
[-----------------85%------------      ] 1716 of 2000 complete in 1482.6 sec
[-----------------85%------------      ] 1717 of 2000 complete in 1483.4 sec
[-----------------85%------------      ] 1718 of 2000 complete in 1484.3 sec
[-----------------85%------------      ] 1719 of 2000 complete in 1485.1 sec
[-----------------86%------------      ] 1720 of 2000 complete in 1486.1 sec
[-----------------86%------------      ] 1721 of 2000 complete in 1486.9 sec
[-----------------86%------------      ] 1722 of 2000 complete in 1487.8 sec
[-----------------86%------------      ] 1723 of 2000 complete in 1488.7 sec
[-----------------86%------------      ] 1724 of 2000 complete in 1489.6 sec
[-----------------86%------------      ] 1725 of 2000 complete in 1490.5 sec
[-----------------86%------------      ] 1726 of 2000 complete in 1491.4 sec
[-----------------86%------------      ] 1727 of 2000 complete in 1492.3 sec
[-----------------86%------------      ] 1728 of 2000 complete in 1493.2 sec
[-----------------86%------------      ] 1729 of 2000 complete in 1494.1 sec
[-----------------75%--------          ] 1516 of 2000 complete in 1406.3 sec
[-----------------75%--------          ] 1517 of 2000 complete in 1407.2 sec
[-----------------75%--------          ] 1518 of 2000 complete in 1408.1 sec
[-----------------75%--------          ] 1519 of 2000 complete in 1409.0 sec
[-----------------76%--------          ] 1520 of 2000 complete in 1409.9 sec
[-----------------76%--------          ] 1521 of 2000 complete in 1410.8 sec
[-----------------76%--------          ] 1522 of 2000 complete in 1411.7 sec
[-----------------76%--------          ] 1523 of 2000 complete in 1412.5 sec
[-----------------76%--------          ] 1524 of 2000 complete in 1413.4 sec
[-----------------76%--------          ] 1525 of 2000 complete in 1414.2 sec
[-----------------76%--------          ] 1526 of 2000 complete in 1415.0 sec
[-----------------76%---------         ] 1527 of 2000 complete in 1415.9 sec
[-----------------76%---------         ] 1528 of 2000 complete in 1416.7 sec
[-----------------76%---------         ] 1529 of 2000 complete in 1417.6 sec
[-----------------76%---------         ] 1530 of 2000 complete in 1418.4 sec
[-----------------76%---------         ] 1531 of 2000 complete in 1419.3 sec
[-----------------76%---------         ] 1532 of 2000 complete in 1420.2 sec
[-----------------76%---------         ] 1533 of 2000 complete in 1421.0 sec
[-----------------76%---------         ] 1534 of 2000 complete in 1421.9 sec
[-----------------76%---------         ] 1535 of 2000 complete in 1422.8 sec
[-----------------76%---------         ] 1536 of 2000 complete in 1423.7 sec
[-----------------76%---------         ] 1537 of 2000 complete in 1424.6 sec
[-----------------76%---------         ] 1538 of 2000 complete in 1425.5 sec
[-----------------76%---------         ] 1539 of 2000 complete in 1426.4 sec
[-----------------77%---------         ] 1540 of 2000 complete in 1427.3 sec
[-----------------77%---------         ] 1541 of 2000 complete in 1428.2 sec
[-----------------77%---------         ] 1542 of 2000 complete in 1429.0 sec
[-----------------77%---------         ] 1543 of 2000 complete in 1429.9 sec
[-----------------77%---------         ] 1544 of 2000 complete in 1430.8 sec
[-----------------77%---------         ] 1545 of 2000 complete in 1431.7 sec
[-----------------77%---------         ] 1546 of 2000 complete in 1432.6 sec
[-----------------77%---------         ] 1547 of 2000 complete in 1433.5 sec
[-----------------77%---------         ] 1548 of 2000 complete in 1434.5 sec
[-----------------77%---------         ] 1549 of 2000 complete in 1435.4 sec
[-----------------77%---------         ] 1550 of 2000 complete in 1436.4 sec
[-----------------77%---------         ] 1551 of 2000 complete in 1437.4 sec
[-----------------77%---------         ] 1552 of 2000 complete in 1438.3 sec
[-----------------77%---------         ] 1553 of 2000 complete in 1439.3 sec
[-----------------77%---------         ] 1554 of 2000 complete in 1440.3 sec
[-----------------77%---------         ] 1555 of 2000 complete in 1441.2 sec
[-----------------77%---------         ] 1556 of 2000 complete in 1442.2 sec
[-----------------77%---------         ] 1557 of 2000 complete in 1443.1 sec
[-----------------77%---------         ] 1558 of 2000 complete in 1444.0 sec
[-----------------77%---------         ] 1559 of 2000 complete in 1445.0 sec
[-----------------78%---------         ] 1560 of 2000 complete in 1445.9 sec
[-----------------78%---------         ] 1561 of 2000 complete in 1446.8 sec
[-----------------78%---------         ] 1562 of 2000 complete in 1447.7 sec
[-----------------78%---------         ] 1563 of 2000 complete in 1448.6 sec
[-----------------78%---------         ] 1564 of 2000 complete in 1449.5 sec
[-----------------78%---------         ] 1565 of 2000 complete in 1450.4 sec
[-----------------78%---------         ] 1566 of 2000 complete in 1451.3 sec
[-----------------78%---------         ] 1567 of 2000 complete in 1452.2 sec
[-----------------78%---------         ] 1568 of 2000 complete in 1453.1 sec
[-----------------78%---------         ] 1569 of 2000 complete in 1454.0 sec
[-----------------78%---------         ] 1570 of 2000 complete in 1455.0 sec
[-----------------78%---------         ] 1571 of 2000 complete in 1455.9 sec
[-----------------78%---------         ] 1572 of 2000 complete in 1456.8 sec
[-----------------78%---------         ] 1573 of 2000 complete in 1457.7 sec
[-----------------78%---------         ] 1574 of 2000 complete in 1458.7 sec
[-----------------78%---------         ] 1575 of 2000 complete in 1459.6 sec
[-----------------78%---------         ] 1576 of 2000 complete in 1460.6 sec
[-----------------78%---------         ] 1577 of 2000 complete in 1461.5 sec
[-----------------78%---------         ] 1578 of 2000 complete in 1462.5 sec
[-----------------78%----------        ] 1579 of 2000 complete in 1463.4 sec
[-----------------79%----------        ] 1580 of 2000 complete in 1464.3 sec
[-----------------79%----------        ] 1581 of 2000 complete in 1465.3 sec
[-----------------79%----------        ] 1582 of 2000 complete in 1466.2 sec
[-----------------79%----------        ] 1583 of 2000 complete in 1467.1 sec
[-----------------79%----------        ] 1584 of 2000 complete in 1468.1 sec
[-----------------79%----------        ] 1585 of 2000 complete in 1469.1 sec
[-----------------79%----------        ] 1586 of 2000 complete in 1470.1 sec
[-----------------79%----------        ] 1587 of 2000 complete in 1471.0 sec
[-----------------79%----------        ] 1588 of 2000 complete in 1471.9 sec
[-----------------79%----------        ] 1589 of 2000 complete in 1472.9 sec
[-----------------79%----------        ] 1590 of 2000 complete in 1473.9 sec
[-----------------79%----------        ] 1591 of 2000 complete in 1474.9 sec
[-----------------79%----------        ] 1592 of 2000 complete in 1475.9 sec
[-----------------79%----------        ] 1593 of 2000 complete in 1476.8 sec
[-----------------79%----------        ] 1594 of 2000 complete in 1477.8 sec
[-----------------79%----------        ] 1595 of 2000 complete in 1478.7 sec
[-----------------79%----------        ] 1596 of 2000 complete in 1479.7 sec
[-----------------79%----------        ] 1597 of 2000 complete in 1480.6 sec
[-----------------79%----------        ] 1598 of 2000 complete in 1481.6 sec
[-----------------79%----------        ] 1599 of 2000 complete in 1482.5 sec
[-----------------80%----------        ] 1600 of 2000 complete in 1483.4 sec
[-----------------80%----------        ] 1601 of 2000 complete in 1484.3 sec
[-----------------80%----------        ] 1602 of 2000 complete in 1485.3 sec
[-----------------80%----------        ] 1603 of 2000 complete in 1486.2 sec
[-----------------80%----------        ] 1604 of 2000 complete in 1487.1 sec
[-----------------80%----------        ] 1605 of 2000 complete in 1488.0 sec
[-----------------80%----------        ] 1606 of 2000 complete in 1488.8 sec
[-----------------80%----------        ] 1607 of 2000 complete in 1489.7 sec
[-----------------80%----------        ] 1608 of 2000 complete in 1490.6 sec
[-----------------80%----------        ] 1609 of 2000 complete in 1491.4 sec
[-----------------80%----------        ] 1610 of 2000 complete in 1492.4 sec
[-----------------80%----------        ] 1611 of 2000 complete in 1493.3 sec
[-----------------80%----------        ] 1612 of 2000 complete in 1494.2 sec
[-----------------80%----------        ] 1613 of 2000 complete in 1495.2 sec
[-----------------80%----------        ] 1614 of 2000 complete in 1496.1 sec
[-----------------80%----------        ] 1615 of 2000 complete in 1497.1 sec
[-----------------80%----------        ] 1616 of 2000 complete in 1497.9 sec
[-----------------80%----------        ] 1617 of 2000 complete in 1498.8 sec
[-----------------80%----------        ] 1618 of 2000 complete in 1499.7 sec
[-----------------80%----------        ] 1619 of 2000 complete in 1500.6 sec
[-----------------81%----------        ] 1620 of 2000 complete in 1501.5 sec
[-----------------81%----------        ] 1621 of 2000 complete in 1502.4 sec

[-----------------81%----------        ] 1624 of 2000 complete in 1413.3 sec
[-----------------81%----------        ] 1625 of 2000 complete in 1414.2 sec
[-----------------81%----------        ] 1626 of 2000 complete in 1415.0 sec
[-----------------81%----------        ] 1627 of 2000 complete in 1415.9 sec
[-----------------81%----------        ] 1628 of 2000 complete in 1416.7 sec
[-----------------81%----------        ] 1629 of 2000 complete in 1417.5 sec
[-----------------81%----------        ] 1630 of 2000 complete in 1418.4 sec
[-----------------81%----------        ] 1631 of 2000 complete in 1419.2 sec
[-----------------81%-----------       ] 1632 of 2000 complete in 1420.1 sec
[-----------------81%-----------       ] 1633 of 2000 complete in 1420.9 sec
[-----------------81%-----------       ] 1634 of 2000 complete in 1421.8 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 1422.6 sec
[-----------------81%-----------       ] 1636 of 2000 complete in 1423.4 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 1424.2 sec
[-----------------81%-----------       ] 1638 of 2000 complete in 1425.0 sec
[-----------------81%-----------       ] 1639 of 2000 complete in 1425.8 sec
[-----------------82%-----------       ] 1640 of 2000 complete in 1426.6 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 1427.4 sec
[-----------------82%-----------       ] 1642 of 2000 complete in 1428.2 sec
[-----------------82%-----------       ] 1643 of 2000 complete in 1429.0 sec
[-----------------82%-----------       ] 1644 of 2000 complete in 1429.8 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 1430.6 sec
[-----------------82%-----------       ] 1646 of 2000 complete in 1431.5 sec
[-----------------82%-----------       ] 1647 of 2000 complete in 1432.3 sec
[-----------------82%-----------       ] 1648 of 2000 complete in 1433.2 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 1434.0 sec
[-----------------82%-----------       ] 1650 of 2000 complete in 1434.8 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 1435.7 sec
[-----------------82%-----------       ] 1652 of 2000 complete in 1436.5 sec
[-----------------82%-----------       ] 1653 of 2000 complete in 1437.4 sec
[-----------------82%-----------       ] 1654 of 2000 complete in 1438.2 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 1439.1 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 1439.9 sec
[-----------------82%-----------       ] 1657 of 2000 complete in 1440.8 sec
[-----------------82%-----------       ] 1658 of 2000 complete in 1441.7 sec
[-----------------82%-----------       ] 1659 of 2000 complete in 1442.5 sec
[-----------------83%-----------       ] 1660 of 2000 complete in 1443.5 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 1444.4 sec
[-----------------83%-----------       ] 1662 of 2000 complete in 1445.3 sec
[-----------------83%-----------       ] 1663 of 2000 complete in 1446.1 sec
[-----------------83%-----------       ] 1664 of 2000 complete in 1447.0 sec
[-----------------83%-----------       ] 1665 of 2000 complete in 1447.9 sec
[-----------------83%-----------       ] 1666 of 2000 complete in 1448.8 sec
[-----------------83%-----------       ] 1667 of 2000 complete in 1449.7 sec
[-----------------83%-----------       ] 1668 of 2000 complete in 1450.6 sec
[-----------------83%-----------       ] 1669 of 2000 complete in 1451.4 sec
[-----------------83%-----------       ] 1670 of 2000 complete in 1452.4 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 1453.3 sec
[-----------------83%-----------       ] 1672 of 2000 complete in 1454.2 sec
[-----------------83%-----------       ] 1673 of 2000 complete in 1455.1 sec
[-----------------83%-----------       ] 1674 of 2000 complete in 1456.0 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 1456.9 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 1457.9 sec
[-----------------83%-----------       ] 1677 of 2000 complete in 1458.8 sec
[-----------------83%-----------       ] 1678 of 2000 complete in 1459.7 sec
[-----------------83%-----------       ] 1679 of 2000 complete in 1460.6 sec
[-----------------84%-----------       ] 1680 of 2000 complete in 1461.5 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 1462.4 sec
[-----------------84%-----------       ] 1682 of 2000 complete in 1463.2 sec
[-----------------84%-----------       ] 1683 of 2000 complete in 1464.1 sec
[-----------------84%-----------       ] 1684 of 2000 complete in 1465.0 sec
[-----------------84%------------      ] 1685 of 2000 complete in 1465.8 sec
[-----------------84%------------      ] 1686 of 2000 complete in 1466.7 sec
[-----------------84%------------      ] 1687 of 2000 complete in 1467.5 sec
[-----------------84%------------      ] 1688 of 2000 complete in 1468.4 sec
[-----------------84%------------      ] 1689 of 2000 complete in 1469.3 sec
[-----------------84%------------      ] 1690 of 2000 complete in 1470.1 sec
[-----------------84%------------      ] 1691 of 2000 complete in 1471.0 sec
[-----------------84%------------      ] 1692 of 2000 complete in 1471.9 sec
[-----------------84%------------      ] 1693 of 2000 complete in 1472.7 sec
[-----------------84%------------      ] 1694 of 2000 complete in 1473.6 sec
[-----------------84%------------      ] 1695 of 2000 complete in 1474.5 sec
[-----------------84%------------      ] 1696 of 2000 complete in 1475.4 sec
[-----------------84%------------      ] 1697 of 2000 complete in 1476.3 sec
[-----------------84%------------      ] 1698 of 2000 complete in 1477.2 sec
[-----------------84%------------      ] 1699 of 2000 complete in 1478.0 sec
[-----------------85%------------      ] 1700 of 2000 complete in 1478.9 sec
[-----------------85%------------      ] 1701 of 2000 complete in 1479.9 sec
[-----------------85%------------      ] 1702 of 2000 complete in 1480.8 sec
[-----------------85%------------      ] 1703 of 2000 complete in 1481.8 sec
[-----------------85%------------      ] 1704 of 2000 complete in 1482.7 sec
[-----------------85%------------      ] 1705 of 2000 complete in 1483.6 sec
[-----------------85%------------      ] 1706 of 2000 complete in 1484.6 sec
[-----------------85%------------      ] 1707 of 2000 complete in 1485.5 sec
[-----------------85%------------      ] 1708 of 2000 complete in 1486.4 sec
[-----------------85%------------      ] 1709 of 2000 complete in 1487.3 sec
[-----------------85%------------      ] 1710 of 2000 complete in 1488.3 sec
[-----------------85%------------      ] 1711 of 2000 complete in 1489.2 sec
[-----------------85%------------      ] 1712 of 2000 complete in 1490.1 sec
[-----------------85%------------      ] 1713 of 2000 complete in 1491.0 sec
[-----------------85%------------      ] 1714 of 2000 complete in 1491.8 sec
[-----------------85%------------      ] 1715 of 2000 complete in 1492.7 sec
[-----------------85%------------      ] 1716 of 2000 complete in 1493.6 sec
[-----------------85%------------      ] 1717 of 2000 complete in 1494.5 sec
[-----------------85%------------      ] 1718 of 2000 complete in 1495.5 sec
[-----------------85%------------      ] 1719 of 2000 complete in 1496.4 sec
[-----------------86%------------      ] 1720 of 2000 complete in 1497.2 sec
[-----------------86%------------      ] 1721 of 2000 complete in 1498.1 sec
[-----------------86%------------      ] 1722 of 2000 complete in 1499.0 sec
[-----------------86%------------      ] 1723 of 2000 complete in 1499.9 sec
[-----------------86%------------      ] 1724 of 2000 complete in 1500.8 sec
[-----------------86%------------      ] 1725 of 2000 complete in 1501.7 sec
[-----------------86%------------      ] 1726 of 2000 complete in 1502.6 sec
[-----------------86%------------      ] 1727 of 2000 complete in 1503.6 sec
[-----------------86%------------      ] 1728 of 2000 complete in 1504.5 sec
[-----------------86%------------      ] 1729 of 2000 complete in 1505.4 sec
[-----------------81%----------        ] 1622 of 2000 complete in 1487.4 sec
[-----------------81%----------        ] 1623 of 2000 complete in 1488.4 sec
[-----------------81%----------        ] 1624 of 2000 complete in 1489.3 sec
[-----------------81%----------        ] 1625 of 2000 complete in 1490.2 sec
[-----------------81%----------        ] 1626 of 2000 complete in 1491.1 sec
[-----------------81%----------        ] 1627 of 2000 complete in 1492.0 sec
[-----------------81%----------        ] 1628 of 2000 complete in 1493.0 sec
[-----------------81%----------        ] 1629 of 2000 complete in 1493.9 sec
[-----------------81%----------        ] 1630 of 2000 complete in 1495.0 sec
[-----------------81%----------        ] 1631 of 2000 complete in 1495.9 sec
[-----------------81%-----------       ] 1632 of 2000 complete in 1496.9 sec
[-----------------81%-----------       ] 1633 of 2000 complete in 1497.8 sec
[-----------------81%-----------       ] 1634 of 2000 complete in 1498.8 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 1499.7 sec
[-----------------81%-----------       ] 1636 of 2000 complete in 1500.7 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 1501.6 sec
[-----------------81%-----------       ] 1638 of 2000 complete in 1502.6 sec
[-----------------81%-----------       ] 1639 of 2000 complete in 1503.5 sec
[-----------------82%-----------       ] 1640 of 2000 complete in 1504.4 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 1505.3 sec
[-----------------82%-----------       ] 1642 of 2000 complete in 1506.2 sec
[-----------------82%-----------       ] 1643 of 2000 complete in 1507.1 sec
[-----------------82%-----------       ] 1644 of 2000 complete in 1507.9 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 1508.9 sec
[-----------------82%-----------       ] 1646 of 2000 complete in 1509.7 sec
[-----------------82%-----------       ] 1647 of 2000 complete in 1510.6 sec
[-----------------82%-----------       ] 1648 of 2000 complete in 1511.6 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 1512.5 sec
[-----------------82%-----------       ] 1650 of 2000 complete in 1513.4 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 1514.3 sec
[-----------------82%-----------       ] 1652 of 2000 complete in 1515.2 sec
[-----------------82%-----------       ] 1653 of 2000 complete in 1516.1 sec
[-----------------82%-----------       ] 1654 of 2000 complete in 1517.0 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 1517.8 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 1518.7 sec
[-----------------82%-----------       ] 1657 of 2000 complete in 1519.6 sec
[-----------------82%-----------       ] 1658 of 2000 complete in 1520.5 sec
[-----------------82%-----------       ] 1659 of 2000 complete in 1521.4 sec
[-----------------83%-----------       ] 1660 of 2000 complete in 1522.3 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 1523.1 sec
[-----------------83%-----------       ] 1662 of 2000 complete in 1524.0 sec
[-----------------83%-----------       ] 1663 of 2000 complete in 1524.9 sec
[-----------------83%-----------       ] 1664 of 2000 complete in 1525.7 sec
[-----------------83%-----------       ] 1665 of 2000 complete in 1526.6 sec
[-----------------83%-----------       ] 1666 of 2000 complete in 1527.5 sec
[-----------------83%-----------       ] 1667 of 2000 complete in 1528.3 sec
[-----------------83%-----------       ] 1668 of 2000 complete in 1529.1 sec
[-----------------83%-----------       ] 1669 of 2000 complete in 1529.9 sec
[-----------------83%-----------       ] 1670 of 2000 complete in 1530.7 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 1531.6 sec
[-----------------83%-----------       ] 1672 of 2000 complete in 1532.4 sec
[-----------------83%-----------       ] 1673 of 2000 complete in 1533.2 sec
[-----------------83%-----------       ] 1674 of 2000 complete in 1534.0 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 1534.8 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 1535.5 sec
[-----------------83%-----------       ] 1677 of 2000 complete in 1536.3 sec
[-----------------83%-----------       ] 1678 of 2000 complete in 1537.1 sec
[-----------------83%-----------       ] 1679 of 2000 complete in 1537.9 sec
[-----------------84%-----------       ] 1680 of 2000 complete in 1538.7 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 1539.5 sec
[-----------------84%-----------       ] 1682 of 2000 complete in 1540.3 sec
[-----------------84%-----------       ] 1683 of 2000 complete in 1541.2 sec
[-----------------84%-----------       ] 1684 of 2000 complete in 1541.9 sec
[-----------------84%------------      ] 1685 of 2000 complete in 1542.7 sec
[-----------------84%------------      ] 1686 of 2000 complete in 1543.5 sec
[-----------------84%------------      ] 1687 of 2000 complete in 1544.3 sec
[-----------------84%------------      ] 1688 of 2000 complete in 1545.1 sec
[-----------------84%------------      ] 1689 of 2000 complete in 1545.9 sec
[-----------------84%------------      ] 1690 of 2000 complete in 1546.8 sec
[-----------------84%------------      ] 1691 of 2000 complete in 1547.6 sec
[-----------------84%------------      ] 1692 of 2000 complete in 1548.4 sec
[-----------------84%------------      ] 1693 of 2000 complete in 1549.2 sec
[-----------------84%------------      ] 1694 of 2000 complete in 1550.0 sec
[-----------------84%------------      ] 1695 of 2000 complete in 1550.8 sec
[-----------------84%------------      ] 1696 of 2000 complete in 1551.5 sec
[-----------------84%------------      ] 1697 of 2000 complete in 1552.3 sec
[-----------------84%------------      ] 1698 of 2000 complete in 1553.1 sec
[-----------------84%------------      ] 1699 of 2000 complete in 1553.8 sec
[-----------------85%------------      ] 1700 of 2000 complete in 1554.7 sec
[-----------------85%------------      ] 1701 of 2000 complete in 1555.5 sec
[-----------------85%------------      ] 1702 of 2000 complete in 1556.3 sec
[-----------------85%------------      ] 1703 of 2000 complete in 1557.2 sec
[-----------------85%------------      ] 1704 of 2000 complete in 1558.0 sec
[-----------------85%------------      ] 1705 of 2000 complete in 1558.8 sec
[-----------------85%------------      ] 1706 of 2000 complete in 1559.6 sec
[-----------------85%------------      ] 1707 of 2000 complete in 1560.4 sec
[-----------------85%------------      ] 1708 of 2000 complete in 1561.2 sec
[-----------------85%------------      ] 1709 of 2000 complete in 1562.0 sec
[-----------------85%------------      ] 1710 of 2000 complete in 1562.8 sec
[-----------------85%------------      ] 1711 of 2000 complete in 1563.7 sec
[-----------------85%------------      ] 1712 of 2000 complete in 1564.5 sec
[-----------------85%------------      ] 1713 of 2000 complete in 1565.3 sec
[-----------------85%------------      ] 1714 of 2000 complete in 1566.1 sec
[-----------------85%------------      ] 1715 of 2000 complete in 1566.9 sec
[-----------------85%------------      ] 1716 of 2000 complete in 1567.8 sec
[-----------------85%------------      ] 1717 of 2000 complete in 1568.6 sec
[-----------------85%------------      ] 1718 of 2000 complete in 1569.4 sec
[-----------------85%------------      ] 1719 of 2000 complete in 1570.2 sec
[-----------------86%------------      ] 1720 of 2000 complete in 1571.0 sec
[-----------------86%------------      ] 1721 of 2000 complete in 1571.8 sec
[-----------------86%------------      ] 1722 of 2000 complete in 1572.6 sec
[-----------------86%------------      ] 1723 of 2000 complete in 1573.4 sec
[-----------------86%------------      ] 1724 of 2000 complete in 1574.2 sec
[-----------------86%------------      ] 1725 of 2000 complete in 1575.0 sec
[-----------------86%------------      ] 1726 of 2000 complete in 1575.8 sec
[-----------------86%------------      ] 1727 of 2000 complete in 1576.6 sec

[-----------------86%------------      ] 1730 of 2000 complete in 1495.0 sec
[-----------------86%------------      ] 1731 of 2000 complete in 1496.0 sec
[-----------------86%------------      ] 1732 of 2000 complete in 1496.9 sec
[-----------------86%------------      ] 1733 of 2000 complete in 1497.8 sec
[-----------------86%------------      ] 1734 of 2000 complete in 1498.7 sec
[-----------------86%------------      ] 1735 of 2000 complete in 1499.6 sec
[-----------------86%------------      ] 1736 of 2000 complete in 1500.5 sec
[-----------------86%-------------     ] 1737 of 2000 complete in 1501.5 sec
[-----------------86%-------------     ] 1738 of 2000 complete in 1502.5 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 1503.4 sec
[-----------------87%-------------     ] 1740 of 2000 complete in 1504.3 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 1505.3 sec
[-----------------87%-------------     ] 1742 of 2000 complete in 1506.2 sec
[-----------------87%-------------     ] 1743 of 2000 complete in 1507.2 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 1508.1 sec
[-----------------87%-------------     ] 1745 of 2000 complete in 1509.1 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 1510.0 sec
[-----------------87%-------------     ] 1747 of 2000 complete in 1511.0 sec
[-----------------87%-------------     ] 1748 of 2000 complete in 1511.9 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 1512.8 sec
[-----------------87%-------------     ] 1750 of 2000 complete in 1513.8 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 1514.7 sec
[-----------------87%-------------     ] 1752 of 2000 complete in 1515.5 sec
[-----------------87%-------------     ] 1753 of 2000 complete in 1516.4 sec
[-----------------87%-------------     ] 1754 of 2000 complete in 1517.2 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 1518.1 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 1518.9 sec
[-----------------87%-------------     ] 1757 of 2000 complete in 1519.8 sec
[-----------------87%-------------     ] 1758 of 2000 complete in 1520.6 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 1521.5 sec
[-----------------88%-------------     ] 1760 of 2000 complete in 1522.3 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 1523.2 sec
[-----------------88%-------------     ] 1762 of 2000 complete in 1524.1 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 1524.9 sec
[-----------------88%-------------     ] 1764 of 2000 complete in 1525.8 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 1526.7 sec
[-----------------88%-------------     ] 1766 of 2000 complete in 1527.7 sec
[-----------------88%-------------     ] 1767 of 2000 complete in 1528.5 sec
[-----------------88%-------------     ] 1768 of 2000 complete in 1529.4 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 1530.3 sec
[-----------------88%-------------     ] 1770 of 2000 complete in 1531.2 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 1532.0 sec
[-----------------88%-------------     ] 1772 of 2000 complete in 1533.0 sec
[-----------------88%-------------     ] 1773 of 2000 complete in 1533.9 sec
[-----------------88%-------------     ] 1774 of 2000 complete in 1534.8 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 1535.7 sec
[-----------------88%-------------     ] 1776 of 2000 complete in 1536.6 sec
[-----------------88%-------------     ] 1777 of 2000 complete in 1537.5 sec
[-----------------88%-------------     ] 1778 of 2000 complete in 1538.4 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 1539.2 sec
[-----------------89%-------------     ] 1780 of 2000 complete in 1540.1 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 1541.0 sec
[-----------------89%-------------     ] 1782 of 2000 complete in 1541.8 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 1542.6 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 1543.5 sec
[-----------------89%-------------     ] 1785 of 2000 complete in 1544.4 sec
[-----------------89%-------------     ] 1786 of 2000 complete in 1545.2 sec
[-----------------89%-------------     ] 1787 of 2000 complete in 1546.0 sec
[-----------------89%-------------     ] 1788 of 2000 complete in 1546.9 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 1547.7 sec
[-----------------89%--------------    ] 1790 of 2000 complete in 1548.6 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 1549.5 sec
[-----------------89%--------------    ] 1792 of 2000 complete in 1550.3 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 1551.2 sec
[-----------------89%--------------    ] 1794 of 2000 complete in 1552.1 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 1553.0 sec
[-----------------89%--------------    ] 1796 of 2000 complete in 1553.8 sec
[-----------------89%--------------    ] 1797 of 2000 complete in 1554.7 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 1555.6 sec
[-----------------89%--------------    ] 1799 of 2000 complete in 1556.4 sec
[-----------------90%--------------    ] 1800 of 2000 complete in 1557.3 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 1558.1 sec
[-----------------90%--------------    ] 1802 of 2000 complete in 1559.0 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 1559.8 sec
[-----------------90%--------------    ] 1804 of 2000 complete in 1560.7 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 1561.6 sec
[-----------------90%--------------    ] 1806 of 2000 complete in 1562.5 sec
[-----------------90%--------------    ] 1807 of 2000 complete in 1563.3 sec
[-----------------90%--------------    ] 1808 of 2000 complete in 1564.2 sec
[-----------------90%--------------    ] 1809 of 2000 complete in 1565.1 sec
[-----------------90%--------------    ] 1810 of 2000 complete in 1566.0 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 1566.8 sec
[-----------------90%--------------    ] 1812 of 2000 complete in 1567.7 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 1568.6 sec
[-----------------90%--------------    ] 1814 of 2000 complete in 1569.4 sec
[-----------------90%--------------    ] 1815 of 2000 complete in 1570.3 sec
[-----------------90%--------------    ] 1816 of 2000 complete in 1571.2 sec
[-----------------90%--------------    ] 1817 of 2000 complete in 1572.0 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 1572.8 sec
[-----------------90%--------------    ] 1819 of 2000 complete in 1573.7 sec
[-----------------91%--------------    ] 1820 of 2000 complete in 1574.5 sec
[-----------------91%--------------    ] 1821 of 2000 complete in 1575.4 sec
[-----------------91%--------------    ] 1822 of 2000 complete in 1576.2 sec
[-----------------91%--------------    ] 1823 of 2000 complete in 1577.0 sec
[-----------------91%--------------    ] 1824 of 2000 complete in 1577.9 sec
[-----------------91%--------------    ] 1825 of 2000 complete in 1578.7 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 1579.5 sec
[-----------------91%--------------    ] 1827 of 2000 complete in 1580.4 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 1581.2 sec
[-----------------91%--------------    ] 1829 of 2000 complete in 1582.1 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 1582.9 sec
[-----------------91%--------------    ] 1831 of 2000 complete in 1583.7 sec
[-----------------91%--------------    ] 1832 of 2000 complete in 1584.5 sec
[-----------------91%--------------    ] 1833 of 2000 complete in 1585.3 sec
[-----------------91%--------------    ] 1834 of 2000 complete in 1586.2 sec
[-----------------91%--------------    ] 1835 of 2000 complete in 1587.0 sec
[-----------------81%----------        ] 1622 of 2000 complete in 1503.3 sec
[-----------------81%----------        ] 1623 of 2000 complete in 1504.2 sec
[-----------------81%----------        ] 1624 of 2000 complete in 1505.0 sec
[-----------------81%----------        ] 1625 of 2000 complete in 1505.9 sec
[-----------------81%----------        ] 1626 of 2000 complete in 1506.8 sec
[-----------------81%----------        ] 1627 of 2000 complete in 1507.7 sec
[-----------------81%----------        ] 1628 of 2000 complete in 1508.5 sec
[-----------------81%----------        ] 1629 of 2000 complete in 1509.3 sec
[-----------------81%----------        ] 1630 of 2000 complete in 1510.2 sec
[-----------------81%----------        ] 1631 of 2000 complete in 1511.1 sec
[-----------------81%-----------       ] 1632 of 2000 complete in 1512.0 sec
[-----------------81%-----------       ] 1633 of 2000 complete in 1512.9 sec
[-----------------81%-----------       ] 1634 of 2000 complete in 1513.8 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 1514.7 sec
[-----------------81%-----------       ] 1636 of 2000 complete in 1515.5 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 1516.4 sec
[-----------------81%-----------       ] 1638 of 2000 complete in 1517.2 sec
[-----------------81%-----------       ] 1639 of 2000 complete in 1518.1 sec
[-----------------82%-----------       ] 1640 of 2000 complete in 1518.9 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 1519.7 sec
[-----------------82%-----------       ] 1642 of 2000 complete in 1520.5 sec
[-----------------82%-----------       ] 1643 of 2000 complete in 1521.3 sec
[-----------------82%-----------       ] 1644 of 2000 complete in 1522.1 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 1522.9 sec
[-----------------82%-----------       ] 1646 of 2000 complete in 1523.7 sec
[-----------------82%-----------       ] 1647 of 2000 complete in 1524.5 sec
[-----------------82%-----------       ] 1648 of 2000 complete in 1525.3 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 1526.1 sec
[-----------------82%-----------       ] 1650 of 2000 complete in 1526.9 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 1527.7 sec
[-----------------82%-----------       ] 1652 of 2000 complete in 1528.4 sec
[-----------------82%-----------       ] 1653 of 2000 complete in 1529.2 sec
[-----------------82%-----------       ] 1654 of 2000 complete in 1530.0 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 1530.8 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 1531.6 sec
[-----------------82%-----------       ] 1657 of 2000 complete in 1532.3 sec
[-----------------82%-----------       ] 1658 of 2000 complete in 1533.1 sec
[-----------------82%-----------       ] 1659 of 2000 complete in 1533.9 sec
[-----------------83%-----------       ] 1660 of 2000 complete in 1534.7 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 1535.5 sec
[-----------------83%-----------       ] 1662 of 2000 complete in 1536.2 sec
[-----------------83%-----------       ] 1663 of 2000 complete in 1537.0 sec
[-----------------83%-----------       ] 1664 of 2000 complete in 1537.8 sec
[-----------------83%-----------       ] 1665 of 2000 complete in 1538.6 sec
[-----------------83%-----------       ] 1666 of 2000 complete in 1539.4 sec
[-----------------83%-----------       ] 1667 of 2000 complete in 1540.2 sec
[-----------------83%-----------       ] 1668 of 2000 complete in 1540.9 sec
[-----------------83%-----------       ] 1669 of 2000 complete in 1541.6 sec
[-----------------83%-----------       ] 1670 of 2000 complete in 1542.4 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 1543.2 sec
[-----------------83%-----------       ] 1672 of 2000 complete in 1543.9 sec
[-----------------83%-----------       ] 1673 of 2000 complete in 1544.7 sec
[-----------------83%-----------       ] 1674 of 2000 complete in 1545.5 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 1546.2 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 1547.0 sec
[-----------------83%-----------       ] 1677 of 2000 complete in 1547.8 sec
[-----------------83%-----------       ] 1678 of 2000 complete in 1548.5 sec
[-----------------83%-----------       ] 1679 of 2000 complete in 1549.3 sec
[-----------------84%-----------       ] 1680 of 2000 complete in 1550.0 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 1550.7 sec
[-----------------84%-----------       ] 1682 of 2000 complete in 1551.5 sec
[-----------------84%-----------       ] 1683 of 2000 complete in 1552.3 sec
[-----------------84%-----------       ] 1684 of 2000 complete in 1553.0 sec
[-----------------84%------------      ] 1685 of 2000 complete in 1553.8 sec
[-----------------84%------------      ] 1686 of 2000 complete in 1554.6 sec
[-----------------84%------------      ] 1687 of 2000 complete in 1555.4 sec
[-----------------84%------------      ] 1688 of 2000 complete in 1556.2 sec
[-----------------84%------------      ] 1689 of 2000 complete in 1557.0 sec
[-----------------84%------------      ] 1690 of 2000 complete in 1557.9 sec
[-----------------84%------------      ] 1691 of 2000 complete in 1558.7 sec
[-----------------84%------------      ] 1692 of 2000 complete in 1559.6 sec
[-----------------84%------------      ] 1693 of 2000 complete in 1560.4 sec
[-----------------84%------------      ] 1694 of 2000 complete in 1561.2 sec
[-----------------84%------------      ] 1695 of 2000 complete in 1562.0 sec
[-----------------84%------------      ] 1696 of 2000 complete in 1562.8 sec
[-----------------84%------------      ] 1697 of 2000 complete in 1563.6 sec
[-----------------84%------------      ] 1698 of 2000 complete in 1564.4 sec
[-----------------84%------------      ] 1699 of 2000 complete in 1565.2 sec
[-----------------85%------------      ] 1700 of 2000 complete in 1566.0 sec
[-----------------85%------------      ] 1701 of 2000 complete in 1566.8 sec
[-----------------85%------------      ] 1702 of 2000 complete in 1567.6 sec
[-----------------85%------------      ] 1703 of 2000 complete in 1568.4 sec
[-----------------85%------------      ] 1704 of 2000 complete in 1569.2 sec
[-----------------85%------------      ] 1705 of 2000 complete in 1570.1 sec
[-----------------85%------------      ] 1706 of 2000 complete in 1570.9 sec
[-----------------85%------------      ] 1707 of 2000 complete in 1571.7 sec
[-----------------85%------------      ] 1708 of 2000 complete in 1572.6 sec
[-----------------85%------------      ] 1709 of 2000 complete in 1573.4 sec
[-----------------85%------------      ] 1710 of 2000 complete in 1574.3 sec
[-----------------85%------------      ] 1711 of 2000 complete in 1575.1 sec
[-----------------85%------------      ] 1712 of 2000 complete in 1575.9 sec
[-----------------85%------------      ] 1713 of 2000 complete in 1576.7 sec
[-----------------85%------------      ] 1714 of 2000 complete in 1577.5 sec
[-----------------85%------------      ] 1715 of 2000 complete in 1578.3 sec
[-----------------85%------------      ] 1716 of 2000 complete in 1579.1 sec
[-----------------85%------------      ] 1717 of 2000 complete in 1579.9 sec
[-----------------85%------------      ] 1718 of 2000 complete in 1580.7 sec
[-----------------85%------------      ] 1719 of 2000 complete in 1581.4 sec
[-----------------86%------------      ] 1720 of 2000 complete in 1582.3 sec
[-----------------86%------------      ] 1721 of 2000 complete in 1583.0 sec
[-----------------86%------------      ] 1722 of 2000 complete in 1583.8 sec
[-----------------86%------------      ] 1723 of 2000 complete in 1584.6 sec
[-----------------86%------------      ] 1724 of 2000 complete in 1585.4 sec
[-----------------86%------------      ] 1725 of 2000 complete in 1586.2 sec
[-----------------86%------------      ] 1726 of 2000 complete in 1587.1 sec
[-----------------86%------------      ] 1727 of 2000 complete in 1587.9 sec

[-----------------86%------------      ] 1730 of 2000 complete in 1506.3 sec
[-----------------86%------------      ] 1731 of 2000 complete in 1507.2 sec
[-----------------86%------------      ] 1732 of 2000 complete in 1508.1 sec
[-----------------86%------------      ] 1733 of 2000 complete in 1509.1 sec
[-----------------86%------------      ] 1734 of 2000 complete in 1510.0 sec
[-----------------86%------------      ] 1735 of 2000 complete in 1510.9 sec
[-----------------86%------------      ] 1736 of 2000 complete in 1511.7 sec
[-----------------86%-------------     ] 1737 of 2000 complete in 1512.7 sec
[-----------------86%-------------     ] 1738 of 2000 complete in 1513.6 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 1514.4 sec
[-----------------87%-------------     ] 1740 of 2000 complete in 1515.3 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 1516.2 sec
[-----------------87%-------------     ] 1742 of 2000 complete in 1517.1 sec
[-----------------87%-------------     ] 1743 of 2000 complete in 1518.0 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 1518.8 sec
[-----------------87%-------------     ] 1745 of 2000 complete in 1519.7 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 1520.5 sec
[-----------------87%-------------     ] 1747 of 2000 complete in 1521.3 sec
[-----------------87%-------------     ] 1748 of 2000 complete in 1522.2 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 1523.0 sec
[-----------------87%-------------     ] 1750 of 2000 complete in 1523.9 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 1524.7 sec
[-----------------87%-------------     ] 1752 of 2000 complete in 1525.6 sec
[-----------------87%-------------     ] 1753 of 2000 complete in 1526.5 sec
[-----------------87%-------------     ] 1754 of 2000 complete in 1527.3 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 1528.2 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 1529.0 sec
[-----------------87%-------------     ] 1757 of 2000 complete in 1529.9 sec
[-----------------87%-------------     ] 1758 of 2000 complete in 1530.7 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 1531.6 sec
[-----------------88%-------------     ] 1760 of 2000 complete in 1532.4 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 1533.3 sec
[-----------------88%-------------     ] 1762 of 2000 complete in 1534.1 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 1535.0 sec
[-----------------88%-------------     ] 1764 of 2000 complete in 1535.8 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 1536.6 sec
[-----------------88%-------------     ] 1766 of 2000 complete in 1537.5 sec
[-----------------88%-------------     ] 1767 of 2000 complete in 1538.3 sec
[-----------------88%-------------     ] 1768 of 2000 complete in 1539.1 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 1540.0 sec
[-----------------88%-------------     ] 1770 of 2000 complete in 1540.8 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 1541.7 sec
[-----------------88%-------------     ] 1772 of 2000 complete in 1542.6 sec
[-----------------88%-------------     ] 1773 of 2000 complete in 1543.5 sec
[-----------------88%-------------     ] 1774 of 2000 complete in 1544.3 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 1545.1 sec
[-----------------88%-------------     ] 1776 of 2000 complete in 1546.0 sec
[-----------------88%-------------     ] 1777 of 2000 complete in 1546.9 sec
[-----------------88%-------------     ] 1778 of 2000 complete in 1547.7 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 1548.6 sec
[-----------------89%-------------     ] 1780 of 2000 complete in 1549.4 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 1550.2 sec
[-----------------89%-------------     ] 1782 of 2000 complete in 1551.0 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 1551.9 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 1552.7 sec
[-----------------89%-------------     ] 1785 of 2000 complete in 1553.5 sec
[-----------------89%-------------     ] 1786 of 2000 complete in 1554.3 sec
[-----------------89%-------------     ] 1787 of 2000 complete in 1555.0 sec
[-----------------89%-------------     ] 1788 of 2000 complete in 1555.8 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 1556.6 sec
[-----------------89%--------------    ] 1790 of 2000 complete in 1557.4 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 1558.2 sec
[-----------------89%--------------    ] 1792 of 2000 complete in 1559.0 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 1559.9 sec
[-----------------89%--------------    ] 1794 of 2000 complete in 1560.7 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 1561.5 sec
[-----------------89%--------------    ] 1796 of 2000 complete in 1562.4 sec
[-----------------89%--------------    ] 1797 of 2000 complete in 1563.2 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 1564.0 sec
[-----------------89%--------------    ] 1799 of 2000 complete in 1564.8 sec
[-----------------90%--------------    ] 1800 of 2000 complete in 1565.7 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 1566.5 sec
[-----------------90%--------------    ] 1802 of 2000 complete in 1567.4 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 1568.3 sec
[-----------------90%--------------    ] 1804 of 2000 complete in 1569.1 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 1569.9 sec
[-----------------90%--------------    ] 1806 of 2000 complete in 1570.8 sec
[-----------------90%--------------    ] 1807 of 2000 complete in 1571.6 sec
[-----------------90%--------------    ] 1808 of 2000 complete in 1572.5 sec
[-----------------90%--------------    ] 1809 of 2000 complete in 1573.3 sec
[-----------------90%--------------    ] 1810 of 2000 complete in 1574.3 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 1575.2 sec
[-----------------90%--------------    ] 1812 of 2000 complete in 1576.1 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 1576.9 sec
[-----------------90%--------------    ] 1814 of 2000 complete in 1577.8 sec
[-----------------90%--------------    ] 1815 of 2000 complete in 1578.7 sec
[-----------------90%--------------    ] 1816 of 2000 complete in 1579.5 sec
[-----------------90%--------------    ] 1817 of 2000 complete in 1580.4 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 1581.2 sec
[-----------------90%--------------    ] 1819 of 2000 complete in 1582.1 sec
[-----------------91%--------------    ] 1820 of 2000 complete in 1582.9 sec
[-----------------91%--------------    ] 1821 of 2000 complete in 1583.8 sec
[-----------------91%--------------    ] 1822 of 2000 complete in 1584.7 sec
[-----------------91%--------------    ] 1823 of 2000 complete in 1585.5 sec
[-----------------91%--------------    ] 1824 of 2000 complete in 1586.4 sec
[-----------------91%--------------    ] 1825 of 2000 complete in 1587.3 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 1588.1 sec
[-----------------91%--------------    ] 1827 of 2000 complete in 1589.0 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 1589.8 sec
[-----------------91%--------------    ] 1829 of 2000 complete in 1590.7 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 1591.6 sec
[-----------------91%--------------    ] 1831 of 2000 complete in 1592.4 sec
[-----------------91%--------------    ] 1832 of 2000 complete in 1593.3 sec
[-----------------91%--------------    ] 1833 of 2000 complete in 1594.1 sec
[-----------------91%--------------    ] 1834 of 2000 complete in 1594.9 sec
[-----------------91%--------------    ] 1835 of 2000 complete in 1595.8 sec
[-----------------86%------------      ] 1728 of 2000 complete in 1577.4 sec
[-----------------86%------------      ] 1729 of 2000 complete in 1578.3 sec
[-----------------86%------------      ] 1730 of 2000 complete in 1579.1 sec
[-----------------86%------------      ] 1731 of 2000 complete in 1579.9 sec
[-----------------86%------------      ] 1732 of 2000 complete in 1580.7 sec
[-----------------86%------------      ] 1733 of 2000 complete in 1581.5 sec
[-----------------86%------------      ] 1734 of 2000 complete in 1582.3 sec
[-----------------86%------------      ] 1735 of 2000 complete in 1583.2 sec
[-----------------86%------------      ] 1736 of 2000 complete in 1584.0 sec
[-----------------86%-------------     ] 1737 of 2000 complete in 1584.8 sec
[-----------------86%-------------     ] 1738 of 2000 complete in 1585.7 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 1586.5 sec
[-----------------87%-------------     ] 1740 of 2000 complete in 1587.3 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 1588.1 sec
[-----------------87%-------------     ] 1742 of 2000 complete in 1588.9 sec
[-----------------87%-------------     ] 1743 of 2000 complete in 1589.8 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 1590.6 sec
[-----------------87%-------------     ] 1745 of 2000 complete in 1591.4 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 1592.2 sec
[-----------------87%-------------     ] 1747 of 2000 complete in 1593.0 sec
[-----------------87%-------------     ] 1748 of 2000 complete in 1593.8 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 1594.6 sec
[-----------------87%-------------     ] 1750 of 2000 complete in 1595.5 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 1596.3 sec
[-----------------87%-------------     ] 1752 of 2000 complete in 1597.1 sec
[-----------------87%-------------     ] 1753 of 2000 complete in 1597.9 sec
[-----------------87%-------------     ] 1754 of 2000 complete in 1598.7 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 1599.5 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 1600.3 sec
[-----------------87%-------------     ] 1757 of 2000 complete in 1601.1 sec
[-----------------87%-------------     ] 1758 of 2000 complete in 1601.8 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 1602.6 sec
[-----------------88%-------------     ] 1760 of 2000 complete in 1603.4 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 1604.1 sec
[-----------------88%-------------     ] 1762 of 2000 complete in 1604.9 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 1605.7 sec
[-----------------88%-------------     ] 1764 of 2000 complete in 1606.4 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 1607.2 sec
[-----------------88%-------------     ] 1766 of 2000 complete in 1608.0 sec
[-----------------88%-------------     ] 1767 of 2000 complete in 1608.7 sec
[-----------------88%-------------     ] 1768 of 2000 complete in 1609.5 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 1610.3 sec
[-----------------88%-------------     ] 1770 of 2000 complete in 1611.0 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 1611.8 sec
[-----------------88%-------------     ] 1772 of 2000 complete in 1612.6 sec
[-----------------88%-------------     ] 1773 of 2000 complete in 1613.4 sec
[-----------------88%-------------     ] 1774 of 2000 complete in 1614.2 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 1614.9 sec
[-----------------88%-------------     ] 1776 of 2000 complete in 1615.7 sec
[-----------------88%-------------     ] 1777 of 2000 complete in 1616.5 sec
[-----------------88%-------------     ] 1778 of 2000 complete in 1617.3 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 1618.1 sec
[-----------------89%-------------     ] 1780 of 2000 complete in 1618.9 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 1619.7 sec
[-----------------89%-------------     ] 1782 of 2000 complete in 1620.5 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 1621.3 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 1622.1 sec
[-----------------89%-------------     ] 1785 of 2000 complete in 1622.9 sec
[-----------------89%-------------     ] 1786 of 2000 complete in 1623.7 sec
[-----------------89%-------------     ] 1787 of 2000 complete in 1624.4 sec
[-----------------89%-------------     ] 1788 of 2000 complete in 1625.2 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 1625.9 sec
[-----------------89%--------------    ] 1790 of 2000 complete in 1626.7 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 1627.4 sec
[-----------------89%--------------    ] 1792 of 2000 complete in 1628.1 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 1628.9 sec
[-----------------89%--------------    ] 1794 of 2000 complete in 1629.6 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 1630.4 sec
[-----------------89%--------------    ] 1796 of 2000 complete in 1631.2 sec
[-----------------89%--------------    ] 1797 of 2000 complete in 1632.0 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 1632.8 sec
[-----------------89%--------------    ] 1799 of 2000 complete in 1633.6 sec
[-----------------90%--------------    ] 1800 of 2000 complete in 1634.3 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 1635.1 sec
[-----------------90%--------------    ] 1802 of 2000 complete in 1635.9 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 1636.7 sec
[-----------------90%--------------    ] 1804 of 2000 complete in 1637.4 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 1638.2 sec
[-----------------90%--------------    ] 1806 of 2000 complete in 1639.0 sec
[-----------------90%--------------    ] 1807 of 2000 complete in 1639.8 sec
[-----------------90%--------------    ] 1808 of 2000 complete in 1640.6 sec
[-----------------90%--------------    ] 1809 of 2000 complete in 1641.4 sec
[-----------------90%--------------    ] 1810 of 2000 complete in 1642.2 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 1643.0 sec
[-----------------90%--------------    ] 1812 of 2000 complete in 1643.7 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 1644.6 sec
[-----------------90%--------------    ] 1814 of 2000 complete in 1645.4 sec
[-----------------90%--------------    ] 1815 of 2000 complete in 1646.2 sec
[-----------------90%--------------    ] 1816 of 2000 complete in 1647.0 sec
[-----------------90%--------------    ] 1817 of 2000 complete in 1647.8 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 1648.6 sec
[-----------------90%--------------    ] 1819 of 2000 complete in 1649.5 sec
[-----------------91%--------------    ] 1820 of 2000 complete in 1650.3 sec
[-----------------91%--------------    ] 1821 of 2000 complete in 1651.2 sec
[-----------------91%--------------    ] 1822 of 2000 complete in 1652.0 sec
[-----------------91%--------------    ] 1823 of 2000 complete in 1652.8 sec
[-----------------91%--------------    ] 1824 of 2000 complete in 1653.7 sec
[-----------------91%--------------    ] 1825 of 2000 complete in 1654.5 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 1655.4 sec
[-----------------91%--------------    ] 1827 of 2000 complete in 1656.3 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 1657.1 sec
[-----------------91%--------------    ] 1829 of 2000 complete in 1658.0 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 1658.9 sec
[-----------------91%--------------    ] 1831 of 2000 complete in 1659.8 sec
[-----------------91%--------------    ] 1832 of 2000 complete in 1660.7 sec
[-----------------91%--------------    ] 1833 of 2000 complete in 1661.6 sec

[-----------------91%--------------    ] 1836 of 2000 complete in 1587.9 sec
[-----------------91%--------------    ] 1837 of 2000 complete in 1588.7 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 1589.5 sec
[-----------------91%--------------    ] 1839 of 2000 complete in 1590.3 sec
[-----------------92%--------------    ] 1840 of 2000 complete in 1591.1 sec
[-----------------92%--------------    ] 1841 of 2000 complete in 1592.0 sec
[-----------------92%--------------    ] 1842 of 2000 complete in 1592.8 sec
[-----------------92%---------------   ] 1843 of 2000 complete in 1593.6 sec
[-----------------92%---------------   ] 1844 of 2000 complete in 1594.5 sec
[-----------------92%---------------   ] 1845 of 2000 complete in 1595.3 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 1596.1 sec
[-----------------92%---------------   ] 1847 of 2000 complete in 1597.0 sec
[-----------------92%---------------   ] 1848 of 2000 complete in 1597.8 sec
[-----------------92%---------------   ] 1849 of 2000 complete in 1598.7 sec
[-----------------92%---------------   ] 1850 of 2000 complete in 1599.5 sec
[-----------------92%---------------   ] 1851 of 2000 complete in 1600.4 sec
[-----------------92%---------------   ] 1852 of 2000 complete in 1601.3 sec
[-----------------92%---------------   ] 1853 of 2000 complete in 1602.2 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 1603.0 sec
[-----------------92%---------------   ] 1855 of 2000 complete in 1603.9 sec
[-----------------92%---------------   ] 1856 of 2000 complete in 1604.7 sec
[-----------------92%---------------   ] 1857 of 2000 complete in 1605.6 sec
[-----------------92%---------------   ] 1858 of 2000 complete in 1606.4 sec
[-----------------92%---------------   ] 1859 of 2000 complete in 1607.3 sec
[-----------------93%---------------   ] 1860 of 2000 complete in 1608.1 sec
[-----------------93%---------------   ] 1861 of 2000 complete in 1608.9 sec
[-----------------93%---------------   ] 1862 of 2000 complete in 1609.7 sec
[-----------------93%---------------   ] 1863 of 2000 complete in 1610.5 sec
[-----------------93%---------------   ] 1864 of 2000 complete in 1611.3 sec
[-----------------93%---------------   ] 1865 of 2000 complete in 1612.1 sec
[-----------------93%---------------   ] 1866 of 2000 complete in 1612.9 sec
[-----------------93%---------------   ] 1867 of 2000 complete in 1613.7 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 1614.5 sec
[-----------------93%---------------   ] 1869 of 2000 complete in 1615.3 sec
[-----------------93%---------------   ] 1870 of 2000 complete in 1616.1 sec
[-----------------93%---------------   ] 1871 of 2000 complete in 1616.9 sec
[-----------------93%---------------   ] 1872 of 2000 complete in 1617.7 sec
[-----------------93%---------------   ] 1873 of 2000 complete in 1618.6 sec
[-----------------93%---------------   ] 1874 of 2000 complete in 1619.4 sec
[-----------------93%---------------   ] 1875 of 2000 complete in 1620.2 sec
[-----------------93%---------------   ] 1876 of 2000 complete in 1621.1 sec
[-----------------93%---------------   ] 1877 of 2000 complete in 1621.9 sec
[-----------------93%---------------   ] 1878 of 2000 complete in 1622.7 sec
[-----------------93%---------------   ] 1879 of 2000 complete in 1623.5 sec
[-----------------94%---------------   ] 1880 of 2000 complete in 1624.4 sec
[-----------------94%---------------   ] 1881 of 2000 complete in 1625.2 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 1626.0 sec
[-----------------94%---------------   ] 1883 of 2000 complete in 1626.8 sec
[-----------------94%---------------   ] 1884 of 2000 complete in 1627.7 sec
[-----------------94%---------------   ] 1885 of 2000 complete in 1628.5 sec
[-----------------94%---------------   ] 1886 of 2000 complete in 1629.3 sec
[-----------------94%---------------   ] 1887 of 2000 complete in 1630.2 sec
[-----------------94%---------------   ] 1888 of 2000 complete in 1630.9 sec
[-----------------94%---------------   ] 1889 of 2000 complete in 1631.8 sec
[-----------------94%---------------   ] 1890 of 2000 complete in 1632.6 sec
[-----------------94%---------------   ] 1891 of 2000 complete in 1633.4 sec
[-----------------94%---------------   ] 1892 of 2000 complete in 1634.3 sec
[-----------------94%---------------   ] 1893 of 2000 complete in 1635.1 sec
[-----------------94%---------------   ] 1894 of 2000 complete in 1635.9 sec
[-----------------94%----------------  ] 1895 of 2000 complete in 1636.8 sec
[-----------------94%----------------  ] 1896 of 2000 complete in 1637.6 sec
[-----------------94%----------------  ] 1897 of 2000 complete in 1638.4 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 1639.2 sec
[-----------------94%----------------  ] 1899 of 2000 complete in 1640.1 sec
[-----------------95%----------------  ] 1900 of 2000 complete in 1640.9 sec
[-----------------95%----------------  ] 1901 of 2000 complete in 1641.7 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 1642.5 sec
[-----------------95%----------------  ] 1903 of 2000 complete in 1643.3 sec
[-----------------95%----------------  ] 1904 of 2000 complete in 1644.1 sec
[-----------------95%----------------  ] 1905 of 2000 complete in 1644.9 sec
[-----------------95%----------------  ] 1906 of 2000 complete in 1645.8 sec
[-----------------95%----------------  ] 1907 of 2000 complete in 1646.7 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 1647.5 sec
[-----------------95%----------------  ] 1909 of 2000 complete in 1648.3 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 1649.2 sec
[-----------------95%----------------  ] 1911 of 2000 complete in 1650.0 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 1650.8 sec
[-----------------95%----------------  ] 1913 of 2000 complete in 1651.6 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 1652.4 sec
[-----------------95%----------------  ] 1915 of 2000 complete in 1653.3 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 1654.1 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 1654.9 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 1655.7 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 1656.5 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 1657.4 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 1658.2 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 1659.0 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 1659.8 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 1660.5 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 1661.3 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 1662.1 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 1663.0 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 1663.8 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 1664.6 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 1665.5 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 1666.3 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 1667.1 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 1667.9 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 1668.7 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 1669.5 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 1670.3 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 1671.1 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 1672.0 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 1672.8 sec
[-----------------97%----------------  ] 1940 of 2000 complete in 1673.6 sec
[-----------------97%----------------  ] 1941 of 2000 complete in 1674.4 sec
[-----------------86%------------      ] 1728 of 2000 complete in 1588.7 sec
[-----------------86%------------      ] 1729 of 2000 complete in 1589.5 sec
[-----------------86%------------      ] 1730 of 2000 complete in 1590.3 sec
[-----------------86%------------      ] 1731 of 2000 complete in 1591.1 sec
[-----------------86%------------      ] 1732 of 2000 complete in 1591.9 sec
[-----------------86%------------      ] 1733 of 2000 complete in 1592.8 sec
[-----------------86%------------      ] 1734 of 2000 complete in 1593.6 sec
[-----------------86%------------      ] 1735 of 2000 complete in 1594.4 sec
[-----------------86%------------      ] 1736 of 2000 complete in 1595.2 sec
[-----------------86%-------------     ] 1737 of 2000 complete in 1596.0 sec
[-----------------86%-------------     ] 1738 of 2000 complete in 1596.8 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 1597.6 sec
[-----------------87%-------------     ] 1740 of 2000 complete in 1598.4 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 1599.2 sec
[-----------------87%-------------     ] 1742 of 2000 complete in 1600.0 sec
[-----------------87%-------------     ] 1743 of 2000 complete in 1600.8 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 1601.7 sec
[-----------------87%-------------     ] 1745 of 2000 complete in 1602.5 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 1603.4 sec
[-----------------87%-------------     ] 1747 of 2000 complete in 1604.2 sec
[-----------------87%-------------     ] 1748 of 2000 complete in 1605.1 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 1605.9 sec
[-----------------87%-------------     ] 1750 of 2000 complete in 1606.7 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 1607.6 sec
[-----------------87%-------------     ] 1752 of 2000 complete in 1608.4 sec
[-----------------87%-------------     ] 1753 of 2000 complete in 1609.3 sec
[-----------------87%-------------     ] 1754 of 2000 complete in 1610.1 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 1611.0 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 1611.8 sec
[-----------------87%-------------     ] 1757 of 2000 complete in 1612.7 sec
[-----------------87%-------------     ] 1758 of 2000 complete in 1613.6 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 1614.4 sec
[-----------------88%-------------     ] 1760 of 2000 complete in 1615.3 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 1616.1 sec
[-----------------88%-------------     ] 1762 of 2000 complete in 1617.0 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 1617.8 sec
[-----------------88%-------------     ] 1764 of 2000 complete in 1618.7 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 1619.5 sec
[-----------------88%-------------     ] 1766 of 2000 complete in 1620.4 sec
[-----------------88%-------------     ] 1767 of 2000 complete in 1621.2 sec
[-----------------88%-------------     ] 1768 of 2000 complete in 1622.1 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 1622.9 sec
[-----------------88%-------------     ] 1770 of 2000 complete in 1623.8 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 1624.6 sec
[-----------------88%-------------     ] 1772 of 2000 complete in 1625.5 sec
[-----------------88%-------------     ] 1773 of 2000 complete in 1626.4 sec
[-----------------88%-------------     ] 1774 of 2000 complete in 1627.3 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 1628.2 sec
[-----------------88%-------------     ] 1776 of 2000 complete in 1629.1 sec
[-----------------88%-------------     ] 1777 of 2000 complete in 1630.0 sec
[-----------------88%-------------     ] 1778 of 2000 complete in 1630.8 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 1631.7 sec
[-----------------89%-------------     ] 1780 of 2000 complete in 1632.7 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 1633.6 sec
[-----------------89%-------------     ] 1782 of 2000 complete in 1634.4 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 1635.3 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 1636.2 sec
[-----------------89%-------------     ] 1785 of 2000 complete in 1637.1 sec
[-----------------89%-------------     ] 1786 of 2000 complete in 1637.9 sec
[-----------------89%-------------     ] 1787 of 2000 complete in 1638.8 sec
[-----------------89%-------------     ] 1788 of 2000 complete in 1639.7 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 1640.6 sec
[-----------------89%--------------    ] 1790 of 2000 complete in 1641.5 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 1642.4 sec
[-----------------89%--------------    ] 1792 of 2000 complete in 1643.3 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 1644.3 sec
[-----------------89%--------------    ] 1794 of 2000 complete in 1645.2 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 1646.2 sec
[-----------------89%--------------    ] 1796 of 2000 complete in 1647.1 sec
[-----------------89%--------------    ] 1797 of 2000 complete in 1648.1 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 1649.0 sec
[-----------------89%--------------    ] 1799 of 2000 complete in 1649.9 sec
[-----------------90%--------------    ] 1800 of 2000 complete in 1650.9 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 1651.8 sec
[-----------------90%--------------    ] 1802 of 2000 complete in 1652.8 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 1653.7 sec
[-----------------90%--------------    ] 1804 of 2000 complete in 1654.7 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 1655.6 sec
[-----------------90%--------------    ] 1806 of 2000 complete in 1656.6 sec
[-----------------90%--------------    ] 1807 of 2000 complete in 1657.5 sec
[-----------------90%--------------    ] 1808 of 2000 complete in 1658.4 sec
[-----------------90%--------------    ] 1809 of 2000 complete in 1659.3 sec
[-----------------90%--------------    ] 1810 of 2000 complete in 1660.3 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 1661.2 sec
[-----------------90%--------------    ] 1812 of 2000 complete in 1662.2 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 1663.0 sec
[-----------------90%--------------    ] 1814 of 2000 complete in 1663.9 sec
[-----------------90%--------------    ] 1815 of 2000 complete in 1664.9 sec
[-----------------90%--------------    ] 1816 of 2000 complete in 1665.8 sec
[-----------------90%--------------    ] 1817 of 2000 complete in 1666.6 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 1667.5 sec
[-----------------90%--------------    ] 1819 of 2000 complete in 1668.4 sec
[-----------------91%--------------    ] 1820 of 2000 complete in 1669.3 sec
[-----------------91%--------------    ] 1821 of 2000 complete in 1670.2 sec
[-----------------91%--------------    ] 1822 of 2000 complete in 1671.0 sec
[-----------------91%--------------    ] 1823 of 2000 complete in 1671.8 sec
[-----------------91%--------------    ] 1824 of 2000 complete in 1672.7 sec
[-----------------91%--------------    ] 1825 of 2000 complete in 1673.5 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 1674.4 sec
[-----------------91%--------------    ] 1827 of 2000 complete in 1675.3 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 1676.1 sec
[-----------------91%--------------    ] 1829 of 2000 complete in 1677.0 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 1677.8 sec
[-----------------91%--------------    ] 1831 of 2000 complete in 1678.7 sec
[-----------------91%--------------    ] 1832 of 2000 complete in 1679.6 sec
[-----------------91%--------------    ] 1833 of 2000 complete in 1680.4 sec

[-----------------91%--------------    ] 1836 of 2000 complete in 1596.6 sec
[-----------------91%--------------    ] 1837 of 2000 complete in 1597.5 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 1598.3 sec
[-----------------91%--------------    ] 1839 of 2000 complete in 1599.2 sec
[-----------------92%--------------    ] 1840 of 2000 complete in 1600.1 sec
[-----------------92%--------------    ] 1841 of 2000 complete in 1600.9 sec
[-----------------92%--------------    ] 1842 of 2000 complete in 1601.8 sec
[-----------------92%---------------   ] 1843 of 2000 complete in 1602.7 sec
[-----------------92%---------------   ] 1844 of 2000 complete in 1603.6 sec
[-----------------92%---------------   ] 1845 of 2000 complete in 1604.4 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 1605.3 sec
[-----------------92%---------------   ] 1847 of 2000 complete in 1606.1 sec
[-----------------92%---------------   ] 1848 of 2000 complete in 1606.9 sec
[-----------------92%---------------   ] 1849 of 2000 complete in 1607.8 sec
[-----------------92%---------------   ] 1850 of 2000 complete in 1608.6 sec
[-----------------92%---------------   ] 1851 of 2000 complete in 1609.5 sec
[-----------------92%---------------   ] 1852 of 2000 complete in 1610.3 sec
[-----------------92%---------------   ] 1853 of 2000 complete in 1611.2 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 1612.0 sec
[-----------------92%---------------   ] 1855 of 2000 complete in 1612.9 sec
[-----------------92%---------------   ] 1856 of 2000 complete in 1613.8 sec
[-----------------92%---------------   ] 1857 of 2000 complete in 1614.6 sec
[-----------------92%---------------   ] 1858 of 2000 complete in 1615.5 sec
[-----------------92%---------------   ] 1859 of 2000 complete in 1616.3 sec
[-----------------93%---------------   ] 1860 of 2000 complete in 1617.1 sec
[-----------------93%---------------   ] 1861 of 2000 complete in 1618.0 sec
[-----------------93%---------------   ] 1862 of 2000 complete in 1618.8 sec
[-----------------93%---------------   ] 1863 of 2000 complete in 1619.6 sec
[-----------------93%---------------   ] 1864 of 2000 complete in 1620.4 sec
[-----------------93%---------------   ] 1865 of 2000 complete in 1621.2 sec
[-----------------93%---------------   ] 1866 of 2000 complete in 1622.0 sec
[-----------------93%---------------   ] 1867 of 2000 complete in 1622.8 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 1623.5 sec
[-----------------93%---------------   ] 1869 of 2000 complete in 1624.3 sec
[-----------------93%---------------   ] 1870 of 2000 complete in 1625.1 sec
[-----------------93%---------------   ] 1871 of 2000 complete in 1625.9 sec
[-----------------93%---------------   ] 1872 of 2000 complete in 1626.7 sec
[-----------------93%---------------   ] 1873 of 2000 complete in 1627.4 sec
[-----------------93%---------------   ] 1874 of 2000 complete in 1628.2 sec
[-----------------93%---------------   ] 1875 of 2000 complete in 1629.0 sec
[-----------------93%---------------   ] 1876 of 2000 complete in 1629.8 sec
[-----------------93%---------------   ] 1877 of 2000 complete in 1630.6 sec
[-----------------93%---------------   ] 1878 of 2000 complete in 1631.4 sec
[-----------------93%---------------   ] 1879 of 2000 complete in 1632.3 sec
[-----------------94%---------------   ] 1880 of 2000 complete in 1633.1 sec
[-----------------94%---------------   ] 1881 of 2000 complete in 1634.0 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 1634.9 sec
[-----------------94%---------------   ] 1883 of 2000 complete in 1635.7 sec
[-----------------94%---------------   ] 1884 of 2000 complete in 1636.6 sec
[-----------------94%---------------   ] 1885 of 2000 complete in 1637.4 sec
[-----------------94%---------------   ] 1886 of 2000 complete in 1638.3 sec
[-----------------94%---------------   ] 1887 of 2000 complete in 1639.2 sec
[-----------------94%---------------   ] 1888 of 2000 complete in 1640.1 sec
[-----------------94%---------------   ] 1889 of 2000 complete in 1641.0 sec
[-----------------94%---------------   ] 1890 of 2000 complete in 1641.8 sec
[-----------------94%---------------   ] 1891 of 2000 complete in 1642.7 sec
[-----------------94%---------------   ] 1892 of 2000 complete in 1643.6 sec
[-----------------94%---------------   ] 1893 of 2000 complete in 1644.4 sec
[-----------------94%---------------   ] 1894 of 2000 complete in 1645.3 sec
[-----------------94%----------------  ] 1895 of 2000 complete in 1646.2 sec
[-----------------94%----------------  ] 1896 of 2000 complete in 1647.1 sec
[-----------------94%----------------  ] 1897 of 2000 complete in 1648.1 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 1648.9 sec
[-----------------94%----------------  ] 1899 of 2000 complete in 1649.8 sec
[-----------------95%----------------  ] 1900 of 2000 complete in 1650.7 sec
[-----------------95%----------------  ] 1901 of 2000 complete in 1651.6 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 1652.6 sec
[-----------------95%----------------  ] 1903 of 2000 complete in 1653.5 sec
[-----------------95%----------------  ] 1904 of 2000 complete in 1654.4 sec
[-----------------95%----------------  ] 1905 of 2000 complete in 1655.3 sec
[-----------------95%----------------  ] 1906 of 2000 complete in 1656.2 sec
[-----------------95%----------------  ] 1907 of 2000 complete in 1657.1 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 1658.0 sec
[-----------------95%----------------  ] 1909 of 2000 complete in 1658.9 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 1659.8 sec
[-----------------95%----------------  ] 1911 of 2000 complete in 1660.7 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 1661.6 sec
[-----------------95%----------------  ] 1913 of 2000 complete in 1662.5 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 1663.4 sec
[-----------------95%----------------  ] 1915 of 2000 complete in 1664.3 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 1665.1 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 1666.0 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 1666.9 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 1667.8 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 1668.7 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 1669.6 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 1670.5 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 1671.4 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 1672.3 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 1673.1 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 1674.0 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 1674.8 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 1675.7 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 1676.6 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 1677.4 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 1678.4 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 1679.3 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 1680.2 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 1681.1 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 1682.0 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 1682.9 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 1683.8 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 1684.7 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 1685.6 sec
[-----------------97%----------------  ] 1940 of 2000 complete in 1686.6 sec
[-----------------97%----------------  ] 1941 of 2000 complete in 1687.5 sec
[-----------------91%--------------    ] 1834 of 2000 complete in 1662.5 sec
[-----------------91%--------------    ] 1835 of 2000 complete in 1663.4 sec
[-----------------91%--------------    ] 1836 of 2000 complete in 1664.4 sec
[-----------------91%--------------    ] 1837 of 2000 complete in 1665.3 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 1666.3 sec
[-----------------91%--------------    ] 1839 of 2000 complete in 1667.3 sec
[-----------------92%--------------    ] 1840 of 2000 complete in 1668.2 sec
[-----------------92%--------------    ] 1841 of 2000 complete in 1669.2 sec
[-----------------92%--------------    ] 1842 of 2000 complete in 1670.1 sec
[-----------------92%---------------   ] 1843 of 2000 complete in 1671.1 sec
[-----------------92%---------------   ] 1844 of 2000 complete in 1672.1 sec
[-----------------92%---------------   ] 1845 of 2000 complete in 1673.0 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 1674.0 sec
[-----------------92%---------------   ] 1847 of 2000 complete in 1674.9 sec
[-----------------92%---------------   ] 1848 of 2000 complete in 1675.8 sec
[-----------------92%---------------   ] 1849 of 2000 complete in 1676.7 sec
[-----------------92%---------------   ] 1850 of 2000 complete in 1677.7 sec
[-----------------92%---------------   ] 1851 of 2000 complete in 1678.6 sec
[-----------------92%---------------   ] 1852 of 2000 complete in 1679.5 sec
[-----------------92%---------------   ] 1853 of 2000 complete in 1680.4 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 1681.4 sec
[-----------------92%---------------   ] 1855 of 2000 complete in 1682.3 sec
[-----------------92%---------------   ] 1856 of 2000 complete in 1683.2 sec
[-----------------92%---------------   ] 1857 of 2000 complete in 1684.1 sec
[-----------------92%---------------   ] 1858 of 2000 complete in 1685.0 sec
[-----------------92%---------------   ] 1859 of 2000 complete in 1686.0 sec
[-----------------93%---------------   ] 1860 of 2000 complete in 1687.0 sec
[-----------------93%---------------   ] 1861 of 2000 complete in 1687.9 sec
[-----------------93%---------------   ] 1862 of 2000 complete in 1688.9 sec
[-----------------93%---------------   ] 1863 of 2000 complete in 1689.8 sec
[-----------------93%---------------   ] 1864 of 2000 complete in 1690.7 sec
[-----------------93%---------------   ] 1865 of 2000 complete in 1691.6 sec
[-----------------93%---------------   ] 1866 of 2000 complete in 1692.5 sec
[-----------------93%---------------   ] 1867 of 2000 complete in 1693.5 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 1694.5 sec
[-----------------93%---------------   ] 1869 of 2000 complete in 1695.5 sec
[-----------------93%---------------   ] 1870 of 2000 complete in 1696.4 sec
[-----------------93%---------------   ] 1871 of 2000 complete in 1697.4 sec
[-----------------93%---------------   ] 1872 of 2000 complete in 1698.3 sec
[-----------------93%---------------   ] 1873 of 2000 complete in 1699.2 sec
[-----------------93%---------------   ] 1874 of 2000 complete in 1700.1 sec
[-----------------93%---------------   ] 1875 of 2000 complete in 1701.1 sec
[-----------------93%---------------   ] 1876 of 2000 complete in 1702.0 sec
[-----------------93%---------------   ] 1877 of 2000 complete in 1702.9 sec
[-----------------93%---------------   ] 1878 of 2000 complete in 1703.8 sec
[-----------------93%---------------   ] 1879 of 2000 complete in 1704.8 sec
[-----------------94%---------------   ] 1880 of 2000 complete in 1705.7 sec
[-----------------94%---------------   ] 1881 of 2000 complete in 1706.6 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 1707.5 sec
[-----------------94%---------------   ] 1883 of 2000 complete in 1708.4 sec
[-----------------94%---------------   ] 1884 of 2000 complete in 1709.2 sec
[-----------------94%---------------   ] 1885 of 2000 complete in 1710.1 sec
[-----------------94%---------------   ] 1886 of 2000 complete in 1711.0 sec
[-----------------94%---------------   ] 1887 of 2000 complete in 1711.8 sec
[-----------------94%---------------   ] 1888 of 2000 complete in 1712.6 sec
[-----------------94%---------------   ] 1889 of 2000 complete in 1713.5 sec
[-----------------94%---------------   ] 1890 of 2000 complete in 1714.3 sec
[-----------------94%---------------   ] 1891 of 2000 complete in 1715.3 sec
[-----------------94%---------------   ] 1892 of 2000 complete in 1716.2 sec
[-----------------94%---------------   ] 1893 of 2000 complete in 1717.0 sec
[-----------------94%---------------   ] 1894 of 2000 complete in 1717.8 sec
[-----------------94%----------------  ] 1895 of 2000 complete in 1718.7 sec
[-----------------94%----------------  ] 1896 of 2000 complete in 1719.6 sec
[-----------------94%----------------  ] 1897 of 2000 complete in 1720.5 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 1721.4 sec
[-----------------94%----------------  ] 1899 of 2000 complete in 1722.2 sec
[-----------------95%----------------  ] 1900 of 2000 complete in 1723.0 sec
[-----------------95%----------------  ] 1901 of 2000 complete in 1723.9 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 1724.7 sec
[-----------------95%----------------  ] 1903 of 2000 complete in 1725.5 sec
[-----------------95%----------------  ] 1904 of 2000 complete in 1726.4 sec
[-----------------95%----------------  ] 1905 of 2000 complete in 1727.2 sec
[-----------------95%----------------  ] 1906 of 2000 complete in 1728.0 sec
[-----------------95%----------------  ] 1907 of 2000 complete in 1728.8 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 1729.7 sec
[-----------------95%----------------  ] 1909 of 2000 complete in 1730.6 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 1731.4 sec
[-----------------95%----------------  ] 1911 of 2000 complete in 1732.3 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 1733.2 sec
[-----------------95%----------------  ] 1913 of 2000 complete in 1734.0 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 1734.9 sec
[-----------------95%----------------  ] 1915 of 2000 complete in 1735.7 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 1736.6 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 1737.4 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 1738.3 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 1739.1 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 1740.0 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 1740.9 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 1741.7 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 1742.6 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 1743.4 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 1744.3 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 1745.1 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 1745.9 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 1746.7 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 1747.5 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 1748.4 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 1749.2 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 1750.1 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 1751.1 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 1751.9 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 1752.8 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 1753.6 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 1754.4 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 1755.2 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 1756.0 sec

[-----------------91%--------------    ] 1834 of 2000 complete in 1681.2 sec
[-----------------91%--------------    ] 1835 of 2000 complete in 1682.1 sec
[-----------------91%--------------    ] 1836 of 2000 complete in 1682.9 sec
[-----------------91%--------------    ] 1837 of 2000 complete in 1683.8 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 1684.6 sec
[-----------------91%--------------    ] 1839 of 2000 complete in 1685.5 sec
[-----------------92%--------------    ] 1840 of 2000 complete in 1686.4 sec
[-----------------92%--------------    ] 1841 of 2000 complete in 1687.3 sec
[-----------------92%--------------    ] 1842 of 2000 complete in 1688.2 sec
[-----------------92%---------------   ] 1843 of 2000 complete in 1689.0 sec
[-----------------92%---------------   ] 1844 of 2000 complete in 1689.9 sec
[-----------------92%---------------   ] 1845 of 2000 complete in 1690.7 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 1691.6 sec
[-----------------92%---------------   ] 1847 of 2000 complete in 1692.5 sec
[-----------------92%---------------   ] 1848 of 2000 complete in 1693.3 sec
[-----------------92%---------------   ] 1849 of 2000 complete in 1694.2 sec
[-----------------92%---------------   ] 1850 of 2000 complete in 1695.1 sec
[-----------------92%---------------   ] 1851 of 2000 complete in 1696.0 sec
[-----------------92%---------------   ] 1852 of 2000 complete in 1696.9 sec
[-----------------92%---------------   ] 1853 of 2000 complete in 1697.7 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 1698.6 sec
[-----------------92%---------------   ] 1855 of 2000 complete in 1699.4 sec
[-----------------92%---------------   ] 1856 of 2000 complete in 1700.3 sec
[-----------------92%---------------   ] 1857 of 2000 complete in 1701.1 sec
[-----------------92%---------------   ] 1858 of 2000 complete in 1702.0 sec
[-----------------92%---------------   ] 1859 of 2000 complete in 1702.8 sec
[-----------------93%---------------   ] 1860 of 2000 complete in 1703.6 sec
[-----------------93%---------------   ] 1861 of 2000 complete in 1704.5 sec
[-----------------93%---------------   ] 1862 of 2000 complete in 1705.4 sec
[-----------------93%---------------   ] 1863 of 2000 complete in 1706.2 sec
[-----------------93%---------------   ] 1864 of 2000 complete in 1707.1 sec
[-----------------93%---------------   ] 1865 of 2000 complete in 1707.9 sec
[-----------------93%---------------   ] 1866 of 2000 complete in 1708.8 sec
[-----------------93%---------------   ] 1867 of 2000 complete in 1709.6 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 1710.4 sec
[-----------------93%---------------   ] 1869 of 2000 complete in 1711.2 sec
[-----------------93%---------------   ] 1870 of 2000 complete in 1712.1 sec
[-----------------93%---------------   ] 1871 of 2000 complete in 1712.9 sec
[-----------------93%---------------   ] 1872 of 2000 complete in 1713.8 sec
[-----------------93%---------------   ] 1873 of 2000 complete in 1714.6 sec
[-----------------93%---------------   ] 1874 of 2000 complete in 1715.4 sec
[-----------------93%---------------   ] 1875 of 2000 complete in 1716.3 sec
[-----------------93%---------------   ] 1876 of 2000 complete in 1717.1 sec
[-----------------93%---------------   ] 1877 of 2000 complete in 1718.0 sec
[-----------------93%---------------   ] 1878 of 2000 complete in 1718.8 sec
[-----------------93%---------------   ] 1879 of 2000 complete in 1719.6 sec
[-----------------94%---------------   ] 1880 of 2000 complete in 1720.4 sec
[-----------------94%---------------   ] 1881 of 2000 complete in 1721.2 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 1722.1 sec
[-----------------94%---------------   ] 1883 of 2000 complete in 1722.9 sec
[-----------------94%---------------   ] 1884 of 2000 complete in 1723.7 sec
[-----------------94%---------------   ] 1885 of 2000 complete in 1724.5 sec
[-----------------94%---------------   ] 1886 of 2000 complete in 1725.4 sec
[-----------------94%---------------   ] 1887 of 2000 complete in 1726.3 sec
[-----------------94%---------------   ] 1888 of 2000 complete in 1727.2 sec
[-----------------94%---------------   ] 1889 of 2000 complete in 1728.0 sec
[-----------------94%---------------   ] 1890 of 2000 complete in 1728.9 sec
[-----------------94%---------------   ] 1891 of 2000 complete in 1729.8 sec
[-----------------94%---------------   ] 1892 of 2000 complete in 1730.6 sec
[-----------------94%---------------   ] 1893 of 2000 complete in 1731.5 sec
[-----------------94%---------------   ] 1894 of 2000 complete in 1732.4 sec
[-----------------94%----------------  ] 1895 of 2000 complete in 1733.3 sec
[-----------------94%----------------  ] 1896 of 2000 complete in 1734.1 sec
[-----------------94%----------------  ] 1897 of 2000 complete in 1735.0 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 1735.8 sec
[-----------------94%----------------  ] 1899 of 2000 complete in 1736.7 sec
[-----------------95%----------------  ] 1900 of 2000 complete in 1737.5 sec
[-----------------95%----------------  ] 1901 of 2000 complete in 1738.3 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 1739.2 sec
[-----------------95%----------------  ] 1903 of 2000 complete in 1740.0 sec
[-----------------95%----------------  ] 1904 of 2000 complete in 1740.8 sec
[-----------------95%----------------  ] 1905 of 2000 complete in 1741.7 sec
[-----------------95%----------------  ] 1906 of 2000 complete in 1742.6 sec
[-----------------95%----------------  ] 1907 of 2000 complete in 1743.5 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 1744.4 sec
[-----------------95%----------------  ] 1909 of 2000 complete in 1745.2 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 1746.1 sec
[-----------------95%----------------  ] 1911 of 2000 complete in 1746.9 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 1747.8 sec
[-----------------95%----------------  ] 1913 of 2000 complete in 1748.7 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 1749.5 sec
[-----------------95%----------------  ] 1915 of 2000 complete in 1750.5 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 1751.3 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 1752.1 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 1752.8 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 1753.7 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 1754.6 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 1755.4 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 1756.2 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 1757.1 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 1757.9 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 1758.8 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 1759.6 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 1760.4 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 1761.3 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 1762.1 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 1763.0 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 1763.8 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 1764.6 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 1765.5 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 1766.3 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 1767.2 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 1768.1 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 1769.0 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 1769.8 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 1770.7 sec
hddm sampling elpased time:  1864.822 s
Start converting to InferenceData...

[-----------------97%----------------  ] 1942 of 2000 complete in 1675.2 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 1676.1 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 1676.9 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 1677.8 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 1678.6 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 1679.4 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 1680.3 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 1681.2 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 1682.1 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 1683.1 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 1684.0 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 1684.9 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 1685.8 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 1686.8 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 1687.6 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 1688.5 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 1689.4 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 1690.2 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 1691.0 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 1691.9 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 1692.8 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 1693.6 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 1694.5 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 1695.4 sec
[-----------------98%----------------- ] 1966 of 2000 complete in 1696.2 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 1697.1 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 1698.0 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 1698.9 sec
[-----------------98%----------------- ] 1970 of 2000 complete in 1699.7 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 1700.6 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 1701.5 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 1702.5 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 1703.4 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 1704.3 sec
[-----------------98%----------------- ] 1976 of 2000 complete in 1705.2 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 1706.1 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 1707.1 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 1707.9 sec
[-----------------99%----------------- ] 1980 of 2000 complete in 1708.8 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 1709.7 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 1710.6 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 1711.5 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 1712.5 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 1713.4 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 1714.3 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 1715.2 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 1716.1 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 1716.9 sec
[-----------------99%----------------- ] 1990 of 2000 complete in 1717.8 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 1718.7 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 1719.6 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 1720.4 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 1721.3 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 1722.2 sec
[-----------------99%----------------- ] 1996 of 2000 complete in 1723.1 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 1724.0 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 1724.8 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 1725.7 sec
[-----------------100%-----------------] 2000 of 2000 complete in 1726.5 sec
[-----------------100%-----------------] 2001 of 2000 complete in 1727.4 sec
hddm sampling elpased time:  1727.583 s
[-----------------97%----------------  ] 1942 of 2000 complete in 1688.4 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 1689.3 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 1690.2 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 1691.1 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 1692.1 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 1693.0 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 1693.8 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 1694.8 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 1695.7 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 1696.7 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 1697.6 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 1698.5 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 1699.4 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 1700.3 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 1701.3 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 1702.2 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 1703.1 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 1704.1 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 1705.0 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 1706.0 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 1707.0 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 1708.0 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 1708.9 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 1709.8 sec
[-----------------98%----------------- ] 1966 of 2000 complete in 1710.7 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 1711.7 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 1712.7 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 1713.7 sec
[-----------------98%----------------- ] 1970 of 2000 complete in 1714.6 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 1715.5 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 1716.5 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 1717.4 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 1718.3 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 1719.2 sec
[-----------------98%----------------- ] 1976 of 2000 complete in 1720.1 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 1721.0 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 1721.8 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 1722.7 sec
[-----------------99%----------------- ] 1980 of 2000 complete in 1723.5 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 1724.4 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 1725.2 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 1726.1 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 1726.9 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 1727.8 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 1728.6 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 1729.5 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 1730.3 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 1731.2 sec
[-----------------99%----------------- ] 1990 of 2000 complete in 1732.1 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 1733.0 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 1733.9 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 1734.7 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 1735.5 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 1736.4 sec
[-----------------99%----------------- ] 1996 of 2000 complete in 1737.2 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 1738.1 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 1739.0 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 1739.8 sec
[-----------------100%-----------------] 2000 of 2000 complete in 1740.7 sec
[-----------------100%-----------------] 2001 of 2000 complete in 1741.6 sec
hddm sampling elpased time:  1741.757 s

[-----------------97%----------------  ] 1940 of 2000 complete in 1756.8 sec
[-----------------97%----------------  ] 1941 of 2000 complete in 1757.7 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 1758.5 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 1759.3 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 1760.1 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 1760.9 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 1761.7 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 1762.5 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 1763.2 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 1764.0 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 1764.8 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 1765.6 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 1766.4 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 1767.1 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 1767.9 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 1768.7 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 1769.5 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 1770.3 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 1771.1 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 1771.9 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 1772.8 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 1773.6 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 1774.5 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 1775.3 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 1776.2 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 1777.0 sec
[-----------------98%----------------- ] 1966 of 2000 complete in 1777.8 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 1778.7 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 1779.5 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 1780.3 sec
[-----------------98%----------------- ] 1970 of 2000 complete in 1781.1 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 1782.0 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 1782.9 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 1783.7 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 1784.6 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 1785.4 sec
[-----------------98%----------------- ] 1976 of 2000 complete in 1786.3 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 1787.1 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 1787.9 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 1788.8 sec
[-----------------99%----------------- ] 1980 of 2000 complete in 1789.7 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 1790.5 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 1791.3 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 1792.2 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 1793.0 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 1793.9 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 1794.7 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 1795.6 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 1796.5 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 1797.3 sec
[-----------------99%----------------- ] 1990 of 2000 complete in 1798.2 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 1799.1 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 1800.0 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 1800.9 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 1801.8 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 1802.7 sec
[-----------------99%----------------- ] 1996 of 2000 complete in 1803.6 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 1804.5 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 1805.5 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 1806.4 sec
[-----------------100%-----------------] 2000 of 2000 complete in 1807.3 sec
[-----------------100%-----------------] 2001 of 2000 complete in 1808.2 sec
hddm sampling elpased time:  1808.37 s
[-----------------97%----------------  ] 1940 of 2000 complete in 1771.6 sec
[-----------------97%----------------  ] 1941 of 2000 complete in 1772.5 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 1773.4 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 1774.3 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 1775.2 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 1776.1 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 1777.0 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 1777.8 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 1778.7 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 1779.6 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 1780.4 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 1781.3 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 1782.1 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 1782.9 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 1783.6 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 1784.4 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 1785.2 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 1786.0 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 1786.8 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 1787.6 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 1788.4 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 1789.2 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 1789.9 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 1790.7 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 1791.5 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 1792.2 sec
[-----------------98%----------------- ] 1966 of 2000 complete in 1793.0 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 1793.7 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 1794.5 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 1795.3 sec
[-----------------98%----------------- ] 1970 of 2000 complete in 1796.0 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 1796.8 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 1797.6 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 1798.3 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 1799.1 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 1799.8 sec
[-----------------98%----------------- ] 1976 of 2000 complete in 1800.6 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 1801.4 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 1802.1 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 1802.9 sec
[-----------------99%----------------- ] 1980 of 2000 complete in 1803.6 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 1804.4 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 1805.1 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 1805.9 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 1806.6 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 1807.4 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 1808.1 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 1808.9 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 1809.6 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 1810.4 sec
[-----------------99%----------------- ] 1990 of 2000 complete in 1811.1 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 1811.9 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 1812.7 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 1813.4 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 1814.2 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 1814.9 sec
[-----------------99%----------------- ] 1996 of 2000 complete in 1815.6 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 1816.4 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 1817.1 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 1817.8 sec
[-----------------100%-----------------] 2000 of 2000 complete in 1818.5 sec
[-----------------100%-----------------] 2001 of 2000 complete in 1819.2 sec
hddm sampling elpased time:  1819.412 s

In [40]:
summary = az.summary(hddmReg_stim_vflip_dc_m2_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

                         mean     sd  hdi_3%  hdi_97%  mcse_mean  mcse_sd
a                       2.038  0.179   1.719    2.381      0.021    0.015  \
a_std                   1.000  0.172   0.686    1.322      0.023    0.016
t                       0.238  0.010   0.219    0.256      0.001    0.001
t_std                   0.054  0.009   0.038    0.073      0.001    0.001
z                       0.541  0.006   0.531    0.551      0.000    0.000
z_std                   0.112  0.015   0.086    0.140      0.000    0.000
v_Intercept(Other)     -0.911  0.617  -1.652    0.341      0.301    0.229
v_Intercept(Self)       1.805  0.586   0.957    2.849      0.285    0.218
v_Intercept_std         0.079  0.059   0.003    0.177      0.017    0.012
v_id[T.Self]           -0.419  1.209  -2.668    0.928      0.596    0.456
v_id[T.Self]_std        0.121  0.073   0.007    0.249      0.011    0.008
v_stim2                 2.568  0.653   1.601    3.971      0.302    0.230
v_stim2_std             1.346  0.173   1.036    1.676      0.012    0.009
v_id[T.Self]:stim2     -0.611  0.290  -1.146   -0.082      0.127    0.097
v_id[T.Self]:stim2_std  0.106  0.081   0.000    0.243      0.014    0.010

                        ess_bulk  ess_tail  r_hat
a                           67.0     362.0   1.04
a_std                       51.0     111.0   1.06
t                           52.0     400.0   1.05
t_std                       56.0     105.0   1.05
z                          428.0    2180.0   1.02
z_std                      928.0    2856.0   1.01
v_Intercept(Other)           4.0      11.0   3.31
v_Intercept(Self)            5.0      12.0   2.60
v_Intercept_std             10.0      25.0   1.32
v_id[T.Self]                 5.0      13.0   3.03
v_id[T.Self]_std            29.0      29.0   1.11
v_stim2                      5.0      12.0   2.17
v_stim2_std                175.0     708.0   1.02
v_id[T.Self]:stim2           6.0      16.0   1.93
v_id[T.Self]:stim2_std      28.0      19.0   1.10

In [42]:
#type2：link function
def v_link_func(x, data=data):
    # 1 is big; 0 is small
    stim = data.stim.loc[x.index]
    v_flip = x.where(stim == 1, -x)
    return v_flip

v_reg = [{'model': "v ~ 0 + id*C(stim)", 'link_func': v_link_func}] 

data['response'] = data['choice']

hddmReg_stim_vflip_m3_diff = hddm.HDDMRegressor(
    data,
    v_reg,
    bias=True, p_outlier=0.05,
    include=['v', 'a', 't', 'z'],
    group_only_regressors=False
)

hddmReg_stim_vflip_m3_diff_idata = hddmReg_stim_vflip_m3_diff.sample(2000, burn=500, chains=4, return_infdata=True, dbname = 'hddmReg_stim_vflip_m3_diff.db', db = 'pickle')
hddmReg_stim_vflip_m3_diff.save('hddmReg_stim_vflip_m3_diff.hddm')

No model attribute --> setting up standard HDDM
Set model to ddm

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

[                  0%                  ] 2 of 2000 complete in 1.3 sec
[                  0%                  ] 3 of 2000 complete in 3.0 sec
[                  0%                  ] 4 of 2000 complete in 4.5 sec
[                  0%                  ] 5 of 2000 complete in 5.9 sec
[                  0%                  ] 6 of 2000 complete in 7.2 sec
[                  0%                  ] 7 of 2000 complete in 8.5 sec
[                  0%                  ] 8 of 2000 complete in 9.8 sec
[                  0%                  ] 9 of 2000 complete in 11.0 sec
[                  0%                  ] 10 of 2000 complete in 12.2 sec
[                  0%                  ] 11 of 2000 complete in 13.4 sec
[                  0%                  ] 12 of 2000 complete in 14.6 sec
[                  0%                  ] 13 of 2000 complete in 15.8 sec
[                  0%                  ] 14 of 2000 complete in 17.0 sec
[                  0%                  ] 15 of 2000 complete in 18.1 sec
[                  0%                  ] 16 of 2000 complete in 19.2 sec
[                  0%                  ] 17 of 2000 complete in 20.4 sec
[                  0%                  ] 18 of 2000 complete in 21.7 sec
[                  0%                  ] 19 of 2000 complete in 22.9 sec
[                  1%                  ] 20 of 2000 complete in 24.0 sec
[                  1%                  ] 21 of 2000 complete in 25.3 sec
[                  1%                  ] 22 of 2000 complete in 26.5 sec
[                  1%                  ] 23 of 2000 complete in 27.8 sec
[                  1%                  ] 24 of 2000 complete in 29.1 sec
[                  1%                  ] 25 of 2000 complete in 30.4 sec
[                  1%                  ] 26 of 2000 complete in 31.7 sec
[                  1%                  ] 27 of 2000 complete in 32.9 sec
[                  1%                  ] 28 of 2000 complete in 34.3 sec
[                  1%                  ] 29 of 2000 complete in 35.6 sec
[                  1%                  ] 30 of 2000 complete in 36.8 sec
[                  1%                  ] 31 of 2000 complete in 38.1 sec
[                  1%                  ] 32 of 2000 complete in 39.4 sec
[                  1%                  ] 33 of 2000 complete in 40.6 sec
[                  1%                  ] 34 of 2000 complete in 41.9 sec
[                  1%                  ] 35 of 2000 complete in 43.2 sec
[                  1%                  ] 36 of 2000 complete in 44.5 sec
[                  1%                  ] 37 of 2000 complete in 45.7 sec
[                  1%                  ] 38 of 2000 complete in 46.9 sec
[                  1%                  ] 39 of 2000 complete in 48.1 sec
[                  2%                  ] 40 of 2000 complete in 49.3 sec
[                  2%                  ] 41 of 2000 complete in 50.5 sec
[                  2%                  ] 42 of 2000 complete in 51.7 sec
[                  2%                  ] 43 of 2000 complete in 52.9 sec
[                  2%                  ] 44 of 2000 complete in 54.2 sec
[                  2%                  ] 45 of 2000 complete in 55.4 sec
[                  2%                  ] 46 of 2000 complete in 56.7 sec
[                  2%                  ] 47 of 2000 complete in 58.1 sec
[                  2%                  ] 48 of 2000 complete in 59.3 sec
[                  2%                  ] 49 of 2000 complete in 60.6 sec
[                  2%                  ] 50 of 2000 complete in 61.9 sec
[                  2%                  ] 51 of 2000 complete in 63.3 sec
[                  2%                  ] 52 of 2000 complete in 64.6 sec
[-                 2%                  ] 53 of 2000 complete in 65.9 sec
[-                 2%                  ] 54 of 2000 complete in 67.1 sec
[-                 2%                  ] 55 of 2000 complete in 68.4 sec
[-                 2%                  ] 56 of 2000 complete in 69.7 sec
[-                 2%                  ] 57 of 2000 complete in 71.0 sec
[-                 2%                  ] 58 of 2000 complete in 72.4 sec
[-                 2%                  ] 59 of 2000 complete in 73.7 sec
[-                 3%                  ] 60 of 2000 complete in 75.1 sec
[-                 3%                  ] 61 of 2000 complete in 76.4 sec
[-                 3%                  ] 62 of 2000 complete in 77.8 sec
[-                 3%                  ] 63 of 2000 complete in 79.1 sec
[-                 3%                  ] 64 of 2000 complete in 80.4 sec
[-                 3%                  ] 65 of 2000 complete in 81.7 sec
[-                 3%                  ] 66 of 2000 complete in 82.9 sec
[-                 3%                  ] 67 of 2000 complete in 84.2 sec
[-                 3%                  ] 68 of 2000 complete in 85.5 sec
[-                 3%                  ] 69 of 2000 complete in 86.8 sec
[-                 3%                  ] 70 of 2000 complete in 88.1 sec
[-                 3%                  ] 71 of 2000 complete in 89.4 sec
[-                 3%                  ] 72 of 2000 complete in 90.7 sec
[-                 3%                  ] 73 of 2000 complete in 92.0 sec
[-                 3%                  ] 74 of 2000 complete in 93.3 sec
[-                 3%                  ] 75 of 2000 complete in 94.6 sec
[-                 3%                  ] 76 of 2000 complete in 95.9 sec
[-                 3%                  ] 77 of 2000 complete in 97.2 sec
[-                 3%                  ] 78 of 2000 complete in 98.5 sec
[-                 3%                  ] 79 of 2000 complete in 99.8 sec
[-                 4%                  ] 80 of 2000 complete in 101.2 sec
[-                 4%                  ] 81 of 2000 complete in 102.4 sec
[-                 4%                  ] 82 of 2000 complete in 103.8 sec
[-                 4%                  ] 83 of 2000 complete in 105.1 sec
[-                 4%                  ] 84 of 2000 complete in 106.3 sec
[-                 4%                  ] 85 of 2000 complete in 107.6 sec
[-                 4%                  ] 86 of 2000 complete in 108.9 sec
[-                 4%                  ] 87 of 2000 complete in 110.1 sec
[-                 4%                  ] 88 of 2000 complete in 111.3 sec
[-                 4%                  ] 89 of 2000 complete in 112.6 sec
[-                 4%                  ] 90 of 2000 complete in 113.8 sec
[-                 4%                  ] 91 of 2000 complete in 115.1 sec
[-                 4%                  ] 92 of 2000 complete in 116.3 sec
[-                 4%                  ] 93 of 2000 complete in 117.7 sec
[-                 4%                  ] 94 of 2000 complete in 118.9 sec
[-                 4%                  ] 95 of 2000 complete in 120.1 sec
[-                 4%                  ] 96 of 2000 complete in 121.3 sec
[-                 4%                  ] 97 of 2000 complete in 122.6 sec
[-                 4%                  ] 98 of 2000 complete in 123.9 sec
[-                 4%                  ] 99 of 2000 complete in 125.1 sec
[-                 5%                  ] 100 of 2000 complete in 126.3 sec
[-                 5%                  ] 101 of 2000 complete in 127.5 sec
[-                 5%                  ] 102 of 2000 complete in 128.7 sec
[-                 5%                  ] 103 of 2000 complete in 129.9 sec
[-                 5%                  ] 104 of 2000 complete in 131.1 sec
[-                 5%                  ] 105 of 2000 complete in 132.2 sec
[--                5%                  ] 106 of 2000 complete in 133.5 sec
[--                5%                  ] 107 of 2000 complete in 134.7 sec
[--                5%                  ] 108 of 2000 complete in 135.9 sec
[--                5%                  ] 109 of 2000 complete in 137.0 sec
[--                5%                  ] 110 of 2000 complete in 138.2 sec
[--                5%                  ] 111 of 2000 complete in 139.4 sec
[--                5%                  ] 112 of 2000 complete in 140.5 sec
[                  0%                  ] 2 of 2000 complete in 1.5 sec
[                  0%                  ] 3 of 2000 complete in 3.2 sec
[                  0%                  ] 4 of 2000 complete in 4.7 sec
[                  0%                  ] 5 of 2000 complete in 6.1 sec
[                  0%                  ] 6 of 2000 complete in 7.4 sec
[                  0%                  ] 7 of 2000 complete in 8.7 sec
[                  0%                  ] 8 of 2000 complete in 10.0 sec
[                  0%                  ] 9 of 2000 complete in 11.3 sec
[                  0%                  ] 10 of 2000 complete in 12.7 sec
[                  0%                  ] 11 of 2000 complete in 13.9 sec
[                  0%                  ] 12 of 2000 complete in 15.3 sec
[                  0%                  ] 13 of 2000 complete in 16.5 sec
[                  0%                  ] 14 of 2000 complete in 17.9 sec
[                  0%                  ] 15 of 2000 complete in 19.2 sec
[                  0%                  ] 16 of 2000 complete in 20.5 sec
[                  0%                  ] 17 of 2000 complete in 21.8 sec
[                  0%                  ] 18 of 2000 complete in 23.2 sec
[                  0%                  ] 19 of 2000 complete in 24.5 sec
[                  1%                  ] 20 of 2000 complete in 25.9 sec
[                  1%                  ] 21 of 2000 complete in 27.3 sec
[                  1%                  ] 22 of 2000 complete in 28.6 sec
[                  1%                  ] 23 of 2000 complete in 29.9 sec
[                  1%                  ] 24 of 2000 complete in 31.2 sec
[                  1%                  ] 25 of 2000 complete in 32.5 sec
[                  1%                  ] 26 of 2000 complete in 34.0 sec
[                  1%                  ] 27 of 2000 complete in 35.3 sec
[                  1%                  ] 28 of 2000 complete in 36.7 sec
[                  1%                  ] 29 of 2000 complete in 38.1 sec
[                  1%                  ] 30 of 2000 complete in 39.5 sec
[                  1%                  ] 31 of 2000 complete in 40.9 sec
[                  1%                  ] 32 of 2000 complete in 42.3 sec
[                  1%                  ] 33 of 2000 complete in 43.7 sec
[                  1%                  ] 34 of 2000 complete in 45.0 sec
[                  1%                  ] 35 of 2000 complete in 46.3 sec
[                  1%                  ] 36 of 2000 complete in 47.6 sec
[                  1%                  ] 37 of 2000 complete in 49.0 sec
[                  1%                  ] 38 of 2000 complete in 50.3 sec
[                  1%                  ] 39 of 2000 complete in 51.6 sec
[                  2%                  ] 40 of 2000 complete in 52.9 sec
[                  2%                  ] 41 of 2000 complete in 54.3 sec
[                  2%                  ] 42 of 2000 complete in 55.6 sec
[                  2%                  ] 43 of 2000 complete in 57.0 sec
[                  2%                  ] 44 of 2000 complete in 58.4 sec
[                  2%                  ] 45 of 2000 complete in 59.7 sec
[                  2%                  ] 46 of 2000 complete in 61.1 sec
[                  2%                  ] 47 of 2000 complete in 62.6 sec
[                  2%                  ] 48 of 2000 complete in 64.0 sec
[                  2%                  ] 49 of 2000 complete in 65.4 sec
[                  2%                  ] 50 of 2000 complete in 66.7 sec
[                  2%                  ] 51 of 2000 complete in 68.0 sec
[                  2%                  ] 52 of 2000 complete in 69.3 sec
[-                 2%                  ] 53 of 2000 complete in 70.6 sec
[-                 2%                  ] 54 of 2000 complete in 71.9 sec
[-                 2%                  ] 55 of 2000 complete in 73.2 sec
[-                 2%                  ] 56 of 2000 complete in 74.5 sec
[-                 2%                  ] 57 of 2000 complete in 75.8 sec
[-                 2%                  ] 58 of 2000 complete in 77.1 sec
[-                 2%                  ] 59 of 2000 complete in 78.4 sec
[-                 3%                  ] 60 of 2000 complete in 79.6 sec
[-                 3%                  ] 61 of 2000 complete in 80.9 sec
[-                 3%                  ] 62 of 2000 complete in 82.2 sec
[-                 3%                  ] 63 of 2000 complete in 83.4 sec
[-                 3%                  ] 64 of 2000 complete in 84.7 sec
[-                 3%                  ] 65 of 2000 complete in 86.0 sec
[-                 3%                  ] 66 of 2000 complete in 87.3 sec
[-                 3%                  ] 67 of 2000 complete in 88.6 sec
[-                 3%                  ] 68 of 2000 complete in 89.9 sec
[-                 3%                  ] 69 of 2000 complete in 91.2 sec
[-                 3%                  ] 70 of 2000 complete in 92.5 sec
[-                 3%                  ] 71 of 2000 complete in 93.9 sec
[-                 3%                  ] 72 of 2000 complete in 95.1 sec
[-                 3%                  ] 73 of 2000 complete in 96.5 sec
[-                 3%                  ] 74 of 2000 complete in 97.8 sec
[-                 3%                  ] 75 of 2000 complete in 99.1 sec
[-                 3%                  ] 76 of 2000 complete in 100.4 sec
[-                 3%                  ] 77 of 2000 complete in 101.8 sec
[-                 3%                  ] 78 of 2000 complete in 103.0 sec
[-                 3%                  ] 79 of 2000 complete in 104.4 sec
[-                 4%                  ] 80 of 2000 complete in 105.6 sec
[-                 4%                  ] 81 of 2000 complete in 106.9 sec
[-                 4%                  ] 82 of 2000 complete in 108.2 sec
[-                 4%                  ] 83 of 2000 complete in 109.5 sec
[-                 4%                  ] 84 of 2000 complete in 110.7 sec
[-                 4%                  ] 85 of 2000 complete in 112.0 sec
[-                 4%                  ] 86 of 2000 complete in 113.3 sec
[-                 4%                  ] 87 of 2000 complete in 114.5 sec
[-                 4%                  ] 88 of 2000 complete in 115.8 sec
[-                 4%                  ] 89 of 2000 complete in 117.1 sec
[-                 4%                  ] 90 of 2000 complete in 118.4 sec
[-                 4%                  ] 91 of 2000 complete in 119.6 sec
[-                 4%                  ] 92 of 2000 complete in 120.9 sec
[-                 4%                  ] 93 of 2000 complete in 122.2 sec
[-                 4%                  ] 94 of 2000 complete in 123.5 sec
[-                 4%                  ] 95 of 2000 complete in 124.8 sec
[-                 4%                  ] 96 of 2000 complete in 126.1 sec
[-                 4%                  ] 97 of 2000 complete in 127.3 sec
[-                 4%                  ] 98 of 2000 complete in 128.6 sec
[-                 4%                  ] 99 of 2000 complete in 129.8 sec
[-                 5%                  ] 100 of 2000 complete in 131.2 sec
[-                 5%                  ] 101 of 2000 complete in 132.5 sec
[-                 5%                  ] 102 of 2000 complete in 133.9 sec
[-                 5%                  ] 103 of 2000 complete in 135.2 sec
[-                 5%                  ] 104 of 2000 complete in 136.5 sec
[-                 5%                  ] 105 of 2000 complete in 137.8 sec
[--                5%                  ] 106 of 2000 complete in 139.2 sec
[--                5%                  ] 107 of 2000 complete in 140.4 sec
[--                5%                  ] 108 of 2000 complete in 141.8 sec
[--                5%                  ] 109 of 2000 complete in 143.1 sec
[--                5%                  ] 110 of 2000 complete in 144.4 sec
[--                5%                  ] 111 of 2000 complete in 145.7 sec
[--                5%                  ] 112 of 2000 complete in 147.0 sec

[                  0%                  ] 2 of 2000 complete in 1.6 sec
[                  0%                  ] 3 of 2000 complete in 3.2 sec
[                  0%                  ] 4 of 2000 complete in 4.6 sec
[                  0%                  ] 5 of 2000 complete in 5.9 sec
[                  0%                  ] 6 of 2000 complete in 7.3 sec
[                  0%                  ] 7 of 2000 complete in 8.6 sec
[                  0%                  ] 8 of 2000 complete in 10.0 sec
[                  0%                  ] 9 of 2000 complete in 11.4 sec
[                  0%                  ] 10 of 2000 complete in 12.7 sec
[                  0%                  ] 11 of 2000 complete in 14.1 sec
[                  0%                  ] 12 of 2000 complete in 15.5 sec
[                  0%                  ] 13 of 2000 complete in 16.8 sec
[                  0%                  ] 14 of 2000 complete in 18.1 sec
[                  0%                  ] 15 of 2000 complete in 19.4 sec
[                  0%                  ] 16 of 2000 complete in 20.8 sec
[                  0%                  ] 17 of 2000 complete in 22.1 sec
[                  0%                  ] 18 of 2000 complete in 23.4 sec
[                  0%                  ] 19 of 2000 complete in 24.8 sec
[                  1%                  ] 20 of 2000 complete in 26.2 sec
[                  1%                  ] 21 of 2000 complete in 27.6 sec
[                  1%                  ] 22 of 2000 complete in 28.9 sec
[                  1%                  ] 23 of 2000 complete in 30.3 sec
[                  1%                  ] 24 of 2000 complete in 31.7 sec
[                  1%                  ] 25 of 2000 complete in 33.1 sec
[                  1%                  ] 26 of 2000 complete in 34.6 sec
[                  1%                  ] 27 of 2000 complete in 35.9 sec
[                  1%                  ] 28 of 2000 complete in 37.3 sec
[                  1%                  ] 29 of 2000 complete in 38.7 sec
[                  1%                  ] 30 of 2000 complete in 40.0 sec
[                  1%                  ] 31 of 2000 complete in 41.3 sec
[                  1%                  ] 32 of 2000 complete in 42.7 sec
[                  1%                  ] 33 of 2000 complete in 44.1 sec
[                  1%                  ] 34 of 2000 complete in 45.5 sec
[                  1%                  ] 35 of 2000 complete in 46.9 sec
[                  1%                  ] 36 of 2000 complete in 48.2 sec
[                  1%                  ] 37 of 2000 complete in 49.5 sec
[                  1%                  ] 38 of 2000 complete in 50.8 sec
[                  1%                  ] 39 of 2000 complete in 52.2 sec
[                  2%                  ] 40 of 2000 complete in 53.5 sec
[                  2%                  ] 41 of 2000 complete in 54.9 sec
[                  2%                  ] 42 of 2000 complete in 56.2 sec
[                  2%                  ] 43 of 2000 complete in 57.6 sec
[                  2%                  ] 44 of 2000 complete in 58.9 sec
[                  2%                  ] 45 of 2000 complete in 60.3 sec
[                  2%                  ] 46 of 2000 complete in 61.8 sec
[                  2%                  ] 47 of 2000 complete in 63.2 sec
[                  2%                  ] 48 of 2000 complete in 64.6 sec
[                  2%                  ] 49 of 2000 complete in 65.9 sec
[                  2%                  ] 50 of 2000 complete in 67.3 sec
[                  2%                  ] 51 of 2000 complete in 68.6 sec
[                  2%                  ] 52 of 2000 complete in 70.0 sec
[-                 2%                  ] 53 of 2000 complete in 71.4 sec
[-                 2%                  ] 54 of 2000 complete in 72.8 sec
[-                 2%                  ] 55 of 2000 complete in 74.2 sec
[-                 2%                  ] 56 of 2000 complete in 75.6 sec
[-                 2%                  ] 57 of 2000 complete in 77.0 sec
[-                 2%                  ] 58 of 2000 complete in 78.4 sec
[-                 2%                  ] 59 of 2000 complete in 79.8 sec
[-                 3%                  ] 60 of 2000 complete in 81.2 sec
[-                 3%                  ] 61 of 2000 complete in 82.5 sec
[-                 3%                  ] 62 of 2000 complete in 84.0 sec
[-                 3%                  ] 63 of 2000 complete in 85.4 sec
[-                 3%                  ] 64 of 2000 complete in 86.7 sec
[-                 3%                  ] 65 of 2000 complete in 88.1 sec
[-                 3%                  ] 66 of 2000 complete in 89.6 sec
[-                 3%                  ] 67 of 2000 complete in 91.0 sec
[-                 3%                  ] 68 of 2000 complete in 92.3 sec
[-                 3%                  ] 69 of 2000 complete in 93.7 sec
[-                 3%                  ] 70 of 2000 complete in 95.0 sec
[-                 3%                  ] 71 of 2000 complete in 96.3 sec
[-                 3%                  ] 72 of 2000 complete in 97.7 sec
[-                 3%                  ] 73 of 2000 complete in 99.1 sec
[-                 3%                  ] 74 of 2000 complete in 100.4 sec
[-                 3%                  ] 75 of 2000 complete in 101.8 sec
[-                 3%                  ] 76 of 2000 complete in 103.2 sec
[-                 3%                  ] 77 of 2000 complete in 104.4 sec
[-                 3%                  ] 78 of 2000 complete in 105.7 sec
[-                 3%                  ] 79 of 2000 complete in 107.1 sec
[-                 4%                  ] 80 of 2000 complete in 108.4 sec
[-                 4%                  ] 81 of 2000 complete in 109.7 sec
[-                 4%                  ] 82 of 2000 complete in 111.0 sec
[-                 4%                  ] 83 of 2000 complete in 112.3 sec
[-                 4%                  ] 84 of 2000 complete in 113.6 sec
[-                 4%                  ] 85 of 2000 complete in 114.8 sec
[-                 4%                  ] 86 of 2000 complete in 116.2 sec
[-                 4%                  ] 87 of 2000 complete in 117.4 sec
[-                 4%                  ] 88 of 2000 complete in 118.7 sec
[-                 4%                  ] 89 of 2000 complete in 120.0 sec
[-                 4%                  ] 90 of 2000 complete in 121.3 sec
[-                 4%                  ] 91 of 2000 complete in 122.5 sec
[-                 4%                  ] 92 of 2000 complete in 123.8 sec
[-                 4%                  ] 93 of 2000 complete in 125.0 sec
[-                 4%                  ] 94 of 2000 complete in 126.3 sec
[-                 4%                  ] 95 of 2000 complete in 127.5 sec
[-                 4%                  ] 96 of 2000 complete in 128.9 sec
[-                 4%                  ] 97 of 2000 complete in 130.1 sec
[-                 4%                  ] 98 of 2000 complete in 131.4 sec
[-                 4%                  ] 99 of 2000 complete in 132.7 sec
[-                 5%                  ] 100 of 2000 complete in 134.0 sec
[-                 5%                  ] 101 of 2000 complete in 135.3 sec
[-                 5%                  ] 102 of 2000 complete in 136.5 sec
[-                 5%                  ] 103 of 2000 complete in 137.8 sec
[-                 5%                  ] 104 of 2000 complete in 139.1 sec
[-                 5%                  ] 105 of 2000 complete in 140.3 sec
[--                5%                  ] 106 of 2000 complete in 141.6 sec
[--                5%                  ] 107 of 2000 complete in 142.9 sec
[--                5%                  ] 108 of 2000 complete in 144.1 sec
[--                5%                  ] 109 of 2000 complete in 145.3 sec
[--                5%                  ] 110 of 2000 complete in 146.6 sec
[--                5%                  ] 111 of 2000 complete in 147.8 sec
[--                5%                  ] 112 of 2000 complete in 149.1 sec
[                  0%                  ] 2 of 2000 complete in 1.4 sec
[                  0%                  ] 3 of 2000 complete in 3.2 sec
[                  0%                  ] 4 of 2000 complete in 4.8 sec
[                  0%                  ] 5 of 2000 complete in 6.1 sec
[                  0%                  ] 6 of 2000 complete in 7.6 sec
[                  0%                  ] 7 of 2000 complete in 8.9 sec
[                  0%                  ] 8 of 2000 complete in 10.3 sec
[                  0%                  ] 9 of 2000 complete in 11.6 sec
[                  0%                  ] 10 of 2000 complete in 13.0 sec
[                  0%                  ] 11 of 2000 complete in 14.3 sec
[                  0%                  ] 12 of 2000 complete in 15.6 sec
[                  0%                  ] 13 of 2000 complete in 17.0 sec
[                  0%                  ] 14 of 2000 complete in 18.3 sec
[                  0%                  ] 15 of 2000 complete in 19.7 sec
[                  0%                  ] 16 of 2000 complete in 21.0 sec
[                  0%                  ] 17 of 2000 complete in 22.4 sec
[                  0%                  ] 18 of 2000 complete in 23.7 sec
[                  0%                  ] 19 of 2000 complete in 25.2 sec
[                  1%                  ] 20 of 2000 complete in 26.6 sec
[                  1%                  ] 21 of 2000 complete in 28.0 sec
[                  1%                  ] 22 of 2000 complete in 29.4 sec
[                  1%                  ] 23 of 2000 complete in 30.8 sec
[                  1%                  ] 24 of 2000 complete in 32.1 sec
[                  1%                  ] 25 of 2000 complete in 33.6 sec
[                  1%                  ] 26 of 2000 complete in 35.0 sec
[                  1%                  ] 27 of 2000 complete in 36.4 sec
[                  1%                  ] 28 of 2000 complete in 37.8 sec
[                  1%                  ] 29 of 2000 complete in 39.2 sec
[                  1%                  ] 30 of 2000 complete in 40.5 sec
[                  1%                  ] 31 of 2000 complete in 41.9 sec
[                  1%                  ] 32 of 2000 complete in 43.3 sec
[                  1%                  ] 33 of 2000 complete in 44.7 sec
[                  1%                  ] 34 of 2000 complete in 46.0 sec
[                  1%                  ] 35 of 2000 complete in 47.3 sec
[                  1%                  ] 36 of 2000 complete in 48.6 sec
[                  1%                  ] 37 of 2000 complete in 49.9 sec
[                  1%                  ] 38 of 2000 complete in 51.3 sec
[                  1%                  ] 39 of 2000 complete in 52.6 sec
[                  2%                  ] 40 of 2000 complete in 53.9 sec
[                  2%                  ] 41 of 2000 complete in 55.3 sec
[                  2%                  ] 42 of 2000 complete in 56.6 sec
[                  2%                  ] 43 of 2000 complete in 57.9 sec
[                  2%                  ] 44 of 2000 complete in 59.3 sec
[                  2%                  ] 45 of 2000 complete in 60.6 sec
[                  2%                  ] 46 of 2000 complete in 62.1 sec
[                  2%                  ] 47 of 2000 complete in 63.6 sec
[                  2%                  ] 48 of 2000 complete in 65.0 sec
[                  2%                  ] 49 of 2000 complete in 66.3 sec
[                  2%                  ] 50 of 2000 complete in 67.6 sec
[                  2%                  ] 51 of 2000 complete in 68.9 sec
[                  2%                  ] 52 of 2000 complete in 70.3 sec
[-                 2%                  ] 53 of 2000 complete in 71.6 sec
[-                 2%                  ] 54 of 2000 complete in 72.9 sec
[-                 2%                  ] 55 of 2000 complete in 74.3 sec
[-                 2%                  ] 56 of 2000 complete in 75.7 sec
[-                 2%                  ] 57 of 2000 complete in 77.1 sec
[-                 2%                  ] 58 of 2000 complete in 78.5 sec
[-                 2%                  ] 59 of 2000 complete in 79.9 sec
[-                 3%                  ] 60 of 2000 complete in 81.4 sec
[-                 3%                  ] 61 of 2000 complete in 82.7 sec
[-                 3%                  ] 62 of 2000 complete in 84.1 sec
[-                 3%                  ] 63 of 2000 complete in 85.4 sec
[-                 3%                  ] 64 of 2000 complete in 86.8 sec
[-                 3%                  ] 65 of 2000 complete in 88.3 sec
[-                 3%                  ] 66 of 2000 complete in 89.7 sec
[-                 3%                  ] 67 of 2000 complete in 91.1 sec
[-                 3%                  ] 68 of 2000 complete in 92.5 sec
[-                 3%                  ] 69 of 2000 complete in 93.9 sec
[-                 3%                  ] 70 of 2000 complete in 95.3 sec
[-                 3%                  ] 71 of 2000 complete in 96.6 sec
[-                 3%                  ] 72 of 2000 complete in 98.1 sec
[-                 3%                  ] 73 of 2000 complete in 99.4 sec
[-                 3%                  ] 74 of 2000 complete in 100.8 sec
[-                 3%                  ] 75 of 2000 complete in 102.1 sec
[-                 3%                  ] 76 of 2000 complete in 103.5 sec
[-                 3%                  ] 77 of 2000 complete in 104.9 sec
[-                 3%                  ] 78 of 2000 complete in 106.3 sec
[-                 3%                  ] 79 of 2000 complete in 107.7 sec
[-                 4%                  ] 80 of 2000 complete in 109.1 sec
[-                 4%                  ] 81 of 2000 complete in 110.5 sec
[-                 4%                  ] 82 of 2000 complete in 111.9 sec
[-                 4%                  ] 83 of 2000 complete in 113.3 sec
[-                 4%                  ] 84 of 2000 complete in 114.7 sec
[-                 4%                  ] 85 of 2000 complete in 116.1 sec
[-                 4%                  ] 86 of 2000 complete in 117.5 sec
[-                 4%                  ] 87 of 2000 complete in 118.9 sec
[-                 4%                  ] 88 of 2000 complete in 120.3 sec
[-                 4%                  ] 89 of 2000 complete in 121.7 sec
[-                 4%                  ] 90 of 2000 complete in 123.1 sec
[-                 4%                  ] 91 of 2000 complete in 124.5 sec
[-                 4%                  ] 92 of 2000 complete in 125.9 sec
[-                 4%                  ] 93 of 2000 complete in 127.4 sec
[-                 4%                  ] 94 of 2000 complete in 128.8 sec
[-                 4%                  ] 95 of 2000 complete in 130.2 sec
[-                 4%                  ] 96 of 2000 complete in 131.5 sec
[-                 4%                  ] 97 of 2000 complete in 132.9 sec
[-                 4%                  ] 98 of 2000 complete in 134.4 sec
[-                 4%                  ] 99 of 2000 complete in 135.8 sec
[-                 5%                  ] 100 of 2000 complete in 137.2 sec
[-                 5%                  ] 101 of 2000 complete in 138.6 sec
[-                 5%                  ] 102 of 2000 complete in 140.0 sec
[-                 5%                  ] 103 of 2000 complete in 141.4 sec
[-                 5%                  ] 104 of 2000 complete in 142.9 sec
[-                 5%                  ] 105 of 2000 complete in 144.3 sec
[--                5%                  ] 106 of 2000 complete in 145.8 sec
[--                5%                  ] 107 of 2000 complete in 147.3 sec
[--                5%                  ] 108 of 2000 complete in 148.8 sec
[--                5%                  ] 109 of 2000 complete in 150.2 sec
[--                5%                  ] 110 of 2000 complete in 151.6 sec
[--                5%                  ] 111 of 2000 complete in 153.1 sec
[--                5%                  ] 112 of 2000 complete in 154.6 sec

[--                5%                  ] 113 of 2000 complete in 141.7 sec
[--                5%                  ] 114 of 2000 complete in 142.9 sec
[--                5%                  ] 115 of 2000 complete in 144.0 sec
[--                5%                  ] 116 of 2000 complete in 145.1 sec
[--                5%                  ] 117 of 2000 complete in 146.3 sec
[--                5%                  ] 118 of 2000 complete in 147.5 sec
[--                5%                  ] 119 of 2000 complete in 148.8 sec
[--                6%                  ] 120 of 2000 complete in 149.9 sec
[--                6%                  ] 121 of 2000 complete in 151.1 sec
[--                6%                  ] 122 of 2000 complete in 152.3 sec
[--                6%                  ] 123 of 2000 complete in 153.4 sec
[--                6%                  ] 124 of 2000 complete in 154.5 sec
[--                6%                  ] 125 of 2000 complete in 155.7 sec
[--                6%                  ] 126 of 2000 complete in 156.9 sec
[--                6%                  ] 127 of 2000 complete in 158.1 sec
[--                6%                  ] 128 of 2000 complete in 159.3 sec
[--                6%                  ] 129 of 2000 complete in 160.4 sec
[--                6%                  ] 130 of 2000 complete in 161.5 sec
[--                6%                  ] 131 of 2000 complete in 162.6 sec
[--                6%                  ] 132 of 2000 complete in 163.7 sec
[--                6%                  ] 133 of 2000 complete in 164.8 sec
[--                6%                  ] 134 of 2000 complete in 165.9 sec
[--                6%                  ] 135 of 2000 complete in 166.9 sec
[--                6%                  ] 136 of 2000 complete in 168.0 sec
[--                6%                  ] 137 of 2000 complete in 169.0 sec
[--                6%                  ] 138 of 2000 complete in 170.1 sec
[--                6%                  ] 139 of 2000 complete in 171.2 sec
[--                7%                  ] 140 of 2000 complete in 172.3 sec
[--                7%                  ] 141 of 2000 complete in 173.4 sec
[--                7%                  ] 142 of 2000 complete in 174.5 sec
[--                7%                  ] 143 of 2000 complete in 175.6 sec
[--                7%                  ] 144 of 2000 complete in 176.8 sec
[--                7%                  ] 145 of 2000 complete in 178.0 sec
[--                7%                  ] 146 of 2000 complete in 179.1 sec
[--                7%                  ] 147 of 2000 complete in 180.2 sec
[--                7%                  ] 148 of 2000 complete in 181.3 sec
[--                7%                  ] 149 of 2000 complete in 182.5 sec
[--                7%                  ] 150 of 2000 complete in 183.6 sec
[--                7%                  ] 151 of 2000 complete in 184.7 sec
[--                7%                  ] 152 of 2000 complete in 185.8 sec
[--                7%                  ] 153 of 2000 complete in 187.0 sec
[--                7%                  ] 154 of 2000 complete in 188.1 sec
[--                7%                  ] 155 of 2000 complete in 189.3 sec
[--                7%                  ] 156 of 2000 complete in 190.4 sec
[--                7%                  ] 157 of 2000 complete in 191.4 sec
[---               7%                  ] 158 of 2000 complete in 192.5 sec
[---               7%                  ] 159 of 2000 complete in 193.5 sec
[---               8%                  ] 160 of 2000 complete in 194.6 sec
[---               8%                  ] 161 of 2000 complete in 195.6 sec
[---               8%                  ] 162 of 2000 complete in 196.7 sec
[---               8%                  ] 163 of 2000 complete in 197.7 sec
[---               8%                  ] 164 of 2000 complete in 198.8 sec
[---               8%                  ] 165 of 2000 complete in 199.9 sec
[---               8%                  ] 166 of 2000 complete in 200.9 sec
[---               8%                  ] 167 of 2000 complete in 202.0 sec
[---               8%                  ] 168 of 2000 complete in 203.1 sec
[---               8%                  ] 169 of 2000 complete in 204.2 sec
[---               8%                  ] 170 of 2000 complete in 205.5 sec
[---               8%                  ] 171 of 2000 complete in 206.7 sec
[---               8%                  ] 172 of 2000 complete in 207.9 sec
[---               8%                  ] 173 of 2000 complete in 209.1 sec
[---               8%                  ] 174 of 2000 complete in 210.2 sec
[---               8%                  ] 175 of 2000 complete in 211.4 sec
[---               8%                  ] 176 of 2000 complete in 212.7 sec
[---               8%                  ] 177 of 2000 complete in 213.9 sec
[---               8%                  ] 178 of 2000 complete in 215.2 sec
[---               8%                  ] 179 of 2000 complete in 216.4 sec
[---               9%                  ] 180 of 2000 complete in 217.7 sec
[---               9%                  ] 181 of 2000 complete in 218.9 sec
[---               9%                  ] 182 of 2000 complete in 220.2 sec
[---               9%                  ] 183 of 2000 complete in 221.5 sec
[---               9%                  ] 184 of 2000 complete in 222.9 sec
[---               9%                  ] 185 of 2000 complete in 224.2 sec
[---               9%                  ] 186 of 2000 complete in 225.5 sec
[---               9%                  ] 187 of 2000 complete in 226.8 sec
[---               9%                  ] 188 of 2000 complete in 228.1 sec
[---               9%                  ] 189 of 2000 complete in 229.4 sec
[---               9%                  ] 190 of 2000 complete in 230.7 sec
[---               9%                  ] 191 of 2000 complete in 231.9 sec
[---               9%                  ] 192 of 2000 complete in 233.2 sec
[---               9%                  ] 193 of 2000 complete in 234.5 sec
[---               9%                  ] 194 of 2000 complete in 235.8 sec
[---               9%                  ] 195 of 2000 complete in 237.1 sec
[---               9%                  ] 196 of 2000 complete in 238.5 sec
[---               9%                  ] 197 of 2000 complete in 239.8 sec
[---               9%                  ] 198 of 2000 complete in 241.1 sec
[---               9%                  ] 199 of 2000 complete in 242.4 sec
[---              10%                  ] 200 of 2000 complete in 243.8 sec
[---              10%                  ] 201 of 2000 complete in 245.2 sec
[---              10%                  ] 202 of 2000 complete in 246.5 sec
[---              10%                  ] 203 of 2000 complete in 247.8 sec
[---              10%                  ] 204 of 2000 complete in 249.2 sec
[---              10%                  ] 205 of 2000 complete in 250.4 sec
[---              10%                  ] 206 of 2000 complete in 251.8 sec
[---              10%                  ] 207 of 2000 complete in 253.2 sec
[---              10%                  ] 208 of 2000 complete in 254.6 sec
[---              10%                  ] 209 of 2000 complete in 256.0 sec
[---              10%                  ] 210 of 2000 complete in 257.3 sec
[----             10%                  ] 211 of 2000 complete in 258.7 sec
[----             10%                  ] 212 of 2000 complete in 260.0 sec
[----             10%                  ] 213 of 2000 complete in 261.4 sec
[----             10%                  ] 214 of 2000 complete in 262.8 sec
[----             10%                  ] 215 of 2000 complete in 264.2 sec
[----             10%                  ] 216 of 2000 complete in 265.5 sec
[----             10%                  ] 217 of 2000 complete in 266.9 sec
[----             10%                  ] 218 of 2000 complete in 268.2 sec
[----             10%                  ] 219 of 2000 complete in 269.5 sec
[----             11%                  ] 220 of 2000 complete in 270.8 sec
[----             11%                  ] 221 of 2000 complete in 272.2 sec
[--                5%                  ] 113 of 2000 complete in 150.3 sec
[--                5%                  ] 114 of 2000 complete in 151.6 sec
[--                5%                  ] 115 of 2000 complete in 152.9 sec
[--                5%                  ] 116 of 2000 complete in 154.2 sec
[--                5%                  ] 117 of 2000 complete in 155.4 sec
[--                5%                  ] 118 of 2000 complete in 156.7 sec
[--                5%                  ] 119 of 2000 complete in 157.9 sec
[--                6%                  ] 120 of 2000 complete in 159.2 sec
[--                6%                  ] 121 of 2000 complete in 160.4 sec
[--                6%                  ] 122 of 2000 complete in 161.6 sec
[--                6%                  ] 123 of 2000 complete in 162.9 sec
[--                6%                  ] 124 of 2000 complete in 164.1 sec
[--                6%                  ] 125 of 2000 complete in 165.3 sec
[--                6%                  ] 126 of 2000 complete in 166.6 sec
[--                6%                  ] 127 of 2000 complete in 167.8 sec
[--                6%                  ] 128 of 2000 complete in 169.1 sec
[--                6%                  ] 129 of 2000 complete in 170.3 sec
[--                6%                  ] 130 of 2000 complete in 171.5 sec
[--                6%                  ] 131 of 2000 complete in 172.8 sec
[--                6%                  ] 132 of 2000 complete in 174.0 sec
[--                6%                  ] 133 of 2000 complete in 175.3 sec
[--                6%                  ] 134 of 2000 complete in 176.6 sec
[--                6%                  ] 135 of 2000 complete in 177.8 sec
[--                6%                  ] 136 of 2000 complete in 179.0 sec
[--                6%                  ] 137 of 2000 complete in 180.4 sec
[--                6%                  ] 138 of 2000 complete in 181.7 sec
[--                6%                  ] 139 of 2000 complete in 182.9 sec
[--                7%                  ] 140 of 2000 complete in 184.2 sec
[--                7%                  ] 141 of 2000 complete in 185.5 sec
[--                7%                  ] 142 of 2000 complete in 186.7 sec
[--                7%                  ] 143 of 2000 complete in 188.0 sec
[--                7%                  ] 144 of 2000 complete in 189.3 sec
[--                7%                  ] 145 of 2000 complete in 190.6 sec
[--                7%                  ] 146 of 2000 complete in 192.0 sec
[--                7%                  ] 147 of 2000 complete in 193.3 sec
[--                7%                  ] 148 of 2000 complete in 194.6 sec
[--                7%                  ] 149 of 2000 complete in 195.9 sec
[--                7%                  ] 150 of 2000 complete in 197.2 sec
[--                7%                  ] 151 of 2000 complete in 198.5 sec
[--                7%                  ] 152 of 2000 complete in 199.8 sec
[--                7%                  ] 153 of 2000 complete in 201.1 sec
[--                7%                  ] 154 of 2000 complete in 202.4 sec
[--                7%                  ] 155 of 2000 complete in 203.7 sec
[--                7%                  ] 156 of 2000 complete in 205.0 sec
[--                7%                  ] 157 of 2000 complete in 206.4 sec
[---               7%                  ] 158 of 2000 complete in 207.7 sec
[---               7%                  ] 159 of 2000 complete in 209.0 sec
[---               8%                  ] 160 of 2000 complete in 210.3 sec
[---               8%                  ] 161 of 2000 complete in 211.5 sec
[---               8%                  ] 162 of 2000 complete in 212.8 sec
[---               8%                  ] 163 of 2000 complete in 214.1 sec
[---               8%                  ] 164 of 2000 complete in 215.4 sec
[---               8%                  ] 165 of 2000 complete in 216.7 sec
[---               8%                  ] 166 of 2000 complete in 218.1 sec
[---               8%                  ] 167 of 2000 complete in 219.4 sec
[---               8%                  ] 168 of 2000 complete in 220.8 sec
[---               8%                  ] 169 of 2000 complete in 222.1 sec
[---               8%                  ] 170 of 2000 complete in 223.4 sec
[---               8%                  ] 171 of 2000 complete in 224.8 sec
[---               8%                  ] 172 of 2000 complete in 226.1 sec
[---               8%                  ] 173 of 2000 complete in 227.4 sec
[---               8%                  ] 174 of 2000 complete in 228.8 sec
[---               8%                  ] 175 of 2000 complete in 230.1 sec
[---               8%                  ] 176 of 2000 complete in 231.4 sec
[---               8%                  ] 177 of 2000 complete in 232.7 sec
[---               8%                  ] 178 of 2000 complete in 234.0 sec
[---               8%                  ] 179 of 2000 complete in 235.2 sec
[---               9%                  ] 180 of 2000 complete in 236.5 sec
[---               9%                  ] 181 of 2000 complete in 237.9 sec
[---               9%                  ] 182 of 2000 complete in 239.2 sec
[---               9%                  ] 183 of 2000 complete in 240.5 sec
[---               9%                  ] 184 of 2000 complete in 241.9 sec
[---               9%                  ] 185 of 2000 complete in 243.2 sec
[---               9%                  ] 186 of 2000 complete in 244.5 sec
[---               9%                  ] 187 of 2000 complete in 245.8 sec
[---               9%                  ] 188 of 2000 complete in 247.2 sec
[---               9%                  ] 189 of 2000 complete in 248.6 sec
[---               9%                  ] 190 of 2000 complete in 249.9 sec
[---               9%                  ] 191 of 2000 complete in 251.3 sec
[---               9%                  ] 192 of 2000 complete in 252.6 sec
[---               9%                  ] 193 of 2000 complete in 253.9 sec
[---               9%                  ] 194 of 2000 complete in 255.2 sec
[---               9%                  ] 195 of 2000 complete in 256.5 sec
[---               9%                  ] 196 of 2000 complete in 257.8 sec
[---               9%                  ] 197 of 2000 complete in 259.1 sec
[---               9%                  ] 198 of 2000 complete in 260.4 sec
[---               9%                  ] 199 of 2000 complete in 261.7 sec
[---              10%                  ] 200 of 2000 complete in 263.0 sec
[---              10%                  ] 201 of 2000 complete in 264.3 sec
[---              10%                  ] 202 of 2000 complete in 265.6 sec
[---              10%                  ] 203 of 2000 complete in 266.9 sec
[---              10%                  ] 204 of 2000 complete in 268.2 sec
[---              10%                  ] 205 of 2000 complete in 269.5 sec
[---              10%                  ] 206 of 2000 complete in 270.9 sec
[---              10%                  ] 207 of 2000 complete in 272.2 sec
[---              10%                  ] 208 of 2000 complete in 273.6 sec
[---              10%                  ] 209 of 2000 complete in 274.9 sec
[---              10%                  ] 210 of 2000 complete in 276.1 sec
[----             10%                  ] 211 of 2000 complete in 277.5 sec
[----             10%                  ] 212 of 2000 complete in 278.8 sec
[----             10%                  ] 213 of 2000 complete in 280.1 sec
[----             10%                  ] 214 of 2000 complete in 281.4 sec
[----             10%                  ] 215 of 2000 complete in 282.8 sec
[----             10%                  ] 216 of 2000 complete in 284.1 sec
[----             10%                  ] 217 of 2000 complete in 285.5 sec
[----             10%                  ] 218 of 2000 complete in 286.8 sec
[----             10%                  ] 219 of 2000 complete in 288.2 sec
[----             11%                  ] 220 of 2000 complete in 289.5 sec
[----             11%                  ] 221 of 2000 complete in 290.8 sec

[--                5%                  ] 113 of 2000 complete in 148.4 sec
[--                5%                  ] 114 of 2000 complete in 149.8 sec
[--                5%                  ] 115 of 2000 complete in 151.1 sec
[--                5%                  ] 116 of 2000 complete in 152.4 sec
[--                5%                  ] 117 of 2000 complete in 153.7 sec
[--                5%                  ] 118 of 2000 complete in 155.1 sec
[--                5%                  ] 119 of 2000 complete in 156.4 sec
[--                6%                  ] 120 of 2000 complete in 157.7 sec
[--                6%                  ] 121 of 2000 complete in 159.1 sec
[--                6%                  ] 122 of 2000 complete in 160.4 sec
[--                6%                  ] 123 of 2000 complete in 161.7 sec
[--                6%                  ] 124 of 2000 complete in 163.1 sec
[--                6%                  ] 125 of 2000 complete in 164.4 sec
[--                6%                  ] 126 of 2000 complete in 165.7 sec
[--                6%                  ] 127 of 2000 complete in 167.0 sec
[--                6%                  ] 128 of 2000 complete in 168.4 sec
[--                6%                  ] 129 of 2000 complete in 169.7 sec
[--                6%                  ] 130 of 2000 complete in 171.1 sec
[--                6%                  ] 131 of 2000 complete in 172.4 sec
[--                6%                  ] 132 of 2000 complete in 173.7 sec
[--                6%                  ] 133 of 2000 complete in 175.0 sec
[--                6%                  ] 134 of 2000 complete in 176.3 sec
[--                6%                  ] 135 of 2000 complete in 177.6 sec
[--                6%                  ] 136 of 2000 complete in 179.0 sec
[--                6%                  ] 137 of 2000 complete in 180.3 sec
[--                6%                  ] 138 of 2000 complete in 181.6 sec
[--                6%                  ] 139 of 2000 complete in 182.9 sec
[--                7%                  ] 140 of 2000 complete in 184.2 sec
[--                7%                  ] 141 of 2000 complete in 185.5 sec
[--                7%                  ] 142 of 2000 complete in 186.8 sec
[--                7%                  ] 143 of 2000 complete in 188.2 sec
[--                7%                  ] 144 of 2000 complete in 189.5 sec
[--                7%                  ] 145 of 2000 complete in 190.8 sec
[--                7%                  ] 146 of 2000 complete in 192.1 sec
[--                7%                  ] 147 of 2000 complete in 193.4 sec
[--                7%                  ] 148 of 2000 complete in 194.7 sec
[--                7%                  ] 149 of 2000 complete in 196.0 sec
[--                7%                  ] 150 of 2000 complete in 197.3 sec
[--                7%                  ] 151 of 2000 complete in 198.6 sec
[--                7%                  ] 152 of 2000 complete in 199.9 sec
[--                7%                  ] 153 of 2000 complete in 201.2 sec
[--                7%                  ] 154 of 2000 complete in 202.5 sec
[--                7%                  ] 155 of 2000 complete in 203.8 sec
[--                7%                  ] 156 of 2000 complete in 205.2 sec
[--                7%                  ] 157 of 2000 complete in 206.5 sec
[---               7%                  ] 158 of 2000 complete in 207.9 sec
[---               7%                  ] 159 of 2000 complete in 209.1 sec
[---               8%                  ] 160 of 2000 complete in 210.4 sec
[---               8%                  ] 161 of 2000 complete in 211.7 sec
[---               8%                  ] 162 of 2000 complete in 213.0 sec
[---               8%                  ] 163 of 2000 complete in 214.2 sec
[---               8%                  ] 164 of 2000 complete in 215.4 sec
[---               8%                  ] 165 of 2000 complete in 216.7 sec
[---               8%                  ] 166 of 2000 complete in 218.0 sec
[---               8%                  ] 167 of 2000 complete in 219.3 sec
[---               8%                  ] 168 of 2000 complete in 220.6 sec
[---               8%                  ] 169 of 2000 complete in 221.9 sec
[---               8%                  ] 170 of 2000 complete in 223.3 sec
[---               8%                  ] 171 of 2000 complete in 224.5 sec
[---               8%                  ] 172 of 2000 complete in 225.8 sec
[---               8%                  ] 173 of 2000 complete in 227.1 sec
[---               8%                  ] 174 of 2000 complete in 228.4 sec
[---               8%                  ] 175 of 2000 complete in 229.7 sec
[---               8%                  ] 176 of 2000 complete in 231.0 sec
[---               8%                  ] 177 of 2000 complete in 232.4 sec
[---               8%                  ] 178 of 2000 complete in 233.7 sec
[---               8%                  ] 179 of 2000 complete in 235.1 sec
[---               9%                  ] 180 of 2000 complete in 236.4 sec
[---               9%                  ] 181 of 2000 complete in 237.7 sec
[---               9%                  ] 182 of 2000 complete in 239.0 sec
[---               9%                  ] 183 of 2000 complete in 240.3 sec
[---               9%                  ] 184 of 2000 complete in 241.7 sec
[---               9%                  ] 185 of 2000 complete in 243.1 sec
[---               9%                  ] 186 of 2000 complete in 244.4 sec
[---               9%                  ] 187 of 2000 complete in 245.7 sec
[---               9%                  ] 188 of 2000 complete in 246.9 sec
[---               9%                  ] 189 of 2000 complete in 248.2 sec
[---               9%                  ] 190 of 2000 complete in 249.4 sec
[---               9%                  ] 191 of 2000 complete in 250.7 sec
[---               9%                  ] 192 of 2000 complete in 252.0 sec
[---               9%                  ] 193 of 2000 complete in 253.3 sec
[---               9%                  ] 194 of 2000 complete in 254.6 sec
[---               9%                  ] 195 of 2000 complete in 255.8 sec
[---               9%                  ] 196 of 2000 complete in 257.2 sec
[---               9%                  ] 197 of 2000 complete in 258.5 sec
[---               9%                  ] 198 of 2000 complete in 259.9 sec
[---               9%                  ] 199 of 2000 complete in 261.3 sec
[---              10%                  ] 200 of 2000 complete in 262.7 sec
[---              10%                  ] 201 of 2000 complete in 264.0 sec
[---              10%                  ] 202 of 2000 complete in 265.4 sec
[---              10%                  ] 203 of 2000 complete in 266.8 sec
[---              10%                  ] 204 of 2000 complete in 268.2 sec
[---              10%                  ] 205 of 2000 complete in 269.6 sec
[---              10%                  ] 206 of 2000 complete in 271.0 sec
[---              10%                  ] 207 of 2000 complete in 272.4 sec
[---              10%                  ] 208 of 2000 complete in 273.7 sec
[---              10%                  ] 209 of 2000 complete in 275.1 sec
[---              10%                  ] 210 of 2000 complete in 276.4 sec
[----             10%                  ] 211 of 2000 complete in 277.8 sec
[----             10%                  ] 212 of 2000 complete in 279.2 sec
[----             10%                  ] 213 of 2000 complete in 280.5 sec
[----             10%                  ] 214 of 2000 complete in 281.9 sec
[----             10%                  ] 215 of 2000 complete in 283.2 sec
[----             10%                  ] 216 of 2000 complete in 284.5 sec
[----             10%                  ] 217 of 2000 complete in 285.9 sec
[----             10%                  ] 218 of 2000 complete in 287.2 sec
[----             10%                  ] 219 of 2000 complete in 288.5 sec
[----             11%                  ] 220 of 2000 complete in 289.8 sec
[----             11%                  ] 221 of 2000 complete in 291.1 sec
[--                5%                  ] 113 of 2000 complete in 156.1 sec
[--                5%                  ] 114 of 2000 complete in 157.5 sec
[--                5%                  ] 115 of 2000 complete in 158.9 sec
[--                5%                  ] 116 of 2000 complete in 160.4 sec
[--                5%                  ] 117 of 2000 complete in 161.8 sec
[--                5%                  ] 118 of 2000 complete in 163.2 sec
[--                5%                  ] 119 of 2000 complete in 164.6 sec
[--                6%                  ] 120 of 2000 complete in 166.0 sec
[--                6%                  ] 121 of 2000 complete in 167.4 sec
[--                6%                  ] 122 of 2000 complete in 168.9 sec
[--                6%                  ] 123 of 2000 complete in 170.4 sec
[--                6%                  ] 124 of 2000 complete in 171.8 sec
[--                6%                  ] 125 of 2000 complete in 173.2 sec
[--                6%                  ] 126 of 2000 complete in 174.6 sec
[--                6%                  ] 127 of 2000 complete in 176.0 sec
[--                6%                  ] 128 of 2000 complete in 177.4 sec
[--                6%                  ] 129 of 2000 complete in 178.9 sec
[--                6%                  ] 130 of 2000 complete in 180.3 sec
[--                6%                  ] 131 of 2000 complete in 181.7 sec
[--                6%                  ] 132 of 2000 complete in 183.0 sec
[--                6%                  ] 133 of 2000 complete in 184.4 sec
[--                6%                  ] 134 of 2000 complete in 185.9 sec
[--                6%                  ] 135 of 2000 complete in 187.2 sec
[--                6%                  ] 136 of 2000 complete in 188.7 sec
[--                6%                  ] 137 of 2000 complete in 190.1 sec
[--                6%                  ] 138 of 2000 complete in 191.6 sec
[--                6%                  ] 139 of 2000 complete in 192.9 sec
[--                7%                  ] 140 of 2000 complete in 194.4 sec
[--                7%                  ] 141 of 2000 complete in 195.9 sec
[--                7%                  ] 142 of 2000 complete in 197.3 sec
[--                7%                  ] 143 of 2000 complete in 198.7 sec
[--                7%                  ] 144 of 2000 complete in 200.1 sec
[--                7%                  ] 145 of 2000 complete in 201.5 sec
[--                7%                  ] 146 of 2000 complete in 203.0 sec
[--                7%                  ] 147 of 2000 complete in 204.4 sec
[--                7%                  ] 148 of 2000 complete in 205.9 sec
[--                7%                  ] 149 of 2000 complete in 207.4 sec
[--                7%                  ] 150 of 2000 complete in 208.8 sec
[--                7%                  ] 151 of 2000 complete in 210.2 sec
[--                7%                  ] 152 of 2000 complete in 211.6 sec
[--                7%                  ] 153 of 2000 complete in 213.1 sec
[--                7%                  ] 154 of 2000 complete in 214.5 sec
[--                7%                  ] 155 of 2000 complete in 215.8 sec
[--                7%                  ] 156 of 2000 complete in 217.2 sec
[--                7%                  ] 157 of 2000 complete in 218.6 sec
[---               7%                  ] 158 of 2000 complete in 220.1 sec
[---               7%                  ] 159 of 2000 complete in 221.6 sec
[---               8%                  ] 160 of 2000 complete in 223.0 sec
[---               8%                  ] 161 of 2000 complete in 224.5 sec
[---               8%                  ] 162 of 2000 complete in 225.9 sec
[---               8%                  ] 163 of 2000 complete in 227.3 sec
[---               8%                  ] 164 of 2000 complete in 228.7 sec
[---               8%                  ] 165 of 2000 complete in 230.1 sec
[---               8%                  ] 166 of 2000 complete in 231.6 sec
[---               8%                  ] 167 of 2000 complete in 233.0 sec
[---               8%                  ] 168 of 2000 complete in 234.4 sec
[---               8%                  ] 169 of 2000 complete in 235.9 sec
[---               8%                  ] 170 of 2000 complete in 237.3 sec
[---               8%                  ] 171 of 2000 complete in 238.8 sec
[---               8%                  ] 172 of 2000 complete in 240.2 sec
[---               8%                  ] 173 of 2000 complete in 241.6 sec
[---               8%                  ] 174 of 2000 complete in 243.0 sec
[---               8%                  ] 175 of 2000 complete in 244.4 sec
[---               8%                  ] 176 of 2000 complete in 245.8 sec
[---               8%                  ] 177 of 2000 complete in 247.3 sec
[---               8%                  ] 178 of 2000 complete in 248.6 sec
[---               8%                  ] 179 of 2000 complete in 250.1 sec
[---               9%                  ] 180 of 2000 complete in 251.6 sec
[---               9%                  ] 181 of 2000 complete in 253.0 sec
[---               9%                  ] 182 of 2000 complete in 254.5 sec
[---               9%                  ] 183 of 2000 complete in 255.9 sec
[---               9%                  ] 184 of 2000 complete in 257.3 sec
[---               9%                  ] 185 of 2000 complete in 258.7 sec
[---               9%                  ] 186 of 2000 complete in 260.1 sec
[---               9%                  ] 187 of 2000 complete in 261.6 sec
[---               9%                  ] 188 of 2000 complete in 263.0 sec
[---               9%                  ] 189 of 2000 complete in 264.3 sec
[---               9%                  ] 190 of 2000 complete in 265.7 sec
[---               9%                  ] 191 of 2000 complete in 267.1 sec
[---               9%                  ] 192 of 2000 complete in 268.5 sec
[---               9%                  ] 193 of 2000 complete in 269.9 sec
[---               9%                  ] 194 of 2000 complete in 271.3 sec
[---               9%                  ] 195 of 2000 complete in 272.7 sec
[---               9%                  ] 196 of 2000 complete in 274.1 sec
[---               9%                  ] 197 of 2000 complete in 275.5 sec
[---               9%                  ] 198 of 2000 complete in 277.0 sec
[---               9%                  ] 199 of 2000 complete in 278.4 sec
[---              10%                  ] 200 of 2000 complete in 279.8 sec
[---              10%                  ] 201 of 2000 complete in 281.3 sec
[---              10%                  ] 202 of 2000 complete in 282.8 sec
[---              10%                  ] 203 of 2000 complete in 284.2 sec
[---              10%                  ] 204 of 2000 complete in 285.7 sec
[---              10%                  ] 205 of 2000 complete in 287.1 sec
[---              10%                  ] 206 of 2000 complete in 288.5 sec
[---              10%                  ] 207 of 2000 complete in 289.9 sec
[---              10%                  ] 208 of 2000 complete in 291.3 sec
[---              10%                  ] 209 of 2000 complete in 292.8 sec
[---              10%                  ] 210 of 2000 complete in 294.2 sec
[----             10%                  ] 211 of 2000 complete in 295.6 sec
[----             10%                  ] 212 of 2000 complete in 297.0 sec
[----             10%                  ] 213 of 2000 complete in 298.5 sec
[----             10%                  ] 214 of 2000 complete in 299.9 sec
[----             10%                  ] 215 of 2000 complete in 301.3 sec
[----             10%                  ] 216 of 2000 complete in 302.7 sec
[----             10%                  ] 217 of 2000 complete in 304.1 sec
[----             10%                  ] 218 of 2000 complete in 305.6 sec
[----             10%                  ] 219 of 2000 complete in 307.0 sec
[----             11%                  ] 220 of 2000 complete in 308.3 sec
[----             11%                  ] 221 of 2000 complete in 309.6 sec

[----             11%                  ] 222 of 2000 complete in 273.5 sec
[----             11%                  ] 223 of 2000 complete in 274.8 sec
[----             11%                  ] 224 of 2000 complete in 276.2 sec
[----             11%                  ] 225 of 2000 complete in 277.7 sec
[----             11%                  ] 226 of 2000 complete in 279.1 sec
[----             11%                  ] 227 of 2000 complete in 280.4 sec
[----             11%                  ] 228 of 2000 complete in 281.7 sec
[----             11%                  ] 229 of 2000 complete in 283.1 sec
[----             11%                  ] 230 of 2000 complete in 284.4 sec
[----             11%                  ] 231 of 2000 complete in 285.9 sec
[----             11%                  ] 232 of 2000 complete in 287.3 sec
[----             11%                  ] 233 of 2000 complete in 288.7 sec
[----             11%                  ] 234 of 2000 complete in 290.1 sec
[----             11%                  ] 235 of 2000 complete in 291.5 sec
[----             11%                  ] 236 of 2000 complete in 292.9 sec
[----             11%                  ] 237 of 2000 complete in 294.3 sec
[----             11%                  ] 238 of 2000 complete in 295.6 sec
[----             11%                  ] 239 of 2000 complete in 297.0 sec
[----             12%                  ] 240 of 2000 complete in 298.5 sec
[----             12%                  ] 241 of 2000 complete in 299.9 sec
[----             12%                  ] 242 of 2000 complete in 301.3 sec
[----             12%                  ] 243 of 2000 complete in 302.7 sec
[----             12%                  ] 244 of 2000 complete in 304.1 sec
[----             12%                  ] 245 of 2000 complete in 305.5 sec
[----             12%                  ] 246 of 2000 complete in 306.9 sec
[----             12%                  ] 247 of 2000 complete in 308.2 sec
[----             12%                  ] 248 of 2000 complete in 309.6 sec
[----             12%                  ] 249 of 2000 complete in 310.9 sec
[----             12%                  ] 250 of 2000 complete in 312.3 sec
[----             12%                  ] 251 of 2000 complete in 313.7 sec
[----             12%                  ] 252 of 2000 complete in 315.2 sec
[----             12%                  ] 253 of 2000 complete in 316.6 sec
[----             12%                  ] 254 of 2000 complete in 318.0 sec
[----             12%                  ] 255 of 2000 complete in 319.4 sec
[----             12%                  ] 256 of 2000 complete in 320.8 sec
[----             12%                  ] 257 of 2000 complete in 322.3 sec
[----             12%                  ] 258 of 2000 complete in 323.8 sec
[----             12%                  ] 259 of 2000 complete in 325.2 sec
[----             13%                  ] 260 of 2000 complete in 326.6 sec
[----             13%                  ] 261 of 2000 complete in 328.0 sec
[----             13%                  ] 262 of 2000 complete in 329.4 sec
[----             13%                  ] 263 of 2000 complete in 330.8 sec
[-----            13%                  ] 264 of 2000 complete in 332.2 sec
[-----            13%                  ] 265 of 2000 complete in 333.6 sec
[-----            13%                  ] 266 of 2000 complete in 334.9 sec
[-----            13%                  ] 267 of 2000 complete in 336.3 sec
[-----            13%                  ] 268 of 2000 complete in 337.7 sec
[-----            13%                  ] 269 of 2000 complete in 339.0 sec
[-----            13%                  ] 270 of 2000 complete in 340.4 sec
[-----            13%                  ] 271 of 2000 complete in 341.7 sec
[-----            13%                  ] 272 of 2000 complete in 343.1 sec
[-----            13%                  ] 273 of 2000 complete in 344.5 sec
[-----            13%                  ] 274 of 2000 complete in 345.9 sec
[-----            13%                  ] 275 of 2000 complete in 347.3 sec
[-----            13%                  ] 276 of 2000 complete in 348.7 sec
[-----            13%                  ] 277 of 2000 complete in 350.0 sec
[-----            13%                  ] 278 of 2000 complete in 351.3 sec
[-----            13%                  ] 279 of 2000 complete in 352.7 sec
[-----            14%                  ] 280 of 2000 complete in 354.1 sec
[-----            14%                  ] 281 of 2000 complete in 355.4 sec
[-----            14%                  ] 282 of 2000 complete in 356.7 sec
[-----            14%                  ] 283 of 2000 complete in 358.1 sec
[-----            14%                  ] 284 of 2000 complete in 359.4 sec
[-----            14%                  ] 285 of 2000 complete in 360.7 sec
[-----            14%                  ] 286 of 2000 complete in 362.0 sec
[-----            14%                  ] 287 of 2000 complete in 363.4 sec
[-----            14%                  ] 288 of 2000 complete in 364.8 sec
[-----            14%                  ] 289 of 2000 complete in 366.1 sec
[-----            14%                  ] 290 of 2000 complete in 367.4 sec
[-----            14%                  ] 291 of 2000 complete in 368.8 sec
[-----            14%                  ] 292 of 2000 complete in 370.2 sec
[-----            14%                  ] 293 of 2000 complete in 371.5 sec
[-----            14%                  ] 294 of 2000 complete in 372.9 sec
[-----            14%                  ] 295 of 2000 complete in 374.2 sec
[-----            14%                  ] 296 of 2000 complete in 375.6 sec
[-----            14%                  ] 297 of 2000 complete in 376.9 sec
[-----            14%                  ] 298 of 2000 complete in 378.2 sec
[-----            14%                  ] 299 of 2000 complete in 379.6 sec
[-----            15%                  ] 300 of 2000 complete in 380.9 sec
[-----            15%                  ] 301 of 2000 complete in 382.3 sec
[-----            15%                  ] 302 of 2000 complete in 383.6 sec
[-----            15%                  ] 303 of 2000 complete in 384.9 sec
[-----            15%                  ] 304 of 2000 complete in 386.3 sec
[-----            15%                  ] 305 of 2000 complete in 387.7 sec
[-----            15%                  ] 306 of 2000 complete in 389.1 sec
[-----            15%                  ] 307 of 2000 complete in 390.4 sec
[-----            15%                  ] 308 of 2000 complete in 391.7 sec
[-----            15%                  ] 309 of 2000 complete in 393.1 sec
[-----            15%                  ] 310 of 2000 complete in 394.4 sec
[-----            15%                  ] 311 of 2000 complete in 395.8 sec
[-----            15%                  ] 312 of 2000 complete in 397.2 sec
[-----            15%                  ] 313 of 2000 complete in 398.5 sec
[-----            15%                  ] 314 of 2000 complete in 399.9 sec
[-----            15%                  ] 315 of 2000 complete in 401.3 sec
[------           15%                  ] 316 of 2000 complete in 402.6 sec
[------           15%                  ] 317 of 2000 complete in 404.0 sec
[------           15%                  ] 318 of 2000 complete in 405.3 sec
[------           15%                  ] 319 of 2000 complete in 406.7 sec
[------           16%                  ] 320 of 2000 complete in 408.0 sec
[------           16%                  ] 321 of 2000 complete in 409.3 sec
[------           16%                  ] 322 of 2000 complete in 410.7 sec
[------           16%                  ] 323 of 2000 complete in 412.0 sec
[------           16%                  ] 324 of 2000 complete in 413.2 sec
[------           16%                  ] 325 of 2000 complete in 414.4 sec
[------           16%                  ] 326 of 2000 complete in 415.7 sec
[------           16%                  ] 327 of 2000 complete in 416.9 sec
[------           16%                  ] 328 of 2000 complete in 418.2 sec
[------           16%                  ] 329 of 2000 complete in 419.5 sec
[------           16%                  ] 330 of 2000 complete in 420.8 sec
[----             11%                  ] 222 of 2000 complete in 292.5 sec
[----             11%                  ] 223 of 2000 complete in 293.8 sec
[----             11%                  ] 224 of 2000 complete in 295.2 sec
[----             11%                  ] 225 of 2000 complete in 296.6 sec
[----             11%                  ] 226 of 2000 complete in 297.9 sec
[----             11%                  ] 227 of 2000 complete in 299.2 sec
[----             11%                  ] 228 of 2000 complete in 300.5 sec
[----             11%                  ] 229 of 2000 complete in 301.9 sec
[----             11%                  ] 230 of 2000 complete in 303.2 sec
[----             11%                  ] 231 of 2000 complete in 304.6 sec
[----             11%                  ] 232 of 2000 complete in 305.9 sec
[----             11%                  ] 233 of 2000 complete in 307.3 sec
[----             11%                  ] 234 of 2000 complete in 308.6 sec
[----             11%                  ] 235 of 2000 complete in 310.0 sec
[----             11%                  ] 236 of 2000 complete in 311.3 sec
[----             11%                  ] 237 of 2000 complete in 312.7 sec
[----             11%                  ] 238 of 2000 complete in 314.0 sec
[----             11%                  ] 239 of 2000 complete in 315.4 sec
[----             12%                  ] 240 of 2000 complete in 316.8 sec
[----             12%                  ] 241 of 2000 complete in 318.2 sec
[----             12%                  ] 242 of 2000 complete in 319.5 sec
[----             12%                  ] 243 of 2000 complete in 320.9 sec
[----             12%                  ] 244 of 2000 complete in 322.3 sec
[----             12%                  ] 245 of 2000 complete in 323.7 sec
[----             12%                  ] 246 of 2000 complete in 325.0 sec
[----             12%                  ] 247 of 2000 complete in 326.4 sec
[----             12%                  ] 248 of 2000 complete in 327.8 sec
[----             12%                  ] 249 of 2000 complete in 329.2 sec
[----             12%                  ] 250 of 2000 complete in 330.6 sec
[----             12%                  ] 251 of 2000 complete in 331.9 sec
[----             12%                  ] 252 of 2000 complete in 333.2 sec
[----             12%                  ] 253 of 2000 complete in 334.5 sec
[----             12%                  ] 254 of 2000 complete in 335.8 sec
[----             12%                  ] 255 of 2000 complete in 337.2 sec
[----             12%                  ] 256 of 2000 complete in 338.5 sec
[----             12%                  ] 257 of 2000 complete in 339.8 sec
[----             12%                  ] 258 of 2000 complete in 341.0 sec
[----             12%                  ] 259 of 2000 complete in 342.3 sec
[----             13%                  ] 260 of 2000 complete in 343.6 sec
[----             13%                  ] 261 of 2000 complete in 344.9 sec
[----             13%                  ] 262 of 2000 complete in 346.2 sec
[----             13%                  ] 263 of 2000 complete in 347.5 sec
[-----            13%                  ] 264 of 2000 complete in 348.7 sec
[-----            13%                  ] 265 of 2000 complete in 350.0 sec
[-----            13%                  ] 266 of 2000 complete in 351.3 sec
[-----            13%                  ] 267 of 2000 complete in 352.5 sec
[-----            13%                  ] 268 of 2000 complete in 353.8 sec
[-----            13%                  ] 269 of 2000 complete in 355.0 sec
[-----            13%                  ] 270 of 2000 complete in 356.3 sec
[-----            13%                  ] 271 of 2000 complete in 357.5 sec
[-----            13%                  ] 272 of 2000 complete in 358.8 sec
[-----            13%                  ] 273 of 2000 complete in 360.1 sec
[-----            13%                  ] 274 of 2000 complete in 361.4 sec
[-----            13%                  ] 275 of 2000 complete in 362.6 sec
[-----            13%                  ] 276 of 2000 complete in 363.9 sec
[-----            13%                  ] 277 of 2000 complete in 365.1 sec
[-----            13%                  ] 278 of 2000 complete in 366.3 sec
[-----            13%                  ] 279 of 2000 complete in 367.6 sec
[-----            14%                  ] 280 of 2000 complete in 368.8 sec
[-----            14%                  ] 281 of 2000 complete in 370.1 sec
[-----            14%                  ] 282 of 2000 complete in 371.4 sec
[-----            14%                  ] 283 of 2000 complete in 372.6 sec
[-----            14%                  ] 284 of 2000 complete in 373.8 sec
[-----            14%                  ] 285 of 2000 complete in 375.0 sec
[-----            14%                  ] 286 of 2000 complete in 376.3 sec
[-----            14%                  ] 287 of 2000 complete in 377.5 sec
[-----            14%                  ] 288 of 2000 complete in 378.7 sec
[-----            14%                  ] 289 of 2000 complete in 379.9 sec
[-----            14%                  ] 290 of 2000 complete in 381.1 sec
[-----            14%                  ] 291 of 2000 complete in 382.3 sec
[-----            14%                  ] 292 of 2000 complete in 383.6 sec
[-----            14%                  ] 293 of 2000 complete in 384.8 sec
[-----            14%                  ] 294 of 2000 complete in 386.0 sec
[-----            14%                  ] 295 of 2000 complete in 387.3 sec
[-----            14%                  ] 296 of 2000 complete in 388.6 sec
[-----            14%                  ] 297 of 2000 complete in 389.9 sec
[-----            14%                  ] 298 of 2000 complete in 391.2 sec
[-----            14%                  ] 299 of 2000 complete in 392.5 sec
[-----            15%                  ] 300 of 2000 complete in 393.8 sec
[-----            15%                  ] 301 of 2000 complete in 395.1 sec
[-----            15%                  ] 302 of 2000 complete in 396.5 sec
[-----            15%                  ] 303 of 2000 complete in 397.9 sec
[-----            15%                  ] 304 of 2000 complete in 399.2 sec
[-----            15%                  ] 305 of 2000 complete in 400.6 sec
[-----            15%                  ] 306 of 2000 complete in 401.9 sec
[-----            15%                  ] 307 of 2000 complete in 403.2 sec
[-----            15%                  ] 308 of 2000 complete in 404.5 sec
[-----            15%                  ] 309 of 2000 complete in 405.7 sec
[-----            15%                  ] 310 of 2000 complete in 406.9 sec
[-----            15%                  ] 311 of 2000 complete in 408.3 sec
[-----            15%                  ] 312 of 2000 complete in 409.5 sec
[-----            15%                  ] 313 of 2000 complete in 410.9 sec
[-----            15%                  ] 314 of 2000 complete in 412.1 sec
[-----            15%                  ] 315 of 2000 complete in 413.4 sec
[------           15%                  ] 316 of 2000 complete in 414.7 sec
[------           15%                  ] 317 of 2000 complete in 416.0 sec
[------           15%                  ] 318 of 2000 complete in 417.3 sec
[------           15%                  ] 319 of 2000 complete in 418.6 sec
[------           16%                  ] 320 of 2000 complete in 419.9 sec
[------           16%                  ] 321 of 2000 complete in 421.2 sec
[------           16%                  ] 322 of 2000 complete in 422.6 sec
[------           16%                  ] 323 of 2000 complete in 424.0 sec
[------           16%                  ] 324 of 2000 complete in 425.4 sec
[------           16%                  ] 325 of 2000 complete in 426.8 sec
[------           16%                  ] 326 of 2000 complete in 428.1 sec
[------           16%                  ] 327 of 2000 complete in 429.6 sec
[------           16%                  ] 328 of 2000 complete in 430.9 sec
[------           16%                  ] 329 of 2000 complete in 432.2 sec
[------           16%                  ] 330 of 2000 complete in 433.6 sec

[----             11%                  ] 222 of 2000 complete in 292.1 sec
[----             11%                  ] 223 of 2000 complete in 293.4 sec
[----             11%                  ] 224 of 2000 complete in 294.8 sec
[----             11%                  ] 225 of 2000 complete in 296.1 sec
[----             11%                  ] 226 of 2000 complete in 297.5 sec
[----             11%                  ] 227 of 2000 complete in 298.8 sec
[----             11%                  ] 228 of 2000 complete in 300.1 sec
[----             11%                  ] 229 of 2000 complete in 301.4 sec
[----             11%                  ] 230 of 2000 complete in 302.8 sec
[----             11%                  ] 231 of 2000 complete in 304.1 sec
[----             11%                  ] 232 of 2000 complete in 305.5 sec
[----             11%                  ] 233 of 2000 complete in 306.8 sec
[----             11%                  ] 234 of 2000 complete in 308.2 sec
[----             11%                  ] 235 of 2000 complete in 309.5 sec
[----             11%                  ] 236 of 2000 complete in 310.8 sec
[----             11%                  ] 237 of 2000 complete in 312.1 sec
[----             11%                  ] 238 of 2000 complete in 313.4 sec
[----             11%                  ] 239 of 2000 complete in 314.8 sec
[----             12%                  ] 240 of 2000 complete in 316.1 sec
[----             12%                  ] 241 of 2000 complete in 317.4 sec
[----             12%                  ] 242 of 2000 complete in 318.7 sec
[----             12%                  ] 243 of 2000 complete in 320.1 sec
[----             12%                  ] 244 of 2000 complete in 321.5 sec
[----             12%                  ] 245 of 2000 complete in 322.9 sec
[----             12%                  ] 246 of 2000 complete in 324.3 sec
[----             12%                  ] 247 of 2000 complete in 325.7 sec
[----             12%                  ] 248 of 2000 complete in 327.0 sec
[----             12%                  ] 249 of 2000 complete in 328.4 sec
[----             12%                  ] 250 of 2000 complete in 329.8 sec
[----             12%                  ] 251 of 2000 complete in 331.1 sec
[----             12%                  ] 252 of 2000 complete in 332.5 sec
[----             12%                  ] 253 of 2000 complete in 333.8 sec
[----             12%                  ] 254 of 2000 complete in 335.1 sec
[----             12%                  ] 255 of 2000 complete in 336.6 sec
[----             12%                  ] 256 of 2000 complete in 338.0 sec
[----             12%                  ] 257 of 2000 complete in 339.4 sec
[----             12%                  ] 258 of 2000 complete in 340.8 sec
[----             12%                  ] 259 of 2000 complete in 342.2 sec
[----             13%                  ] 260 of 2000 complete in 343.6 sec
[----             13%                  ] 261 of 2000 complete in 345.0 sec
[----             13%                  ] 262 of 2000 complete in 346.4 sec
[----             13%                  ] 263 of 2000 complete in 347.8 sec
[-----            13%                  ] 264 of 2000 complete in 349.2 sec
[-----            13%                  ] 265 of 2000 complete in 350.5 sec
[-----            13%                  ] 266 of 2000 complete in 351.9 sec
[-----            13%                  ] 267 of 2000 complete in 353.3 sec
[-----            13%                  ] 268 of 2000 complete in 354.7 sec
[-----            13%                  ] 269 of 2000 complete in 356.0 sec
[-----            13%                  ] 270 of 2000 complete in 357.4 sec
[-----            13%                  ] 271 of 2000 complete in 358.8 sec
[-----            13%                  ] 272 of 2000 complete in 360.1 sec
[-----            13%                  ] 273 of 2000 complete in 361.4 sec
[-----            13%                  ] 274 of 2000 complete in 362.8 sec
[-----            13%                  ] 275 of 2000 complete in 364.1 sec
[-----            13%                  ] 276 of 2000 complete in 365.5 sec
[-----            13%                  ] 277 of 2000 complete in 366.9 sec
[-----            13%                  ] 278 of 2000 complete in 368.2 sec
[-----            13%                  ] 279 of 2000 complete in 369.6 sec
[-----            14%                  ] 280 of 2000 complete in 371.0 sec
[-----            14%                  ] 281 of 2000 complete in 372.3 sec
[-----            14%                  ] 282 of 2000 complete in 373.7 sec
[-----            14%                  ] 283 of 2000 complete in 375.1 sec
[-----            14%                  ] 284 of 2000 complete in 376.6 sec
[-----            14%                  ] 285 of 2000 complete in 378.0 sec
[-----            14%                  ] 286 of 2000 complete in 379.3 sec
[-----            14%                  ] 287 of 2000 complete in 380.7 sec
[-----            14%                  ] 288 of 2000 complete in 382.1 sec
[-----            14%                  ] 289 of 2000 complete in 383.4 sec
[-----            14%                  ] 290 of 2000 complete in 384.8 sec
[-----            14%                  ] 291 of 2000 complete in 386.2 sec
[-----            14%                  ] 292 of 2000 complete in 387.6 sec
[-----            14%                  ] 293 of 2000 complete in 388.9 sec
[-----            14%                  ] 294 of 2000 complete in 390.3 sec
[-----            14%                  ] 295 of 2000 complete in 391.7 sec
[-----            14%                  ] 296 of 2000 complete in 393.0 sec
[-----            14%                  ] 297 of 2000 complete in 394.4 sec
[-----            14%                  ] 298 of 2000 complete in 395.8 sec
[-----            14%                  ] 299 of 2000 complete in 397.2 sec
[-----            15%                  ] 300 of 2000 complete in 398.5 sec
[-----            15%                  ] 301 of 2000 complete in 399.9 sec
[-----            15%                  ] 302 of 2000 complete in 401.3 sec
[-----            15%                  ] 303 of 2000 complete in 402.6 sec
[-----            15%                  ] 304 of 2000 complete in 404.0 sec
[-----            15%                  ] 305 of 2000 complete in 405.3 sec
[-----            15%                  ] 306 of 2000 complete in 406.6 sec
[-----            15%                  ] 307 of 2000 complete in 408.0 sec
[-----            15%                  ] 308 of 2000 complete in 409.3 sec
[-----            15%                  ] 309 of 2000 complete in 410.8 sec
[-----            15%                  ] 310 of 2000 complete in 412.1 sec
[-----            15%                  ] 311 of 2000 complete in 413.4 sec
[-----            15%                  ] 312 of 2000 complete in 414.7 sec
[-----            15%                  ] 313 of 2000 complete in 416.0 sec
[-----            15%                  ] 314 of 2000 complete in 417.4 sec
[-----            15%                  ] 315 of 2000 complete in 418.8 sec
[------           15%                  ] 316 of 2000 complete in 420.2 sec
[------           15%                  ] 317 of 2000 complete in 421.7 sec
[------           15%                  ] 318 of 2000 complete in 423.0 sec
[------           15%                  ] 319 of 2000 complete in 424.4 sec
[------           16%                  ] 320 of 2000 complete in 425.9 sec
[------           16%                  ] 321 of 2000 complete in 427.2 sec
[------           16%                  ] 322 of 2000 complete in 428.6 sec
[------           16%                  ] 323 of 2000 complete in 430.0 sec
[------           16%                  ] 324 of 2000 complete in 431.3 sec
[------           16%                  ] 325 of 2000 complete in 432.7 sec
[------           16%                  ] 326 of 2000 complete in 434.1 sec
[------           16%                  ] 327 of 2000 complete in 435.5 sec
[------           16%                  ] 328 of 2000 complete in 436.8 sec
[------           16%                  ] 329 of 2000 complete in 438.2 sec
[------           16%                  ] 330 of 2000 complete in 439.5 sec
[----             11%                  ] 222 of 2000 complete in 311.0 sec
[----             11%                  ] 223 of 2000 complete in 312.3 sec
[----             11%                  ] 224 of 2000 complete in 313.8 sec
[----             11%                  ] 225 of 2000 complete in 315.1 sec
[----             11%                  ] 226 of 2000 complete in 316.5 sec
[----             11%                  ] 227 of 2000 complete in 317.8 sec
[----             11%                  ] 228 of 2000 complete in 319.3 sec
[----             11%                  ] 229 of 2000 complete in 320.7 sec
[----             11%                  ] 230 of 2000 complete in 322.2 sec
[----             11%                  ] 231 of 2000 complete in 323.6 sec
[----             11%                  ] 232 of 2000 complete in 325.1 sec
[----             11%                  ] 233 of 2000 complete in 326.5 sec
[----             11%                  ] 234 of 2000 complete in 327.8 sec
[----             11%                  ] 235 of 2000 complete in 329.2 sec
[----             11%                  ] 236 of 2000 complete in 330.5 sec
[----             11%                  ] 237 of 2000 complete in 331.8 sec
[----             11%                  ] 238 of 2000 complete in 333.0 sec
[----             11%                  ] 239 of 2000 complete in 334.3 sec
[----             12%                  ] 240 of 2000 complete in 335.7 sec
[----             12%                  ] 241 of 2000 complete in 337.0 sec
[----             12%                  ] 242 of 2000 complete in 338.2 sec
[----             12%                  ] 243 of 2000 complete in 339.6 sec
[----             12%                  ] 244 of 2000 complete in 341.0 sec
[----             12%                  ] 245 of 2000 complete in 342.3 sec
[----             12%                  ] 246 of 2000 complete in 343.6 sec
[----             12%                  ] 247 of 2000 complete in 345.0 sec
[----             12%                  ] 248 of 2000 complete in 346.3 sec
[----             12%                  ] 249 of 2000 complete in 347.6 sec
[----             12%                  ] 250 of 2000 complete in 348.9 sec
[----             12%                  ] 251 of 2000 complete in 350.2 sec
[----             12%                  ] 252 of 2000 complete in 351.6 sec
[----             12%                  ] 253 of 2000 complete in 352.8 sec
[----             12%                  ] 254 of 2000 complete in 354.1 sec
[----             12%                  ] 255 of 2000 complete in 355.3 sec
[----             12%                  ] 256 of 2000 complete in 356.6 sec
[----             12%                  ] 257 of 2000 complete in 357.9 sec
[----             12%                  ] 258 of 2000 complete in 359.1 sec
[----             12%                  ] 259 of 2000 complete in 360.4 sec
[----             13%                  ] 260 of 2000 complete in 361.6 sec
[----             13%                  ] 261 of 2000 complete in 362.9 sec
[----             13%                  ] 262 of 2000 complete in 364.1 sec
[----             13%                  ] 263 of 2000 complete in 365.4 sec
[-----            13%                  ] 264 of 2000 complete in 366.6 sec
[-----            13%                  ] 265 of 2000 complete in 367.8 sec
[-----            13%                  ] 266 of 2000 complete in 369.0 sec
[-----            13%                  ] 267 of 2000 complete in 370.3 sec
[-----            13%                  ] 268 of 2000 complete in 371.6 sec
[-----            13%                  ] 269 of 2000 complete in 372.9 sec
[-----            13%                  ] 270 of 2000 complete in 374.2 sec
[-----            13%                  ] 271 of 2000 complete in 375.4 sec
[-----            13%                  ] 272 of 2000 complete in 376.7 sec
[-----            13%                  ] 273 of 2000 complete in 378.0 sec
[-----            13%                  ] 274 of 2000 complete in 379.3 sec
[-----            13%                  ] 275 of 2000 complete in 380.6 sec
[-----            13%                  ] 276 of 2000 complete in 381.8 sec
[-----            13%                  ] 277 of 2000 complete in 383.1 sec
[-----            13%                  ] 278 of 2000 complete in 384.4 sec
[-----            13%                  ] 279 of 2000 complete in 385.7 sec
[-----            14%                  ] 280 of 2000 complete in 387.1 sec
[-----            14%                  ] 281 of 2000 complete in 388.5 sec
[-----            14%                  ] 282 of 2000 complete in 389.8 sec
[-----            14%                  ] 283 of 2000 complete in 391.1 sec
[-----            14%                  ] 284 of 2000 complete in 392.4 sec
[-----            14%                  ] 285 of 2000 complete in 393.9 sec
[-----            14%                  ] 286 of 2000 complete in 395.3 sec
[-----            14%                  ] 287 of 2000 complete in 396.7 sec
[-----            14%                  ] 288 of 2000 complete in 398.1 sec
[-----            14%                  ] 289 of 2000 complete in 399.5 sec
[-----            14%                  ] 290 of 2000 complete in 400.8 sec
[-----            14%                  ] 291 of 2000 complete in 402.3 sec
[-----            14%                  ] 292 of 2000 complete in 403.6 sec
[-----            14%                  ] 293 of 2000 complete in 405.0 sec
[-----            14%                  ] 294 of 2000 complete in 406.4 sec
[-----            14%                  ] 295 of 2000 complete in 407.8 sec
[-----            14%                  ] 296 of 2000 complete in 409.2 sec
[-----            14%                  ] 297 of 2000 complete in 410.6 sec
[-----            14%                  ] 298 of 2000 complete in 412.0 sec
[-----            14%                  ] 299 of 2000 complete in 413.5 sec
[-----            15%                  ] 300 of 2000 complete in 414.9 sec
[-----            15%                  ] 301 of 2000 complete in 416.3 sec
[-----            15%                  ] 302 of 2000 complete in 417.7 sec
[-----            15%                  ] 303 of 2000 complete in 419.2 sec
[-----            15%                  ] 304 of 2000 complete in 420.6 sec
[-----            15%                  ] 305 of 2000 complete in 421.9 sec
[-----            15%                  ] 306 of 2000 complete in 423.3 sec
[-----            15%                  ] 307 of 2000 complete in 424.7 sec
[-----            15%                  ] 308 of 2000 complete in 426.0 sec
[-----            15%                  ] 309 of 2000 complete in 427.3 sec
[-----            15%                  ] 310 of 2000 complete in 428.7 sec
[-----            15%                  ] 311 of 2000 complete in 430.1 sec
[-----            15%                  ] 312 of 2000 complete in 431.4 sec
[-----            15%                  ] 313 of 2000 complete in 432.7 sec
[-----            15%                  ] 314 of 2000 complete in 434.1 sec
[-----            15%                  ] 315 of 2000 complete in 435.4 sec
[------           15%                  ] 316 of 2000 complete in 436.8 sec
[------           15%                  ] 317 of 2000 complete in 438.1 sec
[------           15%                  ] 318 of 2000 complete in 439.5 sec
[------           15%                  ] 319 of 2000 complete in 440.9 sec
[------           16%                  ] 320 of 2000 complete in 442.2 sec
[------           16%                  ] 321 of 2000 complete in 443.6 sec
[------           16%                  ] 322 of 2000 complete in 445.0 sec
[------           16%                  ] 323 of 2000 complete in 446.4 sec
[------           16%                  ] 324 of 2000 complete in 447.8 sec
[------           16%                  ] 325 of 2000 complete in 449.1 sec
[------           16%                  ] 326 of 2000 complete in 450.4 sec
[------           16%                  ] 327 of 2000 complete in 451.7 sec
[------           16%                  ] 328 of 2000 complete in 453.1 sec
[------           16%                  ] 329 of 2000 complete in 454.4 sec
[------           16%                  ] 330 of 2000 complete in 455.7 sec

[------           16%                  ] 331 of 2000 complete in 422.0 sec
[------           16%                  ] 332 of 2000 complete in 423.2 sec
[------           16%                  ] 333 of 2000 complete in 424.5 sec
[------           16%                  ] 334 of 2000 complete in 425.8 sec
[------           16%                  ] 335 of 2000 complete in 427.1 sec
[------           16%                  ] 336 of 2000 complete in 428.4 sec
[------           16%                  ] 337 of 2000 complete in 429.6 sec
[------           16%                  ] 338 of 2000 complete in 431.0 sec
[------           16%                  ] 339 of 2000 complete in 432.2 sec
[------           17%                  ] 340 of 2000 complete in 433.6 sec
[------           17%                  ] 341 of 2000 complete in 434.9 sec
[------           17%                  ] 342 of 2000 complete in 436.2 sec
[------           17%                  ] 343 of 2000 complete in 437.6 sec
[------           17%                  ] 344 of 2000 complete in 438.9 sec
[------           17%                  ] 345 of 2000 complete in 440.2 sec
[------           17%                  ] 346 of 2000 complete in 441.6 sec
[------           17%                  ] 347 of 2000 complete in 442.9 sec
[------           17%                  ] 348 of 2000 complete in 444.2 sec
[------           17%                  ] 349 of 2000 complete in 445.6 sec
[------           17%                  ] 350 of 2000 complete in 447.0 sec
[------           17%                  ] 351 of 2000 complete in 448.4 sec
[------           17%                  ] 352 of 2000 complete in 449.7 sec
[------           17%                  ] 353 of 2000 complete in 451.0 sec
[------           17%                  ] 354 of 2000 complete in 452.2 sec
[------           17%                  ] 355 of 2000 complete in 453.5 sec
[------           17%                  ] 356 of 2000 complete in 454.7 sec
[------           17%                  ] 357 of 2000 complete in 456.1 sec
[------           17%                  ] 358 of 2000 complete in 457.4 sec
[------           17%                  ] 359 of 2000 complete in 458.8 sec
[------           18%                  ] 360 of 2000 complete in 460.1 sec
[------           18%                  ] 361 of 2000 complete in 461.5 sec
[------           18%                  ] 362 of 2000 complete in 462.8 sec
[------           18%                  ] 363 of 2000 complete in 464.1 sec
[------           18%                  ] 364 of 2000 complete in 465.4 sec
[------           18%                  ] 365 of 2000 complete in 466.7 sec
[------           18%                  ] 366 of 2000 complete in 468.0 sec
[------           18%                  ] 367 of 2000 complete in 469.3 sec
[------           18%                  ] 368 of 2000 complete in 470.7 sec
[-------          18%                  ] 369 of 2000 complete in 472.0 sec
[-------          18%                  ] 370 of 2000 complete in 473.3 sec
[-------          18%                  ] 371 of 2000 complete in 474.6 sec
[-------          18%                  ] 372 of 2000 complete in 476.0 sec
[-------          18%                  ] 373 of 2000 complete in 477.3 sec
[-------          18%                  ] 374 of 2000 complete in 478.6 sec
[-------          18%                  ] 375 of 2000 complete in 479.9 sec
[-------          18%                  ] 376 of 2000 complete in 481.2 sec
[-------          18%                  ] 377 of 2000 complete in 482.6 sec
[-------          18%                  ] 378 of 2000 complete in 483.9 sec
[-------          18%                  ] 379 of 2000 complete in 485.3 sec
[-------          19%                  ] 380 of 2000 complete in 486.6 sec
[-------          19%                  ] 381 of 2000 complete in 488.0 sec
[-------          19%                  ] 382 of 2000 complete in 489.3 sec
[-------          19%                  ] 383 of 2000 complete in 490.7 sec
[-------          19%                  ] 384 of 2000 complete in 492.1 sec
[-------          19%                  ] 385 of 2000 complete in 493.4 sec
[-------          19%                  ] 386 of 2000 complete in 494.8 sec
[-------          19%                  ] 387 of 2000 complete in 496.2 sec
[-------          19%                  ] 388 of 2000 complete in 497.5 sec
[-------          19%                  ] 389 of 2000 complete in 498.8 sec
[-------          19%                  ] 390 of 2000 complete in 500.3 sec
[-------          19%                  ] 391 of 2000 complete in 501.6 sec
[-------          19%                  ] 392 of 2000 complete in 502.9 sec
[-------          19%                  ] 393 of 2000 complete in 504.2 sec
[-------          19%                  ] 394 of 2000 complete in 505.6 sec
[-------          19%                  ] 395 of 2000 complete in 506.9 sec
[-------          19%                  ] 396 of 2000 complete in 508.3 sec
[-------          19%                  ] 397 of 2000 complete in 509.6 sec
[-------          19%                  ] 398 of 2000 complete in 510.9 sec
[-------          19%                  ] 399 of 2000 complete in 512.2 sec
[-------          20%                  ] 400 of 2000 complete in 513.5 sec
[-------          20%                  ] 401 of 2000 complete in 514.8 sec
[-------          20%                  ] 402 of 2000 complete in 516.1 sec
[-------          20%                  ] 403 of 2000 complete in 517.4 sec
[-------          20%                  ] 404 of 2000 complete in 518.7 sec
[-------          20%                  ] 405 of 2000 complete in 520.0 sec
[-------          20%                  ] 406 of 2000 complete in 521.2 sec
[-------          20%                  ] 407 of 2000 complete in 522.4 sec
[-------          20%                  ] 408 of 2000 complete in 523.7 sec
[-------          20%                  ] 409 of 2000 complete in 524.9 sec
[-------          20%                  ] 410 of 2000 complete in 526.2 sec
[-------          20%                  ] 411 of 2000 complete in 527.4 sec
[-------          20%                  ] 412 of 2000 complete in 528.7 sec
[-------          20%                  ] 413 of 2000 complete in 530.0 sec
[-------          20%                  ] 414 of 2000 complete in 531.3 sec
[-------          20%                  ] 415 of 2000 complete in 532.6 sec
[-------          20%                  ] 416 of 2000 complete in 533.8 sec
[-------          20%                  ] 417 of 2000 complete in 535.1 sec
[-------          20%                  ] 418 of 2000 complete in 536.4 sec
[-------          20%                  ] 419 of 2000 complete in 537.8 sec
[-------          21%                  ] 420 of 2000 complete in 539.1 sec
[-------          21%                  ] 421 of 2000 complete in 540.4 sec
[--------         21%                  ] 422 of 2000 complete in 541.7 sec
[--------         21%                  ] 423 of 2000 complete in 543.1 sec
[--------         21%                  ] 424 of 2000 complete in 544.4 sec
[--------         21%                  ] 425 of 2000 complete in 545.7 sec
[--------         21%                  ] 426 of 2000 complete in 547.1 sec
[--------         21%                  ] 427 of 2000 complete in 548.4 sec
[--------         21%                  ] 428 of 2000 complete in 549.7 sec
[--------         21%                  ] 429 of 2000 complete in 551.0 sec
[--------         21%                  ] 430 of 2000 complete in 552.3 sec
[--------         21%                  ] 431 of 2000 complete in 553.6 sec
[--------         21%                  ] 432 of 2000 complete in 555.0 sec
[--------         21%                  ] 433 of 2000 complete in 556.2 sec
[--------         21%                  ] 434 of 2000 complete in 557.6 sec
[--------         21%                  ] 435 of 2000 complete in 558.9 sec
[--------         21%                  ] 436 of 2000 complete in 560.2 sec
[--------         21%                  ] 437 of 2000 complete in 561.5 sec
[--------         21%                  ] 438 of 2000 complete in 562.8 sec
[--------         21%                  ] 439 of 2000 complete in 564.1 sec
[------           16%                  ] 331 of 2000 complete in 435.0 sec
[------           16%                  ] 332 of 2000 complete in 436.3 sec
[------           16%                  ] 333 of 2000 complete in 437.7 sec
[------           16%                  ] 334 of 2000 complete in 439.0 sec
[------           16%                  ] 335 of 2000 complete in 440.3 sec
[------           16%                  ] 336 of 2000 complete in 441.7 sec
[------           16%                  ] 337 of 2000 complete in 443.1 sec
[------           16%                  ] 338 of 2000 complete in 444.4 sec
[------           16%                  ] 339 of 2000 complete in 445.8 sec
[------           17%                  ] 340 of 2000 complete in 447.2 sec
[------           17%                  ] 341 of 2000 complete in 448.6 sec
[------           17%                  ] 342 of 2000 complete in 450.0 sec
[------           17%                  ] 343 of 2000 complete in 451.3 sec
[------           17%                  ] 344 of 2000 complete in 452.6 sec
[------           17%                  ] 345 of 2000 complete in 453.9 sec
[------           17%                  ] 346 of 2000 complete in 455.2 sec
[------           17%                  ] 347 of 2000 complete in 456.6 sec
[------           17%                  ] 348 of 2000 complete in 457.8 sec
[------           17%                  ] 349 of 2000 complete in 459.1 sec
[------           17%                  ] 350 of 2000 complete in 460.4 sec
[------           17%                  ] 351 of 2000 complete in 461.7 sec
[------           17%                  ] 352 of 2000 complete in 463.0 sec
[------           17%                  ] 353 of 2000 complete in 464.4 sec
[------           17%                  ] 354 of 2000 complete in 465.6 sec
[------           17%                  ] 355 of 2000 complete in 467.0 sec
[------           17%                  ] 356 of 2000 complete in 468.3 sec
[------           17%                  ] 357 of 2000 complete in 469.7 sec
[------           17%                  ] 358 of 2000 complete in 471.0 sec
[------           17%                  ] 359 of 2000 complete in 472.3 sec
[------           18%                  ] 360 of 2000 complete in 473.6 sec
[------           18%                  ] 361 of 2000 complete in 474.9 sec
[------           18%                  ] 362 of 2000 complete in 476.2 sec
[------           18%                  ] 363 of 2000 complete in 477.5 sec
[------           18%                  ] 364 of 2000 complete in 478.9 sec
[------           18%                  ] 365 of 2000 complete in 480.2 sec
[------           18%                  ] 366 of 2000 complete in 481.5 sec
[------           18%                  ] 367 of 2000 complete in 482.7 sec
[------           18%                  ] 368 of 2000 complete in 484.0 sec
[-------          18%                  ] 369 of 2000 complete in 485.3 sec
[-------          18%                  ] 370 of 2000 complete in 486.5 sec
[-------          18%                  ] 371 of 2000 complete in 487.8 sec
[-------          18%                  ] 372 of 2000 complete in 489.1 sec
[-------          18%                  ] 373 of 2000 complete in 490.3 sec
[-------          18%                  ] 374 of 2000 complete in 491.5 sec
[-------          18%                  ] 375 of 2000 complete in 492.8 sec
[-------          18%                  ] 376 of 2000 complete in 494.1 sec
[-------          18%                  ] 377 of 2000 complete in 495.4 sec
[-------          18%                  ] 378 of 2000 complete in 496.7 sec
[-------          18%                  ] 379 of 2000 complete in 498.1 sec
[-------          19%                  ] 380 of 2000 complete in 499.4 sec
[-------          19%                  ] 381 of 2000 complete in 500.7 sec
[-------          19%                  ] 382 of 2000 complete in 502.0 sec
[-------          19%                  ] 383 of 2000 complete in 503.4 sec
[-------          19%                  ] 384 of 2000 complete in 504.7 sec
[-------          19%                  ] 385 of 2000 complete in 506.0 sec
[-------          19%                  ] 386 of 2000 complete in 507.4 sec
[-------          19%                  ] 387 of 2000 complete in 508.7 sec
[-------          19%                  ] 388 of 2000 complete in 509.9 sec
[-------          19%                  ] 389 of 2000 complete in 511.2 sec
[-------          19%                  ] 390 of 2000 complete in 512.5 sec
[-------          19%                  ] 391 of 2000 complete in 513.7 sec
[-------          19%                  ] 392 of 2000 complete in 515.0 sec
[-------          19%                  ] 393 of 2000 complete in 516.2 sec
[-------          19%                  ] 394 of 2000 complete in 517.5 sec
[-------          19%                  ] 395 of 2000 complete in 518.8 sec
[-------          19%                  ] 396 of 2000 complete in 520.0 sec
[-------          19%                  ] 397 of 2000 complete in 521.2 sec
[-------          19%                  ] 398 of 2000 complete in 522.5 sec
[-------          19%                  ] 399 of 2000 complete in 523.7 sec
[-------          20%                  ] 400 of 2000 complete in 525.0 sec
[-------          20%                  ] 401 of 2000 complete in 526.2 sec
[-------          20%                  ] 402 of 2000 complete in 527.5 sec
[-------          20%                  ] 403 of 2000 complete in 528.8 sec
[-------          20%                  ] 404 of 2000 complete in 530.0 sec
[-------          20%                  ] 405 of 2000 complete in 531.3 sec
[-------          20%                  ] 406 of 2000 complete in 532.7 sec
[-------          20%                  ] 407 of 2000 complete in 534.0 sec
[-------          20%                  ] 408 of 2000 complete in 535.3 sec
[-------          20%                  ] 409 of 2000 complete in 536.7 sec
[-------          20%                  ] 410 of 2000 complete in 538.0 sec
[-------          20%                  ] 411 of 2000 complete in 539.2 sec
[-------          20%                  ] 412 of 2000 complete in 540.5 sec
[-------          20%                  ] 413 of 2000 complete in 541.8 sec
[-------          20%                  ] 414 of 2000 complete in 543.2 sec
[-------          20%                  ] 415 of 2000 complete in 544.5 sec
[-------          20%                  ] 416 of 2000 complete in 545.9 sec
[-------          20%                  ] 417 of 2000 complete in 547.3 sec
[-------          20%                  ] 418 of 2000 complete in 548.7 sec
[-------          20%                  ] 419 of 2000 complete in 550.0 sec
[-------          21%                  ] 420 of 2000 complete in 551.4 sec
[-------          21%                  ] 421 of 2000 complete in 552.7 sec
[--------         21%                  ] 422 of 2000 complete in 554.1 sec
[--------         21%                  ] 423 of 2000 complete in 555.5 sec
[--------         21%                  ] 424 of 2000 complete in 556.8 sec
[--------         21%                  ] 425 of 2000 complete in 558.1 sec
[--------         21%                  ] 426 of 2000 complete in 559.4 sec
[--------         21%                  ] 427 of 2000 complete in 560.8 sec
[--------         21%                  ] 428 of 2000 complete in 562.2 sec
[--------         21%                  ] 429 of 2000 complete in 563.6 sec
[--------         21%                  ] 430 of 2000 complete in 564.9 sec
[--------         21%                  ] 431 of 2000 complete in 566.3 sec
[--------         21%                  ] 432 of 2000 complete in 567.6 sec
[--------         21%                  ] 433 of 2000 complete in 568.9 sec
[--------         21%                  ] 434 of 2000 complete in 570.3 sec
[--------         21%                  ] 435 of 2000 complete in 571.6 sec
[--------         21%                  ] 436 of 2000 complete in 573.0 sec
[--------         21%                  ] 437 of 2000 complete in 574.2 sec
[--------         21%                  ] 438 of 2000 complete in 575.5 sec
[--------         21%                  ] 439 of 2000 complete in 576.8 sec

[------           16%                  ] 331 of 2000 complete in 440.8 sec
[------           16%                  ] 332 of 2000 complete in 442.1 sec
[------           16%                  ] 333 of 2000 complete in 443.5 sec
[------           16%                  ] 334 of 2000 complete in 444.9 sec
[------           16%                  ] 335 of 2000 complete in 446.3 sec
[------           16%                  ] 336 of 2000 complete in 447.7 sec
[------           16%                  ] 337 of 2000 complete in 449.0 sec
[------           16%                  ] 338 of 2000 complete in 450.4 sec
[------           16%                  ] 339 of 2000 complete in 451.8 sec
[------           17%                  ] 340 of 2000 complete in 453.1 sec
[------           17%                  ] 341 of 2000 complete in 454.5 sec
[------           17%                  ] 342 of 2000 complete in 455.9 sec
[------           17%                  ] 343 of 2000 complete in 457.3 sec
[------           17%                  ] 344 of 2000 complete in 458.6 sec
[------           17%                  ] 345 of 2000 complete in 460.0 sec
[------           17%                  ] 346 of 2000 complete in 461.4 sec
[------           17%                  ] 347 of 2000 complete in 462.8 sec
[------           17%                  ] 348 of 2000 complete in 464.2 sec
[------           17%                  ] 349 of 2000 complete in 465.6 sec
[------           17%                  ] 350 of 2000 complete in 467.0 sec
[------           17%                  ] 351 of 2000 complete in 468.4 sec
[------           17%                  ] 352 of 2000 complete in 469.8 sec
[------           17%                  ] 353 of 2000 complete in 471.3 sec
[------           17%                  ] 354 of 2000 complete in 472.7 sec
[------           17%                  ] 355 of 2000 complete in 474.1 sec
[------           17%                  ] 356 of 2000 complete in 475.4 sec
[------           17%                  ] 357 of 2000 complete in 476.8 sec
[------           17%                  ] 358 of 2000 complete in 478.2 sec
[------           17%                  ] 359 of 2000 complete in 479.6 sec
[------           18%                  ] 360 of 2000 complete in 481.0 sec
[------           18%                  ] 361 of 2000 complete in 482.4 sec
[------           18%                  ] 362 of 2000 complete in 483.9 sec
[------           18%                  ] 363 of 2000 complete in 485.3 sec
[------           18%                  ] 364 of 2000 complete in 486.6 sec
[------           18%                  ] 365 of 2000 complete in 488.0 sec
[------           18%                  ] 366 of 2000 complete in 489.3 sec
[------           18%                  ] 367 of 2000 complete in 490.7 sec
[------           18%                  ] 368 of 2000 complete in 492.2 sec
[-------          18%                  ] 369 of 2000 complete in 493.6 sec
[-------          18%                  ] 370 of 2000 complete in 494.9 sec
[-------          18%                  ] 371 of 2000 complete in 496.3 sec
[-------          18%                  ] 372 of 2000 complete in 497.6 sec
[-------          18%                  ] 373 of 2000 complete in 499.1 sec
[-------          18%                  ] 374 of 2000 complete in 500.5 sec
[-------          18%                  ] 375 of 2000 complete in 501.9 sec
[-------          18%                  ] 376 of 2000 complete in 503.3 sec
[-------          18%                  ] 377 of 2000 complete in 504.6 sec
[-------          18%                  ] 378 of 2000 complete in 506.1 sec
[-------          18%                  ] 379 of 2000 complete in 507.5 sec
[-------          19%                  ] 380 of 2000 complete in 508.9 sec
[-------          19%                  ] 381 of 2000 complete in 510.3 sec
[-------          19%                  ] 382 of 2000 complete in 511.6 sec
[-------          19%                  ] 383 of 2000 complete in 513.0 sec
[-------          19%                  ] 384 of 2000 complete in 514.3 sec
[-------          19%                  ] 385 of 2000 complete in 515.7 sec
[-------          19%                  ] 386 of 2000 complete in 517.1 sec
[-------          19%                  ] 387 of 2000 complete in 518.6 sec
[-------          19%                  ] 388 of 2000 complete in 519.9 sec
[-------          19%                  ] 389 of 2000 complete in 521.3 sec
[-------          19%                  ] 390 of 2000 complete in 522.7 sec
[-------          19%                  ] 391 of 2000 complete in 524.1 sec
[-------          19%                  ] 392 of 2000 complete in 525.4 sec
[-------          19%                  ] 393 of 2000 complete in 526.8 sec
[-------          19%                  ] 394 of 2000 complete in 528.2 sec
[-------          19%                  ] 395 of 2000 complete in 529.6 sec
[-------          19%                  ] 396 of 2000 complete in 531.2 sec
[-------          19%                  ] 397 of 2000 complete in 532.5 sec
[-------          19%                  ] 398 of 2000 complete in 533.9 sec
[-------          19%                  ] 399 of 2000 complete in 535.3 sec
[-------          20%                  ] 400 of 2000 complete in 536.7 sec
[-------          20%                  ] 401 of 2000 complete in 538.0 sec
[-------          20%                  ] 402 of 2000 complete in 539.4 sec
[-------          20%                  ] 403 of 2000 complete in 540.8 sec
[-------          20%                  ] 404 of 2000 complete in 542.3 sec
[-------          20%                  ] 405 of 2000 complete in 543.6 sec
[-------          20%                  ] 406 of 2000 complete in 545.0 sec
[-------          20%                  ] 407 of 2000 complete in 546.4 sec
[-------          20%                  ] 408 of 2000 complete in 547.8 sec
[-------          20%                  ] 409 of 2000 complete in 549.1 sec
[-------          20%                  ] 410 of 2000 complete in 550.5 sec
[-------          20%                  ] 411 of 2000 complete in 552.0 sec
[-------          20%                  ] 412 of 2000 complete in 553.4 sec
[-------          20%                  ] 413 of 2000 complete in 554.8 sec
[-------          20%                  ] 414 of 2000 complete in 556.2 sec
[-------          20%                  ] 415 of 2000 complete in 557.6 sec
[-------          20%                  ] 416 of 2000 complete in 559.0 sec
[-------          20%                  ] 417 of 2000 complete in 560.5 sec
[-------          20%                  ] 418 of 2000 complete in 561.9 sec
[-------          20%                  ] 419 of 2000 complete in 563.4 sec
[-------          21%                  ] 420 of 2000 complete in 564.8 sec
[-------          21%                  ] 421 of 2000 complete in 566.2 sec
[--------         21%                  ] 422 of 2000 complete in 567.5 sec
[--------         21%                  ] 423 of 2000 complete in 568.9 sec
[--------         21%                  ] 424 of 2000 complete in 570.2 sec
[--------         21%                  ] 425 of 2000 complete in 571.6 sec
[--------         21%                  ] 426 of 2000 complete in 573.0 sec
[--------         21%                  ] 427 of 2000 complete in 574.4 sec
[--------         21%                  ] 428 of 2000 complete in 575.7 sec
[--------         21%                  ] 429 of 2000 complete in 577.1 sec
[--------         21%                  ] 430 of 2000 complete in 578.5 sec
[--------         21%                  ] 431 of 2000 complete in 579.9 sec
[--------         21%                  ] 432 of 2000 complete in 581.3 sec
[--------         21%                  ] 433 of 2000 complete in 582.6 sec
[--------         21%                  ] 434 of 2000 complete in 584.0 sec
[--------         21%                  ] 435 of 2000 complete in 585.4 sec
[--------         21%                  ] 436 of 2000 complete in 586.8 sec
[--------         21%                  ] 437 of 2000 complete in 588.2 sec
[--------         21%                  ] 438 of 2000 complete in 589.6 sec
[--------         21%                  ] 439 of 2000 complete in 591.0 sec
[------           16%                  ] 331 of 2000 complete in 456.9 sec
[------           16%                  ] 332 of 2000 complete in 458.2 sec
[------           16%                  ] 333 of 2000 complete in 459.5 sec
[------           16%                  ] 334 of 2000 complete in 460.7 sec
[------           16%                  ] 335 of 2000 complete in 462.0 sec
[------           16%                  ] 336 of 2000 complete in 463.2 sec
[------           16%                  ] 337 of 2000 complete in 464.5 sec
[------           16%                  ] 338 of 2000 complete in 465.8 sec
[------           16%                  ] 339 of 2000 complete in 466.9 sec
[------           17%                  ] 340 of 2000 complete in 468.2 sec
[------           17%                  ] 341 of 2000 complete in 469.5 sec
[------           17%                  ] 342 of 2000 complete in 470.8 sec
[------           17%                  ] 343 of 2000 complete in 472.1 sec
[------           17%                  ] 344 of 2000 complete in 473.3 sec
[------           17%                  ] 345 of 2000 complete in 474.6 sec
[------           17%                  ] 346 of 2000 complete in 475.9 sec
[------           17%                  ] 347 of 2000 complete in 477.2 sec
[------           17%                  ] 348 of 2000 complete in 478.6 sec
[------           17%                  ] 349 of 2000 complete in 479.9 sec
[------           17%                  ] 350 of 2000 complete in 481.2 sec
[------           17%                  ] 351 of 2000 complete in 482.5 sec
[------           17%                  ] 352 of 2000 complete in 483.8 sec
[------           17%                  ] 353 of 2000 complete in 485.1 sec
[------           17%                  ] 354 of 2000 complete in 486.4 sec
[------           17%                  ] 355 of 2000 complete in 487.8 sec
[------           17%                  ] 356 of 2000 complete in 489.2 sec
[------           17%                  ] 357 of 2000 complete in 490.5 sec
[------           17%                  ] 358 of 2000 complete in 491.9 sec
[------           17%                  ] 359 of 2000 complete in 493.3 sec
[------           18%                  ] 360 of 2000 complete in 494.7 sec
[------           18%                  ] 361 of 2000 complete in 496.1 sec
[------           18%                  ] 362 of 2000 complete in 497.4 sec
[------           18%                  ] 363 of 2000 complete in 498.7 sec
[------           18%                  ] 364 of 2000 complete in 500.1 sec
[------           18%                  ] 365 of 2000 complete in 501.4 sec
[------           18%                  ] 366 of 2000 complete in 502.7 sec
[------           18%                  ] 367 of 2000 complete in 504.0 sec
[------           18%                  ] 368 of 2000 complete in 505.4 sec
[-------          18%                  ] 369 of 2000 complete in 506.7 sec
[-------          18%                  ] 370 of 2000 complete in 508.1 sec
[-------          18%                  ] 371 of 2000 complete in 509.5 sec
[-------          18%                  ] 372 of 2000 complete in 510.8 sec
[-------          18%                  ] 373 of 2000 complete in 512.1 sec
[-------          18%                  ] 374 of 2000 complete in 513.4 sec
[-------          18%                  ] 375 of 2000 complete in 514.8 sec
[-------          18%                  ] 376 of 2000 complete in 516.1 sec
[-------          18%                  ] 377 of 2000 complete in 517.4 sec
[-------          18%                  ] 378 of 2000 complete in 518.7 sec
[-------          18%                  ] 379 of 2000 complete in 520.0 sec
[-------          19%                  ] 380 of 2000 complete in 521.2 sec
[-------          19%                  ] 381 of 2000 complete in 522.5 sec
[-------          19%                  ] 382 of 2000 complete in 523.7 sec
[-------          19%                  ] 383 of 2000 complete in 525.0 sec
[-------          19%                  ] 384 of 2000 complete in 526.1 sec
[-------          19%                  ] 385 of 2000 complete in 527.3 sec
[-------          19%                  ] 386 of 2000 complete in 528.5 sec
[-------          19%                  ] 387 of 2000 complete in 529.6 sec
[-------          19%                  ] 388 of 2000 complete in 530.8 sec
[-------          19%                  ] 389 of 2000 complete in 532.0 sec
[-------          19%                  ] 390 of 2000 complete in 533.2 sec
[-------          19%                  ] 391 of 2000 complete in 534.4 sec
[-------          19%                  ] 392 of 2000 complete in 535.6 sec
[-------          19%                  ] 393 of 2000 complete in 536.8 sec
[-------          19%                  ] 394 of 2000 complete in 538.0 sec
[-------          19%                  ] 395 of 2000 complete in 539.2 sec
[-------          19%                  ] 396 of 2000 complete in 540.4 sec
[-------          19%                  ] 397 of 2000 complete in 541.7 sec
[-------          19%                  ] 398 of 2000 complete in 543.0 sec
[-------          19%                  ] 399 of 2000 complete in 544.2 sec
[-------          20%                  ] 400 of 2000 complete in 545.5 sec
[-------          20%                  ] 401 of 2000 complete in 546.7 sec
[-------          20%                  ] 402 of 2000 complete in 548.0 sec
[-------          20%                  ] 403 of 2000 complete in 549.3 sec
[-------          20%                  ] 404 of 2000 complete in 550.5 sec
[-------          20%                  ] 405 of 2000 complete in 551.9 sec
[-------          20%                  ] 406 of 2000 complete in 553.1 sec
[-------          20%                  ] 407 of 2000 complete in 554.5 sec
[-------          20%                  ] 408 of 2000 complete in 555.7 sec
[-------          20%                  ] 409 of 2000 complete in 557.0 sec
[-------          20%                  ] 410 of 2000 complete in 558.2 sec
[-------          20%                  ] 411 of 2000 complete in 559.4 sec
[-------          20%                  ] 412 of 2000 complete in 560.7 sec
[-------          20%                  ] 413 of 2000 complete in 562.0 sec
[-------          20%                  ] 414 of 2000 complete in 563.2 sec
[-------          20%                  ] 415 of 2000 complete in 564.5 sec
[-------          20%                  ] 416 of 2000 complete in 565.7 sec
[-------          20%                  ] 417 of 2000 complete in 567.0 sec
[-------          20%                  ] 418 of 2000 complete in 568.2 sec
[-------          20%                  ] 419 of 2000 complete in 569.5 sec
[-------          21%                  ] 420 of 2000 complete in 570.7 sec
[-------          21%                  ] 421 of 2000 complete in 571.9 sec
[--------         21%                  ] 422 of 2000 complete in 573.1 sec
[--------         21%                  ] 423 of 2000 complete in 574.4 sec
[--------         21%                  ] 424 of 2000 complete in 575.7 sec
[--------         21%                  ] 425 of 2000 complete in 577.0 sec
[--------         21%                  ] 426 of 2000 complete in 578.3 sec
[--------         21%                  ] 427 of 2000 complete in 579.5 sec
[--------         21%                  ] 428 of 2000 complete in 580.8 sec
[--------         21%                  ] 429 of 2000 complete in 582.0 sec
[--------         21%                  ] 430 of 2000 complete in 583.3 sec
[--------         21%                  ] 431 of 2000 complete in 584.5 sec
[--------         21%                  ] 432 of 2000 complete in 585.7 sec
[--------         21%                  ] 433 of 2000 complete in 587.0 sec
[--------         21%                  ] 434 of 2000 complete in 588.3 sec
[--------         21%                  ] 435 of 2000 complete in 589.5 sec
[--------         21%                  ] 436 of 2000 complete in 590.8 sec
[--------         21%                  ] 437 of 2000 complete in 592.1 sec
[--------         21%                  ] 438 of 2000 complete in 593.4 sec
[--------         21%                  ] 439 of 2000 complete in 594.7 sec

[--------         22%                  ] 440 of 2000 complete in 565.4 sec
[--------         22%                  ] 441 of 2000 complete in 566.8 sec
[--------         22%                  ] 442 of 2000 complete in 568.1 sec
[--------         22%                  ] 443 of 2000 complete in 569.4 sec
[--------         22%                  ] 444 of 2000 complete in 570.8 sec
[--------         22%                  ] 445 of 2000 complete in 572.1 sec
[--------         22%                  ] 446 of 2000 complete in 573.3 sec
[--------         22%                  ] 447 of 2000 complete in 574.6 sec
[--------         22%                  ] 448 of 2000 complete in 575.9 sec
[--------         22%                  ] 449 of 2000 complete in 577.2 sec
[--------         22%                  ] 450 of 2000 complete in 578.5 sec
[--------         22%                  ] 451 of 2000 complete in 579.8 sec
[--------         22%                  ] 452 of 2000 complete in 581.1 sec
[--------         22%                  ] 453 of 2000 complete in 582.3 sec
[--------         22%                  ] 454 of 2000 complete in 583.6 sec
[--------         22%                  ] 455 of 2000 complete in 584.8 sec
[--------         22%                  ] 456 of 2000 complete in 586.1 sec
[--------         22%                  ] 457 of 2000 complete in 587.3 sec
[--------         22%                  ] 458 of 2000 complete in 588.5 sec
[--------         22%                  ] 459 of 2000 complete in 589.8 sec
[--------         23%                  ] 460 of 2000 complete in 591.0 sec
[--------         23%                  ] 461 of 2000 complete in 592.3 sec
[--------         23%                  ] 462 of 2000 complete in 593.6 sec
[--------         23%                  ] 463 of 2000 complete in 594.9 sec
[--------         23%                  ] 464 of 2000 complete in 596.1 sec
[--------         23%                  ] 465 of 2000 complete in 597.3 sec
[--------         23%                  ] 466 of 2000 complete in 598.5 sec
[--------         23%                  ] 467 of 2000 complete in 599.7 sec
[--------         23%                  ] 468 of 2000 complete in 601.0 sec
[--------         23%                  ] 469 of 2000 complete in 602.2 sec
[--------         23%                  ] 470 of 2000 complete in 603.5 sec
[--------         23%                  ] 471 of 2000 complete in 604.6 sec
[--------         23%                  ] 472 of 2000 complete in 605.9 sec
[--------         23%                  ] 473 of 2000 complete in 607.1 sec
[---------        23%                  ] 474 of 2000 complete in 608.4 sec
[---------        23%                  ] 475 of 2000 complete in 609.7 sec
[---------        23%                  ] 476 of 2000 complete in 610.9 sec
[---------        23%                  ] 477 of 2000 complete in 612.2 sec
[---------        23%                  ] 478 of 2000 complete in 613.5 sec
[---------        23%                  ] 479 of 2000 complete in 614.7 sec
[---------        24%                  ] 480 of 2000 complete in 615.9 sec
[---------        24%                  ] 481 of 2000 complete in 617.2 sec
[---------        24%                  ] 482 of 2000 complete in 618.4 sec
[---------        24%                  ] 483 of 2000 complete in 619.7 sec
[---------        24%                  ] 484 of 2000 complete in 621.0 sec
[---------        24%                  ] 485 of 2000 complete in 622.3 sec
[---------        24%                  ] 486 of 2000 complete in 623.6 sec
[---------        24%                  ] 487 of 2000 complete in 624.9 sec
[---------        24%                  ] 488 of 2000 complete in 626.3 sec
[---------        24%                  ] 489 of 2000 complete in 627.5 sec
[---------        24%                  ] 490 of 2000 complete in 628.8 sec
[---------        24%                  ] 491 of 2000 complete in 630.0 sec
[---------        24%                  ] 492 of 2000 complete in 631.2 sec
[---------        24%                  ] 493 of 2000 complete in 632.5 sec
[---------        24%                  ] 494 of 2000 complete in 633.8 sec
[---------        24%                  ] 495 of 2000 complete in 635.0 sec
[---------        24%                  ] 496 of 2000 complete in 636.3 sec
[---------        24%                  ] 497 of 2000 complete in 637.6 sec
[---------        24%                  ] 498 of 2000 complete in 638.9 sec
[---------        24%                  ] 499 of 2000 complete in 640.2 sec
[---------        25%                  ] 500 of 2000 complete in 641.4 sec
[---------        25%                  ] 501 of 2000 complete in 642.7 sec
[---------        25%                  ] 502 of 2000 complete in 644.0 sec
[---------        25%                  ] 503 of 2000 complete in 645.2 sec
[---------        25%                  ] 504 of 2000 complete in 646.5 sec
[---------        25%                  ] 505 of 2000 complete in 647.7 sec
[---------        25%                  ] 506 of 2000 complete in 648.9 sec
[---------        25%                  ] 507 of 2000 complete in 650.1 sec
[---------        25%                  ] 508 of 2000 complete in 651.3 sec
[---------        25%                  ] 509 of 2000 complete in 652.5 sec
[---------        25%                  ] 510 of 2000 complete in 653.7 sec
[---------        25%                  ] 511 of 2000 complete in 655.0 sec
[---------        25%                  ] 512 of 2000 complete in 656.3 sec
[---------        25%                  ] 513 of 2000 complete in 657.6 sec
[---------        25%                  ] 514 of 2000 complete in 658.9 sec
[---------        25%                  ] 515 of 2000 complete in 660.1 sec
[---------        25%                  ] 516 of 2000 complete in 661.4 sec
[---------        25%                  ] 517 of 2000 complete in 662.6 sec
[---------        25%                  ] 518 of 2000 complete in 663.7 sec
[---------        25%                  ] 519 of 2000 complete in 664.9 sec
[---------        26%                  ] 520 of 2000 complete in 666.2 sec
[---------        26%                  ] 521 of 2000 complete in 667.3 sec
[---------        26%                  ] 522 of 2000 complete in 668.6 sec
[---------        26%                  ] 523 of 2000 complete in 669.8 sec
[---------        26%                  ] 524 of 2000 complete in 671.0 sec
[---------        26%                  ] 525 of 2000 complete in 672.2 sec
[---------        26%                  ] 526 of 2000 complete in 673.4 sec
[----------       26%                  ] 527 of 2000 complete in 674.6 sec
[----------       26%                  ] 528 of 2000 complete in 675.8 sec
[----------       26%                  ] 529 of 2000 complete in 677.0 sec
[----------       26%                  ] 530 of 2000 complete in 678.2 sec
[----------       26%                  ] 531 of 2000 complete in 679.5 sec
[----------       26%                  ] 532 of 2000 complete in 680.8 sec
[----------       26%                  ] 533 of 2000 complete in 682.0 sec
[----------       26%                  ] 534 of 2000 complete in 683.3 sec
[----------       26%                  ] 535 of 2000 complete in 684.6 sec
[----------       26%                  ] 536 of 2000 complete in 685.9 sec
[----------       26%                  ] 537 of 2000 complete in 687.2 sec
[----------       26%                  ] 538 of 2000 complete in 688.5 sec
[----------       26%                  ] 539 of 2000 complete in 689.9 sec
[----------       27%                  ] 540 of 2000 complete in 691.1 sec
[----------       27%                  ] 541 of 2000 complete in 692.3 sec
[----------       27%                  ] 542 of 2000 complete in 693.6 sec
[----------       27%                  ] 543 of 2000 complete in 694.8 sec
[----------       27%                  ] 544 of 2000 complete in 696.1 sec
[----------       27%                  ] 545 of 2000 complete in 697.3 sec
[----------       27%                  ] 546 of 2000 complete in 698.5 sec
[----------       27%                  ] 547 of 2000 complete in 699.8 sec
[----------       27%                  ] 548 of 2000 complete in 701.0 sec
[--------         22%                  ] 440 of 2000 complete in 578.1 sec
[--------         22%                  ] 441 of 2000 complete in 579.4 sec
[--------         22%                  ] 442 of 2000 complete in 580.7 sec
[--------         22%                  ] 443 of 2000 complete in 582.0 sec
[--------         22%                  ] 444 of 2000 complete in 583.3 sec
[--------         22%                  ] 445 of 2000 complete in 584.6 sec
[--------         22%                  ] 446 of 2000 complete in 585.9 sec
[--------         22%                  ] 447 of 2000 complete in 587.1 sec
[--------         22%                  ] 448 of 2000 complete in 588.3 sec
[--------         22%                  ] 449 of 2000 complete in 589.6 sec
[--------         22%                  ] 450 of 2000 complete in 590.9 sec
[--------         22%                  ] 451 of 2000 complete in 592.1 sec
[--------         22%                  ] 452 of 2000 complete in 593.3 sec
[--------         22%                  ] 453 of 2000 complete in 594.6 sec
[--------         22%                  ] 454 of 2000 complete in 595.9 sec
[--------         22%                  ] 455 of 2000 complete in 597.2 sec
[--------         22%                  ] 456 of 2000 complete in 598.6 sec
[--------         22%                  ] 457 of 2000 complete in 599.9 sec
[--------         22%                  ] 458 of 2000 complete in 601.2 sec
[--------         22%                  ] 459 of 2000 complete in 602.5 sec
[--------         23%                  ] 460 of 2000 complete in 603.8 sec
[--------         23%                  ] 461 of 2000 complete in 605.2 sec
[--------         23%                  ] 462 of 2000 complete in 606.5 sec
[--------         23%                  ] 463 of 2000 complete in 607.8 sec
[--------         23%                  ] 464 of 2000 complete in 609.1 sec
[--------         23%                  ] 465 of 2000 complete in 610.4 sec
[--------         23%                  ] 466 of 2000 complete in 611.8 sec
[--------         23%                  ] 467 of 2000 complete in 613.0 sec
[--------         23%                  ] 468 of 2000 complete in 614.4 sec
[--------         23%                  ] 469 of 2000 complete in 615.6 sec
[--------         23%                  ] 470 of 2000 complete in 617.0 sec
[--------         23%                  ] 471 of 2000 complete in 618.3 sec
[--------         23%                  ] 472 of 2000 complete in 619.7 sec
[--------         23%                  ] 473 of 2000 complete in 621.0 sec
[---------        23%                  ] 474 of 2000 complete in 622.3 sec
[---------        23%                  ] 475 of 2000 complete in 623.6 sec
[---------        23%                  ] 476 of 2000 complete in 625.0 sec
[---------        23%                  ] 477 of 2000 complete in 626.4 sec
[---------        23%                  ] 478 of 2000 complete in 627.7 sec
[---------        23%                  ] 479 of 2000 complete in 629.1 sec
[---------        24%                  ] 480 of 2000 complete in 630.5 sec
[---------        24%                  ] 481 of 2000 complete in 631.8 sec
[---------        24%                  ] 482 of 2000 complete in 633.2 sec
[---------        24%                  ] 483 of 2000 complete in 634.6 sec
[---------        24%                  ] 484 of 2000 complete in 635.9 sec
[---------        24%                  ] 485 of 2000 complete in 637.2 sec
[---------        24%                  ] 486 of 2000 complete in 638.6 sec
[---------        24%                  ] 487 of 2000 complete in 640.0 sec
[---------        24%                  ] 488 of 2000 complete in 641.5 sec
[---------        24%                  ] 489 of 2000 complete in 642.9 sec
[---------        24%                  ] 490 of 2000 complete in 644.2 sec
[---------        24%                  ] 491 of 2000 complete in 645.5 sec
[---------        24%                  ] 492 of 2000 complete in 646.9 sec
[---------        24%                  ] 493 of 2000 complete in 648.2 sec
[---------        24%                  ] 494 of 2000 complete in 649.5 sec
[---------        24%                  ] 495 of 2000 complete in 650.9 sec
[---------        24%                  ] 496 of 2000 complete in 652.2 sec
[---------        24%                  ] 497 of 2000 complete in 653.6 sec
[---------        24%                  ] 498 of 2000 complete in 654.9 sec
[---------        24%                  ] 499 of 2000 complete in 656.2 sec
[---------        25%                  ] 500 of 2000 complete in 657.5 sec
[---------        25%                  ] 501 of 2000 complete in 658.7 sec
[---------        25%                  ] 502 of 2000 complete in 660.0 sec
[---------        25%                  ] 503 of 2000 complete in 661.3 sec
[---------        25%                  ] 504 of 2000 complete in 662.6 sec
[---------        25%                  ] 505 of 2000 complete in 663.8 sec
[---------        25%                  ] 506 of 2000 complete in 665.1 sec
[---------        25%                  ] 507 of 2000 complete in 666.3 sec
[---------        25%                  ] 508 of 2000 complete in 667.5 sec
[---------        25%                  ] 509 of 2000 complete in 668.8 sec
[---------        25%                  ] 510 of 2000 complete in 670.0 sec
[---------        25%                  ] 511 of 2000 complete in 671.3 sec
[---------        25%                  ] 512 of 2000 complete in 672.5 sec
[---------        25%                  ] 513 of 2000 complete in 673.7 sec
[---------        25%                  ] 514 of 2000 complete in 674.9 sec
[---------        25%                  ] 515 of 2000 complete in 676.1 sec
[---------        25%                  ] 516 of 2000 complete in 677.3 sec
[---------        25%                  ] 517 of 2000 complete in 678.5 sec
[---------        25%                  ] 518 of 2000 complete in 679.7 sec
[---------        25%                  ] 519 of 2000 complete in 680.9 sec
[---------        26%                  ] 520 of 2000 complete in 682.0 sec
[---------        26%                  ] 521 of 2000 complete in 683.2 sec
[---------        26%                  ] 522 of 2000 complete in 684.4 sec
[---------        26%                  ] 523 of 2000 complete in 685.6 sec
[---------        26%                  ] 524 of 2000 complete in 686.8 sec
[---------        26%                  ] 525 of 2000 complete in 688.0 sec
[---------        26%                  ] 526 of 2000 complete in 689.2 sec
[----------       26%                  ] 527 of 2000 complete in 690.4 sec
[----------       26%                  ] 528 of 2000 complete in 691.6 sec
[----------       26%                  ] 529 of 2000 complete in 692.7 sec
[----------       26%                  ] 530 of 2000 complete in 693.9 sec
[----------       26%                  ] 531 of 2000 complete in 695.1 sec
[----------       26%                  ] 532 of 2000 complete in 696.3 sec
[----------       26%                  ] 533 of 2000 complete in 697.4 sec
[----------       26%                  ] 534 of 2000 complete in 698.6 sec
[----------       26%                  ] 535 of 2000 complete in 699.8 sec
[----------       26%                  ] 536 of 2000 complete in 701.0 sec
[----------       26%                  ] 537 of 2000 complete in 702.2 sec
[----------       26%                  ] 538 of 2000 complete in 703.4 sec
[----------       26%                  ] 539 of 2000 complete in 704.6 sec
[----------       27%                  ] 540 of 2000 complete in 705.8 sec
[----------       27%                  ] 541 of 2000 complete in 707.0 sec
[----------       27%                  ] 542 of 2000 complete in 708.2 sec
[----------       27%                  ] 543 of 2000 complete in 709.3 sec
[----------       27%                  ] 544 of 2000 complete in 710.6 sec
[----------       27%                  ] 545 of 2000 complete in 711.8 sec
[----------       27%                  ] 546 of 2000 complete in 713.0 sec
[----------       27%                  ] 547 of 2000 complete in 714.2 sec
[----------       27%                  ] 548 of 2000 complete in 715.4 sec

[--------         22%                  ] 440 of 2000 complete in 592.4 sec
[--------         22%                  ] 441 of 2000 complete in 593.8 sec
[--------         22%                  ] 442 of 2000 complete in 595.3 sec
[--------         22%                  ] 443 of 2000 complete in 596.7 sec
[--------         22%                  ] 444 of 2000 complete in 598.0 sec
[--------         22%                  ] 445 of 2000 complete in 599.4 sec
[--------         22%                  ] 446 of 2000 complete in 600.9 sec
[--------         22%                  ] 447 of 2000 complete in 602.3 sec
[--------         22%                  ] 448 of 2000 complete in 603.7 sec
[--------         22%                  ] 449 of 2000 complete in 605.1 sec
[--------         22%                  ] 450 of 2000 complete in 606.5 sec
[--------         22%                  ] 451 of 2000 complete in 607.8 sec
[--------         22%                  ] 452 of 2000 complete in 609.2 sec
[--------         22%                  ] 453 of 2000 complete in 610.5 sec
[--------         22%                  ] 454 of 2000 complete in 611.9 sec
[--------         22%                  ] 455 of 2000 complete in 613.3 sec
[--------         22%                  ] 456 of 2000 complete in 614.7 sec
[--------         22%                  ] 457 of 2000 complete in 616.1 sec
[--------         22%                  ] 458 of 2000 complete in 617.5 sec
[--------         22%                  ] 459 of 2000 complete in 618.8 sec
[--------         23%                  ] 460 of 2000 complete in 620.2 sec
[--------         23%                  ] 461 of 2000 complete in 621.6 sec
[--------         23%                  ] 462 of 2000 complete in 623.0 sec
[--------         23%                  ] 463 of 2000 complete in 624.3 sec
[--------         23%                  ] 464 of 2000 complete in 625.8 sec
[--------         23%                  ] 465 of 2000 complete in 627.2 sec
[--------         23%                  ] 466 of 2000 complete in 628.7 sec
[--------         23%                  ] 467 of 2000 complete in 630.1 sec
[--------         23%                  ] 468 of 2000 complete in 631.5 sec
[--------         23%                  ] 469 of 2000 complete in 632.8 sec
[--------         23%                  ] 470 of 2000 complete in 634.3 sec
[--------         23%                  ] 471 of 2000 complete in 635.7 sec
[--------         23%                  ] 472 of 2000 complete in 637.2 sec
[--------         23%                  ] 473 of 2000 complete in 638.6 sec
[---------        23%                  ] 474 of 2000 complete in 640.0 sec
[---------        23%                  ] 475 of 2000 complete in 641.4 sec
[---------        23%                  ] 476 of 2000 complete in 642.8 sec
[---------        23%                  ] 477 of 2000 complete in 644.2 sec
[---------        23%                  ] 478 of 2000 complete in 645.6 sec
[---------        23%                  ] 479 of 2000 complete in 647.0 sec
[---------        24%                  ] 480 of 2000 complete in 648.3 sec
[---------        24%                  ] 481 of 2000 complete in 649.7 sec
[---------        24%                  ] 482 of 2000 complete in 651.0 sec
[---------        24%                  ] 483 of 2000 complete in 652.4 sec
[---------        24%                  ] 484 of 2000 complete in 653.8 sec
[---------        24%                  ] 485 of 2000 complete in 655.2 sec
[---------        24%                  ] 486 of 2000 complete in 656.6 sec
[---------        24%                  ] 487 of 2000 complete in 657.8 sec
[---------        24%                  ] 488 of 2000 complete in 659.2 sec
[---------        24%                  ] 489 of 2000 complete in 660.5 sec
[---------        24%                  ] 490 of 2000 complete in 661.9 sec
[---------        24%                  ] 491 of 2000 complete in 663.3 sec
[---------        24%                  ] 492 of 2000 complete in 664.7 sec
[---------        24%                  ] 493 of 2000 complete in 666.1 sec
[---------        24%                  ] 494 of 2000 complete in 667.4 sec
[---------        24%                  ] 495 of 2000 complete in 668.9 sec
[---------        24%                  ] 496 of 2000 complete in 670.2 sec
[---------        24%                  ] 497 of 2000 complete in 671.5 sec
[---------        24%                  ] 498 of 2000 complete in 672.9 sec
[---------        24%                  ] 499 of 2000 complete in 674.2 sec
[---------        25%                  ] 500 of 2000 complete in 675.6 sec
[---------        25%                  ] 501 of 2000 complete in 676.9 sec
[---------        25%                  ] 502 of 2000 complete in 678.3 sec
[---------        25%                  ] 503 of 2000 complete in 679.6 sec
[---------        25%                  ] 504 of 2000 complete in 681.0 sec
[---------        25%                  ] 505 of 2000 complete in 682.3 sec
[---------        25%                  ] 506 of 2000 complete in 683.6 sec
[---------        25%                  ] 507 of 2000 complete in 685.0 sec
[---------        25%                  ] 508 of 2000 complete in 686.4 sec
[---------        25%                  ] 509 of 2000 complete in 687.7 sec
[---------        25%                  ] 510 of 2000 complete in 689.0 sec
[---------        25%                  ] 511 of 2000 complete in 690.3 sec
[---------        25%                  ] 512 of 2000 complete in 691.5 sec
[---------        25%                  ] 513 of 2000 complete in 692.8 sec
[---------        25%                  ] 514 of 2000 complete in 694.1 sec
[---------        25%                  ] 515 of 2000 complete in 695.4 sec
[---------        25%                  ] 516 of 2000 complete in 696.7 sec
[---------        25%                  ] 517 of 2000 complete in 698.0 sec
[---------        25%                  ] 518 of 2000 complete in 699.3 sec
[---------        25%                  ] 519 of 2000 complete in 700.6 sec
[---------        26%                  ] 520 of 2000 complete in 701.9 sec
[---------        26%                  ] 521 of 2000 complete in 703.2 sec
[---------        26%                  ] 522 of 2000 complete in 704.5 sec
[---------        26%                  ] 523 of 2000 complete in 705.8 sec
[---------        26%                  ] 524 of 2000 complete in 707.1 sec
[---------        26%                  ] 525 of 2000 complete in 708.4 sec
[---------        26%                  ] 526 of 2000 complete in 709.7 sec
[----------       26%                  ] 527 of 2000 complete in 710.9 sec
[----------       26%                  ] 528 of 2000 complete in 712.2 sec
[----------       26%                  ] 529 of 2000 complete in 713.5 sec
[----------       26%                  ] 530 of 2000 complete in 714.8 sec
[----------       26%                  ] 531 of 2000 complete in 716.2 sec
[----------       26%                  ] 532 of 2000 complete in 717.4 sec
[----------       26%                  ] 533 of 2000 complete in 718.8 sec
[----------       26%                  ] 534 of 2000 complete in 720.2 sec
[----------       26%                  ] 535 of 2000 complete in 721.5 sec
[----------       26%                  ] 536 of 2000 complete in 722.8 sec
[----------       26%                  ] 537 of 2000 complete in 724.1 sec
[----------       26%                  ] 538 of 2000 complete in 725.3 sec
[----------       26%                  ] 539 of 2000 complete in 726.6 sec
[----------       27%                  ] 540 of 2000 complete in 727.9 sec
[----------       27%                  ] 541 of 2000 complete in 729.1 sec
[----------       27%                  ] 542 of 2000 complete in 730.4 sec
[----------       27%                  ] 543 of 2000 complete in 731.7 sec
[----------       27%                  ] 544 of 2000 complete in 733.0 sec
[----------       27%                  ] 545 of 2000 complete in 734.3 sec
[----------       27%                  ] 546 of 2000 complete in 735.6 sec
[----------       27%                  ] 547 of 2000 complete in 736.9 sec
[----------       27%                  ] 548 of 2000 complete in 738.3 sec
[--------         22%                  ] 440 of 2000 complete in 595.9 sec
[--------         22%                  ] 441 of 2000 complete in 597.2 sec
[--------         22%                  ] 442 of 2000 complete in 598.4 sec
[--------         22%                  ] 443 of 2000 complete in 599.6 sec
[--------         22%                  ] 444 of 2000 complete in 600.8 sec
[--------         22%                  ] 445 of 2000 complete in 602.1 sec
[--------         22%                  ] 446 of 2000 complete in 603.3 sec
[--------         22%                  ] 447 of 2000 complete in 604.5 sec
[--------         22%                  ] 448 of 2000 complete in 605.7 sec
[--------         22%                  ] 449 of 2000 complete in 606.9 sec
[--------         22%                  ] 450 of 2000 complete in 608.1 sec
[--------         22%                  ] 451 of 2000 complete in 609.3 sec
[--------         22%                  ] 452 of 2000 complete in 610.5 sec
[--------         22%                  ] 453 of 2000 complete in 611.8 sec
[--------         22%                  ] 454 of 2000 complete in 613.1 sec
[--------         22%                  ] 455 of 2000 complete in 614.4 sec
[--------         22%                  ] 456 of 2000 complete in 615.7 sec
[--------         22%                  ] 457 of 2000 complete in 616.9 sec
[--------         22%                  ] 458 of 2000 complete in 618.1 sec
[--------         22%                  ] 459 of 2000 complete in 619.4 sec
[--------         23%                  ] 460 of 2000 complete in 620.6 sec
[--------         23%                  ] 461 of 2000 complete in 621.9 sec
[--------         23%                  ] 462 of 2000 complete in 623.1 sec
[--------         23%                  ] 463 of 2000 complete in 624.4 sec
[--------         23%                  ] 464 of 2000 complete in 625.7 sec
[--------         23%                  ] 465 of 2000 complete in 627.0 sec
[--------         23%                  ] 466 of 2000 complete in 628.3 sec
[--------         23%                  ] 467 of 2000 complete in 629.5 sec
[--------         23%                  ] 468 of 2000 complete in 630.8 sec
[--------         23%                  ] 469 of 2000 complete in 632.0 sec
[--------         23%                  ] 470 of 2000 complete in 633.3 sec
[--------         23%                  ] 471 of 2000 complete in 634.5 sec
[--------         23%                  ] 472 of 2000 complete in 635.8 sec
[--------         23%                  ] 473 of 2000 complete in 637.1 sec
[---------        23%                  ] 474 of 2000 complete in 638.4 sec
[---------        23%                  ] 475 of 2000 complete in 639.7 sec
[---------        23%                  ] 476 of 2000 complete in 641.1 sec
[---------        23%                  ] 477 of 2000 complete in 642.4 sec
[---------        23%                  ] 478 of 2000 complete in 643.7 sec
[---------        23%                  ] 479 of 2000 complete in 645.0 sec
[---------        24%                  ] 480 of 2000 complete in 646.4 sec
[---------        24%                  ] 481 of 2000 complete in 647.7 sec
[---------        24%                  ] 482 of 2000 complete in 649.0 sec
[---------        24%                  ] 483 of 2000 complete in 650.3 sec
[---------        24%                  ] 484 of 2000 complete in 651.6 sec
[---------        24%                  ] 485 of 2000 complete in 652.9 sec
[---------        24%                  ] 486 of 2000 complete in 654.3 sec
[---------        24%                  ] 487 of 2000 complete in 655.7 sec
[---------        24%                  ] 488 of 2000 complete in 657.1 sec
[---------        24%                  ] 489 of 2000 complete in 658.4 sec
[---------        24%                  ] 490 of 2000 complete in 659.8 sec
[---------        24%                  ] 491 of 2000 complete in 661.1 sec
[---------        24%                  ] 492 of 2000 complete in 662.5 sec
[---------        24%                  ] 493 of 2000 complete in 664.0 sec
[---------        24%                  ] 494 of 2000 complete in 665.3 sec
[---------        24%                  ] 495 of 2000 complete in 666.7 sec
[---------        24%                  ] 496 of 2000 complete in 668.1 sec
[---------        24%                  ] 497 of 2000 complete in 669.4 sec
[---------        24%                  ] 498 of 2000 complete in 670.7 sec
[---------        24%                  ] 499 of 2000 complete in 672.1 sec
[---------        25%                  ] 500 of 2000 complete in 673.6 sec
[---------        25%                  ] 501 of 2000 complete in 675.0 sec
[---------        25%                  ] 502 of 2000 complete in 676.4 sec
[---------        25%                  ] 503 of 2000 complete in 677.8 sec
[---------        25%                  ] 504 of 2000 complete in 679.3 sec
[---------        25%                  ] 505 of 2000 complete in 680.7 sec
[---------        25%                  ] 506 of 2000 complete in 682.1 sec
[---------        25%                  ] 507 of 2000 complete in 683.6 sec
[---------        25%                  ] 508 of 2000 complete in 685.0 sec
[---------        25%                  ] 509 of 2000 complete in 686.4 sec
[---------        25%                  ] 510 of 2000 complete in 687.9 sec
[---------        25%                  ] 511 of 2000 complete in 689.3 sec
[---------        25%                  ] 512 of 2000 complete in 690.7 sec
[---------        25%                  ] 513 of 2000 complete in 692.1 sec
[---------        25%                  ] 514 of 2000 complete in 693.5 sec
[---------        25%                  ] 515 of 2000 complete in 694.9 sec
[---------        25%                  ] 516 of 2000 complete in 696.3 sec
[---------        25%                  ] 517 of 2000 complete in 697.8 sec
[---------        25%                  ] 518 of 2000 complete in 699.2 sec
[---------        25%                  ] 519 of 2000 complete in 700.6 sec
[---------        26%                  ] 520 of 2000 complete in 702.0 sec
[---------        26%                  ] 521 of 2000 complete in 703.4 sec
[---------        26%                  ] 522 of 2000 complete in 704.8 sec
[---------        26%                  ] 523 of 2000 complete in 706.2 sec
[---------        26%                  ] 524 of 2000 complete in 707.6 sec
[---------        26%                  ] 525 of 2000 complete in 709.1 sec
[---------        26%                  ] 526 of 2000 complete in 710.5 sec
[----------       26%                  ] 527 of 2000 complete in 711.9 sec
[----------       26%                  ] 528 of 2000 complete in 713.3 sec
[----------       26%                  ] 529 of 2000 complete in 714.7 sec
[----------       26%                  ] 530 of 2000 complete in 716.0 sec
[----------       26%                  ] 531 of 2000 complete in 717.5 sec
[----------       26%                  ] 532 of 2000 complete in 718.9 sec
[----------       26%                  ] 533 of 2000 complete in 720.3 sec
[----------       26%                  ] 534 of 2000 complete in 721.7 sec
[----------       26%                  ] 535 of 2000 complete in 723.1 sec
[----------       26%                  ] 536 of 2000 complete in 724.4 sec
[----------       26%                  ] 537 of 2000 complete in 725.8 sec
[----------       26%                  ] 538 of 2000 complete in 727.3 sec
[----------       26%                  ] 539 of 2000 complete in 728.7 sec
[----------       27%                  ] 540 of 2000 complete in 730.2 sec
[----------       27%                  ] 541 of 2000 complete in 731.5 sec
[----------       27%                  ] 542 of 2000 complete in 733.0 sec
[----------       27%                  ] 543 of 2000 complete in 734.4 sec
[----------       27%                  ] 544 of 2000 complete in 735.8 sec
[----------       27%                  ] 545 of 2000 complete in 737.2 sec
[----------       27%                  ] 546 of 2000 complete in 738.6 sec
[----------       27%                  ] 547 of 2000 complete in 740.0 sec
[----------       27%                  ] 548 of 2000 complete in 741.4 sec

[----------       27%                  ] 549 of 2000 complete in 702.2 sec
[----------       27%                  ] 550 of 2000 complete in 703.5 sec
[----------       27%                  ] 551 of 2000 complete in 704.7 sec
[----------       27%                  ] 552 of 2000 complete in 705.9 sec
[----------       27%                  ] 553 of 2000 complete in 707.2 sec
[----------       27%                  ] 554 of 2000 complete in 708.4 sec
[----------       27%                  ] 555 of 2000 complete in 709.6 sec
[----------       27%                  ] 556 of 2000 complete in 710.9 sec
[----------       27%                  ] 557 of 2000 complete in 712.1 sec
[----------       27%                  ] 558 of 2000 complete in 713.3 sec
[----------       27%                  ] 559 of 2000 complete in 714.5 sec
[----------       28%                  ] 560 of 2000 complete in 715.7 sec
[----------       28%                  ] 561 of 2000 complete in 716.9 sec
[----------       28%                  ] 562 of 2000 complete in 718.1 sec
[----------       28%                  ] 563 of 2000 complete in 719.3 sec
[----------       28%                  ] 564 of 2000 complete in 720.5 sec
[----------       28%                  ] 565 of 2000 complete in 721.7 sec
[----------       28%                  ] 566 of 2000 complete in 722.9 sec
[----------       28%                  ] 567 of 2000 complete in 724.1 sec
[----------       28%                  ] 568 of 2000 complete in 725.3 sec
[----------       28%                  ] 569 of 2000 complete in 726.5 sec
[----------       28%                  ] 570 of 2000 complete in 727.8 sec
[----------       28%                  ] 571 of 2000 complete in 729.0 sec
[----------       28%                  ] 572 of 2000 complete in 730.2 sec
[----------       28%                  ] 573 of 2000 complete in 731.4 sec
[----------       28%                  ] 574 of 2000 complete in 732.5 sec
[----------       28%                  ] 575 of 2000 complete in 733.8 sec
[----------       28%                  ] 576 of 2000 complete in 735.0 sec
[----------       28%                  ] 577 of 2000 complete in 736.2 sec
[----------       28%                  ] 578 of 2000 complete in 737.5 sec
[-----------      28%                  ] 579 of 2000 complete in 738.8 sec
[-----------      29%                  ] 580 of 2000 complete in 740.0 sec
[-----------      29%                  ] 581 of 2000 complete in 741.3 sec
[-----------      29%                  ] 582 of 2000 complete in 742.5 sec
[-----------      29%                  ] 583 of 2000 complete in 743.8 sec
[-----------      29%                  ] 584 of 2000 complete in 745.1 sec
[-----------      29%                  ] 585 of 2000 complete in 746.4 sec
[-----------      29%                  ] 586 of 2000 complete in 747.8 sec
[-----------      29%                  ] 587 of 2000 complete in 749.1 sec
[-----------      29%                  ] 588 of 2000 complete in 750.4 sec
[-----------      29%                  ] 589 of 2000 complete in 751.7 sec
[-----------      29%                  ] 590 of 2000 complete in 753.0 sec
[-----------      29%                  ] 591 of 2000 complete in 754.4 sec
[-----------      29%                  ] 592 of 2000 complete in 755.7 sec
[-----------      29%                  ] 593 of 2000 complete in 757.1 sec
[-----------      29%                  ] 594 of 2000 complete in 758.4 sec
[-----------      29%                  ] 595 of 2000 complete in 759.7 sec
[-----------      29%                  ] 596 of 2000 complete in 761.0 sec
[-----------      29%                  ] 597 of 2000 complete in 762.4 sec
[-----------      29%                  ] 598 of 2000 complete in 763.8 sec
[-----------      29%                  ] 599 of 2000 complete in 765.3 sec
[-----------      30%                  ] 600 of 2000 complete in 766.6 sec
[-----------      30%                  ] 601 of 2000 complete in 768.0 sec
[-----------      30%                  ] 602 of 2000 complete in 769.4 sec
[-----------      30%                  ] 603 of 2000 complete in 770.7 sec
[-----------      30%                  ] 604 of 2000 complete in 772.1 sec
[-----------      30%                  ] 605 of 2000 complete in 773.5 sec
[-----------      30%                  ] 606 of 2000 complete in 774.9 sec
[-----------      30%                  ] 607 of 2000 complete in 776.2 sec
[-----------      30%                  ] 608 of 2000 complete in 777.6 sec
[-----------      30%                  ] 609 of 2000 complete in 778.9 sec
[-----------      30%                  ] 610 of 2000 complete in 780.3 sec
[-----------      30%                  ] 611 of 2000 complete in 781.7 sec
[-----------      30%                  ] 612 of 2000 complete in 783.0 sec
[-----------      30%                  ] 613 of 2000 complete in 784.4 sec
[-----------      30%                  ] 614 of 2000 complete in 785.7 sec
[-----------      30%                  ] 615 of 2000 complete in 787.2 sec
[-----------      30%                  ] 616 of 2000 complete in 788.6 sec
[-----------      30%                  ] 617 of 2000 complete in 790.0 sec
[-----------      30%                  ] 618 of 2000 complete in 791.4 sec
[-----------      30%                  ] 619 of 2000 complete in 792.8 sec
[-----------      31%                  ] 620 of 2000 complete in 794.1 sec
[-----------      31%                  ] 621 of 2000 complete in 795.5 sec
[-----------      31%                  ] 622 of 2000 complete in 796.9 sec
[-----------      31%                  ] 623 of 2000 complete in 798.3 sec
[-----------      31%                  ] 624 of 2000 complete in 799.7 sec
[-----------      31%                  ] 625 of 2000 complete in 801.0 sec
[-----------      31%                  ] 626 of 2000 complete in 802.4 sec
[-----------      31%                  ] 627 of 2000 complete in 803.8 sec
[-----------      31%                  ] 628 of 2000 complete in 805.1 sec
[-----------      31%                  ] 629 of 2000 complete in 806.4 sec
[-----------      31%                  ] 630 of 2000 complete in 807.8 sec
[-----------      31%                  ] 631 of 2000 complete in 809.1 sec
[------------     31%                  ] 632 of 2000 complete in 810.5 sec
[------------     31%                  ] 633 of 2000 complete in 811.8 sec
[------------     31%                  ] 634 of 2000 complete in 813.2 sec
[------------     31%                  ] 635 of 2000 complete in 814.6 sec
[------------     31%                  ] 636 of 2000 complete in 815.9 sec
[------------     31%                  ] 637 of 2000 complete in 817.2 sec
[------------     31%                  ] 638 of 2000 complete in 818.6 sec
[------------     31%                  ] 639 of 2000 complete in 819.9 sec
[------------     32%                  ] 640 of 2000 complete in 821.3 sec
[------------     32%                  ] 641 of 2000 complete in 822.6 sec
[------------     32%                  ] 642 of 2000 complete in 823.9 sec
[------------     32%                  ] 643 of 2000 complete in 825.1 sec
[------------     32%                  ] 644 of 2000 complete in 826.4 sec
[------------     32%                  ] 645 of 2000 complete in 827.8 sec
[------------     32%                  ] 646 of 2000 complete in 829.1 sec
[------------     32%                  ] 647 of 2000 complete in 830.5 sec
[------------     32%                  ] 648 of 2000 complete in 831.9 sec
[------------     32%                  ] 649 of 2000 complete in 833.2 sec
[------------     32%                  ] 650 of 2000 complete in 834.5 sec
[------------     32%                  ] 651 of 2000 complete in 835.9 sec
[------------     32%                  ] 652 of 2000 complete in 837.2 sec
[------------     32%                  ] 653 of 2000 complete in 838.5 sec
[------------     32%                  ] 654 of 2000 complete in 839.9 sec
[------------     32%                  ] 655 of 2000 complete in 841.2 sec
[------------     32%                  ] 656 of 2000 complete in 842.5 sec
[------------     32%                  ] 657 of 2000 complete in 843.8 sec
[----------       27%                  ] 549 of 2000 complete in 716.6 sec
[----------       27%                  ] 550 of 2000 complete in 717.8 sec
[----------       27%                  ] 551 of 2000 complete in 719.0 sec
[----------       27%                  ] 552 of 2000 complete in 720.2 sec
[----------       27%                  ] 553 of 2000 complete in 721.4 sec
[----------       27%                  ] 554 of 2000 complete in 722.5 sec
[----------       27%                  ] 555 of 2000 complete in 723.7 sec
[----------       27%                  ] 556 of 2000 complete in 724.9 sec
[----------       27%                  ] 557 of 2000 complete in 726.1 sec
[----------       27%                  ] 558 of 2000 complete in 727.3 sec
[----------       27%                  ] 559 of 2000 complete in 728.5 sec
[----------       28%                  ] 560 of 2000 complete in 729.8 sec
[----------       28%                  ] 561 of 2000 complete in 731.0 sec
[----------       28%                  ] 562 of 2000 complete in 732.2 sec
[----------       28%                  ] 563 of 2000 complete in 733.4 sec
[----------       28%                  ] 564 of 2000 complete in 734.6 sec
[----------       28%                  ] 565 of 2000 complete in 735.7 sec
[----------       28%                  ] 566 of 2000 complete in 736.9 sec
[----------       28%                  ] 567 of 2000 complete in 738.1 sec
[----------       28%                  ] 568 of 2000 complete in 739.3 sec
[----------       28%                  ] 569 of 2000 complete in 740.5 sec
[----------       28%                  ] 570 of 2000 complete in 741.7 sec
[----------       28%                  ] 571 of 2000 complete in 742.9 sec
[----------       28%                  ] 572 of 2000 complete in 744.2 sec
[----------       28%                  ] 573 of 2000 complete in 745.4 sec
[----------       28%                  ] 574 of 2000 complete in 746.7 sec
[----------       28%                  ] 575 of 2000 complete in 747.9 sec
[----------       28%                  ] 576 of 2000 complete in 749.1 sec
[----------       28%                  ] 577 of 2000 complete in 750.3 sec
[----------       28%                  ] 578 of 2000 complete in 751.6 sec
[-----------      28%                  ] 579 of 2000 complete in 752.8 sec
[-----------      29%                  ] 580 of 2000 complete in 754.0 sec
[-----------      29%                  ] 581 of 2000 complete in 755.2 sec
[-----------      29%                  ] 582 of 2000 complete in 756.4 sec
[-----------      29%                  ] 583 of 2000 complete in 757.7 sec
[-----------      29%                  ] 584 of 2000 complete in 758.9 sec
[-----------      29%                  ] 585 of 2000 complete in 760.1 sec
[-----------      29%                  ] 586 of 2000 complete in 761.4 sec
[-----------      29%                  ] 587 of 2000 complete in 762.6 sec
[-----------      29%                  ] 588 of 2000 complete in 763.8 sec
[-----------      29%                  ] 589 of 2000 complete in 765.1 sec
[-----------      29%                  ] 590 of 2000 complete in 766.3 sec
[-----------      29%                  ] 591 of 2000 complete in 767.5 sec
[-----------      29%                  ] 592 of 2000 complete in 768.8 sec
[-----------      29%                  ] 593 of 2000 complete in 769.9 sec
[-----------      29%                  ] 594 of 2000 complete in 771.1 sec
[-----------      29%                  ] 595 of 2000 complete in 772.3 sec
[-----------      29%                  ] 596 of 2000 complete in 773.6 sec
[-----------      29%                  ] 597 of 2000 complete in 774.8 sec
[-----------      29%                  ] 598 of 2000 complete in 776.0 sec
[-----------      29%                  ] 599 of 2000 complete in 777.2 sec
[-----------      30%                  ] 600 of 2000 complete in 778.4 sec
[-----------      30%                  ] 601 of 2000 complete in 779.6 sec
[-----------      30%                  ] 602 of 2000 complete in 780.8 sec
[-----------      30%                  ] 603 of 2000 complete in 782.0 sec
[-----------      30%                  ] 604 of 2000 complete in 783.2 sec
[-----------      30%                  ] 605 of 2000 complete in 784.3 sec
[-----------      30%                  ] 606 of 2000 complete in 785.5 sec
[-----------      30%                  ] 607 of 2000 complete in 786.7 sec
[-----------      30%                  ] 608 of 2000 complete in 787.9 sec
[-----------      30%                  ] 609 of 2000 complete in 789.2 sec
[-----------      30%                  ] 610 of 2000 complete in 790.4 sec
[-----------      30%                  ] 611 of 2000 complete in 791.5 sec
[-----------      30%                  ] 612 of 2000 complete in 792.7 sec
[-----------      30%                  ] 613 of 2000 complete in 793.9 sec
[-----------      30%                  ] 614 of 2000 complete in 795.0 sec
[-----------      30%                  ] 615 of 2000 complete in 796.1 sec
[-----------      30%                  ] 616 of 2000 complete in 797.3 sec
[-----------      30%                  ] 617 of 2000 complete in 798.5 sec
[-----------      30%                  ] 618 of 2000 complete in 799.7 sec
[-----------      30%                  ] 619 of 2000 complete in 800.9 sec
[-----------      31%                  ] 620 of 2000 complete in 802.1 sec
[-----------      31%                  ] 621 of 2000 complete in 803.3 sec
[-----------      31%                  ] 622 of 2000 complete in 804.4 sec
[-----------      31%                  ] 623 of 2000 complete in 805.6 sec
[-----------      31%                  ] 624 of 2000 complete in 806.8 sec
[-----------      31%                  ] 625 of 2000 complete in 808.0 sec
[-----------      31%                  ] 626 of 2000 complete in 809.2 sec
[-----------      31%                  ] 627 of 2000 complete in 810.4 sec
[-----------      31%                  ] 628 of 2000 complete in 811.6 sec
[-----------      31%                  ] 629 of 2000 complete in 812.7 sec
[-----------      31%                  ] 630 of 2000 complete in 813.9 sec
[-----------      31%                  ] 631 of 2000 complete in 815.1 sec
[------------     31%                  ] 632 of 2000 complete in 816.3 sec
[------------     31%                  ] 633 of 2000 complete in 817.6 sec
[------------     31%                  ] 634 of 2000 complete in 818.7 sec
[------------     31%                  ] 635 of 2000 complete in 819.9 sec
[------------     31%                  ] 636 of 2000 complete in 821.1 sec
[------------     31%                  ] 637 of 2000 complete in 822.3 sec
[------------     31%                  ] 638 of 2000 complete in 823.5 sec
[------------     31%                  ] 639 of 2000 complete in 824.6 sec
[------------     32%                  ] 640 of 2000 complete in 825.8 sec
[------------     32%                  ] 641 of 2000 complete in 827.0 sec
[------------     32%                  ] 642 of 2000 complete in 828.1 sec
[------------     32%                  ] 643 of 2000 complete in 829.3 sec
[------------     32%                  ] 644 of 2000 complete in 830.5 sec
[------------     32%                  ] 645 of 2000 complete in 831.7 sec
[------------     32%                  ] 646 of 2000 complete in 832.8 sec
[------------     32%                  ] 647 of 2000 complete in 834.0 sec
[------------     32%                  ] 648 of 2000 complete in 835.2 sec
[------------     32%                  ] 649 of 2000 complete in 836.3 sec
[------------     32%                  ] 650 of 2000 complete in 837.5 sec
[------------     32%                  ] 651 of 2000 complete in 838.7 sec
[------------     32%                  ] 652 of 2000 complete in 839.8 sec
[------------     32%                  ] 653 of 2000 complete in 840.9 sec
[------------     32%                  ] 654 of 2000 complete in 842.1 sec
[------------     32%                  ] 655 of 2000 complete in 843.3 sec
[------------     32%                  ] 656 of 2000 complete in 844.4 sec
[------------     32%                  ] 657 of 2000 complete in 845.6 sec

[----------       27%                  ] 549 of 2000 complete in 739.6 sec
[----------       27%                  ] 550 of 2000 complete in 741.0 sec
[----------       27%                  ] 551 of 2000 complete in 742.2 sec
[----------       27%                  ] 552 of 2000 complete in 743.5 sec
[----------       27%                  ] 553 of 2000 complete in 744.8 sec
[----------       27%                  ] 554 of 2000 complete in 746.2 sec
[----------       27%                  ] 555 of 2000 complete in 747.4 sec
[----------       27%                  ] 556 of 2000 complete in 748.7 sec
[----------       27%                  ] 557 of 2000 complete in 750.1 sec
[----------       27%                  ] 558 of 2000 complete in 751.4 sec
[----------       27%                  ] 559 of 2000 complete in 752.7 sec
[----------       28%                  ] 560 of 2000 complete in 754.1 sec
[----------       28%                  ] 561 of 2000 complete in 755.4 sec
[----------       28%                  ] 562 of 2000 complete in 756.7 sec
[----------       28%                  ] 563 of 2000 complete in 758.0 sec
[----------       28%                  ] 564 of 2000 complete in 759.4 sec
[----------       28%                  ] 565 of 2000 complete in 760.7 sec
[----------       28%                  ] 566 of 2000 complete in 762.1 sec
[----------       28%                  ] 567 of 2000 complete in 763.5 sec
[----------       28%                  ] 568 of 2000 complete in 764.9 sec
[----------       28%                  ] 569 of 2000 complete in 766.3 sec
[----------       28%                  ] 570 of 2000 complete in 767.7 sec
[----------       28%                  ] 571 of 2000 complete in 769.0 sec
[----------       28%                  ] 572 of 2000 complete in 770.4 sec
[----------       28%                  ] 573 of 2000 complete in 771.7 sec
[----------       28%                  ] 574 of 2000 complete in 772.9 sec
[----------       28%                  ] 575 of 2000 complete in 774.2 sec
[----------       28%                  ] 576 of 2000 complete in 775.4 sec
[----------       28%                  ] 577 of 2000 complete in 776.6 sec
[----------       28%                  ] 578 of 2000 complete in 777.9 sec
[-----------      28%                  ] 579 of 2000 complete in 779.1 sec
[-----------      29%                  ] 580 of 2000 complete in 780.3 sec
[-----------      29%                  ] 581 of 2000 complete in 781.6 sec
[-----------      29%                  ] 582 of 2000 complete in 782.8 sec
[-----------      29%                  ] 583 of 2000 complete in 784.0 sec
[-----------      29%                  ] 584 of 2000 complete in 785.3 sec
[-----------      29%                  ] 585 of 2000 complete in 786.5 sec
[-----------      29%                  ] 586 of 2000 complete in 787.7 sec
[-----------      29%                  ] 587 of 2000 complete in 788.9 sec
[-----------      29%                  ] 588 of 2000 complete in 790.1 sec
[-----------      29%                  ] 589 of 2000 complete in 791.4 sec
[-----------      29%                  ] 590 of 2000 complete in 792.6 sec
[-----------      29%                  ] 591 of 2000 complete in 793.9 sec
[-----------      29%                  ] 592 of 2000 complete in 795.1 sec
[-----------      29%                  ] 593 of 2000 complete in 796.3 sec
[-----------      29%                  ] 594 of 2000 complete in 797.5 sec
[-----------      29%                  ] 595 of 2000 complete in 798.8 sec
[-----------      29%                  ] 596 of 2000 complete in 799.9 sec
[-----------      29%                  ] 597 of 2000 complete in 801.1 sec
[-----------      29%                  ] 598 of 2000 complete in 802.3 sec
[-----------      29%                  ] 599 of 2000 complete in 803.6 sec
[-----------      30%                  ] 600 of 2000 complete in 804.8 sec
[-----------      30%                  ] 601 of 2000 complete in 806.0 sec
[-----------      30%                  ] 602 of 2000 complete in 807.2 sec
[-----------      30%                  ] 603 of 2000 complete in 808.4 sec
[-----------      30%                  ] 604 of 2000 complete in 809.6 sec
[-----------      30%                  ] 605 of 2000 complete in 810.8 sec
[-----------      30%                  ] 606 of 2000 complete in 812.1 sec
[-----------      30%                  ] 607 of 2000 complete in 813.3 sec
[-----------      30%                  ] 608 of 2000 complete in 814.5 sec
[-----------      30%                  ] 609 of 2000 complete in 815.8 sec
[-----------      30%                  ] 610 of 2000 complete in 817.0 sec
[-----------      30%                  ] 611 of 2000 complete in 818.2 sec
[-----------      30%                  ] 612 of 2000 complete in 819.4 sec
[-----------      30%                  ] 613 of 2000 complete in 820.6 sec
[-----------      30%                  ] 614 of 2000 complete in 821.8 sec
[-----------      30%                  ] 615 of 2000 complete in 823.0 sec
[-----------      30%                  ] 616 of 2000 complete in 824.3 sec
[-----------      30%                  ] 617 of 2000 complete in 825.5 sec
[-----------      30%                  ] 618 of 2000 complete in 826.8 sec
[-----------      30%                  ] 619 of 2000 complete in 828.0 sec
[-----------      31%                  ] 620 of 2000 complete in 829.3 sec
[-----------      31%                  ] 621 of 2000 complete in 830.5 sec
[-----------      31%                  ] 622 of 2000 complete in 831.9 sec
[-----------      31%                  ] 623 of 2000 complete in 833.1 sec
[-----------      31%                  ] 624 of 2000 complete in 834.3 sec
[-----------      31%                  ] 625 of 2000 complete in 835.6 sec
[-----------      31%                  ] 626 of 2000 complete in 836.8 sec
[-----------      31%                  ] 627 of 2000 complete in 838.0 sec
[-----------      31%                  ] 628 of 2000 complete in 839.1 sec
[-----------      31%                  ] 629 of 2000 complete in 840.4 sec
[-----------      31%                  ] 630 of 2000 complete in 841.6 sec
[-----------      31%                  ] 631 of 2000 complete in 842.8 sec
[------------     31%                  ] 632 of 2000 complete in 844.0 sec
[------------     31%                  ] 633 of 2000 complete in 845.2 sec
[------------     31%                  ] 634 of 2000 complete in 846.5 sec
[------------     31%                  ] 635 of 2000 complete in 847.7 sec
[------------     31%                  ] 636 of 2000 complete in 848.9 sec
[------------     31%                  ] 637 of 2000 complete in 850.1 sec
[------------     31%                  ] 638 of 2000 complete in 851.4 sec
[------------     31%                  ] 639 of 2000 complete in 852.7 sec
[------------     32%                  ] 640 of 2000 complete in 853.9 sec
[------------     32%                  ] 641 of 2000 complete in 855.2 sec
[------------     32%                  ] 642 of 2000 complete in 856.4 sec
[------------     32%                  ] 643 of 2000 complete in 857.6 sec
[------------     32%                  ] 644 of 2000 complete in 858.9 sec
[------------     32%                  ] 645 of 2000 complete in 860.1 sec
[------------     32%                  ] 646 of 2000 complete in 861.3 sec
[------------     32%                  ] 647 of 2000 complete in 862.5 sec
[------------     32%                  ] 648 of 2000 complete in 863.7 sec
[------------     32%                  ] 649 of 2000 complete in 864.9 sec
[------------     32%                  ] 650 of 2000 complete in 866.2 sec
[------------     32%                  ] 651 of 2000 complete in 867.4 sec
[------------     32%                  ] 652 of 2000 complete in 868.6 sec
[------------     32%                  ] 653 of 2000 complete in 869.8 sec
[------------     32%                  ] 654 of 2000 complete in 871.1 sec
[------------     32%                  ] 655 of 2000 complete in 872.3 sec
[------------     32%                  ] 656 of 2000 complete in 873.4 sec
[------------     32%                  ] 657 of 2000 complete in 874.6 sec
[----------       27%                  ] 549 of 2000 complete in 742.8 sec
[----------       27%                  ] 550 of 2000 complete in 744.2 sec
[----------       27%                  ] 551 of 2000 complete in 745.6 sec
[----------       27%                  ] 552 of 2000 complete in 747.0 sec
[----------       27%                  ] 553 of 2000 complete in 748.4 sec
[----------       27%                  ] 554 of 2000 complete in 749.9 sec
[----------       27%                  ] 555 of 2000 complete in 751.3 sec
[----------       27%                  ] 556 of 2000 complete in 752.7 sec
[----------       27%                  ] 557 of 2000 complete in 754.2 sec
[----------       27%                  ] 558 of 2000 complete in 755.7 sec
[----------       27%                  ] 559 of 2000 complete in 757.1 sec
[----------       28%                  ] 560 of 2000 complete in 758.5 sec
[----------       28%                  ] 561 of 2000 complete in 759.9 sec
[----------       28%                  ] 562 of 2000 complete in 761.4 sec
[----------       28%                  ] 563 of 2000 complete in 762.9 sec
[----------       28%                  ] 564 of 2000 complete in 764.4 sec
[----------       28%                  ] 565 of 2000 complete in 765.8 sec
[----------       28%                  ] 566 of 2000 complete in 767.3 sec
[----------       28%                  ] 567 of 2000 complete in 768.7 sec
[----------       28%                  ] 568 of 2000 complete in 770.1 sec
[----------       28%                  ] 569 of 2000 complete in 771.5 sec
[----------       28%                  ] 570 of 2000 complete in 772.9 sec
[----------       28%                  ] 571 of 2000 complete in 774.3 sec
[----------       28%                  ] 572 of 2000 complete in 775.7 sec
[----------       28%                  ] 573 of 2000 complete in 777.0 sec
[----------       28%                  ] 574 of 2000 complete in 778.4 sec
[----------       28%                  ] 575 of 2000 complete in 779.8 sec
[----------       28%                  ] 576 of 2000 complete in 781.1 sec
[----------       28%                  ] 577 of 2000 complete in 782.5 sec
[----------       28%                  ] 578 of 2000 complete in 783.8 sec
[-----------      28%                  ] 579 of 2000 complete in 785.2 sec
[-----------      29%                  ] 580 of 2000 complete in 786.5 sec
[-----------      29%                  ] 581 of 2000 complete in 787.9 sec
[-----------      29%                  ] 582 of 2000 complete in 789.3 sec
[-----------      29%                  ] 583 of 2000 complete in 790.6 sec
[-----------      29%                  ] 584 of 2000 complete in 792.1 sec
[-----------      29%                  ] 585 of 2000 complete in 793.4 sec
[-----------      29%                  ] 586 of 2000 complete in 794.9 sec
[-----------      29%                  ] 587 of 2000 complete in 796.2 sec
[-----------      29%                  ] 588 of 2000 complete in 797.5 sec
[-----------      29%                  ] 589 of 2000 complete in 798.9 sec
[-----------      29%                  ] 590 of 2000 complete in 800.3 sec
[-----------      29%                  ] 591 of 2000 complete in 801.7 sec
[-----------      29%                  ] 592 of 2000 complete in 803.0 sec
[-----------      29%                  ] 593 of 2000 complete in 804.4 sec
[-----------      29%                  ] 594 of 2000 complete in 805.8 sec
[-----------      29%                  ] 595 of 2000 complete in 807.2 sec
[-----------      29%                  ] 596 of 2000 complete in 808.6 sec
[-----------      29%                  ] 597 of 2000 complete in 810.0 sec
[-----------      29%                  ] 598 of 2000 complete in 811.4 sec
[-----------      29%                  ] 599 of 2000 complete in 812.7 sec
[-----------      30%                  ] 600 of 2000 complete in 814.1 sec
[-----------      30%                  ] 601 of 2000 complete in 815.4 sec
[-----------      30%                  ] 602 of 2000 complete in 816.8 sec
[-----------      30%                  ] 603 of 2000 complete in 818.2 sec
[-----------      30%                  ] 604 of 2000 complete in 819.6 sec
[-----------      30%                  ] 605 of 2000 complete in 821.0 sec
[-----------      30%                  ] 606 of 2000 complete in 822.4 sec
[-----------      30%                  ] 607 of 2000 complete in 823.8 sec
[-----------      30%                  ] 608 of 2000 complete in 825.2 sec
[-----------      30%                  ] 609 of 2000 complete in 826.6 sec
[-----------      30%                  ] 610 of 2000 complete in 828.0 sec
[-----------      30%                  ] 611 of 2000 complete in 829.4 sec
[-----------      30%                  ] 612 of 2000 complete in 830.8 sec
[-----------      30%                  ] 613 of 2000 complete in 832.1 sec
[-----------      30%                  ] 614 of 2000 complete in 833.4 sec
[-----------      30%                  ] 615 of 2000 complete in 834.8 sec
[-----------      30%                  ] 616 of 2000 complete in 836.2 sec
[-----------      30%                  ] 617 of 2000 complete in 837.4 sec
[-----------      30%                  ] 618 of 2000 complete in 838.7 sec
[-----------      30%                  ] 619 of 2000 complete in 840.1 sec
[-----------      31%                  ] 620 of 2000 complete in 841.4 sec
[-----------      31%                  ] 621 of 2000 complete in 842.8 sec
[-----------      31%                  ] 622 of 2000 complete in 844.1 sec
[-----------      31%                  ] 623 of 2000 complete in 845.5 sec
[-----------      31%                  ] 624 of 2000 complete in 846.8 sec
[-----------      31%                  ] 625 of 2000 complete in 848.2 sec
[-----------      31%                  ] 626 of 2000 complete in 849.5 sec
[-----------      31%                  ] 627 of 2000 complete in 850.9 sec
[-----------      31%                  ] 628 of 2000 complete in 852.3 sec
[-----------      31%                  ] 629 of 2000 complete in 853.7 sec
[-----------      31%                  ] 630 of 2000 complete in 855.1 sec
[-----------      31%                  ] 631 of 2000 complete in 856.5 sec
[------------     31%                  ] 632 of 2000 complete in 857.9 sec
[------------     31%                  ] 633 of 2000 complete in 859.3 sec
[------------     31%                  ] 634 of 2000 complete in 860.6 sec
[------------     31%                  ] 635 of 2000 complete in 862.0 sec
[------------     31%                  ] 636 of 2000 complete in 863.3 sec
[------------     31%                  ] 637 of 2000 complete in 864.7 sec
[------------     31%                  ] 638 of 2000 complete in 866.1 sec
[------------     31%                  ] 639 of 2000 complete in 867.5 sec
[------------     32%                  ] 640 of 2000 complete in 868.9 sec
[------------     32%                  ] 641 of 2000 complete in 870.3 sec
[------------     32%                  ] 642 of 2000 complete in 871.7 sec
[------------     32%                  ] 643 of 2000 complete in 873.1 sec
[------------     32%                  ] 644 of 2000 complete in 874.5 sec
[------------     32%                  ] 645 of 2000 complete in 875.8 sec
[------------     32%                  ] 646 of 2000 complete in 877.2 sec
[------------     32%                  ] 647 of 2000 complete in 878.5 sec
[------------     32%                  ] 648 of 2000 complete in 879.9 sec
[------------     32%                  ] 649 of 2000 complete in 881.3 sec
[------------     32%                  ] 650 of 2000 complete in 882.6 sec
[------------     32%                  ] 651 of 2000 complete in 884.0 sec
[------------     32%                  ] 652 of 2000 complete in 885.4 sec
[------------     32%                  ] 653 of 2000 complete in 886.8 sec
[------------     32%                  ] 654 of 2000 complete in 888.2 sec
[------------     32%                  ] 655 of 2000 complete in 889.5 sec
[------------     32%                  ] 656 of 2000 complete in 890.9 sec
[------------     32%                  ] 657 of 2000 complete in 892.3 sec

[------------     32%                  ] 658 of 2000 complete in 846.7 sec
[------------     32%                  ] 659 of 2000 complete in 847.9 sec
[------------     33%                  ] 660 of 2000 complete in 849.1 sec
[------------     33%                  ] 661 of 2000 complete in 850.2 sec
[------------     33%                  ] 662 of 2000 complete in 851.4 sec
[------------     33%                  ] 663 of 2000 complete in 852.6 sec
[------------     33%                  ] 664 of 2000 complete in 853.8 sec
[------------     33%                  ] 665 of 2000 complete in 855.0 sec
[------------     33%                  ] 666 of 2000 complete in 856.1 sec
[------------     33%                  ] 667 of 2000 complete in 857.3 sec
[------------     33%                  ] 668 of 2000 complete in 858.4 sec
[------------     33%                  ] 669 of 2000 complete in 859.6 sec
[------------     33%                  ] 670 of 2000 complete in 860.8 sec
[------------     33%                  ] 671 of 2000 complete in 862.0 sec
[------------     33%                  ] 672 of 2000 complete in 863.2 sec
[------------     33%                  ] 673 of 2000 complete in 864.3 sec
[------------     33%                  ] 674 of 2000 complete in 865.5 sec
[------------     33%                  ] 675 of 2000 complete in 866.7 sec
[------------     33%                  ] 676 of 2000 complete in 868.0 sec
[------------     33%                  ] 677 of 2000 complete in 869.2 sec
[------------     33%                  ] 678 of 2000 complete in 870.4 sec
[------------     33%                  ] 679 of 2000 complete in 871.6 sec
[------------     34%                  ] 680 of 2000 complete in 872.9 sec
[------------     34%                  ] 681 of 2000 complete in 874.1 sec
[------------     34%                  ] 682 of 2000 complete in 875.3 sec
[------------     34%                  ] 683 of 2000 complete in 876.5 sec
[------------     34%                  ] 684 of 2000 complete in 877.8 sec
[-------------    34%                  ] 685 of 2000 complete in 879.0 sec
[-------------    34%                  ] 686 of 2000 complete in 880.3 sec
[-------------    34%                  ] 687 of 2000 complete in 881.5 sec
[-------------    34%                  ] 688 of 2000 complete in 882.6 sec
[-------------    34%                  ] 689 of 2000 complete in 884.0 sec
[-------------    34%                  ] 690 of 2000 complete in 885.2 sec
[-------------    34%                  ] 691 of 2000 complete in 886.4 sec
[-------------    34%                  ] 692 of 2000 complete in 887.5 sec
[-------------    34%                  ] 693 of 2000 complete in 888.7 sec
[-------------    34%                  ] 694 of 2000 complete in 889.9 sec
[-------------    34%                  ] 695 of 2000 complete in 891.3 sec
[-------------    34%                  ] 696 of 2000 complete in 892.5 sec
[-------------    34%                  ] 697 of 2000 complete in 893.7 sec
[-------------    34%                  ] 698 of 2000 complete in 895.0 sec
[-------------    34%                  ] 699 of 2000 complete in 896.2 sec
[-------------    35%                  ] 700 of 2000 complete in 897.4 sec
[-------------    35%                  ] 701 of 2000 complete in 898.7 sec
[-------------    35%                  ] 702 of 2000 complete in 899.9 sec
[-------------    35%                  ] 703 of 2000 complete in 901.1 sec
[-------------    35%                  ] 704 of 2000 complete in 902.4 sec
[-------------    35%                  ] 705 of 2000 complete in 903.6 sec
[-------------    35%                  ] 706 of 2000 complete in 904.8 sec
[-------------    35%                  ] 707 of 2000 complete in 906.0 sec
[-------------    35%                  ] 708 of 2000 complete in 907.2 sec
[-------------    35%                  ] 709 of 2000 complete in 908.4 sec
[-------------    35%                  ] 710 of 2000 complete in 909.6 sec
[-------------    35%                  ] 711 of 2000 complete in 910.8 sec
[-------------    35%                  ] 712 of 2000 complete in 912.0 sec
[-------------    35%                  ] 713 of 2000 complete in 913.2 sec
[-------------    35%                  ] 714 of 2000 complete in 914.4 sec
[-------------    35%                  ] 715 of 2000 complete in 915.5 sec
[-------------    35%                  ] 716 of 2000 complete in 916.7 sec
[-------------    35%                  ] 717 of 2000 complete in 917.9 sec
[-------------    35%                  ] 718 of 2000 complete in 919.1 sec
[-------------    35%                  ] 719 of 2000 complete in 920.3 sec
[-------------    36%                  ] 720 of 2000 complete in 921.5 sec
[-------------    36%                  ] 721 of 2000 complete in 922.7 sec
[-------------    36%                  ] 722 of 2000 complete in 924.0 sec
[-------------    36%                  ] 723 of 2000 complete in 925.2 sec
[-------------    36%                  ] 724 of 2000 complete in 926.4 sec
[-------------    36%                  ] 725 of 2000 complete in 927.7 sec
[-------------    36%                  ] 726 of 2000 complete in 929.0 sec
[-------------    36%                  ] 727 of 2000 complete in 930.3 sec
[-------------    36%                  ] 728 of 2000 complete in 931.6 sec
[-------------    36%                  ] 729 of 2000 complete in 932.9 sec
[-------------    36%                  ] 730 of 2000 complete in 934.2 sec
[-------------    36%                  ] 731 of 2000 complete in 935.5 sec
[-------------    36%                  ] 732 of 2000 complete in 936.8 sec
[-------------    36%                  ] 733 of 2000 complete in 938.1 sec
[-------------    36%                  ] 734 of 2000 complete in 939.3 sec
[-------------    36%                  ] 735 of 2000 complete in 940.7 sec
[-------------    36%                  ] 736 of 2000 complete in 942.0 sec
[--------------   36%                  ] 737 of 2000 complete in 943.4 sec
[--------------   36%                  ] 738 of 2000 complete in 944.8 sec
[--------------   36%                  ] 739 of 2000 complete in 946.1 sec
[--------------   37%                  ] 740 of 2000 complete in 947.4 sec
[--------------   37%                  ] 741 of 2000 complete in 948.7 sec
[--------------   37%                  ] 742 of 2000 complete in 950.0 sec
[--------------   37%                  ] 743 of 2000 complete in 951.3 sec
[--------------   37%                  ] 744 of 2000 complete in 952.6 sec
[--------------   37%                  ] 745 of 2000 complete in 953.9 sec
[--------------   37%                  ] 746 of 2000 complete in 955.1 sec
[--------------   37%                  ] 747 of 2000 complete in 956.4 sec
[--------------   37%                  ] 748 of 2000 complete in 957.8 sec
[--------------   37%                  ] 749 of 2000 complete in 959.1 sec
[--------------   37%                  ] 750 of 2000 complete in 960.4 sec
[--------------   37%                  ] 751 of 2000 complete in 961.6 sec
[--------------   37%                  ] 752 of 2000 complete in 963.0 sec
[--------------   37%                  ] 753 of 2000 complete in 964.3 sec
[--------------   37%                  ] 754 of 2000 complete in 965.6 sec
[--------------   37%                  ] 755 of 2000 complete in 966.9 sec
[--------------   37%                  ] 756 of 2000 complete in 968.3 sec
[--------------   37%                  ] 757 of 2000 complete in 969.6 sec
[--------------   37%                  ] 758 of 2000 complete in 971.0 sec
[--------------   37%                  ] 759 of 2000 complete in 972.3 sec
[--------------   38%                  ] 760 of 2000 complete in 973.7 sec
[--------------   38%                  ] 761 of 2000 complete in 975.0 sec
[--------------   38%                  ] 762 of 2000 complete in 976.4 sec
[--------------   38%                  ] 763 of 2000 complete in 977.7 sec
[--------------   38%                  ] 764 of 2000 complete in 979.1 sec
[--------------   38%                  ] 765 of 2000 complete in 980.4 sec
[--------------   38%                  ] 766 of 2000 complete in 981.8 sec
[------------     32%                  ] 658 of 2000 complete in 845.1 sec
[------------     32%                  ] 659 of 2000 complete in 846.5 sec
[------------     33%                  ] 660 of 2000 complete in 847.8 sec
[------------     33%                  ] 661 of 2000 complete in 849.2 sec
[------------     33%                  ] 662 of 2000 complete in 850.6 sec
[------------     33%                  ] 663 of 2000 complete in 852.0 sec
[------------     33%                  ] 664 of 2000 complete in 853.3 sec
[------------     33%                  ] 665 of 2000 complete in 854.6 sec
[------------     33%                  ] 666 of 2000 complete in 856.0 sec
[------------     33%                  ] 667 of 2000 complete in 857.3 sec
[------------     33%                  ] 668 of 2000 complete in 858.6 sec
[------------     33%                  ] 669 of 2000 complete in 859.9 sec
[------------     33%                  ] 670 of 2000 complete in 861.2 sec
[------------     33%                  ] 671 of 2000 complete in 862.6 sec
[------------     33%                  ] 672 of 2000 complete in 863.9 sec
[------------     33%                  ] 673 of 2000 complete in 865.3 sec
[------------     33%                  ] 674 of 2000 complete in 866.6 sec
[------------     33%                  ] 675 of 2000 complete in 867.8 sec
[------------     33%                  ] 676 of 2000 complete in 869.2 sec
[------------     33%                  ] 677 of 2000 complete in 870.5 sec
[------------     33%                  ] 678 of 2000 complete in 871.9 sec
[------------     33%                  ] 679 of 2000 complete in 873.2 sec
[------------     34%                  ] 680 of 2000 complete in 874.5 sec
[------------     34%                  ] 681 of 2000 complete in 875.8 sec
[------------     34%                  ] 682 of 2000 complete in 877.1 sec
[------------     34%                  ] 683 of 2000 complete in 878.5 sec
[------------     34%                  ] 684 of 2000 complete in 879.8 sec
[-------------    34%                  ] 685 of 2000 complete in 881.2 sec
[-------------    34%                  ] 686 of 2000 complete in 882.6 sec
[-------------    34%                  ] 687 of 2000 complete in 884.0 sec
[-------------    34%                  ] 688 of 2000 complete in 885.3 sec
[-------------    34%                  ] 689 of 2000 complete in 886.7 sec
[-------------    34%                  ] 690 of 2000 complete in 888.0 sec
[-------------    34%                  ] 691 of 2000 complete in 889.3 sec
[-------------    34%                  ] 692 of 2000 complete in 890.7 sec
[-------------    34%                  ] 693 of 2000 complete in 892.1 sec
[-------------    34%                  ] 694 of 2000 complete in 893.5 sec
[-------------    34%                  ] 695 of 2000 complete in 894.9 sec
[-------------    34%                  ] 696 of 2000 complete in 896.3 sec
[-------------    34%                  ] 697 of 2000 complete in 897.7 sec
[-------------    34%                  ] 698 of 2000 complete in 899.1 sec
[-------------    34%                  ] 699 of 2000 complete in 900.4 sec
[-------------    35%                  ] 700 of 2000 complete in 901.8 sec
[-------------    35%                  ] 701 of 2000 complete in 903.1 sec
[-------------    35%                  ] 702 of 2000 complete in 904.5 sec
[-------------    35%                  ] 703 of 2000 complete in 905.8 sec
[-------------    35%                  ] 704 of 2000 complete in 907.1 sec
[-------------    35%                  ] 705 of 2000 complete in 908.5 sec
[-------------    35%                  ] 706 of 2000 complete in 909.8 sec
[-------------    35%                  ] 707 of 2000 complete in 911.2 sec
[-------------    35%                  ] 708 of 2000 complete in 912.5 sec
[-------------    35%                  ] 709 of 2000 complete in 913.9 sec
[-------------    35%                  ] 710 of 2000 complete in 915.2 sec
[-------------    35%                  ] 711 of 2000 complete in 916.5 sec
[-------------    35%                  ] 712 of 2000 complete in 917.9 sec
[-------------    35%                  ] 713 of 2000 complete in 919.2 sec
[-------------    35%                  ] 714 of 2000 complete in 920.5 sec
[-------------    35%                  ] 715 of 2000 complete in 921.8 sec
[-------------    35%                  ] 716 of 2000 complete in 923.2 sec
[-------------    35%                  ] 717 of 2000 complete in 924.5 sec
[-------------    35%                  ] 718 of 2000 complete in 925.8 sec
[-------------    35%                  ] 719 of 2000 complete in 927.2 sec
[-------------    36%                  ] 720 of 2000 complete in 928.7 sec
[-------------    36%                  ] 721 of 2000 complete in 930.0 sec
[-------------    36%                  ] 722 of 2000 complete in 931.3 sec
[-------------    36%                  ] 723 of 2000 complete in 932.7 sec
[-------------    36%                  ] 724 of 2000 complete in 934.0 sec
[-------------    36%                  ] 725 of 2000 complete in 935.3 sec
[-------------    36%                  ] 726 of 2000 complete in 936.7 sec
[-------------    36%                  ] 727 of 2000 complete in 938.0 sec
[-------------    36%                  ] 728 of 2000 complete in 939.3 sec
[-------------    36%                  ] 729 of 2000 complete in 940.7 sec
[-------------    36%                  ] 730 of 2000 complete in 942.1 sec
[-------------    36%                  ] 731 of 2000 complete in 943.5 sec
[-------------    36%                  ] 732 of 2000 complete in 944.8 sec
[-------------    36%                  ] 733 of 2000 complete in 946.2 sec
[-------------    36%                  ] 734 of 2000 complete in 947.6 sec
[-------------    36%                  ] 735 of 2000 complete in 948.9 sec
[-------------    36%                  ] 736 of 2000 complete in 950.3 sec
[--------------   36%                  ] 737 of 2000 complete in 951.7 sec
[--------------   36%                  ] 738 of 2000 complete in 953.1 sec
[--------------   36%                  ] 739 of 2000 complete in 954.5 sec
[--------------   37%                  ] 740 of 2000 complete in 955.9 sec
[--------------   37%                  ] 741 of 2000 complete in 957.3 sec
[--------------   37%                  ] 742 of 2000 complete in 958.7 sec
[--------------   37%                  ] 743 of 2000 complete in 960.1 sec
[--------------   37%                  ] 744 of 2000 complete in 961.4 sec
[--------------   37%                  ] 745 of 2000 complete in 962.7 sec
[--------------   37%                  ] 746 of 2000 complete in 964.0 sec
[--------------   37%                  ] 747 of 2000 complete in 965.3 sec
[--------------   37%                  ] 748 of 2000 complete in 966.7 sec
[--------------   37%                  ] 749 of 2000 complete in 968.0 sec
[--------------   37%                  ] 750 of 2000 complete in 969.3 sec
[--------------   37%                  ] 751 of 2000 complete in 970.7 sec
[--------------   37%                  ] 752 of 2000 complete in 972.0 sec
[--------------   37%                  ] 753 of 2000 complete in 973.4 sec
[--------------   37%                  ] 754 of 2000 complete in 974.7 sec
[--------------   37%                  ] 755 of 2000 complete in 976.1 sec
[--------------   37%                  ] 756 of 2000 complete in 977.4 sec
[--------------   37%                  ] 757 of 2000 complete in 978.6 sec
[--------------   37%                  ] 758 of 2000 complete in 980.0 sec
[--------------   37%                  ] 759 of 2000 complete in 981.4 sec
[--------------   38%                  ] 760 of 2000 complete in 982.7 sec
[--------------   38%                  ] 761 of 2000 complete in 984.1 sec
[--------------   38%                  ] 762 of 2000 complete in 985.4 sec
[--------------   38%                  ] 763 of 2000 complete in 986.8 sec
[--------------   38%                  ] 764 of 2000 complete in 988.2 sec
[--------------   38%                  ] 765 of 2000 complete in 989.5 sec
[--------------   38%                  ] 766 of 2000 complete in 990.8 sec

[------------     32%                  ] 658 of 2000 complete in 875.8 sec
[------------     32%                  ] 659 of 2000 complete in 877.0 sec
[------------     33%                  ] 660 of 2000 complete in 878.2 sec
[------------     33%                  ] 661 of 2000 complete in 879.3 sec
[------------     33%                  ] 662 of 2000 complete in 880.5 sec
[------------     33%                  ] 663 of 2000 complete in 881.7 sec
[------------     33%                  ] 664 of 2000 complete in 882.9 sec
[------------     33%                  ] 665 of 2000 complete in 884.2 sec
[------------     33%                  ] 666 of 2000 complete in 885.4 sec
[------------     33%                  ] 667 of 2000 complete in 886.7 sec
[------------     33%                  ] 668 of 2000 complete in 887.9 sec
[------------     33%                  ] 669 of 2000 complete in 889.2 sec
[------------     33%                  ] 670 of 2000 complete in 890.4 sec
[------------     33%                  ] 671 of 2000 complete in 891.7 sec
[------------     33%                  ] 672 of 2000 complete in 892.9 sec
[------------     33%                  ] 673 of 2000 complete in 894.3 sec
[------------     33%                  ] 674 of 2000 complete in 895.5 sec
[------------     33%                  ] 675 of 2000 complete in 896.7 sec
[------------     33%                  ] 676 of 2000 complete in 898.0 sec
[------------     33%                  ] 677 of 2000 complete in 899.2 sec
[------------     33%                  ] 678 of 2000 complete in 900.4 sec
[------------     33%                  ] 679 of 2000 complete in 901.6 sec
[------------     34%                  ] 680 of 2000 complete in 902.9 sec
[------------     34%                  ] 681 of 2000 complete in 904.1 sec
[------------     34%                  ] 682 of 2000 complete in 905.3 sec
[------------     34%                  ] 683 of 2000 complete in 906.5 sec
[------------     34%                  ] 684 of 2000 complete in 907.7 sec
[-------------    34%                  ] 685 of 2000 complete in 909.0 sec
[-------------    34%                  ] 686 of 2000 complete in 910.3 sec
[-------------    34%                  ] 687 of 2000 complete in 911.5 sec
[-------------    34%                  ] 688 of 2000 complete in 912.7 sec
[-------------    34%                  ] 689 of 2000 complete in 913.9 sec
[-------------    34%                  ] 690 of 2000 complete in 915.2 sec
[-------------    34%                  ] 691 of 2000 complete in 916.4 sec
[-------------    34%                  ] 692 of 2000 complete in 917.6 sec
[-------------    34%                  ] 693 of 2000 complete in 918.7 sec
[-------------    34%                  ] 694 of 2000 complete in 919.9 sec
[-------------    34%                  ] 695 of 2000 complete in 921.1 sec
[-------------    34%                  ] 696 of 2000 complete in 922.3 sec
[-------------    34%                  ] 697 of 2000 complete in 923.6 sec
[-------------    34%                  ] 698 of 2000 complete in 924.8 sec
[-------------    34%                  ] 699 of 2000 complete in 926.0 sec
[-------------    35%                  ] 700 of 2000 complete in 927.2 sec
[-------------    35%                  ] 701 of 2000 complete in 928.4 sec
[-------------    35%                  ] 702 of 2000 complete in 929.6 sec
[-------------    35%                  ] 703 of 2000 complete in 930.8 sec
[-------------    35%                  ] 704 of 2000 complete in 932.0 sec
[-------------    35%                  ] 705 of 2000 complete in 933.2 sec
[-------------    35%                  ] 706 of 2000 complete in 934.4 sec
[-------------    35%                  ] 707 of 2000 complete in 935.6 sec
[-------------    35%                  ] 708 of 2000 complete in 936.8 sec
[-------------    35%                  ] 709 of 2000 complete in 938.1 sec
[-------------    35%                  ] 710 of 2000 complete in 939.2 sec
[-------------    35%                  ] 711 of 2000 complete in 940.4 sec
[-------------    35%                  ] 712 of 2000 complete in 941.6 sec
[-------------    35%                  ] 713 of 2000 complete in 942.9 sec
[-------------    35%                  ] 714 of 2000 complete in 944.1 sec
[-------------    35%                  ] 715 of 2000 complete in 945.3 sec
[-------------    35%                  ] 716 of 2000 complete in 946.5 sec
[-------------    35%                  ] 717 of 2000 complete in 947.7 sec
[-------------    35%                  ] 718 of 2000 complete in 948.9 sec
[-------------    35%                  ] 719 of 2000 complete in 950.1 sec
[-------------    36%                  ] 720 of 2000 complete in 951.3 sec
[-------------    36%                  ] 721 of 2000 complete in 952.5 sec
[-------------    36%                  ] 722 of 2000 complete in 953.7 sec
[-------------    36%                  ] 723 of 2000 complete in 955.0 sec
[-------------    36%                  ] 724 of 2000 complete in 956.3 sec
[-------------    36%                  ] 725 of 2000 complete in 957.6 sec
[-------------    36%                  ] 726 of 2000 complete in 958.8 sec
[-------------    36%                  ] 727 of 2000 complete in 960.1 sec
[-------------    36%                  ] 728 of 2000 complete in 961.3 sec
[-------------    36%                  ] 729 of 2000 complete in 962.6 sec
[-------------    36%                  ] 730 of 2000 complete in 963.8 sec
[-------------    36%                  ] 731 of 2000 complete in 965.0 sec
[-------------    36%                  ] 732 of 2000 complete in 966.3 sec
[-------------    36%                  ] 733 of 2000 complete in 967.5 sec
[-------------    36%                  ] 734 of 2000 complete in 968.8 sec
[-------------    36%                  ] 735 of 2000 complete in 970.0 sec
[-------------    36%                  ] 736 of 2000 complete in 971.3 sec
[--------------   36%                  ] 737 of 2000 complete in 972.5 sec
[--------------   36%                  ] 738 of 2000 complete in 973.8 sec
[--------------   36%                  ] 739 of 2000 complete in 975.0 sec
[--------------   37%                  ] 740 of 2000 complete in 976.3 sec
[--------------   37%                  ] 741 of 2000 complete in 977.5 sec
[--------------   37%                  ] 742 of 2000 complete in 978.8 sec
[--------------   37%                  ] 743 of 2000 complete in 980.1 sec
[--------------   37%                  ] 744 of 2000 complete in 981.4 sec
[--------------   37%                  ] 745 of 2000 complete in 982.6 sec
[--------------   37%                  ] 746 of 2000 complete in 983.9 sec
[--------------   37%                  ] 747 of 2000 complete in 985.2 sec
[--------------   37%                  ] 748 of 2000 complete in 986.4 sec
[--------------   37%                  ] 749 of 2000 complete in 987.7 sec
[--------------   37%                  ] 750 of 2000 complete in 989.0 sec
[--------------   37%                  ] 751 of 2000 complete in 990.2 sec
[--------------   37%                  ] 752 of 2000 complete in 991.5 sec
[--------------   37%                  ] 753 of 2000 complete in 992.7 sec
[--------------   37%                  ] 754 of 2000 complete in 994.0 sec
[--------------   37%                  ] 755 of 2000 complete in 995.3 sec
[--------------   37%                  ] 756 of 2000 complete in 996.6 sec
[--------------   37%                  ] 757 of 2000 complete in 997.8 sec
[--------------   37%                  ] 758 of 2000 complete in 999.1 sec
[--------------   37%                  ] 759 of 2000 complete in 1000.3 sec
[--------------   38%                  ] 760 of 2000 complete in 1001.7 sec
[--------------   38%                  ] 761 of 2000 complete in 1002.9 sec
[--------------   38%                  ] 762 of 2000 complete in 1004.3 sec
[--------------   38%                  ] 763 of 2000 complete in 1005.5 sec
[--------------   38%                  ] 764 of 2000 complete in 1006.8 sec
[--------------   38%                  ] 765 of 2000 complete in 1008.1 sec
[--------------   38%                  ] 766 of 2000 complete in 1009.4 sec
[------------     32%                  ] 658 of 2000 complete in 893.7 sec
[------------     32%                  ] 659 of 2000 complete in 895.1 sec
[------------     33%                  ] 660 of 2000 complete in 896.5 sec
[------------     33%                  ] 661 of 2000 complete in 897.9 sec
[------------     33%                  ] 662 of 2000 complete in 899.3 sec
[------------     33%                  ] 663 of 2000 complete in 900.7 sec
[------------     33%                  ] 664 of 2000 complete in 902.1 sec
[------------     33%                  ] 665 of 2000 complete in 903.5 sec
[------------     33%                  ] 666 of 2000 complete in 904.9 sec
[------------     33%                  ] 667 of 2000 complete in 906.3 sec
[------------     33%                  ] 668 of 2000 complete in 907.7 sec
[------------     33%                  ] 669 of 2000 complete in 909.1 sec
[------------     33%                  ] 670 of 2000 complete in 910.5 sec
[------------     33%                  ] 671 of 2000 complete in 911.9 sec
[------------     33%                  ] 672 of 2000 complete in 913.4 sec
[------------     33%                  ] 673 of 2000 complete in 914.9 sec
[------------     33%                  ] 674 of 2000 complete in 916.2 sec
[------------     33%                  ] 675 of 2000 complete in 917.7 sec
[------------     33%                  ] 676 of 2000 complete in 919.0 sec
[------------     33%                  ] 677 of 2000 complete in 920.4 sec
[------------     33%                  ] 678 of 2000 complete in 921.8 sec
[------------     33%                  ] 679 of 2000 complete in 923.2 sec
[------------     34%                  ] 680 of 2000 complete in 924.5 sec
[------------     34%                  ] 681 of 2000 complete in 925.9 sec
[------------     34%                  ] 682 of 2000 complete in 927.3 sec
[------------     34%                  ] 683 of 2000 complete in 928.7 sec
[------------     34%                  ] 684 of 2000 complete in 930.0 sec
[-------------    34%                  ] 685 of 2000 complete in 931.4 sec
[-------------    34%                  ] 686 of 2000 complete in 932.8 sec
[-------------    34%                  ] 687 of 2000 complete in 934.1 sec
[-------------    34%                  ] 688 of 2000 complete in 935.5 sec
[-------------    34%                  ] 689 of 2000 complete in 937.0 sec
[-------------    34%                  ] 690 of 2000 complete in 938.4 sec
[-------------    34%                  ] 691 of 2000 complete in 939.8 sec
[-------------    34%                  ] 692 of 2000 complete in 941.2 sec
[-------------    34%                  ] 693 of 2000 complete in 942.7 sec
[-------------    34%                  ] 694 of 2000 complete in 944.1 sec
[-------------    34%                  ] 695 of 2000 complete in 945.6 sec
[-------------    34%                  ] 696 of 2000 complete in 946.9 sec
[-------------    34%                  ] 697 of 2000 complete in 948.4 sec
[-------------    34%                  ] 698 of 2000 complete in 949.8 sec
[-------------    34%                  ] 699 of 2000 complete in 951.2 sec
[-------------    35%                  ] 700 of 2000 complete in 952.6 sec
[-------------    35%                  ] 701 of 2000 complete in 954.0 sec
[-------------    35%                  ] 702 of 2000 complete in 955.3 sec
[-------------    35%                  ] 703 of 2000 complete in 956.7 sec
[-------------    35%                  ] 704 of 2000 complete in 958.1 sec
[-------------    35%                  ] 705 of 2000 complete in 959.5 sec
[-------------    35%                  ] 706 of 2000 complete in 960.9 sec
[-------------    35%                  ] 707 of 2000 complete in 962.3 sec
[-------------    35%                  ] 708 of 2000 complete in 963.6 sec
[-------------    35%                  ] 709 of 2000 complete in 964.9 sec
[-------------    35%                  ] 710 of 2000 complete in 966.3 sec
[-------------    35%                  ] 711 of 2000 complete in 967.7 sec
[-------------    35%                  ] 712 of 2000 complete in 969.1 sec
[-------------    35%                  ] 713 of 2000 complete in 970.5 sec
[-------------    35%                  ] 714 of 2000 complete in 971.8 sec
[-------------    35%                  ] 715 of 2000 complete in 973.2 sec
[-------------    35%                  ] 716 of 2000 complete in 974.6 sec
[-------------    35%                  ] 717 of 2000 complete in 976.0 sec
[-------------    35%                  ] 718 of 2000 complete in 977.3 sec
[-------------    35%                  ] 719 of 2000 complete in 978.8 sec
[-------------    36%                  ] 720 of 2000 complete in 980.2 sec
[-------------    36%                  ] 721 of 2000 complete in 981.6 sec
[-------------    36%                  ] 722 of 2000 complete in 983.0 sec
[-------------    36%                  ] 723 of 2000 complete in 984.4 sec
[-------------    36%                  ] 724 of 2000 complete in 985.8 sec
[-------------    36%                  ] 725 of 2000 complete in 987.3 sec
[-------------    36%                  ] 726 of 2000 complete in 988.6 sec
[-------------    36%                  ] 727 of 2000 complete in 990.0 sec
[-------------    36%                  ] 728 of 2000 complete in 991.4 sec
[-------------    36%                  ] 729 of 2000 complete in 992.7 sec
[-------------    36%                  ] 730 of 2000 complete in 994.2 sec
[-------------    36%                  ] 731 of 2000 complete in 995.6 sec
[-------------    36%                  ] 732 of 2000 complete in 997.1 sec
[-------------    36%                  ] 733 of 2000 complete in 998.5 sec
[-------------    36%                  ] 734 of 2000 complete in 999.9 sec
[-------------    36%                  ] 735 of 2000 complete in 1001.3 sec
[-------------    36%                  ] 736 of 2000 complete in 1002.7 sec
[--------------   36%                  ] 737 of 2000 complete in 1004.1 sec
[--------------   36%                  ] 738 of 2000 complete in 1005.5 sec
[--------------   36%                  ] 739 of 2000 complete in 1006.8 sec
[--------------   37%                  ] 740 of 2000 complete in 1008.2 sec
[--------------   37%                  ] 741 of 2000 complete in 1009.6 sec
[--------------   37%                  ] 742 of 2000 complete in 1010.9 sec
[--------------   37%                  ] 743 of 2000 complete in 1012.3 sec
[--------------   37%                  ] 744 of 2000 complete in 1013.6 sec
[--------------   37%                  ] 745 of 2000 complete in 1015.0 sec
[--------------   37%                  ] 746 of 2000 complete in 1016.4 sec
[--------------   37%                  ] 747 of 2000 complete in 1017.8 sec
[--------------   37%                  ] 748 of 2000 complete in 1019.2 sec
[--------------   37%                  ] 749 of 2000 complete in 1020.5 sec
[--------------   37%                  ] 750 of 2000 complete in 1021.8 sec
[--------------   37%                  ] 751 of 2000 complete in 1023.2 sec
[--------------   37%                  ] 752 of 2000 complete in 1024.5 sec
[--------------   37%                  ] 753 of 2000 complete in 1025.9 sec
[--------------   37%                  ] 754 of 2000 complete in 1027.3 sec
[--------------   37%                  ] 755 of 2000 complete in 1028.6 sec
[--------------   37%                  ] 756 of 2000 complete in 1030.0 sec
[--------------   37%                  ] 757 of 2000 complete in 1031.3 sec
[--------------   37%                  ] 758 of 2000 complete in 1032.7 sec
[--------------   37%                  ] 759 of 2000 complete in 1033.9 sec
[--------------   38%                  ] 760 of 2000 complete in 1035.4 sec
[--------------   38%                  ] 761 of 2000 complete in 1036.7 sec
[--------------   38%                  ] 762 of 2000 complete in 1038.1 sec
[--------------   38%                  ] 763 of 2000 complete in 1039.4 sec
[--------------   38%                  ] 764 of 2000 complete in 1040.8 sec
[--------------   38%                  ] 765 of 2000 complete in 1042.3 sec

[--------------   38%                  ] 767 of 2000 complete in 983.2 sec
[--------------   38%                  ] 768 of 2000 complete in 984.5 sec
[--------------   38%                  ] 769 of 2000 complete in 985.9 sec
[--------------   38%                  ] 770 of 2000 complete in 987.2 sec
[--------------   38%                  ] 771 of 2000 complete in 988.6 sec
[--------------   38%                  ] 772 of 2000 complete in 989.9 sec
[--------------   38%                  ] 773 of 2000 complete in 991.2 sec
[--------------   38%                  ] 774 of 2000 complete in 992.5 sec
[--------------   38%                  ] 775 of 2000 complete in 993.9 sec
[--------------   38%                  ] 776 of 2000 complete in 995.2 sec
[--------------   38%                  ] 777 of 2000 complete in 996.6 sec
[--------------   38%                  ] 778 of 2000 complete in 997.9 sec
[--------------   38%                  ] 779 of 2000 complete in 999.2 sec
[--------------   39%                  ] 780 of 2000 complete in 1000.5 sec
[--------------   39%                  ] 781 of 2000 complete in 1001.9 sec
[--------------   39%                  ] 782 of 2000 complete in 1003.2 sec
[--------------   39%                  ] 783 of 2000 complete in 1004.6 sec
[--------------   39%                  ] 784 of 2000 complete in 1006.0 sec
[--------------   39%                  ] 785 of 2000 complete in 1007.2 sec
[--------------   39%                  ] 786 of 2000 complete in 1008.6 sec
[--------------   39%                  ] 787 of 2000 complete in 1009.9 sec
[--------------   39%                  ] 788 of 2000 complete in 1011.2 sec
[--------------   39%                  ] 789 of 2000 complete in 1012.6 sec
[---------------  39%                  ] 790 of 2000 complete in 1013.9 sec
[---------------  39%                  ] 791 of 2000 complete in 1015.3 sec
[---------------  39%                  ] 792 of 2000 complete in 1016.7 sec
[---------------  39%                  ] 793 of 2000 complete in 1018.0 sec
[---------------  39%                  ] 794 of 2000 complete in 1019.4 sec
[---------------  39%                  ] 795 of 2000 complete in 1020.8 sec
[---------------  39%                  ] 796 of 2000 complete in 1022.2 sec
[---------------  39%                  ] 797 of 2000 complete in 1023.5 sec
[---------------  39%                  ] 798 of 2000 complete in 1024.8 sec
[---------------  39%                  ] 799 of 2000 complete in 1026.1 sec
[---------------  40%                  ] 800 of 2000 complete in 1027.4 sec
[---------------  40%                  ] 801 of 2000 complete in 1028.8 sec
[---------------  40%                  ] 802 of 2000 complete in 1030.1 sec
[---------------  40%                  ] 803 of 2000 complete in 1031.3 sec
[---------------  40%                  ] 804 of 2000 complete in 1032.7 sec
[---------------  40%                  ] 805 of 2000 complete in 1034.1 sec
[---------------  40%                  ] 806 of 2000 complete in 1035.4 sec
[---------------  40%                  ] 807 of 2000 complete in 1036.7 sec
[---------------  40%                  ] 808 of 2000 complete in 1038.1 sec
[---------------  40%                  ] 809 of 2000 complete in 1039.5 sec
[---------------  40%                  ] 810 of 2000 complete in 1041.0 sec
[---------------  40%                  ] 811 of 2000 complete in 1042.4 sec
[---------------  40%                  ] 812 of 2000 complete in 1043.7 sec
[---------------  40%                  ] 813 of 2000 complete in 1045.1 sec
[---------------  40%                  ] 814 of 2000 complete in 1046.5 sec
[---------------  40%                  ] 815 of 2000 complete in 1047.8 sec
[---------------  40%                  ] 816 of 2000 complete in 1049.2 sec
[---------------  40%                  ] 817 of 2000 complete in 1050.6 sec
[---------------  40%                  ] 818 of 2000 complete in 1052.0 sec
[---------------  40%                  ] 819 of 2000 complete in 1053.4 sec
[---------------  41%                  ] 820 of 2000 complete in 1054.8 sec
[---------------  41%                  ] 821 of 2000 complete in 1056.2 sec
[---------------  41%                  ] 822 of 2000 complete in 1057.5 sec
[---------------  41%                  ] 823 of 2000 complete in 1058.9 sec
[---------------  41%                  ] 824 of 2000 complete in 1060.3 sec
[---------------  41%                  ] 825 of 2000 complete in 1061.6 sec
[---------------  41%                  ] 826 of 2000 complete in 1063.0 sec
[---------------  41%                  ] 827 of 2000 complete in 1064.4 sec
[---------------  41%                  ] 828 of 2000 complete in 1065.7 sec
[---------------  41%                  ] 829 of 2000 complete in 1067.1 sec
[---------------  41%                  ] 830 of 2000 complete in 1068.4 sec
[---------------  41%                  ] 831 of 2000 complete in 1069.8 sec
[---------------  41%                  ] 832 of 2000 complete in 1071.2 sec
[---------------  41%                  ] 833 of 2000 complete in 1072.5 sec
[---------------  41%                  ] 834 of 2000 complete in 1073.9 sec
[---------------  41%                  ] 835 of 2000 complete in 1075.2 sec
[---------------  41%                  ] 836 of 2000 complete in 1076.5 sec
[---------------  41%                  ] 837 of 2000 complete in 1077.9 sec
[---------------  41%                  ] 838 of 2000 complete in 1079.3 sec
[---------------  41%                  ] 839 of 2000 complete in 1080.7 sec
[---------------  42%                  ] 840 of 2000 complete in 1082.0 sec
[---------------  42%                  ] 841 of 2000 complete in 1083.4 sec
[---------------  42%                  ] 842 of 2000 complete in 1084.7 sec
[---------------- 42%                  ] 843 of 2000 complete in 1086.1 sec
[---------------- 42%                  ] 844 of 2000 complete in 1087.5 sec
[---------------- 42%                  ] 845 of 2000 complete in 1089.0 sec
[---------------- 42%                  ] 846 of 2000 complete in 1090.4 sec
[---------------- 42%                  ] 847 of 2000 complete in 1091.7 sec
[---------------- 42%                  ] 848 of 2000 complete in 1093.1 sec
[---------------- 42%                  ] 849 of 2000 complete in 1094.4 sec
[---------------- 42%                  ] 850 of 2000 complete in 1095.8 sec
[---------------- 42%                  ] 851 of 2000 complete in 1097.2 sec
[---------------- 42%                  ] 852 of 2000 complete in 1098.6 sec
[---------------- 42%                  ] 853 of 2000 complete in 1099.9 sec
[---------------- 42%                  ] 854 of 2000 complete in 1101.3 sec
[---------------- 42%                  ] 855 of 2000 complete in 1102.6 sec
[---------------- 42%                  ] 856 of 2000 complete in 1104.0 sec
[---------------- 42%                  ] 857 of 2000 complete in 1105.3 sec
[---------------- 42%                  ] 858 of 2000 complete in 1106.8 sec
[---------------- 42%                  ] 859 of 2000 complete in 1108.1 sec
[---------------- 43%                  ] 860 of 2000 complete in 1109.6 sec
[---------------- 43%                  ] 861 of 2000 complete in 1111.0 sec
[---------------- 43%                  ] 862 of 2000 complete in 1112.4 sec
[---------------- 43%                  ] 863 of 2000 complete in 1113.7 sec
[---------------- 43%                  ] 864 of 2000 complete in 1115.1 sec
[---------------- 43%                  ] 865 of 2000 complete in 1116.5 sec
[---------------- 43%                  ] 866 of 2000 complete in 1117.8 sec
[---------------- 43%                  ] 867 of 2000 complete in 1119.1 sec
[---------------- 43%                  ] 868 of 2000 complete in 1120.5 sec
[---------------- 43%                  ] 869 of 2000 complete in 1121.9 sec
[---------------- 43%                  ] 870 of 2000 complete in 1123.3 sec
[---------------- 43%                  ] 871 of 2000 complete in 1124.8 sec
[---------------- 43%                  ] 872 of 2000 complete in 1126.1 sec
[---------------- 43%                  ] 873 of 2000 complete in 1127.4 sec
[--------------   38%                  ] 767 of 2000 complete in 992.1 sec
[--------------   38%                  ] 768 of 2000 complete in 993.5 sec
[--------------   38%                  ] 769 of 2000 complete in 994.9 sec
[--------------   38%                  ] 770 of 2000 complete in 996.2 sec
[--------------   38%                  ] 771 of 2000 complete in 997.5 sec
[--------------   38%                  ] 772 of 2000 complete in 998.9 sec
[--------------   38%                  ] 773 of 2000 complete in 1000.3 sec
[--------------   38%                  ] 774 of 2000 complete in 1001.7 sec
[--------------   38%                  ] 775 of 2000 complete in 1003.1 sec
[--------------   38%                  ] 776 of 2000 complete in 1004.5 sec
[--------------   38%                  ] 777 of 2000 complete in 1005.9 sec
[--------------   38%                  ] 778 of 2000 complete in 1007.3 sec
[--------------   38%                  ] 779 of 2000 complete in 1008.7 sec
[--------------   39%                  ] 780 of 2000 complete in 1010.1 sec
[--------------   39%                  ] 781 of 2000 complete in 1011.4 sec
[--------------   39%                  ] 782 of 2000 complete in 1012.8 sec
[--------------   39%                  ] 783 of 2000 complete in 1014.2 sec
[--------------   39%                  ] 784 of 2000 complete in 1015.5 sec
[--------------   39%                  ] 785 of 2000 complete in 1016.9 sec
[--------------   39%                  ] 786 of 2000 complete in 1018.3 sec
[--------------   39%                  ] 787 of 2000 complete in 1019.6 sec
[--------------   39%                  ] 788 of 2000 complete in 1021.0 sec
[--------------   39%                  ] 789 of 2000 complete in 1022.4 sec
[---------------  39%                  ] 790 of 2000 complete in 1023.9 sec
[---------------  39%                  ] 791 of 2000 complete in 1025.3 sec
[---------------  39%                  ] 792 of 2000 complete in 1026.6 sec
[---------------  39%                  ] 793 of 2000 complete in 1028.0 sec
[---------------  39%                  ] 794 of 2000 complete in 1029.4 sec
[---------------  39%                  ] 795 of 2000 complete in 1030.8 sec
[---------------  39%                  ] 796 of 2000 complete in 1032.1 sec
[---------------  39%                  ] 797 of 2000 complete in 1033.4 sec
[---------------  39%                  ] 798 of 2000 complete in 1034.7 sec
[---------------  39%                  ] 799 of 2000 complete in 1036.0 sec
[---------------  40%                  ] 800 of 2000 complete in 1037.4 sec
[---------------  40%                  ] 801 of 2000 complete in 1038.8 sec
[---------------  40%                  ] 802 of 2000 complete in 1040.3 sec
[---------------  40%                  ] 803 of 2000 complete in 1041.6 sec
[---------------  40%                  ] 804 of 2000 complete in 1043.0 sec
[---------------  40%                  ] 805 of 2000 complete in 1044.4 sec
[---------------  40%                  ] 806 of 2000 complete in 1045.7 sec
[---------------  40%                  ] 807 of 2000 complete in 1047.1 sec
[---------------  40%                  ] 808 of 2000 complete in 1048.4 sec
[---------------  40%                  ] 809 of 2000 complete in 1049.9 sec
[---------------  40%                  ] 810 of 2000 complete in 1051.2 sec
[---------------  40%                  ] 811 of 2000 complete in 1052.6 sec
[---------------  40%                  ] 812 of 2000 complete in 1054.0 sec
[---------------  40%                  ] 813 of 2000 complete in 1055.4 sec
[---------------  40%                  ] 814 of 2000 complete in 1056.7 sec
[---------------  40%                  ] 815 of 2000 complete in 1058.1 sec
[---------------  40%                  ] 816 of 2000 complete in 1059.4 sec
[---------------  40%                  ] 817 of 2000 complete in 1060.8 sec
[---------------  40%                  ] 818 of 2000 complete in 1062.2 sec
[---------------  40%                  ] 819 of 2000 complete in 1063.7 sec
[---------------  41%                  ] 820 of 2000 complete in 1065.1 sec
[---------------  41%                  ] 821 of 2000 complete in 1066.4 sec
[---------------  41%                  ] 822 of 2000 complete in 1067.7 sec
[---------------  41%                  ] 823 of 2000 complete in 1069.1 sec
[---------------  41%                  ] 824 of 2000 complete in 1070.5 sec
[---------------  41%                  ] 825 of 2000 complete in 1071.9 sec
[---------------  41%                  ] 826 of 2000 complete in 1073.3 sec
[---------------  41%                  ] 827 of 2000 complete in 1074.7 sec
[---------------  41%                  ] 828 of 2000 complete in 1076.1 sec
[---------------  41%                  ] 829 of 2000 complete in 1077.5 sec
[---------------  41%                  ] 830 of 2000 complete in 1078.9 sec
[---------------  41%                  ] 831 of 2000 complete in 1080.2 sec
[---------------  41%                  ] 832 of 2000 complete in 1081.6 sec
[---------------  41%                  ] 833 of 2000 complete in 1083.0 sec
[---------------  41%                  ] 834 of 2000 complete in 1084.3 sec
[---------------  41%                  ] 835 of 2000 complete in 1085.7 sec
[---------------  41%                  ] 836 of 2000 complete in 1087.1 sec
[---------------  41%                  ] 837 of 2000 complete in 1088.5 sec
[---------------  41%                  ] 838 of 2000 complete in 1089.9 sec
[---------------  41%                  ] 839 of 2000 complete in 1091.3 sec
[---------------  42%                  ] 840 of 2000 complete in 1092.7 sec
[---------------  42%                  ] 841 of 2000 complete in 1094.1 sec
[---------------  42%                  ] 842 of 2000 complete in 1095.5 sec
[---------------- 42%                  ] 843 of 2000 complete in 1096.9 sec
[---------------- 42%                  ] 844 of 2000 complete in 1098.3 sec
[---------------- 42%                  ] 845 of 2000 complete in 1099.6 sec
[---------------- 42%                  ] 846 of 2000 complete in 1101.0 sec
[---------------- 42%                  ] 847 of 2000 complete in 1102.3 sec
[---------------- 42%                  ] 848 of 2000 complete in 1103.7 sec
[---------------- 42%                  ] 849 of 2000 complete in 1105.0 sec
[---------------- 42%                  ] 850 of 2000 complete in 1106.5 sec
[---------------- 42%                  ] 851 of 2000 complete in 1107.9 sec
[---------------- 42%                  ] 852 of 2000 complete in 1109.4 sec
[---------------- 42%                  ] 853 of 2000 complete in 1110.7 sec
[---------------- 42%                  ] 854 of 2000 complete in 1112.1 sec
[---------------- 42%                  ] 855 of 2000 complete in 1113.4 sec
[---------------- 42%                  ] 856 of 2000 complete in 1114.7 sec
[---------------- 42%                  ] 857 of 2000 complete in 1116.0 sec
[---------------- 42%                  ] 858 of 2000 complete in 1117.5 sec
[---------------- 42%                  ] 859 of 2000 complete in 1118.9 sec
[---------------- 43%                  ] 860 of 2000 complete in 1120.3 sec
[---------------- 43%                  ] 861 of 2000 complete in 1121.7 sec
[---------------- 43%                  ] 862 of 2000 complete in 1123.1 sec
[---------------- 43%                  ] 863 of 2000 complete in 1124.5 sec
[---------------- 43%                  ] 864 of 2000 complete in 1125.9 sec
[---------------- 43%                  ] 865 of 2000 complete in 1127.3 sec
[---------------- 43%                  ] 866 of 2000 complete in 1128.8 sec
[---------------- 43%                  ] 867 of 2000 complete in 1130.1 sec
[---------------- 43%                  ] 868 of 2000 complete in 1131.6 sec
[---------------- 43%                  ] 869 of 2000 complete in 1133.0 sec
[---------------- 43%                  ] 870 of 2000 complete in 1134.4 sec
[---------------- 43%                  ] 871 of 2000 complete in 1135.8 sec
[---------------- 43%                  ] 872 of 2000 complete in 1137.2 sec
[---------------- 43%                  ] 873 of 2000 complete in 1138.5 sec

[--------------   38%                  ] 767 of 2000 complete in 1010.6 sec
[--------------   38%                  ] 768 of 2000 complete in 1011.9 sec
[--------------   38%                  ] 769 of 2000 complete in 1013.2 sec
[--------------   38%                  ] 770 of 2000 complete in 1014.5 sec
[--------------   38%                  ] 771 of 2000 complete in 1015.8 sec
[--------------   38%                  ] 772 of 2000 complete in 1017.0 sec
[--------------   38%                  ] 773 of 2000 complete in 1018.3 sec
[--------------   38%                  ] 774 of 2000 complete in 1019.6 sec
[--------------   38%                  ] 775 of 2000 complete in 1020.9 sec
[--------------   38%                  ] 776 of 2000 complete in 1022.2 sec
[--------------   38%                  ] 777 of 2000 complete in 1023.4 sec
[--------------   38%                  ] 778 of 2000 complete in 1024.6 sec
[--------------   38%                  ] 779 of 2000 complete in 1025.8 sec
[--------------   39%                  ] 780 of 2000 complete in 1027.0 sec
[--------------   39%                  ] 781 of 2000 complete in 1028.2 sec
[--------------   39%                  ] 782 of 2000 complete in 1029.4 sec
[--------------   39%                  ] 783 of 2000 complete in 1030.6 sec
[--------------   39%                  ] 784 of 2000 complete in 1031.8 sec
[--------------   39%                  ] 785 of 2000 complete in 1033.0 sec
[--------------   39%                  ] 786 of 2000 complete in 1034.3 sec
[--------------   39%                  ] 787 of 2000 complete in 1035.5 sec
[--------------   39%                  ] 788 of 2000 complete in 1036.7 sec
[--------------   39%                  ] 789 of 2000 complete in 1037.9 sec
[---------------  39%                  ] 790 of 2000 complete in 1039.1 sec
[---------------  39%                  ] 791 of 2000 complete in 1040.3 sec
[---------------  39%                  ] 792 of 2000 complete in 1041.6 sec
[---------------  39%                  ] 793 of 2000 complete in 1042.7 sec
[---------------  39%                  ] 794 of 2000 complete in 1043.9 sec
[---------------  39%                  ] 795 of 2000 complete in 1045.2 sec
[---------------  39%                  ] 796 of 2000 complete in 1046.3 sec
[---------------  39%                  ] 797 of 2000 complete in 1047.5 sec
[---------------  39%                  ] 798 of 2000 complete in 1048.8 sec
[---------------  39%                  ] 799 of 2000 complete in 1049.9 sec
[---------------  40%                  ] 800 of 2000 complete in 1051.1 sec
[---------------  40%                  ] 801 of 2000 complete in 1052.3 sec
[---------------  40%                  ] 802 of 2000 complete in 1053.5 sec
[---------------  40%                  ] 803 of 2000 complete in 1054.7 sec
[---------------  40%                  ] 804 of 2000 complete in 1055.9 sec
[---------------  40%                  ] 805 of 2000 complete in 1057.1 sec
[---------------  40%                  ] 806 of 2000 complete in 1058.3 sec
[---------------  40%                  ] 807 of 2000 complete in 1059.5 sec
[---------------  40%                  ] 808 of 2000 complete in 1060.6 sec
[---------------  40%                  ] 809 of 2000 complete in 1061.9 sec
[---------------  40%                  ] 810 of 2000 complete in 1063.1 sec
[---------------  40%                  ] 811 of 2000 complete in 1064.3 sec
[---------------  40%                  ] 812 of 2000 complete in 1065.5 sec
[---------------  40%                  ] 813 of 2000 complete in 1066.8 sec
[---------------  40%                  ] 814 of 2000 complete in 1068.1 sec
[---------------  40%                  ] 815 of 2000 complete in 1069.3 sec
[---------------  40%                  ] 816 of 2000 complete in 1070.5 sec
[---------------  40%                  ] 817 of 2000 complete in 1071.6 sec
[---------------  40%                  ] 818 of 2000 complete in 1072.8 sec
[---------------  40%                  ] 819 of 2000 complete in 1074.1 sec
[---------------  41%                  ] 820 of 2000 complete in 1075.3 sec
[---------------  41%                  ] 821 of 2000 complete in 1076.6 sec
[---------------  41%                  ] 822 of 2000 complete in 1077.7 sec
[---------------  41%                  ] 823 of 2000 complete in 1078.9 sec
[---------------  41%                  ] 824 of 2000 complete in 1080.2 sec
[---------------  41%                  ] 825 of 2000 complete in 1081.4 sec
[---------------  41%                  ] 826 of 2000 complete in 1082.7 sec
[---------------  41%                  ] 827 of 2000 complete in 1083.9 sec
[---------------  41%                  ] 828 of 2000 complete in 1085.2 sec
[---------------  41%                  ] 829 of 2000 complete in 1086.4 sec
[---------------  41%                  ] 830 of 2000 complete in 1087.6 sec
[---------------  41%                  ] 831 of 2000 complete in 1088.9 sec
[---------------  41%                  ] 832 of 2000 complete in 1090.1 sec
[---------------  41%                  ] 833 of 2000 complete in 1091.4 sec
[---------------  41%                  ] 834 of 2000 complete in 1092.7 sec
[---------------  41%                  ] 835 of 2000 complete in 1093.9 sec
[---------------  41%                  ] 836 of 2000 complete in 1095.2 sec
[---------------  41%                  ] 837 of 2000 complete in 1096.4 sec
[---------------  41%                  ] 838 of 2000 complete in 1097.7 sec
[---------------  41%                  ] 839 of 2000 complete in 1099.0 sec
[---------------  42%                  ] 840 of 2000 complete in 1100.2 sec
[---------------  42%                  ] 841 of 2000 complete in 1101.5 sec
[---------------  42%                  ] 842 of 2000 complete in 1102.8 sec
[---------------- 42%                  ] 843 of 2000 complete in 1104.1 sec
[---------------- 42%                  ] 844 of 2000 complete in 1105.5 sec
[---------------- 42%                  ] 845 of 2000 complete in 1106.9 sec
[---------------- 42%                  ] 846 of 2000 complete in 1108.2 sec
[---------------- 42%                  ] 847 of 2000 complete in 1109.6 sec
[---------------- 42%                  ] 848 of 2000 complete in 1110.9 sec
[---------------- 42%                  ] 849 of 2000 complete in 1112.2 sec
[---------------- 42%                  ] 850 of 2000 complete in 1113.5 sec
[---------------- 42%                  ] 851 of 2000 complete in 1114.8 sec
[---------------- 42%                  ] 852 of 2000 complete in 1116.0 sec
[---------------- 42%                  ] 853 of 2000 complete in 1117.3 sec
[---------------- 42%                  ] 854 of 2000 complete in 1118.5 sec
[---------------- 42%                  ] 855 of 2000 complete in 1119.8 sec
[---------------- 42%                  ] 856 of 2000 complete in 1121.1 sec
[---------------- 42%                  ] 857 of 2000 complete in 1122.3 sec
[---------------- 42%                  ] 858 of 2000 complete in 1123.5 sec
[---------------- 42%                  ] 859 of 2000 complete in 1124.8 sec
[---------------- 43%                  ] 860 of 2000 complete in 1126.0 sec
[---------------- 43%                  ] 861 of 2000 complete in 1127.2 sec
[---------------- 43%                  ] 862 of 2000 complete in 1128.5 sec
[---------------- 43%                  ] 863 of 2000 complete in 1129.7 sec
[---------------- 43%                  ] 864 of 2000 complete in 1131.0 sec
[---------------- 43%                  ] 865 of 2000 complete in 1132.3 sec
[---------------- 43%                  ] 866 of 2000 complete in 1133.8 sec
[---------------- 43%                  ] 867 of 2000 complete in 1135.1 sec
[---------------- 43%                  ] 868 of 2000 complete in 1136.4 sec
[---------------- 43%                  ] 869 of 2000 complete in 1137.7 sec
[---------------- 43%                  ] 870 of 2000 complete in 1139.0 sec
[---------------- 43%                  ] 871 of 2000 complete in 1140.3 sec
[---------------- 43%                  ] 872 of 2000 complete in 1141.6 sec
[---------------- 43%                  ] 873 of 2000 complete in 1142.9 sec
[--------------   38%                  ] 766 of 2000 complete in 1043.6 sec
[--------------   38%                  ] 767 of 2000 complete in 1045.0 sec
[--------------   38%                  ] 768 of 2000 complete in 1046.4 sec
[--------------   38%                  ] 769 of 2000 complete in 1047.8 sec
[--------------   38%                  ] 770 of 2000 complete in 1049.2 sec
[--------------   38%                  ] 771 of 2000 complete in 1050.6 sec
[--------------   38%                  ] 772 of 2000 complete in 1052.0 sec
[--------------   38%                  ] 773 of 2000 complete in 1053.4 sec
[--------------   38%                  ] 774 of 2000 complete in 1054.8 sec
[--------------   38%                  ] 775 of 2000 complete in 1056.1 sec
[--------------   38%                  ] 776 of 2000 complete in 1057.5 sec
[--------------   38%                  ] 777 of 2000 complete in 1059.0 sec
[--------------   38%                  ] 778 of 2000 complete in 1060.3 sec
[--------------   38%                  ] 779 of 2000 complete in 1061.7 sec
[--------------   39%                  ] 780 of 2000 complete in 1063.1 sec
[--------------   39%                  ] 781 of 2000 complete in 1064.5 sec
[--------------   39%                  ] 782 of 2000 complete in 1065.9 sec
[--------------   39%                  ] 783 of 2000 complete in 1067.3 sec
[--------------   39%                  ] 784 of 2000 complete in 1068.7 sec
[--------------   39%                  ] 785 of 2000 complete in 1070.2 sec
[--------------   39%                  ] 786 of 2000 complete in 1071.6 sec
[--------------   39%                  ] 787 of 2000 complete in 1073.0 sec
[--------------   39%                  ] 788 of 2000 complete in 1074.4 sec
[--------------   39%                  ] 789 of 2000 complete in 1075.8 sec
[---------------  39%                  ] 790 of 2000 complete in 1077.1 sec
[---------------  39%                  ] 791 of 2000 complete in 1078.6 sec
[---------------  39%                  ] 792 of 2000 complete in 1080.0 sec
[---------------  39%                  ] 793 of 2000 complete in 1081.4 sec
[---------------  39%                  ] 794 of 2000 complete in 1082.9 sec
[---------------  39%                  ] 795 of 2000 complete in 1084.3 sec
[---------------  39%                  ] 796 of 2000 complete in 1085.7 sec
[---------------  39%                  ] 797 of 2000 complete in 1087.1 sec
[---------------  39%                  ] 798 of 2000 complete in 1088.5 sec
[---------------  39%                  ] 799 of 2000 complete in 1090.0 sec
[---------------  40%                  ] 800 of 2000 complete in 1091.3 sec
[---------------  40%                  ] 801 of 2000 complete in 1092.6 sec
[---------------  40%                  ] 802 of 2000 complete in 1093.9 sec
[---------------  40%                  ] 803 of 2000 complete in 1095.3 sec
[---------------  40%                  ] 804 of 2000 complete in 1096.8 sec
[---------------  40%                  ] 805 of 2000 complete in 1098.2 sec
[---------------  40%                  ] 806 of 2000 complete in 1099.6 sec
[---------------  40%                  ] 807 of 2000 complete in 1101.0 sec
[---------------  40%                  ] 808 of 2000 complete in 1102.3 sec
[---------------  40%                  ] 809 of 2000 complete in 1103.7 sec
[---------------  40%                  ] 810 of 2000 complete in 1105.1 sec
[---------------  40%                  ] 811 of 2000 complete in 1106.5 sec
[---------------  40%                  ] 812 of 2000 complete in 1107.9 sec
[---------------  40%                  ] 813 of 2000 complete in 1109.2 sec
[---------------  40%                  ] 814 of 2000 complete in 1110.6 sec
[---------------  40%                  ] 815 of 2000 complete in 1112.0 sec
[---------------  40%                  ] 816 of 2000 complete in 1113.4 sec
[---------------  40%                  ] 817 of 2000 complete in 1114.8 sec
[---------------  40%                  ] 818 of 2000 complete in 1116.2 sec
[---------------  40%                  ] 819 of 2000 complete in 1117.7 sec
[---------------  41%                  ] 820 of 2000 complete in 1119.1 sec
[---------------  41%                  ] 821 of 2000 complete in 1120.5 sec
[---------------  41%                  ] 822 of 2000 complete in 1121.9 sec
[---------------  41%                  ] 823 of 2000 complete in 1123.4 sec
[---------------  41%                  ] 824 of 2000 complete in 1124.8 sec
[---------------  41%                  ] 825 of 2000 complete in 1126.2 sec
[---------------  41%                  ] 826 of 2000 complete in 1127.6 sec
[---------------  41%                  ] 827 of 2000 complete in 1129.1 sec
[---------------  41%                  ] 828 of 2000 complete in 1130.4 sec
[---------------  41%                  ] 829 of 2000 complete in 1131.8 sec
[---------------  41%                  ] 830 of 2000 complete in 1133.3 sec
[---------------  41%                  ] 831 of 2000 complete in 1134.8 sec
[---------------  41%                  ] 832 of 2000 complete in 1136.2 sec
[---------------  41%                  ] 833 of 2000 complete in 1137.6 sec
[---------------  41%                  ] 834 of 2000 complete in 1139.0 sec
[---------------  41%                  ] 835 of 2000 complete in 1140.4 sec
[---------------  41%                  ] 836 of 2000 complete in 1141.8 sec
[---------------  41%                  ] 837 of 2000 complete in 1143.2 sec
[---------------  41%                  ] 838 of 2000 complete in 1144.6 sec
[---------------  41%                  ] 839 of 2000 complete in 1146.1 sec
[---------------  42%                  ] 840 of 2000 complete in 1147.6 sec
[---------------  42%                  ] 841 of 2000 complete in 1148.9 sec
[---------------  42%                  ] 842 of 2000 complete in 1150.4 sec
[---------------- 42%                  ] 843 of 2000 complete in 1151.8 sec
[---------------- 42%                  ] 844 of 2000 complete in 1153.2 sec
[---------------- 42%                  ] 845 of 2000 complete in 1154.7 sec
[---------------- 42%                  ] 846 of 2000 complete in 1156.1 sec
[---------------- 42%                  ] 847 of 2000 complete in 1157.5 sec
[---------------- 42%                  ] 848 of 2000 complete in 1159.0 sec
[---------------- 42%                  ] 849 of 2000 complete in 1160.3 sec
[---------------- 42%                  ] 850 of 2000 complete in 1161.7 sec
[---------------- 42%                  ] 851 of 2000 complete in 1163.0 sec
[---------------- 42%                  ] 852 of 2000 complete in 1164.4 sec
[---------------- 42%                  ] 853 of 2000 complete in 1165.9 sec
[---------------- 42%                  ] 854 of 2000 complete in 1167.3 sec
[---------------- 42%                  ] 855 of 2000 complete in 1168.8 sec
[---------------- 42%                  ] 856 of 2000 complete in 1170.1 sec
[---------------- 42%                  ] 857 of 2000 complete in 1171.5 sec
[---------------- 42%                  ] 858 of 2000 complete in 1172.8 sec
[---------------- 42%                  ] 859 of 2000 complete in 1174.2 sec
[---------------- 43%                  ] 860 of 2000 complete in 1175.6 sec
[---------------- 43%                  ] 861 of 2000 complete in 1177.1 sec
[---------------- 43%                  ] 862 of 2000 complete in 1178.4 sec
[---------------- 43%                  ] 863 of 2000 complete in 1179.8 sec
[---------------- 43%                  ] 864 of 2000 complete in 1181.3 sec
[---------------- 43%                  ] 865 of 2000 complete in 1182.6 sec
[---------------- 43%                  ] 866 of 2000 complete in 1184.0 sec
[---------------- 43%                  ] 867 of 2000 complete in 1185.4 sec
[---------------- 43%                  ] 868 of 2000 complete in 1186.8 sec
[---------------- 43%                  ] 869 of 2000 complete in 1188.2 sec
[---------------- 43%                  ] 870 of 2000 complete in 1189.5 sec
[---------------- 43%                  ] 871 of 2000 complete in 1190.9 sec
[---------------- 43%                  ] 872 of 2000 complete in 1192.3 sec

[---------------- 43%                  ] 874 of 2000 complete in 1128.7 sec
[---------------- 43%                  ] 875 of 2000 complete in 1130.0 sec
[---------------- 43%                  ] 876 of 2000 complete in 1131.4 sec
[---------------- 43%                  ] 877 of 2000 complete in 1132.7 sec
[---------------- 43%                  ] 878 of 2000 complete in 1134.2 sec
[---------------- 43%                  ] 879 of 2000 complete in 1135.5 sec
[---------------- 44%                  ] 880 of 2000 complete in 1136.8 sec
[---------------- 44%                  ] 881 of 2000 complete in 1138.2 sec
[---------------- 44%                  ] 882 of 2000 complete in 1139.6 sec
[---------------- 44%                  ] 883 of 2000 complete in 1140.9 sec
[---------------- 44%                  ] 884 of 2000 complete in 1142.2 sec
[---------------- 44%                  ] 885 of 2000 complete in 1143.5 sec
[---------------- 44%                  ] 886 of 2000 complete in 1144.8 sec
[---------------- 44%                  ] 887 of 2000 complete in 1146.1 sec
[---------------- 44%                  ] 888 of 2000 complete in 1147.4 sec
[---------------- 44%                  ] 889 of 2000 complete in 1148.8 sec
[---------------- 44%                  ] 890 of 2000 complete in 1150.2 sec
[---------------- 44%                  ] 891 of 2000 complete in 1151.6 sec
[---------------- 44%                  ] 892 of 2000 complete in 1153.0 sec
[---------------- 44%                  ] 893 of 2000 complete in 1154.4 sec
[---------------- 44%                  ] 894 of 2000 complete in 1155.7 sec
[-----------------44%                  ] 895 of 2000 complete in 1157.0 sec
[-----------------44%                  ] 896 of 2000 complete in 1158.3 sec
[-----------------44%                  ] 897 of 2000 complete in 1159.7 sec
[-----------------44%                  ] 898 of 2000 complete in 1161.0 sec
[-----------------44%                  ] 899 of 2000 complete in 1162.4 sec
[-----------------45%                  ] 900 of 2000 complete in 1163.7 sec
[-----------------45%                  ] 901 of 2000 complete in 1165.0 sec
[-----------------45%                  ] 902 of 2000 complete in 1166.5 sec
[-----------------45%                  ] 903 of 2000 complete in 1167.9 sec
[-----------------45%                  ] 904 of 2000 complete in 1169.2 sec
[-----------------45%                  ] 905 of 2000 complete in 1170.6 sec
[-----------------45%                  ] 906 of 2000 complete in 1171.9 sec
[-----------------45%                  ] 907 of 2000 complete in 1173.3 sec
[-----------------45%                  ] 908 of 2000 complete in 1174.7 sec
[-----------------45%                  ] 909 of 2000 complete in 1176.1 sec
[-----------------45%                  ] 910 of 2000 complete in 1177.5 sec
[-----------------45%                  ] 911 of 2000 complete in 1178.8 sec
[-----------------45%                  ] 912 of 2000 complete in 1180.3 sec
[-----------------45%                  ] 913 of 2000 complete in 1181.6 sec
[-----------------45%                  ] 914 of 2000 complete in 1183.0 sec
[-----------------45%                  ] 915 of 2000 complete in 1184.4 sec
[-----------------45%                  ] 916 of 2000 complete in 1185.8 sec
[-----------------45%                  ] 917 of 2000 complete in 1187.2 sec
[-----------------45%                  ] 918 of 2000 complete in 1188.6 sec
[-----------------45%                  ] 919 of 2000 complete in 1190.0 sec
[-----------------46%                  ] 920 of 2000 complete in 1191.4 sec
[-----------------46%                  ] 921 of 2000 complete in 1192.7 sec
[-----------------46%                  ] 922 of 2000 complete in 1194.1 sec
[-----------------46%                  ] 923 of 2000 complete in 1195.5 sec
[-----------------46%                  ] 924 of 2000 complete in 1196.9 sec
[-----------------46%                  ] 925 of 2000 complete in 1198.2 sec
[-----------------46%                  ] 926 of 2000 complete in 1199.6 sec
[-----------------46%                  ] 927 of 2000 complete in 1201.0 sec
[-----------------46%                  ] 928 of 2000 complete in 1202.4 sec
[-----------------46%                  ] 929 of 2000 complete in 1203.7 sec
[-----------------46%                  ] 930 of 2000 complete in 1205.1 sec
[-----------------46%                  ] 931 of 2000 complete in 1206.5 sec
[-----------------46%                  ] 932 of 2000 complete in 1207.8 sec
[-----------------46%                  ] 933 of 2000 complete in 1209.2 sec
[-----------------46%                  ] 934 of 2000 complete in 1210.5 sec
[-----------------46%                  ] 935 of 2000 complete in 1211.9 sec
[-----------------46%                  ] 936 of 2000 complete in 1213.3 sec
[-----------------46%                  ] 937 of 2000 complete in 1214.7 sec
[-----------------46%                  ] 938 of 2000 complete in 1216.0 sec
[-----------------46%                  ] 939 of 2000 complete in 1217.4 sec
[-----------------47%                  ] 940 of 2000 complete in 1218.9 sec
[-----------------47%                  ] 941 of 2000 complete in 1220.3 sec
[-----------------47%                  ] 942 of 2000 complete in 1221.7 sec
[-----------------47%                  ] 943 of 2000 complete in 1223.1 sec
[-----------------47%                  ] 944 of 2000 complete in 1224.4 sec
[-----------------47%                  ] 945 of 2000 complete in 1225.9 sec
[-----------------47%                  ] 946 of 2000 complete in 1227.3 sec
[-----------------47%                  ] 947 of 2000 complete in 1228.8 sec
[-----------------47%                  ] 948 of 2000 complete in 1230.2 sec
[-----------------47%                  ] 949 of 2000 complete in 1231.6 sec
[-----------------47%                  ] 950 of 2000 complete in 1232.9 sec
[-----------------47%                  ] 951 of 2000 complete in 1234.3 sec
[-----------------47%                  ] 952 of 2000 complete in 1235.7 sec
[-----------------47%                  ] 953 of 2000 complete in 1237.0 sec
[-----------------47%                  ] 954 of 2000 complete in 1238.4 sec
[-----------------47%                  ] 955 of 2000 complete in 1239.8 sec
[-----------------47%                  ] 956 of 2000 complete in 1241.2 sec
[-----------------47%                  ] 957 of 2000 complete in 1242.6 sec
[-----------------47%                  ] 958 of 2000 complete in 1244.0 sec
[-----------------47%                  ] 959 of 2000 complete in 1245.3 sec
[-----------------48%                  ] 960 of 2000 complete in 1246.7 sec
[-----------------48%                  ] 961 of 2000 complete in 1248.2 sec
[-----------------48%                  ] 962 of 2000 complete in 1249.5 sec
[-----------------48%                  ] 963 of 2000 complete in 1250.9 sec
[-----------------48%                  ] 964 of 2000 complete in 1252.3 sec
[-----------------48%                  ] 965 of 2000 complete in 1253.6 sec
[-----------------48%                  ] 966 of 2000 complete in 1254.9 sec
[-----------------48%                  ] 967 of 2000 complete in 1256.3 sec
[-----------------48%                  ] 968 of 2000 complete in 1257.7 sec
[-----------------48%                  ] 969 of 2000 complete in 1259.1 sec
[-----------------48%                  ] 970 of 2000 complete in 1260.5 sec
[-----------------48%                  ] 971 of 2000 complete in 1262.0 sec
[-----------------48%                  ] 972 of 2000 complete in 1263.3 sec
[-----------------48%                  ] 973 of 2000 complete in 1264.7 sec
[-----------------48%                  ] 974 of 2000 complete in 1266.1 sec
[-----------------48%                  ] 975 of 2000 complete in 1267.4 sec
[-----------------48%                  ] 976 of 2000 complete in 1268.8 sec
[-----------------48%                  ] 977 of 2000 complete in 1270.2 sec
[-----------------48%                  ] 978 of 2000 complete in 1271.6 sec
[-----------------48%                  ] 979 of 2000 complete in 1273.0 sec
[-----------------49%                  ] 980 of 2000 complete in 1274.5 sec
[---------------- 43%                  ] 874 of 2000 complete in 1139.9 sec
[---------------- 43%                  ] 875 of 2000 complete in 1141.3 sec
[---------------- 43%                  ] 876 of 2000 complete in 1142.7 sec
[---------------- 43%                  ] 877 of 2000 complete in 1144.1 sec
[---------------- 43%                  ] 878 of 2000 complete in 1145.5 sec
[---------------- 43%                  ] 879 of 2000 complete in 1146.9 sec
[---------------- 44%                  ] 880 of 2000 complete in 1148.2 sec
[---------------- 44%                  ] 881 of 2000 complete in 1149.7 sec
[---------------- 44%                  ] 882 of 2000 complete in 1151.1 sec
[---------------- 44%                  ] 883 of 2000 complete in 1152.5 sec
[---------------- 44%                  ] 884 of 2000 complete in 1153.9 sec
[---------------- 44%                  ] 885 of 2000 complete in 1155.3 sec
[---------------- 44%                  ] 886 of 2000 complete in 1156.7 sec
[---------------- 44%                  ] 887 of 2000 complete in 1158.1 sec
[---------------- 44%                  ] 888 of 2000 complete in 1159.4 sec
[---------------- 44%                  ] 889 of 2000 complete in 1160.7 sec
[---------------- 44%                  ] 890 of 2000 complete in 1162.2 sec
[---------------- 44%                  ] 891 of 2000 complete in 1163.6 sec
[---------------- 44%                  ] 892 of 2000 complete in 1165.0 sec
[---------------- 44%                  ] 893 of 2000 complete in 1166.4 sec
[---------------- 44%                  ] 894 of 2000 complete in 1167.8 sec
[-----------------44%                  ] 895 of 2000 complete in 1169.2 sec
[-----------------44%                  ] 896 of 2000 complete in 1170.6 sec
[-----------------44%                  ] 897 of 2000 complete in 1171.9 sec
[-----------------44%                  ] 898 of 2000 complete in 1173.3 sec
[-----------------44%                  ] 899 of 2000 complete in 1174.7 sec
[-----------------45%                  ] 900 of 2000 complete in 1176.0 sec
[-----------------45%                  ] 901 of 2000 complete in 1177.4 sec
[-----------------45%                  ] 902 of 2000 complete in 1178.8 sec
[-----------------45%                  ] 903 of 2000 complete in 1180.2 sec
[-----------------45%                  ] 904 of 2000 complete in 1181.5 sec
[-----------------45%                  ] 905 of 2000 complete in 1182.9 sec
[-----------------45%                  ] 906 of 2000 complete in 1184.3 sec
[-----------------45%                  ] 907 of 2000 complete in 1185.7 sec
[-----------------45%                  ] 908 of 2000 complete in 1187.1 sec
[-----------------45%                  ] 909 of 2000 complete in 1188.4 sec
[-----------------45%                  ] 910 of 2000 complete in 1189.9 sec
[-----------------45%                  ] 911 of 2000 complete in 1191.3 sec
[-----------------45%                  ] 912 of 2000 complete in 1192.7 sec
[-----------------45%                  ] 913 of 2000 complete in 1194.0 sec
[-----------------45%                  ] 914 of 2000 complete in 1195.4 sec
[-----------------45%                  ] 915 of 2000 complete in 1196.7 sec
[-----------------45%                  ] 916 of 2000 complete in 1198.1 sec
[-----------------45%                  ] 917 of 2000 complete in 1199.6 sec
[-----------------45%                  ] 918 of 2000 complete in 1201.0 sec
[-----------------45%                  ] 919 of 2000 complete in 1202.4 sec
[-----------------46%                  ] 920 of 2000 complete in 1203.7 sec
[-----------------46%                  ] 921 of 2000 complete in 1205.1 sec
[-----------------46%                  ] 922 of 2000 complete in 1206.5 sec
[-----------------46%                  ] 923 of 2000 complete in 1207.8 sec
[-----------------46%                  ] 924 of 2000 complete in 1209.2 sec
[-----------------46%                  ] 925 of 2000 complete in 1210.6 sec
[-----------------46%                  ] 926 of 2000 complete in 1212.0 sec
[-----------------46%                  ] 927 of 2000 complete in 1213.4 sec
[-----------------46%                  ] 928 of 2000 complete in 1214.9 sec
[-----------------46%                  ] 929 of 2000 complete in 1216.2 sec
[-----------------46%                  ] 930 of 2000 complete in 1217.6 sec
[-----------------46%                  ] 931 of 2000 complete in 1218.9 sec
[-----------------46%                  ] 932 of 2000 complete in 1220.3 sec
[-----------------46%                  ] 933 of 2000 complete in 1221.6 sec
[-----------------46%                  ] 934 of 2000 complete in 1223.0 sec
[-----------------46%                  ] 935 of 2000 complete in 1224.3 sec
[-----------------46%                  ] 936 of 2000 complete in 1225.7 sec
[-----------------46%                  ] 937 of 2000 complete in 1227.1 sec
[-----------------46%                  ] 938 of 2000 complete in 1228.5 sec
[-----------------46%                  ] 939 of 2000 complete in 1229.9 sec
[-----------------47%                  ] 940 of 2000 complete in 1231.3 sec
[-----------------47%                  ] 941 of 2000 complete in 1232.6 sec
[-----------------47%                  ] 942 of 2000 complete in 1233.9 sec
[-----------------47%                  ] 943 of 2000 complete in 1235.3 sec
[-----------------47%                  ] 944 of 2000 complete in 1236.6 sec
[-----------------47%                  ] 945 of 2000 complete in 1237.9 sec
[-----------------47%                  ] 946 of 2000 complete in 1239.3 sec
[-----------------47%                  ] 947 of 2000 complete in 1240.6 sec
[-----------------47%                  ] 948 of 2000 complete in 1242.1 sec
[-----------------47%                  ] 949 of 2000 complete in 1243.5 sec
[-----------------47%                  ] 950 of 2000 complete in 1244.9 sec
[-----------------47%                  ] 951 of 2000 complete in 1246.3 sec
[-----------------47%                  ] 952 of 2000 complete in 1247.7 sec
[-----------------47%                  ] 953 of 2000 complete in 1249.1 sec
[-----------------47%                  ] 954 of 2000 complete in 1250.5 sec
[-----------------47%                  ] 955 of 2000 complete in 1251.8 sec
[-----------------47%                  ] 956 of 2000 complete in 1253.2 sec
[-----------------47%                  ] 957 of 2000 complete in 1254.6 sec
[-----------------47%                  ] 958 of 2000 complete in 1256.0 sec
[-----------------47%                  ] 959 of 2000 complete in 1257.3 sec
[-----------------48%                  ] 960 of 2000 complete in 1258.8 sec
[-----------------48%                  ] 961 of 2000 complete in 1260.2 sec
[-----------------48%                  ] 962 of 2000 complete in 1261.5 sec
[-----------------48%                  ] 963 of 2000 complete in 1262.9 sec
[-----------------48%                  ] 964 of 2000 complete in 1264.1 sec
[-----------------48%                  ] 965 of 2000 complete in 1265.5 sec
[-----------------48%                  ] 966 of 2000 complete in 1266.8 sec
[-----------------48%                  ] 967 of 2000 complete in 1268.1 sec
[-----------------48%                  ] 968 of 2000 complete in 1269.4 sec
[-----------------48%                  ] 969 of 2000 complete in 1270.8 sec
[-----------------48%                  ] 970 of 2000 complete in 1272.1 sec
[-----------------48%                  ] 971 of 2000 complete in 1273.4 sec
[-----------------48%                  ] 972 of 2000 complete in 1274.7 sec
[-----------------48%                  ] 973 of 2000 complete in 1276.2 sec
[-----------------48%                  ] 974 of 2000 complete in 1277.5 sec
[-----------------48%                  ] 975 of 2000 complete in 1278.9 sec
[-----------------48%                  ] 976 of 2000 complete in 1280.2 sec
[-----------------48%                  ] 977 of 2000 complete in 1281.5 sec
[-----------------48%                  ] 978 of 2000 complete in 1282.9 sec
[-----------------48%                  ] 979 of 2000 complete in 1284.2 sec
[-----------------49%                  ] 980 of 2000 complete in 1285.4 sec

[---------------- 43%                  ] 874 of 2000 complete in 1144.3 sec
[---------------- 43%                  ] 875 of 2000 complete in 1145.5 sec
[---------------- 43%                  ] 876 of 2000 complete in 1146.8 sec
[---------------- 43%                  ] 877 of 2000 complete in 1148.1 sec
[---------------- 43%                  ] 878 of 2000 complete in 1149.5 sec
[---------------- 43%                  ] 879 of 2000 complete in 1150.8 sec
[---------------- 44%                  ] 880 of 2000 complete in 1152.1 sec
[---------------- 44%                  ] 881 of 2000 complete in 1153.4 sec
[---------------- 44%                  ] 882 of 2000 complete in 1154.8 sec
[---------------- 44%                  ] 883 of 2000 complete in 1156.1 sec
[---------------- 44%                  ] 884 of 2000 complete in 1157.4 sec
[---------------- 44%                  ] 885 of 2000 complete in 1158.7 sec
[---------------- 44%                  ] 886 of 2000 complete in 1160.0 sec
[---------------- 44%                  ] 887 of 2000 complete in 1161.4 sec
[---------------- 44%                  ] 888 of 2000 complete in 1162.7 sec
[---------------- 44%                  ] 889 of 2000 complete in 1164.1 sec
[---------------- 44%                  ] 890 of 2000 complete in 1165.4 sec
[---------------- 44%                  ] 891 of 2000 complete in 1166.8 sec
[---------------- 44%                  ] 892 of 2000 complete in 1168.1 sec
[---------------- 44%                  ] 893 of 2000 complete in 1169.4 sec
[---------------- 44%                  ] 894 of 2000 complete in 1170.8 sec
[-----------------44%                  ] 895 of 2000 complete in 1172.2 sec
[-----------------44%                  ] 896 of 2000 complete in 1173.5 sec
[-----------------44%                  ] 897 of 2000 complete in 1174.8 sec
[-----------------44%                  ] 898 of 2000 complete in 1176.2 sec
[-----------------44%                  ] 899 of 2000 complete in 1177.6 sec
[-----------------45%                  ] 900 of 2000 complete in 1178.9 sec
[-----------------45%                  ] 901 of 2000 complete in 1180.2 sec
[-----------------45%                  ] 902 of 2000 complete in 1181.6 sec
[-----------------45%                  ] 903 of 2000 complete in 1182.9 sec
[-----------------45%                  ] 904 of 2000 complete in 1184.3 sec
[-----------------45%                  ] 905 of 2000 complete in 1185.6 sec
[-----------------45%                  ] 906 of 2000 complete in 1186.9 sec
[-----------------45%                  ] 907 of 2000 complete in 1188.2 sec
[-----------------45%                  ] 908 of 2000 complete in 1189.6 sec
[-----------------45%                  ] 909 of 2000 complete in 1191.0 sec
[-----------------45%                  ] 910 of 2000 complete in 1192.3 sec
[-----------------45%                  ] 911 of 2000 complete in 1193.6 sec
[-----------------45%                  ] 912 of 2000 complete in 1194.9 sec
[-----------------45%                  ] 913 of 2000 complete in 1196.3 sec
[-----------------45%                  ] 914 of 2000 complete in 1197.6 sec
[-----------------45%                  ] 915 of 2000 complete in 1198.9 sec
[-----------------45%                  ] 916 of 2000 complete in 1200.3 sec
[-----------------45%                  ] 917 of 2000 complete in 1201.6 sec
[-----------------45%                  ] 918 of 2000 complete in 1202.9 sec
[-----------------45%                  ] 919 of 2000 complete in 1204.2 sec
[-----------------46%                  ] 920 of 2000 complete in 1205.6 sec
[-----------------46%                  ] 921 of 2000 complete in 1207.0 sec
[-----------------46%                  ] 922 of 2000 complete in 1208.3 sec
[-----------------46%                  ] 923 of 2000 complete in 1209.6 sec
[-----------------46%                  ] 924 of 2000 complete in 1211.0 sec
[-----------------46%                  ] 925 of 2000 complete in 1212.4 sec
[-----------------46%                  ] 926 of 2000 complete in 1213.8 sec
[-----------------46%                  ] 927 of 2000 complete in 1215.2 sec
[-----------------46%                  ] 928 of 2000 complete in 1216.7 sec
[-----------------46%                  ] 929 of 2000 complete in 1218.1 sec
[-----------------46%                  ] 930 of 2000 complete in 1219.4 sec
[-----------------46%                  ] 931 of 2000 complete in 1220.8 sec
[-----------------46%                  ] 932 of 2000 complete in 1222.1 sec
[-----------------46%                  ] 933 of 2000 complete in 1223.4 sec
[-----------------46%                  ] 934 of 2000 complete in 1224.9 sec
[-----------------46%                  ] 935 of 2000 complete in 1226.2 sec
[-----------------46%                  ] 936 of 2000 complete in 1227.6 sec
[-----------------46%                  ] 937 of 2000 complete in 1229.0 sec
[-----------------46%                  ] 938 of 2000 complete in 1230.4 sec
[-----------------46%                  ] 939 of 2000 complete in 1231.8 sec
[-----------------47%                  ] 940 of 2000 complete in 1233.1 sec
[-----------------47%                  ] 941 of 2000 complete in 1234.4 sec
[-----------------47%                  ] 942 of 2000 complete in 1235.8 sec
[-----------------47%                  ] 943 of 2000 complete in 1237.1 sec
[-----------------47%                  ] 944 of 2000 complete in 1238.5 sec
[-----------------47%                  ] 945 of 2000 complete in 1239.8 sec
[-----------------47%                  ] 946 of 2000 complete in 1241.1 sec
[-----------------47%                  ] 947 of 2000 complete in 1242.5 sec
[-----------------47%                  ] 948 of 2000 complete in 1243.8 sec
[-----------------47%                  ] 949 of 2000 complete in 1245.2 sec
[-----------------47%                  ] 950 of 2000 complete in 1246.5 sec
[-----------------47%                  ] 951 of 2000 complete in 1247.9 sec
[-----------------47%                  ] 952 of 2000 complete in 1249.3 sec
[-----------------47%                  ] 953 of 2000 complete in 1250.7 sec
[-----------------47%                  ] 954 of 2000 complete in 1252.1 sec
[-----------------47%                  ] 955 of 2000 complete in 1253.5 sec
[-----------------47%                  ] 956 of 2000 complete in 1254.9 sec
[-----------------47%                  ] 957 of 2000 complete in 1256.2 sec
[-----------------47%                  ] 958 of 2000 complete in 1257.6 sec
[-----------------47%                  ] 959 of 2000 complete in 1259.0 sec
[-----------------48%                  ] 960 of 2000 complete in 1260.4 sec
[-----------------48%                  ] 961 of 2000 complete in 1261.8 sec
[-----------------48%                  ] 962 of 2000 complete in 1263.1 sec
[-----------------48%                  ] 963 of 2000 complete in 1264.5 sec
[-----------------48%                  ] 964 of 2000 complete in 1265.9 sec
[-----------------48%                  ] 965 of 2000 complete in 1267.3 sec
[-----------------48%                  ] 966 of 2000 complete in 1268.6 sec
[-----------------48%                  ] 967 of 2000 complete in 1270.0 sec
[-----------------48%                  ] 968 of 2000 complete in 1271.4 sec
[-----------------48%                  ] 969 of 2000 complete in 1272.8 sec
[-----------------48%                  ] 970 of 2000 complete in 1274.2 sec
[-----------------48%                  ] 971 of 2000 complete in 1275.6 sec
[-----------------48%                  ] 972 of 2000 complete in 1277.0 sec
[-----------------48%                  ] 973 of 2000 complete in 1278.3 sec
[-----------------48%                  ] 974 of 2000 complete in 1279.7 sec
[-----------------48%                  ] 975 of 2000 complete in 1281.1 sec
[-----------------48%                  ] 976 of 2000 complete in 1282.5 sec
[-----------------48%                  ] 977 of 2000 complete in 1283.8 sec
[-----------------48%                  ] 978 of 2000 complete in 1285.2 sec
[-----------------48%                  ] 979 of 2000 complete in 1286.5 sec
[-----------------49%                  ] 980 of 2000 complete in 1288.0 sec
[---------------- 43%                  ] 873 of 2000 complete in 1193.7 sec
[---------------- 43%                  ] 874 of 2000 complete in 1195.1 sec
[---------------- 43%                  ] 875 of 2000 complete in 1196.6 sec
[---------------- 43%                  ] 876 of 2000 complete in 1197.9 sec
[---------------- 43%                  ] 877 of 2000 complete in 1199.3 sec
[---------------- 43%                  ] 878 of 2000 complete in 1200.7 sec
[---------------- 43%                  ] 879 of 2000 complete in 1202.1 sec
[---------------- 44%                  ] 880 of 2000 complete in 1203.5 sec
[---------------- 44%                  ] 881 of 2000 complete in 1204.9 sec
[---------------- 44%                  ] 882 of 2000 complete in 1206.3 sec
[---------------- 44%                  ] 883 of 2000 complete in 1207.6 sec
[---------------- 44%                  ] 884 of 2000 complete in 1208.9 sec
[---------------- 44%                  ] 885 of 2000 complete in 1210.2 sec
[---------------- 44%                  ] 886 of 2000 complete in 1211.5 sec
[---------------- 44%                  ] 887 of 2000 complete in 1213.0 sec
[---------------- 44%                  ] 888 of 2000 complete in 1214.4 sec
[---------------- 44%                  ] 889 of 2000 complete in 1215.8 sec
[---------------- 44%                  ] 890 of 2000 complete in 1217.2 sec
[---------------- 44%                  ] 891 of 2000 complete in 1218.6 sec
[---------------- 44%                  ] 892 of 2000 complete in 1219.9 sec
[---------------- 44%                  ] 893 of 2000 complete in 1221.3 sec
[---------------- 44%                  ] 894 of 2000 complete in 1222.6 sec
[-----------------44%                  ] 895 of 2000 complete in 1224.0 sec
[-----------------44%                  ] 896 of 2000 complete in 1225.5 sec
[-----------------44%                  ] 897 of 2000 complete in 1226.9 sec
[-----------------44%                  ] 898 of 2000 complete in 1228.3 sec
[-----------------44%                  ] 899 of 2000 complete in 1229.7 sec
[-----------------45%                  ] 900 of 2000 complete in 1231.1 sec
[-----------------45%                  ] 901 of 2000 complete in 1232.5 sec
[-----------------45%                  ] 902 of 2000 complete in 1233.8 sec
[-----------------45%                  ] 903 of 2000 complete in 1235.2 sec
[-----------------45%                  ] 904 of 2000 complete in 1236.6 sec
[-----------------45%                  ] 905 of 2000 complete in 1238.1 sec
[-----------------45%                  ] 906 of 2000 complete in 1239.5 sec
[-----------------45%                  ] 907 of 2000 complete in 1240.9 sec
[-----------------45%                  ] 908 of 2000 complete in 1242.3 sec
[-----------------45%                  ] 909 of 2000 complete in 1243.7 sec
[-----------------45%                  ] 910 of 2000 complete in 1245.2 sec
[-----------------45%                  ] 911 of 2000 complete in 1246.7 sec
[-----------------45%                  ] 912 of 2000 complete in 1248.1 sec
[-----------------45%                  ] 913 of 2000 complete in 1249.5 sec
[-----------------45%                  ] 914 of 2000 complete in 1250.9 sec
[-----------------45%                  ] 915 of 2000 complete in 1252.2 sec
[-----------------45%                  ] 916 of 2000 complete in 1253.6 sec
[-----------------45%                  ] 917 of 2000 complete in 1255.0 sec
[-----------------45%                  ] 918 of 2000 complete in 1256.4 sec
[-----------------45%                  ] 919 of 2000 complete in 1257.8 sec
[-----------------46%                  ] 920 of 2000 complete in 1259.2 sec
[-----------------46%                  ] 921 of 2000 complete in 1260.5 sec
[-----------------46%                  ] 922 of 2000 complete in 1261.9 sec
[-----------------46%                  ] 923 of 2000 complete in 1263.3 sec
[-----------------46%                  ] 924 of 2000 complete in 1264.8 sec
[-----------------46%                  ] 925 of 2000 complete in 1266.2 sec
[-----------------46%                  ] 926 of 2000 complete in 1267.7 sec
[-----------------46%                  ] 927 of 2000 complete in 1269.1 sec
[-----------------46%                  ] 928 of 2000 complete in 1270.4 sec
[-----------------46%                  ] 929 of 2000 complete in 1271.9 sec
[-----------------46%                  ] 930 of 2000 complete in 1273.2 sec
[-----------------46%                  ] 931 of 2000 complete in 1274.6 sec
[-----------------46%                  ] 932 of 2000 complete in 1276.0 sec
[-----------------46%                  ] 933 of 2000 complete in 1277.5 sec
[-----------------46%                  ] 934 of 2000 complete in 1278.9 sec
[-----------------46%                  ] 935 of 2000 complete in 1280.3 sec
[-----------------46%                  ] 936 of 2000 complete in 1281.7 sec
[-----------------46%                  ] 937 of 2000 complete in 1283.1 sec
[-----------------46%                  ] 938 of 2000 complete in 1284.5 sec
[-----------------46%                  ] 939 of 2000 complete in 1285.8 sec
[-----------------47%                  ] 940 of 2000 complete in 1287.2 sec
[-----------------47%                  ] 941 of 2000 complete in 1288.6 sec
[-----------------47%                  ] 942 of 2000 complete in 1290.0 sec
[-----------------47%                  ] 943 of 2000 complete in 1291.3 sec
[-----------------47%                  ] 944 of 2000 complete in 1292.8 sec
[-----------------47%                  ] 945 of 2000 complete in 1294.1 sec
[-----------------47%                  ] 946 of 2000 complete in 1295.5 sec
[-----------------47%                  ] 947 of 2000 complete in 1296.9 sec
[-----------------47%                  ] 948 of 2000 complete in 1298.2 sec
[-----------------47%                  ] 949 of 2000 complete in 1299.7 sec
[-----------------47%                  ] 950 of 2000 complete in 1301.0 sec
[-----------------47%                  ] 951 of 2000 complete in 1302.3 sec
[-----------------47%                  ] 952 of 2000 complete in 1303.7 sec
[-----------------47%                  ] 953 of 2000 complete in 1305.0 sec
[-----------------47%                  ] 954 of 2000 complete in 1306.3 sec
[-----------------47%                  ] 955 of 2000 complete in 1307.6 sec
[-----------------47%                  ] 956 of 2000 complete in 1309.0 sec
[-----------------47%                  ] 957 of 2000 complete in 1310.4 sec
[-----------------47%                  ] 958 of 2000 complete in 1311.8 sec
[-----------------47%                  ] 959 of 2000 complete in 1313.2 sec
[-----------------48%                  ] 960 of 2000 complete in 1314.5 sec
[-----------------48%                  ] 961 of 2000 complete in 1315.9 sec
[-----------------48%                  ] 962 of 2000 complete in 1317.2 sec
[-----------------48%                  ] 963 of 2000 complete in 1318.5 sec
[-----------------48%                  ] 964 of 2000 complete in 1319.9 sec
[-----------------48%                  ] 965 of 2000 complete in 1321.3 sec
[-----------------48%                  ] 966 of 2000 complete in 1322.7 sec
[-----------------48%                  ] 967 of 2000 complete in 1324.0 sec
[-----------------48%                  ] 968 of 2000 complete in 1325.4 sec
[-----------------48%                  ] 969 of 2000 complete in 1326.7 sec
[-----------------48%                  ] 970 of 2000 complete in 1328.0 sec
[-----------------48%                  ] 971 of 2000 complete in 1329.4 sec
[-----------------48%                  ] 972 of 2000 complete in 1330.8 sec
[-----------------48%                  ] 973 of 2000 complete in 1332.1 sec
[-----------------48%                  ] 974 of 2000 complete in 1333.4 sec
[-----------------48%                  ] 975 of 2000 complete in 1334.7 sec
[-----------------48%                  ] 976 of 2000 complete in 1336.0 sec
[-----------------48%                  ] 977 of 2000 complete in 1337.3 sec
[-----------------48%                  ] 978 of 2000 complete in 1338.8 sec
[-----------------48%                  ] 979 of 2000 complete in 1340.1 sec

[-----------------49%                  ] 981 of 2000 complete in 1275.9 sec
[-----------------49%                  ] 982 of 2000 complete in 1277.3 sec
[-----------------49%                  ] 983 of 2000 complete in 1278.8 sec
[-----------------49%                  ] 984 of 2000 complete in 1280.2 sec
[-----------------49%                  ] 985 of 2000 complete in 1281.6 sec
[-----------------49%                  ] 986 of 2000 complete in 1283.0 sec
[-----------------49%                  ] 987 of 2000 complete in 1284.3 sec
[-----------------49%                  ] 988 of 2000 complete in 1285.7 sec
[-----------------49%                  ] 989 of 2000 complete in 1287.1 sec
[-----------------49%                  ] 990 of 2000 complete in 1288.6 sec
[-----------------49%                  ] 991 of 2000 complete in 1289.9 sec
[-----------------49%                  ] 992 of 2000 complete in 1291.3 sec
[-----------------49%                  ] 993 of 2000 complete in 1292.7 sec
[-----------------49%                  ] 994 of 2000 complete in 1294.1 sec
[-----------------49%                  ] 995 of 2000 complete in 1295.4 sec
[-----------------49%                  ] 996 of 2000 complete in 1296.8 sec
[-----------------49%                  ] 997 of 2000 complete in 1298.3 sec
[-----------------49%                  ] 998 of 2000 complete in 1299.7 sec
[-----------------49%                  ] 999 of 2000 complete in 1301.0 sec
[-----------------50%                  ] 1000 of 2000 complete in 1302.4 sec
[-----------------50%                  ] 1001 of 2000 complete in 1303.8 sec
[-----------------50%                  ] 1002 of 2000 complete in 1305.2 sec
[-----------------50%                  ] 1003 of 2000 complete in 1306.6 sec
[-----------------50%                  ] 1004 of 2000 complete in 1308.0 sec
[-----------------50%                  ] 1005 of 2000 complete in 1309.3 sec
[-----------------50%                  ] 1006 of 2000 complete in 1310.7 sec
[-----------------50%                  ] 1007 of 2000 complete in 1312.1 sec
[-----------------50%                  ] 1008 of 2000 complete in 1313.5 sec
[-----------------50%                  ] 1009 of 2000 complete in 1314.8 sec
[-----------------50%                  ] 1010 of 2000 complete in 1316.2 sec
[-----------------50%                  ] 1011 of 2000 complete in 1317.6 sec
[-----------------50%                  ] 1012 of 2000 complete in 1319.0 sec
[-----------------50%                  ] 1013 of 2000 complete in 1320.4 sec
[-----------------50%                  ] 1014 of 2000 complete in 1321.7 sec
[-----------------50%                  ] 1015 of 2000 complete in 1323.1 sec
[-----------------50%                  ] 1016 of 2000 complete in 1324.4 sec
[-----------------50%                  ] 1017 of 2000 complete in 1325.7 sec
[-----------------50%                  ] 1018 of 2000 complete in 1327.0 sec
[-----------------50%                  ] 1019 of 2000 complete in 1328.4 sec
[-----------------51%                  ] 1020 of 2000 complete in 1329.6 sec
[-----------------51%                  ] 1021 of 2000 complete in 1331.0 sec
[-----------------51%                  ] 1022 of 2000 complete in 1332.3 sec
[-----------------51%                  ] 1023 of 2000 complete in 1333.7 sec
[-----------------51%                  ] 1024 of 2000 complete in 1335.0 sec
[-----------------51%                  ] 1025 of 2000 complete in 1336.3 sec
[-----------------51%                  ] 1026 of 2000 complete in 1337.6 sec
[-----------------51%                  ] 1027 of 2000 complete in 1339.0 sec
[-----------------51%                  ] 1028 of 2000 complete in 1340.3 sec
[-----------------51%                  ] 1029 of 2000 complete in 1341.9 sec
[-----------------51%                  ] 1030 of 2000 complete in 1343.4 sec
[-----------------51%                  ] 1031 of 2000 complete in 1344.8 sec
[-----------------51%                  ] 1032 of 2000 complete in 1346.2 sec
[-----------------51%                  ] 1033 of 2000 complete in 1347.6 sec
[-----------------51%                  ] 1034 of 2000 complete in 1349.0 sec
[-----------------51%                  ] 1035 of 2000 complete in 1350.3 sec
[-----------------51%                  ] 1036 of 2000 complete in 1351.7 sec
[-----------------51%                  ] 1037 of 2000 complete in 1353.1 sec
[-----------------51%                  ] 1038 of 2000 complete in 1354.4 sec
[-----------------51%                  ] 1039 of 2000 complete in 1355.7 sec
[-----------------52%                  ] 1040 of 2000 complete in 1357.1 sec
[-----------------52%                  ] 1041 of 2000 complete in 1358.4 sec
[-----------------52%                  ] 1042 of 2000 complete in 1359.7 sec
[-----------------52%                  ] 1043 of 2000 complete in 1361.1 sec
[-----------------52%                  ] 1044 of 2000 complete in 1362.3 sec
[-----------------52%                  ] 1045 of 2000 complete in 1363.7 sec
[-----------------52%                  ] 1046 of 2000 complete in 1365.1 sec
[-----------------52%                  ] 1047 of 2000 complete in 1366.4 sec
[-----------------52%                  ] 1048 of 2000 complete in 1367.8 sec
[-----------------52%                  ] 1049 of 2000 complete in 1369.2 sec
[-----------------52%                  ] 1050 of 2000 complete in 1370.6 sec
[-----------------52%                  ] 1051 of 2000 complete in 1371.9 sec
[-----------------52%                  ] 1052 of 2000 complete in 1373.2 sec
[-----------------52%                  ] 1053 of 2000 complete in 1374.6 sec
[-----------------52%                  ] 1054 of 2000 complete in 1376.0 sec
[-----------------52%                  ] 1055 of 2000 complete in 1377.4 sec
[-----------------52%                  ] 1056 of 2000 complete in 1378.8 sec
[-----------------52%                  ] 1057 of 2000 complete in 1380.2 sec
[-----------------52%                  ] 1058 of 2000 complete in 1381.5 sec
[-----------------52%                  ] 1059 of 2000 complete in 1382.9 sec
[-----------------53%                  ] 1060 of 2000 complete in 1384.3 sec
[-----------------53%                  ] 1061 of 2000 complete in 1385.6 sec
[-----------------53%                  ] 1062 of 2000 complete in 1387.0 sec
[-----------------53%                  ] 1063 of 2000 complete in 1388.4 sec
[-----------------53%                  ] 1064 of 2000 complete in 1389.8 sec
[-----------------53%                  ] 1065 of 2000 complete in 1391.2 sec
[-----------------53%                  ] 1066 of 2000 complete in 1392.6 sec
[-----------------53%                  ] 1067 of 2000 complete in 1394.0 sec
[-----------------53%                  ] 1068 of 2000 complete in 1395.3 sec
[-----------------53%                  ] 1069 of 2000 complete in 1396.6 sec
[-----------------53%                  ] 1070 of 2000 complete in 1398.0 sec
[-----------------53%                  ] 1071 of 2000 complete in 1399.3 sec
[-----------------53%                  ] 1072 of 2000 complete in 1400.6 sec
[-----------------53%                  ] 1073 of 2000 complete in 1401.9 sec
[-----------------53%                  ] 1074 of 2000 complete in 1403.3 sec
[-----------------53%                  ] 1075 of 2000 complete in 1404.7 sec
[-----------------53%                  ] 1076 of 2000 complete in 1406.1 sec
[-----------------53%                  ] 1077 of 2000 complete in 1407.5 sec
[-----------------53%                  ] 1078 of 2000 complete in 1408.9 sec
[-----------------53%                  ] 1079 of 2000 complete in 1410.3 sec
[-----------------54%                  ] 1080 of 2000 complete in 1411.7 sec
[-----------------54%                  ] 1081 of 2000 complete in 1413.0 sec
[-----------------54%                  ] 1082 of 2000 complete in 1414.3 sec
[-----------------54%                  ] 1083 of 2000 complete in 1415.8 sec
[-----------------54%                  ] 1084 of 2000 complete in 1417.1 sec
[-----------------54%                  ] 1085 of 2000 complete in 1418.5 sec
[-----------------54%                  ] 1086 of 2000 complete in 1419.9 sec
[-----------------49%                  ] 981 of 2000 complete in 1286.8 sec
[-----------------49%                  ] 982 of 2000 complete in 1288.2 sec
[-----------------49%                  ] 983 of 2000 complete in 1289.5 sec
[-----------------49%                  ] 984 of 2000 complete in 1290.7 sec
[-----------------49%                  ] 985 of 2000 complete in 1292.0 sec
[-----------------49%                  ] 986 of 2000 complete in 1293.3 sec
[-----------------49%                  ] 987 of 2000 complete in 1294.5 sec
[-----------------49%                  ] 988 of 2000 complete in 1295.8 sec
[-----------------49%                  ] 989 of 2000 complete in 1297.0 sec
[-----------------49%                  ] 990 of 2000 complete in 1298.3 sec
[-----------------49%                  ] 991 of 2000 complete in 1299.6 sec
[-----------------49%                  ] 992 of 2000 complete in 1300.8 sec
[-----------------49%                  ] 993 of 2000 complete in 1302.1 sec
[-----------------49%                  ] 994 of 2000 complete in 1303.4 sec
[-----------------49%                  ] 995 of 2000 complete in 1304.7 sec
[-----------------49%                  ] 996 of 2000 complete in 1306.0 sec
[-----------------49%                  ] 997 of 2000 complete in 1307.2 sec
[-----------------49%                  ] 998 of 2000 complete in 1308.5 sec
[-----------------49%                  ] 999 of 2000 complete in 1309.6 sec
[-----------------50%                  ] 1000 of 2000 complete in 1310.9 sec
[-----------------50%                  ] 1001 of 2000 complete in 1312.1 sec
[-----------------50%                  ] 1002 of 2000 complete in 1313.3 sec
[-----------------50%                  ] 1003 of 2000 complete in 1314.6 sec
[-----------------50%                  ] 1004 of 2000 complete in 1315.9 sec
[-----------------50%                  ] 1005 of 2000 complete in 1317.2 sec
[-----------------50%                  ] 1006 of 2000 complete in 1318.5 sec
[-----------------50%                  ] 1007 of 2000 complete in 1319.8 sec
[-----------------50%                  ] 1008 of 2000 complete in 1321.1 sec
[-----------------50%                  ] 1009 of 2000 complete in 1322.4 sec
[-----------------50%                  ] 1010 of 2000 complete in 1323.7 sec
[-----------------50%                  ] 1011 of 2000 complete in 1325.0 sec
[-----------------50%                  ] 1012 of 2000 complete in 1326.3 sec
[-----------------50%                  ] 1013 of 2000 complete in 1327.6 sec
[-----------------50%                  ] 1014 of 2000 complete in 1328.9 sec
[-----------------50%                  ] 1015 of 2000 complete in 1330.2 sec
[-----------------50%                  ] 1016 of 2000 complete in 1331.5 sec
[-----------------50%                  ] 1017 of 2000 complete in 1332.8 sec
[-----------------50%                  ] 1018 of 2000 complete in 1334.1 sec
[-----------------50%                  ] 1019 of 2000 complete in 1335.4 sec
[-----------------51%                  ] 1020 of 2000 complete in 1336.7 sec
[-----------------51%                  ] 1021 of 2000 complete in 1338.0 sec
[-----------------51%                  ] 1022 of 2000 complete in 1339.3 sec
[-----------------51%                  ] 1023 of 2000 complete in 1340.6 sec
[-----------------51%                  ] 1024 of 2000 complete in 1341.9 sec
[-----------------51%                  ] 1025 of 2000 complete in 1343.2 sec
[-----------------51%                  ] 1026 of 2000 complete in 1344.6 sec
[-----------------51%                  ] 1027 of 2000 complete in 1345.8 sec
[-----------------51%                  ] 1028 of 2000 complete in 1347.1 sec
[-----------------51%                  ] 1029 of 2000 complete in 1348.4 sec
[-----------------51%                  ] 1030 of 2000 complete in 1349.7 sec
[-----------------51%                  ] 1031 of 2000 complete in 1351.0 sec
[-----------------51%                  ] 1032 of 2000 complete in 1352.3 sec
[-----------------51%                  ] 1033 of 2000 complete in 1353.7 sec
[-----------------51%                  ] 1034 of 2000 complete in 1355.1 sec
[-----------------51%                  ] 1035 of 2000 complete in 1356.5 sec
[-----------------51%                  ] 1036 of 2000 complete in 1357.9 sec
[-----------------51%                  ] 1037 of 2000 complete in 1359.3 sec
[-----------------51%                  ] 1038 of 2000 complete in 1360.6 sec
[-----------------51%                  ] 1039 of 2000 complete in 1361.9 sec
[-----------------52%                  ] 1040 of 2000 complete in 1363.3 sec
[-----------------52%                  ] 1041 of 2000 complete in 1364.6 sec
[-----------------52%                  ] 1042 of 2000 complete in 1366.0 sec
[-----------------52%                  ] 1043 of 2000 complete in 1367.3 sec
[-----------------52%                  ] 1044 of 2000 complete in 1368.6 sec
[-----------------52%                  ] 1045 of 2000 complete in 1370.0 sec
[-----------------52%                  ] 1046 of 2000 complete in 1371.3 sec
[-----------------52%                  ] 1047 of 2000 complete in 1372.7 sec
[-----------------52%                  ] 1048 of 2000 complete in 1373.9 sec
[-----------------52%                  ] 1049 of 2000 complete in 1375.3 sec
[-----------------52%                  ] 1050 of 2000 complete in 1376.6 sec
[-----------------52%                  ] 1051 of 2000 complete in 1377.9 sec
[-----------------52%                  ] 1052 of 2000 complete in 1379.2 sec
[-----------------52%                  ] 1053 of 2000 complete in 1380.5 sec
[-----------------52%                  ] 1054 of 2000 complete in 1381.9 sec
[-----------------52%                  ] 1055 of 2000 complete in 1383.2 sec
[-----------------52%                  ] 1056 of 2000 complete in 1384.5 sec
[-----------------52%                  ] 1057 of 2000 complete in 1385.8 sec
[-----------------52%                  ] 1058 of 2000 complete in 1387.2 sec
[-----------------52%                  ] 1059 of 2000 complete in 1388.5 sec
[-----------------53%                  ] 1060 of 2000 complete in 1389.9 sec
[-----------------53%                  ] 1061 of 2000 complete in 1391.3 sec
[-----------------53%                  ] 1062 of 2000 complete in 1392.7 sec
[-----------------53%                  ] 1063 of 2000 complete in 1394.0 sec
[-----------------53%                  ] 1064 of 2000 complete in 1395.4 sec
[-----------------53%                  ] 1065 of 2000 complete in 1396.8 sec
[-----------------53%                  ] 1066 of 2000 complete in 1398.2 sec
[-----------------53%                  ] 1067 of 2000 complete in 1399.5 sec
[-----------------53%                  ] 1068 of 2000 complete in 1400.9 sec
[-----------------53%                  ] 1069 of 2000 complete in 1402.3 sec
[-----------------53%                  ] 1070 of 2000 complete in 1403.6 sec
[-----------------53%                  ] 1071 of 2000 complete in 1404.9 sec
[-----------------53%                  ] 1072 of 2000 complete in 1406.3 sec
[-----------------53%                  ] 1073 of 2000 complete in 1407.7 sec
[-----------------53%                  ] 1074 of 2000 complete in 1409.0 sec
[-----------------53%                  ] 1075 of 2000 complete in 1410.4 sec
[-----------------53%                  ] 1076 of 2000 complete in 1411.7 sec
[-----------------53%                  ] 1077 of 2000 complete in 1413.0 sec
[-----------------53%                  ] 1078 of 2000 complete in 1414.3 sec
[-----------------53%                  ] 1079 of 2000 complete in 1415.6 sec
[-----------------54%                  ] 1080 of 2000 complete in 1416.9 sec
[-----------------54%                  ] 1081 of 2000 complete in 1418.2 sec
[-----------------54%                  ] 1082 of 2000 complete in 1419.4 sec
[-----------------54%                  ] 1083 of 2000 complete in 1420.7 sec
[-----------------54%                  ] 1084 of 2000 complete in 1422.0 sec
[-----------------54%                  ] 1085 of 2000 complete in 1423.2 sec
[-----------------54%                  ] 1086 of 2000 complete in 1424.5 sec

[-----------------49%                  ] 981 of 2000 complete in 1289.3 sec
[-----------------49%                  ] 982 of 2000 complete in 1290.7 sec
[-----------------49%                  ] 983 of 2000 complete in 1292.1 sec
[-----------------49%                  ] 984 of 2000 complete in 1293.5 sec
[-----------------49%                  ] 985 of 2000 complete in 1294.9 sec
[-----------------49%                  ] 986 of 2000 complete in 1296.3 sec
[-----------------49%                  ] 987 of 2000 complete in 1297.6 sec
[-----------------49%                  ] 988 of 2000 complete in 1299.1 sec
[-----------------49%                  ] 989 of 2000 complete in 1300.4 sec
[-----------------49%                  ] 990 of 2000 complete in 1301.9 sec
[-----------------49%                  ] 991 of 2000 complete in 1303.2 sec
[-----------------49%                  ] 992 of 2000 complete in 1304.6 sec
[-----------------49%                  ] 993 of 2000 complete in 1306.0 sec
[-----------------49%                  ] 994 of 2000 complete in 1307.4 sec
[-----------------49%                  ] 995 of 2000 complete in 1308.8 sec
[-----------------49%                  ] 996 of 2000 complete in 1310.1 sec
[-----------------49%                  ] 997 of 2000 complete in 1311.5 sec
[-----------------49%                  ] 998 of 2000 complete in 1312.9 sec
[-----------------49%                  ] 999 of 2000 complete in 1314.2 sec
[-----------------50%                  ] 1000 of 2000 complete in 1315.6 sec
[-----------------50%                  ] 1001 of 2000 complete in 1317.0 sec
[-----------------50%                  ] 1002 of 2000 complete in 1318.3 sec
[-----------------50%                  ] 1003 of 2000 complete in 1319.8 sec
[-----------------50%                  ] 1004 of 2000 complete in 1321.2 sec
[-----------------50%                  ] 1005 of 2000 complete in 1322.6 sec
[-----------------50%                  ] 1006 of 2000 complete in 1324.0 sec
[-----------------50%                  ] 1007 of 2000 complete in 1325.3 sec
[-----------------50%                  ] 1008 of 2000 complete in 1326.7 sec
[-----------------50%                  ] 1009 of 2000 complete in 1328.1 sec
[-----------------50%                  ] 1010 of 2000 complete in 1329.4 sec
[-----------------50%                  ] 1011 of 2000 complete in 1330.7 sec
[-----------------50%                  ] 1012 of 2000 complete in 1332.1 sec
[-----------------50%                  ] 1013 of 2000 complete in 1333.5 sec
[-----------------50%                  ] 1014 of 2000 complete in 1335.0 sec
[-----------------50%                  ] 1015 of 2000 complete in 1336.4 sec
[-----------------50%                  ] 1016 of 2000 complete in 1337.8 sec
[-----------------50%                  ] 1017 of 2000 complete in 1339.2 sec
[-----------------50%                  ] 1018 of 2000 complete in 1340.6 sec
[-----------------50%                  ] 1019 of 2000 complete in 1342.0 sec
[-----------------51%                  ] 1020 of 2000 complete in 1343.4 sec
[-----------------51%                  ] 1021 of 2000 complete in 1344.8 sec
[-----------------51%                  ] 1022 of 2000 complete in 1346.1 sec
[-----------------51%                  ] 1023 of 2000 complete in 1347.5 sec
[-----------------51%                  ] 1024 of 2000 complete in 1348.9 sec
[-----------------51%                  ] 1025 of 2000 complete in 1350.4 sec
[-----------------51%                  ] 1026 of 2000 complete in 1351.8 sec
[-----------------51%                  ] 1027 of 2000 complete in 1353.1 sec
[-----------------51%                  ] 1028 of 2000 complete in 1354.5 sec
[-----------------51%                  ] 1029 of 2000 complete in 1356.0 sec
[-----------------51%                  ] 1030 of 2000 complete in 1357.3 sec
[-----------------51%                  ] 1031 of 2000 complete in 1358.8 sec
[-----------------51%                  ] 1032 of 2000 complete in 1360.1 sec
[-----------------51%                  ] 1033 of 2000 complete in 1361.4 sec
[-----------------51%                  ] 1034 of 2000 complete in 1362.8 sec
[-----------------51%                  ] 1035 of 2000 complete in 1364.2 sec
[-----------------51%                  ] 1036 of 2000 complete in 1365.6 sec
[-----------------51%                  ] 1037 of 2000 complete in 1367.1 sec
[-----------------51%                  ] 1038 of 2000 complete in 1368.4 sec
[-----------------51%                  ] 1039 of 2000 complete in 1369.8 sec
[-----------------52%                  ] 1040 of 2000 complete in 1371.1 sec
[-----------------52%                  ] 1041 of 2000 complete in 1372.5 sec
[-----------------52%                  ] 1042 of 2000 complete in 1373.8 sec
[-----------------52%                  ] 1043 of 2000 complete in 1375.1 sec
[-----------------52%                  ] 1044 of 2000 complete in 1376.5 sec
[-----------------52%                  ] 1045 of 2000 complete in 1377.9 sec
[-----------------52%                  ] 1046 of 2000 complete in 1379.2 sec
[-----------------52%                  ] 1047 of 2000 complete in 1380.6 sec
[-----------------52%                  ] 1048 of 2000 complete in 1382.1 sec
[-----------------52%                  ] 1049 of 2000 complete in 1383.4 sec
[-----------------52%                  ] 1050 of 2000 complete in 1384.8 sec
[-----------------52%                  ] 1051 of 2000 complete in 1386.1 sec
[-----------------52%                  ] 1052 of 2000 complete in 1387.5 sec
[-----------------52%                  ] 1053 of 2000 complete in 1388.9 sec
[-----------------52%                  ] 1054 of 2000 complete in 1390.2 sec
[-----------------52%                  ] 1055 of 2000 complete in 1391.5 sec
[-----------------52%                  ] 1056 of 2000 complete in 1392.9 sec
[-----------------52%                  ] 1057 of 2000 complete in 1394.2 sec
[-----------------52%                  ] 1058 of 2000 complete in 1395.6 sec
[-----------------52%                  ] 1059 of 2000 complete in 1397.0 sec
[-----------------53%                  ] 1060 of 2000 complete in 1398.4 sec
[-----------------53%                  ] 1061 of 2000 complete in 1399.8 sec
[-----------------53%                  ] 1062 of 2000 complete in 1401.1 sec
[-----------------53%                  ] 1063 of 2000 complete in 1402.4 sec
[-----------------53%                  ] 1064 of 2000 complete in 1403.9 sec
[-----------------53%                  ] 1065 of 2000 complete in 1405.2 sec
[-----------------53%                  ] 1066 of 2000 complete in 1406.6 sec
[-----------------53%                  ] 1067 of 2000 complete in 1408.0 sec
[-----------------53%                  ] 1068 of 2000 complete in 1409.3 sec
[-----------------53%                  ] 1069 of 2000 complete in 1410.7 sec
[-----------------53%                  ] 1070 of 2000 complete in 1412.1 sec
[-----------------53%                  ] 1071 of 2000 complete in 1413.5 sec
[-----------------53%                  ] 1072 of 2000 complete in 1414.7 sec
[-----------------53%                  ] 1073 of 2000 complete in 1416.1 sec
[-----------------53%                  ] 1074 of 2000 complete in 1417.4 sec
[-----------------53%                  ] 1075 of 2000 complete in 1418.7 sec
[-----------------53%                  ] 1076 of 2000 complete in 1420.1 sec
[-----------------53%                  ] 1077 of 2000 complete in 1421.4 sec
[-----------------53%                  ] 1078 of 2000 complete in 1422.7 sec
[-----------------53%                  ] 1079 of 2000 complete in 1424.1 sec
[-----------------54%                  ] 1080 of 2000 complete in 1425.4 sec
[-----------------54%                  ] 1081 of 2000 complete in 1426.7 sec
[-----------------54%                  ] 1082 of 2000 complete in 1428.1 sec
[-----------------54%                  ] 1083 of 2000 complete in 1429.5 sec
[-----------------54%                  ] 1084 of 2000 complete in 1430.9 sec
[-----------------54%                  ] 1085 of 2000 complete in 1432.2 sec
[-----------------54%                  ] 1086 of 2000 complete in 1433.5 sec
[-----------------49%                  ] 980 of 2000 complete in 1341.6 sec
[-----------------49%                  ] 981 of 2000 complete in 1342.9 sec
[-----------------49%                  ] 982 of 2000 complete in 1344.2 sec
[-----------------49%                  ] 983 of 2000 complete in 1345.5 sec
[-----------------49%                  ] 984 of 2000 complete in 1346.8 sec
[-----------------49%                  ] 985 of 2000 complete in 1348.2 sec
[-----------------49%                  ] 986 of 2000 complete in 1349.5 sec
[-----------------49%                  ] 987 of 2000 complete in 1350.7 sec
[-----------------49%                  ] 988 of 2000 complete in 1352.0 sec
[-----------------49%                  ] 989 of 2000 complete in 1353.4 sec
[-----------------49%                  ] 990 of 2000 complete in 1354.7 sec
[-----------------49%                  ] 991 of 2000 complete in 1355.9 sec
[-----------------49%                  ] 992 of 2000 complete in 1357.3 sec
[-----------------49%                  ] 993 of 2000 complete in 1358.7 sec
[-----------------49%                  ] 994 of 2000 complete in 1360.1 sec
[-----------------49%                  ] 995 of 2000 complete in 1361.4 sec
[-----------------49%                  ] 996 of 2000 complete in 1362.8 sec
[-----------------49%                  ] 997 of 2000 complete in 1364.2 sec
[-----------------49%                  ] 998 of 2000 complete in 1365.5 sec
[-----------------49%                  ] 999 of 2000 complete in 1366.8 sec
[-----------------50%                  ] 1000 of 2000 complete in 1368.2 sec
[-----------------50%                  ] 1001 of 2000 complete in 1369.5 sec
[-----------------50%                  ] 1002 of 2000 complete in 1370.8 sec
[-----------------50%                  ] 1003 of 2000 complete in 1372.2 sec
[-----------------50%                  ] 1004 of 2000 complete in 1373.5 sec
[-----------------50%                  ] 1005 of 2000 complete in 1374.9 sec
[-----------------50%                  ] 1006 of 2000 complete in 1376.2 sec
[-----------------50%                  ] 1007 of 2000 complete in 1377.6 sec
[-----------------50%                  ] 1008 of 2000 complete in 1378.9 sec
[-----------------50%                  ] 1009 of 2000 complete in 1380.3 sec
[-----------------50%                  ] 1010 of 2000 complete in 1381.6 sec
[-----------------50%                  ] 1011 of 2000 complete in 1382.8 sec
[-----------------50%                  ] 1012 of 2000 complete in 1384.1 sec
[-----------------50%                  ] 1013 of 2000 complete in 1385.4 sec
[-----------------50%                  ] 1014 of 2000 complete in 1386.6 sec
[-----------------50%                  ] 1015 of 2000 complete in 1387.9 sec
[-----------------50%                  ] 1016 of 2000 complete in 1389.2 sec
[-----------------50%                  ] 1017 of 2000 complete in 1390.6 sec
[-----------------50%                  ] 1018 of 2000 complete in 1391.8 sec
[-----------------50%                  ] 1019 of 2000 complete in 1393.1 sec
[-----------------51%                  ] 1020 of 2000 complete in 1394.4 sec
[-----------------51%                  ] 1021 of 2000 complete in 1395.8 sec
[-----------------51%                  ] 1022 of 2000 complete in 1397.1 sec
[-----------------51%                  ] 1023 of 2000 complete in 1398.5 sec
[-----------------51%                  ] 1024 of 2000 complete in 1399.8 sec
[-----------------51%                  ] 1025 of 2000 complete in 1401.2 sec
[-----------------51%                  ] 1026 of 2000 complete in 1402.4 sec
[-----------------51%                  ] 1027 of 2000 complete in 1403.7 sec
[-----------------51%                  ] 1028 of 2000 complete in 1405.0 sec
[-----------------51%                  ] 1029 of 2000 complete in 1406.3 sec
[-----------------51%                  ] 1030 of 2000 complete in 1407.6 sec
[-----------------51%                  ] 1031 of 2000 complete in 1408.8 sec
[-----------------51%                  ] 1032 of 2000 complete in 1410.1 sec
[-----------------51%                  ] 1033 of 2000 complete in 1411.5 sec
[-----------------51%                  ] 1034 of 2000 complete in 1412.7 sec
[-----------------51%                  ] 1035 of 2000 complete in 1414.0 sec
[-----------------51%                  ] 1036 of 2000 complete in 1415.3 sec
[-----------------51%                  ] 1037 of 2000 complete in 1416.7 sec
[-----------------51%                  ] 1038 of 2000 complete in 1418.0 sec
[-----------------51%                  ] 1039 of 2000 complete in 1419.3 sec
[-----------------52%                  ] 1040 of 2000 complete in 1420.7 sec
[-----------------52%                  ] 1041 of 2000 complete in 1422.0 sec
[-----------------52%                  ] 1042 of 2000 complete in 1423.3 sec
[-----------------52%                  ] 1043 of 2000 complete in 1424.6 sec
[-----------------52%                  ] 1044 of 2000 complete in 1426.0 sec
[-----------------52%                  ] 1045 of 2000 complete in 1427.3 sec
[-----------------52%                  ] 1046 of 2000 complete in 1428.7 sec
[-----------------52%                  ] 1047 of 2000 complete in 1430.1 sec
[-----------------52%                  ] 1048 of 2000 complete in 1431.4 sec
[-----------------52%                  ] 1049 of 2000 complete in 1432.8 sec
[-----------------52%                  ] 1050 of 2000 complete in 1434.1 sec
[-----------------52%                  ] 1051 of 2000 complete in 1435.4 sec
[-----------------52%                  ] 1052 of 2000 complete in 1436.7 sec
[-----------------52%                  ] 1053 of 2000 complete in 1438.0 sec
[-----------------52%                  ] 1054 of 2000 complete in 1439.3 sec
[-----------------52%                  ] 1055 of 2000 complete in 1440.6 sec
[-----------------52%                  ] 1056 of 2000 complete in 1441.9 sec
[-----------------52%                  ] 1057 of 2000 complete in 1443.2 sec
[-----------------52%                  ] 1058 of 2000 complete in 1444.5 sec
[-----------------52%                  ] 1059 of 2000 complete in 1445.7 sec
[-----------------53%                  ] 1060 of 2000 complete in 1447.0 sec
[-----------------53%                  ] 1061 of 2000 complete in 1448.2 sec
[-----------------53%                  ] 1062 of 2000 complete in 1449.5 sec
[-----------------53%                  ] 1063 of 2000 complete in 1450.8 sec
[-----------------53%                  ] 1064 of 2000 complete in 1452.1 sec
[-----------------53%                  ] 1065 of 2000 complete in 1453.4 sec
[-----------------53%                  ] 1066 of 2000 complete in 1454.8 sec
[-----------------53%                  ] 1067 of 2000 complete in 1456.1 sec
[-----------------53%                  ] 1068 of 2000 complete in 1457.4 sec
[-----------------53%                  ] 1069 of 2000 complete in 1458.7 sec
[-----------------53%                  ] 1070 of 2000 complete in 1460.0 sec
[-----------------53%                  ] 1071 of 2000 complete in 1461.4 sec
[-----------------53%                  ] 1072 of 2000 complete in 1462.7 sec
[-----------------53%                  ] 1073 of 2000 complete in 1464.1 sec
[-----------------53%                  ] 1074 of 2000 complete in 1465.5 sec
[-----------------53%                  ] 1075 of 2000 complete in 1466.9 sec
[-----------------53%                  ] 1076 of 2000 complete in 1468.3 sec
[-----------------53%                  ] 1077 of 2000 complete in 1469.6 sec
[-----------------53%                  ] 1078 of 2000 complete in 1471.0 sec
[-----------------53%                  ] 1079 of 2000 complete in 1472.3 sec
[-----------------54%                  ] 1080 of 2000 complete in 1473.6 sec
[-----------------54%                  ] 1081 of 2000 complete in 1475.0 sec
[-----------------54%                  ] 1082 of 2000 complete in 1476.3 sec
[-----------------54%                  ] 1083 of 2000 complete in 1477.7 sec
[-----------------54%                  ] 1084 of 2000 complete in 1479.0 sec
[-----------------54%                  ] 1085 of 2000 complete in 1480.4 sec

[-----------------54%                  ] 1087 of 2000 complete in 1421.3 sec
[-----------------54%                  ] 1088 of 2000 complete in 1422.7 sec
[-----------------54%                  ] 1089 of 2000 complete in 1424.1 sec
[-----------------54%                  ] 1090 of 2000 complete in 1425.6 sec
[-----------------54%                  ] 1091 of 2000 complete in 1426.9 sec
[-----------------54%                  ] 1092 of 2000 complete in 1428.4 sec
[-----------------54%                  ] 1093 of 2000 complete in 1429.8 sec
[-----------------54%                  ] 1094 of 2000 complete in 1431.1 sec
[-----------------54%                  ] 1095 of 2000 complete in 1432.6 sec
[-----------------54%                  ] 1096 of 2000 complete in 1434.1 sec
[-----------------54%                  ] 1097 of 2000 complete in 1435.4 sec
[-----------------54%                  ] 1098 of 2000 complete in 1436.9 sec
[-----------------54%                  ] 1099 of 2000 complete in 1438.4 sec
[-----------------55%                  ] 1100 of 2000 complete in 1439.7 sec
[-----------------55%                  ] 1101 of 2000 complete in 1441.0 sec
[-----------------55%                  ] 1102 of 2000 complete in 1442.5 sec
[-----------------55%                  ] 1103 of 2000 complete in 1443.9 sec
[-----------------55%                  ] 1104 of 2000 complete in 1445.3 sec
[-----------------55%                  ] 1105 of 2000 complete in 1446.7 sec
[-----------------55%-                 ] 1106 of 2000 complete in 1448.1 sec
[-----------------55%-                 ] 1107 of 2000 complete in 1449.5 sec
[-----------------55%-                 ] 1108 of 2000 complete in 1450.8 sec
[-----------------55%-                 ] 1109 of 2000 complete in 1452.2 sec
[-----------------55%-                 ] 1110 of 2000 complete in 1453.6 sec
[-----------------55%-                 ] 1111 of 2000 complete in 1454.9 sec
[-----------------55%-                 ] 1112 of 2000 complete in 1456.3 sec
[-----------------55%-                 ] 1113 of 2000 complete in 1457.7 sec
[-----------------55%-                 ] 1114 of 2000 complete in 1459.1 sec
[-----------------55%-                 ] 1115 of 2000 complete in 1460.4 sec
[-----------------55%-                 ] 1116 of 2000 complete in 1461.8 sec
[-----------------55%-                 ] 1117 of 2000 complete in 1463.2 sec
[-----------------55%-                 ] 1118 of 2000 complete in 1464.6 sec
[-----------------55%-                 ] 1119 of 2000 complete in 1466.1 sec
[-----------------56%-                 ] 1120 of 2000 complete in 1467.5 sec
[-----------------56%-                 ] 1121 of 2000 complete in 1468.9 sec
[-----------------56%-                 ] 1122 of 2000 complete in 1470.3 sec
[-----------------56%-                 ] 1123 of 2000 complete in 1471.7 sec
[-----------------56%-                 ] 1124 of 2000 complete in 1473.1 sec
[-----------------56%-                 ] 1125 of 2000 complete in 1474.5 sec
[-----------------56%-                 ] 1126 of 2000 complete in 1475.8 sec
[-----------------56%-                 ] 1127 of 2000 complete in 1477.2 sec
[-----------------56%-                 ] 1128 of 2000 complete in 1478.6 sec
[-----------------56%-                 ] 1129 of 2000 complete in 1480.0 sec
[-----------------56%-                 ] 1130 of 2000 complete in 1481.4 sec
[-----------------56%-                 ] 1131 of 2000 complete in 1482.9 sec
[-----------------56%-                 ] 1132 of 2000 complete in 1484.3 sec
[-----------------56%-                 ] 1133 of 2000 complete in 1485.6 sec
[-----------------56%-                 ] 1134 of 2000 complete in 1487.0 sec
[-----------------56%-                 ] 1135 of 2000 complete in 1488.4 sec
[-----------------56%-                 ] 1136 of 2000 complete in 1489.8 sec
[-----------------56%-                 ] 1137 of 2000 complete in 1491.2 sec
[-----------------56%-                 ] 1138 of 2000 complete in 1492.5 sec
[-----------------56%-                 ] 1139 of 2000 complete in 1493.9 sec
[-----------------57%-                 ] 1140 of 2000 complete in 1495.2 sec
[-----------------57%-                 ] 1141 of 2000 complete in 1496.7 sec
[-----------------57%-                 ] 1142 of 2000 complete in 1498.1 sec
[-----------------57%-                 ] 1143 of 2000 complete in 1499.5 sec
[-----------------57%-                 ] 1144 of 2000 complete in 1500.9 sec
[-----------------57%-                 ] 1145 of 2000 complete in 1502.3 sec
[-----------------57%-                 ] 1146 of 2000 complete in 1503.7 sec
[-----------------57%-                 ] 1147 of 2000 complete in 1505.1 sec
[-----------------57%-                 ] 1148 of 2000 complete in 1506.4 sec
[-----------------57%-                 ] 1149 of 2000 complete in 1507.9 sec
[-----------------57%-                 ] 1150 of 2000 complete in 1509.3 sec
[-----------------57%-                 ] 1151 of 2000 complete in 1510.7 sec
[-----------------57%-                 ] 1152 of 2000 complete in 1512.2 sec
[-----------------57%-                 ] 1153 of 2000 complete in 1513.6 sec
[-----------------57%-                 ] 1154 of 2000 complete in 1515.0 sec
[-----------------57%-                 ] 1155 of 2000 complete in 1516.3 sec
[-----------------57%-                 ] 1156 of 2000 complete in 1517.7 sec
[-----------------57%-                 ] 1157 of 2000 complete in 1519.1 sec
[-----------------57%--                ] 1158 of 2000 complete in 1520.5 sec
[-----------------57%--                ] 1159 of 2000 complete in 1521.9 sec
[-----------------58%--                ] 1160 of 2000 complete in 1523.2 sec
[-----------------58%--                ] 1161 of 2000 complete in 1524.6 sec
[-----------------58%--                ] 1162 of 2000 complete in 1526.0 sec
[-----------------58%--                ] 1163 of 2000 complete in 1527.4 sec
[-----------------58%--                ] 1164 of 2000 complete in 1528.9 sec
[-----------------58%--                ] 1165 of 2000 complete in 1530.3 sec
[-----------------58%--                ] 1166 of 2000 complete in 1531.7 sec
[-----------------58%--                ] 1167 of 2000 complete in 1533.1 sec
[-----------------58%--                ] 1168 of 2000 complete in 1534.5 sec
[-----------------58%--                ] 1169 of 2000 complete in 1535.9 sec
[-----------------58%--                ] 1170 of 2000 complete in 1537.2 sec
[-----------------58%--                ] 1171 of 2000 complete in 1538.6 sec
[-----------------58%--                ] 1172 of 2000 complete in 1540.0 sec
[-----------------58%--                ] 1173 of 2000 complete in 1541.4 sec
[-----------------58%--                ] 1174 of 2000 complete in 1542.8 sec
[-----------------58%--                ] 1175 of 2000 complete in 1544.2 sec
[-----------------58%--                ] 1176 of 2000 complete in 1545.6 sec
[-----------------58%--                ] 1177 of 2000 complete in 1547.0 sec
[-----------------58%--                ] 1178 of 2000 complete in 1548.4 sec
[-----------------58%--                ] 1179 of 2000 complete in 1549.8 sec
[-----------------59%--                ] 1180 of 2000 complete in 1551.1 sec
[-----------------59%--                ] 1181 of 2000 complete in 1552.5 sec
[-----------------59%--                ] 1182 of 2000 complete in 1553.9 sec
[-----------------59%--                ] 1183 of 2000 complete in 1555.3 sec
[-----------------59%--                ] 1184 of 2000 complete in 1556.7 sec
[-----------------59%--                ] 1185 of 2000 complete in 1558.0 sec
[-----------------59%--                ] 1186 of 2000 complete in 1559.4 sec
[-----------------59%--                ] 1187 of 2000 complete in 1560.9 sec
[-----------------59%--                ] 1188 of 2000 complete in 1562.3 sec
[-----------------59%--                ] 1189 of 2000 complete in 1563.6 sec
[-----------------59%--                ] 1190 of 2000 complete in 1564.9 sec
[-----------------59%--                ] 1191 of 2000 complete in 1566.3 sec
[-----------------59%--                ] 1192 of 2000 complete in 1567.7 sec
[-----------------54%                  ] 1087 of 2000 complete in 1425.8 sec
[-----------------54%                  ] 1088 of 2000 complete in 1427.1 sec
[-----------------54%                  ] 1089 of 2000 complete in 1428.4 sec
[-----------------54%                  ] 1090 of 2000 complete in 1429.7 sec
[-----------------54%                  ] 1091 of 2000 complete in 1431.0 sec
[-----------------54%                  ] 1092 of 2000 complete in 1432.3 sec
[-----------------54%                  ] 1093 of 2000 complete in 1433.6 sec
[-----------------54%                  ] 1094 of 2000 complete in 1434.9 sec
[-----------------54%                  ] 1095 of 2000 complete in 1436.3 sec
[-----------------54%                  ] 1096 of 2000 complete in 1437.6 sec
[-----------------54%                  ] 1097 of 2000 complete in 1439.0 sec
[-----------------54%                  ] 1098 of 2000 complete in 1440.3 sec
[-----------------54%                  ] 1099 of 2000 complete in 1441.6 sec
[-----------------55%                  ] 1100 of 2000 complete in 1443.0 sec
[-----------------55%                  ] 1101 of 2000 complete in 1444.3 sec
[-----------------55%                  ] 1102 of 2000 complete in 1445.6 sec
[-----------------55%                  ] 1103 of 2000 complete in 1446.9 sec
[-----------------55%                  ] 1104 of 2000 complete in 1448.3 sec
[-----------------55%                  ] 1105 of 2000 complete in 1449.7 sec
[-----------------55%-                 ] 1106 of 2000 complete in 1451.0 sec
[-----------------55%-                 ] 1107 of 2000 complete in 1452.3 sec
[-----------------55%-                 ] 1108 of 2000 complete in 1453.7 sec
[-----------------55%-                 ] 1109 of 2000 complete in 1455.1 sec
[-----------------55%-                 ] 1110 of 2000 complete in 1456.4 sec
[-----------------55%-                 ] 1111 of 2000 complete in 1457.8 sec
[-----------------55%-                 ] 1112 of 2000 complete in 1459.2 sec
[-----------------55%-                 ] 1113 of 2000 complete in 1460.6 sec
[-----------------55%-                 ] 1114 of 2000 complete in 1461.9 sec
[-----------------55%-                 ] 1115 of 2000 complete in 1463.3 sec
[-----------------55%-                 ] 1116 of 2000 complete in 1464.6 sec
[-----------------55%-                 ] 1117 of 2000 complete in 1466.0 sec
[-----------------55%-                 ] 1118 of 2000 complete in 1467.4 sec
[-----------------55%-                 ] 1119 of 2000 complete in 1468.7 sec
[-----------------56%-                 ] 1120 of 2000 complete in 1470.2 sec
[-----------------56%-                 ] 1121 of 2000 complete in 1471.5 sec
[-----------------56%-                 ] 1122 of 2000 complete in 1472.9 sec
[-----------------56%-                 ] 1123 of 2000 complete in 1474.3 sec
[-----------------56%-                 ] 1124 of 2000 complete in 1475.7 sec
[-----------------56%-                 ] 1125 of 2000 complete in 1477.1 sec
[-----------------56%-                 ] 1126 of 2000 complete in 1478.4 sec
[-----------------56%-                 ] 1127 of 2000 complete in 1479.8 sec
[-----------------56%-                 ] 1128 of 2000 complete in 1481.2 sec
[-----------------56%-                 ] 1129 of 2000 complete in 1482.7 sec
[-----------------56%-                 ] 1130 of 2000 complete in 1484.1 sec
[-----------------56%-                 ] 1131 of 2000 complete in 1485.5 sec
[-----------------56%-                 ] 1132 of 2000 complete in 1486.9 sec
[-----------------56%-                 ] 1133 of 2000 complete in 1488.3 sec
[-----------------56%-                 ] 1134 of 2000 complete in 1489.7 sec
[-----------------56%-                 ] 1135 of 2000 complete in 1491.1 sec
[-----------------56%-                 ] 1136 of 2000 complete in 1492.5 sec
[-----------------56%-                 ] 1137 of 2000 complete in 1493.9 sec
[-----------------56%-                 ] 1138 of 2000 complete in 1495.2 sec
[-----------------56%-                 ] 1139 of 2000 complete in 1496.5 sec
[-----------------57%-                 ] 1140 of 2000 complete in 1497.9 sec
[-----------------57%-                 ] 1141 of 2000 complete in 1499.3 sec
[-----------------57%-                 ] 1142 of 2000 complete in 1500.7 sec
[-----------------57%-                 ] 1143 of 2000 complete in 1502.1 sec
[-----------------57%-                 ] 1144 of 2000 complete in 1503.4 sec
[-----------------57%-                 ] 1145 of 2000 complete in 1504.7 sec
[-----------------57%-                 ] 1146 of 2000 complete in 1506.1 sec
[-----------------57%-                 ] 1147 of 2000 complete in 1507.4 sec
[-----------------57%-                 ] 1148 of 2000 complete in 1508.8 sec
[-----------------57%-                 ] 1149 of 2000 complete in 1510.2 sec
[-----------------57%-                 ] 1150 of 2000 complete in 1511.6 sec
[-----------------57%-                 ] 1151 of 2000 complete in 1512.9 sec
[-----------------57%-                 ] 1152 of 2000 complete in 1514.4 sec
[-----------------57%-                 ] 1153 of 2000 complete in 1515.7 sec
[-----------------57%-                 ] 1154 of 2000 complete in 1517.1 sec
[-----------------57%-                 ] 1155 of 2000 complete in 1518.4 sec
[-----------------57%-                 ] 1156 of 2000 complete in 1519.8 sec
[-----------------57%-                 ] 1157 of 2000 complete in 1521.1 sec
[-----------------57%--                ] 1158 of 2000 complete in 1522.5 sec
[-----------------57%--                ] 1159 of 2000 complete in 1523.9 sec
[-----------------58%--                ] 1160 of 2000 complete in 1525.4 sec
[-----------------58%--                ] 1161 of 2000 complete in 1526.8 sec
[-----------------58%--                ] 1162 of 2000 complete in 1528.2 sec
[-----------------58%--                ] 1163 of 2000 complete in 1529.5 sec
[-----------------58%--                ] 1164 of 2000 complete in 1531.0 sec
[-----------------58%--                ] 1165 of 2000 complete in 1532.4 sec
[-----------------58%--                ] 1166 of 2000 complete in 1533.9 sec
[-----------------58%--                ] 1167 of 2000 complete in 1535.3 sec
[-----------------58%--                ] 1168 of 2000 complete in 1536.7 sec
[-----------------58%--                ] 1169 of 2000 complete in 1538.1 sec
[-----------------58%--                ] 1170 of 2000 complete in 1539.5 sec
[-----------------58%--                ] 1171 of 2000 complete in 1540.9 sec
[-----------------58%--                ] 1172 of 2000 complete in 1542.2 sec
[-----------------58%--                ] 1173 of 2000 complete in 1543.6 sec
[-----------------58%--                ] 1174 of 2000 complete in 1545.0 sec
[-----------------58%--                ] 1175 of 2000 complete in 1546.4 sec
[-----------------58%--                ] 1176 of 2000 complete in 1547.7 sec
[-----------------58%--                ] 1177 of 2000 complete in 1549.1 sec
[-----------------58%--                ] 1178 of 2000 complete in 1550.5 sec
[-----------------58%--                ] 1179 of 2000 complete in 1551.8 sec
[-----------------59%--                ] 1180 of 2000 complete in 1553.2 sec
[-----------------59%--                ] 1181 of 2000 complete in 1554.5 sec
[-----------------59%--                ] 1182 of 2000 complete in 1555.9 sec
[-----------------59%--                ] 1183 of 2000 complete in 1557.2 sec
[-----------------59%--                ] 1184 of 2000 complete in 1558.6 sec
[-----------------59%--                ] 1185 of 2000 complete in 1560.0 sec
[-----------------59%--                ] 1186 of 2000 complete in 1561.3 sec
[-----------------59%--                ] 1187 of 2000 complete in 1562.7 sec
[-----------------59%--                ] 1188 of 2000 complete in 1564.1 sec
[-----------------59%--                ] 1189 of 2000 complete in 1565.5 sec
[-----------------59%--                ] 1190 of 2000 complete in 1566.8 sec
[-----------------59%--                ] 1191 of 2000 complete in 1568.2 sec
[-----------------59%--                ] 1192 of 2000 complete in 1569.5 sec

[-----------------54%                  ] 1087 of 2000 complete in 1434.9 sec
[-----------------54%                  ] 1088 of 2000 complete in 1436.3 sec
[-----------------54%                  ] 1089 of 2000 complete in 1437.6 sec
[-----------------54%                  ] 1090 of 2000 complete in 1439.0 sec
[-----------------54%                  ] 1091 of 2000 complete in 1440.3 sec
[-----------------54%                  ] 1092 of 2000 complete in 1441.6 sec
[-----------------54%                  ] 1093 of 2000 complete in 1443.0 sec
[-----------------54%                  ] 1094 of 2000 complete in 1444.3 sec
[-----------------54%                  ] 1095 of 2000 complete in 1445.6 sec
[-----------------54%                  ] 1096 of 2000 complete in 1447.0 sec
[-----------------54%                  ] 1097 of 2000 complete in 1448.4 sec
[-----------------54%                  ] 1098 of 2000 complete in 1449.9 sec
[-----------------54%                  ] 1099 of 2000 complete in 1451.3 sec
[-----------------55%                  ] 1100 of 2000 complete in 1452.6 sec
[-----------------55%                  ] 1101 of 2000 complete in 1454.0 sec
[-----------------55%                  ] 1102 of 2000 complete in 1455.5 sec
[-----------------55%                  ] 1103 of 2000 complete in 1456.9 sec
[-----------------55%                  ] 1104 of 2000 complete in 1458.2 sec
[-----------------55%                  ] 1105 of 2000 complete in 1459.6 sec
[-----------------55%-                 ] 1106 of 2000 complete in 1460.9 sec
[-----------------55%-                 ] 1107 of 2000 complete in 1462.3 sec
[-----------------55%-                 ] 1108 of 2000 complete in 1463.6 sec
[-----------------55%-                 ] 1109 of 2000 complete in 1465.0 sec
[-----------------55%-                 ] 1110 of 2000 complete in 1466.4 sec
[-----------------55%-                 ] 1111 of 2000 complete in 1467.8 sec
[-----------------55%-                 ] 1112 of 2000 complete in 1469.1 sec
[-----------------55%-                 ] 1113 of 2000 complete in 1470.4 sec
[-----------------55%-                 ] 1114 of 2000 complete in 1471.8 sec
[-----------------55%-                 ] 1115 of 2000 complete in 1473.2 sec
[-----------------55%-                 ] 1116 of 2000 complete in 1474.5 sec
[-----------------55%-                 ] 1117 of 2000 complete in 1475.9 sec
[-----------------55%-                 ] 1118 of 2000 complete in 1477.3 sec
[-----------------55%-                 ] 1119 of 2000 complete in 1478.6 sec
[-----------------56%-                 ] 1120 of 2000 complete in 1479.9 sec
[-----------------56%-                 ] 1121 of 2000 complete in 1481.3 sec
[-----------------56%-                 ] 1122 of 2000 complete in 1482.7 sec
[-----------------56%-                 ] 1123 of 2000 complete in 1484.1 sec
[-----------------56%-                 ] 1124 of 2000 complete in 1485.4 sec
[-----------------56%-                 ] 1125 of 2000 complete in 1486.8 sec
[-----------------56%-                 ] 1126 of 2000 complete in 1488.2 sec
[-----------------56%-                 ] 1127 of 2000 complete in 1489.6 sec
[-----------------56%-                 ] 1128 of 2000 complete in 1491.0 sec
[-----------------56%-                 ] 1129 of 2000 complete in 1492.3 sec
[-----------------56%-                 ] 1130 of 2000 complete in 1493.7 sec
[-----------------56%-                 ] 1131 of 2000 complete in 1495.2 sec
[-----------------56%-                 ] 1132 of 2000 complete in 1496.5 sec
[-----------------56%-                 ] 1133 of 2000 complete in 1497.9 sec
[-----------------56%-                 ] 1134 of 2000 complete in 1499.2 sec
[-----------------56%-                 ] 1135 of 2000 complete in 1500.6 sec
[-----------------56%-                 ] 1136 of 2000 complete in 1502.0 sec
[-----------------56%-                 ] 1137 of 2000 complete in 1503.4 sec
[-----------------56%-                 ] 1138 of 2000 complete in 1504.7 sec
[-----------------56%-                 ] 1139 of 2000 complete in 1506.1 sec
[-----------------57%-                 ] 1140 of 2000 complete in 1507.5 sec
[-----------------57%-                 ] 1141 of 2000 complete in 1508.9 sec
[-----------------57%-                 ] 1142 of 2000 complete in 1510.2 sec
[-----------------57%-                 ] 1143 of 2000 complete in 1511.5 sec
[-----------------57%-                 ] 1144 of 2000 complete in 1512.9 sec
[-----------------57%-                 ] 1145 of 2000 complete in 1514.3 sec
[-----------------57%-                 ] 1146 of 2000 complete in 1515.7 sec
[-----------------57%-                 ] 1147 of 2000 complete in 1517.0 sec
[-----------------57%-                 ] 1148 of 2000 complete in 1518.4 sec
[-----------------57%-                 ] 1149 of 2000 complete in 1519.8 sec
[-----------------57%-                 ] 1150 of 2000 complete in 1521.2 sec
[-----------------57%-                 ] 1151 of 2000 complete in 1522.6 sec
[-----------------57%-                 ] 1152 of 2000 complete in 1524.0 sec
[-----------------57%-                 ] 1153 of 2000 complete in 1525.4 sec
[-----------------57%-                 ] 1154 of 2000 complete in 1526.8 sec
[-----------------57%-                 ] 1155 of 2000 complete in 1528.2 sec
[-----------------57%-                 ] 1156 of 2000 complete in 1529.6 sec
[-----------------57%-                 ] 1157 of 2000 complete in 1531.0 sec
[-----------------57%--                ] 1158 of 2000 complete in 1532.3 sec
[-----------------57%--                ] 1159 of 2000 complete in 1533.7 sec
[-----------------58%--                ] 1160 of 2000 complete in 1535.1 sec
[-----------------58%--                ] 1161 of 2000 complete in 1536.4 sec
[-----------------58%--                ] 1162 of 2000 complete in 1537.8 sec
[-----------------58%--                ] 1163 of 2000 complete in 1539.2 sec
[-----------------58%--                ] 1164 of 2000 complete in 1540.7 sec
[-----------------58%--                ] 1165 of 2000 complete in 1542.0 sec
[-----------------58%--                ] 1166 of 2000 complete in 1543.4 sec
[-----------------58%--                ] 1167 of 2000 complete in 1544.8 sec
[-----------------58%--                ] 1168 of 2000 complete in 1546.2 sec
[-----------------58%--                ] 1169 of 2000 complete in 1547.6 sec
[-----------------58%--                ] 1170 of 2000 complete in 1549.0 sec
[-----------------58%--                ] 1171 of 2000 complete in 1550.4 sec
[-----------------58%--                ] 1172 of 2000 complete in 1551.9 sec
[-----------------58%--                ] 1173 of 2000 complete in 1553.3 sec
[-----------------58%--                ] 1174 of 2000 complete in 1554.7 sec
[-----------------58%--                ] 1175 of 2000 complete in 1556.1 sec
[-----------------58%--                ] 1176 of 2000 complete in 1557.4 sec
[-----------------58%--                ] 1177 of 2000 complete in 1558.8 sec
[-----------------58%--                ] 1178 of 2000 complete in 1560.2 sec
[-----------------58%--                ] 1179 of 2000 complete in 1561.7 sec
[-----------------59%--                ] 1180 of 2000 complete in 1563.1 sec
[-----------------59%--                ] 1181 of 2000 complete in 1564.4 sec
[-----------------59%--                ] 1182 of 2000 complete in 1565.8 sec
[-----------------59%--                ] 1183 of 2000 complete in 1567.3 sec
[-----------------59%--                ] 1184 of 2000 complete in 1568.7 sec
[-----------------59%--                ] 1185 of 2000 complete in 1570.0 sec
[-----------------59%--                ] 1186 of 2000 complete in 1571.4 sec
[-----------------59%--                ] 1187 of 2000 complete in 1572.8 sec
[-----------------59%--                ] 1188 of 2000 complete in 1574.1 sec
[-----------------59%--                ] 1189 of 2000 complete in 1575.6 sec
[-----------------59%--                ] 1190 of 2000 complete in 1577.0 sec
[-----------------59%--                ] 1191 of 2000 complete in 1578.4 sec
[-----------------59%--                ] 1192 of 2000 complete in 1579.7 sec
[-----------------54%                  ] 1086 of 2000 complete in 1481.8 sec
[-----------------54%                  ] 1087 of 2000 complete in 1483.2 sec
[-----------------54%                  ] 1088 of 2000 complete in 1484.6 sec
[-----------------54%                  ] 1089 of 2000 complete in 1486.0 sec
[-----------------54%                  ] 1090 of 2000 complete in 1487.4 sec
[-----------------54%                  ] 1091 of 2000 complete in 1488.7 sec
[-----------------54%                  ] 1092 of 2000 complete in 1490.0 sec
[-----------------54%                  ] 1093 of 2000 complete in 1491.5 sec
[-----------------54%                  ] 1094 of 2000 complete in 1492.9 sec
[-----------------54%                  ] 1095 of 2000 complete in 1494.3 sec
[-----------------54%                  ] 1096 of 2000 complete in 1495.7 sec
[-----------------54%                  ] 1097 of 2000 complete in 1497.1 sec
[-----------------54%                  ] 1098 of 2000 complete in 1498.4 sec
[-----------------54%                  ] 1099 of 2000 complete in 1499.8 sec
[-----------------55%                  ] 1100 of 2000 complete in 1501.2 sec
[-----------------55%                  ] 1101 of 2000 complete in 1502.6 sec
[-----------------55%                  ] 1102 of 2000 complete in 1504.0 sec
[-----------------55%                  ] 1103 of 2000 complete in 1505.3 sec
[-----------------55%                  ] 1104 of 2000 complete in 1506.6 sec
[-----------------55%                  ] 1105 of 2000 complete in 1507.9 sec
[-----------------55%-                 ] 1106 of 2000 complete in 1509.3 sec
[-----------------55%-                 ] 1107 of 2000 complete in 1510.8 sec
[-----------------55%-                 ] 1108 of 2000 complete in 1512.1 sec
[-----------------55%-                 ] 1109 of 2000 complete in 1513.4 sec
[-----------------55%-                 ] 1110 of 2000 complete in 1514.8 sec
[-----------------55%-                 ] 1111 of 2000 complete in 1516.1 sec
[-----------------55%-                 ] 1112 of 2000 complete in 1517.4 sec
[-----------------55%-                 ] 1113 of 2000 complete in 1518.8 sec
[-----------------55%-                 ] 1114 of 2000 complete in 1520.1 sec
[-----------------55%-                 ] 1115 of 2000 complete in 1521.4 sec
[-----------------55%-                 ] 1116 of 2000 complete in 1522.7 sec
[-----------------55%-                 ] 1117 of 2000 complete in 1524.0 sec
[-----------------55%-                 ] 1118 of 2000 complete in 1525.4 sec
[-----------------55%-                 ] 1119 of 2000 complete in 1526.7 sec
[-----------------56%-                 ] 1120 of 2000 complete in 1528.2 sec
[-----------------56%-                 ] 1121 of 2000 complete in 1529.6 sec
[-----------------56%-                 ] 1122 of 2000 complete in 1530.9 sec
[-----------------56%-                 ] 1123 of 2000 complete in 1532.2 sec
[-----------------56%-                 ] 1124 of 2000 complete in 1533.5 sec
[-----------------56%-                 ] 1125 of 2000 complete in 1534.8 sec
[-----------------56%-                 ] 1126 of 2000 complete in 1536.1 sec
[-----------------56%-                 ] 1127 of 2000 complete in 1537.4 sec
[-----------------56%-                 ] 1128 of 2000 complete in 1538.7 sec
[-----------------56%-                 ] 1129 of 2000 complete in 1540.0 sec
[-----------------56%-                 ] 1130 of 2000 complete in 1541.2 sec
[-----------------56%-                 ] 1131 of 2000 complete in 1542.4 sec
[-----------------56%-                 ] 1132 of 2000 complete in 1543.7 sec
[-----------------56%-                 ] 1133 of 2000 complete in 1545.0 sec
[-----------------56%-                 ] 1134 of 2000 complete in 1546.3 sec
[-----------------56%-                 ] 1135 of 2000 complete in 1547.6 sec
[-----------------56%-                 ] 1136 of 2000 complete in 1548.9 sec
[-----------------56%-                 ] 1137 of 2000 complete in 1550.1 sec
[-----------------56%-                 ] 1138 of 2000 complete in 1551.4 sec
[-----------------56%-                 ] 1139 of 2000 complete in 1552.7 sec
[-----------------57%-                 ] 1140 of 2000 complete in 1553.9 sec
[-----------------57%-                 ] 1141 of 2000 complete in 1555.2 sec
[-----------------57%-                 ] 1142 of 2000 complete in 1556.4 sec
[-----------------57%-                 ] 1143 of 2000 complete in 1557.7 sec
[-----------------57%-                 ] 1144 of 2000 complete in 1558.9 sec
[-----------------57%-                 ] 1145 of 2000 complete in 1560.2 sec
[-----------------57%-                 ] 1146 of 2000 complete in 1561.5 sec
[-----------------57%-                 ] 1147 of 2000 complete in 1562.8 sec
[-----------------57%-                 ] 1148 of 2000 complete in 1564.0 sec
[-----------------57%-                 ] 1149 of 2000 complete in 1565.2 sec
[-----------------57%-                 ] 1150 of 2000 complete in 1566.5 sec
[-----------------57%-                 ] 1151 of 2000 complete in 1567.8 sec
[-----------------57%-                 ] 1152 of 2000 complete in 1569.0 sec
[-----------------57%-                 ] 1153 of 2000 complete in 1570.3 sec
[-----------------57%-                 ] 1154 of 2000 complete in 1571.6 sec
[-----------------57%-                 ] 1155 of 2000 complete in 1572.8 sec
[-----------------57%-                 ] 1156 of 2000 complete in 1574.1 sec
[-----------------57%-                 ] 1157 of 2000 complete in 1575.4 sec
[-----------------57%--                ] 1158 of 2000 complete in 1576.7 sec
[-----------------57%--                ] 1159 of 2000 complete in 1578.0 sec
[-----------------58%--                ] 1160 of 2000 complete in 1579.3 sec
[-----------------58%--                ] 1161 of 2000 complete in 1580.6 sec
[-----------------58%--                ] 1162 of 2000 complete in 1581.9 sec
[-----------------58%--                ] 1163 of 2000 complete in 1583.1 sec
[-----------------58%--                ] 1164 of 2000 complete in 1584.4 sec
[-----------------58%--                ] 1165 of 2000 complete in 1585.6 sec
[-----------------58%--                ] 1166 of 2000 complete in 1586.9 sec
[-----------------58%--                ] 1167 of 2000 complete in 1588.2 sec
[-----------------58%--                ] 1168 of 2000 complete in 1589.4 sec
[-----------------58%--                ] 1169 of 2000 complete in 1590.7 sec
[-----------------58%--                ] 1170 of 2000 complete in 1591.9 sec
[-----------------58%--                ] 1171 of 2000 complete in 1593.1 sec
[-----------------58%--                ] 1172 of 2000 complete in 1594.4 sec
[-----------------58%--                ] 1173 of 2000 complete in 1595.6 sec
[-----------------58%--                ] 1174 of 2000 complete in 1596.9 sec
[-----------------58%--                ] 1175 of 2000 complete in 1598.1 sec
[-----------------58%--                ] 1176 of 2000 complete in 1599.3 sec
[-----------------58%--                ] 1177 of 2000 complete in 1600.5 sec
[-----------------58%--                ] 1178 of 2000 complete in 1601.6 sec
[-----------------58%--                ] 1179 of 2000 complete in 1602.9 sec
[-----------------59%--                ] 1180 of 2000 complete in 1604.1 sec
[-----------------59%--                ] 1181 of 2000 complete in 1605.3 sec
[-----------------59%--                ] 1182 of 2000 complete in 1606.5 sec
[-----------------59%--                ] 1183 of 2000 complete in 1607.7 sec
[-----------------59%--                ] 1184 of 2000 complete in 1608.9 sec
[-----------------59%--                ] 1185 of 2000 complete in 1610.2 sec
[-----------------59%--                ] 1186 of 2000 complete in 1611.4 sec
[-----------------59%--                ] 1187 of 2000 complete in 1612.7 sec
[-----------------59%--                ] 1188 of 2000 complete in 1613.9 sec
[-----------------59%--                ] 1189 of 2000 complete in 1615.0 sec
[-----------------59%--                ] 1190 of 2000 complete in 1616.2 sec
[-----------------59%--                ] 1191 of 2000 complete in 1617.4 sec

[-----------------59%--                ] 1193 of 2000 complete in 1569.0 sec
[-----------------59%--                ] 1194 of 2000 complete in 1570.3 sec
[-----------------59%--                ] 1195 of 2000 complete in 1571.6 sec
[-----------------59%--                ] 1196 of 2000 complete in 1573.0 sec
[-----------------59%--                ] 1197 of 2000 complete in 1574.3 sec
[-----------------59%--                ] 1198 of 2000 complete in 1575.7 sec
[-----------------59%--                ] 1199 of 2000 complete in 1577.1 sec
[-----------------60%--                ] 1200 of 2000 complete in 1578.5 sec
[-----------------60%--                ] 1201 of 2000 complete in 1579.8 sec
[-----------------60%--                ] 1202 of 2000 complete in 1581.1 sec
[-----------------60%--                ] 1203 of 2000 complete in 1582.5 sec
[-----------------60%--                ] 1204 of 2000 complete in 1583.9 sec
[-----------------60%--                ] 1205 of 2000 complete in 1585.2 sec
[-----------------60%--                ] 1206 of 2000 complete in 1586.6 sec
[-----------------60%--                ] 1207 of 2000 complete in 1587.9 sec
[-----------------60%--                ] 1208 of 2000 complete in 1589.4 sec
[-----------------60%--                ] 1209 of 2000 complete in 1590.8 sec
[-----------------60%--                ] 1210 of 2000 complete in 1592.2 sec
[-----------------60%---               ] 1211 of 2000 complete in 1593.6 sec
[-----------------60%---               ] 1212 of 2000 complete in 1595.0 sec
[-----------------60%---               ] 1213 of 2000 complete in 1596.4 sec
[-----------------60%---               ] 1214 of 2000 complete in 1597.8 sec
[-----------------60%---               ] 1215 of 2000 complete in 1599.2 sec
[-----------------60%---               ] 1216 of 2000 complete in 1600.6 sec
[-----------------60%---               ] 1217 of 2000 complete in 1602.0 sec
[-----------------60%---               ] 1218 of 2000 complete in 1603.4 sec
[-----------------60%---               ] 1219 of 2000 complete in 1604.9 sec
[-----------------61%---               ] 1220 of 2000 complete in 1606.2 sec
[-----------------61%---               ] 1221 of 2000 complete in 1607.6 sec
[-----------------61%---               ] 1222 of 2000 complete in 1609.1 sec
[-----------------61%---               ] 1223 of 2000 complete in 1610.4 sec
[-----------------61%---               ] 1224 of 2000 complete in 1611.8 sec
[-----------------61%---               ] 1225 of 2000 complete in 1613.1 sec
[-----------------61%---               ] 1226 of 2000 complete in 1614.5 sec
[-----------------61%---               ] 1227 of 2000 complete in 1616.0 sec
[-----------------61%---               ] 1228 of 2000 complete in 1617.3 sec
[-----------------61%---               ] 1229 of 2000 complete in 1618.7 sec
[-----------------61%---               ] 1230 of 2000 complete in 1620.2 sec
[-----------------61%---               ] 1231 of 2000 complete in 1621.6 sec
[-----------------61%---               ] 1232 of 2000 complete in 1623.0 sec
[-----------------61%---               ] 1233 of 2000 complete in 1624.4 sec
[-----------------61%---               ] 1234 of 2000 complete in 1625.8 sec
[-----------------61%---               ] 1235 of 2000 complete in 1627.2 sec
[-----------------61%---               ] 1236 of 2000 complete in 1628.6 sec
[-----------------61%---               ] 1237 of 2000 complete in 1630.0 sec
[-----------------61%---               ] 1238 of 2000 complete in 1631.3 sec
[-----------------61%---               ] 1239 of 2000 complete in 1632.8 sec
[-----------------62%---               ] 1240 of 2000 complete in 1634.2 sec
[-----------------62%---               ] 1241 of 2000 complete in 1635.6 sec
[-----------------62%---               ] 1242 of 2000 complete in 1637.0 sec
[-----------------62%---               ] 1243 of 2000 complete in 1638.4 sec
[-----------------62%---               ] 1244 of 2000 complete in 1639.9 sec
[-----------------62%---               ] 1245 of 2000 complete in 1641.2 sec
[-----------------62%---               ] 1246 of 2000 complete in 1642.6 sec
[-----------------62%---               ] 1247 of 2000 complete in 1644.1 sec
[-----------------62%---               ] 1248 of 2000 complete in 1645.6 sec
[-----------------62%---               ] 1249 of 2000 complete in 1647.1 sec
[-----------------62%---               ] 1250 of 2000 complete in 1648.4 sec
[-----------------62%---               ] 1251 of 2000 complete in 1650.0 sec
[-----------------62%---               ] 1252 of 2000 complete in 1651.3 sec
[-----------------62%---               ] 1253 of 2000 complete in 1652.7 sec
[-----------------62%---               ] 1254 of 2000 complete in 1654.0 sec
[-----------------62%---               ] 1255 of 2000 complete in 1655.4 sec
[-----------------62%---               ] 1256 of 2000 complete in 1656.8 sec
[-----------------62%---               ] 1257 of 2000 complete in 1658.2 sec
[-----------------62%---               ] 1258 of 2000 complete in 1659.6 sec
[-----------------62%---               ] 1259 of 2000 complete in 1661.0 sec
[-----------------63%---               ] 1260 of 2000 complete in 1662.3 sec
[-----------------63%---               ] 1261 of 2000 complete in 1663.9 sec
[-----------------63%---               ] 1262 of 2000 complete in 1665.3 sec
[-----------------63%---               ] 1263 of 2000 complete in 1666.7 sec
[-----------------63%----              ] 1264 of 2000 complete in 1668.1 sec
[-----------------63%----              ] 1265 of 2000 complete in 1669.6 sec
[-----------------63%----              ] 1266 of 2000 complete in 1671.1 sec
[-----------------63%----              ] 1267 of 2000 complete in 1672.5 sec
[-----------------63%----              ] 1268 of 2000 complete in 1673.9 sec
[-----------------63%----              ] 1269 of 2000 complete in 1675.3 sec
[-----------------63%----              ] 1270 of 2000 complete in 1676.7 sec
[-----------------63%----              ] 1271 of 2000 complete in 1678.3 sec
[-----------------63%----              ] 1272 of 2000 complete in 1679.7 sec
[-----------------63%----              ] 1273 of 2000 complete in 1681.1 sec
[-----------------63%----              ] 1274 of 2000 complete in 1682.5 sec
[-----------------63%----              ] 1275 of 2000 complete in 1683.9 sec
[-----------------63%----              ] 1276 of 2000 complete in 1685.3 sec
[-----------------63%----              ] 1277 of 2000 complete in 1686.6 sec
[-----------------63%----              ] 1278 of 2000 complete in 1688.0 sec
[-----------------63%----              ] 1279 of 2000 complete in 1689.4 sec
[-----------------64%----              ] 1280 of 2000 complete in 1690.8 sec
[-----------------64%----              ] 1281 of 2000 complete in 1692.2 sec
[-----------------64%----              ] 1282 of 2000 complete in 1693.6 sec
[-----------------64%----              ] 1283 of 2000 complete in 1695.0 sec
[-----------------64%----              ] 1284 of 2000 complete in 1696.4 sec
[-----------------64%----              ] 1285 of 2000 complete in 1697.7 sec
[-----------------64%----              ] 1286 of 2000 complete in 1699.1 sec
[-----------------64%----              ] 1287 of 2000 complete in 1700.5 sec
[-----------------64%----              ] 1288 of 2000 complete in 1701.9 sec
[-----------------64%----              ] 1289 of 2000 complete in 1703.3 sec
[-----------------64%----              ] 1290 of 2000 complete in 1704.6 sec
[-----------------64%----              ] 1291 of 2000 complete in 1706.0 sec
[-----------------64%----              ] 1292 of 2000 complete in 1707.4 sec
[-----------------64%----              ] 1293 of 2000 complete in 1708.8 sec
[-----------------64%----              ] 1294 of 2000 complete in 1710.2 sec
[-----------------64%----              ] 1295 of 2000 complete in 1711.5 sec
[-----------------64%----              ] 1296 of 2000 complete in 1713.0 sec
[-----------------64%----              ] 1297 of 2000 complete in 1714.4 sec
[-----------------64%----              ] 1298 of 2000 complete in 1715.8 sec
[-----------------59%--                ] 1193 of 2000 complete in 1570.9 sec
[-----------------59%--                ] 1194 of 2000 complete in 1572.3 sec
[-----------------59%--                ] 1195 of 2000 complete in 1573.7 sec
[-----------------59%--                ] 1196 of 2000 complete in 1575.0 sec
[-----------------59%--                ] 1197 of 2000 complete in 1576.5 sec
[-----------------59%--                ] 1198 of 2000 complete in 1577.8 sec
[-----------------59%--                ] 1199 of 2000 complete in 1579.1 sec
[-----------------60%--                ] 1200 of 2000 complete in 1580.5 sec
[-----------------60%--                ] 1201 of 2000 complete in 1581.8 sec
[-----------------60%--                ] 1202 of 2000 complete in 1583.2 sec
[-----------------60%--                ] 1203 of 2000 complete in 1584.6 sec
[-----------------60%--                ] 1204 of 2000 complete in 1586.0 sec
[-----------------60%--                ] 1205 of 2000 complete in 1587.4 sec
[-----------------60%--                ] 1206 of 2000 complete in 1588.7 sec
[-----------------60%--                ] 1207 of 2000 complete in 1590.1 sec
[-----------------60%--                ] 1208 of 2000 complete in 1591.5 sec
[-----------------60%--                ] 1209 of 2000 complete in 1593.0 sec
[-----------------60%--                ] 1210 of 2000 complete in 1594.4 sec
[-----------------60%---               ] 1211 of 2000 complete in 1595.7 sec
[-----------------60%---               ] 1212 of 2000 complete in 1597.1 sec
[-----------------60%---               ] 1213 of 2000 complete in 1598.5 sec
[-----------------60%---               ] 1214 of 2000 complete in 1599.8 sec
[-----------------60%---               ] 1215 of 2000 complete in 1601.1 sec
[-----------------60%---               ] 1216 of 2000 complete in 1602.5 sec
[-----------------60%---               ] 1217 of 2000 complete in 1603.8 sec
[-----------------60%---               ] 1218 of 2000 complete in 1605.2 sec
[-----------------60%---               ] 1219 of 2000 complete in 1606.5 sec
[-----------------61%---               ] 1220 of 2000 complete in 1608.0 sec
[-----------------61%---               ] 1221 of 2000 complete in 1609.4 sec
[-----------------61%---               ] 1222 of 2000 complete in 1610.8 sec
[-----------------61%---               ] 1223 of 2000 complete in 1612.1 sec
[-----------------61%---               ] 1224 of 2000 complete in 1613.4 sec
[-----------------61%---               ] 1225 of 2000 complete in 1614.8 sec
[-----------------61%---               ] 1226 of 2000 complete in 1616.3 sec
[-----------------61%---               ] 1227 of 2000 complete in 1617.6 sec
[-----------------61%---               ] 1228 of 2000 complete in 1619.0 sec
[-----------------61%---               ] 1229 of 2000 complete in 1620.5 sec
[-----------------61%---               ] 1230 of 2000 complete in 1621.9 sec
[-----------------61%---               ] 1231 of 2000 complete in 1623.3 sec
[-----------------61%---               ] 1232 of 2000 complete in 1624.7 sec
[-----------------61%---               ] 1233 of 2000 complete in 1626.1 sec
[-----------------61%---               ] 1234 of 2000 complete in 1627.5 sec
[-----------------61%---               ] 1235 of 2000 complete in 1628.9 sec
[-----------------61%---               ] 1236 of 2000 complete in 1630.3 sec
[-----------------61%---               ] 1237 of 2000 complete in 1631.7 sec
[-----------------61%---               ] 1238 of 2000 complete in 1633.1 sec
[-----------------61%---               ] 1239 of 2000 complete in 1634.5 sec
[-----------------62%---               ] 1240 of 2000 complete in 1635.9 sec
[-----------------62%---               ] 1241 of 2000 complete in 1637.3 sec
[-----------------62%---               ] 1242 of 2000 complete in 1638.7 sec
[-----------------62%---               ] 1243 of 2000 complete in 1640.1 sec
[-----------------62%---               ] 1244 of 2000 complete in 1641.6 sec
[-----------------62%---               ] 1245 of 2000 complete in 1643.0 sec
[-----------------62%---               ] 1246 of 2000 complete in 1644.3 sec
[-----------------62%---               ] 1247 of 2000 complete in 1645.8 sec
[-----------------62%---               ] 1248 of 2000 complete in 1647.2 sec
[-----------------62%---               ] 1249 of 2000 complete in 1648.7 sec
[-----------------62%---               ] 1250 of 2000 complete in 1650.2 sec
[-----------------62%---               ] 1251 of 2000 complete in 1651.7 sec
[-----------------62%---               ] 1252 of 2000 complete in 1653.1 sec
[-----------------62%---               ] 1253 of 2000 complete in 1654.4 sec
[-----------------62%---               ] 1254 of 2000 complete in 1655.8 sec
[-----------------62%---               ] 1255 of 2000 complete in 1657.2 sec
[-----------------62%---               ] 1256 of 2000 complete in 1658.6 sec
[-----------------62%---               ] 1257 of 2000 complete in 1659.9 sec
[-----------------62%---               ] 1258 of 2000 complete in 1661.3 sec
[-----------------62%---               ] 1259 of 2000 complete in 1662.8 sec
[-----------------63%---               ] 1260 of 2000 complete in 1664.2 sec
[-----------------63%---               ] 1261 of 2000 complete in 1665.6 sec
[-----------------63%---               ] 1262 of 2000 complete in 1667.1 sec
[-----------------63%---               ] 1263 of 2000 complete in 1668.6 sec
[-----------------63%----              ] 1264 of 2000 complete in 1669.9 sec
[-----------------63%----              ] 1265 of 2000 complete in 1671.3 sec
[-----------------63%----              ] 1266 of 2000 complete in 1672.7 sec
[-----------------63%----              ] 1267 of 2000 complete in 1674.0 sec
[-----------------63%----              ] 1268 of 2000 complete in 1675.5 sec
[-----------------63%----              ] 1269 of 2000 complete in 1677.0 sec
[-----------------63%----              ] 1270 of 2000 complete in 1678.5 sec
[-----------------63%----              ] 1271 of 2000 complete in 1680.0 sec
[-----------------63%----              ] 1272 of 2000 complete in 1681.4 sec
[-----------------63%----              ] 1273 of 2000 complete in 1682.7 sec
[-----------------63%----              ] 1274 of 2000 complete in 1684.2 sec
[-----------------63%----              ] 1275 of 2000 complete in 1685.6 sec
[-----------------63%----              ] 1276 of 2000 complete in 1687.0 sec
[-----------------63%----              ] 1277 of 2000 complete in 1688.3 sec
[-----------------63%----              ] 1278 of 2000 complete in 1689.7 sec
[-----------------63%----              ] 1279 of 2000 complete in 1691.0 sec
[-----------------64%----              ] 1280 of 2000 complete in 1692.5 sec
[-----------------64%----              ] 1281 of 2000 complete in 1693.9 sec
[-----------------64%----              ] 1282 of 2000 complete in 1695.4 sec
[-----------------64%----              ] 1283 of 2000 complete in 1696.8 sec
[-----------------64%----              ] 1284 of 2000 complete in 1698.2 sec
[-----------------64%----              ] 1285 of 2000 complete in 1699.6 sec
[-----------------64%----              ] 1286 of 2000 complete in 1701.0 sec
[-----------------64%----              ] 1287 of 2000 complete in 1702.4 sec
[-----------------64%----              ] 1288 of 2000 complete in 1703.8 sec
[-----------------64%----              ] 1289 of 2000 complete in 1705.2 sec
[-----------------64%----              ] 1290 of 2000 complete in 1706.6 sec
[-----------------64%----              ] 1291 of 2000 complete in 1708.0 sec
[-----------------64%----              ] 1292 of 2000 complete in 1709.3 sec
[-----------------64%----              ] 1293 of 2000 complete in 1710.8 sec
[-----------------64%----              ] 1294 of 2000 complete in 1712.1 sec
[-----------------64%----              ] 1295 of 2000 complete in 1713.4 sec
[-----------------64%----              ] 1296 of 2000 complete in 1714.8 sec
[-----------------64%----              ] 1297 of 2000 complete in 1716.2 sec
[-----------------64%----              ] 1298 of 2000 complete in 1717.7 sec

[-----------------59%--                ] 1193 of 2000 complete in 1581.1 sec
[-----------------59%--                ] 1194 of 2000 complete in 1582.5 sec
[-----------------59%--                ] 1195 of 2000 complete in 1583.9 sec
[-----------------59%--                ] 1196 of 2000 complete in 1585.2 sec
[-----------------59%--                ] 1197 of 2000 complete in 1586.6 sec
[-----------------59%--                ] 1198 of 2000 complete in 1588.0 sec
[-----------------59%--                ] 1199 of 2000 complete in 1589.4 sec
[-----------------60%--                ] 1200 of 2000 complete in 1590.8 sec
[-----------------60%--                ] 1201 of 2000 complete in 1592.2 sec
[-----------------60%--                ] 1202 of 2000 complete in 1593.6 sec
[-----------------60%--                ] 1203 of 2000 complete in 1594.9 sec
[-----------------60%--                ] 1204 of 2000 complete in 1596.3 sec
[-----------------60%--                ] 1205 of 2000 complete in 1597.7 sec
[-----------------60%--                ] 1206 of 2000 complete in 1599.0 sec
[-----------------60%--                ] 1207 of 2000 complete in 1600.4 sec
[-----------------60%--                ] 1208 of 2000 complete in 1601.8 sec
[-----------------60%--                ] 1209 of 2000 complete in 1603.2 sec
[-----------------60%--                ] 1210 of 2000 complete in 1604.6 sec
[-----------------60%---               ] 1211 of 2000 complete in 1606.0 sec
[-----------------60%---               ] 1212 of 2000 complete in 1607.4 sec
[-----------------60%---               ] 1213 of 2000 complete in 1608.8 sec
[-----------------60%---               ] 1214 of 2000 complete in 1610.2 sec
[-----------------60%---               ] 1215 of 2000 complete in 1611.6 sec
[-----------------60%---               ] 1216 of 2000 complete in 1613.0 sec
[-----------------60%---               ] 1217 of 2000 complete in 1614.4 sec
[-----------------60%---               ] 1218 of 2000 complete in 1615.8 sec
[-----------------60%---               ] 1219 of 2000 complete in 1617.3 sec
[-----------------61%---               ] 1220 of 2000 complete in 1618.7 sec
[-----------------61%---               ] 1221 of 2000 complete in 1620.2 sec
[-----------------61%---               ] 1222 of 2000 complete in 1621.6 sec
[-----------------61%---               ] 1223 of 2000 complete in 1623.1 sec
[-----------------61%---               ] 1224 of 2000 complete in 1624.6 sec
[-----------------61%---               ] 1225 of 2000 complete in 1626.0 sec
[-----------------61%---               ] 1226 of 2000 complete in 1627.4 sec
[-----------------61%---               ] 1227 of 2000 complete in 1628.9 sec
[-----------------61%---               ] 1228 of 2000 complete in 1630.2 sec
[-----------------61%---               ] 1229 of 2000 complete in 1631.7 sec
[-----------------61%---               ] 1230 of 2000 complete in 1633.1 sec
[-----------------61%---               ] 1231 of 2000 complete in 1634.5 sec
[-----------------61%---               ] 1232 of 2000 complete in 1635.9 sec
[-----------------61%---               ] 1233 of 2000 complete in 1637.3 sec
[-----------------61%---               ] 1234 of 2000 complete in 1638.8 sec
[-----------------61%---               ] 1235 of 2000 complete in 1640.1 sec
[-----------------61%---               ] 1236 of 2000 complete in 1641.5 sec
[-----------------61%---               ] 1237 of 2000 complete in 1642.9 sec
[-----------------61%---               ] 1238 of 2000 complete in 1644.2 sec
[-----------------61%---               ] 1239 of 2000 complete in 1645.7 sec
[-----------------62%---               ] 1240 of 2000 complete in 1647.1 sec
[-----------------62%---               ] 1241 of 2000 complete in 1648.5 sec
[-----------------62%---               ] 1242 of 2000 complete in 1650.0 sec
[-----------------62%---               ] 1243 of 2000 complete in 1651.5 sec
[-----------------62%---               ] 1244 of 2000 complete in 1652.9 sec
[-----------------62%---               ] 1245 of 2000 complete in 1654.2 sec
[-----------------62%---               ] 1246 of 2000 complete in 1655.6 sec
[-----------------62%---               ] 1247 of 2000 complete in 1657.0 sec
[-----------------62%---               ] 1248 of 2000 complete in 1658.3 sec
[-----------------62%---               ] 1249 of 2000 complete in 1659.7 sec
[-----------------62%---               ] 1250 of 2000 complete in 1661.1 sec
[-----------------62%---               ] 1251 of 2000 complete in 1662.5 sec
[-----------------62%---               ] 1252 of 2000 complete in 1664.0 sec
[-----------------62%---               ] 1253 of 2000 complete in 1665.4 sec
[-----------------62%---               ] 1254 of 2000 complete in 1666.8 sec
[-----------------62%---               ] 1255 of 2000 complete in 1668.3 sec
[-----------------62%---               ] 1256 of 2000 complete in 1669.7 sec
[-----------------62%---               ] 1257 of 2000 complete in 1671.1 sec
[-----------------62%---               ] 1258 of 2000 complete in 1672.4 sec
[-----------------62%---               ] 1259 of 2000 complete in 1673.8 sec
[-----------------63%---               ] 1260 of 2000 complete in 1675.2 sec
[-----------------63%---               ] 1261 of 2000 complete in 1676.8 sec
[-----------------63%---               ] 1262 of 2000 complete in 1678.2 sec
[-----------------63%---               ] 1263 of 2000 complete in 1679.6 sec
[-----------------63%----              ] 1264 of 2000 complete in 1681.1 sec
[-----------------63%----              ] 1265 of 2000 complete in 1682.5 sec
[-----------------63%----              ] 1266 of 2000 complete in 1683.9 sec
[-----------------63%----              ] 1267 of 2000 complete in 1685.3 sec
[-----------------63%----              ] 1268 of 2000 complete in 1686.7 sec
[-----------------63%----              ] 1269 of 2000 complete in 1688.1 sec
[-----------------63%----              ] 1270 of 2000 complete in 1689.4 sec
[-----------------63%----              ] 1271 of 2000 complete in 1690.9 sec
[-----------------63%----              ] 1272 of 2000 complete in 1692.3 sec
[-----------------63%----              ] 1273 of 2000 complete in 1693.6 sec
[-----------------63%----              ] 1274 of 2000 complete in 1695.1 sec
[-----------------63%----              ] 1275 of 2000 complete in 1696.5 sec
[-----------------63%----              ] 1276 of 2000 complete in 1697.9 sec
[-----------------63%----              ] 1277 of 2000 complete in 1699.3 sec
[-----------------63%----              ] 1278 of 2000 complete in 1700.7 sec
[-----------------63%----              ] 1279 of 2000 complete in 1702.0 sec
[-----------------64%----              ] 1280 of 2000 complete in 1703.5 sec
[-----------------64%----              ] 1281 of 2000 complete in 1704.8 sec
[-----------------64%----              ] 1282 of 2000 complete in 1706.2 sec
[-----------------64%----              ] 1283 of 2000 complete in 1707.6 sec
[-----------------64%----              ] 1284 of 2000 complete in 1708.9 sec
[-----------------64%----              ] 1285 of 2000 complete in 1710.4 sec
[-----------------64%----              ] 1286 of 2000 complete in 1711.7 sec
[-----------------64%----              ] 1287 of 2000 complete in 1713.1 sec
[-----------------64%----              ] 1288 of 2000 complete in 1714.4 sec
[-----------------64%----              ] 1289 of 2000 complete in 1715.8 sec
[-----------------64%----              ] 1290 of 2000 complete in 1717.2 sec
[-----------------64%----              ] 1291 of 2000 complete in 1718.6 sec
[-----------------64%----              ] 1292 of 2000 complete in 1719.9 sec
[-----------------64%----              ] 1293 of 2000 complete in 1721.4 sec
[-----------------64%----              ] 1294 of 2000 complete in 1722.7 sec
[-----------------64%----              ] 1295 of 2000 complete in 1724.0 sec
[-----------------64%----              ] 1296 of 2000 complete in 1725.4 sec
[-----------------64%----              ] 1297 of 2000 complete in 1726.8 sec
[-----------------64%----              ] 1298 of 2000 complete in 1728.2 sec
[-----------------59%--                ] 1192 of 2000 complete in 1618.7 sec
[-----------------59%--                ] 1193 of 2000 complete in 1619.9 sec
[-----------------59%--                ] 1194 of 2000 complete in 1621.2 sec
[-----------------59%--                ] 1195 of 2000 complete in 1622.4 sec
[-----------------59%--                ] 1196 of 2000 complete in 1623.6 sec
[-----------------59%--                ] 1197 of 2000 complete in 1624.8 sec
[-----------------59%--                ] 1198 of 2000 complete in 1626.1 sec
[-----------------59%--                ] 1199 of 2000 complete in 1627.3 sec
[-----------------60%--                ] 1200 of 2000 complete in 1628.5 sec
[-----------------60%--                ] 1201 of 2000 complete in 1629.7 sec
[-----------------60%--                ] 1202 of 2000 complete in 1630.9 sec
[-----------------60%--                ] 1203 of 2000 complete in 1632.2 sec
[-----------------60%--                ] 1204 of 2000 complete in 1633.4 sec
[-----------------60%--                ] 1205 of 2000 complete in 1634.6 sec
[-----------------60%--                ] 1206 of 2000 complete in 1635.8 sec
[-----------------60%--                ] 1207 of 2000 complete in 1637.0 sec
[-----------------60%--                ] 1208 of 2000 complete in 1638.2 sec
[-----------------60%--                ] 1209 of 2000 complete in 1639.5 sec
[-----------------60%--                ] 1210 of 2000 complete in 1640.8 sec
[-----------------60%---               ] 1211 of 2000 complete in 1642.0 sec
[-----------------60%---               ] 1212 of 2000 complete in 1643.3 sec
[-----------------60%---               ] 1213 of 2000 complete in 1644.5 sec
[-----------------60%---               ] 1214 of 2000 complete in 1645.9 sec
[-----------------60%---               ] 1215 of 2000 complete in 1647.2 sec
[-----------------60%---               ] 1216 of 2000 complete in 1648.5 sec
[-----------------60%---               ] 1217 of 2000 complete in 1649.9 sec
[-----------------60%---               ] 1218 of 2000 complete in 1651.3 sec
[-----------------60%---               ] 1219 of 2000 complete in 1652.5 sec
[-----------------61%---               ] 1220 of 2000 complete in 1653.8 sec
[-----------------61%---               ] 1221 of 2000 complete in 1655.0 sec
[-----------------61%---               ] 1222 of 2000 complete in 1656.2 sec
[-----------------61%---               ] 1223 of 2000 complete in 1657.5 sec
[-----------------61%---               ] 1224 of 2000 complete in 1658.7 sec
[-----------------61%---               ] 1225 of 2000 complete in 1660.0 sec
[-----------------61%---               ] 1226 of 2000 complete in 1661.2 sec
[-----------------61%---               ] 1227 of 2000 complete in 1662.6 sec
[-----------------61%---               ] 1228 of 2000 complete in 1664.0 sec
[-----------------61%---               ] 1229 of 2000 complete in 1665.3 sec
[-----------------61%---               ] 1230 of 2000 complete in 1666.4 sec
[-----------------61%---               ] 1231 of 2000 complete in 1667.6 sec
[-----------------61%---               ] 1232 of 2000 complete in 1669.0 sec
[-----------------61%---               ] 1233 of 2000 complete in 1670.3 sec
[-----------------61%---               ] 1234 of 2000 complete in 1671.5 sec
[-----------------61%---               ] 1235 of 2000 complete in 1672.7 sec
[-----------------61%---               ] 1236 of 2000 complete in 1674.0 sec
[-----------------61%---               ] 1237 of 2000 complete in 1675.2 sec
[-----------------61%---               ] 1238 of 2000 complete in 1676.6 sec
[-----------------61%---               ] 1239 of 2000 complete in 1678.0 sec
[-----------------62%---               ] 1240 of 2000 complete in 1679.3 sec
[-----------------62%---               ] 1241 of 2000 complete in 1680.6 sec
[-----------------62%---               ] 1242 of 2000 complete in 1681.8 sec
[-----------------62%---               ] 1243 of 2000 complete in 1683.1 sec
[-----------------62%---               ] 1244 of 2000 complete in 1684.3 sec
[-----------------62%---               ] 1245 of 2000 complete in 1685.6 sec
[-----------------62%---               ] 1246 of 2000 complete in 1686.8 sec
[-----------------62%---               ] 1247 of 2000 complete in 1688.1 sec
[-----------------62%---               ] 1248 of 2000 complete in 1689.4 sec
[-----------------62%---               ] 1249 of 2000 complete in 1690.6 sec
[-----------------62%---               ] 1250 of 2000 complete in 1691.8 sec
[-----------------62%---               ] 1251 of 2000 complete in 1693.1 sec
[-----------------62%---               ] 1252 of 2000 complete in 1694.4 sec
[-----------------62%---               ] 1253 of 2000 complete in 1695.7 sec
[-----------------62%---               ] 1254 of 2000 complete in 1696.9 sec
[-----------------62%---               ] 1255 of 2000 complete in 1698.2 sec
[-----------------62%---               ] 1256 of 2000 complete in 1699.4 sec
[-----------------62%---               ] 1257 of 2000 complete in 1700.7 sec
[-----------------62%---               ] 1258 of 2000 complete in 1702.0 sec
[-----------------62%---               ] 1259 of 2000 complete in 1703.3 sec
[-----------------63%---               ] 1260 of 2000 complete in 1704.7 sec
[-----------------63%---               ] 1261 of 2000 complete in 1706.1 sec
[-----------------63%---               ] 1262 of 2000 complete in 1707.4 sec
[-----------------63%---               ] 1263 of 2000 complete in 1708.7 sec
[-----------------63%----              ] 1264 of 2000 complete in 1710.0 sec
[-----------------63%----              ] 1265 of 2000 complete in 1711.2 sec
[-----------------63%----              ] 1266 of 2000 complete in 1712.4 sec
[-----------------63%----              ] 1267 of 2000 complete in 1713.7 sec
[-----------------63%----              ] 1268 of 2000 complete in 1714.9 sec
[-----------------63%----              ] 1269 of 2000 complete in 1716.2 sec
[-----------------63%----              ] 1270 of 2000 complete in 1717.5 sec
[-----------------63%----              ] 1271 of 2000 complete in 1718.8 sec
[-----------------63%----              ] 1272 of 2000 complete in 1720.1 sec
[-----------------63%----              ] 1273 of 2000 complete in 1721.3 sec
[-----------------63%----              ] 1274 of 2000 complete in 1722.6 sec
[-----------------63%----              ] 1275 of 2000 complete in 1723.9 sec
[-----------------63%----              ] 1276 of 2000 complete in 1725.2 sec
[-----------------63%----              ] 1277 of 2000 complete in 1726.4 sec
[-----------------63%----              ] 1278 of 2000 complete in 1727.7 sec
[-----------------63%----              ] 1279 of 2000 complete in 1729.0 sec
[-----------------64%----              ] 1280 of 2000 complete in 1730.2 sec
[-----------------64%----              ] 1281 of 2000 complete in 1731.5 sec
[-----------------64%----              ] 1282 of 2000 complete in 1732.7 sec
[-----------------64%----              ] 1283 of 2000 complete in 1733.9 sec
[-----------------64%----              ] 1284 of 2000 complete in 1735.3 sec
[-----------------64%----              ] 1285 of 2000 complete in 1736.6 sec
[-----------------64%----              ] 1286 of 2000 complete in 1738.0 sec
[-----------------64%----              ] 1287 of 2000 complete in 1739.3 sec
[-----------------64%----              ] 1288 of 2000 complete in 1740.7 sec
[-----------------64%----              ] 1289 of 2000 complete in 1742.0 sec
[-----------------64%----              ] 1290 of 2000 complete in 1743.3 sec
[-----------------64%----              ] 1291 of 2000 complete in 1744.7 sec
[-----------------64%----              ] 1292 of 2000 complete in 1746.0 sec
[-----------------64%----              ] 1293 of 2000 complete in 1747.3 sec
[-----------------64%----              ] 1294 of 2000 complete in 1748.6 sec
[-----------------64%----              ] 1295 of 2000 complete in 1749.9 sec
[-----------------64%----              ] 1296 of 2000 complete in 1751.2 sec
[-----------------64%----              ] 1297 of 2000 complete in 1752.5 sec

[-----------------64%----              ] 1299 of 2000 complete in 1717.2 sec
[-----------------65%----              ] 1300 of 2000 complete in 1718.6 sec
[-----------------65%----              ] 1301 of 2000 complete in 1720.0 sec
[-----------------65%----              ] 1302 of 2000 complete in 1721.4 sec
[-----------------65%----              ] 1303 of 2000 complete in 1722.8 sec
[-----------------65%----              ] 1304 of 2000 complete in 1724.2 sec
[-----------------65%----              ] 1305 of 2000 complete in 1725.6 sec
[-----------------65%----              ] 1306 of 2000 complete in 1727.0 sec
[-----------------65%----              ] 1307 of 2000 complete in 1728.4 sec
[-----------------65%----              ] 1308 of 2000 complete in 1729.7 sec
[-----------------65%----              ] 1309 of 2000 complete in 1731.1 sec
[-----------------65%----              ] 1310 of 2000 complete in 1732.5 sec
[-----------------65%----              ] 1311 of 2000 complete in 1733.9 sec
[-----------------65%----              ] 1312 of 2000 complete in 1735.3 sec
[-----------------65%----              ] 1313 of 2000 complete in 1736.7 sec
[-----------------65%----              ] 1314 of 2000 complete in 1738.1 sec
[-----------------65%----              ] 1315 of 2000 complete in 1739.4 sec
[-----------------65%-----             ] 1316 of 2000 complete in 1740.8 sec
[-----------------65%-----             ] 1317 of 2000 complete in 1742.2 sec
[-----------------65%-----             ] 1318 of 2000 complete in 1743.6 sec
[-----------------65%-----             ] 1319 of 2000 complete in 1744.9 sec
[-----------------66%-----             ] 1320 of 2000 complete in 1746.3 sec
[-----------------66%-----             ] 1321 of 2000 complete in 1747.6 sec
[-----------------66%-----             ] 1322 of 2000 complete in 1748.9 sec
[-----------------66%-----             ] 1323 of 2000 complete in 1750.4 sec
[-----------------66%-----             ] 1324 of 2000 complete in 1751.7 sec
[-----------------66%-----             ] 1325 of 2000 complete in 1753.1 sec
[-----------------66%-----             ] 1326 of 2000 complete in 1754.4 sec
[-----------------66%-----             ] 1327 of 2000 complete in 1755.8 sec
[-----------------66%-----             ] 1328 of 2000 complete in 1757.1 sec
[-----------------66%-----             ] 1329 of 2000 complete in 1758.5 sec
[-----------------66%-----             ] 1330 of 2000 complete in 1759.8 sec
[-----------------66%-----             ] 1331 of 2000 complete in 1761.2 sec
[-----------------66%-----             ] 1332 of 2000 complete in 1762.5 sec
[-----------------66%-----             ] 1333 of 2000 complete in 1763.9 sec
[-----------------66%-----             ] 1334 of 2000 complete in 1765.2 sec
[-----------------66%-----             ] 1335 of 2000 complete in 1766.6 sec
[-----------------66%-----             ] 1336 of 2000 complete in 1768.0 sec
[-----------------66%-----             ] 1337 of 2000 complete in 1769.5 sec
[-----------------66%-----             ] 1338 of 2000 complete in 1770.9 sec
[-----------------66%-----             ] 1339 of 2000 complete in 1772.3 sec
[-----------------67%-----             ] 1340 of 2000 complete in 1773.6 sec
[-----------------67%-----             ] 1341 of 2000 complete in 1775.1 sec
[-----------------67%-----             ] 1342 of 2000 complete in 1776.5 sec
[-----------------67%-----             ] 1343 of 2000 complete in 1778.0 sec
[-----------------67%-----             ] 1344 of 2000 complete in 1779.4 sec
[-----------------67%-----             ] 1345 of 2000 complete in 1780.7 sec
[-----------------67%-----             ] 1346 of 2000 complete in 1782.2 sec
[-----------------67%-----             ] 1347 of 2000 complete in 1783.5 sec
[-----------------67%-----             ] 1348 of 2000 complete in 1785.0 sec
[-----------------67%-----             ] 1349 of 2000 complete in 1786.4 sec
[-----------------67%-----             ] 1350 of 2000 complete in 1787.7 sec
[-----------------67%-----             ] 1351 of 2000 complete in 1789.2 sec
[-----------------67%-----             ] 1352 of 2000 complete in 1790.6 sec
[-----------------67%-----             ] 1353 of 2000 complete in 1792.0 sec
[-----------------67%-----             ] 1354 of 2000 complete in 1793.4 sec
[-----------------67%-----             ] 1355 of 2000 complete in 1794.8 sec
[-----------------67%-----             ] 1356 of 2000 complete in 1796.2 sec
[-----------------67%-----             ] 1357 of 2000 complete in 1797.8 sec
[-----------------67%-----             ] 1358 of 2000 complete in 1799.2 sec
[-----------------67%-----             ] 1359 of 2000 complete in 1800.6 sec
[-----------------68%-----             ] 1360 of 2000 complete in 1802.0 sec
[-----------------68%-----             ] 1361 of 2000 complete in 1803.4 sec
[-----------------68%-----             ] 1362 of 2000 complete in 1804.8 sec
[-----------------68%-----             ] 1363 of 2000 complete in 1806.5 sec
[-----------------68%-----             ] 1364 of 2000 complete in 1808.0 sec
[-----------------68%-----             ] 1365 of 2000 complete in 1809.5 sec
[-----------------68%-----             ] 1366 of 2000 complete in 1811.0 sec
[-----------------68%-----             ] 1367 of 2000 complete in 1812.3 sec
[-----------------68%-----             ] 1368 of 2000 complete in 1813.9 sec
[-----------------68%------            ] 1369 of 2000 complete in 1815.4 sec
[-----------------68%------            ] 1370 of 2000 complete in 1816.8 sec
[-----------------68%------            ] 1371 of 2000 complete in 1818.2 sec
[-----------------68%------            ] 1372 of 2000 complete in 1819.8 sec
[-----------------68%------            ] 1373 of 2000 complete in 1821.4 sec
[-----------------68%------            ] 1374 of 2000 complete in 1822.8 sec
[-----------------68%------            ] 1375 of 2000 complete in 1824.4 sec
[-----------------68%------            ] 1376 of 2000 complete in 1825.9 sec
[-----------------68%------            ] 1377 of 2000 complete in 1827.2 sec
[-----------------68%------            ] 1378 of 2000 complete in 1828.6 sec
[-----------------68%------            ] 1379 of 2000 complete in 1830.1 sec
[-----------------69%------            ] 1380 of 2000 complete in 1831.6 sec
[-----------------69%------            ] 1381 of 2000 complete in 1833.1 sec
[-----------------69%------            ] 1382 of 2000 complete in 1834.4 sec
[-----------------69%------            ] 1383 of 2000 complete in 1835.9 sec
[-----------------69%------            ] 1384 of 2000 complete in 1837.3 sec
[-----------------69%------            ] 1385 of 2000 complete in 1838.7 sec
[-----------------69%------            ] 1386 of 2000 complete in 1840.2 sec
[-----------------69%------            ] 1387 of 2000 complete in 1841.6 sec
[-----------------69%------            ] 1388 of 2000 complete in 1843.0 sec
[-----------------69%------            ] 1389 of 2000 complete in 1844.4 sec
[-----------------69%------            ] 1390 of 2000 complete in 1845.8 sec
[-----------------69%------            ] 1391 of 2000 complete in 1847.2 sec
[-----------------69%------            ] 1392 of 2000 complete in 1848.5 sec
[-----------------69%------            ] 1393 of 2000 complete in 1849.9 sec
[-----------------69%------            ] 1394 of 2000 complete in 1851.3 sec
[-----------------69%------            ] 1395 of 2000 complete in 1852.7 sec
[-----------------69%------            ] 1396 of 2000 complete in 1854.1 sec
[-----------------69%------            ] 1397 of 2000 complete in 1855.5 sec
[-----------------69%------            ] 1398 of 2000 complete in 1856.9 sec
[-----------------69%------            ] 1399 of 2000 complete in 1858.4 sec
[-----------------70%------            ] 1400 of 2000 complete in 1859.8 sec
[-----------------70%------            ] 1401 of 2000 complete in 1861.2 sec
[-----------------70%------            ] 1402 of 2000 complete in 1862.7 sec
[-----------------70%------            ] 1403 of 2000 complete in 1864.2 sec
[-----------------70%------            ] 1404 of 2000 complete in 1865.6 sec
[-----------------64%----              ] 1299 of 2000 complete in 1719.0 sec
[-----------------65%----              ] 1300 of 2000 complete in 1720.4 sec
[-----------------65%----              ] 1301 of 2000 complete in 1721.7 sec
[-----------------65%----              ] 1302 of 2000 complete in 1723.1 sec
[-----------------65%----              ] 1303 of 2000 complete in 1724.5 sec
[-----------------65%----              ] 1304 of 2000 complete in 1726.0 sec
[-----------------65%----              ] 1305 of 2000 complete in 1727.3 sec
[-----------------65%----              ] 1306 of 2000 complete in 1728.8 sec
[-----------------65%----              ] 1307 of 2000 complete in 1730.2 sec
[-----------------65%----              ] 1308 of 2000 complete in 1731.5 sec
[-----------------65%----              ] 1309 of 2000 complete in 1732.9 sec
[-----------------65%----              ] 1310 of 2000 complete in 1734.3 sec
[-----------------65%----              ] 1311 of 2000 complete in 1735.6 sec
[-----------------65%----              ] 1312 of 2000 complete in 1737.0 sec
[-----------------65%----              ] 1313 of 2000 complete in 1738.3 sec
[-----------------65%----              ] 1314 of 2000 complete in 1739.7 sec
[-----------------65%----              ] 1315 of 2000 complete in 1741.0 sec
[-----------------65%-----             ] 1316 of 2000 complete in 1742.4 sec
[-----------------65%-----             ] 1317 of 2000 complete in 1743.8 sec
[-----------------65%-----             ] 1318 of 2000 complete in 1745.1 sec
[-----------------65%-----             ] 1319 of 2000 complete in 1746.5 sec
[-----------------66%-----             ] 1320 of 2000 complete in 1747.9 sec
[-----------------66%-----             ] 1321 of 2000 complete in 1749.3 sec
[-----------------66%-----             ] 1322 of 2000 complete in 1750.7 sec
[-----------------66%-----             ] 1323 of 2000 complete in 1752.1 sec
[-----------------66%-----             ] 1324 of 2000 complete in 1753.5 sec
[-----------------66%-----             ] 1325 of 2000 complete in 1754.9 sec
[-----------------66%-----             ] 1326 of 2000 complete in 1756.2 sec
[-----------------66%-----             ] 1327 of 2000 complete in 1757.7 sec
[-----------------66%-----             ] 1328 of 2000 complete in 1759.1 sec
[-----------------66%-----             ] 1329 of 2000 complete in 1760.5 sec
[-----------------66%-----             ] 1330 of 2000 complete in 1761.8 sec
[-----------------66%-----             ] 1331 of 2000 complete in 1763.2 sec
[-----------------66%-----             ] 1332 of 2000 complete in 1764.6 sec
[-----------------66%-----             ] 1333 of 2000 complete in 1765.9 sec
[-----------------66%-----             ] 1334 of 2000 complete in 1767.3 sec
[-----------------66%-----             ] 1335 of 2000 complete in 1768.7 sec
[-----------------66%-----             ] 1336 of 2000 complete in 1770.3 sec
[-----------------66%-----             ] 1337 of 2000 complete in 1771.7 sec
[-----------------66%-----             ] 1338 of 2000 complete in 1773.0 sec
[-----------------66%-----             ] 1339 of 2000 complete in 1774.4 sec
[-----------------67%-----             ] 1340 of 2000 complete in 1775.8 sec
[-----------------67%-----             ] 1341 of 2000 complete in 1777.4 sec
[-----------------67%-----             ] 1342 of 2000 complete in 1778.9 sec
[-----------------67%-----             ] 1343 of 2000 complete in 1780.3 sec
[-----------------67%-----             ] 1344 of 2000 complete in 1781.7 sec
[-----------------67%-----             ] 1345 of 2000 complete in 1783.2 sec
[-----------------67%-----             ] 1346 of 2000 complete in 1784.7 sec
[-----------------67%-----             ] 1347 of 2000 complete in 1786.2 sec
[-----------------67%-----             ] 1348 of 2000 complete in 1787.7 sec
[-----------------67%-----             ] 1349 of 2000 complete in 1789.2 sec
[-----------------67%-----             ] 1350 of 2000 complete in 1790.7 sec
[-----------------67%-----             ] 1351 of 2000 complete in 1792.1 sec
[-----------------67%-----             ] 1352 of 2000 complete in 1793.5 sec
[-----------------67%-----             ] 1353 of 2000 complete in 1794.9 sec
[-----------------67%-----             ] 1354 of 2000 complete in 1796.4 sec
[-----------------67%-----             ] 1355 of 2000 complete in 1797.9 sec
[-----------------67%-----             ] 1356 of 2000 complete in 1799.4 sec
[-----------------67%-----             ] 1357 of 2000 complete in 1800.9 sec
[-----------------67%-----             ] 1358 of 2000 complete in 1802.2 sec
[-----------------67%-----             ] 1359 of 2000 complete in 1803.7 sec
[-----------------68%-----             ] 1360 of 2000 complete in 1805.3 sec
[-----------------68%-----             ] 1361 of 2000 complete in 1806.8 sec
[-----------------68%-----             ] 1362 of 2000 complete in 1808.3 sec
[-----------------68%-----             ] 1363 of 2000 complete in 1809.8 sec
[-----------------68%-----             ] 1364 of 2000 complete in 1811.3 sec
[-----------------68%-----             ] 1365 of 2000 complete in 1812.7 sec
[-----------------68%-----             ] 1366 of 2000 complete in 1814.3 sec
[-----------------68%-----             ] 1367 of 2000 complete in 1815.9 sec
[-----------------68%-----             ] 1368 of 2000 complete in 1817.3 sec
[-----------------68%------            ] 1369 of 2000 complete in 1818.8 sec
[-----------------68%------            ] 1370 of 2000 complete in 1820.4 sec
[-----------------68%------            ] 1371 of 2000 complete in 1821.9 sec
[-----------------68%------            ] 1372 of 2000 complete in 1823.4 sec
[-----------------68%------            ] 1373 of 2000 complete in 1824.9 sec
[-----------------68%------            ] 1374 of 2000 complete in 1826.3 sec
[-----------------68%------            ] 1375 of 2000 complete in 1827.8 sec
[-----------------68%------            ] 1376 of 2000 complete in 1829.2 sec
[-----------------68%------            ] 1377 of 2000 complete in 1830.6 sec
[-----------------68%------            ] 1378 of 2000 complete in 1832.2 sec
[-----------------68%------            ] 1379 of 2000 complete in 1833.6 sec
[-----------------69%------            ] 1380 of 2000 complete in 1835.0 sec
[-----------------69%------            ] 1381 of 2000 complete in 1836.5 sec
[-----------------69%------            ] 1382 of 2000 complete in 1837.9 sec
[-----------------69%------            ] 1383 of 2000 complete in 1839.3 sec
[-----------------69%------            ] 1384 of 2000 complete in 1840.6 sec
[-----------------69%------            ] 1385 of 2000 complete in 1842.0 sec
[-----------------69%------            ] 1386 of 2000 complete in 1843.4 sec
[-----------------69%------            ] 1387 of 2000 complete in 1844.7 sec
[-----------------69%------            ] 1388 of 2000 complete in 1846.1 sec
[-----------------69%------            ] 1389 of 2000 complete in 1847.6 sec
[-----------------69%------            ] 1390 of 2000 complete in 1849.0 sec
[-----------------69%------            ] 1391 of 2000 complete in 1850.4 sec
[-----------------69%------            ] 1392 of 2000 complete in 1851.8 sec
[-----------------69%------            ] 1393 of 2000 complete in 1853.1 sec
[-----------------69%------            ] 1394 of 2000 complete in 1854.6 sec
[-----------------69%------            ] 1395 of 2000 complete in 1856.1 sec
[-----------------69%------            ] 1396 of 2000 complete in 1857.6 sec
[-----------------69%------            ] 1397 of 2000 complete in 1859.1 sec
[-----------------69%------            ] 1398 of 2000 complete in 1860.5 sec
[-----------------69%------            ] 1399 of 2000 complete in 1861.9 sec
[-----------------70%------            ] 1400 of 2000 complete in 1863.4 sec
[-----------------70%------            ] 1401 of 2000 complete in 1864.8 sec
[-----------------70%------            ] 1402 of 2000 complete in 1866.2 sec
[-----------------70%------            ] 1403 of 2000 complete in 1867.5 sec
[-----------------70%------            ] 1404 of 2000 complete in 1868.9 sec

[-----------------64%----              ] 1299 of 2000 complete in 1729.5 sec
[-----------------65%----              ] 1300 of 2000 complete in 1730.8 sec
[-----------------65%----              ] 1301 of 2000 complete in 1732.1 sec
[-----------------65%----              ] 1302 of 2000 complete in 1733.4 sec
[-----------------65%----              ] 1303 of 2000 complete in 1734.8 sec
[-----------------65%----              ] 1304 of 2000 complete in 1736.1 sec
[-----------------65%----              ] 1305 of 2000 complete in 1737.5 sec
[-----------------65%----              ] 1306 of 2000 complete in 1738.8 sec
[-----------------65%----              ] 1307 of 2000 complete in 1740.2 sec
[-----------------65%----              ] 1308 of 2000 complete in 1741.6 sec
[-----------------65%----              ] 1309 of 2000 complete in 1742.9 sec
[-----------------65%----              ] 1310 of 2000 complete in 1744.3 sec
[-----------------65%----              ] 1311 of 2000 complete in 1745.6 sec
[-----------------65%----              ] 1312 of 2000 complete in 1746.9 sec
[-----------------65%----              ] 1313 of 2000 complete in 1748.3 sec
[-----------------65%----              ] 1314 of 2000 complete in 1749.6 sec
[-----------------65%----              ] 1315 of 2000 complete in 1750.9 sec
[-----------------65%-----             ] 1316 of 2000 complete in 1752.3 sec
[-----------------65%-----             ] 1317 of 2000 complete in 1753.6 sec
[-----------------65%-----             ] 1318 of 2000 complete in 1755.0 sec
[-----------------65%-----             ] 1319 of 2000 complete in 1756.3 sec
[-----------------66%-----             ] 1320 of 2000 complete in 1757.6 sec
[-----------------66%-----             ] 1321 of 2000 complete in 1759.0 sec
[-----------------66%-----             ] 1322 of 2000 complete in 1760.3 sec
[-----------------66%-----             ] 1323 of 2000 complete in 1761.7 sec
[-----------------66%-----             ] 1324 of 2000 complete in 1763.0 sec
[-----------------66%-----             ] 1325 of 2000 complete in 1764.4 sec
[-----------------66%-----             ] 1326 of 2000 complete in 1765.7 sec
[-----------------66%-----             ] 1327 of 2000 complete in 1767.0 sec
[-----------------66%-----             ] 1328 of 2000 complete in 1768.4 sec
[-----------------66%-----             ] 1329 of 2000 complete in 1769.9 sec
[-----------------66%-----             ] 1330 of 2000 complete in 1771.3 sec
[-----------------66%-----             ] 1331 of 2000 complete in 1772.6 sec
[-----------------66%-----             ] 1332 of 2000 complete in 1774.0 sec
[-----------------66%-----             ] 1333 of 2000 complete in 1775.5 sec
[-----------------66%-----             ] 1334 of 2000 complete in 1777.0 sec
[-----------------66%-----             ] 1335 of 2000 complete in 1778.3 sec
[-----------------66%-----             ] 1336 of 2000 complete in 1779.6 sec
[-----------------66%-----             ] 1337 of 2000 complete in 1781.0 sec
[-----------------66%-----             ] 1338 of 2000 complete in 1782.3 sec
[-----------------66%-----             ] 1339 of 2000 complete in 1783.7 sec
[-----------------67%-----             ] 1340 of 2000 complete in 1785.2 sec
[-----------------67%-----             ] 1341 of 2000 complete in 1786.6 sec
[-----------------67%-----             ] 1342 of 2000 complete in 1788.1 sec
[-----------------67%-----             ] 1343 of 2000 complete in 1789.5 sec
[-----------------67%-----             ] 1344 of 2000 complete in 1790.8 sec
[-----------------67%-----             ] 1345 of 2000 complete in 1792.2 sec
[-----------------67%-----             ] 1346 of 2000 complete in 1793.6 sec
[-----------------67%-----             ] 1347 of 2000 complete in 1795.0 sec
[-----------------67%-----             ] 1348 of 2000 complete in 1796.3 sec
[-----------------67%-----             ] 1349 of 2000 complete in 1797.7 sec
[-----------------67%-----             ] 1350 of 2000 complete in 1799.1 sec
[-----------------67%-----             ] 1351 of 2000 complete in 1800.5 sec
[-----------------67%-----             ] 1352 of 2000 complete in 1801.8 sec
[-----------------67%-----             ] 1353 of 2000 complete in 1803.3 sec
[-----------------67%-----             ] 1354 of 2000 complete in 1804.6 sec
[-----------------67%-----             ] 1355 of 2000 complete in 1806.2 sec
[-----------------67%-----             ] 1356 of 2000 complete in 1807.5 sec
[-----------------67%-----             ] 1357 of 2000 complete in 1809.1 sec
[-----------------67%-----             ] 1358 of 2000 complete in 1810.5 sec
[-----------------67%-----             ] 1359 of 2000 complete in 1811.8 sec
[-----------------68%-----             ] 1360 of 2000 complete in 1813.2 sec
[-----------------68%-----             ] 1361 of 2000 complete in 1814.6 sec
[-----------------68%-----             ] 1362 of 2000 complete in 1816.0 sec
[-----------------68%-----             ] 1363 of 2000 complete in 1817.4 sec
[-----------------68%-----             ] 1364 of 2000 complete in 1818.7 sec
[-----------------68%-----             ] 1365 of 2000 complete in 1820.1 sec
[-----------------68%-----             ] 1366 of 2000 complete in 1821.5 sec
[-----------------68%-----             ] 1367 of 2000 complete in 1822.9 sec
[-----------------68%-----             ] 1368 of 2000 complete in 1824.2 sec
[-----------------68%------            ] 1369 of 2000 complete in 1825.6 sec
[-----------------68%------            ] 1370 of 2000 complete in 1826.9 sec
[-----------------68%------            ] 1371 of 2000 complete in 1828.3 sec
[-----------------68%------            ] 1372 of 2000 complete in 1829.6 sec
[-----------------68%------            ] 1373 of 2000 complete in 1830.9 sec
[-----------------68%------            ] 1374 of 2000 complete in 1832.4 sec
[-----------------68%------            ] 1375 of 2000 complete in 1833.7 sec
[-----------------68%------            ] 1376 of 2000 complete in 1835.1 sec
[-----------------68%------            ] 1377 of 2000 complete in 1836.4 sec
[-----------------68%------            ] 1378 of 2000 complete in 1837.8 sec
[-----------------68%------            ] 1379 of 2000 complete in 1839.1 sec
[-----------------69%------            ] 1380 of 2000 complete in 1840.4 sec
[-----------------69%------            ] 1381 of 2000 complete in 1841.7 sec
[-----------------69%------            ] 1382 of 2000 complete in 1843.0 sec
[-----------------69%------            ] 1383 of 2000 complete in 1844.3 sec
[-----------------69%------            ] 1384 of 2000 complete in 1845.7 sec
[-----------------69%------            ] 1385 of 2000 complete in 1847.0 sec
[-----------------69%------            ] 1386 of 2000 complete in 1848.3 sec
[-----------------69%------            ] 1387 of 2000 complete in 1849.7 sec
[-----------------69%------            ] 1388 of 2000 complete in 1851.0 sec
[-----------------69%------            ] 1389 of 2000 complete in 1852.4 sec
[-----------------69%------            ] 1390 of 2000 complete in 1853.7 sec
[-----------------69%------            ] 1391 of 2000 complete in 1855.0 sec
[-----------------69%------            ] 1392 of 2000 complete in 1856.4 sec
[-----------------69%------            ] 1393 of 2000 complete in 1857.8 sec
[-----------------69%------            ] 1394 of 2000 complete in 1859.2 sec
[-----------------69%------            ] 1395 of 2000 complete in 1860.7 sec
[-----------------69%------            ] 1396 of 2000 complete in 1862.2 sec
[-----------------69%------            ] 1397 of 2000 complete in 1863.6 sec
[-----------------69%------            ] 1398 of 2000 complete in 1865.0 sec
[-----------------69%------            ] 1399 of 2000 complete in 1866.4 sec
[-----------------70%------            ] 1400 of 2000 complete in 1867.8 sec
[-----------------70%------            ] 1401 of 2000 complete in 1869.1 sec
[-----------------70%------            ] 1402 of 2000 complete in 1870.5 sec
[-----------------70%------            ] 1403 of 2000 complete in 1871.9 sec
[-----------------70%------            ] 1404 of 2000 complete in 1873.4 sec
[-----------------64%----              ] 1298 of 2000 complete in 1753.8 sec
[-----------------64%----              ] 1299 of 2000 complete in 1755.1 sec
[-----------------65%----              ] 1300 of 2000 complete in 1756.4 sec
[-----------------65%----              ] 1301 of 2000 complete in 1757.6 sec
[-----------------65%----              ] 1302 of 2000 complete in 1759.0 sec
[-----------------65%----              ] 1303 of 2000 complete in 1760.2 sec
[-----------------65%----              ] 1304 of 2000 complete in 1761.5 sec
[-----------------65%----              ] 1305 of 2000 complete in 1762.9 sec
[-----------------65%----              ] 1306 of 2000 complete in 1764.1 sec
[-----------------65%----              ] 1307 of 2000 complete in 1765.5 sec
[-----------------65%----              ] 1308 of 2000 complete in 1766.8 sec
[-----------------65%----              ] 1309 of 2000 complete in 1768.1 sec
[-----------------65%----              ] 1310 of 2000 complete in 1769.6 sec
[-----------------65%----              ] 1311 of 2000 complete in 1771.0 sec
[-----------------65%----              ] 1312 of 2000 complete in 1772.3 sec
[-----------------65%----              ] 1313 of 2000 complete in 1773.7 sec
[-----------------65%----              ] 1314 of 2000 complete in 1775.1 sec
[-----------------65%----              ] 1315 of 2000 complete in 1776.5 sec
[-----------------65%-----             ] 1316 of 2000 complete in 1777.9 sec
[-----------------65%-----             ] 1317 of 2000 complete in 1779.3 sec
[-----------------65%-----             ] 1318 of 2000 complete in 1780.6 sec
[-----------------65%-----             ] 1319 of 2000 complete in 1782.1 sec
[-----------------66%-----             ] 1320 of 2000 complete in 1783.4 sec
[-----------------66%-----             ] 1321 of 2000 complete in 1785.0 sec
[-----------------66%-----             ] 1322 of 2000 complete in 1786.3 sec
[-----------------66%-----             ] 1323 of 2000 complete in 1787.7 sec
[-----------------66%-----             ] 1324 of 2000 complete in 1789.1 sec
[-----------------66%-----             ] 1325 of 2000 complete in 1790.5 sec
[-----------------66%-----             ] 1326 of 2000 complete in 1791.8 sec
[-----------------66%-----             ] 1327 of 2000 complete in 1793.2 sec
[-----------------66%-----             ] 1328 of 2000 complete in 1794.6 sec
[-----------------66%-----             ] 1329 of 2000 complete in 1796.0 sec
[-----------------66%-----             ] 1330 of 2000 complete in 1797.6 sec
[-----------------66%-----             ] 1331 of 2000 complete in 1799.0 sec
[-----------------66%-----             ] 1332 of 2000 complete in 1800.4 sec
[-----------------66%-----             ] 1333 of 2000 complete in 1801.7 sec
[-----------------66%-----             ] 1334 of 2000 complete in 1803.1 sec
[-----------------66%-----             ] 1335 of 2000 complete in 1804.5 sec
[-----------------66%-----             ] 1336 of 2000 complete in 1806.2 sec
[-----------------66%-----             ] 1337 of 2000 complete in 1807.6 sec
[-----------------66%-----             ] 1338 of 2000 complete in 1809.2 sec
[-----------------66%-----             ] 1339 of 2000 complete in 1810.6 sec
[-----------------67%-----             ] 1340 of 2000 complete in 1812.0 sec
[-----------------67%-----             ] 1341 of 2000 complete in 1813.6 sec
[-----------------67%-----             ] 1342 of 2000 complete in 1815.2 sec
[-----------------67%-----             ] 1343 of 2000 complete in 1816.6 sec
[-----------------67%-----             ] 1344 of 2000 complete in 1818.1 sec
[-----------------67%-----             ] 1345 of 2000 complete in 1819.5 sec
[-----------------67%-----             ] 1346 of 2000 complete in 1821.1 sec
[-----------------67%-----             ] 1347 of 2000 complete in 1822.6 sec
[-----------------67%-----             ] 1348 of 2000 complete in 1824.0 sec
[-----------------67%-----             ] 1349 of 2000 complete in 1825.6 sec
[-----------------67%-----             ] 1350 of 2000 complete in 1827.0 sec
[-----------------67%-----             ] 1351 of 2000 complete in 1828.4 sec
[-----------------67%-----             ] 1352 of 2000 complete in 1829.8 sec
[-----------------67%-----             ] 1353 of 2000 complete in 1831.2 sec
[-----------------67%-----             ] 1354 of 2000 complete in 1832.7 sec
[-----------------67%-----             ] 1355 of 2000 complete in 1834.1 sec
[-----------------67%-----             ] 1356 of 2000 complete in 1835.5 sec
[-----------------67%-----             ] 1357 of 2000 complete in 1837.0 sec
[-----------------67%-----             ] 1358 of 2000 complete in 1838.4 sec
[-----------------67%-----             ] 1359 of 2000 complete in 1839.9 sec
[-----------------68%-----             ] 1360 of 2000 complete in 1841.3 sec
[-----------------68%-----             ] 1361 of 2000 complete in 1842.7 sec
[-----------------68%-----             ] 1362 of 2000 complete in 1844.1 sec
[-----------------68%-----             ] 1363 of 2000 complete in 1845.5 sec
[-----------------68%-----             ] 1364 of 2000 complete in 1846.9 sec
[-----------------68%-----             ] 1365 of 2000 complete in 1848.2 sec
[-----------------68%-----             ] 1366 of 2000 complete in 1849.6 sec
[-----------------68%-----             ] 1367 of 2000 complete in 1851.0 sec
[-----------------68%-----             ] 1368 of 2000 complete in 1852.4 sec
[-----------------68%------            ] 1369 of 2000 complete in 1853.8 sec
[-----------------68%------            ] 1370 of 2000 complete in 1855.2 sec
[-----------------68%------            ] 1371 of 2000 complete in 1856.7 sec
[-----------------68%------            ] 1372 of 2000 complete in 1858.2 sec
[-----------------68%------            ] 1373 of 2000 complete in 1859.6 sec
[-----------------68%------            ] 1374 of 2000 complete in 1861.1 sec
[-----------------68%------            ] 1375 of 2000 complete in 1862.5 sec
[-----------------68%------            ] 1376 of 2000 complete in 1864.0 sec
[-----------------68%------            ] 1377 of 2000 complete in 1865.4 sec
[-----------------68%------            ] 1378 of 2000 complete in 1866.7 sec
[-----------------68%------            ] 1379 of 2000 complete in 1868.1 sec
[-----------------69%------            ] 1380 of 2000 complete in 1869.5 sec
[-----------------69%------            ] 1381 of 2000 complete in 1870.9 sec
[-----------------69%------            ] 1382 of 2000 complete in 1872.5 sec
[-----------------69%------            ] 1383 of 2000 complete in 1873.9 sec
[-----------------69%------            ] 1384 of 2000 complete in 1875.3 sec
[-----------------69%------            ] 1385 of 2000 complete in 1876.6 sec
[-----------------69%------            ] 1386 of 2000 complete in 1878.1 sec
[-----------------69%------            ] 1387 of 2000 complete in 1879.4 sec
[-----------------69%------            ] 1388 of 2000 complete in 1880.8 sec
[-----------------69%------            ] 1389 of 2000 complete in 1882.2 sec
[-----------------69%------            ] 1390 of 2000 complete in 1883.5 sec
[-----------------69%------            ] 1391 of 2000 complete in 1884.9 sec
[-----------------69%------            ] 1392 of 2000 complete in 1886.2 sec
[-----------------69%------            ] 1393 of 2000 complete in 1887.6 sec
[-----------------69%------            ] 1394 of 2000 complete in 1889.0 sec
[-----------------69%------            ] 1395 of 2000 complete in 1890.4 sec
[-----------------69%------            ] 1396 of 2000 complete in 1891.8 sec
[-----------------69%------            ] 1397 of 2000 complete in 1893.2 sec
[-----------------69%------            ] 1398 of 2000 complete in 1894.6 sec
[-----------------69%------            ] 1399 of 2000 complete in 1895.9 sec
[-----------------70%------            ] 1400 of 2000 complete in 1897.3 sec
[-----------------70%------            ] 1401 of 2000 complete in 1898.7 sec
[-----------------70%------            ] 1402 of 2000 complete in 1900.1 sec
[-----------------70%------            ] 1403 of 2000 complete in 1901.5 sec

[-----------------70%------            ] 1405 of 2000 complete in 1866.9 sec
[-----------------70%------            ] 1406 of 2000 complete in 1868.3 sec
[-----------------70%------            ] 1407 of 2000 complete in 1869.8 sec
[-----------------70%------            ] 1408 of 2000 complete in 1871.2 sec
[-----------------70%------            ] 1409 of 2000 complete in 1872.5 sec
[-----------------70%------            ] 1410 of 2000 complete in 1873.9 sec
[-----------------70%------            ] 1411 of 2000 complete in 1875.3 sec
[-----------------70%------            ] 1412 of 2000 complete in 1876.7 sec
[-----------------70%------            ] 1413 of 2000 complete in 1878.2 sec
[-----------------70%------            ] 1414 of 2000 complete in 1879.6 sec
[-----------------70%------            ] 1415 of 2000 complete in 1880.9 sec
[-----------------70%------            ] 1416 of 2000 complete in 1882.2 sec
[-----------------70%------            ] 1417 of 2000 complete in 1883.6 sec
[-----------------70%------            ] 1418 of 2000 complete in 1884.9 sec
[-----------------70%------            ] 1419 of 2000 complete in 1886.3 sec
[-----------------71%------            ] 1420 of 2000 complete in 1887.7 sec
[-----------------71%------            ] 1421 of 2000 complete in 1889.1 sec
[-----------------71%-------           ] 1422 of 2000 complete in 1890.5 sec
[-----------------71%-------           ] 1423 of 2000 complete in 1891.9 sec
[-----------------71%-------           ] 1424 of 2000 complete in 1893.3 sec
[-----------------71%-------           ] 1425 of 2000 complete in 1894.7 sec
[-----------------71%-------           ] 1426 of 2000 complete in 1896.1 sec
[-----------------71%-------           ] 1427 of 2000 complete in 1897.5 sec
[-----------------71%-------           ] 1428 of 2000 complete in 1898.9 sec
[-----------------71%-------           ] 1429 of 2000 complete in 1900.3 sec
[-----------------71%-------           ] 1430 of 2000 complete in 1901.8 sec
[-----------------71%-------           ] 1431 of 2000 complete in 1903.2 sec
[-----------------71%-------           ] 1432 of 2000 complete in 1904.5 sec
[-----------------71%-------           ] 1433 of 2000 complete in 1905.9 sec
[-----------------71%-------           ] 1434 of 2000 complete in 1907.4 sec
[-----------------71%-------           ] 1435 of 2000 complete in 1908.7 sec
[-----------------71%-------           ] 1436 of 2000 complete in 1910.1 sec
[-----------------71%-------           ] 1437 of 2000 complete in 1911.6 sec
[-----------------71%-------           ] 1438 of 2000 complete in 1913.0 sec
[-----------------71%-------           ] 1439 of 2000 complete in 1914.5 sec
[-----------------72%-------           ] 1440 of 2000 complete in 1915.9 sec
[-----------------72%-------           ] 1441 of 2000 complete in 1917.3 sec
[-----------------72%-------           ] 1442 of 2000 complete in 1918.6 sec
[-----------------72%-------           ] 1443 of 2000 complete in 1919.9 sec
[-----------------72%-------           ] 1444 of 2000 complete in 1921.3 sec
[-----------------72%-------           ] 1445 of 2000 complete in 1922.6 sec
[-----------------72%-------           ] 1446 of 2000 complete in 1924.0 sec
[-----------------72%-------           ] 1447 of 2000 complete in 1925.4 sec
[-----------------72%-------           ] 1448 of 2000 complete in 1926.8 sec
[-----------------72%-------           ] 1449 of 2000 complete in 1928.2 sec
[-----------------72%-------           ] 1450 of 2000 complete in 1929.6 sec
[-----------------72%-------           ] 1451 of 2000 complete in 1931.1 sec
[-----------------72%-------           ] 1452 of 2000 complete in 1932.5 sec
[-----------------72%-------           ] 1453 of 2000 complete in 1933.9 sec
[-----------------72%-------           ] 1454 of 2000 complete in 1935.4 sec
[-----------------72%-------           ] 1455 of 2000 complete in 1936.7 sec
[-----------------72%-------           ] 1456 of 2000 complete in 1938.2 sec
[-----------------72%-------           ] 1457 of 2000 complete in 1939.6 sec
[-----------------72%-------           ] 1458 of 2000 complete in 1941.0 sec
[-----------------72%-------           ] 1459 of 2000 complete in 1942.4 sec
[-----------------73%-------           ] 1460 of 2000 complete in 1943.8 sec
[-----------------73%-------           ] 1461 of 2000 complete in 1945.2 sec
[-----------------73%-------           ] 1462 of 2000 complete in 1946.6 sec
[-----------------73%-------           ] 1463 of 2000 complete in 1948.0 sec
[-----------------73%-------           ] 1464 of 2000 complete in 1949.4 sec
[-----------------73%-------           ] 1465 of 2000 complete in 1950.8 sec
[-----------------73%-------           ] 1466 of 2000 complete in 1952.2 sec
[-----------------73%-------           ] 1467 of 2000 complete in 1953.6 sec
[-----------------73%-------           ] 1468 of 2000 complete in 1955.0 sec
[-----------------73%-------           ] 1469 of 2000 complete in 1956.4 sec
[-----------------73%-------           ] 1470 of 2000 complete in 1957.8 sec
[-----------------73%-------           ] 1471 of 2000 complete in 1959.2 sec
[-----------------73%-------           ] 1472 of 2000 complete in 1960.6 sec
[-----------------73%-------           ] 1473 of 2000 complete in 1962.0 sec
[-----------------73%--------          ] 1474 of 2000 complete in 1963.4 sec
[-----------------73%--------          ] 1475 of 2000 complete in 1964.8 sec
[-----------------73%--------          ] 1476 of 2000 complete in 1966.1 sec
[-----------------73%--------          ] 1477 of 2000 complete in 1967.5 sec
[-----------------73%--------          ] 1478 of 2000 complete in 1968.9 sec
[-----------------73%--------          ] 1479 of 2000 complete in 1970.3 sec
[-----------------74%--------          ] 1480 of 2000 complete in 1971.6 sec
[-----------------74%--------          ] 1481 of 2000 complete in 1972.9 sec
[-----------------74%--------          ] 1482 of 2000 complete in 1974.3 sec
[-----------------74%--------          ] 1483 of 2000 complete in 1975.7 sec
[-----------------74%--------          ] 1484 of 2000 complete in 1976.9 sec
[-----------------74%--------          ] 1485 of 2000 complete in 1978.4 sec
[-----------------74%--------          ] 1486 of 2000 complete in 1979.8 sec
[-----------------74%--------          ] 1487 of 2000 complete in 1981.1 sec
[-----------------74%--------          ] 1488 of 2000 complete in 1982.5 sec
[-----------------74%--------          ] 1489 of 2000 complete in 1983.9 sec
[-----------------74%--------          ] 1490 of 2000 complete in 1985.3 sec
[-----------------74%--------          ] 1491 of 2000 complete in 1986.6 sec
[-----------------74%--------          ] 1492 of 2000 complete in 1988.0 sec
[-----------------74%--------          ] 1493 of 2000 complete in 1989.3 sec
[-----------------74%--------          ] 1494 of 2000 complete in 1990.7 sec
[-----------------74%--------          ] 1495 of 2000 complete in 1992.0 sec
[-----------------74%--------          ] 1496 of 2000 complete in 1993.4 sec
[-----------------74%--------          ] 1497 of 2000 complete in 1994.8 sec
[-----------------74%--------          ] 1498 of 2000 complete in 1996.2 sec
[-----------------74%--------          ] 1499 of 2000 complete in 1997.6 sec
[-----------------75%--------          ] 1500 of 2000 complete in 1998.9 sec
[-----------------75%--------          ] 1501 of 2000 complete in 2000.3 sec
[-----------------75%--------          ] 1502 of 2000 complete in 2001.6 sec
[-----------------75%--------          ] 1503 of 2000 complete in 2003.0 sec
[-----------------75%--------          ] 1504 of 2000 complete in 2004.4 sec
[-----------------75%--------          ] 1505 of 2000 complete in 2005.8 sec
[-----------------75%--------          ] 1506 of 2000 complete in 2007.1 sec
[-----------------75%--------          ] 1507 of 2000 complete in 2008.5 sec
[-----------------75%--------          ] 1508 of 2000 complete in 2009.9 sec
[-----------------75%--------          ] 1509 of 2000 complete in 2011.3 sec
[-----------------75%--------          ] 1510 of 2000 complete in 2012.7 sec
[-----------------70%------            ] 1405 of 2000 complete in 1870.4 sec
[-----------------70%------            ] 1406 of 2000 complete in 1871.8 sec
[-----------------70%------            ] 1407 of 2000 complete in 1873.2 sec
[-----------------70%------            ] 1408 of 2000 complete in 1874.6 sec
[-----------------70%------            ] 1409 of 2000 complete in 1876.1 sec
[-----------------70%------            ] 1410 of 2000 complete in 1877.5 sec
[-----------------70%------            ] 1411 of 2000 complete in 1879.0 sec
[-----------------70%------            ] 1412 of 2000 complete in 1880.4 sec
[-----------------70%------            ] 1413 of 2000 complete in 1881.8 sec
[-----------------70%------            ] 1414 of 2000 complete in 1883.2 sec
[-----------------70%------            ] 1415 of 2000 complete in 1884.6 sec
[-----------------70%------            ] 1416 of 2000 complete in 1886.1 sec
[-----------------70%------            ] 1417 of 2000 complete in 1887.5 sec
[-----------------70%------            ] 1418 of 2000 complete in 1888.9 sec
[-----------------70%------            ] 1419 of 2000 complete in 1890.2 sec
[-----------------71%------            ] 1420 of 2000 complete in 1891.5 sec
[-----------------71%------            ] 1421 of 2000 complete in 1892.9 sec
[-----------------71%-------           ] 1422 of 2000 complete in 1894.2 sec
[-----------------71%-------           ] 1423 of 2000 complete in 1895.6 sec
[-----------------71%-------           ] 1424 of 2000 complete in 1897.0 sec
[-----------------71%-------           ] 1425 of 2000 complete in 1898.4 sec
[-----------------71%-------           ] 1426 of 2000 complete in 1899.8 sec
[-----------------71%-------           ] 1427 of 2000 complete in 1901.2 sec
[-----------------71%-------           ] 1428 of 2000 complete in 1902.5 sec
[-----------------71%-------           ] 1429 of 2000 complete in 1903.9 sec
[-----------------71%-------           ] 1430 of 2000 complete in 1905.4 sec
[-----------------71%-------           ] 1431 of 2000 complete in 1906.8 sec
[-----------------71%-------           ] 1432 of 2000 complete in 1908.3 sec
[-----------------71%-------           ] 1433 of 2000 complete in 1909.6 sec
[-----------------71%-------           ] 1434 of 2000 complete in 1911.1 sec
[-----------------71%-------           ] 1435 of 2000 complete in 1912.6 sec
[-----------------71%-------           ] 1436 of 2000 complete in 1914.1 sec
[-----------------71%-------           ] 1437 of 2000 complete in 1915.5 sec
[-----------------71%-------           ] 1438 of 2000 complete in 1916.9 sec
[-----------------71%-------           ] 1439 of 2000 complete in 1918.3 sec
[-----------------72%-------           ] 1440 of 2000 complete in 1919.7 sec
[-----------------72%-------           ] 1441 of 2000 complete in 1921.1 sec
[-----------------72%-------           ] 1442 of 2000 complete in 1922.5 sec
[-----------------72%-------           ] 1443 of 2000 complete in 1924.0 sec
[-----------------72%-------           ] 1444 of 2000 complete in 1925.3 sec
[-----------------72%-------           ] 1445 of 2000 complete in 1926.7 sec
[-----------------72%-------           ] 1446 of 2000 complete in 1928.2 sec
[-----------------72%-------           ] 1447 of 2000 complete in 1929.6 sec
[-----------------72%-------           ] 1448 of 2000 complete in 1931.0 sec
[-----------------72%-------           ] 1449 of 2000 complete in 1932.4 sec
[-----------------72%-------           ] 1450 of 2000 complete in 1933.9 sec
[-----------------72%-------           ] 1451 of 2000 complete in 1935.3 sec
[-----------------72%-------           ] 1452 of 2000 complete in 1936.7 sec
[-----------------72%-------           ] 1453 of 2000 complete in 1938.2 sec
[-----------------72%-------           ] 1454 of 2000 complete in 1939.5 sec
[-----------------72%-------           ] 1455 of 2000 complete in 1940.9 sec
[-----------------72%-------           ] 1456 of 2000 complete in 1942.3 sec
[-----------------72%-------           ] 1457 of 2000 complete in 1943.7 sec
[-----------------72%-------           ] 1458 of 2000 complete in 1945.1 sec
[-----------------72%-------           ] 1459 of 2000 complete in 1946.6 sec
[-----------------73%-------           ] 1460 of 2000 complete in 1948.0 sec
[-----------------73%-------           ] 1461 of 2000 complete in 1949.4 sec
[-----------------73%-------           ] 1462 of 2000 complete in 1950.8 sec
[-----------------73%-------           ] 1463 of 2000 complete in 1952.2 sec
[-----------------73%-------           ] 1464 of 2000 complete in 1953.7 sec
[-----------------73%-------           ] 1465 of 2000 complete in 1955.1 sec
[-----------------73%-------           ] 1466 of 2000 complete in 1956.3 sec
[-----------------73%-------           ] 1467 of 2000 complete in 1957.7 sec
[-----------------73%-------           ] 1468 of 2000 complete in 1959.1 sec
[-----------------73%-------           ] 1469 of 2000 complete in 1960.5 sec
[-----------------73%-------           ] 1470 of 2000 complete in 1962.0 sec
[-----------------73%-------           ] 1471 of 2000 complete in 1963.3 sec
[-----------------73%-------           ] 1472 of 2000 complete in 1964.7 sec
[-----------------73%-------           ] 1473 of 2000 complete in 1966.0 sec
[-----------------73%--------          ] 1474 of 2000 complete in 1967.5 sec
[-----------------73%--------          ] 1475 of 2000 complete in 1968.9 sec
[-----------------73%--------          ] 1476 of 2000 complete in 1970.3 sec
[-----------------73%--------          ] 1477 of 2000 complete in 1971.7 sec
[-----------------73%--------          ] 1478 of 2000 complete in 1973.0 sec
[-----------------73%--------          ] 1479 of 2000 complete in 1974.4 sec
[-----------------74%--------          ] 1480 of 2000 complete in 1975.8 sec
[-----------------74%--------          ] 1481 of 2000 complete in 1977.2 sec
[-----------------74%--------          ] 1482 of 2000 complete in 1978.6 sec
[-----------------74%--------          ] 1483 of 2000 complete in 1980.0 sec
[-----------------74%--------          ] 1484 of 2000 complete in 1981.4 sec
[-----------------74%--------          ] 1485 of 2000 complete in 1982.8 sec
[-----------------74%--------          ] 1486 of 2000 complete in 1984.2 sec
[-----------------74%--------          ] 1487 of 2000 complete in 1985.6 sec
[-----------------74%--------          ] 1488 of 2000 complete in 1987.0 sec
[-----------------74%--------          ] 1489 of 2000 complete in 1988.3 sec
[-----------------74%--------          ] 1490 of 2000 complete in 1989.8 sec
[-----------------74%--------          ] 1491 of 2000 complete in 1991.2 sec
[-----------------74%--------          ] 1492 of 2000 complete in 1992.6 sec
[-----------------74%--------          ] 1493 of 2000 complete in 1993.9 sec
[-----------------74%--------          ] 1494 of 2000 complete in 1995.3 sec
[-----------------74%--------          ] 1495 of 2000 complete in 1996.8 sec
[-----------------74%--------          ] 1496 of 2000 complete in 1998.1 sec
[-----------------74%--------          ] 1497 of 2000 complete in 1999.5 sec
[-----------------74%--------          ] 1498 of 2000 complete in 2000.9 sec
[-----------------74%--------          ] 1499 of 2000 complete in 2002.4 sec
[-----------------75%--------          ] 1500 of 2000 complete in 2003.7 sec
[-----------------75%--------          ] 1501 of 2000 complete in 2005.1 sec
[-----------------75%--------          ] 1502 of 2000 complete in 2006.5 sec
[-----------------75%--------          ] 1503 of 2000 complete in 2008.0 sec
[-----------------75%--------          ] 1504 of 2000 complete in 2009.3 sec
[-----------------75%--------          ] 1505 of 2000 complete in 2010.7 sec
[-----------------75%--------          ] 1506 of 2000 complete in 2012.1 sec
[-----------------75%--------          ] 1507 of 2000 complete in 2013.5 sec
[-----------------75%--------          ] 1508 of 2000 complete in 2014.8 sec
[-----------------75%--------          ] 1509 of 2000 complete in 2016.2 sec
[-----------------75%--------          ] 1510 of 2000 complete in 2017.7 sec

[-----------------70%------            ] 1405 of 2000 complete in 1874.8 sec
[-----------------70%------            ] 1406 of 2000 complete in 1876.1 sec
[-----------------70%------            ] 1407 of 2000 complete in 1877.5 sec
[-----------------70%------            ] 1408 of 2000 complete in 1878.9 sec
[-----------------70%------            ] 1409 of 2000 complete in 1880.3 sec
[-----------------70%------            ] 1410 of 2000 complete in 1881.7 sec
[-----------------70%------            ] 1411 of 2000 complete in 1883.0 sec
[-----------------70%------            ] 1412 of 2000 complete in 1884.4 sec
[-----------------70%------            ] 1413 of 2000 complete in 1885.8 sec
[-----------------70%------            ] 1414 of 2000 complete in 1887.1 sec
[-----------------70%------            ] 1415 of 2000 complete in 1888.5 sec
[-----------------70%------            ] 1416 of 2000 complete in 1889.9 sec
[-----------------70%------            ] 1417 of 2000 complete in 1891.3 sec
[-----------------70%------            ] 1418 of 2000 complete in 1892.7 sec
[-----------------70%------            ] 1419 of 2000 complete in 1894.1 sec
[-----------------71%------            ] 1420 of 2000 complete in 1895.4 sec
[-----------------71%------            ] 1421 of 2000 complete in 1896.8 sec
[-----------------71%-------           ] 1422 of 2000 complete in 1898.1 sec
[-----------------71%-------           ] 1423 of 2000 complete in 1899.4 sec
[-----------------71%-------           ] 1424 of 2000 complete in 1900.8 sec
[-----------------71%-------           ] 1425 of 2000 complete in 1902.2 sec
[-----------------71%-------           ] 1426 of 2000 complete in 1903.5 sec
[-----------------71%-------           ] 1427 of 2000 complete in 1904.9 sec
[-----------------71%-------           ] 1428 of 2000 complete in 1906.4 sec
[-----------------71%-------           ] 1429 of 2000 complete in 1907.8 sec
[-----------------71%-------           ] 1430 of 2000 complete in 1909.2 sec
[-----------------71%-------           ] 1431 of 2000 complete in 1910.6 sec
[-----------------71%-------           ] 1432 of 2000 complete in 1912.1 sec
[-----------------71%-------           ] 1433 of 2000 complete in 1913.5 sec
[-----------------71%-------           ] 1434 of 2000 complete in 1914.9 sec
[-----------------71%-------           ] 1435 of 2000 complete in 1916.3 sec
[-----------------71%-------           ] 1436 of 2000 complete in 1917.8 sec
[-----------------71%-------           ] 1437 of 2000 complete in 1919.1 sec
[-----------------71%-------           ] 1438 of 2000 complete in 1920.5 sec
[-----------------71%-------           ] 1439 of 2000 complete in 1921.9 sec
[-----------------72%-------           ] 1440 of 2000 complete in 1923.3 sec
[-----------------72%-------           ] 1441 of 2000 complete in 1924.7 sec
[-----------------72%-------           ] 1442 of 2000 complete in 1926.0 sec
[-----------------72%-------           ] 1443 of 2000 complete in 1927.4 sec
[-----------------72%-------           ] 1444 of 2000 complete in 1928.8 sec
[-----------------72%-------           ] 1445 of 2000 complete in 1930.2 sec
[-----------------72%-------           ] 1446 of 2000 complete in 1931.6 sec
[-----------------72%-------           ] 1447 of 2000 complete in 1933.0 sec
[-----------------72%-------           ] 1448 of 2000 complete in 1934.5 sec
[-----------------72%-------           ] 1449 of 2000 complete in 1935.9 sec
[-----------------72%-------           ] 1450 of 2000 complete in 1937.3 sec
[-----------------72%-------           ] 1451 of 2000 complete in 1938.7 sec
[-----------------72%-------           ] 1452 of 2000 complete in 1940.1 sec
[-----------------72%-------           ] 1453 of 2000 complete in 1941.6 sec
[-----------------72%-------           ] 1454 of 2000 complete in 1943.0 sec
[-----------------72%-------           ] 1455 of 2000 complete in 1944.4 sec
[-----------------72%-------           ] 1456 of 2000 complete in 1945.9 sec
[-----------------72%-------           ] 1457 of 2000 complete in 1947.3 sec
[-----------------72%-------           ] 1458 of 2000 complete in 1948.7 sec
[-----------------72%-------           ] 1459 of 2000 complete in 1950.1 sec
[-----------------73%-------           ] 1460 of 2000 complete in 1951.6 sec
[-----------------73%-------           ] 1461 of 2000 complete in 1952.9 sec
[-----------------73%-------           ] 1462 of 2000 complete in 1954.3 sec
[-----------------73%-------           ] 1463 of 2000 complete in 1955.8 sec
[-----------------73%-------           ] 1464 of 2000 complete in 1957.2 sec
[-----------------73%-------           ] 1465 of 2000 complete in 1958.6 sec
[-----------------73%-------           ] 1466 of 2000 complete in 1960.0 sec
[-----------------73%-------           ] 1467 of 2000 complete in 1961.4 sec
[-----------------73%-------           ] 1468 of 2000 complete in 1962.8 sec
[-----------------73%-------           ] 1469 of 2000 complete in 1964.2 sec
[-----------------73%-------           ] 1470 of 2000 complete in 1965.7 sec
[-----------------73%-------           ] 1471 of 2000 complete in 1967.1 sec
[-----------------73%-------           ] 1472 of 2000 complete in 1968.5 sec
[-----------------73%-------           ] 1473 of 2000 complete in 1970.0 sec
[-----------------73%--------          ] 1474 of 2000 complete in 1971.4 sec
[-----------------73%--------          ] 1475 of 2000 complete in 1972.8 sec
[-----------------73%--------          ] 1476 of 2000 complete in 1974.2 sec
[-----------------73%--------          ] 1477 of 2000 complete in 1975.6 sec
[-----------------73%--------          ] 1478 of 2000 complete in 1977.0 sec
[-----------------73%--------          ] 1479 of 2000 complete in 1978.4 sec
[-----------------74%--------          ] 1480 of 2000 complete in 1979.8 sec
[-----------------74%--------          ] 1481 of 2000 complete in 1981.2 sec
[-----------------74%--------          ] 1482 of 2000 complete in 1982.6 sec
[-----------------74%--------          ] 1483 of 2000 complete in 1984.0 sec
[-----------------74%--------          ] 1484 of 2000 complete in 1985.4 sec
[-----------------74%--------          ] 1485 of 2000 complete in 1986.8 sec
[-----------------74%--------          ] 1486 of 2000 complete in 1988.1 sec
[-----------------74%--------          ] 1487 of 2000 complete in 1989.5 sec
[-----------------74%--------          ] 1488 of 2000 complete in 1990.9 sec
[-----------------74%--------          ] 1489 of 2000 complete in 1992.3 sec
[-----------------74%--------          ] 1490 of 2000 complete in 1993.8 sec
[-----------------74%--------          ] 1491 of 2000 complete in 1995.2 sec
[-----------------74%--------          ] 1492 of 2000 complete in 1996.6 sec
[-----------------74%--------          ] 1493 of 2000 complete in 1998.1 sec
[-----------------74%--------          ] 1494 of 2000 complete in 1999.4 sec
[-----------------74%--------          ] 1495 of 2000 complete in 2000.8 sec
[-----------------74%--------          ] 1496 of 2000 complete in 2002.2 sec
[-----------------74%--------          ] 1497 of 2000 complete in 2003.7 sec
[-----------------74%--------          ] 1498 of 2000 complete in 2005.1 sec
[-----------------74%--------          ] 1499 of 2000 complete in 2006.5 sec
[-----------------75%--------          ] 1500 of 2000 complete in 2007.9 sec
[-----------------75%--------          ] 1501 of 2000 complete in 2009.3 sec
[-----------------75%--------          ] 1502 of 2000 complete in 2010.8 sec
[-----------------75%--------          ] 1503 of 2000 complete in 2012.2 sec
[-----------------75%--------          ] 1504 of 2000 complete in 2013.5 sec
[-----------------75%--------          ] 1505 of 2000 complete in 2015.0 sec
[-----------------75%--------          ] 1506 of 2000 complete in 2016.5 sec
[-----------------75%--------          ] 1507 of 2000 complete in 2017.9 sec
[-----------------75%--------          ] 1508 of 2000 complete in 2019.3 sec
[-----------------75%--------          ] 1509 of 2000 complete in 2020.7 sec
[-----------------75%--------          ] 1510 of 2000 complete in 2022.1 sec
[-----------------70%------            ] 1404 of 2000 complete in 1902.9 sec
[-----------------70%------            ] 1405 of 2000 complete in 1904.3 sec
[-----------------70%------            ] 1406 of 2000 complete in 1905.7 sec
[-----------------70%------            ] 1407 of 2000 complete in 1907.1 sec
[-----------------70%------            ] 1408 of 2000 complete in 1908.6 sec
[-----------------70%------            ] 1409 of 2000 complete in 1909.9 sec
[-----------------70%------            ] 1410 of 2000 complete in 1911.3 sec
[-----------------70%------            ] 1411 of 2000 complete in 1912.7 sec
[-----------------70%------            ] 1412 of 2000 complete in 1914.2 sec
[-----------------70%------            ] 1413 of 2000 complete in 1915.5 sec
[-----------------70%------            ] 1414 of 2000 complete in 1917.0 sec
[-----------------70%------            ] 1415 of 2000 complete in 1918.3 sec
[-----------------70%------            ] 1416 of 2000 complete in 1919.8 sec
[-----------------70%------            ] 1417 of 2000 complete in 1921.2 sec
[-----------------70%------            ] 1418 of 2000 complete in 1922.6 sec
[-----------------70%------            ] 1419 of 2000 complete in 1924.0 sec
[-----------------71%------            ] 1420 of 2000 complete in 1925.4 sec
[-----------------71%------            ] 1421 of 2000 complete in 1926.7 sec
[-----------------71%-------           ] 1422 of 2000 complete in 1928.2 sec
[-----------------71%-------           ] 1423 of 2000 complete in 1929.6 sec
[-----------------71%-------           ] 1424 of 2000 complete in 1930.9 sec
[-----------------71%-------           ] 1425 of 2000 complete in 1932.4 sec
[-----------------71%-------           ] 1426 of 2000 complete in 1933.9 sec
[-----------------71%-------           ] 1427 of 2000 complete in 1935.3 sec
[-----------------71%-------           ] 1428 of 2000 complete in 1936.7 sec
[-----------------71%-------           ] 1429 of 2000 complete in 1938.1 sec
[-----------------71%-------           ] 1430 of 2000 complete in 1939.5 sec
[-----------------71%-------           ] 1431 of 2000 complete in 1941.0 sec
[-----------------71%-------           ] 1432 of 2000 complete in 1942.4 sec
[-----------------71%-------           ] 1433 of 2000 complete in 1943.9 sec
[-----------------71%-------           ] 1434 of 2000 complete in 1945.3 sec
[-----------------71%-------           ] 1435 of 2000 complete in 1946.7 sec
[-----------------71%-------           ] 1436 of 2000 complete in 1948.2 sec
[-----------------71%-------           ] 1437 of 2000 complete in 1949.6 sec
[-----------------71%-------           ] 1438 of 2000 complete in 1951.0 sec
[-----------------71%-------           ] 1439 of 2000 complete in 1952.5 sec
[-----------------72%-------           ] 1440 of 2000 complete in 1953.8 sec
[-----------------72%-------           ] 1441 of 2000 complete in 1955.3 sec
[-----------------72%-------           ] 1442 of 2000 complete in 1956.6 sec
[-----------------72%-------           ] 1443 of 2000 complete in 1958.0 sec
[-----------------72%-------           ] 1444 of 2000 complete in 1959.4 sec
[-----------------72%-------           ] 1445 of 2000 complete in 1960.8 sec
[-----------------72%-------           ] 1446 of 2000 complete in 1962.2 sec
[-----------------72%-------           ] 1447 of 2000 complete in 1963.6 sec
[-----------------72%-------           ] 1448 of 2000 complete in 1964.9 sec
[-----------------72%-------           ] 1449 of 2000 complete in 1966.4 sec
[-----------------72%-------           ] 1450 of 2000 complete in 1967.8 sec
[-----------------72%-------           ] 1451 of 2000 complete in 1969.2 sec
[-----------------72%-------           ] 1452 of 2000 complete in 1970.6 sec
[-----------------72%-------           ] 1453 of 2000 complete in 1971.9 sec
[-----------------72%-------           ] 1454 of 2000 complete in 1973.3 sec
[-----------------72%-------           ] 1455 of 2000 complete in 1974.7 sec
[-----------------72%-------           ] 1456 of 2000 complete in 1976.0 sec
[-----------------72%-------           ] 1457 of 2000 complete in 1977.4 sec
[-----------------72%-------           ] 1458 of 2000 complete in 1978.9 sec
[-----------------72%-------           ] 1459 of 2000 complete in 1980.2 sec
[-----------------73%-------           ] 1460 of 2000 complete in 1981.6 sec
[-----------------73%-------           ] 1461 of 2000 complete in 1983.0 sec
[-----------------73%-------           ] 1462 of 2000 complete in 1984.4 sec
[-----------------73%-------           ] 1463 of 2000 complete in 1985.7 sec
[-----------------73%-------           ] 1464 of 2000 complete in 1987.1 sec
[-----------------73%-------           ] 1465 of 2000 complete in 1988.5 sec
[-----------------73%-------           ] 1466 of 2000 complete in 1989.9 sec
[-----------------73%-------           ] 1467 of 2000 complete in 1991.2 sec
[-----------------73%-------           ] 1468 of 2000 complete in 1992.5 sec
[-----------------73%-------           ] 1469 of 2000 complete in 1993.9 sec
[-----------------73%-------           ] 1470 of 2000 complete in 1995.4 sec
[-----------------73%-------           ] 1471 of 2000 complete in 1996.8 sec
[-----------------73%-------           ] 1472 of 2000 complete in 1998.1 sec
[-----------------73%-------           ] 1473 of 2000 complete in 1999.4 sec
[-----------------73%--------          ] 1474 of 2000 complete in 2000.8 sec
[-----------------73%--------          ] 1475 of 2000 complete in 2002.2 sec
[-----------------73%--------          ] 1476 of 2000 complete in 2003.6 sec
[-----------------73%--------          ] 1477 of 2000 complete in 2004.9 sec
[-----------------73%--------          ] 1478 of 2000 complete in 2006.3 sec
[-----------------73%--------          ] 1479 of 2000 complete in 2007.6 sec
[-----------------74%--------          ] 1480 of 2000 complete in 2009.0 sec
[-----------------74%--------          ] 1481 of 2000 complete in 2010.4 sec
[-----------------74%--------          ] 1482 of 2000 complete in 2011.7 sec
[-----------------74%--------          ] 1483 of 2000 complete in 2013.1 sec
[-----------------74%--------          ] 1484 of 2000 complete in 2014.5 sec
[-----------------74%--------          ] 1485 of 2000 complete in 2015.9 sec
[-----------------74%--------          ] 1486 of 2000 complete in 2017.3 sec
[-----------------74%--------          ] 1487 of 2000 complete in 2018.6 sec
[-----------------74%--------          ] 1488 of 2000 complete in 2020.0 sec
[-----------------74%--------          ] 1489 of 2000 complete in 2021.4 sec
[-----------------74%--------          ] 1490 of 2000 complete in 2022.7 sec
[-----------------74%--------          ] 1491 of 2000 complete in 2024.1 sec
[-----------------74%--------          ] 1492 of 2000 complete in 2025.5 sec
[-----------------74%--------          ] 1493 of 2000 complete in 2026.9 sec
[-----------------74%--------          ] 1494 of 2000 complete in 2028.3 sec
[-----------------74%--------          ] 1495 of 2000 complete in 2029.6 sec
[-----------------74%--------          ] 1496 of 2000 complete in 2031.0 sec
[-----------------74%--------          ] 1497 of 2000 complete in 2032.4 sec
[-----------------74%--------          ] 1498 of 2000 complete in 2033.7 sec
[-----------------74%--------          ] 1499 of 2000 complete in 2035.2 sec
[-----------------75%--------          ] 1500 of 2000 complete in 2036.5 sec
[-----------------75%--------          ] 1501 of 2000 complete in 2038.0 sec
[-----------------75%--------          ] 1502 of 2000 complete in 2039.4 sec
[-----------------75%--------          ] 1503 of 2000 complete in 2040.8 sec
[-----------------75%--------          ] 1504 of 2000 complete in 2042.1 sec
[-----------------75%--------          ] 1505 of 2000 complete in 2043.5 sec
[-----------------75%--------          ] 1506 of 2000 complete in 2045.0 sec
[-----------------75%--------          ] 1507 of 2000 complete in 2046.3 sec
[-----------------75%--------          ] 1508 of 2000 complete in 2047.7 sec
[-----------------75%--------          ] 1509 of 2000 complete in 2049.1 sec

[-----------------75%--------          ] 1511 of 2000 complete in 2014.1 sec
[-----------------75%--------          ] 1512 of 2000 complete in 2015.4 sec
[-----------------75%--------          ] 1513 of 2000 complete in 2016.8 sec
[-----------------75%--------          ] 1514 of 2000 complete in 2018.1 sec
[-----------------75%--------          ] 1515 of 2000 complete in 2019.4 sec
[-----------------75%--------          ] 1516 of 2000 complete in 2020.9 sec
[-----------------75%--------          ] 1517 of 2000 complete in 2022.3 sec
[-----------------75%--------          ] 1518 of 2000 complete in 2023.7 sec
[-----------------75%--------          ] 1519 of 2000 complete in 2025.0 sec
[-----------------76%--------          ] 1520 of 2000 complete in 2026.4 sec
[-----------------76%--------          ] 1521 of 2000 complete in 2027.9 sec
[-----------------76%--------          ] 1522 of 2000 complete in 2029.3 sec
[-----------------76%--------          ] 1523 of 2000 complete in 2030.6 sec
[-----------------76%--------          ] 1524 of 2000 complete in 2032.0 sec
[-----------------76%--------          ] 1525 of 2000 complete in 2033.4 sec
[-----------------76%--------          ] 1526 of 2000 complete in 2034.8 sec
[-----------------76%---------         ] 1527 of 2000 complete in 2036.2 sec
[-----------------76%---------         ] 1528 of 2000 complete in 2037.6 sec
[-----------------76%---------         ] 1529 of 2000 complete in 2039.1 sec
[-----------------76%---------         ] 1530 of 2000 complete in 2040.4 sec
[-----------------76%---------         ] 1531 of 2000 complete in 2041.8 sec
[-----------------76%---------         ] 1532 of 2000 complete in 2043.2 sec
[-----------------76%---------         ] 1533 of 2000 complete in 2044.6 sec
[-----------------76%---------         ] 1534 of 2000 complete in 2045.9 sec
[-----------------76%---------         ] 1535 of 2000 complete in 2047.3 sec
[-----------------76%---------         ] 1536 of 2000 complete in 2048.8 sec
[-----------------76%---------         ] 1537 of 2000 complete in 2050.1 sec
[-----------------76%---------         ] 1538 of 2000 complete in 2051.6 sec
[-----------------76%---------         ] 1539 of 2000 complete in 2053.0 sec
[-----------------77%---------         ] 1540 of 2000 complete in 2054.4 sec
[-----------------77%---------         ] 1541 of 2000 complete in 2055.8 sec
[-----------------77%---------         ] 1542 of 2000 complete in 2057.2 sec
[-----------------77%---------         ] 1543 of 2000 complete in 2058.6 sec
[-----------------77%---------         ] 1544 of 2000 complete in 2060.0 sec
[-----------------77%---------         ] 1545 of 2000 complete in 2061.4 sec
[-----------------77%---------         ] 1546 of 2000 complete in 2062.8 sec
[-----------------77%---------         ] 1547 of 2000 complete in 2064.2 sec
[-----------------77%---------         ] 1548 of 2000 complete in 2065.6 sec
[-----------------77%---------         ] 1549 of 2000 complete in 2067.0 sec
[-----------------77%---------         ] 1550 of 2000 complete in 2068.4 sec
[-----------------77%---------         ] 1551 of 2000 complete in 2069.8 sec
[-----------------77%---------         ] 1552 of 2000 complete in 2071.2 sec
[-----------------77%---------         ] 1553 of 2000 complete in 2072.6 sec
[-----------------77%---------         ] 1554 of 2000 complete in 2074.0 sec
[-----------------77%---------         ] 1555 of 2000 complete in 2075.4 sec
[-----------------77%---------         ] 1556 of 2000 complete in 2076.8 sec
[-----------------77%---------         ] 1557 of 2000 complete in 2078.3 sec
[-----------------77%---------         ] 1558 of 2000 complete in 2079.7 sec
[-----------------77%---------         ] 1559 of 2000 complete in 2081.1 sec
[-----------------78%---------         ] 1560 of 2000 complete in 2082.5 sec
[-----------------78%---------         ] 1561 of 2000 complete in 2083.8 sec
[-----------------78%---------         ] 1562 of 2000 complete in 2085.2 sec
[-----------------78%---------         ] 1563 of 2000 complete in 2086.7 sec
[-----------------78%---------         ] 1564 of 2000 complete in 2088.1 sec
[-----------------78%---------         ] 1565 of 2000 complete in 2089.5 sec
[-----------------78%---------         ] 1566 of 2000 complete in 2090.9 sec
[-----------------78%---------         ] 1567 of 2000 complete in 2092.3 sec
[-----------------78%---------         ] 1568 of 2000 complete in 2093.7 sec
[-----------------78%---------         ] 1569 of 2000 complete in 2095.1 sec
[-----------------78%---------         ] 1570 of 2000 complete in 2096.5 sec
[-----------------78%---------         ] 1571 of 2000 complete in 2098.0 sec
[-----------------78%---------         ] 1572 of 2000 complete in 2099.4 sec
[-----------------78%---------         ] 1573 of 2000 complete in 2100.7 sec
[-----------------78%---------         ] 1574 of 2000 complete in 2102.1 sec
[-----------------78%---------         ] 1575 of 2000 complete in 2103.5 sec
[-----------------78%---------         ] 1576 of 2000 complete in 2104.8 sec
[-----------------78%---------         ] 1577 of 2000 complete in 2106.2 sec
[-----------------78%---------         ] 1578 of 2000 complete in 2107.5 sec
[-----------------78%----------        ] 1579 of 2000 complete in 2108.9 sec
[-----------------79%----------        ] 1580 of 2000 complete in 2110.2 sec
[-----------------79%----------        ] 1581 of 2000 complete in 2111.5 sec
[-----------------79%----------        ] 1582 of 2000 complete in 2112.9 sec
[-----------------79%----------        ] 1583 of 2000 complete in 2114.3 sec
[-----------------79%----------        ] 1584 of 2000 complete in 2115.7 sec
[-----------------79%----------        ] 1585 of 2000 complete in 2117.1 sec
[-----------------79%----------        ] 1586 of 2000 complete in 2118.4 sec
[-----------------79%----------        ] 1587 of 2000 complete in 2119.8 sec
[-----------------79%----------        ] 1588 of 2000 complete in 2121.2 sec
[-----------------79%----------        ] 1589 of 2000 complete in 2122.5 sec
[-----------------79%----------        ] 1590 of 2000 complete in 2123.9 sec
[-----------------79%----------        ] 1591 of 2000 complete in 2125.2 sec
[-----------------79%----------        ] 1592 of 2000 complete in 2126.6 sec
[-----------------79%----------        ] 1593 of 2000 complete in 2128.0 sec
[-----------------79%----------        ] 1594 of 2000 complete in 2129.4 sec
[-----------------79%----------        ] 1595 of 2000 complete in 2130.8 sec
[-----------------79%----------        ] 1596 of 2000 complete in 2132.1 sec
[-----------------79%----------        ] 1597 of 2000 complete in 2133.6 sec
[-----------------79%----------        ] 1598 of 2000 complete in 2134.9 sec
[-----------------79%----------        ] 1599 of 2000 complete in 2136.3 sec
[-----------------80%----------        ] 1600 of 2000 complete in 2137.7 sec
[-----------------80%----------        ] 1601 of 2000 complete in 2139.1 sec
[-----------------80%----------        ] 1602 of 2000 complete in 2140.4 sec
[-----------------80%----------        ] 1603 of 2000 complete in 2141.8 sec
[-----------------80%----------        ] 1604 of 2000 complete in 2143.2 sec
[-----------------80%----------        ] 1605 of 2000 complete in 2144.6 sec
[-----------------80%----------        ] 1606 of 2000 complete in 2146.0 sec
[-----------------80%----------        ] 1607 of 2000 complete in 2147.4 sec
[-----------------80%----------        ] 1608 of 2000 complete in 2148.8 sec
[-----------------80%----------        ] 1609 of 2000 complete in 2150.1 sec
[-----------------80%----------        ] 1610 of 2000 complete in 2151.5 sec
[-----------------80%----------        ] 1611 of 2000 complete in 2153.0 sec
[-----------------80%----------        ] 1612 of 2000 complete in 2154.4 sec
[-----------------80%----------        ] 1613 of 2000 complete in 2155.7 sec
[-----------------80%----------        ] 1614 of 2000 complete in 2157.1 sec
[-----------------80%----------        ] 1615 of 2000 complete in 2158.5 sec
[-----------------80%----------        ] 1616 of 2000 complete in 2159.8 sec
[-----------------75%--------          ] 1511 of 2000 complete in 2019.0 sec
[-----------------75%--------          ] 1512 of 2000 complete in 2020.5 sec
[-----------------75%--------          ] 1513 of 2000 complete in 2021.9 sec
[-----------------75%--------          ] 1514 of 2000 complete in 2023.3 sec
[-----------------75%--------          ] 1515 of 2000 complete in 2024.6 sec
[-----------------75%--------          ] 1516 of 2000 complete in 2026.0 sec
[-----------------75%--------          ] 1517 of 2000 complete in 2027.5 sec
[-----------------75%--------          ] 1518 of 2000 complete in 2028.9 sec
[-----------------75%--------          ] 1519 of 2000 complete in 2030.3 sec
[-----------------76%--------          ] 1520 of 2000 complete in 2031.7 sec
[-----------------76%--------          ] 1521 of 2000 complete in 2033.1 sec
[-----------------76%--------          ] 1522 of 2000 complete in 2034.5 sec
[-----------------76%--------          ] 1523 of 2000 complete in 2035.9 sec
[-----------------76%--------          ] 1524 of 2000 complete in 2037.4 sec
[-----------------76%--------          ] 1525 of 2000 complete in 2038.7 sec
[-----------------76%--------          ] 1526 of 2000 complete in 2040.1 sec
[-----------------76%---------         ] 1527 of 2000 complete in 2041.5 sec
[-----------------76%---------         ] 1528 of 2000 complete in 2042.9 sec
[-----------------76%---------         ] 1529 of 2000 complete in 2044.3 sec
[-----------------76%---------         ] 1530 of 2000 complete in 2045.7 sec
[-----------------76%---------         ] 1531 of 2000 complete in 2047.1 sec
[-----------------76%---------         ] 1532 of 2000 complete in 2048.5 sec
[-----------------76%---------         ] 1533 of 2000 complete in 2049.9 sec
[-----------------76%---------         ] 1534 of 2000 complete in 2051.3 sec
[-----------------76%---------         ] 1535 of 2000 complete in 2052.7 sec
[-----------------76%---------         ] 1536 of 2000 complete in 2054.1 sec
[-----------------76%---------         ] 1537 of 2000 complete in 2055.5 sec
[-----------------76%---------         ] 1538 of 2000 complete in 2056.9 sec
[-----------------76%---------         ] 1539 of 2000 complete in 2058.4 sec
[-----------------77%---------         ] 1540 of 2000 complete in 2059.9 sec
[-----------------77%---------         ] 1541 of 2000 complete in 2061.3 sec
[-----------------77%---------         ] 1542 of 2000 complete in 2062.8 sec
[-----------------77%---------         ] 1543 of 2000 complete in 2064.2 sec
[-----------------77%---------         ] 1544 of 2000 complete in 2065.6 sec
[-----------------77%---------         ] 1545 of 2000 complete in 2067.0 sec
[-----------------77%---------         ] 1546 of 2000 complete in 2068.5 sec
[-----------------77%---------         ] 1547 of 2000 complete in 2070.0 sec
[-----------------77%---------         ] 1548 of 2000 complete in 2071.4 sec
[-----------------77%---------         ] 1549 of 2000 complete in 2072.7 sec
[-----------------77%---------         ] 1550 of 2000 complete in 2074.2 sec
[-----------------77%---------         ] 1551 of 2000 complete in 2075.5 sec
[-----------------77%---------         ] 1552 of 2000 complete in 2077.0 sec
[-----------------77%---------         ] 1553 of 2000 complete in 2078.4 sec
[-----------------77%---------         ] 1554 of 2000 complete in 2079.8 sec
[-----------------77%---------         ] 1555 of 2000 complete in 2081.3 sec
[-----------------77%---------         ] 1556 of 2000 complete in 2082.7 sec
[-----------------77%---------         ] 1557 of 2000 complete in 2084.1 sec
[-----------------77%---------         ] 1558 of 2000 complete in 2085.4 sec
[-----------------77%---------         ] 1559 of 2000 complete in 2086.9 sec
[-----------------78%---------         ] 1560 of 2000 complete in 2088.3 sec
[-----------------78%---------         ] 1561 of 2000 complete in 2089.8 sec
[-----------------78%---------         ] 1562 of 2000 complete in 2091.1 sec
[-----------------78%---------         ] 1563 of 2000 complete in 2092.5 sec
[-----------------78%---------         ] 1564 of 2000 complete in 2093.9 sec
[-----------------78%---------         ] 1565 of 2000 complete in 2095.3 sec
[-----------------78%---------         ] 1566 of 2000 complete in 2096.6 sec
[-----------------78%---------         ] 1567 of 2000 complete in 2098.0 sec
[-----------------78%---------         ] 1568 of 2000 complete in 2099.3 sec
[-----------------78%---------         ] 1569 of 2000 complete in 2100.7 sec
[-----------------78%---------         ] 1570 of 2000 complete in 2102.0 sec
[-----------------78%---------         ] 1571 of 2000 complete in 2103.4 sec
[-----------------78%---------         ] 1572 of 2000 complete in 2104.7 sec
[-----------------78%---------         ] 1573 of 2000 complete in 2106.1 sec
[-----------------78%---------         ] 1574 of 2000 complete in 2107.4 sec
[-----------------78%---------         ] 1575 of 2000 complete in 2108.8 sec
[-----------------78%---------         ] 1576 of 2000 complete in 2110.2 sec
[-----------------78%---------         ] 1577 of 2000 complete in 2111.6 sec
[-----------------78%---------         ] 1578 of 2000 complete in 2113.0 sec
[-----------------78%----------        ] 1579 of 2000 complete in 2114.3 sec
[-----------------79%----------        ] 1580 of 2000 complete in 2115.7 sec
[-----------------79%----------        ] 1581 of 2000 complete in 2117.1 sec
[-----------------79%----------        ] 1582 of 2000 complete in 2118.5 sec
[-----------------79%----------        ] 1583 of 2000 complete in 2119.9 sec
[-----------------79%----------        ] 1584 of 2000 complete in 2121.3 sec
[-----------------79%----------        ] 1585 of 2000 complete in 2122.7 sec
[-----------------79%----------        ] 1586 of 2000 complete in 2124.0 sec
[-----------------79%----------        ] 1587 of 2000 complete in 2125.5 sec
[-----------------79%----------        ] 1588 of 2000 complete in 2126.9 sec
[-----------------79%----------        ] 1589 of 2000 complete in 2128.3 sec
[-----------------79%----------        ] 1590 of 2000 complete in 2129.6 sec
[-----------------79%----------        ] 1591 of 2000 complete in 2130.9 sec
[-----------------79%----------        ] 1592 of 2000 complete in 2132.3 sec
[-----------------79%----------        ] 1593 of 2000 complete in 2133.7 sec
[-----------------79%----------        ] 1594 of 2000 complete in 2135.1 sec
[-----------------79%----------        ] 1595 of 2000 complete in 2136.5 sec
[-----------------79%----------        ] 1596 of 2000 complete in 2137.8 sec
[-----------------79%----------        ] 1597 of 2000 complete in 2139.3 sec
[-----------------79%----------        ] 1598 of 2000 complete in 2140.8 sec
[-----------------79%----------        ] 1599 of 2000 complete in 2142.2 sec
[-----------------80%----------        ] 1600 of 2000 complete in 2143.7 sec
[-----------------80%----------        ] 1601 of 2000 complete in 2145.1 sec
[-----------------80%----------        ] 1602 of 2000 complete in 2146.5 sec
[-----------------80%----------        ] 1603 of 2000 complete in 2147.9 sec
[-----------------80%----------        ] 1604 of 2000 complete in 2149.3 sec
[-----------------80%----------        ] 1605 of 2000 complete in 2150.7 sec
[-----------------80%----------        ] 1606 of 2000 complete in 2152.2 sec
[-----------------80%----------        ] 1607 of 2000 complete in 2153.6 sec
[-----------------80%----------        ] 1608 of 2000 complete in 2154.9 sec
[-----------------80%----------        ] 1609 of 2000 complete in 2156.3 sec
[-----------------80%----------        ] 1610 of 2000 complete in 2157.7 sec
[-----------------80%----------        ] 1611 of 2000 complete in 2159.1 sec
[-----------------80%----------        ] 1612 of 2000 complete in 2160.4 sec
[-----------------80%----------        ] 1613 of 2000 complete in 2161.8 sec
[-----------------80%----------        ] 1614 of 2000 complete in 2163.1 sec
[-----------------80%----------        ] 1615 of 2000 complete in 2164.5 sec
[-----------------80%----------        ] 1616 of 2000 complete in 2165.8 sec

[-----------------75%--------          ] 1511 of 2000 complete in 2023.6 sec
[-----------------75%--------          ] 1512 of 2000 complete in 2025.0 sec
[-----------------75%--------          ] 1513 of 2000 complete in 2026.4 sec
[-----------------75%--------          ] 1514 of 2000 complete in 2027.8 sec
[-----------------75%--------          ] 1515 of 2000 complete in 2029.3 sec
[-----------------75%--------          ] 1516 of 2000 complete in 2030.7 sec
[-----------------75%--------          ] 1517 of 2000 complete in 2032.0 sec
[-----------------75%--------          ] 1518 of 2000 complete in 2033.5 sec
[-----------------75%--------          ] 1519 of 2000 complete in 2034.9 sec
[-----------------76%--------          ] 1520 of 2000 complete in 2036.3 sec
[-----------------76%--------          ] 1521 of 2000 complete in 2037.7 sec
[-----------------76%--------          ] 1522 of 2000 complete in 2039.1 sec
[-----------------76%--------          ] 1523 of 2000 complete in 2040.5 sec
[-----------------76%--------          ] 1524 of 2000 complete in 2041.9 sec
[-----------------76%--------          ] 1525 of 2000 complete in 2043.3 sec
[-----------------76%--------          ] 1526 of 2000 complete in 2044.6 sec
[-----------------76%---------         ] 1527 of 2000 complete in 2046.1 sec
[-----------------76%---------         ] 1528 of 2000 complete in 2047.5 sec
[-----------------76%---------         ] 1529 of 2000 complete in 2048.9 sec
[-----------------76%---------         ] 1530 of 2000 complete in 2050.4 sec
[-----------------76%---------         ] 1531 of 2000 complete in 2051.8 sec
[-----------------76%---------         ] 1532 of 2000 complete in 2053.2 sec
[-----------------76%---------         ] 1533 of 2000 complete in 2054.6 sec
[-----------------76%---------         ] 1534 of 2000 complete in 2056.1 sec
[-----------------76%---------         ] 1535 of 2000 complete in 2057.5 sec
[-----------------76%---------         ] 1536 of 2000 complete in 2058.9 sec
[-----------------76%---------         ] 1537 of 2000 complete in 2060.4 sec
[-----------------76%---------         ] 1538 of 2000 complete in 2061.9 sec
[-----------------76%---------         ] 1539 of 2000 complete in 2063.3 sec
[-----------------77%---------         ] 1540 of 2000 complete in 2064.7 sec
[-----------------77%---------         ] 1541 of 2000 complete in 2066.2 sec
[-----------------77%---------         ] 1542 of 2000 complete in 2067.5 sec
[-----------------77%---------         ] 1543 of 2000 complete in 2069.0 sec
[-----------------77%---------         ] 1544 of 2000 complete in 2070.4 sec
[-----------------77%---------         ] 1545 of 2000 complete in 2071.8 sec
[-----------------77%---------         ] 1546 of 2000 complete in 2073.2 sec
[-----------------77%---------         ] 1547 of 2000 complete in 2074.6 sec
[-----------------77%---------         ] 1548 of 2000 complete in 2075.9 sec
[-----------------77%---------         ] 1549 of 2000 complete in 2077.3 sec
[-----------------77%---------         ] 1550 of 2000 complete in 2078.7 sec
[-----------------77%---------         ] 1551 of 2000 complete in 2080.2 sec
[-----------------77%---------         ] 1552 of 2000 complete in 2081.6 sec
[-----------------77%---------         ] 1553 of 2000 complete in 2083.0 sec
[-----------------77%---------         ] 1554 of 2000 complete in 2084.4 sec
[-----------------77%---------         ] 1555 of 2000 complete in 2085.8 sec
[-----------------77%---------         ] 1556 of 2000 complete in 2087.2 sec
[-----------------77%---------         ] 1557 of 2000 complete in 2088.6 sec
[-----------------77%---------         ] 1558 of 2000 complete in 2090.0 sec
[-----------------77%---------         ] 1559 of 2000 complete in 2091.4 sec
[-----------------78%---------         ] 1560 of 2000 complete in 2092.8 sec
[-----------------78%---------         ] 1561 of 2000 complete in 2094.2 sec
[-----------------78%---------         ] 1562 of 2000 complete in 2095.6 sec
[-----------------78%---------         ] 1563 of 2000 complete in 2097.0 sec
[-----------------78%---------         ] 1564 of 2000 complete in 2098.4 sec
[-----------------78%---------         ] 1565 of 2000 complete in 2099.9 sec
[-----------------78%---------         ] 1566 of 2000 complete in 2101.3 sec
[-----------------78%---------         ] 1567 of 2000 complete in 2102.7 sec
[-----------------78%---------         ] 1568 of 2000 complete in 2104.0 sec
[-----------------78%---------         ] 1569 of 2000 complete in 2105.5 sec
[-----------------78%---------         ] 1570 of 2000 complete in 2106.8 sec
[-----------------78%---------         ] 1571 of 2000 complete in 2108.2 sec
[-----------------78%---------         ] 1572 of 2000 complete in 2109.6 sec
[-----------------78%---------         ] 1573 of 2000 complete in 2111.0 sec
[-----------------78%---------         ] 1574 of 2000 complete in 2112.3 sec
[-----------------78%---------         ] 1575 of 2000 complete in 2113.7 sec
[-----------------78%---------         ] 1576 of 2000 complete in 2115.1 sec
[-----------------78%---------         ] 1577 of 2000 complete in 2116.5 sec
[-----------------78%---------         ] 1578 of 2000 complete in 2117.8 sec
[-----------------78%----------        ] 1579 of 2000 complete in 2119.2 sec
[-----------------79%----------        ] 1580 of 2000 complete in 2120.5 sec
[-----------------79%----------        ] 1581 of 2000 complete in 2121.8 sec
[-----------------79%----------        ] 1582 of 2000 complete in 2123.2 sec
[-----------------79%----------        ] 1583 of 2000 complete in 2124.6 sec
[-----------------79%----------        ] 1584 of 2000 complete in 2125.9 sec
[-----------------79%----------        ] 1585 of 2000 complete in 2127.3 sec
[-----------------79%----------        ] 1586 of 2000 complete in 2128.7 sec
[-----------------79%----------        ] 1587 of 2000 complete in 2130.1 sec
[-----------------79%----------        ] 1588 of 2000 complete in 2131.5 sec
[-----------------79%----------        ] 1589 of 2000 complete in 2132.9 sec
[-----------------79%----------        ] 1590 of 2000 complete in 2134.3 sec
[-----------------79%----------        ] 1591 of 2000 complete in 2135.7 sec
[-----------------79%----------        ] 1592 of 2000 complete in 2137.1 sec
[-----------------79%----------        ] 1593 of 2000 complete in 2138.4 sec
[-----------------79%----------        ] 1594 of 2000 complete in 2139.8 sec
[-----------------79%----------        ] 1595 of 2000 complete in 2141.2 sec
[-----------------79%----------        ] 1596 of 2000 complete in 2142.5 sec
[-----------------79%----------        ] 1597 of 2000 complete in 2144.0 sec
[-----------------79%----------        ] 1598 of 2000 complete in 2145.4 sec
[-----------------79%----------        ] 1599 of 2000 complete in 2146.8 sec
[-----------------80%----------        ] 1600 of 2000 complete in 2148.2 sec
[-----------------80%----------        ] 1601 of 2000 complete in 2149.6 sec
[-----------------80%----------        ] 1602 of 2000 complete in 2151.0 sec
[-----------------80%----------        ] 1603 of 2000 complete in 2152.5 sec
[-----------------80%----------        ] 1604 of 2000 complete in 2153.9 sec
[-----------------80%----------        ] 1605 of 2000 complete in 2155.3 sec
[-----------------80%----------        ] 1606 of 2000 complete in 2156.7 sec
[-----------------80%----------        ] 1607 of 2000 complete in 2158.0 sec
[-----------------80%----------        ] 1608 of 2000 complete in 2159.5 sec
[-----------------80%----------        ] 1609 of 2000 complete in 2160.8 sec
[-----------------80%----------        ] 1610 of 2000 complete in 2162.2 sec
[-----------------80%----------        ] 1611 of 2000 complete in 2163.6 sec
[-----------------80%----------        ] 1612 of 2000 complete in 2164.9 sec
[-----------------80%----------        ] 1613 of 2000 complete in 2166.3 sec
[-----------------80%----------        ] 1614 of 2000 complete in 2167.7 sec
[-----------------80%----------        ] 1615 of 2000 complete in 2169.1 sec
[-----------------80%----------        ] 1616 of 2000 complete in 2170.4 sec
[-----------------75%--------          ] 1510 of 2000 complete in 2050.5 sec
[-----------------75%--------          ] 1511 of 2000 complete in 2051.9 sec
[-----------------75%--------          ] 1512 of 2000 complete in 2053.3 sec
[-----------------75%--------          ] 1513 of 2000 complete in 2054.7 sec
[-----------------75%--------          ] 1514 of 2000 complete in 2056.1 sec
[-----------------75%--------          ] 1515 of 2000 complete in 2057.5 sec
[-----------------75%--------          ] 1516 of 2000 complete in 2058.9 sec
[-----------------75%--------          ] 1517 of 2000 complete in 2060.3 sec
[-----------------75%--------          ] 1518 of 2000 complete in 2061.7 sec
[-----------------75%--------          ] 1519 of 2000 complete in 2063.1 sec
[-----------------76%--------          ] 1520 of 2000 complete in 2064.6 sec
[-----------------76%--------          ] 1521 of 2000 complete in 2065.9 sec
[-----------------76%--------          ] 1522 of 2000 complete in 2067.3 sec
[-----------------76%--------          ] 1523 of 2000 complete in 2068.8 sec
[-----------------76%--------          ] 1524 of 2000 complete in 2070.2 sec
[-----------------76%--------          ] 1525 of 2000 complete in 2071.6 sec
[-----------------76%--------          ] 1526 of 2000 complete in 2073.0 sec
[-----------------76%---------         ] 1527 of 2000 complete in 2074.3 sec
[-----------------76%---------         ] 1528 of 2000 complete in 2075.7 sec
[-----------------76%---------         ] 1529 of 2000 complete in 2077.1 sec
[-----------------76%---------         ] 1530 of 2000 complete in 2078.5 sec
[-----------------76%---------         ] 1531 of 2000 complete in 2079.9 sec
[-----------------76%---------         ] 1532 of 2000 complete in 2081.3 sec
[-----------------76%---------         ] 1533 of 2000 complete in 2082.7 sec
[-----------------76%---------         ] 1534 of 2000 complete in 2084.0 sec
[-----------------76%---------         ] 1535 of 2000 complete in 2085.4 sec
[-----------------76%---------         ] 1536 of 2000 complete in 2086.8 sec
[-----------------76%---------         ] 1537 of 2000 complete in 2088.2 sec
[-----------------76%---------         ] 1538 of 2000 complete in 2089.6 sec
[-----------------76%---------         ] 1539 of 2000 complete in 2090.9 sec
[-----------------77%---------         ] 1540 of 2000 complete in 2092.3 sec
[-----------------77%---------         ] 1541 of 2000 complete in 2093.7 sec
[-----------------77%---------         ] 1542 of 2000 complete in 2095.1 sec
[-----------------77%---------         ] 1543 of 2000 complete in 2096.5 sec
[-----------------77%---------         ] 1544 of 2000 complete in 2097.9 sec
[-----------------77%---------         ] 1545 of 2000 complete in 2099.3 sec
[-----------------77%---------         ] 1546 of 2000 complete in 2100.6 sec
[-----------------77%---------         ] 1547 of 2000 complete in 2102.0 sec
[-----------------77%---------         ] 1548 of 2000 complete in 2103.4 sec
[-----------------77%---------         ] 1549 of 2000 complete in 2104.8 sec
[-----------------77%---------         ] 1550 of 2000 complete in 2106.1 sec
[-----------------77%---------         ] 1551 of 2000 complete in 2107.5 sec
[-----------------77%---------         ] 1552 of 2000 complete in 2108.9 sec
[-----------------77%---------         ] 1553 of 2000 complete in 2110.2 sec
[-----------------77%---------         ] 1554 of 2000 complete in 2111.6 sec
[-----------------77%---------         ] 1555 of 2000 complete in 2112.9 sec
[-----------------77%---------         ] 1556 of 2000 complete in 2114.3 sec
[-----------------77%---------         ] 1557 of 2000 complete in 2115.7 sec
[-----------------77%---------         ] 1558 of 2000 complete in 2117.1 sec
[-----------------77%---------         ] 1559 of 2000 complete in 2118.5 sec
[-----------------78%---------         ] 1560 of 2000 complete in 2119.9 sec
[-----------------78%---------         ] 1561 of 2000 complete in 2121.3 sec
[-----------------78%---------         ] 1562 of 2000 complete in 2122.6 sec
[-----------------78%---------         ] 1563 of 2000 complete in 2123.9 sec
[-----------------78%---------         ] 1564 of 2000 complete in 2125.3 sec
[-----------------78%---------         ] 1565 of 2000 complete in 2126.7 sec
[-----------------78%---------         ] 1566 of 2000 complete in 2128.1 sec
[-----------------78%---------         ] 1567 of 2000 complete in 2129.5 sec
[-----------------78%---------         ] 1568 of 2000 complete in 2130.9 sec
[-----------------78%---------         ] 1569 of 2000 complete in 2132.3 sec
[-----------------78%---------         ] 1570 of 2000 complete in 2133.6 sec
[-----------------78%---------         ] 1571 of 2000 complete in 2135.0 sec
[-----------------78%---------         ] 1572 of 2000 complete in 2136.4 sec
[-----------------78%---------         ] 1573 of 2000 complete in 2137.7 sec
[-----------------78%---------         ] 1574 of 2000 complete in 2139.0 sec
[-----------------78%---------         ] 1575 of 2000 complete in 2140.4 sec
[-----------------78%---------         ] 1576 of 2000 complete in 2141.8 sec
[-----------------78%---------         ] 1577 of 2000 complete in 2143.2 sec
[-----------------78%---------         ] 1578 of 2000 complete in 2144.6 sec
[-----------------78%----------        ] 1579 of 2000 complete in 2146.0 sec
[-----------------79%----------        ] 1580 of 2000 complete in 2147.4 sec
[-----------------79%----------        ] 1581 of 2000 complete in 2148.8 sec
[-----------------79%----------        ] 1582 of 2000 complete in 2150.3 sec
[-----------------79%----------        ] 1583 of 2000 complete in 2151.6 sec
[-----------------79%----------        ] 1584 of 2000 complete in 2153.1 sec
[-----------------79%----------        ] 1585 of 2000 complete in 2154.4 sec
[-----------------79%----------        ] 1586 of 2000 complete in 2155.7 sec
[-----------------79%----------        ] 1587 of 2000 complete in 2157.1 sec
[-----------------79%----------        ] 1588 of 2000 complete in 2158.4 sec
[-----------------79%----------        ] 1589 of 2000 complete in 2159.7 sec
[-----------------79%----------        ] 1590 of 2000 complete in 2161.0 sec
[-----------------79%----------        ] 1591 of 2000 complete in 2162.4 sec
[-----------------79%----------        ] 1592 of 2000 complete in 2163.7 sec
[-----------------79%----------        ] 1593 of 2000 complete in 2165.2 sec
[-----------------79%----------        ] 1594 of 2000 complete in 2166.6 sec
[-----------------79%----------        ] 1595 of 2000 complete in 2168.0 sec
[-----------------79%----------        ] 1596 of 2000 complete in 2169.3 sec
[-----------------79%----------        ] 1597 of 2000 complete in 2170.8 sec
[-----------------79%----------        ] 1598 of 2000 complete in 2172.1 sec
[-----------------79%----------        ] 1599 of 2000 complete in 2173.6 sec
[-----------------80%----------        ] 1600 of 2000 complete in 2175.0 sec
[-----------------80%----------        ] 1601 of 2000 complete in 2176.3 sec
[-----------------80%----------        ] 1602 of 2000 complete in 2177.7 sec
[-----------------80%----------        ] 1603 of 2000 complete in 2179.1 sec
[-----------------80%----------        ] 1604 of 2000 complete in 2180.5 sec
[-----------------80%----------        ] 1605 of 2000 complete in 2181.9 sec
[-----------------80%----------        ] 1606 of 2000 complete in 2183.3 sec
[-----------------80%----------        ] 1607 of 2000 complete in 2184.7 sec
[-----------------80%----------        ] 1608 of 2000 complete in 2186.2 sec
[-----------------80%----------        ] 1609 of 2000 complete in 2187.6 sec
[-----------------80%----------        ] 1610 of 2000 complete in 2189.0 sec
[-----------------80%----------        ] 1611 of 2000 complete in 2190.4 sec
[-----------------80%----------        ] 1612 of 2000 complete in 2191.8 sec
[-----------------80%----------        ] 1613 of 2000 complete in 2193.2 sec
[-----------------80%----------        ] 1614 of 2000 complete in 2194.6 sec
[-----------------80%----------        ] 1615 of 2000 complete in 2196.0 sec

[-----------------80%----------        ] 1617 of 2000 complete in 2161.2 sec
[-----------------80%----------        ] 1618 of 2000 complete in 2162.6 sec
[-----------------80%----------        ] 1619 of 2000 complete in 2163.9 sec
[-----------------81%----------        ] 1620 of 2000 complete in 2165.3 sec
[-----------------81%----------        ] 1621 of 2000 complete in 2166.7 sec
[-----------------81%----------        ] 1622 of 2000 complete in 2168.1 sec
[-----------------81%----------        ] 1623 of 2000 complete in 2169.4 sec
[-----------------81%----------        ] 1624 of 2000 complete in 2170.7 sec
[-----------------81%----------        ] 1625 of 2000 complete in 2172.1 sec
[-----------------81%----------        ] 1626 of 2000 complete in 2173.5 sec
[-----------------81%----------        ] 1627 of 2000 complete in 2174.9 sec
[-----------------81%----------        ] 1628 of 2000 complete in 2176.3 sec
[-----------------81%----------        ] 1629 of 2000 complete in 2177.7 sec
[-----------------81%----------        ] 1630 of 2000 complete in 2179.1 sec
[-----------------81%----------        ] 1631 of 2000 complete in 2180.5 sec
[-----------------81%-----------       ] 1632 of 2000 complete in 2181.8 sec
[-----------------81%-----------       ] 1633 of 2000 complete in 2183.3 sec
[-----------------81%-----------       ] 1634 of 2000 complete in 2184.6 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 2186.1 sec
[-----------------81%-----------       ] 1636 of 2000 complete in 2187.4 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 2188.8 sec
[-----------------81%-----------       ] 1638 of 2000 complete in 2190.1 sec
[-----------------81%-----------       ] 1639 of 2000 complete in 2191.5 sec
[-----------------82%-----------       ] 1640 of 2000 complete in 2192.9 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 2194.3 sec
[-----------------82%-----------       ] 1642 of 2000 complete in 2195.7 sec
[-----------------82%-----------       ] 1643 of 2000 complete in 2197.0 sec
[-----------------82%-----------       ] 1644 of 2000 complete in 2198.4 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 2199.8 sec
[-----------------82%-----------       ] 1646 of 2000 complete in 2201.2 sec
[-----------------82%-----------       ] 1647 of 2000 complete in 2202.6 sec
[-----------------82%-----------       ] 1648 of 2000 complete in 2203.9 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 2205.3 sec
[-----------------82%-----------       ] 1650 of 2000 complete in 2206.7 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 2208.1 sec
[-----------------82%-----------       ] 1652 of 2000 complete in 2209.4 sec
[-----------------82%-----------       ] 1653 of 2000 complete in 2210.8 sec
[-----------------82%-----------       ] 1654 of 2000 complete in 2212.2 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 2213.6 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 2214.9 sec
[-----------------82%-----------       ] 1657 of 2000 complete in 2216.3 sec
[-----------------82%-----------       ] 1658 of 2000 complete in 2217.7 sec
[-----------------82%-----------       ] 1659 of 2000 complete in 2219.2 sec
[-----------------83%-----------       ] 1660 of 2000 complete in 2220.6 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 2221.9 sec
[-----------------83%-----------       ] 1662 of 2000 complete in 2223.4 sec
[-----------------83%-----------       ] 1663 of 2000 complete in 2224.8 sec
[-----------------83%-----------       ] 1664 of 2000 complete in 2226.2 sec
[-----------------83%-----------       ] 1665 of 2000 complete in 2227.6 sec
[-----------------83%-----------       ] 1666 of 2000 complete in 2229.0 sec
[-----------------83%-----------       ] 1667 of 2000 complete in 2230.3 sec
[-----------------83%-----------       ] 1668 of 2000 complete in 2231.8 sec
[-----------------83%-----------       ] 1669 of 2000 complete in 2233.2 sec
[-----------------83%-----------       ] 1670 of 2000 complete in 2234.6 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 2236.1 sec
[-----------------83%-----------       ] 1672 of 2000 complete in 2237.4 sec
[-----------------83%-----------       ] 1673 of 2000 complete in 2238.8 sec
[-----------------83%-----------       ] 1674 of 2000 complete in 2240.2 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 2241.6 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 2242.9 sec
[-----------------83%-----------       ] 1677 of 2000 complete in 2244.3 sec
[-----------------83%-----------       ] 1678 of 2000 complete in 2245.7 sec
[-----------------83%-----------       ] 1679 of 2000 complete in 2247.2 sec
[-----------------84%-----------       ] 1680 of 2000 complete in 2248.6 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 2250.0 sec
[-----------------84%-----------       ] 1682 of 2000 complete in 2251.4 sec
[-----------------84%-----------       ] 1683 of 2000 complete in 2252.8 sec
[-----------------84%-----------       ] 1684 of 2000 complete in 2254.2 sec
[-----------------84%------------      ] 1685 of 2000 complete in 2255.7 sec
[-----------------84%------------      ] 1686 of 2000 complete in 2257.1 sec
[-----------------84%------------      ] 1687 of 2000 complete in 2258.4 sec
[-----------------84%------------      ] 1688 of 2000 complete in 2259.8 sec
[-----------------84%------------      ] 1689 of 2000 complete in 2261.2 sec
[-----------------84%------------      ] 1690 of 2000 complete in 2262.6 sec
[-----------------84%------------      ] 1691 of 2000 complete in 2264.0 sec
[-----------------84%------------      ] 1692 of 2000 complete in 2265.4 sec
[-----------------84%------------      ] 1693 of 2000 complete in 2266.8 sec
[-----------------84%------------      ] 1694 of 2000 complete in 2268.2 sec
[-----------------84%------------      ] 1695 of 2000 complete in 2269.5 sec
[-----------------84%------------      ] 1696 of 2000 complete in 2270.9 sec
[-----------------84%------------      ] 1697 of 2000 complete in 2272.3 sec
[-----------------84%------------      ] 1698 of 2000 complete in 2273.7 sec
[-----------------84%------------      ] 1699 of 2000 complete in 2275.1 sec
[-----------------85%------------      ] 1700 of 2000 complete in 2276.5 sec
[-----------------85%------------      ] 1701 of 2000 complete in 2277.8 sec
[-----------------85%------------      ] 1702 of 2000 complete in 2279.1 sec
[-----------------85%------------      ] 1703 of 2000 complete in 2280.5 sec
[-----------------85%------------      ] 1704 of 2000 complete in 2281.8 sec
[-----------------85%------------      ] 1705 of 2000 complete in 2283.1 sec
[-----------------85%------------      ] 1706 of 2000 complete in 2284.5 sec
[-----------------85%------------      ] 1707 of 2000 complete in 2285.9 sec
[-----------------85%------------      ] 1708 of 2000 complete in 2287.3 sec
[-----------------85%------------      ] 1709 of 2000 complete in 2288.7 sec
[-----------------85%------------      ] 1710 of 2000 complete in 2290.1 sec
[-----------------85%------------      ] 1711 of 2000 complete in 2291.4 sec
[-----------------85%------------      ] 1712 of 2000 complete in 2292.9 sec
[-----------------85%------------      ] 1713 of 2000 complete in 2294.3 sec
[-----------------85%------------      ] 1714 of 2000 complete in 2295.7 sec
[-----------------85%------------      ] 1715 of 2000 complete in 2297.1 sec
[-----------------85%------------      ] 1716 of 2000 complete in 2298.5 sec
[-----------------85%------------      ] 1717 of 2000 complete in 2299.8 sec
[-----------------85%------------      ] 1718 of 2000 complete in 2301.3 sec
[-----------------85%------------      ] 1719 of 2000 complete in 2302.7 sec
[-----------------86%------------      ] 1720 of 2000 complete in 2304.1 sec
[-----------------86%------------      ] 1721 of 2000 complete in 2305.5 sec
[-----------------86%------------      ] 1722 of 2000 complete in 2307.0 sec
[-----------------80%----------        ] 1617 of 2000 complete in 2167.2 sec
[-----------------80%----------        ] 1618 of 2000 complete in 2168.6 sec
[-----------------80%----------        ] 1619 of 2000 complete in 2169.9 sec
[-----------------81%----------        ] 1620 of 2000 complete in 2171.2 sec
[-----------------81%----------        ] 1621 of 2000 complete in 2172.6 sec
[-----------------81%----------        ] 1622 of 2000 complete in 2174.0 sec
[-----------------81%----------        ] 1623 of 2000 complete in 2175.4 sec
[-----------------81%----------        ] 1624 of 2000 complete in 2176.7 sec
[-----------------81%----------        ] 1625 of 2000 complete in 2178.0 sec
[-----------------81%----------        ] 1626 of 2000 complete in 2179.3 sec
[-----------------81%----------        ] 1627 of 2000 complete in 2180.6 sec
[-----------------81%----------        ] 1628 of 2000 complete in 2182.0 sec
[-----------------81%----------        ] 1629 of 2000 complete in 2183.4 sec
[-----------------81%----------        ] 1630 of 2000 complete in 2184.8 sec
[-----------------81%----------        ] 1631 of 2000 complete in 2186.2 sec
[-----------------81%-----------       ] 1632 of 2000 complete in 2187.5 sec
[-----------------81%-----------       ] 1633 of 2000 complete in 2188.9 sec
[-----------------81%-----------       ] 1634 of 2000 complete in 2190.2 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 2191.6 sec
[-----------------81%-----------       ] 1636 of 2000 complete in 2193.0 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 2194.4 sec
[-----------------81%-----------       ] 1638 of 2000 complete in 2195.8 sec
[-----------------81%-----------       ] 1639 of 2000 complete in 2197.2 sec
[-----------------82%-----------       ] 1640 of 2000 complete in 2198.5 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 2199.9 sec
[-----------------82%-----------       ] 1642 of 2000 complete in 2201.3 sec
[-----------------82%-----------       ] 1643 of 2000 complete in 2202.7 sec
[-----------------82%-----------       ] 1644 of 2000 complete in 2204.0 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 2205.4 sec
[-----------------82%-----------       ] 1646 of 2000 complete in 2206.8 sec
[-----------------82%-----------       ] 1647 of 2000 complete in 2208.2 sec
[-----------------82%-----------       ] 1648 of 2000 complete in 2209.6 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 2211.0 sec
[-----------------82%-----------       ] 1650 of 2000 complete in 2212.3 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 2213.7 sec
[-----------------82%-----------       ] 1652 of 2000 complete in 2215.0 sec
[-----------------82%-----------       ] 1653 of 2000 complete in 2216.4 sec
[-----------------82%-----------       ] 1654 of 2000 complete in 2217.8 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 2219.1 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 2220.5 sec
[-----------------82%-----------       ] 1657 of 2000 complete in 2221.9 sec
[-----------------82%-----------       ] 1658 of 2000 complete in 2223.3 sec
[-----------------82%-----------       ] 1659 of 2000 complete in 2224.6 sec
[-----------------83%-----------       ] 1660 of 2000 complete in 2225.9 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 2227.3 sec
[-----------------83%-----------       ] 1662 of 2000 complete in 2228.6 sec
[-----------------83%-----------       ] 1663 of 2000 complete in 2230.0 sec
[-----------------83%-----------       ] 1664 of 2000 complete in 2231.4 sec
[-----------------83%-----------       ] 1665 of 2000 complete in 2232.9 sec
[-----------------83%-----------       ] 1666 of 2000 complete in 2234.2 sec
[-----------------83%-----------       ] 1667 of 2000 complete in 2235.6 sec
[-----------------83%-----------       ] 1668 of 2000 complete in 2237.0 sec
[-----------------83%-----------       ] 1669 of 2000 complete in 2238.3 sec
[-----------------83%-----------       ] 1670 of 2000 complete in 2239.7 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 2241.0 sec
[-----------------83%-----------       ] 1672 of 2000 complete in 2242.4 sec
[-----------------83%-----------       ] 1673 of 2000 complete in 2243.8 sec
[-----------------83%-----------       ] 1674 of 2000 complete in 2245.2 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 2246.7 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 2248.0 sec
[-----------------83%-----------       ] 1677 of 2000 complete in 2249.4 sec
[-----------------83%-----------       ] 1678 of 2000 complete in 2250.9 sec
[-----------------83%-----------       ] 1679 of 2000 complete in 2252.2 sec
[-----------------84%-----------       ] 1680 of 2000 complete in 2253.6 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 2255.0 sec
[-----------------84%-----------       ] 1682 of 2000 complete in 2256.3 sec
[-----------------84%-----------       ] 1683 of 2000 complete in 2257.7 sec
[-----------------84%-----------       ] 1684 of 2000 complete in 2259.1 sec
[-----------------84%------------      ] 1685 of 2000 complete in 2260.5 sec
[-----------------84%------------      ] 1686 of 2000 complete in 2261.9 sec
[-----------------84%------------      ] 1687 of 2000 complete in 2263.2 sec
[-----------------84%------------      ] 1688 of 2000 complete in 2264.6 sec
[-----------------84%------------      ] 1689 of 2000 complete in 2266.0 sec
[-----------------84%------------      ] 1690 of 2000 complete in 2267.4 sec
[-----------------84%------------      ] 1691 of 2000 complete in 2268.8 sec
[-----------------84%------------      ] 1692 of 2000 complete in 2270.2 sec
[-----------------84%------------      ] 1693 of 2000 complete in 2271.6 sec
[-----------------84%------------      ] 1694 of 2000 complete in 2273.0 sec
[-----------------84%------------      ] 1695 of 2000 complete in 2274.3 sec
[-----------------84%------------      ] 1696 of 2000 complete in 2275.7 sec
[-----------------84%------------      ] 1697 of 2000 complete in 2277.1 sec
[-----------------84%------------      ] 1698 of 2000 complete in 2278.4 sec
[-----------------84%------------      ] 1699 of 2000 complete in 2279.7 sec
[-----------------85%------------      ] 1700 of 2000 complete in 2281.1 sec
[-----------------85%------------      ] 1701 of 2000 complete in 2282.4 sec
[-----------------85%------------      ] 1702 of 2000 complete in 2283.8 sec
[-----------------85%------------      ] 1703 of 2000 complete in 2285.2 sec
[-----------------85%------------      ] 1704 of 2000 complete in 2286.6 sec
[-----------------85%------------      ] 1705 of 2000 complete in 2287.9 sec
[-----------------85%------------      ] 1706 of 2000 complete in 2289.3 sec
[-----------------85%------------      ] 1707 of 2000 complete in 2290.6 sec
[-----------------85%------------      ] 1708 of 2000 complete in 2292.1 sec
[-----------------85%------------      ] 1709 of 2000 complete in 2293.5 sec
[-----------------85%------------      ] 1710 of 2000 complete in 2294.8 sec
[-----------------85%------------      ] 1711 of 2000 complete in 2296.2 sec
[-----------------85%------------      ] 1712 of 2000 complete in 2297.6 sec
[-----------------85%------------      ] 1713 of 2000 complete in 2298.9 sec
[-----------------85%------------      ] 1714 of 2000 complete in 2300.3 sec
[-----------------85%------------      ] 1715 of 2000 complete in 2301.7 sec
[-----------------85%------------      ] 1716 of 2000 complete in 2303.1 sec
[-----------------85%------------      ] 1717 of 2000 complete in 2304.4 sec
[-----------------85%------------      ] 1718 of 2000 complete in 2305.8 sec
[-----------------85%------------      ] 1719 of 2000 complete in 2307.2 sec
[-----------------86%------------      ] 1720 of 2000 complete in 2308.6 sec
[-----------------86%------------      ] 1721 of 2000 complete in 2310.0 sec
[-----------------86%------------      ] 1722 of 2000 complete in 2311.3 sec

[-----------------80%----------        ] 1617 of 2000 complete in 2171.9 sec
[-----------------80%----------        ] 1618 of 2000 complete in 2173.3 sec
[-----------------80%----------        ] 1619 of 2000 complete in 2174.7 sec
[-----------------81%----------        ] 1620 of 2000 complete in 2176.1 sec
[-----------------81%----------        ] 1621 of 2000 complete in 2177.5 sec
[-----------------81%----------        ] 1622 of 2000 complete in 2178.9 sec
[-----------------81%----------        ] 1623 of 2000 complete in 2180.2 sec
[-----------------81%----------        ] 1624 of 2000 complete in 2181.6 sec
[-----------------81%----------        ] 1625 of 2000 complete in 2183.0 sec
[-----------------81%----------        ] 1626 of 2000 complete in 2184.4 sec
[-----------------81%----------        ] 1627 of 2000 complete in 2185.8 sec
[-----------------81%----------        ] 1628 of 2000 complete in 2187.2 sec
[-----------------81%----------        ] 1629 of 2000 complete in 2188.6 sec
[-----------------81%----------        ] 1630 of 2000 complete in 2190.0 sec
[-----------------81%----------        ] 1631 of 2000 complete in 2191.4 sec
[-----------------81%-----------       ] 1632 of 2000 complete in 2192.8 sec
[-----------------81%-----------       ] 1633 of 2000 complete in 2194.1 sec
[-----------------81%-----------       ] 1634 of 2000 complete in 2195.5 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 2196.9 sec
[-----------------81%-----------       ] 1636 of 2000 complete in 2198.3 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 2199.7 sec
[-----------------81%-----------       ] 1638 of 2000 complete in 2201.1 sec
[-----------------81%-----------       ] 1639 of 2000 complete in 2202.5 sec
[-----------------82%-----------       ] 1640 of 2000 complete in 2203.9 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 2205.3 sec
[-----------------82%-----------       ] 1642 of 2000 complete in 2206.7 sec
[-----------------82%-----------       ] 1643 of 2000 complete in 2208.1 sec
[-----------------82%-----------       ] 1644 of 2000 complete in 2209.5 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 2210.9 sec
[-----------------82%-----------       ] 1646 of 2000 complete in 2212.2 sec
[-----------------82%-----------       ] 1647 of 2000 complete in 2213.5 sec
[-----------------82%-----------       ] 1648 of 2000 complete in 2214.9 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 2216.3 sec
[-----------------82%-----------       ] 1650 of 2000 complete in 2217.7 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 2219.1 sec
[-----------------82%-----------       ] 1652 of 2000 complete in 2220.5 sec
[-----------------82%-----------       ] 1653 of 2000 complete in 2221.8 sec
[-----------------82%-----------       ] 1654 of 2000 complete in 2223.2 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 2224.6 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 2226.0 sec
[-----------------82%-----------       ] 1657 of 2000 complete in 2227.4 sec
[-----------------82%-----------       ] 1658 of 2000 complete in 2228.7 sec
[-----------------82%-----------       ] 1659 of 2000 complete in 2230.1 sec
[-----------------83%-----------       ] 1660 of 2000 complete in 2231.5 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 2232.8 sec
[-----------------83%-----------       ] 1662 of 2000 complete in 2234.2 sec
[-----------------83%-----------       ] 1663 of 2000 complete in 2235.6 sec
[-----------------83%-----------       ] 1664 of 2000 complete in 2236.9 sec
[-----------------83%-----------       ] 1665 of 2000 complete in 2238.3 sec
[-----------------83%-----------       ] 1666 of 2000 complete in 2239.6 sec
[-----------------83%-----------       ] 1667 of 2000 complete in 2241.1 sec
[-----------------83%-----------       ] 1668 of 2000 complete in 2242.5 sec
[-----------------83%-----------       ] 1669 of 2000 complete in 2243.8 sec
[-----------------83%-----------       ] 1670 of 2000 complete in 2245.2 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 2246.7 sec
[-----------------83%-----------       ] 1672 of 2000 complete in 2248.2 sec
[-----------------83%-----------       ] 1673 of 2000 complete in 2249.6 sec
[-----------------83%-----------       ] 1674 of 2000 complete in 2250.9 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 2252.3 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 2253.6 sec
[-----------------83%-----------       ] 1677 of 2000 complete in 2255.0 sec
[-----------------83%-----------       ] 1678 of 2000 complete in 2256.4 sec
[-----------------83%-----------       ] 1679 of 2000 complete in 2257.7 sec
[-----------------84%-----------       ] 1680 of 2000 complete in 2259.1 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 2260.5 sec
[-----------------84%-----------       ] 1682 of 2000 complete in 2261.8 sec
[-----------------84%-----------       ] 1683 of 2000 complete in 2263.2 sec
[-----------------84%-----------       ] 1684 of 2000 complete in 2264.6 sec
[-----------------84%------------      ] 1685 of 2000 complete in 2266.0 sec
[-----------------84%------------      ] 1686 of 2000 complete in 2267.4 sec
[-----------------84%------------      ] 1687 of 2000 complete in 2268.7 sec
[-----------------84%------------      ] 1688 of 2000 complete in 2270.1 sec
[-----------------84%------------      ] 1689 of 2000 complete in 2271.4 sec
[-----------------84%------------      ] 1690 of 2000 complete in 2272.8 sec
[-----------------84%------------      ] 1691 of 2000 complete in 2274.2 sec
[-----------------84%------------      ] 1692 of 2000 complete in 2275.5 sec
[-----------------84%------------      ] 1693 of 2000 complete in 2276.9 sec
[-----------------84%------------      ] 1694 of 2000 complete in 2278.2 sec
[-----------------84%------------      ] 1695 of 2000 complete in 2279.6 sec
[-----------------84%------------      ] 1696 of 2000 complete in 2280.9 sec
[-----------------84%------------      ] 1697 of 2000 complete in 2282.3 sec
[-----------------84%------------      ] 1698 of 2000 complete in 2283.6 sec
[-----------------84%------------      ] 1699 of 2000 complete in 2285.0 sec
[-----------------85%------------      ] 1700 of 2000 complete in 2286.4 sec
[-----------------85%------------      ] 1701 of 2000 complete in 2287.8 sec
[-----------------85%------------      ] 1702 of 2000 complete in 2289.2 sec
[-----------------85%------------      ] 1703 of 2000 complete in 2290.6 sec
[-----------------85%------------      ] 1704 of 2000 complete in 2292.0 sec
[-----------------85%------------      ] 1705 of 2000 complete in 2293.4 sec
[-----------------85%------------      ] 1706 of 2000 complete in 2294.8 sec
[-----------------85%------------      ] 1707 of 2000 complete in 2296.2 sec
[-----------------85%------------      ] 1708 of 2000 complete in 2297.6 sec
[-----------------85%------------      ] 1709 of 2000 complete in 2299.0 sec
[-----------------85%------------      ] 1710 of 2000 complete in 2300.3 sec
[-----------------85%------------      ] 1711 of 2000 complete in 2301.7 sec
[-----------------85%------------      ] 1712 of 2000 complete in 2303.1 sec
[-----------------85%------------      ] 1713 of 2000 complete in 2304.6 sec
[-----------------85%------------      ] 1714 of 2000 complete in 2306.0 sec
[-----------------85%------------      ] 1715 of 2000 complete in 2307.4 sec
[-----------------85%------------      ] 1716 of 2000 complete in 2308.7 sec
[-----------------85%------------      ] 1717 of 2000 complete in 2310.1 sec
[-----------------85%------------      ] 1718 of 2000 complete in 2311.5 sec
[-----------------85%------------      ] 1719 of 2000 complete in 2312.9 sec
[-----------------86%------------      ] 1720 of 2000 complete in 2314.3 sec
[-----------------86%------------      ] 1721 of 2000 complete in 2315.6 sec
[-----------------86%------------      ] 1722 of 2000 complete in 2317.0 sec
[-----------------80%----------        ] 1616 of 2000 complete in 2197.5 sec
[-----------------80%----------        ] 1617 of 2000 complete in 2199.0 sec
[-----------------80%----------        ] 1618 of 2000 complete in 2200.4 sec
[-----------------80%----------        ] 1619 of 2000 complete in 2201.7 sec
[-----------------81%----------        ] 1620 of 2000 complete in 2203.0 sec
[-----------------81%----------        ] 1621 of 2000 complete in 2204.4 sec
[-----------------81%----------        ] 1622 of 2000 complete in 2205.9 sec
[-----------------81%----------        ] 1623 of 2000 complete in 2207.2 sec
[-----------------81%----------        ] 1624 of 2000 complete in 2208.6 sec
[-----------------81%----------        ] 1625 of 2000 complete in 2210.0 sec
[-----------------81%----------        ] 1626 of 2000 complete in 2211.4 sec
[-----------------81%----------        ] 1627 of 2000 complete in 2212.7 sec
[-----------------81%----------        ] 1628 of 2000 complete in 2214.1 sec
[-----------------81%----------        ] 1629 of 2000 complete in 2215.4 sec
[-----------------81%----------        ] 1630 of 2000 complete in 2216.8 sec
[-----------------81%----------        ] 1631 of 2000 complete in 2218.1 sec
[-----------------81%-----------       ] 1632 of 2000 complete in 2219.5 sec
[-----------------81%-----------       ] 1633 of 2000 complete in 2220.9 sec
[-----------------81%-----------       ] 1634 of 2000 complete in 2222.2 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 2223.6 sec
[-----------------81%-----------       ] 1636 of 2000 complete in 2224.9 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 2226.3 sec
[-----------------81%-----------       ] 1638 of 2000 complete in 2227.6 sec
[-----------------81%-----------       ] 1639 of 2000 complete in 2229.0 sec
[-----------------82%-----------       ] 1640 of 2000 complete in 2230.4 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 2231.8 sec
[-----------------82%-----------       ] 1642 of 2000 complete in 2233.2 sec
[-----------------82%-----------       ] 1643 of 2000 complete in 2234.6 sec
[-----------------82%-----------       ] 1644 of 2000 complete in 2236.0 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 2237.4 sec
[-----------------82%-----------       ] 1646 of 2000 complete in 2238.7 sec
[-----------------82%-----------       ] 1647 of 2000 complete in 2240.1 sec
[-----------------82%-----------       ] 1648 of 2000 complete in 2241.5 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 2243.0 sec
[-----------------82%-----------       ] 1650 of 2000 complete in 2244.4 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 2245.9 sec
[-----------------82%-----------       ] 1652 of 2000 complete in 2247.4 sec
[-----------------82%-----------       ] 1653 of 2000 complete in 2248.8 sec
[-----------------82%-----------       ] 1654 of 2000 complete in 2250.2 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 2251.6 sec
[-----------------82%-----------       ] 1656 of 2000 complete in 2253.0 sec
[-----------------82%-----------       ] 1657 of 2000 complete in 2254.3 sec
[-----------------82%-----------       ] 1658 of 2000 complete in 2255.7 sec
[-----------------82%-----------       ] 1659 of 2000 complete in 2257.1 sec
[-----------------83%-----------       ] 1660 of 2000 complete in 2258.5 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 2259.9 sec
[-----------------83%-----------       ] 1662 of 2000 complete in 2261.2 sec
[-----------------83%-----------       ] 1663 of 2000 complete in 2262.6 sec
[-----------------83%-----------       ] 1664 of 2000 complete in 2264.1 sec
[-----------------83%-----------       ] 1665 of 2000 complete in 2265.5 sec
[-----------------83%-----------       ] 1666 of 2000 complete in 2266.9 sec
[-----------------83%-----------       ] 1667 of 2000 complete in 2268.3 sec
[-----------------83%-----------       ] 1668 of 2000 complete in 2269.8 sec
[-----------------83%-----------       ] 1669 of 2000 complete in 2271.2 sec
[-----------------83%-----------       ] 1670 of 2000 complete in 2272.6 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 2273.9 sec
[-----------------83%-----------       ] 1672 of 2000 complete in 2275.3 sec
[-----------------83%-----------       ] 1673 of 2000 complete in 2276.7 sec
[-----------------83%-----------       ] 1674 of 2000 complete in 2278.1 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 2279.5 sec
[-----------------83%-----------       ] 1676 of 2000 complete in 2280.9 sec
[-----------------83%-----------       ] 1677 of 2000 complete in 2282.2 sec
[-----------------83%-----------       ] 1678 of 2000 complete in 2283.6 sec
[-----------------83%-----------       ] 1679 of 2000 complete in 2285.0 sec
[-----------------84%-----------       ] 1680 of 2000 complete in 2286.4 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 2287.8 sec
[-----------------84%-----------       ] 1682 of 2000 complete in 2289.1 sec
[-----------------84%-----------       ] 1683 of 2000 complete in 2290.6 sec
[-----------------84%-----------       ] 1684 of 2000 complete in 2291.9 sec
[-----------------84%------------      ] 1685 of 2000 complete in 2293.2 sec
[-----------------84%------------      ] 1686 of 2000 complete in 2294.7 sec
[-----------------84%------------      ] 1687 of 2000 complete in 2296.1 sec
[-----------------84%------------      ] 1688 of 2000 complete in 2297.5 sec
[-----------------84%------------      ] 1689 of 2000 complete in 2298.8 sec
[-----------------84%------------      ] 1690 of 2000 complete in 2300.3 sec
[-----------------84%------------      ] 1691 of 2000 complete in 2301.6 sec
[-----------------84%------------      ] 1692 of 2000 complete in 2302.9 sec
[-----------------84%------------      ] 1693 of 2000 complete in 2304.3 sec
[-----------------84%------------      ] 1694 of 2000 complete in 2305.7 sec
[-----------------84%------------      ] 1695 of 2000 complete in 2307.2 sec
[-----------------84%------------      ] 1696 of 2000 complete in 2308.6 sec
[-----------------84%------------      ] 1697 of 2000 complete in 2309.9 sec
[-----------------84%------------      ] 1698 of 2000 complete in 2311.2 sec
[-----------------84%------------      ] 1699 of 2000 complete in 2312.6 sec
[-----------------85%------------      ] 1700 of 2000 complete in 2314.0 sec
[-----------------85%------------      ] 1701 of 2000 complete in 2315.4 sec
[-----------------85%------------      ] 1702 of 2000 complete in 2316.7 sec
[-----------------85%------------      ] 1703 of 2000 complete in 2318.2 sec
[-----------------85%------------      ] 1704 of 2000 complete in 2319.5 sec
[-----------------85%------------      ] 1705 of 2000 complete in 2321.0 sec
[-----------------85%------------      ] 1706 of 2000 complete in 2322.4 sec
[-----------------85%------------      ] 1707 of 2000 complete in 2323.7 sec
[-----------------85%------------      ] 1708 of 2000 complete in 2325.0 sec
[-----------------85%------------      ] 1709 of 2000 complete in 2326.4 sec
[-----------------85%------------      ] 1710 of 2000 complete in 2327.8 sec
[-----------------85%------------      ] 1711 of 2000 complete in 2329.2 sec
[-----------------85%------------      ] 1712 of 2000 complete in 2330.5 sec
[-----------------85%------------      ] 1713 of 2000 complete in 2331.9 sec
[-----------------85%------------      ] 1714 of 2000 complete in 2333.3 sec
[-----------------85%------------      ] 1715 of 2000 complete in 2334.6 sec
[-----------------85%------------      ] 1716 of 2000 complete in 2336.0 sec
[-----------------85%------------      ] 1717 of 2000 complete in 2337.5 sec
[-----------------85%------------      ] 1718 of 2000 complete in 2338.9 sec
[-----------------85%------------      ] 1719 of 2000 complete in 2340.3 sec
[-----------------86%------------      ] 1720 of 2000 complete in 2341.6 sec
[-----------------86%------------      ] 1721 of 2000 complete in 2343.0 sec

[-----------------86%------------      ] 1723 of 2000 complete in 2308.4 sec
[-----------------86%------------      ] 1724 of 2000 complete in 2309.7 sec
[-----------------86%------------      ] 1725 of 2000 complete in 2311.1 sec
[-----------------86%------------      ] 1726 of 2000 complete in 2312.5 sec
[-----------------86%------------      ] 1727 of 2000 complete in 2313.9 sec
[-----------------86%------------      ] 1728 of 2000 complete in 2315.2 sec
[-----------------86%------------      ] 1729 of 2000 complete in 2316.6 sec
[-----------------86%------------      ] 1730 of 2000 complete in 2318.0 sec
[-----------------86%------------      ] 1731 of 2000 complete in 2319.3 sec
[-----------------86%------------      ] 1732 of 2000 complete in 2320.6 sec
[-----------------86%------------      ] 1733 of 2000 complete in 2321.9 sec
[-----------------86%------------      ] 1734 of 2000 complete in 2323.3 sec
[-----------------86%------------      ] 1735 of 2000 complete in 2324.7 sec
[-----------------86%------------      ] 1736 of 2000 complete in 2326.1 sec
[-----------------86%-------------     ] 1737 of 2000 complete in 2327.6 sec
[-----------------86%-------------     ] 1738 of 2000 complete in 2329.0 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 2330.5 sec
[-----------------87%-------------     ] 1740 of 2000 complete in 2331.9 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 2333.3 sec
[-----------------87%-------------     ] 1742 of 2000 complete in 2334.6 sec
[-----------------87%-------------     ] 1743 of 2000 complete in 2336.0 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 2337.3 sec
[-----------------87%-------------     ] 1745 of 2000 complete in 2338.7 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 2340.1 sec
[-----------------87%-------------     ] 1747 of 2000 complete in 2341.5 sec
[-----------------87%-------------     ] 1748 of 2000 complete in 2342.8 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 2344.2 sec
[-----------------87%-------------     ] 1750 of 2000 complete in 2345.5 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 2347.0 sec
[-----------------87%-------------     ] 1752 of 2000 complete in 2348.3 sec
[-----------------87%-------------     ] 1753 of 2000 complete in 2349.7 sec
[-----------------87%-------------     ] 1754 of 2000 complete in 2351.2 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 2352.6 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 2353.9 sec
[-----------------87%-------------     ] 1757 of 2000 complete in 2355.3 sec
[-----------------87%-------------     ] 1758 of 2000 complete in 2356.8 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 2358.2 sec
[-----------------88%-------------     ] 1760 of 2000 complete in 2359.6 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 2361.0 sec
[-----------------88%-------------     ] 1762 of 2000 complete in 2362.3 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 2363.7 sec
[-----------------88%-------------     ] 1764 of 2000 complete in 2365.1 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 2366.5 sec
[-----------------88%-------------     ] 1766 of 2000 complete in 2367.9 sec
[-----------------88%-------------     ] 1767 of 2000 complete in 2369.2 sec
[-----------------88%-------------     ] 1768 of 2000 complete in 2370.6 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 2372.0 sec
[-----------------88%-------------     ] 1770 of 2000 complete in 2373.4 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 2374.8 sec
[-----------------88%-------------     ] 1772 of 2000 complete in 2376.2 sec
[-----------------88%-------------     ] 1773 of 2000 complete in 2377.7 sec
[-----------------88%-------------     ] 1774 of 2000 complete in 2379.0 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 2380.4 sec
[-----------------88%-------------     ] 1776 of 2000 complete in 2381.8 sec
[-----------------88%-------------     ] 1777 of 2000 complete in 2383.2 sec
[-----------------88%-------------     ] 1778 of 2000 complete in 2384.5 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 2385.9 sec
[-----------------89%-------------     ] 1780 of 2000 complete in 2387.2 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 2388.6 sec
[-----------------89%-------------     ] 1782 of 2000 complete in 2390.0 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 2391.4 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 2392.8 sec
[-----------------89%-------------     ] 1785 of 2000 complete in 2394.1 sec
[-----------------89%-------------     ] 1786 of 2000 complete in 2395.6 sec
[-----------------89%-------------     ] 1787 of 2000 complete in 2396.9 sec
[-----------------89%-------------     ] 1788 of 2000 complete in 2398.3 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 2399.7 sec
[-----------------89%--------------    ] 1790 of 2000 complete in 2401.1 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 2402.5 sec
[-----------------89%--------------    ] 1792 of 2000 complete in 2403.9 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 2405.3 sec
[-----------------89%--------------    ] 1794 of 2000 complete in 2406.7 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 2408.0 sec
[-----------------89%--------------    ] 1796 of 2000 complete in 2409.4 sec
[-----------------89%--------------    ] 1797 of 2000 complete in 2410.8 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 2412.2 sec
[-----------------89%--------------    ] 1799 of 2000 complete in 2413.6 sec
[-----------------90%--------------    ] 1800 of 2000 complete in 2415.0 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 2416.4 sec
[-----------------90%--------------    ] 1802 of 2000 complete in 2417.8 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 2419.1 sec
[-----------------90%--------------    ] 1804 of 2000 complete in 2420.7 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 2422.2 sec
[-----------------90%--------------    ] 1806 of 2000 complete in 2423.5 sec
[-----------------90%--------------    ] 1807 of 2000 complete in 2425.0 sec
[-----------------90%--------------    ] 1808 of 2000 complete in 2426.4 sec
[-----------------90%--------------    ] 1809 of 2000 complete in 2427.8 sec
[-----------------90%--------------    ] 1810 of 2000 complete in 2429.1 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 2430.5 sec
[-----------------90%--------------    ] 1812 of 2000 complete in 2431.9 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 2433.3 sec
[-----------------90%--------------    ] 1814 of 2000 complete in 2434.7 sec
[-----------------90%--------------    ] 1815 of 2000 complete in 2436.1 sec
[-----------------90%--------------    ] 1816 of 2000 complete in 2437.5 sec
[-----------------90%--------------    ] 1817 of 2000 complete in 2438.8 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 2440.2 sec
[-----------------90%--------------    ] 1819 of 2000 complete in 2441.6 sec
[-----------------91%--------------    ] 1820 of 2000 complete in 2443.0 sec
[-----------------91%--------------    ] 1821 of 2000 complete in 2444.4 sec
[-----------------91%--------------    ] 1822 of 2000 complete in 2445.8 sec
[-----------------91%--------------    ] 1823 of 2000 complete in 2447.2 sec
[-----------------91%--------------    ] 1824 of 2000 complete in 2448.6 sec
[-----------------91%--------------    ] 1825 of 2000 complete in 2450.0 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 2451.4 sec
[-----------------91%--------------    ] 1827 of 2000 complete in 2452.7 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 2454.1 sec
[-----------------86%------------      ] 1723 of 2000 complete in 2312.7 sec
[-----------------86%------------      ] 1724 of 2000 complete in 2314.1 sec
[-----------------86%------------      ] 1725 of 2000 complete in 2315.4 sec
[-----------------86%------------      ] 1726 of 2000 complete in 2316.9 sec
[-----------------86%------------      ] 1727 of 2000 complete in 2318.3 sec
[-----------------86%------------      ] 1728 of 2000 complete in 2319.7 sec
[-----------------86%------------      ] 1729 of 2000 complete in 2321.1 sec
[-----------------86%------------      ] 1730 of 2000 complete in 2322.4 sec
[-----------------86%------------      ] 1731 of 2000 complete in 2323.9 sec
[-----------------86%------------      ] 1732 of 2000 complete in 2325.3 sec
[-----------------86%------------      ] 1733 of 2000 complete in 2326.8 sec
[-----------------86%------------      ] 1734 of 2000 complete in 2328.1 sec
[-----------------86%------------      ] 1735 of 2000 complete in 2329.5 sec
[-----------------86%------------      ] 1736 of 2000 complete in 2330.9 sec
[-----------------86%-------------     ] 1737 of 2000 complete in 2332.4 sec
[-----------------86%-------------     ] 1738 of 2000 complete in 2333.8 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 2335.1 sec
[-----------------87%-------------     ] 1740 of 2000 complete in 2336.5 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 2337.9 sec
[-----------------87%-------------     ] 1742 of 2000 complete in 2339.2 sec
[-----------------87%-------------     ] 1743 of 2000 complete in 2340.6 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 2341.9 sec
[-----------------87%-------------     ] 1745 of 2000 complete in 2343.3 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 2344.7 sec
[-----------------87%-------------     ] 1747 of 2000 complete in 2346.1 sec
[-----------------87%-------------     ] 1748 of 2000 complete in 2347.5 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 2348.9 sec
[-----------------87%-------------     ] 1750 of 2000 complete in 2350.3 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 2351.6 sec
[-----------------87%-------------     ] 1752 of 2000 complete in 2353.0 sec
[-----------------87%-------------     ] 1753 of 2000 complete in 2354.4 sec
[-----------------87%-------------     ] 1754 of 2000 complete in 2355.9 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 2357.2 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 2358.6 sec
[-----------------87%-------------     ] 1757 of 2000 complete in 2360.0 sec
[-----------------87%-------------     ] 1758 of 2000 complete in 2361.4 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 2362.7 sec
[-----------------88%-------------     ] 1760 of 2000 complete in 2364.1 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 2365.5 sec
[-----------------88%-------------     ] 1762 of 2000 complete in 2366.9 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 2368.3 sec
[-----------------88%-------------     ] 1764 of 2000 complete in 2369.6 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 2371.0 sec
[-----------------88%-------------     ] 1766 of 2000 complete in 2372.4 sec
[-----------------88%-------------     ] 1767 of 2000 complete in 2373.7 sec
[-----------------88%-------------     ] 1768 of 2000 complete in 2375.1 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 2376.5 sec
[-----------------88%-------------     ] 1770 of 2000 complete in 2377.9 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 2379.2 sec
[-----------------88%-------------     ] 1772 of 2000 complete in 2380.6 sec
[-----------------88%-------------     ] 1773 of 2000 complete in 2382.0 sec
[-----------------88%-------------     ] 1774 of 2000 complete in 2383.3 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 2384.7 sec
[-----------------88%-------------     ] 1776 of 2000 complete in 2386.1 sec
[-----------------88%-------------     ] 1777 of 2000 complete in 2387.6 sec
[-----------------88%-------------     ] 1778 of 2000 complete in 2389.0 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 2390.3 sec
[-----------------89%-------------     ] 1780 of 2000 complete in 2391.6 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 2393.1 sec
[-----------------89%-------------     ] 1782 of 2000 complete in 2394.5 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 2395.9 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 2397.3 sec
[-----------------89%-------------     ] 1785 of 2000 complete in 2398.7 sec
[-----------------89%-------------     ] 1786 of 2000 complete in 2400.1 sec
[-----------------89%-------------     ] 1787 of 2000 complete in 2401.5 sec
[-----------------89%-------------     ] 1788 of 2000 complete in 2402.9 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 2404.2 sec
[-----------------89%--------------    ] 1790 of 2000 complete in 2405.6 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 2407.0 sec
[-----------------89%--------------    ] 1792 of 2000 complete in 2408.4 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 2409.7 sec
[-----------------89%--------------    ] 1794 of 2000 complete in 2411.1 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 2412.5 sec
[-----------------89%--------------    ] 1796 of 2000 complete in 2413.9 sec
[-----------------89%--------------    ] 1797 of 2000 complete in 2415.3 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 2416.7 sec
[-----------------89%--------------    ] 1799 of 2000 complete in 2418.3 sec
[-----------------90%--------------    ] 1800 of 2000 complete in 2419.8 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 2421.3 sec
[-----------------90%--------------    ] 1802 of 2000 complete in 2422.7 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 2424.1 sec
[-----------------90%--------------    ] 1804 of 2000 complete in 2425.7 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 2427.0 sec
[-----------------90%--------------    ] 1806 of 2000 complete in 2428.4 sec
[-----------------90%--------------    ] 1807 of 2000 complete in 2429.7 sec
[-----------------90%--------------    ] 1808 of 2000 complete in 2431.1 sec
[-----------------90%--------------    ] 1809 of 2000 complete in 2432.5 sec
[-----------------90%--------------    ] 1810 of 2000 complete in 2433.8 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 2435.2 sec
[-----------------90%--------------    ] 1812 of 2000 complete in 2436.6 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 2438.0 sec
[-----------------90%--------------    ] 1814 of 2000 complete in 2439.5 sec
[-----------------90%--------------    ] 1815 of 2000 complete in 2440.9 sec
[-----------------90%--------------    ] 1816 of 2000 complete in 2442.4 sec
[-----------------90%--------------    ] 1817 of 2000 complete in 2443.9 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 2445.3 sec
[-----------------90%--------------    ] 1819 of 2000 complete in 2446.7 sec
[-----------------91%--------------    ] 1820 of 2000 complete in 2448.1 sec
[-----------------91%--------------    ] 1821 of 2000 complete in 2449.4 sec
[-----------------91%--------------    ] 1822 of 2000 complete in 2450.8 sec
[-----------------91%--------------    ] 1823 of 2000 complete in 2452.3 sec
[-----------------91%--------------    ] 1824 of 2000 complete in 2453.7 sec
[-----------------91%--------------    ] 1825 of 2000 complete in 2455.1 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 2456.4 sec
[-----------------91%--------------    ] 1827 of 2000 complete in 2457.9 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 2459.3 sec

[-----------------86%------------      ] 1723 of 2000 complete in 2318.3 sec
[-----------------86%------------      ] 1724 of 2000 complete in 2319.7 sec
[-----------------86%------------      ] 1725 of 2000 complete in 2321.1 sec
[-----------------86%------------      ] 1726 of 2000 complete in 2322.5 sec
[-----------------86%------------      ] 1727 of 2000 complete in 2323.8 sec
[-----------------86%------------      ] 1728 of 2000 complete in 2325.2 sec
[-----------------86%------------      ] 1729 of 2000 complete in 2326.6 sec
[-----------------86%------------      ] 1730 of 2000 complete in 2327.9 sec
[-----------------86%------------      ] 1731 of 2000 complete in 2329.3 sec
[-----------------86%------------      ] 1732 of 2000 complete in 2330.7 sec
[-----------------86%------------      ] 1733 of 2000 complete in 2332.0 sec
[-----------------86%------------      ] 1734 of 2000 complete in 2333.4 sec
[-----------------86%------------      ] 1735 of 2000 complete in 2334.7 sec
[-----------------86%------------      ] 1736 of 2000 complete in 2336.1 sec
[-----------------86%-------------     ] 1737 of 2000 complete in 2337.5 sec
[-----------------86%-------------     ] 1738 of 2000 complete in 2338.9 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 2340.2 sec
[-----------------87%-------------     ] 1740 of 2000 complete in 2341.6 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 2342.9 sec
[-----------------87%-------------     ] 1742 of 2000 complete in 2344.3 sec
[-----------------87%-------------     ] 1743 of 2000 complete in 2345.7 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 2347.1 sec
[-----------------87%-------------     ] 1745 of 2000 complete in 2348.4 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 2349.8 sec
[-----------------87%-------------     ] 1747 of 2000 complete in 2351.1 sec
[-----------------87%-------------     ] 1748 of 2000 complete in 2352.5 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 2354.0 sec
[-----------------87%-------------     ] 1750 of 2000 complete in 2355.4 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 2356.8 sec
[-----------------87%-------------     ] 1752 of 2000 complete in 2358.2 sec
[-----------------87%-------------     ] 1753 of 2000 complete in 2359.5 sec
[-----------------87%-------------     ] 1754 of 2000 complete in 2360.9 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 2362.3 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 2363.6 sec
[-----------------87%-------------     ] 1757 of 2000 complete in 2364.9 sec
[-----------------87%-------------     ] 1758 of 2000 complete in 2366.3 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 2367.8 sec
[-----------------88%-------------     ] 1760 of 2000 complete in 2369.2 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 2370.6 sec
[-----------------88%-------------     ] 1762 of 2000 complete in 2371.9 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 2373.3 sec
[-----------------88%-------------     ] 1764 of 2000 complete in 2374.7 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 2376.0 sec
[-----------------88%-------------     ] 1766 of 2000 complete in 2377.4 sec
[-----------------88%-------------     ] 1767 of 2000 complete in 2378.7 sec
[-----------------88%-------------     ] 1768 of 2000 complete in 2380.1 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 2381.5 sec
[-----------------88%-------------     ] 1770 of 2000 complete in 2382.9 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 2384.3 sec
[-----------------88%-------------     ] 1772 of 2000 complete in 2385.7 sec
[-----------------88%-------------     ] 1773 of 2000 complete in 2387.0 sec
[-----------------88%-------------     ] 1774 of 2000 complete in 2388.4 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 2389.7 sec
[-----------------88%-------------     ] 1776 of 2000 complete in 2391.2 sec
[-----------------88%-------------     ] 1777 of 2000 complete in 2392.6 sec
[-----------------88%-------------     ] 1778 of 2000 complete in 2394.1 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 2395.4 sec
[-----------------89%-------------     ] 1780 of 2000 complete in 2396.9 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 2398.3 sec
[-----------------89%-------------     ] 1782 of 2000 complete in 2399.7 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 2401.0 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 2402.4 sec
[-----------------89%-------------     ] 1785 of 2000 complete in 2403.8 sec
[-----------------89%-------------     ] 1786 of 2000 complete in 2405.2 sec
[-----------------89%-------------     ] 1787 of 2000 complete in 2406.6 sec
[-----------------89%-------------     ] 1788 of 2000 complete in 2408.1 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 2409.4 sec
[-----------------89%--------------    ] 1790 of 2000 complete in 2410.9 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 2412.3 sec
[-----------------89%--------------    ] 1792 of 2000 complete in 2413.7 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 2415.2 sec
[-----------------89%--------------    ] 1794 of 2000 complete in 2416.5 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 2417.9 sec
[-----------------89%--------------    ] 1796 of 2000 complete in 2419.2 sec
[-----------------89%--------------    ] 1797 of 2000 complete in 2420.7 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 2422.1 sec
[-----------------89%--------------    ] 1799 of 2000 complete in 2423.5 sec
[-----------------90%--------------    ] 1800 of 2000 complete in 2424.9 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 2426.4 sec
[-----------------90%--------------    ] 1802 of 2000 complete in 2427.7 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 2429.2 sec
[-----------------90%--------------    ] 1804 of 2000 complete in 2430.6 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 2432.0 sec
[-----------------90%--------------    ] 1806 of 2000 complete in 2433.4 sec
[-----------------90%--------------    ] 1807 of 2000 complete in 2434.8 sec
[-----------------90%--------------    ] 1808 of 2000 complete in 2436.2 sec
[-----------------90%--------------    ] 1809 of 2000 complete in 2437.6 sec
[-----------------90%--------------    ] 1810 of 2000 complete in 2439.0 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 2440.4 sec
[-----------------90%--------------    ] 1812 of 2000 complete in 2441.9 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 2443.3 sec
[-----------------90%--------------    ] 1814 of 2000 complete in 2444.8 sec
[-----------------90%--------------    ] 1815 of 2000 complete in 2446.2 sec
[-----------------90%--------------    ] 1816 of 2000 complete in 2447.6 sec
[-----------------90%--------------    ] 1817 of 2000 complete in 2449.0 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 2450.3 sec
[-----------------90%--------------    ] 1819 of 2000 complete in 2451.7 sec
[-----------------91%--------------    ] 1820 of 2000 complete in 2453.2 sec
[-----------------91%--------------    ] 1821 of 2000 complete in 2454.6 sec
[-----------------91%--------------    ] 1822 of 2000 complete in 2456.0 sec
[-----------------91%--------------    ] 1823 of 2000 complete in 2457.4 sec
[-----------------91%--------------    ] 1824 of 2000 complete in 2458.9 sec
[-----------------91%--------------    ] 1825 of 2000 complete in 2460.3 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 2461.7 sec
[-----------------91%--------------    ] 1827 of 2000 complete in 2463.2 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 2464.6 sec
[-----------------86%------------      ] 1722 of 2000 complete in 2344.4 sec
[-----------------86%------------      ] 1723 of 2000 complete in 2345.7 sec
[-----------------86%------------      ] 1724 of 2000 complete in 2347.0 sec
[-----------------86%------------      ] 1725 of 2000 complete in 2348.4 sec
[-----------------86%------------      ] 1726 of 2000 complete in 2349.8 sec
[-----------------86%------------      ] 1727 of 2000 complete in 2351.1 sec
[-----------------86%------------      ] 1728 of 2000 complete in 2352.5 sec
[-----------------86%------------      ] 1729 of 2000 complete in 2353.8 sec
[-----------------86%------------      ] 1730 of 2000 complete in 2355.3 sec
[-----------------86%------------      ] 1731 of 2000 complete in 2356.6 sec
[-----------------86%------------      ] 1732 of 2000 complete in 2358.0 sec
[-----------------86%------------      ] 1733 of 2000 complete in 2359.3 sec
[-----------------86%------------      ] 1734 of 2000 complete in 2360.8 sec
[-----------------86%------------      ] 1735 of 2000 complete in 2362.1 sec
[-----------------86%------------      ] 1736 of 2000 complete in 2363.5 sec
[-----------------86%-------------     ] 1737 of 2000 complete in 2364.9 sec
[-----------------86%-------------     ] 1738 of 2000 complete in 2366.3 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 2367.6 sec
[-----------------87%-------------     ] 1740 of 2000 complete in 2369.0 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 2370.4 sec
[-----------------87%-------------     ] 1742 of 2000 complete in 2371.8 sec
[-----------------87%-------------     ] 1743 of 2000 complete in 2373.3 sec
[-----------------87%-------------     ] 1744 of 2000 complete in 2374.6 sec
[-----------------87%-------------     ] 1745 of 2000 complete in 2375.9 sec
[-----------------87%-------------     ] 1746 of 2000 complete in 2377.2 sec
[-----------------87%-------------     ] 1747 of 2000 complete in 2378.7 sec
[-----------------87%-------------     ] 1748 of 2000 complete in 2380.0 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 2381.4 sec
[-----------------87%-------------     ] 1750 of 2000 complete in 2382.8 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 2384.1 sec
[-----------------87%-------------     ] 1752 of 2000 complete in 2385.5 sec
[-----------------87%-------------     ] 1753 of 2000 complete in 2387.0 sec
[-----------------87%-------------     ] 1754 of 2000 complete in 2388.4 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 2389.8 sec
[-----------------87%-------------     ] 1756 of 2000 complete in 2391.2 sec
[-----------------87%-------------     ] 1757 of 2000 complete in 2392.6 sec
[-----------------87%-------------     ] 1758 of 2000 complete in 2394.1 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 2395.5 sec
[-----------------88%-------------     ] 1760 of 2000 complete in 2396.9 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 2398.3 sec
[-----------------88%-------------     ] 1762 of 2000 complete in 2399.7 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 2401.2 sec
[-----------------88%-------------     ] 1764 of 2000 complete in 2402.5 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 2403.9 sec
[-----------------88%-------------     ] 1766 of 2000 complete in 2405.3 sec
[-----------------88%-------------     ] 1767 of 2000 complete in 2406.8 sec
[-----------------88%-------------     ] 1768 of 2000 complete in 2408.2 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 2409.7 sec
[-----------------88%-------------     ] 1770 of 2000 complete in 2411.1 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 2412.6 sec
[-----------------88%-------------     ] 1772 of 2000 complete in 2414.0 sec
[-----------------88%-------------     ] 1773 of 2000 complete in 2415.4 sec
[-----------------88%-------------     ] 1774 of 2000 complete in 2416.8 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 2418.3 sec
[-----------------88%-------------     ] 1776 of 2000 complete in 2419.8 sec
[-----------------88%-------------     ] 1777 of 2000 complete in 2421.3 sec
[-----------------88%-------------     ] 1778 of 2000 complete in 2422.7 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 2424.1 sec
[-----------------89%-------------     ] 1780 of 2000 complete in 2425.6 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 2427.0 sec
[-----------------89%-------------     ] 1782 of 2000 complete in 2428.5 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 2429.9 sec
[-----------------89%-------------     ] 1784 of 2000 complete in 2431.3 sec
[-----------------89%-------------     ] 1785 of 2000 complete in 2432.6 sec
[-----------------89%-------------     ] 1786 of 2000 complete in 2434.0 sec
[-----------------89%-------------     ] 1787 of 2000 complete in 2435.4 sec
[-----------------89%-------------     ] 1788 of 2000 complete in 2436.9 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 2438.3 sec
[-----------------89%--------------    ] 1790 of 2000 complete in 2439.8 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 2441.2 sec
[-----------------89%--------------    ] 1792 of 2000 complete in 2442.6 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 2444.0 sec
[-----------------89%--------------    ] 1794 of 2000 complete in 2445.4 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 2446.8 sec
[-----------------89%--------------    ] 1796 of 2000 complete in 2448.3 sec
[-----------------89%--------------    ] 1797 of 2000 complete in 2449.6 sec
[-----------------89%--------------    ] 1798 of 2000 complete in 2451.0 sec
[-----------------89%--------------    ] 1799 of 2000 complete in 2452.4 sec
[-----------------90%--------------    ] 1800 of 2000 complete in 2453.8 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 2455.3 sec
[-----------------90%--------------    ] 1802 of 2000 complete in 2456.7 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 2458.1 sec
[-----------------90%--------------    ] 1804 of 2000 complete in 2459.5 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 2460.9 sec
[-----------------90%--------------    ] 1806 of 2000 complete in 2462.3 sec
[-----------------90%--------------    ] 1807 of 2000 complete in 2463.7 sec
[-----------------90%--------------    ] 1808 of 2000 complete in 2465.0 sec
[-----------------90%--------------    ] 1809 of 2000 complete in 2466.5 sec
[-----------------90%--------------    ] 1810 of 2000 complete in 2467.9 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 2469.3 sec
[-----------------90%--------------    ] 1812 of 2000 complete in 2470.7 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 2472.2 sec
[-----------------90%--------------    ] 1814 of 2000 complete in 2473.7 sec
[-----------------90%--------------    ] 1815 of 2000 complete in 2475.2 sec
[-----------------90%--------------    ] 1816 of 2000 complete in 2476.6 sec
[-----------------90%--------------    ] 1817 of 2000 complete in 2478.1 sec
[-----------------90%--------------    ] 1818 of 2000 complete in 2479.6 sec
[-----------------90%--------------    ] 1819 of 2000 complete in 2481.0 sec
[-----------------91%--------------    ] 1820 of 2000 complete in 2482.4 sec
[-----------------91%--------------    ] 1821 of 2000 complete in 2483.8 sec
[-----------------91%--------------    ] 1822 of 2000 complete in 2485.2 sec
[-----------------91%--------------    ] 1823 of 2000 complete in 2486.6 sec
[-----------------91%--------------    ] 1824 of 2000 complete in 2488.0 sec
[-----------------91%--------------    ] 1825 of 2000 complete in 2489.4 sec
[-----------------91%--------------    ] 1826 of 2000 complete in 2490.8 sec
[-----------------91%--------------    ] 1827 of 2000 complete in 2492.2 sec

[-----------------91%--------------    ] 1829 of 2000 complete in 2455.5 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 2456.9 sec
[-----------------91%--------------    ] 1831 of 2000 complete in 2458.3 sec
[-----------------91%--------------    ] 1832 of 2000 complete in 2459.7 sec
[-----------------91%--------------    ] 1833 of 2000 complete in 2461.1 sec
[-----------------91%--------------    ] 1834 of 2000 complete in 2462.5 sec
[-----------------91%--------------    ] 1835 of 2000 complete in 2463.8 sec
[-----------------91%--------------    ] 1836 of 2000 complete in 2465.2 sec
[-----------------91%--------------    ] 1837 of 2000 complete in 2466.6 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 2468.0 sec
[-----------------91%--------------    ] 1839 of 2000 complete in 2469.5 sec
[-----------------92%--------------    ] 1840 of 2000 complete in 2470.8 sec
[-----------------92%--------------    ] 1841 of 2000 complete in 2472.2 sec
[-----------------92%--------------    ] 1842 of 2000 complete in 2473.6 sec
[-----------------92%---------------   ] 1843 of 2000 complete in 2475.0 sec
[-----------------92%---------------   ] 1844 of 2000 complete in 2476.4 sec
[-----------------92%---------------   ] 1845 of 2000 complete in 2477.8 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 2479.1 sec
[-----------------92%---------------   ] 1847 of 2000 complete in 2480.5 sec
[-----------------92%---------------   ] 1848 of 2000 complete in 2481.9 sec
[-----------------92%---------------   ] 1849 of 2000 complete in 2483.3 sec
[-----------------92%---------------   ] 1850 of 2000 complete in 2484.7 sec
[-----------------92%---------------   ] 1851 of 2000 complete in 2486.1 sec
[-----------------92%---------------   ] 1852 of 2000 complete in 2487.5 sec
[-----------------92%---------------   ] 1853 of 2000 complete in 2488.9 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 2490.3 sec
[-----------------92%---------------   ] 1855 of 2000 complete in 2491.6 sec
[-----------------92%---------------   ] 1856 of 2000 complete in 2493.1 sec
[-----------------92%---------------   ] 1857 of 2000 complete in 2494.4 sec
[-----------------92%---------------   ] 1858 of 2000 complete in 2495.7 sec
[-----------------92%---------------   ] 1859 of 2000 complete in 2497.0 sec
[-----------------93%---------------   ] 1860 of 2000 complete in 2498.4 sec
[-----------------93%---------------   ] 1861 of 2000 complete in 2499.8 sec
[-----------------93%---------------   ] 1862 of 2000 complete in 2501.3 sec
[-----------------93%---------------   ] 1863 of 2000 complete in 2502.7 sec
[-----------------93%---------------   ] 1864 of 2000 complete in 2504.1 sec
[-----------------93%---------------   ] 1865 of 2000 complete in 2505.5 sec
[-----------------93%---------------   ] 1866 of 2000 complete in 2507.0 sec
[-----------------93%---------------   ] 1867 of 2000 complete in 2508.4 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 2509.8 sec
[-----------------93%---------------   ] 1869 of 2000 complete in 2511.1 sec
[-----------------93%---------------   ] 1870 of 2000 complete in 2512.5 sec
[-----------------93%---------------   ] 1871 of 2000 complete in 2513.9 sec
[-----------------93%---------------   ] 1872 of 2000 complete in 2515.4 sec
[-----------------93%---------------   ] 1873 of 2000 complete in 2516.8 sec
[-----------------93%---------------   ] 1874 of 2000 complete in 2518.1 sec
[-----------------93%---------------   ] 1875 of 2000 complete in 2519.5 sec
[-----------------93%---------------   ] 1876 of 2000 complete in 2521.0 sec
[-----------------93%---------------   ] 1877 of 2000 complete in 2522.4 sec
[-----------------93%---------------   ] 1878 of 2000 complete in 2523.7 sec
[-----------------93%---------------   ] 1879 of 2000 complete in 2525.2 sec
[-----------------94%---------------   ] 1880 of 2000 complete in 2526.6 sec
[-----------------94%---------------   ] 1881 of 2000 complete in 2527.9 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 2529.3 sec
[-----------------94%---------------   ] 1883 of 2000 complete in 2530.6 sec
[-----------------94%---------------   ] 1884 of 2000 complete in 2532.0 sec
[-----------------94%---------------   ] 1885 of 2000 complete in 2533.4 sec
[-----------------94%---------------   ] 1886 of 2000 complete in 2534.8 sec
[-----------------94%---------------   ] 1887 of 2000 complete in 2536.2 sec
[-----------------94%---------------   ] 1888 of 2000 complete in 2537.6 sec
[-----------------94%---------------   ] 1889 of 2000 complete in 2538.9 sec
[-----------------94%---------------   ] 1890 of 2000 complete in 2540.3 sec
[-----------------94%---------------   ] 1891 of 2000 complete in 2541.7 sec
[-----------------94%---------------   ] 1892 of 2000 complete in 2543.1 sec
[-----------------94%---------------   ] 1893 of 2000 complete in 2544.4 sec
[-----------------94%---------------   ] 1894 of 2000 complete in 2545.8 sec
[-----------------94%----------------  ] 1895 of 2000 complete in 2547.1 sec
[-----------------94%----------------  ] 1896 of 2000 complete in 2548.5 sec
[-----------------94%----------------  ] 1897 of 2000 complete in 2549.9 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 2551.3 sec
[-----------------94%----------------  ] 1899 of 2000 complete in 2552.7 sec
[-----------------95%----------------  ] 1900 of 2000 complete in 2554.0 sec
[-----------------95%----------------  ] 1901 of 2000 complete in 2555.4 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 2556.6 sec
[-----------------95%----------------  ] 1903 of 2000 complete in 2558.1 sec
[-----------------95%----------------  ] 1904 of 2000 complete in 2559.5 sec
[-----------------95%----------------  ] 1905 of 2000 complete in 2560.9 sec
[-----------------95%----------------  ] 1906 of 2000 complete in 2562.2 sec
[-----------------95%----------------  ] 1907 of 2000 complete in 2563.7 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 2565.0 sec
[-----------------95%----------------  ] 1909 of 2000 complete in 2566.4 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 2567.8 sec
[-----------------95%----------------  ] 1911 of 2000 complete in 2569.2 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 2570.5 sec
[-----------------95%----------------  ] 1913 of 2000 complete in 2571.9 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 2573.2 sec
[-----------------95%----------------  ] 1915 of 2000 complete in 2574.5 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 2575.9 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 2577.3 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 2578.5 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 2579.8 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 2581.1 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 2582.5 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 2583.8 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 2585.2 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 2586.6 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 2587.9 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 2589.2 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 2590.5 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 2591.8 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 2593.1 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 2594.4 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 2595.7 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 2597.0 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 2598.3 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 2599.6 sec
[-----------------91%--------------    ] 1829 of 2000 complete in 2460.7 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 2462.1 sec
[-----------------91%--------------    ] 1831 of 2000 complete in 2463.6 sec
[-----------------91%--------------    ] 1832 of 2000 complete in 2464.9 sec
[-----------------91%--------------    ] 1833 of 2000 complete in 2466.4 sec
[-----------------91%--------------    ] 1834 of 2000 complete in 2467.8 sec
[-----------------91%--------------    ] 1835 of 2000 complete in 2469.1 sec
[-----------------91%--------------    ] 1836 of 2000 complete in 2470.6 sec
[-----------------91%--------------    ] 1837 of 2000 complete in 2472.0 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 2473.4 sec
[-----------------91%--------------    ] 1839 of 2000 complete in 2474.8 sec
[-----------------92%--------------    ] 1840 of 2000 complete in 2476.1 sec
[-----------------92%--------------    ] 1841 of 2000 complete in 2477.5 sec
[-----------------92%--------------    ] 1842 of 2000 complete in 2478.9 sec
[-----------------92%---------------   ] 1843 of 2000 complete in 2480.3 sec
[-----------------92%---------------   ] 1844 of 2000 complete in 2481.7 sec
[-----------------92%---------------   ] 1845 of 2000 complete in 2483.1 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 2484.5 sec
[-----------------92%---------------   ] 1847 of 2000 complete in 2486.0 sec
[-----------------92%---------------   ] 1848 of 2000 complete in 2487.4 sec
[-----------------92%---------------   ] 1849 of 2000 complete in 2488.9 sec
[-----------------92%---------------   ] 1850 of 2000 complete in 2490.3 sec
[-----------------92%---------------   ] 1851 of 2000 complete in 2491.7 sec
[-----------------92%---------------   ] 1852 of 2000 complete in 2493.1 sec
[-----------------92%---------------   ] 1853 of 2000 complete in 2494.5 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 2495.8 sec
[-----------------92%---------------   ] 1855 of 2000 complete in 2497.2 sec
[-----------------92%---------------   ] 1856 of 2000 complete in 2498.6 sec
[-----------------92%---------------   ] 1857 of 2000 complete in 2500.1 sec
[-----------------92%---------------   ] 1858 of 2000 complete in 2501.5 sec
[-----------------92%---------------   ] 1859 of 2000 complete in 2502.8 sec
[-----------------93%---------------   ] 1860 of 2000 complete in 2504.2 sec
[-----------------93%---------------   ] 1861 of 2000 complete in 2505.7 sec
[-----------------93%---------------   ] 1862 of 2000 complete in 2507.1 sec
[-----------------93%---------------   ] 1863 of 2000 complete in 2508.5 sec
[-----------------93%---------------   ] 1864 of 2000 complete in 2509.8 sec
[-----------------93%---------------   ] 1865 of 2000 complete in 2511.3 sec
[-----------------93%---------------   ] 1866 of 2000 complete in 2512.8 sec
[-----------------93%---------------   ] 1867 of 2000 complete in 2514.2 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 2515.6 sec
[-----------------93%---------------   ] 1869 of 2000 complete in 2517.1 sec
[-----------------93%---------------   ] 1870 of 2000 complete in 2518.5 sec
[-----------------93%---------------   ] 1871 of 2000 complete in 2519.9 sec
[-----------------93%---------------   ] 1872 of 2000 complete in 2521.3 sec
[-----------------93%---------------   ] 1873 of 2000 complete in 2522.6 sec
[-----------------93%---------------   ] 1874 of 2000 complete in 2524.0 sec
[-----------------93%---------------   ] 1875 of 2000 complete in 2525.4 sec
[-----------------93%---------------   ] 1876 of 2000 complete in 2526.8 sec
[-----------------93%---------------   ] 1877 of 2000 complete in 2528.2 sec
[-----------------93%---------------   ] 1878 of 2000 complete in 2529.6 sec
[-----------------93%---------------   ] 1879 of 2000 complete in 2531.0 sec
[-----------------94%---------------   ] 1880 of 2000 complete in 2532.4 sec
[-----------------94%---------------   ] 1881 of 2000 complete in 2533.8 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 2535.2 sec
[-----------------94%---------------   ] 1883 of 2000 complete in 2536.6 sec
[-----------------94%---------------   ] 1884 of 2000 complete in 2538.0 sec
[-----------------94%---------------   ] 1885 of 2000 complete in 2539.5 sec
[-----------------94%---------------   ] 1886 of 2000 complete in 2540.8 sec
[-----------------94%---------------   ] 1887 of 2000 complete in 2542.2 sec
[-----------------94%---------------   ] 1888 of 2000 complete in 2543.6 sec
[-----------------94%---------------   ] 1889 of 2000 complete in 2545.0 sec
[-----------------94%---------------   ] 1890 of 2000 complete in 2546.5 sec
[-----------------94%---------------   ] 1891 of 2000 complete in 2547.9 sec
[-----------------94%---------------   ] 1892 of 2000 complete in 2549.3 sec
[-----------------94%---------------   ] 1893 of 2000 complete in 2550.7 sec
[-----------------94%---------------   ] 1894 of 2000 complete in 2552.1 sec
[-----------------94%----------------  ] 1895 of 2000 complete in 2553.5 sec
[-----------------94%----------------  ] 1896 of 2000 complete in 2554.9 sec
[-----------------94%----------------  ] 1897 of 2000 complete in 2556.3 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 2557.8 sec
[-----------------94%----------------  ] 1899 of 2000 complete in 2559.2 sec
[-----------------95%----------------  ] 1900 of 2000 complete in 2560.6 sec
[-----------------95%----------------  ] 1901 of 2000 complete in 2562.0 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 2563.6 sec
[-----------------95%----------------  ] 1903 of 2000 complete in 2565.1 sec
[-----------------95%----------------  ] 1904 of 2000 complete in 2566.6 sec
[-----------------95%----------------  ] 1905 of 2000 complete in 2568.0 sec
[-----------------95%----------------  ] 1906 of 2000 complete in 2569.4 sec
[-----------------95%----------------  ] 1907 of 2000 complete in 2570.8 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 2572.2 sec
[-----------------95%----------------  ] 1909 of 2000 complete in 2573.7 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 2575.1 sec
[-----------------95%----------------  ] 1911 of 2000 complete in 2576.4 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 2577.8 sec
[-----------------95%----------------  ] 1913 of 2000 complete in 2579.2 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 2580.7 sec
[-----------------95%----------------  ] 1915 of 2000 complete in 2582.3 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 2583.7 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 2585.0 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 2586.5 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 2587.9 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 2589.3 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 2590.8 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 2592.2 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 2593.6 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 2595.0 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 2596.4 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 2597.7 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 2599.1 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 2600.5 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 2602.0 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 2603.4 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 2604.8 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 2606.1 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 2607.5 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 2608.9 sec

[-----------------91%--------------    ] 1829 of 2000 complete in 2466.0 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 2467.5 sec
[-----------------91%--------------    ] 1831 of 2000 complete in 2468.9 sec
[-----------------91%--------------    ] 1832 of 2000 complete in 2470.2 sec
[-----------------91%--------------    ] 1833 of 2000 complete in 2471.6 sec
[-----------------91%--------------    ] 1834 of 2000 complete in 2473.0 sec
[-----------------91%--------------    ] 1835 of 2000 complete in 2474.3 sec
[-----------------91%--------------    ] 1836 of 2000 complete in 2475.7 sec
[-----------------91%--------------    ] 1837 of 2000 complete in 2477.2 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 2478.6 sec
[-----------------91%--------------    ] 1839 of 2000 complete in 2480.0 sec
[-----------------92%--------------    ] 1840 of 2000 complete in 2481.4 sec
[-----------------92%--------------    ] 1841 of 2000 complete in 2482.8 sec
[-----------------92%--------------    ] 1842 of 2000 complete in 2484.3 sec
[-----------------92%---------------   ] 1843 of 2000 complete in 2485.7 sec
[-----------------92%---------------   ] 1844 of 2000 complete in 2487.2 sec
[-----------------92%---------------   ] 1845 of 2000 complete in 2488.6 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 2490.1 sec
[-----------------92%---------------   ] 1847 of 2000 complete in 2491.5 sec
[-----------------92%---------------   ] 1848 of 2000 complete in 2493.0 sec
[-----------------92%---------------   ] 1849 of 2000 complete in 2494.5 sec
[-----------------92%---------------   ] 1850 of 2000 complete in 2495.9 sec
[-----------------92%---------------   ] 1851 of 2000 complete in 2497.3 sec
[-----------------92%---------------   ] 1852 of 2000 complete in 2498.7 sec
[-----------------92%---------------   ] 1853 of 2000 complete in 2500.1 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 2501.5 sec
[-----------------92%---------------   ] 1855 of 2000 complete in 2502.8 sec
[-----------------92%---------------   ] 1856 of 2000 complete in 2504.2 sec
[-----------------92%---------------   ] 1857 of 2000 complete in 2505.6 sec
[-----------------92%---------------   ] 1858 of 2000 complete in 2507.0 sec
[-----------------92%---------------   ] 1859 of 2000 complete in 2508.5 sec
[-----------------93%---------------   ] 1860 of 2000 complete in 2509.9 sec
[-----------------93%---------------   ] 1861 of 2000 complete in 2511.4 sec
[-----------------93%---------------   ] 1862 of 2000 complete in 2512.9 sec
[-----------------93%---------------   ] 1863 of 2000 complete in 2514.3 sec
[-----------------93%---------------   ] 1864 of 2000 complete in 2515.7 sec
[-----------------93%---------------   ] 1865 of 2000 complete in 2517.1 sec
[-----------------93%---------------   ] 1866 of 2000 complete in 2518.5 sec
[-----------------93%---------------   ] 1867 of 2000 complete in 2519.9 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 2521.3 sec
[-----------------93%---------------   ] 1869 of 2000 complete in 2522.6 sec
[-----------------93%---------------   ] 1870 of 2000 complete in 2524.0 sec
[-----------------93%---------------   ] 1871 of 2000 complete in 2525.4 sec
[-----------------93%---------------   ] 1872 of 2000 complete in 2526.8 sec
[-----------------93%---------------   ] 1873 of 2000 complete in 2528.2 sec
[-----------------93%---------------   ] 1874 of 2000 complete in 2529.6 sec
[-----------------93%---------------   ] 1875 of 2000 complete in 2531.0 sec
[-----------------93%---------------   ] 1876 of 2000 complete in 2532.4 sec
[-----------------93%---------------   ] 1877 of 2000 complete in 2533.7 sec
[-----------------93%---------------   ] 1878 of 2000 complete in 2535.2 sec
[-----------------93%---------------   ] 1879 of 2000 complete in 2536.6 sec
[-----------------94%---------------   ] 1880 of 2000 complete in 2537.9 sec
[-----------------94%---------------   ] 1881 of 2000 complete in 2539.3 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 2540.8 sec
[-----------------94%---------------   ] 1883 of 2000 complete in 2542.2 sec
[-----------------94%---------------   ] 1884 of 2000 complete in 2543.6 sec
[-----------------94%---------------   ] 1885 of 2000 complete in 2545.1 sec
[-----------------94%---------------   ] 1886 of 2000 complete in 2546.5 sec
[-----------------94%---------------   ] 1887 of 2000 complete in 2547.9 sec
[-----------------94%---------------   ] 1888 of 2000 complete in 2549.3 sec
[-----------------94%---------------   ] 1889 of 2000 complete in 2550.8 sec
[-----------------94%---------------   ] 1890 of 2000 complete in 2552.2 sec
[-----------------94%---------------   ] 1891 of 2000 complete in 2553.5 sec
[-----------------94%---------------   ] 1892 of 2000 complete in 2554.9 sec
[-----------------94%---------------   ] 1893 of 2000 complete in 2556.2 sec
[-----------------94%---------------   ] 1894 of 2000 complete in 2557.6 sec
[-----------------94%----------------  ] 1895 of 2000 complete in 2559.0 sec
[-----------------94%----------------  ] 1896 of 2000 complete in 2560.4 sec
[-----------------94%----------------  ] 1897 of 2000 complete in 2561.8 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 2563.4 sec
[-----------------94%----------------  ] 1899 of 2000 complete in 2564.8 sec
[-----------------95%----------------  ] 1900 of 2000 complete in 2566.2 sec
[-----------------95%----------------  ] 1901 of 2000 complete in 2567.6 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 2569.0 sec
[-----------------95%----------------  ] 1903 of 2000 complete in 2570.4 sec
[-----------------95%----------------  ] 1904 of 2000 complete in 2571.8 sec
[-----------------95%----------------  ] 1905 of 2000 complete in 2573.2 sec
[-----------------95%----------------  ] 1906 of 2000 complete in 2574.6 sec
[-----------------95%----------------  ] 1907 of 2000 complete in 2576.0 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 2577.4 sec
[-----------------95%----------------  ] 1909 of 2000 complete in 2578.8 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 2580.2 sec
[-----------------95%----------------  ] 1911 of 2000 complete in 2581.6 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 2583.0 sec
[-----------------95%----------------  ] 1913 of 2000 complete in 2584.4 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 2585.8 sec
[-----------------95%----------------  ] 1915 of 2000 complete in 2587.2 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 2588.5 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 2589.9 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 2591.3 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 2592.7 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 2594.0 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 2595.4 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 2596.8 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 2598.2 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 2599.7 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 2601.0 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 2602.4 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 2603.9 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 2605.3 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 2606.7 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 2608.2 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 2609.6 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 2611.0 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 2612.4 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 2613.8 sec
[-----------------91%--------------    ] 1828 of 2000 complete in 2493.6 sec
[-----------------91%--------------    ] 1829 of 2000 complete in 2495.0 sec
[-----------------91%--------------    ] 1830 of 2000 complete in 2496.4 sec
[-----------------91%--------------    ] 1831 of 2000 complete in 2497.8 sec
[-----------------91%--------------    ] 1832 of 2000 complete in 2499.2 sec
[-----------------91%--------------    ] 1833 of 2000 complete in 2500.5 sec
[-----------------91%--------------    ] 1834 of 2000 complete in 2501.9 sec
[-----------------91%--------------    ] 1835 of 2000 complete in 2503.3 sec
[-----------------91%--------------    ] 1836 of 2000 complete in 2504.8 sec
[-----------------91%--------------    ] 1837 of 2000 complete in 2506.2 sec
[-----------------91%--------------    ] 1838 of 2000 complete in 2507.7 sec
[-----------------91%--------------    ] 1839 of 2000 complete in 2509.0 sec
[-----------------92%--------------    ] 1840 of 2000 complete in 2510.4 sec
[-----------------92%--------------    ] 1841 of 2000 complete in 2511.9 sec
[-----------------92%--------------    ] 1842 of 2000 complete in 2513.4 sec
[-----------------92%---------------   ] 1843 of 2000 complete in 2514.8 sec
[-----------------92%---------------   ] 1844 of 2000 complete in 2516.2 sec
[-----------------92%---------------   ] 1845 of 2000 complete in 2517.6 sec
[-----------------92%---------------   ] 1846 of 2000 complete in 2519.1 sec
[-----------------92%---------------   ] 1847 of 2000 complete in 2520.5 sec
[-----------------92%---------------   ] 1848 of 2000 complete in 2522.0 sec
[-----------------92%---------------   ] 1849 of 2000 complete in 2523.3 sec
[-----------------92%---------------   ] 1850 of 2000 complete in 2524.7 sec
[-----------------92%---------------   ] 1851 of 2000 complete in 2526.0 sec
[-----------------92%---------------   ] 1852 of 2000 complete in 2527.5 sec
[-----------------92%---------------   ] 1853 of 2000 complete in 2528.9 sec
[-----------------92%---------------   ] 1854 of 2000 complete in 2530.2 sec
[-----------------92%---------------   ] 1855 of 2000 complete in 2531.6 sec
[-----------------92%---------------   ] 1856 of 2000 complete in 2533.0 sec
[-----------------92%---------------   ] 1857 of 2000 complete in 2534.3 sec
[-----------------92%---------------   ] 1858 of 2000 complete in 2535.7 sec
[-----------------92%---------------   ] 1859 of 2000 complete in 2537.1 sec
[-----------------93%---------------   ] 1860 of 2000 complete in 2538.5 sec
[-----------------93%---------------   ] 1861 of 2000 complete in 2539.9 sec
[-----------------93%---------------   ] 1862 of 2000 complete in 2541.2 sec
[-----------------93%---------------   ] 1863 of 2000 complete in 2542.5 sec
[-----------------93%---------------   ] 1864 of 2000 complete in 2543.9 sec
[-----------------93%---------------   ] 1865 of 2000 complete in 2545.4 sec
[-----------------93%---------------   ] 1866 of 2000 complete in 2546.8 sec
[-----------------93%---------------   ] 1867 of 2000 complete in 2548.2 sec
[-----------------93%---------------   ] 1868 of 2000 complete in 2549.7 sec
[-----------------93%---------------   ] 1869 of 2000 complete in 2551.0 sec
[-----------------93%---------------   ] 1870 of 2000 complete in 2552.4 sec
[-----------------93%---------------   ] 1871 of 2000 complete in 2553.9 sec
[-----------------93%---------------   ] 1872 of 2000 complete in 2555.2 sec
[-----------------93%---------------   ] 1873 of 2000 complete in 2556.6 sec
[-----------------93%---------------   ] 1874 of 2000 complete in 2557.9 sec
[-----------------93%---------------   ] 1875 of 2000 complete in 2559.3 sec
[-----------------93%---------------   ] 1876 of 2000 complete in 2560.8 sec
[-----------------93%---------------   ] 1877 of 2000 complete in 2562.2 sec
[-----------------93%---------------   ] 1878 of 2000 complete in 2563.7 sec
[-----------------93%---------------   ] 1879 of 2000 complete in 2565.2 sec
[-----------------94%---------------   ] 1880 of 2000 complete in 2566.6 sec
[-----------------94%---------------   ] 1881 of 2000 complete in 2568.1 sec
[-----------------94%---------------   ] 1882 of 2000 complete in 2569.5 sec
[-----------------94%---------------   ] 1883 of 2000 complete in 2570.9 sec
[-----------------94%---------------   ] 1884 of 2000 complete in 2572.2 sec
[-----------------94%---------------   ] 1885 of 2000 complete in 2573.6 sec
[-----------------94%---------------   ] 1886 of 2000 complete in 2575.1 sec
[-----------------94%---------------   ] 1887 of 2000 complete in 2576.5 sec
[-----------------94%---------------   ] 1888 of 2000 complete in 2577.9 sec
[-----------------94%---------------   ] 1889 of 2000 complete in 2579.3 sec
[-----------------94%---------------   ] 1890 of 2000 complete in 2580.7 sec
[-----------------94%---------------   ] 1891 of 2000 complete in 2582.1 sec
[-----------------94%---------------   ] 1892 of 2000 complete in 2583.5 sec
[-----------------94%---------------   ] 1893 of 2000 complete in 2584.9 sec
[-----------------94%---------------   ] 1894 of 2000 complete in 2586.2 sec
[-----------------94%----------------  ] 1895 of 2000 complete in 2587.6 sec
[-----------------94%----------------  ] 1896 of 2000 complete in 2588.9 sec
[-----------------94%----------------  ] 1897 of 2000 complete in 2590.3 sec
[-----------------94%----------------  ] 1898 of 2000 complete in 2591.7 sec
[-----------------94%----------------  ] 1899 of 2000 complete in 2593.1 sec
[-----------------95%----------------  ] 1900 of 2000 complete in 2594.4 sec
[-----------------95%----------------  ] 1901 of 2000 complete in 2595.9 sec
[-----------------95%----------------  ] 1902 of 2000 complete in 2597.3 sec
[-----------------95%----------------  ] 1903 of 2000 complete in 2598.6 sec
[-----------------95%----------------  ] 1904 of 2000 complete in 2600.1 sec
[-----------------95%----------------  ] 1905 of 2000 complete in 2601.5 sec
[-----------------95%----------------  ] 1906 of 2000 complete in 2602.9 sec
[-----------------95%----------------  ] 1907 of 2000 complete in 2604.3 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 2605.7 sec
[-----------------95%----------------  ] 1909 of 2000 complete in 2607.1 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 2608.5 sec
[-----------------95%----------------  ] 1911 of 2000 complete in 2609.8 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 2611.2 sec
[-----------------95%----------------  ] 1913 of 2000 complete in 2612.7 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 2614.1 sec
[-----------------95%----------------  ] 1915 of 2000 complete in 2615.6 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 2617.0 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 2618.4 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 2619.9 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 2621.3 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 2622.7 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 2624.1 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 2625.5 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 2627.0 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 2628.4 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 2629.8 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 2631.2 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 2632.7 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 2634.1 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 2635.5 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 2636.9 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 2638.3 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 2639.8 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 2641.1 sec

hddm sampling elpased time:  2787.226 s
Start converting to InferenceData...

In [44]:
summary = az.summary(hddmReg_stim_vflip_m3_diff_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

                                mean     sd  hdi_3%  hdi_97%  mcse_mean
a                              1.990  0.177   1.676    2.322      0.037  \
a_std                          0.931  0.169   0.634    1.243      0.040
t                              0.240  0.010   0.222    0.260      0.002
t_std                          0.051  0.009   0.035    0.068      0.001
z                              0.542  0.006   0.529    0.553      0.000
z_std                          0.134  0.018   0.101    0.167      0.001
v_id[Other]                    3.454  0.228   3.036    3.891      0.030
v_id[Other]_std                1.308  0.170   0.997    1.620      0.023
v_id[Self]                     0.809  1.262  -1.307    3.219      0.574
v_id[Self]_std                 0.660  0.314   0.051    1.191      0.096
v_C(stim)[T.1]                 1.939  1.097  -0.173    3.974      0.508
v_C(stim)[T.1]_std             0.694  0.331   0.003    1.195      0.119
v_id[T.Self]:C(stim)[T.1]      0.570  1.222  -1.481    2.961      0.564
v_id[T.Self]:C(stim)[T.1]_std  0.806  0.362   0.032    1.328      0.134

                               mcse_sd  ess_bulk  ess_tail  r_hat
a                                0.027      22.0     294.0   1.12
a_std                            0.029      17.0     100.0   1.17
t                                0.002      19.0     183.0   1.14
t_std                            0.001      46.0      90.0   1.07
z                                0.000    1797.0    4079.0   1.01
z_std                            0.000     812.0    1814.0   1.01
v_id[Other]                      0.022      56.0    1061.0   1.05
v_id[Other]_std                  0.016      53.0     855.0   1.05
v_id[Self]                       0.433       5.0      11.0   2.30
v_id[Self]_std                   0.070      11.0      34.0   1.28
v_C(stim)[T.1]                   0.384       5.0      14.0   2.40
v_C(stim)[T.1]_std               0.087       8.0      17.0   1.46
v_id[T.Self]:C(stim)[T.1]        0.426       5.0      12.0   2.34
v_id[T.Self]:C(stim)[T.1]_std    0.099       8.0      16.0   1.49

In [45]:
#hddmReg_stim_z_flip
# using stim coding with HDDMRegressor
# type2: acc coding + z flip 
data['response'] = data['acc']

def z_link_func(x, data=data):
  # 1 is self; 0 is other
  stim = data.stim.loc[x.index]
    z_flip = (stim * x) + (1 - x) * (1 - stim)
    return z_flip

z_reg = [{'model': "z ~ 1", 'link_func': z_link_func}] 

hddmReg_stim_zflip_m2_diff = hddm.HDDMRegressor(
    data,
    z_reg,
    bias=True, p_outlier=0.05,
    include=['v', 'a', 't', 'z'],
    depends_on={'v': ['id','stim']},
    group_only_regressors=False
)

hddmReg_stim_zflip_m2_diff_idata = hddmReg_stim_zflip_m2_diff.sample(2000, burn=500, chains=4, return_infdata=True, dbname = 'hddmReg_stim_zflip_m2_diff.db', db = 'pickle')
hddmReg_stim_zflip_m2_diff.save('hddmReg_stim_zflip_m2_diff.hddm')

No model attribute --> setting up standard HDDM
Set model to ddm

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/opt/conda/lib/python3.9/site-packages/scipy/optimize/_optimize.py:2309: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)

[-----------------96%----------------  ] 1934 of 2000 complete in 2642.5 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 2643.9 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 2645.3 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 2646.8 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 2648.3 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 2649.7 sec
[-----------------97%----------------  ] 1940 of 2000 complete in 2651.1 sec
[-----------------97%----------------  ] 1941 of 2000 complete in 2652.5 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 2653.9 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 2655.5 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 2656.8 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 2658.3 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 2659.6 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 2660.9 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 2662.3 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 2663.6 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 2665.0 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 2666.4 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 2667.9 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 2669.3 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 2670.7 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 2672.1 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 2673.5 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 2674.9 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 2676.3 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 2677.7 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 2679.1 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 2680.6 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 2681.9 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 2683.4 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 2684.8 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 2686.3 sec
[-----------------98%----------------- ] 1966 of 2000 complete in 2687.8 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 2689.3 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 2690.7 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 2692.1 sec
[-----------------98%----------------- ] 1970 of 2000 complete in 2693.4 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 2694.7 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 2696.1 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 2697.5 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 2698.8 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 2700.1 sec
[-----------------98%----------------- ] 1976 of 2000 complete in 2701.5 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 2702.9 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 2704.2 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 2705.6 sec
[-----------------99%----------------- ] 1980 of 2000 complete in 2706.8 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 2708.1 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 2709.4 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 2710.6 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 2712.0 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 2713.3 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 2714.6 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 2715.9 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 2717.1 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 2718.4 sec
[-----------------99%----------------- ] 1990 of 2000 complete in 2719.7 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 2721.0 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 2722.4 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 2723.7 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 2724.9 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 2726.2 sec
[-----------------99%----------------- ] 1996 of 2000 complete in 2727.5 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 2728.9 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 2730.1 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 2731.4 sec
[-----------------100%-----------------] 2000 of 2000 complete in 2732.7 sec
[-----------------100%-----------------] 2001 of 2000 complete in 2733.9 sec
hddm sampling elpased time:  2734.088 s
[                  0%                  ] 3 of 2000 complete in 0.7 sec
[                  0%                  ] 5 of 2000 complete in 1.3 sec
[                  0%                  ] 7 of 2000 complete in 1.9 sec
[                  0%                  ] 9 of 2000 complete in 2.5 sec
[                  0%                  ] 11 of 2000 complete in 3.1 sec
[                  0%                  ] 13 of 2000 complete in 3.7 sec
[                  0%                  ] 15 of 2000 complete in 4.3 sec
[                  0%                  ] 17 of 2000 complete in 4.9 sec
[                  0%                  ] 19 of 2000 complete in 5.5 sec
[                  1%                  ] 21 of 2000 complete in 6.1 sec
[                  1%                  ] 23 of 2000 complete in 6.7 sec
[                  1%                  ] 25 of 2000 complete in 7.3 sec
[                  1%                  ] 27 of 2000 complete in 7.9 sec
[                  1%                  ] 29 of 2000 complete in 8.5 sec
[                  1%                  ] 31 of 2000 complete in 9.1 sec
[                  1%                  ] 33 of 2000 complete in 9.7 sec
[                  1%                  ] 35 of 2000 complete in 10.3 sec
[                  1%                  ] 37 of 2000 complete in 11.0 sec
[                  1%                  ] 39 of 2000 complete in 11.6 sec
[                  2%                  ] 41 of 2000 complete in 12.2 sec
[                  2%                  ] 43 of 2000 complete in 12.8 sec
[                  2%                  ] 45 of 2000 complete in 13.3 sec
[                  2%                  ] 47 of 2000 complete in 14.0 sec
[                  2%                  ] 49 of 2000 complete in 14.6 sec
[                  2%                  ] 51 of 2000 complete in 15.2 sec
[-                 2%                  ] 53 of 2000 complete in 15.8 sec
[-                 2%                  ] 55 of 2000 complete in 16.4 sec
[-                 2%                  ] 57 of 2000 complete in 17.0 sec
[-                 2%                  ] 59 of 2000 complete in 17.5 sec
[-                 3%                  ] 61 of 2000 complete in 18.2 sec
[-                 3%                  ] 63 of 2000 complete in 18.7 sec
[-                 3%                  ] 65 of 2000 complete in 19.3 sec
[-                 3%                  ] 67 of 2000 complete in 19.9 sec
[-                 3%                  ] 69 of 2000 complete in 20.5 sec
[-                 3%                  ] 71 of 2000 complete in 21.1 sec
[-                 3%                  ] 73 of 2000 complete in 21.7 sec
[-                 3%                  ] 75 of 2000 complete in 22.3 sec
[-                 3%                  ] 77 of 2000 complete in 23.0 sec
[-                 3%                  ] 79 of 2000 complete in 23.6 sec
[-                 4%                  ] 81 of 2000 complete in 24.2 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 2600.8 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 2602.1 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 2603.4 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 2604.7 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 2606.0 sec
[-----------------97%----------------  ] 1940 of 2000 complete in 2607.3 sec
[-----------------97%----------------  ] 1941 of 2000 complete in 2608.5 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 2609.8 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 2611.1 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 2612.3 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 2613.6 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 2614.8 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 2616.0 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 2617.3 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 2618.5 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 2619.8 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 2621.0 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 2622.2 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 2623.4 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 2624.7 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 2626.0 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 2627.2 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 2628.4 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 2629.6 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 2630.8 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 2632.1 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 2633.3 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 2634.5 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 2635.7 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 2636.9 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 2638.1 sec
[-----------------98%----------------- ] 1966 of 2000 complete in 2639.4 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 2640.6 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 2641.9 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 2643.0 sec
[-----------------98%----------------- ] 1970 of 2000 complete in 2644.3 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 2645.5 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 2646.7 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 2648.0 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 2649.3 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 2650.5 sec
[-----------------98%----------------- ] 1976 of 2000 complete in 2651.7 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 2653.0 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 2654.3 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 2655.6 sec
[-----------------99%----------------- ] 1980 of 2000 complete in 2656.9 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 2658.2 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 2659.6 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 2660.9 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 2662.2 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 2663.5 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 2664.9 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 2666.2 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 2667.6 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 2668.9 sec
[-----------------99%----------------- ] 1990 of 2000 complete in 2670.2 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 2671.6 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 2672.9 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 2674.3 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 2675.6 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 2677.0 sec
[-----------------99%----------------- ] 1996 of 2000 complete in 2678.3 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 2679.6 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 2680.9 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 2682.3 sec
[-----------------100%-----------------] 2000 of 2000 complete in 2683.6 sec
[-----------------100%-----------------] 2001 of 2000 complete in 2685.0 sec
hddm sampling elpased time:  2685.146 s
[                  0%                  ] 3 of 2000 complete in 0.7 sec
[                  0%                  ] 5 of 2000 complete in 1.3 sec
[                  0%                  ] 7 of 2000 complete in 1.9 sec
[                  0%                  ] 9 of 2000 complete in 2.5 sec
[                  0%                  ] 11 of 2000 complete in 3.1 sec
[                  0%                  ] 13 of 2000 complete in 3.7 sec
[                  0%                  ] 15 of 2000 complete in 4.3 sec
[                  0%                  ] 17 of 2000 complete in 4.8 sec
[                  0%                  ] 19 of 2000 complete in 5.4 sec
[                  1%                  ] 21 of 2000 complete in 6.0 sec
[                  1%                  ] 23 of 2000 complete in 6.6 sec
[                  1%                  ] 25 of 2000 complete in 7.2 sec
[                  1%                  ] 27 of 2000 complete in 7.8 sec
[                  1%                  ] 29 of 2000 complete in 8.4 sec
[                  1%                  ] 31 of 2000 complete in 9.0 sec
[                  1%                  ] 33 of 2000 complete in 9.6 sec
[                  1%                  ] 35 of 2000 complete in 10.2 sec
[                  1%                  ] 37 of 2000 complete in 10.9 sec
[                  1%                  ] 39 of 2000 complete in 11.5 sec
[                  2%                  ] 41 of 2000 complete in 12.1 sec
[                  2%                  ] 43 of 2000 complete in 12.6 sec
[                  2%                  ] 45 of 2000 complete in 13.2 sec
[                  2%                  ] 47 of 2000 complete in 13.8 sec
[                  2%                  ] 49 of 2000 complete in 14.4 sec
[                  2%                  ] 51 of 2000 complete in 15.0 sec
[-                 2%                  ] 53 of 2000 complete in 15.6 sec
[-                 2%                  ] 55 of 2000 complete in 16.2 sec
[-                 2%                  ] 57 of 2000 complete in 16.8 sec
[-                 2%                  ] 59 of 2000 complete in 17.4 sec
[-                 3%                  ] 61 of 2000 complete in 18.0 sec
[-                 3%                  ] 63 of 2000 complete in 18.6 sec
[-                 3%                  ] 65 of 2000 complete in 19.2 sec
[-                 3%                  ] 67 of 2000 complete in 19.8 sec
[-                 3%                  ] 69 of 2000 complete in 20.4 sec
[-                 3%                  ] 71 of 2000 complete in 21.0 sec
[-                 3%                  ] 73 of 2000 complete in 21.5 sec
[-                 3%                  ] 75 of 2000 complete in 22.1 sec
[-                 3%                  ] 77 of 2000 complete in 22.7 sec
[-                 3%                  ] 79 of 2000 complete in 23.4 sec
[-                 4%                  ] 81 of 2000 complete in 24.0 sec
[-                 4%                  ] 83 of 2000 complete in 24.5 sec

[-----------------96%----------------  ] 1935 of 2000 complete in 2610.2 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 2611.6 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 2613.0 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 2614.4 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 2615.7 sec
[-----------------97%----------------  ] 1940 of 2000 complete in 2617.1 sec
[-----------------97%----------------  ] 1941 of 2000 complete in 2618.5 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 2619.9 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 2621.3 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 2622.6 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 2623.9 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 2625.3 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 2626.7 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 2628.1 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 2629.5 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 2630.9 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 2632.4 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 2633.8 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 2635.2 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 2636.7 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 2638.1 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 2639.5 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 2640.9 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 2642.3 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 2643.7 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 2645.1 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 2646.5 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 2648.0 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 2649.4 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 2650.8 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 2652.1 sec
[-----------------98%----------------- ] 1966 of 2000 complete in 2653.6 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 2655.1 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 2656.5 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 2657.9 sec
[-----------------98%----------------- ] 1970 of 2000 complete in 2659.3 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 2660.7 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 2662.0 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 2663.4 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 2664.9 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 2666.2 sec
[-----------------98%----------------- ] 1976 of 2000 complete in 2667.6 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 2669.0 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 2670.4 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 2671.8 sec
[-----------------99%----------------- ] 1980 of 2000 complete in 2673.2 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 2674.6 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 2676.0 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 2677.4 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 2678.8 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 2680.2 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 2681.5 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 2683.0 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 2684.3 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 2685.8 sec
[-----------------99%----------------- ] 1990 of 2000 complete in 2687.2 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 2688.6 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 2690.1 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 2691.4 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 2692.7 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 2694.1 sec
[-----------------99%----------------- ] 1996 of 2000 complete in 2695.4 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 2696.7 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 2698.1 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 2699.4 sec
[-----------------100%-----------------] 2000 of 2000 complete in 2700.6 sec
[-----------------100%-----------------] 2001 of 2000 complete in 2701.9 sec
hddm sampling elpased time:  2702.067 s
[                  0%                  ] 3 of 2000 complete in 0.7 sec
[                  0%                  ] 5 of 2000 complete in 1.3 sec
[                  0%                  ] 7 of 2000 complete in 1.9 sec
[                  0%                  ] 9 of 2000 complete in 2.5 sec
[                  0%                  ] 11 of 2000 complete in 3.1 sec
[                  0%                  ] 13 of 2000 complete in 3.7 sec
[                  0%                  ] 15 of 2000 complete in 4.3 sec
[                  0%                  ] 17 of 2000 complete in 4.9 sec
[                  0%                  ] 19 of 2000 complete in 5.5 sec
[                  1%                  ] 21 of 2000 complete in 6.1 sec
[                  1%                  ] 23 of 2000 complete in 6.7 sec
[                  1%                  ] 25 of 2000 complete in 7.4 sec
[                  1%                  ] 27 of 2000 complete in 8.0 sec
[                  1%                  ] 29 of 2000 complete in 8.6 sec
[                  1%                  ] 31 of 2000 complete in 9.2 sec
[                  1%                  ] 33 of 2000 complete in 9.8 sec
[                  1%                  ] 35 of 2000 complete in 10.4 sec
[                  1%                  ] 37 of 2000 complete in 11.0 sec
[                  1%                  ] 39 of 2000 complete in 11.6 sec
[                  2%                  ] 41 of 2000 complete in 12.2 sec
[                  2%                  ] 43 of 2000 complete in 12.8 sec
[                  2%                  ] 45 of 2000 complete in 13.4 sec
[                  2%                  ] 47 of 2000 complete in 14.0 sec
[                  2%                  ] 49 of 2000 complete in 14.6 sec
[                  2%                  ] 51 of 2000 complete in 15.2 sec
[-                 2%                  ] 53 of 2000 complete in 15.8 sec
[-                 2%                  ] 55 of 2000 complete in 16.4 sec
[-                 2%                  ] 57 of 2000 complete in 17.0 sec
[-                 2%                  ] 59 of 2000 complete in 17.6 sec
[-                 3%                  ] 61 of 2000 complete in 18.2 sec
[-                 3%                  ] 63 of 2000 complete in 18.8 sec
[-                 3%                  ] 65 of 2000 complete in 19.4 sec
[-                 3%                  ] 67 of 2000 complete in 20.0 sec
[-                 3%                  ] 69 of 2000 complete in 20.6 sec
[-                 3%                  ] 71 of 2000 complete in 21.2 sec
[-                 3%                  ] 73 of 2000 complete in 21.8 sec
[-                 3%                  ] 75 of 2000 complete in 22.4 sec
[-                 3%                  ] 77 of 2000 complete in 23.0 sec
[-                 3%                  ] 79 of 2000 complete in 23.6 sec
[-                 4%                  ] 81 of 2000 complete in 24.2 sec
[-                 4%                  ] 83 of 2000 complete in 24.8 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 2615.2 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 2616.7 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 2618.1 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 2619.5 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 2620.9 sec
[-----------------97%----------------  ] 1940 of 2000 complete in 2622.3 sec
[-----------------97%----------------  ] 1941 of 2000 complete in 2623.7 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 2625.0 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 2626.4 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 2627.8 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 2629.2 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 2630.7 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 2632.1 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 2633.4 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 2634.8 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 2636.2 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 2637.6 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 2639.0 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 2640.5 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 2641.9 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 2643.3 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 2644.7 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 2646.2 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 2647.6 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 2649.1 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 2650.5 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 2652.0 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 2653.3 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 2654.7 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 2656.1 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 2657.6 sec
[-----------------98%----------------- ] 1966 of 2000 complete in 2659.0 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 2660.4 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 2661.8 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 2663.2 sec
[-----------------98%----------------- ] 1970 of 2000 complete in 2664.7 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 2666.1 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 2667.5 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 2668.9 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 2670.4 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 2671.8 sec
[-----------------98%----------------- ] 1976 of 2000 complete in 2673.2 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 2674.6 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 2676.0 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 2677.5 sec
[-----------------99%----------------- ] 1980 of 2000 complete in 2678.9 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 2680.3 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 2681.7 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 2683.1 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 2684.6 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 2686.0 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 2687.4 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 2689.0 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 2690.5 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 2691.8 sec
[-----------------99%----------------- ] 1990 of 2000 complete in 2693.2 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 2694.4 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 2695.7 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 2697.0 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 2698.3 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 2699.6 sec
[-----------------99%----------------- ] 1996 of 2000 complete in 2700.9 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 2702.3 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 2703.6 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 2704.9 sec
[-----------------100%-----------------] 2000 of 2000 complete in 2706.2 sec
[-----------------100%-----------------] 2001 of 2000 complete in 2707.4 sec
hddm sampling elpased time:  2707.577 s
[                  0%                  ] 3 of 2000 complete in 0.7 sec
[                  0%                  ] 5 of 2000 complete in 1.3 sec
[                  0%                  ] 7 of 2000 complete in 1.9 sec
[                  0%                  ] 9 of 2000 complete in 2.5 sec
[                  0%                  ] 11 of 2000 complete in 3.1 sec
[                  0%                  ] 13 of 2000 complete in 3.7 sec
[                  0%                  ] 15 of 2000 complete in 4.3 sec
[                  0%                  ] 17 of 2000 complete in 4.9 sec
[                  0%                  ] 19 of 2000 complete in 5.5 sec
[                  1%                  ] 21 of 2000 complete in 6.2 sec
[                  1%                  ] 23 of 2000 complete in 6.8 sec
[                  1%                  ] 25 of 2000 complete in 7.4 sec
[                  1%                  ] 27 of 2000 complete in 8.0 sec
[                  1%                  ] 29 of 2000 complete in 8.6 sec
[                  1%                  ] 31 of 2000 complete in 9.2 sec
[                  1%                  ] 33 of 2000 complete in 9.8 sec
[                  1%                  ] 35 of 2000 complete in 10.4 sec
[                  1%                  ] 37 of 2000 complete in 11.1 sec
[                  1%                  ] 39 of 2000 complete in 11.6 sec
[                  2%                  ] 41 of 2000 complete in 12.3 sec
[                  2%                  ] 43 of 2000 complete in 12.8 sec
[                  2%                  ] 45 of 2000 complete in 13.4 sec
[                  2%                  ] 47 of 2000 complete in 14.0 sec
[                  2%                  ] 49 of 2000 complete in 14.6 sec
[                  2%                  ] 51 of 2000 complete in 15.2 sec
[-                 2%                  ] 53 of 2000 complete in 15.8 sec
[-                 2%                  ] 55 of 2000 complete in 16.5 sec
[-                 2%                  ] 57 of 2000 complete in 17.1 sec
[-                 2%                  ] 59 of 2000 complete in 17.7 sec
[-                 3%                  ] 61 of 2000 complete in 18.2 sec
[-                 3%                  ] 63 of 2000 complete in 18.9 sec
[-                 3%                  ] 65 of 2000 complete in 19.5 sec
[-                 3%                  ] 67 of 2000 complete in 20.1 sec
[-                 3%                  ] 69 of 2000 complete in 20.6 sec
[-                 3%                  ] 71 of 2000 complete in 21.2 sec
[-                 3%                  ] 73 of 2000 complete in 21.8 sec
[-                 3%                  ] 75 of 2000 complete in 22.4 sec
[-                 3%                  ] 77 of 2000 complete in 23.1 sec
[-                 3%                  ] 79 of 2000 complete in 23.7 sec
[-                 4%                  ] 81 of 2000 complete in 24.3 sec
[-                 4%                  ] 83 of 2000 complete in 24.9 sec

[-                 4%                  ] 85 of 2000 complete in 25.1 sec
[-                 4%                  ] 87 of 2000 complete in 25.7 sec
[-                 4%                  ] 89 of 2000 complete in 26.3 sec
[-                 4%                  ] 91 of 2000 complete in 26.9 sec
[-                 4%                  ] 93 of 2000 complete in 27.5 sec
[-                 4%                  ] 95 of 2000 complete in 28.0 sec
[-                 4%                  ] 97 of 2000 complete in 28.6 sec
[-                 4%                  ] 99 of 2000 complete in 29.2 sec
[-                 5%                  ] 101 of 2000 complete in 29.8 sec
[-                 5%                  ] 103 of 2000 complete in 30.4 sec
[-                 5%                  ] 105 of 2000 complete in 31.0 sec
[--                5%                  ] 107 of 2000 complete in 31.6 sec
[--                5%                  ] 109 of 2000 complete in 32.2 sec
[--                5%                  ] 111 of 2000 complete in 32.8 sec
[--                5%                  ] 113 of 2000 complete in 33.4 sec
[--                5%                  ] 115 of 2000 complete in 34.0 sec
[--                5%                  ] 117 of 2000 complete in 34.7 sec
[--                5%                  ] 119 of 2000 complete in 35.4 sec
[--                6%                  ] 121 of 2000 complete in 36.0 sec
[--                6%                  ] 123 of 2000 complete in 36.6 sec
[--                6%                  ] 125 of 2000 complete in 37.2 sec
[--                6%                  ] 127 of 2000 complete in 37.9 sec
[--                6%                  ] 129 of 2000 complete in 38.6 sec
[--                6%                  ] 131 of 2000 complete in 39.2 sec
[--                6%                  ] 133 of 2000 complete in 39.8 sec
[--                6%                  ] 135 of 2000 complete in 40.4 sec
[--                6%                  ] 137 of 2000 complete in 41.1 sec
[--                6%                  ] 139 of 2000 complete in 41.8 sec
[--                7%                  ] 141 of 2000 complete in 42.4 sec
[--                7%                  ] 143 of 2000 complete in 43.1 sec
[--                7%                  ] 145 of 2000 complete in 43.7 sec
[--                7%                  ] 147 of 2000 complete in 44.2 sec
[--                7%                  ] 149 of 2000 complete in 44.8 sec
[--                7%                  ] 151 of 2000 complete in 45.5 sec
[--                7%                  ] 153 of 2000 complete in 46.1 sec
[--                7%                  ] 155 of 2000 complete in 46.7 sec
[--                7%                  ] 157 of 2000 complete in 47.4 sec
[---               7%                  ] 159 of 2000 complete in 48.0 sec
[---               8%                  ] 161 of 2000 complete in 48.7 sec
[---               8%                  ] 163 of 2000 complete in 49.3 sec
[---               8%                  ] 165 of 2000 complete in 49.9 sec
[---               8%                  ] 167 of 2000 complete in 50.5 sec
[---               8%                  ] 169 of 2000 complete in 51.1 sec
[---               8%                  ] 171 of 2000 complete in 51.7 sec
[---               8%                  ] 173 of 2000 complete in 52.3 sec
[---               8%                  ] 175 of 2000 complete in 52.9 sec
[---               8%                  ] 177 of 2000 complete in 53.5 sec
[---               8%                  ] 179 of 2000 complete in 54.1 sec
[---               9%                  ] 181 of 2000 complete in 54.7 sec
[---               9%                  ] 183 of 2000 complete in 55.3 sec
[---               9%                  ] 185 of 2000 complete in 55.9 sec
[---               9%                  ] 187 of 2000 complete in 56.4 sec
[---               9%                  ] 189 of 2000 complete in 57.0 sec
[---               9%                  ] 191 of 2000 complete in 57.6 sec
[---               9%                  ] 193 of 2000 complete in 58.2 sec
[---               9%                  ] 195 of 2000 complete in 58.8 sec
[---               9%                  ] 197 of 2000 complete in 59.4 sec
[---               9%                  ] 199 of 2000 complete in 60.0 sec
[---              10%                  ] 201 of 2000 complete in 60.6 sec
[---              10%                  ] 203 of 2000 complete in 61.2 sec
[---              10%                  ] 205 of 2000 complete in 61.8 sec
[---              10%                  ] 207 of 2000 complete in 62.4 sec
[---              10%                  ] 209 of 2000 complete in 63.0 sec
[----             10%                  ] 211 of 2000 complete in 63.6 sec
[----             10%                  ] 213 of 2000 complete in 64.2 sec
[----             10%                  ] 215 of 2000 complete in 64.8 sec
[----             10%                  ] 217 of 2000 complete in 65.4 sec
[----             10%                  ] 219 of 2000 complete in 66.0 sec
[----             11%                  ] 221 of 2000 complete in 66.6 sec
[----             11%                  ] 223 of 2000 complete in 67.2 sec
[----             11%                  ] 225 of 2000 complete in 67.8 sec
[----             11%                  ] 227 of 2000 complete in 68.4 sec
[----             11%                  ] 229 of 2000 complete in 69.1 sec
[----             11%                  ] 231 of 2000 complete in 69.7 sec
[----             11%                  ] 233 of 2000 complete in 70.3 sec
[----             11%                  ] 235 of 2000 complete in 71.0 sec
[----             11%                  ] 237 of 2000 complete in 71.6 sec
[----             11%                  ] 239 of 2000 complete in 72.2 sec
[----             12%                  ] 241 of 2000 complete in 72.7 sec
[----             12%                  ] 243 of 2000 complete in 73.3 sec
[----             12%                  ] 245 of 2000 complete in 73.9 sec
[----             12%                  ] 247 of 2000 complete in 74.5 sec
[----             12%                  ] 249 of 2000 complete in 75.1 sec
[----             12%                  ] 251 of 2000 complete in 75.7 sec
[----             12%                  ] 253 of 2000 complete in 76.3 sec
[----             12%                  ] 255 of 2000 complete in 76.9 sec
[----             12%                  ] 257 of 2000 complete in 77.5 sec
[----             12%                  ] 259 of 2000 complete in 78.1 sec
[----             13%                  ] 261 of 2000 complete in 78.7 sec
[----             13%                  ] 263 of 2000 complete in 79.3 sec
[-----            13%                  ] 265 of 2000 complete in 79.9 sec
[-----            13%                  ] 267 of 2000 complete in 80.6 sec
[-----            13%                  ] 269 of 2000 complete in 81.2 sec
[-----            13%                  ] 271 of 2000 complete in 81.8 sec
[-----            13%                  ] 273 of 2000 complete in 82.4 sec
[-----            13%                  ] 275 of 2000 complete in 83.0 sec
[-----            13%                  ] 277 of 2000 complete in 83.6 sec
[-----            13%                  ] 279 of 2000 complete in 84.2 sec
[-----            14%                  ] 281 of 2000 complete in 84.8 sec
[-----            14%                  ] 283 of 2000 complete in 85.4 sec
[-----            14%                  ] 285 of 2000 complete in 86.0 sec
[-----            14%                  ] 287 of 2000 complete in 86.6 sec
[-----            14%                  ] 289 of 2000 complete in 87.2 sec
[-----            14%                  ] 291 of 2000 complete in 87.8 sec
[-----            14%                  ] 293 of 2000 complete in 88.4 sec
[-----            14%                  ] 295 of 2000 complete in 89.0 sec
[-----            14%                  ] 297 of 2000 complete in 89.7 sec
[-----            14%                  ] 299 of 2000 complete in 90.3 sec
[-----            15%                  ] 301 of 2000 complete in 90.9 sec
[-----            15%                  ] 303 of 2000 complete in 91.5 sec
[-                 4%                  ] 83 of 2000 complete in 24.8 sec
[-                 4%                  ] 85 of 2000 complete in 25.4 sec
[-                 4%                  ] 87 of 2000 complete in 26.0 sec
[-                 4%                  ] 89 of 2000 complete in 26.6 sec
[-                 4%                  ] 91 of 2000 complete in 27.2 sec
[-                 4%                  ] 93 of 2000 complete in 27.8 sec
[-                 4%                  ] 95 of 2000 complete in 28.4 sec
[-                 4%                  ] 97 of 2000 complete in 29.0 sec
[-                 4%                  ] 99 of 2000 complete in 29.6 sec
[-                 5%                  ] 101 of 2000 complete in 30.2 sec
[-                 5%                  ] 103 of 2000 complete in 30.8 sec
[-                 5%                  ] 105 of 2000 complete in 31.3 sec
[--                5%                  ] 107 of 2000 complete in 32.0 sec
[--                5%                  ] 109 of 2000 complete in 32.6 sec
[--                5%                  ] 111 of 2000 complete in 33.2 sec
[--                5%                  ] 113 of 2000 complete in 33.8 sec
[--                5%                  ] 115 of 2000 complete in 34.5 sec
[--                5%                  ] 117 of 2000 complete in 35.1 sec
[--                5%                  ] 119 of 2000 complete in 35.8 sec
[--                6%                  ] 121 of 2000 complete in 36.4 sec
[--                6%                  ] 123 of 2000 complete in 37.0 sec
[--                6%                  ] 125 of 2000 complete in 37.6 sec
[--                6%                  ] 127 of 2000 complete in 38.4 sec
[--                6%                  ] 129 of 2000 complete in 39.0 sec
[--                6%                  ] 131 of 2000 complete in 39.6 sec
[--                6%                  ] 133 of 2000 complete in 40.2 sec
[--                6%                  ] 135 of 2000 complete in 40.9 sec
[--                6%                  ] 137 of 2000 complete in 41.7 sec
[--                6%                  ] 139 of 2000 complete in 42.3 sec
[--                7%                  ] 141 of 2000 complete in 42.9 sec
[--                7%                  ] 143 of 2000 complete in 43.5 sec
[--                7%                  ] 145 of 2000 complete in 44.1 sec
[--                7%                  ] 147 of 2000 complete in 44.7 sec
[--                7%                  ] 149 of 2000 complete in 45.4 sec
[--                7%                  ] 151 of 2000 complete in 46.0 sec
[--                7%                  ] 153 of 2000 complete in 46.6 sec
[--                7%                  ] 155 of 2000 complete in 47.2 sec
[--                7%                  ] 157 of 2000 complete in 47.9 sec
[---               7%                  ] 159 of 2000 complete in 48.5 sec
[---               8%                  ] 161 of 2000 complete in 49.1 sec
[---               8%                  ] 163 of 2000 complete in 49.7 sec
[---               8%                  ] 165 of 2000 complete in 50.4 sec
[---               8%                  ] 167 of 2000 complete in 51.0 sec
[---               8%                  ] 169 of 2000 complete in 51.6 sec
[---               8%                  ] 171 of 2000 complete in 52.2 sec
[---               8%                  ] 173 of 2000 complete in 52.8 sec
[---               8%                  ] 175 of 2000 complete in 53.4 sec
[---               8%                  ] 177 of 2000 complete in 54.0 sec
[---               8%                  ] 179 of 2000 complete in 54.5 sec
[---               9%                  ] 181 of 2000 complete in 55.1 sec
[---               9%                  ] 183 of 2000 complete in 55.7 sec
[---               9%                  ] 185 of 2000 complete in 56.3 sec
[---               9%                  ] 187 of 2000 complete in 56.9 sec
[---               9%                  ] 189 of 2000 complete in 57.5 sec
[---               9%                  ] 191 of 2000 complete in 58.1 sec
[---               9%                  ] 193 of 2000 complete in 58.7 sec
[---               9%                  ] 195 of 2000 complete in 59.3 sec
[---               9%                  ] 197 of 2000 complete in 60.0 sec
[---               9%                  ] 199 of 2000 complete in 60.6 sec
[---              10%                  ] 201 of 2000 complete in 61.2 sec
[---              10%                  ] 203 of 2000 complete in 61.8 sec
[---              10%                  ] 205 of 2000 complete in 62.4 sec
[---              10%                  ] 207 of 2000 complete in 63.0 sec
[---              10%                  ] 209 of 2000 complete in 63.6 sec
[----             10%                  ] 211 of 2000 complete in 64.2 sec
[----             10%                  ] 213 of 2000 complete in 64.8 sec
[----             10%                  ] 215 of 2000 complete in 65.4 sec
[----             10%                  ] 217 of 2000 complete in 66.1 sec
[----             10%                  ] 219 of 2000 complete in 66.7 sec
[----             11%                  ] 221 of 2000 complete in 67.3 sec
[----             11%                  ] 223 of 2000 complete in 67.9 sec
[----             11%                  ] 225 of 2000 complete in 68.5 sec
[----             11%                  ] 227 of 2000 complete in 69.2 sec
[----             11%                  ] 229 of 2000 complete in 69.8 sec
[----             11%                  ] 231 of 2000 complete in 70.4 sec
[----             11%                  ] 233 of 2000 complete in 71.1 sec
[----             11%                  ] 235 of 2000 complete in 71.7 sec
[----             11%                  ] 237 of 2000 complete in 72.2 sec
[----             11%                  ] 239 of 2000 complete in 72.8 sec
[----             12%                  ] 241 of 2000 complete in 73.4 sec
[----             12%                  ] 243 of 2000 complete in 74.0 sec
[----             12%                  ] 245 of 2000 complete in 74.6 sec
[----             12%                  ] 247 of 2000 complete in 75.3 sec
[----             12%                  ] 249 of 2000 complete in 75.9 sec
[----             12%                  ] 251 of 2000 complete in 76.5 sec
[----             12%                  ] 253 of 2000 complete in 77.1 sec
[----             12%                  ] 255 of 2000 complete in 77.7 sec
[----             12%                  ] 257 of 2000 complete in 78.3 sec
[----             12%                  ] 259 of 2000 complete in 79.0 sec
[----             13%                  ] 261 of 2000 complete in 79.6 sec
[----             13%                  ] 263 of 2000 complete in 80.2 sec
[-----            13%                  ] 265 of 2000 complete in 80.8 sec
[-----            13%                  ] 267 of 2000 complete in 81.4 sec
[-----            13%                  ] 269 of 2000 complete in 82.0 sec
[-----            13%                  ] 271 of 2000 complete in 82.6 sec
[-----            13%                  ] 273 of 2000 complete in 83.3 sec
[-----            13%                  ] 275 of 2000 complete in 83.9 sec
[-----            13%                  ] 277 of 2000 complete in 84.5 sec
[-----            13%                  ] 279 of 2000 complete in 85.1 sec
[-----            14%                  ] 281 of 2000 complete in 85.7 sec
[-----            14%                  ] 283 of 2000 complete in 86.3 sec
[-----            14%                  ] 285 of 2000 complete in 86.9 sec
[-----            14%                  ] 287 of 2000 complete in 87.6 sec
[-----            14%                  ] 289 of 2000 complete in 88.2 sec
[-----            14%                  ] 291 of 2000 complete in 88.8 sec
[-----            14%                  ] 293 of 2000 complete in 89.4 sec
[-----            14%                  ] 295 of 2000 complete in 90.0 sec
[-----            14%                  ] 297 of 2000 complete in 90.6 sec
[-----            14%                  ] 299 of 2000 complete in 91.3 sec
[-----            15%                  ] 301 of 2000 complete in 91.9 sec

[-                 4%                  ] 85 of 2000 complete in 25.4 sec
[-                 4%                  ] 87 of 2000 complete in 25.9 sec
[-                 4%                  ] 89 of 2000 complete in 26.6 sec
[-                 4%                  ] 91 of 2000 complete in 27.2 sec
[-                 4%                  ] 93 of 2000 complete in 27.8 sec
[-                 4%                  ] 95 of 2000 complete in 28.4 sec
[-                 4%                  ] 97 of 2000 complete in 29.0 sec
[-                 4%                  ] 99 of 2000 complete in 29.6 sec
[-                 5%                  ] 101 of 2000 complete in 30.2 sec
[-                 5%                  ] 103 of 2000 complete in 30.7 sec
[-                 5%                  ] 105 of 2000 complete in 31.4 sec
[--                5%                  ] 107 of 2000 complete in 32.0 sec
[--                5%                  ] 109 of 2000 complete in 32.6 sec
[--                5%                  ] 111 of 2000 complete in 33.2 sec
[--                5%                  ] 113 of 2000 complete in 33.8 sec
[--                5%                  ] 115 of 2000 complete in 34.4 sec
[--                5%                  ] 117 of 2000 complete in 35.1 sec
[--                5%                  ] 119 of 2000 complete in 35.7 sec
[--                6%                  ] 121 of 2000 complete in 36.4 sec
[--                6%                  ] 123 of 2000 complete in 37.0 sec
[--                6%                  ] 125 of 2000 complete in 37.6 sec
[--                6%                  ] 127 of 2000 complete in 38.4 sec
[--                6%                  ] 129 of 2000 complete in 39.0 sec
[--                6%                  ] 131 of 2000 complete in 39.6 sec
[--                6%                  ] 133 of 2000 complete in 40.2 sec
[--                6%                  ] 135 of 2000 complete in 40.9 sec
[--                6%                  ] 137 of 2000 complete in 41.6 sec
[--                6%                  ] 139 of 2000 complete in 42.3 sec
[--                7%                  ] 141 of 2000 complete in 42.9 sec
[--                7%                  ] 143 of 2000 complete in 43.5 sec
[--                7%                  ] 145 of 2000 complete in 44.1 sec
[--                7%                  ] 147 of 2000 complete in 44.7 sec
[--                7%                  ] 149 of 2000 complete in 45.3 sec
[--                7%                  ] 151 of 2000 complete in 45.9 sec
[--                7%                  ] 153 of 2000 complete in 46.6 sec
[--                7%                  ] 155 of 2000 complete in 47.2 sec
[--                7%                  ] 157 of 2000 complete in 47.9 sec
[---               7%                  ] 159 of 2000 complete in 48.6 sec
[---               8%                  ] 161 of 2000 complete in 49.2 sec
[---               8%                  ] 163 of 2000 complete in 49.8 sec
[---               8%                  ] 165 of 2000 complete in 50.4 sec
[---               8%                  ] 167 of 2000 complete in 51.1 sec
[---               8%                  ] 169 of 2000 complete in 51.7 sec
[---               8%                  ] 171 of 2000 complete in 52.3 sec
[---               8%                  ] 173 of 2000 complete in 52.9 sec
[---               8%                  ] 175 of 2000 complete in 53.5 sec
[---               8%                  ] 177 of 2000 complete in 54.1 sec
[---               8%                  ] 179 of 2000 complete in 54.7 sec
[---               9%                  ] 181 of 2000 complete in 55.3 sec
[---               9%                  ] 183 of 2000 complete in 55.9 sec
[---               9%                  ] 185 of 2000 complete in 56.5 sec
[---               9%                  ] 187 of 2000 complete in 57.1 sec
[---               9%                  ] 189 of 2000 complete in 57.7 sec
[---               9%                  ] 191 of 2000 complete in 58.2 sec
[---               9%                  ] 193 of 2000 complete in 58.9 sec
[---               9%                  ] 195 of 2000 complete in 59.5 sec
[---               9%                  ] 197 of 2000 complete in 60.1 sec
[---               9%                  ] 199 of 2000 complete in 60.7 sec
[---              10%                  ] 201 of 2000 complete in 61.3 sec
[---              10%                  ] 203 of 2000 complete in 61.9 sec
[---              10%                  ] 205 of 2000 complete in 62.5 sec
[---              10%                  ] 207 of 2000 complete in 63.1 sec
[---              10%                  ] 209 of 2000 complete in 63.6 sec
[----             10%                  ] 211 of 2000 complete in 64.3 sec
[----             10%                  ] 213 of 2000 complete in 64.8 sec
[----             10%                  ] 215 of 2000 complete in 65.5 sec
[----             10%                  ] 217 of 2000 complete in 66.1 sec
[----             10%                  ] 219 of 2000 complete in 66.7 sec
[----             11%                  ] 221 of 2000 complete in 67.3 sec
[----             11%                  ] 223 of 2000 complete in 67.9 sec
[----             11%                  ] 225 of 2000 complete in 68.5 sec
[----             11%                  ] 227 of 2000 complete in 69.2 sec
[----             11%                  ] 229 of 2000 complete in 69.8 sec
[----             11%                  ] 231 of 2000 complete in 70.4 sec
[----             11%                  ] 233 of 2000 complete in 71.0 sec
[----             11%                  ] 235 of 2000 complete in 71.7 sec
[----             11%                  ] 237 of 2000 complete in 72.2 sec
[----             11%                  ] 239 of 2000 complete in 72.8 sec
[----             12%                  ] 241 of 2000 complete in 73.4 sec
[----             12%                  ] 243 of 2000 complete in 74.0 sec
[----             12%                  ] 245 of 2000 complete in 74.6 sec
[----             12%                  ] 247 of 2000 complete in 75.2 sec
[----             12%                  ] 249 of 2000 complete in 75.8 sec
[----             12%                  ] 251 of 2000 complete in 76.4 sec
[----             12%                  ] 253 of 2000 complete in 77.0 sec
[----             12%                  ] 255 of 2000 complete in 77.6 sec
[----             12%                  ] 257 of 2000 complete in 78.2 sec
[----             12%                  ] 259 of 2000 complete in 78.8 sec
[----             13%                  ] 261 of 2000 complete in 79.4 sec
[----             13%                  ] 263 of 2000 complete in 80.1 sec
[-----            13%                  ] 265 of 2000 complete in 80.7 sec
[-----            13%                  ] 267 of 2000 complete in 81.3 sec
[-----            13%                  ] 269 of 2000 complete in 81.9 sec
[-----            13%                  ] 271 of 2000 complete in 82.5 sec
[-----            13%                  ] 273 of 2000 complete in 83.1 sec
[-----            13%                  ] 275 of 2000 complete in 83.8 sec
[-----            13%                  ] 277 of 2000 complete in 84.4 sec
[-----            13%                  ] 279 of 2000 complete in 85.0 sec
[-----            14%                  ] 281 of 2000 complete in 85.7 sec
[-----            14%                  ] 283 of 2000 complete in 86.3 sec
[-----            14%                  ] 285 of 2000 complete in 86.9 sec
[-----            14%                  ] 287 of 2000 complete in 87.5 sec
[-----            14%                  ] 289 of 2000 complete in 88.1 sec
[-----            14%                  ] 291 of 2000 complete in 88.7 sec
[-----            14%                  ] 293 of 2000 complete in 89.4 sec
[-----            14%                  ] 295 of 2000 complete in 90.0 sec
[-----            14%                  ] 297 of 2000 complete in 90.6 sec
[-----            14%                  ] 299 of 2000 complete in 91.3 sec
[-----            15%                  ] 301 of 2000 complete in 91.9 sec
[-----            15%                  ] 303 of 2000 complete in 92.5 sec
[-                 4%                  ] 85 of 2000 complete in 25.5 sec
[-                 4%                  ] 87 of 2000 complete in 26.0 sec
[-                 4%                  ] 89 of 2000 complete in 26.7 sec
[-                 4%                  ] 91 of 2000 complete in 27.2 sec
[-                 4%                  ] 93 of 2000 complete in 27.8 sec
[-                 4%                  ] 95 of 2000 complete in 28.4 sec
[-                 4%                  ] 97 of 2000 complete in 29.0 sec
[-                 4%                  ] 99 of 2000 complete in 29.6 sec
[-                 5%                  ] 101 of 2000 complete in 30.3 sec
[-                 5%                  ] 103 of 2000 complete in 30.9 sec
[-                 5%                  ] 105 of 2000 complete in 31.5 sec
[--                5%                  ] 107 of 2000 complete in 32.2 sec
[--                5%                  ] 109 of 2000 complete in 32.8 sec
[--                5%                  ] 111 of 2000 complete in 33.4 sec
[--                5%                  ] 113 of 2000 complete in 34.0 sec
[--                5%                  ] 115 of 2000 complete in 34.6 sec
[--                5%                  ] 117 of 2000 complete in 35.3 sec
[--                5%                  ] 119 of 2000 complete in 35.9 sec
[--                6%                  ] 121 of 2000 complete in 36.6 sec
[--                6%                  ] 123 of 2000 complete in 37.2 sec
[--                6%                  ] 125 of 2000 complete in 37.8 sec
[--                6%                  ] 127 of 2000 complete in 38.6 sec
[--                6%                  ] 129 of 2000 complete in 39.2 sec
[--                6%                  ] 131 of 2000 complete in 39.8 sec
[--                6%                  ] 133 of 2000 complete in 40.4 sec
[--                6%                  ] 135 of 2000 complete in 41.2 sec
[--                6%                  ] 137 of 2000 complete in 41.9 sec
[--                6%                  ] 139 of 2000 complete in 42.5 sec
[--                7%                  ] 141 of 2000 complete in 43.1 sec
[--                7%                  ] 143 of 2000 complete in 43.7 sec
[--                7%                  ] 145 of 2000 complete in 44.3 sec
[--                7%                  ] 147 of 2000 complete in 44.9 sec
[--                7%                  ] 149 of 2000 complete in 45.6 sec
[--                7%                  ] 151 of 2000 complete in 46.2 sec
[--                7%                  ] 153 of 2000 complete in 46.8 sec
[--                7%                  ] 155 of 2000 complete in 47.5 sec
[--                7%                  ] 157 of 2000 complete in 48.1 sec
[---               7%                  ] 159 of 2000 complete in 48.8 sec
[---               8%                  ] 161 of 2000 complete in 49.4 sec
[---               8%                  ] 163 of 2000 complete in 50.0 sec
[---               8%                  ] 165 of 2000 complete in 50.6 sec
[---               8%                  ] 167 of 2000 complete in 51.3 sec
[---               8%                  ] 169 of 2000 complete in 51.9 sec
[---               8%                  ] 171 of 2000 complete in 52.5 sec
[---               8%                  ] 173 of 2000 complete in 53.1 sec
[---               8%                  ] 175 of 2000 complete in 53.7 sec
[---               8%                  ] 177 of 2000 complete in 54.2 sec
[---               8%                  ] 179 of 2000 complete in 54.8 sec
[---               9%                  ] 181 of 2000 complete in 55.5 sec
[---               9%                  ] 183 of 2000 complete in 56.1 sec
[---               9%                  ] 185 of 2000 complete in 56.6 sec
[---               9%                  ] 187 of 2000 complete in 57.2 sec
[---               9%                  ] 189 of 2000 complete in 57.8 sec
[---               9%                  ] 191 of 2000 complete in 58.4 sec
[---               9%                  ] 193 of 2000 complete in 59.0 sec
[---               9%                  ] 195 of 2000 complete in 59.7 sec
[---               9%                  ] 197 of 2000 complete in 60.3 sec
[---               9%                  ] 199 of 2000 complete in 60.9 sec
[---              10%                  ] 201 of 2000 complete in 61.5 sec
[---              10%                  ] 203 of 2000 complete in 62.1 sec
[---              10%                  ] 205 of 2000 complete in 62.7 sec
[---              10%                  ] 207 of 2000 complete in 63.3 sec
[---              10%                  ] 209 of 2000 complete in 63.9 sec
[----             10%                  ] 211 of 2000 complete in 64.5 sec
[----             10%                  ] 213 of 2000 complete in 65.1 sec
[----             10%                  ] 215 of 2000 complete in 65.7 sec
[----             10%                  ] 217 of 2000 complete in 66.3 sec
[----             10%                  ] 219 of 2000 complete in 66.9 sec
[----             11%                  ] 221 of 2000 complete in 67.5 sec
[----             11%                  ] 223 of 2000 complete in 68.2 sec
[----             11%                  ] 225 of 2000 complete in 68.8 sec
[----             11%                  ] 227 of 2000 complete in 69.5 sec
[----             11%                  ] 229 of 2000 complete in 70.1 sec
[----             11%                  ] 231 of 2000 complete in 70.8 sec
[----             11%                  ] 233 of 2000 complete in 71.4 sec
[----             11%                  ] 235 of 2000 complete in 72.0 sec
[----             11%                  ] 237 of 2000 complete in 72.6 sec
[----             11%                  ] 239 of 2000 complete in 73.2 sec
[----             12%                  ] 241 of 2000 complete in 73.8 sec
[----             12%                  ] 243 of 2000 complete in 74.4 sec
[----             12%                  ] 245 of 2000 complete in 75.0 sec
[----             12%                  ] 247 of 2000 complete in 75.6 sec
[----             12%                  ] 249 of 2000 complete in 76.2 sec
[----             12%                  ] 251 of 2000 complete in 76.8 sec
[----             12%                  ] 253 of 2000 complete in 77.4 sec
[----             12%                  ] 255 of 2000 complete in 78.1 sec
[----             12%                  ] 257 of 2000 complete in 78.7 sec
[----             12%                  ] 259 of 2000 complete in 79.3 sec
[----             13%                  ] 261 of 2000 complete in 79.9 sec
[----             13%                  ] 263 of 2000 complete in 80.5 sec
[-----            13%                  ] 265 of 2000 complete in 81.2 sec
[-----            13%                  ] 267 of 2000 complete in 81.8 sec
[-----            13%                  ] 269 of 2000 complete in 82.4 sec
[-----            13%                  ] 271 of 2000 complete in 83.0 sec
[-----            13%                  ] 273 of 2000 complete in 83.6 sec
[-----            13%                  ] 275 of 2000 complete in 84.2 sec
[-----            13%                  ] 277 of 2000 complete in 84.8 sec
[-----            13%                  ] 279 of 2000 complete in 85.4 sec
[-----            14%                  ] 281 of 2000 complete in 86.1 sec
[-----            14%                  ] 283 of 2000 complete in 86.7 sec
[-----            14%                  ] 285 of 2000 complete in 87.3 sec
[-----            14%                  ] 287 of 2000 complete in 87.9 sec
[-----            14%                  ] 289 of 2000 complete in 88.5 sec
[-----            14%                  ] 291 of 2000 complete in 89.1 sec
[-----            14%                  ] 293 of 2000 complete in 89.7 sec
[-----            14%                  ] 295 of 2000 complete in 90.4 sec
[-----            14%                  ] 297 of 2000 complete in 91.0 sec
[-----            14%                  ] 299 of 2000 complete in 91.6 sec
[-----            15%                  ] 301 of 2000 complete in 92.2 sec
[-----            15%                  ] 303 of 2000 complete in 92.9 sec

[-----            15%                  ] 305 of 2000 complete in 92.1 sec
[-----            15%                  ] 307 of 2000 complete in 92.7 sec
[-----            15%                  ] 309 of 2000 complete in 93.3 sec
[-----            15%                  ] 311 of 2000 complete in 94.0 sec
[-----            15%                  ] 313 of 2000 complete in 94.6 sec
[-----            15%                  ] 315 of 2000 complete in 95.2 sec
[------           15%                  ] 317 of 2000 complete in 95.8 sec
[------           15%                  ] 319 of 2000 complete in 96.4 sec
[------           16%                  ] 321 of 2000 complete in 97.0 sec
[------           16%                  ] 323 of 2000 complete in 97.6 sec
[------           16%                  ] 325 of 2000 complete in 98.3 sec
[------           16%                  ] 327 of 2000 complete in 98.9 sec
[------           16%                  ] 329 of 2000 complete in 99.5 sec
[------           16%                  ] 331 of 2000 complete in 100.1 sec
[------           16%                  ] 333 of 2000 complete in 100.7 sec
[------           16%                  ] 335 of 2000 complete in 101.3 sec
[------           16%                  ] 337 of 2000 complete in 101.9 sec
[------           16%                  ] 339 of 2000 complete in 102.5 sec
[------           17%                  ] 341 of 2000 complete in 103.2 sec
[------           17%                  ] 343 of 2000 complete in 103.8 sec
[------           17%                  ] 345 of 2000 complete in 104.4 sec
[------           17%                  ] 347 of 2000 complete in 105.0 sec
[------           17%                  ] 349 of 2000 complete in 105.6 sec
[------           17%                  ] 351 of 2000 complete in 106.2 sec
[------           17%                  ] 353 of 2000 complete in 106.8 sec
[------           17%                  ] 355 of 2000 complete in 107.4 sec
[------           17%                  ] 357 of 2000 complete in 108.0 sec
[------           17%                  ] 359 of 2000 complete in 108.6 sec
[------           18%                  ] 361 of 2000 complete in 109.2 sec
[------           18%                  ] 363 of 2000 complete in 109.8 sec
[------           18%                  ] 365 of 2000 complete in 110.4 sec
[------           18%                  ] 367 of 2000 complete in 111.1 sec
[-------          18%                  ] 369 of 2000 complete in 111.7 sec
[-------          18%                  ] 371 of 2000 complete in 112.3 sec
[-------          18%                  ] 373 of 2000 complete in 112.9 sec
[-------          18%                  ] 375 of 2000 complete in 113.5 sec
[-------          18%                  ] 377 of 2000 complete in 114.1 sec
[-------          18%                  ] 379 of 2000 complete in 114.7 sec
[-------          19%                  ] 381 of 2000 complete in 115.3 sec
[-------          19%                  ] 383 of 2000 complete in 115.9 sec
[-------          19%                  ] 385 of 2000 complete in 116.5 sec
[-------          19%                  ] 387 of 2000 complete in 117.1 sec
[-------          19%                  ] 389 of 2000 complete in 117.7 sec
[-------          19%                  ] 391 of 2000 complete in 118.3 sec
[-------          19%                  ] 393 of 2000 complete in 118.9 sec
[-------          19%                  ] 395 of 2000 complete in 119.5 sec
[-------          19%                  ] 397 of 2000 complete in 120.2 sec
[-------          19%                  ] 399 of 2000 complete in 120.8 sec
[-------          20%                  ] 401 of 2000 complete in 121.4 sec
[-------          20%                  ] 403 of 2000 complete in 122.0 sec
[-------          20%                  ] 405 of 2000 complete in 122.6 sec
[-------          20%                  ] 407 of 2000 complete in 123.2 sec
[-------          20%                  ] 409 of 2000 complete in 123.8 sec
[-------          20%                  ] 411 of 2000 complete in 124.5 sec
[-------          20%                  ] 413 of 2000 complete in 125.1 sec
[-------          20%                  ] 415 of 2000 complete in 125.7 sec
[-------          20%                  ] 417 of 2000 complete in 126.3 sec
[-------          20%                  ] 419 of 2000 complete in 126.9 sec
[-------          21%                  ] 421 of 2000 complete in 127.5 sec
[--------         21%                  ] 423 of 2000 complete in 128.1 sec
[--------         21%                  ] 425 of 2000 complete in 128.7 sec
[--------         21%                  ] 427 of 2000 complete in 129.4 sec
[--------         21%                  ] 429 of 2000 complete in 130.0 sec
[--------         21%                  ] 431 of 2000 complete in 130.6 sec
[--------         21%                  ] 433 of 2000 complete in 131.2 sec
[--------         21%                  ] 435 of 2000 complete in 131.8 sec
[--------         21%                  ] 437 of 2000 complete in 132.5 sec
[--------         21%                  ] 439 of 2000 complete in 133.1 sec
[--------         22%                  ] 441 of 2000 complete in 133.7 sec
[--------         22%                  ] 443 of 2000 complete in 134.3 sec
[--------         22%                  ] 445 of 2000 complete in 134.9 sec
[--------         22%                  ] 447 of 2000 complete in 135.5 sec
[--------         22%                  ] 449 of 2000 complete in 136.1 sec
[--------         22%                  ] 451 of 2000 complete in 136.7 sec
[--------         22%                  ] 453 of 2000 complete in 137.3 sec
[--------         22%                  ] 455 of 2000 complete in 137.9 sec
[--------         22%                  ] 457 of 2000 complete in 138.5 sec
[--------         22%                  ] 459 of 2000 complete in 139.1 sec
[--------         23%                  ] 461 of 2000 complete in 139.7 sec
[--------         23%                  ] 463 of 2000 complete in 140.4 sec
[--------         23%                  ] 465 of 2000 complete in 141.0 sec
[--------         23%                  ] 467 of 2000 complete in 141.6 sec
[--------         23%                  ] 469 of 2000 complete in 142.2 sec
[--------         23%                  ] 471 of 2000 complete in 142.8 sec
[--------         23%                  ] 473 of 2000 complete in 143.4 sec
[---------        23%                  ] 475 of 2000 complete in 144.1 sec
[---------        23%                  ] 477 of 2000 complete in 144.7 sec
[---------        23%                  ] 479 of 2000 complete in 145.3 sec
[---------        24%                  ] 481 of 2000 complete in 146.0 sec
[---------        24%                  ] 483 of 2000 complete in 146.6 sec
[---------        24%                  ] 485 of 2000 complete in 147.2 sec
[---------        24%                  ] 487 of 2000 complete in 147.8 sec
[---------        24%                  ] 489 of 2000 complete in 148.5 sec
[---------        24%                  ] 491 of 2000 complete in 149.1 sec
[---------        24%                  ] 493 of 2000 complete in 149.7 sec
[---------        24%                  ] 495 of 2000 complete in 150.3 sec
[---------        24%                  ] 497 of 2000 complete in 150.9 sec
[---------        24%                  ] 499 of 2000 complete in 151.5 sec
[---------        25%                  ] 501 of 2000 complete in 152.1 sec
[---------        25%                  ] 503 of 2000 complete in 152.7 sec
[---------        25%                  ] 505 of 2000 complete in 153.4 sec
[---------        25%                  ] 507 of 2000 complete in 154.0 sec
[---------        25%                  ] 509 of 2000 complete in 154.6 sec
[---------        25%                  ] 511 of 2000 complete in 155.3 sec
[---------        25%                  ] 513 of 2000 complete in 155.9 sec
[---------        25%                  ] 515 of 2000 complete in 156.5 sec
[---------        25%                  ] 517 of 2000 complete in 157.2 sec
[---------        25%                  ] 519 of 2000 complete in 157.8 sec
[---------        26%                  ] 521 of 2000 complete in 158.4 sec
[-----            15%                  ] 303 of 2000 complete in 92.5 sec
[-----            15%                  ] 305 of 2000 complete in 93.2 sec
[-----            15%                  ] 307 of 2000 complete in 93.8 sec
[-----            15%                  ] 309 of 2000 complete in 94.4 sec
[-----            15%                  ] 311 of 2000 complete in 95.1 sec
[-----            15%                  ] 313 of 2000 complete in 95.7 sec
[-----            15%                  ] 315 of 2000 complete in 96.4 sec
[------           15%                  ] 317 of 2000 complete in 97.0 sec
[------           15%                  ] 319 of 2000 complete in 97.6 sec
[------           16%                  ] 321 of 2000 complete in 98.2 sec
[------           16%                  ] 323 of 2000 complete in 98.8 sec
[------           16%                  ] 325 of 2000 complete in 99.5 sec
[------           16%                  ] 327 of 2000 complete in 100.1 sec
[------           16%                  ] 329 of 2000 complete in 100.7 sec
[------           16%                  ] 331 of 2000 complete in 101.3 sec
[------           16%                  ] 333 of 2000 complete in 101.9 sec
[------           16%                  ] 335 of 2000 complete in 102.6 sec
[------           16%                  ] 337 of 2000 complete in 103.1 sec
[------           16%                  ] 339 of 2000 complete in 103.8 sec
[------           17%                  ] 341 of 2000 complete in 104.4 sec
[------           17%                  ] 343 of 2000 complete in 105.0 sec
[------           17%                  ] 345 of 2000 complete in 105.7 sec
[------           17%                  ] 347 of 2000 complete in 106.3 sec
[------           17%                  ] 349 of 2000 complete in 106.9 sec
[------           17%                  ] 351 of 2000 complete in 107.5 sec
[------           17%                  ] 353 of 2000 complete in 108.1 sec
[------           17%                  ] 355 of 2000 complete in 108.7 sec
[------           17%                  ] 357 of 2000 complete in 109.3 sec
[------           17%                  ] 359 of 2000 complete in 109.9 sec
[------           18%                  ] 361 of 2000 complete in 110.6 sec
[------           18%                  ] 363 of 2000 complete in 111.2 sec
[------           18%                  ] 365 of 2000 complete in 111.8 sec
[------           18%                  ] 367 of 2000 complete in 112.4 sec
[-------          18%                  ] 369 of 2000 complete in 113.0 sec
[-------          18%                  ] 371 of 2000 complete in 113.7 sec
[-------          18%                  ] 373 of 2000 complete in 114.3 sec
[-------          18%                  ] 375 of 2000 complete in 114.9 sec
[-------          18%                  ] 377 of 2000 complete in 115.5 sec
[-------          18%                  ] 379 of 2000 complete in 116.2 sec
[-------          19%                  ] 381 of 2000 complete in 116.8 sec
[-------          19%                  ] 383 of 2000 complete in 117.4 sec
[-------          19%                  ] 385 of 2000 complete in 118.0 sec
[-------          19%                  ] 387 of 2000 complete in 118.6 sec
[-------          19%                  ] 389 of 2000 complete in 119.2 sec
[-------          19%                  ] 391 of 2000 complete in 119.9 sec
[-------          19%                  ] 393 of 2000 complete in 120.5 sec
[-------          19%                  ] 395 of 2000 complete in 121.1 sec
[-------          19%                  ] 397 of 2000 complete in 121.7 sec
[-------          19%                  ] 399 of 2000 complete in 122.3 sec
[-------          20%                  ] 401 of 2000 complete in 122.9 sec
[-------          20%                  ] 403 of 2000 complete in 123.6 sec
[-------          20%                  ] 405 of 2000 complete in 124.2 sec
[-------          20%                  ] 407 of 2000 complete in 124.9 sec
[-------          20%                  ] 409 of 2000 complete in 125.5 sec
[-------          20%                  ] 411 of 2000 complete in 126.1 sec
[-------          20%                  ] 413 of 2000 complete in 126.7 sec
[-------          20%                  ] 415 of 2000 complete in 127.3 sec
[-------          20%                  ] 417 of 2000 complete in 127.9 sec
[-------          20%                  ] 419 of 2000 complete in 128.6 sec
[-------          21%                  ] 421 of 2000 complete in 129.2 sec
[--------         21%                  ] 423 of 2000 complete in 129.8 sec
[--------         21%                  ] 425 of 2000 complete in 130.4 sec
[--------         21%                  ] 427 of 2000 complete in 131.0 sec
[--------         21%                  ] 429 of 2000 complete in 131.7 sec
[--------         21%                  ] 431 of 2000 complete in 132.3 sec
[--------         21%                  ] 433 of 2000 complete in 132.9 sec
[--------         21%                  ] 435 of 2000 complete in 133.5 sec
[--------         21%                  ] 437 of 2000 complete in 134.1 sec
[--------         21%                  ] 439 of 2000 complete in 134.8 sec
[--------         22%                  ] 441 of 2000 complete in 135.4 sec
[--------         22%                  ] 443 of 2000 complete in 136.0 sec
[--------         22%                  ] 445 of 2000 complete in 136.7 sec
[--------         22%                  ] 447 of 2000 complete in 137.3 sec
[--------         22%                  ] 449 of 2000 complete in 137.9 sec
[--------         22%                  ] 451 of 2000 complete in 138.5 sec
[--------         22%                  ] 453 of 2000 complete in 139.1 sec
[--------         22%                  ] 455 of 2000 complete in 139.8 sec
[--------         22%                  ] 457 of 2000 complete in 140.4 sec
[--------         22%                  ] 459 of 2000 complete in 141.0 sec
[--------         23%                  ] 461 of 2000 complete in 141.7 sec
[--------         23%                  ] 463 of 2000 complete in 142.3 sec
[--------         23%                  ] 465 of 2000 complete in 142.9 sec
[--------         23%                  ] 467 of 2000 complete in 143.5 sec
[--------         23%                  ] 469 of 2000 complete in 144.1 sec
[--------         23%                  ] 471 of 2000 complete in 144.7 sec
[--------         23%                  ] 473 of 2000 complete in 145.4 sec
[---------        23%                  ] 475 of 2000 complete in 146.1 sec
[---------        23%                  ] 477 of 2000 complete in 146.7 sec
[---------        23%                  ] 479 of 2000 complete in 147.3 sec
[---------        24%                  ] 481 of 2000 complete in 148.0 sec
[---------        24%                  ] 483 of 2000 complete in 148.6 sec
[---------        24%                  ] 485 of 2000 complete in 149.2 sec
[---------        24%                  ] 487 of 2000 complete in 149.8 sec
[---------        24%                  ] 489 of 2000 complete in 150.5 sec
[---------        24%                  ] 491 of 2000 complete in 151.1 sec
[---------        24%                  ] 493 of 2000 complete in 151.7 sec
[---------        24%                  ] 495 of 2000 complete in 152.4 sec
[---------        24%                  ] 497 of 2000 complete in 153.0 sec
[---------        24%                  ] 499 of 2000 complete in 153.6 sec
[---------        25%                  ] 501 of 2000 complete in 154.3 sec
[---------        25%                  ] 503 of 2000 complete in 154.9 sec
[---------        25%                  ] 505 of 2000 complete in 155.5 sec
[---------        25%                  ] 507 of 2000 complete in 156.2 sec
[---------        25%                  ] 509 of 2000 complete in 156.8 sec
[---------        25%                  ] 511 of 2000 complete in 157.4 sec
[---------        25%                  ] 513 of 2000 complete in 158.1 sec
[---------        25%                  ] 515 of 2000 complete in 158.7 sec
[---------        25%                  ] 517 of 2000 complete in 159.4 sec
[---------        25%                  ] 519 of 2000 complete in 160.0 sec

[-----            15%                  ] 305 of 2000 complete in 93.1 sec
[-----            15%                  ] 307 of 2000 complete in 93.7 sec
[-----            15%                  ] 309 of 2000 complete in 94.3 sec
[-----            15%                  ] 311 of 2000 complete in 95.0 sec
[-----            15%                  ] 313 of 2000 complete in 95.6 sec
[-----            15%                  ] 315 of 2000 complete in 96.2 sec
[------           15%                  ] 317 of 2000 complete in 96.8 sec
[------           15%                  ] 319 of 2000 complete in 97.4 sec
[------           16%                  ] 321 of 2000 complete in 98.1 sec
[------           16%                  ] 323 of 2000 complete in 98.7 sec
[------           16%                  ] 325 of 2000 complete in 99.3 sec
[------           16%                  ] 327 of 2000 complete in 99.9 sec
[------           16%                  ] 329 of 2000 complete in 100.5 sec
[------           16%                  ] 331 of 2000 complete in 101.1 sec
[------           16%                  ] 333 of 2000 complete in 101.8 sec
[------           16%                  ] 335 of 2000 complete in 102.4 sec
[------           16%                  ] 337 of 2000 complete in 103.0 sec
[------           16%                  ] 339 of 2000 complete in 103.6 sec
[------           17%                  ] 341 of 2000 complete in 104.3 sec
[------           17%                  ] 343 of 2000 complete in 104.9 sec
[------           17%                  ] 345 of 2000 complete in 105.5 sec
[------           17%                  ] 347 of 2000 complete in 106.1 sec
[------           17%                  ] 349 of 2000 complete in 106.7 sec
[------           17%                  ] 351 of 2000 complete in 107.3 sec
[------           17%                  ] 353 of 2000 complete in 108.0 sec
[------           17%                  ] 355 of 2000 complete in 108.6 sec
[------           17%                  ] 357 of 2000 complete in 109.2 sec
[------           17%                  ] 359 of 2000 complete in 109.8 sec
[------           18%                  ] 361 of 2000 complete in 110.4 sec
[------           18%                  ] 363 of 2000 complete in 111.0 sec
[------           18%                  ] 365 of 2000 complete in 111.7 sec
[------           18%                  ] 367 of 2000 complete in 112.3 sec
[-------          18%                  ] 369 of 2000 complete in 112.9 sec
[-------          18%                  ] 371 of 2000 complete in 113.5 sec
[-------          18%                  ] 373 of 2000 complete in 114.2 sec
[-------          18%                  ] 375 of 2000 complete in 114.8 sec
[-------          18%                  ] 377 of 2000 complete in 115.4 sec
[-------          18%                  ] 379 of 2000 complete in 116.0 sec
[-------          19%                  ] 381 of 2000 complete in 116.6 sec
[-------          19%                  ] 383 of 2000 complete in 117.2 sec
[-------          19%                  ] 385 of 2000 complete in 117.8 sec
[-------          19%                  ] 387 of 2000 complete in 118.4 sec
[-------          19%                  ] 389 of 2000 complete in 119.0 sec
[-------          19%                  ] 391 of 2000 complete in 119.6 sec
[-------          19%                  ] 393 of 2000 complete in 120.2 sec
[-------          19%                  ] 395 of 2000 complete in 120.9 sec
[-------          19%                  ] 397 of 2000 complete in 121.5 sec
[-------          19%                  ] 399 of 2000 complete in 122.1 sec
[-------          20%                  ] 401 of 2000 complete in 122.8 sec
[-------          20%                  ] 403 of 2000 complete in 123.4 sec
[-------          20%                  ] 405 of 2000 complete in 124.0 sec
[-------          20%                  ] 407 of 2000 complete in 124.6 sec
[-------          20%                  ] 409 of 2000 complete in 125.3 sec
[-------          20%                  ] 411 of 2000 complete in 125.9 sec
[-------          20%                  ] 413 of 2000 complete in 126.5 sec
[-------          20%                  ] 415 of 2000 complete in 127.1 sec
[-------          20%                  ] 417 of 2000 complete in 127.7 sec
[-------          20%                  ] 419 of 2000 complete in 128.4 sec
[-------          21%                  ] 421 of 2000 complete in 129.0 sec
[--------         21%                  ] 423 of 2000 complete in 129.6 sec
[--------         21%                  ] 425 of 2000 complete in 130.2 sec
[--------         21%                  ] 427 of 2000 complete in 130.8 sec
[--------         21%                  ] 429 of 2000 complete in 131.5 sec
[--------         21%                  ] 431 of 2000 complete in 132.1 sec
[--------         21%                  ] 433 of 2000 complete in 132.7 sec
[--------         21%                  ] 435 of 2000 complete in 133.3 sec
[--------         21%                  ] 437 of 2000 complete in 133.9 sec
[--------         21%                  ] 439 of 2000 complete in 134.6 sec
[--------         22%                  ] 441 of 2000 complete in 135.2 sec
[--------         22%                  ] 443 of 2000 complete in 135.8 sec
[--------         22%                  ] 445 of 2000 complete in 136.4 sec
[--------         22%                  ] 447 of 2000 complete in 137.0 sec
[--------         22%                  ] 449 of 2000 complete in 137.6 sec
[--------         22%                  ] 451 of 2000 complete in 138.2 sec
[--------         22%                  ] 453 of 2000 complete in 138.9 sec
[--------         22%                  ] 455 of 2000 complete in 139.5 sec
[--------         22%                  ] 457 of 2000 complete in 140.1 sec
[--------         22%                  ] 459 of 2000 complete in 140.7 sec
[--------         23%                  ] 461 of 2000 complete in 141.3 sec
[--------         23%                  ] 463 of 2000 complete in 141.9 sec
[--------         23%                  ] 465 of 2000 complete in 142.6 sec
[--------         23%                  ] 467 of 2000 complete in 143.2 sec
[--------         23%                  ] 469 of 2000 complete in 143.8 sec
[--------         23%                  ] 471 of 2000 complete in 144.5 sec
[--------         23%                  ] 473 of 2000 complete in 145.1 sec
[---------        23%                  ] 475 of 2000 complete in 145.8 sec
[---------        23%                  ] 477 of 2000 complete in 146.4 sec
[---------        23%                  ] 479 of 2000 complete in 147.1 sec
[---------        24%                  ] 481 of 2000 complete in 147.7 sec
[---------        24%                  ] 483 of 2000 complete in 148.4 sec
[---------        24%                  ] 485 of 2000 complete in 149.0 sec
[---------        24%                  ] 487 of 2000 complete in 149.6 sec
[---------        24%                  ] 489 of 2000 complete in 150.2 sec
[---------        24%                  ] 491 of 2000 complete in 150.9 sec
[---------        24%                  ] 493 of 2000 complete in 151.5 sec
[---------        24%                  ] 495 of 2000 complete in 152.1 sec
[---------        24%                  ] 497 of 2000 complete in 152.7 sec
[---------        24%                  ] 499 of 2000 complete in 153.3 sec
[---------        25%                  ] 501 of 2000 complete in 153.9 sec
[---------        25%                  ] 503 of 2000 complete in 154.6 sec
[---------        25%                  ] 505 of 2000 complete in 155.2 sec
[---------        25%                  ] 507 of 2000 complete in 155.9 sec
[---------        25%                  ] 509 of 2000 complete in 156.5 sec
[---------        25%                  ] 511 of 2000 complete in 157.1 sec
[---------        25%                  ] 513 of 2000 complete in 157.8 sec
[---------        25%                  ] 515 of 2000 complete in 158.4 sec
[---------        25%                  ] 517 of 2000 complete in 159.1 sec
[---------        25%                  ] 519 of 2000 complete in 159.7 sec
[---------        26%                  ] 521 of 2000 complete in 160.3 sec
[-----            15%                  ] 305 of 2000 complete in 93.5 sec
[-----            15%                  ] 307 of 2000 complete in 94.1 sec
[-----            15%                  ] 309 of 2000 complete in 94.7 sec
[-----            15%                  ] 311 of 2000 complete in 95.4 sec
[-----            15%                  ] 313 of 2000 complete in 96.0 sec
[-----            15%                  ] 315 of 2000 complete in 96.6 sec
[------           15%                  ] 317 of 2000 complete in 97.2 sec
[------           15%                  ] 319 of 2000 complete in 97.9 sec
[------           16%                  ] 321 of 2000 complete in 98.5 sec
[------           16%                  ] 323 of 2000 complete in 99.1 sec
[------           16%                  ] 325 of 2000 complete in 99.7 sec
[------           16%                  ] 327 of 2000 complete in 100.3 sec
[------           16%                  ] 329 of 2000 complete in 100.9 sec
[------           16%                  ] 331 of 2000 complete in 101.6 sec
[------           16%                  ] 333 of 2000 complete in 102.2 sec
[------           16%                  ] 335 of 2000 complete in 102.8 sec
[------           16%                  ] 337 of 2000 complete in 103.4 sec
[------           16%                  ] 339 of 2000 complete in 104.0 sec
[------           17%                  ] 341 of 2000 complete in 104.7 sec
[------           17%                  ] 343 of 2000 complete in 105.3 sec
[------           17%                  ] 345 of 2000 complete in 105.9 sec
[------           17%                  ] 347 of 2000 complete in 106.5 sec
[------           17%                  ] 349 of 2000 complete in 107.1 sec
[------           17%                  ] 351 of 2000 complete in 107.7 sec
[------           17%                  ] 353 of 2000 complete in 108.4 sec
[------           17%                  ] 355 of 2000 complete in 109.0 sec
[------           17%                  ] 357 of 2000 complete in 109.6 sec
[------           17%                  ] 359 of 2000 complete in 110.3 sec
[------           18%                  ] 361 of 2000 complete in 110.9 sec
[------           18%                  ] 363 of 2000 complete in 111.5 sec
[------           18%                  ] 365 of 2000 complete in 112.1 sec
[------           18%                  ] 367 of 2000 complete in 112.7 sec
[-------          18%                  ] 369 of 2000 complete in 113.3 sec
[-------          18%                  ] 371 of 2000 complete in 113.9 sec
[-------          18%                  ] 373 of 2000 complete in 114.6 sec
[-------          18%                  ] 375 of 2000 complete in 115.2 sec
[-------          18%                  ] 377 of 2000 complete in 115.8 sec
[-------          18%                  ] 379 of 2000 complete in 116.4 sec
[-------          19%                  ] 381 of 2000 complete in 117.1 sec
[-------          19%                  ] 383 of 2000 complete in 117.7 sec
[-------          19%                  ] 385 of 2000 complete in 118.3 sec
[-------          19%                  ] 387 of 2000 complete in 119.0 sec
[-------          19%                  ] 389 of 2000 complete in 119.6 sec
[-------          19%                  ] 391 of 2000 complete in 120.2 sec
[-------          19%                  ] 393 of 2000 complete in 120.8 sec
[-------          19%                  ] 395 of 2000 complete in 121.4 sec
[-------          19%                  ] 397 of 2000 complete in 122.0 sec
[-------          19%                  ] 399 of 2000 complete in 122.6 sec
[-------          20%                  ] 401 of 2000 complete in 123.2 sec
[-------          20%                  ] 403 of 2000 complete in 123.9 sec
[-------          20%                  ] 405 of 2000 complete in 124.5 sec
[-------          20%                  ] 407 of 2000 complete in 125.1 sec
[-------          20%                  ] 409 of 2000 complete in 125.7 sec
[-------          20%                  ] 411 of 2000 complete in 126.4 sec
[-------          20%                  ] 413 of 2000 complete in 127.0 sec
[-------          20%                  ] 415 of 2000 complete in 127.6 sec
[-------          20%                  ] 417 of 2000 complete in 128.3 sec
[-------          20%                  ] 419 of 2000 complete in 128.9 sec
[-------          21%                  ] 421 of 2000 complete in 129.6 sec
[--------         21%                  ] 423 of 2000 complete in 130.2 sec
[--------         21%                  ] 425 of 2000 complete in 130.8 sec
[--------         21%                  ] 427 of 2000 complete in 131.5 sec
[--------         21%                  ] 429 of 2000 complete in 132.1 sec
[--------         21%                  ] 431 of 2000 complete in 132.7 sec
[--------         21%                  ] 433 of 2000 complete in 133.4 sec
[--------         21%                  ] 435 of 2000 complete in 134.0 sec
[--------         21%                  ] 437 of 2000 complete in 134.6 sec
[--------         21%                  ] 439 of 2000 complete in 135.2 sec
[--------         22%                  ] 441 of 2000 complete in 135.9 sec
[--------         22%                  ] 443 of 2000 complete in 136.5 sec
[--------         22%                  ] 445 of 2000 complete in 137.1 sec
[--------         22%                  ] 447 of 2000 complete in 137.8 sec
[--------         22%                  ] 449 of 2000 complete in 138.4 sec
[--------         22%                  ] 451 of 2000 complete in 139.0 sec
[--------         22%                  ] 453 of 2000 complete in 139.6 sec
[--------         22%                  ] 455 of 2000 complete in 140.3 sec
[--------         22%                  ] 457 of 2000 complete in 140.9 sec
[--------         22%                  ] 459 of 2000 complete in 141.5 sec
[--------         23%                  ] 461 of 2000 complete in 142.2 sec
[--------         23%                  ] 463 of 2000 complete in 142.8 sec
[--------         23%                  ] 465 of 2000 complete in 143.4 sec
[--------         23%                  ] 467 of 2000 complete in 144.0 sec
[--------         23%                  ] 469 of 2000 complete in 144.6 sec
[--------         23%                  ] 471 of 2000 complete in 145.3 sec
[--------         23%                  ] 473 of 2000 complete in 145.9 sec
[---------        23%                  ] 475 of 2000 complete in 146.5 sec
[---------        23%                  ] 477 of 2000 complete in 147.2 sec
[---------        23%                  ] 479 of 2000 complete in 147.8 sec
[---------        24%                  ] 481 of 2000 complete in 148.5 sec
[---------        24%                  ] 483 of 2000 complete in 149.1 sec
[---------        24%                  ] 485 of 2000 complete in 149.7 sec
[---------        24%                  ] 487 of 2000 complete in 150.4 sec
[---------        24%                  ] 489 of 2000 complete in 151.0 sec
[---------        24%                  ] 491 of 2000 complete in 151.6 sec
[---------        24%                  ] 493 of 2000 complete in 152.3 sec
[---------        24%                  ] 495 of 2000 complete in 152.9 sec
[---------        24%                  ] 497 of 2000 complete in 153.6 sec
[---------        24%                  ] 499 of 2000 complete in 154.2 sec
[---------        25%                  ] 501 of 2000 complete in 154.9 sec
[---------        25%                  ] 503 of 2000 complete in 155.5 sec
[---------        25%                  ] 505 of 2000 complete in 156.1 sec
[---------        25%                  ] 507 of 2000 complete in 156.8 sec
[---------        25%                  ] 509 of 2000 complete in 157.4 sec
[---------        25%                  ] 511 of 2000 complete in 158.0 sec
[---------        25%                  ] 513 of 2000 complete in 158.7 sec
[---------        25%                  ] 515 of 2000 complete in 159.3 sec
[---------        25%                  ] 517 of 2000 complete in 159.9 sec
[---------        25%                  ] 519 of 2000 complete in 160.6 sec
[---------        26%                  ] 521 of 2000 complete in 161.2 sec

[---------        26%                  ] 523 of 2000 complete in 159.1 sec
[---------        26%                  ] 525 of 2000 complete in 159.7 sec
[----------       26%                  ] 527 of 2000 complete in 160.3 sec
[----------       26%                  ] 529 of 2000 complete in 160.9 sec
[----------       26%                  ] 531 of 2000 complete in 161.5 sec
[----------       26%                  ] 533 of 2000 complete in 162.1 sec
[----------       26%                  ] 535 of 2000 complete in 162.8 sec
[----------       26%                  ] 537 of 2000 complete in 163.4 sec
[----------       26%                  ] 539 of 2000 complete in 164.0 sec
[----------       27%                  ] 541 of 2000 complete in 164.6 sec
[----------       27%                  ] 543 of 2000 complete in 165.2 sec
[----------       27%                  ] 545 of 2000 complete in 165.8 sec
[----------       27%                  ] 547 of 2000 complete in 166.4 sec
[----------       27%                  ] 549 of 2000 complete in 167.0 sec
[----------       27%                  ] 551 of 2000 complete in 167.6 sec
[----------       27%                  ] 553 of 2000 complete in 168.2 sec
[----------       27%                  ] 555 of 2000 complete in 168.8 sec
[----------       27%                  ] 557 of 2000 complete in 169.4 sec
[----------       27%                  ] 559 of 2000 complete in 170.0 sec
[----------       28%                  ] 561 of 2000 complete in 170.6 sec
[----------       28%                  ] 563 of 2000 complete in 171.2 sec
[----------       28%                  ] 565 of 2000 complete in 171.8 sec
[----------       28%                  ] 567 of 2000 complete in 172.4 sec
[----------       28%                  ] 569 of 2000 complete in 173.0 sec
[----------       28%                  ] 571 of 2000 complete in 173.6 sec
[----------       28%                  ] 573 of 2000 complete in 174.3 sec
[----------       28%                  ] 575 of 2000 complete in 174.8 sec
[----------       28%                  ] 577 of 2000 complete in 175.4 sec
[-----------      28%                  ] 579 of 2000 complete in 176.0 sec
[-----------      29%                  ] 581 of 2000 complete in 176.6 sec
[-----------      29%                  ] 583 of 2000 complete in 177.2 sec
[-----------      29%                  ] 585 of 2000 complete in 177.8 sec
[-----------      29%                  ] 587 of 2000 complete in 178.4 sec
[-----------      29%                  ] 589 of 2000 complete in 179.0 sec
[-----------      29%                  ] 591 of 2000 complete in 179.6 sec
[-----------      29%                  ] 593 of 2000 complete in 180.2 sec
[-----------      29%                  ] 595 of 2000 complete in 180.8 sec
[-----------      29%                  ] 597 of 2000 complete in 181.4 sec
[-----------      29%                  ] 599 of 2000 complete in 182.0 sec
[-----------      30%                  ] 601 of 2000 complete in 182.6 sec
[-----------      30%                  ] 603 of 2000 complete in 183.2 sec
[-----------      30%                  ] 605 of 2000 complete in 183.8 sec
[-----------      30%                  ] 607 of 2000 complete in 184.4 sec
[-----------      30%                  ] 609 of 2000 complete in 185.0 sec
[-----------      30%                  ] 611 of 2000 complete in 185.6 sec
[-----------      30%                  ] 613 of 2000 complete in 186.2 sec
[-----------      30%                  ] 615 of 2000 complete in 186.8 sec
[-----------      30%                  ] 617 of 2000 complete in 187.4 sec
[-----------      30%                  ] 619 of 2000 complete in 188.0 sec
[-----------      31%                  ] 621 of 2000 complete in 188.6 sec
[-----------      31%                  ] 623 of 2000 complete in 189.2 sec
[-----------      31%                  ] 625 of 2000 complete in 189.8 sec
[-----------      31%                  ] 627 of 2000 complete in 190.4 sec
[-----------      31%                  ] 629 of 2000 complete in 191.0 sec
[-----------      31%                  ] 631 of 2000 complete in 191.6 sec
[------------     31%                  ] 633 of 2000 complete in 192.2 sec
[------------     31%                  ] 635 of 2000 complete in 192.9 sec
[------------     31%                  ] 637 of 2000 complete in 193.5 sec
[------------     31%                  ] 639 of 2000 complete in 194.1 sec
[------------     32%                  ] 641 of 2000 complete in 194.7 sec
[------------     32%                  ] 643 of 2000 complete in 195.4 sec
[------------     32%                  ] 645 of 2000 complete in 196.1 sec
[------------     32%                  ] 647 of 2000 complete in 196.7 sec
[------------     32%                  ] 649 of 2000 complete in 197.3 sec
[------------     32%                  ] 651 of 2000 complete in 197.9 sec
[------------     32%                  ] 653 of 2000 complete in 198.5 sec
[------------     32%                  ] 655 of 2000 complete in 199.1 sec
[------------     32%                  ] 657 of 2000 complete in 199.7 sec
[------------     32%                  ] 659 of 2000 complete in 200.3 sec
[------------     33%                  ] 661 of 2000 complete in 200.9 sec
[------------     33%                  ] 663 of 2000 complete in 201.5 sec
[------------     33%                  ] 665 of 2000 complete in 202.1 sec
[------------     33%                  ] 667 of 2000 complete in 202.8 sec
[------------     33%                  ] 669 of 2000 complete in 203.4 sec
[------------     33%                  ] 671 of 2000 complete in 204.0 sec
[------------     33%                  ] 673 of 2000 complete in 204.6 sec
[------------     33%                  ] 675 of 2000 complete in 205.2 sec
[------------     33%                  ] 677 of 2000 complete in 205.8 sec
[------------     33%                  ] 679 of 2000 complete in 206.4 sec
[------------     34%                  ] 681 of 2000 complete in 207.0 sec
[------------     34%                  ] 683 of 2000 complete in 207.6 sec
[-------------    34%                  ] 685 of 2000 complete in 208.2 sec
[-------------    34%                  ] 687 of 2000 complete in 208.8 sec
[-------------    34%                  ] 689 of 2000 complete in 209.5 sec
[-------------    34%                  ] 691 of 2000 complete in 210.1 sec
[-------------    34%                  ] 693 of 2000 complete in 210.7 sec
[-------------    34%                  ] 695 of 2000 complete in 211.4 sec
[-------------    34%                  ] 697 of 2000 complete in 212.0 sec
[-------------    34%                  ] 699 of 2000 complete in 212.6 sec
[-------------    35%                  ] 701 of 2000 complete in 213.2 sec
[-------------    35%                  ] 703 of 2000 complete in 213.8 sec
[-------------    35%                  ] 705 of 2000 complete in 214.4 sec
[-------------    35%                  ] 707 of 2000 complete in 215.0 sec
[-------------    35%                  ] 709 of 2000 complete in 215.6 sec
[-------------    35%                  ] 711 of 2000 complete in 216.3 sec
[-------------    35%                  ] 713 of 2000 complete in 216.9 sec
[-------------    35%                  ] 715 of 2000 complete in 217.5 sec
[-------------    35%                  ] 717 of 2000 complete in 218.1 sec
[-------------    35%                  ] 719 of 2000 complete in 218.7 sec
[-------------    36%                  ] 721 of 2000 complete in 219.3 sec
[-------------    36%                  ] 723 of 2000 complete in 219.9 sec
[-------------    36%                  ] 725 of 2000 complete in 220.5 sec
[-------------    36%                  ] 727 of 2000 complete in 221.1 sec
[-------------    36%                  ] 729 of 2000 complete in 221.7 sec
[-------------    36%                  ] 731 of 2000 complete in 222.3 sec
[-------------    36%                  ] 733 of 2000 complete in 222.9 sec
[-------------    36%                  ] 735 of 2000 complete in 223.6 sec
[--------------   36%                  ] 737 of 2000 complete in 224.2 sec
[--------------   36%                  ] 739 of 2000 complete in 224.8 sec
[---------        26%                  ] 521 of 2000 complete in 160.6 sec
[---------        26%                  ] 523 of 2000 complete in 161.2 sec
[---------        26%                  ] 525 of 2000 complete in 161.8 sec
[----------       26%                  ] 527 of 2000 complete in 162.4 sec
[----------       26%                  ] 529 of 2000 complete in 163.0 sec
[----------       26%                  ] 531 of 2000 complete in 163.7 sec
[----------       26%                  ] 533 of 2000 complete in 164.3 sec
[----------       26%                  ] 535 of 2000 complete in 164.9 sec
[----------       26%                  ] 537 of 2000 complete in 165.5 sec
[----------       26%                  ] 539 of 2000 complete in 166.1 sec
[----------       27%                  ] 541 of 2000 complete in 166.7 sec
[----------       27%                  ] 543 of 2000 complete in 167.4 sec
[----------       27%                  ] 545 of 2000 complete in 168.0 sec
[----------       27%                  ] 547 of 2000 complete in 168.6 sec
[----------       27%                  ] 549 of 2000 complete in 169.2 sec
[----------       27%                  ] 551 of 2000 complete in 169.8 sec
[----------       27%                  ] 553 of 2000 complete in 170.4 sec
[----------       27%                  ] 555 of 2000 complete in 171.0 sec
[----------       27%                  ] 557 of 2000 complete in 171.7 sec
[----------       27%                  ] 559 of 2000 complete in 172.3 sec
[----------       28%                  ] 561 of 2000 complete in 172.9 sec
[----------       28%                  ] 563 of 2000 complete in 173.5 sec
[----------       28%                  ] 565 of 2000 complete in 174.1 sec
[----------       28%                  ] 567 of 2000 complete in 174.8 sec
[----------       28%                  ] 569 of 2000 complete in 175.4 sec
[----------       28%                  ] 571 of 2000 complete in 176.0 sec
[----------       28%                  ] 573 of 2000 complete in 176.6 sec
[----------       28%                  ] 575 of 2000 complete in 177.2 sec
[----------       28%                  ] 577 of 2000 complete in 177.8 sec
[-----------      28%                  ] 579 of 2000 complete in 178.4 sec
[-----------      29%                  ] 581 of 2000 complete in 179.0 sec
[-----------      29%                  ] 583 of 2000 complete in 179.6 sec
[-----------      29%                  ] 585 of 2000 complete in 180.2 sec
[-----------      29%                  ] 587 of 2000 complete in 180.8 sec
[-----------      29%                  ] 589 of 2000 complete in 181.4 sec
[-----------      29%                  ] 591 of 2000 complete in 182.0 sec
[-----------      29%                  ] 593 of 2000 complete in 182.6 sec
[-----------      29%                  ] 595 of 2000 complete in 183.2 sec
[-----------      29%                  ] 597 of 2000 complete in 183.8 sec
[-----------      29%                  ] 599 of 2000 complete in 184.4 sec
[-----------      30%                  ] 601 of 2000 complete in 185.0 sec
[-----------      30%                  ] 603 of 2000 complete in 185.6 sec
[-----------      30%                  ] 605 of 2000 complete in 186.2 sec
[-----------      30%                  ] 607 of 2000 complete in 186.8 sec
[-----------      30%                  ] 609 of 2000 complete in 187.4 sec
[-----------      30%                  ] 611 of 2000 complete in 188.1 sec
[-----------      30%                  ] 613 of 2000 complete in 188.6 sec
[-----------      30%                  ] 615 of 2000 complete in 189.3 sec
[-----------      30%                  ] 617 of 2000 complete in 189.9 sec
[-----------      30%                  ] 619 of 2000 complete in 190.5 sec
[-----------      31%                  ] 621 of 2000 complete in 191.1 sec
[-----------      31%                  ] 623 of 2000 complete in 191.7 sec
[-----------      31%                  ] 625 of 2000 complete in 192.4 sec
[-----------      31%                  ] 627 of 2000 complete in 193.0 sec
[-----------      31%                  ] 629 of 2000 complete in 193.6 sec
[-----------      31%                  ] 631 of 2000 complete in 194.2 sec
[------------     31%                  ] 633 of 2000 complete in 194.9 sec
[------------     31%                  ] 635 of 2000 complete in 195.5 sec
[------------     31%                  ] 637 of 2000 complete in 196.2 sec
[------------     31%                  ] 639 of 2000 complete in 196.8 sec
[------------     32%                  ] 641 of 2000 complete in 197.4 sec
[------------     32%                  ] 643 of 2000 complete in 198.1 sec
[------------     32%                  ] 645 of 2000 complete in 198.7 sec
[------------     32%                  ] 647 of 2000 complete in 199.3 sec
[------------     32%                  ] 649 of 2000 complete in 199.9 sec
[------------     32%                  ] 651 of 2000 complete in 200.5 sec
[------------     32%                  ] 653 of 2000 complete in 201.2 sec
[------------     32%                  ] 655 of 2000 complete in 201.8 sec
[------------     32%                  ] 657 of 2000 complete in 202.4 sec
[------------     32%                  ] 659 of 2000 complete in 203.0 sec
[------------     33%                  ] 661 of 2000 complete in 203.6 sec
[------------     33%                  ] 663 of 2000 complete in 204.3 sec
[------------     33%                  ] 665 of 2000 complete in 204.9 sec
[------------     33%                  ] 667 of 2000 complete in 205.5 sec
[------------     33%                  ] 669 of 2000 complete in 206.1 sec
[------------     33%                  ] 671 of 2000 complete in 206.7 sec
[------------     33%                  ] 673 of 2000 complete in 207.4 sec
[------------     33%                  ] 675 of 2000 complete in 208.0 sec
[------------     33%                  ] 677 of 2000 complete in 208.6 sec
[------------     33%                  ] 679 of 2000 complete in 209.2 sec
[------------     34%                  ] 681 of 2000 complete in 209.8 sec
[------------     34%                  ] 683 of 2000 complete in 210.4 sec
[-------------    34%                  ] 685 of 2000 complete in 211.0 sec
[-------------    34%                  ] 687 of 2000 complete in 211.6 sec
[-------------    34%                  ] 689 of 2000 complete in 212.3 sec
[-------------    34%                  ] 691 of 2000 complete in 212.9 sec
[-------------    34%                  ] 693 of 2000 complete in 213.5 sec
[-------------    34%                  ] 695 of 2000 complete in 214.1 sec
[-------------    34%                  ] 697 of 2000 complete in 214.7 sec
[-------------    34%                  ] 699 of 2000 complete in 215.4 sec
[-------------    35%                  ] 701 of 2000 complete in 216.0 sec
[-------------    35%                  ] 703 of 2000 complete in 216.6 sec
[-------------    35%                  ] 705 of 2000 complete in 217.2 sec
[-------------    35%                  ] 707 of 2000 complete in 217.8 sec
[-------------    35%                  ] 709 of 2000 complete in 218.4 sec
[-------------    35%                  ] 711 of 2000 complete in 219.0 sec
[-------------    35%                  ] 713 of 2000 complete in 219.6 sec
[-------------    35%                  ] 715 of 2000 complete in 220.2 sec
[-------------    35%                  ] 717 of 2000 complete in 220.8 sec
[-------------    35%                  ] 719 of 2000 complete in 221.5 sec
[-------------    36%                  ] 721 of 2000 complete in 222.1 sec
[-------------    36%                  ] 723 of 2000 complete in 222.7 sec
[-------------    36%                  ] 725 of 2000 complete in 223.3 sec
[-------------    36%                  ] 727 of 2000 complete in 223.9 sec
[-------------    36%                  ] 729 of 2000 complete in 224.5 sec
[-------------    36%                  ] 731 of 2000 complete in 225.2 sec
[-------------    36%                  ] 733 of 2000 complete in 225.8 sec
[-------------    36%                  ] 735 of 2000 complete in 226.4 sec
[--------------   36%                  ] 737 of 2000 complete in 227.0 sec

[---------        26%                  ] 523 of 2000 complete in 160.9 sec
[---------        26%                  ] 525 of 2000 complete in 161.5 sec
[----------       26%                  ] 527 of 2000 complete in 162.2 sec
[----------       26%                  ] 529 of 2000 complete in 162.8 sec
[----------       26%                  ] 531 of 2000 complete in 163.4 sec
[----------       26%                  ] 533 of 2000 complete in 164.0 sec
[----------       26%                  ] 535 of 2000 complete in 164.6 sec
[----------       26%                  ] 537 of 2000 complete in 165.2 sec
[----------       26%                  ] 539 of 2000 complete in 165.8 sec
[----------       27%                  ] 541 of 2000 complete in 166.4 sec
[----------       27%                  ] 543 of 2000 complete in 167.0 sec
[----------       27%                  ] 545 of 2000 complete in 167.6 sec
[----------       27%                  ] 547 of 2000 complete in 168.2 sec
[----------       27%                  ] 549 of 2000 complete in 168.8 sec
[----------       27%                  ] 551 of 2000 complete in 169.4 sec
[----------       27%                  ] 553 of 2000 complete in 170.0 sec
[----------       27%                  ] 555 of 2000 complete in 170.6 sec
[----------       27%                  ] 557 of 2000 complete in 171.3 sec
[----------       27%                  ] 559 of 2000 complete in 171.9 sec
[----------       28%                  ] 561 of 2000 complete in 172.5 sec
[----------       28%                  ] 563 of 2000 complete in 173.1 sec
[----------       28%                  ] 565 of 2000 complete in 173.7 sec
[----------       28%                  ] 567 of 2000 complete in 174.4 sec
[----------       28%                  ] 569 of 2000 complete in 175.0 sec
[----------       28%                  ] 571 of 2000 complete in 175.6 sec
[----------       28%                  ] 573 of 2000 complete in 176.2 sec
[----------       28%                  ] 575 of 2000 complete in 176.8 sec
[----------       28%                  ] 577 of 2000 complete in 177.4 sec
[-----------      28%                  ] 579 of 2000 complete in 178.0 sec
[-----------      29%                  ] 581 of 2000 complete in 178.6 sec
[-----------      29%                  ] 583 of 2000 complete in 179.2 sec
[-----------      29%                  ] 585 of 2000 complete in 179.8 sec
[-----------      29%                  ] 587 of 2000 complete in 180.4 sec
[-----------      29%                  ] 589 of 2000 complete in 181.0 sec
[-----------      29%                  ] 591 of 2000 complete in 181.6 sec
[-----------      29%                  ] 593 of 2000 complete in 182.3 sec
[-----------      29%                  ] 595 of 2000 complete in 182.9 sec
[-----------      29%                  ] 597 of 2000 complete in 183.4 sec
[-----------      29%                  ] 599 of 2000 complete in 184.1 sec
[-----------      30%                  ] 601 of 2000 complete in 184.6 sec
[-----------      30%                  ] 603 of 2000 complete in 185.2 sec
[-----------      30%                  ] 605 of 2000 complete in 185.8 sec
[-----------      30%                  ] 607 of 2000 complete in 186.4 sec
[-----------      30%                  ] 609 of 2000 complete in 187.0 sec
[-----------      30%                  ] 611 of 2000 complete in 187.6 sec
[-----------      30%                  ] 613 of 2000 complete in 188.2 sec
[-----------      30%                  ] 615 of 2000 complete in 188.8 sec
[-----------      30%                  ] 617 of 2000 complete in 189.5 sec
[-----------      30%                  ] 619 of 2000 complete in 190.1 sec
[-----------      31%                  ] 621 of 2000 complete in 190.7 sec
[-----------      31%                  ] 623 of 2000 complete in 191.3 sec
[-----------      31%                  ] 625 of 2000 complete in 192.0 sec
[-----------      31%                  ] 627 of 2000 complete in 192.6 sec
[-----------      31%                  ] 629 of 2000 complete in 193.2 sec
[-----------      31%                  ] 631 of 2000 complete in 193.9 sec
[------------     31%                  ] 633 of 2000 complete in 194.5 sec
[------------     31%                  ] 635 of 2000 complete in 195.1 sec
[------------     31%                  ] 637 of 2000 complete in 195.8 sec
[------------     31%                  ] 639 of 2000 complete in 196.4 sec
[------------     32%                  ] 641 of 2000 complete in 197.1 sec
[------------     32%                  ] 643 of 2000 complete in 197.7 sec
[------------     32%                  ] 645 of 2000 complete in 198.3 sec
[------------     32%                  ] 647 of 2000 complete in 198.9 sec
[------------     32%                  ] 649 of 2000 complete in 199.5 sec
[------------     32%                  ] 651 of 2000 complete in 200.2 sec
[------------     32%                  ] 653 of 2000 complete in 200.8 sec
[------------     32%                  ] 655 of 2000 complete in 201.4 sec
[------------     32%                  ] 657 of 2000 complete in 202.0 sec
[------------     32%                  ] 659 of 2000 complete in 202.6 sec
[------------     33%                  ] 661 of 2000 complete in 203.2 sec
[------------     33%                  ] 663 of 2000 complete in 203.9 sec
[------------     33%                  ] 665 of 2000 complete in 204.5 sec
[------------     33%                  ] 667 of 2000 complete in 205.1 sec
[------------     33%                  ] 669 of 2000 complete in 205.7 sec
[------------     33%                  ] 671 of 2000 complete in 206.4 sec
[------------     33%                  ] 673 of 2000 complete in 207.0 sec
[------------     33%                  ] 675 of 2000 complete in 207.6 sec
[------------     33%                  ] 677 of 2000 complete in 208.2 sec
[------------     33%                  ] 679 of 2000 complete in 208.8 sec
[------------     34%                  ] 681 of 2000 complete in 209.4 sec
[------------     34%                  ] 683 of 2000 complete in 210.0 sec
[-------------    34%                  ] 685 of 2000 complete in 210.7 sec
[-------------    34%                  ] 687 of 2000 complete in 211.3 sec
[-------------    34%                  ] 689 of 2000 complete in 211.9 sec
[-------------    34%                  ] 691 of 2000 complete in 212.5 sec
[-------------    34%                  ] 693 of 2000 complete in 213.1 sec
[-------------    34%                  ] 695 of 2000 complete in 213.7 sec
[-------------    34%                  ] 697 of 2000 complete in 214.3 sec
[-------------    34%                  ] 699 of 2000 complete in 214.9 sec
[-------------    35%                  ] 701 of 2000 complete in 215.5 sec
[-------------    35%                  ] 703 of 2000 complete in 216.1 sec
[-------------    35%                  ] 705 of 2000 complete in 216.8 sec
[-------------    35%                  ] 707 of 2000 complete in 217.4 sec
[-------------    35%                  ] 709 of 2000 complete in 218.0 sec
[-------------    35%                  ] 711 of 2000 complete in 218.6 sec
[-------------    35%                  ] 713 of 2000 complete in 219.2 sec
[-------------    35%                  ] 715 of 2000 complete in 219.8 sec
[-------------    35%                  ] 717 of 2000 complete in 220.4 sec
[-------------    35%                  ] 719 of 2000 complete in 221.0 sec
[-------------    36%                  ] 721 of 2000 complete in 221.7 sec
[-------------    36%                  ] 723 of 2000 complete in 222.3 sec
[-------------    36%                  ] 725 of 2000 complete in 222.9 sec
[-------------    36%                  ] 727 of 2000 complete in 223.6 sec
[-------------    36%                  ] 729 of 2000 complete in 224.2 sec
[-------------    36%                  ] 731 of 2000 complete in 224.8 sec
[-------------    36%                  ] 733 of 2000 complete in 225.4 sec
[-------------    36%                  ] 735 of 2000 complete in 226.1 sec
[--------------   36%                  ] 737 of 2000 complete in 226.7 sec
[--------------   36%                  ] 739 of 2000 complete in 227.3 sec
[---------        26%                  ] 523 of 2000 complete in 161.8 sec
[---------        26%                  ] 525 of 2000 complete in 162.4 sec
[----------       26%                  ] 527 of 2000 complete in 163.1 sec
[----------       26%                  ] 529 of 2000 complete in 163.7 sec
[----------       26%                  ] 531 of 2000 complete in 164.3 sec
[----------       26%                  ] 533 of 2000 complete in 164.9 sec
[----------       26%                  ] 535 of 2000 complete in 165.5 sec
[----------       26%                  ] 537 of 2000 complete in 166.1 sec
[----------       26%                  ] 539 of 2000 complete in 166.7 sec
[----------       27%                  ] 541 of 2000 complete in 167.4 sec
[----------       27%                  ] 543 of 2000 complete in 168.0 sec
[----------       27%                  ] 545 of 2000 complete in 168.6 sec
[----------       27%                  ] 547 of 2000 complete in 169.2 sec
[----------       27%                  ] 549 of 2000 complete in 169.8 sec
[----------       27%                  ] 551 of 2000 complete in 170.4 sec
[----------       27%                  ] 553 of 2000 complete in 171.0 sec
[----------       27%                  ] 555 of 2000 complete in 171.7 sec
[----------       27%                  ] 557 of 2000 complete in 172.3 sec
[----------       27%                  ] 559 of 2000 complete in 172.9 sec
[----------       28%                  ] 561 of 2000 complete in 173.6 sec
[----------       28%                  ] 563 of 2000 complete in 174.2 sec
[----------       28%                  ] 565 of 2000 complete in 174.8 sec
[----------       28%                  ] 567 of 2000 complete in 175.4 sec
[----------       28%                  ] 569 of 2000 complete in 176.0 sec
[----------       28%                  ] 571 of 2000 complete in 176.6 sec
[----------       28%                  ] 573 of 2000 complete in 177.2 sec
[----------       28%                  ] 575 of 2000 complete in 177.8 sec
[----------       28%                  ] 577 of 2000 complete in 178.4 sec
[-----------      28%                  ] 579 of 2000 complete in 179.0 sec
[-----------      29%                  ] 581 of 2000 complete in 179.6 sec
[-----------      29%                  ] 583 of 2000 complete in 180.3 sec
[-----------      29%                  ] 585 of 2000 complete in 180.9 sec
[-----------      29%                  ] 587 of 2000 complete in 181.5 sec
[-----------      29%                  ] 589 of 2000 complete in 182.1 sec
[-----------      29%                  ] 591 of 2000 complete in 182.7 sec
[-----------      29%                  ] 593 of 2000 complete in 183.3 sec
[-----------      29%                  ] 595 of 2000 complete in 183.9 sec
[-----------      29%                  ] 597 of 2000 complete in 184.5 sec
[-----------      29%                  ] 599 of 2000 complete in 185.1 sec
[-----------      30%                  ] 601 of 2000 complete in 185.7 sec
[-----------      30%                  ] 603 of 2000 complete in 186.4 sec
[-----------      30%                  ] 605 of 2000 complete in 187.0 sec
[-----------      30%                  ] 607 of 2000 complete in 187.6 sec
[-----------      30%                  ] 609 of 2000 complete in 188.2 sec
[-----------      30%                  ] 611 of 2000 complete in 188.8 sec
[-----------      30%                  ] 613 of 2000 complete in 189.5 sec
[-----------      30%                  ] 615 of 2000 complete in 190.1 sec
[-----------      30%                  ] 617 of 2000 complete in 190.7 sec
[-----------      30%                  ] 619 of 2000 complete in 191.3 sec
[-----------      31%                  ] 621 of 2000 complete in 191.9 sec
[-----------      31%                  ] 623 of 2000 complete in 192.6 sec
[-----------      31%                  ] 625 of 2000 complete in 193.3 sec
[-----------      31%                  ] 627 of 2000 complete in 193.9 sec
[-----------      31%                  ] 629 of 2000 complete in 194.5 sec
[-----------      31%                  ] 631 of 2000 complete in 195.2 sec
[------------     31%                  ] 633 of 2000 complete in 195.8 sec
[------------     31%                  ] 635 of 2000 complete in 196.5 sec
[------------     31%                  ] 637 of 2000 complete in 197.1 sec
[------------     31%                  ] 639 of 2000 complete in 197.7 sec
[------------     32%                  ] 641 of 2000 complete in 198.4 sec
[------------     32%                  ] 643 of 2000 complete in 199.0 sec
[------------     32%                  ] 645 of 2000 complete in 199.6 sec
[------------     32%                  ] 647 of 2000 complete in 200.2 sec
[------------     32%                  ] 649 of 2000 complete in 200.9 sec
[------------     32%                  ] 651 of 2000 complete in 201.5 sec
[------------     32%                  ] 653 of 2000 complete in 202.1 sec
[------------     32%                  ] 655 of 2000 complete in 202.7 sec
[------------     32%                  ] 657 of 2000 complete in 203.3 sec
[------------     32%                  ] 659 of 2000 complete in 204.0 sec
[------------     33%                  ] 661 of 2000 complete in 204.6 sec
[------------     33%                  ] 663 of 2000 complete in 205.2 sec
[------------     33%                  ] 665 of 2000 complete in 205.9 sec
[------------     33%                  ] 667 of 2000 complete in 206.5 sec
[------------     33%                  ] 669 of 2000 complete in 207.1 sec
[------------     33%                  ] 671 of 2000 complete in 207.7 sec
[------------     33%                  ] 673 of 2000 complete in 208.4 sec
[------------     33%                  ] 675 of 2000 complete in 209.0 sec
[------------     33%                  ] 677 of 2000 complete in 209.6 sec
[------------     33%                  ] 679 of 2000 complete in 210.2 sec
[------------     34%                  ] 681 of 2000 complete in 210.9 sec
[------------     34%                  ] 683 of 2000 complete in 211.5 sec
[-------------    34%                  ] 685 of 2000 complete in 212.1 sec
[-------------    34%                  ] 687 of 2000 complete in 212.7 sec
[-------------    34%                  ] 689 of 2000 complete in 213.3 sec
[-------------    34%                  ] 691 of 2000 complete in 213.9 sec
[-------------    34%                  ] 693 of 2000 complete in 214.6 sec
[-------------    34%                  ] 695 of 2000 complete in 215.2 sec
[-------------    34%                  ] 697 of 2000 complete in 215.8 sec
[-------------    34%                  ] 699 of 2000 complete in 216.4 sec
[-------------    35%                  ] 701 of 2000 complete in 217.0 sec
[-------------    35%                  ] 703 of 2000 complete in 217.6 sec
[-------------    35%                  ] 705 of 2000 complete in 218.2 sec
[-------------    35%                  ] 707 of 2000 complete in 218.8 sec
[-------------    35%                  ] 709 of 2000 complete in 219.4 sec
[-------------    35%                  ] 711 of 2000 complete in 220.1 sec
[-------------    35%                  ] 713 of 2000 complete in 220.7 sec
[-------------    35%                  ] 715 of 2000 complete in 221.3 sec
[-------------    35%                  ] 717 of 2000 complete in 222.0 sec
[-------------    35%                  ] 719 of 2000 complete in 222.6 sec
[-------------    36%                  ] 721 of 2000 complete in 223.3 sec
[-------------    36%                  ] 723 of 2000 complete in 223.9 sec
[-------------    36%                  ] 725 of 2000 complete in 224.5 sec
[-------------    36%                  ] 727 of 2000 complete in 225.1 sec
[-------------    36%                  ] 729 of 2000 complete in 225.7 sec
[-------------    36%                  ] 731 of 2000 complete in 226.3 sec
[-------------    36%                  ] 733 of 2000 complete in 226.9 sec
[-------------    36%                  ] 735 of 2000 complete in 227.5 sec
[--------------   36%                  ] 737 of 2000 complete in 228.2 sec
[--------------   36%                  ] 739 of 2000 complete in 228.8 sec

[--------------   37%                  ] 741 of 2000 complete in 225.4 sec
[--------------   37%                  ] 743 of 2000 complete in 226.0 sec
[--------------   37%                  ] 745 of 2000 complete in 226.6 sec
[--------------   37%                  ] 747 of 2000 complete in 227.2 sec
[--------------   37%                  ] 749 of 2000 complete in 227.8 sec
[--------------   37%                  ] 751 of 2000 complete in 228.4 sec
[--------------   37%                  ] 753 of 2000 complete in 229.0 sec
[--------------   37%                  ] 755 of 2000 complete in 229.7 sec
[--------------   37%                  ] 757 of 2000 complete in 230.3 sec
[--------------   37%                  ] 759 of 2000 complete in 230.9 sec
[--------------   38%                  ] 761 of 2000 complete in 231.5 sec
[--------------   38%                  ] 763 of 2000 complete in 232.1 sec
[--------------   38%                  ] 765 of 2000 complete in 232.7 sec
[--------------   38%                  ] 767 of 2000 complete in 233.3 sec
[--------------   38%                  ] 769 of 2000 complete in 233.9 sec
[--------------   38%                  ] 771 of 2000 complete in 234.5 sec
[--------------   38%                  ] 773 of 2000 complete in 235.1 sec
[--------------   38%                  ] 775 of 2000 complete in 235.7 sec
[--------------   38%                  ] 777 of 2000 complete in 236.3 sec
[--------------   38%                  ] 779 of 2000 complete in 236.9 sec
[--------------   39%                  ] 781 of 2000 complete in 237.5 sec
[--------------   39%                  ] 783 of 2000 complete in 238.1 sec
[--------------   39%                  ] 785 of 2000 complete in 238.7 sec
[--------------   39%                  ] 787 of 2000 complete in 239.3 sec
[--------------   39%                  ] 789 of 2000 complete in 239.9 sec
[---------------  39%                  ] 791 of 2000 complete in 240.5 sec
[---------------  39%                  ] 793 of 2000 complete in 241.1 sec
[---------------  39%                  ] 795 of 2000 complete in 241.7 sec
[---------------  39%                  ] 797 of 2000 complete in 242.3 sec
[---------------  39%                  ] 799 of 2000 complete in 242.9 sec
[---------------  40%                  ] 801 of 2000 complete in 243.5 sec
[---------------  40%                  ] 803 of 2000 complete in 244.1 sec
[---------------  40%                  ] 805 of 2000 complete in 244.7 sec
[---------------  40%                  ] 807 of 2000 complete in 245.3 sec
[---------------  40%                  ] 809 of 2000 complete in 245.9 sec
[---------------  40%                  ] 811 of 2000 complete in 246.5 sec
[---------------  40%                  ] 813 of 2000 complete in 247.1 sec
[---------------  40%                  ] 815 of 2000 complete in 247.7 sec
[---------------  40%                  ] 817 of 2000 complete in 248.3 sec
[---------------  40%                  ] 819 of 2000 complete in 248.9 sec
[---------------  41%                  ] 821 of 2000 complete in 249.5 sec
[---------------  41%                  ] 823 of 2000 complete in 250.2 sec
[---------------  41%                  ] 825 of 2000 complete in 250.8 sec
[---------------  41%                  ] 827 of 2000 complete in 251.4 sec
[---------------  41%                  ] 829 of 2000 complete in 252.1 sec
[---------------  41%                  ] 831 of 2000 complete in 252.7 sec
[---------------  41%                  ] 833 of 2000 complete in 253.4 sec
[---------------  41%                  ] 835 of 2000 complete in 254.0 sec
[---------------  41%                  ] 837 of 2000 complete in 254.6 sec
[---------------  41%                  ] 839 of 2000 complete in 255.2 sec
[---------------  42%                  ] 841 of 2000 complete in 255.8 sec
[---------------- 42%                  ] 843 of 2000 complete in 256.4 sec
[---------------- 42%                  ] 845 of 2000 complete in 257.0 sec
[---------------- 42%                  ] 847 of 2000 complete in 257.6 sec
[---------------- 42%                  ] 849 of 2000 complete in 258.2 sec
[---------------- 42%                  ] 851 of 2000 complete in 258.8 sec
[---------------- 42%                  ] 853 of 2000 complete in 259.4 sec
[---------------- 42%                  ] 855 of 2000 complete in 260.0 sec
[---------------- 42%                  ] 857 of 2000 complete in 260.6 sec
[---------------- 42%                  ] 859 of 2000 complete in 261.2 sec
[---------------- 43%                  ] 861 of 2000 complete in 261.8 sec
[---------------- 43%                  ] 863 of 2000 complete in 262.5 sec
[---------------- 43%                  ] 865 of 2000 complete in 263.1 sec
[---------------- 43%                  ] 867 of 2000 complete in 263.7 sec
[---------------- 43%                  ] 869 of 2000 complete in 264.3 sec
[---------------- 43%                  ] 871 of 2000 complete in 264.9 sec
[---------------- 43%                  ] 873 of 2000 complete in 265.5 sec
[---------------- 43%                  ] 875 of 2000 complete in 266.1 sec
[---------------- 43%                  ] 877 of 2000 complete in 266.7 sec
[---------------- 43%                  ] 879 of 2000 complete in 267.3 sec
[---------------- 44%                  ] 881 of 2000 complete in 267.9 sec
[---------------- 44%                  ] 883 of 2000 complete in 268.4 sec
[---------------- 44%                  ] 885 of 2000 complete in 269.0 sec
[---------------- 44%                  ] 887 of 2000 complete in 269.6 sec
[---------------- 44%                  ] 889 of 2000 complete in 270.2 sec
[---------------- 44%                  ] 891 of 2000 complete in 270.8 sec
[---------------- 44%                  ] 893 of 2000 complete in 271.4 sec
[-----------------44%                  ] 895 of 2000 complete in 272.0 sec
[-----------------44%                  ] 897 of 2000 complete in 272.6 sec
[-----------------44%                  ] 899 of 2000 complete in 273.2 sec
[-----------------45%                  ] 901 of 2000 complete in 273.8 sec
[-----------------45%                  ] 903 of 2000 complete in 274.4 sec
[-----------------45%                  ] 905 of 2000 complete in 275.0 sec
[-----------------45%                  ] 907 of 2000 complete in 275.6 sec
[-----------------45%                  ] 909 of 2000 complete in 276.2 sec
[-----------------45%                  ] 911 of 2000 complete in 276.8 sec
[-----------------45%                  ] 913 of 2000 complete in 277.4 sec
[-----------------45%                  ] 915 of 2000 complete in 278.0 sec
[-----------------45%                  ] 917 of 2000 complete in 278.6 sec
[-----------------45%                  ] 919 of 2000 complete in 279.2 sec
[-----------------46%                  ] 921 of 2000 complete in 279.8 sec
[-----------------46%                  ] 923 of 2000 complete in 280.4 sec
[-----------------46%                  ] 925 of 2000 complete in 281.0 sec
[-----------------46%                  ] 927 of 2000 complete in 281.6 sec
[-----------------46%                  ] 929 of 2000 complete in 282.2 sec
[-----------------46%                  ] 931 of 2000 complete in 282.8 sec
[-----------------46%                  ] 933 of 2000 complete in 283.4 sec
[-----------------46%                  ] 935 of 2000 complete in 284.0 sec
[-----------------46%                  ] 937 of 2000 complete in 284.6 sec
[-----------------46%                  ] 939 of 2000 complete in 285.2 sec
[-----------------47%                  ] 941 of 2000 complete in 285.8 sec
[-----------------47%                  ] 943 of 2000 complete in 286.5 sec
[-----------------47%                  ] 945 of 2000 complete in 287.0 sec
[-----------------47%                  ] 947 of 2000 complete in 287.7 sec
[-----------------47%                  ] 949 of 2000 complete in 288.3 sec
[-----------------47%                  ] 951 of 2000 complete in 288.9 sec
[-----------------47%                  ] 953 of 2000 complete in 289.5 sec
[-----------------47%                  ] 955 of 2000 complete in 290.1 sec
[-----------------47%                  ] 957 of 2000 complete in 290.7 sec
[--------------   36%                  ] 739 of 2000 complete in 227.6 sec
[--------------   37%                  ] 741 of 2000 complete in 228.2 sec
[--------------   37%                  ] 743 of 2000 complete in 228.8 sec
[--------------   37%                  ] 745 of 2000 complete in 229.4 sec
[--------------   37%                  ] 747 of 2000 complete in 230.0 sec
[--------------   37%                  ] 749 of 2000 complete in 230.6 sec
[--------------   37%                  ] 751 of 2000 complete in 231.2 sec
[--------------   37%                  ] 753 of 2000 complete in 231.8 sec
[--------------   37%                  ] 755 of 2000 complete in 232.4 sec
[--------------   37%                  ] 757 of 2000 complete in 233.1 sec
[--------------   37%                  ] 759 of 2000 complete in 233.6 sec
[--------------   38%                  ] 761 of 2000 complete in 234.3 sec
[--------------   38%                  ] 763 of 2000 complete in 234.9 sec
[--------------   38%                  ] 765 of 2000 complete in 235.5 sec
[--------------   38%                  ] 767 of 2000 complete in 236.1 sec
[--------------   38%                  ] 769 of 2000 complete in 236.7 sec
[--------------   38%                  ] 771 of 2000 complete in 237.3 sec
[--------------   38%                  ] 773 of 2000 complete in 237.9 sec
[--------------   38%                  ] 775 of 2000 complete in 238.5 sec
[--------------   38%                  ] 777 of 2000 complete in 239.1 sec
[--------------   38%                  ] 779 of 2000 complete in 239.7 sec
[--------------   39%                  ] 781 of 2000 complete in 240.3 sec
[--------------   39%                  ] 783 of 2000 complete in 241.0 sec
[--------------   39%                  ] 785 of 2000 complete in 241.6 sec
[--------------   39%                  ] 787 of 2000 complete in 242.2 sec
[--------------   39%                  ] 789 of 2000 complete in 242.8 sec
[---------------  39%                  ] 791 of 2000 complete in 243.4 sec
[---------------  39%                  ] 793 of 2000 complete in 244.0 sec
[---------------  39%                  ] 795 of 2000 complete in 244.6 sec
[---------------  39%                  ] 797 of 2000 complete in 245.2 sec
[---------------  39%                  ] 799 of 2000 complete in 245.8 sec
[---------------  40%                  ] 801 of 2000 complete in 246.4 sec
[---------------  40%                  ] 803 of 2000 complete in 247.0 sec
[---------------  40%                  ] 805 of 2000 complete in 247.6 sec
[---------------  40%                  ] 807 of 2000 complete in 248.2 sec
[---------------  40%                  ] 809 of 2000 complete in 248.8 sec
[---------------  40%                  ] 811 of 2000 complete in 249.5 sec
[---------------  40%                  ] 813 of 2000 complete in 250.1 sec
[---------------  40%                  ] 815 of 2000 complete in 250.7 sec
[---------------  40%                  ] 817 of 2000 complete in 251.4 sec
[---------------  40%                  ] 819 of 2000 complete in 252.0 sec
[---------------  41%                  ] 821 of 2000 complete in 252.7 sec
[---------------  41%                  ] 823 of 2000 complete in 253.3 sec
[---------------  41%                  ] 825 of 2000 complete in 253.9 sec
[---------------  41%                  ] 827 of 2000 complete in 254.6 sec
[---------------  41%                  ] 829 of 2000 complete in 255.2 sec
[---------------  41%                  ] 831 of 2000 complete in 255.8 sec
[---------------  41%                  ] 833 of 2000 complete in 256.4 sec
[---------------  41%                  ] 835 of 2000 complete in 257.0 sec
[---------------  41%                  ] 837 of 2000 complete in 257.6 sec
[---------------  41%                  ] 839 of 2000 complete in 258.2 sec
[---------------  42%                  ] 841 of 2000 complete in 258.8 sec
[---------------- 42%                  ] 843 of 2000 complete in 259.5 sec
[---------------- 42%                  ] 845 of 2000 complete in 260.1 sec
[---------------- 42%                  ] 847 of 2000 complete in 260.8 sec
[---------------- 42%                  ] 849 of 2000 complete in 261.4 sec
[---------------- 42%                  ] 851 of 2000 complete in 262.0 sec
[---------------- 42%                  ] 853 of 2000 complete in 262.7 sec
[---------------- 42%                  ] 855 of 2000 complete in 263.3 sec
[---------------- 42%                  ] 857 of 2000 complete in 263.9 sec
[---------------- 42%                  ] 859 of 2000 complete in 264.5 sec
[---------------- 43%                  ] 861 of 2000 complete in 265.1 sec
[---------------- 43%                  ] 863 of 2000 complete in 265.7 sec
[---------------- 43%                  ] 865 of 2000 complete in 266.3 sec
[---------------- 43%                  ] 867 of 2000 complete in 266.9 sec
[---------------- 43%                  ] 869 of 2000 complete in 267.5 sec
[---------------- 43%                  ] 871 of 2000 complete in 268.1 sec
[---------------- 43%                  ] 873 of 2000 complete in 268.7 sec
[---------------- 43%                  ] 875 of 2000 complete in 269.3 sec
[---------------- 43%                  ] 877 of 2000 complete in 270.0 sec
[---------------- 43%                  ] 879 of 2000 complete in 270.6 sec
[---------------- 44%                  ] 881 of 2000 complete in 271.2 sec
[---------------- 44%                  ] 883 of 2000 complete in 271.8 sec
[---------------- 44%                  ] 885 of 2000 complete in 272.4 sec
[---------------- 44%                  ] 887 of 2000 complete in 273.1 sec
[---------------- 44%                  ] 889 of 2000 complete in 273.7 sec
[---------------- 44%                  ] 891 of 2000 complete in 274.3 sec
[---------------- 44%                  ] 893 of 2000 complete in 274.9 sec
[-----------------44%                  ] 895 of 2000 complete in 275.5 sec
[-----------------44%                  ] 897 of 2000 complete in 276.1 sec
[-----------------44%                  ] 899 of 2000 complete in 276.7 sec
[-----------------45%                  ] 901 of 2000 complete in 277.3 sec
[-----------------45%                  ] 903 of 2000 complete in 277.9 sec
[-----------------45%                  ] 905 of 2000 complete in 278.5 sec
[-----------------45%                  ] 907 of 2000 complete in 279.1 sec
[-----------------45%                  ] 909 of 2000 complete in 279.7 sec
[-----------------45%                  ] 911 of 2000 complete in 280.3 sec
[-----------------45%                  ] 913 of 2000 complete in 280.9 sec
[-----------------45%                  ] 915 of 2000 complete in 281.5 sec
[-----------------45%                  ] 917 of 2000 complete in 282.1 sec
[-----------------45%                  ] 919 of 2000 complete in 282.8 sec
[-----------------46%                  ] 921 of 2000 complete in 283.3 sec
[-----------------46%                  ] 923 of 2000 complete in 284.0 sec
[-----------------46%                  ] 925 of 2000 complete in 284.6 sec
[-----------------46%                  ] 927 of 2000 complete in 285.2 sec
[-----------------46%                  ] 929 of 2000 complete in 285.8 sec
[-----------------46%                  ] 931 of 2000 complete in 286.4 sec
[-----------------46%                  ] 933 of 2000 complete in 287.0 sec
[-----------------46%                  ] 935 of 2000 complete in 287.6 sec
[-----------------46%                  ] 937 of 2000 complete in 288.3 sec
[-----------------46%                  ] 939 of 2000 complete in 288.9 sec
[-----------------47%                  ] 941 of 2000 complete in 289.5 sec
[-----------------47%                  ] 943 of 2000 complete in 290.1 sec
[-----------------47%                  ] 945 of 2000 complete in 290.7 sec
[-----------------47%                  ] 947 of 2000 complete in 291.3 sec
[-----------------47%                  ] 949 of 2000 complete in 292.0 sec
[-----------------47%                  ] 951 of 2000 complete in 292.6 sec
[-----------------47%                  ] 953 of 2000 complete in 293.1 sec
[-----------------47%                  ] 955 of 2000 complete in 293.7 sec
[--------------   37%                  ] 741 of 2000 complete in 227.9 sec
[--------------   37%                  ] 743 of 2000 complete in 228.5 sec
[--------------   37%                  ] 745 of 2000 complete in 229.1 sec
[--------------   37%                  ] 747 of 2000 complete in 229.7 sec
[--------------   37%                  ] 749 of 2000 complete in 230.3 sec
[--------------   37%                  ] 751 of 2000 complete in 230.9 sec
[--------------   37%                  ] 753 of 2000 complete in 231.5 sec
[--------------   37%                  ] 755 of 2000 complete in 232.1 sec
[--------------   37%                  ] 757 of 2000 complete in 232.8 sec
[--------------   37%                  ] 759 of 2000 complete in 233.4 sec
[--------------   38%                  ] 761 of 2000 complete in 234.0 sec
[--------------   38%                  ] 763 of 2000 complete in 234.6 sec
[--------------   38%                  ] 765 of 2000 complete in 235.2 sec
[--------------   38%                  ] 767 of 2000 complete in 235.8 sec
[--------------   38%                  ] 769 of 2000 complete in 236.4 sec
[--------------   38%                  ] 771 of 2000 complete in 237.0 sec
[--------------   38%                  ] 773 of 2000 complete in 237.7 sec
[--------------   38%                  ] 775 of 2000 complete in 238.3 sec
[--------------   38%                  ] 777 of 2000 complete in 238.9 sec
[--------------   38%                  ] 779 of 2000 complete in 239.5 sec
[--------------   39%                  ] 781 of 2000 complete in 240.1 sec
[--------------   39%                  ] 783 of 2000 complete in 240.7 sec
[--------------   39%                  ] 785 of 2000 complete in 241.4 sec
[--------------   39%                  ] 787 of 2000 complete in 242.0 sec
[--------------   39%                  ] 789 of 2000 complete in 242.6 sec
[---------------  39%                  ] 791 of 2000 complete in 243.2 sec
[---------------  39%                  ] 793 of 2000 complete in 243.8 sec
[---------------  39%                  ] 795 of 2000 complete in 244.4 sec
[---------------  39%                  ] 797 of 2000 complete in 245.0 sec
[---------------  39%                  ] 799 of 2000 complete in 245.6 sec
[---------------  40%                  ] 801 of 2000 complete in 246.3 sec
[---------------  40%                  ] 803 of 2000 complete in 246.9 sec
[---------------  40%                  ] 805 of 2000 complete in 247.5 sec
[---------------  40%                  ] 807 of 2000 complete in 248.1 sec
[---------------  40%                  ] 809 of 2000 complete in 248.7 sec
[---------------  40%                  ] 811 of 2000 complete in 249.3 sec
[---------------  40%                  ] 813 of 2000 complete in 250.0 sec
[---------------  40%                  ] 815 of 2000 complete in 250.6 sec
[---------------  40%                  ] 817 of 2000 complete in 251.2 sec
[---------------  40%                  ] 819 of 2000 complete in 251.9 sec
[---------------  41%                  ] 821 of 2000 complete in 252.5 sec
[---------------  41%                  ] 823 of 2000 complete in 253.1 sec
[---------------  41%                  ] 825 of 2000 complete in 253.8 sec
[---------------  41%                  ] 827 of 2000 complete in 254.4 sec
[---------------  41%                  ] 829 of 2000 complete in 255.0 sec
[---------------  41%                  ] 831 of 2000 complete in 255.6 sec
[---------------  41%                  ] 833 of 2000 complete in 256.2 sec
[---------------  41%                  ] 835 of 2000 complete in 256.8 sec

[--------------   37%                  ] 741 of 2000 complete in 229.4 sec
[--------------   37%                  ] 743 of 2000 complete in 230.0 sec
[--------------   37%                  ] 745 of 2000 complete in 230.6 sec
[--------------   37%                  ] 747 of 2000 complete in 231.2 sec
[--------------   37%                  ] 749 of 2000 complete in 231.8 sec
[--------------   37%                  ] 751 of 2000 complete in 232.4 sec
[--------------   37%                  ] 753 of 2000 complete in 233.0 sec
[--------------   37%                  ] 755 of 2000 complete in 233.6 sec
[--------------   37%                  ] 757 of 2000 complete in 234.2 sec
[--------------   37%                  ] 759 of 2000 complete in 234.9 sec
[--------------   38%                  ] 761 of 2000 complete in 235.5 sec
[--------------   38%                  ] 763 of 2000 complete in 236.1 sec
[--------------   38%                  ] 765 of 2000 complete in 236.7 sec
[--------------   38%                  ] 767 of 2000 complete in 237.3 sec
[--------------   38%                  ] 769 of 2000 complete in 237.9 sec
[--------------   38%                  ] 771 of 2000 complete in 238.6 sec
[--------------   38%                  ] 773 of 2000 complete in 239.2 sec
[--------------   38%                  ] 775 of 2000 complete in 239.8 sec
[--------------   38%                  ] 777 of 2000 complete in 240.4 sec
[--------------   38%                  ] 779 of 2000 complete in 241.0 sec
[--------------   39%                  ] 781 of 2000 complete in 241.7 sec
[--------------   39%                  ] 783 of 2000 complete in 242.3 sec
[--------------   39%                  ] 785 of 2000 complete in 242.9 sec
[--------------   39%                  ] 787 of 2000 complete in 243.5 sec
[--------------   39%                  ] 789 of 2000 complete in 244.1 sec
[---------------  39%                  ] 791 of 2000 complete in 244.7 sec
[---------------  39%                  ] 793 of 2000 complete in 245.3 sec
[---------------  39%                  ] 795 of 2000 complete in 245.9 sec
[---------------  39%                  ] 797 of 2000 complete in 246.5 sec
[---------------  39%                  ] 799 of 2000 complete in 247.1 sec
[---------------  40%                  ] 801 of 2000 complete in 247.7 sec
[---------------  40%                  ] 803 of 2000 complete in 248.4 sec
[---------------  40%                  ] 805 of 2000 complete in 249.0 sec
[---------------  40%                  ] 807 of 2000 complete in 249.6 sec
[---------------  40%                  ] 809 of 2000 complete in 250.2 sec
[---------------  40%                  ] 811 of 2000 complete in 250.8 sec
[---------------  40%                  ] 813 of 2000 complete in 251.5 sec
[---------------  40%                  ] 815 of 2000 complete in 252.1 sec
[---------------  40%                  ] 817 of 2000 complete in 252.8 sec
[---------------  40%                  ] 819 of 2000 complete in 253.4 sec
[---------------  41%                  ] 821 of 2000 complete in 254.0 sec
[---------------  41%                  ] 823 of 2000 complete in 254.6 sec
[---------------  41%                  ] 825 of 2000 complete in 255.2 sec
[---------------  41%                  ] 827 of 2000 complete in 255.9 sec
[---------------  41%                  ] 829 of 2000 complete in 256.5 sec
[---------------  41%                  ] 831 of 2000 complete in 257.1 sec
[---------------  41%                  ] 833 of 2000 complete in 257.7 sec
[---------------  41%                  ] 835 of 2000 complete in 258.3 sec
[---------------  41%                  ] 837 of 2000 complete in 258.9 sec
[---------------  41%                  ] 839 of 2000 complete in 259.5 sec
[---------------  42%                  ] 841 of 2000 complete in 260.2 sec
[---------------- 42%                  ] 843 of 2000 complete in 260.8 sec
[---------------- 42%                  ] 845 of 2000 complete in 261.5 sec
[---------------- 42%                  ] 847 of 2000 complete in 262.1 sec
[---------------- 42%                  ] 849 of 2000 complete in 262.7 sec
[---------------- 42%                  ] 851 of 2000 complete in 263.4 sec
[---------------- 42%                  ] 853 of 2000 complete in 264.0 sec
[---------------- 42%                  ] 855 of 2000 complete in 264.6 sec
[---------------- 42%                  ] 857 of 2000 complete in 265.2 sec
[---------------- 42%                  ] 859 of 2000 complete in 265.8 sec
[---------------- 43%                  ] 861 of 2000 complete in 266.4 sec
[---------------- 43%                  ] 863 of 2000 complete in 267.0 sec
[---------------- 43%                  ] 865 of 2000 complete in 267.6 sec
[---------------- 43%                  ] 867 of 2000 complete in 268.3 sec
[---------------- 43%                  ] 869 of 2000 complete in 268.8 sec
[---------------- 43%                  ] 871 of 2000 complete in 269.5 sec
[---------------- 43%                  ] 873 of 2000 complete in 270.1 sec
[---------------- 43%                  ] 875 of 2000 complete in 270.7 sec
[---------------- 43%                  ] 877 of 2000 complete in 271.3 sec
[---------------- 43%                  ] 879 of 2000 complete in 272.0 sec
[---------------- 44%                  ] 881 of 2000 complete in 272.6 sec
[---------------- 44%                  ] 883 of 2000 complete in 273.2 sec
[---------------- 44%                  ] 885 of 2000 complete in 273.9 sec
[---------------- 44%                  ] 887 of 2000 complete in 274.5 sec
[---------------- 44%                  ] 889 of 2000 complete in 275.1 sec
[---------------- 44%                  ] 891 of 2000 complete in 275.7 sec
[---------------- 44%                  ] 893 of 2000 complete in 276.3 sec
[-----------------44%                  ] 895 of 2000 complete in 276.9 sec
[-----------------44%                  ] 897 of 2000 complete in 277.5 sec
[-----------------44%                  ] 899 of 2000 complete in 278.2 sec
[-----------------45%                  ] 901 of 2000 complete in 278.8 sec
[-----------------45%                  ] 903 of 2000 complete in 279.4 sec
[-----------------45%                  ] 905 of 2000 complete in 280.0 sec
[-----------------45%                  ] 907 of 2000 complete in 280.6 sec
[-----------------45%                  ] 909 of 2000 complete in 281.2 sec
[-----------------45%                  ] 911 of 2000 complete in 281.8 sec
[-----------------45%                  ] 913 of 2000 complete in 282.4 sec
[-----------------45%                  ] 915 of 2000 complete in 283.1 sec
[-----------------45%                  ] 917 of 2000 complete in 283.7 sec
[-----------------45%                  ] 919 of 2000 complete in 284.3 sec
[-----------------46%                  ] 921 of 2000 complete in 284.9 sec
[-----------------46%                  ] 923 of 2000 complete in 285.5 sec
[-----------------46%                  ] 925 of 2000 complete in 286.1 sec
[-----------------46%                  ] 927 of 2000 complete in 286.7 sec
[-----------------46%                  ] 929 of 2000 complete in 287.3 sec
[-----------------46%                  ] 931 of 2000 complete in 287.9 sec
[-----------------46%                  ] 933 of 2000 complete in 288.5 sec
[-----------------46%                  ] 935 of 2000 complete in 289.2 sec
[-----------------46%                  ] 937 of 2000 complete in 289.8 sec
[-----------------46%                  ] 939 of 2000 complete in 290.4 sec
[-----------------47%                  ] 941 of 2000 complete in 291.0 sec
[-----------------47%                  ] 943 of 2000 complete in 291.6 sec
[-----------------47%                  ] 945 of 2000 complete in 292.2 sec
[-----------------47%                  ] 947 of 2000 complete in 292.8 sec
[-----------------47%                  ] 949 of 2000 complete in 293.4 sec
[-----------------47%                  ] 951 of 2000 complete in 294.0 sec
[-----------------47%                  ] 953 of 2000 complete in 294.6 sec
[-----------------47%                  ] 955 of 2000 complete in 295.3 sec
[-----------------47%                  ] 957 of 2000 complete in 295.9 sec
[-----------------47%                  ] 959 of 2000 complete in 291.3 sec
[-----------------48%                  ] 961 of 2000 complete in 291.9 sec
[-----------------48%                  ] 963 of 2000 complete in 292.5 sec
[-----------------48%                  ] 965 of 2000 complete in 293.1 sec
[-----------------48%                  ] 967 of 2000 complete in 293.7 sec
[-----------------48%                  ] 969 of 2000 complete in 294.2 sec
[-----------------48%                  ] 971 of 2000 complete in 294.8 sec
[-----------------48%                  ] 973 of 2000 complete in 295.4 sec
[-----------------48%                  ] 975 of 2000 complete in 296.0 sec
[-----------------48%                  ] 977 of 2000 complete in 296.6 sec
[-----------------48%                  ] 979 of 2000 complete in 297.2 sec
[-----------------49%                  ] 981 of 2000 complete in 297.7 sec
[-----------------49%                  ] 983 of 2000 complete in 298.3 sec
[-----------------49%                  ] 985 of 2000 complete in 298.9 sec
[-----------------49%                  ] 987 of 2000 complete in 299.5 sec
[-----------------49%                  ] 989 of 2000 complete in 300.1 sec
[-----------------49%                  ] 991 of 2000 complete in 300.7 sec
[-----------------49%                  ] 993 of 2000 complete in 301.3 sec
[-----------------49%                  ] 995 of 2000 complete in 301.9 sec
[-----------------49%                  ] 997 of 2000 complete in 302.6 sec
[-----------------49%                  ] 999 of 2000 complete in 303.2 sec
[-----------------50%                  ] 1001 of 2000 complete in 303.8 sec
[-----------------50%                  ] 1003 of 2000 complete in 304.4 sec
[-----------------50%                  ] 1005 of 2000 complete in 305.0 sec
[-----------------50%                  ] 1007 of 2000 complete in 305.6 sec
[-----------------50%                  ] 1009 of 2000 complete in 306.2 sec
[-----------------50%                  ] 1011 of 2000 complete in 306.8 sec
[-----------------50%                  ] 1013 of 2000 complete in 307.4 sec
[-----------------50%                  ] 1015 of 2000 complete in 308.0 sec
[-----------------50%                  ] 1017 of 2000 complete in 308.6 sec
[-----------------50%                  ] 1019 of 2000 complete in 309.2 sec
[-----------------51%                  ] 1021 of 2000 complete in 309.7 sec
[-----------------51%                  ] 1023 of 2000 complete in 310.3 sec
[-----------------51%                  ] 1025 of 2000 complete in 311.0 sec
[-----------------51%                  ] 1027 of 2000 complete in 311.6 sec
[-----------------51%                  ] 1029 of 2000 complete in 312.2 sec
[-----------------51%                  ] 1031 of 2000 complete in 312.8 sec
[-----------------51%                  ] 1033 of 2000 complete in 313.4 sec
[-----------------51%                  ] 1035 of 2000 complete in 314.0 sec
[-----------------51%                  ] 1037 of 2000 complete in 314.6 sec
[-----------------51%                  ] 1039 of 2000 complete in 315.2 sec
[-----------------52%                  ] 1041 of 2000 complete in 315.8 sec
[-----------------52%                  ] 1043 of 2000 complete in 316.4 sec
[-----------------52%                  ] 1045 of 2000 complete in 317.0 sec
[-----------------52%                  ] 1047 of 2000 complete in 317.6 sec
[-----------------52%                  ] 1049 of 2000 complete in 318.2 sec
[-----------------52%                  ] 1051 of 2000 complete in 318.8 sec
[-----------------52%                  ] 1053 of 2000 complete in 319.5 sec
[-----------------52%                  ] 1055 of 2000 complete in 320.1 sec
[-----------------52%                  ] 1057 of 2000 complete in 320.7 sec
[-----------------52%                  ] 1059 of 2000 complete in 321.3 sec
[-----------------53%                  ] 1061 of 2000 complete in 321.9 sec
[-----------------53%                  ] 1063 of 2000 complete in 322.5 sec
[-----------------53%                  ] 1065 of 2000 complete in 323.1 sec
[-----------------53%                  ] 1067 of 2000 complete in 323.7 sec
[-----------------53%                  ] 1069 of 2000 complete in 324.3 sec
[-----------------53%                  ] 1071 of 2000 complete in 324.9 sec
[-----------------53%                  ] 1073 of 2000 complete in 325.5 sec
[-----------------53%                  ] 1075 of 2000 complete in 326.1 sec
[-----------------53%                  ] 1077 of 2000 complete in 326.7 sec
[-----------------53%                  ] 1079 of 2000 complete in 327.3 sec
[-----------------54%                  ] 1081 of 2000 complete in 327.9 sec
[-----------------54%                  ] 1083 of 2000 complete in 328.5 sec
[-----------------54%                  ] 1085 of 2000 complete in 329.1 sec
[-----------------54%                  ] 1087 of 2000 complete in 329.7 sec
[-----------------54%                  ] 1089 of 2000 complete in 330.3 sec
[-----------------54%                  ] 1091 of 2000 complete in 330.9 sec
[-----------------54%                  ] 1093 of 2000 complete in 331.5 sec
[-----------------54%                  ] 1095 of 2000 complete in 332.2 sec
[-----------------54%                  ] 1097 of 2000 complete in 332.8 sec
[-----------------54%                  ] 1099 of 2000 complete in 333.4 sec
[-----------------55%                  ] 1101 of 2000 complete in 334.0 sec
[-----------------55%                  ] 1103 of 2000 complete in 334.6 sec
[-----------------55%                  ] 1105 of 2000 complete in 335.2 sec
[-----------------55%-                 ] 1107 of 2000 complete in 335.8 sec
[-----------------55%-                 ] 1109 of 2000 complete in 336.4 sec
[-----------------55%-                 ] 1111 of 2000 complete in 337.0 sec
[-----------------55%-                 ] 1113 of 2000 complete in 337.6 sec
[-----------------55%-                 ] 1115 of 2000 complete in 338.2 sec
[-----------------55%-                 ] 1117 of 2000 complete in 338.8 sec
[-----------------55%-                 ] 1119 of 2000 complete in 339.4 sec
[-----------------56%-                 ] 1121 of 2000 complete in 340.0 sec
[-----------------56%-                 ] 1123 of 2000 complete in 340.6 sec
[-----------------56%-                 ] 1125 of 2000 complete in 341.2 sec
[-----------------56%-                 ] 1127 of 2000 complete in 341.8 sec
[-----------------56%-                 ] 1129 of 2000 complete in 342.4 sec
[-----------------56%-                 ] 1131 of 2000 complete in 343.1 sec
[-----------------56%-                 ] 1133 of 2000 complete in 343.6 sec
[-----------------56%-                 ] 1135 of 2000 complete in 344.3 sec
[-----------------56%-                 ] 1137 of 2000 complete in 344.9 sec
[-----------------56%-                 ] 1139 of 2000 complete in 345.5 sec
[-----------------57%-                 ] 1141 of 2000 complete in 346.1 sec
[-----------------57%-                 ] 1143 of 2000 complete in 346.7 sec
[-----------------57%-                 ] 1145 of 2000 complete in 347.3 sec
[-----------------57%-                 ] 1147 of 2000 complete in 347.9 sec
[-----------------57%-                 ] 1149 of 2000 complete in 348.5 sec
[-----------------57%-                 ] 1151 of 2000 complete in 349.1 sec
[-----------------57%-                 ] 1153 of 2000 complete in 349.7 sec
[-----------------57%-                 ] 1155 of 2000 complete in 350.3 sec
[-----------------57%-                 ] 1157 of 2000 complete in 350.9 sec
[-----------------57%--                ] 1159 of 2000 complete in 351.6 sec
[-----------------58%--                ] 1161 of 2000 complete in 352.2 sec
[-----------------58%--                ] 1163 of 2000 complete in 352.7 sec
[-----------------58%--                ] 1165 of 2000 complete in 353.4 sec
[-----------------58%--                ] 1167 of 2000 complete in 353.9 sec
[-----------------58%--                ] 1169 of 2000 complete in 354.6 sec
[-----------------58%--                ] 1171 of 2000 complete in 355.1 sec
[-----------------58%--                ] 1173 of 2000 complete in 355.7 sec

[-----------------47%                  ] 957 of 2000 complete in 294.3 sec
[-----------------47%                  ] 959 of 2000 complete in 295.0 sec
[-----------------48%                  ] 961 of 2000 complete in 295.5 sec
[-----------------48%                  ] 963 of 2000 complete in 296.2 sec
[-----------------48%                  ] 965 of 2000 complete in 296.8 sec
[-----------------48%                  ] 967 of 2000 complete in 297.4 sec
[-----------------48%                  ] 969 of 2000 complete in 298.0 sec
[-----------------48%                  ] 971 of 2000 complete in 298.6 sec
[-----------------48%                  ] 973 of 2000 complete in 299.2 sec
[-----------------48%                  ] 975 of 2000 complete in 299.7 sec
[-----------------48%                  ] 977 of 2000 complete in 300.3 sec
[-----------------48%                  ] 979 of 2000 complete in 300.9 sec
[-----------------49%                  ] 981 of 2000 complete in 301.6 sec
[-----------------49%                  ] 983 of 2000 complete in 302.2 sec
[-----------------49%                  ] 985 of 2000 complete in 302.8 sec
[-----------------49%                  ] 987 of 2000 complete in 303.4 sec
[-----------------49%                  ] 989 of 2000 complete in 303.9 sec
[-----------------49%                  ] 991 of 2000 complete in 304.6 sec
[-----------------49%                  ] 993 of 2000 complete in 305.1 sec
[-----------------49%                  ] 995 of 2000 complete in 305.7 sec
[-----------------49%                  ] 997 of 2000 complete in 306.3 sec
[-----------------49%                  ] 999 of 2000 complete in 306.9 sec
[-----------------50%                  ] 1001 of 2000 complete in 307.5 sec
[-----------------50%                  ] 1003 of 2000 complete in 308.1 sec
[-----------------50%                  ] 1005 of 2000 complete in 308.8 sec
[-----------------50%                  ] 1007 of 2000 complete in 309.4 sec
[-----------------50%                  ] 1009 of 2000 complete in 310.0 sec
[-----------------50%                  ] 1011 of 2000 complete in 310.6 sec
[-----------------50%                  ] 1013 of 2000 complete in 311.1 sec
[-----------------50%                  ] 1015 of 2000 complete in 311.8 sec
[-----------------50%                  ] 1017 of 2000 complete in 312.4 sec
[-----------------50%                  ] 1019 of 2000 complete in 313.0 sec
[-----------------51%                  ] 1021 of 2000 complete in 313.6 sec
[-----------------51%                  ] 1023 of 2000 complete in 314.2 sec
[-----------------51%                  ] 1025 of 2000 complete in 314.8 sec
[-----------------51%                  ] 1027 of 2000 complete in 315.4 sec
[-----------------51%                  ] 1029 of 2000 complete in 316.0 sec
[-----------------51%                  ] 1031 of 2000 complete in 316.6 sec
[-----------------51%                  ] 1033 of 2000 complete in 317.2 sec
[-----------------51%                  ] 1035 of 2000 complete in 317.8 sec
[-----------------51%                  ] 1037 of 2000 complete in 318.4 sec
[-----------------51%                  ] 1039 of 2000 complete in 319.0 sec
[-----------------52%                  ] 1041 of 2000 complete in 319.6 sec
[-----------------52%                  ] 1043 of 2000 complete in 320.3 sec
[-----------------52%                  ] 1045 of 2000 complete in 320.9 sec
[-----------------52%                  ] 1047 of 2000 complete in 321.5 sec
[-----------------52%                  ] 1049 of 2000 complete in 322.1 sec
[-----------------52%                  ] 1051 of 2000 complete in 322.7 sec
[-----------------52%                  ] 1053 of 2000 complete in 323.3 sec
[-----------------52%                  ] 1055 of 2000 complete in 323.9 sec
[-----------------52%                  ] 1057 of 2000 complete in 324.5 sec
[-----------------52%                  ] 1059 of 2000 complete in 325.0 sec
[-----------------53%                  ] 1061 of 2000 complete in 325.6 sec
[-----------------53%                  ] 1063 of 2000 complete in 326.2 sec
[-----------------53%                  ] 1065 of 2000 complete in 326.8 sec
[-----------------53%                  ] 1067 of 2000 complete in 327.4 sec
[-----------------53%                  ] 1069 of 2000 complete in 328.0 sec
[-----------------53%                  ] 1071 of 2000 complete in 328.6 sec
[-----------------53%                  ] 1073 of 2000 complete in 329.2 sec
[-----------------53%                  ] 1075 of 2000 complete in 329.9 sec
[-----------------53%                  ] 1077 of 2000 complete in 330.5 sec
[-----------------53%                  ] 1079 of 2000 complete in 331.1 sec
[-----------------54%                  ] 1081 of 2000 complete in 331.7 sec
[-----------------54%                  ] 1083 of 2000 complete in 332.3 sec
[-----------------54%                  ] 1085 of 2000 complete in 332.9 sec
[-----------------54%                  ] 1087 of 2000 complete in 333.5 sec
[-----------------54%                  ] 1089 of 2000 complete in 334.1 sec
[-----------------54%                  ] 1091 of 2000 complete in 334.7 sec
[-----------------54%                  ] 1093 of 2000 complete in 335.3 sec
[-----------------54%                  ] 1095 of 2000 complete in 335.9 sec
[-----------------54%                  ] 1097 of 2000 complete in 336.5 sec
[-----------------54%                  ] 1099 of 2000 complete in 337.1 sec
[-----------------55%                  ] 1101 of 2000 complete in 337.7 sec
[-----------------55%                  ] 1103 of 2000 complete in 338.3 sec
[-----------------55%                  ] 1105 of 2000 complete in 338.9 sec
[-----------------55%-                 ] 1107 of 2000 complete in 339.5 sec
[-----------------55%-                 ] 1109 of 2000 complete in 340.1 sec
[-----------------55%-                 ] 1111 of 2000 complete in 340.7 sec
[-----------------55%-                 ] 1113 of 2000 complete in 341.3 sec
[-----------------55%-                 ] 1115 of 2000 complete in 341.9 sec
[-----------------55%-                 ] 1117 of 2000 complete in 342.5 sec
[-----------------55%-                 ] 1119 of 2000 complete in 343.1 sec
[-----------------56%-                 ] 1121 of 2000 complete in 343.7 sec
[-----------------56%-                 ] 1123 of 2000 complete in 344.4 sec
[-----------------56%-                 ] 1125 of 2000 complete in 345.0 sec
[-----------------56%-                 ] 1127 of 2000 complete in 345.6 sec
[-----------------56%-                 ] 1129 of 2000 complete in 346.2 sec
[-----------------56%-                 ] 1131 of 2000 complete in 346.8 sec
[-----------------56%-                 ] 1133 of 2000 complete in 347.4 sec
[-----------------56%-                 ] 1135 of 2000 complete in 348.0 sec
[-----------------56%-                 ] 1137 of 2000 complete in 348.6 sec
[-----------------56%-                 ] 1139 of 2000 complete in 349.2 sec
[-----------------57%-                 ] 1141 of 2000 complete in 349.8 sec
[-----------------57%-                 ] 1143 of 2000 complete in 350.4 sec
[-----------------57%-                 ] 1145 of 2000 complete in 351.0 sec
[-----------------57%-                 ] 1147 of 2000 complete in 351.6 sec
[-----------------57%-                 ] 1149 of 2000 complete in 352.2 sec
[-----------------57%-                 ] 1151 of 2000 complete in 352.8 sec
[-----------------57%-                 ] 1153 of 2000 complete in 353.5 sec
[-----------------57%-                 ] 1155 of 2000 complete in 354.1 sec
[-----------------57%-                 ] 1157 of 2000 complete in 354.7 sec
[-----------------57%--                ] 1159 of 2000 complete in 355.3 sec
[-----------------58%--                ] 1161 of 2000 complete in 355.9 sec
[-----------------58%--                ] 1163 of 2000 complete in 356.5 sec
[-----------------58%--                ] 1165 of 2000 complete in 357.1 sec
[-----------------58%--                ] 1167 of 2000 complete in 357.7 sec
[-----------------58%--                ] 1169 of 2000 complete in 358.3 sec
[-----------------58%--                ] 1171 of 2000 complete in 359.0 sec
[-----------------47%                  ] 959 of 2000 complete in 294.6 sec
[-----------------48%                  ] 961 of 2000 complete in 295.2 sec
[-----------------48%                  ] 963 of 2000 complete in 295.8 sec
[-----------------48%                  ] 965 of 2000 complete in 296.4 sec
[-----------------48%                  ] 967 of 2000 complete in 297.0 sec
[-----------------48%                  ] 969 of 2000 complete in 297.6 sec
[-----------------48%                  ] 971 of 2000 complete in 298.2 sec
[-----------------48%                  ] 973 of 2000 complete in 298.8 sec
[-----------------48%                  ] 975 of 2000 complete in 299.4 sec
[-----------------48%                  ] 977 of 2000 complete in 300.0 sec
[-----------------48%                  ] 979 of 2000 complete in 300.6 sec
[-----------------49%                  ] 981 of 2000 complete in 301.2 sec
[-----------------49%                  ] 983 of 2000 complete in 301.8 sec
[-----------------49%                  ] 985 of 2000 complete in 302.4 sec
[-----------------49%                  ] 987 of 2000 complete in 303.1 sec
[-----------------49%                  ] 989 of 2000 complete in 303.7 sec
[-----------------49%                  ] 991 of 2000 complete in 304.3 sec
[-----------------49%                  ] 993 of 2000 complete in 304.9 sec
[-----------------49%                  ] 995 of 2000 complete in 305.5 sec
[-----------------49%                  ] 997 of 2000 complete in 306.1 sec
[-----------------49%                  ] 999 of 2000 complete in 306.7 sec
[-----------------50%                  ] 1001 of 2000 complete in 307.3 sec
[-----------------50%                  ] 1003 of 2000 complete in 307.9 sec
[-----------------50%                  ] 1005 of 2000 complete in 308.5 sec
[-----------------50%                  ] 1007 of 2000 complete in 309.1 sec
[-----------------50%                  ] 1009 of 2000 complete in 309.7 sec
[-----------------50%                  ] 1011 of 2000 complete in 310.3 sec
[-----------------50%                  ] 1013 of 2000 complete in 310.9 sec
[-----------------50%                  ] 1015 of 2000 complete in 311.5 sec
[-----------------50%                  ] 1017 of 2000 complete in 312.1 sec
[-----------------50%                  ] 1019 of 2000 complete in 312.7 sec
[-----------------51%                  ] 1021 of 2000 complete in 313.3 sec
[-----------------51%                  ] 1023 of 2000 complete in 313.9 sec
[-----------------51%                  ] 1025 of 2000 complete in 314.5 sec
[-----------------51%                  ] 1027 of 2000 complete in 315.2 sec
[-----------------51%                  ] 1029 of 2000 complete in 315.8 sec
[-----------------51%                  ] 1031 of 2000 complete in 316.4 sec
[-----------------51%                  ] 1033 of 2000 complete in 317.0 sec
[-----------------51%                  ] 1035 of 2000 complete in 317.6 sec
[-----------------51%                  ] 1037 of 2000 complete in 318.3 sec
[-----------------51%                  ] 1039 of 2000 complete in 318.9 sec
[-----------------52%                  ] 1041 of 2000 complete in 319.6 sec
[-----------------52%                  ] 1043 of 2000 complete in 320.2 sec
[-----------------52%                  ] 1045 of 2000 complete in 320.8 sec
[-----------------52%                  ] 1047 of 2000 complete in 321.4 sec
[-----------------52%                  ] 1049 of 2000 complete in 322.0 sec
[-----------------52%                  ] 1051 of 2000 complete in 322.6 sec
[-----------------52%                  ] 1053 of 2000 complete in 323.2 sec
[-----------------52%                  ] 1055 of 2000 complete in 323.8 sec
[-----------------52%                  ] 1057 of 2000 complete in 324.4 sec
[-----------------52%                  ] 1059 of 2000 complete in 325.0 sec
[-----------------53%                  ] 1061 of 2000 complete in 325.6 sec
[-----------------53%                  ] 1063 of 2000 complete in 326.2 sec
[-----------------53%                  ] 1065 of 2000 complete in 326.8 sec
[-----------------53%                  ] 1067 of 2000 complete in 327.4 sec
[-----------------53%                  ] 1069 of 2000 complete in 328.0 sec
[-----------------53%                  ] 1071 of 2000 complete in 328.6 sec
[-----------------53%                  ] 1073 of 2000 complete in 329.2 sec
[-----------------53%                  ] 1075 of 2000 complete in 329.9 sec
[-----------------53%                  ] 1077 of 2000 complete in 330.5 sec
[-----------------53%                  ] 1079 of 2000 complete in 331.1 sec
[-----------------54%                  ] 1081 of 2000 complete in 331.7 sec
[-----------------54%                  ] 1083 of 2000 complete in 332.3 sec
[-----------------54%                  ] 1085 of 2000 complete in 332.9 sec
[-----------------54%                  ] 1087 of 2000 complete in 333.6 sec
[-----------------54%                  ] 1089 of 2000 complete in 334.2 sec
[-----------------54%                  ] 1091 of 2000 complete in 334.8 sec
[-----------------54%                  ] 1093 of 2000 complete in 335.3 sec
[-----------------54%                  ] 1095 of 2000 complete in 336.0 sec
[-----------------54%                  ] 1097 of 2000 complete in 336.6 sec
[-----------------54%                  ] 1099 of 2000 complete in 337.2 sec
[-----------------55%                  ] 1101 of 2000 complete in 337.8 sec
[-----------------55%                  ] 1103 of 2000 complete in 338.4 sec
[-----------------55%                  ] 1105 of 2000 complete in 339.0 sec
[-----------------55%-                 ] 1107 of 2000 complete in 339.6 sec
[-----------------55%-                 ] 1109 of 2000 complete in 340.2 sec
[-----------------55%-                 ] 1111 of 2000 complete in 340.8 sec
[-----------------55%-                 ] 1113 of 2000 complete in 341.4 sec
[-----------------55%-                 ] 1115 of 2000 complete in 342.0 sec
[-----------------55%-                 ] 1117 of 2000 complete in 342.6 sec
[-----------------55%-                 ] 1119 of 2000 complete in 343.2 sec
[-----------------56%-                 ] 1121 of 2000 complete in 343.8 sec
[-----------------56%-                 ] 1123 of 2000 complete in 344.4 sec
[-----------------56%-                 ] 1125 of 2000 complete in 345.1 sec
[-----------------56%-                 ] 1127 of 2000 complete in 345.7 sec
[-----------------56%-                 ] 1129 of 2000 complete in 346.3 sec
[-----------------56%-                 ] 1131 of 2000 complete in 346.9 sec
[-----------------56%-                 ] 1133 of 2000 complete in 347.5 sec
[-----------------56%-                 ] 1135 of 2000 complete in 348.1 sec
[-----------------56%-                 ] 1137 of 2000 complete in 348.7 sec
[-----------------56%-                 ] 1139 of 2000 complete in 349.4 sec
[-----------------57%-                 ] 1141 of 2000 complete in 350.0 sec
[-----------------57%-                 ] 1143 of 2000 complete in 350.6 sec
[-----------------57%-                 ] 1145 of 2000 complete in 351.2 sec
[-----------------57%-                 ] 1147 of 2000 complete in 351.8 sec
[-----------------57%-                 ] 1149 of 2000 complete in 352.4 sec
[-----------------57%-                 ] 1151 of 2000 complete in 353.1 sec
[-----------------57%-                 ] 1153 of 2000 complete in 353.7 sec
[-----------------57%-                 ] 1155 of 2000 complete in 354.3 sec
[-----------------57%-                 ] 1157 of 2000 complete in 354.9 sec
[-----------------57%--                ] 1159 of 2000 complete in 355.5 sec
[-----------------58%--                ] 1161 of 2000 complete in 356.1 sec
[-----------------58%--                ] 1163 of 2000 complete in 356.7 sec
[-----------------58%--                ] 1165 of 2000 complete in 357.3 sec
[-----------------58%--                ] 1167 of 2000 complete in 357.9 sec
[-----------------58%--                ] 1169 of 2000 complete in 358.6 sec
[-----------------58%--                ] 1171 of 2000 complete in 359.2 sec
[-----------------58%--                ] 1173 of 2000 complete in 359.8 sec

[-----------------47%                  ] 959 of 2000 complete in 296.5 sec
[-----------------48%                  ] 961 of 2000 complete in 297.1 sec
[-----------------48%                  ] 963 of 2000 complete in 297.7 sec
[-----------------48%                  ] 965 of 2000 complete in 298.3 sec
[-----------------48%                  ] 967 of 2000 complete in 298.9 sec
[-----------------48%                  ] 969 of 2000 complete in 299.6 sec
[-----------------48%                  ] 971 of 2000 complete in 300.1 sec
[-----------------48%                  ] 973 of 2000 complete in 300.8 sec
[-----------------48%                  ] 975 of 2000 complete in 301.4 sec
[-----------------48%                  ] 977 of 2000 complete in 302.0 sec
[-----------------48%                  ] 979 of 2000 complete in 302.6 sec
[-----------------49%                  ] 981 of 2000 complete in 303.2 sec
[-----------------49%                  ] 983 of 2000 complete in 303.8 sec
[-----------------49%                  ] 985 of 2000 complete in 304.4 sec
[-----------------49%                  ] 987 of 2000 complete in 305.1 sec
[-----------------49%                  ] 989 of 2000 complete in 305.7 sec
[-----------------49%                  ] 991 of 2000 complete in 306.3 sec
[-----------------49%                  ] 993 of 2000 complete in 306.8 sec
[-----------------49%                  ] 995 of 2000 complete in 307.4 sec
[-----------------49%                  ] 997 of 2000 complete in 308.1 sec
[-----------------49%                  ] 999 of 2000 complete in 308.6 sec
[-----------------50%                  ] 1001 of 2000 complete in 309.3 sec
[-----------------50%                  ] 1003 of 2000 complete in 309.9 sec
[-----------------50%                  ] 1005 of 2000 complete in 310.5 sec
[-----------------50%                  ] 1007 of 2000 complete in 311.1 sec
[-----------------50%                  ] 1009 of 2000 complete in 311.7 sec
[-----------------50%                  ] 1011 of 2000 complete in 312.3 sec
[-----------------50%                  ] 1013 of 2000 complete in 313.0 sec
[-----------------50%                  ] 1015 of 2000 complete in 313.6 sec
[-----------------50%                  ] 1017 of 2000 complete in 314.2 sec
[-----------------50%                  ] 1019 of 2000 complete in 314.8 sec
[-----------------51%                  ] 1021 of 2000 complete in 315.4 sec
[-----------------51%                  ] 1023 of 2000 complete in 316.0 sec
[-----------------51%                  ] 1025 of 2000 complete in 316.6 sec
[-----------------51%                  ] 1027 of 2000 complete in 317.2 sec
[-----------------51%                  ] 1029 of 2000 complete in 317.9 sec
[-----------------51%                  ] 1031 of 2000 complete in 318.5 sec
[-----------------51%                  ] 1033 of 2000 complete in 319.1 sec
[-----------------51%                  ] 1035 of 2000 complete in 319.8 sec
[-----------------51%                  ] 1037 of 2000 complete in 320.4 sec
[-----------------51%                  ] 1039 of 2000 complete in 321.0 sec
[-----------------52%                  ] 1041 of 2000 complete in 321.6 sec
[-----------------52%                  ] 1043 of 2000 complete in 322.3 sec
[-----------------52%                  ] 1045 of 2000 complete in 322.9 sec
[-----------------52%                  ] 1047 of 2000 complete in 323.5 sec
[-----------------52%                  ] 1049 of 2000 complete in 324.1 sec
[-----------------52%                  ] 1051 of 2000 complete in 324.7 sec
[-----------------52%                  ] 1053 of 2000 complete in 325.3 sec
[-----------------52%                  ] 1055 of 2000 complete in 325.9 sec
[-----------------52%                  ] 1057 of 2000 complete in 326.5 sec
[-----------------52%                  ] 1059 of 2000 complete in 327.1 sec
[-----------------53%                  ] 1061 of 2000 complete in 327.7 sec
[-----------------53%                  ] 1063 of 2000 complete in 328.3 sec
[-----------------53%                  ] 1065 of 2000 complete in 328.9 sec
[-----------------53%                  ] 1067 of 2000 complete in 329.5 sec
[-----------------53%                  ] 1069 of 2000 complete in 330.2 sec
[-----------------53%                  ] 1071 of 2000 complete in 330.8 sec
[-----------------53%                  ] 1073 of 2000 complete in 331.4 sec
[-----------------53%                  ] 1075 of 2000 complete in 332.0 sec
[-----------------53%                  ] 1077 of 2000 complete in 332.6 sec
[-----------------53%                  ] 1079 of 2000 complete in 333.2 sec
[-----------------54%                  ] 1081 of 2000 complete in 333.9 sec
[-----------------54%                  ] 1083 of 2000 complete in 334.5 sec
[-----------------54%                  ] 1085 of 2000 complete in 335.1 sec
[-----------------54%                  ] 1087 of 2000 complete in 335.7 sec
[-----------------54%                  ] 1089 of 2000 complete in 336.3 sec
[-----------------54%                  ] 1091 of 2000 complete in 336.9 sec
[-----------------54%                  ] 1093 of 2000 complete in 337.6 sec
[-----------------54%                  ] 1095 of 2000 complete in 338.2 sec
[-----------------54%                  ] 1097 of 2000 complete in 338.8 sec
[-----------------54%                  ] 1099 of 2000 complete in 339.4 sec
[-----------------55%                  ] 1101 of 2000 complete in 340.0 sec
[-----------------55%                  ] 1103 of 2000 complete in 340.6 sec
[-----------------55%                  ] 1105 of 2000 complete in 341.2 sec
[-----------------55%-                 ] 1107 of 2000 complete in 341.8 sec
[-----------------55%-                 ] 1109 of 2000 complete in 342.4 sec
[-----------------55%-                 ] 1111 of 2000 complete in 343.1 sec
[-----------------55%-                 ] 1113 of 2000 complete in 343.7 sec
[-----------------55%-                 ] 1115 of 2000 complete in 344.3 sec
[-----------------55%-                 ] 1117 of 2000 complete in 344.9 sec
[-----------------55%-                 ] 1119 of 2000 complete in 345.5 sec
[-----------------56%-                 ] 1121 of 2000 complete in 346.1 sec
[-----------------56%-                 ] 1123 of 2000 complete in 346.7 sec
[-----------------56%-                 ] 1125 of 2000 complete in 347.3 sec
[-----------------56%-                 ] 1127 of 2000 complete in 348.0 sec
[-----------------56%-                 ] 1129 of 2000 complete in 348.5 sec
[-----------------56%-                 ] 1131 of 2000 complete in 349.2 sec
[-----------------56%-                 ] 1133 of 2000 complete in 349.8 sec
[-----------------56%-                 ] 1135 of 2000 complete in 350.4 sec
[-----------------56%-                 ] 1137 of 2000 complete in 351.0 sec
[-----------------56%-                 ] 1139 of 2000 complete in 351.7 sec
[-----------------57%-                 ] 1141 of 2000 complete in 352.3 sec
[-----------------57%-                 ] 1143 of 2000 complete in 352.9 sec
[-----------------57%-                 ] 1145 of 2000 complete in 353.5 sec
[-----------------57%-                 ] 1147 of 2000 complete in 354.1 sec
[-----------------57%-                 ] 1149 of 2000 complete in 354.8 sec
[-----------------57%-                 ] 1151 of 2000 complete in 355.3 sec
[-----------------57%-                 ] 1153 of 2000 complete in 355.9 sec
[-----------------57%-                 ] 1155 of 2000 complete in 356.6 sec
[-----------------57%-                 ] 1157 of 2000 complete in 357.2 sec
[-----------------57%--                ] 1159 of 2000 complete in 357.8 sec
[-----------------58%--                ] 1161 of 2000 complete in 358.4 sec
[-----------------58%--                ] 1163 of 2000 complete in 359.0 sec
[-----------------58%--                ] 1165 of 2000 complete in 359.6 sec
[-----------------58%--                ] 1167 of 2000 complete in 360.3 sec
[-----------------58%--                ] 1169 of 2000 complete in 360.9 sec
[-----------------58%--                ] 1171 of 2000 complete in 361.5 sec
[-----------------58%--                ] 1173 of 2000 complete in 362.1 sec
[-----------------58%--                ] 1175 of 2000 complete in 356.3 sec
[-----------------58%--                ] 1177 of 2000 complete in 356.9 sec
[-----------------58%--                ] 1179 of 2000 complete in 357.5 sec
[-----------------59%--                ] 1181 of 2000 complete in 358.1 sec
[-----------------59%--                ] 1183 of 2000 complete in 358.7 sec
[-----------------59%--                ] 1185 of 2000 complete in 359.4 sec
[-----------------59%--                ] 1187 of 2000 complete in 360.0 sec
[-----------------59%--                ] 1189 of 2000 complete in 360.6 sec
[-----------------59%--                ] 1191 of 2000 complete in 361.3 sec
[-----------------59%--                ] 1193 of 2000 complete in 361.9 sec
[-----------------59%--                ] 1195 of 2000 complete in 362.5 sec
[-----------------59%--                ] 1197 of 2000 complete in 363.1 sec
[-----------------59%--                ] 1199 of 2000 complete in 363.7 sec
[-----------------60%--                ] 1201 of 2000 complete in 364.3 sec
[-----------------60%--                ] 1203 of 2000 complete in 364.9 sec
[-----------------60%--                ] 1205 of 2000 complete in 365.5 sec
[-----------------60%--                ] 1207 of 2000 complete in 366.1 sec
[-----------------60%--                ] 1209 of 2000 complete in 366.7 sec
[-----------------60%---               ] 1211 of 2000 complete in 367.3 sec
[-----------------60%---               ] 1213 of 2000 complete in 367.9 sec
[-----------------60%---               ] 1215 of 2000 complete in 368.5 sec
[-----------------60%---               ] 1217 of 2000 complete in 369.1 sec
[-----------------60%---               ] 1219 of 2000 complete in 369.7 sec
[-----------------61%---               ] 1221 of 2000 complete in 370.3 sec
[-----------------61%---               ] 1223 of 2000 complete in 371.0 sec
[-----------------61%---               ] 1225 of 2000 complete in 371.6 sec
[-----------------61%---               ] 1227 of 2000 complete in 372.2 sec
[-----------------61%---               ] 1229 of 2000 complete in 372.8 sec
[-----------------61%---               ] 1231 of 2000 complete in 373.4 sec
[-----------------61%---               ] 1233 of 2000 complete in 374.0 sec
[-----------------61%---               ] 1235 of 2000 complete in 374.6 sec
[-----------------61%---               ] 1237 of 2000 complete in 375.2 sec
[-----------------61%---               ] 1239 of 2000 complete in 375.8 sec
[-----------------62%---               ] 1241 of 2000 complete in 376.5 sec
[-----------------62%---               ] 1243 of 2000 complete in 377.1 sec
[-----------------62%---               ] 1245 of 2000 complete in 377.7 sec
[-----------------62%---               ] 1247 of 2000 complete in 378.3 sec
[-----------------62%---               ] 1249 of 2000 complete in 378.9 sec
[-----------------62%---               ] 1251 of 2000 complete in 379.5 sec
[-----------------62%---               ] 1253 of 2000 complete in 380.1 sec
[-----------------62%---               ] 1255 of 2000 complete in 380.7 sec
[-----------------62%---               ] 1257 of 2000 complete in 381.3 sec
[-----------------62%---               ] 1259 of 2000 complete in 381.9 sec
[-----------------63%---               ] 1261 of 2000 complete in 382.5 sec
[-----------------63%---               ] 1263 of 2000 complete in 383.1 sec
[-----------------63%----              ] 1265 of 2000 complete in 383.7 sec
[-----------------63%----              ] 1267 of 2000 complete in 384.3 sec
[-----------------63%----              ] 1269 of 2000 complete in 384.9 sec
[-----------------63%----              ] 1271 of 2000 complete in 385.5 sec
[-----------------63%----              ] 1273 of 2000 complete in 386.1 sec
[-----------------63%----              ] 1275 of 2000 complete in 386.7 sec
[-----------------63%----              ] 1277 of 2000 complete in 387.3 sec
[-----------------63%----              ] 1279 of 2000 complete in 388.0 sec
[-----------------64%----              ] 1281 of 2000 complete in 388.6 sec
[-----------------64%----              ] 1283 of 2000 complete in 389.1 sec
[-----------------64%----              ] 1285 of 2000 complete in 389.7 sec
[-----------------64%----              ] 1287 of 2000 complete in 390.3 sec
[-----------------64%----              ] 1289 of 2000 complete in 390.9 sec
[-----------------64%----              ] 1291 of 2000 complete in 391.5 sec
[-----------------64%----              ] 1293 of 2000 complete in 392.1 sec
[-----------------64%----              ] 1295 of 2000 complete in 392.7 sec
[-----------------64%----              ] 1297 of 2000 complete in 393.3 sec
[-----------------64%----              ] 1299 of 2000 complete in 393.9 sec
[-----------------65%----              ] 1301 of 2000 complete in 394.6 sec
[-----------------65%----              ] 1303 of 2000 complete in 395.1 sec
[-----------------65%----              ] 1305 of 2000 complete in 395.7 sec
[-----------------65%----              ] 1307 of 2000 complete in 396.4 sec
[-----------------65%----              ] 1309 of 2000 complete in 397.0 sec
[-----------------65%----              ] 1311 of 2000 complete in 397.6 sec
[-----------------65%----              ] 1313 of 2000 complete in 398.2 sec
[-----------------65%----              ] 1315 of 2000 complete in 398.8 sec
[-----------------65%-----             ] 1317 of 2000 complete in 399.4 sec
[-----------------65%-----             ] 1319 of 2000 complete in 400.0 sec
[-----------------66%-----             ] 1321 of 2000 complete in 400.6 sec
[-----------------66%-----             ] 1323 of 2000 complete in 401.2 sec
[-----------------66%-----             ] 1325 of 2000 complete in 401.7 sec
[-----------------66%-----             ] 1327 of 2000 complete in 402.4 sec
[-----------------66%-----             ] 1329 of 2000 complete in 403.0 sec
[-----------------66%-----             ] 1331 of 2000 complete in 403.5 sec
[-----------------66%-----             ] 1333 of 2000 complete in 404.1 sec
[-----------------66%-----             ] 1335 of 2000 complete in 404.7 sec
[-----------------66%-----             ] 1337 of 2000 complete in 405.3 sec
[-----------------66%-----             ] 1339 of 2000 complete in 405.9 sec
[-----------------67%-----             ] 1341 of 2000 complete in 406.5 sec
[-----------------67%-----             ] 1343 of 2000 complete in 407.1 sec
[-----------------67%-----             ] 1345 of 2000 complete in 407.7 sec
[-----------------67%-----             ] 1347 of 2000 complete in 408.3 sec
[-----------------67%-----             ] 1349 of 2000 complete in 408.9 sec
[-----------------67%-----             ] 1351 of 2000 complete in 409.5 sec
[-----------------67%-----             ] 1353 of 2000 complete in 410.1 sec
[-----------------67%-----             ] 1355 of 2000 complete in 410.7 sec
[-----------------67%-----             ] 1357 of 2000 complete in 411.3 sec
[-----------------67%-----             ] 1359 of 2000 complete in 411.9 sec
[-----------------68%-----             ] 1361 of 2000 complete in 412.5 sec
[-----------------68%-----             ] 1363 of 2000 complete in 413.1 sec
[-----------------68%-----             ] 1365 of 2000 complete in 413.7 sec
[-----------------68%-----             ] 1367 of 2000 complete in 414.3 sec
[-----------------68%------            ] 1369 of 2000 complete in 414.8 sec
[-----------------68%------            ] 1371 of 2000 complete in 415.4 sec
[-----------------68%------            ] 1373 of 2000 complete in 416.0 sec
[-----------------68%------            ] 1375 of 2000 complete in 416.6 sec
[-----------------68%------            ] 1377 of 2000 complete in 417.2 sec
[-----------------68%------            ] 1379 of 2000 complete in 417.8 sec
[-----------------69%------            ] 1381 of 2000 complete in 418.4 sec
[-----------------69%------            ] 1383 of 2000 complete in 419.0 sec
[-----------------69%------            ] 1385 of 2000 complete in 419.6 sec
[-----------------69%------            ] 1387 of 2000 complete in 420.2 sec

[-----------------58%--                ] 1173 of 2000 complete in 359.6 sec
[-----------------58%--                ] 1175 of 2000 complete in 360.2 sec
[-----------------58%--                ] 1177 of 2000 complete in 360.8 sec
[-----------------58%--                ] 1179 of 2000 complete in 361.4 sec
[-----------------59%--                ] 1181 of 2000 complete in 362.0 sec
[-----------------59%--                ] 1183 of 2000 complete in 362.6 sec
[-----------------59%--                ] 1185 of 2000 complete in 363.2 sec
[-----------------59%--                ] 1187 of 2000 complete in 363.8 sec
[-----------------59%--                ] 1189 of 2000 complete in 364.4 sec
[-----------------59%--                ] 1191 of 2000 complete in 365.0 sec
[-----------------59%--                ] 1193 of 2000 complete in 365.6 sec
[-----------------59%--                ] 1195 of 2000 complete in 366.2 sec
[-----------------59%--                ] 1197 of 2000 complete in 366.8 sec
[-----------------59%--                ] 1199 of 2000 complete in 367.4 sec
[-----------------60%--                ] 1201 of 2000 complete in 368.1 sec
[-----------------60%--                ] 1203 of 2000 complete in 368.7 sec
[-----------------60%--                ] 1205 of 2000 complete in 369.3 sec
[-----------------60%--                ] 1207 of 2000 complete in 369.9 sec
[-----------------60%--                ] 1209 of 2000 complete in 370.5 sec
[-----------------60%---               ] 1211 of 2000 complete in 371.1 sec
[-----------------60%---               ] 1213 of 2000 complete in 371.7 sec
[-----------------60%---               ] 1215 of 2000 complete in 372.4 sec
[-----------------60%---               ] 1217 of 2000 complete in 373.0 sec
[-----------------60%---               ] 1219 of 2000 complete in 373.6 sec
[-----------------61%---               ] 1221 of 2000 complete in 374.2 sec
[-----------------61%---               ] 1223 of 2000 complete in 374.8 sec
[-----------------61%---               ] 1225 of 2000 complete in 375.4 sec
[-----------------61%---               ] 1227 of 2000 complete in 376.0 sec
[-----------------61%---               ] 1229 of 2000 complete in 376.6 sec
[-----------------61%---               ] 1231 of 2000 complete in 377.2 sec
[-----------------61%---               ] 1233 of 2000 complete in 377.9 sec
[-----------------61%---               ] 1235 of 2000 complete in 378.5 sec
[-----------------61%---               ] 1237 of 2000 complete in 379.1 sec
[-----------------61%---               ] 1239 of 2000 complete in 379.7 sec
[-----------------62%---               ] 1241 of 2000 complete in 380.3 sec
[-----------------62%---               ] 1243 of 2000 complete in 381.0 sec
[-----------------62%---               ] 1245 of 2000 complete in 381.6 sec
[-----------------62%---               ] 1247 of 2000 complete in 382.2 sec
[-----------------62%---               ] 1249 of 2000 complete in 382.8 sec
[-----------------62%---               ] 1251 of 2000 complete in 383.4 sec
[-----------------62%---               ] 1253 of 2000 complete in 384.1 sec
[-----------------62%---               ] 1255 of 2000 complete in 384.7 sec
[-----------------62%---               ] 1257 of 2000 complete in 385.3 sec
[-----------------62%---               ] 1259 of 2000 complete in 385.9 sec
[-----------------63%---               ] 1261 of 2000 complete in 386.5 sec
[-----------------63%---               ] 1263 of 2000 complete in 387.1 sec
[-----------------63%----              ] 1265 of 2000 complete in 387.7 sec
[-----------------63%----              ] 1267 of 2000 complete in 388.3 sec
[-----------------63%----              ] 1269 of 2000 complete in 389.0 sec
[-----------------63%----              ] 1271 of 2000 complete in 389.5 sec
[-----------------63%----              ] 1273 of 2000 complete in 390.2 sec
[-----------------63%----              ] 1275 of 2000 complete in 390.8 sec
[-----------------63%----              ] 1277 of 2000 complete in 391.4 sec
[-----------------63%----              ] 1279 of 2000 complete in 392.0 sec
[-----------------64%----              ] 1281 of 2000 complete in 392.6 sec
[-----------------64%----              ] 1283 of 2000 complete in 393.2 sec
[-----------------64%----              ] 1285 of 2000 complete in 393.8 sec
[-----------------64%----              ] 1287 of 2000 complete in 394.5 sec
[-----------------64%----              ] 1289 of 2000 complete in 395.1 sec
[-----------------64%----              ] 1291 of 2000 complete in 395.7 sec
[-----------------64%----              ] 1293 of 2000 complete in 396.3 sec
[-----------------64%----              ] 1295 of 2000 complete in 396.9 sec
[-----------------64%----              ] 1297 of 2000 complete in 397.6 sec
[-----------------64%----              ] 1299 of 2000 complete in 398.2 sec
[-----------------65%----              ] 1301 of 2000 complete in 398.7 sec
[-----------------65%----              ] 1303 of 2000 complete in 399.4 sec
[-----------------65%----              ] 1305 of 2000 complete in 399.9 sec
[-----------------65%----              ] 1307 of 2000 complete in 400.6 sec
[-----------------65%----              ] 1309 of 2000 complete in 401.2 sec
[-----------------65%----              ] 1311 of 2000 complete in 401.8 sec
[-----------------65%----              ] 1313 of 2000 complete in 402.4 sec
[-----------------65%----              ] 1315 of 2000 complete in 403.0 sec
[-----------------65%-----             ] 1317 of 2000 complete in 403.6 sec
[-----------------65%-----             ] 1319 of 2000 complete in 404.2 sec
[-----------------66%-----             ] 1321 of 2000 complete in 404.8 sec
[-----------------66%-----             ] 1323 of 2000 complete in 405.4 sec
[-----------------66%-----             ] 1325 of 2000 complete in 406.0 sec
[-----------------66%-----             ] 1327 of 2000 complete in 406.6 sec
[-----------------66%-----             ] 1329 of 2000 complete in 407.2 sec
[-----------------66%-----             ] 1331 of 2000 complete in 407.8 sec
[-----------------66%-----             ] 1333 of 2000 complete in 408.4 sec
[-----------------66%-----             ] 1335 of 2000 complete in 409.0 sec
[-----------------66%-----             ] 1337 of 2000 complete in 409.6 sec
[-----------------66%-----             ] 1339 of 2000 complete in 410.2 sec
[-----------------67%-----             ] 1341 of 2000 complete in 410.8 sec
[-----------------67%-----             ] 1343 of 2000 complete in 411.4 sec
[-----------------67%-----             ] 1345 of 2000 complete in 412.0 sec
[-----------------67%-----             ] 1347 of 2000 complete in 412.6 sec
[-----------------67%-----             ] 1349 of 2000 complete in 413.2 sec
[-----------------67%-----             ] 1351 of 2000 complete in 413.8 sec
[-----------------67%-----             ] 1353 of 2000 complete in 414.4 sec
[-----------------67%-----             ] 1355 of 2000 complete in 415.0 sec
[-----------------67%-----             ] 1357 of 2000 complete in 415.6 sec
[-----------------67%-----             ] 1359 of 2000 complete in 416.2 sec
[-----------------68%-----             ] 1361 of 2000 complete in 416.8 sec
[-----------------68%-----             ] 1363 of 2000 complete in 417.4 sec
[-----------------68%-----             ] 1365 of 2000 complete in 418.0 sec
[-----------------68%-----             ] 1367 of 2000 complete in 418.6 sec
[-----------------68%------            ] 1369 of 2000 complete in 419.2 sec
[-----------------68%------            ] 1371 of 2000 complete in 419.8 sec
[-----------------68%------            ] 1373 of 2000 complete in 420.4 sec
[-----------------68%------            ] 1375 of 2000 complete in 421.0 sec
[-----------------68%------            ] 1377 of 2000 complete in 421.6 sec
[-----------------68%------            ] 1379 of 2000 complete in 422.2 sec
[-----------------69%------            ] 1381 of 2000 complete in 422.8 sec
[-----------------69%------            ] 1383 of 2000 complete in 423.4 sec
[-----------------69%------            ] 1385 of 2000 complete in 424.0 sec
[-----------------58%--                ] 1175 of 2000 complete in 360.4 sec
[-----------------58%--                ] 1177 of 2000 complete in 361.0 sec
[-----------------58%--                ] 1179 of 2000 complete in 361.6 sec
[-----------------59%--                ] 1181 of 2000 complete in 362.2 sec
[-----------------59%--                ] 1183 of 2000 complete in 362.9 sec
[-----------------59%--                ] 1185 of 2000 complete in 363.5 sec
[-----------------59%--                ] 1187 of 2000 complete in 364.1 sec
[-----------------59%--                ] 1189 of 2000 complete in 364.7 sec
[-----------------59%--                ] 1191 of 2000 complete in 365.3 sec
[-----------------59%--                ] 1193 of 2000 complete in 365.9 sec
[-----------------59%--                ] 1195 of 2000 complete in 366.5 sec
[-----------------59%--                ] 1197 of 2000 complete in 367.1 sec
[-----------------59%--                ] 1199 of 2000 complete in 367.7 sec
[-----------------60%--                ] 1201 of 2000 complete in 368.3 sec
[-----------------60%--                ] 1203 of 2000 complete in 368.9 sec
[-----------------60%--                ] 1205 of 2000 complete in 369.5 sec
[-----------------60%--                ] 1207 of 2000 complete in 370.1 sec
[-----------------60%--                ] 1209 of 2000 complete in 370.7 sec
[-----------------60%---               ] 1211 of 2000 complete in 371.4 sec
[-----------------60%---               ] 1213 of 2000 complete in 372.0 sec
[-----------------60%---               ] 1215 of 2000 complete in 372.6 sec
[-----------------60%---               ] 1217 of 2000 complete in 373.2 sec
[-----------------60%---               ] 1219 of 2000 complete in 373.8 sec
[-----------------61%---               ] 1221 of 2000 complete in 374.4 sec
[-----------------61%---               ] 1223 of 2000 complete in 375.0 sec
[-----------------61%---               ] 1225 of 2000 complete in 375.6 sec
[-----------------61%---               ] 1227 of 2000 complete in 376.2 sec
[-----------------61%---               ] 1229 of 2000 complete in 376.8 sec
[-----------------61%---               ] 1231 of 2000 complete in 377.4 sec
[-----------------61%---               ] 1233 of 2000 complete in 378.1 sec
[-----------------61%---               ] 1235 of 2000 complete in 378.7 sec
[-----------------61%---               ] 1237 of 2000 complete in 379.3 sec
[-----------------61%---               ] 1239 of 2000 complete in 379.9 sec
[-----------------62%---               ] 1241 of 2000 complete in 380.5 sec
[-----------------62%---               ] 1243 of 2000 complete in 381.1 sec
[-----------------62%---               ] 1245 of 2000 complete in 381.8 sec
[-----------------62%---               ] 1247 of 2000 complete in 382.4 sec
[-----------------62%---               ] 1249 of 2000 complete in 383.0 sec
[-----------------62%---               ] 1251 of 2000 complete in 383.6 sec
[-----------------62%---               ] 1253 of 2000 complete in 384.2 sec
[-----------------62%---               ] 1255 of 2000 complete in 384.8 sec
[-----------------62%---               ] 1257 of 2000 complete in 385.4 sec
[-----------------62%---               ] 1259 of 2000 complete in 386.0 sec
[-----------------63%---               ] 1261 of 2000 complete in 386.6 sec
[-----------------63%---               ] 1263 of 2000 complete in 387.2 sec
[-----------------63%----              ] 1265 of 2000 complete in 387.9 sec
[-----------------63%----              ] 1267 of 2000 complete in 388.5 sec
[-----------------63%----              ] 1269 of 2000 complete in 389.1 sec
[-----------------63%----              ] 1271 of 2000 complete in 389.7 sec
[-----------------63%----              ] 1273 of 2000 complete in 390.3 sec
[-----------------63%----              ] 1275 of 2000 complete in 390.9 sec
[-----------------63%----              ] 1277 of 2000 complete in 391.5 sec
[-----------------63%----              ] 1279 of 2000 complete in 392.1 sec
[-----------------64%----              ] 1281 of 2000 complete in 392.7 sec
[-----------------64%----              ] 1283 of 2000 complete in 393.3 sec
[-----------------64%----              ] 1285 of 2000 complete in 394.0 sec
[-----------------64%----              ] 1287 of 2000 complete in 394.6 sec
[-----------------64%----              ] 1289 of 2000 complete in 395.2 sec
[-----------------64%----              ] 1291 of 2000 complete in 395.8 sec
[-----------------64%----              ] 1293 of 2000 complete in 396.4 sec
[-----------------64%----              ] 1295 of 2000 complete in 397.0 sec
[-----------------64%----              ] 1297 of 2000 complete in 397.6 sec
[-----------------64%----              ] 1299 of 2000 complete in 398.2 sec
[-----------------65%----              ] 1301 of 2000 complete in 398.8 sec
[-----------------65%----              ] 1303 of 2000 complete in 399.4 sec
[-----------------65%----              ] 1305 of 2000 complete in 400.0 sec
[-----------------65%----              ] 1307 of 2000 complete in 400.6 sec
[-----------------65%----              ] 1309 of 2000 complete in 401.2 sec
[-----------------65%----              ] 1311 of 2000 complete in 401.8 sec
[-----------------65%----              ] 1313 of 2000 complete in 402.5 sec
[-----------------65%----              ] 1315 of 2000 complete in 403.1 sec
[-----------------65%-----             ] 1317 of 2000 complete in 403.7 sec
[-----------------65%-----             ] 1319 of 2000 complete in 404.3 sec
[-----------------66%-----             ] 1321 of 2000 complete in 404.9 sec
[-----------------66%-----             ] 1323 of 2000 complete in 405.5 sec
[-----------------66%-----             ] 1325 of 2000 complete in 406.1 sec
[-----------------66%-----             ] 1327 of 2000 complete in 406.7 sec
[-----------------66%-----             ] 1329 of 2000 complete in 407.3 sec
[-----------------66%-----             ] 1331 of 2000 complete in 407.9 sec
[-----------------66%-----             ] 1333 of 2000 complete in 408.5 sec
[-----------------66%-----             ] 1335 of 2000 complete in 409.1 sec
[-----------------66%-----             ] 1337 of 2000 complete in 409.7 sec
[-----------------66%-----             ] 1339 of 2000 complete in 410.4 sec
[-----------------67%-----             ] 1341 of 2000 complete in 411.0 sec
[-----------------67%-----             ] 1343 of 2000 complete in 411.5 sec
[-----------------67%-----             ] 1345 of 2000 complete in 412.2 sec
[-----------------67%-----             ] 1347 of 2000 complete in 412.8 sec
[-----------------67%-----             ] 1349 of 2000 complete in 413.4 sec
[-----------------67%-----             ] 1351 of 2000 complete in 414.0 sec
[-----------------67%-----             ] 1353 of 2000 complete in 414.6 sec
[-----------------67%-----             ] 1355 of 2000 complete in 415.2 sec
[-----------------67%-----             ] 1357 of 2000 complete in 415.8 sec
[-----------------67%-----             ] 1359 of 2000 complete in 416.4 sec
[-----------------68%-----             ] 1361 of 2000 complete in 417.0 sec
[-----------------68%-----             ] 1363 of 2000 complete in 417.6 sec
[-----------------68%-----             ] 1365 of 2000 complete in 418.2 sec
[-----------------68%-----             ] 1367 of 2000 complete in 418.9 sec
[-----------------68%------            ] 1369 of 2000 complete in 419.5 sec
[-----------------68%------            ] 1371 of 2000 complete in 420.1 sec
[-----------------68%------            ] 1373 of 2000 complete in 420.7 sec
[-----------------68%------            ] 1375 of 2000 complete in 421.3 sec
[-----------------68%------            ] 1377 of 2000 complete in 421.9 sec
[-----------------68%------            ] 1379 of 2000 complete in 422.5 sec
[-----------------69%------            ] 1381 of 2000 complete in 423.1 sec
[-----------------69%------            ] 1383 of 2000 complete in 423.7 sec
[-----------------69%------            ] 1385 of 2000 complete in 424.3 sec
[-----------------69%------            ] 1387 of 2000 complete in 425.0 sec

[-----------------58%--                ] 1175 of 2000 complete in 362.8 sec
[-----------------58%--                ] 1177 of 2000 complete in 363.4 sec
[-----------------58%--                ] 1179 of 2000 complete in 364.0 sec
[-----------------59%--                ] 1181 of 2000 complete in 364.6 sec
[-----------------59%--                ] 1183 of 2000 complete in 365.2 sec
[-----------------59%--                ] 1185 of 2000 complete in 365.8 sec
[-----------------59%--                ] 1187 of 2000 complete in 366.4 sec
[-----------------59%--                ] 1189 of 2000 complete in 367.0 sec
[-----------------59%--                ] 1191 of 2000 complete in 367.6 sec
[-----------------59%--                ] 1193 of 2000 complete in 368.3 sec
[-----------------59%--                ] 1195 of 2000 complete in 368.9 sec
[-----------------59%--                ] 1197 of 2000 complete in 369.5 sec
[-----------------59%--                ] 1199 of 2000 complete in 370.2 sec
[-----------------60%--                ] 1201 of 2000 complete in 370.8 sec
[-----------------60%--                ] 1203 of 2000 complete in 371.4 sec
[-----------------60%--                ] 1205 of 2000 complete in 372.0 sec
[-----------------60%--                ] 1207 of 2000 complete in 372.6 sec
[-----------------60%--                ] 1209 of 2000 complete in 373.2 sec
[-----------------60%---               ] 1211 of 2000 complete in 373.8 sec
[-----------------60%---               ] 1213 of 2000 complete in 374.4 sec
[-----------------60%---               ] 1215 of 2000 complete in 375.1 sec
[-----------------60%---               ] 1217 of 2000 complete in 375.7 sec
[-----------------60%---               ] 1219 of 2000 complete in 376.3 sec
[-----------------61%---               ] 1221 of 2000 complete in 376.9 sec
[-----------------61%---               ] 1223 of 2000 complete in 377.5 sec
[-----------------61%---               ] 1225 of 2000 complete in 378.1 sec
[-----------------61%---               ] 1227 of 2000 complete in 378.7 sec
[-----------------61%---               ] 1229 of 2000 complete in 379.3 sec
[-----------------61%---               ] 1231 of 2000 complete in 380.0 sec
[-----------------61%---               ] 1233 of 2000 complete in 380.6 sec
[-----------------61%---               ] 1235 of 2000 complete in 381.2 sec
[-----------------61%---               ] 1237 of 2000 complete in 381.8 sec
[-----------------61%---               ] 1239 of 2000 complete in 382.4 sec
[-----------------62%---               ] 1241 of 2000 complete in 383.0 sec
[-----------------62%---               ] 1243 of 2000 complete in 383.6 sec
[-----------------62%---               ] 1245 of 2000 complete in 384.2 sec
[-----------------62%---               ] 1247 of 2000 complete in 384.8 sec
[-----------------62%---               ] 1249 of 2000 complete in 385.4 sec
[-----------------62%---               ] 1251 of 2000 complete in 386.0 sec
[-----------------62%---               ] 1253 of 2000 complete in 386.6 sec
[-----------------62%---               ] 1255 of 2000 complete in 387.3 sec
[-----------------62%---               ] 1257 of 2000 complete in 387.9 sec
[-----------------62%---               ] 1259 of 2000 complete in 388.5 sec
[-----------------63%---               ] 1261 of 2000 complete in 389.1 sec
[-----------------63%---               ] 1263 of 2000 complete in 389.7 sec
[-----------------63%----              ] 1265 of 2000 complete in 390.3 sec
[-----------------63%----              ] 1267 of 2000 complete in 391.0 sec
[-----------------63%----              ] 1269 of 2000 complete in 391.6 sec
[-----------------63%----              ] 1271 of 2000 complete in 392.2 sec
[-----------------63%----              ] 1273 of 2000 complete in 392.8 sec
[-----------------63%----              ] 1275 of 2000 complete in 393.4 sec
[-----------------63%----              ] 1277 of 2000 complete in 394.0 sec
[-----------------63%----              ] 1279 of 2000 complete in 394.7 sec
[-----------------64%----              ] 1281 of 2000 complete in 395.3 sec
[-----------------64%----              ] 1283 of 2000 complete in 395.9 sec
[-----------------64%----              ] 1285 of 2000 complete in 396.6 sec
[-----------------64%----              ] 1287 of 2000 complete in 397.2 sec
[-----------------64%----              ] 1289 of 2000 complete in 397.8 sec
[-----------------64%----              ] 1291 of 2000 complete in 398.4 sec
[-----------------64%----              ] 1293 of 2000 complete in 399.0 sec
[-----------------64%----              ] 1295 of 2000 complete in 399.6 sec
[-----------------64%----              ] 1297 of 2000 complete in 400.2 sec
[-----------------64%----              ] 1299 of 2000 complete in 400.8 sec
[-----------------65%----              ] 1301 of 2000 complete in 401.4 sec
[-----------------65%----              ] 1303 of 2000 complete in 402.0 sec
[-----------------65%----              ] 1305 of 2000 complete in 402.6 sec
[-----------------65%----              ] 1307 of 2000 complete in 403.2 sec
[-----------------65%----              ] 1309 of 2000 complete in 403.9 sec
[-----------------65%----              ] 1311 of 2000 complete in 404.4 sec
[-----------------65%----              ] 1313 of 2000 complete in 405.0 sec
[-----------------65%----              ] 1315 of 2000 complete in 405.6 sec
[-----------------65%-----             ] 1317 of 2000 complete in 406.3 sec
[-----------------65%-----             ] 1319 of 2000 complete in 406.9 sec
[-----------------66%-----             ] 1321 of 2000 complete in 407.5 sec
[-----------------66%-----             ] 1323 of 2000 complete in 408.1 sec
[-----------------66%-----             ] 1325 of 2000 complete in 408.7 sec
[-----------------66%-----             ] 1327 of 2000 complete in 409.3 sec
[-----------------66%-----             ] 1329 of 2000 complete in 409.9 sec
[-----------------66%-----             ] 1331 of 2000 complete in 410.6 sec
[-----------------66%-----             ] 1333 of 2000 complete in 411.2 sec
[-----------------66%-----             ] 1335 of 2000 complete in 411.8 sec
[-----------------66%-----             ] 1337 of 2000 complete in 412.4 sec
[-----------------66%-----             ] 1339 of 2000 complete in 413.1 sec
[-----------------67%-----             ] 1341 of 2000 complete in 413.6 sec
[-----------------67%-----             ] 1343 of 2000 complete in 414.3 sec
[-----------------67%-----             ] 1345 of 2000 complete in 414.9 sec
[-----------------67%-----             ] 1347 of 2000 complete in 415.5 sec
[-----------------67%-----             ] 1349 of 2000 complete in 416.1 sec
[-----------------67%-----             ] 1351 of 2000 complete in 416.7 sec
[-----------------67%-----             ] 1353 of 2000 complete in 417.4 sec
[-----------------67%-----             ] 1355 of 2000 complete in 418.0 sec
[-----------------67%-----             ] 1357 of 2000 complete in 418.6 sec
[-----------------67%-----             ] 1359 of 2000 complete in 419.2 sec
[-----------------68%-----             ] 1361 of 2000 complete in 419.8 sec
[-----------------68%-----             ] 1363 of 2000 complete in 420.4 sec
[-----------------68%-----             ] 1365 of 2000 complete in 421.0 sec
[-----------------68%-----             ] 1367 of 2000 complete in 421.6 sec
[-----------------68%------            ] 1369 of 2000 complete in 422.3 sec
[-----------------68%------            ] 1371 of 2000 complete in 422.9 sec
[-----------------68%------            ] 1373 of 2000 complete in 423.5 sec
[-----------------68%------            ] 1375 of 2000 complete in 424.1 sec
[-----------------68%------            ] 1377 of 2000 complete in 424.7 sec
[-----------------68%------            ] 1379 of 2000 complete in 425.3 sec
[-----------------69%------            ] 1381 of 2000 complete in 425.9 sec
[-----------------69%------            ] 1383 of 2000 complete in 426.5 sec
[-----------------69%------            ] 1385 of 2000 complete in 427.1 sec
[-----------------69%------            ] 1387 of 2000 complete in 427.7 sec
[-----------------69%------            ] 1389 of 2000 complete in 420.8 sec
[-----------------69%------            ] 1391 of 2000 complete in 421.4 sec
[-----------------69%------            ] 1393 of 2000 complete in 422.0 sec
[-----------------69%------            ] 1395 of 2000 complete in 422.6 sec
[-----------------69%------            ] 1397 of 2000 complete in 423.2 sec
[-----------------69%------            ] 1399 of 2000 complete in 423.8 sec
[-----------------70%------            ] 1401 of 2000 complete in 424.4 sec
[-----------------70%------            ] 1403 of 2000 complete in 425.0 sec
[-----------------70%------            ] 1405 of 2000 complete in 425.6 sec
[-----------------70%------            ] 1407 of 2000 complete in 426.1 sec
[-----------------70%------            ] 1409 of 2000 complete in 426.7 sec
[-----------------70%------            ] 1411 of 2000 complete in 427.4 sec
[-----------------70%------            ] 1413 of 2000 complete in 427.9 sec
[-----------------70%------            ] 1415 of 2000 complete in 428.5 sec
[-----------------70%------            ] 1417 of 2000 complete in 429.2 sec
[-----------------70%------            ] 1419 of 2000 complete in 429.8 sec
[-----------------71%------            ] 1421 of 2000 complete in 430.4 sec
[-----------------71%-------           ] 1423 of 2000 complete in 431.0 sec
[-----------------71%-------           ] 1425 of 2000 complete in 431.6 sec
[-----------------71%-------           ] 1427 of 2000 complete in 432.2 sec
[-----------------71%-------           ] 1429 of 2000 complete in 432.8 sec
[-----------------71%-------           ] 1431 of 2000 complete in 433.4 sec
[-----------------71%-------           ] 1433 of 2000 complete in 434.0 sec
[-----------------71%-------           ] 1435 of 2000 complete in 434.6 sec
[-----------------71%-------           ] 1437 of 2000 complete in 435.2 sec
[-----------------71%-------           ] 1439 of 2000 complete in 435.8 sec
[-----------------72%-------           ] 1441 of 2000 complete in 436.4 sec
[-----------------72%-------           ] 1443 of 2000 complete in 437.0 sec
[-----------------72%-------           ] 1445 of 2000 complete in 437.6 sec
[-----------------72%-------           ] 1447 of 2000 complete in 438.2 sec
[-----------------72%-------           ] 1449 of 2000 complete in 438.8 sec
[-----------------72%-------           ] 1451 of 2000 complete in 439.4 sec
[-----------------72%-------           ] 1453 of 2000 complete in 440.0 sec
[-----------------72%-------           ] 1455 of 2000 complete in 440.6 sec
[-----------------72%-------           ] 1457 of 2000 complete in 441.2 sec
[-----------------72%-------           ] 1459 of 2000 complete in 441.8 sec
[-----------------73%-------           ] 1461 of 2000 complete in 442.5 sec
[-----------------73%-------           ] 1463 of 2000 complete in 443.1 sec
[-----------------73%-------           ] 1465 of 2000 complete in 443.7 sec
[-----------------73%-------           ] 1467 of 2000 complete in 444.3 sec
[-----------------73%-------           ] 1469 of 2000 complete in 444.8 sec
[-----------------73%-------           ] 1471 of 2000 complete in 445.4 sec
[-----------------73%-------           ] 1473 of 2000 complete in 446.0 sec
[-----------------73%--------          ] 1475 of 2000 complete in 446.6 sec
[-----------------73%--------          ] 1477 of 2000 complete in 447.2 sec
[-----------------73%--------          ] 1479 of 2000 complete in 447.8 sec
[-----------------74%--------          ] 1481 of 2000 complete in 448.4 sec
[-----------------74%--------          ] 1483 of 2000 complete in 449.0 sec
[-----------------74%--------          ] 1485 of 2000 complete in 449.6 sec
[-----------------74%--------          ] 1487 of 2000 complete in 450.2 sec
[-----------------74%--------          ] 1489 of 2000 complete in 450.7 sec
[-----------------74%--------          ] 1491 of 2000 complete in 451.4 sec
[-----------------74%--------          ] 1493 of 2000 complete in 451.9 sec
[-----------------74%--------          ] 1495 of 2000 complete in 452.5 sec
[-----------------74%--------          ] 1497 of 2000 complete in 453.2 sec
[-----------------74%--------          ] 1499 of 2000 complete in 453.7 sec
[-----------------75%--------          ] 1501 of 2000 complete in 454.3 sec
[-----------------75%--------          ] 1503 of 2000 complete in 454.9 sec
[-----------------75%--------          ] 1505 of 2000 complete in 455.5 sec
[-----------------75%--------          ] 1507 of 2000 complete in 456.1 sec
[-----------------75%--------          ] 1509 of 2000 complete in 456.7 sec
[-----------------75%--------          ] 1511 of 2000 complete in 457.3 sec
[-----------------75%--------          ] 1513 of 2000 complete in 457.9 sec
[-----------------75%--------          ] 1515 of 2000 complete in 458.5 sec
[-----------------75%--------          ] 1517 of 2000 complete in 459.1 sec
[-----------------75%--------          ] 1519 of 2000 complete in 459.7 sec
[-----------------76%--------          ] 1521 of 2000 complete in 460.3 sec
[-----------------76%--------          ] 1523 of 2000 complete in 460.8 sec
[-----------------76%--------          ] 1525 of 2000 complete in 461.4 sec
[-----------------76%---------         ] 1527 of 2000 complete in 462.0 sec
[-----------------76%---------         ] 1529 of 2000 complete in 462.6 sec
[-----------------76%---------         ] 1531 of 2000 complete in 463.2 sec
[-----------------76%---------         ] 1533 of 2000 complete in 463.8 sec
[-----------------76%---------         ] 1535 of 2000 complete in 464.4 sec
[-----------------76%---------         ] 1537 of 2000 complete in 465.0 sec
[-----------------76%---------         ] 1539 of 2000 complete in 465.6 sec
[-----------------77%---------         ] 1541 of 2000 complete in 466.2 sec
[-----------------77%---------         ] 1543 of 2000 complete in 466.8 sec
[-----------------77%---------         ] 1545 of 2000 complete in 467.4 sec
[-----------------77%---------         ] 1547 of 2000 complete in 468.1 sec
[-----------------77%---------         ] 1549 of 2000 complete in 468.7 sec
[-----------------77%---------         ] 1551 of 2000 complete in 469.3 sec
[-----------------77%---------         ] 1553 of 2000 complete in 469.8 sec
[-----------------77%---------         ] 1555 of 2000 complete in 470.4 sec
[-----------------77%---------         ] 1557 of 2000 complete in 471.0 sec
[-----------------77%---------         ] 1559 of 2000 complete in 471.6 sec
[-----------------78%---------         ] 1561 of 2000 complete in 472.2 sec
[-----------------78%---------         ] 1563 of 2000 complete in 472.8 sec
[-----------------78%---------         ] 1565 of 2000 complete in 473.4 sec
[-----------------78%---------         ] 1567 of 2000 complete in 474.0 sec
[-----------------78%---------         ] 1569 of 2000 complete in 474.6 sec
[-----------------78%---------         ] 1571 of 2000 complete in 475.2 sec
[-----------------78%---------         ] 1573 of 2000 complete in 475.8 sec
[-----------------78%---------         ] 1575 of 2000 complete in 476.4 sec
[-----------------78%---------         ] 1577 of 2000 complete in 477.0 sec
[-----------------78%----------        ] 1579 of 2000 complete in 477.6 sec
[-----------------79%----------        ] 1581 of 2000 complete in 478.2 sec
[-----------------79%----------        ] 1583 of 2000 complete in 478.7 sec
[-----------------79%----------        ] 1585 of 2000 complete in 479.3 sec
[-----------------79%----------        ] 1587 of 2000 complete in 480.0 sec
[-----------------79%----------        ] 1589 of 2000 complete in 480.5 sec
[-----------------79%----------        ] 1591 of 2000 complete in 481.2 sec
[-----------------79%----------        ] 1593 of 2000 complete in 481.8 sec
[-----------------79%----------        ] 1595 of 2000 complete in 482.4 sec
[-----------------79%----------        ] 1597 of 2000 complete in 482.9 sec
[-----------------79%----------        ] 1599 of 2000 complete in 483.5 sec
[-----------------80%----------        ] 1601 of 2000 complete in 484.1 sec

[-----------------69%------            ] 1387 of 2000 complete in 424.6 sec
[-----------------69%------            ] 1389 of 2000 complete in 425.2 sec
[-----------------69%------            ] 1391 of 2000 complete in 425.8 sec
[-----------------69%------            ] 1393 of 2000 complete in 426.4 sec
[-----------------69%------            ] 1395 of 2000 complete in 427.0 sec
[-----------------69%------            ] 1397 of 2000 complete in 427.6 sec
[-----------------69%------            ] 1399 of 2000 complete in 428.2 sec
[-----------------70%------            ] 1401 of 2000 complete in 428.8 sec
[-----------------70%------            ] 1403 of 2000 complete in 429.4 sec
[-----------------70%------            ] 1405 of 2000 complete in 430.0 sec
[-----------------70%------            ] 1407 of 2000 complete in 430.6 sec
[-----------------70%------            ] 1409 of 2000 complete in 431.2 sec
[-----------------70%------            ] 1411 of 2000 complete in 431.8 sec
[-----------------70%------            ] 1413 of 2000 complete in 432.4 sec
[-----------------70%------            ] 1415 of 2000 complete in 433.0 sec
[-----------------70%------            ] 1417 of 2000 complete in 433.7 sec
[-----------------70%------            ] 1419 of 2000 complete in 434.3 sec
[-----------------71%------            ] 1421 of 2000 complete in 434.8 sec
[-----------------71%-------           ] 1423 of 2000 complete in 435.4 sec
[-----------------71%-------           ] 1425 of 2000 complete in 436.1 sec
[-----------------71%-------           ] 1427 of 2000 complete in 436.7 sec
[-----------------71%-------           ] 1429 of 2000 complete in 437.3 sec
[-----------------71%-------           ] 1431 of 2000 complete in 437.9 sec
[-----------------71%-------           ] 1433 of 2000 complete in 438.5 sec
[-----------------71%-------           ] 1435 of 2000 complete in 439.1 sec
[-----------------71%-------           ] 1437 of 2000 complete in 439.7 sec
[-----------------71%-------           ] 1439 of 2000 complete in 440.3 sec
[-----------------72%-------           ] 1441 of 2000 complete in 441.0 sec
[-----------------72%-------           ] 1443 of 2000 complete in 441.5 sec
[-----------------72%-------           ] 1445 of 2000 complete in 442.1 sec
[-----------------72%-------           ] 1447 of 2000 complete in 442.8 sec
[-----------------72%-------           ] 1449 of 2000 complete in 443.4 sec
[-----------------72%-------           ] 1451 of 2000 complete in 443.9 sec
[-----------------72%-------           ] 1453 of 2000 complete in 444.5 sec
[-----------------72%-------           ] 1455 of 2000 complete in 445.1 sec
[-----------------72%-------           ] 1457 of 2000 complete in 445.7 sec
[-----------------72%-------           ] 1459 of 2000 complete in 446.3 sec
[-----------------73%-------           ] 1461 of 2000 complete in 446.9 sec
[-----------------73%-------           ] 1463 of 2000 complete in 447.5 sec
[-----------------73%-------           ] 1465 of 2000 complete in 448.1 sec
[-----------------73%-------           ] 1467 of 2000 complete in 448.7 sec
[-----------------73%-------           ] 1469 of 2000 complete in 449.3 sec
[-----------------73%-------           ] 1471 of 2000 complete in 449.9 sec
[-----------------73%-------           ] 1473 of 2000 complete in 450.5 sec
[-----------------73%--------          ] 1475 of 2000 complete in 451.1 sec
[-----------------73%--------          ] 1477 of 2000 complete in 451.7 sec
[-----------------73%--------          ] 1479 of 2000 complete in 452.3 sec
[-----------------74%--------          ] 1481 of 2000 complete in 452.9 sec
[-----------------74%--------          ] 1483 of 2000 complete in 453.5 sec
[-----------------74%--------          ] 1485 of 2000 complete in 454.1 sec
[-----------------74%--------          ] 1487 of 2000 complete in 454.7 sec
[-----------------74%--------          ] 1489 of 2000 complete in 455.3 sec
[-----------------74%--------          ] 1491 of 2000 complete in 455.9 sec
[-----------------74%--------          ] 1493 of 2000 complete in 456.5 sec
[-----------------74%--------          ] 1495 of 2000 complete in 457.0 sec
[-----------------74%--------          ] 1497 of 2000 complete in 457.6 sec
[-----------------74%--------          ] 1499 of 2000 complete in 458.3 sec
[-----------------75%--------          ] 1501 of 2000 complete in 458.9 sec
[-----------------75%--------          ] 1503 of 2000 complete in 459.5 sec
[-----------------75%--------          ] 1505 of 2000 complete in 460.1 sec
[-----------------75%--------          ] 1507 of 2000 complete in 460.7 sec
[-----------------75%--------          ] 1509 of 2000 complete in 461.3 sec
[-----------------75%--------          ] 1511 of 2000 complete in 461.9 sec
[-----------------75%--------          ] 1513 of 2000 complete in 462.5 sec
[-----------------75%--------          ] 1515 of 2000 complete in 463.1 sec
[-----------------75%--------          ] 1517 of 2000 complete in 463.7 sec
[-----------------75%--------          ] 1519 of 2000 complete in 464.3 sec
[-----------------76%--------          ] 1521 of 2000 complete in 464.9 sec
[-----------------76%--------          ] 1523 of 2000 complete in 465.5 sec
[-----------------76%--------          ] 1525 of 2000 complete in 466.1 sec
[-----------------76%---------         ] 1527 of 2000 complete in 466.7 sec
[-----------------76%---------         ] 1529 of 2000 complete in 467.3 sec
[-----------------76%---------         ] 1531 of 2000 complete in 467.9 sec
[-----------------76%---------         ] 1533 of 2000 complete in 468.5 sec
[-----------------76%---------         ] 1535 of 2000 complete in 469.1 sec
[-----------------76%---------         ] 1537 of 2000 complete in 469.7 sec
[-----------------76%---------         ] 1539 of 2000 complete in 470.3 sec
[-----------------77%---------         ] 1541 of 2000 complete in 470.9 sec
[-----------------77%---------         ] 1543 of 2000 complete in 471.5 sec
[-----------------77%---------         ] 1545 of 2000 complete in 472.1 sec
[-----------------77%---------         ] 1547 of 2000 complete in 472.7 sec
[-----------------77%---------         ] 1549 of 2000 complete in 473.3 sec
[-----------------77%---------         ] 1551 of 2000 complete in 473.9 sec
[-----------------77%---------         ] 1553 of 2000 complete in 474.5 sec
[-----------------77%---------         ] 1555 of 2000 complete in 475.1 sec
[-----------------77%---------         ] 1557 of 2000 complete in 475.7 sec
[-----------------77%---------         ] 1559 of 2000 complete in 476.3 sec
[-----------------78%---------         ] 1561 of 2000 complete in 476.9 sec
[-----------------78%---------         ] 1563 of 2000 complete in 477.5 sec
[-----------------78%---------         ] 1565 of 2000 complete in 478.2 sec
[-----------------78%---------         ] 1567 of 2000 complete in 478.7 sec
[-----------------78%---------         ] 1569 of 2000 complete in 479.4 sec
[-----------------78%---------         ] 1571 of 2000 complete in 480.0 sec
[-----------------78%---------         ] 1573 of 2000 complete in 480.5 sec
[-----------------78%---------         ] 1575 of 2000 complete in 481.1 sec
[-----------------78%---------         ] 1577 of 2000 complete in 481.7 sec
[-----------------78%----------        ] 1579 of 2000 complete in 482.3 sec
[-----------------79%----------        ] 1581 of 2000 complete in 482.9 sec
[-----------------79%----------        ] 1583 of 2000 complete in 483.5 sec
[-----------------79%----------        ] 1585 of 2000 complete in 484.2 sec
[-----------------79%----------        ] 1587 of 2000 complete in 484.7 sec
[-----------------79%----------        ] 1589 of 2000 complete in 485.4 sec
[-----------------79%----------        ] 1591 of 2000 complete in 486.0 sec
[-----------------79%----------        ] 1593 of 2000 complete in 486.6 sec
[-----------------79%----------        ] 1595 of 2000 complete in 487.2 sec
[-----------------79%----------        ] 1597 of 2000 complete in 487.8 sec
[-----------------79%----------        ] 1599 of 2000 complete in 488.4 sec
[-----------------69%------            ] 1389 of 2000 complete in 425.6 sec
[-----------------69%------            ] 1391 of 2000 complete in 426.2 sec
[-----------------69%------            ] 1393 of 2000 complete in 426.8 sec
[-----------------69%------            ] 1395 of 2000 complete in 427.4 sec
[-----------------69%------            ] 1397 of 2000 complete in 428.0 sec
[-----------------69%------            ] 1399 of 2000 complete in 428.6 sec
[-----------------70%------            ] 1401 of 2000 complete in 429.2 sec
[-----------------70%------            ] 1403 of 2000 complete in 429.8 sec
[-----------------70%------            ] 1405 of 2000 complete in 430.4 sec
[-----------------70%------            ] 1407 of 2000 complete in 431.0 sec
[-----------------70%------            ] 1409 of 2000 complete in 431.6 sec
[-----------------70%------            ] 1411 of 2000 complete in 432.2 sec
[-----------------70%------            ] 1413 of 2000 complete in 432.9 sec
[-----------------70%------            ] 1415 of 2000 complete in 433.5 sec
[-----------------70%------            ] 1417 of 2000 complete in 434.1 sec
[-----------------70%------            ] 1419 of 2000 complete in 434.7 sec
[-----------------71%------            ] 1421 of 2000 complete in 435.2 sec
[-----------------71%-------           ] 1423 of 2000 complete in 435.8 sec
[-----------------71%-------           ] 1425 of 2000 complete in 436.5 sec
[-----------------71%-------           ] 1427 of 2000 complete in 437.1 sec
[-----------------71%-------           ] 1429 of 2000 complete in 437.7 sec
[-----------------71%-------           ] 1431 of 2000 complete in 438.3 sec
[-----------------71%-------           ] 1433 of 2000 complete in 438.9 sec
[-----------------71%-------           ] 1435 of 2000 complete in 439.5 sec
[-----------------71%-------           ] 1437 of 2000 complete in 440.1 sec
[-----------------71%-------           ] 1439 of 2000 complete in 440.7 sec
[-----------------72%-------           ] 1441 of 2000 complete in 441.4 sec
[-----------------72%-------           ] 1443 of 2000 complete in 442.0 sec
[-----------------72%-------           ] 1445 of 2000 complete in 442.6 sec
[-----------------72%-------           ] 1447 of 2000 complete in 443.2 sec
[-----------------72%-------           ] 1449 of 2000 complete in 443.8 sec
[-----------------72%-------           ] 1451 of 2000 complete in 444.4 sec
[-----------------72%-------           ] 1453 of 2000 complete in 445.0 sec
[-----------------72%-------           ] 1455 of 2000 complete in 445.6 sec
[-----------------72%-------           ] 1457 of 2000 complete in 446.1 sec
[-----------------72%-------           ] 1459 of 2000 complete in 446.7 sec
[-----------------73%-------           ] 1461 of 2000 complete in 447.4 sec
[-----------------73%-------           ] 1463 of 2000 complete in 447.9 sec
[-----------------73%-------           ] 1465 of 2000 complete in 448.5 sec
[-----------------73%-------           ] 1467 of 2000 complete in 449.2 sec
[-----------------73%-------           ] 1469 of 2000 complete in 449.8 sec
[-----------------73%-------           ] 1471 of 2000 complete in 450.4 sec
[-----------------73%-------           ] 1473 of 2000 complete in 451.0 sec
[-----------------73%--------          ] 1475 of 2000 complete in 451.6 sec
[-----------------73%--------          ] 1477 of 2000 complete in 452.2 sec
[-----------------73%--------          ] 1479 of 2000 complete in 452.8 sec
[-----------------74%--------          ] 1481 of 2000 complete in 453.4 sec
[-----------------74%--------          ] 1483 of 2000 complete in 454.0 sec
[-----------------74%--------          ] 1485 of 2000 complete in 454.6 sec
[-----------------74%--------          ] 1487 of 2000 complete in 455.2 sec
[-----------------74%--------          ] 1489 of 2000 complete in 455.8 sec
[-----------------74%--------          ] 1491 of 2000 complete in 456.4 sec
[-----------------74%--------          ] 1493 of 2000 complete in 457.0 sec
[-----------------74%--------          ] 1495 of 2000 complete in 457.6 sec
[-----------------74%--------          ] 1497 of 2000 complete in 458.2 sec
[-----------------74%--------          ] 1499 of 2000 complete in 458.8 sec
[-----------------75%--------          ] 1501 of 2000 complete in 459.4 sec
[-----------------75%--------          ] 1503 of 2000 complete in 460.0 sec
[-----------------75%--------          ] 1505 of 2000 complete in 460.6 sec
[-----------------75%--------          ] 1507 of 2000 complete in 461.2 sec
[-----------------75%--------          ] 1509 of 2000 complete in 461.8 sec
[-----------------75%--------          ] 1511 of 2000 complete in 462.4 sec
[-----------------75%--------          ] 1513 of 2000 complete in 463.0 sec
[-----------------75%--------          ] 1515 of 2000 complete in 463.6 sec
[-----------------75%--------          ] 1517 of 2000 complete in 464.2 sec
[-----------------75%--------          ] 1519 of 2000 complete in 464.8 sec
[-----------------76%--------          ] 1521 of 2000 complete in 465.5 sec
[-----------------76%--------          ] 1523 of 2000 complete in 466.1 sec
[-----------------76%--------          ] 1525 of 2000 complete in 466.7 sec
[-----------------76%---------         ] 1527 of 2000 complete in 467.3 sec
[-----------------76%---------         ] 1529 of 2000 complete in 467.9 sec
[-----------------76%---------         ] 1531 of 2000 complete in 468.5 sec
[-----------------76%---------         ] 1533 of 2000 complete in 469.1 sec
[-----------------76%---------         ] 1535 of 2000 complete in 469.7 sec
[-----------------76%---------         ] 1537 of 2000 complete in 470.2 sec
[-----------------76%---------         ] 1539 of 2000 complete in 470.8 sec
[-----------------77%---------         ] 1541 of 2000 complete in 471.4 sec
[-----------------77%---------         ] 1543 of 2000 complete in 472.0 sec
[-----------------77%---------         ] 1545 of 2000 complete in 472.6 sec
[-----------------77%---------         ] 1547 of 2000 complete in 473.2 sec
[-----------------77%---------         ] 1549 of 2000 complete in 473.8 sec
[-----------------77%---------         ] 1551 of 2000 complete in 474.4 sec
[-----------------77%---------         ] 1553 of 2000 complete in 475.0 sec
[-----------------77%---------         ] 1555 of 2000 complete in 475.6 sec
[-----------------77%---------         ] 1557 of 2000 complete in 476.2 sec
[-----------------77%---------         ] 1559 of 2000 complete in 476.8 sec
[-----------------78%---------         ] 1561 of 2000 complete in 477.4 sec
[-----------------78%---------         ] 1563 of 2000 complete in 478.0 sec
[-----------------78%---------         ] 1565 of 2000 complete in 478.6 sec
[-----------------78%---------         ] 1567 of 2000 complete in 479.2 sec
[-----------------78%---------         ] 1569 of 2000 complete in 479.8 sec
[-----------------78%---------         ] 1571 of 2000 complete in 480.5 sec
[-----------------78%---------         ] 1573 of 2000 complete in 481.1 sec
[-----------------78%---------         ] 1575 of 2000 complete in 481.7 sec
[-----------------78%---------         ] 1577 of 2000 complete in 482.3 sec
[-----------------78%----------        ] 1579 of 2000 complete in 482.9 sec
[-----------------79%----------        ] 1581 of 2000 complete in 483.5 sec
[-----------------79%----------        ] 1583 of 2000 complete in 484.1 sec
[-----------------79%----------        ] 1585 of 2000 complete in 484.7 sec
[-----------------79%----------        ] 1587 of 2000 complete in 485.3 sec
[-----------------79%----------        ] 1589 of 2000 complete in 485.9 sec
[-----------------79%----------        ] 1591 of 2000 complete in 486.5 sec
[-----------------79%----------        ] 1593 of 2000 complete in 487.1 sec
[-----------------79%----------        ] 1595 of 2000 complete in 487.7 sec
[-----------------79%----------        ] 1597 of 2000 complete in 488.3 sec
[-----------------79%----------        ] 1599 of 2000 complete in 489.0 sec
[-----------------80%----------        ] 1601 of 2000 complete in 489.6 sec

[-----------------69%------            ] 1389 of 2000 complete in 428.3 sec
[-----------------69%------            ] 1391 of 2000 complete in 428.9 sec
[-----------------69%------            ] 1393 of 2000 complete in 429.5 sec
[-----------------69%------            ] 1395 of 2000 complete in 430.2 sec
[-----------------69%------            ] 1397 of 2000 complete in 430.8 sec
[-----------------69%------            ] 1399 of 2000 complete in 431.4 sec
[-----------------70%------            ] 1401 of 2000 complete in 432.0 sec
[-----------------70%------            ] 1403 of 2000 complete in 432.6 sec
[-----------------70%------            ] 1405 of 2000 complete in 433.3 sec
[-----------------70%------            ] 1407 of 2000 complete in 433.9 sec
[-----------------70%------            ] 1409 of 2000 complete in 434.5 sec
[-----------------70%------            ] 1411 of 2000 complete in 435.1 sec
[-----------------70%------            ] 1413 of 2000 complete in 435.7 sec
[-----------------70%------            ] 1415 of 2000 complete in 436.3 sec
[-----------------70%------            ] 1417 of 2000 complete in 436.9 sec
[-----------------70%------            ] 1419 of 2000 complete in 437.6 sec
[-----------------71%------            ] 1421 of 2000 complete in 438.2 sec
[-----------------71%-------           ] 1423 of 2000 complete in 438.8 sec
[-----------------71%-------           ] 1425 of 2000 complete in 439.4 sec
[-----------------71%-------           ] 1427 of 2000 complete in 440.0 sec
[-----------------71%-------           ] 1429 of 2000 complete in 440.6 sec
[-----------------71%-------           ] 1431 of 2000 complete in 441.3 sec
[-----------------71%-------           ] 1433 of 2000 complete in 441.9 sec
[-----------------71%-------           ] 1435 of 2000 complete in 442.5 sec
[-----------------71%-------           ] 1437 of 2000 complete in 443.1 sec
[-----------------71%-------           ] 1439 of 2000 complete in 443.7 sec
[-----------------72%-------           ] 1441 of 2000 complete in 444.3 sec
[-----------------72%-------           ] 1443 of 2000 complete in 444.9 sec
[-----------------72%-------           ] 1445 of 2000 complete in 445.5 sec
[-----------------72%-------           ] 1447 of 2000 complete in 446.1 sec
[-----------------72%-------           ] 1449 of 2000 complete in 446.7 sec
[-----------------72%-------           ] 1451 of 2000 complete in 447.3 sec
[-----------------72%-------           ] 1453 of 2000 complete in 447.9 sec
[-----------------72%-------           ] 1455 of 2000 complete in 448.6 sec
[-----------------72%-------           ] 1457 of 2000 complete in 449.2 sec
[-----------------72%-------           ] 1459 of 2000 complete in 449.8 sec
[-----------------73%-------           ] 1461 of 2000 complete in 450.4 sec
[-----------------73%-------           ] 1463 of 2000 complete in 451.0 sec
[-----------------73%-------           ] 1465 of 2000 complete in 451.6 sec
[-----------------73%-------           ] 1467 of 2000 complete in 452.2 sec
[-----------------73%-------           ] 1469 of 2000 complete in 452.8 sec
[-----------------73%-------           ] 1471 of 2000 complete in 453.4 sec
[-----------------73%-------           ] 1473 of 2000 complete in 454.0 sec
[-----------------73%--------          ] 1475 of 2000 complete in 454.7 sec
[-----------------73%--------          ] 1477 of 2000 complete in 455.3 sec
[-----------------73%--------          ] 1479 of 2000 complete in 455.9 sec
[-----------------74%--------          ] 1481 of 2000 complete in 456.5 sec
[-----------------74%--------          ] 1483 of 2000 complete in 457.1 sec
[-----------------74%--------          ] 1485 of 2000 complete in 457.7 sec
[-----------------74%--------          ] 1487 of 2000 complete in 458.3 sec
[-----------------74%--------          ] 1489 of 2000 complete in 458.9 sec
[-----------------74%--------          ] 1491 of 2000 complete in 459.5 sec
[-----------------74%--------          ] 1493 of 2000 complete in 460.1 sec
[-----------------74%--------          ] 1495 of 2000 complete in 460.7 sec
[-----------------74%--------          ] 1497 of 2000 complete in 461.3 sec
[-----------------74%--------          ] 1499 of 2000 complete in 461.9 sec
[-----------------75%--------          ] 1501 of 2000 complete in 462.6 sec
[-----------------75%--------          ] 1503 of 2000 complete in 463.2 sec
[-----------------75%--------          ] 1505 of 2000 complete in 463.8 sec
[-----------------75%--------          ] 1507 of 2000 complete in 464.4 sec
[-----------------75%--------          ] 1509 of 2000 complete in 465.0 sec
[-----------------75%--------          ] 1511 of 2000 complete in 465.6 sec
[-----------------75%--------          ] 1513 of 2000 complete in 466.2 sec
[-----------------75%--------          ] 1515 of 2000 complete in 466.8 sec
[-----------------75%--------          ] 1517 of 2000 complete in 467.5 sec
[-----------------75%--------          ] 1519 of 2000 complete in 468.1 sec
[-----------------76%--------          ] 1521 of 2000 complete in 468.7 sec
[-----------------76%--------          ] 1523 of 2000 complete in 469.3 sec
[-----------------76%--------          ] 1525 of 2000 complete in 469.9 sec
[-----------------76%---------         ] 1527 of 2000 complete in 470.5 sec
[-----------------76%---------         ] 1529 of 2000 complete in 471.1 sec
[-----------------76%---------         ] 1531 of 2000 complete in 471.8 sec
[-----------------76%---------         ] 1533 of 2000 complete in 472.4 sec
[-----------------76%---------         ] 1535 of 2000 complete in 473.0 sec
[-----------------76%---------         ] 1537 of 2000 complete in 473.6 sec
[-----------------76%---------         ] 1539 of 2000 complete in 474.2 sec
[-----------------77%---------         ] 1541 of 2000 complete in 474.8 sec
[-----------------77%---------         ] 1543 of 2000 complete in 475.4 sec
[-----------------77%---------         ] 1545 of 2000 complete in 476.1 sec
[-----------------77%---------         ] 1547 of 2000 complete in 476.7 sec
[-----------------77%---------         ] 1549 of 2000 complete in 477.3 sec
[-----------------77%---------         ] 1551 of 2000 complete in 477.9 sec
[-----------------77%---------         ] 1553 of 2000 complete in 478.5 sec
[-----------------77%---------         ] 1555 of 2000 complete in 479.1 sec
[-----------------77%---------         ] 1557 of 2000 complete in 479.7 sec
[-----------------77%---------         ] 1559 of 2000 complete in 480.3 sec
[-----------------78%---------         ] 1561 of 2000 complete in 481.0 sec
[-----------------78%---------         ] 1563 of 2000 complete in 481.6 sec
[-----------------78%---------         ] 1565 of 2000 complete in 482.2 sec
[-----------------78%---------         ] 1567 of 2000 complete in 482.8 sec
[-----------------78%---------         ] 1569 of 2000 complete in 483.4 sec
[-----------------78%---------         ] 1571 of 2000 complete in 484.0 sec
[-----------------78%---------         ] 1573 of 2000 complete in 484.6 sec
[-----------------78%---------         ] 1575 of 2000 complete in 485.2 sec
[-----------------78%---------         ] 1577 of 2000 complete in 485.8 sec
[-----------------78%----------        ] 1579 of 2000 complete in 486.4 sec
[-----------------79%----------        ] 1581 of 2000 complete in 487.0 sec
[-----------------79%----------        ] 1583 of 2000 complete in 487.6 sec
[-----------------79%----------        ] 1585 of 2000 complete in 488.2 sec
[-----------------79%----------        ] 1587 of 2000 complete in 488.8 sec
[-----------------79%----------        ] 1589 of 2000 complete in 489.4 sec
[-----------------79%----------        ] 1591 of 2000 complete in 490.0 sec
[-----------------79%----------        ] 1593 of 2000 complete in 490.6 sec
[-----------------79%----------        ] 1595 of 2000 complete in 491.2 sec
[-----------------79%----------        ] 1597 of 2000 complete in 491.8 sec
[-----------------79%----------        ] 1599 of 2000 complete in 492.5 sec
[-----------------80%----------        ] 1601 of 2000 complete in 493.1 sec
[-----------------80%----------        ] 1603 of 2000 complete in 484.7 sec
[-----------------80%----------        ] 1605 of 2000 complete in 485.4 sec
[-----------------80%----------        ] 1607 of 2000 complete in 486.0 sec
[-----------------80%----------        ] 1609 of 2000 complete in 486.5 sec
[-----------------80%----------        ] 1611 of 2000 complete in 487.1 sec
[-----------------80%----------        ] 1613 of 2000 complete in 487.7 sec
[-----------------80%----------        ] 1615 of 2000 complete in 488.3 sec
[-----------------80%----------        ] 1617 of 2000 complete in 488.9 sec
[-----------------80%----------        ] 1619 of 2000 complete in 489.5 sec
[-----------------81%----------        ] 1621 of 2000 complete in 490.1 sec
[-----------------81%----------        ] 1623 of 2000 complete in 490.7 sec
[-----------------81%----------        ] 1625 of 2000 complete in 491.3 sec
[-----------------81%----------        ] 1627 of 2000 complete in 491.9 sec
[-----------------81%----------        ] 1629 of 2000 complete in 492.5 sec
[-----------------81%----------        ] 1631 of 2000 complete in 493.1 sec
[-----------------81%-----------       ] 1633 of 2000 complete in 493.7 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 494.3 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 494.9 sec
[-----------------81%-----------       ] 1639 of 2000 complete in 495.5 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 496.2 sec
[-----------------82%-----------       ] 1643 of 2000 complete in 496.8 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 497.4 sec
[-----------------82%-----------       ] 1647 of 2000 complete in 498.0 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 498.6 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 499.1 sec
[-----------------82%-----------       ] 1653 of 2000 complete in 499.7 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 500.3 sec
[-----------------82%-----------       ] 1657 of 2000 complete in 501.0 sec
[-----------------82%-----------       ] 1659 of 2000 complete in 501.6 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 502.2 sec
[-----------------83%-----------       ] 1663 of 2000 complete in 502.8 sec
[-----------------83%-----------       ] 1665 of 2000 complete in 503.5 sec
[-----------------83%-----------       ] 1667 of 2000 complete in 504.1 sec
[-----------------83%-----------       ] 1669 of 2000 complete in 504.7 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 505.3 sec
[-----------------83%-----------       ] 1673 of 2000 complete in 506.0 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 506.6 sec
[-----------------83%-----------       ] 1677 of 2000 complete in 507.2 sec
[-----------------83%-----------       ] 1679 of 2000 complete in 507.8 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 508.4 sec
[-----------------84%-----------       ] 1683 of 2000 complete in 509.0 sec
[-----------------84%------------      ] 1685 of 2000 complete in 509.6 sec
[-----------------84%------------      ] 1687 of 2000 complete in 510.2 sec
[-----------------84%------------      ] 1689 of 2000 complete in 510.8 sec
[-----------------84%------------      ] 1691 of 2000 complete in 511.4 sec
[-----------------84%------------      ] 1693 of 2000 complete in 512.1 sec
[-----------------84%------------      ] 1695 of 2000 complete in 512.6 sec
[-----------------84%------------      ] 1697 of 2000 complete in 513.2 sec
[-----------------84%------------      ] 1699 of 2000 complete in 513.8 sec
[-----------------85%------------      ] 1701 of 2000 complete in 514.4 sec
[-----------------85%------------      ] 1703 of 2000 complete in 515.0 sec
[-----------------85%------------      ] 1705 of 2000 complete in 515.6 sec
[-----------------85%------------      ] 1707 of 2000 complete in 516.2 sec
[-----------------85%------------      ] 1709 of 2000 complete in 516.8 sec
[-----------------85%------------      ] 1711 of 2000 complete in 517.4 sec
[-----------------85%------------      ] 1713 of 2000 complete in 518.0 sec
[-----------------85%------------      ] 1715 of 2000 complete in 518.5 sec
[-----------------85%------------      ] 1717 of 2000 complete in 519.1 sec
[-----------------85%------------      ] 1719 of 2000 complete in 519.7 sec
[-----------------86%------------      ] 1721 of 2000 complete in 520.3 sec
[-----------------86%------------      ] 1723 of 2000 complete in 520.8 sec
[-----------------86%------------      ] 1725 of 2000 complete in 521.4 sec
[-----------------86%------------      ] 1727 of 2000 complete in 522.0 sec
[-----------------86%------------      ] 1729 of 2000 complete in 522.6 sec
[-----------------86%------------      ] 1731 of 2000 complete in 523.2 sec
[-----------------86%------------      ] 1733 of 2000 complete in 523.8 sec
[-----------------86%------------      ] 1735 of 2000 complete in 524.4 sec
[-----------------86%-------------     ] 1737 of 2000 complete in 524.9 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 525.5 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 526.1 sec
[-----------------87%-------------     ] 1743 of 2000 complete in 526.8 sec
[-----------------87%-------------     ] 1745 of 2000 complete in 527.4 sec
[-----------------87%-------------     ] 1747 of 2000 complete in 528.3 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 529.0 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 529.7 sec
[-----------------87%-------------     ] 1753 of 2000 complete in 530.3 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 531.1 sec
[-----------------87%-------------     ] 1757 of 2000 complete in 531.8 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 532.5 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 533.2 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 533.9 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 534.6 sec
[-----------------88%-------------     ] 1767 of 2000 complete in 535.3 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 536.0 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 536.7 sec
[-----------------88%-------------     ] 1773 of 2000 complete in 537.4 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 538.0 sec
[-----------------88%-------------     ] 1777 of 2000 complete in 538.7 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 539.3 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 539.8 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 540.4 sec
[-----------------89%-------------     ] 1785 of 2000 complete in 541.0 sec
[-----------------89%-------------     ] 1787 of 2000 complete in 541.6 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 542.2 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 542.8 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 543.4 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 544.0 sec
[-----------------89%--------------    ] 1797 of 2000 complete in 544.6 sec
[-----------------89%--------------    ] 1799 of 2000 complete in 545.2 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 545.8 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 546.4 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 547.0 sec
[-----------------90%--------------    ] 1807 of 2000 complete in 547.7 sec
[-----------------90%--------------    ] 1809 of 2000 complete in 548.3 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 548.9 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 549.5 sec
[-----------------90%--------------    ] 1815 of 2000 complete in 550.1 sec

[-----------------80%----------        ] 1601 of 2000 complete in 489.0 sec
[-----------------80%----------        ] 1603 of 2000 complete in 489.7 sec
[-----------------80%----------        ] 1605 of 2000 complete in 490.2 sec
[-----------------80%----------        ] 1607 of 2000 complete in 490.8 sec
[-----------------80%----------        ] 1609 of 2000 complete in 491.5 sec
[-----------------80%----------        ] 1611 of 2000 complete in 492.1 sec
[-----------------80%----------        ] 1613 of 2000 complete in 492.7 sec
[-----------------80%----------        ] 1615 of 2000 complete in 493.3 sec
[-----------------80%----------        ] 1617 of 2000 complete in 493.9 sec
[-----------------80%----------        ] 1619 of 2000 complete in 494.5 sec
[-----------------81%----------        ] 1621 of 2000 complete in 495.1 sec
[-----------------81%----------        ] 1623 of 2000 complete in 495.7 sec
[-----------------81%----------        ] 1625 of 2000 complete in 496.3 sec
[-----------------81%----------        ] 1627 of 2000 complete in 496.9 sec
[-----------------81%----------        ] 1629 of 2000 complete in 497.5 sec
[-----------------81%----------        ] 1631 of 2000 complete in 498.1 sec
[-----------------81%-----------       ] 1633 of 2000 complete in 498.7 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 499.3 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 499.9 sec
[-----------------81%-----------       ] 1639 of 2000 complete in 500.6 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 501.2 sec
[-----------------82%-----------       ] 1643 of 2000 complete in 501.8 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 502.4 sec
[-----------------82%-----------       ] 1647 of 2000 complete in 503.0 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 503.7 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 504.4 sec
[-----------------82%-----------       ] 1653 of 2000 complete in 505.0 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 505.6 sec
[-----------------82%-----------       ] 1657 of 2000 complete in 506.3 sec
[-----------------82%-----------       ] 1659 of 2000 complete in 506.8 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 507.5 sec
[-----------------83%-----------       ] 1663 of 2000 complete in 508.1 sec
[-----------------83%-----------       ] 1665 of 2000 complete in 508.7 sec
[-----------------83%-----------       ] 1667 of 2000 complete in 509.3 sec
[-----------------83%-----------       ] 1669 of 2000 complete in 509.9 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 510.5 sec
[-----------------83%-----------       ] 1673 of 2000 complete in 511.1 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 511.7 sec
[-----------------83%-----------       ] 1677 of 2000 complete in 512.3 sec
[-----------------83%-----------       ] 1679 of 2000 complete in 512.9 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 513.5 sec
[-----------------84%-----------       ] 1683 of 2000 complete in 514.0 sec
[-----------------84%------------      ] 1685 of 2000 complete in 514.6 sec
[-----------------84%------------      ] 1687 of 2000 complete in 515.2 sec
[-----------------84%------------      ] 1689 of 2000 complete in 515.8 sec
[-----------------84%------------      ] 1691 of 2000 complete in 516.4 sec
[-----------------84%------------      ] 1693 of 2000 complete in 517.0 sec
[-----------------84%------------      ] 1695 of 2000 complete in 517.6 sec
[-----------------84%------------      ] 1697 of 2000 complete in 518.2 sec
[-----------------84%------------      ] 1699 of 2000 complete in 518.8 sec
[-----------------85%------------      ] 1701 of 2000 complete in 519.4 sec
[-----------------85%------------      ] 1703 of 2000 complete in 520.0 sec
[-----------------85%------------      ] 1705 of 2000 complete in 520.6 sec
[-----------------85%------------      ] 1707 of 2000 complete in 521.2 sec
[-----------------85%------------      ] 1709 of 2000 complete in 521.8 sec
[-----------------85%------------      ] 1711 of 2000 complete in 522.4 sec
[-----------------85%------------      ] 1713 of 2000 complete in 523.0 sec
[-----------------85%------------      ] 1715 of 2000 complete in 523.5 sec
[-----------------85%------------      ] 1717 of 2000 complete in 524.2 sec
[-----------------85%------------      ] 1719 of 2000 complete in 524.7 sec
[-----------------86%------------      ] 1721 of 2000 complete in 525.4 sec
[-----------------86%------------      ] 1723 of 2000 complete in 526.0 sec
[-----------------86%------------      ] 1725 of 2000 complete in 526.6 sec
[-----------------86%------------      ] 1727 of 2000 complete in 527.3 sec
[-----------------86%------------      ] 1729 of 2000 complete in 528.2 sec
[-----------------86%------------      ] 1731 of 2000 complete in 528.9 sec
[-----------------86%------------      ] 1733 of 2000 complete in 529.6 sec
[-----------------86%------------      ] 1735 of 2000 complete in 530.3 sec
[-----------------86%-------------     ] 1737 of 2000 complete in 531.0 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 531.7 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 532.5 sec
[-----------------87%-------------     ] 1743 of 2000 complete in 533.2 sec
[-----------------87%-------------     ] 1745 of 2000 complete in 533.9 sec
[-----------------87%-------------     ] 1747 of 2000 complete in 534.6 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 535.3 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 535.9 sec
[-----------------87%-------------     ] 1753 of 2000 complete in 536.6 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 537.3 sec
[-----------------87%-------------     ] 1757 of 2000 complete in 538.0 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 538.6 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 539.2 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 539.8 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 540.4 sec
[-----------------88%-------------     ] 1767 of 2000 complete in 541.0 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 541.6 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 542.3 sec
[-----------------88%-------------     ] 1773 of 2000 complete in 542.9 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 543.5 sec
[-----------------88%-------------     ] 1777 of 2000 complete in 544.1 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 544.7 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 545.3 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 545.9 sec
[-----------------89%-------------     ] 1785 of 2000 complete in 546.5 sec
[-----------------89%-------------     ] 1787 of 2000 complete in 547.1 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 547.7 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 548.3 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 548.9 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 549.5 sec
[-----------------89%--------------    ] 1797 of 2000 complete in 550.1 sec
[-----------------89%--------------    ] 1799 of 2000 complete in 550.8 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 551.4 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 552.0 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 552.5 sec
[-----------------90%--------------    ] 1807 of 2000 complete in 553.1 sec
[-----------------90%--------------    ] 1809 of 2000 complete in 553.7 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 554.4 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 554.9 sec
[-----------------80%----------        ] 1603 of 2000 complete in 490.2 sec
[-----------------80%----------        ] 1605 of 2000 complete in 490.8 sec
[-----------------80%----------        ] 1607 of 2000 complete in 491.4 sec
[-----------------80%----------        ] 1609 of 2000 complete in 492.0 sec
[-----------------80%----------        ] 1611 of 2000 complete in 492.6 sec
[-----------------80%----------        ] 1613 of 2000 complete in 493.2 sec
[-----------------80%----------        ] 1615 of 2000 complete in 493.8 sec
[-----------------80%----------        ] 1617 of 2000 complete in 494.4 sec
[-----------------80%----------        ] 1619 of 2000 complete in 495.0 sec
[-----------------81%----------        ] 1621 of 2000 complete in 495.6 sec
[-----------------81%----------        ] 1623 of 2000 complete in 496.3 sec
[-----------------81%----------        ] 1625 of 2000 complete in 496.9 sec
[-----------------81%----------        ] 1627 of 2000 complete in 497.5 sec
[-----------------81%----------        ] 1629 of 2000 complete in 498.1 sec
[-----------------81%----------        ] 1631 of 2000 complete in 498.7 sec
[-----------------81%-----------       ] 1633 of 2000 complete in 499.3 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 500.0 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 500.6 sec
[-----------------81%-----------       ] 1639 of 2000 complete in 501.2 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 501.9 sec
[-----------------82%-----------       ] 1643 of 2000 complete in 502.5 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 503.1 sec
[-----------------82%-----------       ] 1647 of 2000 complete in 503.8 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 504.4 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 505.1 sec
[-----------------82%-----------       ] 1653 of 2000 complete in 505.7 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 506.3 sec
[-----------------82%-----------       ] 1657 of 2000 complete in 506.9 sec
[-----------------82%-----------       ] 1659 of 2000 complete in 507.5 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 508.1 sec
[-----------------83%-----------       ] 1663 of 2000 complete in 508.7 sec
[-----------------83%-----------       ] 1665 of 2000 complete in 509.4 sec
[-----------------83%-----------       ] 1667 of 2000 complete in 509.9 sec
[-----------------83%-----------       ] 1669 of 2000 complete in 510.5 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 511.2 sec
[-----------------83%-----------       ] 1673 of 2000 complete in 511.8 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 512.4 sec
[-----------------83%-----------       ] 1677 of 2000 complete in 513.0 sec
[-----------------83%-----------       ] 1679 of 2000 complete in 513.6 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 514.2 sec
[-----------------84%-----------       ] 1683 of 2000 complete in 514.8 sec
[-----------------84%------------      ] 1685 of 2000 complete in 515.4 sec
[-----------------84%------------      ] 1687 of 2000 complete in 516.0 sec
[-----------------84%------------      ] 1689 of 2000 complete in 516.6 sec
[-----------------84%------------      ] 1691 of 2000 complete in 517.2 sec
[-----------------84%------------      ] 1693 of 2000 complete in 517.8 sec
[-----------------84%------------      ] 1695 of 2000 complete in 518.4 sec
[-----------------84%------------      ] 1697 of 2000 complete in 518.9 sec
[-----------------84%------------      ] 1699 of 2000 complete in 519.5 sec
[-----------------85%------------      ] 1701 of 2000 complete in 520.1 sec
[-----------------85%------------      ] 1703 of 2000 complete in 520.7 sec
[-----------------85%------------      ] 1705 of 2000 complete in 521.3 sec
[-----------------85%------------      ] 1707 of 2000 complete in 521.9 sec
[-----------------85%------------      ] 1709 of 2000 complete in 522.5 sec
[-----------------85%------------      ] 1711 of 2000 complete in 523.1 sec
[-----------------85%------------      ] 1713 of 2000 complete in 523.7 sec
[-----------------85%------------      ] 1715 of 2000 complete in 524.3 sec
[-----------------85%------------      ] 1717 of 2000 complete in 524.9 sec
[-----------------85%------------      ] 1719 of 2000 complete in 525.5 sec
[-----------------86%------------      ] 1721 of 2000 complete in 526.1 sec
[-----------------86%------------      ] 1723 of 2000 complete in 526.7 sec
[-----------------86%------------      ] 1725 of 2000 complete in 527.4 sec
[-----------------86%------------      ] 1727 of 2000 complete in 528.2 sec
[-----------------86%------------      ] 1729 of 2000 complete in 528.9 sec
[-----------------86%------------      ] 1731 of 2000 complete in 529.7 sec
[-----------------86%------------      ] 1733 of 2000 complete in 530.3 sec
[-----------------86%------------      ] 1735 of 2000 complete in 531.1 sec
[-----------------86%-------------     ] 1737 of 2000 complete in 531.8 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 532.5 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 533.2 sec
[-----------------87%-------------     ] 1743 of 2000 complete in 533.9 sec
[-----------------87%-------------     ] 1745 of 2000 complete in 534.6 sec
[-----------------87%-------------     ] 1747 of 2000 complete in 535.3 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 536.0 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 536.7 sec
[-----------------87%-------------     ] 1753 of 2000 complete in 537.4 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 538.1 sec
[-----------------87%-------------     ] 1757 of 2000 complete in 538.7 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 539.3 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 539.9 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 540.5 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 541.1 sec
[-----------------88%-------------     ] 1767 of 2000 complete in 541.7 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 542.3 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 542.9 sec
[-----------------88%-------------     ] 1773 of 2000 complete in 543.5 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 544.1 sec
[-----------------88%-------------     ] 1777 of 2000 complete in 544.7 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 545.4 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 546.0 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 546.5 sec
[-----------------89%-------------     ] 1785 of 2000 complete in 547.1 sec
[-----------------89%-------------     ] 1787 of 2000 complete in 547.8 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 548.4 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 549.0 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 549.6 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 550.2 sec
[-----------------89%--------------    ] 1797 of 2000 complete in 550.8 sec
[-----------------89%--------------    ] 1799 of 2000 complete in 551.5 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 552.1 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 552.7 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 553.3 sec
[-----------------90%--------------    ] 1807 of 2000 complete in 553.9 sec
[-----------------90%--------------    ] 1809 of 2000 complete in 554.5 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 555.1 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 555.7 sec
[-----------------90%--------------    ] 1815 of 2000 complete in 556.3 sec

[-----------------80%----------        ] 1603 of 2000 complete in 493.7 sec
[-----------------80%----------        ] 1605 of 2000 complete in 494.3 sec
[-----------------80%----------        ] 1607 of 2000 complete in 494.9 sec
[-----------------80%----------        ] 1609 of 2000 complete in 495.5 sec
[-----------------80%----------        ] 1611 of 2000 complete in 496.1 sec
[-----------------80%----------        ] 1613 of 2000 complete in 496.7 sec
[-----------------80%----------        ] 1615 of 2000 complete in 497.3 sec
[-----------------80%----------        ] 1617 of 2000 complete in 497.9 sec
[-----------------80%----------        ] 1619 of 2000 complete in 498.5 sec
[-----------------81%----------        ] 1621 of 2000 complete in 499.1 sec
[-----------------81%----------        ] 1623 of 2000 complete in 499.7 sec
[-----------------81%----------        ] 1625 of 2000 complete in 500.4 sec
[-----------------81%----------        ] 1627 of 2000 complete in 501.0 sec
[-----------------81%----------        ] 1629 of 2000 complete in 501.6 sec
[-----------------81%----------        ] 1631 of 2000 complete in 502.3 sec
[-----------------81%-----------       ] 1633 of 2000 complete in 502.9 sec
[-----------------81%-----------       ] 1635 of 2000 complete in 503.6 sec
[-----------------81%-----------       ] 1637 of 2000 complete in 504.2 sec
[-----------------81%-----------       ] 1639 of 2000 complete in 504.8 sec
[-----------------82%-----------       ] 1641 of 2000 complete in 505.5 sec
[-----------------82%-----------       ] 1643 of 2000 complete in 506.1 sec
[-----------------82%-----------       ] 1645 of 2000 complete in 506.7 sec
[-----------------82%-----------       ] 1647 of 2000 complete in 507.3 sec
[-----------------82%-----------       ] 1649 of 2000 complete in 507.9 sec
[-----------------82%-----------       ] 1651 of 2000 complete in 508.5 sec
[-----------------82%-----------       ] 1653 of 2000 complete in 509.1 sec
[-----------------82%-----------       ] 1655 of 2000 complete in 509.8 sec
[-----------------82%-----------       ] 1657 of 2000 complete in 510.4 sec
[-----------------82%-----------       ] 1659 of 2000 complete in 511.0 sec
[-----------------83%-----------       ] 1661 of 2000 complete in 511.6 sec
[-----------------83%-----------       ] 1663 of 2000 complete in 512.2 sec
[-----------------83%-----------       ] 1665 of 2000 complete in 512.8 sec
[-----------------83%-----------       ] 1667 of 2000 complete in 513.4 sec
[-----------------83%-----------       ] 1669 of 2000 complete in 514.0 sec
[-----------------83%-----------       ] 1671 of 2000 complete in 514.6 sec
[-----------------83%-----------       ] 1673 of 2000 complete in 515.2 sec
[-----------------83%-----------       ] 1675 of 2000 complete in 515.8 sec
[-----------------83%-----------       ] 1677 of 2000 complete in 516.4 sec
[-----------------83%-----------       ] 1679 of 2000 complete in 517.0 sec
[-----------------84%-----------       ] 1681 of 2000 complete in 517.6 sec
[-----------------84%-----------       ] 1683 of 2000 complete in 518.2 sec
[-----------------84%------------      ] 1685 of 2000 complete in 518.8 sec
[-----------------84%------------      ] 1687 of 2000 complete in 519.4 sec
[-----------------84%------------      ] 1689 of 2000 complete in 520.0 sec
[-----------------84%------------      ] 1691 of 2000 complete in 520.6 sec
[-----------------84%------------      ] 1693 of 2000 complete in 521.2 sec
[-----------------84%------------      ] 1695 of 2000 complete in 521.8 sec
[-----------------84%------------      ] 1697 of 2000 complete in 522.4 sec
[-----------------84%------------      ] 1699 of 2000 complete in 523.0 sec
[-----------------85%------------      ] 1701 of 2000 complete in 523.6 sec
[-----------------85%------------      ] 1703 of 2000 complete in 524.2 sec
[-----------------85%------------      ] 1705 of 2000 complete in 524.8 sec
[-----------------85%------------      ] 1707 of 2000 complete in 525.4 sec
[-----------------85%------------      ] 1709 of 2000 complete in 526.0 sec
[-----------------85%------------      ] 1711 of 2000 complete in 526.7 sec
[-----------------85%------------      ] 1713 of 2000 complete in 527.3 sec
[-----------------85%------------      ] 1715 of 2000 complete in 528.2 sec
[-----------------85%------------      ] 1717 of 2000 complete in 528.9 sec
[-----------------85%------------      ] 1719 of 2000 complete in 529.6 sec
[-----------------86%------------      ] 1721 of 2000 complete in 530.3 sec
[-----------------86%------------      ] 1723 of 2000 complete in 531.0 sec
[-----------------86%------------      ] 1725 of 2000 complete in 531.7 sec
[-----------------86%------------      ] 1727 of 2000 complete in 532.5 sec
[-----------------86%------------      ] 1729 of 2000 complete in 533.2 sec
[-----------------86%------------      ] 1731 of 2000 complete in 533.9 sec
[-----------------86%------------      ] 1733 of 2000 complete in 534.6 sec
[-----------------86%------------      ] 1735 of 2000 complete in 535.3 sec
[-----------------86%-------------     ] 1737 of 2000 complete in 536.0 sec
[-----------------86%-------------     ] 1739 of 2000 complete in 536.7 sec
[-----------------87%-------------     ] 1741 of 2000 complete in 537.3 sec
[-----------------87%-------------     ] 1743 of 2000 complete in 538.0 sec
[-----------------87%-------------     ] 1745 of 2000 complete in 538.6 sec
[-----------------87%-------------     ] 1747 of 2000 complete in 539.2 sec
[-----------------87%-------------     ] 1749 of 2000 complete in 539.8 sec
[-----------------87%-------------     ] 1751 of 2000 complete in 540.5 sec
[-----------------87%-------------     ] 1753 of 2000 complete in 541.1 sec
[-----------------87%-------------     ] 1755 of 2000 complete in 541.7 sec
[-----------------87%-------------     ] 1757 of 2000 complete in 542.3 sec
[-----------------87%-------------     ] 1759 of 2000 complete in 542.9 sec
[-----------------88%-------------     ] 1761 of 2000 complete in 543.5 sec
[-----------------88%-------------     ] 1763 of 2000 complete in 544.1 sec
[-----------------88%-------------     ] 1765 of 2000 complete in 544.7 sec
[-----------------88%-------------     ] 1767 of 2000 complete in 545.3 sec
[-----------------88%-------------     ] 1769 of 2000 complete in 545.9 sec
[-----------------88%-------------     ] 1771 of 2000 complete in 546.5 sec
[-----------------88%-------------     ] 1773 of 2000 complete in 547.1 sec
[-----------------88%-------------     ] 1775 of 2000 complete in 547.8 sec
[-----------------88%-------------     ] 1777 of 2000 complete in 548.4 sec
[-----------------88%-------------     ] 1779 of 2000 complete in 549.0 sec
[-----------------89%-------------     ] 1781 of 2000 complete in 549.6 sec
[-----------------89%-------------     ] 1783 of 2000 complete in 550.2 sec
[-----------------89%-------------     ] 1785 of 2000 complete in 550.9 sec
[-----------------89%-------------     ] 1787 of 2000 complete in 551.5 sec
[-----------------89%-------------     ] 1789 of 2000 complete in 552.1 sec
[-----------------89%--------------    ] 1791 of 2000 complete in 552.7 sec
[-----------------89%--------------    ] 1793 of 2000 complete in 553.3 sec
[-----------------89%--------------    ] 1795 of 2000 complete in 553.9 sec
[-----------------89%--------------    ] 1797 of 2000 complete in 554.5 sec
[-----------------89%--------------    ] 1799 of 2000 complete in 555.1 sec
[-----------------90%--------------    ] 1801 of 2000 complete in 555.7 sec
[-----------------90%--------------    ] 1803 of 2000 complete in 556.3 sec
[-----------------90%--------------    ] 1805 of 2000 complete in 557.0 sec
[-----------------90%--------------    ] 1807 of 2000 complete in 557.6 sec
[-----------------90%--------------    ] 1809 of 2000 complete in 558.2 sec
[-----------------90%--------------    ] 1811 of 2000 complete in 558.8 sec
[-----------------90%--------------    ] 1813 of 2000 complete in 559.4 sec
[-----------------90%--------------    ] 1815 of 2000 complete in 560.1 sec
hddm sampling elpased time:  645.051 s
Start converting to InferenceData...

In [46]:
az.summary(hddmReg_stim_zflip_m2_diff_idata)

,mean,sd,hdi_3%,hdi_97%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
a,1.992,0.182,1.667,2.341,0.043,0.031,18.0,58.0,1.15
a_std,0.930,0.170,0.619,1.258,0.044,0.031,15.0,32.0,1.18
a_subj.7304,1.513,0.102,1.330,1.702,0.004,0.003,662.0,823.0,1.00
a_subj.7305,1.732,0.100,1.549,1.913,0.003,0.003,940.0,753.0,1.00
a_subj.7306,1.401,0.086,1.246,1.556,0.003,0.002,691.0,1204.0,1.01
...,...,...,...,...,...,...,...,...,...
z_Intercept_subj.7342,0.491,0.021,0.451,0.530,0.000,0.000,1791.0,2903.0,1.01
z_Intercept_subj.7343,0.573,0.023,0.529,0.614,0.005,0.003,23.0,112.0,1.11
z_Intercept_subj.7344,0.562,0.020,0.523,0.599,0.000,0.000,1761.0,2662.0,1.00
z_Intercept_subj.7345,0.548,0.018,0.513,0.582,0.000,0.000,2225.0,3570.0,1.00
z_Intercept_subj.73370,0.523,0.019,0.489,0.561,0.001,0.000,844.0,1403.0,1.00

In [47]:
hddmReg_stim_zflip_m2_stats = hddmReg_stim_zflip_m2_diff.gen_stats()
hddmReg_stim_zflip_m2_stats[hddmReg_stim_zflip_m2_stats.index.isin(['a', 'z_Intercept','v_stim2','v_id','v(Self.1)', 'v(Other.1)', 
                                                                   'v(Self.0)', 'v(Other.0)'])]

,mean,std,2.5q,25q,50q,75q,97.5q,mc err
a,1.992235,0.181862,1.667171,1.863732,1.982726,2.109573,2.37337,0.010937
v(Other.0),3.455552,0.226129,3.017691,3.302531,3.452031,3.606741,3.908521,0.009872
v(Self.1),3.312202,0.230653,2.86372,3.15591,3.312091,3.466011,3.773995,0.010574
z_Intercept,0.54232,0.00719,0.528699,0.537457,0.542209,0.546998,0.556966,0.000158

In [49]:
#model comprasion
hddm_id_m0_acc = hddm.load('hddm_id_m0_acc_diff.hddm')
hddm_id_m1_choice = hddm.load('hddm_id_m1_choice_diff.hddm')
hddmStim_vflip_dc_m1 = hddm.load('hddmStim_vflip_dc_m1.hddm')
hddmStim_zflip_m1 = hddm.load('hddmStim_zflip_m1_diff.hddm')
hddmReg_id_m0_acc = hddm.load('hddmReg_id_m0_acc_diff.hddm')
hddmReg_id_m2_choice = hddm.load('hddmReg_id_m2_choice_diff.hddm')
hddmReg_stim_vflip_dc_m2 = hddm.load('hddmReg_stim_vflip_dc_m2.hddm')
hddmReg_stim_vflip_m3 = hddm.load('hddmReg_stim_vflip_m3_diff.hddm')
hddmReg_stim_zflip_m2 = hddm.load('hddmReg_stim_zflip_m2_diff.hddm')

In [50]:
# hddmReg_stim_vflip_m3 = hddm.load('hddmReg_stim_vflip_m3.hddm')
DIC_dict = {
    "m0_hddm": hddm_id_m0_acc.dic,
    "m1_hddm": hddm_id_m1_choice.dic,
    "m2_hddmStim": hddmStim_vflip_dc_m1.dic,
    "m3_hddmStim": hddmStim_zflip_m1.dic,
    "m4_hddmReg": hddmReg_id_m0_acc.dic,
    "m5_hddmReg": hddmReg_id_m2_choice.dic,
    "m6_hddmReg": hddmReg_stim_vflip_dc_m2.dic,
    "m7_hddmReg": hddmReg_stim_vflip_m3.dic,
    "m8_hddmReg": hddmReg_stim_zflip_m2.dic,
}

DIC_table = pd.DataFrame.from_dict(DIC_dict, orient="index", columns=["DIC"])
DIC_table["model"] = DIC_table.index
DIC_table = DIC_table[["model", "DIC"]]
DIC_table.sort_values(by=["DIC"], ascending=False)

                   model           DIC
m5_hddmReg    m5_hddmReg -13386.618383
m8_hddmReg    m8_hddmReg -13387.976432
m7_hddmReg    m7_hddmReg -13419.677496
m6_hddmReg    m6_hddmReg -13450.376379
m3_hddmStim  m3_hddmStim -13468.680244
m2_hddmStim  m2_hddmStim -13504.812456
m0_hddm          m0_hddm -13991.686077
m1_hddm          m1_hddm -13992.647634
m4_hddmReg    m4_hddmReg -13998.583524